### ISSUE TITLE
libcurl: request to include curl-config

### ISSUE THREAD

**Issue by weatherhead99** [bincrafters/community#100]
### Description of Problem, Request, or Question
I am writing conan packages for a package which uses libcurl. It builds with autotools, and the autotools buildsystem in this case checks for curl using the "curl-config" tool. This is a request to include this tool in the libcurl package (it is currently removed).

### Package Details (Include if Applicable)
* Package Name/Version: libcurl/7.56.1@bincrafters/stable
* Operating System: Linux
* Compiler+version: gcc-4.8

**Comment by theirix** [comment]
Sure, I'll return it to the 7.56.1 at first and then to other releases.

**Comment by theirix** [comment]
Done, at 7.56.1 and 7.52.1. Thank you for the report!

**Comment by weatherhead99** [comment]
thanks very much :-) 
any idea when this is likely to propagate through to the bintray?
Thanks again!

**Comment by theirix** [comment]
I checked 2 hours ago and it was there. I think you have cached libcurl. Try to run `conan install -u` or even just delete libcurl in Conan cache.

**Comment by weatherhead99** [comment]
got it, thanks
