### ISSUE TITLE
QT package seems to not support cross compilation

### ISSUE THREAD

**Issue by AliAskari** [bincrafters/community#1004]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.12.4**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **gcc-7.4**
  * Cross Compiler+version: **aarch64-linux-gnu-gcc-7.4**
  * Conan version: **conan 1.19.2**
  * Python version: **Python 3.6.8**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Configuration for profile aarch64-linux:

[settings]
os_build=Linux
arch_build=x86_64
os=Linux
arch=armv8
compiler=gcc
compiler.version=7
compiler.libcxx=libstdc++
build_type=Debug
[options]
[build_requires]
[env]
CONAN_CMAKE_TOOLCHAIN_FILE=/tmp/aarch64-linux-toolchain.cmake
CONAN_CMAKE_FIND_ROOT_PATH=/usr/aarch64-linux-gnu
CHOST=aarch64-linux-gnu
AR=/usr/bin/aarch64-linux-gnu-ar
ASM=/usr/bin/aarch64-linux-gnu-as
AS=/usr/bin/aarch64-linux-gnu-as
RANLIB=/usr/bin/aarch64-linux-gnu-ranlib
CC=/usr/bin/aarch64-linux-gnu-gcc
CXX=/usr/bin/aarch64-linux-gnu-g++
STRIP=/usr/bin/aarch64-linux-gnu-strip
RC=/usr/bin/aarch64-linux-gnu-windres
```

### Steps to reproduce (Include if Applicable)
I am trying to cross compile qt for armv8/aarch64 using the following command

`conan install conanfile.txt --profile=aarch64-linux --build=missing`

where conanfile.txt is below:

```
[requires]
zlib/1.2.11@conan/stable
bzip2/1.0.8@conan/stable
qt/5.12.4@bincrafters/stable

[generators]
cmake

[options]
qt:cross_compile=/usr/aarch64-linux-gnu
qt:with_glib=False
qt:with_doubleconversion=False
qt:with_freetype=False
qt:with_harfbuzz=False
qt:with_libjpeg=False
qt:with_libpng=False
qt:with_sqlite3=False
qt:with_mysql=False
qt:with_pq=False
qt:with_odbc=False
qt:with_sdl2=False
```

### Logs (Include/Attach if Applicable)

```
xkbcommon/0.8.4@bincrafters/stable: Applying build-requirement: meson_installer/0.49.0@bincrafters/stable
xkbcommon/0.8.4@bincrafters/stable: Applying build-requirement: bison_installer/3.2.4@bincrafters/stable
xkbcommon/0.8.4@bincrafters/stable: Applying build-requirement: ninja_installer/1.8.2@bincrafters/stable
xkbcommon/0.8.4@bincrafters/stable: Applying build-requirement: m4_installer/1.4.18@bincrafters/stable
dpkg-query: no packages found matching xkb-data:arm64
Running: sudo apt-get update
[sudo] password for ali:
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:3 http://ppa.launchpad.net/fish-shell/release-3/ubuntu bionic InRelease
Hit:4 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:5 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Reading package lists...
Running: sudo apt-get install -y --no-install-recommends xkb-data:arm64
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package xkb-data:arm64
xkbcommon/0.8.4@bincrafters/stable: ERROR: while executing system_requirements(): Command 'sudo apt-get install -y --no-install-recommends xkb-data:arm64' failed
ERROR: Error in system requirements
```

**Comment by ericLemanissier** [comment]
Hi. The error is happening during zlib compilation. Could you try to build this package alone, and if it still fails, repory the issue on https://github.com/conan-io/conan-center-index/issues?
Thanks

**Comment by AliAskari** [comment]
@ericLemanissier Thanks for the quick reply. Yeah, I realized that and fixed the issue (the path to cross compiler was wrong)  but I am getting a new error now where it fails to find the `xkb-data:arm64` package. Running `apt-cache search xkb-data:arm64` returns nothing so this package doesn't exist.

I tried to disable the option that requires xkb and remove it but I still get the same error.

From [qt conan repo](https://github.com/bincrafters/conan-qt/blob/testing/5.13.1/conanfile.py)

![image](https://user-images.githubusercontent.com/4864412/67168516-4b340600-f373-11e9-91b6-0194a2cefd64.png)

I updated the conanfile with `qt:GUI=False` but it still tries to install it. I'm not sure why.

**Comment by ericLemanissier** [comment]
Could you please show the full log ?

**Comment by AliAskari** [comment]
The log isn't much more than what I've mentioned in the original post. I have attached the entire conan output after running

```
conan install conanfile.txt --profile=aarch64-linux --build=missing
```

[conan_log.txt](https://github.com/bincrafters/community/files/3760079/conan_log.txt)

**Comment by ericLemanissier** [comment]
You system package manager does not seem to have any arm repository. Can you please try to add the ones listed here please https://doc.ubuntu-fr.org/depots_bionic#depot_portage ?
If you don't use option `qt:GUI=False`, and it still fails to install some system packages, you can try to set environment variable [CONAN_SYSREQUIRES_MODE=disabled](https://docs.conan.io/en/latest/reference/env_vars.html#conan-sysrequires-mode)
If you can live with option `qt:GUI=False` and it fails with this option, please send the corresponding log.

**Comment by AliAskari** [comment]
Good to know about the `CONAN_SYSREQUIRES_MODE` env variable. After setting it to disabled I am getting a new error

```
xkbcommon/0.8.4@bincrafters/stable: Generator txt created conanbuildinfo.txt
xkbcommon/0.8.4@bincrafters/stable: Calling build()
The Meson build system
Version: 0.49.0
Source dir: /home/ali/.conan/data/xkbcommon/0.8.4/bincrafters/stable/build/4cbc9794b12afcc627064463f22a3e57bf713b82/source_subfolder
Build dir: /home/ali/.conan/data/xkbcommon/0.8.4/bincrafters/stable/build/4cbc9794b12afcc627064463f22a3e57bf713b82/build_subfolder
Build type: native build
Project name: libxkbcommon
Project version: 0.8.4

meson.build:1:0: ERROR:  Could not invoke sanity test executable: [Errno 8] Exec format error: '/home/ali/.conan/data/xkbcommon/0.8.4/bincrafters/stable/build/4cbc9794b12afcc627064463f22a3e57bf713b82/build_subfolder/meson-private/sanitycheckc.exe'.

A full log can be found at /home/ali/.conan/data/xkbcommon/0.8.4/bincrafters/stable/build/4cbc9794b12afcc627064463f22a3e57bf713b82/build_subfolder/meson-logs/meson-log.txt
xkbcommon/0.8.4@bincrafters/stable: 
[conan_log.txt](https://github.com/bincrafters/community/files/3765811/conan_log.txt)
```

I get this error regardless of the `GUI` option. It looks like the qt package is really broken. It's trying to use a windows exe file while cross compiling from linux to arm!

**Comment by ericLemanissier** [comment]
I just recall : [conan does not support cross compilation of meson projects. xkbcommon is built by meson](https://github.com/conan-io/conan/issues/4529), so this is explains why you get this failure during compilation of `xkbcommon/0.8.4@bincrafters/stable`. I started a [PR ](https://github.com/bincrafters/conan-qt/pull/4)to avoid requiring xkbcommon when cross compiling to avoid this, but it means that the system package of xkbcommon will be used instead.
Until then, can you please send the full log when you use option `qt:GUI=False`

**Comment by AliAskari** [comment]
As I mentioned, I get the same error for both `qt:GUI=False` and `qt:GUI=True`. I am not sure what but there's something very wrong with qt conan recipe. It should not even try installing `xkbcommon` when `qt:GUI=False` but for some odd reason it does.

**Comment by ericLemanissier** [comment]
if you don't send me the actual command line and log file when you try to use `qt:GUI=False`, there is just no way I can help you.

**Comment by ericLemanissier** [comment]
Actually, I have an idea. You need to disable option qt:widgets too, otherwise qt:GUI will be enabled anyway: https://github.com/bincrafters/conan-qt/blob/7f90f65c22c2a0a9718571ee9b0610e56511c777/conanfile.py#L171

**Comment by AliAskari** [comment]
Yes, disabling `qt:widgets` resolve this issue. I strongly believe the recipe should be updated to handle cases like this. If a private option of an enabled option is disabled, the recipe should not even try building the package:

i.e. `qt:GUI` looks like a private option for 'qt:widgets`. For the user this is not trivial. If the user enables `qt:widgets` but disables `qt:GUI`, the recipe should handle it and just stop with a message that the requirements of the requested options are not met.

**Comment by ericLemanissier** [comment]
Agreed. That's what was intended with https://github.com/bincrafters/conan-qt/commit/8ab67d93c646caadba1418dabf5329a44b7807f9
