### ISSUE TITLE
Package revisions

### ISSUE THREAD

**Issue by mplatings** [bincrafters/community#1006]
Please can you change the bincrafters bintray repo to use [Conan Package Revisions](https://docs.conan.io/en/latest/versioning/revisions.html)?

This would allow pinning specific recipe revisions.

Background:
I was using Conan 1.18.0 and [this commit](https://github.com/bincrafters/conan-libxml2/commit/29ae00563248d9d37157970fa946d0d5b34ebbe4) broke my build because "zlib/1.2.11" couldn't be resolved. Once I upgraded everywhere to Conan 1.19.2 the problem was fixed, but I'd like to avoid similar problems cropping up in future. I can pin zlib like so: `zlib/1.2.11@#5f4917ce0a630b102f472afd00102d40` but that's not possible for libxml2 since apparently the bincrafters repo on bintray.com doesn't support revisions (it is listed as `libxml2/2.9.9@bincrafters/stable#0`)

Thanks!

**Comment by Croydon** [comment]
I don't think that it is up to us to enable revisions. I'm assuming that revisions will be enabled globally on Bintray at some point

// @SSE4 @uilianries

**Comment by mplatings** [comment]
The [Conan Package Revisions](https://docs.conan.io/en/latest/versioning/revisions.html) says "Bintray" under "Server support" so I was under the impression that it's already enabled globally. Maybe you just need to set `revisions_enabled=1` on the client side?

**Comment by Croydon** [comment]
This is done via https://github.com/bincrafters/community/pull/1358

Revisions are enabled and required by our new remote.
