### ISSUE TITLE
[protobuf/3.9.1] Can't build package with option protobuf:lite=True

### ISSUE THREAD

**Issue by wizardsd** [bincrafters/community#1008]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **protobuf/3.9.1**
  * Operating System+version: **Windows 10 18362.418**
  * Compiler+version: **Visual Studio any version**
  * Conan version: **conan 1.19.2**
  * Python version: **Python 3.7.0**

### Conan profile
```
[settings]
os=Windows
arch=x86_64
compiler=Visual Studio
compiler.version=15
build_type=Release
arch_build=x86_64
os_build=Windows
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
```
conan create . user/channel -o Protobuf:lite=True
```

### Logs (Include/Attach if Applicable)
```
addressbook.pb.obj : error LNK2019: unresolved external symbol "public: static unsigned char * __cdecl google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(class google::protobuf::UnknownFieldSet const &,unsigned char *)" (?SerializeUnknownFieldsToArray@WireFormat@internal@protobuf@google@@SAPEAEAEBVUnknownFieldSet@34@PEAE@Z) referenced in function "public: static unsigned char * __cdecl google::protobuf::internal::WireFormatLite::InternalWriteMessageToArray<class tutorial::Person_PhoneNumber>(int,class tutorial::Person_PhoneNumber const &,unsigned char *)" (??$InternalWriteMessageToArray@VPerson_PhoneNumber@tutorial@@@WireFormatLite@internal@protobuf@google@@SAPEAEHAEBVPerson_PhoneNumber@tutorial@@PEAE@Z) [.\test_package\build\5983277d26a41e044e324c30f93c1e925ffe1d03\test_package.vcxproj]
addressbook.pb.obj : error LNK2019: unresolved external symbol "public: static unsigned __int64 __cdecl google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(class google::protobuf::UnknownFieldSet const &)" (?ComputeUnknownFieldsSize@WireFormat@internal@protobuf@google@@SA_KAEBVUnknownFieldSet@34@@Z) referenced in function "public: virtual unsigned __int64 __cdecl tutorial::AddressBook::ByteSizeLong(void)const " (?ByteSizeLong@AddressBook@tutorial@@UEBA_KXZ) [.\test_package\build\5983277d26a41e044e324c30f93c1e925ffe1d03\test_package.vcxproj]
addressbook.pb.obj : error LNK2019: unresolved external symbol "class google::protobuf::TimestampDefaultTypeInternal google::protobuf::_Timestamp_default_instance_" (?_Timestamp_default_instance_@protobuf@google@@3VTimestampDefaultTypeInternal@12@A) referenced in function "void __cdecl InitDefaultsscc_info_Person_addressbook_2eproto(void)" (?InitDefaultsscc_info_Person_addressbook_2eproto@@YAXXZ) [.\test_package\build\5983277d26a41e044e324c30f93c1e925ffe1d03\test_package.vcxproj]
.\test_package\build\5983277d26a41e044e324c30f93c1e925ffe1d03\bin\test_package.exe : fatal error LNK1120: 32 unresolved externals [.\test_package\build\5983277d26a41e044e324c30f93c1e925ffe1d03\test_package.vcxproj]
ERROR: Protobuf/3.9.1@ntt/testing (test package): Error in build() method, line 12
        cmake.build()
        ConanException: Error 1 while executing cmake --build .\test_package\build\5983277d26a41e044e324c30f93c1e925ffe1d03 --config Release -- /m:8 /verbosity:minimal
```

It would be nice to have one package that contains both libraries for full runtime and lite runtime (or packages with different names), because with `FindProtobuf` you should be able to link the imported targets `protobuf::libprotobuf` and `protobuf::libprotobuf-lite` in one `CMakeLists.txt` (may be in different targets).

And please, add builds with all options enabled to the appveyor.

**Comment by ifabek** [comment]
This is an issue common to all platforms. It happens on my linux machine as well.
If you take a look at the full log you can see that the protobuf-lite library is actually built successfully. You  should be able to check in conan cache.
Actual problem is in the test package that validates protobuf package. It uses precompiled addressbook protobuf message. 
My suspicion is that the message was not compiled using LITE_RUNTIME option, and this make it incompatible with protobuf-lite library - meaning the compiled protobuf message expects some "features" the protobuf-lite library doesn't provide.

**Comment by ifabek** [comment]
My suspicion was right.
I've removed 
> google.protobuf.Timestamp

from the addressbook.proto message (because it doesn't come with protobuf-lite), and added
> option optimize_for = LITE_RUNTIME;

and then recompiled with protoc.
Then I regenerated the protobuf package and the test passed.
Patch for addressbook.proto is attached:
[addresbook_proto.patch.zip](https://github.com/bincrafters/community/files/4531972/addresbook_proto.patch.zip)

**Comment by ifabek** [comment]
Regarding 
> It would be nice to have one package that contains both libraries for full runtime and lite runtime ...

I've submitted [PR](https://github.com/bincrafters/conan-protobuf/pull/42) that does exactly that. It enables you to choose to build only protobuf-lite library, both protobuf-lite and protobuf libraries, or both libraries and protoc binary.

**Comment by Croydon** [comment]
Splitting libraries and executables was previously required to get cross-compiling support.

Conan is currently working on better cross-compiling support and this split is not required anymore

We migrated our protobuf recipe already to the Conan Center Index, and protoc is work in progress: https://github.com/conan-io/conan-center-index/pull/1179

As soon as this is merged our Bincrafters recipes for Protobuf/Protoc will be deprecated

**Comment by Croydon** [comment]
This recipe is now in the [Conan Center Index](https://github.com/conan-io/conan-center-index/).

Please migrate to the recipe version there. 
If this is still an issue, please create a new issue in the [Conan Center Index issue tracker](https://github.com/conan-io/conan-center-index/issues).

Thanks!
