### ISSUE TITLE
[zmq] Missing license file

### ISSUE THREAD

**Issue by vkes** [bincrafters/community#1009]
### Description
libzmq is licensed under LGPLv3. LGPLv3-licensed products must ship [the license texts of both LGPLv3 and GPLv3](http://www.gnu.org/licenses/gpl-howto.html). The [libzmq repository](https://github.com/zeromq/libzmq) contains both licenses as _COPYING_ and _COPYING.LESSER_ files. However, the zmq Conan package only contains the _COPYING_ file with the GPLv3 text.

### Solution
In the conanfile, replace...
```python
self.copy(pattern="COPYING", src=self._source_subfolder, dst='licenses')
```
... by...
```python
self.copy(pattern="COPYING*", src=self._source_subfolder, dst='licenses')
```

### Package and Environment Details
  * Package Name/Version: **zmq/4.3.2**

### Steps to reproduce
```bash
~$ conan download -r bincrafters zmq/4.3.2@bincrafters/stable:ff3306beb129511ba2d0f044555b6137b5f055f4
~$ conan get zmq/4.3.2@bincrafters/stable:ff3306beb129511ba2d0f044555b6137b5f055f4 licenses
Listing directory 'licenses':
 COPYING
```

**Comment by Croydon** [comment]
Thanks for reporting. It should be fixed now
