### ISSUE TITLE
fmt/4.1.0 errors with GCC5

### ISSUE THREAD

**Issue by Croydon** [bincrafters/community#101]
### Package Details
* Package Name/Version: **fmt/4.1.0**
* Operating System: **Linux**
* Compiler+version: **gcc-5.4**
* Docker image: **inexorgame/ci-docker:ubuntu-bionic-gcc05**

### Steps to reproduce

https://travis-ci.org/inexorgame/ci-prebuilds/jobs/337376206#L1159

Any ideas where this is coming from?

**Comment by Croydon** [comment]
It also doesn't export any lib files on all non-only-header configurations.

**Comment by SSE4** [comment]
weird, I've run your container inexorgame/ci-docker:ubuntu-bionic-gcc05, but fmt/4.1.0 builds with no errors in it.

**Comment by Croydon** [comment]
Maybe this only happens when fmt is building as a dep of spdlog. 
I have updated spdlog from 0.14.0 to 0.16.3, which seems to do the trick.

As a more general note, I would recommend to fix the version of fmt https://github.com/bincrafters/conan-spdlog/blob/1328d61ef847730d2032fa207b8e6ad118458b55/conanfile.py#L21

With version ranges builds aren't reproducible.
