### ISSUE TITLE
GLEW_LIBRARY-NOTFOUND Question

### ISSUE THREAD

**Issue by alonsopatron** [bincrafters/community#1011]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **glew/2.1.0**
  * Operating System+version: **MacOs 10.13.5**
  * Compiler+version: **clang-9.1**
  * Conan version: **Conan 1.19.2**
  * Python version: **Python 3.7.4**

### Question Description
Hi, I'm trying to create a package for a third party library. This library has GLEW as a dependency and I'm using bincrafters glew/2.1.0 stable as a requirement for the library.

When I run conan create, during the building stage, I get:

```bash
-- ** GLEW ALREADY FOUND BY CONAN!
-- ** FOUND GLEW: GLEW_LIBRARY-NOTFOUND
``` 

I don't understand why the FindGLEW.cmake that comes with the conan-glew package can't find the library. Thanks in advance for any help.

**Comment by spectras** [comment]
So, how did you solve the issue? It seems I have the same one.
