### ISSUE TITLE
Qt/5.13.1 Build fails with gettext error

### ISSUE THREAD

**Issue by itsjamie** [bincrafters/community#1014]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **bincrafters/conan-qt**
  * Operating System+version: **MacOS X Mojave 10.14.6**
  * Compiler+version: **Clang Apple LLVM version 10.0.1 (clang-1001.0.46.4)**
  * Conan version: **conan 1.18.5**
  * Python version: **Python 2.7.10**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Configuration for profile default:

[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=10.0
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
Create empty folder with `build` folder inside.
Create conanfile.txt with contents:

```
[requires]
qt/5.13.1@bincrafters/stable

[generators]
CMake
```

`cd build`
`conan install ..`

### Logs (Include/Attach if Applicable)

```
gettext/0.20.1@bincrafters/stable: Retrieving package 6c3a931daae9d7916b13c01550e469037fec642b from remote 'bincrafters'
Downloading conanmanifest.txt: 100%|##########| 213/213 [00:00<00:00, 254kB/s]
Downloading conaninfo.txt: 100%|##########| 893/893 [00:00<00:00, 1.11MB/s]
Downloading conan_package.tgz: 100%|##########| 43.5k/43.5k [00:00<00:00, 12.1MB/s]
Decompressing conan_package.tgz: 100%|##########| 43.5k/43.5k [00:00<00:00, 12.9MB/s]
gettext/0.20.1@bincrafters/stable: Package installed 6c3a931daae9d7916b13c01550e469037fec642b
gettext/0.20.1@bincrafters/stable: Downloaded package revision 0
ERROR: gettext/0.20.1@bincrafters/stable: Error in package_info() method, line 33
	self.cpp_info.frameworks.extend(['CoreFoundation'])
	AttributeError: '_CppInfo' object has no attribute 'extend'
```

**Comment by ericLemanissier** [comment]
You need to upgrade to conan >=1.19.0. Your version is missing this  https://github.com/conan-io/docs/pull/1414

**Comment by itsjamie** [comment]
Thank you @ericLemanissier!
