### ISSUE TITLE
[thrift] <Conflicting openssl dependencies through obsolete libevent>

### ISSUE THREAD

**Issue by hplatou** [bincrafters/community#1016]
### Package and Environment Details (include every applicable attribute)
  * thrift/0.12.0: **zstd/1.3.3**
  * Operating System+version: **Windows**

### Conan profile
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=15
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

### Steps to reproduce (Include if Applicable)
`conan install thrift/0.12.0@bincrafters/stable`

### Logs
```
ERROR: Failed requirement 'OpenSSL/1.0.2r@conan/stable' from 'thrift/0.12.0@bincrafters/stable'
ERROR: Requested 'OpenSSL/1.0.2r@conan/stable' but found case incompatible 'openssl'
Case insensitive filesystem can't manage this
```

Problem seems to be usage of obsolete libevent library, which depends on the obsolete `OpenSSL` library.

**Comment by Croydon** [comment]
Fixed by https://github.com/bincrafters/conan-thrift/pull/2
