### ISSUE TITLE
qt doesn't support cross compilation for Neutrino qcc 5.4 armv8

### ISSUE THREAD

**Issue by AliAskari** [bincrafters/community#1017]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.12.4**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **gcc-7.4**, ** cross compiler qcc 5.4**
  * Conan version: **conan 1.19.2**
  * Python version: **Python 3.6.8**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Configuration for profile /home/ali/repos/conan_qt/aarch64-qnx:

[settings]
os_build=Linux
arch_build=x86_64
os=Neutrino
os.version=7.0
arch=armv8
compiler=qcc
compiler.version=5.4
compiler.libcxx=cxx
build_type=Debug
[options]
[build_requires]
[env]
CONAN_CMAKE_FIND_ROOT_PATH=/home/ali/cross_toolchains/qnx/host
CONAN_CMAKE_TOOLCHAIN_FILE=/home/ali/repos/conan_qt/aarch64-qnx-toolchain.cmake
AR=/home/ali/cross_toolchains/qnx/host/usr/bin/aarch64-unknown-nto-qnx7.0.0-ar
AS=/home/ali/cross_toolchains/qnx/host/usr/bin/aarch64-unknown-nto-qnx7.0.0-as
ASM=/home/ali/cross_toolchains/qnx/host/usr/bin/aarch64-unknown-nto-qnx7.0.0-as
CC=/home/ali/cross_toolchains/qnx/host/usr/bin/aarch64-unknown-nto-qnx7.0.0-gcc
CXX=/home/ali/cross_toolchains/qnx/host/usr/bin/aarch64-unknown-nto-qnx7.0.0-g++
RANLIB=/home/ali/cross_toolchains/qnx/host/usr/bin/aarch64-unknown-nto-qnx7.0.0-ranlib
STRIP=/home/ali/cross_toolchains/qnx/host/usr/bin/aarch64-unknown-nto-qnx7.0.0-strip
```

### Steps to reproduce (Include if Applicable)
I'm trying to cross compile qt for qnx7.0, armv8 using the following command:

    conan install conanfile.txt --profile aarch64-qnx --build=outdated

 where the profile is listed as above and the conanfile is this:

```
[requires]
zlib/1.2.11@conan/stable
bzip2/1.0.8@conan/stable
qt/5.12.4@bincrafters/stable

[generators]
cmake

[options]
qt:shared=False
qt:opengl=no
qt:GUI=False
qt:widgets=False
qt:openssl=False
qt:with_glib=False
qt:with_harfbuzz=False
qt:with_mysql=False
qt:with_pq=False
qt:with_odbc=False
qt:with_sdl2=False
qt:with_libalsa=False
qt:with_sqlite3=False
qt:with_openal=False
qt:with_libpng=False
qt:with_libjpeg=False
qt:with_freetype=False
qt:with_pcre2=False
qt:with_doubleconversion=True
```
basically a minimal qt version with all options disabled, except `qt:with_doubleconversion=True`. The problem seems to be that qt recipe is not written to support qnx/neutrino because I am getting this message during conan install:

    qt/5.12.4@bincrafters/stable: WARN: host not supported: Neutrino qcc 5.4 armv8

and it seems qt does not recognize that it's being cross compiled as it does not pass the xplatform flag, also from the logs I only see:

    Build type: linux-g++ (arm64, CPU features: neon)

but it should have been something like  (below is what I get when cross compiling for linux/armv8)

    Building on: linux-g++ (x86_64, CPU features: mmx sse sse2)
    Building for: linux-aarch64-gnu-g++ (arm64, CPU features: neon)

### Logs (Include/Attach if Applicable)

[conan_qnx.log](https://github.com/bincrafters/community/files/3789392/conan_qnx.log)

**Comment by ericLemanissier** [comment]
this should be fixed in 5.13.2
