### ISSUE TITLE
Libjpeg errors in Windows

### ISSUE THREAD

**Issue by memsharded** [bincrafters/community#102]
Windows, all versions

Inspection with ``dumpbin`` over *libjpeg.lib* shows it is using LIBCMT, while the package declares in the *conaninfo.txt* that it is using MD runtime.

It is not building correctly in Windows. I will have another look, try to submit PR if find a fix.

Also, it is very weird that build_requires are hardcoded in this recipe. They should belong to a profile, if any, because the normal thing is to have a mingw in the machine, or in the profile. The version of gcc would be non defined.

**Comment by theirix** [comment]
Thanks for the report! Have you tried the latest version? I updated and reuploaded `stable/9b` it two days ago with the similar fixes.

**Comment by theirix** [comment]
Fixed this and rebuilt stable/9b. Please try.

**Comment by memsharded** [comment]
Yes, now the runtime is the correct one, many thanks for the quick response!
Also I see the build_requires removed, so I think this issue can be closed. :)
