### ISSUE TITLE
[qt] qt/5.13.2 windows build failing

### ISSUE THREAD

**Issue by rpasichnyk** [bincrafters/community#1021]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.13.2**
  * Operating System+version: **Windows 10**
  * Compiler+version: **Visual Studio 2017**
  * Conan version: **conan 1.20.0**
  * Python version: **Python 3.7.4**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=15
build_type=Release

### Steps to reproduce (Include if Applicable)

conan install qt/5.13.2@bincrafters/stable --build

### Logs (Include/Attach if Applicable)

Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=15
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

qt/5.13.2@bincrafters/stable: ************************************************************
qt/5.13.2@bincrafters/stable:   This package defines both 'os' and 'os_build'
qt/5.13.2@bincrafters/stable:   Please use 'os' for libraries and 'os_build'
qt/5.13.2@bincrafters/stable:   only for build-requires used for cross-building
qt/5.13.2@bincrafters/stable: ************************************************************
ERROR: qt/5.13.2@bincrafters/stable: Error in configure() method, line 210
        assert QtConan.version == QtConan._submodules['qtbase']['branch']
        AssertionError:

**Comment by ericLemanissier** [comment]
I cannot reproduce this error. When I download exported files from bintray https://dl.bintray.com/bincrafters/public-conan/bincrafters/qt/5.13.2/stable/0/export/conan_export.tgz, qtmodules.conf has the proper version:
```
[submodule "qtbase"]
	path = qtbase
	url = ../qtbase.git
	branch = 5.13.2
	status = essential
```
Could you please retry with `--update` argument ?

**Comment by Shoodown** [comment]
Hello, I have the same issue on MacOS 10.14.6.

Event with --update arg, it's impossible to add this receipe. Try with mutliple Qt version from 5.12.5 to 5.13.2.
Already tried to uninstall/reinstall Conan pkg.
Don't know what I can do for install Qt with Conan.

```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=11.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]

qt/5.13.2@bincrafters/stable: ************************************************************
qt/5.13.2@bincrafters/stable:   This package defines both 'os' and 'os_build' 
qt/5.13.2@bincrafters/stable:   Please use 'os' for libraries and 'os_build'
qt/5.13.2@bincrafters/stable:   only for build-requires used for cross-building
qt/5.13.2@bincrafters/stable: ************************************************************
ERROR: qt/5.13.2@bincrafters/stable: Error in configure() method, line 210
        assert QtConan.version == QtConan._submodules['qtbase']['branch']
        AssertionError: 
```

**Comment by ericLemanissier** [comment]
could you please send me the file `~\.conan\data\qt\5.13.2\bincrafters\stable\export\qtmodules.conf` ?

**Comment by Shoodown** [comment]
Yes : 
https://gist.github.com/Shoodown/9d8d3436833a65af03861158cced8309

**Comment by ericLemanissier** [comment]
ok, reproduced with conan 1.20.0 on linux. I'm investigating

**Comment by ericLemanissier** [comment]
fix is currently on the testing branch, and will be merged in stable branch when CI will be successful. In the meantime, you can revert back to conan 1.19.2
