### ISSUE TITLE
rapidjson build fails

### ISSUE THREAD

**Issue by Kap1bara** [bincrafters/community#1024]
### Description of Problem, Request, or Question
Failing on executing: **conan install . -s build_type=Release --install-folder=cmake-build-release --build missing -u** with  **assert ref.revision is not None, conan_file** while installing **rapidjson/1.1.0@bincrafters/stable**
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **rapidjson/1.1.0**
  * Operating System+version: **Linux Ubuntu 19.04**
  * Compiler+version: **gcc-9.1**
  * Conan version **1.20.1**
  * Python version: **Python 3.7.3**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]

**Comment by Croydon** [comment]
This recipe is now in the [Conan Center Index](https://github.com/conan-io/conan-center-index/).

Please migrate to the recipe version there. 
If this is still an issue, please create a new issue in the [Conan Center Index issue tracker](https://github.com/conan-io/conan-center-index/issues).

Thanks!
