### ISSUE TITLE
[Swig_installer] Unable to find swg

### ISSUE THREAD

**Issue by rea-yseop** [bincrafters/community#1026]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **swig_installer/4.0.1**
  * Operating System+version: **Linux Debian 10**
  * Compiler+version: **gcc-8**
  * Conan version: **conan 1.19.1**
  * Python version: **Python 3.7.3**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=8
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
./swig -python test.i 

### Logs (Include/Attach if Applicable)
```
:1: Error: Unable to find 'swig.swg'
:3: Error: Unable to find 'python.swg'
```

The issue is similar to the troubleshooting in https://github.com/swig/swig.
And when i tried `swig -swiglib`, it gave an inexistant path.
I also tried to use the option `-I` of swig to give the real path which kinda work but ask me to do it for every folder in `share`.

**Comment by Croydon** [comment]
//@madebr
