### ISSUE TITLE
[m4_installer] m4_installer fails to build (on some systems)

### ISSUE THREAD

**Issue by madebr** [bincrafters/community#1027]
`m4_installer` fails to build on some systems with the following error:
```
freadahead.c: In function 'freadahead':
freadahead.c:92:3: error: #error "Please port gnulib freadahead.c to your platform! Look at the definition of fflush, fread, ungetc on your system, then report this to bug-gnulib."
  #error "Please port gnulib freadahead.c to your platform! Look at the definition of fflush, fread, ungetc on your system, then report this to bug-gnulib."
   ^~~~~
make[3]: *** [Makefile:1910: freadahead.o] Error 1
make[3]: *** Waiting for unfinished jobs....
fseeko.c: In function 'rpl_fseeko':
fseeko.c:110:4: error: #error "Please port gnulib fseeko.c to your platform! Look at the code in fseeko.c, then report this to bug-gnulib."
   #error "Please port gnulib fseeko.c to your platform! Look at the code in fseeko.c, then report this to bug-gnulib."
    ^~~~~
```
Complete log can be found at https://github.com/bincrafters/conan-swig_installer/pull/4#issuecomment-551139542

Reported by @rea-yseop (via #1026 and bincrafters/conan-swig_installer#4)

This looks to be the same problem as:
https://github.com/sifive/freedom-u-sdk/issues/74
https://git.busybox.net/buildroot/commit/?id=c48f8a64626c60bd1b46804b7cf1a699ff53cdf3

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **m4_installer/1.4.18**
  * Operating System+version: **Linux Debian 10**
  * Compiler+version: **gcc-8**
  * Docker image: **conanio/gcc7**
  * Conan version: **conan 1.19.1**
  * Python version: **Python 3.7.3**

### Conan profile

```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=8
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]

**Comment by SSE4** [comment]
@madebr thanks for letting know
I am in process of adding upgraded, bison into conan-center-index, and it turns out I need to add m4 first (maybe upgraded as well)

**Comment by Viatorus** [comment]
Same for me, GCC 9.2 (using it from swig_installer 4.0.1).

**Comment by Talkless** [comment]
Same on Raspbian GNU/Linux 10 (Debian Buster) armv7l while installing qt/5.13.2.
Anyone knows workaround?

**Comment by ericLemanissier** [comment]
@Talkless m4_installer is required mainly for bison_installer and flex_installer. Usually, these two are only required if the system bison (resp flex) is not detected. So the easiest workaround is to install system version of bison and flex.

**Comment by Croydon** [comment]
This recipe is now in the [Conan Center Index](https://github.com/conan-io/conan-center-index/).

Please migrate to the recipe version there. 
If this is still an issue, please create a new issue in the [Conan Center Index issue tracker](https://github.com/conan-io/conan-center-index/issues).

Thanks!
