### ISSUE TITLE
[Cryptopp] Linker error with shared library/dll under Windows

### ISSUE THREAD

**Issue by j-carl** [bincrafters/community#1028]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **cryptopp/8.2.0@bincrafters/stable**
  * Operating System+version: **Microsoft Windows 10 Pro 10.0.18362 N/A 18362**
  * Compiler+version: **Microsoft C/C++ Optimizing Compiler Version 19.23.28106.5 for x84**
  * Conan version: **conan 1.19.2**
  * Python version: **Python 3.8.0**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Windows
os_build=Windows
arch=x86
arch_build=x86
compiler=Visual Studio
compiler.version=16
build_type=Debug
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

1. create configuration file `conanfile.txt` with these settings:

```
[requires]
cryptopp/8.2.0@bincrafters/stable
[generators]
visual_studio
[options]
cryptopp:shared=True
```
2. run `conan install . --build cryptopp`
3. add created propsheet to your VS project
4. include needed headers from CryptoPP to your source code
```
#include <cryptopp/dll.h>
#include <cryptopp/filters.h>
#include <cryptopp/hex.h>
#include <cryptopp/sha.h>

#include <string>

int main() {
  std::string text{"CryptPP"};
  std::string hash{};

  CryptoPP::SHA256 sha256;
  CryptoPP::StringSource(text, new CryptoPP::HashFilter(sha256, new CryptoPP::HexEncoder(new CryptoPP::StringSink(hash))));
  return 0;
}
```

5. build solution

You will get a linker error `LINK 1104 cannot open file 'cryptopp.lib'`.

To use the DLL CryptoPP advises you to include the file `dll.h` (https://github.com/weidai11/cryptopp/blob/master/Readme.txt#L136 ). This file contains the line `#pragma comment(lib, "cryptopp")` to specify which dll to load (https://github.com/weidai11/cryptopp/blob/master/dll.h#L48:L55), but conan packages the shared library with the suffix `-shared` as `cryptopp-shared.lib`. So the linker cannot find the file.

### Logs (Include/Attach if Applicable)
[conanbuild.txt](https://github.com/bincrafters/community/files/3822244/conanbuild.txt)

**Comment by Croydon** [comment]
This recipe is now in the [Conan Center Index](https://github.com/conan-io/conan-center-index/).

Please migrate to the recipe version there. 
If this is still an issue, please create a new issue in the [Conan Center Index issue tracker](https://github.com/conan-io/conan-center-index/issues).

Thanks!

**Comment by jnickg** [comment]
@Croydon any chance you can provide a more direct link to the recipe? I'm getting the same issue as this and am unable to infer the solution based on your response/links.

**Comment by Croydon** [comment]
https://conan.io/center/cryptopp (the recipe reference has to be without the `bincrafters/stable` part)

I don't know if this recipe version still has this issue, but if it has you have to open a new issue here: https://github.com/conan-io/conan-center-index/issues
