### ISSUE TITLE
sdl2_image and sdl2_mixer woes on Windows

### ISSUE THREAD

**Issue by madebr** [bincrafters/community#1029]
Hey, I just wanted to compile a project using SDL2_mixer and SDL2_image.
- SDL2_mixer requires (by default) `libmodplug/0.8.9.0@bincrafters/stable` but cannot find it from the bincrafters remote
- SDL2_image/2.0.5 is not available from the bincrafters remote (neither testing and stable) (I'd prefer to use the 2.0.5 version because this one uses zlib from conan-center-index)
- Also, for `SDL2`, `SDL2_image` and `SDL2_mixer`, it would be interesting to add `self.cpp_info.name = "SDL2_image"` (capitalized `SDL2`)

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libmodplug/0.8.9.0** and **SDL2_image/2.0.5**
  * Operating System+version: **Windows 10**
  * Compiler+version: **Visual Studio 2017**
  * Conan version: **conan 1.20.0**
  * Python version: **Python 3.8.0**

### Logs (Include/Attach if Applicable)
```
ERROR: Failed requirement 'libmodplug/0.8.9.0@bincrafters/stable' from 'sdl2_mixer/2.0.4@bincrafters/stable'
ERROR: Recipe not found: 'libmodplug/0.8.9.0@bincrafters/stable'
```

```
>conan install sdl2_image/2.0.5@bincrafters/testing
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=15
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

sdl2_image/2.0.5@bincrafters/testing: Not found in local cache, looking in remotes...
sdl2_image/2.0.5@bincrafters/testing: Trying with 'conan-center'...
sdl2_image/2.0.5@bincrafters/testing: Trying with 'conan-transit'...
sdl2_image/2.0.5@bincrafters/testing: Trying with 'maarten'...
sdl2_image/2.0.5@bincrafters/testing: Trying with 'bincrafters'...
ERROR: Unable to find 'sdl2_image/2.0.5@bincrafters/testing' in remotes
```

**Comment by Croydon** [comment]
sdl2_image/stable is available: https://bintray.com/bincrafters/public-conan/sdl2_image%3Abincrafters/2.0.5%3Astable

we don't upload testing packages on purpose

libmodplug 0.8.90 should be available as well: https://bintray.com/bincrafters/public-conan/libmodplug%3Abincrafters/0.8.9.0%3Astable

**Comment by madebr** [comment]
The reason I was asking about the testing image was because only that one was using CCI.

**Comment by Croydon** [comment]
I just merged `testing/` into `stable/`

**Comment by Croydon** [comment]
@madebr Can we close this?

**Comment by madebr** [comment]
@Croydon Yup, safe to close
