### ISSUE TITLE
Unnecessary version-ranges on libpng

### ISSUE THREAD

**Issue by memsharded** [bincrafters/community#103]
Latest libpng libpng/1.6.34@bincrafters/stable is doing a version-ranges depndency to zlib. Zlib has not had releases in years, and anyway it is used by many packages. If a new version comes out, it will be mandated by the downstream for overriding in any case.

I would suggest requiring ``zlib/1.2.11`` explictly.

```
Version range '~=1.2' required by 'libpng/1.6.34@bincrafters/stable' valid for downstream requirement 'zlib/1.2.11@conan/stable'
```

**Comment by memsharded** [comment]
Yes, they are much slower to resolve.
And also, repeatibility, unexpected breakages. zlib/1.2.12 (in the case it went out) could break, have bugs... I much prefer fixed versions, and explicit upgrades by consumers.

**Comment by theirix** [comment]
Actually I found no official policy in docs or issues about using version ranges for recipes and reproducibility. If the overriding in a consumer `conanfile.txt` works fine and allows to override fixed or ranged dependencies - it's totally ok, we can switch to fixed versions.

The main reason I am using ranged deps is to automatically provide latest versions (especially OpenSSL) for a consuming project without overriding. The main disadvantage are build non-reproducibility and possibility of breaking things.

If we decide to use fixed deps, we should rework majority of recipes (not only png) and just change their fixed deps to latest version that satisfy a range. It should not affect anything.

**Comment by memsharded** [comment]
I'd say that reproducibility and stability are slightly more important than using the latest versions.

**Comment by theirix** [comment]
Removed range dependency from libpng. Will consider other packages during refactoring.
