### ISSUE TITLE
[jsonformoderncpp] Update for new versions

### ISSUE THREAD

**Issue by ShadowMitia** [bincrafters/community#1030]
### Package Details
  * Package Name: **jsonformoderncpp**
  * Latest available Version: **3.7.2**

The above mentioned version is newly released by the upstream project and not yet available within Bincrafters. Please add this version.

**Comment by Croydon** [comment]
We never had a jsonformoderncpp recipe. You probably confused us with Conan Center Index

https://github.com/conan-io/conan-center-index/tree/master/recipes/jsonformoderncpp

**Comment by ShadowMitia** [comment]
Oh, sorry... I'll have a better look next time!
