### ISSUE TITLE
[swig_installer] unknown option with cmake

### ISSUE THREAD

**Issue by rea-yseop** [bincrafters/community#1031]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **swig_installer/4.0.1**
  * Operating System+version: **Linux Debian 10**
  * Compiler+version: **gcc-8**
  * Conan version: **conan 1.19.1**
  * Python version: **Python 3.7.3**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=8
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
```
# Set up swig
find_package(swig_installer REQUIRED)

# Set policies to new to avoid warning.
# Should be removed in later version of cmake.
if (POLICY CMP0078)
cmake_policy(SET CMP0078 NEW)
endif()

if (POLICY CMP0086)
    cmake_policy(SET CMP0086 NEW)
endif()

# Enable methods from cmake swig.
include(UseSWIG)

# Include python
find_package(Python3 REQUIRED)
include_directories(${Python3_INCLUDE_DIRS})

swig_add_library(my_module
    TYPE MODULE
    LANGUAGE python
    SOURCES my_module.i)
```

### Logs (Include/Attach if Applicable)
```
cmake -E env: unknown option '-python'
```
I am trying to use swig_installer with CMake. 
Not sure if it is related to https://github.com/bincrafters/community/issues/1026.

**Comment by kopylow** [comment]
Hello.
I've got the same issue. Did you maybe found a way to fix this?

**Comment by Croydon** [comment]
@madebr could you maybe have a look? 😄

**Comment by madebr** [comment]
@rea-yseop 
`UseSWIG` only works with cmake's `SWIG`.

So you still need `find_package(SWIG REQUIRED)`.

**Comment by rea-yseop** [comment]
Sorry completely forgot to update this issue.
Thanks for the answer. I also had issue by using only `find_package(SWIG REQUIRED)` and had to be more specific by using `find_package(SWIG 4 REQUIRED)`.

**Comment by madebr** [comment]
@rea-yseop 
This recipe will soon be available on CCI (https://github.com/conan-io/conan-center-index/pull/1717)

**Comment by rea-yseop** [comment]
This works for me. Thank you :)
