### ISSUE TITLE
Make libpng discoverable by cmake find (static version)

### ISSUE THREAD

**Issue by memsharded** [bincrafters/community#104]
At least cmake 3.7 fails to discover libpng in Windows, due to the strange name it has for the static version. Renaming it makes the trick:

```python
    def package(self):
        shutil.rmtree(os.path.join(self.package_folder, 'share', 'man'), ignore_errors=True)
        try:
            os.rename(os.path.join(self.package_folder, "lib", "libpng16_static.lib"),
                      os.path.join(self.package_folder, "lib", "libpng16.lib"))
        except:
            pass
````

, and allows to do:

```cmake
find_package(PNG REQUIRED)
add_executable(${PROJECT_NAME} test_package.cpp)
target_link_libraries(${PROJECT_NAME} PNG::PNG)
set_property(TARGET ${PROJECT_NAME} PROPERTY CXX_STANDARD 11)
```

This is an ugly fix, of course, it needs something more elegant, just the idea for feedback. I might try to submit a PR with a better implementation, but would like feedback first in case I am missing something

cc/ @theirix

**Comment by theirix** [comment]
Good idea, renaming should help. I'll do it.

Perhaps it happened because [recently I dropped](bincrafters/conan-libpng@abde59f585903e0840fbb230a9bf1716fd15b3e4) `FindPNG.cmake` from the package because the system finder does the work (but with standard names).

**Comment by theirix** [comment]
Some thoughts about dropping finders.

Unfortunately libpng does not provide autogenerated `*Config.cmake` with paths - a file that [allows](https://cmake.org/cmake/help/v3.1/command/find_package.html) cmake to find package even without a specific `Find*.cmake` finder and to use exact specified paths from a config.

So there are there possibilities:
1. If package have `*Config.cmake` (webp, openjpeg) we can drop a finder from a package entirely.
2. If package omits config, it should be checked when an oldest CMake like 2.8.11 has the working finder. Usually they are here for old popular packages.
3. If no config and no checker, provide a finder in a conan package.

**Comment by memsharded** [comment]
> Perhaps it happened because recently I dropped FindPNG.cmake from the package because the system finder does the work (but with standard names).

It is good, if the system finder works, it is better than having a custom find inside the package. What is wrong is the library name, better rename it, yep.

About the approach for dropping finders, sound perfect. Just I think conan needs 2.8.12, and might not work with 2.8.11, but not fully sure.

**Comment by theirix** [comment]
Published updated version without suffices. Please check that it works for your cmakefile.

**Comment by memsharded** [comment]
Works like a charm, thank you!

Consider adding:
```cmake
find_package(PNG REQUIRED)
add_executable(${PROJECT_NAME} test_package.cpp)
target_link_libraries(${PROJECT_NAME} PNG::PNG)
set_property(TARGET ${PROJECT_NAME} PROPERTY CXX_STANDARD 11)
```
to the test_package. That could be an addition, you can still compile another executable, with same sources, but using direct conan information. In that way, you would be testing if it works both for cmake ``find_package`` and directly with conan. Just an idea, not really necessary, it looks good as is.

Thanks!
