### ISSUE TITLE
[wxwidgets/3.1.2] not building on macOS Catalina

### ISSUE THREAD

**Issue by ltjax** [bincrafters/community#1042]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **wxwidgets/3.1.2**
  * Operating System+version: **macOS Catalina (10.15.1)**
  * Compiler+version: **Apple clang version 11.0.0**

### Conan profile
```
[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=11.0
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

`conan install wxwidgets/3.1.2@bincrafters/stable --build missing`

### Logs (Include/Attach if Applicable)

```
...
[ 67%] Building CXX object source_subfolder/libs/core/CMakeFiles/core.dir/__/__/__/__/src/osx/carbon/font.cpp.o
/.../.conan/data/wxwidgets/3.1.2/bincrafters/stable/build/490b017f173e6e1248bca78bdd7a390db9baf3fd/source_subfolder/src/html/htmlctrl/webkit/webkit.mm:24:10: fatal error: 'WebKit/HIWebView.h' file
      not found
#include <WebKit/HIWebView.h>
         ^~~~~~~~~~~~~~~~~~~~
/.../.conan/data/wxwidgets/3.1.2/bincrafters/stable/build/490b017f173e6e1248bca78bdd7a390db9baf3fd/source_subfolder/src/html/htmlctrl/webkit/webkit.mm:24:10: note: did not find header 'HIWebView.h'
      in framework 'WebKit' (loaded from '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks')
1 error generated.
...
```

**Comment by ltjax** [comment]
I noticed the offending include is conditional in the new wxWidgets 3.1.3 release:
```
#if MAC_OS_X_VERSION_MAX_ALLOWED < MAC_OS_X_VERSION_10_15
#include <WebKit/HIWebView.h>
#include <WebKit/CarbonUtils.h>
#endif
```
So it's probably not working in upstream or with their autotools-based build as well.

**Comment by Croydon** [comment]
We have made a 3.1.3 release. Are you able to update?

**Comment by ltjax** [comment]
Sure, that's why we made the update. Should we close this?

**Comment by Croydon** [comment]
Since this is an upstream bug and is fixed in the newer release, yes.
