### ISSUE TITLE
[qt] Keep getting "found case incompatible 'Qt'" because the qt package keeps creating it

### ISSUE THREAD

**Issue by zethon** [bincrafters/community#1045]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.13.2**
  * Operating System+version: **macOS 10.14**
  * Compiler+version: **clang 10.0.1**
  * Docker image: **N/A**
  * Conan version: **conan 1.20.4**
  * Python version: **Python 3.7.0**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)

```
$> conan profile show default
Configuration for profile default:

[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=10.0
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

I've been trying to use the Qt package in a project. 

At the beginning of the gif you can see the packages installed on my system, of which Qt is not one of them. I run `conan install ..` which gives the error:

```
ERROR: Requested 'qt/5.13.2@bincrafters/stable' but found case incompatible 'Qt'
Case insensitive filesystem can't manage this
```
And then when I list my packages again, the `Qt/...` package has appeared! So, I delete it, run `conan install ..` again, and get the same error **and** the package has reappeared!
### Logs (Include/Attach if Applicable)

![conanqt](https://user-images.githubusercontent.com/5203583/69482225-797b8a00-0de6-11ea-8225-928f71617906.gif)

**Comment by zethon** [comment]
Here is my `conanfile.txt` for reference:

```[requires]
boost/1.68.0@conan/stable
qt/5.13.2@bincrafters/stable

[options]
boost:shared=False
boost:without_test=False

[generators]
cmake
```

**Comment by ericLemanissier** [comment]
Can you try to remove the folder ~/.conan/data/Qt after calling `conan remove Qt/*` ?

**Comment by zethon** [comment]
Yup, that got rid of the error. Thank you!
