### ISSUE TITLE
[wxwidgets] Mingw cross-compile from Linux to Windows

### ISSUE THREAD

**Issue by bccox** [bincrafters/community#1053]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **wxwidgets/3.1.2**
  * Operating System+version: **Linux Debian bullseye/sid**
  * Compiler+version: **gcc-8.3**
  * Conan version: **Conan 1.20.4**
  * Python version: **Python 3.7.5**

### Description of your feature

I'd like to request that the existing wxWidgets package be extended to support cross-compilation from Linux to Windows. I've found a manual work-around that I'm fine with doing (explained in a bit), but it might save someone else a bit of frustration if this is supported out of the box.

### The Problem

The package gets tantalizingly close as it already is, but most of the generated libraries lack the expected `lib` prefix, instead being named like `wxmsw31u_core.a`, etc. Without the prefix, the CMake generator misses the package's libraries and it tries to compensate by appending `-lwxmsw31u_core` to the link step. What's expected is something like `~/.conan/data/wxwidgets/[...]/package/[...]/lib/gcc_lib/libwxmsw31u_core.a` to be passed directly to the linker for each wxWidgets library.

### Manual Work-around

If I manually create symlinks (e.g., `libwxmsw31u_core.a -> wxmsw31u_core.a`) within the appropriate package directory under `~/.conan/data/wxwidgets` and regenerate my CMake buiild for a project that requires wxWidgets, it successfully cross-links and the resulting program runs on Windows.

**Example profile:**
```
toolchain=/usr/lib/gcc/i686-w64-mingw32
target_host=i686-w64-mingw32
cc_compiler=gcc
cxx_compiler=g++

[settings]
os_build=Linux
arch_build=x86_64
compiler=gcc
compiler.version=8
compiler.libcxx=libstdc++11
os=Windows
arch=x86
build_type=Release

[env]
CONAN_CMAKE_FIND_ROOT_PATH=$toolchain
CHOST=$target_host
AR=$target_host-ar
AS=$target_host-as
RANLIB=$target_host-ranlib
CC=$target_host-$cc_compiler
CXX=$target_host-$cxx_compiler
STRIP=$target_host-strip
RC=$target_host-windres
```

**Comment by Croydon** [comment]
* could you re-test this with wxwidgets 3.1.3 please?
 * is upstream supporting MinGW cross-compiling from Linux to Windows?

**Comment by bccox** [comment]
@Croydon Well, this is a bit embarrassing, but it's looking like this was a PEBKAC error after all. After fiddling with the build, it turns out that you need to explicitly set the `CMAKE_SYSTEM_NAME` CMake variable to "Windows" when cross-compiling. I had originally overlooked that.

Without that variable set, CMake is expecting to find libraries named like `libwxmsw31u_core.a`, and it will configure the build scripts accordingly. With that variable set, CMake will use Windows library naming conventions, such as `wxmsw31u_core.a` (which is what the wxWidgets recipe currently produces for Windows builds) when it's configuring the project's build scripts.

So long as you have a correctly configured Conan profile and you tell CMake that it's cross-compiling to Windows via the `CMAKE_CXX_COMPILER` and `CMAKE_SYSTEM_NAME`, the wxWidgets recipes (both 3.1.2 and 3.1.3) work fine. As far as I now can tell, nothing  needs to be done on your end.

Sorry for the inconvenience of having to deal with this non-issue. I'll close the issue now.
