### ISSUE TITLE
[azure-iot-sdk-c] doesn't build

### ISSUE THREAD

**Issue by RelayrMA** [bincrafters/community#1055]
### Package and Environment Details
  * Package Name/Version: **azure-iot-sdk-c/1.1.21**
  * Operating System+version: **Gentoo**
  * Compiler+version: **gcc-8.3**
  * Conan version: **conan 1.20.4**
  * Python version: **Python 3.6.9**

### Steps to reproduce 
I tried building the IoT SDK. First it failed because it depends on Parson and such library doesn't exist. But I noticed that there's another, called parson. After correcting capitalization it failed with:
AttributeError: 'AzureiotsdkcConan' object has no attribute 'copy'

I don't know how to fix that so I bailed out.

### Logs
[1.txt](https://github.com/bincrafters/community/files/3904715/1.txt)
[2.txt](https://github.com/bincrafters/community/files/3904716/2.txt)

**Comment by Croydon** [comment]
Sorry, but the azure-iot-sdk-c recipe is archived and unmaintained.

https://github.com/bincrafters/conan-azure-iot-sdk-c
