### ISSUE TITLE
[imagemagick] Build fails with 'undefined reference to `fcntl64''

### ISSUE THREAD

**Issue by bmanga** [bincrafters/community#1058]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **imagemagick/7.0.8-44**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **gcc-9.1**
  * Conan version: **conan 1.20.4**
  * Python version: **Python 3.7.0**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
CXX=g++-9
CC=gcc-9

### Steps to reproduce (Include if Applicable)
conan install imagemagick/7.0.8-44@bincrafters/stable --build missing

### Logs (Include/Attach if Applicable)
[compiler_output.txt](https://github.com/bincrafters/community/files/3911810/compiler_output.txt)

**Comment by bmanga** [comment]
imagemagick/7.0.8-10 installs works fine for me.

**Comment by bmanga** [comment]
Actually, imagemagick/7.0.8-10 is still broken for me :( . While the package installs fine, I get a number of linker errors when using it in my project. I have attached the output.
[compiler_output.txt](https://github.com/bincrafters/community/files/3913733/compiler_output.txt)

**Comment by Croydon** [comment]
This recipe is now in the Conan Center Index.

Please migrate to the recipe version there.
If this is still an issue, please create a new issue in the Conan Center Index issue tracker.

Thanks!

https://conan.io/center/imagemagick
