### ISSUE TITLE
What is the plan for all Boost packages?

### ISSUE THREAD

**Issue by helmesjo** [bincrafters/community#106]
### Description of Problem, Request, or Question

I've currently been running `boost/1.64.0@conan/stable`, but because of other dependencies I'm moving over to bincrafters/stable. I noticed, however, that there are both individual packages for each boost module, but also one "top package" called just `Boost` (presumably containing all modules).

Correct me if I'm wrong but if other packages list say `Boost.System/1.64.0` ([soon to be boost_system](https://github.com/bincrafters/community/issues/99#issuecomment-362924153)) as a dependency, that package id will not match `Boost/1.64.0`, thus invoking a new download/build, right?

If so, is the plan to remove `Boost/1.64.0`, and opt for having only the individual modules? The latter sounds better IMO!

@lasote, given above, are there plans for conan to support any form of "bulk download" if it detects that multiple required packages are available in the same repository? Currently fetching the full `Boost`-package is _a lot_ quicker than having to open a new connection for each and every boost-module in the dependency tree (we are talking _seconds vs minutes_).

Anyways, thank you all for the hard work!

### Package Details (Include if Applicable)
* Package Name/Version: **boost_<module>/XXX**
* Operating System: **Linux**
* Compiler+version: **gcc-7**

**Comment by solvingj** [comment]
Hi @helmesjo, great questions. 

Yes, the Boost/1.64.0 meta package concept will go away.  It was helpful for us during initial testing but we didn't intend people to use it.  I suppose if people demonstrated a common use-case for it, we could re-add it, but conceptually it's a bit opposite to the goal of the modular packages, but not entirely. 

We started backporting to boost 1.65.1 last week and ran into a problem. We went back and made some changes, are now doing a rebuild of 1.66.0 now.  Then 1.65.1, then 1.64.0.  WE'll go as fast as we can :)  Hopefully not more than 1 week?

Very interesting question about the bulk-download.  I have also thought about this, but only just recently when looking at our CI.  Bintray API supports a "download list" which I believe supports this kind of behavior, but i never used it, and that's separate from the Conan API.

**Comment by lasote** [comment]
About the bulk download: https://github.com/conan-io/conan/issues/1012

**Comment by solvingj** [comment]
Awesome, thanks.  Closing for now.  @helmesjo please feel free to re-open if you have further questions.

**Comment by solvingj** [comment]
Note, 1.65.1 backport is complete.

**Comment by helmesjo** [comment]
Thanks for the update, and great work! 

__Quick question:__ 
Will 1.64.0 also be adopting the lowercase naming convention?

**Comment by solvingj** [comment]
Yes, hope this week
