### ISSUE TITLE
[qt] How to get qmake?

### ISSUE THREAD

**Issue by romainreignier** [bincrafters/community#1064]
### Package and Environment Details
  * Package Name/Version: **qt/5.13.2**
  * Operating System+version: **Windows 10**
  * Compiler+version: **Visual Studio 15**
  * Conan version: **Conan 1.20.5**

### Question Description
Sorry for the newbie question, but I want to use Conan to build a Qt application using qmake files (`.pro`).
So I have followed this page: https://docs.conan.io/en/latest/integrations/build_system/qmake.html
But how do I get the `qmake` executable. I know that I can get it from a full Qt installation but in that case, there is no point to use Conan and furthermore, if I only use the qmake of a Qt installation, it may mess the libraries path, isn't it?

**Comment by romainreignier** [comment]
Hum... I have found a `qmake.exe` in `C:\.conan\d8d79d\1\bin`.

So now, I have to understand how a build the Qt application using it from the conan cli.

**Comment by ericLemanissier** [comment]
You have to reference `qt/5.13.2@bincrafters/stable` as a requirement in your conanfile, and add the `virtualrunenv` to the generators. This will create a file named `activate_run`, which modify the `PATH` environment variable and make `qmake` available (https://docs.conan.io/en/latest/mastering/virtualenv.html#virtualrunenv-generator)

**Comment by romainreignier** [comment]
Ok, I see, thanks a lot.
