### ISSUE TITLE
[cpprestsdk] with dependencies from Conan Center Index  repo

### ISSUE THREAD

**Issue by dmn-star** [bincrafters/community#1065]
### Description of Problem, Request, or Question
I have tried to use cpprestsdk with the dependencies from Conan Center Index repo.

1) ERROR:  Requested 'openssl/1.1.1d' but found case incompatible 'OpenSSL'
		   Case insensitive filesystem can't manage this

I found the similar issue #1557 https://github.com/conan-io/conan/issues/1557

2) Target "test_conan_index" links to target "CONAN_PKG::libxml2" but the target
    was not found.  Perhaps a find_package() call is missing for an IMPORTED
I've changed from CONAN_PKG::libxml2 to CONAN_PKG::LibXml2.

 Two questions:

1) Do you plan to update cpprestsdk recipe  to works with the dependencies from Conan Center Index repo?

2) Are the CONAN_PKG::xxx case sensitive now? 

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **cpprestsdk/2.10.14@bincrafters/stable**
  * Operating System+version: **macOS Catalina 10.15.1**
  * Compiler+version: **NDK r20 clang (8?)**
   * Conan version: **Conan 1.20.5**
  * Python version: **Python 3.7.4**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
_______________
conanfile.txt
[requires]
cpprestsdk/2.10.14@bincrafters/stable
openssl/1.1.1d
libxml2/2.9.9
zlib/1.2.11
boost/1.70.0
libxslt/1.1.33@bincrafters/stable

[generators]
cmake

[options]
cpprestsdk:exclude_websockets = True

_______________
profile
[settings]
os_build=Macos
arch_build=x86_64

compiler=clang
compiler.version=8
compiler.libcxx=libc++
os=Android
os.api_level=21
arch=armv7
build_type=Release

[build_requires]
android_ndk_installer/r20@bincrafters/stable

### Steps to reproduce (Include if Applicable)
Install & cross build cpprestsdk with custom profile

**Comment by uilianries** [comment]
> ERROR: Requested 'openssl/1.1.1d' but found case incompatible 'OpenSSL'
Case insensitive filesystem can't manage this

You have both openssl/1.1.1d (from CCI) and OpenSSL (from Conan Community). As you can see the name is same, but the package is not the same. Removing the old version (OpenSSL) should work, but as it's that package requires the old version, we need to fix it.

> 1. Do you plan to update cpprestsdk recipe to works with the dependencies from Conan Center Index repo?

Yes, until having it in CCI.

> 2. Are the CONAN_PKG::xxx case sensitive now?

Case sensitive it is a system feature, so if you are running Linux or Max (Unix) it's case-sensitive of course.

The libxml2 module was changed to follow the correct name provided by CMake modules: https://gitlab.kitware.com/cmake/cmake/blob/master/Modules/FindLibXml2.cmake

**Comment by dmn-star** [comment]
Thank you for the info.  I will wait until cpprestsdk is updated. May be we need boost 1.69.0 in CCI because of #969 

> The libxml2 module was changed to follow the correct name provided by CMake modules: https://gitlab.kitware.com/cmake/cmake/blob/master/Modules/FindLibXml2.cmake

Ok. But we don't use the cmake_paths generator and find_package(...) in our CMakeLists.txt
I don't see any reason to changes CONAN_PKG names too.

from our CMakeLists.txt.
..
conan_basic_setup(TARGETS)
...
target_link_libraries( # Specifies the target library.
                       test_conan_index
                       ${log-lib} CONAN_PKG::boost CONAN_PKG::cpprestsdk CONAN_PKG::**libxml2** CONAN_PKG::libxslt)
....

I've changed from CONAN_PKG::libxml2 to CONAN_PKG::LibXml2 to compile successfully.

May be cmake generator bug?

**Comment by jmarrec** [comment]
@dmn-star: conan/1.69.0 is being added by @uilianries : https://github.com/conan-io/conan-center-index/pull/498

I patched websocket here: https://github.com/bincrafters/conan-websocketpp/pull/5

So cpprestsdk/stable will work with 1.71.0 once https://github.com/bincrafters/conan-cpprestsdk/pull/9 is merged in (Sync testing 2.10.14 -> stable 2.10.14).

**Comment by dmn-star** [comment]
@jmarrec Good news.

I have tested the current version of cpprestsdk. It works now except for Android #1076 .

I close this for now. Thanks @all !
