### ISSUE TITLE
upgrade Gstreamer to 1.16.2

### ISSUE THREAD

**Issue by barcharcraz** [bincrafters/community#1066]
### Package Details
  * Package Name: **gstreamer**
  * Latest available Version: **1.16.2**

The above mentioned version is newly released by the upstream project and not yet available within Bincrafters. Please add this version.

**Comment by Croydon** [comment]
https://github.com/conan-io/conan-center-index/pull/2303

**Comment by ericLemanissier** [comment]
gstreamer 1.18.0 is now available on conan-center
