### ISSUE TITLE
ffmpeg: libavformat .pc files unusable on windows

### ISSUE THREAD

**Issue by barcharcraz** [bincrafters/community#1068]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **ffmpeg/4.2**
  * Operating System+version: **Windows 10**
  * Compiler+version: **MSVC (VS 16.5)**
  * Conan version: **conan 1.21.0**
  * Python version: **Python 3.8.0**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)

```
Configuration for profile default:

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
build ffmpeg 4.2 (without openjpeg due to another issue)

in cmake:
```cmake
find_package(PkgConfig REQUIRED)
pkg_check_modules(ffmpeg REQUIRED IMPORTED_TARGET libavformat)
```

and link to `PkgConfig::ffmpeg`

build and observe: `[build] LINK : fatal error LNK1104: cannot open file 'bz2.lib'`

**Comment by barcharcraz** [comment]
More detail. The reason this doesn't work is that ffmpeg's build system runs all the flags it outputs to the pc files through the "flag filter" it uses to support msvc style flags. This results in -libpath getting in the Libs: line of the pc file and thus breakage

Also there _is_ something wrong with how it links to bz2

**Comment by ericLemanissier** [comment]
This recipe is now in the Conan Center Index.

Please migrate to the recipe version there.
If this is still an issue, please create a new issue in the Conan Center Index issue tracker.

Thanks!

https://conan.io/center/ffmpeg
