### ISSUE TITLE
[websocketpp] Recent update to bump to openssl/1.1.1d makes existing pipeline break

### ISSUE THREAD

**Issue by jmarrec** [bincrafters/community#1069]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **websocketpp/0.8.1** (`websocketpp/0.8.1@bincrafters/stable`)
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **gcc-7**
  * Conan version: **conan 1.21.0**
  * Python version: **Python 3.8.0**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)

```
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.version=7
compiler.libcxx=libstdc++11
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

Commit https://github.com/bincrafters/conan-websocketpp/commit/212cd56c856ca0c64be28da89d7c82d2e74fe07b bumped the requirement from `OpenSSL/1.1.1c` to `openssl/1.1.1d` in `websocketpp/0.8.1@bincrafters/stable` . **Notice the rename from OpenSSL to openssl**

If you also require `OpenSSL/1.1.1c` in your requirements, there will be an error. This call will fail:

```
  conan_cmake_run(REQUIRES
    OpenSSL/1.1.0g@conan/stable
    websocketpp/0.8.1@bincrafters/stable
    zlib/1.2.11@conan/stable # Needed or it'll crash
)
```

**I created a MCVE at https://github.com/jmarrec/test-conan-websocketpp** that reproduces the error for convenience.

### Logs (Include/Attach if Applicable)

```
-- Conan: Loading conanbuildinfo.cmake
-- Conan: Using cmake targets configuration
-- Library ssl found /home/julien/.conan/data/openssl/1.1.1d/_/_/package/b781af3f476d0aa5070a0a35b544db7a3c193cc8/lib/libssl.a
-- Library crypto found /home/julien/.conan/data/openssl/1.1.1d/_/_/package/b781af3f476d0aa5070a0a35b544db7a3c193cc8/lib/libcrypto.a
-- Library dl not found in package, might be system one
-- Library pthread not found in package, might be system one
-- Library ssl found /home/julien/.conan/data/openssl/1.1.1d/_/_/package/b781af3f476d0aa5070a0a35b544db7a3c193cc8/lib/libssl.a
CMake Error at build/conanbuildinfo.cmake:726 (add_library):
  add_library cannot create imported target "CONAN_LIB::OpenSSL_ssl" because
  another target with the same name already exists.
Call Stack (most recent call first):
  build/conanbuildinfo.cmake:414 (conan_package_library_targets)
  build/conanbuildinfo.cmake:608 (conan_define_targets)
  build/conan.cmake:503 (conan_basic_setup)
  CMakeLists.txt:75 (conan_cmake_run)


-- Library crypto found /home/julien/.conan/data/openssl/1.1.1d/_/_/package/b781af3f476d0aa5070a0a35b544db7a3c193cc8/lib/libcrypto.a
CMake Error at build/conanbuildinfo.cmake:726 (add_library):
  add_library cannot create imported target "CONAN_LIB::OpenSSL_crypto"
  because another target with the same name already exists.
Call Stack (most recent call first):
  build/conanbuildinfo.cmake:414 (conan_package_library_targets)
  build/conanbuildinfo.cmake:608 (conan_define_targets)
  build/conan.cmake:503 (conan_basic_setup)
  CMakeLists.txt:75 (conan_cmake_run)


-- Library dl not found in package, might be system one
-- Library pthread not found in package, might be system one
CMake Error at build/conanbuildinfo.cmake:430 (add_library):
  add_library cannot create imported target "CONAN_PKG::OpenSSL" because
  another target with the same name already exists.
Call Stack (most recent call first):
  build/conanbuildinfo.cmake:608 (conan_define_targets)
  build/conan.cmake:503 (conan_basic_setup)
  CMakeLists.txt:75 (conan_cmake_run)

```

**Comment by dmn-star** [comment]
it looks like we can't mix the dependencies from Conan Index  and from bincrafters repos.
#1065 

You can try openssl 1.1.1c from https://github.com/conan-io/conan-center-index/blob/master/recipes/openssl/config.yml
___
 conan_cmake_run(REQUIRES
    openssl/1.1.1c
___

**Comment by jmarrec** [comment]
My workaround has been to fork websocketpp, and revert the last commit, then upload that to my own bintray repo.

**Comment by uilianries** [comment]
Hi @jmarrec we strongly update your requirements to the new packages in Conan Center Index.

Please, update your CMake file to:

```cmake
openssl/1.1.0g
websocketpp/0.8.1
zlib/1.2.11
)
```

Why not just reverting the last commit? Conan Center Index is the current official repository for recipes. All recipes there will replace the current ones in Bincrafters and Conan Community.

**Comment by jmarrec** [comment]
@uilianries I take good note of your recommendation, thank you. I did what I had to not stall an entire team of developpers hence the workaround.

My actual list of dependencies is obviously more complicated than the mcve (cf [here](https://github.com/NREL/OpenStudio/blob/93c4d4253cbf8cce5e87268e17584318fbdde95e/ConanInstall.cmake#L64) if you're curious, plus the conan-openstudio-ruby one that itself depends on a bunch more dependencies), so I'm not sure how that's going to play out since all packages aren't available in conan center index (eg the modular boost recipes). Do you have an opinion on whether it's going to be easy?
Otherwise I'll have to try and find out.

**Comment by Croydon** [comment]
Hi @jmarrec and sorry for breaking your pipeline 😅  

@uilianries is right, whenever a dependency is in Conan Center Index (CCI) AND Bincrafters you should switch to the CCI version as soon as possible.

This might actually lead to dependencies conflicts too as some other dependency might not have made this switch yet. If this is the case you should report this so we can speed up the switch in these dependencies. Unfortunately, this is a process and we can't just migrate anything in a single step to CCI.

If a Conan package isn't yet in Conan Center Index you can continue to use the Bincrafters (or Conan Community) version.
In your case you can continue to use the module Boost from Bincrafters, but OpenSSL (and probably others) should be migrated to CCI as soon as possible

**Comment by Croydon** [comment]
Some quick notes and references:

How we replace Conan packages in Bincrafters can be seen here https://github.com/bincrafters/bincrafters-conventions/blob/3432a4fe4333df0a5dd1c9847c8b2e0637b196aa/bincrafters_conventions/actions/update_c_recipe_references.py#L4

Please note that I didn't take the time to actually build and test your project, so you will need to test, but in theory regarding `ConanInstall.cmake`:
  * `  conan_check(VERSION 1.0.0 REQUIRED)` this most likely isn't enough. Bincrafters and CCI recipes use features from much later versions. I believe you should increase this to at least `1.18.0` as this is the first version which doesn't require `user/channel` anymore and therefore is the first version which allows to consume CCI packages and you use them implicitly already via Bincrafters packages. Some packages also use features from 1.20.0, so the minimum version might be even higher.... 
  * `OpenSSL/1.1.0g@conan/stable` -> `openssl/1.1.0l` (or openssl/1.1.1d if you can upgrade; 1.1.0 will be end-of-life at the end of the year aka in 2 weeks)
  * `jsoncpp/1.8.4@theirix/stable` -> `jsoncpp/1.9.2`
  * `zlib/1.2.11@conan/stable` -> `zlib/1.2.11`
  * `fmt/5.2.1@bincrafters/stable` -> `fmt/5.3.0` (or fmt/6.0.0 if you want/can upgrade)
  * `sqlite3/3.27.2@bincrafters/stable` -> `sqlite3/3.29.0`
  * `gtest/1.8.1@bincrafters/stable` -> `gtest/1.8.1`

**Comment by jmarrec** [comment]
Thanks for taking the time to look at it and suggest the appropriate packages. I'll make the leap and report back any problems I found (or lack thereof, one can hope)

**Comment by jmarrec** [comment]
Is is worth opening issues for recipes aren't at the latest version? I don't want to open a dozen issues if that's going to be useless, it'd be a waste of everybody's time. Here's the first one I encountered:

```
ERROR: Conflict in ruby_installer/2.5.5@bincrafters/stable
    Requirement zlib/1.2.11@conan/stable conflicts with already defined zlib/1.2.11
    To change it, override it in your base requirements
```

https://github.com/bincrafters/conan-ruby_installer/blob/stable/2.5.5/conanfile.py#L33

**Comment by Croydon** [comment]
Let's just keep it in this issue for now

The newest `testing/` branch is auto-updated by our bincrafters-conventions tool, `stable/` branches need human interaction. Older versions of recipes aren't maintained in most cases, but we can make smaller updates on request

For this kind of migration task it is often enough to create a pull request from `testing/` -> `stable/` if it is the newest version and the convention update didn't break the builds.

**Comment by Croydon** [comment]
Is there anything else to do?

**Comment by jmarrec** [comment]
Good to go now
