### ISSUE TITLE
Upgrade 'abseil' package

### ISSUE THREAD

**Issue by bfierz** [bincrafters/community#107]
### Upgrade version and build-system for abseil

I've created an update to for the conan-abseil package. Besides fixing the missing *.lib files, I've chained the build system to cmake. You can find the a branch of my fork here:
https://github.com/bfierz/conan-abseil/tree/replace-bazel-with-cmake

How can I contribute these changes back? I'm happy to apply further changes to comply to the guidelines.

**Comment by solvingj** [comment]
Hi @bfierz thanks for the suggestion and contribution!!

I was actually just starting to work on updating our Java/Bazel/Abseil packages. 

After looking at the current state of the Cmake builds, I feel comfortable switching over to it now.  It's still experimental, but officially supported, and so I am confident it will be at least as reliable as the bazel build for us, because bazel has it's own set of challenges. 

If you don't mind, I'll just go through your current version and cherry pick the changes, while also merging in recent bincrafters template changes. I'll keep you posted.

**Comment by solvingj** [comment]
On the surface, we need to try to avoid the cctz thing.  Need to try to package it separately: 

https://github.com/google/cctz/releases

Looks like it's got an internally supported cmake file, doesn't look bad. We shoudl be able to do it.

**Comment by solvingj** [comment]
I got it 95% of the way there, just need someone to make shared build work. 
https://ci.appveyor.com/project/BinCrafters/conan-cctz

**Comment by solvingj** [comment]
Ok, i've made the switch successfully, and it builds on my machine: 
https://github.com/bincrafters/conan-abseil/tree/testing/20180102

We'll see what happens with the CI, but it's very likely to fail until we get cctz working as a shared lib. 

If cctz can't be built as a shared library, then we just need to remove the option and update the CI for it.

**Comment by bfierz** [comment]
Cool. Thank you for working on the upgrade.
If I may suggest. A development branch in the repository would be nice, so people could open pull-requests.

Is thre a reason you want cctz build as a shared lib and not just as a static lib?

**Comment by solvingj** [comment]
Both cctz and abseil have testing branches. Which did you mean?

Well, by the makefile it looks like it supports being built as a shared library, at least on linux.  We like to support all the build variants people might want, and which are supported by upstream. We try very hard not to arbitrarily limit. 

https://github.com/google/cctz/blob/master/Makefile#L24

**Comment by bfierz** [comment]
I see. Building it as a shared lib makes sense.

In order to create a pull-request I need to be able to specify a target branch. Currently there are 3 specifically named branched corresponding to releases, but no generic branch from which a new version could be released. I could have opened a PR targeting the generic branch, instead of submitting my changes here. It's not a necessity, but would add some convenience.

**Comment by solvingj** [comment]
Oh, now I understand your point.  In the future, please just submit PR's to the most recent `/testing` branch.

**Comment by bfierz** [comment]
Ok, thank you very much.

I guess you've noticed it already, but there is a mismatch in the branch name and the version in the conanfile.py (which appveyor does not seem to like).

**Comment by solvingj** [comment]
After working with the upstream maintainer on a few items, we now have a reasonable package for `cctz/2.2` .  We've now updated the abseil package to depend on the cctz package properly, and the package should be ready for consumption after the CI finishes.  We're excited to have you test the package, so let us know if you experience issues.
