### ISSUE TITLE
vorbis - shared library build - so files should be symlinks

### ISSUE THREAD

**Issue by solvingj** [bincrafters/community#1071]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: vorbis/1.3.6
  * Operating System+version: Linux All, Probably macOS also
  * Compiler+version: GCC All + Clang All

### Steps to reproduce (Include if Applicable)

The issue is visible in the manifest, or by looking at the tarball, for any shared linux build:  

https://bintray.com/bincrafters/public-conan/download_file?file_path=bincrafters%2Fvorbis%2F1.3.6%2Fstable%2F0%2Fpackage%2Feda80dc8fb2119b4f00e52c60b766d4eaa9dee8b%2F0%2Fconanmanifest.txt

```
1565386019
FindVORBIS.cmake: 57896077927ba239c813a6ca349066f9
conaninfo.txt: ce103bc2cc2260a1b233791ac360a05d
include/vorbis/Makefile.am: e34448fe35358c4439e74cc00138df44
include/vorbis/codec.h: 2f6228c701eb9476dc2ccec4f2bb5e9c
include/vorbis/vorbisenc.h: 6902bd5cefe9f9f2687c6b872a90a387
include/vorbis/vorbisfile.h: 570d87df0d08fbf58ef17b8e9a21b63d
lib/libvorbis.so: 8bcb840446042c5856f70c678cf711e2
lib/libvorbis.so.0.4.8: 8bcb840446042c5856f70c678cf711e2
lib/libvorbisenc.so: d553483d840cde9c49e4fd7b0d64baa8
lib/libvorbisenc.so.2.0.11: d553483d840cde9c49e4fd7b0d64baa8
lib/libvorbisfile.so: fcc846f4c4fb647a26584d9e4d7cb06d
lib/libvorbisfile.so.3.3.7: fcc846f4c4fb647a26584d9e4d7cb06d
lib/pkgconfig/vorbis.pc: 4c6ef6ee9633a1ded973d6e22ed4753b
lib/pkgconfig/vorbisenc.pc: 025145726231dfdc9fa4d228b75ab09b
lib/pkgconfig/vorbisfile.pc: 7274079921f1b3cf6dfe5f14fb14f989
licenses/COPYING: 70c7063491d2d9f76a098d62ed5134f1
```

We can see that both `libvorbis.so` and `libvorbis.so.0.4.8` have the same hash, indicating identical contents.  The former should be a symlink.  The same is true for all the binaries created. 

This does actually create problems. 

I haven't looked at the root cause, but I believe it's likely to be a misconfiguration in the upstream build system definition.  Probably will require either a patch, or manual creating of the symlinks if that is too much of a hack.

**Comment by solvingj** [comment]
It looks like we wrote the `package()` method manually for some reason, but the upstream CMake build system is very mature and does contain a fine-looking install method.  we should change our recipe to use cmake install.

**Comment by Croydon** [comment]
This recipe is now in the [Conan Center Index](https://github.com/conan-io/conan-center-index/).

Please migrate to the recipe version there. 
If this is still an issue, please create a new issue in the [Conan Center Index issue tracker](https://github.com/conan-io/conan-center-index/issues).

Thanks!
