### ISSUE TITLE
[xkbcommon] fail to build because libxcb fail to build

### ISSUE THREAD

**Issue by ledocc** [bincrafters/community#1072]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **xkbcommon/0.8.4**
  * Operating System+version: **Linux Debian 10**
  * Compiler+version: **gcc-8.2**
  * Docker image: **conanio/gcc8**
  * Conan version: **conan 1.21.0**
  * Python version: **Python 3.7.0**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=8
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]

### Steps to reproduce (Include if Applicable)
conan install xkbcommon/0.8.4@bincrafters/stable -b libxcb

### Logs (Include/Attach if Applicable)
...
  Used CFLAGS:
    CPPFLAGS............: -I/root/.conan/data/libxau/1.0.9/bincrafters/stable/package/a6d233a62376a43c9d8df8a2cee1ebe02626601a/include -I/root/.conan/data/libxdmcp/1.1.3/bincrafters/stable/package/fabdd3530af643298e6bcb227769ea6b1df90d6e/include -I/root/.conan/data/xorgproto/2019.1/bincrafters/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include -I/root/.conan/data/xproto/7.0.31/bincrafters/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include -DNDEBUG -D_GLIBCXX_USE_CXX11_ABI=0
    CFLAGS..............: -m64 -O3 -s -fPIC

  Installation:
    Prefix..............: /root/.conan/data/libxcb/1.13.1/bincrafters/stable/package/1f950197fa3d3e7c0fcae50d8d26716068f84b10

Making all in src
make[1]: Entering directory '/root/.conan/data/libxcb/1.13.1/bincrafters/stable/build/1f950197fa3d3e7c0fcae50d8d26716068f84b10/source_subfolder/src'
make[1]: *** No rule to make target '/home/conan/.conan/data/xcb-proto/1.13/bincrafters/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/share/xcb/', needed by 'xproto.c'.  Stop.
make[1]: Leaving directory '/root/.conan/data/libxcb/1.13.1/bincrafters/stable/build/1f950197fa3d3e7c0fcae50d8d26716068f84b10/source_subfolder/src'
Makefile:792: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
libxcb/1.13.1@bincrafters/stable: 
libxcb/1.13.1@bincrafters/stable: ERROR: Package '1f950197fa3d3e7c0fcae50d8d26716068f84b10' build failed
libxcb/1.13.1@bincrafters/stable: WARN: Build folder /root/.conan/data/libxcb/1.13.1/bincrafters/stable/build/1f950197fa3d3e7c0fcae50d8d26716068f84b10
ERROR: 
        ConanException: Error 2 while executing make -j12

xcb-proto.pc have 
`prefix=/home/conan/.conan/data/xcb-proto/1.13/bincrafters/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9`
instead of
`prefix=/root/.conan/data/xcb-proto/1.13/bincrafters/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9`

To solve this, conan-xkbcommon copy .pc files in build folder then replace prefix by the good one. But libxcb don't do that, and the repository is archived so I can't fix it.

**Comment by ericLemanissier** [comment]
All x11 recipes are generated from this repo https://github.com/bincrafters/conan-x11
They are using the "native" pkgconfig files (as opposed to the conan generated ones). Maybe it's possible to migrate this to pkgconfig generator ? It could be problematic if some packages need to generate several files (not supported by conan yet)
I'd say copying the .pc files and patching the prefix has higher probability of success

**Comment by ledocc** [comment]
Hi @ericLemanissier, thanks for the tips, I will implement a patch for conan-x11 soon.
Regards

**Comment by ledocc** [comment]
[MR](https://github.com/bincrafters/conan-x11/pull/6) done

**Comment by Croydon** [comment]
Pull request is merged. Is there more to do?

**Comment by ledocc** [comment]
All work fine on my side, I close this issue. Thanks you.
