### ISSUE TITLE
[openssl 1.1.1d] build fails on Android crossbuild

### ISSUE THREAD

**Issue by dmn-star** [bincrafters/community#1076]
### Description of Problem, Request, or Question

Build fails with the following errors:

 ${LDCMD:-/Users/dmn/.conan/data/android_ndk_installer/r20/bincrafters/stable/package/96a307d747235b0e7df54f0118d5acaed00b63c5/toolchains/llvm/prebuilt/darwin-x86_64/bin/x86_64-linux-android21-clang} -pthread -m64 -O3 --sysroot=/Users/dmn/.conan/data/android_ndk_installer/r20/bincrafters/stable/package/96a307d747235b0e7df54f0118d5acaed00b63c5/toolchains/llvm/prebuilt/darwin-x86_64/sysroot -Wa,--noexecstack -Qunused-arguments -Wall -O3 -fPIC -L. -L/Users/dmn/.conan/data/zlib/1.2.11/_/_/package/3a891f9314bf3d09dca01a00a86e1fffd99aa8f1/lib -m64 --sysroot=/Users/dmn/.conan/data/android_ndk_installer/r20/bincrafters/stable/package/96a307d747235b0e7df54f0118d5acaed00b63c5/toolchains/llvm/prebuilt/darwin-x86_64/sysroot  \
  		-o test/buildtest_c_txt_db test/buildtest_txt_db.o \
  		 -lssl -lcrypto -ldl -pthread 
  ./libcrypto.a(e_aes.o):e_aes.c:function aesni_init_key: error: undefined reference to 'aesni_set_decrypt_key'
  ./libcrypto.a(e_aes.o):e_aes.c:function aesni_init_key: error: undefined reference to 'aesni_decrypt'
  ./libcrypto.a(e_aes.o):e_aes.c:function aesni_init_key: error: undefined reference to 'aesni_set_encrypt_key'
  ./libcrypto.a(e_aes.o):e_aes.c:function aesni_init_key: error: undefined reference to 'aesni_encrypt'
  ./libcrypto.a(e_aes.o):e_aes.c:function aesni_init_key: error: undefined reference to 'aesni_cbc_encrypt'
  ./libcrypto.a(e_aes.o):e_aes.c:function aesni_init_key: error: undefined reference to 'aesni_ctr32_encrypt_blocks'
  ./libcrypto.a(e_aes.o):e_aes.c:function aesni_cbc_cipher: error: undefined reference to 'aesni_cbc_encrypt'
  ./libcrypto.a(e_aes.o):e_aes.c:function aesni_ecb_cipher: error: undefined reference to 'aesni_ecb_encrypt'
  ./libcrypto.a(e_aes.o):e_aes.c:function aesni_gcm_init_key: error: undefined reference to 'aesni_set_encrypt_key'
  ./libcrypto.a(e_aes.o):e_aes.c:function aesni_gcm_init_key: error: undefined reference to 'aesni_encrypt'
  ./libcrypto.a(e_aes.o):e_aes.c:function aesni_gcm_init_key: error: undefined reference to 'aesni_ctr32_encrypt_blocks'
  ./libcrypto.a(e_aes.o):e_aes.c:function aes_gcm_cipher: error: undefined reference to 'aesni_ctr32_encrypt_blocks'
  ./libcrypto.a(e_aes.o):e_aes.c:function aes_gcm_cipher: error: undefined reference to 'gcm_ghash_avx'
  ./libcrypto.a(e_aes.o):e_aes.c:function aes_gcm_cipher: error: undefined reference to 'aesni_ctr32_encrypt_blocks'
  ./libcrypto.a(e_aes.o):e_aes.c:function aes_gcm_cipher: error: undefined reference to 'gcm_ghash_avx'
  ./libcrypto.a(e_aes.o):e_aes.c:function aes_gcm_cipher: error: undefined reference to 'gcm_ghash_avx'
  ./libcrypto.a(e_aes.o):e_aes.c:function aes_gcm_cipher: error: undefined reference to 'gcm_ghash_avx'
  ./libcrypto.a(e_aes.o):e_aes.c:function aes_gcm_cipher: error: undefined reference to 'aesni_gcm_encrypt'
  ./libcrypto.a(e_aes.o):e_aes.c:function aes_gcm_cipher: error: undefined reference to 'aesni_gcm_encrypt'
  ./libcrypto.a(e_aes.o):e_aes.c:function aes_gcm_cipher: error: undefined reference to 'aesni_gcm_decrypt'
  ./libcrypto.a(e_aes.o):e_aes.c:function aes_gcm_cipher: error: undefined reference to 'aesni_gcm_decrypt'
  ./libcrypto.a(e_aes.o):e_aes.c:function aesni_xts_init_key: error: undefined reference to 'aesni_set_encrypt_key'
  ./libcrypto.a(e_aes.o):e_aes.c:function aesni_xts_init_key: error: undefined reference to 'aesni_xts_encrypt'
  ./libcrypto.a(e_aes.o):e_aes.c:function aesni_xts_init_key: error: undefined reference to 'aesni_encrypt'
  ./libcrypto.a(e_aes.o):e_aes.c:function aesni_xts_init_key: error: undefined reference to 'aesni_set_decrypt_key'
  ./libcrypto.a(e_aes.o):e_aes.c:function aesni_xts_init_key: error: undefined reference to 'aesni_xts_decrypt'
  ./libcrypto.a(e_aes.o):e_aes.c:function aesni_xts_init_key: error: undefined reference to 'aesni_decrypt'
  ./libcrypto.a(e_aes.o):e_aes.c:function aesni_xts_init_key: error: undefined reference to 'aesni_set_encrypt_key'
  ./libcrypto.a(e_aes.o):e_aes.c:function aesni_xts_init_key: error: undefined reference to 'aesni_encrypt'
  ./libcrypto.a(e_aes.o):e_aes.c:function aesni_ccm_init_key: error: undefined reference to 'aesni_ccm64_decrypt_blocks'
  ./libcrypto.a(e_aes.o):e_aes.c:function aesni_ccm_init_key: error: undefined reference to 'aesni_ccm64_encrypt_blocks'
  ./libcrypto.a(e_aes.o):e_aes.c:function aesni_ocb_init_key: error: undefined reference to 'aesni_set_decrypt_key'
  ./libcrypto.a(e_aes.o):e_aes.c:function aesni_ocb_init_key: error: undefined reference to 'aesni_ocb_decrypt'
  ./libcrypto.a(e_aes.o):e_aes.c:function aesni_ocb_init_key: error: undefined reference to 'aesni_ocb_encrypt'
  ./libcrypto.a(e_aes.o):e_aes.c:function aesni_ocb_init_key: error: undefined reference to 'aesni_decrypt'

  openssl/1.1.1d: ERROR: Package '6b3baf6aff1ab96f1b9e4482e1d9a0210ea8085c' build failed
  openssl/1.1.1d: WARN: Build folder /Users/dmn/.conan/data/openssl/1.1.1d/_/_/build/6b3baf6aff1ab96f1b9e4482e1d9a0210ea8085c
  ERROR: openssl/1.1.1d: Error in build() method, line 525

### Package and Environment Details (include every applicable attribute)

- Package Name/Version: *openssl/1.1.1d*
- Operating System+version: *macOS Catalina 10.15.1*
- Compiler+version: *NDK r20 clang (8?)*
- Conan version: *Conan 1.20.5*
- Python version: *Python 3.7.4*

### Conan profile (output of conan profile show default or conan profile show <profile> if custom profile is in use)

conanfile.txt
[requires]
cpprestsdk/2.10.14@bincrafters/stable

[generators]
cmake

[options]
cpprestsdk:exclude_websockets = True

profile
[settings]
os_build=Macos
arch_build=x86_64

compiler=clang
compiler.version=8
compiler.libcxx=libc++
os=Android
os.api_level=21
arch=armv7
build_type=Release

[build_requires]
android_ndk_installer/r20@bincrafters/stable

### Steps to reproduce (Include if Applicable)

Install & cross build cpprestsdk with custom profile

**Comment by uilianries** [comment]
Hi @dmn-star ! OpenSSL is not a Bincrafters' package. Please, move this issue to https://github.com/conan-io/conan-center-index/issues

**Comment by dmn-star** [comment]
Yes, you are right.
