### ISSUE TITLE
[opus] 1.3.1 mingw build fail - opus_decoder.c:964: more undefined references to `__stack_chk_fail' follow

### ISSUE THREAD

**Issue by leyewen** [bincrafters/community#1077]
### Package and Environment Details
  * Package Name/Version: **opus/1.3.1**
  * Operating System+version: **Windows 10**
  * Compiler+version: **gcc-mingw-w64-8.1.0**
  * Docker image: **conanio/gcc8.1**
  * Conan version: **conan 1.21.0**
  * Python version: **Python 3.7.5**

### Conan profile
```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=gcc
compiler.cppstd=14
compiler.exception=seh
compiler.libcxx=libstdc++11
compiler.threads=posix
compiler.version=8.1
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
CONAN_CMAKE_GENERATOR=MinGW Makefiles
```

```
opencv:shared=True
ffmpeg:shared=True
opus:shared=True    # if set opus:shared=False, it build passed
```

### Steps to reproduce
When I build `opencv/4.1.1@conan/stable` with ffmpeg `opencv:ffmpeg=True`, with opus `opus:shared=True`, it fail in build `opus/1.3.1@bincrafters/stable`.
If with opus `opus:shared=False`, it will build passed.

It throws:
```
opus_decoder.c:964: more undefined references to `__stack_chk_fail' follow
collect2.exe: error: ld returned 1 exit status
mingw32-make.exe[2]: *** [source_subfolder\CMakeFiles\opus.dir\build.make:2438: bin/libopus.dll] Error 1
mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:93: source_subfolder/CMakeFiles/opus.dir/all] Error 2
mingw32-make.exe: *** [Makefile:129: all] Error 2
```

### Fixed method
I researched this problem. And found some solutions.
See
https://github.com/xiph/opus/issues/138
https://stackoverflow.com/questions/4492799/undefined-reference-to-stack-chk-fail
https://stackoverflow.com/questions/25230517/undefined-references-to-stack-chk-fail-during-pintos-installation

Please update modify the file `conanfile.py` to
project
https://github.com/bincrafters/conan-opus

`.conan\data\opus\1.3.1\bincrafters\stable\export\conanfile.py`
in line 52 add protector fixed:

src:
```
    def build(self):
        ## line 52
        cmake = self._configure_cmake()
        cmake.build()
```

add:
```
        ## mingw undefined references to `__stack_chk_fail'
        ## -fno-stack-protector/-fstack-protector
        if self.settings.os == "Windows" and self.settings.compiler != "Visual Studio":
            if 'LDFLAGS' in os.environ:
                os.environ['LDFLAGS'] = os.environ['LDFLAGS'] + ' -fstack-protector'
            else:
                os.environ['LDFLAGS'] = '-fstack-protector'
```
And it build passed.

### Logs

> [ 98%] Building C object source_subfolder/CMakeFiles/opus.dir/silk/x86/VAD_sse4_1.c.obj
> [ 99%] Building C object source_subfolder/CMakeFiles/opus.dir/silk/x86/VQ_WMat_EC_sse4_1.c.obj
> [100%] Linking C shared library ..\bin\libopus.dll
> CMakeFiles\opus.dir/objects.a(opus_decoder.c.obj): In function `opus_decoder_get_size':
> C:/Users/Home/.conan/data/opus/1.3.1/bincrafters/stable/build/9e3762944ae8f4cc8b7bd27c3e59996e1e3a0709/source_subfolder/src/opus_decoder.c:114: undefined reference to `__stack_chk_fail'
> CMakeFiles\opus.dir/objects.a(opus_decoder.c.obj): In function `opus_decoder_init':
> C:/Users/Home/.conan/data/opus/1.3.1/bincrafters/stable/build/9e3762944ae8f4cc8b7bd27c3e59996e1e3a0709/source_subfolder/src/opus_decoder.c:157: undefined reference to `__stack_chk_fail'
> CMakeFiles\opus.dir/objects.a(opus_decoder.c.obj): In function `opus_decode_frame':
> C:/Users/Home/.conan/data/opus/1.3.1/bincrafters/stable/build/9e3762944ae8f4cc8b7bd27c3e59996e1e3a0709/source_subfolder/src/opus_decoder.c:624: undefined reference to `__stack_chk_fail'
> CMakeFiles\opus.dir/objects.a(opus_decoder.c.obj): In function `opus_decode_native':
> C:/Users/Home/.conan/data/opus/1.3.1/bincrafters/stable/build/9e3762944ae8f4cc8b7bd27c3e59996e1e3a0709/source_subfolder/src/opus_decoder.c:738: undefined reference to `__stack_chk_fail'
> CMakeFiles\opus.dir/objects.a(opus_decoder.c.obj): In function `opus_decode':
> C:/Users/Home/.conan/data/opus/1.3.1/bincrafters/stable/build/9e3762944ae8f4cc8b7bd27c3e59996e1e3a0709/source_subfolder/src/opus_decoder.c:821: undefined reference to `__stack_chk_fail'
> CMakeFiles\opus.dir/objects.a(opus_decoder.c.obj):C:/Users/Home/.conan/data/opus/1.3.1/bincrafters/stable/build/9e3762944ae8f4cc8b7bd27c3e59996e1e3a0709/source_subfolder/src/opus_decoder.c:964: more undefined references to `__stack_chk_fail' follow
> collect2.exe: error: ld returned 1 exit status
> mingw32-make.exe[2]: *** [source_subfolder\CMakeFiles\opus.dir\build.make:2438: bin/libopus.dll] Error 1
> mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:93: source_subfolder/CMakeFiles/opus.dir/all] Error 2
> mingw32-make.exe: *** [Makefile:129: all] Error 2
> opus/1.3.1@bincrafters/stable: 
> opus/1.3.1@bincrafters/stable: ERROR: Package '9e3762944ae8f4cc8b7bd27c3e59996e1e3a0709' build failed
> opus/1.3.1@bincrafters/stable: WARN: Build folder C:\Users\Home\.conan\data\opus\1.3.1\bincrafters\stable\build\9e3762944ae8f4cc8b7bd27c3e59996e1e3a0709
> ERROR: opus/1.3.1@bincrafters/stable: Error in build() method, line 54
> 	cmake.build()
> 	ConanException: Error 2 while executing cmake --build C:\Users\Home\.conan\data\opus\1.3.1\bincrafters\stable\build\9e3762944ae8f4cc8b7bd27c3e59996e1e3a0709 -- -j4
>

**Comment by ericLemanissier** [comment]
it works on my machine. Is this problem solved by using the configuration you described in https://github.com/bincrafters/community/issues/1074#issuecomment-571470594 ?

**Comment by leyewen** [comment]
Not working in `mingw` only environment, toolchain `x86_64-w64-mingw32` due to same error.
It's mingw build bug.

**Comment by Croydon** [comment]
This recipe is now in the [Conan Center Index](https://github.com/conan-io/conan-center-index/).

Please migrate to the recipe version there. 
If this is still an issue, please create a new issue in the [Conan Center Index issue tracker](https://github.com/conan-io/conan-center-index/issues).

Thanks!
