### ISSUE TITLE
[qt] Linker error for Qt5Network.dll while building on Windows

### ISSUE THREAD

**Issue by FMeinicke** [bincrafters/community#1079]
When I'm trying to build qt/5.13.2 I'm getting a weird linker error (`ld returned 5 exit status`). Googling around, I found that this might be related to some of the linker flags (`-Wl,-s,--relax,--gc-section`, See [this](https://stackoverflow.com/a/45107167) StackOverflow answer). Unfortunately, the complete command-line call is not shown while building (it only says "compiling" or "linking"), so I can't tell if these flags are actually the cause. 

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.13.2**
  * Operating System+version: **Windows 10**
  * Compiler+version: **gcc-7.3 (MinGW)**
  * Conan version: **conan 1.21.0**
  * Python version: **Python 3.7.4**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
> conan profile show .conan\profiles\msys2
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=7.3
os=Windows
os_build=Windows
[options]
[build_requires]
libpq/11.5: msys2_installer/latest@bincrafters/stable
openssl/1.1.1d: msys2_installer/latest@bincrafters/stable
nasm/2.14: msys2_installer/latest@bincrafters/stable
[env]
CC=C:\Qt\Tools\mingw730_64\bin\gcc.exe
CXX=C:\Qt\Tools\mingw730_64\bin\g++.exe
```

### Steps to reproduce (Include if Applicable)
```
conan install qt/5.13.2@bincrafters/stable -o GUI=False -o widgets=False -pr .conan\profiles\msys2 -b missing
```

### Logs (Include/Attach if Applicable)

```
...
linking ../../lib/Qt5Network.dll
collect2.exe: error: ld returned 5 exit status
mingw32-make[4]: *** [Makefile.Release:540: ../../lib/Qt5Network.dll] Error 1
mingw32-make[4]: Leaving directory 'C:/.conan/f2138b/1/qtbase/src/network'
mingw32-make[3]: *** [Makefile:38: release] Error 2
mingw32-make[3]: Leaving directory 'C:/.conan/f2138b/1/qtbase/src/network'
mingw32-make[2]: *** [Makefile:262: sub-network-make_first] Error 2
mingw32-make[2]: Leaving directory 'C:/.conan/f2138b/1/qtbase/src'
mingw32-make[1]: *** [Makefile:47: sub-src-make_first] Error 2
mingw32-make[1]: Leaving directory 'C:/.conan/f2138b/1/qtbase'
mingw32-make: *** [Makefile:43: module-qtbase-make_first] Error 2
qt/5.13.2@bincrafters/stable:
qt/5.13.2@bincrafters/stable: ERROR: Package '35d35d211f943d58d067515665fb7d9deead2a7e' build failed
qt/5.13.2@bincrafters/stable: WARN: Build folder C:\.conan\f2138b\1
ERROR: qt/5.13.2@bincrafters/stable: Error in build() method, line 600
        self.run(make, run_environment=True)
        ConanException: Error 2 while executing mingw32-make
```
See the complete log [here](https://github.com/bincrafters/community/files/3991739/qt5.12.3-build.log) (it was too long for GitHub to post it directly in the issue description).

**Comment by ericLemanissier** [comment]
can you replace all the references to `msys2_installer/latest@bincrafters/stable`with `msys2/20190524` and retry ?

**Comment by FMeinicke** [comment]
If I replace `msys2_installer/latest@bincrafters/stable` with `msys2/20190524` I get the same error as I described [here](https://github.com/conan-io/conan-center-index/issues/511#issuecomment-567518598).

BTW: I was able to build qt/5.13.2 successfully on another machine. At the point where Qt5Network was linked a message box popped up, saying something like "ld.exe is not working anymore" with two options: Either close the program (which resulted in the same error as I described above) or debug the program. When I clicked on debug, another message showed up, saying there wasn't a suitable program found for debugging. I closed the message by clicking OK and the build process continued. For some reason, the linker was then magically able to link Qt5Network.dll.  
I don't have any explanation for that behaviour, nor do I know, why on one machine I get the error message popup and on another I don't - but maybe this information is helpful, anyway.

**Comment by ericLemanissier** [comment]
this error should not happen when you call `conan install qt/5.13.2@bincrafters/stable -o GUI=False -o widgets=False -pr .conan\profiles\msys2 -b missing`, because it should reuse 7Zip binaries from bintray, instead of trying to build it.

**Comment by FMeinicke** [comment]
Ok, so I ran the command again but it still fails when linking Qt5Network.dll. 
See the build log [here](https://github.com/bincrafters/community/files/3995469/qt5.13.2-build2.log).

You were right, however, about the prebuilt binaries. I removed all packages before building qt again. Maybe the 7zip package was corrupted because I attempted to build it from source before.

**Comment by ericLemanissier** [comment]
I cannot reproduce this crash on my machine. Is it possible for you to try with qt 5.14.0 ?
Also, could you please try with the compiler provided by `mingw_installer` package ? you simply need to add 
```
[settings]
compiler.exception=seh
compiler.threads=posix
[build_requires]
mingw_installer/1.0@conan/stable
```
to your profile, and remove the `CC` and `CXX` lines from the `[env]` section. Then make sure you rebuild all the packages from sources (bzip2, double-conversion, libpq, openssl, pcre2, sqlite3 and zlib). you can continue to reuse binaries for msys2, 7zip and mingw_installer.

**Comment by FMeinicke** [comment]
Thanks for your suggestion to try with the compiler provided by `mingw_installer`. This worked perfectly. No problems during the build whatsoever. I am not averse to using qt 5.14.0 but since it works now with the help of the `mingw_installer` package I'm going to leave it at that.

Thanks again for all your help 😄
