### ISSUE TITLE
Add optional-lite repo to bincrafters' CI

### ISSUE THREAD

**Issue by jgsogo** [bincrafters/community#108]
I have created [this repo](https://github.com/bincrafters/conan-optional-lite) for optional-lite, need to enable CI for it. I think everything will work (windows, linux and macos).

Tasks:
 * [ ] Enable CI
 * [ ] Update badges
 * [ ] Add credentials for bintray
 * [ ] Create stable branch

**Comment by jgsogo** [comment]
Notifying @solvingj, @uilianries, and @grafikrobot as suggested in docs.

**Comment by solvingj** [comment]
Done, but since there seems to be a collection of related packages already done below, so it would be best for us to try to help the whole collection make it to Conan Center, rather than duplicate the work. 

https://bintray.com/agauniyal/nonstd-lite
