### ISSUE TITLE
glib can not be installed on Windows 10

### ISSUE THREAD

**Issue by altairwei** [bincrafters/community#1083]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **glib/2.58.3**
  * Operating System+version: **Windows 10**
  * Compiler+version: **Visual Studio 15**
  * Conan version: **conan 1.19.2**
  * Python version: **Python 3.7.3**

### Conan profile

```ini
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=15
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

```shell
conan install glib/2.58.3@bincrafters/stable
```

### Logs (Include/Attach if Applicable)

```shell
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=15
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

Installing package: glib/2.58.3@bincrafters/stable
Requirements
    bzip2/1.0.8 from 'conan-center' - Cache
    gettext/0.20.1@bincrafters/stable from 'bincrafters' - Cache
    glib/2.58.3@bincrafters/stable from 'conan-center' - Cache
    libelf/0.8.13 from 'conan-center' - Cache
    libffi/3.2.1 from 'conan-center' - Cache
    libiconv/1.15 from 'conan-center' - Cache
    libxml2/2.9.9 from 'conan-center' - Cache
    pcre/8.41 from 'conan-center' - Cache
    zlib/1.2.11 from 'conan-center' - Cache
Packages
    bzip2/1.0.8:5be2b7a2110ec8acdbf9a1cea9de5d60747edb34 - Download
    gettext/0.20.1@bincrafters/stable:a9774aed154c59c28dd4265225e420d11b83de50 - Download
    glib/2.58.3@bincrafters/stable:1102e64ce163f61dc359844a682180a176d2ff8c - Download
    libelf/0.8.13:6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7 - Download
    libffi/3.2.1:6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7 - Download
    libiconv/1.15:6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7 - Download
    libxml2/2.9.9:7290a063dd51fa46e746a28f1ebe96773b4d565b - Download
    pcre/8.41:20fc3dfce989c458ac2372442673140ea8028c06 - Download
    zlib/1.2.11:6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7 - Download

bzip2/1.0.8: Retrieving package 5be2b7a2110ec8acdbf9a1cea9de5d60747edb34 from remote 'conan-center' 
Downloading conanmanifest.txt: 100%|##########| 254/254 [00:00<00:00, 51.0kB/s]
Downloading conaninfo.txt: 100%|##########| 490/490 [00:00<00:00, 161kB/s]
Downloading conan_package.tgz: 100%|##########| 86.4k/86.4k [00:01<00:00, 65.7kB/s]
Decompressing conan_package.tgz: 100%|##########| 86.4k/86.4k [00:00<00:00, 903kB/s]
bzip2/1.0.8: Package installed 5be2b7a2110ec8acdbf9a1cea9de5d60747edb34
bzip2/1.0.8: Downloaded package revision 0
ERROR: bzip2/1.0.8: Error in package_info() method, line 57
        self.cpp_info.names["pkg_config"] = "bzip2"
        TypeError: '_CppInfo' object does not support item assignment
```

---

I guess the problem is caused by the package `libffi/3.2.1@_/_` of conan center. The conanfile.py of `bincrafters/conan-glib` did not specify owner and channel of `libffi/3.2.1`, therefore `libffi/3.2.1@_/_` was installed instead of `libffi/3.2.1@bincrafters/stable`. I don't know what the user `_` is, but it may be the cause of the problem.

**Comment by ericLemanissier** [comment]
you just need to update conan to 1.21.0, because bzip2 recipe requires this feature: `Allow setting different cpp_info name for each generator that supports that property using the new cpp_info.names[“generator_name”] property. `

**Comment by altairwei** [comment]
> you just need to update conan to 1.21.0, because bzip2 recipe requires this feature: `Allow setting different cpp_info name for each generator that supports that property using the new cpp_info.names[“generator_name”] property. `
> 
> For your information, packages hosted on Conan Center Index don't have owner/channel, so they are sometimes displayed as _/_. more information on https://github.com/conan-io/conan-center-index/wiki

Thank you!
