### ISSUE TITLE
Upstream Update: msgpack 3.2.1

### ISSUE THREAD

**Issue by Lihis** [bincrafters/community#1084]
### Package Details
  * Package Name: **msgpack**
  * Latest available Version: **3.2.1**

The above mentioned version is newly released by the upstream project and not yet available within Bincrafters. Please add this version.

https://github.com/msgpack/msgpack-c/releases/tag/cpp-3.2.1

**Comment by uilianries** [comment]
Done: https://github.com/bincrafters/conan-msgpack/tree/stable/3.2.1
