### ISSUE TITLE
[libx265] 3.0 file INSTALL cannot find bin/x265.pdb

### ISSUE THREAD

**Issue by leyewen** [bincrafters/community#1085]
### Package and Environment Details
  * Package Name/Version: **libx265/3.0**
  * Operating System+version: **Windows 10**
  * Compiler+version: **gcc-mingw-w64-8.1.0**
  * Docker image: **conanio/gcc8.1**
  * Conan version: **conan 1.21.0**
  * Python version: **Python 3.7.5**

### Conan profile
```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=gcc
compiler.cppstd=14
compiler.exception=seh
compiler.libcxx=libstdc++11
compiler.threads=posix
compiler.version=8.1
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
CONAN_CMAKE_GENERATOR=MinGW Makefiles
```

```
[requires]
libx265/3.0@bincrafters/stable
```

### Steps to reproduce
add package `libx265/3.0@bincrafters/stable` to build.
fail in file INSTALL cannot find bin/x265.pdb:

```
CMake Error at sources/source/cmake_install.cmake:48 (file):
  file INSTALL cannot find
  "C:/Users/Home/.conan/data/libx265/3.0/bincrafters/stable/build/e82f74c25b82d272dbcd1630371590cd62192d65/bin/x265.pdb".
Call Stack (most recent call first):
  cmake_install.cmake:37 (include)


mingw32-make.exe: *** [Makefile:73: install] Error 1
```

### Fixed method
I search file `x265.pdb` in all build and sources, it can't be found (not exist the file).
Just need to disable install pdb, remove install `libx265.pdb` code in `CMakeLists.txt`.

like:
https://github.com/microsoft/vcpkg/blob/master/ports/x265/disable-install-pdb.patch

`.conan\data\libx265\3.0\bincrafters\stable\source\sources\source\CMakeLists.txt`
in line 560
```
if((WIN32 AND ENABLE_CLI) OR (WIN32 AND ENABLE_SHARED))
    if(MSVC_IDE)
        # install(FILES "${PROJECT_BINARY_DIR}/Debug/x265.pdb" DESTINATION ${BIN_INSTALL_DIR} CONFIGURATIONS Debug)
        # install(FILES "${PROJECT_BINARY_DIR}/RelWithDebInfo/x265.pdb" DESTINATION ${BIN_INSTALL_DIR} CONFIGURATIONS RelWithDebInfo)
        install(FILES "${PROJECT_BINARY_DIR}/Debug/libx265.pdb" DESTINATION ${BIN_INSTALL_DIR} CONFIGURATIONS Debug OPTIONAL NAMELINK_ONLY)
        install(FILES "${PROJECT_BINARY_DIR}/RelWithDebInfo/libx265.pdb" DESTINATION ${BIN_INSTALL_DIR} CONFIGURATIONS RelWithDebInfo OPTIONAL NAMELINK_ONLY)
    else()
        # install(FILES "${PROJECT_BINARY_DIR}/x265.pdb" DESTINATION ${BIN_INSTALL_DIR} CONFIGURATIONS Debug)
        # install(FILES "${PROJECT_BINARY_DIR}/x265.pdb" DESTINATION ${BIN_INSTALL_DIR} CONFIGURATIONS RelWithDebInfo)
        install(FILES "${PROJECT_BINARY_DIR}/libx265.pdb" DESTINATION ${BIN_INSTALL_DIR} CONFIGURATIONS Debug OPTIONAL NAMELINK_ONLY)
        install(FILES "${PROJECT_BINARY_DIR}/libx265.pdb" DESTINATION ${BIN_INSTALL_DIR} CONFIGURATIONS RelWithDebInfo OPTIONAL NAMELINK_ONLY)
    endif()
endif()
```

**or**
`.conan\data\libx265\3.0\bincrafters\stable\export\conanfile.py`
in line 40
```
            # file INSTALL cannot find bin/x265.pdb
            tools.replace_in_file(os.path.join('sources', 'source', 'CMakeLists.txt'),
                                  'install(FILES "${PROJECT_BINARY_DIR}/Debug/x265.pdb" DESTINATION ${BIN_INSTALL_DIR} CONFIGURATIONS Debug)',
                                  '# install(FILES "${PROJECT_BINARY_DIR}/Debug/x265.pdb" DESTINATION ${BIN_INSTALL_DIR} CONFIGURATIONS Debug)')
            tools.replace_in_file(os.path.join('sources', 'source', 'CMakeLists.txt'),
                                  'install(FILES "${PROJECT_BINARY_DIR}/RelWithDebInfo/x265.pdb" DESTINATION ${BIN_INSTALL_DIR} CONFIGURATIONS RelWithDebInfo)',
                                  '# install(FILES "${PROJECT_BINARY_DIR}/RelWithDebInfo/x265.pdb" DESTINATION ${BIN_INSTALL_DIR} CONFIGURATIONS RelWithDebInfo)')
            tools.replace_in_file(os.path.join('sources', 'source', 'CMakeLists.txt'),
                                  'install(FILES "${PROJECT_BINARY_DIR}/x265.pdb" DESTINATION ${BIN_INSTALL_DIR} CONFIGURATIONS Debug)',
                                  '# install(FILES "${PROJECT_BINARY_DIR}/x265.pdb" DESTINATION ${BIN_INSTALL_DIR} CONFIGURATIONS Debug)')
            tools.replace_in_file(os.path.join('sources', 'source', 'CMakeLists.txt'),
                                  'install(FILES "${PROJECT_BINARY_DIR}/x265.pdb" DESTINATION ${BIN_INSTALL_DIR} CONFIGURATIONS RelWithDebInfo)',
                                  '# install(FILES "${PROJECT_BINARY_DIR}/x265.pdb" DESTINATION ${BIN_INSTALL_DIR} CONFIGURATIONS RelWithDebInfo)')
```

build pretty.

### Logs

> [ 98%] Building CXX object sources/source/CMakeFiles/cli.dir/x265.cpp.obj
> [100%] Linking CXX executable ..\..\bin\x265.exe
> [100%] Built target cli
> [ 20%] Built target encoder
> [ 83%] Built target common
> [ 84%] Built target x265-static
> [ 87%] Built target x265-shared
> [100%] Built target cli
> Install the project...
> -- Install configuration: "Debug"
> -- Installing: C:/Users/Home/.conan/data/libx265/3.0/bincrafters/stable/package/e82f74c25b82d272dbcd1630371590cd62192d65/lib/libx265.a
> -- Installing: C:/Users/Home/.conan/data/libx265/3.0/bincrafters/stable/package/e82f74c25b82d272dbcd1630371590cd62192d65/include/x265.h
> -- Installing: C:/Users/Home/.conan/data/libx265/3.0/bincrafters/stable/package/e82f74c25b82d272dbcd1630371590cd62192d65/include/x265_config.h
> CMake Error at sources/source/cmake_install.cmake:48 (file):
>   file INSTALL cannot find
>   "C:/Users/Home/.conan/data/libx265/3.0/bincrafters/stable/build/e82f74c25b82d272dbcd1630371590cd62192d65/bin/x265.pdb".
> Call Stack (most recent call first):
>   cmake_install.cmake:37 (include)
> 
> 
> mingw32-make.exe: *** [Makefile:73: install] Error 1
> libx265/3.0@bincrafters/stable:
> libx265/3.0@bincrafters/stable: ERROR: Package 'e82f74c25b82d272dbcd1630371590cd62192d65' build failed
> libx265/3.0@bincrafters/stable: WARN: Build folder C:\Users\Home\.conan\data\libx265\3.0\bincrafters\stable\build\e82f74c25b82d272dbcd1630371590cd62192d65
> ERROR: libx265/3.0@bincrafters/stable: Error in build() method, line 36
> 	self.build_cmake()
> while calling 'build_cmake', line 66
> 	cmake.install()
> 	ConanException: Error 2 while executing cmake --build C:\Users\Home\.conan\data\libx265\3.0\bincrafters\stable\build\e82f74c25b82d272dbcd1630371590cd62192d65 --target install -- -j4
> 
>

**Comment by Croydon** [comment]
This recipe is now in the [Conan Center Index](https://github.com/conan-io/conan-center-index/).

In general, we don't package `pdb` files anymore https://github.com/conan-io/conan-center-index/wiki/Error-Knowledge-Base#kb-h017-pdb-files-not-allowed
