### ISSUE TITLE
[glew] Conan fails to install glew dependency

### ISSUE THREAD

**Issue by FernandoVelcic** [bincrafters/community#1087]
When I try to install glew to my project I've got the following errors:

conan install glew/2.1.0@bincrafters/stable
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

glew/2.1.0@bincrafters/stable: WARN: Package is corrupted, removing folder: C:\Users\fernando\.conan\data\glew\2.1.0\bincrafters\stable\package\3fb49604f9c2f729b85ba3115852006824e72cab
Installing package: glew/2.1.0@bincrafters/stable
Requirements
    glew/2.1.0@bincrafters/stable from 'conan-center' - Cache
Packages
    glew/2.1.0@bincrafters/stable:3fb49604f9c2f729b85ba3115852006824e72cab - Missing

glew/2.1.0@bincrafters/stable: WARN: Can't find a 'glew/2.1.0@bincrafters/stable' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=Release, compiler=Visual Studio, compiler.runtime=MD, compiler.version=16, os=Windows
- Options: shared=False
- Dependencies:
- Package ID: 3fb49604f9c2f729b85ba3115852006824e72cab

ERROR: Missing prebuilt package for 'glew/2.1.0@bincrafters/stable'
Try to build it from sources with "--build glew"
Or read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package"

**Comment by Croydon** [comment]
@FernandoVelcic This should be fixed as soon as this CI job finished: https://ci.appveyor.com/project/bincrafters/conan-glew/builds/29898898

Please try again then

**Comment by Croydon** [comment]
Actually there is a build problem for VS 2019 + Release https://ci.appveyor.com/project/bincrafters/conan-glew/build/job/oxwm2map4nonuc0e

**Comment by winterheart** [comment]
Any news about issue?
