### ISSUE TITLE
[openh264] mingw build make: x86_64-w64-mingw32-ar: Command not found

### ISSUE THREAD

**Issue by leyewen** [bincrafters/community#1089]
### Package and Environment Details
  * Package Name/Version: **openh264/1.7.0**
  * Operating System+version: **Windows 10**
  * Compiler+version: **gcc-mingw-w64-8.1.0**
  * Docker image: **conanio/gcc8.1**
  * Conan version: **conan 1.21.0**
  * Python version: **Python 3.7.5**

### Conan profile
```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=gcc
compiler.cppstd=14
compiler.exception=seh
compiler.libcxx=libstdc++11
compiler.threads=posix
compiler.version=8.1
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
CONAN_CMAKE_GENERATOR=MinGW Makefiles
```

```
[requires]
openh264/1.7.0@bincrafters/stable

[options]
# openh264
openh264:shared=True
```

### Steps to reproduce
add package `openh264/1.7.0@bincrafters/stable` to build.
It fail in mingw:

```
make: x86_64-w64-mingw32-ar: Command not found
```

### Fixed method
https://sourceforge.net/p/mingw-w64/mailman/message/29053757/
```
cd /mingw64/bin/
cp ar.exe to x86_64-w64-mingw32-ar.exe
```

build pretty.

I think it's cross-compiler settings did not recognize `ar.exe` (as `x86_64-w64-mingw32-ar.exe`) in mingw, maybe rewriting cross-compiler settings env (like opencv) would be better .

project
https://github.com/bincrafters/conan-openh264

### Logs

> nasm -DWIN64 -f win64 -I./codec/common/x86/   -o codec/processing/src/x86/denoisefilter.o codec/processing/src/x86/denoisefilter.asm
> nasm -DWIN64 -f win64 -I./codec/common/x86/   -o codec/processing/src/x86/downsample_bilinear.o codec/processing/src/x86/downsample_bilinear.asm
> nasm -DWIN64 -f win64 -I./codec/common/x86/   -o codec/processing/src/x86/vaa.o codec/processing/src/x86/vaa.asm
> x86_64-w64-mingw32-g++ -m64 -g -O3 -DNDEBUG -m64 -DX86_ASM -MMD -MP -DGENERATED_VERSION_HEADER -m64 -g -std=c++14 -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc  -I./codec/console/common/inc -c -o codec/console/common/src/read_config.o codec/console/common/src/read_config.cpp
> rm -f libcommon.a
> x86_64-w64-mingw32-g++ -m64 -g -O3 -DNDEBUG -m64 -DX86_ASM -MMD -MP -DGENERATED_VERSION_HEADER -m64 -g -std=c++14 -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc  -I./codec/decoder/core/inc -I./codec/decoder/plus/inc -c -o codec/decoder/plus/src/welsDecoderExt.o codec/decoder/plus/src/welsDecoderExt.cpp
> x86_64-w64-mingw32-ar cr libcommon.a codec/common/src/common_tables.o codec/common/src/copy_mb.o codec/common/src/cpu.o codec/common/src/crt_util_safe_x.o codec/common/src/deblocking_common.o codec/common/src/expand_pic.o codec/common/src/intra_pred_common.o codec/common/src/mc.o codec/common/src/memory_align.o codec/common/src/sad_common.o codec/common/src/utils.o codec/common/src/welsCodecTrace.o codec/common/src/WelsTaskThread.o codec/common/src/WelsThread.o codec/common/src/WelsThreadLib.o codec/common/src/WelsThreadPool.o codec/common/x86/cpuid.o codec/common/x86/dct.o codec/common/x86/deblock.o codec/common/x86/expand_picture.o codec/common/x86/intra_pred_com.o codec/common/x86/mb_copy.o codec/common/x86/mc_chroma.o codec/common/x86/mc_luma.o codec/common/x86/satd_sad.o codec/common/x86/vaa.o
> make: x86_64-w64-mingw32-ar: Command not found
> make: *** [codec/common/targets.mk:79: libcommon.a] Error 127
> make: *** Waiting for unfinished jobs....
> openh264/1.7.0@bincrafters/stable: ERROR: Package '40d7adf2c28a3324a316cd1f90822d82e34b2a27' build failed
> openh264/1.7.0@bincrafters/stable: WARN: Build folder C:\Users\Home\.conan\data\openh264\1.7.0\bincrafters\stable\build\40d7adf2c28a3324a316cd1f90822d82e34b2a27
> openh264/1.7.0@bincrafters/stable:
> ERROR: openh264/1.7.0@bincrafters/stable: Error in build() method, line 38
> 	self.build_configure()
> while calling 'build_configure', line 101
> 	env_build.make(args=args, target="libraries")
> 	ConanException: Error 2 while executing make libraries ARCH=x86_64 OS=mingw_nt -j4

**Comment by ericLemanissier** [comment]
Is this problem solved by using the configuration you described in https://github.com/bincrafters/community/issues/1074#issuecomment-571470594 ?

**Comment by leyewen** [comment]
use Cross-building toolchain `x86_64-w64-mingw32` in your profile can sloved too.

```
# Cross-building toolchain
# https://docs.conan.io/en/latest/systems_cross_building/cross_building.html
toolchain=x86_64-w64-mingw32
target_host=x86_64-w64-mingw32
cc_compiler=gcc
cxx_compiler=g++

[env]
CONAN_CMAKE_GENERATOR=MinGW Makefiles
CONAN_CMAKE_FIND_ROOT_PATH=$toolchain
CHOST=$target_host
# AR=$target_host-ar
AR=ar
# AS=$target_host-as
AS=as
# RANLIB=$target_host-ranlib
RANLIB=ranlib
CC=$target_host-$cc_compiler
CXX=$target_host-$cxx_compiler
# STRIP=$target_host-strip
STRIP=strip
# RC=$target_host-windres
RC=windres
```

**Comment by Croydon** [comment]
This recipe is now in the [Conan Center Index](https://github.com/conan-io/conan-center-index/).

Please migrate to the recipe version there. 
If this is still an issue, please create a new issue in the [Conan Center Index issue tracker](https://github.com/conan-io/conan-center-index/issues).

Thanks!
