### ISSUE TITLE
pkg_config name in glib

### ISSUE THREAD

**Issue by weatherhead99** [bincrafters/community#1090]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **glib/2.58.3**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **gcc-7.4**
  * Conan version: **Conan 1.21.0**
  * Python version: **Python 3.7.1**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=7
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]

### Steps to reproduce (Include if Applicable)
when building a package that consumes glib via pkg-config, the name it generally uses to find the pc file is "glib-2.0.pc", whereas when using conan's "pkg_config" generator, the generated name is "glib.pc". I believe this can be fixed via a simple addition of 

``` cpp_info.names["pkg_config"] = "glib-2.0" ```

in the package. Happy to submit patch for this

**Comment by ericLemanissier** [comment]
Glib actually uses several pkg-config files (gio-2.0.pc, gmodule-2.0.pc, gobject-2.0.pc, gthread-2.0.pc etc.)
As conan does not have yet a component feature (https://github.com/conan-io/conan/issues/5090), the pkg-config file generated from conan can only be a merge of all these. Providing a file with the same name as the upstream project but a different content would probably be misleading, but I have no strong opinion on this.

**Comment by Croydon** [comment]
This recipe is now in the [Conan Center Index](https://github.com/conan-io/conan-center-index/).

Please migrate to the recipe version there. 
If this is still an issue, please create a new issue in the [Conan Center Index issue tracker](https://github.com/conan-io/conan-center-index/issues).

Thanks!
