### ISSUE TITLE
Upstream Update: depot_tools_installer 20200107

### ISSUE THREAD

**Issue by Tymolc** [bincrafters/community#1092]
### Package Details
  * Package Name: depot_tools_installer
  * Latest available Version: commit 1961043388e63c48946322de077bebbb333fde6a 

There has been a lot of work upstream to improve Python3 compatibility of the depot_tools_installer and chromium itself (see https://chromium.googlesource.com/chromium/tools/depot_tools/+log).

Tested on macOS Catalina with python3, I was able to properly build and install crashpad with conan, using [this recipe](https://github.com/Tymolc/conan-depot_tools_installer/tree/testing/20200107). 
It seems like the upstream project is not yet completely done with the move to Python 3, though, so it's probably not yet enough to fix https://github.com/bincrafters/community/issues/943

**Comment by Tymolc** [comment]
Please note: Please feel free to pull [my branch](https://github.com/Tymolc/conan-depot_tools_installer/tree/testing/20200107) into the upstream repo.

**Comment by Croydon** [comment]
My plan was to wait with a next release until https://bugs.chromium.org/p/chromium/issues/detail?id=984182 is marked as done

Hopefully that won't be too long. After all that should be now a high priority...

**Comment by Tymolc** [comment]
Hm, alright. Looks like they have a lot of work to do still. 3/15 Tickets are done.

**Comment by Croydon** [comment]
Never mind, I just created a 2020-02-07 version

It doesn't seem like migrating to Python 3 is a strong priority for them, so it actually might take a long time...
