### ISSUE TITLE
Upstream Update: crashpad 20200107

### ISSUE THREAD

**Issue by Tymolc** [bincrafters/community#1093]
### Package Details
  * Package Name: crashpad
  * Latest available Version: use updated depot_tools_installer requirement, as described in https://github.com/bincrafters/community/issues/1092

The crashpad recipe should use the updated depot_tools_installer to be more compatible with Python3.

**Comment by Tymolc** [comment]
I'm happy to create an updated recipe for this as soon as #1092 is done

**Comment by reneme** [comment]
I'm in the process of [updating crashpad to the latest stable version](https://github.com/bincrafters/conan-crashpad/pulls/8) (i.e. the one deployed with Chrome 80). Unfortunately, CI [failed on Windows](https://ci.appveyor.com/project/bincrafters/conan-crashpad/builds/31232476). I assume, that depot tools is not yet there with Python 3. :(

**Comment by Tymolc** [comment]
The latest version seems to work well with Python 3. Closing

**Comment by Croydon** [comment]
For reference: we have now a 20200508 version
