### ISSUE TITLE
libvpx: Invalid setting 'Solaris' for Android build

### ISSUE THREAD

**Issue by Morkxy** [bincrafters/community#1095]
### Description of Problem, Request, or Question
Hi,
When i build ffmpeg for Android, the dependency libvpx failed with this error :
```
ERROR: libvpx/1.8.0@bincrafters/stable: Error in build() method, line 170
        env_build = self._configure_autotools()
while calling '_configure_autotools', line 153
        elif self.settings.os == 'Solaris':
        ConanException: Invalid setting 'Solaris' is not a valid 'settings.os' value.
Possible values are ['AIX', 'Android', 'Arduino', 'Emscripten', 'FreeBSD', 'Linux', 'Macos', 'Neutrino', 'SunOS', 'Windows', 'WindowsCE', 'WindowsStore', 'iOS', 'tvOS', 'watchOS']
Read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting"
```

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libvpx/1.8.0**
  * Operating System+version: **Linux Ubuntu 18.04***
  * Conan version: **Conan 1.21.0**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
include(default)
[settings]
arch=x86
build_type=Release
compiler=clang
compiler.libcxx=libc++
compiler.version=8
os=Android
os.api_level=21
[build_requires]
android_ndk_installer/r20@bincrafters/stable
[options]
[env]

### Steps to reproduce (Include if Applicable)
conan install --build missing libvpx/1.8.0@bincrafters/stable --profile Android_x86

### Logs (Include/Attach if Applicable)
```
libvpx/1.8.0@bincrafters/stable: Applying build-requirement: android_ndk_installer/r20@bincrafters/stable
libvpx/1.8.0@bincrafters/stable: Applying build-requirement: yasm_installer/1.3.0@bincrafters/stable
libvpx/1.8.0@bincrafters/stable: WARN: Build folder is dirty, removing it: /home/nico/.conan/data/libvpx/1.8.0/bincrafters/stable/build/2276d9cbea3b706003df95e9df1f1d64fa1eee67
libvpx/1.8.0@bincrafters/stable: Copying sources to build folder
libvpx/1.8.0@bincrafters/stable: Building your package in /home/nico/.conan/data/libvpx/1.8.0/bincrafters/stable/build/2276d9cbea3b706003df95e9df1f1d64fa1eee67
libvpx/1.8.0@bincrafters/stable: Generator txt created conanbuildinfo.txt
libvpx/1.8.0@bincrafters/stable: Calling build()
libvpx/1.8.0@bincrafters/stable:
libvpx/1.8.0@bincrafters/stable: ERROR: Package '2276d9cbea3b706003df95e9df1f1d64fa1eee67' build failed
libvpx/1.8.0@bincrafters/stable: WARN: Build folder /home/nico/.conan/data/libvpx/1.8.0/bincrafters/stable/build/2276d9cbea3b706003df95e9df1f1d64fa1eee67
ERROR: libvpx/1.8.0@bincrafters/stable: Error in build() method, line 170
        env_build = self._configure_autotools()
while calling '_configure_autotools', line 153
        elif self.settings.os == 'Solaris':
        ConanException: Invalid setting 'Solaris' is not a valid 'settings.os' value.
Possible values are ['AIX', 'Android', 'Arduino', 'Emscripten', 'FreeBSD', 'Linux', 'Macos', 'Neutrino', 'SunOS', 'Windows', 'WindowsCE', 'WindowsStore', 'iOS', 'tvOS', 'watchOS']
Read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting"
```

**Comment by Morkxy** [comment]
As suggested here :
 https://docs.conan.io/en/latest/reference/config_files/settings.yml.html

"The settings.yml file is not perfect nor definitive and surely incomplete. Please share any suggestion in the Conan issue tracker with any missing settings and values that could make sense for other users."

=> Solaris OS is missing from the list.

Why this package ("libvpx") can be published in bincrafters without this ?
And... why stop my Android build for a "solaris missing os" ? :D

**Comment by SSE4** [comment]
just add "Solaris" to your **settings.yml** would be enough to fix it
otherwise, you may change condition to `str(self.settings.os) == "Solaris"`, but that would be huge overkill for each recipe
settings.yml provide checks, so it's useful (e.g. we already had an error in recipes: "Solatis" vs "Solaris")

**Comment by Morkxy** [comment]
Yes ok,
Thank you SSE4 ;)
