### ISSUE TITLE
[request] flex/2.6.4 Clang 9

### ISSUE THREAD

**Issue by helmesjo** [bincrafters/community#1096]
### Package Details
  * Package Name/Version: **flex/2.6.4**

Missing prebuilt packages for GCC9 

### Required by
 * [thrift/0.13](https://travis-ci.com/bincrafters/conan-thrift/jobs/274462844#L833)

**Comment by Croydon** [comment]
Clang 9 is missing, not GCC 9 

I'm going to add it

**Comment by Croydon** [comment]
Fixed!

**Comment by helmesjo** [comment]
@Croydon Oh, sorry! Was getting tired I guess.. 😇
Thank you!
