### ISSUE TITLE
[libvpx] 1.8.0 mingw build Error: invalid register for .seh_savexmm vpx_dsp/x86/sad4d_avx512.c.o Error

### ISSUE THREAD

**Issue by leyewen** [bincrafters/community#1099]
### Package and Environment Details
  * Package Name/Version: **libvpx/1.8.0**
  * Operating System+version: **Windows 10**
  * Compiler+version: **gcc-mingw-w64-8.1.0 and msys2**
  * Docker image: **conanio/gcc8.1**
  * Conan version: **conan 1.21.0**
  * Python version: **Python 3.7.5**

### Conan profile
```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=gcc
compiler.cppstd=14
compiler.exception=seh
compiler.libcxx=libstdc++11
compiler.threads=posix
compiler.version=8.1
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
CONAN_CMAKE_GENERATOR=MinGW Makefiles
```

```
[requires]
libvpx/1.8.0@bincrafters/stable
```

### Steps to reproduce
use `msys2` and `mingw64` build, fail in:
```
libvpx/1.8.0@bincrafters/stable: C:\msys64\tmp\ccuqELT5.s:32: Error: invalid register for .seh_savexmm
libvpx/1.8.0@bincrafters/stable: make[1]: *** [Makefile:158: vpx_dsp/x86/sad4d_avx512.c.o] Error 1
```

### Fixed method
this question is related to two mingw-w64 bug reports:

(1) "Error: invalid register for .seh_savexmm"
#681 Assembler Error: invalid register for .seh_savexmm when compiling with
avx-512
https://sourceforge.net/p/mingw-w64/bugs/681/
see also:
Bug 65782 - Assembly failure (invalid register for .seh_savexmm) with -O3
-mavx512f on mingw-w64
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=65782

this can potentially be solved by adding the
"-fno-asynchronous-unwind-tables" as requested here:
https://stackoverflow.com/questions/43152633/invalid-register-for-seh-savexmm-in-cygwin

in line 167 (best)
```
        with tools.vcvars(self.settings) if self.settings.compiler == 'Visual Studio' else tools.no_op():
            env_build = AutoToolsBuildEnvironment(self, win_bash=win_bash)

            # is mingw, fixed: invalid register for .seh_savexmm, [Makefile:158: vpx_dsp/x86/sad4d_avx512.c.o] Error 1
            if self.settings.os == "Windows" and self.settings.compiler == 'gcc':
                self._autotools.flags.append('-fno-asynchronous-unwind-tables')
```

**or**

in line 166
```
        # is mingw, fixed: invalid register for .seh_savexmm, [Makefile:158: vpx_dsp/x86/sad4d_avx512.c.o] Error 1
        if self.settings.os == "Windows" and self.settings.compiler == 'gcc':
            args.append('--extra-cflags=-fno-asynchronous-unwind-tables')
```

And it build pretty.

### Logs

> libvpx/1.8.0@bincrafters/stable:     [CC] vpx_dsp/x86/sum_squares_sse2.c.o
> libvpx/1.8.0@bincrafters/stable:     [CC] vpx_dsp/x86/sad4d_avx2.c.o
> libvpx/1.8.0@bincrafters/stable:     [CC] vpx_dsp/x86/sad_avx2.c.o
> libvpx/1.8.0@bincrafters/stable:     [CC] vpx_dsp/x86/sad4d_avx512.c.o
> libvpx/1.8.0@bincrafters/stable:     [CC] vpx_dsp/variance.c.o
> libvpx/1.8.0@bincrafters/stable: C:\msys64\tmp\ccuqELT5.s: Assembler messages:
> libvpx/1.8.0@bincrafters/stable: C:\msys64\tmp\ccuqELT5.s:32: Error: invalid register for .seh_savexmm
> libvpx/1.8.0@bincrafters/stable: make[1]: *** [Makefile:158: vpx_dsp/x86/sad4d_avx512.c.o] Error 1
> libvpx/1.8.0@bincrafters/stable: make[1]: *** Waiting for unfinished jobs....
> libvpx/1.8.0@bincrafters/stable: make: *** [Makefile:17: .DEFAULT] Error 2
> libvpx/1.8.0@bincrafters/stable: ERROR: Package '2b8eea48ceb8a91c3e4fccdf69329fc3197c3506' build failed
> libvpx/1.8.0@bincrafters/stable: WARN: Build folder C:\Users\Home\.conan\data\libvpx\1.8.0\bincrafters\stable\build\2b8eea48ceb8a91c3e4fccdf69329fc3197c3506
> ERROR: libvpx/1.8.0@bincrafters/stable: Error in build() method, line 175
> 	env_build.make()
> 	ConanException: Error 2 while executing make -j4
> libvpx/1.8.0@bincrafters/stable: 
>

**Comment by Croydon** [comment]
This recipe is now in the [Conan Center Index](https://github.com/conan-io/conan-center-index/).

Please migrate to the recipe version there. 
If this is still an issue, please create a new issue in the [Conan Center Index issue tracker](https://github.com/conan-io/conan-center-index/issues).

Thanks!
