### ISSUE TITLE
boost_iostreams always uses static zlib

### ISSUE THREAD

**Issue by weatherhead99** [bincrafters/community#110]
### Description of Problem, Request, or Question
boost_iostreams always overrides zlib:shared to False, meaning it can't be used in any project which uses a shared zlib. Perhaps this is ultimately a question of 

### Package Details (Include if Applicable)
* Package Name/Version: **boost_iostreams/1.66.0@bincrafters/stable**
* Operating System: **Linux**
* Compiler+version: **gcc-4.8**

### Steps to reproduce (Include if Applicable)

create a recipe (conanfile.txt will do)

with requires:
boost_iostreams/1.66.0@bincrafters/stable 
and e.g. zlib/1.2.11@conan:shable

options:
zlib:shared = True

this will fail with 

ERROR: zlib/1.2.11@conan/stable: boost_iostreams/1.66.0@bincrafters/stable tried to change zlib/1.2.11@conan/stable option shared to False
but it was already assigned to True by Protobuf/3.5.1@inexorgame/stable

**Comment by solvingj** [comment]
just to confirm, you tried setting `-o zlib:shared=False` during `conan install` and conan still error'd due to the conflict?

**Comment by weatherhead99** [comment]
that's  correct - boost always uses static zlib, the recipe explicitly sets self.options["zlib"].shared = False.

**Comment by solvingj** [comment]
I have removed the following block of code and pushed to CI, which should completely resolve your issue.  Please re-open if you experience further issues. 

```
    def configure(self):	
        if self.options.use_bzip2:	
            self.options["bzip"].shared = False	
        if self.options.use_zlib:	
            self.options["zlib"].shared = False	
        if self.options.use_lzma:	
            self.options["lzma"].shared = False
```
