### ISSUE TITLE
[qt] The conan package for Qt should be modularized

### ISSUE THREAD

**Issue by mfurkanuslu** [bincrafters/community#1101]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.14.0**
### Description of your feature
Currently the package downloads [single/qt-everywhere-src-5.14.0.tar.xz](https://download.qt.io/official_releases/qt/5.14/5.14.0/single/qt-everywhere-src-5.14.0.tar.xz) file. But there are [submodules/{qtmodulename}-everywhere-src-5.14.0.tar.xz](https://download.qt.io/official_releases/qt/5.14/5.14.0/submodules/) files. Separating packages for each qt module and downloading sources for each module separately and managing module dependencies as conan package requirements is seemed to me as better approach.

**Comment by ericLemanissier** [comment]
You are right, the current situation is not perfect. The main blocker for modularization currently is qmake, because as far as I know, it can only find qt modules from a single centralized folder structure. Any modularization we could achive during the build phase would be defeated by the fact that in the end we would have to copy all libraries and include files in a single package folder.
Maybe you have a solution to this?

**Comment by mfurkanuslu** [comment]
We may patch qmake in the package.

**Comment by ericLemanissier** [comment]
Sure, we'd be glad to accept contributions on this, if they are somewhat reviewed by someone which knows qmake (ideally the maintainer of qmake). Also, I don't know if qt's cmake scripts have the same limitation

**Comment by mfurkanuslu** [comment]
> I don't know if qt's cmake scripts have the same limitation

They aren't.

**Comment by ericLemanissier** [comment]
@mfurkanuslu I just took a look at my current qt installation (5.14.0) and all the files `Qt5*****Config.cmake` have the following to find dependencies (this is from Qt5QmlConfig.cmake):
```
            find_package(Qt5${_module_dep}
                5.14.0 ${_Qt5Qml_FIND_VERSION_EXACT}
                ${_Qt5Qml_DEPENDENCIES_FIND_QUIET}
                ${_Qt5Qml_FIND_DEPENDENCIES_REQUIRED}
                PATHS "${CMAKE_CURRENT_LIST_DIR}/.." NO_DEFAULT_PATH
```
IIUC [cmake documentation](https://cmake.org/cmake/help/latest/command/find_package.html), the `NO_DEFAULT_PATH` forces cmake to search only in the `PATHS` argument, so it expects to find all the cmake files in a central folder. this is incompatible with conan's storage of packages.

**Comment by Dark-Passenger** [comment]
I believe with qt 6 (specifically https://github.com/qt/qtbase/commit/7bb91398f25cb2016c0558fd397b376f413e3e96#diff-251d177e3e7db921c05d14a06c2495601e4bb0e8ccfff429ac77fa6cd65786ec) we can now modularize the qt package.

**Comment by ericLemanissier** [comment]
Great ! Now we need to make a working recipe, which is still not the case, see build failures on https://github.com/bincrafters/conan-qt/tree/prerelease/6.0.0-beta2 and the bugreports I made
https://bugreports.qt.io/browse/QTBUG-87582
https://bugreports.qt.io/browse/QTBUG-87479
https://bugreports.qt.io/browse/QTBUG-87718
Any help is appreciated !

**Comment by Dark-Passenger** [comment]
> Great ! Now we need to make a working recipe, which is still not the case, see build failures on https://github.com/bincrafters/conan-qt/tree/prerelease/6.0.0-beta2 and the bugreports I made
> https://bugreports.qt.io/browse/QTBUG-87582
> https://bugreports.qt.io/browse/QTBUG-87479
> https://bugreports.qt.io/browse/QTBUG-87718
> Any help is appreciated !

I did see that, I actually had a question about that should we have a new issue for discussions about the recipe for 6.0 ?

Question: why is the recipe still adding additional include paths + lib dirs, why not patch the cmake file at the root to use conanbuildinfo ?

I do want to work on this, just can't seem to find the time right now 😅

**Comment by ericLemanissier** [comment]
Don't hesitate to raise an issue, contact me son slack, or put comments directly on github commits web interface (eg https://github.com/bincrafters/conan-qt/commit/ffb73c9efbeeee83b1953713010ee2d73e7161c4)

**Comment by ericLemanissier** [comment]
This recipe is now in the Conan Center Index, so I started a discussion about modularized package on conan-io/conan-center-index#4416

Please migrate to the recipe version there.
Thanks!

https://conan.io/center/qt
