### ISSUE TITLE
soil2/1.11@bincrafters/stable: Fail on build

### ISSUE THREAD

**Issue by FernandoVelcic** [bincrafters/community#1102]
$ conan install soil2/1.11@bincrafters/stable --build
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

soil2/1.11@bincrafters/stable: Forced build from source
premake_installer/4.4-beta5@bincrafters/stable: Not found in local cache, looking in remotes...
premake_installer/4.4-beta5@bincrafters/stable: Trying with 'conan-center'...
premake_installer/4.4-beta5@bincrafters/stable: Trying with 'bincrafters'...
Downloading conanmanifest.txt completed [0.10k]                                          
Downloading conanfile.py completed [3.26k]                                               
Downloading conan_export.tgz completed [0.74k]                                           
Decompressing conan_export.tgz completed [0.00k]                                         
premake_installer/4.4-beta5@bincrafters/stable: Downloaded recipe revision 0
premake_installer/4.4-beta5@bincrafters/stable: Forced build from source
Installing package: soil2/1.11@bincrafters/stable
Requirements
    soil2/1.11@bincrafters/stable from 'bincrafters' - Cache
Packages
    soil2/1.11@bincrafters/stable:176b7bd27fb0759a69f81f0746a288d1ce945b98 - Build
Build requirements
    premake_installer/4.4-beta5@bincrafters/stable from 'bincrafters' - Downloaded
Build requirements packages
    premake_installer/4.4-beta5@bincrafters/stable:44fcf6b9a7fb86b2586303e3db40189d3b511830 - Build

premake_installer/4.4-beta5@bincrafters/stable: Configuring sources in /home/fernando/.conan/data/premake_installer/4.4-beta5/bincrafters/stable/source
Downloading download completed [582.89k]                                                 

Unzipping 2.1MB, this can take a while
Unzipping 100 %                                                       premake_installer/4.4-beta5@bincrafters/stable: Copying sources to build folder
premake_installer/4.4-beta5@bincrafters/stable: Building your package in /home/fernando/.conan/data/premake_installer/4.4-beta5/bincrafters/stable/build/44fcf6b9a7fb86b2586303e3db40189d3b511830
premake_installer/4.4-beta5@bincrafters/stable: Generator txt created conanbuildinfo.txt
premake_installer/4.4-beta5@bincrafters/stable: Calling build()
==== Building Premake4 (release) ====
Creating obj/Release
Creating ../../bin/release
mkdir -p ../../bin/release
os_chdir.c
mkdir -p obj/Release
os_copyfile.c
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/os_chdir.o" -MF obj/Release/os_chdir.d -c "../../src/host/os_chdir.c"
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/os_copyfile.o" -MF obj/Release/os_copyfile.d -c "../../src/host/os_copyfile.c"
os_getcwd.c
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/os_getcwd.o" -MF obj/Release/os_getcwd.d -c "../../src/host/os_getcwd.c"
os_getversion.c
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/os_getversion.o" -MF obj/Release/os_getversion.d -c "../../src/host/os_getversion.c"
os_is64bit.c
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/os_is64bit.o" -MF obj/Release/os_is64bit.d -c "../../src/host/os_is64bit.c"
os_isdir.c
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/os_isdir.o" -MF obj/Release/os_isdir.d -c "../../src/host/os_isdir.c"
os_isfile.c
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/os_isfile.o" -MF obj/Release/os_isfile.d -c "../../src/host/os_isfile.c"
os_match.c
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/os_match.o" -MF obj/Release/os_match.d -c "../../src/host/os_match.c"
os_mkdir.c
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/os_mkdir.o" -MF obj/Release/os_mkdir.d -c "../../src/host/os_mkdir.c"
os_pathsearch.c
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/os_pathsearch.o" -MF obj/Release/os_pathsearch.d -c "../../src/host/os_pathsearch.c"
os_rmdir.c
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/os_rmdir.o" -MF obj/Release/os_rmdir.d -c "../../src/host/os_rmdir.c"
os_stat.c
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/os_stat.o" -MF obj/Release/os_stat.d -c "../../src/host/os_stat.c"
os_uuid.c
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/os_uuid.o" -MF obj/Release/os_uuid.d -c "../../src/host/os_uuid.c"
path_isabsolute.c
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/path_isabsolute.o" -MF obj/Release/path_isabsolute.d -c "../../src/host/path_isabsolute.c"
premake.c
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/premake.o" -MF obj/Release/premake.d -c "../../src/host/premake.c"
premake_main.c
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/premake_main.o" -MF obj/Release/premake_main.d -c "../../src/host/premake_main.c"
scripts.c
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/scripts.o" -MF obj/Release/scripts.d -c "../../src/host/scripts.c"
string_endswith.c
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/string_endswith.o" -MF obj/Release/string_endswith.d -c "../../src/host/string_endswith.c"
lapi.c
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/lapi.o" -MF obj/Release/lapi.d -c "../../src/host/lua-5.1.4/src/lapi.c"
lauxlib.c
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/lauxlib.o" -MF obj/Release/lauxlib.d -c "../../src/host/lua-5.1.4/src/lauxlib.c"
lbaselib.c
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/lbaselib.o" -MF obj/Release/lbaselib.d -c "../../src/host/lua-5.1.4/src/lbaselib.c"
lcode.c
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/lcode.o" -MF obj/Release/lcode.d -c "../../src/host/lua-5.1.4/src/lcode.c"
../../src/host/lua-5.1.4/src/lauxlib.c: In function ‘luaL_loadfile’:
../../src/host/lua-5.1.4/src/lauxlib.c:577:4: warning: this ‘while’ clause does not guard... [-Wmisleading-indentation]
  577 |    while ((c = getc(lf.f)) != EOF && c != LUA_SIGNATURE[0]) ;
      |    ^~~~~
../../src/host/lua-5.1.4/src/lauxlib.c:578:5: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘while’
  578 |     lf.extraline = 0;
      |     ^~
ldblib.c
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/ldblib.o" -MF obj/Release/ldblib.d -c "../../src/host/lua-5.1.4/src/ldblib.c"
ldebug.c
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/ldebug.o" -MF obj/Release/ldebug.d -c "../../src/host/lua-5.1.4/src/ldebug.c"
../../src/host/lua-5.1.4/src/ldebug.c: In function ‘symbexec’:
../../src/host/lua-5.1.4/src/ldebug.c:268:22: warning: this statement may fall through [-Wimplicit-fallthrough=]
  268 | #define check(x)  if (!(x)) return 0;
      |                      ^
../../src/host/lua-5.1.4/src/ldebug.c:272:26: note: in expansion of macro ‘check’
  272 | #define checkreg(pt,reg) check((reg) < (pt)->maxstacksize)
      |                          ^~~~~
../../src/host/lua-5.1.4/src/ldebug.c:414:9: note: in expansion of macro ‘checkreg’
  414 |         checkreg(pt, a+3);
      |         ^~~~~~~~
../../src/host/lua-5.1.4/src/ldebug.c:416:7: note: here
  416 |       case OP_JMP: {
      |       ^~~~
ldo.c
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/ldo.o" -MF obj/Release/ldo.d -c "../../src/host/lua-5.1.4/src/ldo.c"
ldump.c
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/ldump.o" -MF obj/Release/ldump.d -c "../../src/host/lua-5.1.4/src/ldump.c"
lfunc.c
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/lfunc.o" -MF obj/Release/lfunc.d -c "../../src/host/lua-5.1.4/src/lfunc.c"
lgc.c
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/lgc.o" -MF obj/Release/lgc.d -c "../../src/host/lua-5.1.4/src/lgc.c"
linit.c
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/linit.o" -MF obj/Release/linit.d -c "../../src/host/lua-5.1.4/src/linit.c"
liolib.c
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/liolib.o" -MF obj/Release/liolib.d -c "../../src/host/lua-5.1.4/src/liolib.c"
llex.c
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/llex.o" -MF obj/Release/llex.d -c "../../src/host/lua-5.1.4/src/llex.c"
lmathlib.c
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/lmathlib.o" -MF obj/Release/lmathlib.d -c "../../src/host/lua-5.1.4/src/lmathlib.c"
../../src/host/lua-5.1.4/src/llex.c: In function ‘llex’:
../../src/host/lua-5.1.4/src/llex.c:367:14: warning: this statement may fall through [-Wimplicit-fallthrough=]
  367 |         else luaX_lexerror(ls, "invalid long string delimiter", TK_STRING);
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../src/host/lua-5.1.4/src/llex.c:369:7: note: here
  369 |       case '=': {
      |       ^~~~
lmem.c
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/lmem.o" -MF obj/Release/lmem.d -c "../../src/host/lua-5.1.4/src/lmem.c"
loadlib.c
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/loadlib.o" -MF obj/Release/loadlib.d -c "../../src/host/lua-5.1.4/src/loadlib.c"
lobject.c
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/lobject.o" -MF obj/Release/lobject.d -c "../../src/host/lua-5.1.4/src/lobject.c"
lopcodes.c
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/lopcodes.o" -MF obj/Release/lopcodes.d -c "../../src/host/lua-5.1.4/src/lopcodes.c"
loslib.c
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/loslib.o" -MF obj/Release/loslib.d -c "../../src/host/lua-5.1.4/src/loslib.c"
lparser.c
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/lparser.o" -MF obj/Release/lparser.d -c "../../src/host/lua-5.1.4/src/lparser.c"
lstate.c
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/lstate.o" -MF obj/Release/lstate.d -c "../../src/host/lua-5.1.4/src/lstate.c"
lstring.c
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/lstring.o" -MF obj/Release/lstring.d -c "../../src/host/lua-5.1.4/src/lstring.c"
lstrlib.c
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/lstrlib.o" -MF obj/Release/lstrlib.d -c "../../src/host/lua-5.1.4/src/lstrlib.c"
ltable.c
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/ltable.o" -MF obj/Release/ltable.d -c "../../src/host/lua-5.1.4/src/ltable.c"
ltablib.c
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/ltablib.o" -MF obj/Release/ltablib.d -c "../../src/host/lua-5.1.4/src/ltablib.c"
../../src/host/lua-5.1.4/src/ltablib.c: In function ‘addfield’:
../../src/host/lua-5.1.4/src/ltablib.c:137:3: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
  137 |   if (!lua_isstring(L, -1))
      |   ^~
../../src/host/lua-5.1.4/src/ltablib.c:140:5: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  140 |     luaL_addvalue(b);
      |     ^~~~~~~~~~~~~
../../src/host/lua-5.1.4/src/ltable.c: In function ‘luaH_get’:
../../src/host/lua-5.1.4/src/ltable.c:473:23: warning: this statement may fall through [-Wimplicit-fallthrough=]
  473 |     case LUA_TNUMBER: {
      |                       ^
../../src/host/lua-5.1.4/src/ltable.c:481:5: note: here
  481 |     default: {
      |     ^~~~~~~
ltm.c
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/ltm.o" -MF obj/Release/ltm.d -c "../../src/host/lua-5.1.4/src/ltm.c"
lundump.c
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/lundump.o" -MF obj/Release/lundump.d -c "../../src/host/lua-5.1.4/src/lundump.c"
lvm.c
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/lvm.o" -MF obj/Release/lvm.d -c "../../src/host/lua-5.1.4/src/lvm.c"
lzio.c
gcc -m64  -MMD -MP -DNDEBUG -DLUA_USE_POSIX -DLUA_USE_DLOPEN -I../../src/host/lua-5.1.4/src  -Wall -Wextra -Os  -o "obj/Release/lzio.o" -MF obj/Release/lzio.d -c "../../src/host/lua-5.1.4/src/lzio.c"
Linking Premake4
gcc -o ../../bin/release/premake4 obj/Release/os_chdir.o obj/Release/os_copyfile.o obj/Release/os_getcwd.o obj/Release/os_getversion.o obj/Release/os_is64bit.o obj/Release/os_isdir.o obj/Release/os_isfile.o obj/Release/os_match.o obj/Release/os_mkdir.o obj/Release/os_pathsearch.o obj/Release/os_rmdir.o obj/Release/os_stat.o obj/Release/os_uuid.o obj/Release/path_isabsolute.o obj/Release/premake.o obj/Release/premake_main.o obj/Release/scripts.o obj/Release/string_endswith.o obj/Release/lapi.o obj/Release/lauxlib.o obj/Release/lbaselib.o obj/Release/lcode.o obj/Release/ldblib.o obj/Release/ldebug.o obj/Release/ldo.o obj/Release/ldump.o obj/Release/lfunc.o obj/Release/lgc.o obj/Release/linit.o obj/Release/liolib.o obj/Release/llex.o obj/Release/lmathlib.o obj/Release/lmem.o obj/Release/loadlib.o obj/Release/lobject.o obj/Release/lopcodes.o obj/Release/loslib.o obj/Release/lparser.o obj/Release/lstate.o obj/Release/lstring.o obj/Release/lstrlib.o obj/Release/ltable.o obj/Release/ltablib.o obj/Release/ltm.o obj/Release/lundump.o obj/Release/lvm.o obj/Release/lzio.o    -m64 -L. -s -rdynamic   -lm -ldl
premake_installer/4.4-beta5@bincrafters/stable: Package '44fcf6b9a7fb86b2586303e3db40189d3b511830' built
premake_installer/4.4-beta5@bincrafters/stable: Build folder /home/fernando/.conan/data/premake_installer/4.4-beta5/bincrafters/stable/build/44fcf6b9a7fb86b2586303e3db40189d3b511830
premake_installer/4.4-beta5@bincrafters/stable: Generated conaninfo.txt
premake_installer/4.4-beta5@bincrafters/stable: Generated conanbuildinfo.txt
premake_installer/4.4-beta5@bincrafters/stable: Generating the package
premake_installer/4.4-beta5@bincrafters/stable: Package folder /home/fernando/.conan/data/premake_installer/4.4-beta5/bincrafters/stable/package/44fcf6b9a7fb86b2586303e3db40189d3b511830
premake_installer/4.4-beta5@bincrafters/stable: Calling package()
premake_installer/4.4-beta5@bincrafters/stable package(): Packaged 1 file: premake4
premake_installer/4.4-beta5@bincrafters/stable package(): Packaged 1 '.txt' file: LICENSE.txt
premake_installer/4.4-beta5@bincrafters/stable: Package '44fcf6b9a7fb86b2586303e3db40189d3b511830' created
premake_installer/4.4-beta5@bincrafters/stable: Created package revision 8943e40ee09ba3b12cd17eb322f83b76
soil2/1.11@bincrafters/stable: Applying build-requirement: premake_installer/4.4-beta5@bincrafters/stable
soil2/1.11@bincrafters/stable: ERROR: while executing system_requirements(): local variable 'packages' referenced before assignment
ERROR: Error in system requirements
[fernando@fernando mu-client]$ conan install soil2/1.11@bincrafters/stable
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

Installing package: soil2/1.11@bincrafters/stable
Requirements
    soil2/1.11@bincrafters/stable from 'bincrafters' - Cache
Packages
    soil2/1.11@bincrafters/stable:176b7bd27fb0759a69f81f0746a288d1ce945b98 - Download

soil2/1.11@bincrafters/stable: ERROR: while executing system_requirements(): local variable 'packages' referenced before assignment
ERROR: Error in system requirements

**Comment by ericLemanissier** [comment]
It should be fixed. Can you update the recipe and retry ?

**Comment by FernandoVelcic** [comment]
Thanks @ericLemanissier now it works! :+1:
