### ISSUE TITLE
[request] glfw/3.3.1

### ISSUE THREAD

**Issue by munoah** [bincrafters/community#1103]
### Package Details
  * Package Name/Version: **glfw/3.3.1**
  * Changelogs: 
    - **https://github.com/glfw/glfw/releases/tag/3.3.1** 
    - **https://www.glfw.org/changelog.html**

The above mentioned version is newly released by the upstream project and not yet available as a recipe. Please add this version.

**Comment by munoah** [comment]
Update: version 3.3.2 is out now
https://github.com/glfw/glfw/releases/tag/3.3.2

**Comment by ericLemanissier** [comment]
thanks for noticing. 3.3.1/stable packages are being built and uploaded currently, and 3.3.2 will come directly after

**Comment by ZaMaZaN4iK** [comment]
Is it still actual or can be closed? @munoah

**Comment by Croydon** [comment]
3.3.1 and 3.3.2 are available now

Thanks everyone!
