### ISSUE TITLE
[question] troubles creating a recipe with sfml and imgui

### ISSUE THREAD

**Issue by barsoosayque** [bincrafters/community#1104]
Sorry to jam two different questions together, but they are all relevant to the library I'm trying to wrap in a recipe.

I am trying to create a recipe for [eliasdaler/imgui-sfml](https://github.com/eliasdaler/imgui-sfml) for later request for inclusion, and by this time I already have done most of the work, but there are some troubles with CI, and also I am very confused about imgui, so it would be nice if someone will help me to sort stuff out. Here is the repo for the recipe: [barsoosayque/conan-imgui-sfml](https://github.com/barsoosayque/conan-imgui-sfml).

So, the issues:
1. Travis fails to build ([last build](https://travis-ci.org/barsoosayque/conan-imgui-sfml/builds/590842488)) my recipe because of missing prebuilt *libpng*. It is a transitive dependency of SFML, on which my recipe depend. What I did is I just copypasted travis configs from the conan-sfml repo to mine, but it didn't help, and I'm just clueless why is that even happening in the first place (since conan-sfml seems to build successfully).
2. The library I'm trying to write a recipe for is using imgui as a main dependency. I know that there is a conan-imgui recipe, but it actually *builds* imgui, add compiler/linker flags and such. Yet I don't need any of that, because CMake files of imgui-sfml do build imgui too, I just need to provide it with a sources. To give user options on what imgui to build this library with, the recipe has an option (`imgui_version`). What is the correct way of handling a situation like this:
    a) Continue with the option and download imgui release to consume it.
    b) Write a patch to change CMake files of the library, and depend on conan-imgui.

**Comment by Croydon** [comment]
CI fails for you, because you try to build 32bit for which we don't provide pre-builds anymore

and the rest fails because `conans.errors.NotFoundException: Not found: https://github.com/eliasdaler/imgui-sfml/archive/v2.1.0.tar.gz`

**Comment by barsoosayque** [comment]
Closed in favor of #1125.
