### ISSUE TITLE
[openh264] 1.7.0 not copy the static and dynamic libs

### ISSUE THREAD

**Issue by leyewen** [bincrafters/community#1105]
### Package and Environment Details
  * Package Name/Version: **openh264/1.7.0**
  * Operating System+version: **Windows 10**
  * Compiler+version: **gcc-mingw-w64-8.1.0**
  * Docker image: **conanio/gcc8.1**
  * Conan version: **conan 1.21.0**
  * Python version: **Python 3.7.5**

### Conan profile
```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=gcc
compiler.cppstd=14
compiler.exception=seh
compiler.libcxx=libstdc++11
compiler.threads=posix
compiler.version=8.1
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
CONAN_CMAKE_GENERATOR=MinGW Makefiles
```

```
opencv:shared=True
ffmpeg:shared=True
openh264:shared=True
```

### Steps to reproduce
When I build `openh264/1.7.0@bincrafters/stable` is ok.
When I build ffmpeg

It throws:
```
collect2.exe: error: ld returned 1 exit status
ERROR: openh264 not found using pkg-config
```

### Fixed method
I researched this problem.
Find some issuse
https://stackoverflow.com/questions/56949282/compiling-ffmpeg-with-x265-has-error-x265-not-found-using-pkg-config
https://community.bitnami.com/t/cant-build-ffmpeg-on-wordpress-vm-freetype2/31805
https://stackoverflow.com/questions/23650885/build-ffmpeg-with-freetype2-for-arm

Finally, I find out `\package\40d7adf2c28a3324a316cd1f90822d82e34b2a27\lib\` have not `libopenh264.dll.a` file due to this error.

update
`.conan\data\openh264\1.7.0\bincrafters\stable\export\conanfile.py`
in line 107 add fixed:
```
        # Copying static and dynamic libs
        build_dir = os.path.join(self._source_subfolder, "_build")
        if self.options.shared:
            self.copy(pattern="*.dylib*", dst="lib", src=build_dir, keep_path=False, symlinks=True)
            self.copy(pattern="*.so*", dst="lib", src=build_dir, keep_path=False, symlinks=True)
            self.copy(pattern="*.dll", dst="bin", src=build_dir, keep_path=False)
            self.copy(pattern="*.dll.a", dst="lib", src=build_dir, keep_path=False)
        else:
            self.copy(pattern="*.a", dst="lib", src=build_dir, keep_path=False)
        self.copy(pattern="*.lib", dst="lib", src=build_dir, keep_path=False)
```
And it build passed.

### Logs

> ffmpeg/4.2.1@bincrafters/stable: Calling:
>  > /c/users/home/.conan/data/ffmpeg/4.2.1/bincrafters/stable/build/6fa54f8aed0c07ff98fa8552e083308abc29e905/source_subfolder/configure --prefix=/c/users/home/.conan/data/ffmpeg/4.2.1/bincrafters/stable/package/6fa54f8aed0c07ff98fa8552e083308abc29e905 --disable-doc --disable-programs --disable-static --enable-shared --pkg-config-flags=--static --disable-optimizations --disable-mmx --disable-stripping --enable-debug --enable-postproc --enable-zlib --enable-bzlib --enable-lzma --enable-iconv --enable-libfreetype --enable-libopenjpeg --enable-libopenh264 --enable-libvorbis --enable-libopus --disable-libzmq --disable-sdl2 --enable-libx264 --enable-libx265 --enable-libvpx --enable-libmp3lame --enable-libfdk-aac --enable-libwebp --enable-openssl --enable-gpl --enable-nonfree --disable-libmfx --disable-cuda --disable-cuvid
> ffmpeg/4.2.1@bincrafters/stable: run_in_windows_bash: bash  -c ^"cd \^"/c/users/home/.conan/data/ffmpeg/4.2.1/bincrafters/stable/build/6fa54f8aed0c07ff98fa8552e083308abc29e905/source_subfolder\^" ^&^& PATH=\^"/c/users/home/.conan/data/yasm/1.3.0/_/_/package/456f15897172eef340fcbac8a70811f2beb26a93/bin:/c/.conan/caae83/1/bin:/c/users/home/.conan/data/freetype/2.10.1/_/_/package/a1079a931c8c51582435c1fbfa33f2fd1f4c0b2a/bin:$PATH\^" ^&^& /c/users/home/.conan/data/ffmpeg/4.2.1/bincrafters/stable/build/6fa54f8aed0c07ff98fa8552e083308abc29e905/source_subfolder/configure --prefix=/c/users/home/.conan/data/ffmpeg/4.2.1/bincrafters/stable/package/6fa54f8aed0c07ff98fa8552e083308abc29e905 --disable-doc --disable-programs --disable-static --enable-shared --pkg-config-flags=--static --disable-optimizations --disable-mmx --disable-stripping --enable-debug --enable-postproc --enable-zlib --enable-bzlib --enable-lzma --enable-iconv --enable-libfreetype --enable-libopenjpeg --enable-libopenh264 --enable-libvorbis --enable-libopus --disable-libzmq --disable-sdl2 --enable-libx264 --enable-libx265 --enable-libvpx --enable-libmp3lame --enable-libfdk-aac --enable-libwebp --enable-openssl --enable-gpl --enable-nonfree --disable-libmfx --disable-cuda --disable-cuvid  ^"
> ffmpeg/4.2.1@bincrafters/stable: ERROR: openh264 not found using pkg-config
> ffmpeg/4.2.1@bincrafters/stable:
> ffmpeg/4.2.1@bincrafters/stable: If you think configure made a mistake, make sure you are using the latest
> ffmpeg/4.2.1@bincrafters/stable: version from Git.  If the latest version fails, report the problem to the
> ffmpeg/4.2.1@bincrafters/stable: ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
> ffmpeg/4.2.1@bincrafters/stable: Include the log file "ffbuild/config.log" produced by configure as this will help
> ffmpeg/4.2.1@bincrafters/stable: solve the problem.
> ffmpeg/4.2.1@bincrafters/stable: ERROR: Package '6fa54f8aed0c07ff98fa8552e083308abc29e905' build failed
> ffmpeg/4.2.1@bincrafters/stable: WARN: Build folder C:\Users\Home\.conan\data\ffmpeg\4.2.1\bincrafters\stable\build\6fa54f8aed0c07ff98fa8552e083308abc29e905
> ERROR: ffmpeg/4.2.1@bincrafters/stable: Error in build() method, line 226
> 	self.build_configure()
> while calling 'build_configure', line 317
> 	env_build.configure(args=args, build=False, host=False, target=False)
> 	ConanException: Error 1 while executing /c/users/home/.conan/data/ffmpeg/4.2.1/bincrafters/stable/build/6fa54f8aed0c07ff98fa8552e083308abc29e905/source_subfolder/configure --prefix=/c/users/home/.conan/data/ffmpeg/4.2.1/bincrafters/stable/package/6fa54f8aed0c07ff98fa8552e083308abc29e905 --disable-doc --disable-programs --disable-static --enable-shared --pkg-config-flags=--static --disable-optimizations --disable-mmx --disable-stripping --enable-debug --enable-postproc --enable-zlib --enable-bzlib --enable-lzma --enable-iconv --enable-libfreetype --enable-libopenjpeg --enable-libopenh264 --enable-libvorbis --enable-libopus --disable-libzmq --disable-sdl2 --enable-libx264 --enable-libx265 --enable-libvpx --enable-libmp3lame --enable-libfdk-aac --enable-libwebp --enable-openssl --enable-gpl --enable-nonfree --disable-libmfx --disable-cuda --disable-cuvid
> ffmpeg/4.2.1@bincrafters/stable:
> 

log "source_subfolder\ffbuild\config.log"

> pkg-config --exists --print-errors openh264
> check_func_headers wels/codec_api.h WelsGetCodecVersion -IC:/Users/Home/.conan/data/openh264/1.7.0/bincrafters/stable/package/40d7adf2c28a3324a316cd1f90822d82e34b2a27/include -LC:/Users/Home/.conan/data/openh264/1.7.0/bincrafters/stable/package/40d7adf2c28a3324a316cd1f90822d82e34b2a27/lib -lopenh264 -lstdc++ -Wl,-rpath=C:/Users/Home/.conan/data/openh264/1.7.0/bincrafters/stable/package/40d7adf2c28a3324a316cd1f90822d82e34b2a27/lib
> test_ld cc -IC:/Users/Home/.conan/data/openh264/1.7.0/bincrafters/stable/package/40d7adf2c28a3324a316cd1f90822d82e34b2a27/include -LC:/Users/Home/.conan/data/openh264/1.7.0/bincrafters/stable/package/40d7adf2c28a3324a316cd1f90822d82e34b2a27/lib -lopenh264 -lstdc++ -Wl,-rpath=C:/Users/Home/.conan/data/openh264/1.7.0/bincrafters/stable/package/40d7adf2c28a3324a316cd1f90822d82e34b2a27/lib
> test_cc -IC:/Users/Home/.conan/data/openh264/1.7.0/bincrafters/stable/package/40d7adf2c28a3324a316cd1f90822d82e34b2a27/include -LC:/Users/Home/.conan/data/openh264/1.7.0/bincrafters/stable/package/40d7adf2c28a3324a316cd1f90822d82e34b2a27/lib -Wl,-rpath=C:/Users/Home/.conan/data/openh264/1.7.0/bincrafters/stable/package/40d7adf2c28a3324a316cd1f90822d82e34b2a27/lib
> BEGIN /c/Users/Home/AppData/Local/Temp/ffconf.2S9uwzWB/test.c
>     1	#include <wels/codec_api.h>
>     2	#include <stdint.h>
>     3	long check_WelsGetCodecVersion(void) { return (long) WelsGetCodecVersion; }
>     4	int main(void) { int ret = 0;
>     5	 ret |= ((intptr_t)check_WelsGetCodecVersion) & 0xFFFF;
>     6	return ret; }
> END /c/Users/Home/AppData/Local/Temp/ffconf.2S9uwzWB/test.c
> gcc -I/c/users/home/.conan/data/xz_utils/5.2.4/_/_/package/9bae293509b8f1cbf43b85e17e13bb8ccb9d978a/include -I/c/.conan/caae83/1/include -I/c/users/home/.conan/data/freetype/2.10.1/_/_/package/a1079a931c8c51582435c1fbfa33f2fd1f4c0b2a/include -I/c/users/home/.conan/data/freetype/2.10.1/_/_/package/a1079a931c8c51582435c1fbfa33f2fd1f4c0b2a/include/freetype2 -I/c/users/home/.conan/data/openjpeg/2.3.1/_/_/package/61ae25ebb96d0515437eaf1a126800a654c38e19/include -I/c/users/home/.conan/data/openjpeg/2.3.1/_/_/package/61ae25ebb96d0515437eaf1a126800a654c38e19/include/openjpeg-2.3 -I/c/users/home/.conan/data/openh264/1.7.0/bincrafters/stable/package/40d7adf2c28a3324a316cd1f90822d82e34b2a27/include -I/c/users/home/.conan/data/vorbis/1.3.6/bincrafters/stable/package/96a7402d295b00c881e8542e0940babef75b8b41/include -I/c/users/home/.conan/data/opus/1.3.1/bincrafters/stable/package/9e3762944ae8f4cc8b7bd27c3e59996e1e3a0709/include -I/c/users/home/.conan/data/opus/1.3.1/bincrafters/stable/package/9e3762944ae8f4cc8b7bd27c3e59996e1e3a0709/include/opus -I/c/users/home/.conan/data/libx264/20190605/_/_/package/1a9b746db3232276ada4cf64b16512ba901fcf09/include -I/c/users/home/.conan/data/libx265/3.0/bincrafters/stable/package/e82f74c25b82d272dbcd1630371590cd62192d65/include -I/c/users/home/.conan/data/libvpx/1.8.0/bincrafters/stable/package/2b8eea48ceb8a91c3e4fccdf69329fc3197c3506/include -I/c/users/home/.conan/data/libmp3lame/3.100/bincrafters/stable/package/40d7adf2c28a3324a316cd1f90822d82e34b2a27/include -I/c/users/home/.conan/data/libfdk_aac/2.0.0/_/_/package/40d7adf2c28a3324a316cd1f90822d82e34b2a27/include -I/c/users/home/.conan/data/libwebp/1.0.3/_/_/package/cccf43a11dc2e80d0eb543e565c4bda253be64b1/include -I/c/users/home/.conan/data/openssl/1.1.1d/_/_/package/fe2be2fc17a1b9debab465283722a7570095eb04/include -I/c/users/home/.conan/data/bzip2/1.0.8/_/_/package/d12c5e44e00b9a21043038ad3a54127cfe2a8e9a/include -I/c/users/home/.conan/data/libpng/1.6.37/_/_/package/fe2be2fc17a1b9debab465283722a7570095eb04/include -I/c/users/home/.conan/data/ogg/1.3.4/_/_/package/9e3762944ae8f4cc8b7bd27c3e59996e1e3a0709/include -I/c/users/home/.conan/data/zlib/1.2.11/_/_/package/9e3762944ae8f4cc8b7bd27c3e59996e1e3a0709/include -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -U__STRICT_ANSI__ -D__USE_MINGW_ANSI_STDIO=1 -D__printf__=__gnu_printf__ -D_WIN32_WINNT=0x0600 -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -DPIC -m64 -g -std=c11 -IC:/Users/Home/.conan/data/zlib/1.2.11/_/_/package/9e3762944ae8f4cc8b7bd27c3e59996e1e3a0709/include -IC:/Users/Home/.conan/data/libfdk_aac/2.0.0/_/_/package/40d7adf2c28a3324a316cd1f90822d82e34b2a27/include -IC:/Users/Home/.conan/data/freetype/2.10.1/_/_/package/a1079a931c8c51582435c1fbfa33f2fd1f4c0b2a/include -IC:/Users/Home/.conan/data/freetype/2.10.1/_/_/package/a1079a931c8c51582435c1fbfa33f2fd1f4c0b2a/include/freetype2 -IC:/Users/Home/.conan/data/libpng/1.6.37/_/_/package/fe2be2fc17a1b9debab465283722a7570095eb04/include -IC:/Users/Home/.conan/data/zlib/1.2.11/_/_/package/9e3762944ae8f4cc8b7bd27c3e59996e1e3a0709/include -IC:/Users/Home/.conan/data/bzip2/1.0.8/_/_/package/d12c5e44e00b9a21043038ad3a54127cfe2a8e9a/include -IC:/Users/Home/.conan/data/openh264/1.7.0/bincrafters/stable/package/40d7adf2c28a3324a316cd1f90822d82e34b2a27/include -LC:/Users/Home/.conan/data/openh264/1.7.0/bincrafters/stable/package/40d7adf2c28a3324a316cd1f90822d82e34b2a27/lib -Wl,-rpath=C:/Users/Home/.conan/data/openh264/1.7.0/bincrafters/stable/package/40d7adf2c28a3324a316cd1f90822d82e34b2a27/lib -c -o /c/Users/Home/AppData/Local/Temp/ffconf.2S9uwzWB/test.o /c/Users/Home/AppData/Local/Temp/ffconf.2S9uwzWB/test.c
> C:/Users/Home/AppData/Local/Temp/ffconf.2S9uwzWB/test.c: In function 'check_WelsGetCodecVersion':
> C:/Users/Home/AppData/Local/Temp/ffconf.2S9uwzWB/test.c:3:47: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
>  long check_WelsGetCodecVersion(void) { return (long) WelsGetCodecVersion; }
>                                                ^
> gcc -m64 -L/c/users/home/.conan/data/xz_utils/5.2.4/_/_/package/9bae293509b8f1cbf43b85e17e13bb8ccb9d978a/lib -L/c/.conan/caae83/1/lib -L/c/users/home/.conan/data/freetype/2.10.1/_/_/package/a1079a931c8c51582435c1fbfa33f2fd1f4c0b2a/lib -L/c/users/home/.conan/data/openjpeg/2.3.1/_/_/package/61ae25ebb96d0515437eaf1a126800a654c38e19/lib -L/c/users/home/.conan/data/openh264/1.7.0/bincrafters/stable/package/40d7adf2c28a3324a316cd1f90822d82e34b2a27/lib -L/c/users/home/.conan/data/vorbis/1.3.6/bincrafters/stable/package/96a7402d295b00c881e8542e0940babef75b8b41/lib -L/c/users/home/.conan/data/opus/1.3.1/bincrafters/stable/package/9e3762944ae8f4cc8b7bd27c3e59996e1e3a0709/lib -L/c/users/home/.conan/data/libx264/20190605/_/_/package/1a9b746db3232276ada4cf64b16512ba901fcf09/lib -L/c/users/home/.conan/data/libx265/3.0/bincrafters/stable/package/e82f74c25b82d272dbcd1630371590cd62192d65/lib -L/c/users/home/.conan/data/libvpx/1.8.0/bincrafters/stable/package/2b8eea48ceb8a91c3e4fccdf69329fc3197c3506/lib -L/c/users/home/.conan/data/libmp3lame/3.100/bincrafters/stable/package/40d7adf2c28a3324a316cd1f90822d82e34b2a27/lib -L/c/users/home/.conan/data/libfdk_aac/2.0.0/_/_/package/40d7adf2c28a3324a316cd1f90822d82e34b2a27/lib -L/c/users/home/.conan/data/libwebp/1.0.3/_/_/package/cccf43a11dc2e80d0eb543e565c4bda253be64b1/lib -L/c/users/home/.conan/data/openssl/1.1.1d/_/_/package/fe2be2fc17a1b9debab465283722a7570095eb04/lib -L/c/users/home/.conan/data/bzip2/1.0.8/_/_/package/d12c5e44e00b9a21043038ad3a54127cfe2a8e9a/lib -L/c/users/home/.conan/data/libpng/1.6.37/_/_/package/fe2be2fc17a1b9debab465283722a7570095eb04/lib -L/c/users/home/.conan/data/ogg/1.3.4/_/_/package/9e3762944ae8f4cc8b7bd27c3e59996e1e3a0709/lib -L/c/users/home/.conan/data/zlib/1.2.11/_/_/package/9e3762944ae8f4cc8b7bd27c3e59996e1e3a0709/lib -Wl,--nxcompat,--dynamicbase -Wl,--high-entropy-va -Wl,--as-needed -Wl,--image-base,0x140000000 -IC:/Users/Home/.conan/data/openh264/1.7.0/bincrafters/stable/package/40d7adf2c28a3324a316cd1f90822d82e34b2a27/include -LC:/Users/Home/.conan/data/openh264/1.7.0/bincrafters/stable/package/40d7adf2c28a3324a316cd1f90822d82e34b2a27/lib -Wl,-rpath=C:/Users/Home/.conan/data/openh264/1.7.0/bincrafters/stable/package/40d7adf2c28a3324a316cd1f90822d82e34b2a27/lib -o /c/Users/Home/AppData/Local/Temp/ffconf.2S9uwzWB/test.exe /c/Users/Home/AppData/Local/Temp/ffconf.2S9uwzWB/test.o -lopenh264 -lstdc++
> C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lopenh264
> collect2.exe: error: ld returned 1 exit status
> ERROR: openh264 not found using pkg-config
>

**Comment by Croydon** [comment]
This recipe is now in the [Conan Center Index](https://github.com/conan-io/conan-center-index/).

Please migrate to the recipe version there. 
If this is still an issue, please create a new issue in the [Conan Center Index issue tracker](https://github.com/conan-io/conan-center-index/issues).

Thanks!
