### ISSUE TITLE
[request] cppzmq/4.6.0

### ISSUE THREAD

**Issue by gummif** [bincrafters/community#1106]
### Package Details
  * Package Name/Version: **cppzmq/4.6.0**
  * Changelog: **https://github.com/zeromq/cppzmq/releases/tag/v4.6.0**

The above mentioned version is newly released by the upstream project and not yet available as a recipe. Please add this version.

**Comment by gummif** [comment]
All the build in my company have been failing for a week because of conan/cmake caching/32-bit checking bug. Any reason it takes so long to add a new version? Looks like there is also little activity in 
conan-center-index. Anything I can do?

**Comment by uilianries** [comment]
> All the build in my company have been failing for a week because of conan/cmake caching/32-bit checking bug

What do you mean? Docker image version, Conan package ... ?

**Comment by uilianries** [comment]
Done!

https://bintray.com/bincrafters/public-conan/cppzmq%3Abincrafters/4.6.0%3Astable

**Comment by gummif** [comment]
Great! Thanks for that.

@uilianries  The symptom is like in this https://github.com/catchorg/Catch2/issues/1368. When getting the (header only) package with conan, and using find_package in CMake, it fails because there is a check if the system is 32bits.

**Comment by uilianries** [comment]
I see, I think it's related to cmake_sizeof_void_p, but right row we are migrating our packages to Conan Center Index, where we should not publish the cmake files provided by the author with the package, Conan is able to generate a customized Findxxx.cmake which is enough for any case.
