### ISSUE TITLE
[request] libwebsockets/3.2.0

### ISSUE THREAD

**Issue by AltenOosterbeek** [bincrafters/community#1109]
### Package Details
  * Package Name/Version: **libwebsockets/3.2.0**
  * Changelog: **https://github.com/warmcat/libwebsockets/blob/v3.2-stable/changelog**

The above mentioned version is newly released by the upstream project and not yet available as a recipe. Please add this version.

**Comment by uilianries** [comment]
Done!

https://github.com/bincrafters/conan-libwebsockets/tree/stable/3.2.2
https://travis-ci.com/bincrafters/conan-libwebsockets/builds/145531403
https://ci.appveyor.com/project/bincrafters/conan-libwebsockets/builds/30281495

You need to wait ~2h until all packages be available for download (CI build + upload).

**Comment by AltenOosterbeek** [comment]
Thanks!
