### ISSUE TITLE
conan installing cryptopp 8.2.0, visual studio, with compiler toolset as v141_xp

### ISSUE THREAD

**Issue by FanjingLiu** [bincrafters/community#1110]
### Description of Problem, Request, or Question
I am on windows 10 trying to build a dll for windows 7 therefore, from my previous google research I need to use toolset v141_xp on VS2017. This doesn't happen when I try don't use the regular "v141" version of the tool set. 

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: Cryptopp/8.2.0
  * Operating System+version: Windows
  * Compiler+version: MSVC 19.06
  * Docker image: **conanio/gcc7**
  * Conan version: **Conan 1.21.0**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
os_target=Windows
arch_target=x86_64
compiler=Visual Studio
compiler.version=15
compiler.toolset=v141_xp
build_type=Release
[options]
[build_requires]
[env]
### Steps to reproduce (Include if Applicable)
Command: "conan install ."

### Logs (Include/Attach if Applicable)
source_subfolder\zlib.cpp : fatal error C1083: Cannot open include file: 'winapifamily.h':

**Comment by Croydon** [comment]
Please post the entire log

**Comment by Croydon** [comment]
This recipe is now in the [Conan Center Index](https://github.com/conan-io/conan-center-index/).

Please migrate to the recipe version there. 
If this is still an issue, please create a new issue in the [Conan Center Index issue tracker](https://github.com/conan-io/conan-center-index/issues).

Thanks!
