### ISSUE TITLE
[request] android_ndk_installer/r21

### ISSUE THREAD

**Issue by dmn-star** [bincrafters/community#1111]
### Package Details
  * Package Name/Version: **ndk 21**

The above mentioned version is newly released by the upstream project and not yet available as a recipe. Please add this version.

> ERROR: android_ndk_installer/r20@bincrafters/stable: Invalid configuration: only Clang 8 is supported

**Comment by Croydon** [comment]
We do have a testing branch for r21

https://github.com/bincrafters/conan-android_ndk_installer/commits/testing/r21

@SSE4 has done a lot of work there, if he feels comfortable to release this we can do it 😄

**Comment by Croydon** [comment]
Why do we get a 405 here?

https://travis-ci.com/bincrafters/conan-android_ndk_installer/jobs/280988268#L3439

**Comment by dmn-star** [comment]
Wish I could help. :-)

**Comment by dmn-star** [comment]
Any news about?

**Comment by dmn-star** [comment]
NDK21 stable is now on Bintray. Thnx. 

https://bintray.com/bincrafters/public-conan/android_ndk_installer%3Abincrafters/r21%3Astable

**Comment by Croydon** [comment]
Re-opening until all upload issues are solved

**Comment by dmn-star** [comment]
Ok. Sorry for closing.

**Comment by Croydon** [comment]
This recipe is now in the [Conan Center Index](https://github.com/conan-io/conan-center-index/).

Please migrate to the recipe version there. 

Thanks!

https://conan.io/center/android-ndk
