### ISSUE TITLE
gstreamer/1.16.0: Build failed, on MacOS 10.14, with Apple-Clang 11.0

### ISSUE THREAD

**Issue by BlueSolei** [bincrafters/community#1112]
### Package and Environment Details 
  * Package Name/Version: **gstreamer/1.16.0**
  * Operating System+version: **MacOS Mojave 10.14**
  * Compiler+version: **Apple-Clang 11**
  * Conan version: **Conan version 1.21.1**
  * Python version: **Python 3.7.6**

### Conan profile ([as detected by CMake](https://github.com/conan-io/cmake-conan))

```
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=11.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]
```

### Steps to reproduce 
Add `gstreamer/1.16.0@bincrafters/stable`
as a requirement to a conanfile.txt
IMPORTANT:
[Current package: `gstreamer/1.16.0@bincrafters/stable` is broken, and fixed here](https://github.com/bincrafters/conan-gstreamer/commit/1012caefea20f12a00e05cb363f9dc48ab4b75f9)  
Affeer applying the fix, I get the link failure, which this issue is about.

### Logs 
[build.log](https://github.com/bincrafters/community/files/4112996/build.log)
Start at line 431:
```
Undefined symbols for architecture x86_64:
  "_CFArrayGetCount", referenced from:
      _libintl_setlocale in libgnuintl.a(setlocale.o)
      __nl_language_preferences_default in libgnuintl.a(langprefs.o)
  "_CFArrayGetValueAtIndex", referenced from:
```

### My findings:
The bug is in GStreamer sources. the package builds from a [tarball](https://gitlab.freedesktop.org/gstreamer/gstreamer/-/archive/1.16.0/gstreamer-1.16.0.tar.bz2).
I found the issue and created a [pull request](https://github.com/GStreamer/gstreamer/pull/5) to fix it.
I don't know how the package should fix this issue, as its build from a specific GStreamer release.
I can offer to patch the sources: [BuildMacOSFix.patch.txt](https://github.com/bincrafters/community/files/4113021/BuildMacOSFix.patch.txt)

**Comment by ericLemanissier** [comment]
This looks like the issue solved with https://github.com/conan-io/conan/pull/6309.could you please retry when conan 1.22.0 is released?

**Comment by BlueSolei** [comment]
thanks, I will.
When it planned to be released?

**Comment by ericLemanissier** [comment]
4 days ago, according to https://github.com/conan-io/conan/milestone/120 ;)
it should be in the coming days/weeks I guess

**Comment by BlueSolei** [comment]
I update to 1.22.0, and installing of gstreamer failed with the same error.
Here are the logs: 
[ConanInstallGStreamer.log](https://github.com/bincrafters/community/files/4142578/ConanInstallGStreamer.log)

**Comment by ericLemanissier** [comment]
@BlueSolei it's been several month, but the log you sent starts with
```
conan --version
Conan version 1.21.2
```
So I guess there was a problem with the update.
Could you retry to update conan and restart ?

**Comment by BlueSolei** [comment]
Yes, it is working now.
Thanks a lot for your response.
