### ISSUE TITLE
[request] sqlite3/3.31.0

### ISSUE THREAD

**Issue by toge** [bincrafters/community#1113]
### Package Details
  * Package Name/Version: **sqlite3/3.31.0**
  * Changelog: **https://www.sqlite.org/changes.html#version_3_31_0**

The above mentioned version is newly released by the upstream project and not yet available as a recipe. Please add this version.

**Comment by ericLemanissier** [comment]
sqlite3 is now on conan center index. Please report this on https://github.com/conan-io/conan-center-index/issues/new?labels=upstream+update&template=package_upstream_update.md&title=%5Brequest%5D+%3CLIBRARY-NAME%3E%2F%3CLIBRARY-VERSION%3E
