### ISSUE TITLE
conan-mesa: Problem with mesa-loader on archlinux

### ISSUE THREAD

**Issue by FernandoVelcic** [bincrafters/community#1119]
I am doing a game project that uses GLFW and I have this error when I try to create context.

I am compiling and running all on arch linux.

libGL error: MESA-LOADER: failed to open i965 (search paths /home/conan/.conan/data/mesa/19.3.1/bincrafters/stable/package/ef3d5fd75c61f59e0bbcbdba10f7ff46b8e5b0b8/lib/dri)
libGL error: failed to load driver: i965
libGL error: MESA-LOADER: failed to open i965 (search paths /home/conan/.conan/data/mesa/19.3.1/bincrafters/stable/package/ef3d5fd75c61f59e0bbcbdba10f7ff46b8e5b0b8/lib/dri)
libGL error: failed to load driver: i965
libGL error: MESA-LOADER: failed to open swrast (search paths /home/conan/.conan/data/mesa/19.3.1/bincrafters/stable/package/ef3d5fd75c61f59e0bbcbdba10f7ff46b8e5b0b8/lib/dri)
libGL error: failed to load driver: swrast
[2020-02-06 11:44:09.381505] [0x00007fa42e712300] [error]   Failed to Create OpenGL Context

**Comment by ericLemanissier** [comment]
can you try to build mesa on your machine ? (by using `-b mesa` command line argument)

**Comment by FernandoVelcic** [comment]
It works! thanks a lot!
![image](https://user-images.githubusercontent.com/7217340/73954097-1b881a00-48e0-11ea-9e3c-ad8b11cdcf8f.png)

**Comment by ericLemanissier** [comment]
There is another solution: you should use the `virtualenv` generator, because mesa recipe sets the `LIBGL_DRIVERS_PATH`. This variable should help mesa find the dri drivers
