### ISSUE TITLE
cygwin_installer:bincrafters inclusion request

### ISSUE THREAD

**Issue by lasote** [bincrafters/community#112]
## Inclusion Request Review

@solvingj @SSE4 

This is a review for [cygwin_installer:bincrafters](https://github.com/bincrafters/conan-cygwin_installer) inclusion request to conan-center.
This review follows the [inclusion guidelines or third-party libraries](http://docs.conan.io/en/latest/uploading_packages/bintray/conan_center_guide.html#inclusion-guidelines-for-third-party-libraries).

### Package
cygwin_installer/2.9.0@bincrafters/stable

#### Recipe quality
- [x] Git public repository
- [x] Recipe fields
- [x] Linter
- [x] Updated
- [x]  Clean
- [x] test_package
- [x] Raise errors on invalid configurations
- [x] LICENSE of the recipe
- [x] LICENSE of the tool **I've not found it, but as we are extracting all the installer, I think it doesn't apply in this case**

#### CI Integration
- [ ]  CI configurations for Windows

I'm not sure if it is ok. I can't access the appveyor build when I click on the badge of the readme it tells me denied. Shouldn't it be public?

When I run:

   ` conan search cygwin_installer/2.9.0@bincrafters/stable --table /tmp/table.html`

![image](https://user-images.githubusercontent.com/3807515/36150774-0f0c56ce-10c5-11e8-9648-af7f3f546b98.png)

I think the "None" could be a Conan issue with the --table feature, that couldn't understand the `os_build` and other missing settings, but it looks like the package for x86 is not updated.

Looking at the build.py and appveyor.yml, I think it should upload both packages, so probably there is something wrong.

#### Bintray Package Information
- [x] Description
- [x] Licenses
- [x] Tags
- [x] Maturity
- [x] Website (if any)
- [x] Issue tracker
- [x] Version control
- [x] GitHub repo (user/repo)

**Comment by SSE4** [comment]
@lasote should be fixed
```
C:\projects\conan>conan search cygwin_installer/2.9.0@bincrafters/stable -r upload_repo
Existing packages for recipe cygwin_installer/2.9.0@bincrafters/stable:

    Package_ID: 11e6a84a7894f41df553e7c92534c3bf26896802
        [settings]
            arch: x86
            os: Windows
        outdated from recipe: True

    Package_ID: 456f15897172eef340fcbac8a70811f2beb26a93
        [options]
            additional_packages: None
        [settings]
            arch_build: x86_64
            os_build: Windows
        outdated from recipe: False

    Package_ID: b2fcbc60b3bee75023a4f7934cadb723eec550bd
        [options]
            additional_packages: None
        [settings]
            arch_build: x86
            os_build: Windows
        outdated from recipe: False

    Package_ID: ca33edce272a279b24f87dc0d4cf5bbdcffbc187
        [settings]
            arch: x86_64
            os: Windows
        outdated from recipe: True
```

**Comment by lasote** [comment]
Great. Accepting! Congrats!
