### ISSUE TITLE
SDL2/2.0.10: SDL_Init failed: No available video device

### ISSUE THREAD

**Issue by AnotherFoxGuy** [bincrafters/community#1121]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **SDL2/2.0.10**
  * Operating System+version: **Manjaro Linux**
  * Compiler+version: **GCC 9.2.0**
  * Conan version: **conan 1.22.0**
  * Python version: **Python 3.8.1**

### Conan profile 
```
# Profile generated by PMM 1.9.1
# https://github.com/AnotherFoxGuy/pmm

[settings]
os=Linux
os_build=Linux
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++11
arch=x86_64
arch_build=x86_64
build_type=Release

[options]

[env]
CC=/usr/bin/cc
CXX=/usr/bin/c++
```

### Steps to reproduce (Include if Applicable)

1. Download the test project here: https://github.com/AnotherFoxGuy/conan-sdl2-test
2. Build and run the test project
3. The executable crashes with `SDL_Init failed: No available video device`

If you downgrade SDL2 to version 2.0.9 the executable works fine

**Comment by JimmySnails** [comment]
SDL2 2.0.12 is available on bincrafters and it's still broken from 2.0.10 and upwards.

It basically prevents us (and other SDL2 based projects) to upgrade from 2.0.9 (next version have sprite batching and other fantastic features) or forces us to build the libraries manually.

This bug applies for all linux distributions

Are there any plans to fix this issue?

**Comment by Croydon** [comment]
Yes, certainly. 

I'm -assuming- that we are pretty close to shipping a solution

**Comment by SamuelHusky** [comment]
I'm also interested in an update to this as my project is broken on Linux right now.

Both video and audio fail to init with the following errors:

Video: No available video device
Audio: ALSA: Couldn't open audio device: No such file or directory

If I link against Manjaro's libSDL2 then both video and audio work fine. Not sure why it is defaulting to ALSA either, I would have expected pulseaudio.

**Comment by Croydon** [comment]
This should be solved for a while now. Can any of you re-try on your end please?

**Comment by Croydon** [comment]
Please make also sure that your local copy of the recipe is up to date, that your Conan version is up to date and that you use SDL 2.0.12

**Comment by ericLemanissier** [comment]
This recipe is now in the Conan Center Index.

Please migrate to the recipe version there.
If this is still an issue, please create a new issue in the Conan Center Index issue tracker.

Thanks!

https://conan.io/center/sdl
