### ISSUE TITLE
[question][qt] why does qt package do not append bin folder to PATH

### ISSUE THREAD

**Issue by yuriy-mochurad** [bincrafters/community#1124]
I have tried to use `qt 5.14.1` conan package and noticed that the only env variable it creates is `CMAKE_PREFIX_PATH`. This works perfect when project is being built with cmake.

But this doesn't work if there is a need to use same qt binaries, e.g. for test automation. I have tried to generate conan virtual environment and again it provides me only the `CMAKE_PREFIX_PATH` that contains root folder of the package. I can use that, but I also expected that package should append qt `bin` folder to the `PATH` variable. Is there any reason of not doing so?

**Comment by ericLemanissier** [comment]
Hi. Conan is able to add the bin folder to the PATH without setting it explicitely in package_info. You can either use tools.RunEnvironment, or the run_environment argument of self.run, or conan virtual environment generator.

**Comment by yuriy-mochurad** [comment]
@ericLemanissier I have just installed qt 5.14.1 on both osx and windows with virtual environment generated:
`conan install qt/5.14.1@bincrafters/stable -g=virtualenv --build=missing`
I have received generated virtual env files, but when I open the `environment.sh.env` file it mentions qt only in `CMAKE_PREFIX_PATH` . variable. Also trying to use qmake with activated env does not find `qmake` binary. Could you, please, let me know what am I doing wrong?

**Comment by ericLemanissier** [comment]
I was not being precise enough: you need to use [virtualrunenv generator](https://docs.conan.io/en/latest/mastering/virtualenv.html#virtualrunenv-generator)

**Comment by yuriy-mochurad** [comment]
@ericLemanissier yes, that does work. Thanks for quick support
