### ISSUE TITLE
depot_tools_installer/20200207: Bintray package content has faulty permissions

### ISSUE THREAD

**Issue by Tymolc** [bincrafters/community#1126]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: depot_tools_installer/20200207
  * Operating System+version: MacOS
  * Compiler+version: All
  * Conan version: All
  * Python version: All

### Steps to reproduce
The depot_tools_installer recipe has a step called `_fix_permissions`, which adds execution permissions to executable files in the package.
This step may have been skipped or didn't work correctly in the package uploaded to [bintray](https://bintray.com/bincrafters/public-conan/depot_tools_installer%3Abincrafters/20200207%3Astable#files/bincrafters%2Fdepot_tools_installer%2F20200207%2Fstable%2F0%2Fpackage%2F5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9%2F0).
Maybe the package did not go through the `package()` step or was created on Windows without MinGW (in which case the permissions would not be adapted)?
Either way, if `https://api.bintray.com/conan/bincrafters/public-conan` is set as a conan remote, a conan package that depends on depot_tools_installer will not be able to use the executables due to a `permission denied`.

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>
For example, when trying to build crashpad with the new depot_tools_installer version, this will happen (in this case on MacOS):

```

depot_tools_installer/20200207@bincrafters/stable: Not found in local cache, looking in remotes...
depot_tools_installer/20200207@bincrafters/stable: Trying with 'bintray'...
Downloading conanmanifest.txt
Downloading conanfile.py
depot_tools_installer/20200207@bincrafters/stable: Downloaded recipe revision 0

crashpad/20200207@nexenio/stable: Applying build-requirement: depot_tools_installer/20200207@bincrafters/stable
crashpad/20200207@nexenio/stable: Applying build-requirement: ninja/1.9.0
crashpad/20200207@nexenio/stable: Configuring sources in /Users/nexenio/.conan/data/crashpad/20200207/nexenio/stable/source

/bin/sh: /Users/nexenio/.conan/data/depot_tools_installer/20200207/bincrafters/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/gclient: Permission denied
```

Permissions (e.g. for `gclient`, but also for all other executables) look like this:

`-rw-r--r--   1 timoesterreich  staff   903B Feb 12 10:47 gclient`

</details>

**Comment by Croydon** [comment]
Could you please try again?

**Comment by Tymolc** [comment]
Works 👍 Thank you!
