### ISSUE TITLE
Inclusion request gflags to conan-center

### ISSUE THREAD

**Issue by lasote** [bincrafters/community#113]
## Inclusion Request Review

@solvingj @dimi309 @DariuszOstolski 

This is a review for [bincrafters / conan-gflags](https://github.com/bincrafters/conan-gflags) inclusion request to conan-center.
This review follows the [inclusion guidelines or third-party libraries](http://docs.conan.io/en/latest/uploading_packages/bintray/conan_center_guide.html#inclusion-guidelines-for-third-party-libraries).

### Package
gflags/2.2.1@bincrafters/stable

#### Recipe quality
- [x] Git public repository
- [x] Recipe fields
- [x] Linter
- [x] Updated
- [x]  Clean
- [x] test_package
- [x] Raise errors on invalid configurations
- [x] LICENSE of the recipe
- [x] LICENSE of the tool

#### CI Integration
- [x] (If not header only) CI configurations for Linux/MacOSX/Windows

1. Missing Macos CI

![image](https://user-images.githubusercontent.com/3807515/36156802-74eb91ae-10d8-11e8-8aab-1651258adf51.png)

2. A lot of outdated packages, it looks like you introduced a new "nothreads" option and now the rest are dead packages (unreachable), please, delete them, you could use the `conan remove gflags/2.2.1@bincrafters/stable --outdated -r bincrafters` (we didn't try this against bintray, let us know how it goes and if it doesn't remove more than the expected LoL)

![image](https://user-images.githubusercontent.com/3807515/36159108-3a1bda88-10de-11e8-952b-a257927f2a8c.png)

#### Bintray Package Information
- [x] Description
- [x] Licenses
- [x] Tags
- [x] Maturity
- [x] Website (if any)
- [x] Issue tracker
- [x] Version control
- [x] GitHub repo (user/repo)

**Comment by dimi309** [comment]
I have no access to change it directly but it seems to me that, once again, macos CI was removed while trying out circleci. It shouldn't be much trouble to reactivate, since this package [was building successfully on macos](https://travis-ci.org/bincrafters/conan-gflags/builds/317352767).

**Comment by SSE4** [comment]
I've removed outdated packages from our repository
I've also re-enabled OSX on testing branch, but unfortunately it failed with the following error:
`/Users/travis/.travis/job_stages: line 166: shell_session_update: command not found`
see also https://travis-ci.org/bincrafters/conan-gflags/jobs/341045987
would be nice if someone can take a look

**Comment by solvingj** [comment]
Should be fixed now, @lasote please review at your leisure.

**Comment by lasote** [comment]
Hi! for me it is ok, but the table shows some yellow entries for the osx x86, did the remove of the outdated fail? did you change something later? it should be blank squares. Any hint? Mostly to discard a hidden bug

![image](https://user-images.githubusercontent.com/3807515/36194979-19ff190c-116c-11e8-83dc-8e7b947946e7.png)

**Comment by SSE4** [comment]
nope, it didn't fail

**Comment by lasote** [comment]
Could you try again?

**Comment by SSE4** [comment]
done, no errors

**Comment by lasote** [comment]
All green! :) We are accepting ASAP. Congrats again! you are doing high quality packages ;)
