### ISSUE TITLE
libmad/0.15.1b@bincrafters/stable: Does not compile in Release / RelWithDebInfo with Visual Studio

### ISSUE THREAD

**Issue by JimmySnails** [bincrafters/community#1130]
libmad is a dependency of SDL2_Mixer. It fails with Visual Studio 2017 and 2019 when choosing any other configuration than debug. 

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libmad/0.15.1b**
  * Operating System+version: **Windows 10 1909**
  * Compiler+version: **Visual Studio 2017 and 2019**
  * Docker image: **n/A**
  * Conan version: **conan 1.22.0**
  * Python version: **Python 3.8.1**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
build_type=Release
[options]
[build_requires]
[env]

```

### Steps to reproduce (Include if Applicable)
Just use libmad, it'll fail.

### Logs (Include/Attach if Applicable)
Unfortunately there's no detailed hint...

```
libmad/0.15.1b@bincrafters/stable: ERROR: Package '75ed07303f056424be45ffb582032fe7ad980a95' build failed
libmad/0.15.1b@bincrafters/stable: WARN: Build folder C:\Users\talan\.conan\data\libmad\0.15.1b\bincrafters\stable\build\75ed07303f056424be45ffb582032fe7ad980a95
ERROR: libmad/0.15.1b@bincrafters/stable: Error in build() method, line 44
        self._build_msvc()
while calling '_build_msvc', line 61
        msbuild.build(project_file="libmad.vcxproj")
        ConanException: Error 1 while executing echo Conan:vcvars already set && devenv "libmad.vcxproj" /upgrade && msbuild "libmad.vcxproj" /p:Configuration="RelWithDebInfo" /p:UseEnv=true /p:Platform="x64" /m:12 /p:PlatformToolset="v142" /verbosity:minimal /p:ForceImportBeforeCppTargets="C:\Users\talan\.conan\data\libmad\0.15.1b\bincrafters\stable\build\75ed07303f056424be45ffb582032fe7ad980a95\source_subfolder\msvc++\conan_build.props"
CMake Error at D:/Repos/git/build/_pmm/1.9.1/conan.cmake:488 (message):
  Conan install failed [1]
```

</details>

**Comment by Croydon** [comment]
Could you try to `conan install libmad/0.15.1b@ --build libmad` please?

libmad is already in the CCI, but sdl2_mixer has currently some other problems so there isn't a stable version yet, which uses libmad from CCI

So please try if you can install libmad from CCI on its own

**Comment by JimmySnails** [comment]
Thx for the quick reply! How can i tell conan to build the x64 library? -s arch=x86_64 does not work and it still fails with 
```
.\Release\bit.obj : fatal error LNK1112: Modul-Computertyp "x86" steht in Konflikt mit dem Zielcomputertyp "x64". [C:\Users\talan\.conan\data\libmad\0.15.1b\_\_\build\3fb49604f9c2f729b85ba3115852006824e72cab\source_subfolder\msvc++\libmad.vcxproj]
```

(sry, it's german...) 
which means trying to build x86 on x64

**Comment by JimmySnails** [comment]
ok, it added `libmad/0.15.1b` to my conanfile and it resolved the issue. 
Should we close this issue or do you want to keep it until SDL2Mixer is fixed?

**Comment by Croydon** [comment]
Since it is a libmad issue and we migrated libmad to CCI already, this issue can be closed

Thanks for testing!
