### ISSUE TITLE
mongo-c-driver/all: Package ID does not include conditional dependencies

### ISSUE THREAD

**Issue by jargonzombies** [bincrafters/community#1132]
The mongo-c-driver conanfiles for all versions do not properly handle several dependencies that are included in the build if autodetected. The package id does not reflect any autodetected dependencies.

I have a branch open for the newest library release [here](https://github.com/jargonzombies/conan-mongo-c-driver/tree/testing/1.16.1). That `conanfile` disables all `AUTO` options in mongo-c-driver's CMake except for ICU, which is explicitly modeled as an option and a dependency since it already exists in bincrafters. That should ensure a consistent ABI and dependency list.

I'm not sure about the workflow here regarding branches. Principally, I think what is necessary is to fix all existing branches and increment a build number.

### Package and Environment Details
  * Package Name/Version: **mongo-c-driver/any**
  * Operating System+version: **Linux Ubuntu 19.10**
  * Compiler+version: **GCC 9**
  * Conan version: **conan 1.22.0**
  * Python version: **Python 3.7.5**

**Comment by uilianries** [comment]
Hi @jargonzombies could you please open a PR with your branch ?

**Comment by jargonzombies** [comment]
@uilianries I can't, because there is no testing/1.16.1 branch yet.

But I can make separate PRs to all the existing branches, if that works for you?

**Comment by uilianries** [comment]
Done, I've opened a new branch for 1.16.0. Please, open your PR there.

**Comment by Croydon** [comment]
Merged, thanks!
