### ISSUE TITLE
[question] cppcheck_installer/1.90

### ISSUE THREAD

**Issue by mjvk** [bincrafters/community#1133]
I seemed to have added version 1.90 as stable. I pushed this to the bincrafters repo accidentally and was surprised it worked. I think the stable branch is missing protection there.

**Comment by Croydon** [comment]
I just found this issue. I previously commented on https://github.com/bincrafters/conan-cppcheck_installer/commit/6934f5826aa8e2141af0658fd3980bc45ed82d22 😄  

Actually, protecting new branches from getting created is a bit tricky. I have enabled protection that CI needs to pass first. This might do the trick.

I have created a `testing/1.90` branch
