### ISSUE TITLE
mongo-cxx-driver/all: no fPIC

### ISSUE THREAD

**Issue by jargonzombies** [bincrafters/community#1134]
None of the mongo-cxx-driver `conanfile`s have an `fPIC` option though static builds are possible.

It might be worth resolving #1132 first to make a new version that has working dependencies.

**Comment by jargonzombies** [comment]
@Croydon Could you open a testing/3.4.0 branch on `mongo-cxx-driver` for me so I can work on a PR?

**Comment by Croydon** [comment]
Done 😄

**Comment by pigubaoza** [comment]
Hi, I would like to understand better. Does this mean that even though we are able to build a static mongo-cxx library, we are unable to link it to another project because it lacks fPIC? 
If not, how else would I be able to link a static mongo-cxx library into another project?

**Comment by Croydon** [comment]
This recipe is now in the [Conan Center Index](https://github.com/conan-io/conan-center-index/).

Please migrate to the recipe version there. 
If this is still an issue, please create a new issue in the [Conan Center Index issue tracker](https://github.com/conan-io/conan-center-index/issues).

Thanks!
