### ISSUE TITLE
libpng/1.6.37: build fails on macos because of zlib version

### ISSUE THREAD

**Issue by bertrandGuyot** [bincrafters/community#1135]
It seems the build step uses a different zlib than the configure step.
We were able to bypass the issue by adding few lines in the _configure_cmake function:

        if self.settings.os == "Macos":
            cmake.definitions["ZLIB_LIBRARY"] = self.deps_cpp_info["zlib"].libs[0]
            cmake.definitions["ZLIB_INCLUDE_DIR"] = self.deps_cpp_info["zlib"].include_paths[0]

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libpng/1.6.37**
  * Operating System+version: **MacOS Catalina Version 10.15.3**
  * Compiler+version: **clang 11.0**
  * Conan version: **conan 1.22.0**
  * Python version: **Python 3.6.9**

### Conan profile
```
Configuration for profile default:
[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=11.0
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
conan install libpng/1.6.37@bincrafters/stable --build=missing

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
...
[ 60%] Building C object source_subfolder/CMakeFiles/png_static.dir/pngget.c.o
In file included from ~/.conan/data/libpng/1.6.37/bincrafters/stable/build/a468ffad8adea3fcab8dd371aecce5321635f9fc/source_subfolder/pngrio.c:21:
~/.conan/data/libpng/1.6.37/bincrafters/stable/build/a468ffad8adea3fcab8dd371aecce5321635f9fc/source_subfolder/pngpriv.h:920:4: error: ZLIB_VERNUM != PNG_ZLIB_VERNUM       "-I (include path) error: see the notes in pngpriv.h"
#  error ZLIB_VERNUM != PNG_ZLIB_VERNUM \
   ^
In file included from
~/.conan/data/libpng/1.6.37/bincrafters/stable/build/a468ffad8adea3fcab8dd371aecce5321635f9fc/source_subfolder/png.c:14:
~/.conan/data/libpng/1.6.37/bincrafters/stable/build/a468ffad8adea3fcab8dd371aecce5321635f9fc/source_subfolder/pngpriv.h:920:4: error: ZLIB_VERNUM != PNG_ZLIB_VERNUM       "-I (include path) error: see the notes in pngpriv.h"
#  error ZLIB_VERNUM != PNG_ZLIB_VERNUM \
   ^
...
```

</details>

**Comment by Croydon** [comment]
This recipe is now in the [Conan Center Index](https://github.com/conan-io/conan-center-index/).

Please migrate to the recipe version there. 
If this is still an issue, please create a new issue in the [Conan Center Index issue tracker](https://github.com/conan-io/conan-center-index/issues).

Thanks!
