### ISSUE TITLE
thrift_installer/0.13.0: fails to build

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [bincrafters/community#1137]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **thrift_installer/0.13.0**
  * Operating System+version: **Windows 10**
  * Compiler+version: **Visual Studio 2017**
  * Conan version: **conan 1.22.2**
  * Python version: **Python 3.8.1**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Windows
os_build=Windows
arch=x86
arch_build=x86
compiler=Visual Studio
compiler.version=15
compiler.toolset=v141
build_type=Debug
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
conan install thrift_installer/0.13.0@bincrafters/stable -r bincrafters --build missing

### Logs (Include/Attach if Applicable)
<details><summary>
</summary>

```
thrift_installer/0.13.0@bincrafters/stable: Generator cmake created conanbuildinfo.cmake
thrift_installer/0.13.0@bincrafters/stable: Calling build()
thrift_installer/0.13.0@bincrafters/stable: WARN: CMake generator could not be deduced from settings
thrift_installer/0.13.0@bincrafters/stable:
thrift_installer/0.13.0@bincrafters/stable: ERROR: Package 'b36a351ee873d96c7e2636c65307b23d0f459eaa' build failed
thrift_installer/0.13.0@bincrafters/stable: WARN: Build folder C:\Users\mirko.vonleipzig\.conan\data\thrift_installer\0.13.0\bincrafters\stable\build\b36a351ee873d96c7e2636c65307b23d0f459eaa
ERROR: thrift_installer/0.13.0@bincrafters/stable: Error in build() method, line 27
        cmake.configure(build_folder=self._build_subfolder)
        ConanException: CMake does not support toolsets with generator "None:.Please check your conan profile to either remove the toolset, or change the CMake generator.
```

</details>

**Comment by uilianries** [comment]
@Mirko-von-Leipzig Seems like CMake didn't find any generator. Did you try configuring the env var:

    set CONAN_CMAKE_GENERATOR="Visual Studio 14 2015"

Regards!

**Comment by Mirko-von-Leipzig** [comment]
That let it successfully compile, thanks (using "Visual Studio 15 2017" to match my profile).

I've never had to do that before - is there something missing in my profile or why was it not able to deduce that?

**Comment by uilianries** [comment]
Probably something is missing in your environment. Like, detecting your default compiler by msvc environment variables. Usually, I run that specific prompt command provided by Visual Studio.

Anyway, you can configure your conan profile to force it, but it's a workaround only.
