### ISSUE TITLE
conan-protobuf/3.6.1: OnShutdownDelete shadowing errors

### ISSUE THREAD

**Issue by AltenOosterbeek** [bincrafters/community#1138]
Hi,

I was trying to use conan-protobuf v3.6.1, but unfortunately ran into shadowing errors, similar to what is described at https://github.com/protocolbuffers/protobuf/issues/4887.
It is a very small fix in protobuf.patch, only adding
`diff --git a/src/google/protobuf/stubs/common.h b/src/google/protobuf/stubs/common.h
index d35377ae5..585e0128b 100644
--- a/src/google/protobuf/stubs/common.h
+++ b/src/google/protobuf/stubs/common.h
@@ -206,7 +206,7 @@ LIBPROTOBUF_EXPORT void OnShutdownRun(void (*f)(const void*), const void* arg);

 template <typename T>
 T* OnShutdownDelete(T* p) {
-  OnShutdownRun([](const void* p) { delete static_cast<const T*>(p); }, p);
+  OnShutdownRun([](const void* pp) { delete static_cast<const T*>(pp); }, p);
   return p;
 }`
So hopefully, this can be included in the v3.6.1 conan package as well.

Thanks in advance.

Cheers,

**Comment by Croydon** [comment]
This recipe is now in the [Conan Center Index](https://github.com/conan-io/conan-center-index/).

Please migrate to the recipe version there. 
If this is still an issue, please create a new issue in the [Conan Center Index issue tracker](https://github.com/conan-io/conan-center-index/issues).

Thanks!
