### ISSUE TITLE
gtest package: gmock by default?

### ISSUE THREAD

**Issue by lasote** [bincrafters/community#114]
Hi guys, @lippertto opened an issue in my gtest repository and I think we could attend it better here, where the officially conan-center package is maintaned. What do you think? What are the reasons to default to False the inclusion of gmock? 

> Hello @lasote, thanks for providing the link to the bincrafters repository.
By default, the packages do not provide the gmock headers. For me, this is unexpected because gmock comes usually bundled with gtest. But I do now know what people will expect in general :-)
However, if I set the build_gmock option to True, and use --build missing , the library is built, and the headers are availabe. So that works for me. The only question is, whether the flag should be set to True or False by default.

### Package Details (Include if Applicable)
* Package Name/Version: **gtest/1.8.0**
* Operating System: **All**

**Comment by dimi309** [comment]
The idea was to keep v1.8 working like v1.7 by default. If it wasn't a good one, please (whoever has access) feel free to change it.

**Comment by solvingj** [comment]
We're going to change gmock default to true and rebuild.  Will report back when done.

**Comment by lasote** [comment]
I was checking and I had just the opposite: 
`cmake.definitions["BUILD_GTEST"] = "ON" if self.options.no_gmock else "OFF"`
So gmock by default

**Comment by lasote** [comment]
Yeah, my recipe hasn't gmock by default but I think enable it by default is better.

**Comment by solvingj** [comment]
Changed default of `build_gmock` to `True` and pushed to CI.
