### ISSUE TITLE
qt/5.14.1: Cannot find -lxcb-xkb when linking Qt

### ISSUE THREAD

**Issue by wouterbeek** [bincrafters/community#1141]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.14.1**
  * Operating System+version: **Linux Ubuntu 19.10**
  * Compiler+version: **GCC 9.2.1**
  * Conan version: **conan 1.22.2**
  * Python version: **Python 3.7.5**

### Conan profile

```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce

Store the following in dummy source file `test.cpp`:

```cpp
int main(){}
```

and store the following in `CMakeLists.txt`:

```cmake
cmake_minimum_required(VERSION 3.16.4)
project(test LANGUAGES CXX)

if(NOT EXISTS ${CMAKE_BINARY_DIR}/conan.cmake)
  file(
    DOWNLOAD "https://github.com/conan-io/cmake-conan/raw/v0.14/conan.cmake"
    ${CMAKE_BINARY_DIR}/conan.cmake)
endif()
include(${CMAKE_BINARY_DIR}/conan.cmake)
conan_cmake_run(
  BASIC_SETUP CMAKE_TARGETS
  BUILD missing
  REQUIRES qt/5.14.1@bincrafters/stable)

find_package(Qt5 REQUIRED Core)

set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTOUIC ON)
set(CMAKE_AUTORCC ON)

add_executable(test test.cpp)
target_link_libraries(test CONAN_PKG::qt)
```

Run the following commands:

```sh
mkdir Debug && cd Debug
cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_VERBOSE_MAKEFILE=ON
cmake --build .
[qt.log](https://github.com/bincrafters/community/files/4272122/qt.log)
```

Observe the following error:

```
/usr/bin/ld: cannot find -lxcb-xkb
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/test.dir/build.make:187: bin/test] Error 1
make[2]: Leaving directory '/home/wouter/cpp/my-gui/Debug'
make[1]: *** [CMakeFiles/Makefile2:80: CMakeFiles/test.dir/all] Error 2
make[1]: Leaving directory '/home/wouter/cpp/my-gui/Debug'
make: *** [Makefile:87: all] Error 2
```

### Logs

The full logs are attached.

**Comment by ericLemanissier** [comment]
your log says 
```
-- Library xcb not found in package, might be system one
-- Library xcb-xkb not found in package, might be system one
```
which is surprising, because these should be in /home/wouter/.conan/data/libxcb/1.13.1/bincrafters/stable/package/b8c98b327e58b392e50971217071e1166220829f/lib. are they?
can you try to update the recipes by using --update argument ?

As a workaround, If you don't mind using system packages, you can install "libxcb-xkb-dev"

**Comment by wouterbeek** [comment]
> these should be in /home/wouter/.conan/data/libxcb/1.13.1/bincrafters/stable/package/b8c98b327e58b392e50971217071e1166220829f/lib. are they?

**Comment by wouterbeek** [comment]
@ericLemanissier Thanks for looking into my problem.

> your log says
> -- Library xcb not found in package, might be system one
> -- Library xcb-xkb not found in package, might be system one

I don't know how it determines that.  According to APT I did not have `libxcb-xkb-dev` installed...

> these should be in /home/wouter/.conan/data/libxcb/1.13.1/bincrafters/stable/package/b8c98b327e58b392e50971217071e1166220829f/lib. are they?

Yes, they are in that directory (lots of `.so` files).

> can you try to update the recipes by using --update argument ?

I don't know how that works?  In my MWE I do not have a separate Conan file.  The requirements are specified using CMake-Conan.

> As a workaround, If you don't mind using system packages, you can install "libxcb-xkb-dev"

Yes, that works.

> EDIT: can you try to require xkbcommon/0.10.0@bincrafters/stable too ?

Yes, that works too.

**Comment by ericLemanissier** [comment]
ok, it should be solved with https://github.com/bincrafters/conan-qt/commit/39492329fb95ac2e2e1b9a9b37cfc5f74ef4f81c then

**Comment by wouterbeek** [comment]
Thanks!
