### ISSUE TITLE
Qt Add Conan install options

### ISSUE THREAD

**Issue by jsfdez** [bincrafters/community#1142]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt**

### Description of your feature

The readme file of the repository does not include the options required to use submodules of Qt (like Qt Quick Controls 2). It would be useful to document them to allow users to be able to create other applications than widget-based.

**Comment by Croydon** [comment]
We stopped documenting options in the README a while ago. Qt did had it until like 8h ago (https://github.com/bincrafters/conan-qt/pull/49), but it really isn't something that is maintainable.

Our end goal is to get things into the Conan Center Index and recipes don't have individual readmes there either.

**Comment by jsfdez** [comment]
I see! Fair enough.

Thank you :)
