### ISSUE TITLE
qt/5.14.1 - Library is not compiled with Vulkan support

### ISSUE THREAD

**Issue by jroweboy** [bincrafters/community#1144]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.14.1**
  * Operating System+version: **All** (At least Windows MSVC 2019 in my personal test, but i couldn't find any build system that had it enabled)
  * Compiler+version: **All**
  * Conan version: **Latest**
  * Python version: **Latest**

### Description of your feature

Starting from Qt 5.10, Qt added Vulkan support in the form of QVulkanWindow and similar classes. https://www.qt.io/blog/2017/06/06/vulkan-support-qt-5-10-part-1 These need to be compiled into the Qt build in order to be usable at run time, and so the vulkan headers and SDK needs to be present at Qt configure and build time in order for it to support it at run time. I'm working on a project that uses QVulkanWindow and wanted to move them over to conan, but this is a soft blocker for that change.

**Comment by ericLemanissier** [comment]
Thanks for the report. There is currently no conan package for vulkan: https://github.com/conan-io/wishlist/issues/144, so we have to rely on system level vulkan. If you install it on your machine and rebuilt the qt package, does it still miss the vulkan classes ?

**Comment by Cscotttaakan** [comment]
I'm actually having this issue as well. It's not able to resolve `QVulkanInstance` and other vulkan types. This is definitely an issue for me.

**Comment by ericLemanissier** [comment]
can you send the config.log file which can be found in the folder ~\.conan\data\qt\5.14.2\bincrafters\stable\build\ ?

**Comment by Cscotttaakan** [comment]
There is no build folder, when should that be triggered?
I'm using command `conan install . -if={folder} --build missing -s build_type=Debug`

**Comment by ericLemanissier** [comment]
so you are probably reusing an existing binary from bincrafters' bintray. It's true that they don't have Vulkan classes. you need to build qt on your machine to get them. You can do this by using argument `--build qt`
