### ISSUE TITLE
libuvc/0.0.6: libuvc does not build with CONAN_V2_MODE

### ISSUE THREAD

**Issue by Morwenn** [bincrafters/community#1146]
I was trying to build my library stack with the `CONAN_V2_MODE` introduced in Conan 1.23 and it appears that the libuvc recipe does not work with that mode: it accesses `self.options` in `source()`, which isn't allowed in that mode.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libuvc/0.0.6**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **GCC 7**
  * Conan version: **conan 1.23.0**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=7
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

`export CONAN_V2_MODE=1` then try to create a libuvc package.

### Logs (Include/Attach if Applicable)

I'm using a copied version of the `libuvc` recipe, but the error exists in the original `bincrafters` recipe.

```libuvc/0.0.6@my-company/stable: Configuring sources in ~/.conan/data/libuvc/0.0.6/my-company/stable/source
libuvc/0.0.6@my-company/stable: SCM: Getting sources from url: 'https://github.com/microsoft/libuvc.git'
ERROR: libuvc/0.0.6@my-company/stable: Error in source() method, line 60
	if self.options.jpeg_turbo:
	ConanV2Exception: Conan v2 incompatible: 'self.options' access in source() method is deprecated

```

**Comment by Morwenn** [comment]
Just moving the contents of `source()` to the beginning of `build()` seems to be enough to get things working.

**Comment by Croydon** [comment]
Should be fixed via https://github.com/bincrafters/conan-libuvc/commit/fe07792bb8c6318aa50343de3f9f2d2f0e70086c

**Comment by Morwenn** [comment]
Thanks a lot!
