### ISSUE TITLE
Inclusion request conan-center glog

### ISSUE THREAD

**Issue by lasote** [bincrafters/community#115]
## Inclusion Request Review

@solvingj @dimi309 @sigmoidal 

This is a review for [bincrafters / conan-glog](https://github.com/bincrafters/conan-glog) inclusion request to conan-center.
This review follows the [inclusion guidelines or third-party libraries](http://docs.conan.io/en/latest/uploading_packages/bintray/conan_center_guide.html#inclusion-guidelines-for-third-party-libraries).

### Package
glog/0.3.5@bincrafters/stable

#### Recipe quality
- [x] Git public repository
- [x] Recipe fields
- [x] Linter
- [x] Updated
- [ ] Other
- [x] Clean
- [x] test_package
- [x] Raise errors on invalid configurations
- [x] LICENSE of the recipe
- [x] LICENSE of the tool

The require is using version ranges, we think the versions in conan center should be fixed:

    `self.requires("gflags/[>=2.2]@bincrafters/stable")`

In the build, the `BUILD_SHARED_LIBS` is automatically managed by the CMake helper so it shouldn't be necessary:

`cmake.definitions["BUILD_SHARED_LIBS"] = self.options.shared`

#### CI Integration
- [x] (If not header only) CI configurations for Linux/MacOSX/Windows

1. Missing Macos CI

![image](https://user-images.githubusercontent.com/3807515/36204117-4168ea04-118a-11e8-9225-15b1f0fa0cfe.png)

2. Outdated packages for clang 7.3. If there are not supported anymore (I'm ok with that) it's better to remove them:
 
 `conan remove glog/0.3.5@bincrafters/stable --outdated -r bincrafters`

![image](https://user-images.githubusercontent.com/3807515/36204170-6e94af5e-118a-11e8-8628-6c5c47f368c7.png)

#### Bintray Package Information
- [x] Description
- [x] Licenses
- [x] Tags
- [x] Maturity
- [x] Website (if any)
- [x] Issue tracker
- [x] Version control
- [x] GitHub repo (user/repo)

**Comment by lasote** [comment]
The apple-clang are back, please remove the outdated:
`conan remove glog/0.3.5@bincrafters/stable --outdated -r bincrafters`

**Comment by solvingj** [comment]
Done i think :)

**Comment by lasote** [comment]
Where are in! Congrats!
