### ISSUE TITLE
zmq/4.3.1: build from sources fails due to wrong references to source

### ISSUE THREAD

**Issue by AltenOosterbeek** [bincrafters/community#1151]
# Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **zmq/4.3.1**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Conan version: **conan 1.18.0**
  * Tried with multiple conan profiles...

### Steps to reproduce (Include if Applicable)
When adding zmq/4.3.1 as a required package, I use conan create to build the package, but it gives the following error:
```
ERROR: libsodium/1.0.16@bincrafters/stable: Error in source() method, line 33
        tools.get(source_url, sha256=sha256)
        NotFoundException: Not found: https://download.libsodium.org/libsodium/releases/libsodium-1.0.16.tar.gz
```
This is due to the fact the 1.0.16 has been moved to the old/ subdirectory, so the correct link is then: https://download.libsodium.org/libsodium/releases/old/libsodium-1.0.16.tar.gz

Please change this. Thanks in advance!

Kind regards,

Wouter Oosterbeek

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
Put your log output here
```

</details>

**Comment by Croydon** [comment]
This recipe is now in the [Conan Center Index](https://github.com/conan-io/conan-center-index/).

Please migrate to the recipe version there. 
If this is still an issue, please create a new issue in the [Conan Center Index issue tracker](https://github.com/conan-io/conan-center-index/issues).

Thanks!

**Comment by Croydon** [comment]
PS: The name changed to `zeromq`: https://conan.io/center/zeromq/4.3.2/?user=_&channel=_

**Comment by AltenOosterbeek** [comment]
Thanks for the quick response. However, I would like to keep using 4.3.1, otherwise I get a lot of deprecated errors, which I would rather fix a little later...
Since 4.3.2 uses libsodium/1.0.18 the same problem doesn't exist there.
Should I still put the issue on conan-center? Because there is nu 4.3.1 there.

**Comment by Croydon** [comment]
Can zeromq/4.3.1 use libsodium/1.0.18?

If so you can put `libsodium/1.0.18` in your conanfile to overwrite the version

**Comment by AltenOosterbeek** [comment]
That seems to be working! Thanks for the tip, unfortunately I didn't think about it myself hahah
