### ISSUE TITLE
[icu] conan-icu repo should have a master or develop branch

### ISSUE THREAD

**Issue by datalogics-robb** [bincrafters/community#1153]
### Github repository for conan-icu https://github.com/bincrafters/conan-icu
  * Package Name/Version: **icu/ALL**
  
### create a master branch
As new versions of ICU are released, we need a place to submit PRs for supporting them.
Currently there are branches for each release 
   testing/64.1
   stable/64.1

This leaves no obvious base branch to submit a PR for a new version.

**Comment by Croydon** [comment]
As answered in https://github.com/bincrafters/conan-icu/pull/31 just open pull requests with new versions against the current default branch, we can create and switch the target branch afterwards then

I see absolutely no way to solve this in a smarter way

**Comment by Croydon** [comment]
I created a `testing/66.1` branch

**Comment by datalogics-robb** [comment]
What would be the problem with creating a branch called "master" or the like?

**Comment by Croydon** [comment]
It would not solve the problem and we would have just one more branch with no clear role in our workflow 😄
