### ISSUE TITLE
glew:2.1.0 Add fPic option

### ISSUE THREAD

**Issue by Mazrog** [bincrafters/community#1158]
### Package and Environment Details 
  * Package Name/Version: **glew/2.1.0**
  * Operating System+version: **Linux Manjaro 19.02**
  * Compiler+version: **g++-9.0**
  * Conan version: **Conan 1.23**
  * Python version: **Python 3.8.2**

### Description of your feature
Trying to migrate a glew opengl application with conan, ` glew/2.1.0@bincrafters/stable` is asking to be compiled with fPIC option:

`/usr/bin/ld: /home/mazrog/.conan/data/glew/2.1.0/bincrafters/stable/package/9cc0cfd28c986cd076d8c3c0c7b2a4492f780054/lib/libGLEWd.a(glew.c.o): relocation R_X86_64_32 against « __glewCopyTexSubImage3D » can not be     used when making a shared object; recompile with -fPIC
`
Would it be possible to add the option to the package?

**Comment by ericLemanissier** [comment]
This recipe was transferred on Conan Center Index, and it now has the fPIC option: https://github.com/conan-io/conan-center-index/blob/master/recipes/glew/all/conanfile.py#L17
Thanks for the report!
