### ISSUE TITLE
glfw/3.3: why does it need mesa on linux?

### ISSUE THREAD

**Issue by cstoitner** [bincrafters/community#1159]
After updating to a new revision of the glfw/3.3 package my application stopped working. After installing this package for clang-9 und rebuilding my project, running it gives several errors like this:
```
libGL error: MESA-LOADER: failed to open i965 (search paths /home/conan/.conan/data/mesa/19.3.1/bincrafters/stable/package/f58780b39a582cde6f22ad3540227024a8563072/lib/dri)
libGL error: failed to load driver: i965
```
The error message looks identical to https://github.com/bincrafters/community/issues/1119.
While this is probably just a wrong hard-coded path in the prebuild package (I don't have a user conan on this system), it made me look closer at the changes in the build file.

Why does glfw depend on mesa at all? A previous revision of the package just used whatever libgl is installed on the system. The glfw site also doesn't list mesa as a dependency. In fact I am pretty sure libgl is completely optional for glfw at build and run-time. Mesa also isn't the only provider for libgl on linux.
Running a different opengl driver than the one installed in the system is just asking for trouble. How is this supposed to work for people not using a mesa based driver?

Note that for windows the package doesn't depend on any opengl drivers either.

**Comment by VladasZ** [comment]
Also glfw/3.3 fails to build on Raspberry Pi because of mesa build error #1169 .
glfw/3.2.1@bincrafters/stable builds without problems.

**Comment by ericLemanissier** [comment]
fixed with https://github.com/bincrafters/conan-glfw/commit/769640f624d6949485ce6632d851efb2b8db2daf
