### ISSUE TITLE
sdl2/2.0.12: Unable to search/install sdl2

### ISSUE THREAD

**Issue by akshit-sharma** [bincrafters/community#1164]
I am not able to search or install sdl2 using Conan. Bincrafters does have the [repo](https://github.com/bincrafters/conan-sdl2) for it. 
1. I am confused it I am using the Conan search wrong or conan does not have any package for sdl2. 
2. Similarly, I am not able to install sdl2/2.0.8 which was [fixed](https://github.com/bincrafters/community/issues/329).
3. Also, where can I know the difference between bincrafters and bintray?

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **sdl2/2.0.12**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **GCC 8.3**
  * Conan version: **conan 1.23.0**
  * Python version: **Python 3.6.9**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=8.3
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
Search for sdl2 : `conan search sdl2`
Install sdl2 using bincrafters : `conan install sdl2/2.0.12@bincraters/stable`
Install sdl2 using bintray :  `conan install sdl2/2.0.12@bintray/stable`

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
akshit:cmake-build-debug$ conan search *sdl2*
There are no packages matching the '*sdl2*' pattern
akshit:cmake-build-debug$ conan install sdl2/2.0.12@bincraters/stable
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=8.3
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

sdl2/2.0.12@bincraters/stable: Not found in local cache, looking in remotes...
sdl2/2.0.12@bincraters/stable: Trying with 'conan-center'...
sdl2/2.0.12@bincraters/stable: Trying with 'conan-community'...
sdl2/2.0.12@bincraters/stable: Trying with 'bincrafters'...
ERROR: Unable to find 'sdl2/2.0.12@bincraters/stable' in remotes
akshit:cmake-build-debug$ conan install sdl2/2.0.12@bintray/stable
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=8.3
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

sdl2/2.0.12@bintray/stable: Not found in local cache, looking in remotes...
sdl2/2.0.12@bintray/stable: Trying with 'conan-center'...
sdl2/2.0.12@bintray/stable: Trying with 'conan-community'...
sdl2/2.0.12@bintray/stable: Trying with 'bincrafters'...
ERROR: Unable to find 'sdl2/2.0.12@bintray/stable' in remotes
akshit:cmake-build-debug$ 
```

</details>

**Comment by Croydon** [comment]
Bintray is our host of our Conan repository.

`conan install sdl2/2.0.12@bincrafters/stable` 

You had a typo there: You wrote `bincraters` instead of `bincrafters`
