### ISSUE TITLE
Inclusion Request: libcds

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [bincrafters/community#1176]
### Package Details
  * Package Name: **libcds**
  * Operating Systems+versions: **Linux-based**
  * Compiler support: **gcc, clang**
  * Conan recipe repository: **https://github.com/ZaMaZaN4iK/conan-libcds**

### Inclusion request
  * Fill all checkboxes with x if you agree with the statement or if it applies to your Conan recipe
  * [x] I want that my Conan recipe is getting included into the Bincrafters organisation
  * [x] I understand that if my request is accepted we are cloning your repository with all its history into Bincrafters, adapt some configurations and meta data if needed, and publishing it under the Bincrafters name and accounts
  * [ ] I have used the Bincrafters templates to develop my Conan recipe - https://github.com/bincrafters/templates
  * [x] My Conan recipe and all parts of it are licensed under the MIT license - https://choosealicense.com/licenses/mit/
    * Bincrafters are releasing all recipes under MIT license. If you want to have your recipe within Bincrafters we kindly ask you to do the same
    * it is okay if your test_package contains code from the upstream project under the upstream project's license, as long as it is clearly mentioned within the test_package files
  * [x] My Conan recipe covers (at least) the latest stable version which is available for the package
  * [ ] I know that my Conan recipe is working on all operating system and compilers mentioned above right now
    * if not: please provide here links to your CI platforms and / or build logs and describe the problems you encounter
  * [ ] I'm willing to help to maintain the recipe even after it is included into Bincrafters

That's my try to push package for `libcds` library into Conan. This package has unfinished state (I think it doesn't work on Windows platform (since library author recommends use `.sln` for building on Windows)), but I think it can be finished.

I want to see this package in Conan since `vcpkg` has included a package for `libcds` 1.5 year ago.

I've tested this package locally on Fedora 31 only with Clang 9.

Also this package doesn't provide configurations, which is possible for building directly from `CMake` (like switching between standard and Boost atomic primitives).

I hope Bincrafter guys can help with finishing the recipe.

Original recipe was this one: https://github.com/dmitry256/conan-libcds

Thank you for your work!

### Checklist for the Bincrafters team
  * Ignore this if you are not part of the Bincrafters team
  * [ ] There is no such Conan package yet in conan-center, conan-community or Bincrafters
  * [ ] The project is either popular or deserves to be maintained for another good reason (we can't package every single project out there)
  * [ ] [bincrafters-conventions](https://github.com/bincrafters/bincrafters-conventions) reports no complains; the recipe fulfills our general quality requirements and conventions
  * [ ] The recipe is cloned into our organisation; CI is enabled and configurated and succeeds
  * [ ] There is a branch protection rule for `stable/*` branches, which requires a pull request with at least one approval first before things can get published
  * Considering granding the inclusion request author push rights to the recipe repository (there is no guarantee that everyone is getting push rights, we decide this on a case-to-case base)

**Comment by Croydon** [comment]
Inclusion requests are meant for outsiders, but you are a member of Bincrafters. You have the permissions to create new repositories for new recipes 😄

**Comment by ZaMaZaN4iK** [comment]
@Croydon Yeah, I know... But honestly I didn't work on huge recipes for Conan a long time (so don't know about "the latest" practices for creation modern Conan recipes), so help from other members probably will be required.

And I thought that creating an inclusion request is the best way to communicate with other members about such stuff :)

If you think that direct repo creation and discussing in Slack/PR are more comfortable ways for other members - I will immediately do it :)

**Comment by Croydon** [comment]
It looks like all dependencies are in CCI, so a recipe for it should go directly into CCI instead

Closing
