### ISSUE TITLE
[request] libjson-rpc-cpp/1.3.0

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [bincrafters/community#1177]
### Package Details
  * Package Name/Version: **libjson-rpc-cpp/1.3.0**
  * Changelog: **https://github.com/cinemast/libjson-rpc-cpp/releases**

The above mentioned version is newly released by the upstream project and not yet available as a recipe. Please add this version.

In Bincrafters only 1.1.0 version is available. Please add all missing versions (1.1.1, 1.2.0, 1.3.0).

Thank you a lot!

**Comment by Croydon** [comment]
Seems like you might have resolved this yourself 😄 

However, please notice that you should always create and push to `testing/` branches first, before you push something to a `stable/` branch

**Comment by Croydon** [comment]
I have created now the `testing/` branch. Version is available. Closing.
