### ISSUE TITLE
GLM (OpenGL Mathematics) is missing [RFC]

### ISSUE THREAD

**Issue by madebr** [bincrafters/community#118]
### Description of Problem, Request, or Question
The library GLM (https://glm.g-truc.net) is missing.

### Package Details (Include if Applicable)
* Package Name/Version: **glm/0.9.8.5**

### RFC
I tried writing a conan package for glm. This is my first encounter to conan.
It can be found at https://github.com/madebr/conan-glm
Can someone review this and transfer ownership to bincrafters?

**Comment by madebr** [comment]
Thank you for the link.

I do not need any modifications, As glm is an include only library, everything is included in the package.

**Comment by dimi309** [comment]
You're welcome!
