### ISSUE TITLE
Qt/5.10/11: Recipe's download link is incorrect

### ISSUE THREAD

**Issue by fletcher-blight** [bincrafters/community#1180]
I am trying to use conan for work and we require Qt 5.11 however the download links are incorrect. 
The recipe tries to download qt from ["download.qt.io/archive"](https://download.qt.io/archive/) but it appears that select versions are here "5.9, 5.12, 5.13, 5.14".
So for versions 5.10 and 5.11 (and others), they need to use the link ["download.qt.io/new_archive"](https://download.qt.io/new_archive/).

More specifically, in the branch 5.11.3 (and others that match this pattern) the recipe needs to change this line:
`https://download.qt.io/archive/qt/{0}/{1}/single/qt-everywhere-src-{1}`
to:
`https://download.qt.io/new_archive/qt/{0}/{1}/single/qt-everywhere-src-{1}`

Details:
Package: Qt (multiple versions)
OS: Linux Ubuntu 19.10
Compiler: GCC

attached a screenshot of the command and output errors.
![Screenshot from 2020-04-25 10-27-50](https://user-images.githubusercontent.com/49885087/80266487-8414b500-86df-11ea-8362-2546360bbd9f.png)

**Comment by Croydon** [comment]
I'm not sure about the URL, but the screenshot output you posted has nothing to do with it

We provide no builds for your configuration combined with this Qt version, so you need to build it yourself

`Try to build it from source with --build qt`

**Comment by TheRealMazur** [comment]
It seems that `download.qt.io` is down.
Even official [Offline installers](https://www.qt.io/offline-installers) don't work.
It may be a temporary thing, or it could have to do with the announcement:
>From February onward, everyone, including open-source Qt users, will require valid Qt accounts to download Qt binary packages.

[Source](https://www.qt.io/blog/qt-offering-changes-2020)

**Comment by ericLemanissier** [comment]
thanks for the notification ! The stable branch is now fixed, and it should be uploaded to bintray shortly
