### ISSUE TITLE
flex/2.6.4: Can't access flex or flex++ binary within package.

### ISSUE THREAD

**Issue by lcsdavid** [bincrafters/community#1182]
Conan package() should also include flex and flex++ binaries in package's bin folder. (non-generic fix, please improve)

```
--- a/conanfile.py
+++ b/conanfile.py
@@ -22,6 +22,4 @@ class ConanFileDefault(ConanFileBase):
 
     def package(self):
         super(ConanFileDefault, self).package()
-        bindir = os.path.join(self.package_folder, "bin")
-        if os.path.isdir(bindir):
-            shutil.rmtree(bindir)
+        self.copy(pattern="flex", dst="bin", src="source_subfolder/src")
```

It's a bit frustrating when you need to import flex binary within your project build folder to generate your scanner from your own flex build.

**Comment by Croydon** [comment]
There is a second package with the binaries: `flex_installer/2.6.4@bincrafters/stable`

**Comment by Croydon** [comment]
`flex_installer/2.6.4@bincrafters/stable` and `flex/2.6.4@bincrafters/stable` are now unified to `flex/2.6.4`

This recipe is now in the [Conan Center Index](https://github.com/conan-io/conan-center-index/).

Please migrate to the recipe version there. 
If this is still an issue, please create a new issue in the [Conan Center Index issue tracker](https://github.com/conan-io/conan-center-index/issues).

Thanks!
