### ISSUE TITLE
[question] Qt options for packages

### ISSUE THREAD

**Issue by Cscotttaakan** [bincrafters/community#1186]
Is it possible to disable unneeded qt components, for example only installing `QtBase` and `QtGui`, omitting everything else?
Is there a list of qt components that are disableable like the Qt installer?

**Comment by ericLemanissier** [comment]
by default, qt recipe builds only [qtbase](https://code.qt.io/cgit/qt/qtbase.git/) (Core, Gui, Widgets, Network, ...). You can enable other modules by enabling the corresponding option (eg qt::qtsvg=True). All modules are listed https://code.qt.io/cgit/qt/qt5.git/tree/.gitmodules
[Qt installer framework](https://doc.qt.io/qtinstallerframework) is a separate project which would need another recipe. It is never built by bincrafters' qt recipe
What parts of qt do you want to disable ?

**Comment by Cscotttaakan** [comment]
I'd only like QtCore and Widgets. I'm trying to build a docker base image with qt but the conan file is about ~6GB.

**Comment by Cscotttaakan** [comment]
Using this conanfile
```
[requires]

expat/2.2.9
libelf/0.8.13
libpciaccess/0.16@bincrafters/stable
libpthread-stubs/0.1@bincrafters/stable
util-macros/1.19.2@bincrafters/stable
xcb-proto/1.13@bincrafters/stable
xorgproto/2019.1@bincrafters/stable
xproto/7.0.31@bincrafters/stable
xtrans/1.4.0@bincrafters/stable
xz_utils/5.2.4
libdrm/2.4.100@bincrafters/stable
libunwind/1.3.1
libxau/1.0.9@bincrafters/stable
libxdmcp/1.1.3@bincrafters/stable
libxshmfence/1.3@bincrafters/stable
libxcb/1.13.1@bincrafters/stable
libx11/1.6.8@bincrafters/stable
libxext/1.3.4@bincrafters/stable
libxfixes/5.0.3@bincrafters/stable
libxrender/0.9.10@bincrafters/stable
libxcursor/1.2.0@bincrafters/stable
libxdamage/1.1.5@bincrafters/stable
libxi/1.7.10@bincrafters/stable
libxinerama/1.1.4@bincrafters/stable
libxrandr/1.5.2@bincrafters/stable
libxxf86vm/1.1.4@bincrafters/stable
mesa/19.3.1@bincrafters/stable
qt/5.14.2@bincrafters/stable

[generators]
cmake
qt

[options]
qca:shared=True
qt:opengl=no
qt:shared=True
qt:with_fontconfig=False
qt:with_harfbuzz=False
qt:with_libalsa=False
qt:with_libjpeg=False
qt:with_libpng=False
qt:with_mysql=False
qt:with_odbc=False
qt:with_openal=False
qt:with_pcre2=False
qt:with_pq=False
qt:with_sdl2=False
qt:with_sqlite3=False
qt:openssl=False
qt:with_glib=False
qt:GUI=True
qt:qtwebengine=False
qt:qtsvg=False
qt:qtdeclarative=False
qt:qtactiveqt=False
qt:qtmultimedia=False
qt:qttools=False
qt:qtxmlpatterns=False
qt:qttranslations=False
qt:qtdoc=False
qt:qtrepotools=False
qt:qtqa=False
qt:qtlocation=False
qt:qtconnectivity=False
qt:qtimageformats=False
qt:qtgraphicaleffects=False
qt:qtquickcontrols=False
qt:qtserialbus=False
qt:qtserialport=False
qt:qtx11extras=False
qt:qtmacextras=False
qt:qtwinextras=False
qt:qtandroidextras=False
qt:qtwebsockets=False
qt:qtwebchannel=False
qt:qtwebview=False
qt:qtquickcontrols2=False
qt:qtpurchasing=False
qt:qtcharts=False
qt:qtdatavis3d=False
qt:qtvirtualkeyboard=False
qt:qtgamepad=False
qt:qtspeech=False
qt:qtnetworkauth=False
qt:qtremoteobjects=False
qt:qtwebglplugin=False
qt:qtlottie=False
qt:qtquicktimeline=False
qt:qtquick3d=False

[imports]
bin, *.pdb -> ./bin
bin, *.dll -> ./bin # Copies all dll files from packages bin folder to my "bin" folder
lib, *.dylib* -> ./lib # Copies all dylib files from packages lib folder to my "lib" folder
lib, *.so* -> ./lib # Copies all so files from packages lib folder to my "lib" folder
```

and checking the `qt\data` directory, it seems `qtwebengine` is still present in source

root@03265fb854bc:~/.conan/data/qt/5.14.2/bincrafters/stable/source# du -ah --max-depth 2 .
4.0K	./patches/3f9c9db_.diff
4.0K	./patches/fbde9c7.diff
4.0K	./patches/3f9c9db.diff
4.0K	./patches/a9cc8aa.diff
4.0K	./patches/aa2a39dea5.diff
24K	./patches
8.0K	./qtmodules.conf
14M	./qt5/qtcharts
4.0K	./qt5/configure.bat
3.1M	./qt5/qtwinextras
20M	./qt5/qtgraphicaleffects
4.0K	./qt5/qt.pro
8.0K	./qt5/LICENSE.LGPLv3
4.0K	./qt5/_clang-format
80K	./qt5/.QT-FOR-AUTOMATION-LICENSE-AGREEMENT
1.7M	./qt5/qtpurchasing
164M	./qt5/qtquick3d
**1.7G	./qt5/qtwebengine**
4.7M	./qt5/gnuwin32
1.9M	./qt5/qtgamepad
28K	./qt5/LICENSE.LGPLv21
128M	./qt5/qt3d
80K	./qt5/LICENSE.QT-LICENSE-AGREEMENT
2.8M	./qt5/qtactiveqt
11M	./qt5/qtimageformats
35M	./qt5/qtvirtualkeyboard
80K	./qt5/.QT-FOR-APPLICATION-DEVELOPMENT-LICENSE-AGREEMENT
9.5M	./qt5/qtsensors
3.6M	./qt5/qtserialport
3.3M	./qt5/qtx11extras
15M	./qt5/qtquickcontrols
13M	./qt5/qtdoc
4.0K	./qt5/configure.json
14M	./qt5/qtdatavis3d
872K	./qt5/qtwebglplugin
19M	./qt5/qttranslations
24K	./qt5/LICENSE.FDL
80K	./qt5/.QT-ENTERPRISE-LICENSE-AGREEMENT
30M	./qt5/qtscript
4.0K	./qt5/README
15M	./qt5/qtsvg
20M	./qt5/qtxmlpatterns
48K	./qt5/.QT-FOR-AUTOMOTIVE-LICENSE-AGREEMENT
8.0K	./qt5/.gitmodules
3.6M	./qt5/qtwebsockets
4.0K	./qt5/.tag
1.4M	./qt5/qtwebview
1.3M	./qt5/qtnetworkauth
1.7M	./qt5/qtlottie
8.2M	./qt5/qtwayland
55M	./qt5/qttools
4.4M	./qt5/qtremoteobjects
3.3M	./qt5/qtwebchannel
14M	./qt5/qtconnectivity
4.1M	./qt5/qtserialbus
252M	./qt5/qtdeclarative
36K	./qt5/LICENSE.GPLv3
796K	./qt5/qtquicktimeline
1.2M	./qt5/qtspeech
16K	./qt5/LICENSE.GPLv2
1.5M	./qt5/qtandroidextras
80K	./qt5/.QT-FOR-DEVICE-CREATION-LICENSE-AGREEMENT
4.0K	./qt5/configure
3.1M	./qt5/coin
355M	./qt5/qtbase
35M	./qt5/qtmultimedia
1.3M	./qt5/qtmacextras
73M	./qt5/qtlocation
6.2M	./qt5/qtscxml
32M	./qt5/qtquickcontrols2
3.0G	./qt5
4.0K	./conandata.yml

**Comment by ericLemanissier** [comment]
Yes, all the sources are kept, so that you can vhange options and still build the package. If you prebuild all the needed binaries of qt in your docker image, you van simply remove the whole source folder. If you need to allow users of your docker image to build other variants of qt, but never qtwebengine, then you can remove the qtwebengine folder only.
You should remove the build folder also, because it'll never be usefull.
