### ISSUE TITLE
cmake_findboost_modular - several bugs being fixed now

### ISSUE THREAD

**Issue by solvingj** [bincrafters/community#119]
This ticket is just to point out that we are aware of and working to fix at least 2 substantial bugs in our `cmake_findboost_modular` package. We will post update here when finished. 

### Package Details (Include if Applicable)
* Package Name/Version: **cmake_findboost_modular**
* Operating System: all
* Compiler+version: all
* Docker image: all

**Comment by SSE4** [comment]
changes are pushed, seems to be working fine with CppRestSDK and azmq. feel free to test and lemme know if there are any issues.

**Comment by solvingj** [comment]
I've pushed to 1.66.0/stable .  Will bring to 1.65.1 soon

**Comment by SSE4** [comment]
closing as working good so far with CppRestSDK
