### ISSUE TITLE
[request] PulseAudio/13.99.1

### ISSUE THREAD

**Issue by redpandamonium** [bincrafters/community#1190]
### Package Details
  * Package Name/Version: **PulseAudio/13.99.1**
  * Changelog: **none https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/tags/v13.99.1**

The above mentioned version is released by the upstream project and not yet available as a recipe. Please add this version. 

It should be compatible with 13.0 and only contain bug fixes. But I'm not 100% sure on that as there's no changelog. Among other things it fixes a compile error with clang 10 and can now be built on the latest version.

**Comment by ericLemanissier** [comment]
this release is not listed in https://www.freedesktop.org/wiki/Software/PulseAudio/. It's probably a development release to prepare 14.0 don't you think?
