### ISSUE TITLE
sfml/2.5.1@bincrafters/stable: Link error in graphics and window modules: undefined reference to `reallocarray'

### ISSUE THREAD

**Issue by fgallegosalido** [bincrafters/community#1194]
### Package and Environment Details
  * Package Name/Version: **sfml/2.5.1@bincrafters/stable**
  * Operating System+version: **Linux Ubuntu 16.04**
  * Compiler+version: **GCC 9**
  * Conan version: **conan 1.25.0**
  * Python version: **Python 3.7.7 (conda 4.8.3)**

### Conan profile
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce
The setup requires the same files as the test_package folder inside the conan-sfml repository, but with a conanfile.txt instead of a conanfile.py with the next content:
```
[requires]
sfml/2.5.1@bincrafters/stable

[generators]
cmake
```
Now we run these commands:
```
$> mkdir build
$> cd build
$> conan install .. --build=missing
$> cmake .. -DWITH_WINDOW=ON # -DWITH_GRAPHICS=ON has the same effect too
$> make
```
If we do `cmake .. -DWITH_AUDIO=ON -DWITH_NETWORK=ON`, no linker error happens.

### Logs
I'm only posting the linker error, as everything else looks just fine (and the conan log when installing sfml is quite large).
<details><summary>Click to expand log</summary>

```
/home/francisco/.conan/data/libx11/1.6.8/bincrafters/stable/package/91154d8213bd8cdda5619b42ffdb674c4ab78416/lib/libX11.a(Depths.o): In function `XListDepths':
Depths.c:(.text+0x51): undefined reference to `reallocarray'
/home/francisco/.conan/data/libx11/1.6.8/bincrafters/stable/package/91154d8213bd8cdda5619b42ffdb674c4ab78416/lib/libX11.a(PutImage.o): In function `PutSubImage':
PutImage.c:(.text+0x2007): undefined reference to `reallocarray'
/home/francisco/.conan/data/libx11/1.6.8/bincrafters/stable/package/91154d8213bd8cdda5619b42ffdb674c4ab78416/lib/libX11.a(PutImage.o): In function `XPutImage':
PutImage.c:(.text+0x2eb9): undefined reference to `reallocarray'
/home/francisco/.conan/data/libx11/1.6.8/bincrafters/stable/package/91154d8213bd8cdda5619b42ffdb674c4ab78416/lib/libX11.a(QuTree.o): In function `XQueryTree':
QuTree.c:(.text+0xe8): undefined reference to `reallocarray'
/home/francisco/.conan/data/libx11/1.6.8/bincrafters/stable/package/91154d8213bd8cdda5619b42ffdb674c4ab78416/lib/libX11.a(SetHints.o): In function `XSetIconSizes':
SetHints.c:(.text+0x294): undefined reference to `reallocarray'
/home/francisco/.conan/data/libx11/1.6.8/bincrafters/stable/package/91154d8213bd8cdda5619b42ffdb674c4ab78416/lib/libX11.a(SetHints.o):SetHints.c:(.text+0x40d): more undefined references to `reallocarray' follow
collect2: error: ld returned 1 exit status
```

</details>

**Comment by charmyt** [comment]
Is this related? Is there a workaround? Is the libX11.a supposed to have undefined symbols as reported by `nm`?

```
/usr/bin/ld: /home/xxx/.conan/data/libx11/1.6.8/bincrafters/stable/package/8cfe340971768a5f1c785526b65ae747644030c3/lib/libX11.a(OpenDis.o): undefined reference to symbol 'xcb_get_setup'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libxcb.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

```

**Comment by fgallegosalido** [comment]
I'm not entirely sure, but using Conan 1.26.0, everything seems to work fine right now. I haven't tried using conan 1.25.0, but if it is a problem in that version, just upgrade your conan installation. Maybe someone has some idea why that happened and if it is still happening.

**Comment by charmyt** [comment]
I'm seeing this with
Conan version 1.27.1

**Comment by fgallegosalido** [comment]
I'm having another problem right now. It seems that the package xorg/system is failing the build. Here is the error message:

```
dpkg-query: no package was found matching xorg-dev. 
ERROR: The following packages need to be installed:
 xorg-dev
xorg/system: ERROR: while executing system_requirements(): Aborted due to CONAN_SYSREQUIRES_MODE=verify. Some system packages need to be installed
ERROR: Error in system requirements
```

It seems that it tries to check if the package xorg-dev is available through `dpkg-query -l xorg-dev`, but it returns false (the package doesn't exist), while it can be installed through apt (I'm using Ubuntu 16.04, but 20.04 gives the same error).

I'm using Conan 1.28.1.

**Comment by uilianries** [comment]
@fgallegosalido to install the system packages, [CONAN_SYSREQUIRES_MODE](https://docs.conan.io/en/latest/reference/env_vars.html#conan-sysrequires-mode) should be set to `enabled`.

If the package doesn't exist, please, open an [issue](https://github.com/conan-io/conan-center-index/issues/new/choose) to Conan Center Index, which is the package's owner, or even a PR with fix since your error is very specific for distro.

**Comment by Croydon** [comment]
@fgallegosalido Did you got it working? Is this issue still relevant?

**Comment by fgallegosalido** [comment]
I don't think I've had any further problems for a while. I consider this issue not relevant anymore

**Comment by Croydon** [comment]
Closing then. Please feel free to create new issues if something occurs.
