### ISSUE TITLE
depot_tools_installer/20200515: Auto-update is not disabled via DEPOT_TOOLS_UPDATE=0

### ISSUE THREAD

**Issue by reneme** [bincrafters/community#1198]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **depot_tools_installer/20200515**
  * Operating System+version: **all**

### Steps to reproduce (Include if Applicable)

The `depot_tools` have an auto-update feature that is enabled by default and makes the scripts and tools contained in the package auto-update itself on invocation. As we want reproducible results, this feature is technically not desired for the conan recipe of depot_tools.

Unfortunately, the most recent version of depot_tools does not work on Windows when `DEPOT_TOOLS_UPDATE=0` is exported via the recipe's `self.env_info`. Regardless of auto-update, the depot_tools perform a bootstrapping of their scripts on first use. It seems that on Windows this is (presumably inadvertently) disabled when auto-updating is disabled.

It seems that [the issue is known upstream](https://bugs.chromium.org/p/chromium/issues/detail?id=1067590#c7) ([#2](https://bugs.chromium.org/p/chromium/issues/detail?id=1077384)), but for now [we decided to leave auto-updates enabled](https://github.com/bincrafters/conan-depot_tools_installer/pull/5#discussion_r426868771) for depot_tools_installer/20200515.

### Further Info

* depot_tools documentation: [how to disable auto-updates](https://dev.chromium.org/developers/how-tos/depottools#TOC-Disabling-auto-update)
* https://github.com/bincrafters/community/issues/943#issuecomment-629307967

**Comment by Croydon** [comment]
This recipe is now in the [Conan Center Index](https://github.com/conan-io/conan-center-index/).

Please migrate to the recipe version there. 
If this is still an issue, please create a new issue in the [Conan Center Index issue tracker](https://github.com/conan-io/conan-center-index/issues).

Thanks!

____


In this case it is still a thing, so could you please copy those information to a CCI issue? Thanks!
