### ISSUE TITLE
[glib/2.*] Please add self.cpp_info.names["cmake_find_package"] = "GLib2"

### ISSUE THREAD

**Issue by SemyonDuB** [bincrafters/community#1199]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **glib/2.\***
  * Conan version: **Conan 1.21.1**
  * Python version: **Python 3.7.7**

### Description of your feature
I'm trying to create the package for dbus with `generators = "cmake_find_package"` and it's using `find_package(GLib2)`, but conan passes Findglib.cmake, so dbus cmake can't find glib2. I asked some peoples about this problem and someone suggest me to add in glib package something like that: `self.cpp_info.names["cmake_find_package"] = "GLib2"`
Of course, a solution for this problem may like just replace GLib2 to glib in CMakeLists.txt, but I think, If glib will uses in other projects with cmake it's a maybe big problem. Also the same problem with `libx11/1.6.8@bincrafters/stable`.

**Comment by uilianries** [comment]
Hi @SemyonDuB !

Do you have any reference about that name, is it the official for cmake find?

**Comment by SemyonDuB** [comment]
> Do you have any reference about that name, is it the official for cmake find?

I don't have any reference about official glib for CMake find, because most people use pkg_check_modules(GLIB2 "glib-2.0") to find glib. But, I also mentioned libx11 that have official CMake find module `FindX11.cmake`, so maybe I hurried with adding cmake_find_package name for glib, but I think to add this for x11 package it's relevant?
