### ISSUE TITLE
Package flac

### ISSUE THREAD

**Issue by sztomi** [bincrafters/community#12]
https://xiph.org/downloads/

WIP here: https://github.com/sztomi/conan-flac

 - [x] macOS (local)
 - [x] Linux (local)
 - [x] Travis CI
 - [x] Windows (local)
 - [x] AppVeyor
 - [x] README
 - [x] Move to bincrafters

**Comment by sztomi** [comment]
Little update: Travis and most of Appveyor now works; however, some configurations break on Appveyor.

**Comment by sztomi** [comment]
AppVeyor and Travis CI now pass, the package is almost ready.

**Comment by sztomi** [comment]
Builds from the repo now under bincrafters: 

  * https://travis-ci.org/bincrafters/conan-flac/builds/314459007
  * https://ci.appveyor.com/project/BinCrafters/conan-flac/build/1.0.1

@solvingj OK to push to stable?

**Comment by solvingj** [comment]
Yes!
