### ISSUE TITLE
glfw/3.3.2: Driver load issues with the conan package

### ISSUE THREAD

**Issue by LunarWatcher** [bincrafters/community#1200]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **glfw/3.3.2** 
  * Operating System+version: **Linux Mint 19.3**
    * GPU: Nvidia GTX 1060M (6GB), proprietary drivers (440.59)
  * Compiler+version: **GCC 7**
  * Docker image: (not applicable)
  * Conan version: **conan 1.25.1**
  * Python version: **Python 3.6.9**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Configuration for profile gcc:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=7
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
test.cpp:
```cpp
#include <GLFW/glfw3.h>

int main() {
    if (!glfwInit())
    {
        return -1;
    }

    GLFWwindow* window = glfwCreateWindow(640, 480, "My Title", NULL, NULL);
    if (!window)
    {
        return -1;
    }
    glfwMakeContextCurrent(window); 
    glfwSwapBuffers(window);
    int width, height;
    glfwGetFramebufferSize(window, &width, &height);
    glViewport(0, 0, width, height);
    while (!glfwWindowShouldClose(window))
    {
        glfwPollEvents();
    }

    glfwTerminate();
}
```

conanfile.txt:
```ini
[requires]
glfw/3.3.2@bincrafters/stable
glew/2.1.0@bincrafters/stable

[generators]
cmake
```

CMakeLists.txt:
```cmake
cmake_minimum_required(VERSION 3.8)
project("Test")

include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()

add_executable(Test test.cpp)
target_include_directories(Test PRIVATE ".")
target_link_libraries(Test ${CONAN_LIBS})

```

```bash
mkdir build && cd build && conan install .. --profile gcc
cmake ..
LIBGL_DEBUG=verbose ./bin/Test.cpp
```

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
libGL: screen 0 does not appear to be DRI3 capable
libGL: screen 0 does not appear to be DRI2 capable
libGL: MESA-LOADER: dlopen(/home/lunarwatcher/.conan/data/mesa/19.3.1/bincrafters/stable/package/0584dc45620b4bdf99bddb906b9a0e5224605ec2/lib/dri/swrast_dri.so)
libGL: Can't open configuration file /home/lunarwatcher/.conan/data/mesa/19.3.1/bincrafters/stable/package/0584dc45620b4bdf99bddb906b9a0e5224605ec2/etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/lunarwatcher/.drirc: No such file or directory.
libGL: Can't open configuration file /home/lunarwatcher/.conan/data/mesa/19.3.1/bincrafters/stable/package/0584dc45620b4bdf99bddb906b9a0e5224605ec2/etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/lunarwatcher/.drirc: No such file or directory.
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
```

</details>

While I've included a lot of code here, this issue is specific to conan. With this CMakeLists:

```cmake
cmake_minimum_required(VERSION 3.8)
project("Test")

add_executable(Test test.cpp)

target_include_directories(Test PRIVATE ".")

add_subdirectory(glfw EXCLUDE_FROM_ALL)
target_link_libraries(Test PRIVATE glfw)

add_definitions(-DGLEW_STATIC)
add_subdirectory(glew-cmake EXCLUDE_FROM_ALL)
target_link_libraries(Test PRIVATE libglew_static)
```

And these submodules:

```ini
[submodule "glfw"]
	path = glfw
	url = https://github.com/glfw/glfw
[submodule "glew-cmake"]
	path = glew-cmake
	url = https://github.com/Perlmint/glew-cmake
```

with identical code (test.cpp) to the conan test, it suddenly works fine:

![image](https://user-images.githubusercontent.com/29489988/82430249-6132b200-9a8d-11ea-95f4-752fb2d32f2f.png)

As far as I can tell, this is a problem with the Conan package. GLFW itself works fine outside conan, and the standard glxgears test passes without issues. Games or other software requiring the GPU driver to work also works fine. 

Also, #1119: building mesa did not make a difference.

**Comment by ericLemanissier** [comment]
thanks for the bug report. We are migrating away from the mesa package. Could you please try with the updated glfw/3.3.2 recipe ?

**Comment by LunarWatcher** [comment]
Mesa is still pulled in by conan-glew apparently. Specifically, it requires mesa-glu, which pulls in mesa/19.3.1, which still causes the same crash. glfw works fine on its own now at least.

**Comment by ericLemanissier** [comment]
That's unfortunate, but this will be fixed when someone will have some time available to finalize https://github.com/bincrafters/conan-glu: conan-glew will depend on conan-glu instead of mesa-glu. Fell free ton contribute !

**Comment by LunarWatcher** [comment]
What exactly is missing? I compiled conan-glu locally and changed conan-glew to include conan-glu instead, and it appears to work fine without any modifications.

**Comment by ericLemanissier** [comment]
@Croydon started the work, so he would be the correct person to answer you, unfortunately he has little time for this currently. He mentionned 2 todos: https://github.com/bincrafters/conan-glu/blob/testing/virtual/conanfile.py#L15-L16, so that's a start !

**Comment by Croydon** [comment]
A glu system package is now Work-In-Progress here: https://github.com/conan-io/conan-center-index/pull/1976

Afterwards the glew package can be updated

glfw is now available from the Conan Center Index and should be used from there. The respective Bincrafters' package is now obsolete.
