### ISSUE TITLE
Glfw/3.3.2 Support GLFW_VULKAN_STATIC glfw option

### ISSUE THREAD

**Issue by Erlkoenig90** [bincrafters/community#1201]
### Package and Environment Details
  * Package Name/Version: **Glfw/3.3.2**

### Description of your feature
Glfw supports a CMake option `GLFW_VULKAN_STATIC` for linking Vulkan statically. This is desirable particularly for Mac OS, where linking MoltenVK statically is [preferred](https://github.com/KhronosGroup/MoltenVK/blob/master/Docs/MoltenVK_Runtime_UserGuide.md), as it is not part of the driver but rather an application-level feature. Therefore I'd suggest adding a conan option to enable this CMake flag.

I'll submit a PR for this.

**Comment by ericLemanissier** [comment]
This recipe is now on [Conan-Center-Index](https://github.com/conan-io/conan-center-index). Please migrate your issue [there](https://github.com/conan-io/conan-center-index/issues). Thanks!
