### ISSUE TITLE
ffmpeg/4.2.1: ERROR: yasm/1.3.0: 'settings.arch_build' value not defined

### ISSUE THREAD

**Issue by GarrickLin** [bincrafters/community#1202]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **ffmpeg/4.2.1@bincrafters/stable**
  * Operating System+version: **Linux Ubuntu 16.04**
  * target platform: aarch64 + linux
  * Compiler+version: **GCC 6.3**
  * Docker image: 
  * Conan version: **conan 1.25.2**
  * Python version: **Python 3.8.2**
   

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
arch=armv8
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=6.3
os=Linux
[options]
[build_requires]
[env]
AR=aarch64-himix100-linux-ar
AS=aarch64-himix100-linux-as
ASFLAGS=-mcpu=cortex-a7 -mfloat-abi=softfp -mfpu neon-vfpv4
CC=aarch64-himix100-linux-gcc
CFLAGS=-fPIC -I/opt/hisi-linux/x86-arm/aarch64-himix100-linux/aarch64-linux-gnueabi/include/c++/6.3.0
CHOST=aarch64-himix100-linux
CONAN_CMAKE_FIND_ROOT_PATH=/opt/hisi-linux/x86-arm/aarch64-himix100-linux/target
CONAN_CMAKE_TOOLCHAIN_FILE=/opt/toolchains/aarch64-himix100.toolchain.cmake
CXX=aarch64-himix100-linux-g++
CXXFLAGS=-fPIC -I/opt/hisi-linux/x86-arm/aarch64-himix100-linux/aarch64-linux-gnueabi/include/c++/6.3.0
LD=aarch64-himix100-linux-ld
LDFLAGS=-pie
PATH=[/opt/hisi-linux/x86-arm/aarch64-himix100-linux/bin]
RANLIB=aarch64-himix100-linux-ranlib
STRIP=aarch64-himix100-linux-strip
```

### Steps to reproduce (Include if Applicable)

```
conan create .  bincrafters/stable  -pr aarch64-himix100.profile --build=missing
```

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
ERROR: yasm/1.3.0: 'settings.arch_build' value not defined
```

</details>

**Comment by mjvk** [comment]
You could try defining arch_build and os_build in your profile.
