### ISSUE TITLE
Inclusion Request: dbus

### ISSUE THREAD

**Issue by SemyonDuB** [bincrafters/community#1209]
### Package Details
  * Package Name: **dbus**
  * Compiler support: **gcc-10**
  * Should work on Linux Fedora and other distributions, also work on FreeBSD with GNU make
  * Conan recipe repository: **https://github.com/SemyonDuB/conan-dbus**

### What is D-Bus?
D-Bus is a message bus system, a simple way for applications to talk to one another. In addition to interprocess communication, D-Bus helps coordinate process lifecycle; it makes it simple and reliable to code a "single instance" application or daemon, and to launch applications and daemons on demand when their services are needed.  
D-Bus in freedesktop.org: https://www.freedesktop.org/wiki/Software/dbus/

### Inclusion request
  * Fill all checkboxes with x if you agree with the statement or if it applies to your Conan recipe
  * [x] I want that my Conan recipe is getting included into the Bincrafters organisation
  * [x] I understand that if my request is accepted we are cloning your repository with all its history into Bincrafters, adapt some configurations and meta data if needed, and publishing it under the Bincrafters name and accounts
  * [x] I have used the Bincrafters templates to develop my Conan recipe - https://github.com/bincrafters/templates
  * [x] My Conan recipe and all parts of it are licensed under the MIT license (the dbus source have AFL license) - https://choosealicense.com/licenses/mit/ 
    * Bincrafters are releasing all recipes under MIT license. If you want to have your recipe within Bincrafters we kindly ask you to do the same
    * it is okay if your test_package contains code from the upstream project under the upstream project's license, as long as it is clearly mentioned within the test_package files
  * [x] My Conan recipe covers (at least) the latest stable version which is available for the package
  * [x] I know that my Conan recipe is working on all operating system and compilers mentioned above right now
    * if not: please provide here links to your CI platforms and / or build logs and describe the problems you encounter
  * [x] I'm willing to help to maintain the recipe even after it is included into Bincrafters

### Checklist for the Bincrafters team
  * Ignore this if you are not part of the Bincrafters team
  * [ ] There is no such Conan package yet in conan-center, conan-community or Bincrafters
  * [ ] The project is either popular or deserves to be maintained for another good reason (we can't package every single project out there)
  * [ ] [bincrafters-conventions](https://github.com/bincrafters/bincrafters-conventions) reports no complains; the recipe fulfills our general quality requirements and conventions
  * [ ] The recipe is cloned into our organisation; CI is enabled and configurated and succeeds
  * [ ] There is a branch protection rule for `stable/*` branches, which requires a pull request with at least one approval first before things can get published
  * Considering granding the inclusion request author push rights to the recipe repository (there is no guarantee that everyone is getting push rights, we decide this on a case-to-case base)

**Comment by Croydon** [comment]
Hi @SemyonDuB! 

I believe that we are somewhat close of having glib in the Conan Center Index (CCI), and we also have now the `xorg/system` package in the CCI, which means that soon all dependencies should be available from there

If this is the case the dbus recipe should go directly there. Please leave your inclusion request open until then

If it should take a long time I will still include your recipe in Bincrafters first

Thanks for contributing!

**Comment by SemyonDuB** [comment]
@Croydon thanks for the reply, of course, I leave the request open. I was glad to hear that CCI will add glib and xorg soon

**Comment by Croydon** [comment]
`glib/2.64.0` is now in CCI via https://github.com/conan-io/conan-center-index/pull/1756

You can create there now a pull request adding a dbus recipe! 😄
