### ISSUE TITLE
bullet3 by bincrafters

### ISSUE THREAD

**Issue by madebr** [bincrafters/community#121]
### Description of Problem, Request, or Question
For a project ([OpenRW](https://github.com/rwengine/openrw)), I want to use conan for CI and windows builds.
The project depends on OpenAL, **bullet3**, glm, ffmpeg and sdl2.

I have created a **bullet3** conan package at https://github.com/madebr/conan-bullet3.
If possible, I would like to hand over ownership to bincrafters.

Can you please review this package, take over ownership and setup packages on bintray?

Appveyor builds at https://ci.appveyor.com/project/madebr/conan-bullet3
Travis builds at https://travis-ci.org/madebr/conan-bullet3/

Thanks.

### Package Details (Include if Applicable)
* Package Name/Version: **bullet3/2.87**
* Operating System: **all**
* Compiler+version: **all**

**Comment by solvingj** [comment]
Hi @madebr , thanks so much for the PR!

The recipe looks really great.  Very impressive!  We'll get a repository created for this package ASAP and let you know when to submit a PR.  FYI, we're in the middle of a multi-day build process, so sorry if there's a delay.

**Comment by madebr** [comment]
Hi @solvingj ,

when you come around creating the repo, call it `conan-bullet` (without the 3).

**Comment by solvingj** [comment]
Thanks again for the contribution.  The repository has been created, recipe files copied, some minor adjustments made, and Ci enabled. 

https://github.com/bincrafters/conan-bullet

**Comment by madebr** [comment]
Thanks for your work, @solvingj !
some remarks:
- I added a requirement on `cpython@bincrafters`. I'm not sure how to handle that
- I think I read somewhere that conan should fail on invalid configurations, so I think this should be added to `build()`:
```python
        if not self.options.pybullet and self.options.pybullet_numpy:
            raise ConanException("Cannot have pybullet_numpy enabled and pybullet disabled.")1
```
- looking at your commits to conan-openal today, it seems that optimization can also be applied to this package (your optimizations to `package(self)`).

**Comment by solvingj** [comment]
1.  Lets just create a package for cpython ASAP.  It's off by default so it's fine for now. 
2.  We can add that in the near future as a revision.  Also, I think there are a bunch of other combinations of the options which would be invalid also. Please look through them all and try to cover as many as you can think of.  Also, for posterity, they will go in the `configure()` method.  

3. I did bypass the `package()` method already
4. I renamed to `bullet`, good catch.
