### ISSUE TITLE
Bintray broken link

### ISSUE THREAD

**Issue by ShamanTcler** [bincrafters/community#1210]
Simple problem/fix

use this URL: https://bintray.com/bincrafters/public-conan/Qt%3Abincrafters

In this string:	
[DEPRECATED] USE https://bintray.com/bincrafters/public-conan/qt:bincrafters INSTEAD!

The actual link is only for https://bintray.com/bincrafters/public-conan/qt   ... it does not include the ":bincrafters"

**Comment by Croydon** [comment]
This is an upstream bug and there is nothing we can do personally about it

https://github.com/conan-io/conan/issues/4091
