### ISSUE TITLE
pango/1.44.7: Incorrect licence

### ISSUE THREAD

**Issue by alanb-sony** [bincrafters/community#1213]
The licence of Pango is set to "MIT" but should be "LGPLv2": https://gitlab.gnome.org/GNOME/pango/-/blob/master/COPYING

**Comment by Croydon** [comment]
Thanks for the hint!

Is it LGPL-2.0-only or LGPL-2.0-and-later?

**Comment by Croydon** [comment]
At least according to a random file it would be LPGL-2.0-and-later, so I assume that this applied to all of pango?

https://gitlab.gnome.org/GNOME/pango/-/blob/master/pango/ellipsize.c#L9

**Comment by alanb-sony** [comment]
The source files seem to vary, I'd have thought the top level file was authoritative: https://gitlab.gnome.org/GNOME/pango/-/blob/master/COPYING
