### ISSUE TITLE
Inclusion Request: hyperscan

### ISSUE THREAD

**Issue by Flow-It** [bincrafters/community#1218]
### Package Details
  * Package Name: hyperscan
  * Operating Systems+versions: Tested on **ArchLinux**, should work equally well for others
  * Compiler support: Tested with **gcc-10**
  * Conan recipe repository: **https://github.com/Flow-It/conan-hyperscan**

### Inclusion request
  * Fill all checkboxes with x if you agree with the statement or if it applies to your Conan recipe
  * [x] I want that my Conan recipe is getting included into the Bincrafters organisation
  * [x] I understand that if my request is accepted we are cloning your repository with all its history into Bincrafters, adapt some configurations and meta data if needed, and publishing it under the Bincrafters name and accounts
  * [x] I have used the Bincrafters templates to develop my Conan recipe - https://github.com/bincrafters/templates
  * [x] My Conan recipe and all parts of it are licensed under the MIT license - https://choosealicense.com/licenses/mit/
    * Bincrafters are releasing all recipes under MIT license. If you want to have your recipe within Bincrafters we kindly ask you to do the same
    * it is okay if your test_package contains code from the upstream project under the upstream project's license, as long as it is clearly mentioned within the test_package files
  * [x] My Conan recipe covers (at least) the latest stable version which is available for the package
  * [x] I know that my Conan recipe is working on all operating system and compilers mentioned above right now
    * if not: please provide here links to your CI platforms and / or build logs and describe the problems you encounter
  * [x] I'm willing to help to maintain the recipe even after it is included into Bincrafters

Package was requested in conan center: conan-io/conan-center-index#1662

### Checklist for the Bincrafters team
  * Ignore this if you are not part of the Bincrafters team
  * [ ] There is no such Conan package yet in conan-center, conan-community or Bincrafters
  * [ ] The project is either popular or deserves to be maintained for another good reason (we can't package every single project out there)
  * [ ] [bincrafters-conventions](https://github.com/bincrafters/bincrafters-conventions) reports no complains; the recipe fulfills our general quality requirements and conventions
  * [ ] The recipe is cloned into our organisation; CI is enabled and configurated and succeeds
  * [ ] There is a branch protection rule for `stable/*` branches, which requires a pull request with at least one approval first before things can get published
  * Considering granding the inclusion request author push rights to the recipe repository (there is no guarantee that everyone is getting push rights, we decide this on a case-to-case base)

**Comment by Croydon** [comment]
hyperscan depends on ragel_installer, which seems to be portable to CCI https://github.com/bincrafters/conan-ragel_installer/blob/testing/6.10/conanfile.py

I think it is better to migrate ragal first, then include hyperscan directly in CCI

**Comment by Croydon** [comment]
Does hyperscan require ragel 6.10 or would it work with ragel 7.0.0.11 too?

**Comment by Flow-It** [comment]
Excuse me for asking, what is CCI and how does it influence the inclusion process?

According to http://www.colm.net/open-source/ragel/ ragel 7.0.0.12 is still a development version, so the latest stable release is still 6.10.

I'd try to build hyperscan with ragel 7, but the newer version of ragel now depends on colm, which we would have to package as well.

**Comment by Croydon** [comment]
CCI is the Conan Center Index

If the recipe can go directly into the CCI, then it should

If a recipe relies on dependencies outside of the CCI, then it can't be merge there and then Bincrafters is a good place for it

**Comment by Croydon** [comment]
I will have a look into migrating ragal 6 to the CCI later today

**Comment by Croydon** [comment]
I have created a PR to add ragel to the CCI https://github.com/conan-io/conan-center-index/pull/1895

**Comment by Croydon** [comment]
Ragel is now available as `ragel/6.10` from CCI

Now you can update your recipe to use ragel from CCI and create a PR there to add hyperscan

Thanks for contributing!
