### ISSUE TITLE
qt/5.15.0: cannot build multiconfiguration on linux

### ISSUE THREAD

**Issue by Dark-Passenger** [bincrafters/community#1220]
fail to build with the settings

qt:multiconfiguration=True

error 
```
WARNING: -debug-and-release is only supported on Darwin and Windows platforms.
Qt can be built in release mode with separate debug information, so
-debug-and-release is no longer necessary.

ERROR: Feature 'debug_and_release' was enabled, but the pre-condition 'config.darwin || config.win32' failed.

ERROR: Feature 'fontconfig' was enabled, but the pre-condition '!config.msvc && features.system-freetype && libs.fontconfig' failed.
```

**Comment by ericLemanissier** [comment]
How is this a bug? It's a limitation of qt itself, and the message is pretty clear. What improvement do you want here ?

**Comment by Dark-Passenger** [comment]
not really, it's pretty simple.

include free-type when compiler is not msvc (even if the multiconfig is set)

and 

set the -release -force-debug-info for linux instead of -debug-and-release

**Comment by ericLemanissier** [comment]
that's what will happen if you use setting build_type = "RelWithDebInfo"

**Comment by Dark-Passenger** [comment]
But line https://github.com/bincrafters/conan-qt/blob/testing/5.15.0/conanfile.py#L265

is removing the build_type configuration. and the configuration needs to work cross platform.

**Comment by Dark-Passenger** [comment]
the reason I am using the multiconfiguration settings only because I want to use the bundled qt 3rd party dependancies and because prebuilt packages still fail if I use system doubleconversion (inspite of -feature-relocatable)

**Comment by ericLemanissier** [comment]
qt's multiconfiguration feature is not cross platform, so the recipe's option cannot be. Regarding the use of bundled 3rd party sources, it's an anti-pattern in package management. What is the actual error you need to solve ?

**Comment by Dark-Passenger** [comment]
ah cool didn't know multi-configuration was not cross platform.

**Comment by Dark-Passenger** [comment]
the same error as https://github.com/bincrafters/community/issues/1155

thus closing this.
