### ISSUE TITLE
android_ndk_installer/r21d: ANDROID_STL is set to the wrong value by default

### ISSUE THREAD

**Issue by theodelrieu** [bincrafters/community#1225]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **android_ndk_installer/r21d**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **GCC 8**
  * Docker image: **conanio/gcc8**
  * Conan version: **conan 1.26.0**
  * Python version: **Python 3.7.4**

The recipe sets the `ANDROID_STL` env var to `c++_shared` by default, which is against the NDK default (`c++_static`, as mentioned here: https://developer.android.com/ndk/guides/cpp-support#cmake)

**Comment by uilianries** [comment]
As @SSE4 commented, probably it changed after some version.

**Comment by Croydon** [comment]
This recipe is now in the [Conan Center Index](https://github.com/conan-io/conan-center-index/).

Please migrate to the recipe version there. 
If this is still an issue, please create a new issue in the [Conan Center Index issue tracker](https://github.com/conan-io/conan-center-index/issues).

Thanks!

https://conan.io/center/android-ndk
