### ISSUE TITLE
qt/5.15.0: Unable to build, "multiple definition of QBasicMutex::lockInternal"

### ISSUE THREAD

**Issue by BastienGarcia** [bincrafters/community#1228]
I get the following error whenever I try to install.
I reported this bug previously (#974 ), it was closed and a report was opened on the [qt forums](https://bugreports.qt.io/browse/QTBUG-78729) but it lead nowhere.
 I updated my OS, compiler, conan, python and the package version but I still get the issue.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.15.0**
  * Operating System+version: **Linux Fedora 32**
  * Compiler+version: **GCC 10.1**
  * Conan version: **conan 1.26.1**
  * Python version: **Python 3.8.3**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=10
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
```
echo "[requires]\nqt/5.15.0@bincrafters/stable\n\n[generators]\ncmake\ntxt\n\n[imports]\nbin, *.dll -> ./bin\nlib, *dylib* -> ./bin" > conanfile.txt
conan install . --build qt
```

### Logs (Include/Attach if Applicable)
See attached logs
[log.txt](https://github.com/bincrafters/community/files/4853043/log.txt)

**Comment by ericLemanissier** [comment]
you should push https://bugreports.qt.io/browse/QTBUG-78729, because it is a qt bug, not related to the recipe itself.
Could you show us all the environment variables which are set when building qt (the output of `printenv`, and all variables that would be set by your conan profile) ?

**Comment by BastienGarcia** [comment]
@ericLemanissier not sure how to do that

**Comment by ericLemanissier** [comment]
you can simply run `printenv` or `env` in the same console you use to run `conan install . --build qt`. also, please show the output of `conan profile show default`

**Comment by BastienGarcia** [comment]
Conan default profile:
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=10
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

Env:
<details><summary>Click to expend</summary>
MODULEPATH=/etc/scl/modulefiles:/etc/scl/modulefiles:/usr/share/Modules/modulefiles:/etc/modulefiles:/usr/share/modulefiles
SSH_AUTH_SOCK=/tmp/ssh-CggPldKOCKX2/agent.1046
MODULESHOME=/usr/share/Modules
MOZ_GMP_PATH=/usr/lib64/mozilla/plugins/gmp-gmpopenh264/system-installed
LANG=en_US.utf8
XDG_CURRENT_DESKTOP=XFCE
SSH_AGENT_PID=1213
MODULES_RUN_QUARANTINE=LD_LIBRARY_PATH
SESSION_MANAGER=local/unix:@/tmp/.ICE-unix/1046,unix/unix:/tmp/.ICE-unix/1046
WINDOWID=98566147
DISPLAY=:0.0
XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/GARCIA_B
LESSOPEN=||/usr/bin/lesspipe.sh %s
QT_IM_MODULE=xim
HOME=/home/GARCIA_B
HOSTNAME=localhost.localdomain
XDG_MENU_PREFIX=xfce-
HISTSIZE=50000
IMSETTINGS_MODULE=none
KDEDIRS=/usr
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
DOTNET_BUNDLE_EXTRACT_BASE_DIR=/home/GARCIA_B/.cache/dotnet_bundle_extract
OLDPWD=/home/GARCIA_B
DESKTOP_SESSION=xfce
MANPATH=:
XDG_SEAT=seat0
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
XDG_VTNR=1
USER=GARCIA_B
XDG_CONFIG_DIRS=/etc/xdg
XDG_DATA_DIRS=/home/GARCIA_B/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop:/usr/share
XDG_SESSION_DESKTOP=xfce
COLORTERM=truecolor
VTE_VERSION=6003
SHLVL=1
MAIL=/var/spool/mail/GARCIA_B
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
LOGNAME=GARCIA_B
IMSETTINGS_INTEGRATE_DESKTOP=yes
XDG_RUNTIME_DIR=/run/user/1000
XMODIFIERS=@im=none
DOTNET_ROOT=/usr/lib64/dotnet
SHELL=/bin/zsh
XDG_SESSION_TYPE=x11
FPATH=/home/GARCIA_B/.oh-my-zsh/plugins/git:/home/GARCIA_B/.oh-my-zsh/plugins/git-flow:/home/GARCIA_B/.oh-my-zsh/plugins/extract:/home/GARCIA_B/.oh-my-zsh/functions:/home/GARCIA_B/.oh-my-zsh/completions:/usr/share/Modules/init/zsh-functions:/usr/local/share/zsh/site-functions:/usr/share/zsh/site-functions:/usr/share/zsh/5.8/functions
LOADEDMODULES=
HISTCONTROL=ignoredups
XDG_SESSION_ID=2
PATH=/home/GARCIA_B/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/home/GARCIA_B/.local/bin:/home/GARCIA_B/bin:/home/GARCIA_B/my_scripts/:/home/GARCIA_B/.dotnet/tools:/var/lib/snapd/snap/bin
PWD=/tmp/conan
XAUTHORITY=/run/lightdm/GARCIA_B/xauthority
MODULES_CMD=/usr/share/Modules/libexec/modulecmd.tcl
SSH_ASKPASS=/usr/libexec/openssh/gnome-ssh-askpass
MODULEPATH_modshare=/usr/share/modulefiles:1:/usr/share/Modules/modulefiles:1:/etc/modulefiles:1
XDG_SESSION_CLASS=user
TERM=xterm-256color
PANEL_GDK_CORE_DEVICE_EVENTS=0
GDMSESSION=xfce
LS_COLORS=rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=48;5;232;38;5;9:mi=01;37;41:su=48;5;196;38;5;15:sg=48;5;11;38;5;16:ca=48;5;196;38;5;226:tw=48;5;10;38;5;16:ow=48;5;10;38;5;21:st=48;5;21;38;5;15:ex=38;5;40:*.tar=38;5;9:*.tgz=38;5;9:*.arc=38;5;9:*.arj=38;5;9:*.taz=38;5;9:*.lha=38;5;9:*.lz4=38;5;9:*.lzh=38;5;9:*.lzma=38;5;9:*.tlz=38;5;9:*.txz=38;5;9:*.tzo=38;5;9:*.t7z=38;5;9:*.zip=38;5;9:*.z=38;5;9:*.dz=38;5;9:*.gz=38;5;9:*.lrz=38;5;9:*.lz=38;5;9:*.lzo=38;5;9:*.xz=38;5;9:*.zst=38;5;9:*.tzst=38;5;9:*.bz2=38;5;9:*.bz=38;5;9:*.tbz=38;5;9:*.tbz2=38;5;9:*.tz=38;5;9:*.deb=38;5;9:*.rpm=38;5;9:*.jar=38;5;9:*.war=38;5;9:*.ear=38;5;9:*.sar=38;5;9:*.rar=38;5;9:*.alz=38;5;9:*.ace=38;5;9:*.zoo=38;5;9:*.cpio=38;5;9:*.7z=38;5;9:*.rz=38;5;9:*.cab=38;5;9:*.wim=38;5;9:*.swm=38;5;9:*.dwm=38;5;9:*.esd=38;5;9:*.jpg=38;5;13:*.jpeg=38;5;13:*.mjpg=38;5;13:*.mjpeg=38;5;13:*.gif=38;5;13:*.bmp=38;5;13:*.pbm=38;5;13:*.pgm=38;5;13:*.ppm=38;5;13:*.tga=38;5;13:*.xbm=38;5;13:*.xpm=38;5;13:*.tif=38;5;13:*.tiff=38;5;13:*.png=38;5;13:*.svg=38;5;13:*.svgz=38;5;13:*.mng=38;5;13:*.pcx=38;5;13:*.mov=38;5;13:*.mpg=38;5;13:*.mpeg=38;5;13:*.m2v=38;5;13:*.mkv=38;5;13:*.webm=38;5;13:*.webp=38;5;13:*.ogm=38;5;13:*.mp4=38;5;13:*.m4v=38;5;13:*.mp4v=38;5;13:*.vob=38;5;13:*.qt=38;5;13:*.nuv=38;5;13:*.wmv=38;5;13:*.asf=38;5;13:*.rm=38;5;13:*.rmvb=38;5;13:*.flc=38;5;13:*.avi=38;5;13:*.fli=38;5;13:*.flv=38;5;13:*.gl=38;5;13:*.dl=38;5;13:*.xcf=38;5;13:*.xwd=38;5;13:*.yuv=38;5;13:*.cgm=38;5;13:*.emf=38;5;13:*.ogv=38;5;13:*.ogx=38;5;13:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
ZSH=/home/GARCIA_B/.oh-my-zsh
UPDATE_ZSH_DAYS=7
PAGER=less
LESS=-R
LC_CTYPE=en_US.utf8
LSCOLORS=Gxfxcxdxbxegedabagacad
LIBRARY_PATH=:/home/GARCIA_B/.graph_programming/lib
LD_LIBRARY_PATH=:/home/GARCIA_B/.graph_programming/lib:/home/GARCIA_B/.graph_programming/lib
CPATH=:/home/GARCIA_B/.graph_programming/include
_=/usr/bin/printenv
</details>

**Comment by ericLemanissier** [comment]
Can you remove the first `:` at the beginning of CPATH ?

**Comment by BastienGarcia** [comment]
Removing the `:` from the CPATH corrected the issue, I will share this issue with the others that had the same problem.
I thank you for your time, being able to build on my machine will greatly help my workflow.
You can close the issue you opened on qt.io
