### ISSUE TITLE
qt/5.15.0: libqxcb missing

### ISSUE THREAD

**Issue by BastienGarcia** [bincrafters/community#1229]
libqxcb seems to be missing in 5.15.0 when built from source on Fedora.
I have built it several time to verify I didn't interrupt it the first time, the issue is still present.
This isn't an issue in 5.14.2.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.15.0**
  * Operating System+version: **Linux Fedora 32**
  * Compiler+version: **GCC 10.1.1**
  * Conan version: **conan 1.26.1**
  * Python version: **Python 3.8.3**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=10
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
Using the following conanfile, install and build the dependencies
```
[requires]
qt/5.15.0@bincrafters/stable

[generators]
cmake
qt

[imports]
bin, *.dll -> ./bin
lib, *dylib* -> ./bin
plugins, platforms/* ->./bin
```
After building a sample program, running it will lead to an abort (logs below).
If the platform directory in the output directory or the qt package is checked, libqxcb is missing.

Using the same conanfile and changing the version to 5.14.2, the build is successful and there are no issues at runtime.
If the platform directory in the output directory or the qt package is checked, libqxcb is present.

### Logs (Include/Attach if Applicable)
[log.txt](https://github.com/bincrafters/community/files/4871946/log.txt)
Most important section
```
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc.
```

**Comment by ericLemanissier** [comment]
Please make sure xkbcommon is installed, retry build of qt with -u argument, and send the full qt build anyway.

**Comment by BastienGarcia** [comment]
xkbcommon is installed.
Output of `sudo dnf list installed | grep xkbcommon`
```
libxkbcommon.x86_64                               0.10.0-2.fc32                          @fedora                     
libxkbcommon-x11.x86_64                           0.10.0-2.fc32                          @fedora 
```
Qt build logs for `conan install .. --build qt -u >../log.txt 2>&1`
[log.txt](https://github.com/bincrafters/community/files/4872971/log.txt)

**Comment by ericLemanissier** [comment]
Sorry, I was not precise enough: you should make sure `libxkbcommon-devel` is installed
currently, your log fails with
```
Checking for xkbcommon >= 0.5.0... 
Trying source 0 (type pkgConfig) of library xkbcommon ...
+ /usr/bin/pkg-config --exists --silence-errors xkbcommon '>=' 0.5.0
pkg-config did not find package.
  => source produced no result.
Trying source 1 (type inline) of library xkbcommon ...
xkbcommon/xkbcommon.h not found in [] and global paths.
  => source produced no result.
test config.qtbase_gui.libraries.xkbcommon FAILED
```

**Comment by BastienGarcia** [comment]
I have installed `libxkbcommon-devel`as requested
```
libxkbcommon.x86_64                               0.10.0-2.fc32                          @fedora                     
libxkbcommon-devel.x86_64                         0.10.0-2.fc32                          @fedora                     
libxkbcommon-x11.x86_64                           0.10.0-2.fc32                          @fedora
```

I'm still missing libqxcb after the build
[log.txt](https://github.com/bincrafters/community/files/4879072/log.txt)

**Comment by BastienGarcia** [comment]
Also installed `libxkbcommon-x11-devel`, build log seems to be the exact same, still missing libqxcb.

**Comment by ericLemanissier** [comment]
could you try `xcb-util-wm-devel` ?

**Comment by BastienGarcia** [comment]
```
xcb-util-wm-devel.x86_64                          0.4.1-17.fc32                          @fedora
```
[log.txt](https://github.com/bincrafters/community/files/4879258/log.txt)

**Comment by ericLemanissier** [comment]
now you miss `xcb-util-keysyms-devel`. We may need to go several round again like this

**Comment by BastienGarcia** [comment]
Are the dependencies listed somewhere maybe? So that I can download them all in one go

**Comment by ericLemanissier** [comment]
The complete list should be the following:
```
xcb-util-wm-devel
xcb-util-image-devel
xcb-util-keysyms-devel
libxcb-devel
xcb-util-renderutil-devel
```

**Comment by ericLemanissier** [comment]
if you require xcb plugin, you can use option `qt:config=-xcb` so that the build fails early if any lib is not detected properly

**Comment by BastienGarcia** [comment]
The build is successful after adding the dependencies, problem solved. Any idea why the build failed only in 5.15 and not under?

**Comment by ericLemanissier** [comment]
Yes, it's a consequence of https://github.com/bincrafters/conan-qt/commit/d504c309fe8a551b72a580157d5fe47915f8aa74
I'll make a PR on CCI to make xorg/system install all these xcb packages

**Comment by BastienGarcia** [comment]
I see, thank you for your help once more!
