### ISSUE TITLE
Conan libstdcxx setting and modern Linux С++ ABI in packages

### ISSUE THREAD

**Issue by himikof** [bincrafters/community#123]
The Conan package tools have a `pure_c` argument (defaults to True), which disables the generation of Linux libstdc++11 build targets.

I would argue that the current default behavior (for Linux builds) is quite unfortunate for both C and C++ libraries.

Case 1: a pure C library. The Conan package should be excluding `compiler.libcxx` setting from `configure` method, or the built packages would not be usable on any modern Linux system (gcc >= 5 and libstdc++11). The default `pure_c` value of True fits.

Case 2: a C++03 library. This could be surprising, but the ABI of a C++03 library *does not* depend on `compiler.libcxx` difference between libstdc++11 vs libstdc++ (but the ABI does differ between any other values). I'm not sure if this is even possible to express in Conan. A possible solution could be something like (abusing the fact that there are no ABI-incompatible libstdcxx values on this platform for this case):
```
def configure(self):
    if self.settings.os == "Linux" and self.settings.compiler == "gcc" and self.settings.compiler.version >= 5:
        del self.settings.compiler.libcxx
```
The default of `pure_c=True` then surprisingly fits.

Case 2a: a C++03 library with a pure C interface. This could be handled either as case 1 or as case 2, both are correct from the ABI point of view, with slightly different resulting package semantics.

Case 3: a C++11 library. The ABI does depend on the full range of `compiler.libcxx` setting, so no additional settings configuration is required. But the default of `pure_c=True` does not fit, failing to pass `pure_c=False` would mean the library builds would not actually match any modern Linux system.

So, the default values do not actually work properly in all these cases. Can this be somehow solved in the package template/bincrafters tools/upstream conan tools, so that the packagers would specify which case the library matches and then the right thing would happen? Or is it a matter of explicitly documenting the possible cases and manually implementing it for almost every package?

A few concrete examples:
* `zstd/1.3.3@bincrafters/stable` matches case 1, but leaves the default libcxx behavior. As the result, the binary packages are not usable on modern Linux systems.
* `protobuf/3.5.1@bincrafters/stable`, which matches case 2, but has the same configuration (and problems) as `zstd`.
* `fmt/4.1.0@bincrafters/stable` with header_only=False matches case 3, but there are currently no libstdc++11 builds due to the same default configuration.

**Comment by solvingj** [comment]
@himikof thank you for raising this issue, and also for bringing so much detail.  this is a current topic under discussion, and your feedback from the field is extremely relevant.  Will keep you posted.

**Comment by lasote** [comment]
Hi! 

> Case 1: a pure C library. The Conan package should be excluding compiler.libcxx setting from configure method, or the built packages would not be usable on any modern Linux system (gcc >= 5 and libstdc++11). The default pure_c value of True fits.

The conan package should exclude the `compiler.libcxx`, yes, it is very important. But the sentence "or the built packages would not be usable on any modern Linux" is not true. In this case and following you are explaining, the packages won't be located when a (default or not) profile specifies `libstdc++11`. By default Conan always set `libstdc++` irrespective of the compiler version. In the Conan 1.1 a big message will be shown to warn the user to change the default when gcc >=5.

> Case 2: a C++03 library. This could be surprising, but the ABI of a C++03 library does not depend on compiler.libcxx difference between libstdc++11 vs libstdc++ (but the ABI does differ between any other values)....

The standard version doesn't depend on the standard library ABI mode. 
To model the standard with Conan there are some approaches pending to review, the latest here: https://github.com/conan-io/conan/pull/2486

> Case 2a: a C++03 library with a pure C interface. This could be handled either as case 1 or as case 2, both are correct from the ABI point of view, with slightly different resulting package semantics.

This is an interesting use case, I think the most accurate would be to not remove the setting in the `configure` but exclude it from the `package_id()`:

```python
def package_id(self):
        self.info.settings.compiler.libcxx = "ANY"
```

> Case 3: a C++11 library. The ABI does depend on the full range of compiler.libcxx setting, so no additional settings configuration is required. But the default of pure_c=True does not fit, failing to pass pure_c=False would mean the library builds would not actually match any modern Linux system.

The same I commented previously, of course you have to change the default to `pure_c=False`, but the "not matching modern Linux" is not accurate. About the library being c++98, 11, 14, 17 or 20 it is not related with this.

We are reviewing many inclusion requests, and it's true that the `pure_c` parameter and the `libcxx` subsetting is a little tricky and sometimes even us do not review it carefully. 

We have to think about the `pure_c` parameter, maybe it is better to make it non-optional, but I'll break many builds. For your bincrafters package tools I think it is a good idea.

But, even with the `pure_c` parameter not optional, it is still a little weak, @memsharded should we think again about a way to "mark" the recipes as "C" or as "C++" or even as "header only" somehow as a higher level layer to manage automatically all this `configure/package_id` stuff automatically? We can open an issue in the conan repo and discuss it there.

**Comment by himikof** [comment]
My main concern is that the `compiler.libstdcxx=libstdc++` package will cause an ABI mismatch when depending on system libraries (other than libstdc++, but with ABI-dependent C++ interface) on any modern distribution. So I use only `compiler.libstdcxx=libstdc++11` setting in my profiles, to match the system C++ ABI. And then, suddenly, many packages from remotes could only be built from source, because due to defaults in package tools, no binary package matching `compiler.libstdcxx=libstdc++11` is available for them.

Maybe the invariant package tools should try to hold by default should be this: either the binary packages are built without `compiler.libstdcxx` setting, or `pure_c=False` (so both ABI modes are built on modern GCC). This way most of the cases described previously should just work on both old and new distributions/GCC versions/`compiler.libstdcxx` settings. 
If this is not technically feasible, maybe it could be a matter of (documented) packaging policy?

> But the sentence "or the built packages would not be usable on any modern Linux" is not true. In this case and following you are explaining, the packages won't be located when a (default or not) profile specifies libstdc++11. By default Conan always set libstdc++ irrespective of the compiler version. In the Conan 1.1 a big message will be shown to warn the user to change the default when gcc >=5.

Well, I personally consider a `compiler.libstdcxx=libstdc++` with GCC >= 5 compiler a marginal configuraton, to be selected only by an expert user who knows how do debug ABI mismatch problems, and a completely invalid one for a general C++ developer on any modern Linux distribution. I am not aware of a *single* distribution which now has GCC >= 5 and which has opted to use the old C++ ABI. That is to say, the Linux C++ ecosystem has already completed this ABI transition (long ago). The only case I have seen is on Travis CI with Ubuntu trusty and manually upgraded GCC (but old system-wide libstdc++), which is actually a broken configuration (due to the missing/incomplete/broken runtime support for new C++ features from the new compiler, especially C++17 ones). The fact that Conan defaults to this configuration on any modern distro is a separate unfortunate issue. 

> The standard version doesn't depend on the standard library ABI mode.
To model the standard with Conan there are some approaches pending to review, the latest here: conan-io/conan#2486

Yes, in the case 2 I just confused everyone along with myself.
What I actually meant is that if a library does not use any dual-ABI-dependent symbols in its ABI (which is not the case for every C++03 library, of course, but is surprisingly common in legacy proprietary code), then it is fully binary-compatible between `compiler.libstdcxx=libstdc++` and `compiler.libstdcxx=libstdc++11`, but only between those 2 values and not any possible other standard C++ library implementations. And I'm not sure if this fact could be accurately described in Conan now. But this seems not that important.

> The same I commented previously, of course you have to change the default to pure_c=False, but the "not matching modern Linux" is not accurate. About the library being c++98, 11, 14, 17 or 20 it is not related with this.

Again, I might have explained myself poorly. You are right, the C++ standard used by the library is not directly related, so my classification is confusing. There are no problems in this case with `pure_c=False`.

**Comment by Croydon** [comment]
I think we manage `self.settings.compiler.libcxx` and `self.settings.compiler.cppstd` now much better in recipes.

In Bincrafters' package tools we also don't need to manually set the `pure_c` parameter anymore.

Therefore, I think this issue can be closed.

If there is more to discuss, then it should go either to CCI if it is about how we write recipes, or to the main Conan issue tracker if Conan itself may need improvements.
