### ISSUE TITLE
[question] qt/5.15.0 QtQuick module

### ISSUE THREAD

**Issue by Blinkuu** [bincrafters/community#1231]
I tried using Conan with the Qt/5.15.0 package. However, I need QtQuick module, not only the base ones. Is it possible to make Conan actually download additional modules as well?

**Comment by ericLemanissier** [comment]
yes, you can use option `qt:qtdeclarative=True`. The different modules are listed in https://github.com/bincrafters/conan-qt/blob/testing/5.15.0/qtmodules.conf
