### ISSUE TITLE
qt/5.15.0: Linux xcb plugin not working

### ISSUE THREAD

**Issue by Blinkuu** [bincrafters/community#1239]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.15.0**
  * Operating System+version: **Linux Ubuntu 19.10**
  * Compiler+version: **GCC 9**
  * Conan version: **conan 1.27.0**
  * Python version: **Python 3.7.5**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
arch=x86_64
arch_build=x86_64
build_type=RelWithDebInfo
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]
```

### Conanfile
```
[requires]
qt/5.15.0@bincrafters/stable

[generators]
cmake
qt

[options]
qt:GUI=True
qt:qtdeclarative=True
qt:qtmultimedia=True
qt:qttools=True
qt:qt3d=True
qt:qtquickcontrols=True
qt:qtquickcontrols2=True
qt:qtquick3d=True
qt:qtx11extras=True

[imports]
bin, *.dll -> ./bin # Copies all dll files from packages bin folder to my "bin" folder
lib, *.dylib* -> ./bin # Copies all dylib files from packages lib folder to my "bin" folder
lib, *.so* -> ./bin # Copies all so files from packages lib folder to my "bin" folder
```

### Logs
When running binary output is as following:

```
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: linuxfb, minimal, offscreen, vnc.
```

### Additional
When I enter folder where the qt/5.15.0 was installed via Conan I can see only the following libs:
```
libqlinuxfb.so, libqminimal.so, libqoffscrean.so, libqvnc.so
```

It seems like the xcb plugin is not being installed

**Comment by ericLemanissier** [comment]
can you please install system package `libxkbcommon-x11-dev` and retry ? The plan is to add dependancy on `xkbcommon/system` once https://github.com/conan-io/conan-center-index/pull/2157is merged, but in the meantime you have to install it manually unfortunately :/

**Comment by Blinkuu** [comment]
> can you please install system package `libxkbcommon-x11-dev` and retry ? The plan is to add dependancy on `xkbcommon/system` once https://github.com/conan-io/conan-center-index/pull/2157is merged, but in the meantime you have to install it manually unfortunately :/

**Comment by Blinkuu** [comment]
Installing this package did not help :/

**Comment by ericLemanissier** [comment]
can you run `conan remove --system-reqs '*'` to force reinstallation of system packages, then retry to build qt, with `-u` command line argument to update the recipes. If it still does not work, please send the full build log

**Comment by Blinkuu** [comment]
Still doesn't work. This is my Conan.cmake:
```
macro(run_conan)
  # Download automatically, you can also just copy the conan.cmake file
  if(NOT EXISTS "${CMAKE_BINARY_DIR}/conan.cmake")
    message(STATUS "Downloading conan.cmake from https://github.com/conan-io/cmake-conan")
    file(DOWNLOAD "https://github.com/conan-io/cmake-conan/raw/v0.15/conan.cmake" "${CMAKE_BINARY_DIR}/conan.cmake")
  endif()

  include(${CMAKE_BINARY_DIR}/conan.cmake)

  conan_add_remote(
    NAME
    bincrafters
    URL
    https://api.bintray.com/conan/bincrafters/public-conan)

  conan_cmake_run(
    CONANFILE conanfile.txt
    REQUIRES
    ${CONAN_EXTRA_REQUIRES}
    OPTIONS
    ${CONAN_EXTRA_OPTIONS}
    BASIC_SETUP
    CMAKE_TARGETS # individual targets to link to
    BUILD
    missing)
endmacro()
```

Both ${CONAN_EXTRA_REQUIRES} and ${CONAN_EXTRA_OPTIONS} are empty atm.

**Comment by ericLemanissier** [comment]
You need to force a rebuilt of qt.  you can call `conan remove qt/5.15.0@bincrafters/stable --packages` and then rebuild you cmake project.

**Comment by shauidu** [comment]
I encountered a same problem, and this solution works for me, thank you.
