### ISSUE TITLE
[question] qt/5.14.2 missing  quickcontrols2 module

### ISSUE THREAD

**Issue by Roman-Bober** [bincrafters/community#1245]
Hi I have instralled qt/5.14.2 and when trying to compile project with  quickcontrols2
getting below error
Seems  quickcontrols2 module isn't installed properly
Do you have idea why?

 : qmake: Project ERROR: Unknown module(s) in QT:  quickcontrols2

**Comment by ericLemanissier** [comment]
did you set option `qt:qtquickcontrols2=True` ?
