### ISSUE TITLE
qt/5.15.0: libcrypto key error when building

### ISSUE THREAD

**Issue by wouterbeek** [bincrafters/community#1248]
I get the following error when I build Qt:

```
ERROR: qt/5.15.0@bincrafters/stable: Error in build() method, line 563
	args.append("\"%s_LIBS=%s\"" % (var, " ".join(self._gather_libs(package))))
while calling '_gather_libs', line 685
	libs += self._gather_libs(dep)
while calling '_gather_libs', line 680
	libs = ["-l" + i for i in self.deps_cpp_info[p].libs + self.deps_cpp_info[p].system_libs]
	KeyError: 'libcrypto'
```

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.15.0**
  * Operating System+version: **Linux Ubuntu 20.04**
  * Compiler+version: **GCC 10**
  * Python version: **Python 3.8.2**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=10
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

```sh
conan install qt/5.15.0@bincrafters/stable -b missing
```

**Comment by ericLemanissier** [comment]
This is https://github.com/conan-io/conan/issues/7474.  It will be solved with conan 1.28.1
