### ISSUE TITLE
qt/5.14.2: Build error: libxcb-image.a: undefined reference to `xcb_aux_create_gc'

### ISSUE THREAD

**Issue by chubei-oppen** [bincrafters/community#1249]
The error happens because in build/c3f3f20c45e3079cce7c13faf8ee7065a09801b5/qtbase/src/plugins/platforms/xcb/Makefile.xcb_qpa_lib, -lxcb-image is put after -lxcb-util.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.14.2@bincrafters/stable**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **GCC 8.4.0**
  * Conan version: **conan 1.28.1**
  * Python version: **Python 3.7.7**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=8
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
```
conan install qt/5.14.2@bincrafters/stable -b qt
```

### Logs (Include/Attach if Applicable)

[qt_build.log](https://github.com/bincrafters/community/files/5040516/qt_build.log)

<details><summary>Click to expand log</summary>

```
ERROR: qt/5.14.2@bincrafters/stable: Error in build() method, line 690
        self.run(make, run_environment=True)
        ConanException: Error 2 while executing make
```

</details>

**Comment by ericLemanissier** [comment]
is it possible for you to try with `qt/5.15.0@bincrafters/stable` instead ? It uses on `xorg/system` which uses system packages for xcb, so it should solve your problem

**Comment by chubei-oppen** [comment]
5.15.0 builds fine. Thanks.
