### ISSUE TITLE
OpenAL: wrong include directory

### ISSUE THREAD

**Issue by madebr** [bincrafters/community#125]
### Description of Problem, Request, or Question
The include directores of the OpenAL package should also contain the `include/AL` directory.
`FindOpenAL.cmake` supplied with cmake does this too (see the comments in the header):
https://github.com/Kitware/CMake/blob/master/Modules/FindOpenAL.cmake

### Package Details (Include if Applicable)
* Package Name/Version: **openal/1.18.2@bincrafters/stable**
* Operating System: **Linux**
* Compiler+version: **gcc-7.3.1**

### Steps to reproduce (Include if Applicable)
The file, albeit not doing anything useful, should compile :

```
#include <al.h>

int main() {return 0;}
```

### Solution
Add
```
        self.cpp_info.includedirs = ["include", "include/AL"]
```
to `package_info(self)` in https://github.com/bincrafters/conan-openal/blob/72882d9c5735b4ab58f822b6ba1a464cfa65d160/conanfile.py

**Comment by solvingj** [comment]
Added here, should see it on stable by end of day. 
https://github.com/bincrafters/conan-openal/commit/644516730021633db63d4c8b3416bc5843a2ce2c
