### ISSUE TITLE
Conflict with GLEW and GLFW

### ISSUE THREAD

**Issue by AlexRamallo** [bincrafters/community#1253]
### Description of Problem, Request, or Question

For the following conanfile.txt:
```
[requires]
glfw/3.3.2@bincrafters/stable
glew/2.1.0@bincrafters/stable

[generators]
json
virtualrunenv

[options]

[imports]
bin, *.dll -> .
lib, *.dylib* -> .
```

I am getting the following error:

```
ERROR: Conflict in glew/2.1.0@bincrafters/stable:
    'glew/2.1.0@bincrafters/stable' requires 'opengl/system' while 'glfw/3.3.2@bincrafters/stable' requires 'opengl/virtual@bincrafters/stable'.
    To fix this conflict you need to override the package 'opengl' in your root package.
```

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **glew/2.1.0**, **glfw/3.3.2**
  * Operating System+version: **Linux Ubuntu 20.04 LTS**
  * Compiler+version: **gcc 9.3.0**
  * Conan version: **Conan 1.28.1**
  * Python version: **Python 3.8.2**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

**Comment by ericLemanissier** [comment]
Can you please use `glew/2.1.0` and `glfw/3.3.2` (without `@bincrafters/stable`) ? The bincrafters versions of these recipes are deprecated now that they have been integrated in conan-center-index.

**Comment by AlexRamallo** [comment]
That fixed it, thanks.
