### ISSUE TITLE
Add fPIC option for qt recipe

### ISSUE THREAD

**Issue by AndreyMlashkin** [bincrafters/community#1256]
Add fPIC option for qt recipe

qt/5.15.0@bincrafters/stable

**Comment by ericLemanissier** [comment]
As fare as I know, there is no way to configure PIC, qmake sets it behind the scenes when it decides to do so, without any user interface. Don't hesitate to reopen if you know a way to do it.

**Comment by AndreyMlashkin** [comment]
The issue is still there. Should I duplicate it here?
https://github.com/bincrafters/community/issues/1274

**Comment by ericLemanissier** [comment]
hmm, there seem to be a confusion here:  fPIC is a [compiler option](https://gcc.gnu.org/onlinedocs/gcc/Code-Gen-Options.html) which has nothing to do with folders, but with memory layout
