### ISSUE TITLE
[GLFW] 3.2.1 cannot find pdbs

### ISSUE THREAD

**Issue by p-groarke** [bincrafters/community#126]
### Description of Problem, Request, or Question
I doubt this is harmful, though it might point to some mixup in Release/Debug settings for the recipe when using `cmake_multi`.

### Package Details (Include if Applicable)
* Package Name/Version: **glfw/3.2.1**
* Operating System: **Windows**
* Compiler+version: **VS-15.5.6**
* Docker image: **?**

### Steps to reproduce (Include if Applicable)
I am using `cmake_multi` generator. Add glfw to your conanfile.
```
conan install .. --build missing -s build_type=Release
conan install .. --build missing -s build_type=Debug
cmake .. -A x64 && cmake --build . --config Debug
```

Will output the following on first try :

```
(Link target) ->
  glfw3.lib(context.obj) : warning LNK4099: PDB 'glfw.pdb' was not found with 'glfw3.lib(context.obj)' or at 'C:\proj\build\bin\glfw.pdb'; linking object as if no debug info [C:\proj\build\proj.vcxproj]
  glfw3.lib(init.obj) : warning LNK4099: PDB 'glfw.pdb' was not found with 'glfw3.lib(init.obj)' or at 'C:\proj\build\bin\glfw.pdb'; linking object as if no debug info [C:\proj\build\proj.vcxproj]
  glfw3.lib(input.obj) : warning LNK4099: PDB 'glfw.pdb' was not found with 'glfw3.lib(input.obj)' or at 'C:\proj\build\bin\glfw.pdb'; linking object as if no debug info [C:\proj\build\proj.vcxproj]
  glfw3.lib(monitor.obj) : warning LNK4099: PDB 'glfw.pdb' was not found with 'glfw3.lib(monitor.obj)' or at 'C:\proj\build\bin\glfw.pdb'; linking object as if no debug info [C:\proj\build\proj.vcxproj]
  glfw3.lib(vulkan.obj) : warning LNK4099: PDB 'glfw.pdb' was not found with 'glfw3.lib(vulkan.obj)' or at 'C:\proj\build\bin\glfw.pdb'; linking object as if no debug info [C:\proj\build\proj.vcxproj]
  glfw3.lib(window.obj) : warning LNK4099: PDB 'glfw.pdb' was not found with 'glfw3.lib(window.obj)' or at 'C:\proj\build\bin\glfw.pdb'; linking object as if no debug info [C:\proj\build\proj.vcxproj]
  glfw3.lib(win32_init.obj) : warning LNK4099: PDB 'glfw.pdb' was not found with 'glfw3.lib(win32_init.obj)' or at 'C:\proj\build\bin\glfw.pdb'; linking object as if no debug info [C:\proj\build\proj.vcxproj]
  glfw3.lib(win32_joystick.obj) : warning LNK4099: PDB 'glfw.pdb' was not found with 'glfw3.lib(win32_joystick.obj)' or at 'C:\proj\build\bin\glfw.pdb'; linking object as if no debug info [C:\proj\build\proj.vcxproj]
  glfw3.lib(win32_monitor.obj) : warning LNK4099: PDB 'glfw.pdb' was not found with 'glfw3.lib(win32_monitor.obj)' or at'C:\proj\build\bin\glfw.pdb'; linking object as if no debug info [C:\proj\build\proj.vcxproj]
  glfw3.lib(win32_time.obj) : warning LNK4099: PDB 'glfw.pdb' was not found with 'glfw3.lib(win32_time.obj)' or at 'C:\proj\build\bin\glfw.pdb'; linking object as if no debug info [C:\proj\build\proj.vcxproj]
  glfw3.lib(win32_tls.obj) : warning LNK4099: PDB 'glfw.pdb' was not found with 'glfw3.lib(win32_tls.obj)' or at 'C:\proj\build\bin\glfw.pdb'; linking object as if no debug info [C:\proj\build\proj.vcxproj]
  glfw3.lib(win32_window.obj) : warning LNK4099: PDB 'glfw.pdb' was not found with 'glfw3.lib(win32_window.obj)' or at'C:\proj\build\bin\glfw.pdb'; linking object as if no debug info [C:\proj\build\proj.vcxproj]
  glfw3.lib(wgl_context.obj) : warning LNK4099: PDB 'glfw.pdb' was not found with 'glfw3.lib(wgl_context.obj)' or at 'C:\proj\build\bin\glfw.pdb'; linking object as if no debug info [C:\proj\build\proj.vcxproj]
  glfw3.lib(egl_context.obj) : warning LNK4099: PDB 'glfw.pdb' was not found with 'glfw3.lib(egl_context.obj)' or at 'C:\proj\build\bin\glfw.pdb'; linking object as if no debug info [C:\proj\build\proj.vcxproj]
```

**Comment by dimi309** [comment]
Hi @p-groarke ,

First of all I will admit that I have never used the cmake_multi generator so I am sorry if I am making a mistake somewhere but are we sure that this is a problem with the package? Note that it does package pdbs when built in debug mode and I have tested it with various projects and it did not produce these warnings. Of course, you will have to copy the pdbs to your bin directory using a CMAKE or conan command, but the same is the case for dlls for example, when you are using shared binaries.

**Comment by p-groarke** [comment]
Well I wouldn't call that a mistake. GLFW links and works, however it is the only package I've used that prints these warnings. Do you know what other packages might do differently? Having the debug symbols, though not essential, would be nice.

**Comment by SSE4** [comment]
my suggestion is to use /Z7 option instead of /Zi when building glfw as static library - this way debugging information is embedded into library and pdb files are not needed

**Comment by dimi309** [comment]
Nonetheless, if you prefer to work with the .pdb file, you should find it in the bin directory of the debug package. I am not sure why it is causing you an issue but it is there and I am copying it successfully to my projects...

**Comment by p-groarke** [comment]
I just thought they could be copied by conan automatically.

**Comment by dimi309** [comment]
They almost can. If you are using a `conanfile.txt`, you can do it with Under [imports], e.g. :

```
[imports]
bin, *.pdb -> ./bin

```
If you are using a conanfile.py:

```
def imports(self):
            self.copy(pattern="*.pdb", dst="bin", src="bin")

```

**Comment by dimi309** [comment]
And that will copy the pdbs from ALL the packages you are referencing 😃

**Comment by hpesoj** [comment]
I am having the same issue. The problem is that Visual Studio searches for the `.pdb` file in the same directory as the library. The fix would be to package to the `lib` directory.

`self.copy("*.pdb", dst="lib", keep_path=False)`

Is there a reason you are not doing this currently?

**Comment by ToTheSol** [comment]
What I did to solve this problem is if you go to Project -> Properties - > C/C++ -> General, then click on the dropdown for Debug Information Format and choose C7 compatible(/Z7)

Please note that this is for Platform x64 with All Configurations (See Picture below)

![image](https://user-images.githubusercontent.com/29029348/100152691-1432fc80-2e71-11eb-9649-d83502d8af08.png)
