### ISSUE TITLE
[request] conan-cppcheck_installer/2.1

### ISSUE THREAD

**Issue by wouterbeek** [bincrafters/community#1260]
### Package Details
  * Package Name/Version: **conan-cppcheck_installer/2.1**
  * Changelog: **https://sourceforge.net/p/cppcheck/news/2020/06/cppcheck-21/**

The above mentioned version is newly released by the upstream project and not yet available as a recipe. Please add this version.

**Comment by uilianries** [comment]
Done: https://github.com/bincrafters/conan-cppcheck_installer/tree/testing/2.1

It requires some minutes to be processed by CI jobs.
