### ISSUE TITLE
qt/5.15.0: fail to build with Visual Studio if cl.exe set in CC and CXX env var of conan profile

### ISSUE THREAD

**Issue by SpaceIm** [bincrafters/community#1269]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.15.0**
  * Operating System+version: **Windows 10**
  * Compiler+version: **Visual Studio 2019**
  * Conan version: **conan 1.29.0**
  * Python version: **Python 3.7.1**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
build_type=Release
[options]
[build_requires]
[env]
CC=cl.exe
CXX=cl.exe
```

or

```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
build_type=Release
[options]
[build_requires]
[env]
CC="C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe"
CXX="C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe"
```

### Steps to reproduce (Include if Applicable)

`conan install qt/5.15.0@bincrafters/stable`

If I remove CC and CXX, it succeeds (but I need to restore this in my conan profile afterwards, because I have MinGW in my PATH, and not setting CC and CXX in conan profile leads to undesirable side effects when using Ninja generator for CMake based recipes).

### Logs (Include/Attach if Applicable)

[qt_build_error.log](https://github.com/bincrafters/community/files/5187138/qt_build_error.log)

There a plenty of messages like `cl : Command line warning D9002 : ignoring unknown option '/NOLOGO'` at the beginning.

**Comment by ericLemanissier** [comment]
Would it be ok for your if `QMAKE_LINK_C`, `QMAKE_LINK_C_SHLIB`, `QMAKE_LINK` and `QMAKE_LINK_SHLIB` were populated with `LD` environment variable, as suggested [here](https://github.com/conan-io/conan-center-index/pull/1759/files#r483111395) ?

**Comment by SpaceIm** [comment]
I have updated my local qt's conanfile.py with:

```python
        value = _getenvpath('CC')
        if value:
            args += ["QMAKE_CC=\"{}\"".format(value)]

        value = _getenvpath('CXX')
        if value:
            args += ["QMAKE_CXX=\"{}\"".format(value)]
```

It seems to properly work now.

**Comment by ericLemanissier** [comment]
Can you try this https://github.com/ericLemanissier/conan-qt/commit/2d6fd88d049b72c32fc15b358a576b4478a1af0e ?
@Minimonium WDYT of this change ?

**Comment by SpaceIm** [comment]
If CC and CXX are set, but not LD, if fails.

**Comment by ericLemanissier** [comment]
also requesting @ohanar's review on this change

**Comment by Minimonium** [comment]
@ericLemanissier The issue is how to escape them, I tried a few variations but to no avail.

**Comment by ohanar** [comment]
Initial guess on correct escaping would be along the lines of `'"QMAKE_LINK_C=%s"'`. The command prompt tends to leave parsing of quotations within arguments up to individual programs, and not everything handles them correctly (or in the same way). The safest bet to be portable is to quote the entire argument, as then the command prompt will parse the whole argument together and pass that off to the underlying program -- although, this doesn't always work due to various programs' hacks around the poor state of command prompt quotation parsing. As far as posix is concerned, the two methods of quoting are equivalent, there has just been a convention to use the quotes after an equals.

I'm on vacation this week, but I'll be able to check when I'm back at work next week.

**Comment by Minimonium** [comment]
I've tried that too. It still fails in the Makefiles that `jom` uses on Windows. I'm afraid it could be a limitation of the build tool, not something that Conan can actively help in here.

**Comment by ohanar** [comment]
Yup, qmake generates invalid nmakefile or makefiles when CC and/or CXX contains a space. Probably stems from a history of making things like `CC="gcc -m64"` and the like work.

**Comment by ericLemanissier** [comment]
Does one of you know if this space problem is reported on https://bugreports.qt.io/ ?

**Comment by ericLemanissier** [comment]
This recipe is now in the Conan Center Index.

Please migrate to the recipe version there.
If this is still an issue, please create a new issue in the Conan Center Index issue tracker.

Thanks!

https://conan.io/center/qt
