### ISSUE TITLE
boost_test misses unit_test_main (linking fails)

### ISSUE THREAD

**Issue by madebr** [bincrafters/community#127]
### Description of Problem, Request, or Question
Linking my unittests to `boost_test`, I get the the following error:
```sh
CMakeFiles/rwtests.dir/main.cpp.o: In function `main':
main.cpp:(.text+0x99): undefined reference to `boost::unit_test::unit_test_main(bool (*)(), int, char**)
```

### Package Details (Include if Applicable)
* Package Name/Version: **boost_test/1.66.0**
* Operating System: **Linux**
* Compiler+version: **gcc-7** (7.3.1)

### Steps to reproduce (Include if Applicable)
An empty `main.cpp` file suffices:
```cpp
#define BOOST_TEST_MODULE test_module
#include <boost/test/unit_test.hpp>
```

**Comment by madebr** [comment]
Fixed by using https://github.com/bincrafters/conan-cmake_findboost_modular

**Comment by solvingj** [comment]
@madebr looks like we definitely need someone who uses both `boost_test` and knows a bit about conan to figure this one out.  Sorry for the delay.

**Comment by madebr** [comment]
I fixed the issue in the mean time.
There was a stray BOOST_TEST_DYN_LINK in the tests CMakeLists.txt file.

**Comment by solvingj** [comment]
Oh, wow, good to hear.  Sometimes the test libraries have a bunch of special instructions and nuances for the main method.  Hopefully this one won't :)
