### ISSUE TITLE
qt/5.12.9: Build failure due to xkbcommon

### ISSUE THREAD

**Issue by planetmarshall** [bincrafters/community#1270]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.12.9**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **Clang-9*
  * Conan version: **conan 1.29.0**
  * Python version: **Python 3.8.3**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=clang
compiler.version=9
compiler.libcxx=libc++
build_type=Release
```

### Steps to reproduce (Include if Applicable)

```
conan create . qt/5.12.9@ -o qt:with_glib=False -o qt:with_harfbuzz=False
```

### Logs (Include/Attach if Applicable)

```
ERROR: Feature 'xcb' was enabled, but the pre-condition 'features.thread && features.xkbcommon && libs.xcb' failed. 
ERROR: Feature 'system-xcb' was enabled, but the pre-condition 'features.xcb && tests.xcb_syslibs' failed.
```

Looks like a few linking errors from XRender

```
/home/andrew/.conan/data/libxrender/0.9.10/bincrafters/stable/package/de62f0913dbebb7b37f89b679daa9ced08bb5080/lib/libXrender.a(FillRect.o):FillRect.c:func     tion XRenderFillRectangle: error: undefined reference to '_XGetRequest'
```

Full log attached.

[log.txt](https://github.com/bincrafters/community/files/5191344/log.txt)

**Comment by ericLemanissier** [comment]
5.12.9 recipe is not really maintained any more unfortunately. Is there any chance that you can migrate to 5.15.0 ?

**Comment by planetmarshall** [comment]
> 5.12.9 recipe is not really maintained any more unfortunately. Is there any chance that you can migrate to 5.15.0 ?

Yes I'll look into it, thanks.

**Comment by planetmarshall** [comment]
Closed as recipe is deprecated.
