### ISSUE TITLE
qt/5.15.1@bincrafters/stable: produces position dependent configs

### ISSUE THREAD

**Issue by AndreyMlashkin** [bincrafters/community#1274]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.15.1@bincrafters/stable**
  * Operating System+version: **Macos 10.15.6**
  * Compiler+version: **apple-clang 12**
  * Conan version: **conan 1.29.0**
  * Python version: **Python 3.7.4**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=12.0
compiler.cppstd=14
compiler.libcxx=libc++
build_type=Release
[options]
*:shared=False
*:fPic=True
*:with_glib=False
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
conan install qt/5.15.1@bincrafters/stable -u --build "*" -g deploy
grep -r "andreimalashkin" .  # substitute your user here
# qt config files will contain absolute paths for linker, see example below 

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
./qt/lib/libQt5Widgets.la:dependency_libs='-L/Users/andreimalashkin/.conan/data/pcre2/10.33/_/_/package/2d8245d819a6b7543095d62df5d99244060071ba/lib -L/Users/andreimalashkin/.conan/data/double-conversion/3.1.5/_/_/package/2c05b696523a432f7b39159a51219129d095742b/lib -L/Users/andreimalashkin/.conan/data/freetype/2.10.2/_/_/package/42b58dfbaf06fc41aabbe10ba829e1cc77d0ecd6/lib -L/Users/andreimalashkin/.conan/data/sqlite3/3.31.0/_/_/package/0fb5ca7e7eef2dc13e84ceca1633e96c06b88024/lib -L/Users/andreimalashkin/.conan/data/libmysqlclient/8.0.17/_/_/package/02c55d2bdd0704a4468c3954b5ca79fea24fa8ce/lib -L/Users/andreimalashkin/.conan/data/libpq/11.5/_/_/package/6615b55b95ff43a02a83c3955d071acd71dad079/lib -L/Users/andreimalashkin/.conan/data/odbc/2.3.7/_/_/package/5f4c4ed8ddf27bb70b22f93ac66b6827fc5411d1/lib -L/Users/andreimalashkin/.conan/data/zstd/1.4.4/_/_/package/647afeb69d3b0a2d3d316e80b24d38c714cc6900/lib -L/Users/andreimalashkin/.conan/data/openssl/1.1.1g/_/_/package/647afeb69d3b0a2d3d316e80b24d38c714cc6900/lib -L/Users/andreimalashkin/.conan/data/bzip2/1.0.8/_/_/package/75fe66fbfe61230e9fcbb361f13b6b3baa483e0a/lib -L/Users/andreimalashkin/.conan/data/libpng/1.6.37/_/_/package/88955cec2844f731470e07bd44ce5a3a24ec88b7/lib -L/Users/andreimalashkin/.conan/data/libjpeg/9d/_/_/package/647afeb69d3b0a2d3d316e80b24d38c714cc6900/lib -L/Users/andreimalashkin/.conan/data/libiconv/1.16/_/_/package/647afeb69d3b0a2d3d316e80b24d38c714cc6900/lib -L/Users/andreimalashkin/.conan/data/zlib/1.2.11/_/_/package/647afeb69d3b0a2d3d316e80b24d38c714cc6900/lib -L=/Users/andreimalashkin/.conan/data/qt/5.15.0/bincrafters/stable/package/d5086eb474d39b4d1d4218d2d55ea0d24653a15b/lib -lQt5Gui -framework Metal -framework CoreGraphics -framework OpenGL -framework AGL -lpng16 -lQt5Core -framework DiskArbitration -framework IOKit -lm -framework AppKit -framework Security -framework ApplicationServices -framework CoreServices -framework CoreFoundation -framework Foundation -ldouble-conversion -lpcre2-posix -lpcre2-8 -lpcre2-16 -lpcre2-32 -lz -lbz2 -lzstd'
```

</details>

This can be critical in a CI pipline, where for example, qt is compiled in docker and uploaded to local conan server and dependent project is compiled locally, using compiled binaries from the previous step. The dependencies will be pointing to /Users/**ContainerAdmin**/.conan instead of /Users/**LocalUser**/.conan

**Comment by ericLemanissier** [comment]
Can you please send us the full path and file name of such file, and its content ?

**Comment by AndreyMlashkin** [comment]
every *.prl file contains position dependent paths.
As example, see attachment of qt/lib/libQt5Core.prl
[libQt5.zip](https://github.com/bincrafters/community/files/5258345/libQt5.zip)

**Comment by AndreyMlashkin** [comment]
duplicate of https://github.com/bincrafters/community/issues/1278
