### ISSUE TITLE
unable to download source file from Qt site (v5.11.2)

### ISSUE THREAD

**Issue by kangsheng89** [bincrafters/community#1276]
Qt version 5.11.2 unable to download source file as sourcefile is located:
https://download.qt.io/new_archive/qt/5.11/5.11.2/single/qt-everywhere-src-5.11.2.zip

logs:
Qt/5.11.2@bincrafters/stable: Configuring sources in C:\.conan\66418f\1
ERROR: Qt/5.11.2@bincrafters/stable: Error in source() method, line 162
        tools.get("%s.zip" % url)
        NotFoundException: Not found: http://download.qt.io/official_releases/qt/5.11/5.11.2/single/qt-everywhere-src-5.11.2.zip

version older than 5.12 is located at
- https://download.qt.io/new_archive/qt/
the source path provided in conanfile.py (stable/5.11.2) pointed as below:
     def source(self):
        url = "http://download.qt.io/official_releases/qt/{0}/{1}/single/qt-everywhere-src-{1}" \

**Comment by ericLemanissier** [comment]
the fix is already present in 5.11.3: https://github.com/bincrafters/conan-qt/commit/5c0f7571b38c26139103105fa3c2a045d73896c9#diff-2b1d42f71f22b7ea0412d7602dec166f
Can you upgrade ?

**Comment by kangsheng89** [comment]
@ericLemanissier  yes i have migrated to 5.11.3, is good to add a Readme note regarding this also. Thx!
