### ISSUE TITLE
[question] upload built packages

### ISSUE THREAD

**Issue by AndreyMlashkin** [bincrafters/community#1277]
In our company we have a CI that uses conan to compile products.
We used jfrog artifactory server to store recipes and compiled binaries and it worked fine.
We want to migrate to gitlab, but it has some limits on package naming, which means we cannot upload compiled binaries for community recipes there.
There are pre-build packages from the community, but not for all combination of options.

We would like to integrate our CI system to bincrafters to have a possibility to upload compiled packages. I think it would be beneficial for everyone.

**Comment by Croydon** [comment]
Hi @AndreyMlashkin 

What recipes and packages do you have? 
Are the packaged applications open source (or at least publicly available for free)?

We welcome contributions for recipes and those accepted do also run on our CI and the packages are getting uploaded to our Conan remote on Bintray.

If the recipes fulfill all quality standards, they should be contributed to the official Conan Center Index: https://github.com/conan-io/conan-center-index/

If this isn't possible for some reason we welcome recipe contributions to Bincrafters 😄

**Comment by AndreyMlashkin** [comment]
I have only proprietary recipes, but they are depending on some community packages, with the configuration options, that are not built by community CI.

I am looking for a possibility to upload those binaries of community recipes to bincrafters

**Comment by ericLemanissier** [comment]
Can you give us a list of these community recipes, along with the options you use ? maybe we could add these options combinations to Bincrafters CI

**Comment by AndreyMlashkin** [comment]
Here they are:

Linux:

[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=14
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
os_build=Linux
[options]
*:shared=False
[build_requires]
[env]

Windows:

[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.cppstd=14
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
*:fPIC=True
*:shared=False
*:with_glib=False
[build_requires]
[env]


opencv/4.3.0@conan/stable
protobuf/3.5.2@bincrafters/stable
qt/5.15.0@bincrafters/stable

**Comment by Croydon** [comment]
Unfortunately, this is not feasible.

Supporting other configurations is a question of resources and time to support them. And you would not get those extra configurations for any package in the [Conan Center Index](https://github.com/conan-io/conan-center-index) or [conan-community](https://github.com/conan-community/).

OpenCV 4 and Protobuf are both available in Conan Center Index and their former packages are not supported anymore by conan-community and Bincrafters respectively.
