### ISSUE TITLE
[question] Is the quick module not in the precompiled binaries?

### ISSUE THREAD

**Issue by cajus** [bincrafters/community#1280]
I just tried to use the precompiled packages for the first time for a little conan demo here.

In the mini project, I placed this *conanfile.txt*:

```ini
[requires]
qt/5.15.1@bincrafters/stable

[generators]
qmake
```
and installed the dependencies using `conan install -s compiler.version=9 .`. These seem to be downloaded fine. Picking up the package path using

```
conan info qt/5.15.1@bincrafters/stable --paths -s compiler.version=9 --only package_folder --package-filter qt/5.15.1@*
```

returns

```
qt/5.15.1@bincrafters/stable
    package_folder: /home/cajus/.conan2/.conan/data/qt/5.15.1/bincrafters/stable/package/e5e09db0db8b2342496078fd02f6760cbe2d618f
```

Running *bin/qmake* from there runs into:

```
$ /home/cajus/.conan/data/qt/5.15.1/bincrafters/stable/package/e5e09db0db8b2342496078fd02f6760cbe2d618f/bin/qmake ..
Project ERROR: Unknown module(s) in QT: quick
```

*gui* seems to be there. I can't find anything that switches this off in the package defaults. Am I missing something?

**Comment by ericLemanissier** [comment]
Indeed, only qtbase is enabled by default, you need to set option `qt:qtdeclarative=True`

**Comment by cajus** [comment]
Oh. Looks I've missed that... Thanks!
