### ISSUE TITLE
qt/5.15.1: build fails with MinGW 8.0.0 (some issue with d3d12)

### ISSUE THREAD

**Issue by SpaceIm** [bincrafters/community#1283]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.15.1@bincrafters/stable**
  * Operating System+version: **Windows 10**
  * Compiler+version: **GCC 10.2.0 with MinGW 8.0.0**
  * Conan version: **conan 1.30.0**
  * Python version: **Python 3.7.1**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=10
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
CC=C:/msys64/mingw64/bin/gcc.exe
CXX=C:/msys64/mingw64/bin/g++.exe
```

### Steps to reproduce (Include if Applicable)

- Install MinGW 8.0.0 and gcc 10.2.0 (probably any version of gcc), through msys2 or from http://winlibs.com/ for example
- `conan install qt/5.15.1@bincrafters/stable -b missing`

This issue probably comes from Qt build files or MinGW 8.0.0. See https://bugreports.qt.io/browse/QTBUG-86892.
Maybe patching some Qt config file to make `config.qtdeclarative_quick.tests.d3d12` (maybe also `config.qtmultimedia_multimedia.libraries.wmf`) fails if MinGW?
This test fails with MinGW 7.x.x (which properly builds qt 5.15.1). But it succeeds with MinGW 8.0.0, leading to errors afterwards.

I've tested with 2 computers: one having DirectX SDK, and the another one not having it. Both fail to build qt with MinGW 8.0.0

### Logs (Include/Attach if Applicable)

[qt5.15.1_windows10_mingw8.0.0_gcc_10.2.0.log](https://github.com/bincrafters/community/files/5335868/qt5.15.1_windows10_mingw8.0.0_gcc_10.2.0.log)

**Comment by SpaceIm** [comment]
I've added this workaround in `source()`:

```python
        tools.replace_in_file(os.path.join(self.source_folder, "qt5", "qtdeclarative", "config.tests", "d3d12", "d3d12.cpp"),
                              "#include <d3d12.h>",
                              "#ifndef __MINGW32__\n#include <d3d12.h>\n#else\n#include <force_fail_mingw.h\n#endif")
        tools.replace_in_file(os.path.join(self.source_folder, "qt5", "qtmultimedia", "config.tests", "wmf", "main.cpp"),
                              "#include <d3d9.h>",
                              "#ifndef __MINGW32__\n#include <d3d9.h>\n#else\n#include <force_fail_mingw.h\n#endif")
```

Seems to work so far.

**Comment by ericLemanissier** [comment]
Can you submit this patch [upstream](https://codereview.qt-project.org/) ?

**Comment by ericLemanissier** [comment]
This recipe is now in the Conan Center Index.

Please migrate to the recipe version there.
If this is still an issue, please create a new issue in the Conan Center Index issue tracker.

Thanks!

https://conan.io/center/qt
