### ISSUE TITLE
bincrafters-conventions: ability to skip bot

### ISSUE THREAD

**Issue by Croydon** [bincrafters/community#1285]
sometimes it is just unwanted that the bot pushes convention updates, hence there should be a way to skip it

Possibilities:
  * add a tag to PR title
  * OR add a tag to PR description
  * OR add a tag to the latest(?)/any(?) commit message
  * OR detect if bots' commits got reverted (not sure how hard this is)

**Comment by ericLemanissier** [comment]
Also, maybe put a comment on the line you don't want the bot to modify ?

**Comment by Croydon** [comment]
I don't like this idea as it would mean having to put tool specific meta data into recipes 🤔

**Comment by uilianries** [comment]
Usually commit message is used for most CI services, but thinking about CCI, when I open a PR there and the bot updates, I would like something more straightforward, like the first option: add a tag to PR title.

**Comment by Croydon** [comment]
I no longer maintain Conventions, closing.
