### ISSUE TITLE
libjpeg-turbo/2.0.2: Mismatch between shipped jconfig.h and build configuration

### ISSUE THREAD

**Issue by Ext3h** [bincrafters/community#1289]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libjpeg-turbo/2.0.2**
  * Operating System+version: **Windows 10**
  * Compiler+version: **Visual Studio 15**
  * Conan version: **conan 1.30.0**
  * Python version: **Python 3.8.2**
  * self.options["libjpeg-turbo"].shared = false * 

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=15
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

- Use package with hash 9b721b63e452039565ba8417e25a183d1bbcb4df
- Include libjpeg-turbo as Conan-Target
- Attempt to use a full compression context, initialized with jpeg_create_compress()

libjpeg-turbo will terminate with an error, as the library had been built with `#define JPEG_LIB_VERSION  90`, but the shipped `jconfig.h` contains `#define JPEG_LIB_VERSION  80` instead. 

The package test was insufficient, as it did not use the high level interface (where the define did change the layout of structs), but only low-level functions which were not affected:
https://github.com/bincrafters/conan-libjpeg-turbo/blob/testing/2.0.2/test_package/test_package.c

#### Minimal reproducible example

```c++
#include <jpeglib.h>

struct jpeg_error_mgr handler;
jpeg_std_error(&handler);
// Test decompressor
{
	struct jpeg_decompress_struct decompressor;
	decompressor.err = handler;
	jpeg_create_decompress(&decompressor);
	jpeg_destroy_decompress(&decompressor);
}
// Test compressor
{
	struct jpeg_compress_struct compressor;
	compressor.err = handler;
	jpeg_create_compress(&compressor);
	jpeg_destroy_compress(&compressor);
}
```

### Logs (Include/Attach if Applicable)

```
Wrong JPEG library version: library is 90, caller expects 80
```

**Comment by Croydon** [comment]
This recipe is now in the [Conan Center Index](https://github.com/conan-io/conan-center-index/).

Please migrate to the recipe version there. 
If this is still an issue, please create a new issue in the [Conan Center Index issue tracker](https://github.com/conan-io/conan-center-index/issues).

Thanks!

https://conan.io/center/libjpeg-turbo

PS: That is why the git repo is archived
