### ISSUE TITLE
[conan-qt] Does conan binary ship static builds

### ISSUE THREAD

**Issue by VedantParanjape** [bincrafters/community#1294]
Does the bincrafter repository ship with static binaries of qt5 library ?

**Comment by ericLemanissier** [comment]
yes, but only of qtbase alone (it's the same for shared library by the way). Building other modules make it too long for free CI services.

**Comment by VedantParanjape** [comment]
Ok. Makes sense.

**Comment by ericLemanissier** [comment]
yes, as with nearly all conan recipes, you just need to use option `-o shared=False`. https://docs.conan.io/en/latest/creating_packages/getting_started.html
