### ISSUE TITLE
 sdl2/2.0.12@bincrafters/stable: Unable to load runtime dependencies due to build issue

### ISSUE THREAD

**Issue by Aypahyo** [bincrafters/community#1296]
* Package Name/Version: **sdl2/2.0.12@bincrafters/stable**
  * Operating System+version: **Linux Ubuntu 20.04**
  * Compiler+version: **gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0**
  * Docker image: **none, installed on os**
  * Conan version: **Conan version 1.31.0**
  * Python version: **Python 3.8.5**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]

```

### Steps to reproduce (Include if Applicable)
I posted this issue also here:

[stackoverflow](https://stackoverflow.com/questions/64706266/unable-to-set-up-sdl2-to-run-with-audio-alsa-on-linux-ubuntu-20-04-using-conan?noredirect=1#comment114429373_64706266)

and here:
[discourse.libsdl.org](https://discourse.libsdl.org/t/sdl2-alsa-dynamic-unabl-to-load-libalsa-1-1-9/28320/4)

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

runtime thing - that does not show directly during build but is connected to either cmake or the missing configure

</details>

**Comment by ericLemanissier** [comment]
can you try to use option `libalsa:shared=True` ?

**Comment by Aypahyo** [comment]
@ericLemanissier sure.
I added 
```
[options]
libalsa:shared=True
```
I ran
```
conan remove libalsa
conan install .. --build=libalsa --build sdl2 
```
The error message did change:

> 
> error SDL_OpenAudioDevice: ALSA: Couldn't open audio device: No such file or directory
> ALSA lib conf.c:3956:(snd_config_update_r) Cannot access file /home/aypahyo/.conan/data/libalsa/1.1.9/_/_/package/9e890f42f320e0611c0f5d26f85e02c47ed3e390/share/alsa/alsa.conf
> ALSA lib conf.c:3956:(snd_config_update_r) Cannot access file /home/aypahyo/.conan/data/libalsa/1.1.9/_/_/package/9e890f42f320e0611c0f5d26f85e02c47ed3e390/share/alsa/alsa.conf
> ALSA lib pcm.c:2564:(snd_pcm_open_noupdate) Unknown PCM default

```
cd /home/aypahyo/.conan/data/libalsa/1.1.9/
find . | grep  alsa.conf
```
gives the result

> ./_/_/build/9e890f42f320e0611c0f5d26f85e02c47ed3e390/source_subfolder/src/conf/alsa.conf
> ./_/_/package/9e890f42f320e0611c0f5d26f85e02c47ed3e390/include/alsa/conf.h
> ./_/_/source/source_subfolder/src/conf/alsa.conf

`ls /home/aypahyo/.conan/data/libalsa/1.1.9/_/_/package/9e890f42f320e0611c0f5d26f85e02c47ed3e390`

gives the result

> bin  conaninfo.txt  conanmanifest.txt  include  lib  licenses

I am not sure what to make of this.
