### ISSUE TITLE
Dynamic bullet library on windows does not export all data

### ISSUE THREAD

**Issue by madebr** [bincrafters/community#130]
### Description of Problem, Request, or Question
When using `gContactProcessedCallback` of the dynamic bullet library, linking will fail with a `LNK2001` error.
```cmd
main.obj : error LNK2001: unresolved external symbol "bool (__cdecl* gContactProcessedCallback)(class btManifoldPoint &,void *,void *)" (?gContactProcessedCallback@@3P6A_NAEAVbtManifoldPoint@@PEAX1@ZEA) [C:\issues\conan_bullet_1\build\issue.vcxproj]
```

Declaration of `gContactProcessedCallback`: https://github.com/bulletphysics/bullet3/blob/62b86e6eab91ce82bcfd4f7461d41ecd4a52bc01/src/BulletCollision/NarrowPhaseCollision/btPersistentManifold.h#L42
Definition of `gContactProcessedCallback`: https://github.com/bulletphysics/bullet3/blob/62b86e6eab91ce82bcfd4f7461d41ecd4a52bc01/src/BulletCollision/NarrowPhaseCollision/btPersistentManifold.cpp#L29

This might be an issue with the bullet3 library rather than a conan issue but I'm raising it here (first) as I cannot find any other references to this problem.

Linking to a static bullet library succeeds (apart from a warning).

### Package Details (Include if Applicable)
* Package Name/Version: **bullet/2.8.7**
* Operating System: **Windows**
* Compiler+version: **Visual Studio 2017**

### Steps to reproduce (Include if Applicable)
LInking to dynamic bullet:
I've created a repro at https://github.com/madebr/issues/tree/master/conan_bullet_1
Output at https://ci.appveyor.com/project/madebr/issues/build/1.0.24/job/8qbslvwoc1j2dbnh

Linking to static bullet:
I've created a repro at https://github.com/madebr/issues/tree/master/conan_bullet_2
Output at https://ci.appveyor.com/project/madebr/issues/build/1.0.24/job/hbgvx3uoxriqi3tp

**Comment by SSE4** [comment]
seems like symbol is not exported, appears to be library issue.

**Comment by SSE4** [comment]
upstream issue

**Comment by solvingj** [comment]
Does this mean package just can't work for shared lib?  If not, we should raise exception perhaps?

**Comment by madebr** [comment]
I'm looking into it.
It might have something to do with linker flags: https://msdn.microsoft.com/en-us/library/bxwfs976.aspx

**Comment by madebr** [comment]
It's an upstream bug.
The headers need to add `__declspec(import)` to the exported static variables.

Current [master](https://github.com/bulletphysics/bullet3/commit/6d326a79c8a609ef312a4a8edb5a55d2a1f5f9e3) does not even build dynamic libraries because of this exact issue.

**Comment by solvingj** [comment]
Thanks for doing the research.  Let's raise exception.
