### ISSUE TITLE
travis-ci plan change - migrate away from Travis

### ISSUE THREAD

**Issue by ericLemanissier** [bincrafters/community#1307]
following, https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing, the situation of travis-ci is not really clear. We may want to migrate some of our scripts to something else (github actions or azure pipelines are great candidates)

Here is a list of travis-ci jobs we have currently:
- [x] https://github.com/bincrafters/bincrafters-remove-outdated/blob/master/.travis.yml - https://github.com/bincrafters/bincrafters-remove-outdated/commit/7d592038d13b6b671f2fea63ca2ffb5479be7da2, https://github.com/bincrafters/bincrafters-remove-outdated/commit/013add4aeb668047d2b12452b4ecbcf22266efd7

- [x] https://github.com/bincrafters/bincrafters-default-branch/blob/master/.travis.yml - https://github.com/bincrafters/bincrafters-default-branch/commit/ccb49bc4d11af2a71dd92153c3d0194bb377e49e

- [x] https://github.com/bincrafters/community/blob/main/.travis.yml - https://github.com/bincrafters/community/commit/ff2bbbe7330c22658693f883bc8a18729c4a4f38

- [x] https://github.com/bincrafters/bincrafters-conventions/blob/main/.travis.yml - https://github.com/bincrafters/bincrafters-conventions/commit/1ab45c8c7ecc0d0e5b688c9e519b1bc1c3326c39

- [x] https://github.com/bincrafters/bincrafters-package-tools/blob/develop/.travis.yml - https://github.com/bincrafters/bincrafters-package-tools/commit/f36f3f886f94706fe2a811f0b8135fc452f21256

- [x] https://github.com/bincrafters/templates/blob/main/.travis.sh - https://github.com/bincrafters/templates/commit/4ab94e170f2269e29573291864dec947614bc1bc

- [x] https://github.com/bincrafters/templates/blob/main/.ci/travis-macos.yml - https://github.com/bincrafters/templates/commit/4ab94e170f2269e29573291864dec947614bc1bc, https://github.com/bincrafters/templates/commit/e035c7f055fe9e354eec182c1a8ea7fbbcdcca4e

- [x] https://github.com/bincrafters/templates/blob/main/.ci/travis-macos-installer.yml - https://github.com/bincrafters/templates/commit/4ab94e170f2269e29573291864dec947614bc1bc, https://github.com/bincrafters/templates/commit/e035c7f055fe9e354eec182c1a8ea7fbbcdcca4e

- [x] https://github.com/bincrafters/templates/blob/main/default/.travis.yml - https://github.com/bincrafters/templates/commit/011a208663dfb8c0927aab3576428e967dc674bf

**Comment by Croydon** [comment]
Fully agreed.

Pretty much, we have slowly moved away from Travis anyways and I think it is about time to finish this migration.

Other platforms offer more speed for free AND are much more flexible to use. 

We are currently using 4 CI platforms at the same time which makes it harder than it has to be.

I have recently asked for a PYPI token and added it as an organization-wide GitHub Actions Secret as `PYPI_TOKEN`. I'm all for moving our Python packages to GitHub Actions

**Comment by Croydon** [comment]
I removed Travis for the deployment of templates https://github.com/bincrafters/templates/commit/c2648cfaec7c51f80e33a1206f5dadb18f91fa0c

And deprecated Travis config files which can be imported in Travis runs https://github.com/bincrafters/templates/commit/4ab94e170f2269e29573291864dec947614bc1bc

**Comment by Croydon** [comment]
I updated the issue, hope that is okay with you @ericLemanissier

**Comment by ericLemanissier** [comment]
mm it looks like bincrafters-default-branch is still running on [travis](https://travis-ci.com/github/bincrafters/bincrafters-default-branch) (we should probably just disable the cron task), but no job is listed on https://dev.azure.com/bincrafters/packages/_build?view=folders. is it just a matter of creating the project on AZP ?

**Comment by Croydon** [comment]
bincrafters-default-branch is using GHA not AZP https://github.com/bincrafters/bincrafters-default-branch/actions

You are right, the corn job on Travis should be deleted

**Comment by Croydon** [comment]
All done
