### ISSUE TITLE
[SDL2] What system dependencies to pre-install?

### ISSUE THREAD

**Issue by helmesjo** [bincrafters/community#1308]
Looking at the system dependencies listed [in the recipe](https://github.com/bincrafters/community/blob/3f2c5c46726b05c4a3f5a89d9ef396f065e71446/recipes/sdl2/all/conanfile.py#L104-L126), it still doesn't appear to cover all, since if I pre-install those listed there on my ubuntu comp, it still keeps failing with all these small obscure dependencies like:
```
libxcb-render0-dev
libxcb-xkb-dev
libxcb-icccm4-dev
libxcb-image0-dev
libxcb-keysyms1-dev
libxcb-randr0-dev
```
etc. I have to install these one by one (only one i listed each time if fails, of course), maybe 10 or so extra.
If I set up my dockerfile I'd just like to list the minimum (which I thought was what is listed in the recipe), but it doesn't seem to cover it. 

Am I missing something? Which exactly are the 5-8 or so packages that need to be installed so I don't get these errors and have to manually install..?

**Comment by helmesjo** [comment]
Oh, those appear to actually be from the `xorg/system` package. A nice little tree here to climb, my bad! 
I'll just go through the different dependencies and find all required system packages, then I guess it should be all set!

In hindsight, the error actually directed me:
```
ERROR: The following packages need to be installed:
 libxcb-sync-dev
xorg/system: ERROR: while executing system_requirements(): Aborted due to CONAN_SYSREQUIRES_MODE=verify. Some system packages need to be installed
ERROR: Error in system requirements
```

**Comment by Croydon** [comment]
If you trust us and Conan enough, you can also set the environment variable `CONAN_SYSREQUIRES_MODE` to  `enabled`. This will cause Conan to attempt to install the system requirements automatically.

**Comment by helmesjo** [comment]
Yeah I saw that one, but problem is that this doesn't work inside my docker container (no `sudo` available), and I like having my docker files ready as is.

I've seen various discussions about `system_dependencies()`, though could you direct me to where the main discussion/documentation is regarding this, how one should approach it in their own recipes?

Thanks!

**Comment by helmesjo** [comment]
Or a follow-up question to that: Is there a conan-command so that I can trigger installation of all system commands for a package?

Say something like: `conan install-system-depenedencies sdl2/2.0.12@bincrafters/stable`? If so, then I could just trigger this during building of the docker image (in the `.dockerfile`).

**Comment by Croydon** [comment]
Pointing to one resources it almost impossible. Our current census has developed over the last three years from experiences

Basically, avoid `system_dependencies()` at all cost if possible at all. Some things like OpenGL drivers or systemd are too low level to be build and deployed by Conan for most use cases, in such cases we develop `<name>/system` system packages, which do nothing except installing system dependencies and expose the information to build systems.

The Conan Center Index does not allow `system_requirements()`, except when wrapped up in a system package

In Bincrafters we still have many recipes with system requirements, but we are working towards creating Conan packages for all of them so we can replace them.

**Comment by Croydon** [comment]
> Or a follow-up question to that: Is there a conan-command so that I can trigger installation of all system dependencies for a package?

I'm not aware of such a command

If you can modify the Docker container you might want to install sudo and change user permission in a way that Conan can install them automatically. It might be the easiest solution

**Comment by helmesjo** [comment]
Yep, that's one solution. What's otherwise special with the conan docker images (besides g++ etc)? Or is it just that they are setup to manage these situations (because conan use and test with them for center-index)?

**Comment by Croydon** [comment]
The big advantage is that they are used every single day for this purpose, not only by Conan Center Index, but also Bincrafters and many others individuals
