### ISSUE TITLE
qt/5.15.1@bincrafters/stable: macdeployqt is faulty

### ISSUE THREAD

**Issue by AndreyMlashkin** [bincrafters/community#1311]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.15.1@bincrafters/stable**
  * Operating System+version: **MacOs Catalina**
  * Compiler+version: **apple-clang12**
  * Conan version: **conan 1.31.3**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.cppstd=14
compiler.libcxx=libc++
compiler.version=11.0
os=Macos
os_build=Macos
[options]
*:fPIC=True
*:shared=False
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
1. build any app with qt dependency.
2. in bin folder of compiled app call:
  APICATION_NAME="myAppName"
  mkdir $APICATION_NAME.app
  mv $APICATION_NAME $APICATION_NAME.app
  macdeployqt $APICATION_NAME.app

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
 macdeployqt myAppName.app  
ERROR: no file at "/Users/jenkins/w/cci_PR-3452@3/.conan/data/libpq/11.5/_/_/package/7d580b8b776a28848f92026fbc163831c04c4598/lib/libpq.5.dylib"
```

</details>

Strange thing, that I have compiled qt statically, but some dyncamic lib is missing

**Comment by ericLemanissier** [comment]
can you try to use `-o libpq:shared=False -b libpq` arguments to see if it creates a shared library or a static library ?

**Comment by AndreyMlashkin** [comment]
Still the same result.

Important addition: I also generate virtualrunenvironment and source it.
Otherwise it complains, about different qt installation

**Comment by ericLemanissier** [comment]
This recipe is now in the Conan Center Index.

Please migrate to the recipe version there.
If this is still an issue, please create a new issue in the Conan Center Index issue tracker.

Thanks!

https://conan.io/center/qt
