### ISSUE TITLE
qt/5.15.2: Package does not include QML classes

### ISSUE THREAD

**Issue by wouterbeek** [bincrafters/community#1315]
When installing the Conan Qt package, none of the QML classes seems to be installed.  I am not sure whether this is intentional or a bug?  The package does not seem to contain any options for enabling/disabling the QML component.

A simple way to reproduce this is to install the Conan Qt package and then search for class `QQmlApplicationEngine` in the installation directory (`~/.conan/data/{etc}`).  This should return no results.

### Package and Environment Details (include every applicable attribute)

  * Package Name/Version: **qt/5.15.2**
  * Operating System+version: **Linux Ubuntu 20.04**
  * Compiler+version: **GCC 10**
  * Conan version: **conan 1.32.0**
  * Python version: **Python 3.8.5**

### Conan profile (output of `conan profile show default`

```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=10
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

**Comment by ericLemanissier** [comment]
Qt modules are options of the recipe, so you probably want to use -o qt:qt declarative=true. All the modules are listed on https://www.github.com/bincrafters/conan-qt/tree/testing%2F5.15.2/qtmodules.conf

**Comment by wouterbeek** [comment]
Indeed, that work!  Thanks @ericLemanissier

**Comment by bgsa** [comment]
@ericLemanissier , even though enabling qt:qtdeclarative=True , Conan does not build "QML folder" with QML modules... 
for instance QtQuick2Plugin.dll is not built.
Does anybody have any solution to build QML modules using Conan?

**Comment by ericLemanissier** [comment]
@bgsa please provide the full build log of qt

**Comment by bgsa** [comment]
@ericLemanissier I may have done some mistake... I think I was looking for another folder. QT has build the plugins dlls ...
Thank you!
