### ISSUE TITLE
[request] qt/6.0

### ISSUE THREAD

**Issue by wouterbeek** [bincrafters/community#1316]
### Package Details
  * Package Name/Version: **qt/6.0**
  * Changelog: **https://www.qt.io/blog/qt-6.0-released**

The above mentioned version is newly released by the upstream project and not yet available as a recipe. Please add this version.

**Comment by ericLemanissier** [comment]
WIP on https://github.com/bincrafters/conan-qt/tree/testing/6.0.0 unfortunately I'm not sure qt 6 will be easy to build with conan :/

**Comment by ericLemanissier** [comment]
`qt/6.0.0@bincrafters/stable` is being compiled and uploaded as I type. please report the issues you will find !
