### ISSUE TITLE
bincrafters-remove-outdated: suggest and/or track upstream issue to make tool obsolete

### ISSUE THREAD

**Issue by Croydon** [bincrafters/community#1320]
I believe that the tool [bincrafters-remove-outdated](https://github.com/bincrafters/bincrafters-remove-outdated) shouldn't be necessary to begin with.

Removing outdated binary packages from a remote should be something which is easily doable with official Conan capabilities

See also
  * https://github.com/conan-io/conan-package-tools/issues/282
  * slightly related (maybe): https://github.com/conan-io/conan/issues/5453 (though this one is only local for now)

**Comment by ericLemanissier** [comment]
In theory it could be already replaced with a single call to `conan remove -r REMOTE -o -f */*` no ?

**Comment by Croydon** [comment]
According to the documentation

https://docs.conan.io/en/latest/reference/commands/misc/remove.html

>   -o, --outdated        Remove only outdated from recipe packages. This flag
                        can only be used with a reference

So almost, I think. We still need to get a list of all referenes.

I'm wondering if it would be reasonable to suggest advancing it for an entire remote and/or pattern?

WDYT? // @uilianries

**Comment by ericLemanissier** [comment]
`CONAN_REQUEST_TIMEOUT=3600 conan remove -r bincrafters -o -f "*/*"` seems to work on my machine

**Comment by Croydon** [comment]
This seems to work indeed! 🥳 

Looks like you know more than the documentation 😄

**Comment by Croydon** [comment]
At least it work for me locally. CI runs for the maximum time and then times out

https://github.com/bincrafters/bincrafters-conventions/runs/1555012641?check_suite_focus=true

**Comment by ericLemanissier** [comment]
That's surprising, it means the search for "*/*" failed 4 times with a timeout happening after 1h ?

**Comment by Croydon** [comment]
This works fine now: https://github.com/bincrafters/bincrafters-conventions/blob/0ec9c9f5052a00bbcdb962d8dae0117b131ac323/.github/workflows/remove-obsolete-packages.yml#L27

Deprecating our own tool for the call `conan remove -r <remote> --outdated`
