### ISSUE TITLE
qt/5.x.x: Qt Charts requires Qt widgets

### ISSUE THREAD

**Issue by mjvankampen** [bincrafters/community#1322]
Qt charts requires qt widgets to be enabled. To prevent people from making the same mistake as I did it might be nice to give a warning/error when this occurs. Not sure if this also happens for other modules.

**Comment by ericLemanissier** [comment]
can you please report the issue on https://bugreports.qt.io/secure/Dashboard.jspa ?

**Comment by mjvankampen** [comment]
Ah yes will do makes more sense to give this warning from Qt instead of conan!

**Comment by ericLemanissier** [comment]
This recipe is now in the Conan Center Index.

Please migrate to the recipe version there.
If this is still an issue, please create a new issue in the Conan Center Index issue tracker.

Thanks!

https://conan.io/center/qt
