### ISSUE TITLE
bincrafters-conventions: detect for CCI-like repos which recipes+versions do NOT have open PRs

### ISSUE THREAD

**Issue by Croydon** [bincrafters/community#1325]
More automation should not mean more work for humans.

I would like to get to the point, that bincrafters-conventions is automatically creating PRs for convention updates.

However, several updates could cause a need of rebasing in existing PRs. Hence I would like to let the bot only create automatic PRs for recipes in versioned recipe folders, which do not have currently PRs open against them.

What is the easiest way to assembly a list of paths that are getting changed in ALL opened PRs?

Is there an easier trick than iterating over all PRs, checking them all out via git and literally going over all file changes?

**Comment by ericLemanissier** [comment]
There may be another way, but that's how I did it https://github.com/ericLemanissier/conan-center-conflicting-prs/blob/main/main.py#L30-L58

**Comment by Croydon** [comment]
Thanks! That looks good

**Comment by ericLemanissier** [comment]
My parsing of diffs is too rudimentary, I should use unidiff instead, but did not have the time to go through it yet.

**Comment by Croydon** [comment]
I no longer maintain Conventions, closing.
