### ISSUE TITLE
[question] Package ID unexpected behavior

### ISSUE THREAD

**Issue by Forbinn** [bincrafters/community#1326]
I discovered a weird behaviour in the generation of the package ID for a recipe that requires qt.

Here is the minimal example:

- `conanfile.txt`
```
[requires]
qt/5.15.2@bincrafters/stable
```

Environment:
- docker image `conanio/gcc7`
- `conan profile new --detect default`
- `conan profile update settings.compiler.libcxx=libstdc++11 default`
- `conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan`

Default package ID mode:
- `cat $HOME/.conan/conan.conf | grep default_package_id_mode`
```
default_package_id_mode = semver_direct_mode # environment CONAN_DEFAULT_PACKAGE_ID_MODE
```

If I run `conan info -n id .` I get:
```
conanfile.txt
    ID: a13c4ee5c4526b19b1ae512ddd11c56d93c7e2f2
```

But now If I run `conan info -n id -o qt:with_mysql=False .`, I get:
```
conanfile.txt
    ID: 967981d76f1d4beb7a6e8b10a88a7548c314e7d2
```

Has you can see the package ID of my recipe changes depending on option set on its qt dependencies. The package ID only changes if the option of qt I used actually changes qt recipe own requirements.

Is this behaviour expected ? Because if I look at https://blog.conan.io/2019/09/27/package-id-modes.html, this shouldn't be the case but there is maybe something I missed.

**Comment by ericLemanissier** [comment]
setting qt:with_mysql=False removes `libmysqlclient/8.0.17` from qt's dependency, so it's probably why it changes your package ID, but you can ask for this on https://github.com/conan-io/conan/issues.

**Comment by Forbinn** [comment]
Ok, I have opened the same issue on conan center github (https://github.com/conan-io/conan/issues/8227). Thank you.
