### ISSUE TITLE
portaudio/v190600.20161030: Include C++ bindings

### ISSUE THREAD

**Issue by fmaker** [bincrafters/community#1327]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **portaudio/v190600.20161030**

### Description of your feature
Can you enable [C++ bindings](https://github.com/PortAudio/portaudio/blob/1a5c410f7f09042d2d7ce1509ec3cf0b6091c7f8/configure.in#L79) for the portaudio recipe? I think all that is required is to add "--enable-cxx" to [args](https://github.com/bincrafters/community/blob/7fcd9ab5c24a8b43b45272fc2740b68edf4e02a5/recipes/portaudio/all/conanfile.py#L88)

**Comment by Croydon** [comment]
Done via https://github.com/bincrafters/community/pull/1328

**Comment by fmaker** [comment]
Thanks!
