### ISSUE TITLE
conan-sdl2 should have fpic option 

### ISSUE THREAD

**Issue by solvingj** [bincrafters/community#133]
### Description of Problem, Request, or Question
SDL2 should support fpic as an option

### Package Details (Include if Applicable)
* Package Name/Version: **SDL2/all**
* Operating System: **Linux**
* Compiler+version: **all**
* Docker image: **all**

### Steps to reproduce (Include if Applicable)
N/A

**Comment by SSE4** [comment]
added in https://github.com/bincrafters/conan-sdl2/commit/829ad6981c080b38176e29382517fc3397bb870c
