### ISSUE TITLE
qt/5.15.x: QWebSocket is missing

### ISSUE THREAD

**Issue by AJIOB** [bincrafters/community#1331]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.15.1**, **qt/5.15.2**
  * Operating System+version: **Linux Ubuntu 20.04**
  * Compiler+version: **GCC 9**
  * Conan version: **conan 1.32.1**
  * Python version: **Python 3.8.5**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
/q/include/public/websocket.h:13:10: fatal error: QtWebSockets/QWebSocket: No such file or directory
   13 | #include <QtWebSockets/QWebSocket>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

</details>

**Comment by ericLemanissier** [comment]
As all qt modules, it needs to be enabled by setting option `qt:qtwebsockets=True`
