### ISSUE TITLE
Qt/6.0.0: gcc 10.2 build error

### ISSUE THREAD

**Issue by synacker** [bincrafters/community#1337]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: qt/6.0.0
  * Operating System+version: Fedora 33
  * Compiler+version: gcc 10.2.1
  * Conan version: conan 1.32.1
  * Python version: Python 3.9.1

### Conan profile
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=10
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
1. Add as a dependency qt6 in conanfile - ````self.requires("qt/6.0.0@bincrafters/stable")````
2. conan install .. build=missing

### Logs (Include/Attach if Applicable)
There are too much errors. I was grep messages about errors:

```
collect2: error: ld returned 1 exit status
src.cxx:8:1: error: 'alloca' was not declared in this scope; did you mean 'valloc'?
src.cxx:9:4: error: #error Intel CET not available
    9 | #  error Intel CET not available
#  error Intel CET not available
src.cxx:13:1: error: 'pollts' was not declared in this scope; did you mean 'poll'?
src.cxx:12:10: error: #include expects "FILENAME" or <FILENAME>
src.cxx:20:1: error: 'locale_t' was not declared in this scope
src.cxx:23:29: error: 'invalidLocale' was not declared in this scope
src.cxx:23:1: error: 'qDoubleSnprintf' was not declared in this scope
src.cxx:24:1: error: 'qDoubleSscanf' was not declared in this scope
src.cxx:5:10: fatal error: netinet/sctp.h: No such file or directory
src.cxx:2:10: fatal error: netlistmgr.h: No such file or directory
src.cxx:3:10: fatal error: bcm_host.h: No such file or directory
src.cxx:2:10: fatal error: EGL/fbdev_window.h: No such file or directory
src.cxx:9:1: error: 'mali_native_window' was not declared in this scope
src.cxx:9:21: error: 'w' was not declared in this scope
src.cxx:3:10: fatal error: EGL/eglvivante.h: No such file or directory
src.cxx:2:10: fatal error: wfd.h: No such file or directory
collect2: error: ld returned 1 exit status
src.cxx:2:10: fatal error: device/fbdriver.h: No such file or directory
src.cxx:1:11: fatal error: dwrite_2.h: No such file or directory
src.cxx:1:11: fatal error: dwrite_3.h: No such file or directory
src.cxx:1:11: fatal error: d2d1.h: No such file or directory
src.cxx:1:11: fatal error: d2d1_1.h: No such file or directory
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
```

The qt/5.15.2 were build successfully.

**Comment by ericLemanissier** [comment]
Please send the full build log

**Comment by synacker** [comment]
@ericLemanissier thank you for reply!
My logs:
[Conan install](https://paste.centos.org/view/969c4edb)
[CMakeOutput.log](https://paste.centos.org/view/9a5be75c)
[CMakeError.log](https://paste.centos.org/view/441a6366)

**Comment by synacker** [comment]
I don't understand why, but it looks like this commit were resolved my problem - https://github.com/synacker/daggy/commit/f752da0c38092d7ee3189259712f40d84bafe7e2.
I sucessfully compiled qt/6.0.0.

**Comment by jiapei100** [comment]
Hey, @synacker 

I got exactly the same error while **building Qt6 from source**. It looks it has **NOTHING** to do with daggy, but it should be a problem form Qt6 itself. I don't have a solution yet....

**Comment by synacker** [comment]
Hi, @jiapei100 

I solved my problem, when Qt were migrated to conan-center-index. You can see my recipe for building with Qt - https://github.com/conan-io/conan-center-index/blob/master/recipes/daggy/2.1/conanfile.py
