### ISSUE TITLE
Caching conan (boost) packages on appveyor

### ISSUE THREAD

**Issue by madebr** [bincrafters/community#134]
### Description of Problem, Request, or Question
I'm using conan for doing CI for the openrw project.
To speed things up, I've added the directory `C:\Users\Appveyor\.conan` to the cache.

After installation of conan (`pip3 install conan`),
`conan install` redownloads the conan boost packages even tough I enabled the cache.
Other packages such as bullet and ffmpeg are correctly cached.

How can I cache the boost packages?
I estimate caching would save 2 minutes from the build time + megabytes of bandwidth.

### Steps to reproduce (Include if Applicable)
Appveyor output of openrw build - 1st run: https://ci.appveyor.com/project/madebr/openrw/build/1.0.415
Appveyor output of openrw build - 1st run: https://ci.appveyor.com/project/madebr/openrw/build/1.0.416

**Comment by solvingj** [comment]
You need to also add `c:\.conan` to your cache statement.  Packages with `short_paths=True` are cached in this directory.

**Comment by madebr** [comment]
Thanks for the tip!
