### ISSUE TITLE
qt/6.0.0@bincrafters/stable: can not build qt 6.0.0 with qt3d option

### ISSUE THREAD

**Issue by yuriy-mochurad** [bincrafters/community#1342]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: qt/6.0.0@bincrafters/stable
  * Operating System+version: macos 11.1
  * Compiler+version: clang 12
  * Conan version: 1.32.1
  * Python version: 3.7.9

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=12.0
os=Macos
os_build=Macos
[options]
qt:qt3d=True
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
```
conan install qt/6.0.0@bincrafters/stable --build=missing -o qt:qt3d=True
```

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
ERROR: qt/6.0.0@bincrafters/stable: option 'qt3d' doesn't exist
Possible options are ['shared', 'commercial', 'opengl', 'with_vulkan', 'openssl', 'with_pcre2', 'with_glib', 'with_freetype', 'with_fontconfig', 'with_icu', 'with_harfbuzz', 'with_libjpeg', 'with_libpng', 'with_sqlite3', 'with_mysql', 'with_pq', 'with_odbc', 'with_libalsa', 'with_openal', 'with_zstd', 'GUI', 'widgets', 'device', 'cross_compile', 'sysroot', 'multiconfiguration', 'qtsvg', 'qtdeclarative', 'qttools', 'qttranslations', 'qtdoc', 'qtrepotools', 'qtqa', 'qtwayland', 'qtquickcontrols2', 'qtquicktimeline', 'qtquick3d', 'qtshadertools', 'qt5compat']

```

</details>

**Comment by ericLemanissier** [comment]
the fact that its status is `ignore` in https://code.qt.io/cgit/qt/qt5.git/tree/.gitmodules?h=v6.0.0#n128 makes it not part of qt6.
it is now shipped via conan https://www.qt.io/blog/qt-6-additional-libraries-via-package-manager, but unfortunately, I don't think there is another way to get the recipe than using qt online installer

**Comment by yuriy-mochurad** [comment]
@ericLemanissier I missed that it has `ignored` status. Thanks for quick explanation. Closing this ticket
