### ISSUE TITLE
qt/5.12.6 binary packages are not portable across different linux distros with the same toolchain

### ISSUE THREAD

**Issue by bukulin** [bincrafters/community#1345]
### Description of Problem, Request, or Question
Consider two linux distributions with essentially the same conan profile (same compiler, same compiler version, same architecture, etc). If the qt/5.12.6@bincrafters/stable package is built on one of the distros it cannot be reused on the other. The reason for that is that the libEGL.so and libGL.so files are searched by their absoulte path found at build time of Qt package by the CMake config file `<conan_home>/data/qt/bincrafters/stable/package/<hash>/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake`, and the files are placed in different directories in the different distros

Gentoo:
```
_qt5gui_find_extra_libs(EGL "/usr/lib64/libEGL.so" "" "")
_qt5gui_find_extra_libs(OPENGL "/usr/lib64/libGL.so" "" "")
```

Ubuntu-20.04:
```
_qt5gui_find_extra_libs(EGL "/usr/lib/x86_64-linux-gnu/libEGL.so" "" "")
_qt5gui_find_extra_libs(OPENGL "/usr/lib/x86_64-linux-gnu/libGL.so" "" "")
```

However the `_qt5gui_find_extra_libs` macro is able to find libraries **not** by their absolute path. If I tweak the formerly mentioned file just like this, then it works on each distro:
```
_qt5gui_find_extra_libs(EGL "EGL" "" "")
_qt5gui_find_extra_libs(OPENGL "GL" "" "")
```

Furthermore, recent versions of Qt do the search in this more flexible way.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.12.6@bincrafters/stable**
  * Operating System+version: **Gentoo default/linux/amd64/17.1**, **Ubuntu 20.04.01**
  * Compiler+version: **gcc-9.3.0**
  * ~~Docker image: **conanio/gcc7**~~
  * Conan version: **Conan 1.32.1**
  * Python version: 
    * Gentoo: **Python 3.7.9**
    * Ubuntu: **Python 3.8.5**

#### Gentoo
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]

#### Ubuntu-20.04
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]

### Steps to reproduce (Include if Applicable)

1. Build `qt/5.12.6@bincrafters/stable` package with the formerly mentioned profile on one of the distros
2. Upload the package to the artifactory server
3. Reuse the binary package on the other distro

### Logs (Include/Attach if Applicable)
During cmake configuration of my project that requries Qt5Gui and with the wrong libEGL.so path I got the following:
```
CMake Error at /home/<user>/.conan/data/qt/5.12.6/bincrafters/stable/package/0b9e875690f0787dd7ba37e1dfb0e8fe78012214/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake:15 (message):
  The imported target "Qt5::Gui" references the file

     "/usr/lib/x86_64-linux-gnu/libEGL.so"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/home/<user>/.conan/data/qt/5.12.6/bincrafters/stable/package/0b9e875690f0787dd7ba37e1dfb0e8fe78012214/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /home/<user>/.conan/data/qt/5.12.6/bincrafters/stable/package/0b9e875690f0787dd7ba37e1dfb0e8fe78012214/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake:45 (_qt5_Gui_check_file_exists)
  /home/<user>/.conan/data/qt/5.12.6/bincrafters/stable/package/0b9e875690f0787dd7ba37e1dfb0e8fe78012214/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake:68 (_qt5gui_find_extra_libs)
  /home/<user>/.conan/data/qt/5.12.6/bincrafters/stable/package/0b9e875690f0787dd7ba37e1dfb0e8fe78012214/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake:175 (include)
  <MyProject>/CMakeLists.txt:11 (find_package)


-- Configuring incomplete, errors occurred!
```

**Comment by ericLemanissier** [comment]
I think this is https://bugreports.qt.io/browse/QTBUG-87054. It has very little (understand zero) chance to be solved in qt 5. This is linked to qmake, so maybe it's fixed on qt6,which does not use qmake. Did you have a chance to try it?

**Comment by bukulin** [comment]
> I think this is https://bugreports.qt.io/browse/QTBUG-87054. It has very little (understand zero) chance to be solved in qt 5. This is linked to qmake, so maybe it's fixed on qt6,which does not use qmake. Did you have a chance to try it?

I was not precise enough, when I wrote "more recent versions". Actually everything is good with qt-5.15.2, but I suppose 5.14 is also good.

I'll do my best trying out qt-6, but the project has some CMake flaws, where this integrates, and it strictly requires qt-5.12.6

**Comment by ericLemanissier** [comment]
This recipe is now in the Conan Center Index.

Please migrate to the recipe version there.
If this is still an issue, please create a new issue in the Conan Center Index issue tracker.

Thanks!

https://conan.io/center/qt
