### ISSUE TITLE
qt/5.15.2@bincrafters/stable: failed to download sources

### ISSUE THREAD

**Issue by AndreyMlashkin** [bincrafters/community#1347]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.15.2@bincrafters/stable**
  * Operating System+version: **any**
  * Conan version: **conan 1.32.1**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=9.3
os=Linux
os_build=Linux
[options]
*:fPIC=True
[build_requires]
[env]

```

### Steps to reproduce (Include if Applicable)
conan install qt/5.15.2@bincrafters/stable  --build outdated

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
qt/5.15.2@bincrafters/stable: WARN: Trying to remove corrupted source folder
qt/5.15.2@bincrafters/stable: WARN: This can take a while for big packages
qt/5.15.2@bincrafters/stable: Configuring sources in /home/andrei/.conan/data/qt/5.15.2/bincrafters/stable/source
./reb	
ERROR: Error downloading file https://download.qt.io/archive/qt/5.15/5.15.2/single/qt-everywhere-src-5.15.2.tar.xz: 'HTTPSConnectionPool(host='download.qt.io', port=443): Max retries exceeded with url: /archive/qt/5.15/5.15.2/single/qt-everywhere-src-5.15.2.tar.xz (Caused by ReadTimeoutError("HTTPSConnectionPool(host='download.qt.io', port=443): Read timed out. (read timeout=60.0)"))'
Waiting 5 seconds to retry...
ERROR: qt/5.15.2@bincrafters/stable: Error in source() method, line 360
	tools.get(**self.conan_data["sources"][self.version])
	ConanException: Error downloading file https://download.qt.io/archive/qt/5.15/5.15.2/single/qt-everywhere-src-5.15.2.tar.xz: 'HTTPSConnectionPool(host='download.qt.io', port=443): Max retries exceeded with url: /archive/qt/5.15/5.15.2/single/qt-everywhere-src-5.15.2.tar.xz (Caused by ReadTimeoutError("HTTPSConnectionPool(host='download.qt.io', port=443): Read timed out. (read timeout=60.0)"))'

```

</details>

**Comment by ericLemanissier** [comment]
download.qt.io is down for today. It should be ok tomorrow

**Comment by ericLemanissier** [comment]
see https://lists.qt-project.org/pipermail/development/2021-January/040917.html

**Comment by AndreyMlashkin** [comment]
It is already a problem for quite a while... is it possible to use some mirror for downloading sources?

**Comment by ericLemanissier** [comment]
yeah :/ https://lists.qt-project.org/pipermail/development/2021-January/040919.html gives some mirrors. You can modify the recipe locally to download from one of these.
last news about the issue was yesterday : https://lists.qt-project.org/pipermail/development/2021-January/040926.html
You can watch https://www.qt.io/blog to know when it will be fixed
