### ISSUE TITLE
sqlite3 inclusion request into conan-center

### ISSUE THREAD

**Issue by pvicente** [bincrafters/community#135]
## Inclusion Request Review

This is a review for [sqlite3:bincrafters](https://bintray.com/bincrafters/public-conan/sqlite3%3Abincrafters/3.21.0%3Astable) inclusion request into conan-center.

### Package

sqlite3/3.21.0@bincrafters/stable

### Checks and Comments

**Recipe quality**

- [X] Git public repository
- [X] Recipe fields
- [X] Linter
- [X] Updated
- [X] Clean
- [X] test_package
- [X] Raise errors on invalid configurations
- [X] LICENSE of recipe
- [X] LICENSE of library

There is no [homepage attribute](http://docs.conan.io/en/latest/reference/conanfile/attributes.html?highlight=homepage) with **https://www.sqlite.org/** please add it to the recipe.

**CI integration**

- [X] (If not header only) CI configurations for Linux/MacOSX/Windows

There are some outdated builds (see table below) from recipe and all of them are using libstc++. As long as this library
is pure_c, there is no benefit of storing them in **bintray repo**. Could you please remove them?. See example command:

```conan remove sqlite3/3.21.0@bincrafters/stable --outdated -r bincrafters``` 

![screenshot 2018-02-22 17 56 20](https://user-images.githubusercontent.com/471109/36555426-d98284f6-17f9-11e8-95e7-bdacb5291228.png)

**Bintray Package Information**

- [X] Description
- [X] Licenses
- [ ] Tags
- [X] Maturity
- [X] Website (if any)
- [X] Issue tracker
- [X] Version control
- [X] Github repo (user/repo)

**Missing Tags**

### Additional comments

The recipe is looking good. Only address the suggested changes and it will be ready for the inclusion into conan-center.

**Comment by pvicente** [comment]
Hi @uilianries many thanks for your contribution.

Please have a look at the comments.

Cheers,
Pedro

**Comment by solvingj** [comment]
I removed the outdated builds, but FYI , adding a homepage will unfortunately render all the existing binaries outdated, meaning we'll have to do a full CI re-run.  What if we add it the homepage to the recipe in GIT but skip CI.  It will then get rolled into Bintray the next time we run CI, which at the very latest will be upon the next version release. 

I'm just apprehensive to re-run CI for cosmetics.  Not only is it wasteful, we're having tons of problems with CI lately, jobs are failing regularly due to random HTTP errors, and we're rebuilding a lot of things which were 99% complete.  It's really bad.

**Comment by pvicente** [comment]
Hi @solvingj, yes no problem, **homepage** is not a mandatory attribute so feel free to add to git and/or for next versions of this library.

Thanks for the quick reply.

**Comment by pvicente** [comment]
All done, now it's in conan-center:

https://bintray.com/conan/conan-center?filterByPkgName=sqlite3%3Abincrafters

**Comment by pvicente** [comment]
Hi @solvingj could you also add some tags for this library in bintray please?

Thanks,
Pedro

**Comment by solvingj** [comment]
done

**Comment by danimtb** [comment]
Hi @solvingj 
It seems something went wrong with the remove of outdated packages and now all Visual Studio packages are shown as outdated:

![image](https://user-images.githubusercontent.com/10808592/36584891-e7fc663c-187b-11e8-915a-02c6b3d8d418.png)

Could you check that please?

**Comment by solvingj** [comment]
it's rebuilding now.  i rebuilt earlier from mobile, but appveyor defaulted to building testing branch.  Should be done in an hour.
