### ISSUE TITLE
[question] qt/5.15.2 effective workflow for qml app dev on windows

### ISSUE THREAD

**Issue by TheHugeManatee** [bincrafters/community#1357]
I am having trouble trying to figure the workflow of how to use the qt package for app dev on windows.
Here's my problem: I have successfully built the qt package with some custom options (qt3d, qtdeclarative, qtquickcontrols/2) and manage to also successfully compile my application.

however, now I am trying to figure out a "proper" way to actually start and debug my application, however, I can't find a workflow that has all the dlls and qml files in the right places. things I've considered/tried:
 - normally I would use 'windeployqt', however it seems this is not built with the recipe
 - I have a standard dll copy command in my app's `conanfile.py`:
    ```python
    def imports(self):
        self.copy("*.dll", dst="bin", src="bin") # From bin to bin
    ```
    This puts the main qt dlls in the right place, but is still missing the platform plugins.
 - using the 'qt' generator creates a qt.conf pointing to the right qt conan package (making qt able to find the qml files), however this does not help with missing DLLs and platform plugin discovery
 - the `deploy` generator puts a qt subfolder with qt/bin and qt/qml folders next to the app binary, but I would again have to manually move them directly next to my binary so the dlls are discovered
 - The virtualenv generator does not out of the box set up the qt bin path either. I edited the qt conan recipe to include this line:
    ```python 
    def package_info(self):
        self.env_info.path.append(os.path.join(self.package_folder, "bin"))
         [...]
    ```
    which allows me to successfully run the application with the `./activate` script from the virtualenv generator. however, I still can't debug the application from within visual studio, which is quite inconvenient...

It feels like I am still missing some essential point here, is there a "proper" way to do this? of course I could start visual studio from the command line after the `./activate` to have the right environment but is this really the way to go?

**Comment by ericLemanissier** [comment]
Here are 2 quick pieces of advice:
- windeployqt is compiled if you set option `qt:qttools=True`
- use the `virtualrunenv` and run `activate_run` before starting your application

**Comment by TheHugeManatee** [comment]
Thank you @ericLemanissier for the tips!
The `virtualrunenv` did not really help with running the application (the env is specific to only one build config, switching between Debug and Release in the IDE would break), but it helps as in the normal `virtualenv` the `windeployqt` tool is not available. 

We ended up "manually" deploying the qt files through our app's conanfile.py: 
```python
    def imports(self):
        if self.settings.os == "Windows":
            self.copy("*.dll", dst=f"bin/{self.settings.build_type}", src="bin")
            self.copy("*.dll", dst=f"bin/{self.settings.build_type}", src="plugins")
            self.copy("*", dst=f"bin/{self.settings.build_type}", src="qml")
        # non-windows stuff
```
this works specifically for the combination of a) using the `cmake_multi` generator, b) using the CMake visual studio generator and c) running/developing from the visual studio IDE. In other cases the files need to be copied directly to the `bin/` folder.

I'm closing this as there does not seem to be an obvious solution, but would still be interested in more "elegant" solutions.
