### ISSUE TITLE
cpython

### ISSUE THREAD

**Issue by madebr** [bincrafters/community#136]
### Description of Problem, Request, or Question

I've created a `cpython` package at https://github.com/madebr/conan-cpython .
The package builds and tests ok on my linux system but fails on CI.

Can you point out some mistakes so I can fix these?
When finished, please take over ownership :sweat_smile: 

Travis: https://travis-ci.org/madebr/conan-cpython/
Appveyor: https://ci.appveyor.com/project/madebr/conan-cpython

### Package Details (Include if Applicable)
* Package Name/Version: **cpython/3.6.4**

Thanks for the support!

**Comment by solvingj** [comment]
Ok, i've made a PR with a substantial change to the windows build (and consequently moved the linux build around a bit).  Still doesn't work, but we can do more in time.

**Comment by madebr** [comment]
Thanks! I will poke further and report back when I get further.

**Comment by solvingj** [comment]
So far, the ones we don't have are: 

```
Fetching external libraries...
Fetching bzip2-1.0.6...
Fetching openssl-1.0.2k...
Fetching sqlite-3.21.0.0...
Fetching tcl-core-8.6.6.0...
Fetching tk-8.6.6.0...     <---------
Fetching tix-8.4.3.6...    <---------
Fetching xz-5.2.2...       <---------
Fetching external binaries...
Fetching nasm-2.11.06...
```

**Comment by solvingj** [comment]
@madebr would you be willing to open issues on the conan wishlist for these libs, and then we can work towards it that way?  Would you be willing to work on packaging these? 

If so, we can create a small github project to track the progress. Otherwise, i'm not sure anyone on the team currently has need for this library or the deps.

**Comment by madebr** [comment]
This look promising: https://github.com/python-cmake-buildsystem/python-cmake-buildsystem

**Comment by madebr** [comment]
I have updated it to support cpython 3.7.1.
https://github.com/madebr/conan-cpython/tree/testing/3.7.1

It works if non-crosscompiling. Building on x86_64 for x86_64.
**But fails for building x86_64 for x86.**

I have packaged the dependencies and tested on my machine only (linux x86_64), but not uploaded them (yet).

**Comment by solvingj** [comment]
ping @madebr any further updates here?

**Comment by madebr** [comment]
- I think I have it working (for Linux at least)
- CPython can be used as an installer so #625 applies
  Because cpython_installer and cpython have so much, I prefer to keep them both in the same repo.
  I have created conan packages for these dependencies, for which I will open issues in the future.
- a cpython_installer is absolutely required because for building e.g. cpython 3.7.2, a native cpython version with the same MAJOR.MINOR version is required
-  bincrafters/conan-center misses recipes for some requirements.
  I have created recipes for these dependencies, for which I will open issues in the future.
  These recipes compile on Linux but not all do on Linux and/or Windows.
    * libdb (berkeley's database)
    * mpdecimal
    * gdbm (GNU dbm)
    * libnsl
    * tk

Once these dependencies get merged, I will finish cpython.

**Comment by SSE4** [comment]
this should go to the https://github.com/conan-io/conan-center-index now

**Comment by Croydon** [comment]
cpython might be non-trivial, in that case Bincrafters could serve as a collaborative place to get this recipe mature

**Comment by Guekka** [comment]
Sorry to bump a closed issue, but I'm wondering about the status of this recipe, now that it looks like all the dependencies are available

**Comment by madebr** [comment]
I plan to look at it again in the future.

**Comment by solvingj** [comment]
I'll try to work with you in slack.

**Comment by madebr** [comment]
See conan-io/conan-center-index#1510
