### ISSUE TITLE
Problems installing ffmpeg on Linux

### ISSUE THREAD

**Issue by rudolfheszele** [bincrafters/community#1365]
Hi,

I am trying to use the ffmpeg package on Linux, but I cannot install it, I need to build it from source. I tried with GCC version 9, and Clang version 10, nut no luck. (Building form source works fine)
Doing a conan search - `conan search --remote all --query 'os=Linux AND arch=x86_64 AND compiler=gcc AND compiler.version=9' ffmpeg/4.2.1@bincrafters/stable` - shows packages so I should be able to use the pre-built ones.
I think the issue with the settings.compiler.libcxx value. If I add it to the query, then no packages are found. (It is not defined for ffmpeg, since it is pure C, I guess)
I tried to create a profile, where the libcxx is not defined, but then I got the following error:
```
$ conan install --profile gcc-ffmpeg  ffmpeg/4.2.1@bincrafters/stable
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

ERROR: openh264/1.7.0: 'settings.compiler.libcxx' value not defined
```
It might be that I do not know conan enough, but I wonder how could I use the prebuilt packages on Linux?
Is it a problem in the ffmpeg package or the openh264 package? (Or me not knowing conan?)

Thanks for the help in advance!

**Comment by ericLemanissier** [comment]
@rudolfheszele you have to define libcxx in your profile, but it should not have any impact on which pre-existing binary is downloaded.  Can you please give us the full console log of the error (with libcxx set) ?

**Comment by ericLemanissier** [comment]
This recipe is now in the Conan Center Index.

Please migrate to the recipe version there.
If this is still an issue, please create a new issue in the Conan Center Index issue tracker.

Thanks!

https://conan.io/center/ffmpeg
