### ISSUE TITLE
Inclusion Request: flecs

### ISSUE THREAD

**Issue by rawbby** [bincrafters/community#1366]
### Package Details

  * Package Name: **flecs**
  * Platform/Compiler: 
    * Windows: msvc
    * Ubuntu: gcc (7, 8, 9, 10), clang (8, 9)
    * MacOS: gcc 10, clang 9
  * Conan recipe repository: **https://github.com/rawbby/conan-flecs**

### Inclusion request

  * [x] I want that my Conan recipe is getting included into the Bincrafters organisation
  * [x] I understand that if my request is accepted we are cloning your repository with all its history into Bincrafters, adapt some configurations and meta data if needed, and publishing it under the Bincrafters name and accounts
  * [x] I have used the Bincrafters templates to develop my Conan recipe - https://github.com/bincrafters/templates
  * [x] My Conan recipe and all parts of it are licensed under the MIT license - https://choosealicense.com/licenses/mit/
    * Bincrafters are releasing all recipes under MIT license. If you want to have your recipe within Bincrafters we kindly ask you to do the same
    * it is okay if your test_package contains code from the upstream project under the upstream project's license, as long as it is clearly mentioned within the test_package files
  * [x] My Conan recipe covers (at least) the latest stable version which is available for the package
  * [x] I know that my Conan recipe is working on all operating system and compilers mentioned above right now
    * if not: please provide here links to your CI platforms and / or build logs and describe the problems you encounter
  * [x] I'm willing to help to maintain the recipe even after it is included into Bincrafters

### Comments

As I am new to the Bincrafters Community I dont know if the package is perfectly polished yet.
If someone can have a look at the repository, that would be very nice! :)

Atm the github workflow contains a gcc 4.9 job. gcc 4.9 is not supported by the package, but I dont know how to specify the matrix using bincrafters-package-tools.

 #1355 It would be nice if the flecs_STATIC compile definition would be set by the conan target for cmake.
I dont know if this is possible.

### Checklist for the Bincrafters team

  * [ ] There is no such Conan package yet in conan-center, conan-community or Bincrafters
  * [ ] The project is either popular or deserves to be maintained for another good reason (we can't package every single project out there)
  * [ ] [bincrafters-conventions](https://github.com/bincrafters/bincrafters-conventions) reports no complains; the recipe fulfills our general quality requirements and conventions
  * [ ] The recipe is cloned into our organisation; CI is enabled and configurated and succeeds
  * [ ] There is a branch protection rule for `stable/*` branches, which requires a pull request with at least one approval first before things can get published
  * Considering granding the inclusion request author push rights to the recipe repository (there is no guarantee that everyone is getting push rights, we decide this on a case-to-case base)

**Comment by Croydon** [comment]
Hi @rawbby!

The recipe seems to have no dependencies (which means also no dependencies that are not yet in Conan Center Index), therefore the recipe should go directly into the Conan Center Index instead of Bincrafters

You can check it out here and create a pull request against it: https://github.com/conan-io/conan-center-index

**Comment by rawbby** [comment]
Hey @Croydon, thanks for the input! I opened an issue [https://github.com/conan-io/conan-center-index/issues/4541](https://github.com/conan-io/conan-center-index/issues/4541) in Conan Center Index.
