### ISSUE TITLE
[Qt 6.0.0] <integration with cmake find_package>

### ISSUE THREAD

**Issue by petrolifero** [bincrafters/community#1367]
I am using qt 6.0.0/stable in a toy project, but get errors because qt package don't define targets to the meta-object compiler and variables like QT_VERSION_MAJOR e QT_VERSION_MINOR. To test works, with 1 class using Q_OBJECT, so needed moc, I need to create a FindQt6.cmake that build this wrapper, something like

FindQt6.cmake
```
set(CMAKE_INCLUDE_CURRENT_DIR ON)

set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)
set(CMAKE_AUTOUIC ON)

set(QT_VERSION_MAJOR 6)
set(QT_VERSION_MINOR 0)

find_package(qt 6.0.0 EXACT REQUIRED)
add_library(Qt6 ALIAS qt::qt)
add_executable(Qt6::moc IMPORTED GLOBAL)
set_target_properties(Qt6::moc PROPERTIES IMPORTED_LOCATION ${AUTOMOC_EXECUTABLE})
add_executable(Qt6::rcc IMPORTED GLOBAL)
set_target_properties(Qt6::rcc PROPERTIES IMPORTED_LOCATION ${AUTORCC_EXECUTABLE})
add_executable(Qt6::uic IMPORTED GLOBAL)
set_target_properties(Qt6::uic PROPERTIES IMPORTED_LOCATION ${AUTOUIC_EXECUTABLE})
```

The find_package(qt 6.0.0 ...) is getting the qt from conan. The AUTO*_EXECUTABLE was inserted in my conanfile with fixed paths, because I don't see in the qt conanfile exposing the bindirs.

How can I remove this auxiliary cmake and stop setting this variables?

conanfile.py : 
```
from conans import ConanFile, CMake, tools
import os

class KhanwarsSimplifierConan(ConanFile):
    name = "khanwarsSimplifier"
    version = "0.1"
    license = "AGPLv3+"
    author = "João Pedro Abreu de Souza <jp_abreu@id.uff.br>"
    url = "<Package recipe repository url here, for issues about the package>"
    description = "<Description of KhanwarsSimplifier here>"
    topics = ("<Put some tag here>", "<here>", "<and here>")
    settings = "os", "compiler", "build_type", "arch"
    generators = "cmake"
    requires = "qt/6.0.0@bincrafters/stable"

    def config_options(self):
        pass

    def source(self):
        pass

    def build(self):
        cmake = CMake(self,"Ninja")
        cmake.definitions['CMAKE_MODULE_PATH']=self.build_folder + ";" + self.source_folder + "/" + "modules"
        cmake.definitions['AUTOMOC_EXECUTABLE']="/home/joao/.conan/data/qt/6.0.0/bincrafters/stable/package/5371b0f762d64db60f6a878d67f97c68c4259a65/bin/moc"
        cmake.definitions['AUTORCC_EXECUTABLE']="/home/joao/.conan/data/qt/6.0.0/bincrafters/stable/package/5371b0f762d64db60f6a878d67f97c68c4259a65/bin/rcc"
        cmake.definitions['AUTOUIC_EXECUTABLE']="/home/joao/.conan/data/qt/6.0.0/bincrafters/stable/package/5371b0f762d64db60f6a878d67f97c68c4259a65/bin/uic"
        cmake.configure()
        cmake.build()
        cmake.test()

    def package(self):
        pass

    def package_info(self):
        pass

```
main CMakeLists.txt
./CMakeLists.txt
```
cmake_minimum_required(VERSION 3.19.3)
project(khanWars)
enable_testing()


#find_package(qt 6.0.0 EXACT REQUIRED)
find_package(Qt6 EXACT REQUIRED)

set(CMAKE_CXX_STANDARD 17)
add_compile_options(-fPIC)

add_subdirectory(user)
add_subdirectory(console)

add_executable(main main.cpp)

target_link_libraries(main PRIVATE qt::qt)
target_link_libraries(main PRIVATE user)
target_link_libraries(main PRIVATE console)




add_test(NAME findUsernameAndPassword COMMAND main)
set(sucessTestEnv "KHANWARS_USERNAME=petrolifero" "KHANWARS_PASSWORD=123")
set_tests_properties(findUsernameAndPassword PROPERTIES ENVIRONMENT "${sucessTestEnv}")

add_test(NAME dontFindUsernameOrPassword COMMAND main)
set_tests_properties(dontFindUsernameOrPassword PROPERTIES WILL_FAIL true)

```

CMakeLists.txt from module console, that is the module using the moc, so the source of this hack
./console/CMakeLists.txt
```
add_library(console
		STATIC
		console.cpp
		console.hpp)
target_include_directories(console PUBLIC .)
target_link_libraries(console PUBLIC Qt6)
target_link_libraries(console PRIVATE user)

```

**Comment by petrolifero** [comment]
I install de dependencies on build folder using

conan install .. -gcmake_find_package

**Comment by ericLemanissier** [comment]
can you please try with`qt/6.0.2` (without `@bincrafters/stable`) ? The recipe was integrated in conan-center, and has support for components, mimicking native cmake targets.

**Comment by kobalicek** [comment]
I'm facing the same issue.

I can compile Qt6 with Conan, but I cannot use it.

@ericLemanissier Can you share a minimal CMakeLists.txt that would demonstrate how to use Qt6 with Conan+CMake?

The current status is:
  - I failed to use `find_package()`
  - I failed to use `CMAKE_AUTOMOC` feature

So I'm really wondering how this should be used?

**Comment by ericLemanissier** [comment]
if you are using `qt/*@bincrafters/stable`, there are two way to consume from cmake: https://github.com/bincrafters/conan-qt/blob/testing/6.0.0/test_package/cmake/CMakeLists.txt and https://github.com/bincrafters/conan-qt/blob/testing/6.0.0/test_package/cmake_find_package_multi/CMakeLists.txt. the later requires that you invoke moc manually.

But as I said in my last message, you should switch to `qt/6.0.2` (without `@bincrafters/stable`) which can be consumed from cmake in a more standard way: https://github.com/conan-io/conan-center-index/blob/master/recipes/qt/6.x.x/test_package/CMakeLists.txt

**Comment by kobalicek** [comment]
Thanks a lot of the link to the test. I was actually trying `qt/6.0.3`, but I wasn't able to get it working - even when I figured the find_package I was not able to link to Qt. Maybe I should note that I used `qt:shared=False` option.

**Comment by ericLemanissier** [comment]
Please report the issue on https://github.com/conan-io/conan-center-index/issues, with all the details mentionned in the issue template

**Comment by petrolifero** [comment]
Same problem here. I tested with 6.0.3, don't need more the findqt.cmake, because the components are great :)
But now broke with a non defined symbol on vtable. On web, this look like a problem with automoc, so I enable CMAKE_AUTOMOC and the problem appear only on a internal library

`[20/20] Linking CXX executable main
FAILED: main 
: && /usr/bin/c++ -O3 -DNDEBUG  CMakeFiles/main.dir/main_autogen/mocs_compilation.cpp.o CMakeFiles/main.dir/main.cpp.o -o main -L/home/joao/.conan/data/qt/6.0.3/_/_/package/a4f3c9d49d5ce61f2b2f3dd61da3feebfea5dcc0/lib   -L/home/joao/.conan/data/pcre2/10.36/_/_/package/3b544e62795c293d95ba624360f2fc91ca32ce44/lib   -L/home/joao/.conan/data/icu/68.2/_/_/package/1524904dd725e06dec6d8b171834126a56e52d5a/lib   -L/home/joao/.conan/data/openssl/1.1.1j/_/_/package/6af9cc7cb931c5ad942174fd7838eb655717c709/lib -Wl,-rpath,/home/joao/.conan/data/qt/6.0.3/_/_/package/a4f3c9d49d5ce61f2b2f3dd61da3feebfea5dcc0/lib:/home/joao/.conan/data/pcre2/10.36/_/_/package/3b544e62795c293d95ba624360f2fc91ca32ce44/lib:/home/joao/.conan/data/icu/68.2/_/_/package/1524904dd725e06dec6d8b171834126a56e52d5a/lib:/home/joao/.conan/data/openssl/1.1.1j/_/_/package/6af9cc7cb931c5ad942174fd7838eb655717c709/lib  user/libuser.a  console/libconsole.a  api/libapi.a  user/libuser.a  api/libapi.a  /home/joao/.conan/data/qt/6.0.3/_/_/package/a4f3c9d49d5ce61f2b2f3dd61da3feebfea5dcc0/lib/libQt6Network.a  /home/joao/.conan/data/qt/6.0.3/_/_/package/a4f3c9d49d5ce61f2b2f3dd61da3feebfea5dcc0/lib/libQt6Core.a  /home/joao/.conan/data/qt/6.0.3/_/_/package/a4f3c9d49d5ce61f2b2f3dd61da3feebfea5dcc0/lib/libQt6Core_qobject.a  /home/joao/.conan/data/pcre2/10.36/_/_/package/3b544e62795c293d95ba624360f2fc91ca32ce44/lib/libpcre2-posix.a  /home/joao/.conan/data/pcre2/10.36/_/_/package/3b544e62795c293d95ba624360f2fc91ca32ce44/lib/libpcre2-8.a  /home/joao/.conan/data/zlib/1.2.11/_/_/package/6af9cc7cb931c5ad942174fd7838eb655717c709/lib/libz.a  /home/joao/.conan/data/bzip2/1.0.8/_/_/package/da606cf731e334010b0bf6e85a2a6f891b9f36b0/lib/libbz2.a  /home/joao/.conan/data/pcre2/10.36/_/_/package/3b544e62795c293d95ba624360f2fc91ca32ce44/lib/libpcre2-16.a  /home/joao/.conan/data/pcre2/10.36/_/_/package/3b544e62795c293d95ba624360f2fc91ca32ce44/lib/libpcre2-32.a  /home/joao/.conan/data/double-conversion/3.1.5/_/_/package/b911f48570f9bb2902d9e83b2b9ebf9d376c8c56/lib/libdouble-conversion.a  /home/joao/.conan/data/icu/68.2/_/_/package/1524904dd725e06dec6d8b171834126a56e52d5a/lib/libicuio.a  /home/joao/.conan/data/icu/68.2/_/_/package/1524904dd725e06dec6d8b171834126a56e52d5a/lib/libicutest.a  /home/joao/.conan/data/icu/68.2/_/_/package/1524904dd725e06dec6d8b171834126a56e52d5a/lib/libicutu.a  /home/joao/.conan/data/icu/68.2/_/_/package/1524904dd725e06dec6d8b171834126a56e52d5a/lib/libicui18n.a  /home/joao/.conan/data/icu/68.2/_/_/package/1524904dd725e06dec6d8b171834126a56e52d5a/lib/libicuuc.a  -lm  /home/joao/.conan/data/icu/68.2/_/_/package/1524904dd725e06dec6d8b171834126a56e52d5a/lib/libicudata.a  -lstdc++  /home/joao/.conan/data/openssl/1.1.1j/_/_/package/6af9cc7cb931c5ad942174fd7838eb655717c709/lib/libssl.a  /home/joao/.conan/data/openssl/1.1.1j/_/_/package/6af9cc7cb931c5ad942174fd7838eb655717c709/lib/libcrypto.a  -ldl  -lrt  -lpthread && :
/usr/bin/ld: /home/joao/.conan/data/qt/6.0.3/_/_/package/a4f3c9d49d5ce61f2b2f3dd61da3feebfea5dcc0/lib/libQt6Network.a(qdecompresshelper.cpp.o): in function 'QDecompressHelper::setEncoding(QDecompressHelper::ContentEncoding)':
qdecompresshelper.cpp:(.text._ZN17QDecompressHelper11setEncodingENS_15ContentEncodingE+0x31): undefined reference to 'BrotliDecoderCreateInstance'
/usr/bin/ld: /home/joao/.conan/data/qt/6.0.3/_/_/package/a4f3c9d49d5ce61f2b2f3dd61da3feebfea5dcc0/lib/libQt6Network.a(qdecompresshelper.cpp.o): in function 'QDecompressHelper::clear()':
qdecompresshelper.cpp:(.text._ZN17QDecompressHelper5clearEv+0x40): undefined reference to 'BrotliDecoderDestroyInstance'
/usr/bin/ld: /home/joao/.conan/data/qt/6.0.3/_/_/package/a4f3c9d49d5ce61f2b2f3dd61da3feebfea5dcc0/lib/libQt6Network.a(qdecompresshelper.cpp.o): in function 'QDecompressHelper::readBrotli(char*, long long)':
qdecompresshelper.cpp:(.text._ZN17QDecompressHelper10readBrotliEPcx+0x58): undefined reference to 'BrotliDecoderHasMoreOutput'
/usr/bin/ld: qdecompresshelper.cpp:(.text._ZN17QDecompressHelper10readBrotliEPcx+0xae): undefined reference to 'BrotliDecoderHasMoreOutput'
/usr/bin/ld: qdecompresshelper.cpp:(.text._ZN17QDecompressHelper10readBrotliEPcx+0xc0): undefined reference to 'BrotliDecoderTakeOutput'
/usr/bin/ld: qdecompresshelper.cpp:(.text._ZN17QDecompressHelper10readBrotliEPcx+0x16a): undefined reference to 'BrotliDecoderDecompressStream'
/usr/bin/ld: qdecompresshelper.cpp:(.text._ZN17QDecompressHelper10readBrotliEPcx+0x199): undefined reference to 'BrotliDecoderDestroyInstance'
/usr/bin/ld: qdecompresshelper.cpp:(.text._ZN17QDecompressHelper10readBrotliEPcx+0x26c): undefined reference to 'BrotliDecoderHasMoreOutput'
/usr/bin/ld: qdecompresshelper.cpp:(.text._ZN17QDecompressHelper10readBrotliEPcx+0x5f9): undefined reference to 'BrotliDecoderGetErrorCode'
/usr/bin/ld: qdecompresshelper.cpp:(.text._ZN17QDecompressHelper10readBrotliEPcx+0x600): undefined reference to 'BrotliDecoderErrorString'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.`

I know the moc work because the compiled files double (10 -> 20)

**Comment by ericLemanissier** [comment]
This issue is not about bincrafters recipe, Please report the issue on https://github.com/conan-io/conan-center-index/issues, with all the details mentionned in the issue template

**Comment by petrolifero** [comment]
Ok, thank you very much

**Comment by ericLemanissier** [comment]
https://github.com/conan-io/conan-center-index/issues/5434
