### ISSUE TITLE
bison/3.7.1: m4 subprocess failed

### ISSUE THREAD

**Issue by kad-beekw** [bincrafters/community#1369]
I'm unable to use Bison because of an issue with m4.  That dependency is also installed, but the Bison executable does not seem able to find the m4 executable:

```
m4 subprocess failed: No such file or directory
```

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **bison/3.7.1**
  * Operating System+version: **Linux Ubuntu 20.10**
  * Compiler+version: **GCC 10.2.0**
  * Conan version: **conan 1.34.0**
  * Python version: **Python 3.8.6**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)

```
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=10
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

1. Install Bison through Conan:

    ```sh
    conan install bison/3.7.1@_/_
    ```

2. Call Bison over an input file:

   ```sh
   ~/.conan/data/bison/3.7.1/_/_/package/21011818b664ba5f28bbba5f38f3117d33c4b91b/bin/bison test.yy
   ```

3. Notice that the following error is emitted:

    ```sh
    /home/{user}/.conan/data/bison/3.7.1/_/_/package/21011818b664ba5f28bbba5f38f3117d33c4b91b/bin/bison: m4 subprocess failed: No such file or directory
    ```

**Comment by Croydon** [comment]
You are either 

a) actually using the bison/m4 Bincrafters recipes, which are obsolete. In this case please migrate to the versions in the Conan Center Index https://github.com/conan-io/conan-center-index

b) you are using the recipes from there and choose the wrong issue tracker 😄

**Comment by kad-beekw** [comment]
I have opened this issue in the correct repo now: <https://github.com/conan-io/conan-center-index/issues/4699>
