### ISSUE TITLE
conan-sqlite3 binaries are out of date for Windows

### ISSUE THREAD

**Issue by pvicente** [bincrafters/community#137]
Hi @solvingj,

This is the current status of the binaries.

![screenshot 2018-02-23 09 05 40](https://user-images.githubusercontent.com/471109/36586459-caf58b9c-1879-11e8-963a-06824cd67b00.png)

And it loos like latest merge into stable/3.21.0 was skipped for Appveyor but not for Travis.

Please update binaries for generated with Appveyor.

**Comment by solvingj** [comment]
it's rebuilding now. i rebuilt earlier from mobile, but appveyor defaulted to building testing branch. Should be done in an hour.

**Comment by solvingj** [comment]
![image](https://user-images.githubusercontent.com/8557737/36600407-2ba77238-1880-11e8-978d-56cd7463b689.png)
