### ISSUE TITLE
[request] ruby_installer/2.7.2

### ISSUE THREAD

**Issue by jmarrec** [bincrafters/community#1374]
### Package Details
  * Package Name/Version: **ruby_installer/2.7.2**
  * Changelog: **https://www.ruby-lang.org/en/news/2020/10/02/ruby-2-7-2-released**

Cf PR: https://github.com/bincrafters/conan-ruby_installer/pull/8

The above mentioned version is newly released by the upstream project and not yet available as a recipe. Please add this version.

I actually currently use 2.5.5, but on mac m1 I cannot compile ruby_installer/2.5.5 due to a C99 thing. Hoping that ruby 2.7.2 will fix it

```
compiling ../../source_subfolder/ext/fiddle/conversions.c
../../source_subfolder/ext/fiddle/closure.c:264:14: error: implicit declaration of function 'ffi_prep_closure' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    result = ffi_prep_closure(pcl, cif, callback, (void *)self);
             ^
1 error generated.
make[2]: *** [closure.o] Error 1
make[2]: *** Waiting for unfinished jobs.
```

**Comment by Croydon** [comment]
Done
