### ISSUE TITLE
conan-log4cplus inclusion request into conan-center

### ISSUE THREAD

**Issue by pvicente** [bincrafters/community#138]
## Inclusion Request Review

This is a review for [log4cplus:bincrafters](https://bintray.com/bincrafters/public-conan/log4cplus%3Abincrafters/1.2.1%3Astable) inclusion request into conan-center.

### Package

log4cplus/1.2.1@bincrafters/stable

### Checks and Comments

**Recipe quality**

- [X] Git public repository
- [X] Recipe fields
- [X] Linter
- [X] Updated
- [X] Clean
- [X] test_package
- [X] Raise errors on invalid configurations
- [X] LICENSE of recipe
- [X] LICENSE of library

* Add ``homepage=https://downloads.sourceforge.net/project/log4cplus/log4cplus-stable`` attribute in the recipe

* [test_package](https://github.com/bincrafters/conan-log4cplus/blob/testing/1.2.1/test_package/test_package.cpp#L31) has commented out ``log4cplus::Initializer initializer;`` which is not available in this library version, please remove it.

**CI integration**

- [X] (If not header only) CI configurations for Linux/MacOSX/Windows

 * Binaries are not up to date for Windows (see below table), and ``MINGW_CONFIGURATIONS`` is commented in [appveyor.yml](https://github.com/bincrafters/conan-log4cplus/blob/testing/1.2.1/appveyor.yml#L9) please remove it.

![screenshot 2018-02-23 13 01 40](https://user-images.githubusercontent.com/471109/36595364-d0012a72-1899-11e8-842f-67ee036f1031.png)

**Bintray Package Information**

- [X] Description
- [X] Licenses
- [X] Tags
- [X] Maturity
- [X] Website (if any)
- [X] Issue tracker
- [X] Version control
- [X] Github repo (user/repo)

### Additional comments

The library looks ok. Please have a look at the comments and ensure that CI binaries are up to date in [bintray](https://bintray.com/bincrafters/public-conan/log4cplus%3Abincrafters/1.2.1%3Astable).

Thanks for your contribution.

**Comment by pvicente** [comment]
Hi @solvingj just a curiosity, I've seen that there are more options supported by this library but they haven't been included into the recipe. Any special reason ? 

- https://github.com/log4cplus/log4cplus/blob/REL_1_2_1/CMakeLists.txt#L29

- https://github.com/log4cplus/log4cplus/blob/REL_1_2_1/CMakeLists.txt#L66

**Comment by solvingj** [comment]
No. It was brought in from community member, i think we should try to add good support for these options.  Please put on hold until we have chance to revisit.

**Comment by pvicente** [comment]
Hi @solvingj for us these options are not mandatory and they are not blocking the inclusion request, it was only a comment/open question.

It's good if you add some of them maybe in a future release or new version but for us the package would be ready without modelling these options in ``conanfile.py``.

**Comment by solvingj** [comment]
I really don't like the idea of adding/removing options after pushing to Conan center.  There will be times when we really need to do it and it's unavoidable, but we have time now.  Also, these are trivial. Let me see if i can get done before i finish today.

**Comment by solvingj** [comment]
Ok, here's a first run through with the new options.  lets see how she goes: 
https://travis-ci.org/bincrafters/conan-log4cplus
https://ci.appveyor.com/project/BinCrafters/conan-log4cplus/build/1.0.43

**Comment by pvicente** [comment]
I've checked the [changes](https://github.com/bincrafters/conan-log4cplus/compare/stable/1.2.1...testing-options/1.2.1) and I have a few comments:

It adds a requirement```libiconv/1.15@bincrafters/stable``` so we need to do inclusion request for that library before accepting ```log4cplus```, please go ahead if it hasn't been done.

About the requirement, conan didn't retrieve it with the current changes but I did a small change:

```
11:25 $ git diff
diff --git a/conanfile.py b/conanfile.py
index 22f181f..daa7d02 100644
--- a/conanfile.py
+++ b/conanfile.py
@@ -52,7 +52,7 @@ class Log4cplusConan(ConanFile):
         else:
             self.options.working_c_locale = False

-    def config_options(self):
+    def requirements(self):
         if self.options.with_iconv:
             self.requires("libiconv/1.15@bincrafters/stable")
```

And after that the libiconv is retrieved by conan. But I'm trying to use it in shared mode with:

```conan create . pedro/test -o log4cplus:with_iconv=True -o *:shared=True -k```
and I can see that test_package is try to link with it:

```
/usr/bin/c++    -m64 -O3 -DNDEBUG        -rdynamic CMakeFiles/test_package.dir/test_package.cpp.o  -o bin/test_package  -L/home/conan/.conan/data/log4cplus/1.2.1/pedro/test/package/c1848b135137581ac3c775621b0d0937dbb86ba6/lib  -L/home/conan/.conan/data/libiconv/1.15/bincrafters/stable/package/e30939caa2339df448fcf9917da7b5ebc54646b6/lib -Wl,-rpath,/home/conan/.conan/data/log4cplus/1.2.1/pedro/test/package/c1848b135137581ac3c775621b0d0937dbb86ba6/lib:/home/conan/.conan/data/libiconv/1.15/bincrafters/stable/package/e30939caa2339df448fcf9917da7b5ebc54646b6/lib -llog4cplus -ldl -lpthread -liconv
```

but  I can't see it with ```ldd test_package```, I can only see ```liblog4cplus``` 
```
conan@830d58f05955:/Users/pvicente/git/conan/conan-community/review_libraries/conan-log4cplus$ ldd test_package/build/ff52de0bf1aafb28a3f193fa8569095f6e7a9100/bin/test_package
    linux-vdso.so.1 =>  (0x00007ffd09d19000)
    liblog4cplus.so.0 => /home/conan/.conan/data/log4cplus/1.2.1/pedro/test/package/c1848b135137581ac3c775621b0d0937dbb86ba6/lib/liblog4cplus.so.0 (0x00007fd42e845000)
    libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fd42e4c3000)
    libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fd42e2ad000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd42dee3000)
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd42dcc6000)
    librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fd42dabe000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd42d7b5000)
    /lib64/ld-linux-x86-64.so.2 (0x00007fd42ead9000)```

Maybe I'm wrong but I thought that the ```test_package``` should be linked against both shared libraries.
 
Another thing is the check for fPIC, ```if self.settings.compiler in ("clang", "gcc"):``` we are doing it with ```self.settings.os != "Windows"``` and maybe pthread too in package_info, pthread is not for windows definitely.

It would be good if you can test a bit, some of these options, maybe the ones including extra requirements, and check that they are enabled in the final build with CMake.

Let me know if you need any help,
Pedro

**Comment by solvingj** [comment]
I've submitted the libiconv package to conan center. 

I've replaced the `config_options` method with the `requirements` method locally.

We've had many discussions about how to filter with fPIC. Just last week i was told by several people on the team that it's bad to use the OS as the filter for this.  I will defer to @SSE4 on this. 

Also, he originally created the `libiconv` package, so perhaps he can comment on your linking question.

**Comment by SSE4** [comment]
libiconv isn't linked unless test_package uses log4cplus APIs which actually require libiconv. need to look int o this.
for -fPIC, in general, filter by OS might be more relevant than by compiler. e.g. fPIC passed to MinGW is not harmful, but useless, and produces warning.

**Comment by pvicente** [comment]
Hi @SSE4 @solvingj, thanks for your quick reply.

I can confirm that linking is working when test_package is using **libiconv** explicitly, thanks @SSE4 for making it more clear.

```bash
conan@b0c0e1ed2221:/Users/pvicente/git/conan/conan-community/review_libraries/conan-log4cplus/test_package/build/ff52de0bf1aafb28a3f193fa8569095f6e7a9100/bin$ ldd test_package
	linux-vdso.so.1 =>  (0x00007ffdc9d4d000)
	liblog4cplus.so.0 => /home/conan/.conan/data/log4cplus/1.2.1/pedro/test/package/c1848b135137581ac3c775621b0d0937dbb86ba6/lib/liblog4cplus.so.0 (0x00007fd11a982000)
	libiconv.so.2 => /home/conan/.conan/data/libiconv/1.15/bincrafters/stable/package/e30939caa2339df448fcf9917da7b5ebc54646b6/lib/libiconv.so.2 (0x00007fd11a691000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fd11a30f000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fd11a0f9000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd119d2f000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd119b12000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fd11990a000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd119601000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fd11ac16000)
```

I'm reviewing now [libiconv inclusion request](https://bintray.com/bincrafters/public-conan/libiconv:bincrafters/1.15:stable) so we can proceed with ``log4cplus``.

Please do all the changes needed to make it work with all the supported options.

Many thanks.

**Comment by pvicente** [comment]
Hi @SSE4, many thanks for the changes.

I've been reviewing the latest version and it looks ok. Checker is fine and binaries are ok.

## Checker

![screenshot 2018-03-06 08 49 14](https://user-images.githubusercontent.com/471109/37022980-75a2e8b4-211c-11e8-8f9e-d3a94ebef3f8.png)

## Binaries

![screenshot 2018-03-06 08 57 26](https://user-images.githubusercontent.com/471109/37023009-8670a7bc-211c-11e8-9197-3e5e4804779f.png)

I've also been checking **with_iconv** support that you've added to the test package and I have a question for you 😄 

Building the package with **iconv** and **shared** option enabled ``` conan create . pedro/test -o *:with_iconv=True -o *:shared=True```, I can see that the final test_package binary is not linked/using ```libiconv.so```

```
conan@d6b642a355ac:/Users/pvicente/git/conan/conan-community/review_libraries/conan-log4cplus$ ldd test_package/build/0d8c2a5b4975e9c6a99324cd497a84515e2fa517/bin/test_package
	linux-vdso.so.1 =>  (0x00007ffcfdbb5000)
	liblog4cplus.so.0 => /home/conan/.conan/data/log4cplus/1.2.1/pedro/test/package/b7c9287b6c24e7c3a3157b3c865ac47885eb1a34/lib/liblog4cplus.so.0 (0x00007fbd8c85a000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fbd8c4d8000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fbd8c2c2000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fbd8bef8000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fbd8bcdb000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fbd8bad3000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fbd8b7ca000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fbd8caee000)
```

I've tried to build it in Windows/Mac/Linux with the same results (not seeing the dynamic lib in final test_package binary).

The only way that I've found to make it work is using it explicitly (not through log4cplus) in ```test_package```. See diff:

```
09:07 $ git diff
diff --git a/test_package/test_package.cpp b/test_package/test_package.cpp
index fbe0ca4..60f5ef8 100644
--- a/test_package/test_package.cpp
+++ b/test_package/test_package.cpp
@@ -3,6 +3,7 @@
 #include <log4cplus/logger.h>
 #ifdef WITH_ICONV
 #include <log4cplus/tchar.h>
+#include <iconv.h>
 #endif

 using namespace std;
@@ -41,6 +42,12 @@ int main()
     printMsgs();

 #ifdef WITH_ICONV
+    cout << "********** Using libiconv *********" << endl;
+    iconv_t context = iconv_open("UCS-4-INTERNAL", "US-ASCII");
+    if ((iconv_t)(-1) == context) {
+        cerr << "iconv_open failed" << std::endl;
+        return 1;
+    }
     std::wstring wstr = log4cplus::helpers::towstring("test");
     std::string str = log4cplus::helpers::tostring(L"test");
 #endif
```

See ldd output:

```
conan@d6b642a355ac:/Users/pvicente/git/conan/conan-community/review_libraries/conan-log4cplus$ ldd test_package/build/0d8c2a5b4975e9c6a99324cd497a84515e2fa517/bin/test_package
	linux-vdso.so.1 =>  (0x00007ffc9e1bc000)
	liblog4cplus.so.0 => /home/conan/.conan/data/log4cplus/1.2.1/pedro/test/package/b7c9287b6c24e7c3a3157b3c865ac47885eb1a34/lib/liblog4cplus.so.0 (0x00007fa597cc9000)
	libiconv.so.2 => /home/conan/.conan/data/libiconv/1.15/bincrafters/stable/package/e30939caa2339df448fcf9917da7b5ebc54646b6/lib/libiconv.so.2 (0x00007fa5979d8000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fa597656000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fa597440000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa597076000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa596e59000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fa596c51000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa596948000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fa597f5d000)
```

Any thoughts?? Thank you.

**Comment by SSE4** [comment]
sorry, no idea right now on how to get log4cplus to actually use libiconv. the only place using iconv I see is towstring/tostring methods, but there are appear to be multiple implementations of them. 
https://github.com/log4cplus/log4cplus/blob/5aef420f5e59b72702a2e3121f45e547f6f51ff4/src/stringhelper-iconv.cxx
I need to investigate it deeper.

**Comment by pvicente** [comment]
Hi @SSE4, did you have time to investigate it? Not sure if it should block the inclusion request but it would be good to know what do you think about it ...

**Comment by SSE4** [comment]
not yet, sorry

**Comment by pvicente** [comment]
Hi @SSE4/ @solvingj  I've found the problem.

Kindly review PR above.

After this fix library should be ready for inclusion in conan-center.

**Comment by pvicente** [comment]
Hi @solvingj,

Now library is in [conan-center](https://bintray.com/conan/conan-center?filterByPkgName=log4cplus%3Abincrafters). Thanks for merging the changes.

![screenshot 2018-03-13 09 39 43](https://user-images.githubusercontent.com/471109/37333937-7c984296-26a2-11e8-9435-0aa95a94f752.png)
