### ISSUE TITLE
[MOC] Implement workaround patch for QTBUG-83160

### ISSUE THREAD

**Issue by sminjard** [bincrafters/community#1388]
OS : Linux
QT Version : qt/5.15.2@bincrafters/stable
GCC: 10.2

See description of QT bug [here](https://bugreports.qt.io/browse/QTBUG-83160)

When retrieving conan repository qt/5.15.2@bincrafters/stable, on Linux, the moc subcommand fails as described in this [other bug](https://bugreports.qt.io/browse/QTBUG-73263). Apparently, it is due to moc not knowing what to do with GCC macro _GLIBCXX_VISIBILITY . Adding it to the list of dumped elements should resolve the issue.

**Comment by ericLemanissier** [comment]
This recipe is now in the Conan Center Index.

Please migrate to the recipe version there.
If this is still an issue, please create a new issue in the Conan Center Index issue tracker.

Thanks!

https://conan.io/center/qt
