### ISSUE TITLE
Log4cplus - add support additional CMake options

### ISSUE THREAD

**Issue by solvingj** [bincrafters/community#139]
### Description of Problem, Request, or Question
This library has the following options which were not included in the current recipe.  The options should be added to the conan recipe and passed to cmake and tested. 

This was discovered in ticket: https://github.com/bincrafters/community/issues/138 and we need to address before it is included in conan center.

Also, please address the other issues in the that ticket as well.  (Homepage field, cleanup test_package, remove mingw from appveyor). 

### Package Details (Include if Applicable)
* Package Name/Version: log4cplus/1.2.1@bincrafters/stable
* Operating System: all
* Compiler+version: all
* Docker image: all

### Steps to reproduce (Include if Applicable)
Here's the list of options we should be adding: 

- LOG4CPLUS_SINGLE_THREADED
- LOG4CPLUS_BUILD_LOGGINGSERVER 
- WITH_ICONV 
- LOG4CPLUS_QT4 
- LOG4CPLUS_QT5
- LOG4CPLUS_WORKING_C_LOCALE

**Comment by solvingj** [comment]
Currently, just raise exception "not supported". When we have qt packages, or when a user requests that we support it because they actually need it, we can try to enable.

**Comment by SSE4** [comment]
roger that, thx

**Comment by SSE4** [comment]
new options were added
