### ISSUE TITLE
[BPT] Pass environment variables inside conan dockers

### ISSUE THREAD

**Issue by lgisler** [bincrafters/community#1393]
Hi guys, first time contributor so hopefully this workflow is appropriate :)

### Description of your feature
I would like to be able to pass environment variables into the conan docker container. 

### Proposed solution
Append to CONAN_DOCKER_RUN_OPTIONS environment variable instead of setting it inside bincrafters-package-tools/bincrafters/build_autodetect.py
 
PR: https://github.com/bincrafters/bincrafters-package-tools/pull/35

Thanks,

lgisler

**Comment by Croydon** [comment]
PR is merged. Thanks!
