### ISSUE TITLE
Bincrafters Community Vote - User Feedback Needed

### ISSUE THREAD

**Issue by solvingj** [bincrafters/community#14]
Attention to all those who use Bincrafters Conan packages, based on the issue below, we have decided to have a vote, please let us know what you think: 

https://twitter.com/bincrafters/status/938049797105299456

#8 

Please don't vote or comment here.

**Comment by uilianries** [comment]
Should we close this issue? I think that this thread is done.

**Comment by solvingj** [comment]
Yes, current result is 85/15, in favor of those who don’t mind the change now.
