### ISSUE TITLE
gtest: How to find gmock?

### ISSUE THREAD

**Issue by liberforce** [bincrafters/community#140]
### Description of Problem, Request, or Question
The gtest package is built with gmock support. However when running cmake on a project that uses gtest and gmock, cmake complains that it can't find gmock.

```
CMake Error at /home/luismenina/.local/share/cmake/qibuild/internal/uselib.cmake:81 (find_package):
  By not providing "Findgmock.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "gmock", but
  CMake did not find one.

  Could not find a package configuration file provided by "gmock" with any of
  the following names:

    gmockConfig.cmake
    gmock-config.cmake

  Add the installation prefix of "gmock" to CMAKE_PREFIX_PATH or set
  "gmock_DIR" to a directory containing one of the above files.  If "gmock"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  /home/luismenina/.local/share/cmake/qibuild/internal/uselib.cmake:162 (_qi_use_lib_get_deps)
  /home/luismenina/.local/share/cmake/qibuild/stage.cmake:247 (_qi_use_lib_internal)
  /home/luismenina/.local/share/cmake/qibuild/target.cmake:279 (qi_use_lib)
  tests/CMakeLists.txt:8 (qi_create_lib)
```

How does one is supposed to use gmock from the conan package in an application?

### Package Details (Include if Applicable)
* Package Name/Version: **gtest/1.8.0@bincrafters/stable** as of 2018-02-20 05:03:52
* Operating System: **Ubuntu Linux 14.04**
* Compiler+version: **gcc-4.8**

**Comment by solvingj** [comment]
Yep, probably need a find_gmock.cmake or something.  Looking for someone to grab this one now. 

We should check lasotes old package to see if he had one that we missed.

**Comment by solvingj** [comment]
Thanks to @dimi309 your project might just work now.  Please give it another test and let us know.

**Comment by wpalfi** [comment]
We are using gtest with

```cmake
find_package(GTest REQUIRED)
target_link_libraries(${target} GTest::GTest GTest::Main)
```

as recommended here: 
https://cmake.org/cmake/help/latest/module/FindGTest.html

Until yesterday that worked fine with the default cmake findGTest.cmake. Could you please add the imported targets to the custom findGTest.cmake?

**Comment by liberforce** [comment]
@wpalfi: This issue is about GMock.You should probably open a separate bug report.

**Comment by solvingj** [comment]
It's fine, we're addressing it ASAP.

**Comment by SSE4** [comment]
I've added required targets https://github.com/bincrafters/conan-gtest/commit/20b692e6b0854c331d91160ff6f5742d3033abd3
please update and lemme know if it works for you

**Comment by wpalfi** [comment]
Yes it works. Thanks!

I already issues here https://github.com/bincrafters/community/issues/26#issuecomment-366164172 that the compile definitions are missing with this approach. Could you please add this line:

```cmake
set_property(TARGET GTest::GTest PROPERTY INTERFACE_COMPILE_DEFINITIONS
    ${CONAN_COMPILE_DEFINITIONS_GTEST})
```

?

**Comment by SSE4** [comment]
right, I'll add them

**Comment by SSE4** [comment]
@wpalfi INTERFACE_COMPILE_DEFINITIONS were added, please update and try again

**Comment by wpalfi** [comment]
Perfect

**Comment by liberforce** [comment]
Still doesn't work for me:

```
-- Found GTEST: general;/home/luismenina/.conan/data/gtest/1.8.0/bincrafters/stable/package/6caa294d9d75275655c47387040b576a19a9a97e/lib/libgtest.a;general;/home/luismenina/.conan/data/gtest/1.8.0/bincrafters/stable/package/6caa294d9d75275655c47387040b576a19a9a97e/lib/libgtest_main.a  
CMake Error at /home/luismenina/.conan/data/gtest/1.8.0/bincrafters/stable/package/6caa294d9d75275655c47387040b576a19a9a97e/FindGTest.cmake:33 (set_property):
  Property INTERFACE_LINK_LIBRARIES may not contain link-type keyword
  "general".  The INTERFACE_LINK_LIBRARIES property may contain
  configuration-sensitive generator-expressions which may be used to specify
  per-configuration rules.
Call Stack (most recent call first):
  /home/luismenina/.local/share/cmake/qibuild/internal/uselib.cmake:80 (find_package)
  /home/luismenina/.local/share/cmake/qibuild/internal/uselib.cmake:157 (_qi_use_lib_get_deps)
  /home/luismenina/.local/share/cmake/qibuild/stage.cmake:247 (_qi_use_lib_internal)
  /home/luismenina/.local/share/cmake/qibuild/target.cmake:278 (qi_use_lib)
  tests/CMakeLists.txt:8 (qi_create_lib)


-- Could NOT find GTEST (missing: GMOCK_BOTH_LIBARIES) 
```

**Comment by SSE4** [comment]
@liberforce interesting, I'll take a look

**Comment by liberforce** [comment]
In FindGMock.cmake, I think that:

`find_package_handle_standard_args(GTEST REQUIRED_VARS ...`

should be:

`find_package_handle_standard_args(GMOCK REQUIRED_VARS ...`

**Comment by SSE4** [comment]
good catch, thanks!

**Comment by liberforce** [comment]
Commit https://github.com/bincrafters/conan-gtest/commit/d21a0c4a78ec6865f036a962d690bbe1fe37179e fixes the `-- Could NOT find GTEST (missing: GMOCK_BOTH_LIBARIES) ` error.

The ` Property INTERFACE_LINK_LIBRARIES may not contain link-type keyword  "general"` error is still there though.

**Comment by SSE4** [comment]
I am working on this

**Comment by liberforce** [comment]
Seems that the "general" keywords is added by qibuild (meta build system made above cmake), so that's probably in our code, not yours.

**Comment by SSE4** [comment]
yep, I cannot reproduce an error locally, however, found few others and fixing em right away. anything else to be fixed?

**Comment by liberforce** [comment]
No for now, feel free to close once you push the last fixes, I'll reopen if I find something else. Thanks for your work and responsiveness :+1:

**Comment by SSE4** [comment]
confirmed as fixed
