### ISSUE TITLE
no binaries available for SDL2

### ISSUE THREAD

**Issue by ericLemanissier** [bincrafters/community#1405]
Currently all users of sdl2 have to build it from source locally because there is no binary available in bincrafters remote:
```
$ conan search sdl2/2.0.14@bincrafters/stable
Existing packages for recipe sdl2/2.0.14@bincrafters/stable:

There are no packages for reference 'sdl2/2.0.14@bincrafters/stable', but package recipe found.
```

This is surprising because the CI of the last commit was successful: https://github.com/bincrafters/community/commit/e776c5a50092ab4597b3ef20586d12dbcb3cec78

also there is  neither recipe nor binaries for sdl2/2.0.12:
```
$ conan search sdl2/*
Existing package recipes:

sdl2/2.0.14@bincrafters/stable
```

**Comment by ericLemanissier** [comment]
my bad, I forgot the `-r bincrafters` argument.....

**Comment by ericLemanissier** [comment]
That said, a lot of binaries are missing for sdl2/2.0.14:
There is no binaries for windows (they were built in https://dev.azure.com/bincrafters/packages/_build/results?buildId=8826&view=results). Also there is no binaries for sdl2:shared=False (built in https://github.com/bincrafters/community/actions/runs/1010447291)

**Comment by ericLemanissier** [comment]
maybe the missing binaries are caused by a miss-behaving of remove-outdated-packages GHA. Looking at the log I noticed that [revisions were not enabled](https://github.com/bincrafters/bincrafters-conventions/runs/3109467872?check_suite_focus=true#step:4:21):
```
WARN: No matching packages to remove for pcapplusplus/20.08@bincrafters/stable#0
WARN: No matching packages to remove for ruby_installer/2.7.3@bincrafters/stable#0
WARN: No matching packages to remove for sdl2/2.0.12@bincrafters/stable#0
WARN: No matching packages to remove for sdl2/2.0.14@bincrafters/stable#0
WARN: No matching packages to remove for sdl2_ttf/2.0.15@bincrafters/stable#0
WARN: No matching packages to remove for wxwidgets/3.1.5@bincrafters/stable#0
```
I added `conan config set general.revisions_enabled=1` in the script and [it may be better now (?)](https://github.com/bincrafters/bincrafters-conventions/runs/3119425292?check_suite_focus=true#step:4:22)
```
WARN: No matching packages to remove for fluidsynth/2.1.9@bincrafters/stable#f9438d37d85d65db7c21812157793080
WARN: No matching packages to remove for fluidsynth/2.2.2@bincrafters/stable#f9438d37d85d65db7c21812157793080
WARN: No matching packages to remove for pcapplusplus/20.08@bincrafters/stable#05748ef5985c940f9f670b28308d3fc3
WARN: No matching packages to remove for ruby_installer/2.7.3@bincrafters/stable#0657ac2c16f1c7f776b0e4197d00571f
WARN: No matching packages to remove for sdl2/2.0.12@bincrafters/stable#79f7880b34ca6c90116f82c7dd4d9233
WARN: No matching packages to remove for sdl2/2.0.14@bincrafters/stable#79f7880b34ca6c90116f82c7dd4d9233
WARN: No matching packages to remove for sdl2_ttf/2.0.15@bincrafters/stable#e2ef4fdfad03f6dc1a89907ab7621225
WARN: No matching packages to remove for wxwidgets/3.1.4@bincrafters/stable#2bd101187013cefd2fec50de62392b12
WARN: No matching packages to remove for wxwidgets/3.1.5@bincrafters/stable#2bd101187013cefd2fec50de62392b12
```
at least, SDL2 binaries for static builds and windows builds are available now. I'll keep an eye on them.

**Comment by Croydon** [comment]
Good catch!

**Comment by Croydon** [comment]
Looks solved to me. Thanks @ericLemanissier!
