### ISSUE TITLE
bzip2/1.0.6: build script depends on https://bintray.com/conan/Sources

### ISSUE THREAD

**Issue by starcatter** [bincrafters/community#1407]
When attempting to build the package, I get a 403: Forbidden error, as it attempts to download sources from now defunct bintray.com

Boost-interprocess depends on this bzip2 package version, so building it is also broken where binaries are not available.

Editing the conanfile.py and replacing the tools.get() URL with https://sourceware.org/pub/bzip2/bzip2-1.0.6.tar.gz fixed the problem for me.

**Comment by uilianries** [comment]
Hello @starcatter ! Did you read https://bincrafters.github.io/2020/04/19/infrastructure-changes-and-required-actions/ ? We needed to change our old URL Bintray url.

**Comment by ericLemanissier** [comment]
This recipe is now in the Conan Center Index.

Please migrate to the recipe version there.
If this is still an issue, please create a new issue in the Conan Center Index issue tracker.

Thanks!

https://conan.io/center/bzip2
