### ISSUE TITLE
sdl2/2.0.14: Linking fails with Mingw-w64

### ISSUE THREAD

**Issue by joshua-barnett** [bincrafters/community#1408]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **sdl2/2.0.14**
  * Operating System+version: **Linux Ubuntu 18.04.5 LTS**
  * Compiler+version: **/usr/bin/x86_64-w64-mingw32-g++ (GCC) 7.3-win32 20180312**
  * Docker image: **conanio/gcc7-mingw**
  * Conan version: **conan 1.38.0**
  * Python version: **Python 3.7.5**

### Conan profile
```shell
$ conan profile show default
Configuration for profile default:

[settings]
os=Windows
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=7
compiler.libcxx=libstdc++
build_type=Release
[options]
[conf]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
Attempt to build a Conan project that requires and uses `sdl2/2.0.14` in the `conanio/gcc7-mingw` Docker image.

### Fix?

https://github.com/msys2/MINGW-packages/issues/6379#issue-598436450

I have to reorder the linker flags in order to avoid the following error.

```shell
/usr/lib/gcc/x86_64-w64-mingw32/7.3-win32/../../../../x86_64-w64-mingw32/lib/libmingw32.a(lib64_libmingw32_a-crt0_c.o): In function `main':
./mingw-w64-crt/crt/crt0_c.c:18: undefined reference to `WinMain'
collect2: error: ld returned 1 exit status
```

This is the addition to my project's `CMakeList.txt` to reorder the linker flags appropriately.

```cmake
# Reorder linker flags to fix 'undefined reference to WinMain'
if (MINGW)
    list(REMOVE_ITEM CONAN_LIBS "mingw32")
    list(APPEND CONAN_LIBS "-mwindows")
    list(PREPEND CONAN_LIBS "mingw32")
endif()
```

**Comment by ericLemanissier** [comment]
Thanks for the report. You are doing 2 things: moving mingw32 to the beginning of the list, and adding -mwindows link flag. What happens if you only add -mwindows link flag to your application ?

**Comment by ericLemanissier** [comment]
This recipe is now in the Conan Center Index.

Please migrate to the recipe version there.
If this is still an issue, please create a new issue in the Conan Center Index issue tracker.

Thanks!

https://conan.io/center/sdl
