### ISSUE TITLE
boost_signals2 only in testing version

### ISSUE THREAD

**Issue by JohnboyJovi** [bincrafters/community#141]
Hello,

I want to use ``boost_signals2``. However, it seems only to exist in a testing version ([see conan page](https://bintray.com/bincrafters/public-conan/boost_signals2%3Abincrafters)).

Is there any reason for this? Is it safe to use the testing versions for everything, although I would rather only use stable packages. 

Furthermore I thought signals2 would be header-only. However, the testing version seems to require python (which I would rather not include, if possible): ``boost_signals2`` :arrow_right: ``boost_parameter`` :arrow_right: ``boost_python``. Do you see any way around?

Thanks for any pointer in the right direction.

**Comment by solvingj** [comment]
Thank you for reporting this issue. I have now resolved this by building signals2 stable branches. 

The Bincrafters packages, follow the dependency tree defined generated from the boost build dependency information. The same information is also rendered here: 
https://pdimov.github.io/boostdep-report/master/module-levels.html

We understand there are some circumstances where this dependency tree includes some dependencies which could technically be left out without issue (assuming certain features of said libraries are never invoked). At this time, we have no way for users to do this with Conan.

**Comment by JohnboyJovi** [comment]
Thanks a lot. The stable packages seem to work for me.

Concerning the dependencies, I understand that this is not your fault. 

So I close this issue.
