### ISSUE TITLE
ffmpeg: is it possible to build without xcb?

### ISSUE THREAD

**Issue by DoomHammer** [bincrafters/community#1412]
I've added FFMPEG to conanfile and also added the options section to disable xcb:

```
[options]
ffmpeg:xcb=False
```

However, FFMPEG still depends on xorg and tries to build it.

Is there a way to override it? I don't need Xorg with FFMPEG.

**Comment by ericLemanissier** [comment]
xorg is also a dependency of pulseaudio, so you have to use `ffmpeg:pulse=False` or `pulseaudio:with_x11=False`

**Comment by DoomHammer** [comment]
Thanks for your quick response! Disabling Pulseaudio helped for this dependency!

BTW: is there a way to list transitional dependencies in Conan?

**Comment by ericLemanissier** [comment]
yes, see https://docs.conan.io/en/latest/reference/commands/consumer/info.html (especially the `-g` argument)
