### ISSUE TITLE
boost_python does not build on CentOS

### ISSUE THREAD

**Issue by JohnboyJovi** [bincrafters/community#142]
### Description of Problem

in the conanfile.py of boost_python line 64 the package ``python-dev`` is explicitely searched. Unfortunately under CentOS it is named ``python-devel``.
So this should either be dependend on the Linux distribution or this package name could also be an options, so that I can configure it correctly when using it.

### Package Details
* Package Name/Version: **boost_python/1.66.0**
* Operating System: **CentOS**

**Comment by SSE4** [comment]
changes are in boost_python/1.66.0@bincrafters/testing, please give another try

**Comment by JohnboyJovi** [comment]
Very good that seems to work. At least the conan package is building. Thanks a lot :-)

**Comment by JohnboyJovi** [comment]
This is not in `stable` yet, right? Because `stable` is still not building, and now the `testing` version fails with another problem, see #62 
So I leave this open until the changes made it to `stable`. Sorry for closing it too early.

**Comment by solvingj** [comment]
ping @JohnboyJovi still an issue with latest boost?

**Comment by JohnboyJovi** [comment]
Unfortunately the project we used that in died. I tried to check it, but since a lot more things changed since then, conan does not build through, but I fear this might also be due to other problems.

**Comment by SSE4** [comment]
okay, @JohnboyJovi , what would you recommend to do with this issue?

**Comment by JohnboyJovi** [comment]
Since the fix in testing already worked, I would say this issue can be closed if it now made it into stable
