### ISSUE TITLE
conan-libiconv inclusion request into conan-center

### ISSUE THREAD

**Issue by pvicente** [bincrafters/community#143]
## Inclusion Request Review

This is a review for [libiconv:bincrafters](https://bintray.com/bincrafters/public-conan/libiconv%3Abincrafters/1.15%3Astable) inclusion request into conan-center.

### Package

libiconv/1.15@bincrafters/stable

### Checks and Comments

**Recipe quality**

- [X] Git public repository
- [X] Recipe fields
- [X] Linter
- [X] Updated
- [X] Clean
- [X] test_package
- [X] Raise errors on invalid configurations
- [X] LICENSE of recipe
- [X] LICENSE of library

**Linter**:  Only pointing this out
```
ibiconv/1.15@pedro/test: Exporting package recipe
Linter warnings
    WARN: Linter. Line 105: TODO : clang on Windows and others
```

**Updated**: There are some binaries for Mac OS X x86 outdated, please remove outdated binaries from bintray: 

```$ conan remove libiconv/1.15@bincrafters/stable --outdated -r bincrafters```

![screenshot 2018-02-26 13 12 04](https://user-images.githubusercontent.com/471109/36672324-c38e6a52-1af6-11e8-9c19-7b87fcf511d1.png)

**CI integration**

- [X] (If not header only) CI configurations for Linux/MacOSX/Windows

MINGW_CONFIGURATIONS commented out in ``appveyor.yml`` any reason?

**Bintray Package Information**

- [X] Description
- [X] Licenses
- [X] Tags
- [X] Maturity
- [X] Website (if any)
- [X] Issue tracker
- [X] Version control
- [X] Github repo (user/repo)

### Additional comments
Library is passing all the checks. I only have tiny comments/questions.

Please remove outdated binaries and it will be ready to be included into conan-center.

Thanks for your contribution.

**Comment by solvingj** [comment]
FYI the outdated are gone but we should wait to see if we should rebuild with pure_c=True. Awaiting response from @SSE4

**Comment by pvicente** [comment]
Hi @solvingj thanks for doing it and also thank you for checking ```pure_c=True```.

@SSE4 I've tried to build it in my windows environment without success 😞 

```
checking whether the C compiler works... no
configure: error: in `/cygdrive/c/users/barbarian 
```

My default profile is:

```
(conan1.0.4) λ cat "c:\Users\Barbarian team\.conan\profiles\default
[build_requires]
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=15
build_type=Release
[options]
[env]
```
And the building profile ```default_libiconv``` is:

```
(conan1.0.4) λ cat "c:\Users\Barbarian team\.conan\profiles\default_libiconv"                
include(default)                                                                             
[settings]                                                                                   
arch=x86                                                                                     
build_type=Release                                                                           
compiler=Visual Studio                                                                       
compiler.runtime=MT                                                                          
compiler.version=15                                                                          
[options]                                                                                    
libiconv:shared=False                                                                        
[env]                                                                                        
[build_requires]                                                                             
*:cygwin_installer/2.9.0@bincrafters/stable
```

See full output:

```E:\git\conan\conan-community\review_libraries\conan-libiconv (stable/1.15 -> origin)
(conan1.0.4) λ conan create . pedro/test -pr=default_libiconv
libiconv/1.15@pedro/test: Exporting package recipe
Linter warnings
    WARN: Linter. Line 105: TODO : clang on Windows and others
libiconv/1.15@pedro/test: A new conanfile.py version was exported
libiconv/1.15@pedro/test: Folder: C:\Users\Barbarian team\.conan\data\libiconv\1.15\pedro\test\export
libiconv/1.15@pedro/test: Package recipe modified in export, forcing source folder removal
libiconv/1.15@pedro/test: Use the --keep-source, -k option to skip it
libiconv/1.15@pedro/test: Removing 'source' folder, this can take a while for big packages
libiconv/1.15@pedro/test (test package): Installing E:\git\conan\conan-community\review_libraries\conan-libiconv\test_package\conanfile.py
Requirements
    libiconv/1.15@pedro/test from local
Packages
    libiconv/1.15@pedro/test:8a04d8cc09fd6b6f267d775ab034669b764b3595

Cross-build from 'Windows:x86_64' to 'Windows:x86'
libiconv/1.15@pedro/test (test package): Installing build requirements of: PROJECT
libiconv/1.15@pedro/test (test package): Build requires: [cygwin_installer/2.9.0@bincrafters/stable]
libiconv/1.15@pedro/test (test package): Requirements
libiconv/1.15@pedro/test (test package):     cygwin_installer/2.9.0@bincrafters/stable from conan-center
libiconv/1.15@pedro/test (test package): Packages
libiconv/1.15@pedro/test (test package):     cygwin_installer/2.9.0@bincrafters/stable:456f15897172eef340fcbac8a70811f2beb26a93
libiconv/1.15@pedro/test (test package):
cygwin_installer/2.9.0@bincrafters/stable: Already installed!
cygwin_installer/2.9.0@bincrafters/stable: Creating CYGWIN_ROOT env var : C:/.conan\cbjedh\1
cygwin_installer/2.9.0@bincrafters/stable: Creating CYGWIN_BIN env var : C:/.conan\cbjedh\1\bin
cygwin_installer/2.9.0@bincrafters/stable: Appending PATH env var with : C:/.conan\cbjedh\1\bin
libiconv/1.15@pedro/test (test package): Installed build requirements of: PROJECT
libiconv/1.15@pedro/test: WARN: Forced build from source
libiconv/1.15@pedro/test: Installing build requirements of: libiconv/1.15@pedro/test
libiconv/1.15@pedro/test: Build requires: [cygwin_installer/2.9.0@bincrafters/stable]
libiconv/1.15@pedro/test: Requirements
libiconv/1.15@pedro/test:     cygwin_installer/2.9.0@bincrafters/stable from conan-center
libiconv/1.15@pedro/test: Packages
libiconv/1.15@pedro/test:     cygwin_installer/2.9.0@bincrafters/stable:456f15897172eef340fcbac8a70811f2beb26a93
libiconv/1.15@pedro/test:
cygwin_installer/2.9.0@bincrafters/stable: Already installed!
cygwin_installer/2.9.0@bincrafters/stable: Creating CYGWIN_ROOT env var : C:/.conan\cbjedh\1
cygwin_installer/2.9.0@bincrafters/stable: Creating CYGWIN_BIN env var : C:/.conan\cbjedh\1\bin
cygwin_installer/2.9.0@bincrafters/stable: Appending PATH env var with : C:/.conan\cbjedh\1\bin
libiconv/1.15@pedro/test: Installed build requirements of: libiconv/1.15@pedro/test
libiconv/1.15@pedro/test: Building your package in C:\Users\Barbarian team\.conan\data\libiconv\1.15\pedro\test\build\8a04d8cc09fd6b6f267d775ab034669b764b3595
libiconv/1.15@pedro/test: Configuring sources in C:\Users\Barbarian team\.conan\data\libiconv\1.15\pedro\test\source
[==================================================] 5.0MB/5.0MB
libiconv/1.15@pedro/test: Copying sources to build folder
libiconv/1.15@pedro/test: Generator txt created conanbuildinfo.txt
libiconv/1.15@pedro/test: Calling build()
libiconv/1.15@pedro/test: run_in_windows_bash: C:/.conan\cbjedh\1\bin/bash.exe --login -c ^"cd \^"/cygdrive/c/users/barbarian team/.conan/data/libiconv/1.15/pedro/test/build/8a04d8cc09fd6b6f267d775ab034669b764b3595/libiconv-1.15\^" ^&^& PATH=\^"/cygdrive/c/.conan/cbjedh/1/bin:$PATH\^" ^&^& chmod +x build-aux/ar-lib build-aux/compile ^"
libiconv/1.15@pedro/test: run_in_windows_bash: C:/.conan\cbjedh\1\bin/bash.exe --login -c ^"cd \^"/cygdrive/c/users/barbarian team/.conan/data/libiconv/1.15/pedro/test/build/8a04d8cc09fd6b6f267d775ab034669b764b3595/libiconv-1.15\^" ^&^& PATH=\^"/cygdrive/c/.conan/cbjedh/1/bin:$PATH\^" ^&^& \^"/cygdrive/c/users/barbarian team/.conan/data/libiconv/1.15/pedro/test/build/8a04d8cc09fd6b6f267d775ab034669b764b3595/libiconv-1.15\^"/configure \^"--prefix=C:/Users/Barbarian team/.conan/data/libiconv/1.15/pedro/test/package/8a04d8cc09fd6b6f267d775ab034669b764b3595\^" --enable-static --disable-shared \^"CC=$PWD/build-aux/compile cl -nologo\^" CFLAGS=-MT \^"CXX=$PWD/build-aux/compile cl -nologo\^" CXXFLAGS=-MT \^"CPPFLAGS=-D_WIN32_WINNT=0x0600 -IC:/Users/Barbarian team/.conan/data/libiconv/1.15/pedro/test/package/8a04d8cc09fd6b6f267d775ab034669b764b3595/include\^" \^"LDFLAGS=-LC:/Users/Barbarian team/.conan/data/libiconv/1.15/pedro/test/package/8a04d8cc09fd6b6f267d775ab034669b764b3595/lib\^" LD=link \^"NM=dumpbin -symbols\^" STRIP=: \^"AR=$PWD/build-aux/ar-lib lib\^" RANLIB=: \^"RC=windres --target=pe-i386\^" \^"WINDRES=windres --target=pe-i386\^" --host=i686-w64-mingw32 ^"
checking for a BSD-compatible install... /cygdrive/c/.conan/cbjedh/1/bin/install -c
checking whether build environment is sane... yes
checking for i686-w64-mingw32-strip... :
checking for a thread-safe mkdir -p... /cygdrive/c/.conan/cbjedh/1/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make sets $(MAKE)... (cached) yes
checking for i686-w64-mingw32-gcc... /cygdrive/c/users/barbarian team/.conan/data/libiconv/1.15/pedro/test/build/8a04d8cc09fd6b6f267d775ab034669b764b3595/libiconv-1.15/build-aux/compile cl -nologo
checking whether the C compiler works... no
configure: error: in `/cygdrive/c/users/barbarian team/.conan/data/libiconv/1.15/pedro/test/build/8a04d8cc09fd6b6f267d775ab034669b764b3595/libiconv-1.15':
configure: error: C compiler cannot create executables
See `config.log' for more details
libiconv/1.15@pedro/test:
libiconv/1.15@pedro/test: ERROR: Package '8a04d8cc09fd6b6f267d775ab034669b764b3595' build failed
libiconv/1.15@pedro/test: WARN: Build folder C:\Users\Barbarian team\.conan\data\libiconv\1.15\pedro\test\build\8a04d8cc09fd6b6f267d775ab034669b764b3595
ERROR: libiconv/1.15@pedro/test: Error in build() method, line 101
        self.build_autotools()
while calling 'build_autotools', line 90
        env_build.configure(args=configure_args, host=host, build=build)
        ConanException: Error 77 while executing C:/.conan\cbjedh\1\bin/bash.exe --login -c ^"cd \^"/cygdrive/c/users/barbarian team/.conan/data/libiconv/1.15/pedro/test/build/8a04d8cc09fd6b6f267d775ab034669b764b3595/libiconv-1.15\^" ^&^& PATH=\^"/cygdrive/c/.conan/cbjedh/1/bin:$PATH\^" ^&^& \^"/cygdrive/c/users/barbarian team/.conan/data/libiconv/1.15/pedro/test/build/8a04d8cc09fd6b6f267d775ab034669b764b3595/libiconv-1.15\^"/configure \^"--prefix=C:/Users/Barbarian team/.conan/data/libiconv/1.15/pedro/test/package/8a04d8cc09fd6b6f267d775ab034669b764b3595\^" --enable-static --disable-shared \^"CC=$PWD/build-aux/compile cl -nologo\^" CFLAGS=-MT \^"CXX=$PWD/build-aux/compile cl -nologo\^" CXXFLAGS=-MT \^"CPPFLAGS=-D_WIN32_WINNT=0x0600 -IC:/Users/Barbarian team/.conan/data/libiconv/1.15/pedro/test/package/8a04d8cc09fd6b6f267d775ab034669b764b3595/include\^" \^"LDFLAGS=-LC:/Users/Barbarian team/.conan/data/libiconv/1.15/pedro/test/package/8a04d8cc09fd6b6f267d775ab034669b764b3595/lib\^" LD=link \^"NM=dumpbin -symbols\^" STRIP=: \^"AR=$PWD/build-aux/ar-lib lib\^" RANLIB=: \^"RC=windres --target=pe-i386\^" \^"WINDRES=windres --target=pe-i386\^" --host=i686-w64-mingw32 ^"
```

Can you see anything that can explain the my problem?

FYI: I've been building other projects with my Visual Studio compiler but it's the first time that I'm trying with autotools and the cygwin build_requirement.

**Comment by SSE4** [comment]
@pvicente hard to say - if you can share your config.log, it would be helpful

**Comment by pvicente** [comment]
@SSE4 hope it helps:

[config.log](https://github.com/bincrafters/community/files/1762656/config.log)

**Comment by SSE4** [comment]
Seems like it doesn’t handle path with spaces well (barbarian team). Not
sure where is a bug, will check later.

**Comment by pvicente** [comment]
Ohh yes I see:

```
configure:4097: checking for C compiler version
configure:4106: /cygdrive/c/users/barbarian team/.conan/data/libiconv/1.15/pedro/test/build/8a04d8cc09fd6b6f267d775ab034669b764b3595/libiconv-1.15/build-aux/compile cl -nologo --version >&5
/cygdrive/c/users/barbarian team/.conan/data/libiconv/1.15/pedro/test/build/8a04d8cc09fd6b6f267d775ab034669b764b3595/libiconv-1.15/configure: line 4108: /cygdrive/c/users/barbarian: No such file or directory
configure:4117: $? = 127
```

**Comment by pvicente** [comment]
Hi @SSE4 I've found https://github.com/conan-io/conan/issues/2344 that could be related

**Comment by SSE4** [comment]
okay, I'll take a look and check what could be done

**Comment by SSE4** [comment]
were trying to quote/escape spaces multiple times, no luck :(
if someone have ideas - please share
problematic place - `'CC=$PWD/build-aux/compile cl -nologo'` $PWD resolves into path with spaces here

**Comment by pvicente** [comment]
Hi @SSE4, @solvingj I've been doing more tests and I have a possible solution but with tradeoffs ...

We can use the attribute [short_paths=True](http://docs.conan.io/en/latest/reference/conanfile/attributes.html#short-paths) and basically instead of building in your home ```c:\Users\your_home\.conan``` it's going to use [CONAN_USER_HOME_SHORT](http://docs.conan.io/en/latest/reference/env_vars.html?highlight=SHORT#conan-user-home-short) which is by default ``c:\.conan``.

I've tried it with the ```libiconv```  but there is a problem, at least in my windows environment, hitting a weird backtrace:

![short_paths_linker_problem](https://user-images.githubusercontent.com/471109/36852926-f73bf214-1d64-11e8-94f0-045aff602e2f.png)

If I explore the ```libiconv-1.15/src``` folder:

![short_paths_file_permissions](https://user-images.githubusercontent.com/471109/36853003-25b605c6-1d65-11e8-9802-158e4e1a37bc.png)

There are no read permissions for these files which is weird, and if I create any file in that folder I have the same problem:

![short_path_facl_src_problems](https://user-images.githubusercontent.com/471109/36853059-4f52bee2-1d65-11e8-9f5c-eebba5c96589.png)

I've been digging a bit more and I've found that there is a problem between the acl mapping of file system in windows to file system in cygwin ```c:\.conan```.  By default cygwin acls are enabled, see mount options for ```/cygwin``` drive at ```/etc/fstab```:

```
none /cygdrive cygdrive binary,posix=0,user 0 0
```
There is an option of disabling acls for the ```cygwin``` mount point editing ```/etc/fstab```:

```
none /cygdrive cygdrive binary,noacl,posix=0,user 0 0
```

For more information see also:
-  https://stackoverflow.com/questions/5828037/cygwin-sets-file-permission-to-000
-  https://cygwin.com/cygwin-ug-net/using-filemodes.html

In that way the build progress and works. But there is another way of fixing this problem (not touching cygwin ```/etc/fstab```. I've checked out the differences in file permissions between short_path folder ```c:\.conan``` (not working with short_path=True) and default home folder ```c:\Users\your_user_home```:

![windows permissions](https://user-images.githubusercontent.com/471109/36854425-e0d3c87c-1d68-11e8-8827-0b55629dd2fc.png)

And if we assign the full control permissions to current build user, in this case ```pedro```, to ```c:\.conan``` the build works without touching anything inside in ```cygwin```.

That folder is created by [conan](https://github.com/conan-io/conan/blob/release/1.1.1/conans/util/windows.py#L50) but by default windows doesn't assign user permissions to that folder as you can see above, only group permissions. The workaround would be setting  user permissions to that folder if it doesn't have them, looks like there is a way in python:

- https://stackoverflow.com/questions/12168110/setting-folder-permissions-in-windows-using-python

So it looks like there is a way to make it work with ```short_paths=True``` but with some intervention.

Let me know your thoughts,
Pedro

**Comment by SSE4** [comment]
@pvicente that's a great investigation! thanks a lot for spending your time on that.
I gonna try to do that and apply necessary changes to the recipe. thanks again.

**Comment by pvicente** [comment]
@SSE4 I'm going to submit a PR with some changes to improve the way of using the ```build_require```  instead of using [this line](https://github.com/bincrafters/conan-libiconv/blob/stable/1.15/conanfile.py#L96). Credits for that to @lasote

**Comment by SSE4** [comment]
sure, np

**Comment by pvicente** [comment]
Done!!! see https://github.com/bincrafters/conan-libiconv/pull/4. Let's wait to the CI

**Comment by SSE4** [comment]
@pvicente btw, I've made required changes in the **testing/1.15** branch.
I didn't use win32security/ntsecuritycon modules, as they are not in default python installation, instead I've just invoked cacls utility, hope it's okay.

**Comment by pvicente** [comment]
Thanks @SSE4, I've checked it and it works.

![cacl build dir](https://user-images.githubusercontent.com/471109/36860961-a2af2430-1d7a-11e8-9d60-a51672e19992.png)

Maybe a good contribution for conan would be [setting these permissions to the short_home folder](https://github.com/conan-io/conan/blob/release/1.1.1/conans/util/windows.py#L50) after creating the directory, so nobody will hit this problem with other recipes anymore. But it's ok to keep it in recipe until it has been fixed in conan.

**Comment by pvicente** [comment]
@SSE4 @solvingj Unfortunately the build require [msys2_installer:bincrafters](https://bintray.com/bincrafters/public-conan/msys2_installer%3Abincrafters) doesn't work with ```short_paths=true``` like  [cygwin build require](https://github.com/bincrafters/conan-cygwin_installer/blob/stable/2.9.0/conanfile.py#L21). Submitting pull request to update it and make it work in weird situations like this one.

**Comment by pvicente** [comment]
Thanks @SSE4 for accepting the last PR.

I've done another change to manage the fPIC option for Windows this is a best practice form the ```conan-team```.  Hope that's ok.

**Comment by pvicente** [comment]
@solvingj @SSE4 Cheers for merging all the changes.

Last thing before the inclusion, I promise, could you remove outdated binaries from bintray please? 

![screenshot 2018-03-02 18 32 54](https://user-images.githubusercontent.com/471109/36915337-33f106a2-1e48-11e8-90c4-9d3485fec015.png)

**Comment by solvingj** [comment]
should be done, please check again.

**Comment by pvicente** [comment]
![screenshot 2018-03-03 11 46 48](https://user-images.githubusercontent.com/471109/36933893-96ede71c-1ed8-11e8-839e-ce553c69101f.png)

Perfect, ready to go!!! Thank you all for your contribution.

**Comment by pvicente** [comment]
All done!!! https://bintray.com/conan/conan-center?filterByPkgName=libiconv%3Abincrafters.
