### ISSUE TITLE
sdl package video options seem to not have any impact 

### ISSUE THREAD

**Issue by positivcheg94** [bincrafters/community#1440]
So from my observation, it does look like options provided by the sdl conan package and OpenGL, OpenGLES, DirectX, Vulkan seem to not have any impact on library build.

Why is it though?
To prove my point.

1. I found it strange that when I load my app in visual studio it loads DLLs on startup such as
```
'ApplicationExample.exe' (Win32): Loaded 'C:\Windows\System32\opengl32.dll'. 
'ApplicationExample.exe' (Win32): Loaded 'C:\Windows\System32\glu32.dll'.
```
2. in .conan\data\sdl\2.0.18\_\_\build\164640aad040835ac89882393a96d89200694f04\build_subfolder if I check CMakeCache.txt it shows cached variables for graphics backends
```
//Include OpenGL support
SDL_OPENGL:BOOL=ON
//Include OpenGL ES support
SDL_OPENGLES:BOOL=ON
```
3. Also from the build log of conan install I see
--   SDL_OPENGL                  (Wanted: ON): ON
--   SDL_OPENGLES                (Wanted: ON): ON

So all of that makes me assume that either package is not picking correctly the options or am I doing something wrong?
In that conan package build folder .conan\data\sdl\2.0.18\_\_\build\164640aad040835ac89882393a96d89200694f04 conaninfo.txt seem to pick correctly options that I've provided in my project's conanfile.py though default_options - `"sdl:opengl":False`

```
[settings]
    arch=x86_64
    build_type=Debug
    compiler=Visual Studio
    compiler.runtime=MDd
    compiler.version=17
    os=Windows

[requires]


[options]
    directx=False
    opengl=False
    opengles=False
    shared=False
    vulkan=False

[full_settings]
    arch=x86_64
    build_type=Debug
    compiler=Visual Studio
    compiler.runtime=MDd
    compiler.version=17
    os=Windows

[full_requires]


[full_options]
    directx=False
    opengl=False
    opengles=False
    sdl2main=False
    shared=False
    vulkan=False

[recipe_hash]
    5d99981c667b8a9f3939c3cdc8f7e4a3

[env]
```

Any feedback on this?

**Comment by ericLemanissier** [comment]
issues on `sdl/*` should be reported on https://github.com/conan-io/conan-center-index/
The recipe maintained on bincrafters repository is `sdl2/*@bincrafters/stable`

**Comment by ericLemanissier** [comment]
https://github.com/conan-io/conan-center-index/issues/8617
