### ISSUE TITLE
[request] wxwidgets/3.1.6

### ISSUE THREAD

**Issue by Rapatas** [bincrafters/community#1441]
### Package Details
  * Package Name/Version: **wxwidgets/3.1.6**
  * Changelog: **https://raw.githubusercontent.com/wxWidgets/wxWidgets/v3.1.6/docs/changes.txt**
  * Release: https://github.com/wxWidgets/wxWidgets/releases/tag/v3.1.6

The above mentioned version is newly released by the upstream project and not yet available as a recipe. Please add this version.

**Comment by Rapatas** [comment]
Hello @Croydon, I have noticed you tried to add this new version in the wxwidgets branch. Have you identified any problems? Is there something I could do to help with this issue?

**Comment by Croydon** [comment]
I don't recall the problems. You can have a look into the CI longs for hints.

wxwidgets is really painful to maintain and it probably won't get much better until we have Conan packages for all those dependencies https://github.com/bincrafters/community/blob/44f1e72ab50eb92a63a851b5ed1e27e930f5e602/recipes/wxwidgets/all/conanfile.py#L91

**Comment by Croydon** [comment]
wxwidgets is now in CCI https://conan.io/center/recipes/wxwidgets
