### ISSUE TITLE
can't install boost-python

### ISSUE THREAD

**Issue by 013ez** [bincrafters/community#145]
### Package Details (Include if Applicable)
- Package Name/Version: **Boost.Python/1.65.1 (1.66.0)**
- Operating System: **Macos High Sierra10.13.3**
- Compiler+version: **Apple LLVM version 9.0.0 (clang-900.0.39.2)**
- Docker image: 

### Steps to reproduce (Include if Applicable)

```bash
$ conan install Boost.Python/1.65.1@bincrafters/stable
Boost.Fusion/1.65.1@bincrafters/stable is locked by another concurrent conan process, wait...
If not the case, quit, and do 'conan remove Boost.Fusion/1.65.1@bincrafters/stable -f'
```

Remove call not helped.

**Comment by solvingj** [comment]
Hi @013ez , sorry for the confusion but all of our packages with the capital letters and dots are old and deprecated. 

Please switch to `conan install boost_python/1.65.1@bincrafters/stable` and let us know if you continue to have issues.

**Comment by 013ez** [comment]
I cleaned my ```~/.conan/data``` folder and it helped.

Ok, thank you, i will update all my ```conanfile.txt``` files.
