### ISSUE TITLE
Bincrafter Conan repo down again

### ISSUE THREAD

**Issue by taol-assignments** [bincrafters/community#1454]
When I trying to access
https://bincrafters.jfrog.io/artifactory/api/conan/public-conan
I got this:
```
Time flies when you’re having fun.
Your 14-day trial may be over, but you have options!

Need help choosing the right subscription or additional time on your trial? Just let us know and a DevOps expert will reach out to assist you.
```
This is the same as #1451

**Comment by uilianries** [comment]
@taol-assignments Thank you for reporting, I'll be checking it.

**Comment by aminya** [comment]
Hi, is the repository still down?

**Comment by farafonov-alexey** [comment]
> @taol-assignments Thank you for reporting, I'll be checking it.

Hello! Is there any info when it will be back online?

**Comment by farafonov-alexey** [comment]
@uilianries any updates?

**Comment by Reavolt** [comment]
@uilianries Is there any information?

**Comment by Reavolt** [comment]
@uilianries Can you tell me if it’s possible to find recipes for projects that were posted on bincrafters somewhere?

**Comment by uilianries** [comment]
@Reavolt you could use the search bar in Github for it:

- https://www.freecodecamp.org/news/github-search-tips/
- https://docs.github.com/en/search-github/github-code-search/understanding-github-code-search-syntax

E.g. https://github.com/search?q=org%3Abincrafters&user%3Auilianries&type=code

**Comment by Croydon** [comment]
> Unfortunately not yet 😞 I'm checking an alternative in case not being possible to re-new Artifactory, like, using Bincrafters' Github as remote (under investigation).

I had the same though already. If we can get a data dump of ALL data in the Artifactory this might be an option. Conan just added the feature of local CCI-like recipe-only remotes. If we can access only data, we can probably bring it into such a form via scripting.

Then it would be recipe-only purely without any chance for binaries, but it would be fully independent.


In any case, I hope that at the very least, we can get a full download of all data at the very least, so we have options to explore from there.

**Comment by uilianries** [comment]
@Croydon Agreed, I'll be checking to recover it.

**Comment by farafonov-alexey** [comment]
Is there any ETA?
