### ISSUE TITLE
gtest linking problem

### ISSUE THREAD

**Issue by db4** [bincrafters/community#146]
gtest 1.0.8 adds libraries to `cpp_info.libs` in wrong order: instead of `gtest gmock gmock_main` it should be `gmock_main gmock  gtest`. Due to that I cannot build https://github.com/db4/conan-rabbitmq-c under Linux.  `conan create . dbely/testing -o '*:shared=False'` fails with:
```
mock_main.cc.o): In function `main':
gmock_main.cc:(.text.startup+0x28): undefined reference to `testing::InitGoogleMock(int*, char**)'
collect2: error: ld returned 1 exit status
```
`testing::InitGoogleMock` is defined in `gmock`, so  it should go after `gmock_main` in ld command line.

### Package Details (Include if Applicable)
* Package Name/Version: **gtest/1.0.8**
* Operating System: **Linux**
* Compiler+version: **gcc-5.4**

**Comment by SSE4** [comment]
@db4 I think I have fixed it, could you possibly update and try again?

**Comment by db4** [comment]
Yes, now it links without any errors. Thanks!

**Comment by SSE4** [comment]
confirmed as fixed
