### ISSUE TITLE
Websocketpp cmake target fails when linking (looks for .lib)

### ISSUE THREAD

**Issue by helmesjo** [bincrafters/community#147]
### Description of Problem, Request, or Question

I've got a feeling I'm missing something very obvious here, but how do I link the websocketpp (header-only) lib? The usual `target_link_library( mytarget PRIVATE websocketpp )` works during configuration, but while **linking throws this error**: 
`LINK : fatal error LNK1181: cannot open input file 'websocketpp.lib'`

Isn't [websocketpp](https://github.com/bincrafters/conan-websocketpp) setup as an _INTERFACE_ target, publicly including the "header-only" header? It shouldn't be looking for a _.lib_ file...

### Package Details
* Package Name/Version: **websocketpp/0.7.0**
* Operating System: **Linux**
* Compiler+version: **gcc-7.x**

### Steps to reproduce
CMakeLists.txt:
```
add_library( mytarget
	main.cpp
)
target_link_libraries( mytarget
	PRIVATE websocketpp
)
```

**Comment by SSE4** [comment]
as I can see, websocketpp doesn't declare any interface targets
https://github.com/zaphoyd/websocketpp/blob/master/websocketpp-config.cmake.in
but you may wish to use conan-generated target instead `target_link_libraries(mytarget PRIVATE CONAN_PKG::websocketpp)`

**Comment by helmesjo** [comment]
Wow, didn't even occur to me that they failed to provide an interface target... Looking at their cmake-scripts, on quickly finds a lot of deprecated `include_directories`, unfortunately.

Also, I already tried with `CONAN_PKG::websocketpp`, but I get:
`Target "myapp" links to target "CONAN_PKG::websocketpp" but the
  target was not found.`

This is with `websocketpp/0.7.0@bincrafters/stable` in my conanfile.txt & `conan_basic_setup()` before trying to link target. I can see it in the generated `conanbuildinfo.cmake` file though...

**Comment by SSE4** [comment]
in order to use conan-generated targets, you have to invoke conan like this:
`conan_basic_setup(TARGETS)`
when you will be able to use `CONAN_PKG::<package_name>`

**Comment by helmesjo** [comment]
Oh, more than I knew! Now I'll just need cmake 3.11.0 & [wrap it in my own interface target](https://github.com/conan-io/conan/issues/2125#issuecomment-359725468) to avoid downstream targets having to know about conan!

Anyways, thanks, now it works :)
