### ISSUE TITLE
[zmq] creates .so files when zmq:shared=False

### ISSUE THREAD

**Issue by hestad** [bincrafters/community#148]
### Package Details (Include if Applicable)
* Package Name/Version: **zmq/4.2.2**
* Operating System: **Linux Ubuntu 16.04**
* Compiler+version: **clang 5.0.1**
* Docker image: **none**
* Conan version: 0.28.1

conanfile.txt
```
[requires]
zmq/4.2.2@bincrafters/stable
[options]
zmq:shared=False
zmq:fPIC=True
zmq:encryption=None

[generators]
cmake
virtualrunenv
```

### Steps to reproduce (Include if Applicable)
1. conan install .. -e CC=/usr/bin/clang-5.0 -e CXX=/usr/bin/clang++-5.0 -s compiler=clang -s compiler.version=5.0 -s compiler.libcxx=libstdc++11 --build=missing

2.find ~/.conan/data/zmq -name "*.so"
```
/home/hestad/.conan/data/zmq/4.2.2/bincrafters/stable/package/9601b49a6ba7559997005c8795c886a6df75acf8/lib/libzmq.so
/home/hestad/.conan/data/zmq/4.2.2/bincrafters/stable/build/9601b49a6ba7559997005c8795c886a6df75acf8/build/sources/lib/libzmq.so
```
When using target_link_libraries with ${CONAN_LIBS} the .so file is dynamically linked which is unwanted.

**Comment by SSE4** [comment]
I've took a look, and ZeroMQ unconditionally builds both static and shared libraries in case of CMake build. how should we deal with such case?

/cc @solvingj @sigmoidal

**Comment by hestad** [comment]
I changed from this https://github.com/memsharded/conan-zmq/blob/4.2.0/conanfile.py

They seem to have solved it.

**Comment by SSE4** [comment]
yep, this can be solved by copying libraries conditionally
I'll change to do something similar

**Comment by SSE4** [comment]
@hestad I think I have fixed it, could you update and give another try? thanks

**Comment by SSE4** [comment]
so works as expected, right?

**Comment by hestad** [comment]
Yes. You can close this.

I also did a check with shared:True
```
Step 7/7 : RUN find ~/.conan/data -name "*.so" -o -name "*.a"
 ---> Running in fdf9a4580765
/root/.conan/data/zmq/4.2.2/bincrafters/stable/package/118911cf9edd1d780c2c6bd76a1fece9fdea6544/lib/libzmq.so
/root/.conan/data/zmq/4.2.2/bincrafters/stable/build/118911cf9edd1d780c2c6bd76a1fece9fdea6544/build/lib/libzmq.so
/root/.conan/data/zmq/4.2.2/bincrafters/stable/build/118911cf9edd1d780c2c6bd76a1fece9fdea6544/build/lib/libzmq.a
```

**Comment by SSE4** [comment]
confirmed as fixed
