### ISSUE TITLE
libtiff

### ISSUE THREAD

**Issue by lasote** [bincrafters/community#149]
### Description of Problem, Request, or Question

Hi, I accepted the inclusion request and then we realized that it is a C library and the packages being generated have the libstdc++. Could you activate the pure_c in CI and clean outdated, please?
Many thanks

**Comment by solvingj** [comment]
fyi, update, looks like rebuild is happening now.

**Comment by SSE4** [comment]
@lasote libtiff is rebuilt, outdated packages were removed
