### ISSUE TITLE
Publish opus (xiph) package

### ISSUE THREAD

**Issue by dimi309** [bincrafters/community#15]
I've added the opus library, from xiph, as a conan package:

https://github.com/bincrafters/conan-opus

Proof of successful builds from my fork:

https://travis-ci.org/dimi309/conan-opus/builds/312258190
https://ci.appveyor.com/project/coding3d/conan-opus/build/1.0.3

(some are still building at the time of writing but they should be fine)

I had to skip VS builds < v2015 because the library only provides a VS 2015 solution (can upgrade but can't downgrade)

Works on Linux, MacOS / OSX and Windows VS, but not MinGW because... autotools (see here: https://github.com/bincrafters/community/issues/13#issuecomment-349212800)

cc @SSE4 (as discussed)

**Comment by sztomi** [comment]
Since opus is a C library, I don't think it matters which compiler you are using on Windows. You can link a MSVC lib file in mingw-gcc no problem, if it's C.

**Comment by dimi309** [comment]
Manually yes, but how do you deploy to make a consumer detect it as "ok for gcc"?

**Comment by sztomi** [comment]
You can fake that the binary was compiled with gcc, i.e. if `self.settings.compiler == "gcc"` you just compile with MSVC. The conaninfo will contain gcc in this case and the binary will be built by MSVC (but compatible because it's C).

**Comment by dimi309** [comment]
It's an interesting method but do you have an example of a package that does this? The thing is in any case, if someone only has mingw on their system and this package needs to be built locally it will fail..

**Comment by dimi309** [comment]
I mean if he doesn't have VS at the same time..

**Comment by SSE4** [comment]
let's not apply workaround for MinGW
C libraries aren't so interchangeable as you may think, there are some other dark corners:

- calling convention - which may cause linking issues or problems in runtime
- memory management - e.g. passing buffer allocated in MSVC module into MinGW module and freeing it - probably bad idea due to the different malloc/free implementations
- structure alignment differences

I am going to look into MinGW builds soon, so for now please just add the following:

``` if self.settings.os == "Windows" and self.settings.compiler == "GCC":
    raise Exception("MinGW build is not implemented yet")```

**Comment by dimi309** [comment]
Sounds good. But are we sure we want the exception? Because I can only detect its condition as os == "Windows" and compiler == "gcc" and that would block people from using the package with say cygwin, which might work (I organise all my package builds as "build like this for visual studio, otherwise build like this", not being more specific on purpose..

**Comment by SSE4** [comment]
@dimi309 what combination of settings identify Cygwin build? how to distinguish MinGW builds from Cygwin?

**Comment by dimi309** [comment]
@SSE4 I think we can't, unless I am mistaken. If I am right, this is part of the problem we will have with these builds in general (see the other issue where we are discussing mingw, cygwin etc https://github.com/bincrafters/community/issues/13)

**Comment by SSE4** [comment]
I'll raise a question on Conan GitHub and CC you

**Comment by dimi309** [comment]
The package has been published. We can close this after we also publish my latest pull request 😄

**Comment by dimi309** [comment]
Thanks for verifying the pull request @solvingj . Shall we push to stable?

**Comment by solvingj** [comment]
yes go ahead.

**Comment by dimi309** [comment]
Ok, the xiph opus package is done: https://bintray.com/bincrafters/public-conan/opus%3Abincrafters

Final builds:
https://ci.appveyor.com/project/BinCrafters/conan-opus/build/1.0.7
https://travis-ci.org/bincrafters/conan-opus/builds/314206507
