### ISSUE TITLE
OpenAL: static=true but contains a DLL

### ISSUE THREAD

**Issue by madebr** [bincrafters/community#150]
### Description of Problem, Request, or Question
The option is `static=True`, but the archive contains a dynamic library, aka a dll.

See https://bintray.com/bincrafters/public-conan/openal%3Abincrafters#files/bincrafters%2Fopenal%2F1.18.2%2Fstable%2Fpackage%2F6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7
6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7

### Package Details (Include if Applicable)
* Package Name/Version: **openal/1.18.2**
* Operating System: **Windows**
* Compiler+version: **Visual Studio 2017**

**Comment by SSE4** [comment]
@madebr I think I have fixed it. could you possibly update and try again?

**Comment by madebr** [comment]
Fixed! Thank you very much!
