### ISSUE TITLE
ffmpeg with Intel QuickSync Video

### ISSUE THREAD

**Issue by maximMalofeev** [bincrafters/community#151]
Hi. ffmpeg have an opportunity to be compiled with Intel QuickSync Video. As for me it's a really important thing. Could you add the option libmfx to the recipe? I will really grateful if you do this.

### Package Details (Include if Applicable)
* Package Name/Version: **ffmpeg/3.4**
* Operating System: **Win**
* Compiler+version: **Visual Studio 2017**

**Comment by SSE4** [comment]
@maximMalofeev yep, it's on plan. I'll let you know once it's ready (may take day or two).

**Comment by maximMalofeev** [comment]
@SSE4 thanks for feedback. I'm looking forward to it)

**Comment by maximMalofeev** [comment]
Im sorry for importunity, but could you tell me about the date you are expect to solve this issue. It really important for me. Thanks.

**Comment by SSE4** [comment]
working hard on it :) expect on March 10

**Comment by SSE4** [comment]
@maximMalofeev ffmpeg with QSV is ready, could you give a try?

**Comment by maximMalofeev** [comment]
Thanks a lot, i will try it as soon as i can

**Comment by maximMalofeev** [comment]
Unfortunately it is dont work for me, at list an example from \share\ffmpeg\examples\qsvdec.c doesnt  work. But it seems another one issue, when i set option ffmpeg:qsv = False, all networks protocols, like rtp, becomes not avaliable....

**Comment by SSE4** [comment]
@maximMalofeev would be helpful if you could provide more information.
does it fail to compiler/link or run or what exactly happens?
is there an error message or detailed error log?

**Comment by maximMalofeev** [comment]
ok. In the case when qsv not works: as i said i use qsvdec.c frome ffmpeg sources. it compiled, but when i run it stops with an error, log looks like this: 
[avi @ 047292C0] non-interleaved AVI
[AVHWFramesContext @ 0CDA2F10] Error synchronizing the operation: -3
Error transferring the data to system memory
[AVHWFramesContext @ 0CDA2F10] Error synchronizing the operation: -2
Error transferring the data to system memory
Unknown error occurred

But if i change in av_hwdevice_ctx_create(&decode.hw_device_ref, AV_HWDEVICE_TYPE_QSV, "auto", NULL, 0) "auto" to "auto_any" and add some delay in decoding routine it starts work, but with my Nvidia gpu, not Intel.

**Comment by maximMalofeev** [comment]
Another one issue, when i disable ffmpeg:qsv, network protocols isnt available.
`
    av_register_all();
    avformat_network_init();

	void *op = nullptr;
	while (true) {
		auto prtr = avio_enum_protocols(&op, 0);
		if (prtr) {
			std::cout << prtr << "; ";
		}
		else {
			std::cout << std::endl;
			break;
		}
	}
`
this snippet prints the next list of protocols: async; cache; concat; crypto; data; file; hls; pipe; subfile;

When i use [options] by default(ffmpeg:qsv = True) list of available protocols looks like this: async; cache; concat; crypto; data; ffrtmphttp; file; ftp; gopher; hls; http; httpproxy; https; mmsh; mmst; pipe; rtmp; rtmps; rtmpt; rtmpts; rtp; srtp; subfile; tcp; tls; udp; udplite;

**Comment by SSE4** [comment]
@maximMalofeev sorry for the delayed response. I am back :)
about failing sample, it seems to be some problem with your installation of driver or Intel Media SDK. I regret but I don't think I can do much about it. may be it's worth to ask on Intel forum?
about protocols, it's also weird issues. could you upload your **ffbuild/config.log** files for builds with qsv=True and qsv=False?
