### ISSUE TITLE
libpng download sources fails

### ISSUE THREAD

**Issue by lasote** [bincrafters/community#152]
### Description of Problem, Request, or Question
Sourceforge is having some problems and the direct download of sources from conan is failing. It downloads instead of the zipped file an HTML file saying that you need js because they are in maintenance mode or something similar. I fixed zlib pointing to an alternate mirror. Is this GH official? https://github.com/glennrp/libpng/tree/v1.6.34 maybe it is worth it to change to download the tag.

### Package Details (Include if Applicable)
* Package Name/Version: **libpng/X**

### Steps to reproduce (Include if Applicable)

Clone repository:
conan create . user/channel

**Comment by theirix** [comment]
Yes, we suffer too from flaky sourceforge downloads. Last week SF was very unstable and even provided unstable mirrors.
Now it says: `The sourceforge.net website is temporarily in static offline mode. Only a very limited set of project pages are available until the main website returns to service.`

Another GH repo is https://github.com/glennrp/libpng-releases. Anyway I found no reference to glennrp repositories. It is not official mirror so it is not safe to use third-party sources.

**Comment by theirix** [comment]
Sourceforge seems to be up and the problem should go away.
I checked libpng-releases repository again - it is a repository with files (not github releases) and they do not have non-latest releases which are needed for our packages (1.6.32). So both repos cannot help us.

**Comment by lasote** [comment]
Confirmed that works.
