### ISSUE TITLE
zlib missing in boost_iostreams debug

### ISSUE THREAD

**Issue by wpalfi** [bincrafters/community#155]
### Description of Problem, Request, or Question
I am using Visual Studio 15 x64.
zlib works with boost_iostreams in release build but it is missing in debug build.
```
conan install boost_iostreams/1.66.0@bincrafters/stable -o boost*:shared=True -s build_type=Release
package 9a1aa32e7a416098eedc5d65b8639db9a6fea006
->zlib is there

conan install boost_iostreams/1.66.0@bincrafters/stable -o boost*:shared=True -s build_type=Debug
package a554b875b3cb47fd831b51f95a6803b68e11ba72
->no zlib!
```

When I try to build it, I get

```
> conan install boost_iostreams/1.66.0@bincrafters/stable -o boost*:shared=True -s build_type=Debug --build boost_iostreams
...
notice: [zlib] Using pre-installed library
notice: [zlib] Condition
...
====================================================
notice: [zlib] zlib is already configured
notice: [bzip2] bzip is already configured
notice: [lzma] lzma is already configured
Performing configuration checks

    - zlib                     : no
    - bzip2                    : yes
    - lzma                     : yes
```

I figured out that in
`zlib/1.2.11@conan/stable:8cf01e2f50fcd6b63525e70584df0326550364e1`
the lib filename is "zlibd.lib" and boost seems to look for "zlib.lib".

So I modified conanfile.py of boost_generator
```python
     def zlib_lib_paths(self):
         try:
             if self.conanfile.options.use_zlib:
-                return '"{0}"'.format('" "'.join(self.deps_build_info["zlib"].lib_paths)).replace('\\', '/')
+                dir = self.deps_build_info["zlib"].lib_paths[0]
+                tmpdir = tempfile.mkdtemp()
+                shutil.copyfile(os.path.join(dir,"zlibd.lib"),os.path.join(tmpdir,"zlib.lib"))
+                return '"{0}"'.format(tmpdir.replace('\\', '/'))
```
and it works with this hack.

I also checked https://github.com/conan-community/conan-boost and it has the same problem.

### Package Details (Include if Applicable)
* Package Name/Version: **boost_iostreams/1.66.0@bincrafters/stable:a554b875b3cb47fd831b51f95a6803b68e11ba72**
* Operating System: **Windows**
* Compiler+version: **Visual Studio 15**
* Docker image: **-**

**Comment by jamezmoran** [comment]
Can confirm this error, we currently cannot use boost::iostreams from conan in Debug because of this.

**Comment by SSE4** [comment]
@wpalfi @jamezmoran  changes are in testing/1.66.0 branch, please give another try

**Comment by SSE4** [comment]
I am closing this one, as changes were applied. please open new issue if you still encounter an error.
