### ISSUE TITLE
Websocketpp - Make boost and asio-standalone dependencies optional

### ISSUE THREAD

**Issue by helmesjo** [bincrafters/community#157]
### Description of Problem, Request, or Question
[Websocketpp](https://github.com/zaphoyd/websocketpp) has [no hard dependency](https://github.com/zaphoyd/websocketpp/issues/474) on [boost_asio](https://github.com/bincrafters/conan-boost_asio) or [asio standalone](https://github.com/bincrafters/conan-asio) (see also `ASIO_STANDALONE`), thus it should be possible to specify both as an option (if to require/install or not).

See more [here](https://www.zaphoyd.com/tags/websocketpp):

> **Standalone Asio now supported**
> Asio Transport may optionally use standalone Asio rather than Boost Asio. 
> This allows the use of the Asio transport with a C++11 build environment without any Boost libraries. 
> To enable, define ASIO_STANDALONE before any WebSocket++ or Asio headers.

Being able to run websocketpp with C++11 & Asio (without boost) would be very nice!

### Package Details
* Package Name/Version: **websocketpp/0.7.0**

**Comment by SSE4** [comment]
@helmesjo I've added asio option to support standalone asio use case.
you can use it like `-o websocketpp:asio=standalone`
can you update and give a try?

**Comment by helmesjo** [comment]
Thanks a lot, that worked! I did however have to manually link a threading library (`pthreads` in my case with gcc) to get rid of some linking errors in my target using `asio` (indirectly through `websocketpp`).

I'm using CMake so I did [this](https://cmake.org/cmake/help/v3.10/module/FindThreads.html) to keep it cross-platform:
```
# Asio requires a threading library
find_package(Threads REQUIRED)

target_link_libraries( my_target
	PRIVATE
		Threads::Threads
		CONAN_PKG::asio
		CONAN_PKG::websocketpp
)
```

I might be wrong but shouldn't this "Thread" requirement by `asio` be transitively added to `my_target` when linking `CONAN_PKG::asio`? That is, shouldn't it be a requirement on `asio` so that I as a client just link `asio` & "compile and run"? 
Does conan handle situations like these where some library is required by a package, that may differ depending on platform/compiler? Or I'm I supposed to manage compiler-specific settings myself?

**Comment by SSE4** [comment]
conan can handle that. I'll add pthread to asio.

**Comment by helmesjo** [comment]
Great, thanks! 

Just let me know when it's done and I'll test & hopefully close this.

**Comment by SSE4** [comment]
@helmesjo asio/1.11.0@bincrafters/stable has required changes

**Comment by helmesjo** [comment]
Got same issue at first, but after a cleanup of installed package (`conan remove asio/1.11.0@bincrafters/stable`), it seems to work correctly!

I now only have to do:
```
target_link_libraries( my_target
    PRIVATE
        CONAN_PKG::websocketpp
)
```

Thanks for the help, and extra thanks for quick the responses!

**Comment by solvingj** [comment]
Thanks for reporting @helmesjo , Great work @SSE4 .
