### ISSUE TITLE
inclusion request: spdlog

### ISSUE THREAD

**Issue by memsharded** [bincrafters/community#159]
Hi!

We are processing spdlog for conan-center and found some issues and have some questions:

- It uses by default the internal FMT, shouldn't be the external FMT from conan-center the default one?

- Please use a more complete test, like: 
```c++
int main(){
	auto console = spdlog::stdout_color_mt("console");
	console->info("Welcome to spdlog!");
	console->error("Some error message with arg{}..", 1);
	console->warn("Easy padding in numbers like {:08d}", 12);
}
```
It will allow seeing things on screen, which is nice. But what is more important, please remember than C++ optimizations might optimize out things that are not used, as the ``console`` var. Not that it is done in this case, and it is header-only so no big deal, but could be in other cases.

- It is a bit confusing that having the fmt external/Internal option the final package is still the same. So the package with ``fmt_external=True`` will still have a copy of **fmt** inside the package. Hopefully the include paths will be ok, and ``SPDLOG_FMT_EXTERNAL`` will be enough, but it is difficult to assess or guarantee that.

- It is a bit weird that creating the package requires building some source files that aren't used at all for any purpose. Is it possible to skip this build?

Many thanks!

**Comment by sourcedelica** [comment]
10-4

**Comment by sourcedelica** [comment]
I will work on this this weekend

**Comment by memsharded** [comment]
Actually, I have changed my mind. I have inspected the internals of spdlog, how it includes fmt, and keeping the build is necessary so cmake generates all the find-cmake stuff.

So I think only:
- Change fmt_external=True default
- Check that the find.cmake scripts generated are really usable (because they are not in the root, the are in ``lib/cmake``)

Many thanks!

**Comment by solvingj** [comment]
Thanks @memsharded and @sourcedelica for working on this!

**Comment by sourcedelica** [comment]
See my comments/questions on https://github.com/bincrafters/conan-spdlog/pull/4

**Comment by sourcedelica** [comment]
I think it's ready to go: https://github.com/bincrafters/conan-spdlog/pull/4

**Comment by uilianries** [comment]
The package was merged in Conan center: https://bintray.com/conan/conan-center?filterByPkgName=spdlog%3Abincrafters
