### ISSUE TITLE
cmake_findboost_modular - always add all includes

### ISSUE THREAD

**Issue by wpalfi** [bincrafters/community#161]
From https://cmake.org/cmake/help/latest/module/FindBoost.html:

> This module first searches for the Boost header files using the above hint variables (excluding BOOST_LIBRARYDIR) and saves the result in Boost_INCLUDE_DIR. Then it searches for requested component libraries 
[...]
> Boost::boost                  - Target for header-only dependencies
>                                 (Boost include directory)

So all header-only-libs should **always** be added to Boost_INCLUDE_DIRS and an additional `Boost::boost` target should be created. The current implementation in cmake_findboost_modular adds header-only-libs only if no components are requested:

```cmake
if (NOT Boost_FIND_COMPONENTS)
   #add all
endif()
```

E.g. when used with `find_package(Boost COMPONENTS test)`, it only adds boost_test. Any additional installed header-only-libs that are not required by boost_test are missing.

I propose to replace the above block with:

```cmake
add_library(Boost::boost INTERFACE IMPORTED)
foreach(component ${Boost_ALL_COMPONENTS})
    string(TOUPPER ${component} component_upper)
    set(include_dir ${CONAN_INCLUDE_DIRS_BOOST_${component_upper}})
    if(include_dir)
        target_include_directories(Boost::boost INTERFACE ${include_dir})
        list(APPEND Boost_INCLUDE_DIRS ${include_dir})
    endif()
endforeach()
```

**Comment by SSE4** [comment]
thanks for the reporting. I'll implement required changes tomorrow and let you know once they are ready for testing.

**Comment by SSE4** [comment]
@wpalfi changes applied, could you possibly give an another try?

**Comment by wpalfi** [comment]
I checked it, but there is still a problem: 

I know the documentation says

> Boost::boost - Target for header-only dependencies

So you added a new variable Boost_INCLUDE_DIRS_HEADER_ONLY that you are using for Boost::boost. That sounds reasonable and was also my first intention. But some header-only-libs include headers of non-header-only-libs. E.g. we are using lexical_cast which includes `boost/container/container_fwd.hpp`. That is not a full dependency (you can use lexical_cast without the container binaries), so linking with Boost::boost is sufficient. We have the correct dependencies in the conan recipes (lexical_cast->level8group->container), so the lib is installed, but we must add the includes also to Boost::boost. So I would just use Boost_INCLUDE_DIRS instead of Boost_INCLUDE_DIRS_HEADER_ONLY.

**Comment by SSE4** [comment]
okay, sounds reasonable, I'll make the change

**Comment by wpalfi** [comment]
One more point: I am not sure, but after reading the cmake documentation, I think you should remove the 
```cmake
if (NOT Boost_FIND_COMPONENTS)
   #add all...
endif()
```
block. I think components (binaries) should only be used when explicitly requested with `COMPONENTS`.

**Comment by SSE4** [comment]
this block is required to populate other variables (like Boost_LIBRARY_DIRS), which has to be set up even if no components specified. see issue #boo

**Comment by wpalfi** [comment]
Hm, why do you need Boost_LIBRARY_DIRS if no components specified?

**Comment by SSE4** [comment]
e.g. in old projects and old CMake I was using code like:
```
find_package(Boost REQUIRED)
include_directories(${Boost_INCLUDE_DIRS})
link_directories(${Boost_LIBRARY_DIRS})
target_link_libraries(something ${Boost_LIBRARIES})
```
and it worked very well, without any components specified

**Comment by SSE4** [comment]
btw, new changes are in bintray, please give one more try

**Comment by wpalfi** [comment]
Will try immediately...

regarding Boost_LIBRARY_DIRS:
I still dont see the problem. I just tried this:

```cmake
find_package(Boost REQUIRED)
message(STATUS "Boost_LIBRARY_DIRS (${Boost_LIBRARY_DIRS})")
target_link_libraries(something ${Boost_LIBRARIES})
```

With cmake's default findBoost it just links nothing and prints
`Boost_LIBRARY_DIRS ()`

With your findBoost it links everything and prints
`Boost_LIBRARY_DIRS (;C:/.conan/9kw727ap/1/algorithm/lib (ALGORITHM);C:/.conan/93tzh2u6/1/any/lib (ANY);......<many more>)`

After removing the add-all-block, it links nothing and again prints
`Boost_LIBRARY_DIRS ()`

**Comment by SSE4** [comment]
yep, seems like you're right - I've checked old CMake 2.6 documentation, and it always worked that way. I'll remove mentioned block.

**Comment by wpalfi** [comment]
Tested Boost::boost again. Works now with lexical_cast, thanks:-)

**Comment by SSE4** [comment]
okay, I am closing the issue then.
