### ISSUE TITLE
Conflict in boost_assign/1.66.0@bincrafters/stable

### ISSUE THREAD

**Issue by mpusz** [bincrafters/community#162]
### Description of Problem, Request, or Question
```
ERROR: Conflict in boost_assign/1.66.0@bincrafters/stable
    Requirement boost_package_tools/1.66.0@bincrafters/testing conflicts with already defined boost_package_tools/1.66.0@bincrafters/stable
    Keeping boost_package_tools/1.66.0@bincrafters/stable
    To change it, override it in your base requirements
```
### Package Details (Include if Applicable)
* Package Name/Version: **boost_assign/1.66.0**
* Operating System: **Windows**
* Compiler+version: **VS2017**
* Docker image: ****

**Comment by SSE4** [comment]
Hi @mpusz 
unfortunately I was unable to reproduce this error.
could you possibly run the following command:
```conan remove boost_* -f```
and give another try?

see also dependency report for boost_assign/1.66.0@bincrafters/stable - it doesn't contain any testing dependencies.

[boost_assign.txt](https://github.com/bincrafters/community/files/1925016/boost_assign.txt)

**Comment by SSE4** [comment]
@mpusz I am closing the issue for now, please open a new one if it still happens
