### ISSUE TITLE
catch upstream version bump

### ISSUE THREAD

**Issue by solvingj** [bincrafters/community#163]
### Description of Problem, Request, or Question
Catch2 v2.2 is out:
https://github.com/catchorg/Catch2/releases/tag/v2.2.0
https://github.com/bincrafters/conan-catch

We just need someone to bump and trigger CI

**Comment by uilianries** [comment]
Done!
https://github.com/bincrafters/conan-catch2/tree/stable/2.2.0
https://bintray.com/bincrafters/public-conan/catch2%3Abincrafters/2.2.0%3Astable
