### ISSUE TITLE
Inclusion request review: openal/1.18.2@bincrafters/stable 

### ISSUE THREAD

**Issue by lasote** [bincrafters/community#164]
## Inclusion Request Review

This is a review for [openal/1.18.2@bincrafters/stable (bincrafters/public-conan)](https://github.com/bincrafters/conan-openal) inclusion request to conan-center.
This review follows the [inclusion guidelines or third party libraries](http://docs.conan.io/en/latest/uploading_packages/bintray/conan_center_guide.html#inclusion-guidelines-for-third-party-libraries).

### Package
openal/1.18.2@bincrafters/stable

#### Recipe quality
- [x] Git public repository
- [x] Recipe fields
- [x] Linter
- [x] Updated
- [x] Clean
- [x] test_package
- [x] Raise errors on invalid configurations
- [x] LICENSE of the recipe
- [x] LICENSE of the library

#### CI Integration
- [x] Provide at least one CI configuration (header only)
- [x] (If not header only) CI configurations for Linux/MacOSX/Windows

#### Bintray Package Information
- [x] Description
- [x] Licenses
- [x] Tags
- [x] Maturity
- [x] Website (if any)
- [x] Issue tracker
- [x] Version control

### Additional comments

I've opened https://github.com/bincrafters/conan-openal/pull/2 to help.

There are some outdated packages, clean them up with: 
`conan remove openal/1.18.2@bincrafters/stable --outdated -r bincrafters`

**Comment by SSE4** [comment]
outdated packages were removed

**Comment by lasote** [comment]
Approved! congrats!
