### ISSUE TITLE
Inclusion request lcms/2.9@bincrafters/stable 

### ISSUE THREAD

**Issue by lasote** [bincrafters/community#165]
## Inclusion Request Review

This is a review for [lcms/2.9@bincrafters/stable (bincrafters/public-conan)](https://github.com/bincrafters/conan-lcms) inclusion request to conan-center.
This review follows the [inclusion guidelines or third party libraries](http://docs.conan.io/en/latest/uploading_packages/bintray/conan_center_guide.html#inclusion-guidelines-for-third-party-libraries).

### Package
lcms/2.9@bincrafters/stable

#### Recipe quality
- [x] Git public repository
- [x] Recipe fields
- [x] Linter
- [x] Updated
- [x] Clean
- [x] test_package
- [x] Raise errors on invalid configurations
- [x] LICENSE of the recipe
- [x] LICENSE of the library

#### CI Integration
- [x] Provide at least one CI configuration (header only)
- [x] (If not header only) CI configurations for Linux/MacOSX/Windows

#### Bintray Package Information
- [x] Description
- [x] Licenses
- [x] Tags
- [x] Maturity
- [x] Website (if any)
- [x] Issue tracker
- [x] Version control

### Additional comments

- There is a PR opened to remove the `libcxx` and using a new feature to manage the Win32 != x86 in visual projects: https://github.com/bincrafters/conan-lcms/pull/1
- Introduce some tags in the Bintray page.

**Comment by theirix** [comment]
Added tags

**Comment by lasote** [comment]
There are some missing packages since we removed the libcxx. Please remove them with:

`conan remove lcms/2.9@bincrafters/stable --outdated -r bincrafters`

Also, there a linter error solved in a new pr.

**Comment by theirix** [comment]
sure, I'm on it

**Comment by theirix** [comment]
Merged PR and cleaned up outdated recipes.

**Comment by lasote** [comment]
Accepted! congrats, great job.
