### ISSUE TITLE
conan-sqlite_orm update to 1.0

### ISSUE THREAD

**Issue by AlexandrePTJ** [bincrafters/community#170]
Hi,
I maintain conan-sqlite_orm recipe.
As sqlite_orm just changes its version to 1.0 I am trying to create the corresponding branch but it looks like I do not have right permission to do it.
Did I miss something in the process ?

Thanks.

**Comment by SSE4** [comment]
you may create pull request

**Comment by AlexandrePTJ** [comment]
Did it. Thanks.
