### ISSUE TITLE
libcurl status

### ISSUE THREAD

**Issue by danimtb** [bincrafters/community#171]
### Description of Problem, Request, or Question

We have checked [libcurl](https://github.com/bincrafters/conan-libcurl) as we have some arising necessities to have it in conan-center and it looks quite good! 👍

I would like to point some issues to start working on the process of a future inclusion request.

### Package Details (Include if Applicable)
* Package Name/Version: **libcurl/7.50.3**, **libcurl/7.52.1**, **libcurl/7.56.1**
* Operating System: **Windows 10**
* Compiler+version: **Visual Studio 15**

### Steps to reproduce (Include if Applicable)

- License: There is no licenses folder or file packaged.
- Remove libcxx flag: Libcurl seems to be a C library so please remove libcxx setting.

```
def configure(self):
    del self.settings.compiler.libcxx
```

- There are some outdated packages from recipe that would need a rebuild or just delete them:

```
$ conan remove libcurl/7.50.3@bincrafters/stable -r bincrafters --outdated
```

**Comment by theirix** [comment]
Thank you for checking libcurl!

1. I had added licenses at least at January. Packages are updated last time a week ago. Checked now 7.50.3, 7.56.1 - licenses are here, `licenses/COPYING`. I cleaned up outdated packages, please check again, maybe you hit a very old binary.

2. setting libcxx is already removed in `config_options`

3. Cleaned up outdated packages, thanks!

**Comment by danimtb** [comment]
Thanks for the quick response @theirix!

- My mistake: You are right, licenses are actually there. I had a problem with `short_paths=True`.
- Didn't notice the deletion of libcxx in `config_options()`. We usually do it in `configure()` as that is the best place to delete settings. It is ok, but please consider it for next updates and packages :)
- Table looks fine now!

Thank you!

**Comment by theirix** [comment]
You are right, the manual says that `config_options` should be used for 'modify options based on settings'. I'll consider moving it to `configure` next time.

Please note that libcurl is very fast-paced software and latest version (7.58.0) is not yet available. The conan package tries to use various patches and fixes based on upstream version so adding a new version should be easy. I can add it if it will be required for inclusion request.

Closing for now.

**Comment by danimtb** [comment]
Is OK as it is, don't worry! An thanks again for the great work 😉

**Comment by danimtb** [comment]
Sorry, I have just checked and as this is a C library you would have to delete libcxx here too:

```
def configure(self):
     del self.settings.compiler.libcxx
```

Just this it would be ready for conan-center!

**Comment by theirix** [comment]
Hmm, deleting just in `config_options` is not enough?

**Comment by theirix** [comment]
Latest changes:
1. Moved out libcxx to `configure`
2. Added `fPIC` option for unix builds
3. Rebuilt and cleaned outdated packages
4. Filled a request

**Comment by danimtb** [comment]
libcurl is finally in conan-center! Thank you so much for the great work on this library  💯
