### ISSUE TITLE
gtest/1.8.0 linkage error (gcc-4.9)

### ISSUE THREAD

**Issue by jgsogo** [bincrafters/community#172]
### Description of Problem, Request, or Question
I think it is the same problem as [here](https://github.com/bincrafters/community/issues/160), `libgmock.a` needs to be rebuilt for gcc4.9. Error is:

```
/usr/bin/ld: /home/conan/.conan/data/gtest/1.8.0/bincrafters/stable/package/040f7870129deed6e8a5b6c8560202a92eea89a3/lib/libgmock.a(gmock-all.cc.o): unrecognized relocation (0x2b) in section `.text'
/usr/bin/ld: final link failed: Bad value
```
--> CI job here: https://travis-ci.org/jgsogo/conan-variant/jobs/352262570#L929

### Package Details (Include if Applicable)
* Package Name/Version: **gtest/1.8.0**
* Operating System: **Linux Ubuntu 16.04**
* Compiler+version: **gcc-4.9**
* Docker image: **lasote/conangcc49**

**Comment by solvingj** [comment]
gtest package was rebuild by @SSE4 a few hours after you opened this ticket. Please try again.

**Comment by jgsogo** [comment]
Now it is working, thanks @SSE4
