### ISSUE TITLE
libssh2 status

### ISSUE THREAD

**Issue by danimtb** [bincrafters/community#173]
### Description of Problem, Request, or Question

We have checked [libssh2](https://github.com/bincrafters/conan-libssh2) as we have some arising necessities to have it in conan-center. It is working great! 😃 

I would like to point some issues to start working on the process of a future inclusion request.

### Package Details (Include if Applicable)
* Package Name/Version: **libssh2/1.8.0**
* Operating System: **Windows 10**
* Compiler+version: **Visual Studio 15**

### Steps to reproduce (Include if Applicable)

- Remove libcxx flag: libssh2 seems to be a C library so please remove libcxx setting.

```
def configure(self):
    del self.settings.compiler.libcxx
```

- There are some outdated packages from recipe that would need a rebuild or just delete them:

```
$ conan remove libssh2/1.8.0@bincrafters/stable -r bincrafters --outdated
```

**Comment by theirix** [comment]
Thank you for the advice!
Removed libcxx, rebuilt and removed outdated packages.

**Comment by danimtb** [comment]
Thanks @theirix! Please consider making the inclusion-request when you are fine with it :)

**Comment by danimtb** [comment]
Sorry, I have just checked and as this is a C library you would have to delete libcxx here too:

```
def configure(self):
    del self.settings.compiler.libcxx
```

Just this it would be ready for conan-center!

**Comment by theirix** [comment]
It is removed in `config_options`. Just checked experimentally that it's not required to remove in `configure` too. Please correct me if I'm mistaken.
Anyway I'll move it to `configure` at next build.

**Comment by theirix** [comment]
> Anyway I'll move it to configure at next build.

Done
