### ISSUE TITLE
abseil/20180223 - ConanException not imported

### ISSUE THREAD

**Issue by drrlvn** [bincrafters/community#174]
### Description of Problem, Request, or Question
When trying to install `abseil/20180223` I get the following error:
```
ERROR: abseil/20180223@bincrafters/stable: Error in configure() method, line 35
	raise ConanException(
	NameError: name 'ConanException' is not defined
```

### Package Details (Include if Applicable)
* Package Name/Version: **abseil/20180223**
* Operating System: **Arch Linux**
* Compiler+version: **gcc-7.3**

**Comment by r-darwish** [comment]
@solvingj these kind of errors aren't detected by Travis because we usually don't test bad paths. However, they can probably be detected by tools such as Pylint. If you're interested, I can check how difficult would it be to start analysing conanfiles with Pylint in Travis

**Comment by SSE4** [comment]
@drrlvn  required changes were applied
@r-darwish conan already runs linter and reports about such error, we just need to pay attention to these warnings :)
