### ISSUE TITLE
conan-ogg inclusion request into conan-center

### ISSUE THREAD

**Issue by pvicente** [bincrafters/community#175]
## Inclusion Request Review

This is a review for [ogg/1.3.3@bincrafters/stable](https://bintray.com/bincrafters/public-conan/ogg%3Abincrafters/1.3.3%3Astable) inclusion request into conan-center.

### Package

ogg/1.3.3@bincrafters/stable

### Checks and Comments

**Recipe quality**

- [X] Git public repository
- [X] Recipe fields
- [X] Linter
- [X] Updated
- [X] Clean
- [X] test_package
- [X] Raise errors on invalid configurations
- [X] LICENSE of recipe
- [X] LICENSE of library

**Comments**:

- fPIC handling needs to be moved to config_options
- source and package license needs to be packaged in licenses folder.
- package method is a bit complicated, calling cmake.install() should simplify it.

**CI integration**

- [X] (If not header only) CI configurations for Linux/MacOSX/Windows

**Comments**:
- Binaries in Bintray are not up to date (see below)
- Added clang 5.0 in CI for Linux

![screenshot 2018-03-13 13 55 13](https://user-images.githubusercontent.com/471109/37346045-46d3fd20-26c6-11e8-976a-bf4b0016c6f6.png)

To remove out of date binaries run:

```$conan remove ogg/1.3.3@bincrafters/stable --outdated -r bincrafters```

**Bintray Package Information**

- [X] Description
- [x] Licenses
- [x] Tags
- [X] Maturity
- [X] Website (if any)
- [X] Issue tracker
- [X] Version control
- [X] Github repo (user/repo)

**Comments**:
- License in Bintray should be BSD (sources license) not MIT see [doc](http://docs.conan.io/en/latest/uploading_packages/bintray/conan_center_guide.html#bintray-package-information)
- Please add some tags for search ```audio  | c | c++```

**Comment by pvicente** [comment]
Hi @solvingj @SSE4, many thanks for merging the changes.

Could you updated the missing parts in [Bintray](https://bintray.com/bincrafters/public-conan/ogg%3Abincrafters) please?

- License should be BSD (library license)
- Some tags for search i.e: ```audio | c | c++```

**Comment by SSE4** [comment]
@pvicente license changed, tags added

**Comment by pvicente** [comment]
@SSE4 I can't see any changes in [bintray](https://bintray.com/bincrafters/public-conan/ogg%3Abincrafters)

**Comment by SSE4** [comment]
@pvicente try again pls

**Comment by pvicente** [comment]
All ok, above MR can be added integrated later, only cosmetic change.
