### ISSUE TITLE
RapidJSON package to bincrafters

### ISSUE THREAD

**Issue by Mikayex** [bincrafters/community#179]
### Description of Problem, Request, or Question
Hi !
I've created a package for [RapidJSON](http://rapidjson.org/) using your packaging standards : https://github.com/Mikayex/conan-rapidjson. It is ready to be copied to bincrafters organization (everything reference bincrafters/rapidjson package).

You can find CI here :
- https://ci.appveyor.com/project/Mikayex/conan-rapidjson
- https://travis-ci.org/Mikayex/conan-rapidjson

PS : I don't know if this is the correct procedure to do this...
PPS : I really like your commitment to create high quality packages ! I may help you create other packages, depending on my free time.

### Package Details
* Package Name/Version: **rapidjson/1.1.0**
* Operating System: **all** (header only)
* Compiler+version: **all** (header only)

**Comment by uilianries** [comment]
Hi @Mikayex !

Thanks for your submission.

It looks a great job! Very clean recipe!

I'm going to pull your project into Bincrafters.

Please, join us at [Slack](cpplang.slack.com) if you are interested to discuss more about the community.

Best regards!

**Comment by uilianries** [comment]
Done!

https://github.com/bincrafters/conan-rapidjson
https://bintray.com/bincrafters/public-conan/rapidjson%3Abincrafters
https://ci.appveyor.com/project/BinCrafters/conan-rapidjson
https://travis-ci.org/bincrafters/conan-rapidjson

I'm going to request the submission on Conan center.

Thanks again for your effort!

**Comment by solvingj** [comment]
Please change license field in conanfile to abbreviated form.

**Comment by uilianries** [comment]
@solvingj Done!

**Comment by solvingj** [comment]
Great job @Mikayex, thank you very much for this contribution!  Indeed, we look forward to working with you more in the future.
