### ISSUE TITLE
Define a scripting strategy for updating Bintray metadata

### ISSUE THREAD

**Issue by solvingj** [bincrafters/community#18]
When switching our strategy to aggregate all github issues to this repository, I scripted the `jfrog cli` to update the metadata on Bintray.  An example command is given below. 

Currently, each time we publish a new package, we have to update the metadata manually.  Using the `jfrog cli` a script could parse out all the information it needs from `conanfile.py` and/or `README.md`, and this step could be made much easier.  We could also add a final step to our Travis or Appveyor CI process, to run the script when the branch is stable, however it's unclear if we actually want that or not. 

*Note:  This scripting I used to create the command below was tailored to a mass one-time update, so not really useful as a starting point.*

`jfrog bt pu --licenses BSL-1.0 --pub-dn true --vcs-url https://github.com/bincrafters/conan-boost-accumulators --desc "Framework for incremental calculation, and collection of statistical accumulators, from Eric Niebler" --website-url https://github.com/boostorg/accumulators --github-repo bincrafters/conan-boost-accumulators --issuetracker-url https://github.com/bincrafters/conan-boost-accumulators/issues bincrafters/public-conan/Boost.Accumulators:bincraftersjfrog bt pu --licenses BSL-1.0 --pub-dn true --vcs-url https://github.com/bincrafters/conan-boost- --desc "Framework for incremental calculation, and collection of statistical accumulators, from Eric Niebler" --website-url https://github.com/boostorg/ --github-repo bincrafters/conan-boost- --issuetracker-url https://github.com/bincrafters/conan-boost-/issues bincrafters/public-conan/Boost.accumulators:bincrafters`

**Comment by uilianries** [comment]
You read my thoughts! I was thinking about this after to push RapidJSON.

Maybe we could improve Conan Package Tools to push all these information.

**Comment by solvingj** [comment]
Actually, that reminds me that I created this feature request: 
https://github.com/conan-io/conan/issues/1675

Now, while it would be possible to write a few python classes to do the API calls to the Bintray API behind the scenes in Conan or Conan Package Tools, I think now is a bad time for this.  I've just sent an email to jfrog asking if there's any API changes on the roadmap.  Will decide what to do upon response.

**Comment by SSE4** [comment]
can't bintray extract all necessary metadata from conan metadata, as it's already in place?
it sounds like more feature for conan rather for packagers

**Comment by solvingj** [comment]
Yes, the conan ticket i referenced was asking them to handle it on the backend, but it's likely to be a slow one, so it's probably worth it to automate until then since it will be fairly easy to do on our side.

**Comment by solvingj** [comment]
don't see anyone getting to this soon. we'll wait for it to happen on the backend.
