### ISSUE TITLE
Manage fpic correctly in libxml

### ISSUE THREAD

**Issue by danimtb** [bincrafters/community#180]
### Description of Problem, Request, or Question
https://github.com/bincrafters/conan-libxml2
fpic option is not deleted in windows

### Package Details (Include if Applicable)
* Package Name/Version: *libxml2/2.9.8@bincrafters/stable**

### Steps to reproduce (Include if Applicable)

Please delete fpic option in windows:

```
def config_options(self):
    if self.settings.os == "Windows":
        del self.options.fPIC
```

After that it should be OK for conan-center
Thanks! :)

cc/ @theirix

**Comment by uilianries** [comment]
@danimtb Done!

**Comment by danimtb** [comment]
Many thanks! I t should be ready to conan-center just after libiconv requirement :)

**Comment by theirix** [comment]
Great! By the way libiconv is already is conan-center (since Mar 03).

**Comment by danimtb** [comment]
ups, I checked the wrong libiconv url! Perfect then!
