### ISSUE TITLE
conan-flac inclusion request into conan-center

### ISSUE THREAD

**Issue by pvicente** [bincrafters/community#181]
## Inclusion Request Review

This is a review for [flac/1.3.2@bincrafters/stable (bincrafters/public-conan)](https://github.com/bincrafters/conan-flac) inclusion request to conan-center.
This review follows the [inclusion guidelines or third party libraries](http://docs.conan.io/en/latest/uploading_packages/bintray/conan_center_guide.html#inclusion-guidelines-for-third-party-libraries).

### Package
flac/1.3.2@bincrafters/stable

#### Recipe quality
- [x] Git public repository
- [x] Recipe fields
- [x] Linter
- [ ] Updated
- [ ] Clean
- [x] test_package
- [ ] Raise errors on invalid configurations
- [x] LICENSE of the recipe
- [ ] LICENSE of the library

Test package is only using a function from the C API but not the CXX API. It should be better if it's using the CXX API and it's encoding some file, see official [example.cpp](https://github.com/xiph/flac/blob/master/examples/cpp/encode/file/main.cpp) 

#### CI Integration
- [ ] Provide at least one CI configuration (header only)
- [ ] (If not header only) CI configurations for Linux/MacOSX/Windows

Some binaries are missed.

#### Bintray Package Information
- [x] Description
- [x] Licenses
- [x] Tags
- [x] Maturity
- [x] Website (if any)
- [x] Issue tracker
- [x] Version control

### Additional comments

There are some outdated packages, clean them up with: <br>`conan remove flac/1.3.2@bincrafters/stable --outdated -r bincrafters`

**Comment by pvicente** [comment]
@dimi309 @SSE4 After the merge the only remaining thing is to remove outdated binaries:

```conan remove flac/1.3.2@bincrafters/stable --outdated -r bincrafters```

Please do it and we'll do the integration in conan-center.

See details:

![screenshot 2018-03-15 14 23 24](https://user-images.githubusercontent.com/471109/37469136-8a3792b0-285c-11e8-9de7-a361418e89db.png)

**Comment by SSE4** [comment]
@pvicente done

**Comment by pvicente** [comment]
@SSE4 Many thanks!!! All done, https://bintray.com/conan/conan-center?filterByPkgName=flac%3Abincrafters
