### ISSUE TITLE
Argh already in conan-center

### ISSUE THREAD

**Issue by danimtb** [bincrafters/community#182]
### Description of Problem, Request, or Question
Argh library is already in conan-center supported directly by the author.
https://github.com/adishavit/argh
https://bintray.com/adishavit/conan/argh%3Aadishavit

This is just a reminder in case you want to take further action regarding your repository here:
https://github.com/bincrafters/conan-argh

Bintray: https://bintray.com/bincrafters/public-conan/argh%3Abincrafters/1.2.0%3Astable

### Package Details (Include if Applicable)
* Package Name/Version: **argh/1.2.0@bincrafters/stable**

**Comment by solvingj** [comment]
i've deleted our package and the github project.  was unlikely to be used by anyone.  thanks for pointing it out.

**Comment by danimtb** [comment]
That recipe was indeed a great starting point to make the author adopt conan.
Thanks a lot for the great job!
