### ISSUE TITLE
Package contributing guidelines

### ISSUE THREAD

**Issue by rhard** [bincrafters/community#183]
### General package workflow
...
9. Once working and verified, create the equivalent repo in Bincrafters
...
### Problem
I want to contribute to Bincrafters. Given I already have my private package tested and ready for submit. 
In the documentation above (package_guidelines_faq.rst) it is not clear how to create repository in Bincrafters. Could you please give more details here?

**Comment by uilianries** [comment]
Hi @rhard!

We (Bincrafters members) are able to create an equivalent repo, that means, same repo name, but using your repository as origin. So, we preserve your commits and authority.

For example, our package for [rapidjson](https://github.com/bincrafters/conan-rapidjson) was created by @Mikayex.  
Initially, he created his own repo and after to finish the recipe, he asked to include in our repo by a new issue here in the community.  
We made the review, and after to be approved, his project was "copied" into Bincrafters.  
After to copy, we pushed the packages on our Bintray repository and requested to be included on Conan center.

**Comment by rhard** [comment]
Thanks! So, I will need to open an issue with a link to my repository. Maybe you can extend the FAQ with this details?

**Comment by uilianries** [comment]
You are correct on both arguments,  
you should open an issue requesting the project inclusion, where we could review and discuss about.  
And as you said, we must improve our FAQ to include these details.  

Thanks for ask about it, you just helped to get a better documentation.  

BTW, there is a good example [here](https://github.com/bincrafters/community/issues/179), how to request your package inclusion.
