### ISSUE TITLE
Upgrade catch2 to 2.2.1

### ISSUE THREAD

**Issue by sourcedelica** [bincrafters/community#184]
### Package Details (Include if Applicable)
* Package Name/Version: **catch2/2.2.0**
* Operating System: **Linux**
* Compiler+version: **gcc-5.4**

Catch2 has been upgraded to 2.2.1 to fix a major bug: https://github.com/catchorg/Catch2/issues/1215

Catch Reports Exit Code 0 Even with Failed Tests · Issue #1215 · catchorg/Catch2

**Comment by uilianries** [comment]
Done!

https://bintray.com/bincrafters/public-conan/catch2%3Abincrafters/2.2.1%3Astable

**Comment by sourcedelica** [comment]
Thanks dude!

**Comment by uilianries** [comment]
Enjoy!
