### ISSUE TITLE
conan-pcre2 Windows PCRE2_STATIC not defined for consumer

### ISSUE THREAD

**Issue by vadixidav** [bincrafters/community#188]
### Description of Problem, Request, or Question

pcre2 specifies __declspec(dllimport) if PCRE2_STATIC is not defined. Since the package doesn't set this define for consumers, it results in symbols failing to be found for "__impl_*" on Windows since it is looking for dllimport symbols rather than the static symbols which are present.

To fix the `conanfile.py` needs this in `package_info`:
```python
if not self.options.shared:
    self.cpp_info.defines.append("PCRE2_STATIC")
```

### Package Details (Include if Applicable)
* Package Name/Version: **pcre2/10.31**
* Operating System: **Windows 10**
* Compiler+version: **Visual Studio 2015 Professional**

**Comment by uilianries** [comment]
@vadixidav Please, update again.

If you see any problem, re-open this issue.

Regards!
