### ISSUE TITLE
cpprest for android

### ISSUE THREAD

**Issue by alexxxgu** [bincrafters/community#189]
Hi, I'm trying to build cpprestsdk 2.10.1 & 2.9.1 using clang, standalone toochain, and conan profile.
include from CXXFLAGS= -fPIE -fPIC -I$standalone_toolchain/include/c++/4.9.x is missing
```
...found 176 targets...
...updating 13 targets...
common.copy system/lib/jamroot.jam
clang-linux.compile.c++.without-pth bin/system/build/49fab69930d5ddcba6d43c790dc712bb/error_code.o
In file included from system/src/error_code.cpp:16:
In file included from system/include/boost/system/error_code.hpp:14:
In file included from system/include/boost/system/config.hpp:13:
In file included from /home/user/.conan/data/boost_config/1.66.0/bincrafters/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/config/include/boost/config.hpp:44:
/home/user/.conan/data/boost_config/1.66.0/bincrafters/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/config/include/boost/config/detail/select_stdlib_config.hpp:18:12: fatal error: 'cstddef' file not found
#  include <cstddef>
           ^~~~~~~~~
1 error generated.

  "clang++" -c -x c++ -fPIC -stdlib=libc++ -O0 -g -fno-inline -Wall -g -fPIC -stdlib=libc++ -DBOOST_ALL_NO_LIB=1 -DBOOST_SYSTEM_STATIC_LINK=1 -I"/home/user/.conan/data/boost_assert/1.66.0/bincrafters/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/assert/include" -I"/home/user/.conan/data/boost_config/1.66.0/bincrafters/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/config/include" -I"/home/user/.conan/data/boost_core/1.66.0/bincrafters/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/core/include" -I"/home/user/.conan/data/boost_predef/1.66.0/bincrafters/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/predef/include" -I"/home/user/.conan/data/boost_winapi/1.66.0/bincrafters/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/winapi/include" -I"system/include" -o "bin/system/build/49fab69930d5ddcba6d43c790dc712bb/error_code.o" "system/src/error_code.cpp"

```

boost/1.66.0@conan/stable is ok.

**Comment by alexxxgu** [comment]
CFLAGS= -fPIC -I$standalone_toolchain/include/c++/4.9.x
CXXFLAGS= -fPIC -I$standalone_toolchain/include/c++/4.9.x 

and /mnt/c/Android/arm_19_toolchain15/include/c++/4.9.x/stddef.h exists

**Comment by solvingj** [comment]
so sorry for the delay, there was some issue with github notifications.

**Comment by SSE4** [comment]
hi @alexxxgu 
from your build log, it seems like actually boost config fails to build.
could you possibly share your profile?

**Comment by alexxxgu** [comment]
Hi, it just an Android profile from Conan article:
`standalone_toolchain=/mnt/c/Android/arm_21_toolchain16
target_host=arm-linux-androideabi
cc_compiler=clang
cxx_compiler=clang++

[settings]
compiler=clang
compiler.version=5.0
compiler.libcxx=libc++
os=Android
os.api_level=21
arch=armv7
build_type=Debug

[env]
CONAN_CMAKE_FIND_ROOT_PATH=$standalone_toolchain/sysroot
PATH=[$standalone_toolchain/bin]
CHOST=$target_host
AR=$target_host-ar
AS=$target_host-as
RANLIB=$target_host-ranlib
CC=$target_host-$cc_compiler
CXX=$target_host-$cxx_compiler
LD=$target_host-ld
STRIP=$target_host-strip
CFLAGS= -fPIE -fPIC -DNONCLFLAG -I$standalone_toolchain/include/c++/4.9.x
CXXFLAGS= -fPIE -fPIC -DNONCXXFLAG -I$standalone_toolchain/include/c++/4.9.x
LDFLAGS= -pie`

**Comment by SSE4** [comment]
I am back on this one. it seems to be the problem that custom CFLAGS/CXXFLAGS/LDFLAGS are not applied for boost, I'll fix it soon.

**Comment by SSE4** [comment]
@alexxxgu despite of opened issues against conan and cpprestsdk, latest recipe builds fine for Android in my case. please check on your side.
