### ISSUE TITLE
Inclusion request harfbuzz/1.7.6@bincrafters/stable

### ISSUE THREAD

**Issue by pvicente** [bincrafters/community#194]
## Inclusion Request Review

This is a review for [harfbuzz/1.7.6@bincrafters/stable (bincrafters/public-conan)](https://github.com/bincrafters/conan-harfbuzz) inclusion request to conan-center.
This review follows the [inclusion guidelines or third party libraries](http://docs.conan.io/en/latest/uploading_packages/bintray/conan_center_guide.html#inclusion-guidelines-for-third-party-libraries).

### Package
harfbuzz/1.7.6@bincrafters/stable

### Checks and Comments
The following options are not working:

- ```harfbuzz :with_icu=True```
- ```harfbuzz:with_glib=True```
- ```harfbuzz:with_graphite2=True```

It's better to remove them until external libraries are supported. 

The same applies to ```harfbuzz:with_freetype``` but I know that @uilianries is working on it so
this inclusion request will be hold until freetype is added.

#### Recipe quality
- [x] Git public repository
- [x] Recipe fields
- [x] Linter
- [ ] Updated
- [ ] Clean
- [x] test_package
- [ ] Raise errors on invalid configurations
- [x] LICENSE of the recipe
- [x] LICENSE of the library

#### CI Integration
- [ ] Provide at least one CI configuration (header only)
- [x] (If not header only) CI configurations for Linux/MacOSX/Windows

#### Bintray Package Information
- [x] Description
- [x] Licenses
- [x] Tags
- [x] Maturity
- [x] Website (if any)
- [x] Issue tracker
- [x] Version control

### Additional comments

![screenshot 2018-03-23 13 26 10](https://user-images.githubusercontent.com/471109/37831543-d38ec810-2e9d-11e8-96fd-5736c1618da2.png)

**Comment by uilianries** [comment]
I just created a new MR: https://github.com/bincrafters/conan-harfbuzz/pull/3

**Comment by solvingj** [comment]
merged, great work.

**Comment by pvicente** [comment]
Hi @uilianries @solvingj 

Please remove  outdated binaries:

 ```conan remove harfbuzz/1.7.6@bincrafters/stable --outdated -r bincrafters``` 

![screenshot 2018-03-26 10 47 52](https://user-images.githubusercontent.com/471109/37899403-59cd1c0a-30e3-11e8-8a2e-c7af689c9caf.png)

After that everything should be ready for the inclusion but [conan-freetype](https://github.com/bincrafters/conan-freetype) needs to be included first (optional dependency of harfbuzz).

**Comment by solvingj** [comment]
I removed the outdated recipes but it looks like we're a bit stuck on freetype currently:
https://github.com/bincrafters/community/issues/190#issuecomment-376709898

**Comment by uilianries** [comment]
Thanks! I'll revisit freetype on holiday.

**Comment by uilianries** [comment]
@lasote @memsharded Freetype is present now on Conan center. Harfbuzz could be the next.

**Comment by lasote** [comment]
@danimtb could you manage?

**Comment by danimtb** [comment]
yes, I am on it! Thanks for the reminder @uilianries @lasote

**Comment by danimtb** [comment]
Hi guys!

Seems Linux and Mac packages are outdated from reacipe in ``harfbuzz/1.7.6@bincrafters/stable``. Please retrigger builds when possible.

I have seen recipes for versions 1.7.1 and 1.7.2 are way different from that latest version. Should the recipe be updated or just delete those versions?

Those old versions are using your [ragel_installer ](https://github.com/bincrafters/conan-ragel_installer), why 1.7.6 is not using it?

**Comment by danimtb** [comment]
@uilianries thanks for the quick response. Ragel installer worked fine in my Windows machine, maybe with just a bit of work it would made to conan-center. But it is ok as it is for now.

Thanks!

**Comment by uilianries** [comment]
Okay, I'll work on ragel after to finish Harfbuzz. I could open an issue as enhancement for Harfbuzz include ragel_installer in the future.

**Comment by danimtb** [comment]
Harfbuzz in conan-center! Thanks a lot guys 👍

Please @uilianries fill the enhancement issue for ragel and feel free to close this one 😄

**Comment by uilianries** [comment]
1.7.6 is updated:

https://travis-ci.org/bincrafters/conan-harfbuzz/builds/374480060
https://ci.appveyor.com/project/BinCrafters/conan-harfbuzz/build/1.0.71

![](https://screenshotscdn.firefoxusercontent.com/images/2e40143a-3a92-42f3-9bd8-8408feea9f19.png)

I'll update 1.7.1 and 1.7.2 later.

**Comment by SSE4** [comment]
closing as package was accepted into conan centre
