### ISSUE TITLE
lzma fails to build on Raspbian

### ISSUE THREAD

**Issue by obiltschnig** [bincrafters/community#197]
### Description of Problem, Request, or Question

```
XZ Utils 5.2.3

System type:
checking build system type... Invalid configuration `None-linux-gnu': machine `None' not recognized
configure: error: /bin/bash build-aux/config.sub None-linux-gnu failed
lzma/5.2.3@bincrafters/stable: 
lzma/5.2.3@bincrafters/stable: ERROR: Package 'ac873a00fd3cd4fa2dbdb9efe7d318532afae973' build failed
lzma/5.2.3@bincrafters/stable: WARN: Build folder /home/pi/.conan/data/lzma/5.2.3/bincrafters/stable/build/ac873a00fd3cd4fa2dbdb9efe7d318532afae973
ERROR: lzma/5.2.3@bincrafters/stable: Error in build() method, line 95
	self.build_configure()
while calling 'build_configure', line 82
	env_build.configure(args=args)
	ConanException: Error 256 while executing ./configure '--disable-xz' '--disable-xzdec' '--disable-lzmadec' '--disable-lzmainfo' '--disable-scripts' '--disable-doc' '--prefix=/home/pi/.conan/data/lzma/5.2.3/bincrafters/stable/package/ac873a00fd3cd4fa2dbdb9efe7d318532afae973' '--with-pic' '--enable-static' '--disable-shared' --build=None-linux-gnu --host=arm-linux-gnueabi
```

### Package Details (Include if Applicable)
* Package Name/Version: lzma/5.2.3
* Operating System: Raspbian/Debian Stretch 9.4
* Compiler+version: gcc (Raspbian 6.3.0-18+rpi1+deb9u1) 6.3.0 20170516
* Docker image: n/a

### Steps to reproduce (Include if Applicable)

Install the following bincrafters boost packages on Raspbian via following `conanfile.txt`:
```
[requires]
 boost_beast/1.66.0@bincrafters/stable
 boost_property_tree/1.66.0@bincrafters/stable

 [generators]
 cmake
```

**Comment by uilianries** [comment]
@obiltschnig Did you try cross-building or just running over ARM?

**Comment by obiltschnig** [comment]
No cross-building, running Conan directly on my Raspberry Pi.

**Comment by uilianries** [comment]
I'll check this issue soon. Thanks for report.

**Comment by solvingj** [comment]
@obiltschnig interesting use case. We have an open opportunity with the worksonarm project to add an additional CI configuration and run arm builds. We didn’t foresee enough value to justify the massive complexity since most developer workflows for arm seem to involve cross-building (so far). That story might change soon as ARM is grown and changing rapidly, but not there yet. .  Are you finding many advantages to doing the development work right on the box, or is it more of a hobby / cornercase situation?

**Comment by obiltschnig** [comment]
That specific use case is for an article I wrote about IoT programming with C++, where I'm introducing different libraries that may be relevant (Boost.Beast, Poco, Paho, libmraa/upm) with small examples that should work on the Rasperry Pi. I've also decided to use Conan to manage the dependencies. Unfortunately, Boost fails to install due to above issue. Hopefully this can be fixed before the article comes out in a few weeks. It would also be nice to have pre-built Conan packages for Raspbian. Compiling these takes a long time and it would make Conan really shine if it could provide binaries of up-to-date library versions, as opposed to Debian packages, which can be quite outdated.

Anything professional would probably involve cross compiling (and probably not a Pi to start with), but cross-compiling for the Pi (and also, e.g., the BeagleBone) can be a challenge in itself, getting the correct toolchain that matches the runtime libs on the target. A big advantage of using a Pi for prototyping is that you have a standard Linux development environment, although a rather slow one, and don't have to deal with cross-compiling and remote debugging and all that pain that still goes along with it.

**Comment by uilianries** [comment]
@obiltschnig The fix is done. Please, update your copy and try again.

My raspberry pi is running some stuff, so I used my Orangepi, but I was able to reproduce your error.

**Comment by obiltschnig** [comment]
Awesome, thanks - it works.

**Comment by uilianries** [comment]
I'm closing this issue now. 

If you find any other problem related, please re-open it.

Regards!

**Comment by solvingj** [comment]
Thanks for the feedback. Thanks @uilianries for tackling.
