### ISSUE TITLE
Proposal : conan-pugixml

### ISSUE THREAD

**Issue by AlexandrePTJ** [bincrafters/community#198]
Hi,

I just created recipes for pugixml library.
It can be found here: https://github.com/AlexandrePTJ/conan-pugixml

Thanks for any feedback.

**Comment by uilianries** [comment]
I'm updating some points to create a MR.

**Comment by uilianries** [comment]
Created https://github.com/AlexandrePTJ/conan-pugixml/pull/1

**Comment by uilianries** [comment]
Almost done:

https://github.com/bincrafters/conan-pugixml

Any review will be welcome!

**Comment by uilianries** [comment]
Done!

https://github.com/bincrafters/conan-pugixml
https://bintray.com/bincrafters/public-conan/pugixml%3Abincrafters
https://ci.appveyor.com/project/BinCrafters/conan-pugixml
https://travis-ci.org/bincrafters/conan-pugixml
