### ISSUE TITLE
boost_iostreams test_package failure

### ISSUE THREAD

**Issue by Floofy-KH** [bincrafters/community#199]
The test_package for boost::iostreams is currently failing for me in Windows due to unresolved external symbols when using the zlib, bzip2 and/or lzma compression filters. 

* Package Name/Version: boost_iostreams/1.66.0
* Operating System: Windows 10
* Compiler+version: Visual Studio 2017

Runnning _conan create_ or _build.py_ causes the error while building the test package. I've noticed that you are getting the same errors in appveyor for Windows. I can currently get around the error by disabling all of the compression filters in the conanfile.py file, but not without making some more changes in the test_package. I've attached a patch with the changes that were required, as I cannot create a PR at the moment. I hope that's helpful.

It doesn't solve the main problem, however, and the test package will still fail on Windows when using the compression filters. Reading through the iostreams build documentation it mentions needing to create a .jam file to point Boost.Build to the libraries, but I couldn't find that being done anywhere in the package recipes, and wasn't sure where to start. 

[iostreams.zip](https://github.com/bincrafters/community/files/1855239/iostreams.zip)

**Comment by solvingj** [comment]
I see the error, and will assign this issue for further review. We generate the jam files for all the boost libraries from the `boost_generator` package, that's why you don't see it in the recipe itself.

**Comment by SSE4** [comment]
@Floofy-KH changes are in testing/1.66.0 branch, please give another try

**Comment by Floofy-KH** [comment]
Thanks @SSE4 
Working as expected.
