### ISSUE TITLE
Use issue template to solve package name

### ISSUE THREAD

**Issue by uilianries** [bincrafters/community#2]
Hi!

When a new one creates an issue, would be nice to get some information to guide what it needs.

I'm thinking some like Catch: https://github.com/catchorg/Catch2/issues/new
Also, we can include the package name as required

Github supports templates for issue and PR:
https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by solvingj** [comment]
Another great idea !

**Comment by uilianries** [comment]
Done!
