### ISSUE TITLE
Create template branch for tools installers and build_requires

### ISSUE THREAD

**Issue by solvingj** [bincrafters/community#20]
Model after `msys_installer`.

At least one customization for this template will be in `.travis.yml` as shown below, no need to download a docker image upon build: 
```
matrix:
   include:
      - <<: *linux
      - <<: *osx

**Comment by solvingj** [comment]
Need someone to validate the following: 

With the matrix above, we got this error on linux/travis: 
https://travis-ci.org/bincrafters/conan-gyp_installer/jobs/313141383#L750

@sigmoidal pointed out a workaround which was to add this: 
`git config --global http.sslVerify false`

@SSE4 went on to workaround the problem a different way: 
https://github.com/bincrafters/conan-gyp_installer/commit/3132a29c0b8b6b504a384116163f6cc6f9865f03

I wondered why we never had this problem with `git clone` before, and never seen it in any recipe's in the past.  I believe it's because 99% of Linux installs people use have this package already.  When using Travis, we almost always use docker containers from Conan team (which is unnecessary and wasteful of bandwidth, time, on Travis for build tools).  

@SSE4's workaround seems to be the most robust solution, but it's unpleasant to put a `system_requires` for something so primitive in `conanfile.py` just because of Travis.  It brings up a larger point:  in theory, there are a vast number of system packages for Linux which we are "system_requirements" but that we take for granted and don't specify.  

An alternative would be add the `apt-get` installation of the CA Certs package to the `.travis.yml` file and keep it out of the `conanfile.py`.  However, that's not great either.  Both are deviations from the norm, I just wanted to point it out for posterity and get others thoughts.  My guess is we'll keep this as-is and include it in the future template for `build_requires` which use GIT to obtain sources.  Perhaps the other note is that it's very rare for a `build_requires` to use GIT to download.  Maybe the best fix is ultimately to do away with that somehow.

**Comment by dimi309** [comment]
This may sound like cheating but what if we tried a direct download and not git clone here? I have been avoiding the use of git in my conanfiles, because it can cause a couple of issues, for example someone not having git in their path, which is the case on my machine. The reason you might not have git in your path would be that your preferred version is git-scm which in effect runs on its own MinGW 64, using msys and, if detected during a mingw build, it can make it crash because of a conflict with the proper mingw installation or because of the detection of msys during a cmake -G"MinGW makefiles" configuration.

**Comment by solvingj** [comment]
I was able to remove the `system_requirement()` on package `ca-certificates` by changing the `source` method from this: 
`self.run('git clone --depth 1 https://github.com/SSE4/gyp')`
to this
`tools.get("https://github.com/SSE4/gyp/archive/master.zip")`

It's surprising because it still uses `https` which I thought would still require the `ca-certificates` package that Travis doesn't seem to have. Clearly, it does not.

**Comment by dimi309** [comment]
Well, at least the build seems to run ok now.

**Comment by SSE4** [comment]
is there python git module that doesn't require git executable available?
for GitHub we can download archives instead of cloning repository, but not for other repositories.

**Comment by solvingj** [comment]
Valid question, there might be one based on a wrapper for `libgit` (a native library).  I used libgit2sharp wrapper for libgit. 

To be honest though, I'm not worried about it at all.  I've only seen a few recipes we were using GIT for.  Out of those very few, all of them were on Github.  It will be very rare that we'll have a situation where we need to use GIT, AND the provider happens to not be github, and also doesn't have an HTTPs-like interface (bitbucket does). We can solve that problem when it arises.
