### ISSUE TITLE
Error while install conan-boost_bind package under msys2

### ISSUE THREAD

**Issue by ClausKlein** [bincrafters/community#205]
### Description of Problem, Request, or Question
/bin/sh: bootstrap: command not found

### Package Details (Include if Applicable)
* Package Name/Version: **boost_bind/1.66.0**
* Operating System: **MSYS_NT-6.1 WD002402 2.10.0(0.325/5/3) 2018-02-09 15:25 x86_64 Msys**
* Compiler+version: **gcc (GCC) 6.4.0**
* Docker image: **none**

### Steps to reproduce (Include if Applicable)
klein_cl@WD002402 MSYS ~/workspace/cpp/conan-boost_bind
$ !conan
conan create . clausklein/channel --build=missing
msys

boost_bind/1.66.0@clausklein/channel: Exporting package recipe
boost_bind/1.66.0@clausklein/channel: The stored package has not changed
boost_bind/1.66.0@clausklein/channel (test package): Installing /home/klein_cl/workspace/cpp/conan-boost_bind/test_package/conanfile.py
Requirements
    boost_assert/1.66.0@bincrafters/stable from 'bincrafters'
    boost_bind/1.66.0@clausklein/channel from local cache
    boost_config/1.66.0@bincrafters/stable from 'bincrafters'
    boost_core/1.66.0@bincrafters/stable from 'bincrafters'
    boost_package_tools/1.66.0@bincrafters/stable from 'bincrafters'
Packages
    boost_assert/1.66.0@bincrafters/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
    boost_bind/1.66.0@clausklein/channel:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
    boost_config/1.66.0@bincrafters/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
    boost_core/1.66.0@bincrafters/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
    boost_package_tools/1.66.0@bincrafters/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9

boost_package_tools/1.66.0@bincrafters/stable: Already installed!
boost_config/1.66.0@bincrafters/stable: Already installed!
boost_assert/1.66.0@bincrafters/stable: Already installed!
boost_core/1.66.0@bincrafters/stable: Already installed!
boost_bind/1.66.0@clausklein/channel: Installing build requirements of: boost_bind/1.66.0@clausklein/channel
boost_bind/1.66.0@clausklein/channel: Build requires: [boost_generator/1.66.0@bincrafters/stable]
boost_bind/1.66.0@clausklein/channel: Requirements
boost_bind/1.66.0@clausklein/channel:     boost_build/1.66.0@bincrafters/stable from 'bincrafters'
boost_bind/1.66.0@clausklein/channel:     boost_generator/1.66.0@bincrafters/stable from 'bincrafters'
boost_bind/1.66.0@clausklein/channel: Packages
boost_bind/1.66.0@clausklein/channel:     boost_build/1.66.0@bincrafters/stable:3b91f3b23c08201caa85611262cd93a235370ed7
boost_bind/1.66.0@clausklein/channel:     boost_generator/1.66.0@bincrafters/stable:6ec6439c54a97da1cfddff786d1ea15988300369
boost_bind/1.66.0@clausklein/channel:
boost_build/1.66.0@bincrafters/stable: Building your package in /home/klein_cl/.conan/data/boost_build/1.66.0/bincrafters/stable/build/3b91f3b23c08201caa85611262cd93a235370ed7
boost_build/1.66.0@bincrafters/stable: Copying sources to build folder
boost_build/1.66.0@bincrafters/stable: Generator txt created conanbuildinfo.txt
boost_build/1.66.0@bincrafters/stable: Calling build()

----Running------
> bootstrap
-----------------
Logging command output to file '/home/klein_cl/.conan/data/boost_build/1.66.0/bincrafters/stable/build/3b91f3b23c08201caa85611262cd93a235370ed7/build/conan_run.log'
/bin/sh: bootstrap: command not found

----Running------
> type bootstrap.log
-----------------
Logging command output to file '/home/klein_cl/.conan/data/boost_build/1.66.0/bincrafters/stable/build/3b91f3b23c08201caa85611262cd93a235370ed7/build/conan_run.log'
/bin/sh: line 0: type: bootstrap.log: not found
boost_build/1.66.0@bincrafters/stable:
boost_build/1.66.0@bincrafters/stable: ERROR: Package '3b91f3b23c08201caa85611262cd93a235370ed7' build failed
boost_build/1.66.0@bincrafters/stable: WARN: Build folder /home/klein_cl/.conan/data/boost_build/1.66.0/bincrafters/stable/build/3b91f3b23c08201caa85611262cd93a235370ed7
ERROR: boost_build/1.66.0@bincrafters/stable: Error in build() method, line 45
        self.run("{0} bootstrap.log".format(read_cmd))
        ConanException: Error 1 while executing type bootstrap.log

klein_cl@WD002402 MSYS ~/workspace/cpp/conan-boost_bind
$

**Comment by solvingj** [comment]
Thanks also for this ticket @ClausKlein .  

As mentioned in another similar issue here: 
https://github.com/bincrafters/community/issues/210#issuecomment-378790446

It's unclear to what degree exististing packages will support MSYS out of the box.  It's a bit unfortunate, but with three competing subsystems and substantial differences and complexities between them, i think the limit of our support will be to make the subsystem installers available . 

Let us know if you have any further thoughts.

**Comment by ClausKlein** [comment]
There are a fundamental problems with msys2
====================================

There exists 3 subsystems and most people don't know the differences:

1.  **msys** (POSIX API)
2. mingw32 (Windows API)
3. mingw64 (Windows API)

see https://github.com/msys2/msys2/wiki/How-does-MSYS2-differ-from-Cygwin

The most problems I found are based on the fault, people think mys is a Windows subsystem.
-----------------------------------------------------------------------------------------------

If you want to execute `bootstrap.sh` you have to use the extension, that's all.

We use **msys** to cross compile for our embedded system.
And we use the **msys** clang++ to check the code for portability.
We use too _clang-format_, _clang-tidy_, _cppcheck_, and other GNU tools under **msys**.
We liked to work on a **bash** and can use most GNU tools without problems.
We prevent to use windows tools and drive letters and use never `"c:\\some strange path\\.."`

**We do not build any windows programs under mingw!**

We use msys2 shell only (never mingw!)  with this conan profile:
-------------------------------------------------------------------

`klein@MSYS ~/.conan/profiles
$ cat msys2
[build_requires]
#NO! mingw_installer/1.0@conan/stable
#NO! msys2_installer/latest@bincrafters/stable

[settings]
os_build=Windows
os=Windows
os.subsystem=msys2
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=6.4
compiler.exception=seh
compiler.libcxx=libstdc++
compiler.threads=posix
build_type=Release

[options]
    *:cxx_14=True
    *:shared=False
    *:header_only=True

    ###FIXME --build=zlib failed! CK
    # OpenSSL:no_zlib=True
    # Poco:enable_zip=False
    # Poco:enable_crypto=False
    # Poco:enable_netssl=False
    # Poco:enable_netssl_win=False
    # asio:force_openssl=False

[env]
CC=/usr/bin/gcc
CXX=/usr/bin/g++
CXXFLAGS=-std=c++14

CONAN_RUN_TESTS=True
CONAN_CMAKE_SYSTEM_NAME="MSYS"
CONAN_CMAKE_SYSTEM_VERSION="2.10.0(0.325/5/3)"
CONAN_CMAKE_GENERATOR=Ninja
CMAKE_LEGACY_CYGWIN_WIN32=0
CONAN_BASH_PATH=/usr/bin/bash
`

**Comment by ClausKlein** [comment]
**The information found here is not not clear and does not help!**

http://docs.conan.io/en/latest/systems_cross_building/windows_subsystems.html?highlight=msys2

**Comment by SSE4** [comment]
@ClausKlein changes were applied to the testing/1.66.0 branch, could you possibly give another try and lemme know?

**Comment by ClausKlein** [comment]
Hi, now it works fine:

boost_build/1.67.0@bincrafters/testing: Package '3b91f3b23c08201caa85611262cd93a235370ed7' created
boost_build/1.67.0@bincrafters/testing (test package): Generator txt created conanbuildinfo.txt
boost_build/1.67.0@bincrafters/testing (test package): Generated conaninfo.txt
boost_build/1.67.0@bincrafters/testing (test package): Running build()
boost_build/1.67.0@bincrafters/testing (test package): WARN: This conanfile has no build step
boost_build/1.67.0@bincrafters/testing (test package): Running test()

----Running------
> b2 --debug-configuration
-----------------
Logging command output to file '/home/klein_cl/workspace/cpp/conan-boost_build/test_package/build/78fcbcbc5121dcda6df852ac4d9089ba8d5594e0/conan_run.log'
notice: found boost-build.jam at /home/klein_cl/.conan/data/boost_build/1.67.0/bincrafters/testing/package/3b91f3b23c08201caa85611262cd93a235370ed7/share/boost-build/src/kernel/boost-build.jam
notice: loading Boost.Build from /home/klein_cl/.conan/data/boost_build/1.67.0/bincrafters/testing/package/3b91f3b23c08201caa85611262cd93a235370ed7/share/boost-build/src/kernel
/home/klein_cl/.conan/data/boost_build/1.67.0/bincrafters/testing/package/3b91f3b23c08201caa85611262cd93a235370ed7/share/boost-build/src/util/os.jam:50: Unescaped special character in argument ([^.]*)$
/home/klein_cl/.conan/data/boost_build/1.67.0/bincrafters/testing/package/3b91f3b23c08201caa85611262cd93a235370ed7/share/boost-build/src/util/os.jam:204: Unescaped special character in argument os:
/home/klein_cl/.conan/data/boost_build/1.67.0/bincrafters/testing/package/3b91f3b23c08201caa85611262cd93a235370ed7/share/boost-build/src/util/os.jam:205: Unescaped special character in argument os:
notice: Searching '/home/klein_cl' '/home/klein_cl/.conan/data/boost_build/1.67.0/bincrafters/testing/package/3b91f3b23c08201caa85611262cd93a235370ed7/share/boost-build/src/kernel/.' '/home/klein_cl/.conan/data/boost_build/1.67.0/bincrafters/testing/package/3b91f3b23c08201caa85611262cd93a235370ed7/share/boost-build/src/kernel' '/home/klein_cl/.conan/data/boost_build/1.67.0/bincrafters/testing/package/3b91f3b23c08201caa85611262cd93a235370ed7/share/boost-build/src/kernel' '/home/klein_cl/.conan/data/boost_build/1.67.0/bincrafters/testing/package/3b91f3b23c08201caa85611262cd93a235370ed7/share/boost-build/src/util' '/home/klein_cl/.conan/data/boost_build/1.67.0/bincrafters/testing/package/3b91f3b23c08201caa85611262cd93a235370ed7/share/boost-build/src/build' '/home/klein_cl/.conan/data/boost_build/1.67.0/bincrafters/testing/package/3b91f3b23c08201caa85611262cd93a235370ed7/share/boost-build/src/tools' '/home/klein_cl/.conan/data/boost_build/1.67.0/bincrafters/testing/package/3b91f3b23c08201caa85611262cd93a235370ed7/share/boost-build/src/contrib' '/home/klein_cl/.conan/data/boost_build/1.67.0/bincrafters/testing/package/3b91f3b23c08201caa85611262cd93a235370ed7/share/boost-build/src/.' for site-config configuration file 'site-config.jam'.
notice: Configuration file 'site-config.jam' not found in '/home/klein_cl' '/home/klein_cl/.conan/data/boost_build/1.67.0/bincrafters/testing/package/3b91f3b23c08201caa85611262cd93a235370ed7/share/boost-build/src/kernel/.' '/home/klein_cl/.conan/data/boost_build/1.67.0/bincrafters/testing/package/3b91f3b23c08201caa85611262cd93a235370ed7/share/boost-build/src/kernel' '/home/klein_cl/.conan/data/boost_build/1.67.0/bincrafters/testing/package/3b91f3b23c08201caa85611262cd93a235370ed7/share/boost-build/src/kernel' '/home/klein_cl/.conan/data/boost_build/1.67.0/bincrafters/testing/package/3b91f3b23c08201caa85611262cd93a235370ed7/share/boost-build/src/util' '/home/klein_cl/.conan/data/boost_build/1.67.0/bincrafters/testing/package/3b91f3b23c08201caa85611262cd93a235370ed7/share/boost-build/src/build' '/home/klein_cl/.conan/data/boost_build/1.67.0/bincrafters/testing/package/3b91f3b23c08201caa85611262cd93a235370ed7/share/boost-build/src/tools' '/home/klein_cl/.conan/data/boost_build/1.67.0/bincrafters/testing/package/3b91f3b23c08201caa85611262cd93a235370ed7/share/boost-build/src/contrib' '/home/klein_cl/.conan/data/boost_build/1.67.0/bincrafters/testing/package/3b91f3b23c08201caa85611262cd93a235370ed7/share/boost-build/src/.'.
notice: Searching '/home/klein_cl' '/home/klein_cl/.conan/data/boost_build/1.67.0/bincrafters/testing/package/3b91f3b23c08201caa85611262cd93a235370ed7/share/boost-build/src/kernel/.' '/home/klein_cl/.conan/data/boost_build/1.67.0/bincrafters/testing/package/3b91f3b23c08201caa85611262cd93a235370ed7/share/boost-build/src/kernel' '/home/klein_cl/.conan/data/boost_build/1.67.0/bincrafters/testing/package/3b91f3b23c08201caa85611262cd93a235370ed7/share/boost-build/src/kernel' '/home/klein_cl/.conan/data/boost_build/1.67.0/bincrafters/testing/package/3b91f3b23c08201caa85611262cd93a235370ed7/share/boost-build/src/util' '/home/klein_cl/.conan/data/boost_build/1.67.0/bincrafters/testing/package/3b91f3b23c08201caa85611262cd93a235370ed7/share/boost-build/src/build' '/home/klein_cl/.conan/data/boost_build/1.67.0/bincrafters/testing/package/3b91f3b23c08201caa85611262cd93a235370ed7/share/boost-build/src/tools' '/home/klein_cl/.conan/data/boost_build/1.67.0/bincrafters/testing/package/3b91f3b23c08201caa85611262cd93a235370ed7/share/boost-build/src/contrib' '/home/klein_cl/.conan/data/boost_build/1.67.0/bincrafters/testing/package/3b91f3b23c08201caa85611262cd93a235370ed7/share/boost-build/src/.' for user-config configuration file 'user-config.jam'.
notice: Configuration file 'user-config.jam' not found in '/home/klein_cl' '/home/klein_cl/.conan/data/boost_build/1.67.0/bincrafters/testing/package/3b91f3b23c08201caa85611262cd93a235370ed7/share/boost-build/src/kernel/.' '/home/klein_cl/.conan/data/boost_build/1.67.0/bincrafters/testing/package/3b91f3b23c08201caa85611262cd93a235370ed7/share/boost-build/src/kernel' '/home/klein_cl/.conan/data/boost_build/1.67.0/bincrafters/testing/package/3b91f3b23c08201caa85611262cd93a235370ed7/share/boost-build/src/kernel' '/home/klein_cl/.conan/data/boost_build/1.67.0/bincrafters/testing/package/3b91f3b23c08201caa85611262cd93a235370ed7/share/boost-build/src/util' '/home/klein_cl/.conan/data/boost_build/1.67.0/bincrafters/testing/package/3b91f3b23c08201caa85611262cd93a235370ed7/share/boost-build/src/build' '/home/klein_cl/.conan/data/boost_build/1.67.0/bincrafters/testing/package/3b91f3b23c08201caa85611262cd93a235370ed7/share/boost-build/src/tools' '/home/klein_cl/.conan/data/boost_build/1.67.0/bincrafters/testing/package/3b91f3b23c08201caa85611262cd93a235370ed7/share/boost-build/src/contrib' '/home/klein_cl/.conan/data/boost_build/1.67.0/bincrafters/testing/package/3b91f3b23c08201caa85611262cd93a235370ed7/share/boost-build/src/.'.
jamroot.jam:1: Unescaped special character in argument info:
info: Success loading project jamroot.jam file.
warning: No toolsets are configured.
warning: Configuring default toolset "gcc".
warning: If the default is wrong, your build may not work correctly.
warning: Use the "toolset=xxxxx" option to override our guess.
warning: For more configuration options, please consult
warning: http://boost.org/boost-build2/doc/html/bbv2/advanced/configuration.html
notice: will use 'g++' for gcc, condition <toolset>gcc-6.4.0
notice: using gcc libraries :: <toolset>gcc-6.4.0 :: /usr/bin /usr/lib /usr/lib32 /usr/lib64
notice: using gcc archiver :: <toolset>gcc-6.4.0 :: /usr/x86_64-pc-msys/bin/ar.exe
notice: using gcc ranlib :: <toolset>gcc-6.4.0 :: /usr/x86_64-pc-msys/bin/ranlib.exe
notice: using rc compiler :: <toolset>gcc-6.4.0 :: /usr/bin/windres
...found 1 target...

klein_cl@WD002402 MSYS ~/workspace/cpp/conan-boost_build
$

**Comment by SSE4** [comment]
thanks for the confirmation, closing
