### ISSUE TITLE
Passing the GLEW package over to bincrafters

### ISSUE THREAD

**Issue by dimi309** [bincrafters/community#206]
### Description of Problem, Request, or Question

Hi everyone,

As discussed (see https://github.com/bincrafters/community/issues/204) I have finished packaging glew, according to bincrafters standards. The package is here:

https://github.com/bincrafters/conan-glew

I have set up CI with [my own fork](https://github.com/dimi309/conan-glew) and it works well:

https://ci.appveyor.com/project/coding3d/conan-glew
https://travis-ci.org/dimi309/conan-glew

The only problem I have not been able to solve is that, on travis, the linux x86 build doesn't work on the 64 bit VM because cmake can't find opengl, even though I set the 32 bit version up together with multilib. But this only concerns on-travis cross-building x86 binaries on a 64 bit VM. Locally everything works fine. So please set up the travis build with an env variable CONAN_ARCHS=x86_64.

### Package Details (Include if Applicable)
* Package Name/Version: **glew/2.0.1**
* Operating System: **Windows / MacOS / Linux**
* Compiler+version: **all**
* Docker image: **all supported by bincrafters**

**Comment by solvingj** [comment]
Turned on the CI, having a little download trouble with sourceforge which you did not seem to have.  The log says `Not Found` (assume 404), but when i browse to the link it downloads.  Very confused.

**Comment by dimi309** [comment]
That happens sometimes. I would just restart the build. Sourceforge is a little temperamental.

**Comment by SSE4** [comment]
packages are available, closing

**Comment by dimi309** [comment]
Thanks!
