### ISSUE TITLE
libcurl apple-clang 9.1

### ISSUE THREAD

**Issue by lasote** [bincrafters/community#207]
### Package Details (Include if Applicable)
* Package Name/Version: **libcurl/7.56.1**
* Operating System: **OSX**
* Compiler+version: **apple-clang 9.1**

### Steps to reproduce (Include if Applicable)

Clone libcurl and perform a create.

Since I upgraded my xcode to the latest version it is failing to link with OpenSSL (default options specified, so darwin_ssl):

```
Undefined symbols for architecture x86_64:
  "_ASN1_INTEGER_get", referenced from:
      _get_cert_chain in libcurl.a(libcurl_la-openssl.o)
  "_ASN1_STRING_data", referenced from:
      _verifyhost in libcurl.a(libcurl_la-openssl.o)
  "_ASN1_STRING_length", referenced from:
      _verifyhost in libcurl.a(libcurl_la-openssl.o)
  "_ASN1_STRING_print", referenced from:
      _X509V3_ext in libcurl.a(libcurl_la-openssl.o)
  "_ASN1_STRING_to_UTF8", referenced from:
      _verifyhost in libcurl.a(libcurl_la-openssl.o)
  "_ASN1_STRING_type", referenced from:
      _verifyhost in libcurl.a(libcurl_la-openssl.o)
  "_ASN1_TIME_print", referenced from:
      _servercert in libcurl.a(libcurl_la-openssl.o)
      _get_cert_chain in libcurl.a(libcurl_la-openssl.o)
  "_BIO_ctrl", referenced from:
...
```
This is very weird, have you tried? I suspect it can be something bad with my installation, otherwise something changed in the Apple frameworks?

Thanks!

**Comment by theirix** [comment]
Hello! Could you please check two things:
1. update to latest version. I reworked openssl/darwinssl/winssl a week ago. But it should not cause this kind of bug.
2. show the exact configure command by running with `CONAN_PRINT_RUN_COMMANDS=1` or ideally the whole log.

I have 9.0 clang (older xcode) and there is no such problem.

**Comment by theirix** [comment]
Installed 9.1, success:
`> ./configure --without-libidn2 --without-librtmp --without-libmetalink --without-libpsl --without-nghttp2 --with-darwinssl --without-libssh2 --with-zlib=/Users/irix/.conan/data/zlib/1.2.11/conan/stable/package/0eaf3bfbc94fb6d2c8f230d052d75c6c1a57a4ce/lib  --disable-shared --enable-static --disable-ldap --prefix=/Users/irix/.conan/data/libcurl/7.56.1/theirix/testing/package/c524ca20330d4dcedff6342b243b52f8309c04c9`

**Comment by lasote** [comment]
This is weird. I have the latest changes from your repository. Here is my output: https://gist.github.com/lasote/663ff7c1c7a809f7ddc7d48c747cb39d

**Comment by theirix** [comment]
Reproduced, working on the fix.
Reason is that libcurl found openssl.pc and picked up it automatically.

**Comment by theirix** [comment]
Could you please try testing/7.56.1 from github repository?

**Comment by lasote** [comment]
Correct! Many thanks, looking forward to seeing it fixed in conan-center.
