### ISSUE TITLE
Cpprestsdk needs boost even with websockets disabled

### ISSUE THREAD

**Issue by promgamer** [bincrafters/community#211]
### Package Details (Include if Applicable)
* Package Name/Version: **cpprestsdk/2.10.1**
* Operating System: **Linux Ubuntu 16.04** (Apple and Android are also affected)

### Steps to reproduce (Include if Applicable)
The Cpprestsdk needs boost_asio even if you disable websockets (to implement http_client), on APPLE and LINUX devices (check lines [84-100](https://github.com/Microsoft/cpprestsdk/blob/master/Release/CMakeLists.txt#L84).

The current conanfile is only enabling those libraries if [websockets are enabled](https://github.com/bincrafters/conan-cpprestsdk/blob/stable/2.10.1/conanfile.py#L45).

Am I seeing this problem from the wrong perspective? I would think it would make sense to add an extra check to see if it's windows or not. Or, if you want to delegate that to cpprestsdk's CMakeLists, at least enable boost libraries even if websockets are disabled (even though we are requiring people to build boost on a platform that doesn't need it).

I would be happy to contribute with a Pull Request!

**Comment by SSE4** [comment]
@promgamer changes are in testing/2.10.1 branch, please give a try

**Comment by promgamer** [comment]
@SSE4 it's working as intended on Linux! :smile:
