### ISSUE TITLE
Can't compile fmt with a toolchain file

### ISSUE THREAD

**Issue by blastrock** [bincrafters/community#212]
### Description of Problem, Request, or Question

I am trying to cross-compile fmt with a cmake toolchain file but it fails with

```
CMake Error in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.9)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
```

### Package Details
* Package Name/Version: **fmt/4.1.0@bincrafters/stable**
* Operating System: **Linux debian unstable**
* Compiler+version: **gcc-7.2**

### Steps to reproduce

1. Create a cross building profile in `~/.conan/profiles/test`

```ini
[build_requires]
test-toolchain/01@test/test

[settings]
os_build=Linux
arch_build=x86_64
os=Linux
arch=armv7
compiler=gcc
compiler.version=7.2
compiler.libcxx=libstdc++11

[options]
[scopes]
[env]
```

2. Create a toolchain folder with a file named testtoolchain.cmake:

```cmake
cmake_minimum_required( VERSION 2.6.3 )
```

3. And a conanfile.py recipe:

```py
import os

from conans import ConanFile


class TestToolchainConan(ConanFile):
    name = "test-toolchain"
    version = "01"
    settings = "os", "arch"
    exports_sources = "testtoolchain.cmake"

    def package(self):
        self.copy(pattern="*.cmake")

    def package_info(self):
        self.env_info.CONAN_CMAKE_TOOLCHAIN_FILE = os.path.join(self.package_folder, "testtoolchain.cmake")
```

4. Now, in the toolchain folder with the two files, run:

```sh
conan create . test/test -pr test
```

5. And now, try to cross-compile fmt:

```sh
conan install fmt/4.1.0@bincrafters/stable --build fmt -pr test
```

6. It fails with the error above

### Possible source of the issue

I think this is because of the [CMakeLists](https://github.com/bincrafters/conan-fmt/blob/b52f1a45d164112f4e62f7be30a18df1bc38f30f/CMakeLists.txt) you use to wrap the one provided by fmt which doesn't contain a version.

**Comment by uilianries** [comment]
Thanks for report. I'll take look into.

**Comment by uilianries** [comment]
Confirmed, the wrapper needs cmake_minimum_required.

BTW, your issue is well described and detailed.

**Comment by uilianries** [comment]
@blastrock I just pushed a new version, please update.

I was able to reproduce your steps and see your error. After to add cmake minimum version, the error disappeared. Thanks for the solution.

If you find any problem related, please re-open this issue.

Regards!

**Comment by blastrock** [comment]
Thanks for the quick reaction!

I didn't have the time to test the fix yet, however please see my other comment: https://github.com/bincrafters/conan-templates/pull/24#issuecomment-378506865

**Comment by uilianries** [comment]
Right! I'm going to change now

**Comment by blastrock** [comment]
Thanks, it works :)

**Comment by solvingj** [comment]
great work @uilianries , thanks!
