### ISSUE TITLE
Recipe version

### ISSUE THREAD

**Issue by AlexandrePTJ** [bincrafters/community#213]
A recent update on spdlog recipes brokes our build (a default option value changed).
This was easy too fix from our side.

The problem is that we do not have ability to track recipes changes.
Two publications of spdlog 0.16.3 cannot be distinguished.

Package on Archlinux have the semantic : <library version>-<package version>.
This allow to create 0.16.3-1 then 0.16.3-2. Can it be possible with conan or here in any manner ?

**Comment by uilianries** [comment]
Unfortunately not, but Conan knows about it. Even I asked about this feature in the past.

There are a bunch of discussion relating this limitation, but I think 
https://github.com/conan-io/conan/issues/798 is the main issue.

**Comment by solvingj** [comment]
@AlexandrePTJ I consider this a failure on my part approving the PR which changed the default.  once recipe's are accepted into Conan Center, we have a responsibility to avoid breaking changes such as this.  As @uilianries said, there's been a long-term discussion involving a number of people and a number of factors on this topic.  I don't think anyone is satisfied with the current state of things.  It actually applies to all package managers, but currently affects conan more significantly than others.  

Thanks for reporting this, apologies,  I'll be more vigilant about the breaking changes in the future.

**Comment by AlexandrePTJ** [comment]
Don't worry about this. As I read the discussion on conan, I am reassured that the problem is known and part of a real discuss.
Thanks for the feedback !
