### ISSUE TITLE
yaml-cpp using deprecated boost as requirement

### ISSUE THREAD

**Issue by tpilien** [bincrafters/community#215]
### Description of Problem, Request, or Question
The yaml-cpp packge cannot be fully resolved because it still uses the old boost naming convention, which I believe has now been removed.

```
$ conan install ..
yaml-cpp/0.5.3@bincrafters/stable: Not found in local cache, looking in remotes...
yaml-cpp/0.5.3@bincrafters/stable: Trying with 'conan-center'...
yaml-cpp/0.5.3@bincrafters/stable: Trying with 'conan-transit'...
yaml-cpp/0.5.3@bincrafters/stable: Trying with 'bincrafters'...
Downloading conanmanifest.txt
[==================================================] 166B/166B
Downloading conanfile.py
[==================================================] 2.0KB/2.0KB
Downloading conan_export.tgz
[==================================================] 757B/757B
ERROR: The version in '>=1.65.1' from requirement 'Boost.Smart_Ptr/[>=1.65.1]@bincrafters/stable' could not be resolved
```

I have a pull request here which changes it to the new naming convention if that is of interest. https://github.com/bincrafters/conan-yaml-cpp/pull/8

### Package Details (Include if Applicable)
* Package Name/Version: **yaml-cpp/0.5.3@bincrafters/stable**
* Operating System: **Windows 10 64**
* Compiler+version: **Visual Studio 15**
* Docker image: **None**

### Steps to reproduce (Include if Applicable)
Using a simple conanfile.txt
```
[requires]
yaml-cpp/0.5.3@bincrafters/stable

[generators]
cmake
```

Running conan install will result in the above errors.

**Comment by uilianries** [comment]
Thanks for report!

**Comment by uilianries** [comment]
Done! stable is synced now, but we need several minutes until Travis and Appveyor push the packages.

Thanks!
