### ISSUE TITLE
[Freetype] Link error when used from a thirdparty

### ISSUE THREAD

**Issue by lucienboillod** [bincrafters/community#216]
### Description of Problem, Request, or Question
It seems like the dependencies of freetype are not linked when freetype is builded from a thirparty.

### Package Details (Include if Applicable)
* Package Name/Version: **freetype/2.9.0**
* Operating System: **Windows**
* Compiler+version: **Visual Studio 15 2017**

### Steps to reproduce (Include if Applicable)
We are trying to use Freetype as a thirdparty of a project (https://github.com/Tulip-Dev/tulip).
So in our conanfile.py we did put freetype as requirement, but we have errors when building tulip (actually ftgl-tulip):
```
freetype.lib(sfnt.obj) : error LNK2019: symbole externe non résolu png_create_read_struct référencé dans la fonction Load_SBit_Png
```

**Comment by uilianries** [comment]
@lucienboillod What options are you using?

**Comment by lucienboillod** [comment]
@uilianries the defaults ones, with is "with_png=True" for the case of libpng

**Comment by lucienboillod** [comment]
The full log:
```
freetype.lib(sfnt.obj) : error LNK2019: symbole externe non résolu png_create_read_struct référencé dans la fonction Load_SBit_Png
freetype.lib(sfnt.obj) : error LNK2019: symbole externe non résolu png_set_longjmp_fn référencé dans la fonction Load_SBit_Png
freetype.lib(sfnt.obj) : error LNK2019: symbole externe non résolu png_create_info_struct référencé dans la fonction Load_SBit_Png
freetype.lib(sfnt.obj) : error LNK2019: symbole externe non résolu png_read_info référencé dans la fonction Load_SBit_Png
freetype.lib(sfnt.obj) : error LNK2019: symbole externe non résolu png_set_expand_gray_1_2_4_to_8 référencé dans la fonction Load_SBit_Png
freetype.lib(sfnt.obj) : error LNK2019: symbole externe non résolu png_set_palette_to_rgb référencé dans la fonction Load_SBit_Png
freetype.lib(sfnt.obj) : error LNK2019: symbole externe non résolu png_set_tRNS_to_alpha référencé dans la fonction Load_SBit_Png
freetype.lib(sfnt.obj) : error LNK2019: symbole externe non résolu png_set_gray_to_rgb référencé dans la fonction Load_SBit_Png
freetype.lib(sfnt.obj) : error LNK2019: symbole externe non résolu png_set_filler référencé dans la fonction Load_SBit_Png
freetype.lib(sfnt.obj) : error LNK2019: symbole externe non résolu png_set_packing référencé dans la fonction Load_SBit_Png
freetype.lib(sfnt.obj) : error LNK2019: symbole externe non résolu png_set_interlace_handling référencé dans la fonction Load_SBit_Png
freetype.lib(sfnt.obj) : error LNK2019: symbole externe non résolu png_set_strip_16 référencé dans la fonction Load_SBit_Png
freetype.lib(sfnt.obj) : error LNK2019: symbole externe non résolu png_read_update_info référencé dans la fonction Load_SBit_Png
freetype.lib(sfnt.obj) : error LNK2019: symbole externe non résolu png_read_image référencé dans la fonction Load_SBit_Png
freetype.lib(sfnt.obj) : error LNK2019: symbole externe non résolu png_read_end référencé dans la fonction Load_SBit_Png
freetype.lib(sfnt.obj) : error LNK2019: symbole externe non résolu png_destroy_read_struct référencé dans la fonction Load_SBit_Png
freetype.lib(sfnt.obj) : error LNK2019: symbole externe non résolu png_get_error_ptr référencé dans la fonction error_callback
freetype.lib(sfnt.obj) : error LNK2019: symbole externe non résolu png_set_read_fn référencé dans la fonction Load_SBit_Png
freetype.lib(sfnt.obj) : error LNK2019: symbole externe non résolu png_get_io_ptr référencé dans la fonction read_data_from_FT_Stream
freetype.lib(sfnt.obj) : error LNK2019: symbole externe non résolu png_set_read_user_transform_fn référencé dans la fonction Load_SBit_Png
freetype.lib(sfnt.obj) : error LNK2019: symbole externe non résolu png_error référencé dans la fonction read_data_from_FT_Stream
freetype.lib(sfnt.obj) : error LNK2019: symbole externe non résolu png_get_valid référencé dans la fonction Load_SBit_Png
freetype.lib(sfnt.obj) : error LNK2019: symbole externe non résolu png_get_IHDR référencé dans la fonction Load_SBit_Png
freetype.lib(ftgzip.obj) : error LNK2019: symbole externe non résolu inflate référencé dans la fonction FT_Gzip_Uncompress
freetype.lib(ftgzip.obj) : error LNK2019: symbole externe non résolu inflateEnd référencé dans la fonction FT_Gzip_Uncompress
freetype.lib(ftgzip.obj) : error LNK2019: symbole externe non résolu inflateReset référencé dans la fonction ft_gzip_file_io
freetype.lib(ftgzip.obj) : error LNK2019: symbole externe non résolu inflateInit2_ référencé dans la fonction FT_Gzip_Uncompress
freetype.lib(ftbzip2.obj) : error LNK2019: symbole externe non résolu BZ2_bzDecompressInit référencé dans la fonction FT_Stream_OpenBzip2
freetype.lib(ftbzip2.obj) : error LNK2019: symbole externe non résolu BZ2_bzDecompress référencé dans la fonction ft_bzip2_file_fill_output
freetype.lib(ftbzip2.obj) : error LNK2019: symbole externe non résolu BZ2_bzDecompressEnd référencé dans la fonction ft_bzip2_stream_close
C:\Users\lboillod\conan-tulip\build\tulip\thirdparty\ftgl\ftgl-tulip-5_2.dll : fatal error LNK1120: 30 externes non résolus
```

**Comment by uilianries** [comment]
@lucienboillod  Thanks, this should help me find the same point.

**Comment by memsharded** [comment]
I have been having a look, but I cannot make if fail. I'd need some code that uses freetype-png, but I can't find any online, and it is difficult to reproduce with ftgl, because it is not isolated, it has other dependencies (${Tess2Library} ${GLEW_LIBRARY})

Could you please @lucienboillod try to provide some reference (an actual main() would be excellent) of some code using freetype with png support to make it fail? Or maybe detailed instructions how to reproduce while building ftgl. I cannot find a branch with the ongoing work using freetype from the bincrafters repo.

Many thanks!

**Comment by uilianries** [comment]
On Linux there is no problem (just checking)

```
$ conan download -r bincrafters freetype/2.9.0@bincrafters/stable -p ef8748f5cbd093a0afa01a8ba0f18ad519142fe5
$ nm ~/.conan/data/freetype/2.9.0/bincrafters/stable/package/ef8748f5cbd093a0afa01a8ba0f18ad519142fe5/lib/libfreetype.a  | grep png_set
                 U png_set_expand_gray_1_2_4_to_8
                 U png_set_filler
                 U png_set_gray_to_rgb
                 U png_set_interlace_handling
                 U png_set_longjmp_fn
                 U png_set_packing
                 U png_set_palette_to_rgb
                 U png_set_read_fn
                 U png_set_read_user_transform_fn
                 U png_set_strip_16
                 U png_set_tRNS_to_alpha
```
Same result for `shared=True`

**Comment by uilianries** [comment]
On Windows:

I found png symbols when running `dumpbin.exe /ALL C:\Users\Uilian Ries\.conan\data\freetype\2.9.0\bincrafters\stable\package\a618d1d550d4f57511529bcb6ff07c7274b8b29d\lib\freetype.lib`  
And during link stage:
```
 Link:
         C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.13.26128\bin\HostX86\x64\link.exe /ERRORREPORT:QUEUE /OUT:"C:\Users\Uilian Ries\Development\conan\conan-freetype\test_package\build\dd137b11470c12a
         b2cc61188ad6810342e08a8ca\bin\test_package.exe" /INCREMENTAL:NO /NOLOGO /LIBPATH:"C:/Users/Uilian Ries/.conan/data/freetype/2.9.0/bincrafters/testing/package/081e0a59ca5bd1b2b4129dc41eaa1fe62a1e36df/lib" /LIBPATH:"C:/Users/Uili
         an Ries/.conan/data/freetype/2.9.0/bincrafters/testing/package/081e0a59ca5bd1b2b4129dc41eaa1fe62a1e36df/lib/Release" /LIBPATH:"C:/Users/Uilian Ries/.conan/data/bzip2/1.0.6/conan/stable/package/ce1f8ff23addde793223a2a82ed7fe355c
         57a589/lib" /LIBPATH:"C:/Users/Uilian Ries/.conan/data/bzip2/1.0.6/conan/stable/package/ce1f8ff23addde793223a2a82ed7fe355c57a589/lib/Release" /LIBPATH:"C:/Users/Uilian Ries/.conan/data/libpng/1.6.34/bincrafters/stable/package/6
         06fdb601e335c2001bdf31d478826b644747077/lib" /LIBPATH:"C:/Users/Uilian Ries/.conan/data/libpng/1.6.34/bincrafters/stable/package/606fdb601e335c2001bdf31d478826b644747077/lib/Release" /LIBPATH:"C:/Users/Uilian Ries/.conan/data/z
         lib/1.2.11/conan/stable/package/6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7/lib" /LIBPATH:"C:/Users/Uilian Ries/.conan/data/zlib/1.2.11/conan/stable/package/6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7/lib/Release" kernel32.lib user32
         .lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib freetype.lib bz2.lib libpng16.lib zlib.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:"C:/U
         sers/Uilian Ries/Development/conan/conan-freetype/test_package/build/dd137b11470c12ab2cc61188ad6810342e08a8ca/bin/test_package.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/Uilian Ries/Development/co
         nan/conan-freetype/test_package/build/dd137b11470c12ab2cc61188ad6810342e08a8ca/lib/test_package.lib" /MACHINE:X64   /machine:x64 test_package.dir\Release\test_package.obj
            Creating library C:/Users/Uilian Ries/Development/conan/conan-freetype/test_package/build/dd137b11470c12ab2cc61188ad6810342e08a8ca/lib/test_package.lib and object C:/Users/Uilian Ries/Development/conan/conan-freetype/test_pa
         ckage/build/dd137b11470c12ab2cc61188ad6810342e08a8ca/lib/test_package.exp
         test_package.vcxproj -> C:\Users\Uilian Ries\Development\conan\conan-freetype\test_package\build\dd137b11470c12ab2cc61188ad6810342e08a8ca\bin\test_package.exe
```
Yeah, huge, but libpng and bz2 are listed.

Same for `freetype:shared=True`:
```
Link:
         C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.13.26128\bin\HostX86\x64\link.exe /ERRORREPORT:QUEUE /OUT:"C:\Users\Uilian Ries\Development\conan\conan-freetype\test_package\build\bbbd54bbce1ff43
         e1f0e8258eae1fec92c9ec148\bin\test_package.exe" /INCREMENTAL:NO /NOLOGO /LIBPATH:"C:/Users/Uilian Ries/.conan/data/freetype/2.9.0/bincrafters/testing/package/ead1b5a1fd92444812a38e44d77368ec20c3ac24/lib" /LIBPATH:"C:/Users/Uili
         an Ries/.conan/data/freetype/2.9.0/bincrafters/testing/package/ead1b5a1fd92444812a38e44d77368ec20c3ac24/lib/Release" /LIBPATH:"C:/Users/Uilian Ries/.conan/data/bzip2/1.0.6/conan/stable/package/ce1f8ff23addde793223a2a82ed7fe355c
         57a589/lib" /LIBPATH:"C:/Users/Uilian Ries/.conan/data/bzip2/1.0.6/conan/stable/package/ce1f8ff23addde793223a2a82ed7fe355c57a589/lib/Release" /LIBPATH:"C:/Users/Uilian Ries/.conan/data/libpng/1.6.34/bincrafters/stable/package/6
         06fdb601e335c2001bdf31d478826b644747077/lib" /LIBPATH:"C:/Users/Uilian Ries/.conan/data/libpng/1.6.34/bincrafters/stable/package/606fdb601e335c2001bdf31d478826b644747077/lib/Release" /LIBPATH:"C:/Users/Uilian Ries/.conan/data/z
         lib/1.2.11/conan/stable/package/6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7/lib" /LIBPATH:"C:/Users/Uilian Ries/.conan/data/zlib/1.2.11/conan/stable/package/6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7/lib/Release" kernel32.lib user32
         .lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib freetype.lib bz2.lib libpng16.lib zlib.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:"C:/U
         sers/Uilian Ries/Development/conan/conan-freetype/test_package/build/bbbd54bbce1ff43e1f0e8258eae1fec92c9ec148/bin/test_package.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/Uilian Ries/Development/co
         nan/conan-freetype/test_package/build/bbbd54bbce1ff43e1f0e8258eae1fec92c9ec148/lib/test_package.lib" /MACHINE:X64   /machine:x64 test_package.dir\Release\test_package.obj
         test_package.vcxproj -> C:\Users\Uilian Ries\Development\conan\conan-freetype\test_package\build\bbbd54bbce1ff43e1f0e8258eae1fec92c9ec148\bin\test_package.exe
```
However, I didn't find any png symbol in freetype.lib wrapper

The dumpbin logs are here: https://gist.github.com/uilianries/4516495e3e3ae156ee8409e64f344d33

**Comment by memsharded** [comment]
> However, I didn't find any png symbol in freetype.lib wrapper

Seems could be an issue of freetype build system, not the conan package. Such main.cpp to reproduce would be very useful indeed...

**Comment by lucienboillod** [comment]
I just managed to have a reproductible example, but you will need a least Qt5 (you can put the path at the dedicated line in the conanfile).

You should be able to get the link errors by doing:
```
conan source .
mkcd build & conan install .. 
conan build ..
```

https://github.com/lucienboillod/conan-tulip

Please tellme if you need anything,

Many Thanks!

**Comment by uilianries** [comment]
Thanks, I'll check later

**Comment by uilianries** [comment]
A good soul provided Qt5 on Bintray: https://github.com/osechet/conan-qt

I added his recipe as requirement to solve Qt dependency.

**Comment by uilianries** [comment]
I could not build Tulip on Linux. I saved the log in: https://gist.github.com/uilianries/0485bbca5bcd5d995966eaf2f6b55c85

The project is huge and hard to debug, so I created a simply example, using freetype + png:

https://github.com/uilianries/freetype-png-example

It's working on Linux. I'll on Windows soon.

**Comment by uilianries** [comment]
It's working on Windows. I used both options `*:shared=False` and `freetype:shared=False`

Now I'm curious if your project really includes libpng in `target_link_libraries`

**Comment by lucienboillod** [comment]
@uilianries the Qt package provided by Osechet is not up-to-date (years ago) so I cannot use it in the current state.

Yes Freetype with png works correctly when used like that, the problem appears when it is used as a thirdparty it seems to not depth link with libpng. Maybe it is not the job of conan, or there is something I don't understand but, why should I write down libpng in the target link directly of CMake, since it is a dependency of Freetype ? It is not handle already by conan ?

**Comment by memsharded** [comment]
It is handled by conan. When you depend on conan packages, you will get defined the ${CONAN_LIBS} variable with an ordered list of libraries you need to link with, if you are using old-style cmake with global configuration. Or you can use CONAN_PKG::freetype target if using modern cmake style. Conan provides both ways to do so.

But if you have in your CMakeLists.txt:

```cmake
TARGET_LINK_LIBRARIES(${FTGLLibrary} ${OPENGL_gl_LIBRARY} ${FREETYPE_LIBRARY} ${Tess2Library} ${GLEW_LIBRARY})
```

And the ``${FREETYPE_LIBRARY}`` comes from a ``find_package`` that is not managed by conan, there is nothing conan can do. (Btw: conan will never mess with your build system, it declares things to be used, but the consumer needs to explicitly use them). The conan package knows that it has a transitive dependency to libpng, and it will add it to CONAN_LIBS or CONAN_PKG::freetype, but it seems the cmake find_package for freetype is not aware of this transitivity.

Maybe you could try to set ${FREETYPE_LIBRARY} to point to CONAN_PKG::freetype, instead of using the one provided by find_package

**Comment by lucienboillod** [comment]
Alright, many thanks for the explanations ! I understand the problem now.

I'll try your way asap and let you know

**Comment by lucienboillod** [comment]
It is working fine ! thanks a lot

A last question, for now I'm setting the CONAN_LIBS variable directly from the CMakeLists, is there a way to set from the conan side and not touch the Cmake part ?

**Comment by memsharded** [comment]
@lucienboillod great! :)

Sorry, I didn't understand. Conan is defining itself the CONAN_LIBS variable in conanbuildinfo.cmake, you meant, that you are using it in your CMakeLists? Could you please clarify? Thanks!

**Comment by uilianries** [comment]
@lucienboillod You could use a cmake wrapper as we did for many recipes:

https://github.com/conan-community/conan-zlib/blob/release/1.2.11/CMakeLists.txt

Another way, run `tools.replace_in_file` to inject all required libraries, but is totally ugly IMO.

**Comment by lucienboillod** [comment]
@memsharded yes I replaced the {FREETYPE_LIBRARY} by {CONAN_LIBS} in the CMakeLists.txt of the ftg thirdparty, I know it is hardcoded and it is ugly that was juste to test. I wonder now if there is a good pratice or something, in order to not modify at all the CMakelists and leave FREETYPE_LIBRARY variable inside.

@uilianries yes I already use the cmake wrapper :)

**Comment by uilianries** [comment]
@memsharded replace ${FREETYPE_LIBRARY} by ${CONAN_LIBS} could solve it, but in my understanding, _libpng_ should be statically linked to _libfreetype_, so only ${FREETYPE_LIBRARY} should be enough.

When I ran `nm` on Linux and `dumpbin` on Windows, over _libfreetype_, I was able find all _libpng_ symbols.

**Comment by lucienboillod** [comment]
@uilianries btw, it is off topic, but in some cases, the use of cmake wrapper (with CMakeLists.txt) seems to invalidate the CMAKE_SOURCE_DIR, so some times tools.replace_in_file is a better option :/

**Comment by uilianries** [comment]
I just updated my example to have the same behavior.

https://github.com/uilianries/freetype-png-example

Log: https://gist.github.com/uilianries/1001863bf450c613c02c13b3e2895b4f

Now I'm able to see the same error. Well, looks like my FindFreetype is not solving libpng and all other dependencies.

I think that I need to check some variable from conanbuildinfo.cmake to fill ${FREETYPE_LIBRARIES}

**Comment by uilianries** [comment]
I found a solution, the key is change FindFreetype.cmake provided by conan-freetype:

```cmake
cmake_minimum_required(VERSION 2.8)

foreach(libname ${CONAN_LIBS})
    find_library(${libname}_LIBRARY NAMES ${libname} PATHS ${CONAN_LIB_DIRS} NO_CMAKE_FIND_ROOT_PATH)
    set(FREETYPE_LIBRARY ${FREETYPE_LIBRARY} ${${libname}_LIBRARY})
endforeach(libname ${CONAN_LIBS})

set(FREETYPE_INCLUDE_DIRS ${CONAN_INCLUDE_DIRS})
set(FREETYPE_INCLUDE_DIR ${CONAN_INCLUDE_DIRS_FREETYPE})
set(FREETYPE_LIBRARIES ${CONAN_LIBS})

MESSAGE("** FREETYPE ALREADY FOUND BY CONAN!")
SET(FREETYPE_FOUND TRUE)
MESSAGE("** FOUND FREETYPE:  ${FREETYPE_LIBRARY}")
MESSAGE("** FOUND FREETYPE INCLUDE:  ${FREETYPE_INCLUDE_DIR}")

mark_as_advanced(FREETYPE_LIBRARY FREETYPE_INCLUDE_DIR)

set(FREETYPE_MAJOR_VERSION "2")
set(FREETYPE_MINOR_VERSION "9")
set(FREETYPE_PATCH_VERSION "0")
```

As we can see, I listed each library involving freetype and pushed into FREETYPE_LIBRARY. Other variables are collected from conanbuildinfo.cmake

I'm going update on testing branch.

@memsharded @lucienboillod WDYT?

**Comment by uilianries** [comment]
I just updated https://github.com/bincrafters/conan-freetype/tree/testing/2.9.0 with the new changes. This recipe will not be on Bintray.

**Comment by lucienboillod** [comment]
@uilianries Seems like the foreach is setting variables that are not only freetype dependencies, which leads my build to have CMake Error.

```
** FREETYPE ALREADY FOUND BY CONAN!
** FOUND FREETYPE:  C:/Users/lboillod/.babun/cygwin/home/lboillod/.conan/data/freetype/2.9.0/lboillod/testing/package/081e0a59ca5bd1b2b4129dc41eaa1fe62a1e36df/lib/freetype.lib;C:/Users/lboillod/.babun/cygwin/home/lboillod/.conan/data/glew/2.1.0/dimi309/stable/package/6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7/lib/glew32s.lib;OpenGL32.lib_LIBRARY-NOTFOUND;C:/Users/lboillod/.babun/cygwin/home/lboillod/.conan/data/gtest/1.8.0/bincrafters/stable/package/3f7b6d42d6c995a23d193db1f844ed23ae943226/lib/gmock_main.lib;C:/Users/lboillod/.babun/cygwin/home/lboillod/.conan/data/gtest/1.8.0/bincrafters/stable/package/3f7b6d42d6c995a23d193db1f844ed23ae943226/lib/gmock.lib;C:/Users/lboillod/.babun/cygwin/home/lboillod/.conan/data/gtest/1.8.0/bincrafters/stable/package/3f7b6d42d6c995a23d193db1f844ed23ae943226/lib/gtest.lib;C:/Users/lboillod/.babun/cygwin/home/lboillod/.conan/data/libjpeg/9b/bincrafters/stable/package/6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7/lib/libjpeg.lib;C:/Users/lboillod/.babun/cygwin/home/lboillod/.conan/data/bzip2/1.0.6/conan/stable/package/ce1f8ff23addde793223a2a82ed7fe355c57a589/lib/bz2.lib;C:/Users/lboillod/.babun/cygwin/home/lboillod/.conan/data/libpng/1.6.34/bincrafters/stable/package/606fdb601e335c2001bdf31d478826b644747077/lib/libpng16.lib;C:/Users/lboillod/.babun/cygwin/home/lboillod/.conan/data/zlib/1.2.11/conan/stable/package/6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7/lib/zlib.lib
** FOUND FREETYPE INCLUDE:  C:/Users/lboillod/.babun/cygwin/home/lboillod/.conan/data/freetype/2.9.0/lboillod/testing/package/081e0a59ca5bd1b2b4129dc41eaa1fe62a1e36df/include;C:/Users/lboillod/.babun/cygwin/home/lboillod/.conan/data/freetype/2.9.0/lboillod/testing/package/081e0a59ca5bd1b2b4129dc41eaa1fe62a1e36df/include/freetype2
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
OpenGL32.lib_LIBRARY
    linked by target "ftgl-tulip-5_2" in directory C:/Users/lboillod/conan-tulip-lb/tulip/thirdparty/ftgl
    linked by target "tulip-ogl-5_2" in directory C:/Users/lboillod/conan-tulip-lb/tulip/library/tulip-ogl/src
```

**Comment by uilianries** [comment]
Understood, it should collect only freetype dependencies in FREETYPE_LIBRARY.

@lucienboillod Are you running over `freetype/2.9.0@bincrafters/testing` (the newest patch)?

**Comment by lucienboillod** [comment]
@uilianries yes

right that was I thought

**Comment by memsharded** [comment]
That is true. The PR looked good to me initially, but it is true that iterating over CONAN_LIBS on the consumer cmake space, will iterate over all dependencies, not only the freetype one. 

For me, this is one of the big inconveniences of find_package: transitivity is quite difficult, even at small scale (just 1 level of transitive dependencies). With many nested dependencies it becomes unmanageable.

**Comment by memsharded** [comment]
@uilianries 

I would suggest trying to do an explicit find of png in the find_package, something in the line:
```cmake
find_library(PNG_LIBRARY NAMES ${CONAN_LIBS_PNG} PATHS ${CONAN_LIB_DIRS_PNG} NO_CMAKE_FIND_ROOT_PATH)
set(FREETYPE_LIBRARY ${FREETYPE_LIBRARY} ${PNG_LIBRARY})
```

**Comment by uilianries** [comment]
Thanks @memsharded 

I'll put some conditionals also, libpng is an option on recipe.

**Comment by uilianries** [comment]
@lucienboillod I updated the package, please run it again.

**Comment by lucienboillod** [comment]
@uilianries  Tested. It does the job !

**Comment by memsharded** [comment]
@uilianries great job!
Thanks @lucienboillod for your feedback and support!

**Comment by uilianries** [comment]
Thanks to @memsharded for his great support and review!
