### ISSUE TITLE
The Google double conversion library package, prerequisite for Facebook folly, is ready for publishing

### ISSUE THREAD

**Issue by dimi309** [bincrafters/community#22]
I've added Google's double conversion library, as a conan package:

https://github.com/bincrafters/conan-double-conversion

Proof of successful builds from my fork:

https://ci.appveyor.com/project/coding3d/conan-double-conversion/build/1.0.4
https://travis-ci.org/dimi309/conan-double-conversion/builds/314002170

(some are still building at the time of writing but they should be fine)

Works on Linux/MacOS/Windows, most likely also on MinGW even though I haven't tried it there yet.

**Comment by dimi309** [comment]
I've just checked and the package does work with MinGW as well :)

**Comment by solvingj** [comment]
Sounds great, lets move forward .

**Comment by dimi309** [comment]
Great! Can you activate the builds? I'll then push it to stable.

**Comment by dimi309** [comment]
Published!
https://bintray.com/bincrafters/public-conan/double-conversion%3Abincrafters
