### ISSUE TITLE
Bump version pugixml

### ISSUE THREAD

**Issue by uilianries** [bincrafters/community#221]
### Description of Problem, Request, or Question
Bump pugixml to 2.9

Related PR: https://github.com/bincrafters/conan-pugixml/pull/1

**Comment by uilianries** [comment]
Done!

https://github.com/bincrafters/conan-pugixml/tree/stable/1.9
https://bintray.com/bincrafters/public-conan/pugixml%3Abincrafters/1.9%3Astable

**Comment by AlexandrePTJ** [comment]
Thanks you !
