### ISSUE TITLE
Catch2: export cmake files to enable ctest integration

### ISSUE THREAD

**Issue by promgamer** [bincrafters/community#222]
I think it would be nice to export [catch's cmake files](https://github.com/catchorg/Catch2/blob/master/docs/build-systems.md#automatic-test-registration) to enable integration with ctest.

Right now it's what is making me use catch as a submodule instead of a conan package.

Let me know if you think this can be a good issue to tackle, so I can try to contribute with a PR.

**Comment by uilianries** [comment]
I see no problem. In your case, without catch's cmake files, you need to copy all ctest from catch project on your cmake file.

**Comment by uilianries** [comment]
Closing this issue.

The update was merged into stable branch, but need several minutes until push on Bintray.

Please, re-open this issue if you detect any problem.

**Comment by Quincunx271** [comment]
The files are copied into a suboptimal location. If we [look at the conanfile.py inside Catch2 itself](https://github.com/catchorg/Catch2/blob/v2.3.0/conanfile.py), it just configures and installs using CMake. If we don't want to do it that way, the files should still be installed to the same location CMake would, namely `lib/cmake/Catch2`.

**Comment by Quincunx271** [comment]
Actually, this point should be its own issue. See #397
