### ISSUE TITLE
New XCode images provided by Travis CI

### ISSUE THREAD

**Issue by uilianries** [bincrafters/community#224]
### Description of Problem, Request, or Question
Should we update our template to use xcode 9.2 and xcode 9.3?

https://docs.travis-ci.com/user/reference/osx/#OS-X-Version

### Package Details (Include if Applicable)
* Package Name/Version: **Any**
* Operating System: **Macos**
* Compiler+version: **clang**

**Comment by SSE4** [comment]
template was updated, script to update projects automatically was invented, also the majority of projects has been updated already. I guess we can close. WDYT @uilianries @solvingj  ?

**Comment by uilianries** [comment]
@SEE4 Agreed.
