### ISSUE TITLE
[pugixml] Add option for wchar mode

### ISSUE THREAD

**Issue by kylemacfarlan** [bincrafters/community#225]
Pugixml supports building with wchar* instead of char*, and it would be nice to make that a conan option. The option can be set by changing the pugiconfig.hpp file (uncommenting the #define PUGIXML_WCHAR_MODE). 

It doesn't seem like pugixml has a specific cmake flag for that, so one somewhat brute-force option is to edit the pugiconfig.hpp file from conan during the build step. I've attached a conanfile.py that does this, but it feels like a hack. I'm not sure if there is a more elegant solution. 
[conanfile.zip](https://github.com/bincrafters/community/files/1895023/conanfile.zip)

**Comment by uilianries** [comment]
Hi @kylemacfarlan !

Thanks for your suggestion, I'll take this soon.

Regards.

**Comment by uilianries** [comment]
Hi @kylemacfarlan !

I just created a PR including your request:

https://github.com/bincrafters/conan-pugixml/pull/2

**Comment by uilianries** [comment]
Hi @kylemacfarlan @AlexandrePTJ !

Please, update the package and check!

Regards!

**Comment by kylemacfarlan** [comment]
Works great! Thank you!
