### ISSUE TITLE
Can't install ICU

### ISSUE THREAD

**Issue by jacobborisov** [bincrafters/community#232]
### Description of Problem, Request, or Question
Hello. At this time I'm unable to install any version of ICU package, see example for details. Thanks.

### Package Details
* Package Name/Version: **Conan version 1.0.4**
* Operating System: **Fedora release 27 (Twenty Seven)**

### Steps to reproduce
```
$ conan install icu/60.2@bincrafters/stable                                   
icu/60.2@bincrafters/stable: Not found in local cache, looking in remotes...
icu/60.2@bincrafters/stable: Trying with 'conan-center'...
ERROR: Unable to find 'icu/60.2@bincrafters/stable' in remotes
```

**Comment by uilianries** [comment]
Hi @jacobborisov !

As listed on your search, you only have Conan center listed.
You need to add Bincrafters' remote to pull our packages.

```
$ conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-cona
$ conan install icu/60.2@bincrafters/stable
```

Regards.

**Comment by jacobborisov** [comment]
Hi, thanks for you help!
