### ISSUE TITLE
Bump cli11 to version 1.5.3

### ISSUE THREAD

**Issue by drrlvn** [bincrafters/community#237]
https://github.com/CLIUtils/CLI11/releases/tag/v1.5.3

### Package Details (Include if Applicable)
* Package Name/Version: **cli11/1.4.0**
* Operating System: **Arch Linux**
* Compiler+version: **gcc-7.3**

**Comment by uilianries** [comment]
Done!

https://github.com/bincrafters/conan-cli11/tree/stable/1.5.3
https://travis-ci.org/bincrafters/conan-cli11/builds/369729591
https://ci.appveyor.com/project/BinCrafters/conan-cli11/build/1.0.19
https://bintray.com/bincrafters/public-conan/cli11%3Abincrafters/1.5.3%3Astable
