### ISSUE TITLE
glfw v3.2.1.20180327 corrupted package

### ISSUE THREAD

**Issue by dimi309** [bincrafters/community#238]
### Description of Problem, Request, or Question

Hi everyone. Can somebody relaunch the builds for v3.2.1.20180327 of GLFW, especially the ones for Windows? I think the stored package is corrupted. I get this error upon `conan install`:

```
glfw/3.2.1.20180327@bincrafters/stable: Trying with 'bintraybincrafters'...
Downloading conanmanifest.txt
[==================================================] 170B/170B
Downloading conanfile.py
[==================================================] 6.2KB/6.2KB
Downloading conan_export.tgz
[==================================================] 287B/287B
ERROR: Error while downloading/extracting files to C:\Users\user\.conan\data\glfw\3.2.1.20180327\bincrafters\stable\export
file could not be opened successfully
Folder removed
```

### Package Details (Include if Applicable)
* Package Name/Version: **glfw/3.2.1.20180327**
* Operating System: **Windows 10**
* Compiler+version: **Visual Studio 2017**

### Steps to reproduce (Include if Applicable)

Just reference version 3.2.1.20180327 of the package from a project.

**Comment by uilianries** [comment]
https://ci.appveyor.com/project/BinCrafters/conan-glfw/build/1.0.24

**Comment by dimi309** [comment]
It works now. Thanks a lot!
