### ISSUE TITLE
cygwin_installer breaks symlinks

### ISSUE THREAD

**Issue by db4** [bincrafters/community#239]
This
```python
    def fix_symlinks(self):
        path = os.path.join(self.package_folder, 'bin', '*')
        self.run('attrib -r +s /D "%s" /S /L' % path)
```
is not enough, it only fixes symlinks inside bin, but there are others, e.g. `/usr/ssl/certs/ca-bundle.crt -> /usr/ssl/certs`. Without it git is unusable:
```
$ git fetch -q origin
fatal: unable to access 'https://github.com/fdopen/opam-repository-mingw.git/': error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
```
So we need better method to restore symlinks. What about shutil.copytree() that preserves file attributes instead of conan copy()?

**Comment by SSE4** [comment]
@db4 packages are built, please give a try

**Comment by db4** [comment]
No problems so far. You can close the issue.

**Comment by SSE4** [comment]
thanks for the confirmation and for contribution!
