### ISSUE TITLE
spdlog: False reference to fmt

### ISSUE THREAD

**Issue by Croydon** [bincrafters/community#24]
https://github.com/bincrafters/conan-spdlog/blob/4f62824f5294da64d0013dfec9e9950ae54d3a35/conanfile.py#L18

I'm pretty sure that this should be `fmt` instead of `fmtlib`.

**Comment by solvingj** [comment]
You are correct, the author of `fmt` suggested we change the package name at the last minute and it looks like we did not catch this one. 

I will use this opportunity to refresh the `spdlog` recipe with all the recent standards we've implemented since it was last touched.

**Comment by solvingj** [comment]
I have corrected the error, and will now move on to refreshing.

**Comment by solvingj** [comment]
Actually, disregard the bit about refreshing, the rest looks up-to-date.  I was looking at a very old commit and I thought i was looking at the latest. 

Please let me know if the latest commit works for you.

**Comment by Croydon** [comment]
Seems to be fine now, thanks!
