### ISSUE TITLE
gtest packages without Combine feature

### ISSUE THREAD

**Issue by piponazo** [bincrafters/community#240]
### Description of Problem, Request, or Question

I am trying to move my project to use your gtest recipe but I found a issue with the Windows/MSVC15 package. The `::testing::Combine` functionality is not available, and I think it is because you have these lines in the recipe:

```
        if self.settings.compiler == "Visual Studio" and float(str(self.settings.compiler.version)) >= 15:
            self.cpp_info.defines.append("GTEST_LANG_CXX11=1")
            self.cpp_info.defines.append("GTEST_HAS_TR1_TUPLE=0")
```
Then, the internal `gtest-port.h` code has:

```
// Determines whether to support Combine(). This only makes sense when
// value-parameterized tests are enabled.  The implementation doesn't
// work on Sun Studio since it doesn't understand templated conversion
// operators.
#if GTEST_HAS_PARAM_TEST && GTEST_HAS_TR1_TUPLE && !defined(__SUNPRO_CC)
# define GTEST_HAS_COMBINE 1
#endif
```
And finally the feature is not available. Until now I have been using a customized gtest recipe without defining `GTEST_HAS_TR1_TUPLE` and it has been working properly with Windows/MSVC15. Why do you need to define such define?

### Package Details (Include if Applicable)
* Package Name/Version: **gtest/1.8.0**
* Operating System: **Windows 10**
* Compiler+version: **MSVC 15.3.2**

### Steps to reproduce (Include if Applicable)

If you try to use `::testing::Combine` in your test_package, you should see the problem.

**Comment by uilianries** [comment]
@mropert any idea?

**Comment by uilianries** [comment]
According the [log](https://github.com/bincrafters/conan-gtest/commit/3766b50052c4a242340411bb2258857cdd4f3d5e) there was some problem to build using Visual Studio 2017.

**Comment by mropert** [comment]
I would agree with @piponazo's analysis.
The defines are there to disable the TR1 impl and use the C++11 std:: one because GTest is unable to detect that Visual Studio now supports the standard properly.
It seems like they missed something...

In the meantime I'm afraid the only option is to create a package for a particular git commit on the master branch :(

**Comment by piponazo** [comment]
Apparently they will change the release policy in the next months:

https://github.com/google/googletest/issues/1079
https://github.com/google/googletest/issues/1366

**Comment by SSE4** [comment]
@solvingj  @uilianries so, what should we do? options I see:
1. do nothing and close
2. add patch with fix to our 1.8.0 package
3. build package from the specific revision 
4. wait for the next gtest release and keep issue open

**Comment by piponazo** [comment]
Hi guys,

Just a comment about this. At Pix4D we were using our own version of the recipe, and we were not using at all the definitions you added:

```
if self.settings.compiler == "Visual Studio" and float(str(self.settings.compiler.version)) >= 15:
            self.cpp_info.defines.append("GTEST_LANG_CXX11=1")
            self.cpp_info.defines.append("GTEST_HAS_TR1_TUPLE=0")
```
I think that by just removing that conditional, packages will work on Windows. Even though, the recipe will not be as precise as it is now, I think it is another option you might consider. But I think the patch approach would be more correct.

**Comment by piponazo** [comment]
Let me know if I can help here, I would be happy to contribute to this recipe :smiley:

**Comment by mropert** [comment]
@piponazo I'm pretty sure if you don't put those flags on VS 2017 you'll get warnings from tr1 usage.
Unless you don't use the /std to enforce standard compliance.

**Comment by piponazo** [comment]
> @piponazo I'm pretty sure if you don't put those flags on VS 2017 you'll get warnings from tr1 usage.
Unless you don't use the /std to enforce standard compliance.

Right, probably we are silencing those warnings. I remember we have a wrapper to gtest.h with something like this:

```
#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable : 4251)
#pragma warning(disable : 4275)
#endif
#include <gmock/gmock.h>
#ifdef _MSC_VER
#pragma warning(pop)
#endif
```

**Comment by SSE4** [comment]
@piponazo if you're willing to contribute, could you open PR against our Google Test recipe? or at least provide a patch file against Google Test itself, which solves problems for you?

**Comment by piponazo** [comment]
PR created, let me know if the patch satisfies your guidelines ;)

**Comment by SSE4** [comment]
@piponazo  changes were merged, pls give another try

**Comment by SSE4** [comment]
closing as changes were merge, @piponazo if you have any other problems with GTest package, feel free to open new issue(s).
