### ISSUE TITLE
Inclusion request review for libzip

### ISSUE THREAD

**Issue by danimtb** [bincrafters/community#243]
## Inclusion Request Review

This is a review for [libzip/1.4.0@bincrafters/stable (bincrafters/public-conan)](https://github.com/bincrafters/conan-libzip) inclusion request to conan-center.
This review follows the [inclusion guidelines or third party libraries](http://docs.conan.io/en/latest/uploading_packages/bintray/conan_center_guide.html#inclusion-guidelines-for-third-party-libraries).

### Package
libzip/1.4.0@bincrafters/stable (It also applies to 1.5.1 and 1.2.0)

#### Recipe quality
- [x] Git public repository
- [x] Recipe fields
- [x] Linter
- [x] Updated
- [x] Clean
- [x] test_package
- [x] Raise errors on invalid configurations
- [x] LICENSE of the recipe
- [x] LICENSE of the library

#### CI Integration
- [x] Provide at least one CI configuration (header only)
- [x] (If not header only) CI configurations for Linux/MacOSX/Windows

#### Bintray Package Information
- [x] Description
- [x] Licenses
- [x] Tags
- [x] Maturity
- [x] Website (if any)
- [x] Issue tracker
- [x] Version control

### Additional comments

Can't detect cpp sources but the conanfile doesn't remove ``compiler.libcxx``

Suggestion: 
```
def configure(self):
    del self.settings.compiler.libcxx
```

Please consider improving the C code en the *test_package* to really test some functionality of the library and ensure it is consuming the package well.

**Comment by uilianries** [comment]
Need to solve https://github.com/conan-community/community/issues/16 before to continue.

**Comment by danimtb** [comment]
Sorry @uilianries but I cant see why this issue is blocked by conan-community/community#16

libzip only depends on `zlib`...

**Comment by uilianries** [comment]
Well, on libzip's cmake file: https://github.com/nih-at/libzip/blob/rel-1-5-1/CMakeLists.txt#L181

So, the project uses bipz2 as optional. However bipz2 package does not work for clang 5. I didn't check bzip2 package, but if I install by apt, using lasote/conanclang50 the find_package works

But now I'm curious, because I didn't run ldd to check if libzip uses bipz2 when it's found.

**Comment by danimtb** [comment]
Ok, no I see it.

So after that is fixed, you would have to add bzip2 dependency in the conanfile, now bzip2 is missing in the requires.

**Comment by uilianries** [comment]
bzip2 is included as optional.

There is the option with_bzip2, that is checked on function requirements

**Comment by lasote** [comment]
Check again if now it works. the issues with bzip2 should be fixed. 
About the inclusion process itself, add the apple-clang 9.1 packages

**Comment by SSE4** [comment]
bz2 issue solved, apple-clang 9.1 added

**Comment by danimtb** [comment]
# libzip/1.4.0
- One windows job failed: https://ci.appveyor.com/project/BinCrafters/conan-libzip

- There are some outdated packages, please remove them:
  ![image](https://user-images.githubusercontent.com/10808592/40112976-1e820fdc-5908-11e8-9f8e-cc7a0bb79287.png)


# libzip/1.5.1
- One Linux job failed for 1.5.1: https://travis-ci.org/bincrafters/conan-libzip/builds/379528628
One Windows job failed for 1.5.1: https://ci.appveyor.com/project/BinCrafters/conan-libzip/build/1.0.22/job/ftxx0b0i0au4p6vu
Both seem to be connection issues when uploading/downloading (sorry). This causes some outdated packages:
![image](https://user-images.githubusercontent.com/10808592/40113349-751e1fc4-5909-11e8-82cb-17f29928d2ba.png)

# libzip/1.2.0
Seems the recipe for this version is a bit outdated. No fPIC options, no need to handle share option expicitly in CMake...
- Missing packages for apple-clang 9.1
- Missing packages for Visual Studio 12
- Missing packages for Visual Studio 14
- Missing packages for Visual Studio 15
![image](https://user-images.githubusercontent.com/10808592/40113982-809e0bdc-590b-11e8-992e-286eb71dfec6.png)

- Please remove `libcxx`:
```
def configure(self):
    del self.settings.compiler.libcxx
```

**Comment by uilianries** [comment]
Some uploads failed. I'm update the things later. Thanks for report

**Comment by uilianries** [comment]
@danimtb Finally! After 8h waiting for CI!

All versions are updated, including test package.

![libzip/1.2.0](https://screenshotscdn.firefoxusercontent.com/images/00a990f5-4dcc-4449-ab4d-670d9fd75164.png)

![libzip/1.4.0](https://screenshotscdn.firefoxusercontent.com/images/02b89c48-581b-4b4b-806d-9d503bf03d0c.png)

![libzip/1.5.1](https://screenshotscdn.firefoxusercontent.com/images/488d7571-7d02-4775-863d-6573867b99b8.png)

**Comment by danimtb** [comment]
approved!! Thanks @uilianries

**Comment by uilianries** [comment]
Awesome, thanks!
