### ISSUE TITLE
Inclusion request review for jansson

### ISSUE THREAD

**Issue by danimtb** [bincrafters/community#244]
## Inclusion Request Review

This is a review for [jansson/2.11@bincrafters/stable (bincrafters/public-conan)](https://github.com/bincrafters/conan-jansson) inclusion request to conan-center.
This review follows the [inclusion guidelines or third party libraries](http://docs.conan.io/en/latest/uploading_packages/bintray/conan_center_guide.html#inclusion-guidelines-for-third-party-libraries).

### Package
jansson/2.11@bincrafters/stable

#### Recipe quality
- [x] Git public repository
- [x] Recipe fields
- [x] Linter
- [x] Updated
- [x] Clean
- [x] test_package
- [x] Raise errors on invalid configurations
- [x] LICENSE of the recipe
- [x] LICENSE of the library: There is no license packaged for this library, please include library package license in a *licenses* folder inside the package folder.

#### CI Integration
- [x] Provide at least one CI configuration (header only)
- [x] (If not header only) CI configurations for Linux/MacOSX/Windows

#### Bintray Package Information
- [x] Description
- [x] Licenses
- [x] Tags
- [x] Maturity
- [x] Website (if any)
- [x] Issue tracker
- [x] Version control

### Additional comments

Seems this is a pure C library. Can't detect cpp sources but the conanfile doesn't remove ``compiler.libcxx``

Suggestion: 
```
def configure(self):
    del self.settings.compiler.libcxx
```

**Comment by lasote** [comment]
Also missing packages for apple clang 9.1. So summarizing:

- Add license file
- Remove libcxx
- Add apple-clang 9.1 to CI

**Comment by uilianries** [comment]
I created the follow PRs:

https://github.com/bincrafters/conan-jansson/pull/2
https://github.com/bincrafters/conan-jansson/pull/3

Just waiting for CI to merge.

**Comment by uilianries** [comment]
@danimtb @lasote Done!

![jansson/2.11](https://screenshotscdn.firefoxusercontent.com/images/6f7a5526-a7ba-460f-98d1-51a9c95cf584.png)

![jansson/2.10](https://screenshotscdn.firefoxusercontent.com/images/fd2480d7-898c-4399-b137-612334120634.png)

**Comment by uilianries** [comment]
Created new PR to solve this issue:

https://github.com/bincrafters/conan-jansson/pull/5
https://github.com/bincrafters/conan-jansson/pull/4

After to merge, it will need to remove outdated packages -- Windows + fPIC

**Comment by uilianries** [comment]
@danimtb Done!

![jansson/2.10](https://screenshotscdn.firefoxusercontent.com/images/d0f12e44-9275-43f9-9ad4-58423764d54a.png)

![jansson/2.11](https://screenshotscdn.firefoxusercontent.com/images/2e1ee9da-0db4-480e-9607-6970c6fd7ccf.png)

**Comment by danimtb** [comment]
accepted!! Thank you so much @uilianries 😄 Happy to have another one in conan-center!

**Comment by uilianries** [comment]
Thanks so much for accept this package! Cheers!
