### ISSUE TITLE
Inclusion request review for greatest

### ISSUE THREAD

**Issue by danimtb** [bincrafters/community#245]
## Inclusion Request Review

This is a review for [greatest/1.3.1@bincrafters/stable (bincrafters/public-conan)](https://github.com/bincrafters/conan-greatest) inclusion request to conan-center.
This review follows the [inclusion guidelines or third party libraries](http://docs.conan.io/en/latest/uploading_packages/bintray/conan_center_guide.html#inclusion-guidelines-for-third-party-libraries).

### Package
greatest/1.3.1@bincrafters/stable

#### Recipe quality
- [x] Git public repository
- [x] Recipe fields
- [x] Linter
- [x] Updated
- [x] Clean
- [x] test_package
- [x] Raise errors on invalid configurations
- [x] LICENSE of the recipe
- [x] LICENSE of the library: License of the library is not being copied to a *licenses* folder in the pckage folder.

#### CI Integration
- [x] Provide at least one CI configuration (header only)
- [x] (If not header only) CI configurations for Linux/MacOSX/Windows

#### Bintray Package Information
- [x] Description
- [x] Licenses
- [x] Tags
- [x] Maturity
- [x] Website (if any)
- [x] Issue tracker
- [x] Version control

### Additional comments
Just to notify bincrafters community there is a new version of `greatest`: 1.4.0 https://github.com/silentbicycle/greatest/releases/tag/v1.4.0 😸

**Comment by uilianries** [comment]
Done!

LICENSE fixed: https://github.com/bincrafters/conan-greatest/blob/stable/1.4.0/conanfile.py#L26

Version 1.4.0: https://bintray.com/bincrafters/public-conan/greatest%3Abincrafters/1.4.0%3Astable

**Comment by danimtb** [comment]
Checked and accepted into conan-center! Thanks @uilianries for the support and the update to new version 😃
