### ISSUE TITLE
Bincrafters Package Tools - Sync with Conan package tools 0.17.0

### ISSUE THREAD

**Issue by uilianries** [bincrafters/community#246]
### Description of Problem, Request, or Question
After to new release of CPT 0.17.0, would be nice to update out wrapper to follow the new stuff.

### Package Details (Include if Applicable)
* Package Name/Version: https://github.com/bincrafters/bincrafters-package-tools

**Comment by SSE4** [comment]
any details on what exactly should be updated/added (new stuff)?

**Comment by uilianries** [comment]
Hi @SSE4 

Just bump CTP version required and import cpt instead of packager.

Would be nice to validate all configs, including Boost and header-only.
