### ISSUE TITLE
Package OpenAL

### ISSUE THREAD

**Issue by sztomi** [bincrafters/community#25]
WIP here: https://github.com/sztomi/conan-openal
 
 - [x] macOS (local)
 - [x] Linux (local)
 - [ ] Travis CI
 - [x] Windows (local)
 - [ ] AppVeyor
 - [ ] README
 - [ ] Move to bincrafters

**Comment by sztomi** [comment]
WIP here: https://github.com/sztomi/conan-openal

**Comment by SSE4** [comment]
OpenAL is packaged and ready for submission into conan center https://github.com/bincrafters/conan-openal
