### ISSUE TITLE
Review of inclusion request `libusb/1.0.21@bincrafters/stable`

### ISSUE THREAD

**Issue by lasote** [bincrafters/community#254]
## Inclusion Request Review

This is a review for [libusb/1.0.21@bincrafters/stable (bincrafters/public-conan)](https://github.com/bincrafters/conan-libusb) inclusion request to conan-center.
This review follows the [inclusion guidelines or third party libraries](http://docs.conan.io/en/latest/uploading_packages/bintray/conan_center_guide.html#inclusion-guidelines-for-third-party-libraries).

### Package
libusb/1.0.21@bincrafters/stable

#### Recipe quality
- [x] Git public repository
- [x] Recipe fields
- [x] Linter
- [ ] Updated

    - The recipe is using the deprecated `build_sln_command`, it has been replaced with the build helper `MSBuild()`
    - To avoid the "x86"/"Win32" replacement probably you can use the `platforms` parameter `platforms={"x86":"Win32"}` (read [reference](http://docs.conan.io/en/latest/reference/build_helpers/visual_studio.html))

     ```
     build_command = tools.build_sln_command(self.settings, solution_file, upgrade_project=False)
     if self.settings.arch == "x86":
          build_command = build_command.replace("x86", "Win32")
     ```

    - For Linux/Mac/MinGW, the `AutoToolsBuildEnvironment` now take cares automatically of the `--prefix` so you can remove it, and use directly the `env_build.configure` 

- [x] Clean
- [x] test_package
- [x] Raise errors on invalid configurations
- [x] LICENSE of the recipe
- [x] LICENSE of the library

#### CI Integration
- [x] Provide at least one CI configuration (header only)
- [x] (If not header only) CI configurations for Linux/MacOSX/Windows

#### Bintray Package Information
- [x] Description
- [x] Licenses
- [x] Tags
- [x] Maturity
- [x] Website (if any)
- [x] Issue tracker
- [x] Version control

### Additional comments

There are some outdated packages, regenerate all and/or:

`conan remove libusb/1.0.21@bincrafters/stable --outdated -r bincrafters`

Good work! just some comments due to some Conan improvements.

**Comment by lasote** [comment]
PD: Add apple-clang 9.1 ;)

**Comment by uilianries** [comment]
@lasote Done!

- Updated both 0.1.12 and 1.0.21
- Added 1.0.22

![libusb/0.1.12@bincrafters/stable](https://screenshotscdn.firefoxusercontent.com/images/795d2bcf-f837-43cc-8542-9ac0949da165.png)

![libusb/1.0.21@bincrafters/stable](https://screenshotscdn.firefoxusercontent.com/images/5cf3e0ab-590b-4a84-b54a-934ce4c9bec5.png)

![libusb/1.0.22@bincrafters/stable](https://screenshotscdn.firefoxusercontent.com/images/bb11dcb1-d86b-4502-93cb-526211e511f1.png)

**Comment by lasote** [comment]
libusb in conan-center!!! 🎉  Congrats and many thanks!

**Comment by solvingj** [comment]
@uilianries is amazing.

**Comment by lasote** [comment]
Yes he is!
