### ISSUE TITLE
Inclusion Request Review: mosquitto/1.4.15@bincrafters/stable

### ISSUE THREAD

**Issue by lasote** [bincrafters/community#256]
## Inclusion Request Review

This is a review for [mosquitto/1.4.15@bincrafters/stable (bincrafters/public-conan)](https://github.com/bincrafters/conan-mosquitto) inclusion request to conan-center.
This review follows the [inclusion guidelines or third party libraries](http://docs.conan.io/en/latest/uploading_packages/bintray/conan_center_guide.html#inclusion-guidelines-for-third-party-libraries).

### Package
mosquitto/1.4.15@bincrafters/stable

#### Recipe quality
- [x] Git public repository
- [x] Recipe fields
- [x] Linter
- [ ] Updated
    - The fPIC Management is now (1.3) automatically managed by the CMake build helper, just FYI, the way we (both conan team and bincrafters) were managing this is wrong:

    ```
    cmake.definitions["CMAKE_POSITION_INDEPENDENT_CODE"] = self.options.fPIC
    ```

    CMake by default, adjust `CMAKE_POSITION_INDEPENDENT_CODE` to True when the library is shared, but once you specify it by hand, like this case, you need to activate it also when shared:
  
    ```
    cmake.definitions["CMAKE_POSITION_INDEPENDENT_CODE"] = self.options.fPIC or self.options.shared
    
    ```

    But anyway Conan is doing it automatically now, so remove it and we are good.

- [x] Clean
- [x] test_package
- [x] Raise errors on invalid configurations
- [x] LICENSE of the recipe
- [x] LICENSE of the library

#### CI Integration
- [x] Provide at least one CI configuration (header only)
- [x] (If not header only) CI configurations for Linux/MacOSX/Windows

#### Bintray Package Information
- [x] Description
- [x] Licenses
- [x] Tags
- [x] Maturity
- [x] Website (if any)
- [x] Issue tracker
- [x] Version control

### Additional comments

- Pending apple-clang 9.1 packages, so I would need to check again when they are available (sorry, but this is my environment and where I try it, so I need the prebuilt packages to verify that everything is ok!)

- There are some outdated packages, clean them up with: 
`conan remove mosquitto/1.4.15@bincrafters/stable --outdated -r bincrafters`

- The recipe is fantastic, willing to approve it.

**Comment by uilianries** [comment]
I saw the feature on release notes :+1: 

so should I remove `cmake.definitions["CMAKE_POSITION_INDEPENDENT_CODE"] = self.options.fPIC` from the recipe?

**Comment by uilianries** [comment]
I'm just afraid if someone try to build mosquitto from source running Conan < 1.3.x

**Comment by lasote** [comment]
Any updates with this?

**Comment by uilianries** [comment]
I'm going to continue this package later.

**Comment by uilianries** [comment]
It's updated and good to go IMO

We need to wait for CI to finish the PR.

**Comment by uilianries** [comment]
Almost there, just waiting for stable branch finish on CI

**Comment by uilianries** [comment]
@lasote Mosquitto is done!

**Comment by lasote** [comment]
Looks like you changed some options and there are many outdated packages:

![image](https://user-images.githubusercontent.com/3807515/40008099-5a682fec-5753-11e8-882d-06f5e922973d.png)

Try to clean them up with:

`conan remove mosquitto/1.4.15@bincrafters/stable --outdated -r bincrafters`

**Comment by uilianries** [comment]
Thanks for report, I'm going to restart now

**Comment by uilianries** [comment]
Done!

![mosquitto](https://screenshotscdn.firefoxusercontent.com/images/7def8a8b-033d-457d-ad55-5db198fe8b66.png)

**Comment by uilianries** [comment]
Awesome! I'm going to add deploy feature on next patch. Thanks!

**Comment by uilianries** [comment]
Done! I just create a PR including `deploy()`

https://github.com/bincrafters/conan-mosquitto/pull/5
