### ISSUE TITLE
Corrupted libcurl package

### ISSUE THREAD

**Issue by memsharded** [bincrafters/community#260]
https://bintray.com/bincrafters/public-conan/libcurl%3Abincrafters/7.56.1%3Astable#files/bincrafters%2Flibcurl%2F7.56.1%2Fstable%2Fpackage%2Faa0f125ad888d892d88d160a09f3859b1a39af20

This package has a broken conaninfo.txt, for some reason it seems it is a binary file. 
This breaks the serach for libcurl 7.56.1. I'd suggest deleting it, then running a ``conan search <ref> --table=file.html`` to check for the missing binary.

Many thanks!!

**Comment by theirix** [comment]
It's strange. Was it a failing upload or a more serious storage failure?
Anyway, I'll rebuild 7.56.1 by adding clang 9.1 :)

**Comment by memsharded** [comment]
Great, thanks. 

I have no idea, I'd bet on some error during the transfer, but I can't know right now.

Please make sure to remove that failing one first, just in case it doesn't get properly overwritten for some reason.

**Comment by theirix** [comment]
Removed old package and rebuilt, the search goes well.

Version for clang-9.1 and arm had not been rebuilt yet, will be done later.

**Comment by memsharded** [comment]
Perfect, it works now, many thanks!
