### ISSUE TITLE
Corrupted package: json-c/0.13.1@bincrafters/stable

### ISSUE THREAD

**Issue by danimtb** [bincrafters/community#263]
### Description of Problem, Request, or Question
Seems that json-c/0.13.1 has a corrupted pacakge [d26a890fe7c7ee3ac1546d4143036620012dbc73](https://bintray.com/bincrafters/public-conan/json-c%3Abincrafters/0.13.1%3Astable#files/bincrafters%2Fjson-c%2F0.13.1%2Fstable%2Fpackage%2Fd26a890fe7c7ee3ac1546d4143036620012dbc73)

Same issue as in #260 

### Package Details (Include if Applicable)
* Package Name/Version: **json-c/0.13.1**

### Steps to reproduce (Include if Applicable)

```
$ conan search json-c/0.13.1@bincrafters/stable -r bincrafters
ERROR: Service Error. [Remote: bincrafters]
```

**Comment by uilianries** [comment]
Done!

Also, I included Clang 9.1

![json-c](https://screenshotscdn.firefoxusercontent.com/images/7aac2a6c-2969-4cdf-9680-3401b28930c0.png)

**Comment by SSE4** [comment]
@danimtb any idea how and why packages got corrupted? I guess it would be better to fix underlying problem on conan side, instead of constantly rebuilding corrupted packages (which doesn't scale well in my opinion).

**Comment by danimtb** [comment]
You are totally right @SSE4, this is currently under investigation.

We are not really sure if this was a problem in the client side, a corruption during the upload or in the Bintray database. We only spotted some packages and did some checks but no clue yet, so we will keep an eye on it.

**Comment by uilianries** [comment]
@danimtb fPIC was removed on new PR

https://github.com/bincrafters/conan-json-c/pull/2

**Comment by danimtb** [comment]
Linux builds failing: https://travis-ci.org/bincrafters/conan-json-c/builds/376827071

**Comment by danimtb** [comment]
Accepted into conan-center! Thanks for the great support @uilianries 😄

**Comment by uilianries** [comment]
Awesome! Thanks!
