### ISSUE TITLE
Inclusion request review for libwebp

### ISSUE THREAD

**Issue by danimtb** [bincrafters/community#264]
## Inclusion Request Review

This is a review for [libwebp/0.6.1@bincrafters/stable (bincrafters/public-conan)](https://github.com/bincrafters/conan-libwebp) inclusion request to conan-center.
This review follows the [inclusion guidelines of third party libraries](http://docs.conan.io/en/latest/uploading_packages/bintray/conan_center_guide.html#inclusion-guidelines-for-third-party-libraries).

### Package
libwebp/0.6.1@bincrafters/stable
libwebp/1.0.0@bincrafters/stable

#### Recipe quality
- [x] Git public repository
- [x] Recipe fields
- [x] Linter
- [x] Updated
Note as from [conan 1.3.0](https://docs.conan.io/en/latest/changelog.html#april-2018), CMake helper handles fpic automatically, so there is no need to set `CMAKE_POSITION_INDEPENDENT_CODE` anymore.
- [x] Clean
- [x] test_package
- [x] Raise errors on invalid configurations
- [x] LICENSE of the recipe
- [x] LICENSE of the library

#### CI Integration
- [x] Provide at least one CI configuration (header only)
- [x] (If not header only) CI configurations for Linux/MacOSX/Windows

#### Bintray Package Information
- [x] Description
- [x] Licenses
- [x] Tags
- [x] Maturity: Fill maturity field in Bintray
- [x] Website (if any)
- [x] Issue tracker
- [x] Version control

### Additional comments
Just some comments:
- Handle `fPIC` correctly in recipe. It should be removed in `config_options()`, not in `configure()`:
```
def config_options(self):
    if self.settings.compiler == 'Visual Studio':
        del self.options.fPIC
```
- I haven't looked into the options of the lirary too much but there are some options [at the top of the *CMakeLists.txt*](https://github.com/webmproject/libwebp/blob/6b7a95fd8385baa6d18c96d5c0f2bea5632faf55/CMakeLists.txt#L5) that might be worth to check and model them in the recipe.

- I think there is no need to specify [this two lines](https://github.com/bincrafters/conan-libwebp/blob/testing/0.6.1/conanfile.py#L84#L85), just trust `tools.collect_libs(self)`. It should pick the right libs even for MinGW generated ones.

**Comment by theirix** [comment]
Thanks for the thorough review!

Changed:
- updated maturity
- moved fPIC removal to `config_options`. Strange that I forgot it
- removed unneeded code for Conan 1.3.0. Wish it remove fPIC automatically too :)
- added three options `"with_simd=True", "near_lossless=True", "swap_16bit_csp=False"` and passed through the upstream cmake. Other options are not so useful.
- regarding the `.dll` suffix for libs - it was added for reason (commit 1e5d955d) because mingw build was tested for all imaging libraries. I do not remember details…

Changes are in 0.6.1. After reviewing I'll port them to 1.0.0 and stable branches.

**Comment by theirix** [comment]
> Sorry, my bad. fPIC should be handled this way 😢

Fixed this. fPIC really doesn't make sense even on mingw.

> Yes, we are totally aware of the need to automate things such as fpic, libcxx, shared and so on. We are working on it to get all of those things out of recipe and recude work for package creators.

Glad to hear that those repeated things like fPIC are subject for beeing automated!

**Comment by danimtb** [comment]
Thanks again @theirix!

Final thing: As you added new options now there ae some outdated packages. Please run `conan remove libwebp/0.6.1@bincrafters/stable --outdated -r bincrafters` to delete them and it should be good to go! 😄

**Comment by SSE4** [comment]
@danimtb seems like there are no such packages:
```
conan remove libwebp/0.6.1@bincrafters/stable --outdated -r upload_repo
WARN: No matching packages to remove for libwebp/0.6.1@bincrafters/stable
```

**Comment by theirix** [comment]
@SSE4 I am doing the same thing now :)

**Comment by theirix** [comment]
Cleaned all outdated packages!

**Comment by theirix** [comment]
There is a problem with metadata for 1.0.0, search gives `ERROR: Service Error. [Remote: bincrafters]`. Posted to slack.

**Comment by theirix** [comment]
@danimtb just wondering, how is it going? Is the problem fixed now?

**Comment by danimtb** [comment]
Sorry @theirix but the Bintray Team seems to be still investigating the issue related to this package.

I have cloned all the packages including the corrupted one into my own repo on bintray so it could be reproduced in case the Bincrafters' one changes. Let's wait until the end of this week to make a decision.

Sorry guys

**Comment by theirix** [comment]
Absolutely no problem, I'll wait.

**Comment by danimtb** [comment]
HI @theirix and @SSE4,

Finally we got response fron the Bintray team and it seems the issue is not trivial to reproduce. They have tracked down the problem and will continue with further investigation for next BIntray deployments.

We will work with them to report similar issues in the future and it would be very helpul for us if you could please report any trouble you have with Bintray that could be related to this.

To push this inclusion forward lets follow the steps below:

1. Delete corrupted package: `conan remove libwebp/0.6.1@bincrafters/stable -p ddbab2d75d666065f9399961a36b2bf562a6d261 -r bincrafters`
2. Remove outdated packages: `conan remove libwebp/0.6.1@bincrafters/stable --outdated -r bincrafters`
3. At this point we should be good to go but if it is OK with you lets retrigger the CI to finally rebuild all packages to stay safe.

Hope all of this makes sense. Thanks a lot for the collaboration.

**Comment by theirix** [comment]
Great news, glad to hear!

I'll perform these steps.

**Comment by theirix** [comment]
@danimtb you mentioned removing a package 0.6.1 in your comment. Anyway I run it but searching for 1.0.0 is still failing.
```
conan search 'libwebp/1.0.0@bincrafters/stable' -r bincrafters --table /tmp/foo.html
ERROR: Service Error. [Remote: bincrafters]
```

**Comment by danimtb** [comment]
@theirix did you removed the corrupted package in the remote?

I still see the `ddbab2d75d666065f9399961a36b2bf562a6d261 `package there. Did the remove fail?

I just tried with my own repository and it worked. Could you check it please?

**Comment by theirix** [comment]
@danimtb yes, I tried to remove this package from 0.6.1. Removing from 1.0.0 and searching works, thanks!

**Comment by theirix** [comment]
Rebuilt, done.

**Comment by danimtb** [comment]
yeah, my mistake. I was talking all the time about 1.0.0 sorry. I will wait until rebuild finishes and check everything again

**Comment by danimtb** [comment]
And finally this is accepted into conan-center! Thanks you so much @theirix :)
