### ISSUE TITLE
Inclusion request review for pugixml

### ISSUE THREAD

**Issue by danimtb** [bincrafters/community#265]
## Inclusion Request Review

This is a review for [pugixml/1.8.1@bincrafters/stable (bincrafters/public-conan)](https://github.com/bincrafters/conan-pugixml) inclusion request to conan-center.
This review follows the [inclusion guidelines of third party libraries](http://docs.conan.io/en/latest/uploading_packages/bintray/conan_center_guide.html#inclusion-guidelines-for-third-party-libraries).

### Package
pugixml/1.8.1@bincrafters/stable
pugixml/1.9@bincrafters/stable

#### Recipe quality
- [x] Git public repository
- [x] Recipe fields
- [x] Linter
- [x] Updated
Note as from [conan 1.3.0](https://docs.conan.io/en/latest/changelog.html#april-2018), CMake helper handles fpic automatically, so there is no need to set `CMAKE_POSITION_INDEPENDENT_CODE` anymore.
- [x] Clean
- [x] test_package
- [x] Raise errors on invalid configurations
- [x] LICENSE of the recipe
- [x] LICENSE of the library

#### CI Integration
- [x] Provide at least one CI configuration (header only)
- [x] (If not header only) CI configurations for Linux/MacOSX/Windows

#### Bintray Package Information
- [x] Description
- [x] Licenses
- [x] Tags
- [x] Maturity
- [x] Website (if any)
- [x] Issue tracker
- [x] Version control

### Additional comments

Just a minor issue and it should be good to go! 👍

**Comment by uilianries** [comment]
Done!

https://github.com/bincrafters/conan-pugixml/pull/3
https://github.com/bincrafters/conan-pugixml/pull/4

Also, I included the support to Apple clang 9.1

![pugixml/1.9@bincrafters/stable](https://screenshotscdn.firefoxusercontent.com/images/7471f11d-ed8c-478c-8e17-9717b9e6d15e.png)

![pugixml/1.8.1@bincrafters/stable](https://screenshotscdn.firefoxusercontent.com/images/e1c3a9de-68ba-46b8-a4fb-0f5bfae438df.png)

**Comment by danimtb** [comment]
Accepted into conan-center! Thanks once again @uilianries 😃
