### ISSUE TITLE
Inclusion request for leptonica/1.75.1@bincrafters/stable

### ISSUE THREAD

**Issue by lasote** [bincrafters/community#266]
## Inclusion Request Review

This is a review for [leptonica/1.75.1@bincrafters/stable (bincrafters/public-conan)](https://github.com/bincrafters/conan-leptonica) inclusion request to conan-center.
This review follows the [inclusion guidelines or third-party libraries](http://docs.conan.io/en/latest/uploading_packages/bintray/conan_center_guide.html#inclusion-guidelines-for-third-party-libraries).

### Package
leptonica/1.75.1@bincrafters/stable

#### Recipe quality
- [x] Git public repository
- [x] Recipe fields
- [x] Linter
- [] Updated
- The fPIC Management is now (1.3) automatically managed by the CMake build helper, just FYI, the way we (both conan team and bincrafters) were managing this is wrong:

    ```
    cmake.definitions["CMAKE_POSITION_INDEPENDENT_CODE"] = self.options.fPIC
    ```

    CMake by default, adjust `CMAKE_POSITION_INDEPENDENT_CODE` to True when the library is shared, but once you specify it by hand, like this case, you need to activate it also when shared:
  
    ```
    cmake.definitions["CMAKE_POSITION_INDEPENDENT_CODE"] = self.options.fPIC or self.options.shared
    
    ```

    But anyway Conan is doing it automatically now, so remove it and we are good.

- [x] Clean
- [x] test_package
- [x] Raise errors on invalid configurations
- [x] LICENSE of the recipe
- [x] LICENSE of the library

#### CI Integration
- [x] Provide at least one CI configuration (header only)
- [x] (If not header only) CI configurations for Linux/MacOSX/Windows

#### Bintray Package Information
- [x] Description
- [x] Licenses
- [x] Tags
- [x] Maturity
- [x] Website (if any)
- [x] Issue tracker
- [x] Version control

### Additional comments

 
Missing Packages for apple-clang 9.1

**Comment by theirix** [comment]
Thanks for the review!
Already working for clang 9.1, fPIC improvement and updated dependencies for Leptonica 1.76.0. I will backport it to 1.75.1 soon.

**Comment by theirix** [comment]
Updated and rebuilt on CI both versions.

**Comment by lasote** [comment]
Perfect. Accepting! many thanks @theirix

**Comment by theirix** [comment]
Thanks!
