### ISSUE TITLE
Update Clang 9.1 for official Bincrafters package

### ISSUE THREAD

**Issue by uilianries** [bincrafters/community#269]
### Description of Problem, Request, or Question
Hi! I just executed **conan-clang-update** to update our official packages on Conan center. @lasote opened some issues days ago, reporting outdated packages.

The log generated during the update is [here](https://gist.github.com/uilianries/c9c8050946eba89fbe235d5ed3750ed2)

All follow PRs are related to update Clang 9.1:

- [x] https://github.com/bincrafters/conan-fmt/pull/6
- [x] https://github.com/bincrafters/conan-fmt/pull/7
- [x] https://github.com/bincrafters/conan-gflags/pull/2
- [x] https://github.com/bincrafters/conan-zstd/pull/2
- [x] https://github.com/bincrafters/conan-zstd/pull/3
- [x] https://github.com/bincrafters/conan-openal/pull/3
- [x] https://github.com/bincrafters/conan-gtest/pull/15
- [x] https://github.com/bincrafters/conan-gtest/pull/16
- [x] https://github.com/bincrafters/conan-lz4/pull/4
- [x] https://github.com/bincrafters/conan-libjpeg-turbo/pull/1
- [x] https://github.com/bincrafters/conan-libiconv/pull/6
- [x] https://github.com/bincrafters/conan-sqlite3/pull/4
- [x] https://github.com/bincrafters/conan-libcurl/pull/10
- [x] https://github.com/bincrafters/conan-libxml2/pull/4
- [x] https://github.com/bincrafters/conan-libxml2/pull/5
- [x] https://github.com/bincrafters/conan-libssh2/pull/1
- [x] https://github.com/bincrafters/conan-glog/pull/2
- [x] https://github.com/bincrafters/conan-lzma/pull/5
- [x] https://github.com/bincrafters/conan-log4cplus/pull/5
- [x] https://github.com/bincrafters/conan-log4cplus/pull/6
- [ ] https://github.com/bincrafters/conan-harfbuzz/pull/6

As you can see, the list is huge and the CI is unstable, so I'll need help to finish this task.

/cc @lasote @SSE4 @solvingj @theirix

**Comment by theirix** [comment]
Great! I'm specifically after libxml2, libssh2, libjpeg-turbo.
libcurl is WIP because blocked by #261

**Comment by uilianries** [comment]
Some jobs failed during the build. I'll wait for ALL green on stable CI status to check as finished. As we know, both Travis and Appveyor are not totally stable, so they could fail during any job, even after to merge on stable branch.

**Comment by SSE4** [comment]
everything except harfbuzz is merged, which requies ragel_installer update

**Comment by uilianries** [comment]
Awesome! Thanks guys! You rock!

I'm going to work on ragel_installer at evening. I opened the issue https://github.com/bincrafters/community/issues/271 to track this.

**Comment by theirix** [comment]
all versions of libcurl (including the newest ome 7.60.0) are fully rebuilt too.

**Comment by uilianries** [comment]
I would consider finish this issue. Only harfbuzz is blocked, but is not because clang version.

**Comment by SSE4** [comment]
I am closing this one, as we have dedicated issue for harfbuzz/ragel_installer
