### ISSUE TITLE
conan-botan : handle clang_abi issue in conanfile.py configure()

### ISSUE THREAD

**Issue by solvingj** [bincrafters/community#27]
The following exists in the `build.py` file for CI. It seems it would be safer overall to explicitly disallow such configuration in the `configure()` method of `conanfile.py`.  However, interested in discussing further if there are other reasons/factors for doing it this way. 

https://github.com/bincrafters/conan-Botan/blob/stable/2.1.0/build.py#L54

```
def _fix_clang_abi(build):
    compiler = build.settings['compiler']
    libcxx = build.settings['compiler.libcxx']
    if compiler == 'clang' and libcxx == 'libstdc++':
        build.settings['compiler.libcxx'] = 'libstdc++11'
    return build
```

**Comment by SSE4** [comment]
as botan is written in C++11, it will require C++11 compliant standard library (libstdc++11 or libc++)
linking it with different standard library will end up in issues, so such configuration should be explicitly disallowed in configure() method. libstdc++ build shouldn't silently fall back into libstdc++11.

**Comment by fmorgner** [comment]
AFAICT there are already checks in place in `conanfile.py`. I removed the fallback on the 2.1.0 testing branch. Will cherry-pick on success

**Comment by solvingj** [comment]
this is done, build is currently failling, but that is separate issue.
