### ISSUE TITLE
[Qt] error when trying to build with openssl

### ISSUE THREAD

**Issue by Blubbz0r** [bincrafters/community#277]
### Description of Problem, Request, or Question

When setting option "openssl" to "yes", the build fails with the following error:

```
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.6.4
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
+ cd qtbase
+ C:\.conan\gy99n1kz\1\qt5\qtbase\configure.bat -top-level -opensource -confirm-license -nomake examples -nomake tests -prefix C:/.conan\cole4tpq\1 -debug -opengl desktop -openssl
Perl not found in PATH. Aborting.
Qt/5.11@bincrafters/stable:
Qt/5.11@bincrafters/stable: ERROR: Package '6aee9b08c159348af6fa3ce2111ab7da204c5134' build failed
Qt/5.11@bincrafters/stable: WARN: Build folder C:/.conan\gy99n1kz\1
ERROR: Qt/5.11@bincrafters/stable: Error in build() method, line 130
        self._build_msvc(args)
while calling '_build_msvc', line 166
        self.run("%s && configure %s" % (vcvars, " ".join(args)))
        ConanException: Error 1 while executing set "VSCMD_START_DIR=%CD%" && call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC/Auxiliary/Build/vcvarsall.bat" amd64 && configure -opensource -confirm-license -nomake examples -nomake tests -prefix C:/.conan\cole4tpq\1 -debug -opengl desktop -openssl
```

### Package Details (Include if Applicable)
* Package Name/Version: **qt/5.11**
* Operating System: **Windows 10**
* Compiler+version: **Visual Studio 2017**
* Docker image: **lasote/conangcc72**

### Steps to reproduce (Include if Applicable)

1. Clone https://github.com/bincrafters/conan-qt
1. Apply the fix from [this](https://github.com/bincrafters/conan-qt/pull/2) MR (otherwise, building with Visual Studio will not be possible)
1. run `conan create . user/channel -o Qt:openssl=yes`

**Comment by Blubbz0r** [comment]
Is the "openssl" option actually correct at all?

If it is set to "yes", a `self.requires("OpenSSL/1.0.2l@conan/stable")` is added to requirements and `-openssl` is added to the configure flags. a) I don't see a `-openssl` switch when running `configure.bat --help`. I only see these:

```
Network options:

  -ssl ................. Enable either SSL support method [auto]
  -no-openssl .......... Do not use OpenSSL [default on Apple and WinRT]
  -openssl-linked ...... Use OpenSSL and link to libssl [no]
  -openssl-runtime ..... Use OpenSSL and dynamically load libssl [auto]
  -securetransport ..... Use SecureTransport [auto] (Apple only)
```

b) I'm not sure why the requirement is added, since Qt's configure is not using the package anywhere?

If it is set to "linked", the same requirement is added and '-openssl-linked' is added to the configure flags. However, the paths to the openssl package need to be added as well (see e.g. [here](https://stackoverflow.com/a/24271568/2152166)).

Am I missing something?

**Comment by lucienboillod** [comment]
Sorry for the delay, I'll investigate this asap

**Comment by lucienboillod** [comment]
@Blubbz0r I am working on it right now, did you test the package with "Qt:openssl=linked" flags, we actually don't need to precise the paths since is it a require (conan will set CONAN_LIBS variables). Can you make some tests with linked ?

Concerning the "Qt:openssl=yes" option, I am facing this error:
```
link /NOLOGO /DYNAMICBASE /NXCOMPAT /INCREMENTAL:NO /SUBSYSTEM:CONSOLE "/MANIFESTDEPENDENCY:type='win32' name='M
icrosoft.Windows.Common-Controls' version='6.0.0.0' publicKeyToken='6595b64144ccf1df' language='*' processorArchitecture
='*'" /MANIFEST:embed /OUT:..\..\..\bin\moc.exe @C:\Users\worleyg\AppData\Local\Temp\nm12EE.tmp
Qt5Bootstrap.lib(qbytearray.obj) : error LNK2019: unresolved external symbol compress2 referenced in function "class QBy
teArray __cdecl qCompress(unsigned char const *,int,int)" (?qCompress@@YA?AVQByteArray@@PEBEHH@Z)
Qt5Bootstrap.lib(qbytearray.obj) : error LNK2019: unresolved external symbol uncompress referenced in function "class QB
yteArray __cdecl qUncompress(unsigned char const *,int)" (?qUncompress@@YA?AVQByteArray@@PEBEH@Z)
..\..\..\bin\moc.exe : fatal error LNK1120: 2 unresolved externals
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\link.EXE"' : return code '
0x460'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : return code
'0x2'
Stop.
NMAKE : fatal error U1077: 'cd' : return code '0x2'
Stop.
NMAKE : fatal error U1077: 'cd' : return code '0x2'
Stop.
NMAKE : fatal error U1077: 'cd' : return code '0x2'
Stop.

Qt/5.8.0@vadix/stable: ERROR: Package '8d6d24cc7b3687214215b1b6db6283e2a14dccef' build failed
Qt/5.8.0@vadix/stable: WARN: Build folder C:/.conan\ib28fy\1
ERROR: Qt/5.8.0@vadix/stable: Error in build() method, while calling '_build_msvc', line 183
        % (self.source_dir, vcvars, build_command, " ".join(build_args)))
        ConanException: Error 2 while executing cd qt5 && call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Comm
on7\Tools\../../VC/vcvarsall.bat" amd64 && nmake.exe
```
Configure Qt with openssl seems to be a bit tricky, I will update you asap

**Comment by lucienboillod** [comment]
@SSE4 yes I found this option ```self.options["OpenSSL"].no_zlib = True``` and this flag ```-no-zlib``` but it seems to make no difference. So I will have to require zlib on build

**Comment by Blubbz0r** [comment]
@lucienboillod I ran into the same error with "Qt:openssl=yes" and manually adding Perl to the path.  Did not try with "linked" yet. Will do so when I find the time.

**Comment by Blubbz0r** [comment]
Same error with "Qt:openssl=linked". I've managed to do a successful build with a shared openssl build (inspired by [this](https://github.com/osechet/conan-qt/issues/25). The following steps are required:

* Clone https://github.com/bincrafters/conan-qt
* Apply the fix from this [commit](https://github.com/bincrafters/conan-qt/pull/2/commits/b47ab008698fe16a659430e69c82f375bbc91868) (otherwise, building with Visual Studio will not be possible)
* add `self.requires("strawberryperl/5.26.0@conan/stable")`, which fixes my initial "Perl not found in PATH. Aborting." error
  * I've just put it into `def requirements` and only for "Windows" and when openssl is "yes" or "linked". Not sure if that is the most reasonable place...
* add `self.options["OpenSSL"].no_zlib = True` and `self.options["OpenSSL"].shared = True` after the openssl requires
* run conan create . user/channel -o Qt:openssl=yes

However, a shared openssl is not really what I'm looking for. Will play around with it a bit more.

**Comment by Blubbz0r** [comment]
With the following steps:

* Clone https://github.com/bincrafters/conan-qt
* Apply the fix from this [commit](https://github.com/bincrafters/conan-qt/pull/2/commits/b47ab008698fe16a659430e69c82f375bbc91868) (otherwise, building with Visual Studio will not be possible)
* add `self.requires("strawberryperl/5.26.0@conan/stable")`, which fixes my initial "Perl not found in PATH. Aborting." error
  * I've just put it into `def requirements` and only for "Windows" and when openssl is "yes" or "linked". Not sure if that is the most reasonable place...
* add `self.options["OpenSSL"].no_zlib = True` after the openssl requires
* run conan create . user/channel -o Qt:openssl=linked

I get:

```
Generating Code...
        link /NOLOGO /DYNAMICBASE /NXCOMPAT /DEBUG /DLL /SUBSYSTEM:WINDOWS /VERSION:5.11 /MANIFEST:embed /OUT:..\..\lib\Qt5Networkd.dll @C:\Users\habrich\AppData\Local\Temp\nm6505.tmp
   Creating library ..\..\lib\Qt5Networkd.lib and object ..\..\lib\Qt5Networkd.exp
libeay32.lib(cryptlib.obj) : error LNK2019: unresolved external symbol __imp_GetProcessWindowStation referenced in function OPENSSL_isservice
libeay32.lib(cryptlib.obj) : error LNK2019: unresolved external symbol __imp_GetUserObjectInformationW referenced in function OPENSSL_isservice
libeay32.lib(cryptlib.obj) : error LNK2019: unresolved external symbol __imp_MessageBoxW referenced in function OPENSSL_showfatal
libeay32.lib(rand_win.obj) : error LNK2019: unresolved external symbol __imp_CreateCompatibleBitmap referenced in function readscreen
libeay32.lib(rand_win.obj) : error LNK2019: unresolved external symbol __imp_DeleteObject referenced in function readscreen
libeay32.lib(rand_win.obj) : error LNK2019: unresolved external symbol __imp_GetDeviceCaps referenced in function readscreen
libeay32.lib(rand_win.obj) : error LNK2019: unresolved external symbol __imp_GetDIBits referenced in function readscreen
libeay32.lib(rand_win.obj) : error LNK2019: unresolved external symbol __imp_GetObjectW referenced in function readscreen
libeay32.lib(rand_win.obj) : error LNK2019: unresolved external symbol __imp_GetDC referenced in function readscreen
libeay32.lib(rand_win.obj) : error LNK2019: unresolved external symbol __imp_ReleaseDC referenced in function readscreen
..\..\lib\Qt5Networkd.dll : fatal error LNK1120: 10 unresolved externals
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\link.EXE"' : return code '0x460'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: 'cd' : return code '0x2'
Stop.
NMAKE : fatal error U1077: 'cd' : return code '0x2'
Stop.
NMAKE : fatal error U1077: 'cd' : return code '0x2'
Stop.
Qt/5.11@habrich/testing:
Qt/5.11@habrich/testing: ERROR: Package 'ddfcfb59077dc5bec658ccb3ba727b0fe11d1f0e' build failed
Qt/5.11@habrich/testing: WARN: Build folder C:/.conan\2utz7jhh\1
ERROR: Qt/5.11@habrich/testing: Error in build() method, line 132
        self._build_msvc(args)
while calling '_build_msvc', line 168
        self.run("%s && %s %s" % (vcvars, build_command, " ".join(build_args)))
        ConanException: Error 2 while executing set "VSCMD_START_DIR=%CD%" && call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC/Auxiliary/Build/vcvarsall.bat" amd64 && nmake.exe
```

These functions come from user32.lib and gd32i.lib. However, right now I'm unsure how to add these in the conanfile.py 😒 .

**Comment by lucienboillod** [comment]
Hi! can you make some tests with my master branch ? https://github.com/lucienboillod/conan-qt

On my side, with Windows (msvc) both conan create . user/channel -o Qt:openssl=linked and -o Qt:openssl=yes are compiling fine, but I did not test, do you have something to test it quickly ? :blush: 

After we know that msvc is working I'll do the same for linux

**Comment by Blubbz0r** [comment]
Have tested with `Qt:openssl=linked` (also did `Qt:tools=True`, `Qt:translations=True`, `Qt:svg=True`, since it is needed for my project). Both `conan create` and compiling my project against the created Qt version worked fine.

**Comment by lucienboillod** [comment]
Nice ! thanks a lot for the outputs !

Do you have by any chance a quick way to test your project on linux and mingw ? (just updated my master branch). Otherwise I will do some tests.

**Comment by Blubbz0r** [comment]
Not really. Only working with Windows/MSVC at the moment.

**Comment by ttdd11** [comment]
@Blubbz0r Looking to reproduce your build and new to conan. Tried your steps but the source is different now so I'm not sure if they apply. Received this error early on probably unrelated to the different source ERROR: Failed requirement 'mysql-connector-c/6.1.11@bincrafters/stable' from 'qt/5.12.1@user/channel'

Any ideas?

**Comment by Blubbz0r** [comment]
@ttdd11 qt/5.12.1 is definitely working fine for me. In your error: Why is it saying "qt/5.12.1@**user/channel**"? Was that a typo or did you not use the package directly from bincrafters (e.g. did you download the conanfile.py and export it yourself manually)?

**Comment by ttdd11** [comment]
I tried to follow your instructions identically. Obviously that isnt how
this works. My goal is to build qt with openssl in static linking. Is this
your setup?

**Comment by Blubbz0r** [comment]
The instructions above should not be needed anymore. It should only be necessary to do the following:

1. In conanfile add qt/5.12.1@bincrafters/stable as requirement
2. In conanfile add qt:openssl=True as option
3. Add the bincrafters remote to conan (https://bincrafters.readthedocs.io/en/latest/using_packages.html#adding-the-bincrafters-repository-as-a-conan-remote)
4. Run conan install

That works fine for me with visual studio 2017 x86.

**Comment by ttdd11** [comment]
Okay thank you I will try this is vs2015 x64.

**Comment by ttdd11** [comment]
Okay I can't get this build to work but that's probably because I don't
know how to use conan properly.

What I did was this:
1. install conan using pip
2. clone your source
3. in requirements of conanfile.py add
self.requires("qt/5.12.1@bincrafters/stable")
under requirements
4. run this line conan remote add bincrafters
https://api.bintray.com/conan/bincrafters/public-conan
5. run conan install qt/5.12.1@bincrafters/stable

I know I'm not doing this correctly and should be able to get this working.
Any help would be greatly appreciated.

**Comment by Blubbz0r** [comment]
I'm actually unsure what the second step "clone your source" is exactly. You shouldn't need to manually clone anything. The steps to use the qt package for a CMake based project (that's the only environment where I've used conan yet) should be:

1. install conan using pip
2. add a conanfile.py to your existing or newly created project where you want to use the qt package
    * add self.requires("qt/5.12.1@bincrafters/stable") under requirements
    * add self.options["qt"].openssl = True
3. in the main CMakeLists.txt of your project, add
```
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()
```
4. add bincrafters remote (using your command from step 4; this only needs to be done once)
5. run `conan install {PATH_TO_THE_CONANFILE_PY_FROM_STEP_2}` in your CMake binary dir
    * this will generate conanbuildinfo.cmake (as well as two other files) referenced above

Btw: Not sure if you already gave the conan documentation a try, but the [getting started](https://docs.conan.io/en/latest/getting_started.html) and [using packages](https://docs.conan.io/en/latest/using_packages.html) sections might have a few useful details as well as step-by-step tutorials.

Also, there is a slack server for C++ (https://cpplang.now.sh/) with a #conan channel where you might find other people able to provide help with your questions about your first steps with conan 😉
