### ISSUE TITLE
Inclusion-request review for http-parser

### ISSUE THREAD

**Issue by danimtb** [bincrafters/community#279]
## Inclusion Request Review

This is a review for [http-parser/2.8.1@bincrafters/stable (bincrafters/public-conan)](https://github.com/bincrafters/conan-http-parser) inclusion request to conan-center.
This review follows the [inclusion guidelines of third party libraries](http://docs.conan.io/en/latest/uploading_packages/bintray/conan_center_guide.html#inclusion-guidelines-for-third-party-libraries).

### Package
http-parser/2.8.1@bincrafters/stable

#### Recipe quality
- [x] Git public repository
- [x] Recipe fields
- [x] Linter
- [x] Updated
- [x] Clean
- [x] test_package
- [x] Raise errors on invalid configurations
- [x] LICENSE of the recipe
- [x] LICENSE of the library

#### CI Integration
- [x] Provide at least one CI configuration (header only)
- [x] (If not header only) CI configurations for Linux/MacOSX/Windows

#### Bintray Package Information
- [x] Description
- [x] Licenses
- [x] Tags
- [x] Maturity
- [x] Website (if any)
- [x] Issue tracker
- [x] Version control

### Additional comments

Great job! just a minor issue and it is ready for the central repo 😄 
http-parser seems to be a pure C library, please remove `libcxx`:

```
def configure(self):
    del self.settings.compiler.libcxx
```

cc/ @theirix

**Comment by theirix** [comment]
It's already tracked in #274.
By the way, libcxx was removed a long time ago. Maybe you reviewed another version?

**Comment by danimtb** [comment]
Sorry, my fault. Closing this
