### ISSUE TITLE
conan-cpprestsdk - new minor version

### ISSUE THREAD

**Issue by solvingj** [bincrafters/community#28]
Microsoft has released new minor version.  Need to publish an update after the refresh.

**Comment by uilianries** [comment]
Okay, I can to do this later.

**Comment by solvingj** [comment]
Thank you kindly.

**Comment by uilianries** [comment]
Started new branch testing branch here: https://github.com/bincrafters/conan-cpprestsdk/tree/testing/2.10.1

**Comment by ImpressiveDev** [comment]
Is a stable release of 2.10.1 still planned?

**Comment by solvingj** [comment]
Yessir, now that we have some good boost packages, this should be imminent.

**Comment by SSE4** [comment]
faced issue with docker package tools: https://github.com/conan-io/conan-docker-tools/pull/35

**Comment by solvingj** [comment]
thanks for update

**Comment by SSE4** [comment]
now blocked by https://github.com/conan-community/conan-bzip2/issues/8

**Comment by SSE4** [comment]
now blocked by https://github.com/conan-community/community/issues/1

**Comment by SSE4** [comment]
new version is on bintray
