### ISSUE TITLE
Bump fmt to version 5.0.0

### ISSUE THREAD

**Issue by drrlvn** [bincrafters/community#283]
The fmt library version 5.0.0 was released, please bump the package.

https://github.com/fmtlib/fmt/releases/tag/5.0.0

**Comment by uilianries** [comment]
Some information about this new version:

- MSVC 12 is not supported by fmt 5.0.0 (read the changelog)
- cppstd is necessary to make sure -std=c++11

**Comment by uilianries** [comment]
Done! 

https://bintray.com/bincrafters/public-conan/fmt%3Abincrafters/5.0.0%3Astable
