### ISSUE TITLE
[Qt] Missing options for all "essentials" sub modules

### ISSUE THREAD

**Issue by ImpressiveDev** [bincrafters/community#285]
### Description of Problem, Request, or Question

Some Qt modules marked with an "essentials" status (when looking at Qt's `.gitmodules` file) cannot be enabled from the Conan recipe options list. 

More specifically, the "qtdeclarative" one, which compiles the QML library. A lot of people uses QML, adding this option would be a great added feature. 

Here is the list of all "essentials" sub modules that cannot be configured from the options list:

- qtdeclarative
- qtmultimedia
- qtdoc
- qtrepotools
- qtqa
- qtquickcontrols

It would be great if these could be configurable. 

### Package Details (Include if Applicable)
* Package Name/Version: **Qt/5.11**

**Comment by lucienboillod** [comment]
Nice! thanks for the feedback, indeed it would be great. I will look after this as soon as others Qt issues are done. Also if you have any others feedback don't hesitate :blush:
