### ISSUE TITLE
[gtest] Support for android, emscripten, uwp and ios

### ISSUE THREAD

**Issue by birsoyo** [bincrafters/community#286]
I have my own gtest recipe, but I would like to start using bincrafters recipes as much as I can. Towards that goal gtest is my first target to try this.

In general (not just gtest) the most obvious mismatch seems to be platform support. I need a recipe that could build for android, emscripten, uwp and ios in addition to what current bincrafters recipes support.

First, is supporting these platforms something bincrafters would be interested in? 

Second, supporting all these platforms, add additional complexity to the recipes and I am not sure what would be a good way to add these to bincrafters recipes. Any pointers would be appreciated. Relevant code from my recipe is below.

* I am using my own `ndk` recipe, with 2 minor patches to the original so that ndk provided android cmake toolchain works, without standalone toolchain generation.
* I am using my own `emscripten` recipe.
* `ios` is still experimental. I am currently planing to develop a cmake toolchain file specific for ios. Something like this, [vtk ios toolchain](https://github.com/Kitware/VTK/blob/master/CMake/ios.toolchain.xcode.cmake).

```python
        if self.settings.os == 'Android':
            _CMAKE_ANDROID_ABI_MAP = {
                'armv8'   : 'arm64-v8a',
                'armv7'   : 'armeabi-v7a',
                'x86'     : 'x86',
                'x86_64'  : 'x86_64',
            }

            defs['ANDROID_PLATFORM'] = f'android-{self.settings.os.api_level}'
            defs['ANDROID_ABI'] = _CMAKE_ANDROID_ABI_MAP[str(self.settings.arch)]
            defs['ANDROID_STL'] = 'c++_static'
            defs['ANDROID_CPP_FEATURES'] = 'rtti exceptions'
            defs['CMAKE_TOOLCHAIN_FILE'] = self.deps_user_info['ndk'].cmake_toolchain_path
        elif self.settings.os == 'Emscripten':
            defs['CMAKE_TOOLCHAIN_FILE'] = self.deps_user_info['emscripten'].cmake_toolchain_path
        elif self.settings.os == 'WindowsStore':
            defs['CMAKE_SYSTEM_NAME'] = 'WindowsStore'
            defs['CMAKE_SYSTEM_VERSION'] = '10.0.16299.0'
        elif self.settings.os == 'iOS':
            defs['CMAKE_CXX_COMPILER_WORKS'] = True
            defs['CMAKE_C_COMPILER_WORKS'] = True
            if self.settings.arch == 'x86_64':
                cxxflags = f'-mios-simulator-version-min={self.settings.os.version}'
                defs['CMAKE_OSX_ARCHITECTURES'] = 'x86_64'
                defs['CMAKE_OSX_SYSROOT'] = '/Applications/Xcode.9.2.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk'
            elif self.settings.arch == 'armv7':
                cxxflags = f'-mios-version-min={self.settings.os.version}'
                defs['CMAKE_OSX_ARCHITECTURES'] = 'armv7'
                defs['CMAKE_OSX_SYSROOT'] = '/Applications/Xcode.9.2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk'
            elif self.settings.arch == 'armv8':
                cxxflags = f'-mios-version-min={self.settings.os.version}'
                defs['CMAKE_OSX_ARCHITECTURES'] = 'arm64'
                defs['CMAKE_OSX_SYSROOT'] = '/Applications/Xcode.9.2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk'
```

**Comment by SSE4** [comment]
hi @birsoyo 
in general, I am also interested in additional platforms support, like iOS, Android, UWP and Emscripten, and working on adding them. however, adding additional logic to recipes don't scale well, and it's much better to contribute to conan itself in order to provide support for such platforms out of the box, so modifications in recipes are not needed.
so the best approach is to think on how to generalize quirks we're using in recipes to support additional platforms and integrate them into conan codebase.

**Comment by SSE4** [comment]
I am closing this issue for now. please open feature requests about supporting each of mentioned platforms in conan bug-tracker.
