### ISSUE TITLE
Inclusion request for PEGTL

### ISSUE THREAD

**Issue by pleroux0** [bincrafters/community#288]
### Description of Problem, Request, or Question

I'm following the steps from 
http://bincrafters.readthedocs.io/en/latest/contributing_to_packages/package_guidelines_faq.html
to include the package 
https://bintray.com/pleroux0/pleroux0/pegtl%3Apleroux0

Disclosure: I am *not* the author of PEGTL,but the author is not interested in supporting the conan package himself.

"While we are open to having the PEGTL included in as many package managers as reasonable" and  "We support package maintainers, but are not package maintainers ourselves - there are simply too many." from https://github.com/taocpp/PEGTL/pull/59

I have setup TravicCL, but AppVeyor is running into issues including my repo. As soon as their support gets back to me then I'll do the README.md with the bincrafters style.

The License is currently under my name (MIT), but that is easily changed. Is there anything else required from my side?

**Comment by uilianries** [comment]
Hi @pleroux0 !

Looks promising! I'm going to pull your recipe into bincrafters and rectify some points.

Thanks!

**Comment by uilianries** [comment]
Done!

https://github.com/bincrafters/conan-pegtl
https://bintray.com/bincrafters/public-conan/pegtl%3Abincrafters
https://travis-ci.org/bincrafters/conan-pegtl
https://ci.appveyor.com/project/BinCrafters/conan-pegtl

**Comment by pleroux0** [comment]
You guys work fast! Thanks! I'll check what was missing for future contributions.
