### ISSUE TITLE
Publish gflags improvements

### ISSUE THREAD

**Issue by dimi309** [bincrafters/community#29]
Hi everyone,

I see my pull request has been accepted here:

https://github.com/bincrafters/conan-gflags/tree/testing/2.2.1

Don't forget to publish to stable if you agree with the changes 😄 

We need these improvements to then proceed to publish glog too.

**Comment by uilianries** [comment]
LGTM

Just a point. I don't know if is really necessary [set](https://github.com/bincrafters/conan-gflags/blob/testing/2.2.1/conanfile.py#L43) `CMAKE_POSITION_INDEPENDENT_CODE`
As described in [docs](https://cmake.org/cmake/help/v3.4/prop_tgt/POSITION_INDEPENDENT_CODE.html#prop_tgt:POSITION_INDEPENDENT_CODE) this value is automatic.

**Comment by dimi309** [comment]
A lot of @lasote's packages were setting this to "true" by default, even for static builds, on the contrary to what is mentioned in the documentation. I have also had one case, that of vorbis, the current version of which is built using autotools and has ogg as a dependency and wouldn't work without ogg having the -fPIC parameter and it would crash telling me that I have to set it to true. I could not fix that no matter what I did with fpic in vorbis. So I think it is a bit risky to be leaving this parameter to "default" usage. In my humble opinion, we should even add it to our template..

**Comment by dimi309** [comment]
... or perhaps we should decide on following a default behaviour like cmake and harmonise, also across the packages that use autotools. That would mean changing a lot of packages though... It might be useful in any case to know @lasote's thoughts on this (I had learned about fPIC from his code).

**Comment by uilianries** [comment]
I agree with you, for both assumptions.

Would be nice to make a decision about how to use -fPIC and converge the statement in our template.

**Comment by sigmoidal** [comment]
It depends what you do with the library. AFAIK one compiles a lib with fPIC if it will be linked from another shared lib, otherwise position independent code is not necessary. 

My suggestion is to set it as an option in the template to allow people to switch it on/off. Default behavior may be good to be the same as that of cmake. Either way it very much depends on what users will use the libs for and one size doesn't fit all in this case.

**Comment by solvingj** [comment]
Good thoughts.  Would someone be willing to ask @lasote for his reasoning on his packages?

**Comment by solvingj** [comment]
@dimi309 go ahead and merge to stable with the current changes.

**Comment by dimi309** [comment]
Done
