### ISSUE TITLE
boost_fiber recipe does not build the library

### ISSUE THREAD

**Issue by krzysztofwos** [bincrafters/community#290]
### Description of Problem, Request, or Question
`conan-boost_fiber` recipe does not build the library. It installs header files only.

### Package Details (Include if Applicable)
* Package Name/Version: **boost_fiber/1.66.0**
* Operating System: **Linux Ubuntu 16.04**
* Compiler+version: **clang-6.0**
* Docker image: **lasote/conanclang60**

### Steps to reproduce (Include if Applicable)
Trying to run `conan test` as follows
```
conan test test_package boost_fiber/1.66.0@bincrafters/testing --build missing
```
Results in the following error
```
Undefined symbols for architecture x86_64:
  "boost::fibers::fiber::start_()", referenced from:
      _main in test_package.cpp.o
  "boost::fibers::context::terminate()", referenced from:
      boost::fibers::worker_context<main::$_0>::run_(boost::context::continuation&&) in test_package.cpp.o
  "boost::fibers::context::~context()", referenced from:
      _main in test_package.cpp.o
      boost::fibers::worker_context<main::$_0>::~worker_context() in test_package.cpp.o
      boost::fibers::worker_context<main::$_0>::~worker_context() in test_package.cpp.o
  "typeinfo for boost::fibers::context", referenced from:
      typeinfo for boost::fibers::worker_context<main::$_0> in test_package.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/test_package] Error 1
make[1]: *** [CMakeFiles/test_package.dir/all] Error 2
make: *** [all] Error 2
ERROR: PROJECT: Error in build() method, line 15
        cmake.build()
        ConanException: Error 512 while executing cmake --build '/Users/kwos/Work/conan-boost_fiber/test_package/build/cd3601ac1ef07679242d04c71a1f8cb266c63e70' '--' '-j8'
```

**Comment by SSE4** [comment]
@krzysztofwos unfortunately I wasn't able to reproduce it, could you possibly upload a full log, please?

**Comment by krzysztofwos** [comment]
@SSE4 I am actually having some trouble reproducing the issue on Ubuntu Xenial. I usually develop on macOS and there it's easy enough to reproduce the problem. To do that, however, I had to modify the `test_package.cpp` file to contain the following:

```c++
#include <boost/fiber/all.hpp>

int main()
{
	boost::fibers::buffered_channel<int> chan{2};
	boost::fibers::condition_variable_any cnd_count{};
}
```

The error is the same as above:

```c++
Undefined symbols for architecture x86_64:
  "boost::fibers::context::active()", referenced from:
      boost::fibers::buffered_channel<int>::close() in test_package.cpp.o
  "boost::fibers::context::schedule(boost::fibers::context*)", referenced from:
      boost::fibers::buffered_channel<int>::close() in test_package.cpp.o
```

The problem seems to be that the `libboost_fiber.a` library is not being built. Running

```bash
find $HOME/.conan/data/boost_fiber/ -name "*.a"
```

Returns nothing.

How can I produce a log that would be most useful for you?

**Comment by krzysztofwos** [comment]
Attached the [output](https://github.com/bincrafters/community/files/2123791/out.txt) from running

```bash
conan test -s compiler.version=9.1 test_package boost_fiber/1.66.0@bincrafters/stable --build missing
```

My compiler is the following

```
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

The OS

```
Darwin MacBook-Pro-2013.local 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64
```

**Comment by krzysztofwos** [comment]
[Here](https://github.com/bincrafters/community/files/2123799/out.txt) is the output from trying to build the package. As noted above, the library is not built:

```
boost_fiber/1.66.0@bincrafters/stable: Calling package()
boost_fiber/1.66.0@bincrafters/stable package(): Copied 1 '.jam' file: jamroot.jam
boost_fiber/1.66.0@bincrafters/stable package(): Copied 61 '.hpp' files:
boost_fiber/1.66.0@bincrafters/stable: Package '6b355e9f1fc832175cc28e8bdab286b7737850f2' created
boost_fiber/1.66.0@bincrafters/stable (test package): Generator cmake created conanbuildinfo.cmake
```

**Comment by SSE4** [comment]
I am back, will check it on my Mac Book Pro and let you know

**Comment by SSE4** [comment]
yes, I see the same issue
it seems like library requires C++11 (according to the https://www.boost.org/doc/libs/1_66_0/libs/fiber/doc/html/fiber/overview.html), but somehow C++11 support is not detected:
```
    - Boost.Config Feature Check: cxx11_auto_declarations : no
    - Boost.Config Feature Check: cxx11_constexpr : no
    - Boost.Config Feature Check: cxx11_defaulted_functions : no
    - Boost.Config Feature Check: cxx11_final : no
    - Boost.Config Feature Check: cxx11_hdr_mutex : no
    - Boost.Config Feature Check: cxx11_hdr_regex : no
    - Boost.Config Feature Check: cxx11_hdr_tuple : no
    - Boost.Config Feature Check: cxx11_lambdas : no
    - Boost.Config Feature Check: cxx11_noexcept : no
    - Boost.Config Feature Check: cxx11_nullptr : no
    - Boost.Config Feature Check: cxx11_rvalue_references : no
    - Boost.Config Feature Check: cxx11_template_aliases : no
    - Boost.Config Feature Check: cxx11_thread_local : no
    - Boost.Config Feature Check: cxx11_variadic_templates : no
```

**Comment by SSE4** [comment]
that's right, boost_generator doesn't pass `-std=c++11` only for clang + libc++ (which is default on OSX):
https://github.com/bincrafters/conan-boost_generator/blob/stable/1.66.0/conanfile.py#L336

**Comment by SSE4** [comment]
in general, I suppose boost_generator should also handle conan's cppstd setting (https://docs.conan.io/en/latest/howtos/manage_cpp_standard.html)
and boost_fiber should refuse to build for cppstd < 11 (add check to `configure` method)
@solvingj @grafikrobot WDYT?

**Comment by SSE4** [comment]
@solvingj @grafikrobot if you don't mind, I am gonna push changes to boost generator which should address multiple issues about C++ standard. please let me know if you have any objections.

**Comment by SSE4** [comment]
related to the:
https://github.com/bincrafters/conan-boost_generator/pull/5
https://github.com/bincrafters/conan-boost_generator/pull/1

**Comment by SSE4** [comment]
related to the:
https://github.com/bincrafters/community/issues/336
https://github.com/bincrafters/community/issues/298

**Comment by SSE4** [comment]
also related to the:
https://github.com/bincrafters/community/issues/193

**Comment by SSE4** [comment]
I am closing for now, as fix was applied
