### ISSUE TITLE
Bump msgpack to version 3.0.1

### ISSUE THREAD

**Issue by drrlvn** [bincrafters/community#291]
Last version available from bincrafters is 2.1.5

https://github.com/msgpack/msgpack-c/releases/tag/cpp-3.0.1

**Comment by uilianries** [comment]
Done!

https://github.com/bincrafters/conan-msgpack/tree/stable/3.0.1
https://bintray.com/bincrafters/public-conan/msgpack%3Abincrafters

![msgpack/3.0.1](https://screenshotscdn.firefoxusercontent.com/images/91e46586-9fda-49ba-b2c4-86dbf2ac4fe8.png)
