### ISSUE TITLE
Inclusion request for operators

### ISSUE THREAD

**Issue by pleroux0** [bincrafters/community#293]
### Description of Problem, Request, or Question

I'm following the steps from
http://bincrafters.readthedocs.io/en/latest/contributing_to_packages/package_guidelines_faq.html
to include the package
https://bintray.com/pleroux0/pleroux0/operators%3Apleroux0

Disclosure: I am not the author of operators

I have setup TravicCL and Appveyor and the bintray repository under my name for testing.

Just let me know if there is anything needed from my side.

**Comment by lucienboillod** [comment]
Thank you for the submission! the repo url is https://github.com/pleroux0/conan-operators right ?

**Comment by pleroux0** [comment]
Yes

**Comment by uilianries** [comment]
Hi @pleroux0 !

It will be a pleasure to receive your package!

I see no errors on your recipe. I'm going to copy your recipe into our repo.

Thanks so much.

**Comment by uilianries** [comment]
Done!

https://github.com/bincrafters/conan-operators
https://bintray.com/bincrafters/public-conan/operators%3Abincrafters
https://ci.appveyor.com/project/BinCrafters/conan-operators
https://travis-ci.org/bincrafters/conan-operators

@pleroux0 All yours commits were preserved.

Please, fell free to re-open this issue if you find any problem.
