### ISSUE TITLE
Invalid relocation error on CentOS with fmt/4.1.0

### ISSUE THREAD

**Issue by rdeterre** [bincrafters/community#296]
### Description of Problem, Request, or Question

Hi,

I'm building an application that uses fmt on a 7 machine and the following error appears:

```
ld: /home/user/.conan/data/fmt/4.1.0/bincrafters/stable/package/b759e10106fc0b4923414b05bb78eba0bbc8b30b/lib/libfmt.a(format.cc.o): unrecognized relocation (0x2a) in section `.text'
ld: final link failed: Bad value
```

The machine uses the Red Hat devtoolset 4 that comes with GCC 5.3.1 (`gcc (GCC) 5.3.1 20160406 (Red Hat 5.3.1-6)`). Here is the profile that is used:

```
$ cat ~/.conan/profiles/default
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=5
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]
```

Running `conan install --build fmt` makes this error disappear.

### Package Details (Include if Applicable)
* Package Name/Version: **fmt/4.1.0**
* Operating System: **Linux CentOS 7**
* Compiler+version: **gcc-5.3**

### Steps to reproduce (Include if Applicable)

Building any application that uses fmt shows this issue on this machine. Here is an example one:

conanfile.py:
``` python
from conans import ConanFile, CMake
import os


class TestFMT(ConanFile):
    requires = "fmt/4.1.0@bincrafters/stable"

    settings = "os", "compiler", "build_type", "arch"
    generators = "cmake"

    def build(self):
        cmake = CMake(self)
        self.run('cmake "{}" {}'.format(
                 self.source_folder, cmake.command_line))
        self.run('cmake --build . %s' % cmake.build_config)
```

CMakeLists.txt:
``` cmake
cmake_minimum_required(VERSION 3.1)

include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()

add_executable(testfmt main.cpp)
target_link_libraries(testfmt ${CONAN_LIBS_FMT})
```

main.cpp:
``` c++
#include "fmt/format.h"

int main() {
  fmt::print("test");
}

```

With these files in a directory, calling `conan install .` followed by `conan build .` shows the issue

**Comment by uilianries** [comment]
Hi @rdeterre 

I'm going to check it.

**Comment by uilianries** [comment]
I have used docker image centos:7 + devtoolset-4 + conan 1.3.3 and I followed all your steps. Unfortunately, I didn't see any error.

```
[conan@5a70546a7271 project]$ gcc --version
gcc (GCC) 5.3.1 20160406 (Red Hat 5.3.1-6)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[conan@5a70546a7271 project]$ conan profile new default --detect
Found gcc 5.3
gcc>=5, using the major as version
Profile created with detected settings: /home/conan/.conan/profiles/default
[conan@5a70546a7271 project]$ conan profile show default
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=5
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]
[conan@5a70546a7271 project]$ ls
CMakeLists.txt  conanfile.py  main.cpp
[conan@5a70546a7271 project]$ mkdir build && cd build
[conan@5a70546a7271 build]$ conan install ..
fmt/4.1.0@bincrafters/stable: Not found in local cache, looking in remotes...
fmt/4.1.0@bincrafters/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt
[==================================================] 166B/166B        
Downloading conanfile.py
[==================================================] 2.7KB/2.7KB      
Downloading conan_export.tgz
[==================================================] 758B/758B        
PROJECT: Installing /project/conanfile.py
Requirements
    fmt/4.1.0@bincrafters/stable from 'conan-center'
Packages
    fmt/4.1.0@bincrafters/stable:b759e10106fc0b4923414b05bb78eba0bbc8b30b

fmt/4.1.0@bincrafters/stable: Retrieving package b759e10106fc0b4923414b05bb78eba0bbc8b30b from remote 'conan-center' 
Downloading conanmanifest.txt
[==================================================] 993B/993B        
Downloading conaninfo.txt
[==================================================] 496B/496B        
Downloading conan_package.tgz
[==================================================] 140.7KB/140.7KB  
fmt/4.1.0@bincrafters/stable: Package installed b759e10106fc0b4923414b05bb78eba0bbc8b30b
PROJECT: Generator cmake created conanbuildinfo.cmake
PROJECT: Generator txt created conanbuildinfo.txt
PROJECT: Generated conaninfo.txt
[conan@5a70546a7271 build]$ conan build ..
Project: Running build()
-- The C compiler identification is GNU 5.3.1
-- The CXX compiler identification is GNU 5.3.1
-- Check for working C compiler: /opt/rh/devtoolset-4/root/usr/bin/cc
-- Check for working C compiler: /opt/rh/devtoolset-4/root/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/rh/devtoolset-4/root/usr/bin/c++
-- Check for working CXX compiler: /opt/rh/devtoolset-4/root/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: called by CMake conan helper
-- Conan: Compiler GCC>=5, checking major version 5
-- Conan: Checking correct version: 5
-- Conan: Using cmake global configuration
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
-- Conan: C++ stdlib: libstdc++
-- Configuring done
-- Generating done
-- Build files have been written to: /project/build
Scanning dependencies of target project
[ 50%] Building CXX object CMakeFiles/project.dir/main.cpp.o
[100%] Linking CXX executable bin/testfmt
[100%] Built target testfmt
[conan@5a70546a7271 build]$ bin/testfmt
test
```

As you can see, the package id is the same.

The image that I used to validate those steps can be found here: https://hub.docker.com/r/uilianries/centosconan/

I'll ask for help to figure out what might have happened.

**Comment by uilianries** [comment]
@SSE4 Excellent observation!

**Comment by SSE4** [comment]
/cc @lasote @memsharded @danimtb
this problems keep popping up pretty often, any plan to address this in conan itself or at least official recommendation/position on this type of issues with glibc?

**Comment by lasote** [comment]
I still think we shouldn't model different glibc versions in Conan center, because the number of binaries and missing packages will explode.

However I agree we can do it better managing this situation.

The first and easy recommendation is to rebuild the packages from sources, using "--build", once the packages are built against the native glibc it should work.

We are analyzing some improvements to the remotes model for conan 1.5, so you could upload these own made binaries to a local server and still bean able to mix the recipes from Conan center and the binaries from the local server. Currently you can manage caching in the local server all the needed deps and prioritizing the local remote in the remotes list. The only downside is that you cannot keep pointing to the Conan center recipes, so you cannot automatically get the latest improvements from the community.

We could also improve the detection of the glibc version to somehow ease the task of detecting it (opt-in) and modeling it in the settings.yml. And of course document a how-to to refer when this issue pops up.

These are only ideas that we will need to test.

**Comment by memsharded** [comment]
Does anyone has a clear grasp of what distros have an old, incompatible glibc?

- Adding a glibc version to settings would make the thing unusable
- But maybe a setting ``old_glibc: [None, True]`` (None is the default that doesn't affect existing binaries), which those distros could set to True, could help.

**Comment by SSE4** [comment]
@lasote I believe with careful and smart implementation it will not cause explosion of number of binaries.
I mean if glibc version will be forward compatible version, package with glibc=2.14 will not require rebuild of package for glibc=2.17, while glibc=2.10 will require rebuild on the user's machine and will not attempt to use package glibc=2.14 (which obviously will fail anyway). if glibc version setting will work in such way, then amount of linux packages on conan center will remain the same as before.

**Comment by SSE4** [comment]
@memsharded this might be helpful https://gist.github.com/wagenet/35adca1a032cec2999d47b6c40aa45b1

**Comment by bc-lee** [comment]
If conan implements range-based version search for glibc (for example, a system with glibc=2.23 (Ubuntu 16.04 LTS) can consume libraries with glibc<=2.23 and it can use a library with glibc=2.17 (CentOS 7) by searching in remote and local packages with glibc=2.23, 2.22, 2.21 and so on), it would be awesome if conan works with libstdc++ versions ( libstdc++.so.6.0.18 , libstdc++.so.6.0.23 and so on).

**Comment by SSE4** [comment]
we need to convert this one into conan feature request
