### ISSUE TITLE
Probably invalid libcurl findCURL.cmake 

### ISSUE THREAD

**Issue by lasote** [bincrafters/community#297]
### Description of Problem, Request, or Question

Hi @theirix, @solvingj @uilianries , I'm making some tests with the new Conan 1.4 cmake generators and the libcurl library to prepare a blog post explaining them.

I found an issue, the custom `FindCURL.cmake` file (probably inherited from my original recipe) is assuming that the variables `${CONAN_INCLUDE_DIRS_LIBCURL}` and `${CONAN_LIB_DIRS_LIBCURL}` are present, but it is only true if you are using the `cmake` generator and including the `conanbuildinfo.cmake` file. 

https://github.com/bincrafters/conan-libcurl/blob/stable/7.52.1/FindCURL.cmake

I'm wondering if we still want to keep that customized `FindCURL.cmake` file. Since some time ago, I stopped to provide custom find package scripts, because the ones from the cmake installation become inaccesible, and the recipe gets outdated with the improvements that kitware introduces (for example, the target creation). In other recipes where the original find_package was not finding the libraries (because of different names ,corresponding to not tested by kitware configurations) I decided to package the libraries renaming first.  

What do you think? Now the find_package is broken unless you specify the cmake generator, it doesn't sound good.

### Package Details (Include if Applicable)
* Package Name/Version: **libcurl/7.52.1**
* Operating System: **OSX high sierra**
* Compiler+version: **apple clang 9.1**

**Comment by lasote** [comment]
Any thoughts on this?

**Comment by theirix** [comment]
Sorry, forgot this issue.

Could you please link to the idea of the cmake change in Conan 1.4?

I don't remember why we are including this. It's here since the recipe imported from lasote/conan-libcurl. FindCURL.cmake is available as a cmake standard module even for the ancient cmake 2.8.0. Of course it's better to have a standard module and I prefer to drop those from recipes.

I'll try to rebuild recipes dependent on libcurl on an isolated machine without recipe-provided findcurl.cmake.

**Comment by lasote** [comment]
In 1.4 we provide two new generators for cmake, extracted from "https://blog.conan.io/2018/05/30/New-conan-release-1-4.html":

```
New cmake_paths and cmake_find_package generators
After all the feedback collected regarding CMake integration, we focused the development with the goal of providing a transparent way to integrate CMake relying on find_package(), especially useful for Conan package consumers.

This led to two different generators:

cmake_find_package generator creates one Find<package_name>.cmake file for each dependency. This will make each find_package in you CMakeLists.txt point to the dependency solved by Conan after a conan install. Read more.

cmake_paths generator creates a conan_paths.cmake file with CMAKE_MODULE_PATH and CMAKE_PREFIX_PATH variables adjusted to the dependencies folders. This also allow users to integrate Conan without modifying the CMakeLists.txt: cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_paths.cmake. Read more.
```

So, the custom FindCURL.cmake makes no sense, especially if it is attached to the `cmake` generator, because it won't work unless you are using it.

**Comment by lasote** [comment]
To clarify, we DO NOT recommend to replace the usage of the classic `cmake` generator with the new ones. It is just a new approach that could be interesting to a consumer of packages.

**Comment by lasote** [comment]
Any progress with this? Could I help?

**Comment by theirix** [comment]
Sorry, I was a little busy these weeks.
As promised I'll try to drop a package-provided FindCURL.cmake (so the cmake-provided file is used) and build a few dependent packages. I can check it this evening with Linux and Mac. Could you please do the same for Windows?

**Comment by lasote** [comment]
The best way to really make sure it works is with the test_package, forcing to use `find_package(CURL)`  after remote the package-provided `FindCurl`. 
I'll try it in Windows and submit a PR if a library rename is needed (my recommended approach, but not always agreed by people)

**Comment by lasote** [comment]
I'm running all the common configurations using the native `findCurl` in the test_package. I took a look at the native findCurl and to the names, we declare in the `package_info()` and I'm pretty sure we can remove it safely, they cover all the possible names.
Anyway, I will inform again when all the configurations are built in windows.

**Comment by lasote** [comment]
Every configuration working on Windows using the native findCurl.

**Comment by lasote** [comment]
Diff for 7.52.1 (also upgrading openssl):

```
diff --git a/conanfile.py b/conanfile.py
index da6a444..b613f45 100644
--- a/conanfile.py
+++ b/conanfile.py
@@ -15,7 +15,7 @@ class LibcurlConan(ConanFile):
     homepage = "http://curl.haxx.se"
     license = "MIT"
     exports = ["LICENSE.md"]
-    exports_sources = ["FindCURL.cmake", "lib_Makefile_add.am", "CMakeLists.txt"]
+    exports_sources = ["lib_Makefile_add.am", "CMakeLists.txt"]
     generators = "cmake"
     source_subfolder = "source_subfolder"
     settings = "os", "arch", "compiler", "build_type"
@@ -101,7 +101,7 @@ class LibcurlConan(ConanFile):
             elif self.settings.os == "Windows" and self.options.with_winssl:
                 pass
             else:
-                self.requires.add("OpenSSL/1.0.2n@conan/stable")
+                self.requires.add("OpenSSL/1.0.2o@conan/stable")
         if self.options.with_libssh2:
             if self.settings.compiler != "Visual Studio":
                 self.requires.add("libssh2/1.8.0@bincrafters/stable")
@@ -126,7 +126,6 @@ class LibcurlConan(ConanFile):

     def package(self):
         # Everything is already installed by make install
-        self.copy("FindCURL.cmake")
         self.copy(pattern="COPYING*", dst="licenses", src=self.source_subfolder, ignore_case=True, keep_path=False)

         # Copy the certs to be used by client
@@ -179,10 +178,6 @@ class LibcurlConan(ConanFile):
                                   "define CURL_MAX_WRITE_SIZE 16384",
                                   "define CURL_MAX_WRITE_SIZE 10485760")

-        tools.replace_in_file('FindCURL.cmake',
-                              'set(CURL_VERSION_STRING "0")',
-                              'set(CURL_VERSION_STRING "%s")' % self.version)
-
         # temporary workaround for DEBUG_POSTFIX (curl issues #1796, #2121)
         # introduced in 7.55.0
         if self.version_components[0] == 7 and self.version_components[1] >= 55:
```

**Comment by theirix** [comment]
@lasote , thank you! I checked the build on Linux too – it works well.
Removed finder in the branch testing/7.52.1 (except the OpenSSL upgrade, it should go to different one).

**Comment by lasote** [comment]
looks green: https://travis-ci.org/bincrafters/conan-libcurl/builds/388148563
About the OpenSSL, np, it is not important for me right now.

**Comment by theirix** [comment]
I have merged changes to stable/7.52.1, built successfully. Please try it.

**Comment by lasote** [comment]
I detected some issue with Bintray and the new package: https://conan.bintray.com/v1/conans/libcurl/7.52.1/bincrafters/stable/download_urls

They are investigating. 😭

**Comment by lasote** [comment]
Now is working fine. They found a concurrency issue and they expect to solve it soon, but anyway, the libcurl 7.52.1 is working perfectly. Thanks. You could proceed for the rest of versions

**Comment by theirix** [comment]
Done!
