### ISSUE TITLE
Publish glog

### ISSUE THREAD

**Issue by dimi309** [bincrafters/community#30]
I've put it here:

https://github.com/bincrafters/conan-glog

I don't have proof of a successful build online because, for the build to work, the gflags improvements have to be published firtst: https://github.com/bincrafters/community/issues/29

But I've tested it locally and it's ok as far as I have seen.

**Comment by uilianries** [comment]
I'll put in CI (Travis/AppVeyor)

**Comment by uilianries** [comment]
AppVeyor: https://ci.appveyor.com/project/BinCrafters/conan-glog/build/1.0.1
Travis: https://travis-ci.org/bincrafters/conan-glog/builds/318534657

**Comment by dimi309** [comment]
Thanks! As I've mentioned, my changes to the gflags package have to be published before the glog builds can work.

**Comment by uilianries** [comment]
I see. Your gflags package LGTM. Let's wait one more review to publish.

Regards.

**Comment by dimi309** [comment]
There's the fPIC issue, I added another comment. Maybe it's a detail but maybe it's as good as time as any to talk about it, decide something and get it out of the way 😄

**Comment by solvingj** [comment]
Thanks to both of you.  Yes as soon as gflags is done we'll build this one.

**Comment by solvingj** [comment]
Appveyor is failing with most recent builds of GFlags.  Can someone please investigate?

**Comment by dimi309** [comment]
Hi everyone and sorry, I've been away from my dev terminal for a while and I still am unfortunately. Until then, if someone can look into this note that it is an error that appears in gflags when the conanfile does not contain the following in package_info:

```
if self.settings.os == "Windows":
            self.cpp_info.libs.extend(['shlwapi'])
        else:
self.cpp_info.libs.extend(["pthread"])
```
Of course, the published version does contain it from what I see. Maybe we could try adding this to glog too. Darius had it there but I removed it thinking that it's sufficient to only have it in gflags. Maybe I was wrong but it worked locally...

**Comment by SSE4** [comment]
actually, it should be:
```
if self.settings.os == "Windows":
            self.cpp_info.libs.extend(['shlwapi'])
elif self.settings.os == "Linux":
            self.cpp_info.libs.extend(["pthread"])
```

**Comment by dimi309** [comment]
I could be wrong but I have the impression that you need pthread in mingw and in macos too. In any case, unless proven otherwise and with the exception of fPIC for mingw and some statically linked libs for macos, I usually assume that what's good for linux is also good for macos and mingw so I don't use a lot of os == Linux conditionals, preferring a "Windows or else" policy...

**Comment by dimi309** [comment]
It seems that the package still builds on my machine, even without shlwapi and pthread. The problem is probably somewhere else. I'm looking into it.. (might take a while though)

**Comment by SSE4** [comment]
then I'd prefer to add explicit conditions for Linux and MinGW, rather than making assumption everything but Windows needs pthread.
1. as I understand from conan settings, MinGW may use pthread, but it also may use other threading models `threads: [None, posix, win32] #  Windows MinGW` (from conan's **settings.yml**)
2. there are platforms where linking to pthread fails (e.g. Android)

**Comment by dimi309** [comment]
Ok, it sounds like a good idea to start adding explicit conditions for macos, mingw and linux. Of course the mingw condition will probably be "gcc on windows" grouping it together with cygwin, unless something changes with regard to this matter: https://github.com/conan-io/conan/issues/2120

**Comment by dimi309** [comment]
I have another finding. Building glog with my locally built gflags succeeds. Building it against the gflags version published on bintray fails with the error that we also see in appveyor...

**Comment by dimi309** [comment]
... and there is no difference in the conan packaging source code between my locally built gflags and the one checked into the bincrafters stable branch...

**Comment by dimi309** [comment]
Status update: Linking to shlwapi in glog didn't do the trick (I've tried just now). It turns out it is sufficient to extend libs in gflags. What did work is always building glog with shared gflags like I do here:

https://github.com/dimi309/conan-glog/commit/383a0758356e7512582988613c140d70f221620a

I'm not sure why given the above-mentioned shlwapi situation. I have not yet created a pull request for this change because I am now having what I think is a package tools / images related error on both appveyor and travis:

https://travis-ci.org/dimi309/conan-glog/jobs/319561201
https://ci.appveyor.com/project/coding3d/conan-glog/build/job/0cus2pjluolc1jn7

... and sadly I've run out of time again ☹️ 
I'm just leaving this info here in case someone comes up with a solution.

**Comment by solvingj** [comment]
Thanks for the great notes! The notes are key for people to pick it up and move it forwarwd. Who knew Glog would be such a challenge, I'm glad we're tackling it here.

**Comment by dimi309** [comment]
Thanks @solvingj . I am usually around, I just have very little access to my dev platform these days, so to speak.
I don't know if I overlooked something but this error really looks like it came out of nowhere and is related to a new version of conan package tools or something. Doesn't anyone get the same with other builds?

**Comment by dimi309** [comment]
My bad... The package couldn't build from my repository because it had a dependency (gflags) and build.py won't run in that case if it's not on bincrafters. (My own conan repo is not called public-conan, that's why)
Now we have the problem that there is no prebuilt shared gflags, which glog uses by default as I've mentioned above:

https://ci.appveyor.com/project/BinCrafters/conan-glog/build/1.0.5/job/ywdl22s1sddf5wfv

To cut a long story short, there are two ways to fix this. Either we add "--build missing" to glog, or we make the shared build the default one for gflags or force it somehow. 

What do you guys think?

**Comment by dimi309** [comment]
My deepest apologies for making everyone dizzy with this package. The problem was that the glog cmakelists file was automatically building some unit tests which, since they were not known to conan, were not being linked to gflags properly. I've disabled these unit tests and everything should be fine now.

**Comment by solvingj** [comment]
Hah, I had been writing up my suggestions for the past 5 minutes , but i still wasn't sure what was happening.  Glad to see you figured it out :)

**Comment by dimi309** [comment]
Sorry man... 🙁

**Comment by dimi309** [comment]
😭 https://ci.appveyor.com/project/BinCrafters/conan-glog/build/1.0.6

**Comment by dimi309** [comment]
Ok, I've fixed it and now there are no crashes in the build. The only problem is that the VS 14 job times out:

https://ci.appveyor.com/project/BinCrafters/conan-glog/build/1.0.7

I don't know if someone can find a way around this and then publish to stable. Unfortunately, it is more than likely that I won't be able to work on this for the next few days.

**Comment by sigmoidal** [comment]
@dimi309  try on appveyor with Previous Visual Studio 2015 ?

I think they recently updated the images and it may be the current VS2015 image may be buggy.

**Comment by dimi309** [comment]
Thanks @sigmoidal ! I didn't know that. Unfortunately it looks like I won't be able to code for a few days, so if someone else has the time to look into this and publish this library, that would be great 😸

**Comment by dimi309** [comment]
To my understanding, glog has now been published.
