### ISSUE TITLE
PEGTL by the authors is now in conan-center

### ISSUE THREAD

**Issue by danimtb** [bincrafters/community#301]
So finally the library authors of PEGTL (@d-frey) submitted their library an it is now in conan-center: https://bintray.com/taocpp/public-conan/pegtl:taocpp

We talked together with @solvingj that best approach is to let both packages (bincrafters' and taocpp's) live together in conan-center to not brake users and let them choose. 

As authors are commited to maintain the conan packages, I suppose bincrafters is not going to keep updating their package. At this point I would like to know what you think about placing a `[DEPRECATED]` tag in the bintray description of PEGTL to warn users or even something like `self.output.warn("[Deprecated] Use pegtl/2.5.2@taocpp/stable")` in the conanfile??

cc/ @uilianries

**Comment by uilianries** [comment]
This is really great! @taocpp is an excellent project source. I'm really happy to know about this.

Yes, the idea about insert [deprecated] warning looks good to me. I'll take this.

Also, on next taocpp packages, I'll try to help the author to create the Conan recipes and avoid to create on Bincrafters repo.

Thanks for the report.

**Comment by danimtb** [comment]
Thanks a lot @uilianries! Let's keep this issue open until the message is added 😉

**Comment by uilianries** [comment]
Done!

the recipe is updated and pushed in Bintray.

https://github.com/bincrafters/conan-pegtl/blob/stable/2.5.1/conanfile.py#L17

https://travis-ci.org/bincrafters/conan-pegtl/builds/388734866
https://ci.appveyor.com/project/BinCrafters/conan-pegtl/build/1.0.5

**Comment by solvingj** [comment]
Since this will happen with other libs in future, I'm thinking of formalizing this a bit, where we update the Bintray and Github repositories to say: "This package will remain here, but users are recommended to depend on the newer official package here" ... with links and such.  Perhaps a new section at the top of the readme for some of these.  I really like inserting the warning in the recipe, that was a great idea.  In future, maybe our message can make it slightly more clear why it was deprecated, maybe just saying suggested package is "Official" from library author.

**Comment by danimtb** [comment]
I will wait for those messages to close this 😉 Thanks!

**Comment by uilianries** [comment]
@solvingj just published the draft on Slack:

> ## Package Deprecation Notice
> 
> The author of this library has taken ownership of the public Conan package for this library, which can be found at the following links:  
> 
> https://github.com/taocpp/PEGTL  
> https://bintray.com/taocpp/public-conan/pegtl%3Ataocpp  
> 
> Bincrafters will keep this version of the package on Github and Bintray for some unspecified amount of time (typically several weeks), however it will no longer be maintained or supported and will be removed without any further warning or notice. Users are advised to update their projects to use the official Conan package maintained by the library author immediately.

Looks pretty good IMO.

**Comment by uilianries** [comment]
@solvingj  just update the README file:

https://github.com/bincrafters/conan-pegtl/blob/stable/2.5.1/README.md

**Comment by danimtb** [comment]
Thank you guys!
