### ISSUE TITLE
taocpp operators inclusion to conan-center

### ISSUE THREAD

**Issue by danimtb** [bincrafters/community#302]
@uilianries, @d-frey just got this in the Conan Inclusion Request's panel 🤣 

![image](https://user-images.githubusercontent.com/10808592/41028029-cb64c5de-6978-11e8-86ef-3d1009e82f94.png)

Let's join efforts an decide here what we should do. Are you both willing to collaborate in the same package?

**Comment by uilianries** [comment]
@d-frey is the @taocpp author, his version should be accepted :smile: I'll keep Bincrafters as deprecated.

Anyway, @d-frey I would like to help you to create Conan recipes for @taocpp projects. WDYT?

**Comment by danimtb** [comment]
excellent!

I think @d-frey, it would be better to name the package with original name "operators" so users are not confused with that new name. Don't you think so?

It is your decision (or @taocpp 's one), just tell me 😄 

Thanks a lot guys!

**Comment by uilianries** [comment]
I'd prefer `operators@taocpp` but is just my opinion.

**Comment by solvingj** [comment]
The conversation on naming has moved to slack. This can probably be closed.

**Comment by danimtb** [comment]
No that we have the slack channel it is totally ok. Thanks a lot for the reminder @solvingj and just ping me if you need something else for the inclusion request!
