### ISSUE TITLE
ffmpeg: request for profile inclusion

### ISSUE THREAD

**Issue by madebr** [bincrafters/community#304]
### Description of Problem, Request, or Question
I'm using bincrafters' ffmpeg for the openrw project with non-standard options.
This causes ffmpeg to be rebuilt for every travis/appveyor job.

Might it be possible to add these binaries?

The options are:
```
ffmpeg:iconv=False
ffmpeg:vdpau=False
ffmpeg:vaapi=False
ffmpeg:xcb=False
```
for Linux (and mac but untested so ignore Apple)

and
```
ffmpeg:iconv=False
ffmpeg:qsv=False
```
for Windows

### Package Details (Include if Applicable)
* Package Name/Version: **ffmpeg/4.0**
* Operating System: **Linux Ubuntu 16.04** + **Fedora** + **Arch**
* Compiler+version: **gcc-7** (and higher) + **Visual Studio 2017**

### Steps to reproduce (Include if Applicable)
conanfile at https://github.com/madebr/openrw/blob/conan/conanfile.py
profiles at https://github.com/madebr/openrw/tree/conan/scripts/conan

**Comment by SSE4** [comment]
@madebr I've built branch with required config, please check it out

**Comment by madebr** [comment]
Seems to work!
Thanks!
