### ISSUE TITLE
sdl2: request for profile inclusion

### ISSUE THREAD

**Issue by madebr** [bincrafters/community#305]
### Description of Problem, Request, or Question
I'm using bincrafters' sdl2 for the openrw project with non-standard options.
This causes sdl2 to be rebuilt for every travis job.

Might it be possible to add these binaries?

The options are:
```
sdl2:esd=False
sdl2:wayland=True
sdl2:x11=True
```
for Linux

### Package Details (Include if Applicable)
* Package Name/Version: **sdl2/2.0.8**
* Operating System: **Linux Ubuntu 16.04** + **Fedora** + **Arch**
* Compiler+version: **gcc-7** (and higher)

### Steps to reproduce (Include if Applicable)
conanfile at https://github.com/madebr/openrw/blob/conan/conanfile.py
profiles at https://github.com/madebr/openrw/tree/conan/scripts/conan

**Comment by SSE4** [comment]
@madebr  I've built branch with required config, please check it out

**Comment by madebr** [comment]
There is something wrong with the sdl2 package on linux, at least on Linux.
When launching my application, the error
```
E [exception] SDL_CreateWindow failed: SDL not configured with OpenGL/GLX support
```
appears.
I had this problem earlier when creating the sdl2 package with wayland=False.

Reproducer: (you need gta3 to run the game, but the error is reproduceable without data)
Clone openrw repo + create config file:
```
git clone -b conan https://github.com/madebr/openrw.git /tmp/openrw
echo "[game]
path=PATH_TO_GTA3_DATA
language=american
[input]
invert_y=0
[window]
width=800
height=600
fullscreen=0
">/tmp/openrw.ini
```

Build using conan using sdl2 on bintray: (The resulting bin/rwgame does not work)
```
conan remove -f sdl2*
rm -rf /tmp/openrw/build
mkdir -p /tmp/openrw/build && cd /tmp/openrw/build
conan install /tmp/openrw -pr /tmp/openrw/scripts/conan/linux
conan build /tmp/openrw
/tmp/openrw/build/bin/rwgame -c /tmp/openrw.ini
```

Build using conan using locally built sdl2: (The resulting bin/rwgame works)
```
conan remove -f sdl2*
rm -rf /tmp/openrw/build
mkdir -p /tmp/openrw/build && cd /tmp/openrw/build
conan install /tmp/openrw -pr /tmp/openrw/scripts/conan/linux --build sdl2
conan build /tmp/openrw
/tmp/openrw/build/bin/rwgame -c /tmp/openrw.ini
```


Development system properties:
- Fedora 26
- gcc 7.3.1
- conan-sdl2 hash is `7764b093a4ba020fcb1259047bd884ebbdab8140`
- `~/.conan/data/sdl2/2.0.8/bincrafters/stable/package/7764b093a4ba020fcb1259047bd884ebbdab8140/conaninfo.txt`:
```
[settings]
    arch=x86_64
    build_type=Release
    compiler=gcc
    compiler.version=7
    os=Linux

[requires]


[options]
    alsa=True
    arts=False
    directfb=False
    esd=False
    fPIC=True
    iconv=False
    jack=True
    mir=False
    nas=True
    pulse=True
    shared=False
    wayland=True
    x11=True
    xcursor=True
    xinerama=True
    xinput=True
    xrandr=True
    xscrnsaver=True
    xshape=True
    xvm=True

[full_settings]
    arch=x86_64
    build_type=Release
    compiler=gcc
    compiler.version=7
    os=Linux

[full_requires]


[full_options]
    alsa=True
    arts=False
    directfb=False
    esd=False
    fPIC=True
    iconv=False
    jack=True
    mir=False
    nas=True
    pulse=True
    shared=False
    wayland=True
    x11=True
    xcursor=True
    xinerama=True
    xinput=True
    xrandr=True
    xscrnsaver=True
    xshape=True
    xvm=True

[recipe_hash]
    a2bdf55ecd78dd4e3e29f8514600ada8

[env]
```

**Comment by SSE4** [comment]
interesting, I'll take a look

**Comment by SSE4** [comment]
@madebr I've added some missing packages, could you possible give an another try, please?

**Comment by madebr** [comment]
The game is working now!
Thanks for the quick response!
Big :+1: !
