### ISSUE TITLE
cpprestsdk/2.10.1 module machine type 'x64' conflicts with target machine type 'X86'

### ISSUE THREAD

**Issue by sinall** [bincrafters/community#307]
### Package Details (Include if Applicable)
* Package Name/Version: **cpprestsdk/2.10.1**
* Operating System: **Windows 10**
* Compiler+version: **VC++2015**

### Steps to reproduce (Include if Applicable)
conanfile.txt
```
[requires]
cpprestsdk/2.10.1@bincrafters/stable

[generators]
visual_studio

```

Add connanbuildinfo.props into VC++ project property manager.

Compile, then errors show:

> Error	LNK1112	module machine type 'x64' conflicts with target machine type 'X86'

**Comment by SSE4** [comment]
hi @sinall , few questions:
1. as I understand, you're building for x86, is it correct?
2. how do you invoke `conan install`, could you possibly paste full command line?
3. what is your default conan profile? (output of command `conan profile show default`)

**Comment by SSE4** [comment]
@lasote @danimtb @memsharded seems to be bintray problem?

**Comment by danimtb** [comment]
- Installation worked well for me with the profile provided:
  ```
  $ conan install cpprestsdk/2.10.1@bincrafters/stable -pr cpprestsdk_profile
  ```
  I see no problem here with Bintray. My bet is that this was a random connection issue.

- Building an example worked well too, but I had to test with Visual Studio 2017 (my default profile) as I dont have a setup fot VS 2015:
  ```
  $ git clone git@github.com:bincrafters/conan-cpprestsdk.git
  $ cd conan-cpprestsdk
  $ git checkout stable/2.10.1
  $ conan test test_package cpprestsdk/2.10.1@bincrafters/stable -s arch=x86
  ```
Normally those linking erros happen when the package is ill-formed with different arch binaries, which is quite typical if you dont include `conanbuildinfo.cmake` but I think this is not the case. No clue I can see from my side @SSE4 😞

**Comment by SSE4** [comment]
@sinall could you give another try please? it seems to be just a random connection issue

**Comment by sinall** [comment]
@SSE4 `conan install . -s arch=x86` works now.

I'm using Win 10 64bit, Do you know if there a way to config `arch=x86` in ~/.conan.conf, conanfile.txt or other config file?

**Comment by SSE4** [comment]
yes, just edit ~/.conan/profiles/default

**Comment by sinall** [comment]
Great, I love this tool.
