### ISSUE TITLE
CLI11 by the author is now in conan-center

### ISSUE THREAD

**Issue by danimtb** [bincrafters/community#309]
CLI11 was recently accepted into conan-center as an inclusion request from the author.

Now this package an the one contributed by bincrafters live together in conan-center. However, author is commited to maintain his library and set up CI to release conan packages for every new version.

Please add when possible deprecation messages for bincrafters CLI11 package: https://bintray.com/bincrafters/public-conan/cli11%3Abincrafters

Many thanks!

**Comment by solvingj** [comment]
Thanks for the reminder, Done! 
https://github.com/bincrafters/conan-cli11

**Comment by danimtb** [comment]
Thanks @solvingj !
