### ISSUE TITLE
[question] Boost packages for Centos 7 and gcc compiler 4.8.5

### ISSUE THREAD

**Issue by keithrob91** [bincrafters/community#311]
Sorry if this is a really stupid question, I'm new to both Conan and Bincrafters.

I'm using Centos 7 to trial Conan with a view to switching to it within our company, and our software makes heavy use of Boost. Conan don't provide individual Boost library recipes so I was looking at Bincrafters for this.

Problem is, the gcc compiler with Centos 7 is 4.8.5 but the packages provided with Bincrafters only go down to 4.9 (as far as I can tell).

My understanding is that I can't use the provided Bincrafters packages because of this. Is this right? If this is right, is there a  reason you haven't provided packages for this setup?

Cheers in advance.

**Comment by danimtb** [comment]
Hi @keithrob91,

The conan community in general is providing the most used binary configurations but we cannot provide them all. Supporting down to gcc 4.9 is enough for most users.

I you want to use brincrafters (or any other) recipes to build packages for your configuration it should (in most cases) work building from sources. For example:

```
$ conan install boost_regex/1.66.0@bincrafters/stable --build missing
```

After that you can upload the pages to your own bintray repo or private Artifatory CE. Give it a try and let us know! 😄

**Comment by Croydon** [comment]
@keithrob91 Was your question answered?

**Comment by keithrob91** [comment]
Sorry, yes it was.
