### ISSUE TITLE
glm 0.9.9.0 has been released

### ISSUE THREAD

**Issue by madebr** [bincrafters/community#314]
### Description of Problem, Request, or Question
glm 0.9.9.0 has been released May 22, 2018
https://github.com/g-truc/glm/releases
Current version on bintray is 0.9.8.5

### Package Details (Include if Applicable)
* Package Name/Version: **glm/0.9.8.5**

**Comment by SSE4** [comment]
@madebr `glm/0.9.9.0@bincrafters/stable` is now available

**Comment by madebr** [comment]
@SSE4 Thank you very much! The updated version is now in use!
