### ISSUE TITLE
gsl_microsoft (GSL) upstream has released version 1.0.0

### ISSUE THREAD

**Issue by mcquay239** [bincrafters/community#315]
GSL upstream has recently released the first numbered version of the library: https://github.com/Microsoft/GSL/releases/tag/v1.0.0.
The release description states the following: "GSL commits are all CI verified and considered stable. However, we would like to mark significant changes (such as API breaking ones or adding extra functionality) by changing versions.".

The gsl_microsoft package currently uses a date-based versioning scheme, which seems to conflict with the new upstream versioning.
Updating the recipe to the released version seems trivial, but the versioning issue should be probably discussed for a bit before that.

**Comment by solvingj** [comment]
Great to have a proper version to use going forward, will bump ASAP.

**Comment by SSE4** [comment]
@mcquay239 `gsl_microsoft/1.0.0@bincrafters/stable` is now available

**Comment by SSE4** [comment]
I am closing an issue for now, as new version is available. @mcquay239 if you have any other problems with GSL package, please open new issue.
