### ISSUE TITLE
Missing prebuilt package for 'lzma/5.2.3@bincrafters/stable'

### ISSUE THREAD

**Issue by sinall** [bincrafters/community#316]
### Package Details (Include if Applicable)
* Package Name/Version: **lzma/5.2.3**
* Operating System: **Windows 10 64bit**
* Compiler+version: **VC++ 2015  R3**

### Steps to reproduce (Include if Applicable)
conanfile.txt
```
[requires]
lzma/5.2.3@bincrafters/stable

[generators]
visual_studio_multi

[options]
```

conan profile show default
```
Configuration for profile default:

[settings]
arch=x86
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=14
os=Windows
[options]
[build_requires]
[env]

```

PROJECT: Installing D:\Documents\Visual_Studio_2015\Projects\ConanTest\conanfile.txt
Requirements
    lzma/5.2.3@bincrafters/stable from 'conan-center'
Packages
    lzma/5.2.3@bincrafters/stable:10b873a178ffdbd5f8b1274645ac279fd1fe9274

Result:

> Cross-build from 'Windows:x86_64' to 'Windows:x86'
> lzma/5.2.3@bincrafters/stable: WARN: Package is corrupted, removing folder: D:\.conan\data\lzma\5.2.3\bincrafters\stable
> \package\10b873a178ffdbd5f8b1274645ac279fd1fe9274
> lzma/5.2.3@bincrafters/stable: WARN: Can't find a 'lzma/5.2.3@bincrafters/stable' package for the specified options and
> settings:
> - Settings: arch=x86, build_type=Debug, compiler=Visual Studio, compiler.runtime=MD, compiler.version=14, os=Windows
> - Options: shared=False
> - Package ID: 10b873a178ffdbd5f8b1274645ac279fd1fe9274
> 
> ERROR: Missing prebuilt package for 'lzma/5.2.3@bincrafters/stable'
> Try to build it from sources with "--build lzma"
> Or read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package"
> 

conan install . -s build_type=Debug --build lzma

> PROJECT: Installing D:\Documents\Visual_Studio_2015\Projects\ConanTest\conanfile.txt
> Requirements
>     lzma/5.2.3@bincrafters/stable from 'conan-center'
> Packages
>     lzma/5.2.3@bincrafters/stable:10b873a178ffdbd5f8b1274645ac279fd1fe9274
> 
> Cross-build from 'Windows:x86_64' to 'Windows:x86'
> lzma/5.2.3@bincrafters/stable: WARN: Package is corrupted, removing folder: D:\.conan\data\lzma\5.2.3\bincrafters\stable
> \package\10b873a178ffdbd5f8b1274645ac279fd1fe9274
> lzma/5.2.3@bincrafters/stable: WARN: Forced build from source
> lzma/5.2.3@bincrafters/stable: Building your package in D:\.conan\data\lzma\5.2.3\bincrafters\stable\build\10b873a178ffd
> bd5f8b1274645ac279fd1fe9274
> lzma/5.2.3@bincrafters/stable: Copying sources to build folder
> lzma/5.2.3@bincrafters/stable: Generator txt created conanbuildinfo.txt
> lzma/5.2.3@bincrafters/stable: Calling build()
> Skipped sln project upgrade
> WARN: ***** The configuration Debug|x86 does not exist in this solution *****
> WARN: Use 'platforms' argument to define your architectures
> Microsoft (R) Build Engine version 14.0.25420.1
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> Build started 2018-06-15 1:22:31 AM.
>      1>Project "D:\.conan\data\lzma\5.2.3\bincrafters\stable\build\10b873a178ffdbd5f8b1274645ac279fd1fe9274\xz-5.2.3\wi
>        ndows\xz_win.sln" on node 1 (liblzma target(s)).
>      1>ValidateSolutionConfiguration:
>          Building solution configuration "Debug|Win32".
>      1>Project "D:\.conan\data\lzma\5.2.3\bincrafters\stable\build\10b873a178ffdbd5f8b1274645ac279fd1fe9274\xz-5.2.3\wi
>        ndows\xz_win.sln" (1) is building "D:\.conan\data\lzma\5.2.3\bincrafters\stable\build\10b873a178ffdbd5f8b1274645
>        ac279fd1fe9274\xz-5.2.3\windows\liblzma.vcxproj" (2) on node 1 (default targets).
>      2>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The
>        build tools for v120 (Platform Toolset = 'v120') cannot be found. To build using the v120 build tools, please in
>        stall v120 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Proj
>        ect menu or right-click the solution, and then selecting "Retarget solution". [D:\.conan\data\lzma\5.2.3\bincraf
>        ters\stable\build\10b873a178ffdbd5f8b1274645ac279fd1fe9274\xz-5.2.3\windows\liblzma.vcxproj]
>      2>Done Building Project "D:\.conan\data\lzma\5.2.3\bincrafters\stable\build\10b873a178ffdbd5f8b1274645ac279fd1fe92
>        74\xz-5.2.3\windows\liblzma.vcxproj" (default targets) -- FAILED.
>      1>Done Building Project "D:\.conan\data\lzma\5.2.3\bincrafters\stable\build\10b873a178ffdbd5f8b1274645ac279fd1fe92
>        74\xz-5.2.3\windows\xz_win.sln" (liblzma target(s)) -- FAILED.
> 
> Build FAILED.
> 
>        "D:\.conan\data\lzma\5.2.3\bincrafters\stable\build\10b873a178ffdbd5f8b1274645ac279fd1fe9274\xz-5.2.3\windows\xz
>        _win.sln" (liblzma target) (1) ->
>        "D:\.conan\data\lzma\5.2.3\bincrafters\stable\build\10b873a178ffdbd5f8b1274645ac279fd1fe9274\xz-5.2.3\windows\li
>        blzma.vcxproj" (default target) (2) ->
>        (PlatformPrepareForBuild target) ->
>          C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: Th
>        e build tools for v120 (Platform Toolset = 'v120') cannot be found. To build using the v120 build tools, please
>        install v120 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Pr
>        oject menu or right-click the solution, and then selecting "Retarget solution". [D:\.conan\data\lzma\5.2.3\bincr
>        afters\stable\build\10b873a178ffdbd5f8b1274645ac279fd1fe9274\xz-5.2.3\windows\liblzma.vcxproj]
> 
>     0 Warning(s)
>     1 Error(s)
> 
> Time Elapsed 00:00:00.92
> lzma/5.2.3@bincrafters/stable:
> lzma/5.2.3@bincrafters/stable: ERROR: Package '10b873a178ffdbd5f8b1274645ac279fd1fe9274' build failed
> lzma/5.2.3@bincrafters/stable: WARN: Build folder D:\.conan\data\lzma\5.2.3\bincrafters\stable\build\10b873a178ffdbd5f8b
> 1274645ac279fd1fe9274
> ERROR: lzma/5.2.3@bincrafters/stable: Error in build() method, line 88
>         self.build_msvc()
> while calling 'build_msvc', line 59
>         self.run(command)
>         ConanException: Error 1 while executing call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC/vcvarsall.b
> at" x86 && msbuild xz_win.sln /p:Configuration=Debug /p:Platform="Win32" /m:4 /target:liblzma /p:ForceImportBeforeCppTar
> gets="C:\Users\ruigao\AppData\Local\Temp\tmphy93n6pftmp_conan\.conan_properties"
> 

Is it hard for me to install v120 toolset while I'm using VC2015.

**Comment by sinall** [comment]
BTW, bzip2 is also missing, seems both of them are dependencies of cpprestsdk.

**Comment by SSE4** [comment]
@sinall 
weird, for me package is available:
```
C:\bincrafters>conan install lzma/5.2.3@bincrafters/stable -s arch=x86 -s build_type=Release -s compiler="Visual Studio" -s compiler.version=14 -s compiler.runtime=MD -s os=Windows --build never -r conan-center
lzma/5.2.3@bincrafters/stable: Not found, retrieving from server 'conan-center'
lzma/5.2.3@bincrafters/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt
[==================================================] 103B/103B
Downloading conanfile.py
[==================================================] 5.1KB/5.1KB
Downloading conan_export.tgz
[==================================================] 766B/766B
lzma/5.2.3@bincrafters/stable: Installing package
Requirements
    lzma/5.2.3@bincrafters/stable from 'conan-center'
Packages
    lzma/5.2.3@bincrafters/stable:1299b26cefc5e04411a3481abe1c8b63227e2896

Cross-build from 'Windows:x86_64' to 'Windows:x86'
lzma/5.2.3@bincrafters/stable: Retrieving package 1299b26cefc5e04411a3481abe1c8b63227e2896 from remote 'conan-center'
Downloading conanmanifest.txt
[==================================================] 996B/996B
Downloading conaninfo.txt
[==================================================] 432B/432B
Downloading conan_package.tgz
[==================================================] 299.4KB/299.4KB
lzma/5.2.3@bincrafters/stable: Package installed 1299b26cefc5e04411a3481abe1c8b63227e2896
```

could you possibly to run the following command and let me know about the result:
```
conan install lzma/5.2.3@bincrafters/stable -s arch=x86 -s build_type=Release -s compiler="Visual Studio" -s compiler.version=14 -s compiler.runtime=MD -s os=Windows --build never -r conan-center
```

**Comment by SSE4** [comment]
@sinall oh, please ignove my commend above
after closer look at your log, I found:
```
Settings: arch=x86, build_type=Debug, compiler=Visual Studio, compiler.runtime=MD, compiler.version=14, os=Windows
```
I guess it's not a default combination (compiler.runtime=MD and build_type=Debug)
you should use either (compiler.runtime=MD and build_type=Release), or (compiler.runtime=MDd and build_type=Debug), otherwise you'll get runtime mismatches

**Comment by sinall** [comment]
I don't have this issue now. Don't know if it is because v120 toolset has been installed.

Since the combination(compiler.runtime and build_type) may confuse people, don't know if there is a way to reduce the confusion.
