### ISSUE TITLE
Request for cpprestsdk-2.10.10 + boost-1.69 [was cpprestsdk-2.10.2 + boost-1.67]?

### ISSUE THREAD

**Issue by sinall** [bincrafters/community#318]
### Package Details (Include if Applicable)
* Package Name/Version: **cpprestsdk/2.10.2**
* Operating System: **Windows 10**
* Compiler+version: **VC 2015**

### Steps to reproduce (Include if Applicable)

The latest cpprestsdk version is v2.10.2. Could you please upgrade it? Please also upgrade boost to 1.67.

**Comment by SSE4** [comment]
@sinall I am adding cpprestsdk/2.10.2, once boost 1.67.0 is available in our repository, I'll update cpprestsdk to it

**Comment by SSE4** [comment]
@grafikrobot @solvingj could you possibly comment on boost 1.67.0 status?

**Comment by SSE4** [comment]
@sinall I've added **cpprestsdk/2.10.2@bincrafters/stable** (not using boost 1.67 yet)

**Comment by SSE4** [comment]
@sinall boost 1.67 is WIP, I'll let you know once it's ready

**Comment by sinall** [comment]
OK

**Comment by sinall** [comment]
@SSE4 OK, let me know.

**Comment by sinall** [comment]
@SSE4 I see a lot of boost libraries has version 1.67, can I consider 1.67 is ready for use?

**Comment by SSE4** [comment]
question to @solvingj and @grafikrobot  :)

**Comment by solvingj** [comment]
Sorry for the delay @sinall 

No, we're pushing the stable branches now, and i will try to remember to post here when complete.

**Comment by sinall** [comment]
@solvingj
OK, it has been long time, the latest versions are cpprestsdk-v2.10.7 and boost-1.68.

**Comment by sinall** [comment]
Any updates?

**Comment by SSE4** [comment]
I think boost 1.69 is in progress, @solvingj do you have a details?

**Comment by solvingj** [comment]
Sorry for delay, not sure how i've missed this ticket for so long. 
Let me look at exactly which boost libs are required in cpprestsdk 2.10.10 and make sure they're all stable.

**Comment by solvingj** [comment]
This appears to be the list: 
https://github.com/Microsoft/cpprestsdk/blob/master/Release/cmake/cpprest_find_boost.cmake#L52

**Comment by solvingj** [comment]
@sinall I have bumped cpprestsdk to 2.10.10 using boost 1.69.0.  Please give it a try at your next opportunity.  Let us know if you have any issues.

**Comment by sinall** [comment]
@solvingj 

```
ERROR: Conflict in libzip/1.5.1@bincrafters/stable
    Requirement OpenSSL/1.0.2o@conan/stable conflicts with already defined OpenSSL/1.0.2q@conan/stable
    Keeping OpenSSL/1.0.2q@conan/stable
    To change it, override it in your base requirements
```

conanfile.py
```
	requires = (
		"boost/1.69.0@conan/stable",
		"cpprestsdk/2.10.10@bincrafters/stable",
		"libzip/1.5.1@bincrafters/stable",
		"zlib/1.2.11@conan/stable",
		"gsl_microsoft/2.0.0@bincrafters/stable",
	)

```
How should I _override it in your base requirements_?

**Comment by solvingj** [comment]
It's saying to override it in your "consumer" recipe.  You have to add `OpenSSL` explicitly in your recipe to decide the conflict.

**Comment by sinall** [comment]
@solvingj , Like this?

```
	requires = (
		"OpenSSL/1.0.2q@conan/stable",
		"boost/1.69.0@conan/stable",
		"cpprestsdk/2.10.10@bincrafters/stable",
		"libzip/1.5.1@bincrafters/stable",
		"zlib/1.2.11@conan/stable",
		"gsl_microsoft/2.0.0@bincrafters/stable",
	)

```

**Comment by solvingj** [comment]
Yes, that should work. Let us know if it doesn't. 

Here's a link to the relevant docs for posterity: 

https://docs.conan.io/en/latest/using_packages/conanfile_txt.html?highlight=override#overriding-requirements
