### ISSUE TITLE
SDL 2.0.8 fails on Ubuntu Bionic

### ISSUE THREAD

**Issue by Croydon** [bincrafters/community#320]
Since there is no libesd0-dev package anymore, which the recipe trys to install.

**Comment by SSE4** [comment]
I will change default option `esd=False`

**Comment by Croydon** [comment]
Thanks!

Another error, does this look familar to you somehow? https://travis-ci.org/inexorgame/inexor-core/jobs/393244811#L738

**Comment by SSE4** [comment]
@Croydon updated version is ready (with esd=False by default)

**Comment by madebr** [comment]
@Croydon I cannot find any travis output with the error you described [above](https://github.com/bincrafters/community/issues/320#issuecomment-397865958).
Has the error disappeared? It may have been caused by caching.

**Comment by Croydon** [comment]
@madebr No, the log is gone due to a re-run and a changed recipe, but I copied the error before.

If you can't reproduce it otherwhise I could trigger the error again later. But I'm not sure if there are any more helpful information.

**Comment by SSE4** [comment]
@Croydon if issue still happens for you, please open an issue on conan.io and link here. I'll keep this issue open until it's clear if it's problem with recipe itself or some conan bug. thank you.

**Comment by SSE4** [comment]
@Croydon does AttributeError issue still happen for you? have you opened bug for conan.io yet?
I am back to continue my work on SDL2_image, hopefully will have it done by the end of week.

**Comment by SSE4** [comment]
@Croydon which conan version do you run? I've just run into the same issue (AttributeError) with 1.0.4, but `python -m pip install --upgrade conan` solved it

**Comment by Croydon** [comment]
I will do another test, just don't have the time right now.

I can't say it for sure anymore, but I don't remember we have updated our Docker containers between this error and the re-run with a modified variant of the recipe, so it should be Conan 1.4.4

**Comment by Croydon** [comment]
Doesn't seem to happen anymore with the update to Conan 1.5.1

Thanks!
