### ISSUE TITLE
Not possible to build Tesseract without building Leptonica

### ISSUE THREAD

**Issue by datalogics-kam** [bincrafters/community#324]
First, I want to thank you for all the great work on making these packages available. This is our first foray into using C++ package management, and we are delighted that we don't have to add a large number of OSS projects on our own.

### Description of Problem, Request, or Question

Tesseract can't include transitive includes from Leptonica, when `conan install` has to build Tesseract but not Leptonica. This causes failures in our project setups when Leptonica has a matching package but Tesseract does not, and we use `--build missing`.

### Package Details (Include if Applicable)
* Package Name/Version: **tesseract/3.05.01**
* Operating System: **Windows 10**
* Compiler+version: **Visual Studio 12**

### Steps to reproduce (Include if Applicable)

```
conan install tesseract/3.05.01@bincrafters/stable --build tesseract
```

The problem appears to be that the Leptonica package has CMake information that refers to the build environment in `conan/data/leptonica/1.76.0/bincrafters/stable/package/2439e46a57e4eb427ec7626c1803084e708cf08a/cmake/LeptonicaTargets.cmake`

```
set_target_properties(leptonica PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/appveyor/.conan/data/giflib/5.1.4/bincrafters/stable/package/3ca85915ce57a6607676849c47c2cee02c75209c/include;C:/Users/appveyor/.conan/data/libjpeg/9c/bincrafters/stable/package/3ca85915ce57a6607676849c47c2cee02c75209c/include;C:/Users/appveyor/.conan/data/libpng/1.6.34/bincrafters/stable/package/e942631065059eabe964ca471ad35bb453c15b31/include;C:/Users/appveyor/.conan/data/zlib/1.2.11/conan/stable/package/3ca85915ce57a6607676849c47c2cee02c75209c/include;C:/Users/appveyor/.conan/data/libtiff/4.0.9/bincrafters/stable/package/e942631065059eabe964ca471ad35bb453c15b31/include;C:/Users/appveyor/.conan/data/zlib/1.2.11/conan/stable/package/3ca85915ce57a6607676849c47c2cee02c75209c/include"
)
```

Errors are like this: 

```
CMake Error in CMakeLists.txt:
  Imported target "leptonica" includes non-existent path

    "C:/Users/appveyor/.conan/data/giflib/5.1.4/bincrafters/stable/package/88a8c94ba0d38ce69afccbcf0043e87eb56f222b/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

## Workaround

Forcing a build of leptonica helps:

```
conan install tesseract/3.05.01@bincrafters/stable --build tesseract --build leptonica
```

...but it'd still be great if we could get away with just `--build missing` in our scripts.

**Comment by theirix** [comment]
Thank you for reporting and sorry for a delayed response. We are aware of this problem and it is a tricky one. Several approaches to fix this problem in a recipe are https://github.com/conan-io/conan/pull/2343 or  `patch_config_paths` function in a just-released Conan 1.5.0. I hope the latter approach will help. 

Unfortunately, I am going for a vacation tomorrow so I can fix recipes (leptonica and tesseract) only next month.

**Comment by datalogics-kam** [comment]
Thanks for the reply. We're working around it by building all our Tesseract configs locally and forcing Leptonica to build when we do, so I'm good for now. Have a good vacation (or I hope you did if you don't get this until you return).

**Comment by theirix** [comment]
Fixed it in the latest release of leptonica (please update recipes). Now you can build tesseract even with prebuilt leptonica! Please try it.

**Comment by datalogics-kam** [comment]
Solves my problem! Thanks for the fix, @theirix!

(For future reference, the fix: https://github.com/bincrafters/conan-leptonica/commit/bd489bb0dcb39fff73213670358eecf9711b370a)

**Comment by theirix** [comment]
You are welcome!
