### ISSUE TITLE
Qt 5.11.0 for gcc 8

### ISSUE THREAD

**Issue by madebr** [bincrafters/community#326]
### Description of Problem, Request, or Question
Qt 5.11.0 has no packages for gcc 8

### Package Details (Include if Applicable)
* Package Name/Version: **qt/5.11.0**
* Operating System: **Fedora 28**
* Compiler+version: **gcc-8**

### Steps to reproduce (Include if Applicable)
```
conan install qt/5.11.0@bincrafters/stable
```

**Comment by uilianries** [comment]
Related commit: https://github.com/bincrafters/conan-qt/commit/19f4acf3cb2fd0883fe23dc685b971a17ca13f9f

**Comment by lucienboillod** [comment]
@uilianries the branch you commited is deprecated, the new branches are 5.11.0, 5.9.6 and 5.6.3 :blush:

**Comment by uilianries** [comment]
Okay, I'll update this!

**Comment by lucienboillod** [comment]
@uilianries thank you, I have updated every branchs with the PR of Eric also, and changes the readme and url, you may have the fetch the changes

**Comment by uilianries** [comment]
Thanks for that!

**Comment by lucienboillod** [comment]
@uilianries we cherry-picked your commit and waiting the CI to finish to integrate it :blush:

**Comment by uilianries** [comment]
Thanks @lucienboillod !

**Comment by lucienboillod** [comment]
Changes were pushed. Closing this, thanks a lot everyone!
