### ISSUE TITLE
Bullet 2.87 for gcc 8

### ISSUE THREAD

**Issue by madebr** [bincrafters/community#327]
### Description of Problem, Request, or Question
bullet/2.87 has no packages for gcc 8

### Package Details (Include if Applicable)
* Package Name/Version: **bullet/2.87**
* Operating System: **Fedora 28**
* Compiler+version: **gcc-8**

### Steps to reproduce (Include if Applicable)
```
conan install bullet/2.87@bincrafters/stable
```

**Comment by madebr** [comment]
bincrafters/conan-bullet#2 might also be interesing to merge.

Idk whether this requires a rebuild.

**Comment by uilianries** [comment]
Hi @madebr the package is up-to-date!

![conan-bullet](https://screenshotscdn.firefoxusercontent.com/images/8f022f8f-4433-4906-8d2f-788c5109236b.png)
