### ISSUE TITLE
Publish libxml2

### ISSUE THREAD

**Issue by theirix** [bincrafters/community#33]
Recipe from lasote is outdated and doesn't work with latest conans.
I have refactored it and put into https://github.com/bincrafters/conan-libxml2.

Improvements:
- uses modern conan
- uses zlib from dependencies for msvc
- example checks proper linking
- does not package junk files like testdso

**Comment by solvingj** [comment]
Thanks buddy, i'm on it!  Please remove the wiki/issues/projects on the repo :)

**Comment by theirix** [comment]
Great! Done.

**Comment by theirix** [comment]
Builds fine for both testing and stable branches. Tested with an external app. I think, it's done

**Comment by uilianries** [comment]
Could we close this issue?

**Comment by theirix** [comment]
Do not know about workflow, but I'll close it.
