### ISSUE TITLE
libalsa/1.1.5@conan/stable

### ISSUE THREAD

**Issue by madebr** [bincrafters/community#330]
### Description of Problem, Request, or Question
libalsa/1.1.5 has no packages for gcc 8

### Package Details (Include if Applicable)
* Package Name/Version: **libalsa/1.1.5**
* Operating System: **Fedora 28**
* Compiler+version: **gcc-8**

### Steps to reproduce (Include if Applicable)
```
conan install libalsa/1.1.5@bincrafters/stable
```
(openal/1.18.2@bincrafters/stable depends on this package, so that one also needs a gcc 8 version)

**Comment by uilianries** [comment]
Hi @madebr !

[libalsa](https://github.com/conan-community/conan-libalsa) is maintained by [conan-community](https://github.com/conan-community/community/issues)

Please, open an issue on Conan community.

/cc @danimtb
