### ISSUE TITLE
gflags not building for compiler.libcxx == libstdc++11

### ISSUE THREAD

**Issue by mbeach** [bincrafters/community#331]
### Description of Problem, Request, or Question

The `build.py` file in conan-gflags does not set the `pure_c` flag to false in the call to `get_builder()`. This results in the CI builds only running for `libstdc++` and not `libstdc++11`.

I have a pull request bincrafters/conan-gflags#3 open which fixes this issue.

### Package Details (Include if Applicable)
* Package Name/Version: **gflags/2.2.1**
* Operating System: **Linux Ubuntu 16.04**

**Comment by uilianries** [comment]
Thanks! I merged your PR!

Indeed gflags uses c++ support.
