### ISSUE TITLE
ffmpeg 4.0 for gcc 8

### ISSUE THREAD

**Issue by madebr** [bincrafters/community#334]
### Description of Problem, Request, or Question
ffmpeg/4.0 has no packages for gcc 8

### Package Details (Include if Applicable)
* Package Name/Version: **ffmpeg/4.0**
* Operating System: **Fedora 28**
* Compiler+version: **gcc-8**

### Steps to reproduce (Include if Applicable)
```
conan install ffmpeg/4.0@bincrafters/stable -o vdpau=False -o vaapi=False -o xcb=False
```
Depends on #328

**Comment by SSE4** [comment]
binaries are available
