### ISSUE TITLE
lz4 should have compiler.libcxx setting deleted

### ISSUE THREAD

**Issue by mbeach** [bincrafters/community#337]
### Description of Problem, Request, or Question
lz4 is pure C code, but is being built with the compiler.libcxx setting present. This results in the Linux gcc CI builds all having the compiler.libcxx setting set to libstdc++, which means that the packages won't be considered when building C++ code with compiler.libcxx set to libstdc++11.

To fix this we should delete the compiler.libcxx setting in conanfile.py, so that the packages become usable regardless of the setting of compiler.libcxx when building code that wishes to link against lz4.

I have a pull request bincrafters/conan-lz4#5 open to contribute this change.

### Package Details (Include if Applicable)
* Package Name/Version: **lz4/1.8.0**

**Comment by uilianries** [comment]
Many thanks! You are doing a great job on this community!

Thanks again for all your effort.

I just accepted your PR some minutes ago. After to have all packages on Bintray, will be needed to remove the outdated.

**Comment by uilianries** [comment]
I'll keep this issue open until remove all outdated packages.

**Comment by mbeach** [comment]
No worries. I'm mostly just scratching my own itch, trying to get CI builds of https://github.com/mbeach/conan-folly working (I think I'm almost there...), but if the stuff I stumble across along the way helps then I'm very pleased about that.

**Comment by uilianries** [comment]
Folly is a huge project, please feel to ask for help or discuss any idea on Slack.

cpplang.slack.com our channel is #bincrafters

**Comment by solvingj** [comment]
Yes, thank you. I believe our folly is very close to working also.  https://github.com/bincrafters/conan-folly

**Comment by uilianries** [comment]
@solvingj he forked our repo ;)

**Comment by mbeach** [comment]
Thanks, I didn't know about the slack channel. I will check it out.

**Comment by uilianries** [comment]
Done!

![lz4/1.8.0@bincrafters/stable](https://screenshotscdn.firefoxusercontent.com/images/3ea6bb36-dc81-4882-ab7a-f070f0f6ffcb.png)
