### ISSUE TITLE
cygwin installer failing due to defaulted option in test_package/conanfile.py

### ISSUE THREAD

**Issue by lasote** [bincrafters/community#338]
### Description of Problem, Request, or Question

Hi, If I try to install the cygwin_installer package, not binary package is found.
I think it is because the recipe defaults the `no_acl` to False but the test_package is forcing the `no_acl` to True, so the generated packages are for `no_acl=True` that it is not the default of the recipe.

https://github.com/bincrafters/conan-cygwin_installer/blob/fe5b8f966a12fe8fc195312fe4e07a63b026a074/test_package/conanfile.py#L10

### Package Details (Include if Applicable)
* Package Name/Version: **cygwin_installer/2.9.0@bincrafters/stable** **https://github.com/bincrafters/conan-cygwin_installer**
* Operating System: **Windows x86_64**

### Steps to reproduce (Include if Applicable)

`conan install cygwin_installer/2.9.0@bincrafters/stable`

**Comment by uilianries** [comment]
Hi @lasote! I'll check this.

**Comment by uilianries** [comment]
Indeed only outdated packages are `no_acl=False`

![cygwin_installer/2.9.0@bincrafters/stable](https://screenshotscdn.firefoxusercontent.com/images/91df0f25-b8be-47c8-9ce6-90f615525467.png)

**Comment by uilianries** [comment]
@laote I built both options for no_acl and uploaded to Bintray

Please, check again.

**Comment by SSE4** [comment]
interesting, so default_options from test_package have priority over default_options from package itself?

**Comment by lasote** [comment]
Yes. When a test package is present, the package is built using the test package as a consumer, so it can change any option upstream. It is not recommend, of course.

**Comment by lasote** [comment]
It is working good now. Thanks friends!
