### ISSUE TITLE
Upstream Release - FMT 4.1.0

### ISSUE THREAD

**Issue by solvingj** [bincrafters/community#34]
Need volunteer to test the recipe with the latest version of FMT. 

https://github.com/fmtlib/fmt/releases/tag/4.1.0

**Comment by uilianries** [comment]
Testing 4.1.0 was created. Waiting for CI to merge into Stable 4.1.0

https://github.com/bincrafters/conan-fmt/tree/testing/4.1.0
https://travis-ci.org/bincrafters/conan-fmt/builds/319463165
https://ci.appveyor.com/project/BinCrafters/conan-fmt/build/1.0.6

**Comment by uilianries** [comment]
Done!

https://github.com/bincrafters/conan-fmt
