### ISSUE TITLE
Possibly missing libraries for SDL2 static build

### ISSUE THREAD

**Issue by tanshihaj** [bincrafters/community#341]
### Description of Problem, Request, or Question
When I'm building static SDL2 library on windows and trying to link into my application I receive some undefined reference errors. Linking with additional libraries -lole32 -loleaut32 -lgdi32 solve problem.

### Package Details (Include if Applicable)
* Package Name/Version: **sdl2/2.0.8**
* Operating System: **Windows 10**
* Compiler+version: **gcc-5.3.0** (from Qt installation)

```
profile:
MINGW_PATH=C:\Qt\Tools\mingw530_32

[settings]
os_build=Windows
arch_build=x86_64
os=Windows
arch=x86
compiler=gcc
compiler.version=5.3
compiler.exception=seh
compiler.libcxx=libstdc++11
compiler.threads=posix
shared=False

[env]
PATH=[$MINGW_PATH\bin\]
MINGW_HOME=$MINGW_PATH
CC=$MINGW_PATH\bin\gcc.exe
CXX=$MINGW_PATH\bin\g++.exe
```

### Steps to reproduce (Include if Applicable)
conan install sdl2/[>2.0.0]@bincrafters/stable --build=missing --profile=C:/path/to/profile

**Comment by SSE4** [comment]
thanks for the report, I'll add additional libraries needed

**Comment by SSE4** [comment]
@tanshihaj new binaries are on bintray, could you possibly give an another try?

**Comment by tanshihaj** [comment]
Yep, now it links, thanks!
