### ISSUE TITLE
Update yaml-cpp to 0.6.2

### ISSUE THREAD

**Issue by madebr** [bincrafters/community#344]
### Description of Problem, Request, or Question
yaml-cpp 0.6.2 is available since 6 March 2018: https://github.com/jbeder/yaml-cpp/releases

### Package Details (Include if Applicable)
* Package Name/Version: **yaml-cpp/0.6.2**

### Steps to reproduce (Include if Applicable)
- PR at bincrafters/conan-yaml-cpp#12
- CI fails because no `0.6.2/stable branch` exists

**Comment by uilianries** [comment]
@madebr Thanks!

**Comment by uilianries** [comment]
I merged your version on testing/0.6.2. I'll wait for CI result to push on stable branch.

**Comment by madebr** [comment]
Can you check whether the package contains a `yaml-cpp-targets.cmake` file and makes it visible to its consumers? I'm not sure about that.

**Comment by uilianries** [comment]
sure! I'll check on my side

**Comment by uilianries** [comment]
done!

the yaml-cpp-targets.cmake is at package_folder/lib/cmake/yaml-cpp-targets.cmake

![yaml-cpp](https://screenshotscdn.firefoxusercontent.com/images/290c10d9-b822-4652-b405-b037e72d3e91.png)
