### ISSUE TITLE
sdl2/2.0.8 install fails when the system requirements are not installed

### ISSUE THREAD

**Issue by madebr** [bincrafters/community#345]
### Description of Problem, Request, or Question

Install of sdl2/2.0.8 fails. No dependencies are installed.

```
$ conan install sdl2/2.0.8@bincrafters/stable
sdl2/2.0.8@bincrafters/stable: Installing package
Requirements
    sdl2/2.0.8@bincrafters/stable from 'bincrafters' - Cache
Packages
    sdl2/2.0.8@bincrafters/stable:fb1f29c51ac764b305133e500e349e8480fd322a - Cache

sdl2/2.0.8@bincrafters/stable: Already installed!
sdl2/2.0.8@bincrafters/stable: Creating SDL2_CONFIG environment variable: /home/maarten/.conan/data/sdl2/2.0.8/bincrafters/stable/package/fb1f29c51ac764b305133e500e349e8480fd322a/bin/sdl2-config
Package jack was not found in the pkg-config search path.
Perhaps you should add the directory containing `jack.pc'
to the PKG_CONFIG_PATH environment variable
Package 'jack', required by 'virtual:world', not found
ERROR: sdl2/2.0.8@bincrafters/stable: Error in package_info() method, line 224
	self.add_libraries_from_pc('jack')
while calling 'add_libraries_from_pc', line 200
	libs = [lib[2:] for lib in pkg_config.libs_only_l]  # cut -l prefix
	ConanException: pkg-config command ['pkg-config', '--libs-only-l', 'jack', '--static'] failed with error: Command '['pkg-config', '--libs-only-l', 'jack', '--static']' returned non-zero exit status 1.
```
### Package Details (Include if Applicable)
* Package Name/Version: **sdl2/2.0.8**
* Operating System: **Fedora 28**
* Compiler+version: **gcc-8.1.1**

**Comment by Croydon** [comment]
IIRC this is the reason why @lasote never uploaded packages for SDL2.

**Comment by SSE4** [comment]
this one is tricky
if SDL was built with jack support, then it will require jack libraries in runtime, as well as require jack libraries for linking (at least in case of static build)
in case jack is not available on target system, binaries will not link, or at least will not run, isn't it?
so, I guess jack is requirements (if it's not needed, one may pass `-o sdl2:jack=False` to profile or conan install)
but for me it looks suspicious why system requirements were not invoked (I mean conanfile's method)?

**Comment by madebr** [comment]
Idk whether something has changed, but installing sdl2 now has another behavior.

<details>
  <summary>Output of running <code>conan install sdl2/2.0.8@bincrafters/stable</code></summary>
<pre><code>$ conan install sdl2/2.0.8@bincrafters/stable
sdl2/2.0.8@bincrafters/stable: Not found in local cache, looking in remotes...
sdl2/2.0.8@bincrafters/stable: Trying with 'conan-center'...
sdl2/2.0.8@bincrafters/stable: Trying with 'bincrafters'...
Downloading conanmanifest.txt
[==================================================] 166B/166B        
Downloading conanfile.py
[==================================================] 15.2KB/15.2KB    
Downloading conan_export.tgz
[==================================================] 758B/758B        
sdl2/2.0.8@bincrafters/stable: Installing package
Requirements
    sdl2/2.0.8@bincrafters/stable from 'bincrafters' - Downloaded
Packages
    sdl2/2.0.8@bincrafters/stable:fb1f29c51ac764b305133e500e349e8480fd322a - Download

sdl2/2.0.8@bincrafters/stable: Retrieving package fb1f29c51ac764b305133e500e349e8480fd322a from remote 'bincrafters' 
Downloading conanmanifest.txt
[==================================================] 5.7KB/5.7KB      
Downloading conaninfo.txt
[==================================================] 972B/972B        
Downloading conan_package.tgz
[==================================================] 941.4KB/941.4KB  
sdl2/2.0.8@bincrafters/stable: Package installed fb1f29c51ac764b305133e500e349e8480fd322a
package pkgconfig.x86_64 is not installed
Running: sudo yum check-update
Last metadata expiration check: 0:04:42 ago on vr 06 jul 2018 16:45:33 CEST.

bind-export-libs.x86_64                                                       32:9.11.3-12.fc28                                             updates 
bind-libs.x86_64                                                              32:9.11.3-12.fc28                                             updates 
bind-libs-lite.x86_64                                                         32:9.11.3-12.fc28                                             updates 
bind-license.noarch                                                           32:9.11.3-12.fc28                                             updates 
bind-utils.x86_64                                                             32:9.11.3-12.fc28                                             updates 
capstone.x86_64                                                               3.0.4-16.fc28                                                 updates 
dnsmasq.x86_64                                                                2.79-3.fc28                                                   updates 
efibootmgr.x86_64                                                             16-2.fc28                                                     updates 
efivar.x86_64                                                                 35-1.fc28                                                     updates 
efivar-libs.x86_64                                                            35-1.fc28                                                     updates 
elfutils.x86_64                                                               0.173-1.fc28                                                  updates 
elfutils-default-yama-scope.noarch                                            0.173-1.fc28                                                  updates 
elfutils-libelf.i686                                                          0.173-1.fc28                                                  updates 
elfutils-libelf.x86_64                                                        0.173-1.fc28                                                  updates 
elfutils-libs.x86_64                                                          0.173-1.fc28                                                  updates 
emacs-filesystem.noarch                                                       1:26.1-3.fc28                                                 updates 
flatpak.x86_64                                                                0.99.2-1.fc28                                                 updates 
flatpak-libs.x86_64                                                           0.99.2-1.fc28                                                 updates 
fwupdate-efi.x86_64                                                           11-2.fc28                                                     updates 
fwupdate-libs.x86_64                                                          11-2.fc28                                                     updates 
gdb.x86_64                                                                    8.1-19.fc28                                                   updates 
gdb-headless.x86_64                                                           8.1-19.fc28                                                   updates 
geocode-glib.x86_64                                                           3.26.0-1.fc28                                                 updates 
glusterfs.x86_64                                                              4.1.1-1.fc28                                                  updates 
glusterfs-api.x86_64                                                          4.1.1-1.fc28                                                  updates 
glusterfs-cli.x86_64                                                          4.1.1-1.fc28                                                  updates 
glusterfs-client-xlators.x86_64                                               4.1.1-1.fc28                                                  updates 
glusterfs-fuse.x86_64                                                         4.1.1-1.fc28                                                  updates 
glusterfs-libs.x86_64                                                         4.1.1-1.fc28                                                  updates 
gnome-calculator.x86_64                                                       3.28.2-1.fc28                                                 updates 
gspell.x86_64                                                                 1.8.1-1.fc28                                                  updates 
gtksourceview3.x86_64                                                         3.24.8-1.fc28                                                 updates 
ibus-typing-booster.noarch                                                    2.0.2-1.fc28                                                  updates 
kernel.x86_64                                                                 4.17.3-200.fc28                                               updates 
kernel-core.x86_64                                                            4.17.3-200.fc28                                               updates 
kernel-headers.x86_64                                                         4.17.3-200.fc28                                               updates 
kernel-modules.x86_64                                                         4.17.3-200.fc28                                               updates 
kernel-modules-extra.x86_64                                                   4.17.3-200.fc28                                               updates 
libbytesize.x86_64                                                            1.3-2.fc28                                                    updates 
libdazzle.x86_64                                                              3.28.3-1.fc28                                                 updates 
libldb.x86_64                                                                 1.4.0-1.fc28                                                  updates 
libsemanage.x86_64                                                            2.8-2.fc28                                                    updates 
libsmbclient.x86_64                                                           2:4.8.3-1.fc28                                                updates 
libsolv.x86_64                                                                0.6.34-3.fc28                                                 updates 
libsoup.x86_64                                                                2.62.2-2.fc28                                                 updates 
libwbclient.x86_64                                                            2:4.8.3-1.fc28                                                updates 
libxcrypt.i686                                                                4.0.1-3.fc28                                                  updates 
libxcrypt.x86_64                                                              4.0.1-3.fc28                                                  updates 
libxcrypt-devel.i686                                                          4.0.1-3.fc28                                                  updates 
libxcrypt-devel.x86_64                                                        4.0.1-3.fc28                                                  updates 
memtest86+.x86_64                                                             5.01-20.fc28                                                  updates 
mesa-dri-drivers.i686                                                         18.0.5-2.fc28                                                 updates 
mesa-dri-drivers.x86_64                                                       18.0.5-2.fc28                                                 updates 
mesa-filesystem.i686                                                          18.0.5-2.fc28                                                 updates 
mesa-filesystem.x86_64                                                        18.0.5-2.fc28                                                 updates 
mesa-libEGL.i686                                                              18.0.5-2.fc28                                                 updates 
mesa-libEGL.x86_64                                                            18.0.5-2.fc28                                                 updates 
mesa-libEGL-devel.x86_64                                                      18.0.5-2.fc28                                                 updates 
mesa-libGL.i686                                                               18.0.5-2.fc28                                                 updates 
mesa-libGL.x86_64                                                             18.0.5-2.fc28                                                 updates 
mesa-libGL-devel.x86_64                                                       18.0.5-2.fc28                                                 updates 
mesa-libGLES.x86_64                                                           18.0.5-2.fc28                                                 updates 
mesa-libGLES-devel.x86_64                                                     18.0.5-2.fc28                                                 updates 
mesa-libOSMesa.i686                                                           18.0.5-2.fc28                                                 updates 
mesa-libOSMesa.x86_64                                                         18.0.5-2.fc28                                                 updates 
mesa-libOpenCL.x86_64                                                         18.0.5-2.fc28                                                 updates 
mesa-libgbm.i686                                                              18.0.5-2.fc28                                                 updates 
mesa-libgbm.x86_64                                                            18.0.5-2.fc28                                                 updates 
mesa-libglapi.i686                                                            18.0.5-2.fc28                                                 updates 
mesa-libglapi.x86_64                                                          18.0.5-2.fc28                                                 updates 
mesa-libxatracker.x86_64                                                      18.0.5-2.fc28                                                 updates 
mesa-vulkan-drivers.x86_64                                                    18.0.5-2.fc28                                                 updates 
opencc.x86_64                                                                 1.0.5-1.fc28                                                  updates 
orca.noarch                                                                   3.28.2-1.fc28                                                 updates 
perl-Time-Local.noarch                                                        1:1.280-1.fc28                                                updates 
python3-bind.noarch                                                           32:9.11.3-12.fc28                                             updates 
python3-bytesize.x86_64                                                       1.3-2.fc28                                                    updates 
qt5-qtdeclarative.x86_64                                                      5.10.1-6.fc28                                                 updates 
rpm-ostree-libs.x86_64                                                        2018.6-2.fc28                                                 updates 
samba-client.x86_64                                                           2:4.8.3-1.fc28                                                updates 
samba-client-libs.x86_64                                                      2:4.8.3-1.fc28                                                updates 
samba-common.noarch                                                           2:4.8.3-1.fc28                                                updates 
samba-common-libs.x86_64                                                      2:4.8.3-1.fc28                                                updates 
samba-common-tools.x86_64                                                     2:4.8.3-1.fc28                                                updates 
samba-libs.x86_64                                                             2:4.8.3-1.fc28                                                updates 
samba-winbind.x86_64                                                          2:4.8.3-1.fc28                                                updates 
samba-winbind-clients.x86_64                                                  2:4.8.3-1.fc28                                                updates 
samba-winbind-modules.x86_64                                                  2:4.8.3-1.fc28                                                updates 
shared-mime-info.x86_64                                                       1.10-1.fc28                                                   updates 
shim-ia32.x86_64                                                              15-2                                                          updates 
shim-x64.x86_64                                                               15-2                                                          updates 
sudo.x86_64                                                                   1.8.23-1.fc28                                                 updates 
tracker.x86_64                                                                2.0.4-1.fc28                                                  updates 
tracker-miners.x86_64                                                         2.0.5-1.fc28                                                  updates 
vim-common.x86_64                                                             2:8.1.119-1.fc28                                              updates 
vim-enhanced.x86_64                                                           2:8.1.119-1.fc28                                              updates 
vim-filesystem.noarch                                                         2:8.1.119-1.fc28                                              updates 
vim-minimal.x86_64                                                            2:8.1.119-1.fc28                                              updates 
xen-libs.x86_64                                                               4.10.1-5.fc28                                                 updates 
xen-licenses.x86_64                                                           4.10.1-5.fc28                                                 updates 
Obsoleting Packages
kernel-headers.x86_64                                                         4.17.3-200.fc28                                               updates 
    kernel-headers.x86_64                                                     4.17.2-200.fc28                                               @updates
vulkan-loader.i686                                                            1.1.77.0-4.fc28                                               updates 
    vulkan.x86_64                                                             1.1.73.0-1.fc28                                               @updates
vulkan-loader.i686                                                            1.1.77.0-4.fc28                                               updates 
    vulkan.i686                                                               1.1.73.0-1.fc28                                               @updates
vulkan-loader.i686                                                            1.1.77.0-4.fc28                                               updates 
    vulkan-filesystem.noarch                                                  1.1.73.0-1.fc28                                               @updates
vulkan-loader.x86_64                                                          1.1.77.0-4.fc28                                               updates 
    vulkan.x86_64                                                             1.1.73.0-1.fc28                                               @updates
vulkan-loader.x86_64                                                          1.1.77.0-4.fc28                                               updates 
    vulkan.i686                                                               1.1.73.0-1.fc28                                               @updates
vulkan-loader.x86_64                                                          1.1.77.0-4.fc28                                               updates 
    vulkan-filesystem.noarch                                                  1.1.73.0-1.fc28                                               @updates
sdl2/2.0.8@bincrafters/stable: ERROR: while executing system_requirements(): Command 'sudo yum check-update' failed
ERROR: Error in system requirements
</code></ver>
</details>

The exit code of `sudo yum check-update` is 100.

**Comment by SSE4** [comment]
according to the doc https://access.redhat.com/solutions/2779441, it's legal situation.
```returns exit value of 100 if there are packages avail‐able for an update.```
probably, conan doesn't handle this case with system package tool well.
I'll check if it's possible to somehow bypass.

**Comment by SSE4** [comment]
yep, this seems to be conan issue, it should be using `yum update` instead of `yum check-update`.
two things how to bypass:
1. running `yum update` manually
2. add **update=False** to the conanfile.py: `installer.install(package, update=False)`

**Comment by madebr** [comment]
Ok, I updated my system and that error goes away.
New error:
```
$ conan install sdl2/2.0.8@bincrafters/stable
sdl2/2.0.8@bincrafters/stable: WARN: Package is corrupted, removing folder: /home/maarten/.conan/data/sdl2/2.0.8/bincrafters/stable/package/fb1f29c51ac764b305133e500e349e8480fd322a
sdl2/2.0.8@bincrafters/stable: Installing package
Requirements
    sdl2/2.0.8@bincrafters/stable from 'bincrafters' - Cache
Packages
    sdl2/2.0.8@bincrafters/stable:fb1f29c51ac764b305133e500e349e8480fd322a - Download

sdl2/2.0.8@bincrafters/stable: Retrieving package fb1f29c51ac764b305133e500e349e8480fd322a from remote 'bincrafters' 
Downloading conanmanifest.txt
[==================================================] 5.7KB/5.7KB      
Downloading conaninfo.txt
[==================================================] 972B/972B        
Downloading conan_package.tgz
[==================================================] 941.4KB/941.4KB  
sdl2/2.0.8@bincrafters/stable: Package installed fb1f29c51ac764b305133e500e349e8480fd322a
package pkgconfig.x86_64 is not installed
Running: sudo yum check-update
Last metadata expiration check: 0:23:43 ago on vr 06 jul 2018 16:45:33 CEST.
Security: kernel-core-4.17.3-200.fc28.x86_64 is an installed security update
Security: kernel-core-4.17.2-200.fc28.x86_64 is the currently running version
Running: sudo yum install -y pkgconfig.x86_64
Last metadata expiration check: 0:23:45 ago on vr 06 jul 2018 16:45:33 CEST.
No match for argument: pkgconfig.x86_64
Error: Unable to find a match
sdl2/2.0.8@bincrafters/stable: ERROR: while executing system_requirements(): Command 'sudo yum install -y pkgconfig.x86_64' failed
ERROR: Error in system requirements
```
`pkg-config` is provided by `pkgconf-pkg-config` on fedora.

**Comment by SSE4** [comment]
thanks, I'll take some time to get correct package names for fedora as well. I'll keep you informed.

**Comment by madebr** [comment]
@SSE4 https://github.com/bincrafters/conan-sdl2/pull/10

**Comment by SSE4** [comment]
@madebr new version was built, please give a try

**Comment by madebr** [comment]
The install step succeeds and the package is downloaded successfully.
It also compiles and links perfectly.

The default options are also fine now: esd=False, x11=True and wayland=False
I don't need to override them anymore in our conanfile/profile to get our game to run.

**Comment by madebr** [comment]
@SSE4  Thank you very much for your effort!
