### ISSUE TITLE
Fixes for folly to get it building on Linux with gcc and with Visual Studio

### ISSUE THREAD

**Issue by mbeach** [bincrafters/community#350]
### Description of Problem, Request, or Question

Hi, I have bincrafters/conan-folly#3 open to get folly building with gcc on Linux and Visual Studio on Windows. It should be pretty straightforward to get it building with clang as well once #349 is addressed too.

### Package Details (Include if Applicable)
* Package Name/Version: **folly/0.58.0**

**Comment by mbeach** [comment]
Hi @uilianries, so is the use of boost from conan-community a special case because you want to get Folly onto Conan center, or is there a more general move away from modular boost to the conan-community non-modular boost?

**Comment by uilianries** [comment]
I want to get Folly onto Conan Center :)

**Comment by solvingj** [comment]
We’re still planning on modular boost In Conan center as alternative to monolithic boost, but we’ll continue to mature the recipes until it’s almost fully automated. Only a few more conan features needed.

**Comment by uilianries** [comment]
Okay, the problem only happens with Boost 1.68.0, the version where boost::system::generic_category_instance was added.

All working good with Boost 1.67.0

**Comment by uilianries** [comment]
Hi @mbeach !

Folly is working now: https://bintray.com/bincrafters/public-conan/folly%3Abincrafters

Please, try it and give us a feedback when possible :cat:

**Comment by SSE4** [comment]
@uilianries I think this is now done, WDYY?

**Comment by uilianries** [comment]
looks good to me! :+1:
