### ISSUE TITLE
libusb has incorrect license field

### ISSUE THREAD

**Issue by amerry** [bincrafters/community#351]
### Description of Problem, Request, or Question
The "license" field in `conanfile.py` lists the package's license as "GPL-2", but libusb is actually licensed under LGPL 2.1 (as can be seen from the COPYING file installed with the package).

### Package Details (Include if Applicable)
* Package Name/Version: **libusb/1.0.22** (but also other versions)

**Comment by uilianries** [comment]
Hi @amerry !

Thanks for your report! I'll fix it soon.

Regards!

**Comment by uilianries** [comment]
I created the follow PRs fixing the issue:

https://github.com/bincrafters/conan-libusb/pull/19
https://github.com/bincrafters/conan-libusb/pull/20 
https://github.com/bincrafters/conan-libusb/pull/21 

Also I updated on Bintray:  
https://bintray.com/bincrafters/public-conan/libusb%3Abincrafters

**Comment by uilianries** [comment]
Done!

If you find any problem, please re-open this issue.
