### ISSUE TITLE
libcurl/7.60.0 linking causes undefined reference to BrotliDecoderVersion

### ISSUE THREAD

**Issue by Artalus** [bincrafters/community#357]
### Package Details (Include if Applicable)
* Package Name/Version: **libcurl/7.60.0**
* Operating System: **Linux 4.14.40-rt30-MANJARO**
* Compiler+version: **clang-6.0**

### Steps to reproduce (Include if Applicable)
Linking my project and my package's `test_package` against libcurl causes undefined references for `Brotli` functions:
```
[100%] Linking CXX executable bin/example
/home/artalus/.conan/data/libcurl/7.60.0/bincrafters/stable/package/0afd05fcddd1fc736ead6524d3ff6ca588013a50/lib/libcurl.a(libcurl_la-version.o): In function `curl_version.part.0':
version.c:(.text+0xaf): undefined reference to `BrotliDecoderVersion'
```

After downgrading requirement to `7.56.1` or `7.52.1` the problem goes away, but still present for `7.60.0`.

> > From Slack by @SSE4 
> 1. seems like libcurl was built with `--with-brotli`, not sure if it's default or auto-detected
> 2. you probably need package `libbrotli-dev` or similar (depending on Linux distribution)
> 3. I guess you need to also run `pkg-config --libs brotli` to find out which libraries has to be linked 
> 4. in general, I believe libcurl recipe should be doing `add_libraries_from_pc`, as it is done in ffmpeg or sdl2 recipes

**Comment by SSE4** [comment]
okay, I've reproduced on image `bincrafters/docker-manjaro-clang6`
libcurl auto-detects certain libraries, one of them is brotli. so, on clean environment, it builds successfully.
but after running `pacman -S --noconfirm brotli` it will fail with an error above. I'll make it more explicit (add option for brotli, off by default).

**Comment by SSE4** [comment]
@Artalus I've pushed required changes, please give an another try
