### ISSUE TITLE
Missing GCC 8 packages for tesseract/3.05.01@bincrafters/stable

### ISSUE THREAD

**Issue by danimtb** [bincrafters/community#366]
After this PR https://github.com/bincrafters/conan-tesseract/pull/1

I realized there are some GCC 8 packages missing in its requirements:
```
...
Packages
    giflib/5.1.4@bincrafters/stable:1abd7c1ee1c95ef7eb8701f64d57dee2fbf6def4 - Missing
    leptonica/1.76.0@bincrafters/stable:0f5ca8dfdc91dd678fbbbc66368777f6aa0a2416 - Missing
```

**Comment by theirix** [comment]
merged giflib 5.1.4

**Comment by theirix** [comment]
I am after leptonica now

**Comment by theirix** [comment]
Now the tesseract and all its dependencies works fine with gcc8.

**Comment by danimtb** [comment]
Thanks a lot for the quick support guys @theirix @SSE4!
