### ISSUE TITLE
Inclusion request review for opus/1.2.1 into conan-center

### ISSUE THREAD

**Issue by danimtb** [bincrafters/community#368]
## Inclusion Request Review

This is a review for [opus/1.2.1@bincrafters/stable (bincrafters/public-conan)](https://github.com/bincrafters/conan-opus) inclusion request to conan-center.
This review follows the [inclusion guidelines of third party libraries](http://docs.conan.io/en/latest/uploading_packages/bintray/conan_center_guide.html#inclusion-guidelines-for-third-party-libraries).

### Package
opus/1.2.1@bincrafters/stable

#### Recipe quality
- [x] Git public repository
- [x] Recipe fields
- [x] Linter
- [x] Updated:
  - fPIC and --prefix is automanaged in Autotools build helper.
  - Some options are removed in configure() instead of config_options()
  - tools.build_sln_command() is deprecated, please use MSBuild()
- [x] Clean
- [x] test_package
- [x] Raise errors on invalid configurations
- [x] LICENSE of the recipe
- [x] LICENSE of the library

#### CI Integration
- [x] Provide at least one CI configuration (header only)
- [x] (If not header only) CI configurations for Linux/MacOSX/Windows

#### Bintray Package Information
- [x] Description
- [x] Licenses
- [x] Tags: Missing tags in Bintray metadata
- [x] Maturity
- [x] Website (if any)
- [x] Issue tracker
- [x] Version control

### Additional comments

There are some outdated packages, clean them up with: 
`conan remove opus/1.2.1@bincrafters/stable --outdated -r bincrafters`

Missing packages for apple-clang 9.1, Linux clang 5 and 6, Linux GCC 8

**Comment by SSE4** [comment]
everything is done, except not all options can be moved into **config_options**, as it is executed before options have their values, while fixed-point presence depends on shared option

**Comment by danimtb** [comment]
Looks good @SSE4. Just minor tweaks:

- ``del self.settings.compiler.libcxx`` should be in ``configure()`` (Generally modifications of settings are done in `configure()` and modification of options are done in `config_options()`)
- Include a little more code of the library in *test_package/test_pacakge.cpp*

Will accept the inclusion into conan-center. Thanks!

**Comment by SSE4** [comment]
@danimtb recommended changes were applied as well
