### ISSUE TITLE
Can not build lzma

### ISSUE THREAD

**Issue by acsvln** [bincrafters/community#369]
### Description of Problem, Request, or Question
Can not build lzma package from sources. My command line:
`acsvln@acsvln-Inspiron-5567:~/development/samples/gtest_sample$ conan install . -s compiler=gcc -s compiler.version=5.4 -s compiler.libcxx=libstdc++11 --build lzma`
And result:
```
lzma/5.2.3@bincrafters/stable: Configuring sources in /home/acsvln/.conan/data/lzma/5.2.3/bincrafters/stable/source
ERROR: Error downloading file https://tukaani.org/xz/xz-5.2.3.tar.gz: 'HTTPSConnectionPool(host='tukaani.org', port=443): Max retries exceeded with url: /xz/xz-5.2.3.tar.gz (Caused by SSLError(CertificateError("hostname 'tukaani.org' doesn't match either of '*.zoner.fi', 'zoner.fi'",),))'
Waiting 5 seconds to retry...
lzma/5.2.3@bincrafters/stable: WARN: Trying to remove dirty source folder
lzma/5.2.3@bincrafters/stable: WARN: This can take a while for big packages
ERROR: lzma/5.2.3@bincrafters/stable: Error in source() method, line 38
	tools.download(source_url, archive_name, verify=True)
	ConanException: Error downloading file https://tukaani.org/xz/xz-5.2.3.tar.gz: 'HTTPSConnectionPool(host='tukaani.org', port=443): Max retries exceeded with url: /xz/xz-5.2.3.tar.gz (Caused by SSLError(CertificateError("hostname 'tukaani.org' doesn't match either of '*.zoner.fi', 'zoner.fi'",),))'
acsvln@acsvln-Inspiron-
```
### Package Details (Include if Applicable)
* Package Name/Version: **lzma/5.2.3**
* Operating System: **Linux Ubuntu 16.04**
* Compiler+version: **gcc-5.4**

**Comment by acsvln** [comment]
I fear i have some problems with conan (or maybe python?) environment.
First command failed (same result), second succeeded.

**Comment by Croydon** [comment]
Since this seems to be a temporary issue I'm going to close it. Please report back if you continue to have problems.
