### ISSUE TITLE
[bug] Qt 5.11.1: fPIC=False doesn't work

### ISSUE THREAD

**Issue by ArekPiekarz** [bincrafters/community#370]
### Description of Problem

Qt 5.11.1 compiled with `fPIC=False` still behaves as if `fPIC=True` was used, giving error when #included in your program:
`qglobal.h:1177:4: error: #error "You must build your code with position independent code if Qt was built with -reduce-relocations. " "Compile your code with -fPIC (-fPIE is not enough)."`

### Package Details
* Package Name/Version: **Qt/5.11.1**
* Operating System: **Linux Ubuntu 18.04 x64**
* Compiler+version: **gcc-8.0.1**
* CMake: **3.11.4**

### Steps to reproduce
conanfile.txt
```
[requires]
Qt/5.11.1@bincrafters/stable

[options]
*:shared=False
Qt:fPIC=False

[generators]
cmake
```
CMakeLists.txt
```
cmake_minimum_required(VERSION 3.11)

project(conan-qt-test LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CONAN_SYSTEM_INCLUDES ON)

include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()

add_executable(${PROJECT_NAME} main.cpp)
target_link_libraries(${PROJECT_NAME} ${CONAN_LIBS})
```
main.cpp
```
#include <QtCore/QDebug>

int main()
{
    qDebug() << "hello";
    return 0;
}
```
~/.conan/data/profiles/default
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=8
[options]
[build_requires]
[env]
```
Commands:
```
mkdir build-static-debug
cd build-static-debug
conan install .. --build missing
cmake -DCMAKE_BUILD_TYPE=Debug ..
make
```

#### Expected result
Compilation should succeed.

#### Actual result
Compilation fails with:
```
$ make
Scanning dependencies of target conan-qt-test
[ 50%] Building CXX object CMakeFiles/conan-qt-test.dir/main.cpp.o
In file included from /home/fazer/.conan/data/Qt/5.11.1/bincrafters/stable/package/cc14c9c4bcfb961f817287709e546f5550560715/include/QtCore/qalgorithms.h:43,
                 from /home/fazer/.conan/data/Qt/5.11.1/bincrafters/stable/package/cc14c9c4bcfb961f817287709e546f5550560715/include/QtCore/qdebug.h:44,
                 from /home/fazer/.conan/data/Qt/5.11.1/bincrafters/stable/package/cc14c9c4bcfb961f817287709e546f5550560715/include/QtCore/QDebug:1,
                 from /home/fazer/dev/project/test/conan-qt-static-bug/main.cpp:1:
/home/fazer/.conan/data/Qt/5.11.1/bincrafters/stable/package/cc14c9c4bcfb961f817287709e546f5550560715/include/QtCore/qglobal.h:1177:4: error: #error "You must build your code with position independent code if Qt was built with -reduce-relocations. " "Compile your code with -fPIC (-fPIE is not enough)."
 #  error "You must build your code with position independent code if Qt was built with -reduce-relocations. "\
    ^~~~~
CMakeFiles/conan-qt-test.dir/build.make:62: recipe for target 'CMakeFiles/conan-qt-test.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/conan-qt-test.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/conan-qt-test.dir/all' failed
make[1]: *** [CMakeFiles/conan-qt-test.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```
Log from conan install:
[conan-install-output.txt](https://github.com/bincrafters/community/files/2202796/conan-install-output.txt)
Log from cmake:
[cmake-output.txt](https://github.com/bincrafters/community/files/2202798/cmake-output.txt)

**Comment by lucienboillod** [comment]
Thanks for your input. I am on it

**Comment by lucienboillod** [comment]
This flag is actually useless in our recipe, we have no control over this fPIC flag (we will delete it asap), and Qt will anyway compile with it. Why do you need to deactived fPIC @ArekPiekarz  ?

**Comment by ArekPiekarz** [comment]
fPIC is not really needed for static libraries and its presence can disable some compiler optimizations. However it's not critical for me right now - if Qt doesn't allow easily turning it off, we can leave it at that.

**Comment by lucienboillod** [comment]
Yes it seems out of our hands :disappointed: 
https://bugreports.qt.io/browse/QTBUG-55605

**Comment by SSE4** [comment]
@ArekPiekarz fPIC is needed if you link static library into shared library

**Comment by PikachuHy** [comment]
```
QtCore/qglobal.h:1177:4: error: #error "You must build your code with position independent code if Qt was built with -reduce-relocations. " "Compile your code with -fPIC (-fPIE is not enough)."
 #  error "You must build your code with position independent code if Qt was built with -reduce-relocations. "\
```
same error ![55](https://assets-cdn.github.com/images/icons/emoji/unicode/1f61e.png)

**Comment by ericLemanissier** [comment]
I think the problem should go away if you use find_package and qt targets as described in Qt's documentation http://doc.qt.io/qt-5/cmake-manual.html and as in the test_package https://github.com/bincrafters/conan-qt/blob/stable/5.11.1/test_package/CMakeLists.txt
Could you please try this ?

**Comment by PikachuHy** [comment]
@ericLemanissier  it works. thanks.
