### ISSUE TITLE
Options for conan-qt imageformats

### ISSUE THREAD

**Issue by vadixidav** [bincrafters/community#373]
* Package Name/Version: **Qt/5.9.6**
* Operating System: **Windows 10 Pro**
* Compiler+version: **Visual Studio 2015**

The Qt `imageformats` module supports copying certain "3rdparty" builds into the `src/3rdparty` folder of `imageformats` to produce additional imageformats plugins. These plugins are produced as a side effect of running QMake on the `imageformats` module with these source trees and pri files in `src/3rdparty`.

The documentation describing this can be found at this page: http://doc.qt.io/qt-5/qtimageformats-index.html

Building each of these imageformats plugins that isn't included by default should be allowed via an option in the package and the licenses for each one should likely be copied into the package if they are included.

I am personally looking for JP2 and Direct Draw Surface (DDS) to be added to the build. Everything else I need is being built already by default in `imageformats`.

**Comment by SSE4** [comment]
@vadixidav in general, follow pep8 and conan-center guidelines (https://docs.conan.io/en/latest/uploading_packages/bintray/conan_center_guide.html). also, you may check out our guidelines (https://github.com/bincrafters/community/tree/master/contributing_to_packages).

**Comment by ericLemanissier** [comment]
I'm not sure anything needs to be modified in the recipe. the doc you linked says 
> In case of a third party codec, the build process will look for it among the system libraries. If not found, 
it may fall back on using a bundled copy (in src/3rdparty).

It does not look like Qt expects you to copy anything in its own sources.

About DDS https://forum.qt.io/topic/75846/qt-5-8-supported-image-formats says
> dds was moved to unmaintained status in 5.8, you'll have to uncomment the dds line in src/plugins/imageformats/imageformats.pro if you want to build it manually (no compile flag exists to enable it).
https://bugreports.qt.io/browse/QTBUG-59955 mentioned security problems, it does not sound like a good idea to enable this in the bincrafters recipe. You still have the opportunity to use your own recipe, and patch imageformats.pro to uncomment the dds line in the source method.

about JP2 It seems that qt configurations tests fail to find the bundled sources of the codec. Did you try installing libjasper-dev ?

**Comment by vadixidav** [comment]
@ericLemanissier I was messing around with it to try and get Jasper included. I think QMAKE_CONFIG±=config_jasper needs to be passed as the last argument to the configure script for QT. I am not super familiar with qmake, but I think the line in the pro file that adds jasper is enabled by that (it says config_jasper {}). I will be trying it out.

**Comment by ericLemanissier** [comment]
This recipe is now in the Conan Center Index.

Please migrate to the recipe version there.
If this is still an issue, please create a new issue in the Conan Center Index issue tracker.

Thanks!

https://conan.io/center/qt
