### ISSUE TITLE
ffmpeg can't find openh264 on Windows builds due to issues with pkgconfig

### ISSUE THREAD

**Issue by oliverdaniell** [bincrafters/community#375]
### ffmpeg can't find openh264 on Windows builds due to issues with pkgconfig
Building ffmpeg with openh264 is currently broken on Windows. The majority of the issues are due to environment variables not being passed to msys2 builds https://github.com/conan-io/conan/pull/3104. However, there are also a couple of issues with the ffmpeg package. I've address these issues in [bug/windows-build](https://github.com/bincrafters/conan-ffmpeg/compare/stable/4.0...oliverdaniell:bug/windows-build). The fixes maintain linux compatibility  and fix the windows build once https://github.com/conan-io/conan/pull/3104 is merged.

Should I create a pull request to stable/4.0 or testing/4.0?

### Package Details (Include if Applicable)
* Package: ffmpeg/4.0
* Operating System: **Windows 10**
* Compiler+version: **msvc 15 2017**

### Steps to reproduce (Include if Applicable)
```conan create . mypackages/ffmpeg -o ffmpeg:openh264=True```

**Comment by SSE4** [comment]
hi @oliverdaniell 
could you possibly try **quicktest/4.0** branch? in mentioned branch, I am solving most of issues with external libraries, like openh264. hope to merge it soon.

**Comment by oliverdaniell** [comment]
@SSE4 I've tested  **quicktest/4.0** with openh264 using **conan v1.6.0**. That solves the problem!

It might worth reviewing https://github.com/conan-io/conan/pull/3104 as the fixes there will make the msys2 path hacks in **quicktest/4.0**  redundant.

**Comment by SSE4** [comment]
yes, I've take a look today evening, I hope

**Comment by SSE4** [comment]
I am closing an issue as confirmed as fixed. changes were merged to the **testing/4.0** branch, and soon will be available in the **stable/4.0** as well (today/tomorrow).
