### ISSUE TITLE
Conan gtest package fails to build with clang

### ISSUE THREAD

**Issue by krojew** [bincrafters/community#376]
* Package Name/Version: **gtest/1.8.0@bincrafters/stable**
* Operating System: **Linux Ubuntu 17.10**
* Compiler+version: **clang 5.0**

### Steps to reproduce (Include if Applicable)

Try to build with the following command:

conan install .. --build=missing -s compiler=clang -s compiler.libcxx=libstdc++11 -s compiler.version=5.0

The build fails, because gtest recognized gcc as the compiler, not clang:

gtest/1.8.0@bincrafters/stable: Calling build()
-- The C compiler identification is GNU 7.2.0
-- The CXX compiler identification is GNU 7.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: called by CMake conan helper
CMake Error at conanbuildinfo.cmake:412 (message):
  Incorrect 'clang', is not the one detected by CMake: 'GNU'
Call Stack (most recent call first):
  conanbuildinfo.cmake:58 (conan_check_compiler)
  CMakeLists.txt:4 (conan_basic_setup)

-- Configuring incomplete, errors occurred!

**Comment by SSE4** [comment]
this is probably a profile issue, could you run `conan profile show default` and paste an output here?

**Comment by krojew** [comment]
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=7
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]

**Comment by SSE4** [comment]
@krojew 
may you try to add the following into your profile?
```
[env]
CC=clang
CXX=clang++
```
and try again? (or alternatively, just set CC and CXX environment variables)

**Comment by krojew** [comment]
That seems to fix the issue.

**Comment by SSE4** [comment]
I am closing an issue when

**Comment by krojew** [comment]
I think conanfile.py should be able to enforce the compiler which is set by conan (like other packages do), instead of requiring the user to set additional settings. The issue should not be closed then.

**Comment by uilianries** [comment]
@Croydon yes, as it's a profile problem, not a package bug.
