### ISSUE TITLE
Qt/5.11.1: OpenSSL options + OpenGL by default

### ISSUE THREAD

**Issue by madebr** [bincrafters/community#379]
### Description of Problem, Request, or Question
I've opened a PR: https://github.com/bincrafters/conan-qt/pull/11

**Comment by madebr** [comment]
What is the general feeling towards this?

**Comment by SSE4** [comment]
@lucienboillod @ericLemanissier

**Comment by ericLemanissier** [comment]
I'm totally ok with you changes. If you don't mind I'll do a rebase on top of my current branch, because there will be conflicts to solve. If everything looks ok to @lucienboillod he will be able to push the changes on bincrafter's repo, but he is very busy these days..

**Comment by ericLemanissier** [comment]
The changes are now on stable/5.11.1 branch. Thanks !

**Comment by SSE4** [comment]
changes are merged, closing
