### ISSUE TITLE
gtest 1.8.0 - MSVC15 testing branch failing

### ISSUE THREAD

**Issue by solvingj** [bincrafters/community#38]
## Description
When gtest 1.8.0 was pushed a month ago, it was simply done on the stable branch, and no `testing/1.8.0` branch got created.  I just created this branch off the stable one and for some reason it's failing on MSVC15.  

Of note, the Travis build failed immediately due to the Conan/Travis changes, so i've fixed that on the testing branch.  Travis is now passing.  When this MSVC issue is resolved, we need to merge changes into `stable/1.8.0` and let it rebuild. 

Here's the git repo: 
https://github.com/bincrafters/conan-gtest

Here's the failing Appveyor build:
https://ci.appveyor.com/project/BinCrafters/conan-gtest/build/1.0.3

### package
gtest/1.8.0@bincrafters/testing

### Extra information
* Conan version: **v0.30.3**
* Operating System: **Windows**
* Compiler+version: **MSVC15**

**Comment by dimi309** [comment]
I've fixed this. Please review the abovementioned pull request.

**Comment by dimi309** [comment]
All done then.
