### ISSUE TITLE
Inclusion request for kainjow-mustache

### ISSUE THREAD

**Issue by Croydon** [bincrafters/community#380]
kainjow-mustache is one of many implementations of [Mustache](https://mustache.github.io/). It's a tiny header-only library.

I'm currently maintaining it for and within @inexorgame, but would now like to transfer it to Bincrafters and continue maintaining it there (which is very little effort actually, since it also doesn't have many updates 😄 ).

I have applied Bincrafters standards to the best of my knowledge; with maybe the exception of adding CI. If it is still canon that header-only libraries don't even get a small-ish CI then I will remove it. 

(Kinda off-topic: Even though as a general idea maybe there should be at least a CI script which automates uploading when publishing to the stable channel?)

Please let me know what you think and if there are things I need to improve further. If you accept this request then I'm going to transfer the entire repository over to bincrafters.

https://github.com/Croydon/conan-kainjow-mustache
Original repo: https://github.com/inexorgame/conan-kainjow-mustache
https://github.com/kainjow/Mustache

**Comment by uilianries** [comment]
Sounds good to me. I'll pull your repo. Thank you for great this contribution!

**Comment by uilianries** [comment]
Done!

I copied your repository to [bincrafters/conan-kainjow-mustache](https://github.com/bincrafters/conan-kainjow-mustache). All commits were preserved :smile_cat: 

https://github.com/bincrafters/conan-kainjow-mustache
https://bintray.com/bincrafters/public-conan/kainjow-mustache%3Abincrafters

I'm going to include Conan center inclusion.

![kainjow-mustache/3.2.1@bincrafters/stable](https://screenshotscdn.firefoxusercontent.com/images/3c5c5ab8-9292-4088-b578-66aaa782c8f7.png)

**Comment by Croydon** [comment]
Thanks!

**Comment by danimtb** [comment]
Inclusion request approved! Thanks guys
