### ISSUE TITLE
conan-cpprestsdk MSVC12 linkage problem 

### ISSUE THREAD

**Issue by rhard** [bincrafters/community#382]
### Description of Problem, Request, or Question
For conan-cpprestsdk library on Windows with VS2013 there is a linkage problem when trying to use package with qmake. The library name is wrong. Must be cpprest120_2_10.lib instead of cpprest_2_10.lib

### Package Details (Include if Applicable)
* Package Name/Version: **cpprestsdk/2.10.2@bincrafters/stable**
* Operating System: **Windows 7**
* Compiler+version: **VS2013**
### Possible fix

Please add VS2013 compiler in line 132 in the conanfile.py

```
    def package_info(self):
        if self.settings.compiler == "Visual Studio":
            debug_suffix = 'd' if self.settings.build_type == 'Debug' else ''
            toolset = {'12': '120', <------- HERE IS THE FIX
                       '14': '140',
                       '15': '141'}.get(str(self.settings.compiler.version))
            version_tokens = self.version.split(".") 
```

**Comment by SSE4** [comment]
@rhard fix was applied, please give one more try

**Comment by rhard** [comment]
Issue fixed. Thanks!
