### ISSUE TITLE
Creating own test_package.cpp in test_package folder - linker command failed with exit code 1 -solved in 5.11.1

### ISSUE THREAD

**Issue by HorvathAnton** [bincrafters/community#384]
I download the conan-qt and when I run commnad 

**_conan create . Qt/5.11.0@bincrafters/public-conan_**

its works and also runs the test_package.cpp. But I try to modify the test_package.cpp in test_package folder to use qt library as follow.

```
#include <QtCore/QCoreApplication>
#include <QtCore/QString>
#include <iostream>

int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);
    QString lstr = "Hello Conan";
    std::cout << lstr.toStdString() << std::endl;
    
    return a.exec();
}
```

But its failed. Here is the bottom of the log from terminal.

-- Build files have been written to: /Users/tony/Job/conan-qt/test_package/build/cd3601ac1ef07679242d04c71a1f8cb266c63e70
Scanning dependencies of target test_package
[ 50%] Building CXX object CMakeFiles/test_package.dir/HelloConan/main.cpp.o
[100%] Linking CXX executable bin/test_package
Undefined symbols for architecture x86_64:
  "qt_assert(char const*, char const*, int)", referenced from:
      QString::toStdString() const in main.cpp.o
  "QArrayData::deallocate(QArrayData*, unsigned long, unsigned long)", referenced from:
      _main in main.cpp.o
      QString::toStdString() const in main.cpp.o
  "QCoreApplication::exec()", referenced from:
      _main in main.cpp.o
  "QCoreApplication::QCoreApplication(int&, char**, int)", referenced from:
      _main in main.cpp.o
  "QCoreApplication::~QCoreApplication()", referenced from:
      _main in main.cpp.o
  "QString::toUtf8_helper(QString const&)", referenced from:
      QString::toStdString() const in main.cpp.o
  "QString::fromAscii_helper(char const*, int)", referenced from:
      _main in main.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [CMakeFiles/test_package.dir/build.make:84: bin/test_package] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/test_package.dir/all] Error 2
gmake: *** [Makefile:84: all] Error 2
ERROR: PROJECT: Error in build() method, line 16
	cmake.build()
	ConanException: Error 512 while executing cmake --build '/Users/tony/Job/conan-qt/test_package/build/cd3601ac1ef07679242d04c71a1f8cb266c63e70' '--' '-j8'

os=Macos - high sierra 10.13.6
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=9.1
compiler.libcxx=libc++
build_type=Release

Any help will be highly appreciated!

**Comment by ericLemanissier** [comment]
Could you please try with 5.11.1 ?

**Comment by HorvathAnton** [comment]
Tonys-MacBook-Pro:conan-qt tony$ conan create . Qt/5.11.1@bincrafters/public-conan
Qt/5.11.1@bincrafters/public-conan: Exporting package recipe
ERROR: Package recipe exported with version 5.11.1!=5.11.0

**Comment by ericLemanissier** [comment]
you need to get the sources of conan-qt 5.11.1 first, the same way you got 5.11.0, for example checkout 5.11.1 branch of https://github.com/bincrafters/conan-qt/

**Comment by HorvathAnton** [comment]
Its already running. Thank you for quick response.

**Comment by HorvathAnton** [comment]
Works!

**Comment by HorvathAnton** [comment]
@ericLemanissier  with which parameter have to call conan create if I want to use QtWidgets not just QtCore ?

**Comment by SSE4** [comment]
closing as confirmed fixed
