### ISSUE TITLE
Inclusion request for SFML

### ISSUE THREAD

**Issue by notskm** [bincrafters/community#385]
I created a package for SFML. The static library builds for Mac are currently failing likely due to some libraries missing from `self.cpp_info.libs`, but I don't have a Mac to test on. All other builds are working just fine. https://github.com/notskm/conan-sfml

**Comment by notskm** [comment]
I just noticed that there's already an SFML repo. I thought I checked for that, but apparently not. Either way, this supports a newer version of SFML and just needs the static builds for Mac fixed. Let me know if there's anything I need to do.

**Comment by SSE4** [comment]
hi @notskm 
thank you for your contribution!
I've created new repository https://github.com/bincrafters/conan-sfml (you should have access rights)
I've also triggered CI against it
I can take a look at OSX build failures tomorrow

**Comment by notskm** [comment]
Awesome, thank you!

**Comment by SSE4** [comment]
problems are a bit deeper than they first looked
in general, SFML tries to link to bundled frameworks of FLAC, OpenAL, vorbis, etc.
this causes lots of issues during linking, running, packaging and distribution
I'll try to change it to link to conan dependencies instead

**Comment by notskm** [comment]
I was looking into doing that. I ran into a problem with the Freetype library on Windows. I think I was getting linker errors for libpng and bzip, but I didn't dig any deeper.

**Comment by SSE4** [comment]
just found this https://github.com/conan-io/wishlist/issues/142
I'd like to avoid overlap, @danimtb what's the state of your SFML package?

**Comment by danimtb** [comment]
We should wait for @lasote as he was the on working on it. I think he was doing the work on his fork: https://github.com/lasote/conan-sfml/commit/46e0740276902a8efac2b54e94f1e960e8fecca5

@notskm recipe looks quite good bu better sync ASAP to not duplicate efforts. Thanks for noticing @SSE4 !

**Comment by notskm** [comment]
I think I managed to make the Windows and Mac builds use the conan dependencies instead of the ones SFML is packaged with last night. I need to clean it up a bit before I push the changes. I'll hold off on that until we hear from @lasote unless you'd like me to push before then.

**Comment by SSE4** [comment]
@notskm let's wait for @lasote for a while. if he is actively working on his repo, we'll merge our changes to his branch and close repository in bincrafters group. let's pause development for now to minimize amount of changes diverged to be merged.

**Comment by lasote** [comment]
Hi all! I didn't get much time lately to continue with SFML, maybe you can leverage from my package and improve yours (if there is something to improve, I haven't look at it). WDYT? I can help explaining what you need.

**Comment by lasote** [comment]
Good! 
It's ok if we support only the latest 2.5.0, no problem.

**Comment by notskm** [comment]
Just to confirm, we're just going to continue development on the Bincrafters repo, correct? If so, I'll go ahead and push my changes.

**Comment by lasote** [comment]
Correct.

**Comment by notskm** [comment]
Pushed. If all goes well, this should build on all platforms.

**Comment by notskm** [comment]
@SSE4 I just pushed a commit that caused one of the Mac builds to fail for some reason. If you could please check it out, I'd appreciate it. I'm not sure how to fix it. Once that's done, the testing branch should be ready to merge and this issue can probably be closed.

**Comment by SSE4** [comment]
@notskm sure, I'll take a look

**Comment by SSE4** [comment]
@notskm all done, build fixed, changes merged to stable, closing
