### ISSUE TITLE
Refresh parson CI and readme

### ISSUE THREAD

**Issue by solvingj** [bincrafters/community#386]
The parson readme still shows CircleCI which we no longer use, and the Appveyor build says failing.  We should revisit and refresh this recipe and repository. 

Also, since there's no semantic versioning on this project, we should probably switch to date-based-versioning.

**Comment by uilianries** [comment]
> The parson readme still shows CircleCI which we no longer use, and the Appveyor build says failing. We should revisit and refresh this recipe and repository.

https://github.com/bincrafters/conan-parson/commit/076d81fd0009b9bc1d90872b22da09590052c322

**Comment by SSE4** [comment]
seems to be green and with no CircleCI, great job, @uilianries
