### ISSUE TITLE
PDB files are not packaged in debug builds of the SDL2 library

### ISSUE THREAD

**Issue by rdeterre** [bincrafters/community#387]
### Description of Problem, Request, or Question

The SDL2 library does not appear to package PDB files during debug builds on Windows. This generates a series of LNK4099 linker warnings like the following to be generated during compilation:

```
  SDL2d.lib(SDL_systimer.c.obj) : warning LNK4099: PDB 'SDL2-static.pdb' was not found with 'SDL2d.lib(SDL_systimer.c.obj)' or at '<project-dir>\build\bin\SDL2-static.pdb'; linking object as if no debug info [<project-dir>\build\alazarcharts_t.vcxproj]
```

### Package Details (Include if Applicable)
* Package Name/Version: **sdl2/2.0.8**
* Operating System: **Windows**
* Compiler+version: **Visual Studio 14 Win64**

The profile that was used to test is this:

```
[build_requires]
[settings]
arch=x86_64
build_type=Debug
compiler=Visual Studio
compiler.runtime=MDd
compiler.version=14
os=Windows
arch_build=x86_64
os_build=Windows
[options]
[env]
```

### Steps to reproduce (Include if Applicable)

Create a project that uses SDL2, then run `conan install . -pr=profile` and `conan build .` with `profile` the profile above

**Comment by SSE4** [comment]
@rdeterre PDB files were added, please give a try

**Comment by SSE4** [comment]
closing, confirmed as fixed
