### ISSUE TITLE
Error in build() method, line 19 on Windows - running create command

### ISSUE THREAD

**Issue by HorvathAnton** [bincrafters/community#388]
Runing command conan create . Qt/5.11.1@bincrafters/public-conan  failed with 

Maybe you forgot to setup the environment?
ERROR: PROJECT: Error in build() method, line 19
        self.run("qmake %s" % self.source_folder)
        ConanException: Error 3 while executing qmake c:\Work\Foxit\conan-qt\test_package

Looks like package is download properly only python script of test_package failed.

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=15
build_type=Release

**Comment by ericLemanissier** [comment]
Hello,

I'm surprised "Qt/5.11.1@bincrafters/public-conan" works because there is no "public-conan" channel. it should be Qt/5.11.1@bincrafters/stable.
Could you try to remove all the Qt packages from your local cache and then `conan create . Qt/5.11.1@bincrafters/stable --build Qt` ?

**Comment by HorvathAnton** [comment]
I try that and it is end with the same error.

**Comment by ericLemanissier** [comment]
Can you please try again to remove all the Qt packages from your local cache and then go in the conan-qt directory (not in the test_package subdirectory), and run `conan create . Qt/5.11.1@bincrafters/stable --build Qt`, and then send the full log?

**Comment by HorvathAnton** [comment]
I do exactly what you wrote but still the same error appears 

Here is the bottom of the log its so long.

Microsoft (R) Program Maintenance Utility Version 14.12.25835.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\doc\global C:\.conan\f4lv5t0x\1\doc\global
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\bin\fixqt4headers.pl C:\.conan\f4lv5t0x\1\bin\fixqt4headers.pl
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\bin\syncqt.pl C:\.conan\f4lv5t0x\1\bin\syncqt.pl
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\lu3si6i5\1\qtbase\mkspecs\qconfig.pri C:\.conan\f4lv5t0x\1\mkspecs\qconfig.pri
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\lu3si6i5\1\qtbase\mkspecs\qmodule.pri C:\.conan\f4lv5t0x\1\mkspecs\qmodule.pri
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\lu3si6i5\1\qtbase\mkspecs\qdevice.pri C:\.conan\f4lv5t0x\1\mkspecs\qdevice.pri
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\aix-g++ C:\.conan\f4lv5t0x\1\mkspecs\aix-g++
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\aix-g++-64 C:\.conan\f4lv5t0x\1\mkspecs\aix-g++-64
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\android-clang C:\.conan\f4lv5t0x\1\mkspecs\android-clang
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\android-g++ C:\.conan\f4lv5t0x\1\mkspecs\android-g++
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\common C:\.conan\f4lv5t0x\1\mkspecs\common
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\cygwin-g++ C:\.conan\f4lv5t0x\1\mkspecs\cygwin-g++
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\darwin-g++ C:\.conan\f4lv5t0x\1\mkspecs\darwin-g++
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\devices C:\.conan\f4lv5t0x\1\mkspecs\devices
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\dummy C:\.conan\f4lv5t0x\1\mkspecs\dummy
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\features C:\.conan\f4lv5t0x\1\mkspecs\features
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\freebsd-clang C:\.conan\f4lv5t0x\1\mkspecs\freebsd-clang
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\freebsd-g++ C:\.conan\f4lv5t0x\1\mkspecs\freebsd-g++
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\haiku-g++ C:\.conan\f4lv5t0x\1\mkspecs\haiku-g++
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\hpuxi-g++-64 C:\.conan\f4lv5t0x\1\mkspecs\hpuxi-g++-64
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\hurd-g++ C:\.conan\f4lv5t0x\1\mkspecs\hurd-g++
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\integrity-armv7 C:\.conan\f4lv5t0x\1\mkspecs\integrity-armv7
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\integrity-armv7-imx6 C:\.conan\f4lv5t0x\1\mkspecs\integrity-armv7-imx6
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\integrity-armv8-rcar C:\.conan\f4lv5t0x\1\mkspecs\integrity-armv8-rcar
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\integrity-x86 C:\.conan\f4lv5t0x\1\mkspecs\integrity-x86
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\linux-aarch64-gnu-g++ C:\.conan\f4lv5t0x\1\mkspecs\linux-aarch64-gnu-g++
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\linux-arm-gnueabi-g++ C:\.conan\f4lv5t0x\1\mkspecs\linux-arm-gnueabi-g++
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\linux-clang C:\.conan\f4lv5t0x\1\mkspecs\linux-clang
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\linux-clang-libc++ C:\.conan\f4lv5t0x\1\mkspecs\linux-clang-libc++
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\linux-g++ C:\.conan\f4lv5t0x\1\mkspecs\linux-g++
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\linux-g++-32 C:\.conan\f4lv5t0x\1\mkspecs\linux-g++-32
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\linux-g++-64 C:\.conan\f4lv5t0x\1\mkspecs\linux-g++-64
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\linux-icc C:\.conan\f4lv5t0x\1\mkspecs\linux-icc
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\linux-icc-32 C:\.conan\f4lv5t0x\1\mkspecs\linux-icc-32
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\linux-icc-64 C:\.conan\f4lv5t0x\1\mkspecs\linux-icc-64
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\linux-icc-k1om C:\.conan\f4lv5t0x\1\mkspecs\linux-icc-k1om
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\linux-llvm C:\.conan\f4lv5t0x\1\mkspecs\linux-llvm
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\linux-lsb-g++ C:\.conan\f4lv5t0x\1\mkspecs\linux-lsb-g++
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\lynxos-g++ C:\.conan\f4lv5t0x\1\mkspecs\lynxos-g++
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\macx-clang C:\.conan\f4lv5t0x\1\mkspecs\macx-clang
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\macx-g++ C:\.conan\f4lv5t0x\1\mkspecs\macx-g++
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\macx-icc C:\.conan\f4lv5t0x\1\mkspecs\macx-icc
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\macx-ios-clang C:\.conan\f4lv5t0x\1\mkspecs\macx-ios-clang
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\macx-tvos-clang C:\.conan\f4lv5t0x\1\mkspecs\macx-tvos-clang
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\macx-watchos-clang C:\.conan\f4lv5t0x\1\mkspecs\macx-watchos-clang
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\macx-xcode C:\.conan\f4lv5t0x\1\mkspecs\macx-xcode
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\netbsd-g++ C:\.conan\f4lv5t0x\1\mkspecs\netbsd-g++
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\openbsd-g++ C:\.conan\f4lv5t0x\1\mkspecs\openbsd-g++
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\qnx-aarch64le-qcc C:\.conan\f4lv5t0x\1\mkspecs\qnx-aarch64le-qcc
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\qnx-armle-v7-qcc C:\.conan\f4lv5t0x\1\mkspecs\qnx-armle-v7-qcc
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\qnx-x86-64-qcc C:\.conan\f4lv5t0x\1\mkspecs\qnx-x86-64-qcc
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\qnx-x86-qcc C:\.conan\f4lv5t0x\1\mkspecs\qnx-x86-qcc
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\solaris-cc C:\.conan\f4lv5t0x\1\mkspecs\solaris-cc
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\solaris-cc-64 C:\.conan\f4lv5t0x\1\mkspecs\solaris-cc-64
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\solaris-cc-64-stlport C:\.conan\f4lv5t0x\1\mkspecs\solaris-cc-64-stlport
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\solaris-cc-stlport C:\.conan\f4lv5t0x\1\mkspecs\solaris-cc-stlport
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\solaris-g++ C:\.conan\f4lv5t0x\1\mkspecs\solaris-g++
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\solaris-g++-64 C:\.conan\f4lv5t0x\1\mkspecs\solaris-g++-64
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\unsupported C:\.conan\f4lv5t0x\1\mkspecs\unsupported
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\win32-clang-g++ C:\.conan\f4lv5t0x\1\mkspecs\win32-clang-g++
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\win32-clang-msvc C:\.conan\f4lv5t0x\1\mkspecs\win32-clang-msvc
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\win32-g++ C:\.conan\f4lv5t0x\1\mkspecs\win32-g++
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\win32-icc C:\.conan\f4lv5t0x\1\mkspecs\win32-icc
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\win32-icc-k1om C:\.conan\f4lv5t0x\1\mkspecs\win32-icc-k1om
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\win32-msvc C:\.conan\f4lv5t0x\1\mkspecs\win32-msvc
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\winrt-arm-msvc2015 C:\.conan\f4lv5t0x\1\mkspecs\winrt-arm-msvc2015
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\winrt-arm-msvc2017 C:\.conan\f4lv5t0x\1\mkspecs\winrt-arm-msvc2017
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\winrt-x64-msvc2015 C:\.conan\f4lv5t0x\1\mkspecs\winrt-x64-msvc2015
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\winrt-x64-msvc2017 C:\.conan\f4lv5t0x\1\mkspecs\winrt-x64-msvc2017
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\winrt-x86-msvc2015 C:\.conan\f4lv5t0x\1\mkspecs\winrt-x86-msvc2015
        C:\.conan\lu3si6i5\1\qtbase\bin\qmake.exe -install qinstall C:\.conan\dbm7rgwk\1\qt5\qtbase\mkspecs\winrt-x86-msvc2017 C:\.conan\f4lv5t0x\1\mkspecs\winrt-x86-msvc2017
Qt/5.11.1@bincrafters/stable: Package '7e4c0a6aad9c3f9e1ada5058e5ec3bd1d8b2139d' built
Qt/5.11.1@bincrafters/stable: Build folder C:/.conan\lu3si6i5\1
Qt/5.11.1@bincrafters/stable: Generated conaninfo.txt
Qt/5.11.1@bincrafters/stable: Generated conanbuildinfo.txt
Qt/5.11.1@bincrafters/stable: Generating the package
Qt/5.11.1@bincrafters/stable: Package folder C:/.conan\f4lv5t0x\1
Qt/5.11.1@bincrafters/stable: Calling package()
Qt/5.11.1@bincrafters/stable: WARN: No files copied from source folder!
Qt/5.11.1@bincrafters/stable package(): Copied 1 '.conf' file: qt.conf
Qt/5.11.1@bincrafters/stable: Package '7e4c0a6aad9c3f9e1ada5058e5ec3bd1d8b2139d' created
Qt/5.11.1@bincrafters/stable (test package): Generator cmake created conanbuildinfo.cmake
Qt/5.11.1@bincrafters/stable (test package): Generator txt created conanbuildinfo.txt
Qt/5.11.1@bincrafters/stable (test package): Generated conaninfo.txt
Qt/5.11.1@bincrafters/stable (test package): Running build()
Qt/5.11.1@bincrafters/stable (test package): Building with qmake
Project ERROR: Cannot run compiler 'cl'. Output:
===================
===================
Maybe you forgot to setup the environment?
ERROR: PROJECT: Error in build() method, line 19
        self.run("qmake %s" % self.source_folder)
        ConanException: Error 3 while executing qmake C:\Work\Foxit\conan-qt\test_package

**Comment by ericLemanissier** [comment]
ok, it seems to break because CL is not in your path. I modified the test recipe on my repo to handle this case. Could you please download https://raw.githubusercontent.com/ericLemanissier/conan-qt/stable/5.11.1/test_package/conanfile.py and replace the existing conanfile.py file inside the test_package directory ?

**Comment by HorvathAnton** [comment]
Your new python script solve the iisue https://raw.githubusercontent.com/ericLemanissier/conan-qt/stable/5.11.1/test_package/conanfile.py

Thanks. 

However, I have another question which is not related to this issue. 
When I take the code from test_package folder delete the conanfile.py and replace it with conanfile.txt which include conan-qt package and use cmake as a generator and run command. 

conan install .

The process is ends properly but I have no build folder. Thats why I cant open my .pro qt preject. I really don't know what else I have to do to be able to properly use the conan-qt package in real project.

**Comment by ericLemanissier** [comment]
Good news that it solved the issue.
For your second question, it depends on how you expect to build your project:
if you want to call qmake+make from the command line, then use the [virtualenv generator](https://docs.conan.io/en/latest/reference/generators/virtualenv.html). You can the do conan install, call activate.bat, and the qmake+om/nmake
if you want to build your project from qt creator, then I think you have no other choice than going in options->kits, to add a Qt Version which points to the conan's package folder, then add a kit using this Qt Version and the proper compiler.
If you have other dependencies than Qt in your conanfile, you can use the [qmake generator](https://docs.conan.io/en/latest/reference/generators/qmake.html). In this case I recommend you add a custom compilation step calling conan install, before qmake step
