### ISSUE TITLE
[glad] 0.1.16a0 has been removed.

### ISSUE THREAD

**Issue by p-groarke** [bincrafters/community#389]
Why has 0.1.16a0 been removed? I created the glad package on 0.1.16a0. It works, there is no reason to remove it.

**Comment by p-groarke** [comment]
Seems like the build is broken. Will lend a hand when I have some time.

**Comment by SSE4** [comment]
from glad's readme:
```IMPORTANT: If you're experiencing errors like identifier "GLintptr" is undefined, update to the latest glad version!```
related issues:
https://github.com/Dav1dde/glad/issues/149
https://github.com/Dav1dde/glad/issues/148

**Comment by p-groarke** [comment]
@SSE4  If you want to keep v0.1.16a0, you could revert the merge that broke it. Or you could delete the version. Is the maintainer still around?

**Comment by SSE4** [comment]
as I understand reverting will not help, as glad downloads specs from Khronos site, and specs were updated, that's why it's broken now

**Comment by SSE4** [comment]
if update is not an option for you, I'll take a deeper look on how to workaround breaking changes in Khronos specification

**Comment by p-groarke** [comment]
No its OK. Trash it! ;)

**Comment by SSE4** [comment]
@p-groarke okay, less things to worry then :) I've removed branches for 0.1.16a0
