### ISSUE TITLE
package dependencies not found when using CI and forks due to wrong "remotes"

### ISSUE THREAD

**Issue by sigmoidal** [bincrafters/community#39]
There is workflow problem with the conan-template and specifically the build.py.
If you look at: https://github.com/bincrafters/conan-templates/blob/master/build.py#L67

```
62    builder = ConanMultiPackager(
63        username=username,
64        channel=channel,
65        reference=reference,
66        upload=upload,
67         remotes=upload,  # while redundant, this moves bincrafters remote to position 0
68        upload_only_when_stable=True,
69        stable_branch_pattern="stable/*")
```

this assumes that:
```
upload = "https://api.bintray.com/conan/{0}/public-conan".format(username)
```
exists and contains the repo where dependencies can be found.

So, if one forks from bincrafters and tries to build a package the bincrafters'  remote is not found, and in turn that prevents from using bincrafter's as a tree to lookup dependencies.

To solve this, one would have to ensure after forking that the bincrafters' remote repo is supplied, e.g. via CONAN_REMOTES.

I am not sure if this is an intended approach, but maybe we can do better? It is also a detail that people forking may not realize and thus have a hard time finding out why it is happening (took me a while to track down!)

As a very simple, yet probably also very effective way, I propose that we add to the remotes= used for CI the bincrafters' repository by default, if a CONAN_REMOTES is not provided, in the build.py.

After all this is intended to be used by us mainly, right?

**Comment by solvingj** [comment]
Thank you for raising this, should have a fix similar to what was suggested in the refresh.

**Comment by solvingj** [comment]
@uilianries has implemented better handling of remotes when templates used by non-bincrafters. if there are still corner cases, please reopen.
