### ISSUE TITLE
PROTOBUF_GENERATE_CPP missing feature or documentation

### ISSUE THREAD

**Issue by davidtazy** [bincrafters/community#395]
### Description of Problem, Request, or Question
i'm using cmake_find_package generator.
i would like to use the PROTOBUF_GENERATE_CPP function provided by cmake modules.

### Package Details (Include if Applicable)
* Package Name/Version: **conan-protobuf/3.6.1**
* Operating System: **Linux Ubuntu 16.04**
* Compiler+version: **gcc-5.4**
* Docker image: **lasote/conangcc72**

**Comment by uilianries** [comment]
I'll check later. Thank you for report it.

**Comment by uilianries** [comment]
Hi @DariuszOstolski !

Unfortunately is not possible to solve PROTOBUF_GENERATE_CPP by cmake_find_package generator.

The cmake_find_package doesn't solve additional cmake_module_path.  
What you are looking for is under package_folder/lib/cmake/protobuf/protobuf-module.cmake

My recommendation is use cmake_path instead:

```
# conanfile.txt
[requires]
protobuf/3.6.1@bincrafters/stable

[generators]
cmake_paths
```

    conan install ..
    cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=./conan_paths.cmake

```
# CMakeLists.txt
find_package(protobuf REQUIRED CONFIG)

...
protobuf_generate(TARGET ${PROJECT_NAME})
```

/cc @danimtb @lasote @memsharded

Hey Barbarians, is there some request to solve transitive CMake using cmake_module_path?

references:
https://blog.conan.io/2018/06/11/Transparent-CMake-Integration.html
https://docs.conan.io/en/latest/reference/generators/cmake_find_package.html
https://docs.conan.io/en/latest/reference/generators/cmake_paths.html
https://github.com/conan-io/conan/blob/master/conans/client/generators/cmake_find_package.py

**Comment by lasote** [comment]
I agree with you about using `cmake_paths` generator. You need the original CMake module containing the `PROTOBUF_GENERATE_CPP`, so the generated by `cmake_find_package` is not enough for you.

> Hey Barbarians, is there some request to solve transitive CMake using cmake_module_path?

What do you mean?

**Comment by uilianries** [comment]
Solve cmake_module_path by cmake_find_package, instead to use cmake_path
only.

**Comment by davidtazy** [comment]
ok, so switched to cmake_paths generator 
find_package(Protobuf) is ok, but....

![image](https://user-images.githubusercontent.com/30446373/44364342-fe327680-a4c6-11e8-8017-b2524d7022f2.png)

protoc cannot be launched because protoc dependencies are not in the path...

is it because of ? :
`[options]
 protobuf:shared=True
`

thanks.

**Comment by SSE4** [comment]
@davidtazy we're going to extract protoc into its own package (build_requires named protoc_installer) which will have no runtime dependencies

**Comment by SSE4** [comment]
@davidtazy we have just updated `protobuf/3.6.1` recipe, which now should use `protoc_installer`, which is always built statically to avoid such problems. please give an another try.

**Comment by SSE4** [comment]
interesting, these package must be x86 according to the conaninfo.txt:
https://bintray.com/bincrafters/public-conan/protobuf%3Abincrafters#files/bincrafters%2Fprotobuf%2F3.6.1%2Fstable%2Fpackage%2Fee49f89584777c36226cc37565c5080426372795
I'll check it in Docker and let you know

**Comment by SSE4** [comment]
@Croydon it was built 2 months ago, but become outdated only yesterday, when I built new packages :)

**Comment by davidtazy** [comment]
I did remove and download again 3.6.1 binaries and i'havv got same error

~/.conan/data/protobuf/3.6.1/bincrafters/stable/package/34f0007e0ad3739e1c5258a06decf641965e656a/lib/cmake/protobuf/protobuf-config-version.cmake
contains 
![image](https://user-images.githubusercontent.com/30446373/46548851-7f579880-c8d0-11e8-843a-d5df08688c3f.png)
i patched this file to assume 32bits machines
cmake  is ok

then run make with a protoc error
and i think the 64bit version was downloaded
![image](https://user-images.githubusercontent.com/30446373/46549767-68667580-c8d3-11e8-9893-d08646b1b885.png)

**Comment by SSE4** [comment]
okay, I am looking into this problem

**Comment by uilianries** [comment]
@Croydon yes, It should. I'll check later.

**Comment by Croydon** [comment]
> yes, It should. I'll check later.

@uilianries No need. I misinterpreted the statement of @SSE4. The script should work fine :)

**Comment by uilianries** [comment]
nice! :+1:

**Comment by SSE4** [comment]
@davidtazy I've updated protobuf and protoc_installer packages, could you please give an another try?

**Comment by davidtazy** [comment]
@uilianries ,
 its seems like good practice is to use cmake_find_package generator now.
so how to access protobuf_generate_cpp function? 
I understand that cmake guys should separate find_package (to link) and helper functions., but they not.
my solution is to rm conan generated FindProtobuf.cmake....

thx

**Comment by uilianries** [comment]
Hi @DariuszOstolski !

Actually we moved Protobuf recipe to Conan Center Index: https://conan.io/center/protobuf

Yes, `cmake_find_package` it's a good practice. Related to the macros, the cmake files with those macros are copied when building the package. Macro is a special case that we can't emulate, so the best approach is copying it to the package folder.
