### ISSUE TITLE
Bullet: Wrong package reference in Bintray

### ISSUE THREAD

**Issue by Enhex** [bincrafters/community#398]
### Description of Problem, Request, or Question
for: https://github.com/bincrafters/conan-bullet
in: https://bintray.com/bincrafters/public-conan/bullet%3Abincrafters/2.87%3Astable
The reference is listed as:
`bullet3/2.87@bincrafters/stable`
instead of:
`bullet/2.87@bincrafters/stable`
(should be `bullet` without `3`)

**Comment by Croydon** [comment]
The GitHub repository needs to be renamed and the name in the recipe changed.

**Comment by uilianries** [comment]
Now I'm confused. Should we use bullet or bullet3 ?

The original project is https://github.com/bulletphysics/bullet3 with `3`  
And all libraries generated by the project are `Bullet3???`

**Comment by Croydon** [comment]
> in my understanding, it should be bullet3

Correct
