### ISSUE TITLE
fmt link error

### ISSUE THREAD

**Issue by sinall** [bincrafters/community#399]
### Package Details (Include if Applicable)
* Package Name/Version: **fmt/5.1.0**
* Operating System: **Windows 10**
* Compiler+version: **VC++ 2015U3**

### Steps to reproduce (Include if Applicable)

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	LNK2019	unresolved external symbol "class fmt::v5::internal::fp __cdecl fmt::v5::internal::get_cached_power(int,int &)" (?get_cached_power@internal@v5@fmt@@YA?AVfp@123@HAAH@Z) referenced in function "private: void __thiscall fmt::v5::basic_writer<class fmt::v5::back_insert_range<class fmt::v5::internal::basic_buffer<char> > >::write_double<double>(double,class fmt::v5::basic_format_specs<char> const &)" (??$write_double@N@?$basic_writer@V?$back_insert_range@V?$basic_buffer@D@internal@v5@fmt@@@v5@fmt@@@v5@fmt@@AAEXNABV?$basic_format_specs@D@12@@Z)

I have tried to build source, get same error.

I can use pre-defined macro 'FMT_HEADER_ONLY' to make it work.

**Comment by sinall** [comment]
BTW, even "fmt:shared=True" is configured, conan still produces dll.

**Comment by uilianries** [comment]
@sinall do you have some example to reproduce this error, including the package id?

I opened an issue to check this, but any new information could help.

**Comment by sinall** [comment]
Any example would reproduce this, since this is a link error, not runtime error.
`format("{:*^30}", "centered");  // use '*' as a fill char`

**Comment by uilianries** [comment]
Hi @sinall !

I just updated our recipe.

Could you try it again? It's possible to use find_package directly:

https://github.com/bincrafters/conan-fmt/blob/stable/5.1.0/test_package/CMakeLists.txt

Cheers!

**Comment by sinall** [comment]
Did you have a try?

I Got:

> 
> Severity	Code	Description	Project	File	Line	Suppression State
> Error	LNK2001	unresolved external symbol "public: static char const * const fmt::v5::internal::basic_data<void>::DIGITS" (?DIGITS@?$basic_data@X@internal@v5@fmt@@2QBDB)
> fmt::v5::internal::basic_data<void>::POWERS_OF_10_32" (?POWERS_OF_10_32@?$basic_data@X@internal@v5@fmt@@2QBIB)	
> Error	LNK2001	unresolved external symbol "public: static unsigned __int64 const * const fmt::v5::internal::basic_data<void>::POWERS_OF_10_64" (?POWERS_OF_10_64@?$basic_data@X@internal@v5@fmt@@2QB_KB)	
>

**Comment by sinall** [comment]
I can also see a **dll** been installed, my configuration is "**fmt:shared=True**".

**Comment by uilianries** [comment]
did you import .dll in your bin folder?

```
def imports(self):
    self.copy("*.dll", "bin", "bin")
```

**Comment by sinall** [comment]
@uilianries It's a link error.

"**fmt:shared=True**" should generate static lib, right?

**Comment by uilianries** [comment]
Oh, yes I got your point now. Yes, it generates both .lib and .dll, although the .lib is just a wrapper to link.

We are forcing CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS in CMake because we detected in the past that fmt doesn't export all symbols when built as shared.

I'll remove this sentence to check what happens now.

**Comment by uilianries** [comment]
Hi @sinall !

The problem was that `FMT_SHARED` should be defined in compiler flags when shared is True.

Please, update the fmt package :)

**Comment by sinall** [comment]
@uilianries build successfully. But it says 'fmtd.dll' is missing when run.

Does it generate a real static lib or a wrapper as you mentioned above?

**Comment by uilianries** [comment]
> Does it generate a real static lib or a wrapper as you mentioned above?

Just a wrapper.

Okay, I moved the .dll to /lib again. It should work now. There is a new version for Windows on Bintray. I'm waiting for Travis to upload the Linux version.

Did you import the .dll file, or are you using RunEnvironment?
https://docs.conan.io/en/latest/reference/conanfile_txt.html#imports

**Comment by sinall** [comment]
Do you know why it doesn't have a real static lib?

**Comment by uilianries** [comment]
It's because the option shared is True in such case. This option is used to
provide a DLL but you need to solve all symbols during the linkage so the
static wrapper is the reason.

**Comment by sinall** [comment]
Oh, my bad, shared=True means 'dll'.
It works now.
