### ISSUE TITLE
Libusb does not build on ArchLinux

### ISSUE THREAD

**Issue by JBHarvey** [bincrafters/community#400]
### Description of Problem
I'm developing an application that requires `libusb`.  
This application has to be cross platform on several linux and windows, so we use `conan`.  
When the build process (with cmake) runs, it crashes with during the conan installation step because of an error in the installation of `libusb`.  

#### Error log
```
-- The CXX compiler identification is GNU 8.2.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- 
-- Downloading conan dependencies
-- 
libusb/1.0.22@bincrafters/stable: Retrieving from predefined remote 'bincrafters'
libusb/1.0.22@bincrafters/stable: Trying with 'bincrafters'...
Downloading conanmanifest.txt

Downloading conanfile.py

Downloading conan_export.tgz

PROJECT: Installing /home/jb/Dropbox/work/phantom-intelligence/SensorGateway/sensor-gateway/conanfile.txt
Requirements
    libusb/1.0.22@bincrafters/stable from 'bincrafters' - Downloaded
Packages
    libusb/1.0.22@bincrafters/stable:6b13d6d5aa4bb4227960b1305bbafd5dd7aee07d - Build

libusb/1.0.22@bincrafters/stable: ERROR: while executing system_requirements(): Could not install libudev: Undefined package name for platform.
ERROR: Error in system requirements

CMake Error at cmake-module/setupConanDependenciesAndLinkToTarget.cmake:24 (message):
  Could not run conan.

   Make sure 'conan' is installed
Call Stack (most recent call first):
  sensor-gateway/CMakeLists.txt:15 (setup_conan_dependencies_and_link_to_target)


-- Configuring incomplete, errors occurred!
```

#### Exact error location
The crash happens in the `.conan/data/libusb/1.0.22/bincrafters/stable/export/conanfile.py`, `line 57` in the `system_requirements` function (line 40).   
My guess is because there is no `elif os_info.with_<name for arch /* pacman I guess? */>:` case handling that would set the correct name for the `libudev_name` variable.  
Here's the function in which the crash occurs:  
```
    def system_requirements(self):
        if self.settings.os == "Linux":
            if self.options.enable_udev:
                package_tool = tools.SystemPackageTool()
                libudev_name = ""
                os_info = tools.OSInfo()
                if os_info.with_apt:
                    libudev_name = "libudev-dev"
                    if tools.detected_architecture() == "x86_64" and str(self.settings.arch) == "x86":
                        libudev_name += ":i386"
                    elif "x86" in tools.detected_architecture() and "arm" in str(self.settings.arch):
                        libudev_name += ":armhf"
                elif os_info.with_yum:
                    libudev_name = "libudev-devel"
                    if tools.detected_architecture() == "x86_64" and str(self.settings.arch) == "x86":
                        libudev_name += ".i686"
                else:
                    raise Exception("Could not install libudev: Undefined package name for platform.")
                package_tool.install(packages=libudev_name, update=True)

```

### Package Details 
* Package Name/Version: **libusb/1.0.22:stable**   
* Bincrafter/public-conan reference:  **libusb/1.0.22@bincrafters/stable**  
* Operating System: **Arch Linux 4.17.13**  
* Compiler+version: **gcc-8.2.0**  

### Steps to reproduce
1. Clone [the project](https://github.com/PhantomIntelligence/SensorGateway/tree/feature/WAG-56/wagner-support)  
2. `git checkout feature/WAG-56/wagner-support`  
3. Run:  
```
mkdir cmake-build-debug
cd cmake-build-debug
cmake -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - UnixMakefile" ..
```
(the cmake process should fail because of a conan error)

**Comment by JBHarvey** [comment]
@uilianries  is there anything I can do to help with the resolving of this issue?  
I am required to make this work and I am blocked by this problem...

**Comment by uilianries** [comment]
Hi @JBHarvey !

libusb requires libudev, but is totally insane to package libudev only.

My recommendation as workaround is skip `system_requirements` and try to solve libudev by your native package manager (pacman).

I don't know if Conan supports pacman. Also, I'll check later how to install libudev by pacman and update this recipe.

Sorry about this.

**Comment by uilianries** [comment]
UPDATE:

You could skip libudev integration by the option `libusb:enable_udev=False`


    conan install libusb/1.0.22@bincrafters/stable -o libusb:enable_udev=False

This approach should be enough to solve your problem by now

**Comment by JBHarvey** [comment]
@uilianries adding `-o libusb:enable_udev=False` did the trick on arch!
> although it might break other things the other distros I need to support, I'll have to check.


On the subject of `libudev`, it is packaged in `libsystemd`, which is a core library of Arch. so AFAIK libudev is installed by default.
If I may be so bold and suggest: maybe a solution to the problem would be not to throw an error in the `system_requirements` function of the `conanfile.py` of `libusb` when the os is arch for the `libudev` dependency?

**Comment by uilianries** [comment]
> maybe a solution to the problem would be not to throw an error in the system_requirements function of the conanfile.py of libusb when the os is arch for the libudev dependency?

Well, I could change to an warning message only. I think that is enough to avoid future problems involving libudev.

But anyway, I'll support arch linux, using pacman.

**Comment by uilianries** [comment]
@JBHarvey I merged the Arch linux support. Could you check the new version?

**Comment by JBHarvey** [comment]
@uilianries it work!

**Comment by uilianries** [comment]
Nice! :smile:
