### ISSUE TITLE
wxWidgets 3.1.1 segmentation fault on linux

### ISSUE THREAD

**Issue by MB3hel** [bincrafters/community#401]
### Description of Problem, Request, or Question
I have a simple GUI calculator program that I use for testing. The GUI is created with wxWidgets (3.1.1) and I use cmake as the build system. I use the bincrafters wxwidgets 3.1.1 package with conan and everything works perfectly on windows (MSVC 14) and macOS (Apple Clang 9.1.0), but when trying to build on linux (Ubuntu 16.04 with gcc 5.4.0) the program builds successfully without errors, however when I run the program it always results in a segmentation fault. When I build using shared libs (`-o wxwidgets:shared=True`) I get an error message like the one below

```*** Error in` ./wxCalc': free(): invalid pointer: 0x00007f3717e91178 ***```

The following memory map does not idientify a specific library using that address.This program builds and runs ccorrectly when I use cmake's find_package function to find the system wxWidgets library (also version 3.1.1 installed from codelite repos).

### Package Details (Include if Applicable)
* Package Name/Version: **wxwidgets/3.1.1**
* Operating System: **Linux Ubuntu 16.04**
* Compiler+version: **gcc-5.4.0**

### Steps to reproduce (Include if Applicable)
The wxCalculator project is in [wxcalculator.zip](https://github.com/bincrafters/community/files/2287655/wxcalculator.zip)
Install conan and cmake.
Extract the zip and open terminal in the project direcotory. Run the following commands
```
mkdir build
cd build
conan install ..
cmake ..
cmake -- build .
bin/wxCalc
```
A segmentation fault will occur.

**Comment by SSE4** [comment]
@MB3hel the problem is abi mismatch
default conan profile is:
```
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=5
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]
```
after changing `compiler.libcxx=libstdc++11` in `~/.conan/profiles/default` I've got no segmentation fault:
```
conan@1c6da621aa3f:/host/conan/wxcalculator/build$ ./bin/wxCalc
12:55:37: Error: Unable to initialize GTK+, is DISPLAY set properly?
```

**Comment by MB3hel** [comment]
@SSE4 This does seem to fix the problem, however changing it to libstdc++11 requires that the package be built from source. 

My default profile is as follows.

```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=5
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

It might be a good idea to pre-build a version of the wxWidgets package with libstdc++11.

**Comment by SSE4** [comment]
@MB3hel  sure, I'll add this configuration to our CI
