### ISSUE TITLE
ConanException: Error -1073740791 while executing qmake_folder/...

### ISSUE THREAD

**Issue by HorvathAnton** [bincrafters/community#402]
Hello 

I upload the binaries  and recipe to artifactory server. Now when I delete package from my local cache and try to download binaries from server it's work for Mac but fails on Win with this error:

ERROR: PROJECT: Error in test() method, line 57
        self.run(os.path.join("qmake_folder", bin_path, "imageviewer"))
        ConanException: Error -1073740791 while executing qmake_folder\release\imageviewer

Can you please help me.

Thanks.

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=15
build_type=Release

**Comment by dudasl** [comment]
Looks like path to `plugins\platforms\` is not registered while downloading binaries from server. It's only windows problem. Any GUI application needs known where qwindows.dll is located.

When I run `set QT_QPA_PLATFORM_PLUGIN_PATH=d:\.conan\cp1oerak\1\plugins\platforms\` before running test it works fine. I found similar issue (https://github.com/mmozeiko/RcloneBrowser/issues/59#issuecomment-305107762).

When we build binaries on computer from source codes it works perfectly. When using artifacts from server it doesn't work. Looks like building process registers path to `plugins\platforms\` path but I cannot find where.

**Comment by ericLemanissier** [comment]
I just uploaded a new version of the 5.11.2 recipe. You can now add the "qt" generator to your conanfile, and it will create the qt.conf file for you. You just have to copy/move it in the directory containing the application executable. With this you should not have to use QT_QPA_PLATFORM_PLUGIN_PATH environment variable. Can you tell me if it works for you ?

**Comment by dudasl** [comment]
Hello, I tried compile our small demo application using 5.11.2 recipe but didn't success:
```
D:\QtSamples\Demo_application>conan remote list
conan-center: https://conan.bintray.com [Verify SSL: True]
bincrafters: https://api.bintray.com/conan/bincrafters/public-conan [Verify SSL: True]

D:\QtSamples\Demo_application>conan install .
Qt/5.11.2@bincrafters/public-conan: Not found in local cache, looking in remotes...
Qt/5.11.2@bincrafters/public-conan: Trying with 'conan-center'...
Qt/5.11.2@bincrafters/public-conan: Trying with 'bincrafters'...
ERROR: Failed requirement 'Qt/5.11.2@bincrafters/public-conan' from 'PROJECT'
ERROR: Unable to find 'Qt/5.11.2@bincrafters/public-conan' in remotes
```

Is Qt/5.11.2@bincrafters/public-conan correct?

**Comment by ericLemanissier** [comment]
No, Qt/5.11.2@bincrafters/stable is the correct reference

**Comment by solvingj** [comment]
@dudasl can you please reopen case if your issue is not fixed ?

**Comment by dudasl** [comment]
Sorry didn't reply. With reference send by @ericLemanissier all was fine.
