### ISSUE TITLE
opus/1.2.1 library includes main function

### ISSUE THREAD

**Issue by madebr** [bincrafters/community#404]
### Description of Problem, Request, or Question
The package `opus/1.2.1@bincrafters/stable` on Windows includes a main function.
I have  detected this because when linking my test application with opus (through ffmpeg) before boost (unit_test_framework), the linker selects the main function from opus instead of the main function of boost.

I believe it's [this file](https://github.com/xiph/opus/blob/master/src/opus_compare.c) that is included in the library.

### Package Details (Include if Applicable)
* Package Name/Version: **opus/1.2.1**
* Operating System: **Windows**
* Compiler+version: **Visual Studio 15 2017**

### Steps to reproduce (Include if Applicable)

The project below should fail at the linking stage because of the missing main function, but it does not.

conanfile.txt
```
[requires]
opus/1.2.1@bincrafters/stable

[generators]
cmake
```
CMakeLists.txt
```
cmake_minimum_required(VERSION 3.8)
project(opus_test C)

 include("${CMAKE_BINARY_DIR}/conanbuildinfo.cmake")
 conan_basic_setup(TARGETS)

 add_executable(app file.c)
 target_link_libraries(app
    PUBLIC
        CONAN_PKG::opus
    )
```
file.c (extracted from [here](https://github.com/xiph/opus/blob/master/doc/trivial_example.c))
```
#include <opus/opus.h>
#include <stdio.h>

#define SAMPLE_RATE 48000
#define CHANNELS 2
#define APPLICATION OPUS_APPLICATION_AUDIO

void some_function() {
    int err;
    OpusEncoder *encoder = opus_encoder_create(SAMPLE_RATE, CHANNELS, APPLICATION, &err);
    if (err < 0)
    {
        printf("failed to create an encoder: %s\n", opus_strerror(err));
        return;
    }
    opus_encoder_destroy(encoder);
}
```

**Comment by SSE4** [comment]
@madebr I've excluded opus_compare.c from the build, please give an another try

**Comment by madebr** [comment]
Works! Thanks!
