### ISSUE TITLE
Update spdlog to version 1.1.0

### ISSUE THREAD

**Issue by james-atkins** [bincrafters/community#408]
spdlog v1.1.0 was [released](https://github.com/gabime/spdlog/releases/tag/v1.1.0) yesterday.

**Comment by uilianries** [comment]
Done!

https://github.com/bincrafters/conan-spdlog/tree/stable/1.1.0
https://bintray.com/bincrafters/public-conan/spdlog%3Abincrafters/1.1.0%3Astable
