### ISSUE TITLE
Inclusion request review for mbedtls into conan-center

### ISSUE THREAD

**Issue by danimtb** [bincrafters/community#409]
## Inclusion Request Review

This is a review for [mbedtls/2.11.0@bincrafters/stable (bincrafters/public-conan)](https://github.com/bincrafters/conan-mbedtls) inclusion request to conan-center.
This review follows the [inclusion guidelines of third party libraries](http://docs.conan.io/en/latest/uploading_packages/bintray/conan_center_guide.html#inclusion-guidelines-for-third-party-libraries).

### Package
mbedtls/2.11.0@bincrafters/stable

#### Recipe quality
- [x] Git public repository
- [x] Recipe fields
- [x] Linter
- [x] Updated
- [x] Clean
- [x] test_package
- [x] Raise errors on invalid configurations
- [x] LICENSE of the recipe
- [x] LICENSE of the library

#### CI Integration
- [x] Provide at least one CI configuration (header only)
- [x] (If not header only) CI configurations for Linux/MacOSX/Windows

#### Bintray Package Information
- [x] Description
- [x] Licenses
- [x] Tags: Add some tags describing the library
- [x] Maturity: Fill this field in Bintray
- [x] Website (if any)
- [x] Issue tracker
- [x] Version control

### Additional comments

**Missing packages for Visual Studio 12**

**Comment by danimtb** [comment]
Thanks for the update @SSE4.

Having a second look at the conanfile I am concerned about `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS` as it is [supported from CMake 3.4 onwards](https://blog.kitware.com/create-dlls-on-windows-without-declspec-using-new-cmake-export-all-feature/) and original _CMakeLists.txt_ says minimum required version is 2.6. However, minimum required version of your _CMakeLists.txt_ wrapper declares 2.8.11. Is this definition truly needed for Win shared builds?

If so, I'd rather use 3.4 as minimum required version in the wrapper.

Also beware that there is no `fPIC` option. Not something compulsory, just to let you know if you want to add it in next changes.

Thanks

**Comment by SSE4** [comment]
@danimtb thanks for noticing
I'll update minimum required version, as well as add fPIC option and let you know.

**Comment by SSE4** [comment]
@danimtb done

**Comment by danimtb** [comment]
My mistake @SSE4, forgot to check that library licence was included in the package. Will accept it into conan-center but please update the package step with the license when possible.

Also 2.6.1 version will need an update with this little changes (not urgent).

Summary:
- Add Visual Studio 12
- Use CMake 3.4 as minimum required version in the wrapper
- Add fPIC option
- Include library license in package step.

Thanks a lot and sorry for the inconveniences 😥

**Comment by SSE4** [comment]
sure, will do and let you know

**Comment by SSE4** [comment]
@danimtb all done for both 2.6.1 and 2.11.0

**Comment by danimtb** [comment]
Thanks!!
