### ISSUE TITLE
Cannot compile Qt with Visual Studio 15.8.1

### ISSUE THREAD

**Issue by dudasl** [bincrafters/community#411]
I updated Visual Studio compiler to newest version (Microsoft (R) C/C++ Optimizing Compiler Version 19.15.26726 for x64) and now I cannot compile Qt from source codes while calling `conan create . Qt/5.11.1@bincrafters/public-conan`. Process fail to compile while compiling qrandom.cpp file. Error:
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include\type_traits(1271): error C2338: You've instantiated std::aligned_storage<Len, Align> with an extended alignment (in other words, Align > alignof(max_align_t)). Before VS 2017 15.8, the member type would non-conformingly have an alignment of only alignof(max_align_t). VS 2017 15.8 was fixed to handle this correctly, but the fix inherently changes layout and breaks binary compatibility (*only* for uses of aligned_storage with extended alignments). Please define either (1) _ENABLE_EXTENDED_ALIGNED_STORAGE to acknowledge that you understand this message and that you actually want a type with an extended alignment, or (2) _DISABLE_EXTENDED_ALIGNED_STORAGE to silence this message and get the old non-conformant behavior. (compiling source file D:\.conan\pyn4ai5r\1\qt5\qtbase\src\corelib\global\qrandom.cpp)
```

### Package Details (Include if Applicable)
* Package Name/Version: **Qt/5.11.1**
* Operating System: **Microsoft Windows 10 Pro build 17134**
* Compiler+version: **Microsoft (R) C/C++ Optimizing Compiler Version 19.15.26726 for x64**

### Steps to reproduce (Include if Applicable)
Just call `conan create . Qt/5.11.1@bincrafters/public-conan`

### Proposed solution
I know that this is bug in Qt, but you can pass `_DISABLE_EXTENDED_ALIGNED_STORAGE` to compiler while compiling on VS 15.8 or higher.

**Comment by greenjava** [comment]
A patch has been integrated to correct this ([Fix qtbase build for MSVC 2017 15.8 ](https://github.com/qt/qtbase/commit/0ef66e98ccf4946a0e4513ab5fc157df0f0aca4e)) and it'll be available in Qt 5.11.2
For the current version on bincrafters, we can apply the [patch](https://github.com/qt/qtbase/commit/0ef66e98ccf4946a0e4513ab5fc157df0f0aca4e.patch)
