### ISSUE TITLE
Protobuf cross compilation (protoc)

### ISSUE THREAD

**Issue by rodolfo-picoreti** [bincrafters/community#412]
### Description of Problem, Request, or Question
I am trying to cross compile the protobuf package using a conan arm docker image. But I dont think the recipe is complete enough to include this case, and I don't know exactly how to modify it since we need to compile the protobuf compiler in the host arch and the library in the target arch. 

### Package Details (Include if Applicable)
* Package Name/Version: **bincrafters/conan-protobuf**
* Operating System: **Linux Ubuntu 16.04**
* Compiler+version: **gcc-7.2**
* Docker image: **lasote/conangcc7-armv7**

**Comment by SSE4** [comment]
need to take a look in this use-case. probably splitting package into protoc and protobuf would be fine.

**Comment by SSE4** [comment]
I gonna split protobuf into two dedicated packages:
* protoc (protobuf compiler)
* protobuf (libraries)
two reasons:
* cross-compiling
* protoc might be useful as build_requires
/cc @uilianries @solvingj

**Comment by uilianries** [comment]
Excellent ideia @SSE4 !  
should we use protoc_installer in the name?

**Comment by SSE4** [comment]
yes, we can use protoc_installer for the consistency

**Comment by Croydon** [comment]
@SSE4 Do you understand where the current error is coming from?

>  setuptools_scm.version.SetuptoolsOutdatedWarning: your setuptools is too old (<12)

**Comment by Croydon** [comment]
@SSE4 Would you mind explaining why it uses CentOS containers?

**Comment by SSE4** [comment]
@Croydon I've used CentOS for build tools to ensure they work with older glibc. this is temporary, until I get glibc_version_header fully working.

**Comment by SSE4** [comment]
@Croydon for `SetuptoolsOutdatedWarning` - no idea unfortunately (probably you need to update python's setup tools somehow, but I don't have a detail)

**Comment by Croydon** [comment]
> for SetuptoolsOutdatedWarning - no idea unfortunately (probably you need to update python's setup tools somehow, but I don't have a detail)

This is happening in the CI and the docker files are already (trying) to update setuptools: https://github.com/bincrafters/docker-centos-gcc48/blob/21cbb8eae6c8cfc8208abeeb0acefe9e67f89516/Dockerfile#L15

Either the uploaded and therefore used containers are not up to date with this Dockerfile or this isn't working/enough.

I'm kinda interested in moving this forward, as this is blocking
protoc_installer
--> protoc_installer in conan-center 
----> protobuf in conan-center
------> grpc conan support upstream
but I'm not sure what needs to be done here (and if I would be capable to help at all)

**Comment by Croydon** [comment]
I believe @SSE4 has updated the CentOS containers while working on ragel. The CI is now green

**Comment by SSE4** [comment]
yes, @Croydon is absoltely right

**Comment by SSE4** [comment]
hi @rodolfo-picoreti 
I was able to successfully cross-compile `protobuf/3.6.1` with latest changes on `lasote/conangcc7-armv7` image. I've split protobuf and protoc_installer packages, and added required tweaks to enforce usage of protoc for build machine instead of target machine. could you please give a try?
once we're good with it, I'll backport all changes to other branches.

**Comment by rodolfo-picoreti** [comment]
Hey @SSE4 ,
What a coincidence, I was planning on taking a look on this today :)
I try to use it later and let you know. Thanks!

**Comment by rodolfo-picoreti** [comment]
bincrafters/conan-protoc_installer#1

**Comment by SSE4** [comment]
@rodolfo-picoreti PR was merged, does it work for you now?

**Comment by rodolfo-picoreti** [comment]
Hey @SSE4, I tested both the x86 and arm version and both seem to be working fine. Thank you all for the help! (@SSE4, @Croydon and @uilianries).

**Comment by digitalist** [comment]
thanks for the recipe but how do you add installed conan binary exec `protoc` file to path to actually use it?

**Comment by SSE4** [comment]
@digitalist if you add protoc_installer to your profile, it will be automatically added to the PATH by conan
