### ISSUE TITLE
Upgrade log4plus to new latest version

### ISSUE THREAD

**Issue by malirod** [bincrafters/community#417]
New version of log4cplus has been released recently 2.0.2 : https://github.com/log4cplus/log4cplus/releases/tag/REL_2_0_2

Please upgrade bincrafters repo.

**Comment by uilianries** [comment]
Done!

https://bintray.com/bincrafters/public-conan/log4cplus%3Abincrafters/2.0.2%3Astable

![log4plus](https://screenshotscdn.firefoxusercontent.com/images/c2488ec7-34e2-43a7-9d9e-3707fcbe0cdd.png)

**Comment by malirod** [comment]
Thanks!
