### ISSUE TITLE
libjpeg linker errors with wxWidgets when using MinGW-w64

### ISSUE THREAD

**Issue by MB3hel** [bincrafters/community#418]
### Description of Problem, Request, or Question
When trying to build a simple wxWidgets project using MinGW linking with libjpeg (9c) always fails with an Invalid Operation error.
```
C:/Users/marcu/.conan/data/libjpeg/9c/bincrafters/stable/package/138b9feca367fddcd510e3315f1e4b740ab5d9bc/lib/libjpeg.a(jcapimin.o): could not read symbols: Invalid operation
collect2.exe: error: ld returned 1 exit status
mingw32-make.exe[2]: *** [wxCalc\CMakeFiles\wxCalc.dir\build.make:130: bin/wxCalc.exe] Error 1
mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:184: wxCalc/CMakeFiles/wxCalc.dir/all] Error 2
mingw32-make.exe: *** [Makefile:151: all] Error 2
```
This same project works with MSVC.
I have tried building all libraries on my system, however there was no change.

### Package Details (Include if Applicable)
* Package Name/Version: **libjpeg/9c@bincrafters/stable** and (maybe) **wxwidgets/3.1.1@bincrafters/stable**
* Operating System: **Windows 10 Pro 1803**
* Compiler+version: **gcc-5.4, gcc-7.1, gcc-6  all x86_64 mingw-w64 posix/seh**

### Steps to reproduce (Include if Applicable)
The project can be found at: [https://drive.google.com/open?id=1HX6YZdNU8yaM57uDgO39vF8HUWWPdIBY](https://drive.google.com/open?id=1HX6YZdNU8yaM57uDgO39vF8HUWWPdIBY)

The mingw64 profile:
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=7.1
compiler.libcxx=libstdc++11
compiler.exception=seh
build_type=Release
[options]
[build_requires]
[env]
```

Run the following commands in the project's root dir:

```
mkdir build
cd build
conan install .. -pr mingw64 --build
```
You will now need to edit build\conanbuildinfo.cmake On line 4 there should be a wxWidgets lib dir specified. Add gcc_lib to the end of the path. So

`C:/Users/marcu/.conan/data/wxwidgets/3.1.1/bincrafters/stable/package/3b93b0a85f2288d620e8467cf856b03fe7751fec/lib/`

should become

`C:/Users/marcu/.conan/data/wxwidgets/3.1.1/bincrafters/stable/package/3b93b0a85f2288d620e8467cf856b03fe7751fec/lib/gcc_lib`

I have no idea what is going on because the library exists and was built on the same system with the same compiler. 

If anyone has any ideas as to what might cause this I would be happy to try to fix this problem.

**Comment by SSE4** [comment]
I'll take my time to reproduce, once https://github.com/bincrafters/community/issues/415 is done

**Comment by MB3hel** [comment]
It seems that this is caused by the fact that libjpeg requires the use of a windows subsystem (MSYS2 or unix). It is locating the MSYS2 installation on my machine and is using MSYS2 to compile libjpeg (which is, of course, incompatible with MinGW-w64). When I try to build in a VM without MSYS2 installed (just MinGW-w64) I get the following error:
```
libjpeg/9c@bincrafters/stable: WARN: Build folder C:\Users\mbehe\.conan\data\libjpeg\9c\bincrafters\stable\build\138b9feca367fddcd510e3315f1e4b740ab5d9bc
ERROR: libjpeg/9c@bincrafters/stable: Error in build() method, line 78
        self.build_configure()
while calling 'build_configure', line 70
        env_build.configure(configure_dir=self.source_subfolder, args=config_args)
        ConanException: Cannot recognize the Windows subsystem, install MSYS2/cygwin or specify a build_require to apply it.
``` 

@SSE4 Is there any way to remove this requirement on a windows subsystem, or is this a limitation of libjpeg?

**Comment by SSE4** [comment]
@MB3hel this is because libjpeg is autotools-base project, and requires various unix-like utilities to build (e.g. grep, sed, make, awk, etc.). either MSYS or Cygwin provide set of such utilities, while MinGW provides only compiler and related utilities (e.g. linker, archiver, striper, etc.). so, in order to build autotools-based project with MinGW, you need both MinGW and some subsystem.
utilities from subsystem in general shouldn't affect produced binary. this probably indicates it didn't pick up right compiler during the build (e.g. used GCC from MSYS instead of GCC from MinGW - GCC from MSYS may only produce binaries for MSYS subsystem itself, such binaries will depend on MSYS DLLs, and this is not something most users want). I'll take a look on what's going wrong with libjpeg build and let you know.

**Comment by MB3hel** [comment]
@SSE4 This seems to be caused by the Windows Subsystem for Linux, not MSYS2. 

Looking through build output I have found that `run_in_windows_bash` uses `C:\Windows\System32\bash.exe`, which is the WSL bash executable. I setup a Windows VM with MinGW-w64 and MSYS2 (No WSL). It builds and links correctly with the VM. 

It also works as intended when I put MSYS2's `/usr/bin` directory.

**Comment by SSE4** [comment]
@MB3hel thanks for the update
to clarify, do you need WSL use-case to be fixed?

**Comment by MB3hel** [comment]
@SSE4 I don't need it. Honestly it seems like it would be a lot of trouble to fix as there are two systems involved. It probably is not worth the time.

**Comment by MB3hel** [comment]
MSYS2 and Cygwin are more common and easier to use anyways.
