### ISSUE TITLE
Catch2 isn't usable on a 64-bit machine

### ISSUE THREAD

**Issue by cjdb** [bincrafters/community#419]
### Package Details (Include if Applicable)
* Package Name/Version: **catch2/2.3.0@bincrafters/stable**
* Operating System: **Linux Ubuntu 16.04**
* Compiler+version: **gcc-8**

## Description

While trying to build something with Conan (that uses Catch2), I encountered this diagnostic:

```
CMake Error at CMakeLists.txt:28 (find_package):
  Could not find a configuration file for package "Catch2" that is compatible
  with requested version "2.3.0".

  The following configuration files were considered but not accepted:

    /home/cjdb/.conan/data/catch2/2.3.0/bincrafters/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/lib/cmake/Catch2/Catch2Config.cmake, version: 2.3.0 (32bit)
```

@mmha identified that the call to write_basic_package_version_file in the root CMakeLists.txt generates something that checks the system architecture. Catch2 is specified to be a header-only library, but is checking for platform-specific information. By commenting out the following lines in `/home/cjdb/.conan/data/catch2/2.3.0/bincrafters/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/lib/cmake/Catch2/Catch2ConfigVersion.cmake`, we were able to kill the error:

```cmake
# check that the installed version has the same 32/64bit-ness as the one which is currently searching:
#if(NOT CMAKE_SIZEOF_VOID_P STREQUAL "4")
#  math(EXPR installedBits "4 * 8")
#  set(PACKAGE_VERSION "${PACKAGE_VERSION} (${installedBits}bit)")
#  set(PACKAGE_VERSION_UNSUITABLE TRUE)
```

I'm using a 64-bit machine, which is appears to be different to the bincrafters' machine (as it is expecting a 32-bit machine).

### Steps to reproduce

Add this to your project's CMakeLists.txt

```cmake
find_package(Catch2 2.3.0 REQUIRED)
```

### Extra information

```
# conanfile.txt
[requires]
boost/1.68.0@conan/stable
range-v3/0.3.6@ericniebler/stable
catch2/2.3.0@bincrafters/stable

[generators]
cmake_paths
virtualenv
```

**Comment by uilianries** [comment]
Hi @cjdb !

Thanks for report this issue. I'm going to provide a new patch soon.

**Comment by Quincunx271** [comment]
Same bug: #416

**Comment by uilianries** [comment]
Waiting for CI job ... Travis will push the new version on Bintray :)

**Comment by 3galki** [comment]
I have build your branch - nothing changed. tools.replace_in_file failed to locate file to patch because in some systems folder name is "lib64" instead of "lib"

**Comment by 3galki** [comment]
The following patch helps me. But I'm not sure that is the good way :)
`[root@66f09fc2afef conan-catch2]# git diff
diff --git a/conanfile.py b/conanfile.py
index 60ceae7..50f222c 100644
--- a/conanfile.py
+++ b/conanfile.py
@@ -42,7 +42,10 @@ class Catch2Conan(ConanFile):
         cmake.install()
         self.copy(pattern="LICENSE.txt", dst="licenses", src=self.source_subfolder)
         self.copy(pattern=self.header_name, dst=os.path.join("include", self.name))
-        self.copy(pattern="*.cmake", dst=module_dir, src=os.path.join(install_dir, module_dir))
+        source_dir = os.path.join(install_dir, module_dir)
+        if not os.path.exists(source_dir):
+          source_dir = os.path.join(install_dir, "lib64", "cmake", "Catch2")
+        self.copy(pattern="*.cmake", dst=module_dir, src=source_dir)
         tools.replace_in_file(os.path.join(self.package_folder, module_dir, "Catch2ConfigVersion.cmake"),
          "# if the installed or the using project don't have CMAKE_SIZEOF_VOID_P set, ignore it:", "return()")
 
`

**Comment by mmha** [comment]
There was a patch for the bitness check added upstream: catchorg/Catch2@646e1f608d37640d4f4e359cf6b7ff7d9c7bbcdd

**Comment by uilianries** [comment]
Hi guys! Thanks for reporting ...

I updated the package to install all files using `lib` folder.

https://github.com/bincrafters/conan-catch2/commit/623b7c51fd8e3b1915c2b2b3751bf710b777b0f8

Please, update your local copy.
