### ISSUE TITLE
Inclusion request for libtirpc

### ISSUE THREAD

**Issue by r-darwish** [bincrafters/community#421]
I created a package for [libtirpc](https://sourceforge.net/projects/libtirpc/). I'd like it to be transferred to Bincrafters.

https://github.com/r-darwish/conan-libtirpc

This library is only meant for Linux. Thus, I removed the AppVeyor file, as well the macOS entries from Travis.

**Comment by SSE4** [comment]
hi @r-darwish 
I've created a repository for you: https://github.com/bincrafters/conan-libtirpc
(you should get an e-mail from GitHub about access rights)
and triggered travis build: https://travis-ci.org/bincrafters/conan-libtirpc/builds/421899637

**Comment by SSE4** [comment]
I am closing for now as everything was set up and build was successful

**Comment by solvingj** [comment]
Awesome, thanks to both
