### ISSUE TITLE
 Incorrect 'gcc', is not the one detected by CMake: 'Clang'

### ISSUE THREAD

**Issue by HorvathAnton** [bincrafters/community#422]
Hi I used this command to change my compiler from apple-clang to gcc 

conan install . -s compiler=gcc -s compiler.libcxx=libstdc++ -s compiler.version=7

It is successfully built from sources but when I run my cmake command:

cmake build . -DCMAKE_CXX_COMPILER=/usr/bin/gcc

 its fail with the following error:

Tonys-MacBook-Pro:Demo_application tony$ cmake build . -DCMAKE_CXX_COMPILER=/usr/bin/gcc
-- The C compiler identification is AppleClang 9.1.0.9020039
-- The CXX compiler identification is AppleClang 9.1.0.9020039
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/gcc
-- Check for working CXX compiler: /usr/bin/gcc -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Current conanbuildinfo.cmake directory: /Users/tony/job/QtSamples/Demo_application
CMake Error at conanbuildinfo.cmake:470 (message):
  Incorrect 'gcc', is not the one detected by CMake: 'Clang'
Call Stack (most recent call first):
  conanbuildinfo.cmake:116 (conan_check_compiler)
  CMakeLists.txt:7 (conan_basic_setup)

[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=9.1
compiler.libcxx=libc++
build_type=Release

Please help thx.

**Comment by ericLemanissier** [comment]
Could you try the following ? 
quoting https://cmake.org/pipermail/cmake/2006-October/011638.html:
> Any time you change the compiler you have to wipe out the build tree and start from scratch.  Try running CMake like this instead:
>
> $ rm -rf build; mkdir build; cd build
> $ CC=gcc CXX=g++ cmake ..

**Comment by solvingj** [comment]
Closing due to lack of response. If still having issues, @HorvathAnton , please re-open your case here: 
https://github.com/conan-io/conan/issues
