### ISSUE TITLE
ffmpeg/4.0 with freetype enabled breaks ffmpeg build

### ISSUE THREAD

**Issue by joshgamer474** [bincrafters/community#424]
### Description of Problem, Request, or Question
I've found that there are a few issues when trying to build ffmpeg/4.0 with freetype enabled:
* Building ffmpeg/4.0 as Release with freetype enabled breaks ffmpeg's build due to pkg-config not being able to find png16.lib
`LINK : fatal error LNK1181: cannot open input file 'png16.lib'
ERROR: freetype2 not found using pkg-config`
* Build ffmpeg/4.0 as Debug with freetype enabled breaks ffmpeg's build due to pkg-config not being able to find freetype.lib
`LINK : fatal error LNK1181: cannot open input file 'freetype.lib'
ERROR: freetype2 not found using pkg-config`

I believe that both issues are due to the `pkgconfig/freetype.pc` and `pkgconfig/freetype2.pc` files that are generated from `export_source/freetype.pc.in` are incorrect/need to be modified, or more specifically this line in `freetype.pc.in`:
`Libs: -L${libdir} -lfreetype -lpng16 -lz `

When ffmpeg/4.0 is built as Debug, it creates these dependency libs: 
`freetyped.lib`, `libpngd.lib`, and `zlib.lib`

And when ffmpeg/4.0 is built as Release, it creates these dependency libs:
`freetype.lib`, `libpng.lib`, and `zlib.lib`

To fix building as Debug so freetyped.lib can be found, I think `freetype.pc.in` should be modified to use something like:
`Libs: -L${libdir} -lfreetyped -lpng16d -lz `

To fix building as Release so libpng16.lib can be found, I think `freetype.pc.in` should be modified to use something like:
`Libs: -L${libdir} -lfreetype -llibpng16 -lzlib `

Combine these two fixes and I think the solution for `freetype.pc.in` could look something like:
`debug_enabled=<Set or modify this in freetype's conanfile.py>`
`...`
`Libs: -L${libdir} -lfreetype${debug_enabled} -llibpng16${debug_enabled} -lzlib `

### Package Details (Include if Applicable)
* Package Name/Version: **ffmpeg/4.0**
* Package Name/Version: **freetype/2.8.1**
* Operating System: **Windows 10 Pro**
* Compiler+version: **Visual Studio 14**

### Steps to reproduce (Include if Applicable)
For building as Release:
`conan install ffmpeg/4.0@bincrafters/stable -o freetype=True --build=missing`

For building as Debug:
`conan install ffmpeg/4.0@bincrafters/stable -o freetype=True  --build=missing --profile=debug`

**Comment by SSE4** [comment]
@joshgamer474 I've fixed the FreeType recipe, please give an another try
also, next ffmpeg build will use freetype=True by default (later this week)

**Comment by joshgamer474** [comment]
@SSE4 Thank you! Tried building ffmpeg/4.0 with it enabled and both Release and Debug builds worked flawlessly. 
Will the latest Freetype conan recipes be uploaded to Bincrafter's conan remote? It looks like the fix(es) are only on the github repos currently.

**Comment by joshgamer474** [comment]
@SSE4 my bad, it looks like they aren't updated on 
`conan-center: https://conan.bintray.com [Verify SSL: True]`
I'll move my bincrafters remote up so it's higher priority. Thanks again

**Comment by SSE4** [comment]
closing, confirmed as fixed
