### ISSUE TITLE
[glad] 1.0.24 Does not compile with latest version of conan

### ISSUE THREAD

**Issue by matkam7** [bincrafters/community#426]
### Description of Problem, Request, or Question
After pushing a really simple commit on my package all of my CI tests failed (Windows, Linux and Macos). I updated conan to the latest version locally and got the same error message:

ERROR: C:\Users\...\.conan\data\glad\0.1.24\bincrafters\stable\export\conanfile.py: Error while initializing options. Please define a default value for 'extensions' in'default_options'

Within the [conanfile.py](https://github.com/bincrafters/conan-glad/blob/stable/0.1.24/conanfile.py), the issue lies with:
```
default_options = (
        ...
        "extensions=",
        ...
    )
```
which is not valid syntax anymore (since 1.7.0). I am guessing that the way to fix this would be to remove extensions from default_options.

**Comment by uilianries** [comment]
Thanks for reporting this.

**Comment by uilianries** [comment]
I just checked using Conan 1.7.1, indeed Conan 1.7.x does not work with empty value on default_option.

I used an empty string to fill extensions. Waiting for CI to merge on stable.

**Comment by uilianries** [comment]
merged!

**Comment by uilianries** [comment]
@matkam7 Could you check the new package, please?

**Comment by matkam7** [comment]
It works on my end, thanks!
