### ISSUE TITLE
wxWidgets missing some libraries with gcc on windows

### ISSUE THREAD

**Issue by MB3hel** [bincrafters/community#427]
### Description of Problem, Request, or Question
Some additional libraries are needed when using wxWidgets on windows.

### Package Details (Include if Applicable)
* Package Name/Version: **wxwidgets/3.1.1**
* Operating System: **Windows 10 x64**
* Compiler+version: **gcc-7.1**

I have made a pull request for the wxWidgets repo ([here](https://github.com/bincrafters/conan-wxwidgets/pull/3))

**Comment by MB3hel** [comment]
It would also be a good idea to merge this with the stable/3.1.1 branch.

**Comment by SSE4** [comment]
merged
