### ISSUE TITLE
protobuf: library targets have different names under Windows and Linux

### ISSUE THREAD

**Issue by sigiesec** [bincrafters/community#429]
### Description of Problem, Request, or Question

Library targets have different names under Windows and Linux because of different handling if "lib" prefix.

### Package Details (Include if Applicable)
* Package Name/Version: **protobuf/3.6.1**
* Operating System: **Linux, Windows**

### Steps to reproduce (Include if Applicable)

Using the conan cmake generator, in the CMakeLists.txt of a dependent package, I want to reference the library as
```
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup(TARGET)

add_library(my_library STATIC)
target_link_libraries(my_library PUBLIC CONAN_LIB::Protobuf_protobuf)
```

But this variant only works under Linux, while under Windows, I need to use `CONAN_LIB::Protobuf_libprotobuf` instead.

**Comment by SSE4** [comment]
@sigiesec have you tried to use `CONAN_PKG::protobuf` instead?

**Comment by sigiesec** [comment]
Yes, but CONAN_PKG::protobuf also depends on (lib)protoc, which I don't want. In general, I want to specify depedencies on a specific library, not a whole package.

Actually, we have a modified version of the recipe, which also builds (lib)protobuf_lite, which makes the problem more apparent, since you cannot link to both libraries, since this would yield ambiguous symbols.

**Comment by sigiesec** [comment]
I found a way to circumvent this problem now by using find_package(Protobuf).

**Comment by SSE4** [comment]
this one might be tricky to solve. I guess the following proposed conan feature may help:
https://github.com/conan-io/conan/issues/2387

**Comment by sigiesec** [comment]
Really? Hm, then the problem appears to be more fundamental than I thought, in general. As I wrote, for libprotobuf specifically I found a way to circumvent this, so for my part, we could close this issue.

**Comment by SSE4** [comment]
okay, I am closing this for now, as this requires some new conan feature to implement.
