### ISSUE TITLE
Update to catch 2.4.0

### ISSUE THREAD

**Issue by Quincunx271** [bincrafters/community#430]
Catch2 recently released [v2.4.0](https://github.com/catchorg/Catch2/releases/tag/v2.4.0). The catch2 package should be updated to `catch2/2.4.0@bincrafters/stable`.

Catch2 updated Catch2ConfigVersion.cmake, so the target arch check workaround in https://github.com/bincrafters/conan-catch2/pull/4 should be unneeded. That is, it should work to just copy the files without edits (untested by me, though)

**Comment by uilianries** [comment]
Unfortunately is the same: https://github.com/catchorg/Catch2/blob/v2.4.0/CMakeLists.txt#L136 :disappointed:

**Comment by uilianries** [comment]
Well, something was modified:

```
$ diff /v2.4.0/lib/cmake/Catch2/Catch2ConfigVersion.cmake /v2.3.0/lib/cmake/Catch2/Catch2ConfigVersion.cmake

< set(PACKAGE_VERSION "2.3.0")
---
> set(PACKAGE_VERSION "2.4.0")
18c18
<   if("2.3.0" MATCHES "^([0-9]+)\\.")
---
>   if("2.4.0" MATCHES "^([0-9]+)\\.")
21c21
<     set(CVF_VERSION_MAJOR "2.3.0")
---
>     set(CVF_VERSION_MAJOR "2.4.0")
37c37
< if("${CMAKE_SIZEOF_VOID_P}" STREQUAL "" OR "8" STREQUAL "")
---
> if("${CMAKE_SIZEOF_VOID_P}" STREQUAL "" OR "" STREQUAL "")
42,43c42,43
< if(NOT CMAKE_SIZEOF_VOID_P STREQUAL "8")
<   math(EXPR installedBits "8 * 8")
---
> if(NOT CMAKE_SIZEOF_VOID_P STREQUAL "")
>   math(EXPR installedBits " * 8")
```

**Comment by uilianries** [comment]
Done!

![catch2/2.4.0](https://screenshotscdn.firefoxusercontent.com/images/7905216e-bbc0-4e92-9e21-3b2287d524db.png)

https://github.com/bincrafters/conan-catch2/tree/stable/2.4.0
https://travis-ci.org/bincrafters/conan-catch2/builds/425046500
https://ci.appveyor.com/project/BinCrafters/conan-catch2/build/1.0.45

**Comment by Quincunx271** [comment]
Whose feedback does the feedback label ask for? My feedback is that it seems to be working correctly

**Comment by uilianries** [comment]
Thanks, it's enough for me :smile:
