### ISSUE TITLE
Cannot build lzma with MinGW.

### ISSUE THREAD

**Issue by MB3hel** [bincrafters/community#431]
### Description of Problem, Request, or Question
When trying to use the boost_asio pacakge lzma 5.2.3 inst downloaded and built (as no prebuilt package exists), lzma fails to build with the following output.

```
ERROR: lzma/5.2.3@bincrafters/stable: Error in build() method, line 82
        msys_bin = self.deps_env_info['msys2_installer'].MSYS_BIN
        KeyError: 'msys2_installer'
```

### Package Details (Include if Applicable)
* Package Name/Version: **lzma/5.2.3**
* Operating System: **Windows 10 x64**
* Compiler+version: **gcc-7.1 mingw-w64 posix seh**

### Steps to reproduce (Include if Applicable)
Try to install boost_asio with the following profile
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=7.1
compiler.libcxx=libstdc++
compiler.exception=seh
build_type=Release
```

**Comment by SSE4** [comment]
@MB3hel LZMA requires MSYS2 to be built via MinGW, you may add the following into your profile:
```
msys2_installer/latest@bincrafters/stable
```

**Comment by MB3hel** [comment]
Ok.  Thanks @SSE4. I assumed that lzma would work with the CONAN_BASH_PATH variable like most other packages, but this solves the problem.
