### ISSUE TITLE
Upgrade conan-caf to 0.16.0

### ISSUE THREAD

**Issue by sourcedelica** [bincrafters/community#432]
### Package Details (Include if Applicable)
* Package Name/Version: **caf/0.16.0**

Pull request: https://github.com/bincrafters/conan-caf/pull/18

**Comment by uilianries** [comment]
Waiting for CI result:

https://travis-ci.org/bincrafters/conan-caf/builds/426397605
https://ci.appveyor.com/project/BinCrafters/conan-caf/build/1.0.60

**Comment by uilianries** [comment]
Done!

https://travis-ci.org/bincrafters/conan-caf/builds/426425275
https://ci.appveyor.com/project/BinCrafters/conan-caf/build/1.0.60

**Comment by sourcedelica** [comment]
Thanks!
