### ISSUE TITLE
Protobuf support of gcc-4.8

### ISSUE THREAD

**Issue by bashbug** [bincrafters/community#437]
Running: `conan install protobuf/3.6.1@bincrafters/stable`
Leads to: `ERROR: Unable to find 'protobuf/3.6.1@bincrafters/stable' in remotes`

From here: https://github.com/bincrafters/community/issues/392 and specifically https://camo.githubusercontent.com/4f222ee19e71cac7c464221911a2c66667d48bd7/68747470733a2f2f73637265656e73686f747363646e2e66697265666f7875736572636f6e74656e742e636f6d2f696d616765732f34343731616533642d666331352d343034362d383438622d6336393536343439363065642e706e67

Ubuntu 14.04 users with gcc-4.8 are not supported. Any plan to do so?

### Package Details
* Package Name/Version: **protobuf/3.6.1**
* Operating System: **Linux Ubuntu 14.04**
* Compiler+version: **gcc-4.8**

**Comment by uilianries** [comment]
Hi @bashbug !

we don't provide support for GCC 4.8 by default, but we can add when requested.

we dropped GCC 4.8 some time ago to save our CI time using Travis and also we had no objections.

**Comment by bashbug** [comment]
@uilianries thanks for the fast response.
For now, I have to build from source and have to maintain the package by myself. Would really like not to do so.
I think it would be really helpful, if gcc-4.8 gets supported. Others might need it too.

**Comment by uilianries** [comment]
Hi @bashbug !

Now it is possible to download protobuf with GCC 4.8 support

![protobuf/3.6.1@bincrafters/stable](https://screenshotscdn.firefoxusercontent.com/images/658e0e2e-9e3a-41e8-9e7f-65d2dc865a72.png)

There is support for 64 bits only, but feel free to ask if you need to use 32 bits also.

**Comment by bashbug** [comment]
Hi @uilianries 
Thanks for that fast integration!
I tried to pull it from bincrafters but it seems not to be availabe. From your latest commit https://github.com/bincrafters/conan-protobuf/commit/5d7e882ddd7f237ef0332bc8aa8518ce626f9dd2 it looks like you reverted the commit supporting gcc 4.8. ?

**Comment by SSE4** [comment]
@bashbug it was re-added after revert https://github.com/bincrafters/conan-protobuf/commit/b03bfcf021d37f9f9c562044ffe26ad3b0e65cb9
please give an another try

**Comment by SSE4** [comment]
GCC 4.8 packages were added, closing

**Comment by bashbug** [comment]
@uilianries @SSE4 I'm very sorry for the late response. Thanks for adding gcc 4.8 support. Works!

While using the package I saw that https://bintray.com/bincrafters/public-conan/protoc_installer%3Abincrafters/3.6.1%3Astable gets also installed. Which means the protoc binary is available. Really useful would be to have `protobuf_generate_cpp` available, which is normally part of a protobuf installation https://github.com/protocolbuffers/protobuf/blob/master/cmake/protobuf-module.cmake.in

**Comment by SSE4** [comment]
@bashbug I am not sure I got the point, do you have more information on what is `protobuf_generate_cpp`, is it executable, library, header or what? we invoke `install` of protobuf, so it should have everything installed

**Comment by bashbug** [comment]
Sorry, I didn't want to re-open that issue! Was just a suggestion which came to my mind.

If you install protobuf https://github.com/protocolbuffers/protobuf/tree/master/cmake
When calling `find_package(protobuf)` in within a `CMakeLists.txt`
The `protobuf-config.cmake` is called and https://github.com/protocolbuffers/protobuf/blob/master/cmake/protobuf-config.cmake.in#L125 includes `protobuf-module.cmake` which provides the function `protobuf_generate_cpp` https://github.com/protocolbuffers/protobuf/blob/master/cmake/protobuf-module.cmake.in#L4

This function can then be used within your `CMakeLists.txt` to invoke the protoc executable to generate from `*.proto` file its `*.pb.cc` and `*.pb.h` files. This allows you to generate those files during build time with cmake.

**Comment by SSE4** [comment]
I think it's already available and used, e.g. take a look at our test_package implementation:
https://github.com/bincrafters/conan-protobuf/blob/stable/3.6.1/test_package/CMakeLists.txt#L29

**Comment by bashbug** [comment]
I tried it `protobuf_MODULE_COMPATIBLE` is always false. Even without checking that, the function `protobuf_generate_cpp` is not defined.

I guess, the test you referring to is just skipped and the variables `${TEST_SRCS} ${TEST_PROTOS}` are empty. I can not see from the test, that it actually tests if the `protobuf_MODULE_COMPATIBLE` is true and the files are really generated.

**Comment by bashbug** [comment]
@SSE4 You my man! Thanks a lot for digging it out! The new function is called `protobuf_generate` as it is now part of the protobuf-config.cmake https://github.com/protocolbuffers/protobuf/blob/c7352b39f85e910c017a8b872a08be3bfb1f117f/cmake/protobuf-config.cmake.in#L10
I'm not really a cmake pro. It's interesting that `find_package(protobuf)` is not appending invoking the `protobuf-config.cmake` I have to explicitly call `find_package(protobuf CONFIG)`. But now it works. Thanks for you help!

**Comment by bashbug** [comment]
So sad, the new function `protobuf_generate` has a bug which is fixed here https://github.com/protocolbuffers/protobuf/commit/1509e8e3b3d10a2a903f60d6281e30e51b8ecba5

**Comment by Croydon** [comment]
Is this done? If not what is left to do?

**Comment by bashbug** [comment]
From my side it is done.
