### ISSUE TITLE
gsl_microsoft (GSL) upstream has released version 2.0.0

### ISSUE THREAD

**Issue by xenstalker** [bincrafters/community#439]
### Description of Problem, Request, or Question
Need to update GSL version to 2.0.0.

### Package Details (Include if Applicable)
* Package Name: **gsl_microsoft**
* GSL upstream: [GSL v2.0.0](https://github.com/Microsoft/GSL/releases/tag/v2.0.0)

**Comment by SSE4** [comment]
@xenstalker thanks! updated version is available on bintray now
