### ISSUE TITLE
libjpeg pull request to fix cross compiling with mingw

### ISSUE THREAD

**Issue by MB3hel** [bincrafters/community#441]
### Description of Problem, Request, or Question
I have opened a pull request for libjpeg to fix cross compiling. See the issue [here](https://github.com/bincrafters/conan-libjpeg/pull/2)

### Package Details (Include if Applicable)
* Package Name/Version: **libjpeg/9c**

**Comment by SSE4** [comment]
this was merged, thanks for the contribution!
