### ISSUE TITLE
Bump msgpack to version 3.1.1

### ISSUE THREAD

**Issue by drrlvn** [bincrafters/community#442]
### Description of Problem, Request, or Question
Please bump msgpack to latest version 3.1.1 released September 9th.

https://github.com/msgpack/msgpack-c/releases/tag/cpp-3.1.1

### Package Details (Include if Applicable)
* Package Name/Version: **msgpack/3.1.1**

**Comment by SSE4** [comment]
@drrlvn thanks! updated version is available on bintray now

**Comment by SSE4** [comment]
closing as version is available
