### ISSUE TITLE
libiconv fails to build on linux-ppc64le

### ISSUE THREAD

**Issue by Croydon** [bincrafters/community#443]
`--build=ppc64le` doesn't seem to get passed along, instead it uses `--build=x86_64-linux-gnu`

https://travis-ci.org/Croydon/doxygen/jobs/429336064#L830

**Comment by SSE4** [comment]
weird it is looking for the **libiconv.so** while `--disable-shared` is passed

**Comment by SSE4** [comment]
this is fixed in conan and will be available in 1.8 release

**Comment by Croydon** [comment]
Thanks for your work upstream!

I will leave this open until Conan 1.8 is released and re-test it then.

**Comment by SSE4** [comment]
@Croydon conan 1.8.0 is out, please give a try

**Comment by Croydon** [comment]
As soon as Travis displays me again the logs for the linux-ppc64le images I can tell...

**Comment by Croydon** [comment]
I'm not seeing any `--build` parameter at all anymore https://travis-ci.org/Croydon/doxygen/jobs/439221148#L709

The build itself seems successful, but I'm getting an error when consuming libiconv with doxygen https://travis-ci.org/Croydon/doxygen/jobs/439221148#L2852

Not sure how related this is or what the source of the error is

**Comment by SSE4** [comment]
something inside `cmake/FindIconv.cmake` failed, need to look what does it check

**Comment by Croydon** [comment]
Yeah, the weird thing is: The doxygen CI uses https://packages.ubuntu.com/xenial/cmake
which means CMake 3.5, which was released March 2016 (https://github.com/Kitware/CMake/releases/tag/v3.5.0), but the FindIconv.cmake file was added Nov 2017 (https://github.com/Kitware/CMake/commits/master/Modules/FindIconv.cmake)

And I can't find in there the error output from CI

**Comment by SSE4** [comment]
@Croydon do we have any update/progress on this one?

**Comment by Croydon** [comment]
Oops, sorry, I somehow missed your last question.

Unfortunately, no progress so far :/

**Comment by Croydon** [comment]
Actually, using a newer CMake version solves the problem 🎉 

I'm using cmake_installer to install a newer version in CI. However, since this is about linux-ppc64le it first needs to build cmake, which increases build time even more... I don't think it is a good idea to provide prebuilds for ppc64le in general, but maybe we can make some exception for some popular build_requires 🤔

**Comment by Croydon** [comment]
I'm guessing I just came full circle on this issue and will continue to use Ubuntu system packages to let Doxygen build for linux-ppc64le, as I don't think that the maintainers would find it funny when normal Linux jobs run around 6 minutes but linux-ppc64le ones take ~30 minutes and as soon as all dependencies are available with Conan even longer....

I still think it was good work to fix support within Conan and enable this. And maybe even Doxygen makes use of it in the future, just not in every single CI run without available prebuilds.
