### ISSUE TITLE
glfw/3.2.1 cannot be found?

### ISSUE THREAD

**Issue by sssilver** [bincrafters/community#445]
### Description of Problem, Request, or Question
Trying to pull **glfw** as a dependency for my project. All other dependencies resolve/download correctly. GLFW errors out:
```
-- Conan executing:
CMake Error at cmake/conan.cmake:17 (message):
  Conan install failed for Debug (1).  glfw/3.2.1@bincrafters/stable: Not
  found in local cache, looking in remotes...

  glfw/3.2.1@bincrafters/stable: Trying with 'conan-center'...

  ERROR: Failed requirement 'glfw/3.2.1@bincrafters/stable' from 'PROJECT'

  ERROR: Unable to find 'glfw/3.2.1@bincrafters/stable' in remotes
```

Which seems strange, since the package [seems to be there](https://bintray.com/bincrafters/public-conan/glfw%3Abincrafters/3.2.1%3Astable).

My conanfile.txt:
```
λ cat conanfile.txt
[requires]
gtest/1.8.0@bincrafters/stable
spdlog/1.1.0@bincrafters/stable
glfw/3.2.1@bincrafters/stable

[generators]
cmake
```

My Conan remotes:
```
λ conan remote list
conan-center: https://conan.bintray.com [Verify SSL: True]
```

### Package Details (Include if Applicable)
* Package Name/Version: **glfw/3.2.1@bincrafters/stable**
* Operating System: **Windows 10**
* Compiler+version: **VS2017**

### Steps to reproduce (Include if Applicable)

- Add `glfw/3.2.1@bincrafters/stable` to conanfile.txt `[requires]` section
- Run `$ conan install ${CMAKE_CURRENT_SOURCE_DIR} ${profile_flag} -s build_type=Debug -g cmake_multi`
- Observe the error pasted in the description

**Comment by Croydon** [comment]
glfw is not in [conan-center](https://bintray.com/conan/conan-center) but for now only in the bincrafters repository

So you need to add the bincrafters repository if you want to use the glfw package right now 

> conan remote add <REMOTE> https://api.bintray.com/conan/bincrafters/public-conan
