### ISSUE TITLE
Google benchmark upstream support

### ISSUE THREAD

**Issue by Mikayex** [bincrafters/community#449]
### Description of Problem, Request, or Question
Hi !
I've created a package for [Google benchmark](https://github.com/google/benchmark) using your packaging standards : https://github.com/Mikayex/conan-benchmark. It is ready to be copied to bincrafters organization (you just need to make the stable branch once you've tested on your side).

Please note I had to explicitly disable `shared=True` configuration on Windows CI as it is not supported by the library (no dllexports).

You can find CI here :
- https://ci.appveyor.com/project/Mikayex/conan-benchmark
- https://travis-ci.org/Mikayex/conan-benchmark

### Package Details
* Package Name/Version: **benchmark/1.4.1**
* Operating System: **all**
* Compiler+version: 
**GCC 4.8+**
**Clang 3.4+**
**MSVC 2013+**

**Comment by Croydon** [comment]
If you allow me to answer here @mpusz to keep this together..

(from https://github.com/Croydon/conan-google_benchmark/issues/1)

```Hi,

I just found your repo. It turned out that I am working on the same subject for a long time now. You can find it here:
https://github.com/mpusz/conan-google-benchmark

I think you could reconsider having the following options:
"enable_testing=False","enable_gtest_tests=False"
They do not have a sense from user/client point of view. They might have a sense from the packaging point of view. I think that you could handle them similar to what I am doing in my repo.
https://github.com/mpusz/conan-google-benchmark

I will be talking about that today at CppCon.

Maybe you will find some other things there interesting too ;-)

Best

Mat
```

My repository https://github.com/Croydon/conan-google_benchmark is now obsolete. I did work there on packaging benchmark as a third-party package, but I eventually switched to upstream support as can be seen in the pull request https://github.com/google/benchmark/pull/647 and here https://github.com/Croydon/benchmark

I agree that these options don't make any sense when it is a third-party package, but this might be useful since this will be upstream supported?

**Comment by mpusz** [comment]
Hi,

Every change in "setting" or an "option" produces a different binary. What
will be the observable difference for a user in a packaged binary for
"enable_testing=False"
and "enable_testing=True"? Why the user have to be forced to build and
store 2 versions of a library in the local cache for both those values?

In my believe "option" or "setting" should be introduced only if it makes
the binary different and observable by the user. For configuring of the
mode of your Continuous Integration builds it is better to use environment
variables as you can find in my repo. You can also find more info on that
subject in my slides here:
https://github.com/train-it-eu/conf-slides/blob/master/2018.09%20-%20CppCon/Git%2C%20CMake%2C%20Conan%20-%20How%20to%20ship%20and%20reuse%20our%20C%2B%2B%20projects.pdf

Please let me know if you have any questions or comments.

Best

Mat

pt., 28 wrz 2018 o 10:32 użytkownik Croydon <notifications@github.com>
napisał:

**Comment by Croydon** [comment]
> Why the user have to be forced to build and store 2 versions of a library in the local cache for both those values?

Users are never forced to install and store more versions than they are actually using?

If a different package_id is your concern, then I can simply overwrite it so that these development options don't make a difference. I do think that it has benefits that if you work directly at a library (again: upstream in-source Conan support) that you only need to handle settings and options and you aren't forced to use environment variables as a third way to define things.

**Comment by mpusz** [comment]
Hi,

Sorry but I tend to disagree with you ;-)

I consider settings and options a public interface of your library. Would
you expose some private debug stuff in an interface of a public function of
your C++ interface or would you rather use some preprocessor defines? I
think that is the same case here.

Talking about the complexity of setting an environment variable I think it
is actually easier than handling user option which is often package
specific.

There is a special predefined environment variable for that specific case
CONAN_RUN_TESTS. You can set it either:
- in the OS so it is global for whole machine (i.e. CI environment),
- in a Conan profile that you use for builds that should run unit tests
- or directly with - e option of conan install command.

It really does not matter if the Conan recipe packages external or internal
sources.

Best

Mat




sob., 29 wrz 2018, 08:32 użytkownik Croydon <notifications@github.com>
napisał:

**Comment by Croydon** [comment]
> There is a special predefined environment variable for that specific case CONAN_RUN_TESTS.

Thanks. I wasn't aware that there is an official environment variable like this.

> It really does not matter if the Conan recipe packages external or internal sources.

I disagree. If you are a third-party packager then you don't really care about internals, but you can also use Conan when you are the maintainer of the library itself, right? And then you do care about internals, debugging stuff and tests.

I haven't exposed any new internals by the way, I have mapped the CMake options to Conan options.

I have changed the recipe to use the CONAN_RUN_TESTS environment variable; I have removed the enable_testing option; the option enable_gtest_tests does NOT change the package_id anymore and is only available when CONAN_RUN_TESTS  is True.

https://github.com/Croydon/benchmark/commit/796c8865f2ef2c70bb42809ae6fd407c5f071948

Does this look better now to you?

**Comment by Croydon** [comment]
Well, **actually**, actually there are at least 5 people who have worked separately on a benchmark recipe 🙄 🙄  

https://github.com/iblis-ms/conan_gbenchmark

**Comment by Croydon** [comment]
## Progress: Benchmark has now official Conan suppport https://github.com/google/benchmark/pull/728

Next step: CI support + Conan Center https://github.com/google/benchmark/pull/647

**Comment by SSE4** [comment]
@Croydon I think now we don't need this, please open PR into  https://github.com/conan-io/conan-center-index

**Comment by Croydon** [comment]
Yes, exactly. I just haven't had time to catch up with all issues, pull requests etc. regarding the new situation
