### ISSUE TITLE
bincrafters-package-tools: shared configuration false positive

### ISSUE THREAD

**Issue by Mikayex** [bincrafters/community#450]
### Description of Problem
For a library I'm packaging (https://github.com/Mikayex/conan-benchmark), the `shared=True` configuration is not supported on Windows (no dllexports). However the default `build.py` tries to generate `shared=True` configurations, thus CI builds fails.

Here is an excerpt of my conanfile.py:
```py
options = {
        "shared": [True, False],
        "fPIC": [True, False],
        "exceptions": [True, False],
        "lto": [True, False],
}

def config_options(self):
    if self.settings.os == 'Windows':
        del self.options.fPIC
        del self.options.shared
```

This works correctly on Conan and it should be the correct way to conditionally disable an option (it throws an error when you try to set the option).

I saw that the shared option detection is done with regexp (see [build_shared.py#L27](https://github.com/bincrafters/bincrafters-package-tools/blob/79fc0b3c98728906da22033d9b048de7076138ef/bincrafters/build_shared.py#L27)), so it may be the root cause (but I don't know how to solve it).

As a workaround my `build.py` is like so:
```py
from bincrafters import build_template_default
import platform

if __name__ == "__main__":
    # The shared option is not supported on Windows so it is explicitly disabled
    builder = build_template_default.get_builder(shared_option_name=('' if platform.system() == 'Windows' else None))

    builder.run()
```

**Comment by uilianries** [comment]
Thanks for reporting this!

**Comment by uilianries** [comment]
The problem is that we dont have how to inspect your recipe to define such rule. Did you try `False` instead of ` ` ?

**Comment by Croydon** [comment]
The issue here is rather that the option is only not available on some platform. I don't think we can completely automate this. The situation got however way better with new Conan and package tools releases.

IIRC when ConanInvalidConfiguration exceptions are used the packages tools will just continue with the rest of the builds without letting the CI fail, correct @uilianries?

**Comment by solvingj** [comment]
The `build.py` conditional for the `shared_option_name` is a very appropriate way to handle this situation (explicitly). Even if we could make it implicitly handle this situation without the conditional, I don't think it would be a good thing.
