### ISSUE TITLE
need help: Testing Qt package - how to config qtmodules

### ISSUE THREAD

**Issue by nesc1** [bincrafters/community#451]
Hi all,

I'm currently testing the Qt conan package and it seems to me that I don't know or I don't understand how to change the configuration of a qtmodule...

In specific I'm trying to enable handwrite and t9write for qtvirtualkeyboard module... how can be this be done?

Sory if this is not the correct place to put this kind of questions.. if not please point me to the right place please.

Regards,
Nuno

Package details:
Name: Qt/5.11.1@bincrafters/stable
Operating system: windows
Compiler: VS2017

**Comment by ericLemanissier** [comment]
Hi, You should be able to build qtvirtualkeyboard module by setting option Qt:qtvirtualkeyboard=true
Unfortunately I think it won't enable handwriting. This would require that we add an option to the recipe and that we handle virtualkeyboard module in a special way. I'll try to look at it in the coming days.

**Comment by nesc1** [comment]
Thank you ericLemanissier, so if i want to enable it manually, should i change the configuration file manually? (manually = using the conanfile.py with patch or any other method)

Can you point me on how can i achieve this?

**Comment by ericLemanissier** [comment]
You would need to fork bincrafters/conan-qt and modify the conanfile.py: 
1. add a t9write option
2. always pass the argument `-skip qtvirtualkeyboard` to configure
3. if the t9write option is enabled, then implement at the end of the `_build` method what is described [here](https://doc.qt.io/qt-5.11/qtvirtualkeyboard-build.html#t9-write-integration), then call `qmake CONFIG+=t9write && make && make install`

If you have a working solution, I would be very happy to merge a pull request !

**Comment by nesc1** [comment]
Hi ericLemanissier, no i'm still trying to understand how the qmake CONFIG+=... works, because what i see on the conanfile.py is that the configure is called with the options selected (inclusive the generic option 'config') then the make and then the make install.

So the question here is where are the call of the qmake? in configure? or is the qmake called on 'self.run(make)'?

Question: why do you add '-skip qtvirtualkeyboard' ? what is this for?

Thanks

**Comment by ericLemanissier** [comment]
for all "non skipped" modules, qmake is called during https://github.com/bincrafters/conan-qt/blob/stable/5.11.1/conanfile.py#L275
This is why you would need to -skip qtvirtualkeyboard, so that you can call 
```
$ cd src/virtualkeyboard/3rdparty/t9write/
$ python unpack.py T9Write_Alpha_v7-8-0_SDK.zip .
```
and then call qmake from the qtvirtualkeyboard folder with the argument `CONFIG+=t9write`, and finish

**Comment by ericLemanissier** [comment]
After rethinking about it, you should actually do the `python unpack.py` part from the `source` method (unconditionaly). I think you have to download the T9Write archive beforehand.

Then the `_build` method would be 
```
                self.run("%s/qt5/configure %s" %
                         (self.source_folder, " ".join(args)))
                self.run(make)
                self.run("%s install" % make)
                if self.options.t9write:
                    with tools.chdir("qtvirtualkeyboard"):
                        self.run("qmake %s/qtvirtualkeyboard/qtvirtualkeyboard.pro CONFIG+=t9write" % self.source_folder)
                        self.run(make)
                        self.run("%s install" % make)
```

**Comment by nesc1** [comment]
yep agree, and thanks for the code update ericLemanissier
