### ISSUE TITLE
Using Qt with Conan via Cmake

### ISSUE THREAD

**Issue by ZodiacFRA** [bincrafters/community#456]
### Description of Problem, Request, or Question

**I can't get Qt to work with a simple test main:**

#include < QApplication >
#include < QWidget >

int main(int argc, char **argv)
{
	std::cout << client OK << std::endl;
	QApplication app (argc, argv);
	QWidget window;
	window.resize(250, 150);
	window.setWindowTitle(Simple example);
	window.show();
	return app.exec();
}

**and the following CMakeLists.txt :**

include_directories(${babel_SOURCE_DIR}/client/inc)
include_directories(${babel_SOURCE_DIR}/common)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR})
set(CMAKE_INCLUDE_CURRENT_DIR ON)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTOUIC ON)
find_package(Qt5Widgets CONFIG REQUIRED)
set(CMAKE_CXX_FLAGS "-Wall -fPIC -std=c++11")
add_executable(babel_client main.cpp)
target_link_libraries(babel_client ${CONAN_LIBS})

**called by this "master" CmakeLists.txt:**

cmake_minimum_required (VERSION 3.11.2)
project(babel)
include(${CMAKE_SOURCE_DIR}/build/conanbuildinfo.cmake)
conan_basic_setup()
subdirs(server client)

**because the following error is thrown at execution of the binary:**

qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Aborted (core dumped)

**Any ideas?**

### Package Details
* Package Name/Version: **Qt/5.11**
* Operating System: **Linux Fedora 28**
* Compiler+version: **gcc-8.1.1**

**Comment by ericLemanissier** [comment]
Could you please try to create a file named qt.conf in the directory containing the application executable. Write in the file:
```
[Paths]
Prefix = /path/to/the/qt/package/binaries
```
The prefix must have plugins/platforms sub-directory. If it solves your problem I will have to find a way to integrate this in the recipe somehow.
Another solution is to rebuild the qt package, I guess you are using downloaded binaries right ?

**Comment by ZodiacFRA** [comment]
Hello,


I've tried with the qt.conf file (I've put it in my root dir, next to my executable), and it's working now, thanks :)


the file looks like this:


[Paths]

Prefix = /home/jdupuy/.conan/data/Qt/5.11/bincrafters/stable/package/e8fa0f46f269de0e47e5811369aa4a092c818e15


However, as you can see the path is highly specific to my system, and won't work on any other computer, how could we avoid that?


Have a nice day

________________________________
De : ericLemanissier <notifications@github.com>
Envoyé : lundi 24 septembre 2018 08:40:50
À : bincrafters/community
Cc : Jean-baptiste Dupuy; Author
Objet : Re: [bincrafters/community] Using Qt with Conan via Cmake (#456)


Could you please try to create a file named qt.conf in the directory containing the application executable. Write in the file:

[Paths]
Prefix = /path/to/the/qt/package/binaries


The prefix must have plugins/platforms sub-directory. If it solves your problem I will have to find a way to integrate this in the recipe somehow.
Another solution is to rebuild the qt package, I guess you are using downloaded binaries right ?

**Comment by ericLemanissier** [comment]
If you are using a conanfile.py to build your application, then you can add the following in the `build()` method
```python
with open('path/to/executable/qt.conf', 'w') as f:
    f.write('[Paths]\nPrefix = %s' % self.deps_cpp_info["Qt"].rootpath)
```
If you are using conanfile.txt, then I think the only solution is the following:
1. I modify the Qt recipe so that calling `conan install` creates the qt.conf file with the actual path where qt package is stored
2. You, as all consumer, have to move this qt.conf file next to the executable from your build script

**Comment by ericLemanissier** [comment]
I just uploaded a new version of the 5.11.2 recipe. You can now add the "qt" generator to your conanfile, and it will create the `qt.conf` file for you. You just have to copy/move it in the directory containing the application executable. Can you tell me if it works for you ?

**Comment by ZodiacFRA** [comment]
Hello, the installation of Qt 5.11.2 works, however conan does not seem to be able to link to Qt anymore.
I get 
`CMake Error at client/src/CMakeLists.txt:7 (find_package):`
`By not providing "FindCONAN_PKG::Qt.cmake" in CMAKE_MODULE_PATH this
project has asked CMake to find a package configuration file provided by "CONAN_PKG::Qt", but CMake did not find one.`

 `Could not find a package configuration file provided by "CONAN_PKG::Qt" with any of the following names:`

`CONAN_PKG::QtConfig.cmake`
`conan_pkg::qt-config.cmake`

  `Add the installation prefix of "CONAN_PKG::Qt" to CMAKE_PREFIX_PATH or set "CONAN_PKG::Qt_DIR" to a directory containing one of the above files.`
`If "CONAN_PKG::Qt" provides a separate development package or SDK, be sure it
  has been installed.`

I added 'qt' to the generators in the conanfile, but it does not create any qt.conf file

my CMakeLists.txt now are:
(master)
`cmake_minimum_required (VERSION 3.11.2)`
`project(babel)`
`include(${CMAKE_SOURCE_DIR}/build/conanbuildinfo.cmake)`
`conan_basic_setup(TARGET)`
`subdirs(client)`

(called):
`SET(CMAKE_AUTOUIC ON)`
`set(AUTOGEN_BUILD_DIR ${CMAKE_SOURCE_DIR/client/inc})`
`set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR})`

`find_package(CONAN_PKG::Qt REQUIRED)`

`set(babel_client_SRCS
main.cpp
GUIWindow.cpp
GUICustomClasses.cpp
)`

`add_executable(babel_client ${babel_client_SRCS})`

`target_include_directories(babel_client PUBLIC ${babel_SOURCE_DIR}/common
PRIVATE ${babel_SOURCE_DIR}/client/inc)`

`target_link_libraries(babel_client CONAN_PKG::Qt)`

Any Ideas? thanks

**Comment by ZodiacFRA** [comment]
**Hello, Installation of 5.11.2 is working great, but I can't link it properly, I get the following error:**
`CMake Error at client/src/CMakeLists.txt:10 (find_package):`
`By not providing "FindCONAN_PKG::Qt.cmake" in CMAKE_MODULE_PATH this project has asked CMake to find a package configuration file provided by "CONAN_PKG::Qt", but CMake did not find one.`

`Could not find a package configuration file provided by "CONAN_PKG::Qt" with any of the following names:`

`    CONAN_PKG::QtConfig.cmake`
`    conan_pkg::qt-config.cmake`

`Add the installation prefix of "CONAN_PKG::Qt" to CMAKE_PREFIX_PATH or set "CONAN_PKG::Qt_DIR" to a directory containing one of the above files.`
`If "CONAN_PKG::Qt" provides a separate development package or SDK, be sure it has been installed.`

**I've added the qt option to the conan generators, and the qt.conf generated file is placed in the root directory, here are my CMakeList.txt:
(master)**
`cmake_minimum_required (VERSION 3.11.2)`
`project(babel)`
`include(${CMAKE_SOURCE_DIR}/build/conanbuildinfo.cmake)`
`conan_basic_setup(TARGETS)`
`file(COPY ${CMAKE_BINARY_DIR}/qt.conf DESTINATION ${CMAKE_SOURCE_DIR})`
`subdirs(client)`

**(called)**
`SET(CMAKE_AUTOUIC ON)`
`set(AUTOGEN_BUILD_DIR ${CMAKE_SOURCE_DIR/client/inc})`

`set(babel_client_SRCS
main.cpp
GUIWindow.cpp
GUICustomClasses.cpp
)`

`find_package(CONAN_PKG::Qt REQUIRED)`

`set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR})`
`add_executable(babel_client ${babel_client_SRCS})`

`target_include_directories(babel_client PUBLIC ${babel_SOURCE_DIR}/common`
`PUBLIC ${babel_SOURCE_DIR}/client/inc)`

`target_link_libraries(babel_client CONAN_PKG::Qt)`

Any Ideas? Have a nice day

**Comment by ericLemanissier** [comment]
For your CMakeLists, you have to use what is described on [Qt doc](http://doc.qt.io/qt-5/cmake-manual.html):
> find_package(Qt5Core CONFIG REQUIRED)
> target_link_libraries(${PROJECT_NAME} Qt5::Core)

as seen on the [test package](https://github.com/bincrafters/conan-qt/blob/stable/5.11.2/test_package/CMakeLists.txt)

**Comment by ZodiacFRA** [comment]
ah okay sorry, I've changed my CMakeList.txt and it's working now.
Many thanks for your work and quick responses
