### ISSUE TITLE
libiconv library name is wrong if mingw

### ISSUE THREAD

**Issue by sourcedelica** [bincrafters/community#457]
### Package Details (Include if Applicable)
* Package Name/Version: **libiconv/1.15**
* Operating System: **Windows**
* Compiler+version: **Mingw gcc**

### Steps to reproduce (Include if Applicable)
Cannot find file error when linking against the shared version of the Mingw library

**Comment by SSE4** [comment]
do you have full log?

**Comment by SSE4** [comment]
never mind, I think we can close this one, right?
