### ISSUE TITLE
Create envy python package

### ISSUE THREAD

**Issue by uilianries** [bincrafters/community#458]
### Description of Problem, Request, or Question

@SSE4 Provided the [envy](https://github.com/bincrafters/envy) project to help us updating environment variables for travis and appveyor.

We could include this project as a python package on pypi.org. However we need to rename it as "bincrafters-envy" because envy already exists.

WDYT @SSE4 @solvingj ?

**Comment by SSE4** [comment]
I have no objections, let's do it

**Comment by SSE4** [comment]
I'd consider this as done, closing
