### ISSUE TITLE
Use Qt with Conan on Fedora 28 (x84)

### ISSUE THREAD

**Issue by Sadikum** [bincrafters/community#459]
### Description of Problem, Request, or Question

When trying to use Qt on Fedora28 (x64 architecture) I get an error in the "install" phase.

I would say that this happen because Fedora use `.x86_64` after the packages name to specify the required architecture and not `:amd64`

### Package Details

* Package Name/Version: **Qt/5.11.2@bincrafters/stable**
* Operating System: **Linux Fedora 28 (x64)**
* Compiler+version: **gcc-8.1.1**

### Steps to reproduce

On a Fedora 28 (x64), try to install Qt as a dependency using Conan.

`mkdir build && cd build && conan install ..`

```
Downloading conaninfo.txt

PROJECT: Installing /usr/local/bugs/conanfile.txt
Requirements
    Qt/5.11.2@bincrafters/stable from 'bincrafters' - Cache
Packages
    Qt/5.11.2@bincrafters/stable:0f4662410f0a9bdf85201fd748f5a42c05d1f5a4 - Download

Qt/5.11.2@bincrafters/stable: Retrieving package 0f4662410f0a9bdf85201fd748f5a42c05d1f5a4 from remote 'bincrafters' 
Downloading conanmanifest.txt
[==================================================] 236.0KB/236.0KB  
Downloading conaninfo.txt
[==================================================] 2.4KB/2.4KB      
Downloading conan_package.tgz
[==================================================] 29.8MB/29.8MB    
Qt/5.11.2@bincrafters/stable: Package installed 0f4662410f0a9bdf85201fd748f5a42c05d1f5a4
package libxcb:amd64 is not installed
package mesa-libGL-devel:amd64 is not installed
Running: sudo yum update
Last metadata expiration check: 0:14:03 ago on Mon 24 Sep 2018 12:54:44 PM UTC.
Dependencies resolved.
Nothing to do.
Complete!
Running: sudo yum install -y libxcb:amd64 mesa-libGL-devel:amd64
Last metadata expiration check: 0:14:06 ago on Mon 24 Sep 2018 12:54:44 PM UTC.
No match for argument: libxcb:amd64
No match for argument: mesa-libGL-devel:amd64
Error: Unable to find a match
Qt/5.11.2@bincrafters/stable: ERROR: while executing system_requirements(): Command 'sudo yum install -y libxcb:amd64 mesa-libGL-devel:amd64' failed
ERROR: Error in system requirements
```

It seems that this happened following the fix used for this issue: https://github.com/bincrafters/community/issues/452

**Comment by ZodiacFRA** [comment]
Hello, I've used Qt 5.11 to avoid this problem.

However 5.11.1 and 5.11.2 are still giving this issue:
`No match for argument: libxcb:amd64
No match for argument: mesa-libGL-devel:amd64
Error: Unable to find a match
Qt/5.11.2@bincrafters/stable: ERROR: while executing system_requirements(): Command 'sudo yum install -y libxcb:amd64 mesa-libGL-devel:amd64' failed
ERROR: Error in system requirements`

I'm on fedora 28 as well and I've tried 2 minutes ago to take your commit into account.

**Comment by ericLemanissier** [comment]
Would one of you have the possibility to try with this recipe https://github.com/bincrafters/conan-qt/tree/testing/5.11.2 ?

**Comment by Elassyo** [comment]
This seems to have fixed the problem on Arch Linux

**Comment by Sadikum** [comment]
Using "conan create" on it doesn't work for me on Fedora but this seems to be an unlinked issue.

```
Preparing build tree...
Creating qmake...
Done.
Could not find qmake spec ''.
Error processing project file: /root/.conan/data/Qt/5.11.2/demo/testing/source/qt5
Qt/5.11.2@demo/testing: 
Qt/5.11.2@demo/testing: ERROR: Package '0f4662410f0a9bdf85201fd748f5a42c05d1f5a4' build failed
```
I may be doing something wrong.

**Comment by ericLemanissier** [comment]
what are the values of settings.compiler and settings.arch ?
