### ISSUE TITLE
CMAKE_AUTOUIC not generating ui header files // CMake & QT5 & Conan

### ISSUE THREAD

**Issue by ZodiacFRA** [bincrafters/community#460]
### Description of Problem, Request, or Question
I'm using the Qt given by conan and it looks like the Qt uic is not working properly

the Qt's UIC can transform any plop.ui file generated by Qtcreator to a ui_plop.h header.

This should be achieved automatically by adding the `set(CMAKE_AUTOUIC ON)` command in my CMakeLists.txt so the Qt's UIC automatically converts any ui_*.h included in the source code to an understandable header for the compiler.

however adding the `set(CMAKE_AUTOUIC ON)` does not change anything
### Package Details (Include if Applicable)
* Package Name/Version: **Qt/5.11**
* Operating System: **Linux Fedora 28**
* Compiler+version: **gcc-8.1.1**

### Config
Here is my first CMakeLists.txt (at the root of the project, which calls the second one):
`    cmake_minimum_required (VERSION 3.11.2)`
`    project(babel)`
`    include(${CMAKE_SOURCE_DIR}/build/conanbuildinfo.cmake)`
`    conan_basic_setup()`
`    subdirs(client)`

and the second one is:

`    include_directories(${babel_SOURCE_DIR}/client/inc)`
`    include_directories(${babel_SOURCE_DIR}/common)`
`    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR})`
`    set(babel_client_SRCS`
`    main.cpp`
`    mainwindow.cpp`
`    )`
`    set(CMAKE_CXX_FLAGS "-Wall -fPIC -std=c++11")`
`    set(CMAKE_AUTOUIC ON)`
`    set(AUTOGEN_BUILD_DIR ${CMAKE_SOURCE_DIR/client/inc})`
`    add_executable(babel_client ${babel_client_SRCS})`
`    target_link_libraries(babel_client ${CONAN_LIBS})`

my main.cpp got #include "ui_mainwindow.h" and here is the error output:

`[ 33%] Building CXX object client/src/CMakeFiles/babel_client.dir/main.cpp.o
/plopPath/client/src/main.cpp:1:10: fatal error: ui_mainwindow.h: No such file or directory`
` #include "ui_mainwindow.h"`
`      ^~~~~~~~~~~~~~~~~`
`compilation terminated.`
`gmake[2]: *** [client/src/CMakeFiles/babel_client.dir/build.make:63: client/src/CMakeFiles/babel_client.dir/main.cpp.o] Error 1`
`gmake[1]: *** [CMakeFiles/Makefile2:104: client/src/CMakeFiles/babel_client.dir/all] Error 2`
`gmake: *** [Makefile:84: all] Error 2`

Any Ideas? I've tried putting the set(CMAKE_AUTOUIC ON) at different places in my CMaleLists.txt but it looks like nothing changes (there is NO ui_mainwindow.h created in the project folders)

PS: I'm using the multiplatform binary manager CONAN to get Qt (using Qt without .ui files is working perfectly fine however)

Thanks a lot! have a nice day

**Comment by ericLemanissier** [comment]
Could you please try with 5.11.2 version ?

**Comment by ericLemanissier** [comment]
You should add the .ui files to the `babel_client_SRCS` variable
