### ISSUE TITLE
CUnit adoption

### ISSUE THREAD

**Issue by k0ekk0ek** [bincrafters/community#461]
### Description of Request
I've created a package for CUnit using your packaging standards: https://github.com/atolab/conan-cunit. It is ready to be copied to the bincrafters organization (you'll just need the stable:2.1-3 branch once you've tested on your side).

You can find CI here:
* [AppVeyor](https://ci.appveyor.com/project/atolab/conan-cunit)
* [Travis CI](https://travis-ci.org/atolab/conan-cunit)

### Package Details
* Package Name/Version: **stable/2.1-3**
* Operating System: **Linux**, **macOS** and **Windows**
* Compiler+version: **gcc-4.9**, **gcc-5**, **gcc-6**, **gcc-7**, **gcc-8**, **clang-3.9**, **clang-4.0**, **clang-5.0**, **clang-6.0**, **Xcode 7.3**, **Xcode 8.3**, **Xcode 9**, **Xcode 9.3**, **Xcode 9.4**, **Visual Studio 2015**, **Visual Studio 2017**

**Comment by SSE4** [comment]
done, repository was created, and I've added you to the collaborators
