### ISSUE TITLE
webpmux is missing from the libwebp build

### ISSUE THREAD

**Issue by anibali** [bincrafters/community#463]
### Description of Problem, Request, or Question

The build for libwebp includes library files for `webp`, `webpdecode`, and `webpdemux`. However, `webpmux` is absent. This particular library is required for creating webp animations, which is a fairly common use case for people wanting to use libwebp.

A possible reason for the absence is that CMakeLists for the source package doesn't seem to build webpmux by default (see https://github.com/webmproject/libwebp/blob/423f257930f47b9109471697e90d58964ec4df6c/CMakeLists.txt#L222).

/cc @theirix @solvingj @SSE4

**Comment by theirix** [comment]
Already working on support for webpmux in testing/1.0.0 branch. It's ready for Unix and mingw. Windows should be a little later.

**Comment by theirix** [comment]
Done for all platforms. Merged to stable, waiting for CI.

**Comment by anibali** [comment]
Seems to be working well on my end (tested on Linux and Windows), thanks!

**Comment by TentacleSama4254** [comment]
> library

Still missing in mine
