### ISSUE TITLE
libxml2 configured to link against x86_64 libs when cross-compiling for ARM

### ISSUE THREAD

**Issue by ehargitt** [bincrafters/community#465]
### Description of Problem, Request, or Question
Hello. This is my first time posting here and I'm new to Conan, so please have patience with me 😊
As the title suggests, I'm getting a linking error when trying to cross-compile libxml2 as a dependency for another library (libiio). I can show my full output, Dockerfile, conanfile.py, or whatever you need. Please let me know if I should Pastebin link them here or just directly paste. Here is there error causing the issue:
`/usr/lib/x86_64-linux-gnu/libdl.so: file not recognized: File format not recognized`
I am using the preconfigured Conan profile that comes with the lasote Docker image I'm starting with (see below).

Linked here is the package I'm working on: 
[libiio-0.15.zip](https://github.com/bincrafters/community/files/2425470/libiio-0.15.zip)

### Package Details (Include if Applicable)
* Package Name/Version: **libxml2/2.9.8**
* Compiler+version: **gcc-4.9**
* Docker image: Base image: **lasote/conangcc49-armv7hf**. See linked package for Dockerfile for my bugged package.

### Steps to reproduce (Include if Applicable)
1. Comment out the lines where I add my company's Conan artifactory repositories (lines 18-23 inclusive).
1. Make the Docker image using `docker build -t libiio_armv7hf -f Dockerfile_armv7hf .` or whatever name you want.
1. Start an interactive session using `docker run -it --rm libiio_armv7hf`.
1. You will already be in the project folder. Run `conan install . -sf=tmp/source`. I noticed that this will use the root user's default Conan profile, which is not for cross-compiling. This seems inconsequential to me at this stage, but correct me if I'm wrong. UPDATE: I copied the profile from `/home/conan/.conan/profiles/default` to the root user's Conan area and it made no difference in outcome.
1. Run `conan install . -if=tmp/build -pr=/home/conan/.conan/profiles/default --build=missing`
1. Observe the linking error.

**Comment by SSE4** [comment]
seems to be the same issue as https://github.com/bincrafters/community/issues/443
should be fixed in conan 1.8

**Comment by ehargitt** [comment]
You're right, it seems to be the same problem. I'll also leave this open until I test again on 1.8. Do you know when it will be released?

**Comment by SSE4** [comment]
AFAIK next week

**Comment by SSE4** [comment]
@ehargitt conan 1.8.0 is out, please give a try

**Comment by ehargitt** [comment]
This time I had to use `--build` since it was cache resolving this time around for some reason. I'm getting a slightly different error now:
```bash
libiconv/1.15@bincrafters/stable: ERROR: Package 'b869e6c05cb587ad588e5ec485deb62012ec7b93' build failed
libiconv/1.15@bincrafters/stable: WARN: Build folder /root/.conan/data/libiconv/1.15/bincrafters/stable/build/b869e6c05cb587ad588e5ec485deb62012ec7b93
ERROR: libiconv/1.15@bincrafters/stable: Error in build() method, line 119
        self.build_autotools()
while calling 'build_autotools', line 99
        env_build.configure(args=configure_args, host=host, build=build)
        ConanException: Error 19712 while executing ./configure '--prefix=/root/.conan/data/libiconv/1.15/bincrafters/stable/package/b869e6c05cb587ad588e5ec485deb62012ec7b93' '--enable-static' '--disable-shared' '--bindir=${prefix}/bin' '--sbin=${prefix}/bin' '--libexec=${prefix}/bin' '--libdir=${prefix}/lib' '--includedir=${prefix}/include' '--oldincludedir=${prefix}/include' '--datarootdir=${prefix}/res'
```

Any info you want me to grab?

**Comment by SSE4** [comment]
yes, if there is config.log file within /root/.conan/data/libiconv/1.15/bincrafters/stable/build/b869e6c05cb587ad588e5ec485deb62012ec7b93, please paste it here

**Comment by SSE4** [comment]
the error is:
```arm-linux-gnueabihf-gcc-4.9: error: unrecognized command line option '-m64'```
need to check where `-m64` coming from

**Comment by ehargitt** [comment]
`-m64` is listed on the `man` page, so not sure why it doesn't like it. There is also an error with `-qversion`, which isn't in the 'man' page or help message.

**Comment by Croydon** [comment]
This recipe is now in the [Conan Center Index](https://github.com/conan-io/conan-center-index/).

Please migrate to the recipe version there. 
If this is still an issue, please create a new issue in the [Conan Center Index issue tracker](https://github.com/conan-io/conan-center-index/issues).

Thanks!
