### ISSUE TITLE
using Q_OBJECT gives "undefined reference to vtable for plop" at compilation

### ISSUE THREAD

**Issue by ZodiacFRA** [bincrafters/community#466]
### Description of Problem, Request, or Question
When I add Q_OBJECT to my class declaration header, I get `undefined reference to vtable for babel::MainWindow`

### Package Details (Include if Applicable)
* Package Name/Version: **Qt/5.11**
* Operating System: **Linux Fedora 28**
* Compiler+version: **gcc-8.1.1**

### Steps to reproduce (Include if Applicable)
here is my class declaration:
`class MainWindow : public QWidget {`
		`Q_OBJECT`
	`public:`
		`MainWindow(QWidget *parent = nullptr);`

It looks like I need the Q_OBJECT macro to prevent my program from segfaulting
I've added the AUTOMOC in my CMakeLists.txt like this:

`set(CMAKE_AUTOUIC ON)`
`set(CMAKE_AUTOMOC ON)`
`set(CMAKE_INCLUDE_CURRENT_DIR ON)`

and AUTOMOC does link the generated (empty?) .cpp
`[ 85%] Building CXX object client/src/CMakeFiles/babel_client.dir/babel_client_autogen/mocs_compilation.cpp.o`

the generated .cpp looks like this:
`// This file is autogenerated. Changes will be overwritten.`
`// No files found that require moc or the moc files are included`
`enum some_compilers { need_more_than_nothing };`

And I get `undefined reference to vtable for babel::MainWindow`

Any ideas? Every forums i looked at said to run qMake again, but since I'm using conan and Cmake I don't see how I could do this (https://stackoverflow.com/questions/1552069/undefined-reference-to-vtable-trying-to-compile-a-qt-project)

Have a nice day!

**Comment by ericLemanissier** [comment]
Please don't use 5.11 version. It is not maintained. Go for 5.11.2 instead. Also could you please try to remove your build folder and rebuild from scratch?
Your class most probably needs Q_OBJECT.

**Comment by ZodiacFRA** [comment]
Ah i'm sorry, I made a typo, I'm already using 5.11.2, and I delete the build folder and rebuild from scratch everytime. And when I add the Q_OBJECT to my class I get `undefined reference to vtable for babel::MainWindow` so i really don't get it

**Comment by ericLemanissier** [comment]
Could you please send a full minimal reproducible case, including (at least) the cmakelists.txt, the sources and headers, and the conanfile ?

**Comment by ZodiacFRA** [comment]
Even this simple example from Qt's doc: [https://wiki.qt.io/Qt_for_Beginners](url), which is working in my QtCreator, won't work with my build system: [https://send.firefox.com/download/19607aacf2/#AGZOYl-kY0fNnH-wyZPLFg](url)

`Scanning dependencies of target babel_client_autogen`
`[ 20%] Automatic MOC and UIC for target babel_client`
`[ 20%] Built target babel_client_autogen`
`Scanning dependencies of target babel_client`
`[ 40%] Building CXX object client/src/CMakeFiles/babel_client.dir/window.cpp.o`
`[ 60%] Building CXX object client/src/CMakeFiles/babel_client.dir/main.cpp.o`
`[ 80%] Building CXX object client/src/CMakeFiles/babel_client.dir/babel_client_autogen/mocs_compilation.cpp.o`
`[100%] Linking CXX executable ../../../babel_client`

`CMakeFiles/babel_client.dir/window.cpp.o: In function Window::Window(QWidget*):`
`/home/jdupuy/Documents/Epitech/TMP/babel_light_test_creator/client/src/window.cpp:7: undefined reference to vtable for Window`
`/home/jdupuy/Documents/Epitech/TMP/babel_light_test_creator/client/src/window.cpp:7: undefined reference to vtable for Window`

`CMakeFiles/babel_client.dir/window.cpp.o: In function Window::slotButtonClicked(bool):`
`/home/jdupuy/Documents/Epitech/TMP/babel_light_test_creator/client/src/window.cpp:34: undefined reference to Window::counterReached()`

`CMakeFiles/babel_client.dir/main.cpp.o: In function Window::~Window():`
`/home/jdupuy/Documents/Epitech/TMP/babel_light_test_creator/client/inc/window.h:7: undefined reference to vtable for Window`
`/home/jdupuy/Documents/Epitech/TMP/babel_light_test_creator/client/inc/window.h:7: undefined reference to vtable for Window`

`collect2: error: ld returned 1 exit status`
`gmake[2]: *** [client/src/CMakeFiles/babel_client.dir/build.make:118: ../babel_client] Error 1`
`gmake[1]: *** [CMakeFiles/Makefile2:87: client/src/CMakeFiles/babel_client.dir/all] Error 2`
`gmake: *** [Makefile:84: all] Error 2`

**Comment by ericLemanissier** [comment]
This error is not related to conan: you need to add your header files in add_executable, otherwise the moc won't parse them

**Comment by ZodiacFRA** [comment]
Hurray!!! it's working, thank you so much! I spent so much time on this, it's strange that NONE of the forums I saw mentioned this cause. Anyway, thank you again :)

**Comment by ericLemanissier** [comment]
You are welcome. This problem is basically not documented. Most user don't have it because the header files are automatically processed by moc if they are in the same folder as the associated cpp (and have the same name), as explained [here](https://cmake.org/cmake/help/latest/prop_tgt/AUTOMOC.html)
By the way, you can remove ` ${Qt5Network_INCLUDE_DIRS} ${Qt5Widgets_INCLUDE_DIRS}` from your `target_include_directories`, this is handled automatically via `target_link_libraries`

**Comment by hjs3531** [comment]
> 
> 
> This error is not related to conan: you need to add your header files in add_executable, otherwise the moc won't parse them

correct, thanks

**Comment by dimalosev0605** [comment]
> This error is not related to conan: you need to add your header files in add_executable, otherwise the moc won't parse them

Thanks!!!
