### ISSUE TITLE
Qt on Windows with qtx11extras option

### ISSUE THREAD

**Issue by LaMout** [bincrafters/community#467]
### Description of Problem, Request, or Question
Imposible to compile Qt with the qtx11extras option set to True

### Package Details (Include if Applicable)
* Package Name/Version: **Qt/5.11.2@bincrafters/stable**
* Operating System: **Windows 10**
* Compiler+version: **Visual Studio 15**

### Steps to reproduce (Include if Applicable)
Run : ` conan install .. -b missing -s compiler="Visual Studio" -s compiler.version=15 -s arch=x86 -s build_type=Release -s os="Windows"`

The conan file:
```
[requires]
Qt/5.11.2@bincrafters/stable

[options]
Qt:qtx11extras=True

[generators]
cmake
```
At the end I get : 
```
Qt is now configured for building. Just run 'jom'.
Once everything is built, you must run 'jom install'.
Qt will be installed into 'C:\.conan\oqxllov1\1'.

Prior to reconfiguration, make sure you remove any leftovers from
the previous build.


jom 1.1.2 - empower your cores

        cd qtbase\ && ( if not exist Makefile C:\.conan\nj1ohbld\1\qtbase\bin\qmake.exe -o Makefile C:\.conan\eego6q9s\1\qt5\qtbase\qtbase.pro ) && C:\Users\GR000-6K5VTNN821AI\.conan\data\jom_installer\1.1.2\bincrafters\stable\package\3475bd55b91ae904ac96fde0f106a136ab951a5e\bin\jom.exe -f Makefile
Info: creating cache file C:\.conan\nj1ohbld\1\qtbase\.qmake.cache
Le chemin d'accès spécifié est introuvable.
jom: C:\.conan\nj1ohbld\1\Makefile [module-qtbase-make_first] Error 1
Qt/5.11.2@bincrafters/stable:
Qt/5.11.2@bincrafters/stable: ERROR: Package 'd7937ca88bcacbb1568311f7928c1d9b660590b5' build failed
Qt/5.11.2@bincrafters/stable: WARN: Build folder C:/.conan\nj1ohbld\1
ERROR: Qt/5.11.2@bincrafters/stable: Error in build() method, line 295
        _build(self, "jom", args)
while calling '_build', line 289
        self.run(make)
        ConanException: Error 2 while executing jom
```
Am I doing something wrong ?

**Comment by ericLemanissier** [comment]
Hello. To my knowledge, [QtX11Extras is linux only](http://doc.qt.io/qt-5/qtx11extras-index.html), so It is most probably not compatible with MSVC. Maybe you need [qtwinextras](http://doc.qt.io/qt-5/qtwinextras-index.html) instead ?
Do you get the same error with `Qt:qtx11extras=False`
