### ISSUE TITLE
Recipe for GeographicLib

### ISSUE THREAD

**Issue by AlexandrePTJ** [bincrafters/community#468]
Hi,

Here is recipe for geographiclib:
[https://github.com/AlexandrePTJ/conan-geographiclib](https://github.com/AlexandrePTJ/conan-geographiclib)

Please review and tell me if I missed something.

**Comment by uilianries** [comment]
Thanks @AlexandrePTJ !!

**Comment by uilianries** [comment]
Done!

https://bintray.com/bincrafters/public-conan/geographiclib%3Abincrafters

![geographiclib/1.49@bincraftrers/stable](https://screenshotscdn.firefoxusercontent.com/images/57fabd34-451d-46f6-9810-9a0edeeb2cf4.png)

I'll request inclusion on Conan center.

**Comment by AlexandrePTJ** [comment]
Thanks for everything !

**Comment by uilianries** [comment]
It's now available in Conan center! :1st_place_medal: 

https://bintray.com/bincrafters/public-conan/geographiclib%3Abincrafters
