### ISSUE TITLE
conan-ogg CMake wrapper lacks cmake_minimum_required

### ISSUE THREAD

**Issue by asleszyn** [bincrafters/community#471]
### Description

CMake configuration step fails when using the Android cmake toolchain file:
```
CMake Error in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.10)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
```
Passing `-Wno-dev` has no effect.

### Package Details
* Package Name/Version: **ogg/1.3.3**
* Operating System: **Linux Ubuntu 17.10**
* Compiler+version: **Android NDK r17 clang 6.0**

### Steps to reproduce
`cmake <conan_ogg_path> -DCMAKE_TOOLCHAIN_FILE="<ndk>/build/cmake/android.toolchain.cmake"`

**Comment by asleszyn** [comment]
@SSE4 it works, thanks for such a quick fix!

**Comment by SSE4** [comment]
confirmed as fixed, closing
