### ISSUE TITLE
Best way to handle apt-get dependencies?

### ISSUE THREAD

**Issue by ehargitt** [bincrafters/community#473]
I was torn between asking here or on SO, but I think it's a matter of style or opinion. I'm working on creating a recipe for Libiio, which I will turn over to Bincrafters when I'm done 😄. My issue is that I want to handle non-Conan build dependencies using the system package manager (apt, yum, choco). Specifically for Ubuntu, what is a good way to handle adding sources to `/etc/apt/sources.list` when cross-compiling? The `lasote/conangccXX-YY` Docker images set up the cross-compiling toolchain, but don't set up the sources for resolving cross-platform libraries through the package manager. If needing to add sources for each OS/distro, it can get messy. Is there a good way to handle this?

**Comment by ehargitt** [comment]
If it helps the library that I can't resolve is ncurses.

**Comment by solvingj** [comment]
With that said, we are currently avoiding using any system package requirements in Open-Source conan recipes.  There are several reasons for this.  Probably at this time, it's better to check if the packages are installed, then raise an exception if not, and print out the command the user needs to run to install them. 

Thoughts @uilianries @SSE4 @grafikrobot ?

**Comment by uilianries** [comment]
I think the best solution is providing Conan packages or even Conan installer packages.

But depends on how much time you have to spend writing a recipe. IMO I prefer to write a recipe, even a very limited recipe, instead to invoke system_requirements.

@solvingj mentioned relevant points, as sudo requirement. They could provoke headache if you have multiple environments, including linux distros and other OS.

**Comment by solvingj** [comment]
Ah, that's a good point I failed to mention.  Yes, if there's one or two system-dependencies, then we would like to go back and package them with Conan.  However, the harder cases are those where there are 5+ system dependencies for Linux.  In those cases, nobody will be likely to have time to go back and do all those.  great point.

**Comment by SSE4** [comment]
from my personal point of view, there should be clear division when to uses SystemRequirement and when to use conan packages.
I guess it's clear what regular cross-platform libraries such as zlib, boost, openssl, etc. must be used as conan packages.
however, there are libraries which are very system-specific, usually required to access hardware resources, for instance graphics (e.g. OpenGL, vdpau, vaapi, X11, OpenCL, etc). I doubt it makes any sense to provide conan packages for such libraries, and I suppose system requirements shall be used instead.

**Comment by Croydon** [comment]
@ehargitt Please search and upvote or create new issue on the wishlist for missing packages. It helps to better understand what packages are needed the most https://github.com/conan-io/wishlist/issues

I agree with @SSE4 when it comes to low level system-specific libraries it's okay to install them via the system package managers.

I guess it is also okay to install some high level libraries via system package managers as a temporary solution until their are available as Conan packages. However, if you have the motivation and resources to package them by yourself, then I would recommend to do this first.

**Comment by ehargitt** [comment]
Thanks for your help everyone. Added the missing Conan package to the wishlist: https://github.com/conan-io/wishlist/issues/172

**Comment by Croydon** [comment]
@ehargitt Is your question answered for the moment?

**Comment by ehargitt** [comment]
Yep, all good for now. Thanks!
