### ISSUE TITLE
Complete SOIL2 recipe when there is a premake generator

### ISSUE THREAD

**Issue by Croydon** [bincrafters/community#474]
Right now the recipe uses a custom CMake script to get something going, but I think it is better to wait until Conan has a premake generator to continue working on this recipe. Otherwise it would be necessary to implement the entire logic of the premake file in CMake as the current setup is not enough to actually work on all configurations.

Even better when there is a [premake_installer](https://github.com/conan-io/wishlist/issues/162) package, but for the beginning it could be installed via the system package managers.

**Comment by SSE4** [comment]
I've added https://github.com/bincrafters/conan-premake_installer

**Comment by SSE4** [comment]
@Croydon @uilianries @solvingj do you think if we should make premake_generator as a conan package, or just contribute to the conan instead?

**Comment by Croydon** [comment]
Since @memshared already has made an experimental premake generator I would like to have his input in this question.

https://github.com/memsharded/conan-premake

However, in general I think that upstream support is obviously the best as it reaches the most people.

**Comment by SSE4** [comment]
I guess we will add premake generator as builtin soon https://github.com/conan-io/conan/issues/3693

**Comment by Croydon** [comment]
Waiting for the 1.9 release

**Comment by SSE4** [comment]
so far, conan 1.9.0 is released, and `premake_installer` available for 4.3, 4.4 and 5.0 versions

**Comment by SSE4** [comment]
I am closing this out, as:
1. premake generator is now available in conan
2. premake_installer is green (both versions 4 and 5)
3. soil2 is green (except Visual Studio 2013 on appveyor which has license expired)
