### ISSUE TITLE
Generate packages for other architectures

### ISSUE THREAD

**Issue by jgsogo** [bincrafters/community#475]
I've tried to generate libpng for architecture ``armv7hf``, and found it is failing (here it is a PR: https://github.com/bincrafters/conan-libpng/pull/12). 

It is using docker image ``lasote/conangcc49-armv7hf`` and cross-compiling ``Cross-build from 'Linux:x86_64' to 'Linux:armv7hf'``.

Do we want to add more architectures for _every_ package? Some of them already have it... but I understand it could be a little bit of work at many, many recipes.

**Comment by Croydon** [comment]
I think this is rather a question of resources as anything else, in specific CI build time and Bintray disk space.

**Comment by jgsogo** [comment]
Those could be a problem, but the real problem right now (at least for me) is not being able to compile those recipes for those configurations.

**Comment by jgsogo** [comment]
``libpng`` is already working (thanks to @uilianries), but the issue remains with the question: should we add this jobs to every package? other archs? or just add them if requested?

**Comment by solvingj** [comment]
We’ve had this discussion before, as we were granted access to an experimental CI service from ARM last year.  The conclusion was that there are infinite possible platforms and combinations we could precompiled and support, but we have to draw an line somewhere. We’re doing way more than I think most people would expect already, and tbh we can barely keep up with new clangs and xcodes. 

I believe the most practical goal we should set is to make it easy for organizations to fork out repos and make the adjustments they need to make on libraries as-needed. And as always, if people submit those patches back as PR’s we’ll accept them. Also, we have several backlogged projects to further automate our maintenance. 

There is also the possibility that some future CI infrastructure could make it possible to support more configurations and arch’s trivially. We’ll see.

**Comment by jgsogo** [comment]
Ok, thanks, @solvingj! I'll close this issue then 👍
