### ISSUE TITLE
Plugin to update Bintray page

### ISSUE THREAD

**Issue by uilianries** [bincrafters/community#476]
### Description of Problem, Request, or Question

Conan 1.8.0 brought two important feature:
- [Plugins](https://docs.conan.io/en/latest/reference/plugins.html)
- [Inspect](https://docs.conan.io/en/latest/reference/commands/misc/inspect.html)

Now it's possible to read any recipe info and update Bintray using both features together!

**Comment by Croydon** [comment]
![automate_all_the_things](https://user-images.githubusercontent.com/1593194/46670920-c77a0200-cbd3-11e8-911d-8f8f2e4ed43b.jpeg)

**Comment by solvingj** [comment]
I hope that the Bintray and equivalent Artifactory updater plugins can be maintained by conan-community actually.  Github updater plugin could go either way.  In any case, if Conan team doesn't want to maintain them, bincrafters will do it :)

**Comment by uilianries** [comment]
I could move to conan-community 

WDYT @memshared @lasote?

**Comment by memsharded** [comment]
We have a repo here: https://github.com/conan-io/plugins

Things that make sense to be officially supported, might be submitted there as PRs

**Comment by SSE4** [comment]
we have an issue on conan-hooks repository to track this one, closing

**Comment by Croydon** [comment]
also: https://github.com/conan-io/conan/issues/1675
