### ISSUE TITLE
conan-zmq: setting encryption=None

### ISSUE THREAD

**Issue by wpalfi** [bincrafters/community#478]
### Description of Problem, Request, or Question
Due to a bug in conan 1.7.3, it is not possible to set zmq:encryption=None. 
https://github.com/conan-io/conan/issues/3407

### Package Details (Include if Applicable)
* Package Name/Version: **conan-zmq stable/4.2.2**
* Operating System: **Windows**
* Compiler+version: **Visual Studio 2017**
* Docker image: **-**

**Comment by Croydon** [comment]
Conan 1.8.0 got released 2 days ago 😄

**Comment by SSE4** [comment]
@wpalfi please update to 1.8.1 and give an another try

**Comment by Croydon** [comment]
Closing this now. Please report back if the issue remains @wpalfi
