### ISSUE TITLE
Conan 1.8 and new conventions for recipes

### ISSUE THREAD

**Issue by uilianries** [bincrafters/community#479]
### Description of Problem, Request, or Question

Hi!

@danimtb released a new and excellent post about [Conan 1.8](https://blog.conan.io/2018/10/11/New-conan-release-1-8.html)

There is special section that we should talk about:

> New conventions for recipes
>
> Protected ConanFile members
>
> We have seen a great evolution of recipes being created and with the development of new features we think there is a need for a naming convention for the ConanFile attributes and methods to avoid any future collision.
>
> From now on, we encourage users to use protected members in their recipes in case they want to use custom attributes:
>
>class MyConanFile(ConanFile):
>    name = "myconan"
>    version = "1.0.0"
>    _custom_attribute = "some_value"  # user protected attribute
>
>    def _custom_method(self):
>         self.output.info(_custom_attribute)
>
>A note has been included in the reference section to make users aware of this new convention.

As mentioned in the post, custom attributes and method should be protected. In the past @solvingj and I talked about but we chose by using public.

IMO we could change `source_subfolder`, `build_subfolder` and `configure_cmake` from our template to be protected.

/cc @SSE4 @Croydon @solvingj @ericLemanissier

**Comment by SSE4** [comment]
AFAIK in python there is no public/protected methods like in C++, and everything is public and accessible, correct me if I am mistaken

**Comment by Croydon** [comment]
> IMO we could change source_subfolder, build_subfolder and configure_cmake from our template to be protected.

Agreed.

> AFAIK in python there is no public/protected methods like in C++, and everything is public and accessible, correct me if I am mistaken

Correct, but it is common convention to use `_` as a prefix for "private" methods/members.

**Comment by SSE4** [comment]
okay, I have no objection doing so in new recipes, and renaming in old recipes as soon as I touch them for other reasons.

**Comment by ericLemanissier** [comment]
agreed

**Comment by danimtb** [comment]
At the top of this section https://docs.conan.io/en/latest/reference/conanfile.html there is an explanation about this too. It is kind of using a "namespace" for conan and a convention for package creators.

Thanks @uilianries for spreading the word!

**Comment by uilianries** [comment]
> AFAIK in python there is no public/protected methods like in C++, and everything is public and accessible, correct me if I am mistaken

**public**: foo
**protected**: _foo
**private**: __foo

**Comment by SSE4** [comment]
I've update conan-templates

**Comment by solvingj** [comment]
Of note, I am almost certain that I have had generators fail to access protected attributes on my conanfiles.

**Comment by uilianries** [comment]
it makes sense ... if you are getting from public interface. Do you have some example?
