### ISSUE TITLE
conan-bison should explicitly depend on m4

### ISSUE THREAD

**Issue by liberforce** [bincrafters/community#481]
### M4 is required to build bison _and_ run it

Current recipe doesn't depend on m4. At least on linux this should be handled by a [system requirement](https://docs.conan.io/en/latest/reference/conanfile/methods.html#method-system-requirements) to fallback on installing a system package.

### Package Details
* Package Name/Version: **bison/3.0.4@bincrafters/stable**
* Operating System: **Linux Ubuntu 16.04**
* Compiler+version: **gcc-5.4**

### Steps to reproduce

Try to build conan-bison on an Linux system without m4.

**Comment by Croydon** [comment]
Depending on how hard it is to package m4 this should get an own Conan package.

https://www.gnu.org/software/m4/m4.html

**Comment by liberforce** [comment]
I found what is a bit tricky here. I was building a software that depends on bison. The build was working on Ubuntu 14.04, but failing on Ubuntu 16.04. In fact, the Ubuntu 14.04 machine had m4 installed, but not the 16.04.

When running `conan create`, if I force building bison, I will have an error at configure-time, telling me m4 is absent. But if I don't force building bison, conan will just happily download the bison package and will fail **at runtime**. The error I had was:

`
/home/conan/.conan/data/bison/3.0.4/bincrafters/stable/package/d358fec34c04bcd89832a09158783c750a3304dc/share/bison/m4sugar/m4sugar.m4: cannot open: No such file or directory`

The path here is wrong, because `BISON_PKGDATADIR` was ignored : `/home/conan/` is from the binary package built on bincrafters infrastructure, my $HOME is different. If you happen to use a `conan` user to do your builds, you probably won't even see the problem.

The short-term solution is really use SystemPackageTool to force m4 installation so the error message is a bit more informative. In the longer run, a m4 package would be nice, of course.

**Comment by SSE4** [comment]
@liberforce `bison/3.3.2@bincrafters/stable` and `bison_installer/3.3.2@bincrafters/stable` now have a dependency on `m4_installer/1.4.18@bincrafters/stable`.
