### ISSUE TITLE
Request for inclusion: mongo-cxx-driver

### ISSUE THREAD

**Issue by DEGoodmanWilson** [bincrafters/community#485]
### Description of Problem, Request, or Question

Would like to hand over mongocxx conan wrapper to bincrafters
https://github.com/DEGoodmanWilson/conan-mongocxx

### Package Details (Include if Applicable)
* Package Name/Version: **mongocxx/3.2.0**
* Operating System: **Linux and OS X**
* Compiler+version: **gcc 4.9–7, clang 3.9–4.0*, Apple clang 7.3–10.0*
* Docker image: n/a

### Notes

I've been using this for a while, and it feels ready for others to use. The only caveat is that I don't have Windows builds going because TBH I don't know how to set those up.

I also have mongo-c-driver wrappers which I would like to contribute, in a [separate issue](https://github.com/bincrafters/community/issues/484)

**Comment by SSE4** [comment]
@DEGoodmanWilson 
repository was create
CI has been enabled
you should have an GitHub invitation in your e-mail

**Comment by DEGoodmanWilson** [comment]
@SSE4 is it possible to rename the repo? It seems either I named my repo badly, or Mongo renamed theirs. It should be `conan-mongo-cxx-driver`, to match `mongodb/mongo-cxx-driver`

**Comment by Croydon** [comment]
This is done, isn't it?

**Comment by promgamer** [comment]
still WiP on my side

**Comment by VioletGiraffe** [comment]
What's the current status? I can see the package `mongo-cxx-driver/3.2.0@bincrafters/stable`, but its installation fails: 
ERROR: Version range '~=1.2' from requirement 'zlib/[~=1.2]@conan/stable' required by 'mongo-c-driver/1.9.4@bincrafters/stable' could not be resolved
Is it even the same package that's being worked on here?

**Comment by promgamer** [comment]
I'm working on the 3.3.0 version, still on branch testing. 3.2.0 is @DEGoodmanWilson's one

**Comment by DEGoodmanWilson** [comment]
so now we have two issues… @VioletGiraffe could you open a new issue for your problem? Let's get that fixed for you.

**Comment by VioletGiraffe** [comment]
@DEGoodmanWilson : done (#509).

**Comment by Croydon** [comment]
@DEGoodmanWilson Could you please
  * add a sha256 checksum to the tools.get() download (use the sha256 parameter)
  * remove the version ranges for deps and add absolute versions (Conan team recommendation, Bincrafters convention)
  * replace the url in the `license` attribute with the SPDX name 
  * replace `default_options` with a  python dictionary (recent change in Conan convention)
  * add the meta data attributes `topics` and `author`, reference: https://github.com/bincrafters/conan-templates/blob/master/conanfile.py#L13

**Comment by promgamer** [comment]
I had some days away from the keyboard. Going to resume my work on this tomorrow!

**Comment by DEGoodmanWilson** [comment]
@Croydon Working on those changes now to mongo-c-driver and mongo-cxx-driver, as well as updateing the build to use the same system as @promgamer so we can have windows builds.

But mongo-c-driver 1.9.x doesn't use cmake. It only uses make. That makes me sad (ooooh, puns). I have no experience with building on Windows with Makefiles. @promgamer is this something you can help me with?

**Comment by Croydon** [comment]
@DEGoodmanWilson Ping? :)

**Comment by DEGoodmanWilson** [comment]
Pong. Will have a look at this starting next week. Apologies that I've been busy on other things.

**Comment by SSE4** [comment]
I am closing, as version 3.3.0 is available now
for any further problems with package, please open new issues
