### ISSUE TITLE
GLM glm:g-truc is outdated

### ISSUE THREAD

**Issue by ShFil119** [bincrafters/community#486]
### Description of Problem, Request, or Question
Actual available version contains some bugs, fixed in newer versions.
### Package Details (Include if Applicable)
* Package Name/Version: *0.9.9.0*

### Steps to reproduce (Include if Applicable)
I think especially about this bug:
https://github.com/g-truc/glm/issues/754

Example log of problem:
https://travis-ci.org/ShFil119/openrw/jobs/441110077

**Comment by SSE4** [comment]
new version is available, please give an another try

**Comment by ShFil119** [comment]
Works, thanks. :D
https://travis-ci.org/ShFil119/openrw/jobs/442058961
