### ISSUE TITLE
Icu/59.1 cmake transitive dependancy

### ISSUE THREAD

**Issue by davidtazy** [bincrafters/community#487]
Hi, 
I think this use case should work:

### Description of Problem

MyApp depends on MyLib.
MyLib depends on libicu: target_link_library(MyLib PRIVATE libicu::libicu)
Icu flag shared is on
Use cmake_find_package generator
Use libicu::libicu target
MyLib is shared.

MyApp approximately compile error (sorry):
/conan/path/LibicuXXX.so complains missing libicuYYY.so 
Cmake error advice to use rpath.

I fixed my problem switching from PRIVATE to PUBLIC in : target_link_library(MyLib PUBLIC libicu::libicu)

ldd /Conan/path/libicuXXX confirmed that depends to libicuYYY is without rpath.. 

With wIndows msvc2017 : no build error

### Package Details (Include if Applicable)
* Package Name/Version: **icu/59.1**
* Operating System: **Linux Ubuntu 16.04 amd64**
* Compiler+version: **gcc-5.4**

Regards

**Comment by SSE4** [comment]
@davidtazy may you try with `icu/63.1` (newer version)?

**Comment by davidtazy** [comment]
same error:
`
/usr/bin/g++  -O3 -DNDEBUG  -rdynamic _/CMakeFiles/_.dir/src/main.cpp.o _/CMakeFiles/_.dir/__autogen/mocs_compilation.cpp.o _/CMakeFiles/_.dir/__autogen/QFTX5SWBVD/qrc_ressource.cpp.o  -o _/_  -Wl,-rpath,/opt/Qt/5.9.7/gcc_64/lib:/home/david/Documents/build-Workspace_PCSurface-Desktop_Qt_5_9_7_GCC_64bit-Release/Common/:/home/david/Documents/build-Workspace_PCSurface-Desktop_Qt_5_9_7_GCC_64bit-Release/Common/libTranslit2: /opt/Qt/5.9.7/gcc_64/lib/libQt5Widgets.so.5.9.7 /opt/Qt/5.9.7/gcc_64/lib/libQt5Gui.so.5.9.7 o Common/libTranslit/libtranslit.so /opt/Qt/5.9.7/gcc_64/lib/libQt5Core.so.5.9.7  /opt/Qt/5.9.7/gcc_64/lib/libQt5Core.so.5.9.7 /opt/Qt/5.9.7/gcc_64/lib/libQt5Core.so.5.9.7 && :
/usr/bin/ld: warning: libicudata.so.63, needed by //home/david/.conan/data/icu/63.1/bincrafters/stable/package/79c7866f730546d6983f6a733610e8483f2299fc/lib/libicuuc.so.63, not found (try using -rpath or -rpath-link)
//home/david/.conan/data/icu/63.1/bincrafters/stable/package/79c7866f730546d6983f6a733610e8483f2299fc/lib/libicuuc.so.63: undefined reference to icudt63_dat'
collect2: error: ld returned 1 exit status
`

**Comment by SSE4** [comment]
the following simple example works for me:
**CMakeLists.txt**
```
cmake_minimum_required(VERSION 2.8)

project(icu-test)

set(CMAKE_MODULE_PATH "${CMAKE_MODULE_PATH};${CMAKE_CURRENT_SOURCE_DIR}")

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

find_package(icu REQUIRED)

add_executable(icu-test main.cpp)

target_link_libraries(icu-test icu::icu)
```
**conanfile.txt**
```
[requires]
icu/64.2@bincrafters/testing
[generators]
cmake_find_package
[options]
icu:shared=True
```
**main.cpp**
```
#include <stdio.h>
#include "unicode/utypes.h"
#include "unicode/uchar.h"
#include "unicode/locid.h"
#include "unicode/ustring.h"
#include "unicode/ucnv.h"
#include "unicode/unistr.h"

int
main(int argc, const char *argv[]) {
    UErrorCode errorCode=U_ZERO_ERROR;

    auto cnv=ucnv_open(NULL, &errorCode);
    if(U_FAILURE(errorCode)) {
        fprintf(stderr, "error %s opening the default converter\n", u_errorName(errorCode));
        return errorCode;
    }

    ucnv_close(cnv);
    return 0;
}
```

**Comment by SSE4** [comment]
@davidtazy if you could share your code it would be helpful

**Comment by davidtazy** [comment]
thx for your time
here is the minimal code to reproduce issue

on ubuntu 16.04 x64  gcc 5.4

**CMakeLists.txt**
```
cmake_minimum_required(VERSION 2.8)

project(icu-test)

set(CMAKE_MODULE_PATH "${CMAKE_MODULE_PATH};${CMAKE_CURRENT_SOURCE_DIR}")

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

find_package(icu REQUIRED)

add_library(pimpl_icu SHARED pimpl_icu.cpp )  # STATIC is OK
target_include_directories(pimpl_icu PUBLIC .)
target_link_libraries(pimpl_icu PRIVATE icu::icu) #PUBLIC is OK

add_executable(icu-test main.cpp )
target_link_libraries(icu-test pimpl_icu)
```
**conanfile.txt**  * (icu/64.2@bincrafters/testing is not available )
``` 
requires]
icu/64.2@bincrafters/stable
[generators]
cmake_find_package
[options]
icu:shared=True
```

**pimpl_icu.h**
``` 
struct pimpl_icu{

    int do_icu_stuff();

};
```

**pimpl_icu.cpp**
``` 
#include "pimpl_icu.h"
#include <stdio.h>
#include "unicode/utypes.h"
#include "unicode/uchar.h"
#include "unicode/locid.h"
#include "unicode/ustring.h"
#include "unicode/ucnv.h"
#include "unicode/unistr.h"

int pimpl_icu::do_icu_stuff(){
    UErrorCode errorCode=U_ZERO_ERROR;

    auto cnv=ucnv_open(NULL, &errorCode);
    if(U_FAILURE(errorCode)) {
        fprintf(stderr, "error %s opening the default converter\n", u_errorName(errorCode));
        return errorCode;
    }
    printf("ok\n");

    ucnv_close(cnv);
    return 0;
}
```

**main.cpp**
```
#include <pimpl_icu.h>

int
main(int argc, const char *argv[]) {
    pimpl_icu obj;
    return obj.do_icu_stuff();
}
```

**make console output**
```
david@david-VirtualBox:~/icu_test/build$ make
Scanning dependencies of target pimpl_icu
[ 25%] Building CXX object CMakeFiles/pimpl_icu.dir/pimpl_icu.cpp.o
[ 50%] Linking CXX shared library libpimpl_icu.so
[ 50%] Built target pimpl_icu
Scanning dependencies of target icu-test
[ 75%] Building CXX object CMakeFiles/icu-test.dir/main.cpp.o
[100%] Linking CXX executable icu-test
/usr/bin/ld: warning: libicudata.so.64, needed by //home/david/.conan/data/icu/64.2/bincrafters/stable/package/8df9d614e4b5d8842dfd3fa36360df85c4465147/lib/libicuuc.so.64, not found (try using -rpath or -rpath-link)
//home/david/.conan/data/icu/64.2/bincrafters/stable/package/8df9d614e4b5d8842dfd3fa36360df85c4465147/lib/libicuuc.so.64 : référence indéfinie vers « icudt64_dat »
collect2: error: ld returned 1 exit status
CMakeFiles/icu-test.dir/build.make:95 : la recette pour la cible « icu-test » a échouée
make[2]: *** [icu-test] Erreur 1
CMakeFiles/Makefile2:67 : la recette pour la cible « CMakeFiles/icu-test.dir/all » a échouée
make[1]: *** [CMakeFiles/icu-test.dir/all] Erreur 2
Makefile:83 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2
```

**Comment by Croydon** [comment]
This recipe is now in the [Conan Center Index](https://github.com/conan-io/conan-center-index/).

Please migrate to the recipe version there. 
If this is still an issue, please create a new issue in the [Conan Center Index issue tracker](https://github.com/conan-io/conan-center-index/issues).

Thanks!

https://conan.io/center/icu
