### ISSUE TITLE
conan-qt doesn't respect the CC or CXX env variables when running Qt's ./configure script

### ISSUE THREAD

**Issue by Quincunx271** [bincrafters/community#488]
### Description of Problem, Request, or Question

When building conan-qt from source with the compiler settings and corresponding environment variables specified, when running Qt's configure script, the compiler used is not the one set in the environment variable, but the unversioned compiler.

### Package Details (Include if Applicable)
* Package Name/Version: **Qt/5.11.2**
* Operating System: **Linux Ubuntu 16.04**
* Compiler+version: Any compiler which isn't the unversioned compiler for the system

### Steps to reproduce (Include if Applicable)

Run `conan install` with the following arguments:

```sh
Qt/5.11.2@bincrafters/stable --build Qt
# Set up the compiler information. The specific version doesn't seem to matter as long as
# it's not the unversioned version (the one that would be called like `g++` instead of `g++-n`)
# I don't think the compiler.libcxx matters either.
-s compiler=gcc
-s compiler.version=8.1
-s compiler.libcxx=libstdc++
# Pass the environment variables for the compiler
-e CC=$(which gcc-8)
-e CXX=$(which g++-8)
```

Then, examine the `config.log` for the build:

```sh
$ cat ~/.conan/data/Qt/5.11.2/bincrafters/stable/build/hash/config.log
```

All the compiler invocations are using the unversioned compiler (`g++`) instead of the versioned compiler (`g++-8`).

Also tested with Clang 8.0 (built from source - I believe Clang 8.0 is not yet released). Instead of using `g++`, the configure script uses `clang++`. This fails the build on my system, since `clang++` is `clang++-5.0` which somehow fails when trying to `#include <stdio.h>`

**Comment by ericLemanissier** [comment]
Thanks for the report !
I just pushed the fix to branches stable/5.9.7 and stable/5.11.2. It is available if you build from github sources. Binaries will be available on bintray in the coming days. Can you confirm it works on your side ?

**Comment by Quincunx271** [comment]
I cloned the conan-qt repository and ran `conan create -s compiler=clang -s compiler.version=8.0 -s compiler.libcxx=libstdc++11 -e CC=$(which clang-8.0) -e CXX=$(which clang++-8.0) .. Qt/5.11.2@bincrafters/asdf`, but it didn't completely work. Here's the config.log:

```
Command line: -shared -confirm-license -silent -nomake examples -nomake tests -prefix /path/to/.conan/data/Qt/5.11.2/bincrafters/asdf/package/d4a69867a98c7657f586cbf6e63c3d201e2c89e2 -opensource -release -skip qtserialport -skip qtwebchannel -skip qtwebglplugin -skip qtlocation -skip qtdeclarative -skip qtimageformats -skip qtandroidextras -skip qtconnectivity -skip qtscxml -skip qtwebengine -skip qtwebsockets -skip qtwayland -skip qtactiveqt -skip qtmultimedia -skip qtdoc -skip qtwebview -skip qttranslations -skip qt3d -skip qtscript -skip qtnetworkauth -skip qtmacextras -skip qtgraphicaleffects -skip qtx11extras -skip qtsvg -skip qtcharts -skip qtsensors -skip qtquickcontrols2 -skip qtspeech -skip qtremoteobjects -skip qtquickcontrols -skip qtserialbus -skip qtgamepad -skip qtvirtualkeyboard -skip qtwinextras -skip qtdatavis3d -skip qttools -skip qtcanvas3d -skip qtpurchasing -skip qtxmlpatterns -opengl desktop -no-openssl -qt-xcb -xplatform linux-clang QMAKE_CC=/path/toclang-8.0 QMAKE_CXX=/path/to/clang++-8.0 -qt-zlib
executing config test use_gold_linker
+ cd /path/to/.conan/data/Qt/5.11.2/bincrafters/asdf/build/d4a69867a98c7657f586cbf6e63c3d201e2c89e2/config.tests && clang++ -pipe -fuse-ld=gold -o conftest-out conftest.cpp
test config.qtbase.tests.use_gold_linker succeeded
executing config test machineTuple
+ clang++ -dumpmachine
> i386--linux-gnu
test config.qtbase.tests.machineTuple succeeded
executing config test verifyspec
+ cd /path/to/.conan/data/Qt/5.11.2/bincrafters/asdf/build/d4a69867a98c7657f586cbf6e63c3d201e2c89e2/config.tests/verifyspec && /path/to/.conan/data/Qt/5.11.2/bincrafters/asdf/build/d4a69867a98c7657f586cbf6e63c3d201e2c89e2/qtbase/bin/qmake "CONFIG -= qt debug_and_release app_bundle lib_bundle" "CONFIG += shared use_gold_linker warn_off console single_arch" QMAKE_CC=/path/toclang-8.0 QMAKE_CXX=/path/to/clang++-8.0 -early "CONFIG += cross_compile" /path/to/.conan/data/Qt/5.11.2/bincrafters/asdf/source/qt5/qtbase/config.tests/verifyspec
+ cd /path/to/.conan/data/Qt/5.11.2/bincrafters/asdf/build/d4a69867a98c7657f586cbf6e63c3d201e2c89e2/config.tests/verifyspec && MAKEFLAGS= /usr/bin/make
> /path/to/clang++-8.0 -c -pipe -O2 -std=gnu++11 -w -fPIC  -I/path/to/.conan/data/Qt/5.11.2/bincrafters/asdf/source/qt5/qtbase/config.tests/verifyspec -I. -I/path/to/.conan/data/Qt/5.11.2/bincrafters/asdf/source/qt5/qtbase/mkspecs/linux-clang -o verifyspec.o /path/to/.conan/data/Qt/5.11.2/bincrafters/asdf/source/qt5/qtbase/config.tests/verifyspec/verifyspec.cpp
> clang++ -ccc-gcc-name g++ -fuse-ld=gold -o verifyspec verifyspec.o
> /usr/bin/ld.gold: error: verifyspec.o: incompatible target
> /usr/bin/../lib/gcc/x86_64-linux-gnu/5.5.0/../../../i386-linux-gnu/crt1.o(.text+0x18): error: undefined reference to 'main'
> clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
> Makefile:66: recipe for target 'verifyspec' failed
> make: *** [verifyspec] Error 1
```

I can see that it is using `clang++-8.0` to compile the file. However, it appears that it is still using the unversioned `clang++` to link, and that there's some problem with an undefined reference to main. I don't know if this has to do with this particular report, though.

**Comment by ericLemanissier** [comment]
Indeed, I forgot the linker. I just pushed a fix on https://github.com/bincrafters/conan-qt/tree/testing/5.11.2. Could you please checkout testing/5.11.2 branch and retry ?

**Comment by Quincunx271** [comment]
It seems to have worked. It configured and built Qt.

However, when it tried to build the `(test package)`, it again tried to use the unversioned `clang++`. I think this only happened because I ran `conan create`, though. IIUC, `conan install` won't run the test package.

**Comment by ericLemanissier** [comment]
Thanks for doing the test. I just amended testing/5.11.2: the test recipe uses also CC and CXX environment variable for qmake build. I am not sure if something needs to be done for the cmake test. Could you please try it ?

**Comment by Quincunx271** [comment]
It looks like it worked. The full command executed without problems and used the versioned executable.
