### ISSUE TITLE
[question] Should winflexbison be considered as a build requirement?

### ISSUE THREAD

**Issue by danimtb** [bincrafters/community#489]
### Description of Problem, Request, or Question

I have no experience with winflexbison but I have seen it builds an executable so I think it is kind of a tool. Should it be considered always a a build requirement in Conan?

In that case maybe add these lines:

```
    def package_info(self):
          self.env_info.PATH.append(os.path.join(self.package_folder, "bin"))
```

Thanks!

### Package Details (Include if Applicable)
* Package Name/Version: **winflexbison**
* Operating System: **Windows**

cc/ @Croydon

**Comment by uilianries** [comment]
When I started bison and flex my concern was build other linux libraries that depend both them.

But I was wrong naming both bison and flex as package name. They should be bison_installer and flex_installer. Now we have the situation where same package contains binaries and libraries.

This discussion is about winflexbison, but it's going on same way.

**Comment by Croydon** [comment]
Is the common opinion to use the `_installer` suffix for binaries-only packages? I had the impression it is used for build_requirements binaries only. Isn't it more beneficial to use the official names of the projects?

**Comment by SSE4** [comment]
IMO it should be clearly separated by the `_installer` suffix
e.g. we may install `OpenSSL` as a library to link against it, in another time, we may want to install `OpenSSL` as a package providing command line tool `openssl` (or `openssl.exe`), e.g. to generate some certificates during the build. it's hypothetical situation, but I believe it applies to wider range of tools/libraries (e.g. I believe, it might be case for `ffmpeg` or `imagemagick`). sometime tools/libraries are already clearly separated (e.g. `libiconv` vs `iconv`, or `libcurl` vs `curl`), sometimes not.

**Comment by Croydon** [comment]
But wouldn't that mean that you are separating projects into several packages which are one project upstream?  Wouldn't it be better to keep it together in most cases as it is upstream?

**Comment by SSE4** [comment]
probably yes, as different settings apply for tool and library. e.g. while `compiler` is important for library, it's irrelevant for tool.

**Comment by Croydon** [comment]
This is done, but I'm wondering if we should continue to live with the inconsistent name `winflexbison`, even though it should be clearly `winflexbison_installer` or if we should migrate it 🤔 

Opinions? Pinging @danimtb as it is already included in conan-center

**Comment by danimtb** [comment]
The recipe is packaging header files and executables (https://github.com/bincrafters/conan-winflexbison/blob/stable/2.5.16/conanfile.py) so I am not sure if it is used as a tool, as a library or both.

If it is a tool, I'd use `winflexbison_installer`. if not, I'd keep it as it is right now.

P.S. I'd say it is a tool regarding its test_package https://github.com/bincrafters/conan-winflexbison/blob/stable/2.5.16/test_package/conanfile.py

**Comment by Croydon** [comment]
Having a look in the build package, I believe the line which copies headers is a mistake, as no headers are actually getting copied. 

Flex/bison are tools-only from my understanding. I believe however that this executable are requiring m4 which is in `bin/data`, which contains some configurations, source and headers, but when this is only used by the executable I believe it still qualifies as tool-only.

Maybe @uilianries can shed some light on the purpose of m4. I'm not familiar with it

**Comment by SSE4** [comment]
`m4` is GNU macro processor. it's well-known as the base of auto tools and its `configure` scripts, as well as `bison` uses `m4` under the hood.
in order to operator, `bison` requires `m4` executable, as well as bunch of `.m4` files (which is common macro library and some templates for code generation). without its data folder, bison is basically non-operable and useless.

**Comment by Croydon** [comment]
Should be fixed by 

https://github.com/bincrafters/conan-winflexbison/commit/38bbfc7aea65f5452fa73dbfc4fb42c2735b457e
https://github.com/bincrafters/conan-winflexbison/commit/469d07f29b3e16d048cda10bbb2f3b3289b03565

**Comment by madebr** [comment]
@Croydon 
You should add
```
        self.info.include_build_settings()
```
to the body of `package_id()`

When you review the package id of the current x86 and the x64 builds on appveyor, they are currently the same.
https://github.com/madebr/conan-winflexbison/blob/2aa18a5396492c820c5c284afebca58081c8b259/conanfile.py#L31

**Comment by Croydon** [comment]
Thanks, I wasn't aware that Conan is removing the `_build` attributes automatically as soon as others are defined as well.

From the docs:
https://docs.conan.io/en/latest/faq/conan1.0.html#new-features
