### ISSUE TITLE
Cannot install libsodium

### ISSUE THREAD

**Issue by Konijnendijk** [bincrafters/community#490]
### Description of Problem

When installing libsodium (in my case needed for libzmq) the following error occurs: 

```
ERROR: /path/to/.conan/data/libsodium/1.0.16/bincrafters/stable/export/conanfile.py not found!
```

### Package Details (Include if Applicable)
* Package Name/Version: **libsodium/1.0.16**
* Operating System: **Linux Debian Buster**
* Compiler+version: **gcc-8.2.0**

### Steps to reproduce

Create a `conanfile.txt` with the following contents: 

```
[requires]
libsodium/1.0.16@bincrafters/stable
```

Run `conan install` to get the following error: 

```
libsodium/1.0.16@bincrafters/stable: Retrieving from predefined remote 'bincrafters'
libsodium/1.0.16@bincrafters/stable: Trying with 'bincrafters'...
Downloading conanmanifest.txt
[==================================================] 182B/182B        
ERROR: /path/to/.conan/data/libsodium/1.0.16/bincrafters/stable/export/conanfile.py not found!
```

**Comment by SSE4** [comment]
it was recently rebuilt, could you possibly try running `conan remove -f libsodium*`, then try again?

**Comment by Konijnendijk** [comment]
Thanks for the quick response!

Unfortunately I'm still getting the same error. Also (not sure if this is relevant) I can't seem to find the `conanfile.py` when browsing the repository on Bintray.

**Comment by SSE4** [comment]
@Konijnendijk rebuild is done, please try one more time

**Comment by Konijnendijk** [comment]
I did another 
```
conan remove -f "libsodium*"
conan install .
```
but unfortunately I'm still getting the same error message.

**Comment by SSE4** [comment]
@danimtb do you have any ideas on what might be going wrong?

**Comment by db4** [comment]
Yes, now it works for me. Thanks.

**Comment by Konijnendijk** [comment]
It works for me too. Thanks for fixing this so quickly!
