### ISSUE TITLE
"Add fPIC option to a Conan Recipe" documentation is confusing

### ISSUE THREAD

**Issue by sigiesec** [bincrafters/community#492]
https://github.com/bincrafters/community/blob/master/howtos/add_fpic_option_to_recipe.rst is quite confusing:

> At a certain point, we realized we should be adding fPIC option for many packages which we did not consider before. So, please check with the team in slack if you’re not sure whether or not you need fPIC.

See my other issue #491 on that.

> In order to add fPIC options, modify your conanfile.py by adding highlighted lines:
> ```
> options = {"shared": [True, False], "fPIC": [True, False]}
> default_options = "shared=False", "fPIC=True"
> ```

This is confusing insofar as this appears to imply that no options/default_options were defined before (which might not be the case), but in that case also adds the "shared" option (which is probably always a good idea, see #491, but is not related to the topic of that page).

> also, you’ll need **configure** method to skip fPIC for Visual Studio

Why? As far as I understand this, this is unnecssary. For what scenario should this make a difference? When using cmake, cmake correctly handles the POSITION_INDEPENDENT_CODE property for all supported platforms (and for platforms where it is not needed, it already has no effect). Autotools do not work under Windows anyway, and any custom build must handle this in a custom way anyway. When it is unnecessary, I think it is not a good idea to add this, because it distracts from other relevant parts of the recipes.

> For CMake-based projects Conan is **automatically** setting **CMAKE_POSITION_INDEPENDENT_CODE** based on the **fPIC** recipe option. This looks internally similar to this:

Besides this is inaccurate, I do think it is a good idea to explain implementation details of conan here, which might change over time. 

> For autotools-based projects, you may just need:

I don't think this is needed anymore. When using AutoToolsBuildEnvironment, this was handled automatically even before the above-mentioned handling for the cmake generators was implemented.

So this could be reduced to:
```
When using any of the cmake generators, or AutoToolsBuildEnvironment, Conan handles this automatically based on the **fPIC** recipe option.
```

> Or alternatively, if configure provides **–with-pic** option:

This part is actually true, but somewhat context-less. It is unclear where the code fragment should be added to conanfile.py

I can try to rework the page.

**Comment by SSE4** [comment]
` Autotools do not work under Windows anyway`
they do work on Windows - as with MinGW, as with Visual Studio, for instance, we build `libiconv` and `ffmpeg` via autotools for Windows.
`Why? As far as I understand this, this is unnecssary.`
this is necessary. first, option is useless on Windows, so it's confusing to have it available when it has no effect. second, adding `-fPIC` on Windows may produce compiler warnings, or even errors (if we build with `treat warnings as errors` option). we already have seen it happened with MinGW builds.

**Comment by sigiesec** [comment]
>  they do work on Windows
Ok, maybe I was mistaken in this regard, and I did not have MinGW in mind.

> this is necessary. first, option is useless on Windows, so it's confusing to have it available when it has no effect

Ok. I see this differently. cmake handles this differently, in the way I expect it: Properties are specified in a platform-independent way, and naturally, they have different effects on different platforms. The effect may be none for some properties on some platforms.

Perhaps the different view on this is also reflected in the naming. fPIC is a gcc/clang/... compiler option, which is not a platform-independent view on this. POSITION_INDEPENDENT_CODE (from cmake) is a platform-independent name. On Windows, code might be always position-independent. That's fine.

> -fPIC on Windows may produce compiler warnings

I think you refer to gcc/clang -fPIC with MinGW here, right? Maybe there is some bug/omission in some other part of the tool chain, and maybe a workaround is needed for that. But if a workaround is needed for gcc/clang on MinGW, shouldn't it be skipped specifically for that platform?

**Comment by Croydon** [comment]
We need to delete fPIC for MSVC otherwise the build with fPIC=True and fPIC=False would produce the exact same result, but would still be treated as two different packages by Conan. Also as @SSE4 already said it is confusing to be able to set options which have no effect.

**Comment by sigiesec** [comment]
> We need to delete fPIC for MSVC otherwise the build with fPIC=True and fPIC=False would produce the exact same result, but would still be treated as two different packages by Conan.

I think this is legitimate point, though only an optimization IMO to reduce the number of necessary builds. But it would make sense to add this information to the documentation page, and maybe also to the comment template.

**Comment by Croydon** [comment]
I'm closing this as no further action seems to be needed.

IMHO, Documentation is fine for now and might need soon a general overhaul.
