### ISSUE TITLE
gtest/1.8.1 cannot be found by CMake on Windows/Debug

### ISSUE THREAD

**Issue by piponazo** [bincrafters/community#493]
### Description of Problem, Request, or Question

When I try to find the gtest 1.8.1 package on Windows + MSVC + Debug mode, this is not found:

```
-- Could NOT find GTEST (missing: GTEST_LIBRARIES GTEST_MAIN_LIBRARIES GTEST_BOTH_LIBRARIES)
```

I think this is due to the customised `FindGTest.cmake` file that is not including the library names with the suffix `d`.

### Package Details (Include if Applicable)
* Package Name/Version: **gtest/1.8.1**
* Operating System: **Windows 10**
* Compiler+version: **Visual Studio 2017, Debug Mode**

### Steps to reproduce (Include if Applicable)

conan profile used:
```
[build_requires]
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=15
build_type=Debug
[options]
[env]
```
Note that the 1.8.0 version works perfectly in Release and Debug modes.

**Comment by uilianries** [comment]
Hi @piponazo !

Thanks for reporting!

**Comment by uilianries** [comment]
Hi @piponazo !

Sorry for the delay, gtest is fixed now, please, try again when possible.

![gtest/1.8.1@bincrafters/stable](https://screenshotscdn.firefoxusercontent.com/images/1dabd4cb-d2d0-43bb-8301-8d5e5ac5347f.png)

**Comment by piponazo** [comment]
Great! I tested the new package and now it works like a charm 😉

**Comment by lordnigh** [comment]
I continue with same problem in Linux Version, cannot compile in Debug mode, what steps i have do in version 1.8.1/stable for compile in debug mode. i use gtest with conan

**Comment by Croydon** [comment]
@lordnigh Bincrafters' gtest package is migrated to the (new) Conan Center Index

Please start using gtest from there: https://conan.io/center/gtest/1.10.0/

If you still run into issue open an issue on the Index

**Comment by SeanSnyders** [comment]
I think I am experiencing the same situation here, even though using latest GTest 1.10.0 package from conan center and CMake 3.19.1 (or latest 3.19.3 which gives the same error).

Compiling on macOS and including gtest via `build_requires` and trying to compile my own package/library and CMake's `FindGTest` tries to set variables `GTEST_LIBRARY` `GTEST_INCLUDE_DIR` `GTEST_MAIN_LIBRARY` set, but these cannot be set when building your own library in `Debug` mode as the `FindGTest` logic tries to set these variables based off the library filenames in the found conan package.
So e.g. via Conan setting `-s build_type=Debug` which then targets the debug Conan package of GTest, which *has only* the debug libraries compiled and available there (i.e. `lib*d.a`) it sets variables `GTEST_LIBRARY_DEBUG` and `GTEST_MAIN_LIBRARY_DEBUG` but not  `GTEST_LIBRARY` and `GTEST_MAIN_LIBRARY` and thus the `FindGTest` fails with a `NOTFOUND` as its logic depends on the non-debug CMake variables.

To fix, either
1. `FindGTest` needs better logic to carry debug variables over to release ones when only debug is found, or
2.  Conan GTest package needs to include both debug and release in the same package, and `FindGTest` will thus still always use released libraries, but at least it will not error.
3. Specify a Conan profile to always override/set GTest `build_type` to `Release` (https://github.com/conan-io/conan/issues/3000). But this is just circumvention of the problem.
