### ISSUE TITLE
License naming in Conan recipes

### ISSUE THREAD

**Issue by uilianries** [bincrafters/community#494]
### Description of Problem, Request, or Question

Hi folks!

As we know Conan provides the attribute **license**.
Usually we use the license URL or the license name to fill that attribute.

My goal here is to follow the Bintray naming convention. For Example:

"Apache-2.0", "BSL-2.0", "MIT", BSD-Clause3"

All available licenses could be checked by:

`curl https://api.bintray.com/licenses/oss_licenses`

But why?
I started a [Conan plugin](https://github.com/conan-io/plugins/pull/2) to update all metadata on Bintray page, reading all attributes from recipe. However, all attributes must be valid.

I want to discuss before to change anything.

/cc @Croydon @solvingj @ericLemanissier @SSE4

**Comment by Croydon** [comment]
I'm not sure what you question is. Like if we want to check the license at all?

> My goal here is to follow the Bintray naming convention.

Small note: SPDX is more like a Linux Foundation specification instead of a Bintray naming convention 😄

**Comment by uilianries** [comment]
Sorry, SPDX that's the name! Thanks @Croydon!

Anyway, my objective is follow the exactly same name, including hyphen and dots. Otherwise, it will not work with Bintray.

**Comment by Croydon** [comment]
Bintray doesn't seeem to support the entire SPDX specification I can't find `GPL-3.0-or-later` for example. https://spdx.org/licenses/

And some projects are using custom licenses as well, or multiple ones. I would suggest that the plugin should check if the conanfile `license` attribute has a value which is in the Bintray license list and 
  * if yes, update the Bintray license field
  * if not, set the license field to unspecific/default/empty

**Comment by uilianries** [comment]
Sounds good!

We could request license inclusion for Bintray support. I have requested but was refused, I dont remember for which package.

**Comment by Croydon** [comment]
@uilianries Since I have added a SPDX check within bincrafters-conventions, do you think we can close this now?

**Comment by Croydon** [comment]
I have also added a comment to the templates that it should use SPDX identifiers

**Comment by uilianries** [comment]
Yes, I think it's good enough :)
