### ISSUE TITLE
Conan package: imagemagick

### ISSUE THREAD

**Issue by uilianries** [bincrafters/community#495]
### Description of Problem, Request, or Question

https://github.com/bincrafters/conan-imagemagick

#### Requirements
- [x] Update libjpeg: https://github.com/bincrafters/conan-libjpeg/pull/5
- [X] Fix clang 6 build
- [x] Fix apple clang 10 build
- [x] Fix MSVC 12 build
- [x] Fix MSVC 14 build
- [x] Fix MSVC 15 build

**Comment by uilianries** [comment]
on windows only x86_64 jobs are failing:

https://ci.appveyor.com/project/BinCrafters/conan-imagemagick/builds/19627706

**Comment by Croydon** [comment]
I added Apple Clang 10 to lzma and created a pull request to add Apple Clang 10 to openexr https://github.com/conan-community/conan-openexr/pull/2

**Comment by uilianries** [comment]
Awesome! thanks @Croydon

**Comment by Croydon** [comment]
Freetype has also added Apple Clang 10 now (CI still running)

**Comment by SSE4** [comment]
finally done, thanks everyone!
