### ISSUE TITLE
Inclusion request for FFTW

### ISSUE THREAD

**Issue by h-ls** [bincrafters/community#496]
### Description of Request

I created a recipe for the [FFTW library](http://www.fftw.org) following your template and requirements and I would like to include it into the bincrafters repository. This could fulfill the following package request: https://github.com/conan-io/wishlist/issues/123

Recipe: https://github.com/hlysunnaram/conan-fftw
Travis CI: https://ci.appveyor.com/project/hlysunnaram/conan-fftw
AppVeyor: https://ci.appveyor.com/project/hlysunnaram/conan-fftw

Feel free to leave comments or report issues, I will be pleased to deal with them :-)

### Package Details
* Package Name/Version: **conan-fftw/3.3.8**

**Comment by SSE4** [comment]
I've created repository for you, and enabled CI, you should have an invitation

**Comment by hlysunnaram** [comment]
Great! Thanks for your responsivness!

I just noticed that the README badge URLs and links point to my personal repository. 
Is that ok if I update them without trigger a rebuild?

**Comment by Croydon** [comment]
Yes, please use our conan-readme-generator to do this

**Comment by SSE4** [comment]
@hlysunnaram in commit message please specify `[skip ci]` to avoid unnecessary builds
