### ISSUE TITLE
Create pull request for Fruit and get into Conan Center

### ISSUE THREAD

**Issue by Croydon** [bincrafters/community#499]
Google Fruit already has official Conan support, but the upload seems to happen manual right now. I will create a pull request upstream with CI additions, latest Conan conventions etc. and afterwards help them to get it into conan-center.

https://github.com/google/fruit/issues/72 
https://github.com/google/fruit/issues/93
https://github.com/google/fruit/issues/83

**Comment by uilianries** [comment]
Amazing!

**Comment by SSE4** [comment]
@Croydon issue seems to be closed in fruit bug tracker. is there anything else to be done?

**Comment by Croydon** [comment]
It isn't yet in conan-center and the upload isn't automated, so yes: https://github.com/google/fruit/issues/82

**Comment by SSE4** [comment]
@Croydon should we close this one now in favor of https://github.com/conan-io/conan-center-index?

**Comment by Croydon** [comment]
Yes
