### ISSUE TITLE
Installing libcurl as a shared library does not depend on the OpenSSL shared library on Linux

### ISSUE THREAD

**Issue by hanspacket** [bincrafters/community#501]
### Description of Problem

When libcurl is installed by conan as a shared library on linux, the downloaded package does not depend on the OpenSSL shared library, even when providing OpenSSL:shared=True as option.
- The resulting conaninfo.txt file includes OpenSSL:shared=False in the [full_options] section. Expected: OpenSSL:shared=True
- Calling ldd on the downloaded libcurl.so library does not list libssl.so / libcrypto.so (which I would expect)

The reason I have this expectations is because of /path/to/.conan/data/libcurl/7.61.1/bincrafters/stable/export/conanfile.py, which (among others) contains the following (line 79-82):

```
if self.options.with_openssl:
    # enforce shared linking due to openssl dependency
    if self.settings.os != "Macos" or not self.options.darwin_ssl:
        self.options["OpenSSL"].shared = self.options.shared
```
So my main question would be: is this a bug ? Or am I doing something wrong ? In that case, some guidance would be helpful.

Note: on Windows (Visual Studio), I don't have this problem.

### Package Details
* Package Name/Version: libcurl/7.61.1@bincrafters/stable + OpenSSL/1.0.2n@conan/stable
* Operating System: Linux Ubuntu 18.04
* Compiler+version: gcc-5.5.0

### Steps to reproduce

1) Call the following command:
```
conan install libcurl/7.61.1@bincrafters/stable -s build_type=Debug -o shared=True --build=libcurl
```

2) ldd /path/to/.conan/data/libcurl/7.61.1/bincrafters/stable/package/4ef57650ca71d5856c580f3fd5e99f29c7e8af96/lib/libcurl.so
Result:
```
        linux-vdso.so.1
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2
        /lib64/ld-linux-x86-64.so.2
```

Expected:
```
        linux-vdso.so.1
        libssl.so.x.x.x => /something/libssl.so.x.x.x
        libcrypto.so.x.x.x => /something/libcrypto.so.x.x.x
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f41634a0000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f41630a0000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f4162e90000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f4164200000)
```

3) Look at the contents of /path/to/.conan/data/libcurl/7.61.1/bincrafters/stable/package/4ef57650ca71d5856c580f3fd5e99f29c7e8af96/conaninfo.txt
Result:
```
...
[full_options]
    ...
    OpenSSL:shared=False
    ...
```
Expected:
```
...
[full_options]
    ...
    OpenSSL:shared=True
    ...
```

### Workaround

I was able to work around this issue by calling

```
conan install libcurl/7.61.1@bincrafters/stable -s build_type=Debug -o shared=True -o OpenSSL:shared=True --build=libcurl
```

This produces the results I expect. Within my build system, this is not a practical workaround though.

**Comment by theirix** [comment]
Thanks for the report. I have moved options setup for dependent packages to the `configure` method. It fixed a problem. Testing and merging soon.

**Comment by theirix** [comment]
While I had fixed the original problem, another problem reappeared (#524) that blocks using shared OpenSSL at least on newer macOS with SIP enabled.

**Comment by hanspacket** [comment]
I can confirm that your fix solves the problem for me.
Thanks !
