### ISSUE TITLE
Request for inclusion: tcl

### ISSUE THREAD

**Issue by madebr** [bincrafters/community#503]
### Description of Problem, Request, or Question
I would like to hand over my conan wrappers of tcl to bincrafters.
https://github.com/madebr/conan-tcl

### Package Details (Include if Applicable)
* Package Name/Version: **tcl/8.6.8**
* Operating System: **Windows** + **Linux** + **Macos**
* Compiler+version: **gcc** + **clang** + **mingw** + **Visual Studio**

Remark for the reviewers:
- when using mingw, I had to explicitly add the `z` library to the libs. Is this a bug in `zlib/1.2.11@conan/stable`?

appveyor logs: https://ci.appveyor.com/project/madebr/conan-tcl/builds/19801109
travis logs: https://travis-ci.org/madebr/conan-tcl/builds/446375671
bintray repo: https://bintray.com/madebr/maarten/tcl%3Amadebr

Kudos to @uilianries for pointing me to an example of nmake.

**Comment by Croydon** [comment]
Some notes for further recipes: 
  * recipes should have some meta information in them (like url, homepage, topics, author...), you can see all of them in our [conan-templates](https://github.com/bincrafters/conan-templates)
  * several pages in CI are only required when the build time exceeds the maximum time
  * please add a readme with our [conan-readme-generator](https://github.com/bincrafters/conan-readme-generator)
    * at least as soon as it is fixed #504
  * please always add a LICENSE.md file
  * if tools.get() is used there should be a `sha256` checksum used
  * the test_package seems quite heavy, it should make sure that the binaries/libs/headers are fine but nothing beyond that
    * also have you written them by yourself or copied somewhere?


I have created a repository and applied our conventions and gave you push rights. CI still needs to be enabled by someone else.

**Comment by madebr** [comment]
- I see you've already added the metadata, LICENSE.md and sha256 checksum
- I've used pages in CI because the error `The job exceeded the maximum log length, and has been terminated.` was thrown. See https://travis-ci.org/madebr/conan-tcl/builds/445918724
- I've managed to create a readme. I guess I should use the `stable` channel? Even though only the testing channel is present atm.
- The test_package is a modified version of https://wiki.tcl-lang.org/page/How+to+embed+Tcl+in+C+applications

**Comment by Croydon** [comment]
> I've used pages in CI because the error The job exceeded the maximum log length, and has been terminated. was thrown. See https://travis-ci.org/madebr/conan-tcl/builds/445918724

Ah, sorry. This maximum log issue is something I haven't have yet in mind. I heard that several Bincrafters recipes run into this recently. Maybe this is some new limit from Travis?

> I've managed to create a readme. I guess I should use the stable channel? Even though only the testing channel is present atm.

Yes, stable only is totally fine. It's too much work and noise to change it every time you merge something from testing to stable.

**Comment by Croydon** [comment]
https://bintray.com/bincrafters/public-conan/tcl%3Abincrafters 
https://github.com/bincrafters/conan-tcl

**Comment by Croydon** [comment]
@bincrafters/administrators If someone is familiar with mingw, could one please have a look at this mingw/zlib/z thing?

**Comment by madebr** [comment]
I just pushed testing/8.6.9.
I think the libz thing is resolved.
