### ISSUE TITLE
conan-readme-generator: Flexible badge adaption

### ISSUE THREAD

**Issue by Croydon** [bincrafters/community#508]
The readme generator should be able to:
  * display a Travis badge under the header **Linux & macOS**, pointing to the current branch  **-IF-** at the time of calling a `.travis.yml` file exists
  * display a AppVeyor badge under the header **Windows**, pointing to the current branch **-IF-** at the time of a calling a `appveyor.yml` file exists 
  * display a Azure Pipelines badge under the header **Linux & macOS** (shared table header if Travis and Azure exists), pointing to the current branch **-IF-** at the time of calling a `azure-pipelines.yml` file exists 
    * this is the new one, Travis & AppVeyor should get the new conditions however, as they might not be present on every repository with Azure in the mix now 
    * badge url: e.g. https://dev.azure.com/bincrafters/packages/_apis/build/status/bincrafters.conan-qt?branchName=stable/5.11.2 (branch name should be replaced with the information from the current conanfile reference)
     * https://dev.azure.com/bincrafters/packages/_apis/build/status/bincrafters.conan-[RECIPE NAME]?branchName=[BRANCH NAME]
      * there seems to be no way the badge can currently be linked in a more useful way then to the generic overview of ALL packages (https://dev.azure.com/bincrafters/packages/_build). While the badge API url has the speaking repository name in it, the Azure build page has some numeric ID which we can't know in the generator (something like https://dev.azure.com/bincrafters/packages/_build/latest?definitionId=7)

**Comment by Croydon** [comment]
Alright, then `show the Azure badge of the latest build` it is.

**Comment by DEGoodmanWilson** [comment]
Agreed, that kind of functionality could be very awesome…I'll see if I can figure out whose ear to whisper into 👂

**Comment by DEGoodmanWilson** [comment]
But while I agree that doing branch-specific things in Git can lead to weridness…the whole `target/version` branching structure is already pretty out there into unconventional territory. Maintaining a tree that is explicitly designed _not_ to be eventually merged down into a single release branch is already breaking branching conventions and will lead to weirdness and merge mistakes.

So, actually, I can see the sense of creating branch-specific READMEs with badges pointing to specific builds. It doesn't seem so foreign, once we have walked into the Bincrafters branch naming style.

But it does require a lot of diligence!

What might be better than direct badge support would be the ability to have variables defined—variables containin the repo owner, name, and current branch name, for instance! But now I'm really getting ahead of myself…

**Comment by solvingj** [comment]
Cool idea, no idea how that would work though :)

Its certainly true that our branching isn't consistent with one primary idiomatic use of GIT.  But, in terms of the vast array of ways people have leveraged GIT branches,  I wouldn't even call what we're doing uncommon.  I've seen similar strategies across a number of different ecosystems on Github, with really elaborate badge schemes for dealing with this problem.

**Comment by DEGoodmanWilson** [comment]
Oh, believe you me, I've done stranger things with branches. Indeed, I'm about to run a workshop on some unconventional uses for branches. So I'm a fan! I guess you might summarize my response above as: Bincrafters does something weird with branches: Embrace it 🤗

**Comment by Croydon** [comment]
Actually, I have to disagree with my former self. I think it is okay if we need to re-generate the readme once when we release a new version. In the future this should become a plugin so we automate this, for now it also has the benefit that the options etc. stay up to date as well. And the badges are way more helpful if they actually point to the current branch builds.

**Comment by Croydon** [comment]
Done https://github.com/bincrafters/conan-readme-generator/commit/9f64789a53c8c12015189bc3aa037c594bd61615
