### ISSUE TITLE
mongo-cxx-driver/3.2.0@bincrafters/stable build fails on Ubuntu

### ISSUE THREAD

**Issue by VioletGiraffe** [bincrafters/community#509]
* Package Name/Version: mongo-cxx-driver/3.2.0@bincrafters/stable
* Operating System: **Linux Ubuntu 18.10**
* Compiler+version: **gcc-8.1**

The error message is: 
`ERROR: Version range '~=1.2' from requirement 'zlib/[~=1.2]@conan/stable' required by 'mongo-c-driver/1.9.4@bincrafters/stable' could not be resolved`

**Comment by DEGoodmanWilson** [comment]
So, first thought is that `conan-center` is not in your remotes. Can you do `conan remote list`, and see if this is in the results:
```
conan-center: https://conan.bintray.com [Verify SSL: True]
```

**Comment by VioletGiraffe** [comment]
I've been told that to get anything done with Conan, one has to invoke `install` with `-r bincrafters`. Perhaps, that arguments overrides the default `conan-center` repo? Do I have to specify both repos when installing stuff?

**Comment by DEGoodmanWilson** [comment]
You should have both remotes listed, in fact. Here is an example on my machine:

```
$ /usr/local/bin/conan remote list
conan-center: https://conan.bintray.com [Verify SSL: True]
vthiery: https://api.bintray.com/conan/vthiery/conan-packages [Verify SSL: True]
degoodmanwilson: https://api.bintray.com/conan/degoodmanwilson/opensource [Verify SSL: True]
upload_repo: https://api.bintray.com/conan/bincrafters/opensource [Verify SSL: True]
bincrafters: https://api.bintray.com/conan/bincrafters/public-conan [Verify SSL: True]
```

As you can see I have added several remotes using `conan remote add`

**Comment by Croydon** [comment]
Based on the recommendation from the Conan team we don't want to use version ranges anyway (slow to resolve, non-reproducible builds...)

**Comment by Croydon** [comment]
@VioletGiraffe Please make sure that you have conan-center AND bincrafters in your remote list (`conan remote list`) and don't add `-r bincrafters` when invoking `install`. Conan will search through your remotes and will find our packages just fine.

**Comment by VioletGiraffe** [comment]
@Croydon : thanks for the tips, but I was doing just that, and it didn't work, at which point an experienced Conan user told me to use `-r`. I would experiment with it again, but right now I can't even install Conan on Ubuntu (or, rather, can't use it after installing because it doesn't get registered system wide). True open-source experience.

**Comment by Croydon** [comment]
Are you installing it via pip? If not, you should try this. It is the recommend and most stable way.

**Comment by VioletGiraffe** [comment]
@Croydon: yes, of course, `pip install conan`, as recommended by the official manual. I understand this is out of scope of this discussion, guess I'm just grumpy. Don't mind me.
