### ISSUE TITLE
conan-libjpeg_turbo - Troubleshoot mingw builds

### ISSUE THREAD

**Issue by solvingj** [bincrafters/community#51]
In applying the new standard builds for windows to `appveyor.yml`, the MinGW build is failing.  It would be great if someone can claim and troubleshoot the issue. 

https://ci.appveyor.com/project/BinCrafters/conan-libjpeg-turbo

**Comment by SSE4** [comment]
build seems to be green already

**Comment by theirix** [comment]
I updated it yesterday, works fine.
