### ISSUE TITLE
boost_asio Failed requirement 'bzip2/1.0.6@conan/stable'

### ISSUE THREAD

**Issue by babysitter** [bincrafters/community#510]
Hi, guys, thank you for keeping up good job!
I am really new to Conan, wanted to play around with Boost::asio and decided to try out this promising technology, but I'm stuck and not sure what am I doing wrong. Never mind, let's get down to business.

this is my sample `conanfile.txt` (also tried 1.66.0:stable and 1.65.1:stable)
```
[requires]
boost_asio/1.67.0@bincrafters/testing

[generators]
cmake

[options]
Boost:shared=False
```
I'm trying to install dependancies using this profile:
```
[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=9.1
```
with (sometimes with `--build --update` just in case)
`conan install .. -pr=./mac_test_profile`

after plenty of successful messages I'm getting following error:
```
bzip2/1.0.6@conan/stable: Trying with 'bintray'...
ERROR: Failed requirement 'bzip2/1.0.6@conan/stable' from 'boost_iostreams/1.67.0@bincrafters/testing'
ERROR: Unable to find 'bzip2/1.0.6@conan/stable' in remotes
```
googled a lot, any help appreciated!

### Package Details
* Package Name/Version: **boost_asio/1.67.0@bincrafters/testing**
* Operating System: **macOS 10.13.6 High Sierra**
* Compiler+version: **apple-clang 9.1.0**

https://bintray.com/bincrafters/public-conan/boost_asio%3Abincrafters

**Comment by Croydon** [comment]
Can you please post the output of `conan remote list`?

**Comment by babysitter** [comment]
@Croydon `bintray: https://api.bintray.com/conan/bincrafters/public-conan [Verify SSL: True]`

**Comment by Croydon** [comment]
You are missing conan-center which is the official, moderated, central conan repository. Conan-center is default in all new Conan installations, but I believe didn't get installed when updated from a pre-1.0 release. Or for some reason you deleted it manually?

Please execute `conan remote add conan-center https://api.bintray.com/conan/conan/conan-center --insert`

**Comment by babysitter** [comment]
looking good so far, thank you. that wasn't obvious to me at all for some reason. sorry for wasting your time.

**Comment by Croydon** [comment]
Your welcome :)
