### ISSUE TITLE
sdl2 package's conanfile.py lists incorrect license

### ISSUE THREAD

**Issue by DavidLudwig** [bincrafters/community#515]
### Description of Problem, Request, or Question
The conanfile.py for sdl2 lists the wrong license.  LibSDL2's license is zlib, however this file lists it as being under "LGPL-2.1".

A copy of SDL2's zlib-based license can be found at http://www.libsdl.org/license.php

For reference, SDL 1.x had been licensed under the LGPL, however its license changed to ZLib's for SDL 2.x.

### Package Details (Include if Applicable)
* Package Name/Version: **sdl2/2.0.8**

**Comment by Croydon** [comment]
Thanks for reporting! I will fix this

**Comment by Croydon** [comment]
Done in testing branch, merging into stable as soon as CI finishes.

https://github.com/bincrafters/conan-sdl2/pull/14
