### ISSUE TITLE
[package tools] Bug: We are uploading testing packages

### ISSUE THREAD

**Issue by Croydon** [bincrafters/community#518]
I just noticed that we are uploading testing packages from all repositories. Seems like something broke recently which prevented this so far. We should fix this as soon as possible as this is a huge waste of resources.

**Comment by uilianries** [comment]
I'll check soon

**Comment by uilianries** [comment]
Done!

Bincrafters Package Tools 0.17.4 Released!

https://pypi.org/project/bincrafters-package-tools/0.17.4/
