### ISSUE TITLE
conan-botan - Troubleshoot CI issues 

### ISSUE THREAD

**Issue by solvingj** [bincrafters/community#52]
In applying the new standard builds to appveyor.yml and travis.yml, the MinGW builds on appveyor and some of the GCC builds on travis are failing. It would be great if someone can claim and troubleshoot the issues.

https://ci.appveyor.com/project/BinCrafters/conan-botan
https://travis-ci.org/bincrafters/conan-botan

**Comment by solvingj** [comment]
Turns out appveyor and MinGW are fine, it was an upload failure. 

There does seem to be a problem with GCC but on 2.1.0.  Testing that again now.

**Comment by solvingj** [comment]
Still broken, still needs a look:

**Comment by SSE4** [comment]
build is fixed, merged to stable
