### ISSUE TITLE
Unable to link sfml using Cmake and Conan

### ISSUE THREAD

**Issue by ZodiacFRA** [bincrafters/community#521]
**### Description of Problem**
When building my C++ project I get:
`/usr/bin/ld: CMakeFiles/r-type_client.dir/NetworkManager/TcpManager/TcpManager.cpp.o:`
`in function rtype::TcpManager::TcpManager():`
`TcpManager.cpp:(.text+0x24): undefined reference to sf::TcpSocket::TcpSocket()`
and other errors of the same type, concerning calls to SFML's functions or types

**### Package Details**
* Package Name/Version: **sfml/2.5.1@bincrafters/stable**
* Operating System: **Fedora 29**
* Compiler+version: **CXX GNU-8.2.1**

**### Steps to reproduce**
I have the following conanfile.txt at the projet's root:
`[requires]`
`sfml/2.5.1@bincrafters/stable`
`[generators]`
`cmake`

And here is my first CMakeLists.txt:
`cmake_minimum_required (VERSION 3.11.2)`
`PROJECT(RType)`
`include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)`
`conan_basic_setup()`
`subdirs(client)`

which calls the second one:
`set(CLIENT_DIR ${CMAKE_CURRENT_SOURCE_DIR})`
`set(CLIENT_SRCS`
`	${CLIENT_DIR}/main.cpp`
`	${CLIENT_DIR}/Errors/RtypeErrors.cpp`
`	${CLIENT_DIR}/Client/Client.cpp`
`	${CLIENT_DIR}/NetworkManager/NetworkManager.cpp`
`	${CLIENT_DIR}/NetworkManager/TcpManager/TcpManager.cpp`
`	${CLIENT_DIR}/NetworkManager/UdpManager/UdpManager.cpp)`
`add_executable(r-type_client ${CLIENT_SRCS})`

`set_target_properties(r-type_client PROPERTIES`
`	LINKER_LANGUAGE CXX`
`	RUNTIME_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR})`

`target_link_libraries(r-type_client ${CONAN_LIBS})`

`target_include_directories(r-type_client PUBLIC`
`	${CLIENT_DIR}/Client`
`	${CLIENT_DIR}/Errors`
`	${CLIENT_DIR}/NetworkManager`
`	${CLIENT_DIR}/NetworkManager/TcpManager`
`	${CLIENT_DIR}/NetworkManager/UdpManager)`

I've already tried the conan's target approach:
`target_link_libraries(r-type_client CONAN_PKG::sfml)`
using the `conan_basic_setup(TARGETS)` first but it's not working either.

The `findPackage` CMake method is not working, since i don't know SFML paths.

If you have any ideas please let me know
Thanks for taking the time to read, Have a nice day!

**Comment by uilianries** [comment]
Hi @ZodiacFRA !

Thanks for reporting, we will investigate.

**Comment by ZodiacFRA** [comment]
thanks :)
**I'll add a few more details:**
The problem happens only at LINK time, I do not have errors like 
`#include <SFML/Network.hpp> not found`

and **here is the full build failure output:**
`[100%] Linking CXX executable ../../r-type_client`
 `-----------------------`
`/usr/bin/ld: CMakeFiles/r-type_client.dir/NetworkManager/TcpManager/TcpManager.cpp.o:`
**`in function rtype::TcpManager::TcpManager()':`**
`TcpManager.cpp:(.text+0x24):` **`undefined reference to sf::TcpSocket::TcpSocket()'`**
`------------------------`
`/usr/bin/ld: CMakeFiles/r-type_client.dir/NetworkManager/TcpManager/TcpManager.cpp.o:`
**`in function rtype::TcpManager::connect`**`(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)':`
`TcpManager.cpp:(.text+0xb7): `**`undefined reference to sf::IpAddress::IpAddress`**
`(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'`
`------------------------`
`/usr/bin/ld: `**`TcpManager.cpp:(.text+0xcf): undefined reference to sf::TcpSocket::connect`**
`(sf::IpAddress const&, unsigned short, sf::Time)'`
`------------------------`
`/usr/bin/ld: CMakeFiles/r-type_client.dir/NetworkManager/TcpManager/TcpManager.cpp.o:`
`(.rodata._ZTIN2sf9TcpSocketE[_ZTIN2sf9TcpSocketE]+0x10): undefined reference to typeinfo for sf::Socket'`                                  **I don't understand this one**
`------------------------`
`/usr/bin/ld: CMakeFiles/r-type_client.dir/NetworkManager/TcpManager/TcpManager.cpp.o:`
**`in function sf::TcpSocket::~TcpSocket()':`**
`TcpManager.cpp:(.text._ZN2sf9TcpSocketD2Ev[_ZN2sf9TcpSocketD5Ev]+0x30): `
**`undefined reference to sf::Socket::~Socket()'`**
`------------------------`
`collect2: error: ld returned 1 exit status`
`gmake[2]: *** [client/CMakeFiles/r-type_client.dir/build.make:160: ../r-type_client] Error 1`
`gmake[1]: *** [CMakeFiles/Makefile2:91: client/CMakeFiles/r-type_client.dir/all] Error 2`
`gmake: *** [Makefile:84: all] Error 2`

Hope this helps (I've added the - separators for legibility purposes)
Have a nice day

**Comment by ZodiacFRA** [comment]
Okay I figured it out you can close the issue :)
I needed the 
`[options]`
`sfml:network=True`

(I didn't need any of that when i used other conan's packages, so I did not know that was a thing)

Thanks again!

**Comment by uilianries** [comment]
Nice! Thanks for sharing!
