### ISSUE TITLE
Update Sqlite3

### ISSUE THREAD

**Issue by barcharcraz** [bincrafters/community#522]
Sqlite3 3.25 is a huge release and includes support for window functions!

**Comment by uilianries** [comment]
new branch created:
https://github.com/bincrafters/conan-sqlite3/tree/testing/3.25.3

Lets wait for CI result for promotion on stable channel.

**Comment by uilianries** [comment]
Done!

![sqlite3/3.25.3@bincrafters/stable](https://screenshotscdn.firefoxusercontent.com/images/df05be14-72ec-4e8a-a0fa-e0dd955d4527.png)
