### ISSUE TITLE
Qt builds not finding SVG includes

### ISSUE THREAD

**Issue by ShamanTcler** [bincrafters/community#523]
Win 10 64
MSVS 2015 
Conan version 1.9.1
cmake version 3.12.3
Qt 5.9.7
Qwt 6.1.3 ( https://sourceforge.net/projects/qwt/files/qwt/6.1.3/  )

Trying to build a static lib version of Qwt. Qwt uses a few Qt "extras" so:

find_package(Qt5 COMPONENTS Concurrent Core OpenGL PrintSupport svg Widgets CONFIG REQUIRED)

Is necessary. By the way this is not s std. build for you, but you downloaded the sources and compiled it like a champ ... thank you, thank you.

In my CMakelist.txt I try and do a sanity check:

if( Qt5PrintSupport_FOUND )
   MESSAGE(STATUS "Found Qt5PrintSupport!")
   MESSAGE(STATUS "Qt5PrintSupport includes:" ${Qt5PrintSupport_INCLUDE_DIRS})
endif( Qt5PrintSupport_FOUND )

if( Qt5svg_FOUND )
   MESSAGE(STATUS "Found Qt5SVG!")
   MESSAGE(STATUS "Qt5SVG includes:" ${Qt5SVG_INCLUDE_DIRS})
endif( Qt5svg_FOUND )

if( Qt5Concurrent_FOUND )
   MESSAGE(STATUS "Found Qt5Concurrent!")
   MESSAGE(STATUS "Qt5Concurrent includes:" ${Qt5Concurrent_INCLUDE_DIRS})
endif( Qt5Concurrent_FOUND )

This produces: 
-- Found Qt5PrintSupport!
-- Qt5PrintSupport includes:D:/Users/210008258/.conan/data/Qt/5.9.7/bincrafters/stable/package/c6db5599f857eaff5502ecaa870c3258c1121ae3/include/D:/Users/210008258/.conan/data/Qt/5.9.7/bincrafters/stable/package/c6db5599f857eaff5502ecaa870c3258c1121ae3/include/QtPrintSupportD:/Users/210008258/.conan/data/Qt/5.9.7/bincrafters/stable/package/c6db5599f857eaff5502ecaa870c3258c1121ae3/include/QtWidgetsD:/Users/210008258/.conan/data/Qt/5.9.7/bincrafters/stable/package/c6db5599f857eaff5502ecaa870c3258c1121ae3/include/QtGuiD:/Users/210008258/.conan/data/Qt/5.9.7/bincrafters/stable/package/c6db5599f857eaff5502ecaa870c3258c1121ae3/include/QtCoreD:/Users/210008258/.conan/data/Qt/5.9.7/bincrafters/stable/package/c6db5599f857eaff5502ecaa870c3258c1121ae3/.//mkspecs/win32-msvc
-- Found Qt5SVG!
-- Qt5SVG includes:        **<- NOTHING HERE!** 
-- Found Qt5Concurrent!
-- Qt5Concurrent includes:D:/Users/210008258/.conan/data/Qt/5.9.7/bincrafters/stable/package/c6db5599f857eaff5502ecaa870c3258c1121ae3/include/D:/Users/210008258/.conan/data/Qt/5.9.7/bincrafters/stable/package/c6db5599f857eaff5502ecaa870c3258c1121ae3/include/QtConcurrentD:/Users/210008258/.conan/data/Qt/5.9.7/bincrafters/stable/package/c6db5599f857eaff5502ecaa870c3258c1121ae3/include/QtCoreD:/Users/210008258/.conan/data/Qt/5.9.7/bincrafters/stable/package/c6db5599f857eaff5502ecaa870c3258c1121ae3/.//mkspecs/win32-msvc

So somehow SVG is falling through the cracks

My primitive approach to this is to download qwt zip, unpack then add these files, in the qwt-6.1.3 dir.

[CMakeLists.txt](https://github.com/bincrafters/community/files/2566001/CMakeLists.txt)
[conanfile.txt](https://github.com/bincrafters/community/files/2566002/conanfile.txt)

Then I have a little bat file: (yes it is slow but does a clean build each time)
     rm -r build
     mkdir build
     cd build
     conan install .. --build missing -s build_type=Release
     cmake .. -G Ninja  -DCMAKE_BUILD_TYPE=Release
     ninja
     cd ..

The compile error is:
C:\PROGRA~2\MICROS~2.0\VC\bin\amd64\cl.exe  /nologo /TP -DQT_CONCURRENT_LIB -DQT_CORE_LIB
 -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -I.
 -I..\ -IProject_autogen\include -I..\src 
 -ID:\Users\myID\.conan\data\Qt\5.9.7\bincrafters\stable\package\c6db5599f857eaff5502ecaa870c3258c1121ae3\include 
 -ID:\Users\myID\.conan\data\Qt\5.9.7\bincrafters\stable\package\c6db5599f857eaff5502ecaa870c3258c1121ae3\include\QtConcurrent 
 -ID:\Users\myID\.conan\data\Qt\5.9.7\bincrafters\stable\package\c6db5599f857eaff5502ecaa870c3258c1121ae3\include\QtCore 
 -ID:\Users\myID\.conan\data\Qt\5.9.7\bincrafters\stable\package\c6db5599f857eaff5502ecaa870c3258c1121ae3\.\mkspecs\win32-msvc 
 -ID:\Users\myID\.conan\data\Qt\5.9.7\bincrafters\stable\package\c6db5599f857eaff5502ecaa870c3258c1121ae3\include\QtOpenGL 
 -ID:\Users\myID\.conan\data\Qt\5.9.7\bincrafters\stable\package\c6db5599f857eaff5502ecaa870c3258c1121ae3\include\QtWidgets 
 -ID:\Users\myID\.conan\data\Qt\5.9.7\bincrafters\stable\package\c6db5599f857eaff5502ecaa870c3258c1121ae3\include\QtGui 
 -ID:\Users\myID\.conan\data\Qt\5.9.7\bincrafters\stable\package\c6db5599f857eaff5502ecaa870c3258c1121ae3\include\QtPrintSupport
 /DWIN32 /D_WINDOWS /W3 /GR /EHsc   /MD /O2 /Ob2 /DNDEBUG /showIncludes /FoCMakeFiles\Project.dir\src\qwt_plot_svgitem.cpp.obj
 /FdCMakeFiles\Project.dir\Project.pdb /FS -c ..\src\qwt_plot_svgitem.cpp
..\src\qwt_plot_svgitem.cpp(14): fatal error C1083: **Cannot open include file: 'qsvgrenderer.h':** No such file or directory

So yup the svg dir is not being included.

Thanks for looking into it.

**Comment by ericLemanissier** [comment]
Can you please force rebuild of qt and paste the log corresponding to conan install ?

**Comment by ShamanTcler** [comment]
Note:
-The include dirs exist in the Conan data dir 
- Debug was built first then release

[qt_debug_conan.log](https://github.com/bincrafters/community/files/2573026/qt_debug_conan.log)
[qt_release_conan.log](https://github.com/bincrafters/community/files/2573027/qt_release_conan.log)

**Comment by ShamanTcler** [comment]
Eric:

          I do NOT claim to be a CMake expert, but I think I have it right.

          These three snippets:
 
_if( Qt5PrintSupport_FOUND )
MESSAGE(STATUS "Found Qt5PrintSupport!")
MESSAGE(STATUS "Qt5PrintSupport includes:" ${Qt5PrintSupport_INCLUDE_DIRS})
endif( Qt5PrintSupport_FOUND )

if( Qt5svg_FOUND )
MESSAGE(STATUS "Found Qt5SVG!")
MESSAGE(STATUS "Qt5SVG includes:" ${Qt5SVG_INCLUDE_DIRS})
endif( Qt5svg_FOUND )

if( Qt5Concurrent_FOUND )
MESSAGE(STATUS "Found Qt5Concurrent!")
MESSAGE(STATUS "Qt5Concurrent includes:" ${Qt5Concurrent_INCLUDE_DIRS})
endif( Qt5Concurrent_FOUND )_

Now the results of these snippets are: 

_-- Found Qt5PrintSupport!
-- Qt5PrintSupport includes:D:/Users/210008258/.conan/data/Qt/5.9.7/bincrafters/stable/package/c6db5599f857eaff5502ecaa870c3258c1121ae3/include/D:/Users/210008258/.conan/data/Qt/5.9.7/bincrafters/stable/package/c6db5599f857eaff5502ecaa870c3258c1121ae3/include/QtPrintSupportD:/Users/210008258/.conan/data/Qt/5.9.7/bincrafters/stable/package/c6db5599f857eaff5502ecaa870c3258c1121ae3/include/QtWidgetsD:/Users/210008258/.conan/data/Qt/5.9.7/bincrafters/stable/package/c6db5599f857eaff5502ecaa870c3258c1121ae3/include/QtGuiD:/Users/210008258/.conan/data/Qt/5.9.7/bincrafters/stable/package/c6db5599f857eaff5502ecaa870c3258c1121ae3/include/QtCoreD:/Users/210008258/.conan/data/Qt/5.9.7/bincrafters/stable/package/c6db5599f857eaff5502ecaa870c3258c1121ae3/.//mkspecs/win32-msvc
-- Found Qt5SVG!
-- Qt5SVG includes: <- **NOTHING HERE**!
-- Found Qt5Concurrent!
-- Qt5Concurrent includes:D:/Users/210008258/.conan/data/Qt/5.9.7/bincrafters/stable/package/c6db5599f857eaff5502ecaa870c3258c1121ae3/include/D:/Users/210008258/.conan/data/Qt/5.9.7/bincrafters/stable/package/c6db5599f857eaff5502ecaa870c3258c1121ae3/include/QtConcurrentD:/Users/210008258/.conan/data/Qt/5.9.7/bincrafters/stable/package/c6db5599f857eaff5502ecaa870c3258c1121ae3/include/QtCoreD:/Users/210008258/.conan/data/Qt/5.9.7/bincrafters/stable/package/c6db5599f857eaff5502ecaa870c3258c1121ae3/.//mkspecs/win32-msvc_


So you can see Qt5SVG is being found so spelling should not be an issue ... in my mind.

What I don't know is how Conan sets those variables. Should I copy this over to Conan?

**Comment by ericLemanissier** [comment]
let me insist. On my local distribution of Qt, I can see inside various Qt5Svg*.cmake that Qt5Svg is always written `Qt5Svg`, never `Qt5SVG` nor `Qt5svg`.

**Comment by ShamanTcler** [comment]
Ok fair enough, let me give it a shot

**Comment by ShamanTcler** [comment]
My deepest apologies.

Changing to:

if( Qt5Svg_FOUND )
   MESSAGE(STATUS "Found Qt5Svg!")
   MESSAGE(STATUS "Qt5SVG includes:" ${Qt5Svg_INCLUDE_DIRS})
endif( Qt5svg_FOUND )

CMake no longer finds  Qt5Svg_FOUND to be true, but the darn thing works.

I **was** able the build the qwt library.

I still think things are a bit "off" here as the CMake debugging approach of "*_FOUND" being true and then dumping the value seems pretty routine.

Again sorry I just didn't try your suggestion, it worked.

**Comment by ericLemanissier** [comment]
No Problem. You should also put a capital S on svg in your `find_package` call. I think this is why `Qt5svg_FOUND` is set, but not `Qt5Svg_FOUND`
