### ISSUE TITLE
libcurl: configure problem with shared dependencies

### ISSUE THREAD

**Issue by theirix** [bincrafters/community#524]
The problem with shared OpenSSL still persists. Autotools helper does not call `conanfile.run` with a `run_environment` parameter which is the only way to overcome macOS dyld env variables strip.

I'll fill a PR to Conan later.

### Package Details (Include if Applicable)
* Package Name/Version: **libcurl/7.61.1**
* Operating System: **macOS 10.13**
* Compiler+version: **apple-clang 10**

### Steps to reproduce (Include if Applicable)

```sh
conan create -o libcurl:shared=True -o libcurl:darwin_ssl=False --build=libcurl . theirix/testing
```

**Comment by theirix** [comment]
Unfortunately, `run_environment` parameter does not help to fix configure scripts. So we copy shared libraries from dependencies to the build directory.

**Comment by solvingj** [comment]
You mean it can’t ever do it, or it doesn’t do it currently and Conan team has a ticket?

**Comment by theirix** [comment]
@solvingj here is the solution - https://github.com/conan-io/conan/issues/3929#issuecomment-439416699 . Not very obvious.
