### ISSUE TITLE
C2440 while building boost_python/1.65.1

### ISSUE THREAD

**Issue by HughLo** [bincrafters/community#525]
### Description of Problem, Request, or Question
Build error while building boost_python/1.65.1

### Package Details (Include if Applicable)
* Package Name/Version: **boost_python/1.65.1**
* Operating System: **Win 10**
* Compiler+version: **vc15.8.9**
* Docker image: **none**

### Steps to reproduce (Include if Applicable)
Just type the command 
``` ps
conan install boost_python/1.65.1@bincrafters/stable --build missing
```
The error reported by Conan is:
boost_python/1.65.1@bincrafters/stable: ERROR: Package '12f473e54e00049ac1c764cc8445756b0dd81945' build failed
boost_python/1.65.1@bincrafters/stable: WARN: Build folder C:\.conan\wc2ngljs\1
ERROR: boost_python/1.65.1@bincrafters/stable: Error in build() method, line 135
        boost_package_tools.build(self)
        ConanException: Error 1 while executing b2 -j4 -a --hash=yes --debug-configuration --layout=system  include=graph/include include=multi_index/include include=parameter/include include=property_map/include include=serialization/include include=unordered/include python-build

I think the root of this error message is a compiling error in the log:
python\src\converter\builtin_converters.cpp(51): error C2440: “return”: cannot convert from “const char *” to “void *”

Can anybody help me with this?

**Comment by SSE4** [comment]
hi @HughLo 
have you tried newer boost versions?

**Comment by Croydon** [comment]
No feedback in a long time. Closing
