### ISSUE TITLE
Make Qt package name lowercase

### ISSUE THREAD

**Issue by Croydon** [bincrafters/community#529]
Qt isn't yet in conan-center. We should take this opportunity to change the name to `qt` before we are committing to a stability promise. 

It would be kinda stupid to continue with the uppercase name, even though we had a change in convention a long time ago to use only lowercase package names.

**Comment by melMass** [comment]
@Croydon Not sure if it's relevant (I haven't read much about conan conventions yet), but I like the fact that conan is case sensitive, especially for searches.

**Comment by Croydon** [comment]
@ericLemanissier IIRC you asked once if we can remove old versions. I see this as pretty much the last chance where we could chop of old version from Bintray (indirectly, by not uploading them anymore with the new lowercase name). What do you think? I would suggest to wait for the 5.12.0 release and then making this naming switch.

/remind me in 16 days that Qt 5.12.0 is released

**Comment by ericLemanissier** [comment]
Yes, I'll first make it so that starting with Qt 5.12.0, azure pipelines are used and qt package name is lowercase

**Comment by Croydon** [comment]
> @Croydon Not sure if it's relevant (I haven't read much about conan conventions yet), but I like the fact that conan is case sensitive, especially for searches.

@melMass Yes, but also making it lower case doesn't take the case sensitivity away. It became a convention for Bincrafters and conan-community to use only lower case names as it is much user-friendly to not need to figure out the right cases. Also people on Windows (which is case insensitive) might just use a random case version of names and it will work fine on Windows but break on Linux/macOS. Having the lower case conventions just makes life easier for everyone.

**Comment by ericLemanissier** [comment]
changed in Qt 5.11.3 and later releases with https://github.com/bincrafters/conan-qt/commit/8e7f9baa553920bec02a19af076d0b8260fa12b4
