### ISSUE TITLE
GitHub Issues: Create different templates

### ISSUE THREAD

**Issue by Croydon** [bincrafters/community#531]
For:
  * bugs
  * feature request
  * upstream updates 
   * package inclusion requests
   * general discussions and questions about conventions and methods

**Comment by SSE4** [comment]
@Croydon I've added some initial templates, feel free to modify them: https://github.com/bincrafters/community/tree/master/.github/ISSUE_TEMPLATE
P.S. this repository might be useful as source of examples: https://github.com/stevemao/github-issue-templates
