### ISSUE TITLE
No dll files for sdl2 and sdl2_image

### ISSUE THREAD

**Issue by Ansoulom** [bincrafters/community#532]
### Description of Problem, Request, or Question
No dll files get installed when building sdl2 nor sdl2_image on Windows. sdl2_ttf have them though.
There seemed to be a similar closed issue: [https://github.com/bincrafters/community/issues/55](https://github.com/bincrafters/community/issues/55)
I want to install the binaries in my build location, so that I can directly run my executable, like so:
```
[imports]
bin, *.dll -> ./bin
```
This seems to work without a problem for sdl2_ttf, but not for the other two sdl2 libraries.
This is the command I run:
`conan install .. -s compiler="Visual Studio" -s compiler.version=15 --build missing`
I'm building for x86_64. I haven't done anything else special.

### Package Details
* Package Name/Version: **sdl2/2.0.9 and sdl2_image/2.0.3**
* Operating System: **Windows 10**
* Compiler+version: **msvc-15.0**

**Comment by Croydon** [comment]
There are only dll files if you make a shared build of the packages which is not default.

You need to make it explicit, e.g.: `conan create . bincrafters/stable -o sdl2:shared=True`

**Comment by Ansoulom** [comment]
Oh I see, thanks for telling me! It just felt a bit strange that the sdl2 and sdl2_image packages were inconsistent with sdl2_ttf, as that one produced dll files without me having to specify anything.
