### ISSUE TITLE
conan-spdlog doesn't define SPDLOG_FMT_EXTERNAL when using the cmake_paths generator

### ISSUE THREAD

**Issue by Quincunx271** [bincrafters/community#533]
Upstream issue: https://github.com/gabime/spdlog/issues/904

I spent the last few days tracking down a segfault which turned out to be an ODR violation because I was using both spdlog and fmt without `-DSPDLOG_FMT_EXTERNAL`. If I was using the `cmake` generator, the conan-spdlog package would have set that for me. However, I was using `cmake_paths` (or rather, I was using `conan_set_find_paths()`). It would be nice if we could do something to make it harder to run into this bug.

For instance, we could patch the `spdlogConfig.cmake` to make the `spdlog::spdlog` package set `SPDLOG_FMT_EXTERNAL` if the `fmt_external` option is set.

**Comment by Quincunx271** [comment]
> As FMT_EXTERNAL is defined in config file we would need to distribute multiple packages and this is not our concern about spdlog.

I don't understand this sentence, specifically the "this is not our concern about spdlog." I think you are saying that we don't want to distribute multiple spdlog packages. Why is distributing multiple packages bad?

**Comment by uilianries** [comment]
exactly, we would need to change spdlogConfig.cmake and each file will be different according `fmt_external` option, and as spdlog uses an unique package id this wouldn't work. The only way to handle this is to create new package IDs based on the options.

however, using cmake generator or cmake_find_package are enough for this to work.

**Comment by Quincunx271** [comment]
Yes, using the cmake generator is enough for this to work. My intent was to make this error harder to fall into when using the cmake_paths generator. I don't understand what's bad about creating a new package ID based on the options.

Come to think of it, is there any reason to have `fmt_external` set to `False`? I can't imagine it would change reasonable code. I guess someone could have `#ifndef SPDLOG_FMT_EXTERNAL`, but I don't particularly care about breaking them. I believe the point of upstream spdlog having this option is to make it easier to use (you don't have to set up fmt as well), but conan-spdlog works with conan, a package manager which can easily set up fmt.

**Comment by solvingj** [comment]
Ping @SSE4 , thoughts on removing option and making default for conan?

**Comment by SSE4** [comment]
@solvingj unfortunately, I am not very familiar with spdlog project, as I've never used it before
studying the doc (https://github.com/gabime/spdlog/wiki/8.-Tweaking), my understanding that it may use either its own copy of `fmt` library, or external one, and `SPDLOG_FMT_EXTERNAL` controls exactly that usage.
this clearly introduces different package ids, as CMake config files will be different, so we should do one of the following:
- remove `header_only` from the recipe
- remove `fmt_external` option althogether and always require external fmt installation
I personally vote for the second approach, as it make things more simple.
probably, it makes recipe a bit less flexible (as it removes an option to use embedded fmt installation), but for me personally embedded fmt not very transparent (read - not clear which fmt version is in use), and I'd prefer to control fmt version via conan. if you need another version - you always can override it in `conanfile.txt`, right?

**Comment by SSE4** [comment]
okay, there were no replies for 20 days, so I am removing `fmt_external` option then

**Comment by SSE4** [comment]
@Quincunx271 applied changes to 1.1.0 and 1.2.1 branches, please give a try

**Comment by tarunbelagodu** [comment]
why was it removed from older releases?

**Comment by tarunbelagodu** [comment]
also, I am not too familiar with the purpose of fmt_external. Our build system set it to False. Is there a different recipe we should follow or is it no longer required entirely?

**Comment by Quincunx271** [comment]
@tarunbelagodu You should be able to remove it entirely. The purpose of `fmt_external` was just to use spdlog's embedded fmt if `fmt_external=False`, but since conan is a package manager, it can just supply us with fmt automatically.

**Comment by Quincunx271** [comment]
Although I have responded, I actually forgot to test this yet. I'll try to remember to test this tomorrow

**Comment by tarunbelagodu** [comment]
> @tarunbelagodu You should be able to remove it entirely. The purpose of `fmt_external` was just to use spdlog's embedded fmt if `fmt_external=False`, but since conan is a package manager, it can just supply us with fmt automatically.

Thanks for the feedback

**Comment by Quincunx271** [comment]
I had a chance to look at the changes.

It looks to me like this change doesn't affect the original issue. There is no `-DSPDLOG_FMT_EXTERNAL` in my build flags when using `find_package(spdlog)` and `spdlog::spdlog` rather than `CONAN_PKG::spdlog`, so the original ODR violation is still just as easy to fall into.

One option would be to edit the spdlogConfig.cmake file:

```cmake
set_target_properties(spdlog::spdlog PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  # Add the following line:
  INTERFACE_COMPILE_DEFINITIONS "SPDLOG_FMT_EXTERNAL"
)
```

**Comment by SSE4** [comment]
@Quincunx271 this is weird, as `conanfile.py` adds definition unconditionally now:
https://github.com/bincrafters/conan-spdlog/blob/stable/1.2.1/conanfile.py#L48

**Comment by Quincunx271** [comment]
@SSE4 I believe that `self.cpp_info` has no effect on the `cmake_paths` generator, because with `cmake_paths`, you are using `find_package(PackageName)` to get the package, not `CONAN_PKG::PackageName`. So CMake only uses the `PackageNameConfig.cmake` file, thus doesn't see anything in `self.cpp_info`.

**Comment by SSE4** [comment]
@Quincunx271 this seems to be unavoidable issue, what do you think should we do about it?

**Comment by Quincunx271** [comment]
@SSE4 I believe it is avoidable if we edit the spdlogConfig.cmake file in the install step to have `SPDLOG_FMT_EXTERNAL` by default. Is that possible?

**Comment by SSE4** [comment]
yeas, I think so

**Comment by SSE4** [comment]
@Quincunx271 I've applied required changes, please give an another try

**Comment by uilianries** [comment]
Thanks @SSE4 💪

**Comment by Quincunx271** [comment]
@SSE4 Looks good to me. Thanks!

**Comment by SSE4** [comment]
@Quincunx271 okay, I am closing the issue then
