### ISSUE TITLE
sdl2_ttf/2.0.14 fails on Windows/Visual Studio

### ISSUE THREAD

**Issue by Croydon** [bincrafters/community#535]
> ERROR: sdl2_ttf/2.0.14@bincrafters/stable: Error in build() method, line 65
        self.build_with_vs()
while calling 'build_with_vs', line 78
        toolset=self.settings.compiler.toolset)
        ConanException: Error 1 while executing set "VSCMD_START_DIR=%CD%" && call "E:\Program Files\x86\Microsoft Visual Studio\2017\Community\VC/Auxiliary/Build/vcvarsall.bat" amd64 && devenv "SDL2_ttf-2.0.14\VisualC\SDL_ttf.sln" /upgrade && msbuild "SDL2_ttf-2.0.14\VisualC\SDL_ttf.sln" /p:Configuration="Release" /p:UseEnv=true /p:Platform="x64" /m:8 /p:ForceImportBeforeCppTargets="C:\Users\Micha\AppData\Local\Temp\tmpzblbys08tmp_conan\t

Any ideas @elizagamedev?

**Comment by Croydon** [comment]
> Configuration:
[settings]
arch=x86_64
build_type=Release
os=Windows
compiler=Visual Studio
compiler.version=15
compiler.runtime=MTd
arch_build=x86_64
os_build=Windows
[options]
[build_requires]
[env]

**Comment by SSE4** [comment]
@Croydon do you have a full log?

**Comment by Croydon** [comment]
/remind me in 6 days to provide full logs

**Comment by elizagamedev** [comment]
I'll take a look at this when I've got a chance next week.

**Comment by SSE4** [comment]
@Croydon ping :)

**Comment by Croydon** [comment]
I'm not sure how I can change the MSVC output to English.... So I'm going to translate some parts manually.... 😕 

```
build started at 16.12.2018 15:36:52
     1>project "C:\Users\Micha\.conan\data\sdl2_ttf\2.0.14\bincrafters\stable\build\c8ad6831ea32858501281360e805b3dd382a1d7c\SDL2_ttf-2.0.14\VisualC\SDL_ttf.sln" auf Knoten "1" (default target).
     1>ValidateSolutionConfiguration:
         Die projectmappenkonfiguration "Release|x64" wird erstellt.
     1>Das project "C:\Users\Micha\.conan\data\sdl2_ttf\2.0.14\bincrafters\stable\build\c8ad6831ea32858501281360e805b3dd382a1d7c\SDL2_ttf-2.0.14\VisualC\SDL_ttf.sln" (1) erstellt "C:\Users\Micha\.conan\data\sdl2_ttf\2.0.14\bincrafters\stable\build\c8ad6831ea32858501281360e805b3dd382a1d7c\SDL2_ttf-2.0.14\VisualC\SDL_ttf.vcxproj" (2) auf Knoten "1" (default target).
     2>E:\Program Files\x86\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets(65,5): error MSB8020: Die Buildtools f▒r Visual Studio 2010 (Plattformtoolset = "v100") wurden nicht gefunden. Installieren Sie zum Erstellen mithilfe der v100-Buildtools die Visual Studio 2010-Buildtools. Alternativ k▒nnen Sie ein Upgrade auf die aktuellen Visual Studio-Tools durchf▒hren, indem Sie das Men▒ "project" ausw▒hlen oder mit der rechten Maustaste auf die projectmappe klicken und dann "projectmappe neu zuweisen" ausw▒hlen. [C:\Users\Micha\.conan\data\sdl2_ttf\2.0.14\bincrafters\stable\build\c8ad6831ea32858501281360e805b3dd382a1d7c\SDL2_ttf-2.0.14\VisualC\SDL_ttf.vcxproj]
     2>Die Erstellung des projects "C:\Users\Micha\.conan\data\sdl2_ttf\2.0.14\bincrafters\stable\build\c8ad6831ea32858501281360e805b3dd382a1d7c\SDL2_ttf-2.0.14\VisualC\SDL_ttf.vcxproj" ist abgeschlossen (default target) -- ERROR.
     1>Die Erstellung des projects "C:\Users\Micha\.conan\data\sdl2_ttf\2.0.14\bincrafters\stable\build\c8ad6831ea32858501281360e805b3dd382a1d7c\SDL2_ttf-2.0.14\VisualC\SDL_ttf.sln" ist abgeschlossen (default target) -- ERROR.

error at the build steps.

       "C:\Users\Micha\.conan\data\sdl2_ttf\2.0.14\bincrafters\stable\build\c8ad6831ea32858501281360e805b3dd382a1d7c\SDL2_ttf-2.0.14\VisualC\SDL_ttf.sln" (default target) (1) ->
       "C:\Users\Micha\.conan\data\sdl2_ttf\2.0.14\bincrafters\stable\build\c8ad6831ea32858501281360e805b3dd382a1d7c\SDL2_ttf-2.0.14\VisualC\SDL_ttf.vcxproj" (default target) (2) ->
       (PlatformPrepareForBuild Ziel) ->
         E:\Program Files\x86\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets(65,5): error MSB8020: Die Buildtools f▒r Visual Studio 2010 (Plattformtoolset = "v100") wurden nicht gefunden. Installieren Sie zum Erstellen mithilfe der v100-Buildtools die Visual Studio 2010-Buildtools. Alternativ k▒nnen Sie ein Upgrade auf die aktuellen Visual Studio-Tools durchf▒hren, indem Sie das Men▒ "project" ausw▒hlen oder mit der rechten Maustaste auf die projectmappe klicken und dann "projectmappe neu zuweisen" ausw▒hlen. [C:\Users\Micha\.conan\data\sdl2_ttf\2.0.14\bincrafters\stable\build\c8ad6831ea32858501281360e805b3dd382a1d7c\SDL2_ttf-2.0.14\VisualC\SDL_ttf.vcxproj]

    0 Warnung(en)
    1 error

Verstrichene Zeit 00:00:00.35
sdl2_ttf/2.0.14@bincrafters/stable:
sdl2_ttf/2.0.14@bincrafters/stable: ERROR: Package 'c8ad6831ea32858501281360e805b3dd382a1d7c' build failed
sdl2_ttf/2.0.14@bincrafters/stable: WARN: Build folder C:\Users\Micha\.conan\data\sdl2_ttf\2.0.14\bincrafters\stable\build\c8ad6831ea32858501281360e805b3dd382a1d7c
ERROR: sdl2_ttf/2.0.14@bincrafters/stable: Error in build() method, line 65
        self.build_with_vs()
while calling 'build_with_vs', line 78
        toolset=self.settings.compiler.toolset)
        ConanException: Error 1 while executing set "VSCMD_START_DIR=%CD%" && call "E:\Program Files\x86\Microsoft Visual Studio\2017\Community\VC/Auxiliary/Build/vcvarsall.bat" amd64 && devenv "SDL2_ttf-2.0.14\VisualC\SDL_ttf.sln" /upgrade && msbuild "SDL2_ttf-2.0.14\VisualC\SDL_ttf.sln" /p:Configuration="Release" /p:UseEnv=true /p:Platform="x64" /m:8 /p:ForceImportBeforeCppTargets="C:\Users\Micha\AppData\Local\Temp\tmpdqmshvjltmp_conan\t"
```

I guess the important part is:

```2>E:\Program Files\x86\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets(65,5): error MSB8020: Die Buildtools f▒r Visual Studio 2010 (Plattformtoolset = "v100") wurden nicht gefunden. Installieren Sie zum Erstellen mithilfe der v100-Buildtools die Visual Studio 2010-Buildtools. Alternativ k▒nnen Sie ein Upgrade auf die aktuellen Visual Studio-Tools durchf▒hren, indem Sie das Men▒ "project" ausw▒hlen oder mit der rechten Maustaste auf die projectmappe klicken und dann "projectmappe neu zuweisen" ausw▒hlen. [C:\Users\Micha\.conan\data\sdl2_ttf\2.0.14\bincrafters\stable\build\c8ad6831ea32858501281360e805b3dd382a1d7c\SDL2_ttf-2.0.14\VisualC\SDL_ttf.vcxproj]```

which roughly translates to:

> the build tools for Visual Studio 210 (platform tools = "v100") could not be found. Install the Visual Studio 2010 build tools to compile with v100 build tools. As an alternative you can upgrade to the latest Visual Studio Tools by choosing [??, my console kinda destroyed this word due to special chars] "project" or by right clicking with the mouse on the project folder and choosing "reassign project folder".

Can we workaround this dependency on 8 year old platform tools somehow?

**Comment by SSE4** [comment]
yep, I've seen similar issue with some projects on my machine. setting explicit toolset to the MSBuild cures this, but I don't think each recipe needs it. I suppose it's better to be fixed in conan codebase.

**Comment by SSE4** [comment]
@Croydon I think this one should have been fixed by conan 1.12 release. could you possibly try to update and run new build?

**Comment by SSE4** [comment]
@Croydon something is going wrong with libpng:
```
** FOUND PNG:  PNG_LIBRARY-NOTFOUND
** FOUND PNG INCLUDE:  C:/Users/Micha/.conan/data/libpng/1.6.34/bincrafters/stable/package/b98b29f486702ec177c83ea1868a9059b286b666/include
```
so, it found headers, but not libraries.
could you post here list of `C:/Users/Micha/.conan/data/libpng/1.6.34/bincrafters/stable/package/b98b29f486702ec177c83ea1868a9059b286b666/lib` folder?

**Comment by SSE4** [comment]
also, it seems like custom `FindPNG.cmake` is used, but it appears to be already removed from our repository, so you might have an outdated version of libpng package?
it would be nice if you could try to remove your local libpng package and give one more try.

**Comment by SSE4** [comment]
@Croydon I suppose it should be fixed now, as we have switched `sdl2_ttf` builds to CMake.

**Comment by Croydon** [comment]
Sorry, I kinda forgot about this one. I still run into the same `PNG_LIBRARY-NOTFOUND` issue

>could you post here list of C:/Users/Micha/.conan/data/libpng/1.6.34/bincrafters/stable/package/b98b29f486702ec177c83ea1868a9059b286b666/lib folder?

```lib\libpng
lib\libpng16_static.lib
lib\libpng\libpng16-release.cmake
ib\libpng\libpng16.cmake
```

**Comment by Croydon** [comment]
This is actually more a freetype/libpng issue. When I'm installing freetype alone this happens as well
