### ISSUE TITLE
libuuid misses builds for recent gcc and clang

### ISSUE THREAD

**Issue by madebr** [bincrafters/community#536]
### Description of Problem, Request, or Question
https://github.com/bincrafters/conan-libuuid

### Package Details (Include if Applicable)
* Package Name/Version: **libuuid/1.0.3**
* Operating System: **Fedora 28**
* Compiler+version: **gcc-8.1**

**Comment by madebr** [comment]
Also, I would suggest to add the `uuid` subdirectory to `self.cpp_info.includedirs`

**Comment by uilianries** [comment]
it's wrong! patching again.

**Comment by SSE4** [comment]
I think it's done, WDYT @uilianries ?
