### ISSUE TITLE
static libtirpc is not built with fPIC

### ISSUE THREAD

**Issue by madebr** [bincrafters/community#537]
### Description of Problem, Request, or Question
When building a shared library that links to the static libtirpc, linking fails becaus static libtirpc is always built as a non-pic library.
This error appears:
```
/usr/bin/ld: /home/maarten/.conan/data/libtirpc/1.1.4/bincrafters/stable/package/2d5685a99e2ff5a0d2b054bb1fbfa46781f8a46a/lib/libtirpc.a(libtirpc_la-clnt_perror.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
```

### Package Details (Include if Applicable)
* Package Name/Version: **libtirpc/1.1.4**
* Operating System: **Fedora 28**
* Compiler+version: **gcc-8.1**
### Steps to reproduce (Include if Applicable)

It can be fixed by adding
```
"--with-pic" if self.options.fPIC else "--without-pic",
```
to `args` in `build()` of libtirpc's [conanfile.py](https://github.com/bincrafters/conan-libtirpc/blob/fd90fc8a02e11637f46c1914d203390583e1ed79/conanfile.py#L42)

**Comment by madebr** [comment]
https://github.com/bincrafters/conan-libtirpc/pull/1

**Comment by SSE4** [comment]
closing as merged
