### ISSUE TITLE
Sfml free(): invalid pointer abort

### ISSUE THREAD

**Issue by SamuelRousseaux** [bincrafters/community#538]
Hi !
I'm currently using conan and bincrafters's sfml for a project, and no matter what I'm trying, I get a "free(): invalid pointer" error, resulting in an abort, even with the most simple sfml project (just opening a window, and keeping it open).

I tried compiling my file with "real" sfml sources, and it works great. I don't really know how to fix this right now...

Here are the details :
* Package Name/Version: sfml/2.5.1
* Operating System: Linux Ubuntu 18.04.1 LTS
* Compiler+version: gcc 7.3.0

I use the linked files to compile, then use this line : 
`rm -rf build && mkdir build && cd build && conan install .. --build=missing && cmake .. -G "Unix Mak\
efiles" && cmake –build . && make && cd ..`

[CMakeLists.txt](https://github.com/bincrafters/community/files/2586702/CMakeLists.txt)
[conanfile.txt](https://github.com/bincrafters/community/files/2586703/conanfile.txt)

I've been on this since 2 days, and I really don't understand the problem

Strange thing : if I launch the program with valgrind, it seems to work perfectly, no crash to be seen

Thanks !

**Comment by uilianries** [comment]
Thanks for reporting, we will take a look

**Comment by SamuelRousseaux** [comment]
Hi !

I've been working on it since the post yesterday, and I found a workaround. I had to replace in _~/.conan/profiles/default_ the value of **compiler.libcxx** from **libstdc++** to **libstdc++11**

I hope it will help if someone encounters the same problem !

**Comment by scorsi** [comment]
Wow, it did the trick ! Thanks @SamuelRousseaux

**Comment by Croydon** [comment]
@uilianries What should we do about this issue?

**Comment by uilianries** [comment]
@Croydon let me revisit it!

**Comment by uilianries** [comment]
I can't reproduce using conanio/gcc7.

    conan create . bincrafters/testing -o sfml:graphics=True

Also, I added `add_definitions("-std=c++17 -fPIC")` to test_package. I think I need a specific function to crash.

@SamuelRousseaux do you have some specific C++ code that reproduces your problem?

**Comment by MaximeHouis** [comment]
Hello,
I have the issue by creating a new SFML window :
```cpp
sf::RenderWindow sfWin{sf::VideoMode{1600, 900}, "Window title", sf::Style::Close};
```
From the stack trace, it seems that the crash happens when the string is destroyed.  
I've tried passing different types of strings, C style, std::string and sf::String: crashed every time.

* Compilers: `g++ 9.2.0` `clang++ 9.0.0`
* CMake: `1.15.5`
* Conan: `1.19.3`
* OS: `Arch Linux 5.3.8-arch1-1`

conanfile.txt:
```
[requires]
sfml/2.5.1@bincrafters/stable

[options]
sfml:graphics=True
sfml:window=True
sfml:audio=True
sfml:network=False

[generators]
cmake
```
**Note:** Got the same crash with both gcc and clang. (rebuilt all with separate profiles)

**Comment by MaximeHouis** [comment]
> Hi !
> 
> I've been working on it since the post yesterday, and I found a workaround. I had to replace in _~/.conan/profiles/default_ the value of **compiler.libcxx** from **libstdc++** to **libstdc++11**
> 
> I hope it will help if someone encounters the same problem !

This fixes the issue for now, but I would prefer a portable solution if possible.

**Comment by glpuga** [comment]
> I can't reproduce using conanio/gcc7.
> 
> ```
> conan create . bincrafters/testing -o sfml:graphics=True
> ```
> 
> Also, I added `add_definitions("-std=c++17 -fPIC")` to test_package. I think I need a specific function to crash.
> 
> @SamuelRousseaux do you have some specific C++ code that reproduces your problem?

I also found this issue while trying to run imgui-sfml, and the fix mentioned above fixes it.

I attached files to create a docker container that has this precise issue for repeatability.

To replicate build and run the container using the scripts in the tar file, and then run `cmake .. ; make ; ./bin/ImGuiExample` to see the failure.

[test_environment.zip](https://github.com/bincrafters/community/files/5288719/test_environment.zip)
