### ISSUE TITLE
Deprecate our own Catch2 package / helping upstream

### ISSUE THREAD

**Issue by barcharcraz** [bincrafters/community#539]
As it says in the issue title catch is on 2.4.2 now.

Also catch has an upstream conanfile now, which may be better to use than this one (for one it actually installs using cmake.

**Comment by Croydon** [comment]
If they have official Conan support then our package is becoming obsolete and we should help them instead to get it into conan-center.

**Comment by Croydon** [comment]
Actually: https://github.com/catchorg/Catch2/pull/943

**Comment by uilianries** [comment]
oh man, just 1 year ago ... :birthday: 

I need to update that PR!

**Comment by uilianries** [comment]
Related PR: https://github.com/catchorg/Catch2/pull/1443

**Comment by uilianries** [comment]
Let's wait for the next Catch2 release before to deprecate Bincrafters support for Catch2. Also we should update the README file and add an warning message.

**Comment by Croydon** [comment]
Catch2 has now own uploads on Bintray. We can help them now getting it into conan-center (if not already done @uilianries? 😄 )

**Comment by Croydon** [comment]
## Todo
  * Help get upstream Catch2 into conan-center
  * Publish a 2.5.0 recipe in Bincrafters as explained here https://github.com/bincrafters/community/issues/546#issuecomment-444057900

**Comment by danimtb** [comment]
Hi guys!

I have just included official Catch2 into Conan Center: https://bintray.com/catchorg/Catch2/Catch2%3Acatchorg

Next step would be deprecating the bincrafters recipe with a message. We already did this with PEGTL:  https://bintray.com/bincrafters/public-conan/pegtl%3Abincrafters

Thanks!

**Comment by uilianries** [comment]
Thanks @danimtb !

**Comment by uilianries** [comment]
Ops! https://travis-ci.com/bincrafters/conan-catch2/builds/93495573#L927

Looks like alias is not working well
