### ISSUE TITLE
Update rxcpp to 4.1.0

### ISSUE THREAD

**Issue by tt4g** [bincrafters/community#542]
### Description

Could you upgrade rxcpp to version 4.1.0?

I want to use C++17 libraries and rxcpp.
Can't compile rxcpp 4.0.0 in C++17:  ReactiveX/RxCpp#388

### Package Details (Include if Applicable)
* Package Name/Version: **rxcpp/4.0.0**
* Operating System: **Windows 10**
* Compiler+version: **VC 2017**

**Comment by uilianries** [comment]
Done!

https://github.com/bincrafters/conan-rxcpp/tree/stable/4.1.0
https://bintray.com/bincrafters/public-conan/rxcpp%3Abincrafters/4.1.0%3Astable

![rxcpp/4.1.0@bincrafters/stable](https://screenshotscdn.firefoxusercontent.com/images/58f3b938-05ef-4f70-8785-5f63f0ab6214.png)

**Comment by tt4g** [comment]
Thank you for your quick response.
