### ISSUE TITLE
Include ExprTk package

### ISSUE THREAD

**Issue by kylemacfarlan** [bincrafters/community#543]
I have created a package for the ExprTk library (https://github.com/ArashPartow/exprtk). I think it would be a nice addition to the bincrafters repo. It is a header-only library, so it is very straightforward. You can find my package here: https://github.com/kylemacfarlan/conan-exprtk

Feel free to reach out to me here or on slack for questions and/or comments.

**Comment by Croydon** [comment]
Ah, yes, sorry about that. It is on my to do list to unify the header templates with the non-headers ones. It's just to much pain to maintain both in separate branches.

**Comment by Croydon** [comment]
Done! https://github.com/bincrafters/conan-exprtk

I invited you to the repository.

**Comment by uilianries** [comment]
looks good enough to be promoted in conan center

**Comment by Croydon** [comment]
You can move this forward if you want :)

**Comment by uilianries** [comment]
Okay, I made the request, let's wait for review.

**Comment by Croydon** [comment]
It's now in conan-center 🎉
