### ISSUE TITLE
Maintain templates for header-only and non-header-only packages in same branch

### ISSUE THREAD

**Issue by Croydon** [bincrafters/community#544]
Too much pain to maintain it separated and also tot hard to discover.

the header branch is currently heavily outdated.

**Comment by uilianries** [comment]
is there a template generator?

**Comment by Croydon** [comment]
> is there a template generator?

not directly, we have gen-ci.py for CI scripts but could have expended on this. 

Not sure what to do with this issue. Maintaining both branches while just a few lines differ is really tiring, My original plan was to merge them and depending on the exact file difference either improve our tooling for header_only detection to get rid of differences in our CI and adding a second conanfile.header-only.py file or something along these lines.

Since @solvingj vetoed it that we have files in the template directory which needs deleting (even though this can never be completely avoided, e.g. Linux-only support never needs Windows CI) I would like to hear his input here.

**Comment by uilianries** [comment]
> Maintaining both branches while just a few lines differ is really tiring. 

Our first idea was to create a project by feature, but as you can see, it would be a mess to maintain, so we opted by branches. Branches are easier to maintain because we could open PR to shared a new feature or PR, but it's not intuitive for newbies and as you said, they are really tiring.

On the other hand, using generators could solve all possible templates by one simple command, but again is not intuitive for newbies, anyone will need to learn a new tool just to start a new project instead of copying all files.

I think we should think in a middle term, it's a trade off situation.

**Comment by SSE4** [comment]
what if we just have several folders within single master branch? e.g. `regular`, `header-only`, `installer`, etc.?

**Comment by uilianries** [comment]
> what if we just have several folders within single master branch? e.g. regular, header-only, installer, etc.?

It's an option.

* pros:
- Anyone is able to know all templates at first view
- Anyone is able to start a new project just copying a folder

* cons
- Any hotfix/enhancement should be replicated manually (e.g diff command).

**Comment by SSE4** [comment]
we may symlink files which are shared between all templates (e.g. `ci/install.sh` & `ci/run.sh`)
other files which differ (e.g. `build.py`, `travis.yml`, `appveyor.yml`) has to be updated multiple times.
but for me it appears to be  much simpler than use 3 branches.

**Comment by solvingj** [comment]
This is a good point and I agree that a single branch would be more discoverable without adding too much complexity.  I've done a consolidation in my fork here, let me know what you think. 

https://github.com/solvingj/conan-templates/tree/all_templates

**Comment by uilianries** [comment]
:top: :top: :top:

**Comment by SSE4** [comment]
@Croydon @uilianries @solvingj I think we should consider this done, WDYT?
