### ISSUE TITLE
Synchronize Github repository settings accross packages

### ISSUE THREAD

**Issue by Croydon** [bincrafters/community#545]
... via bot and put default settings in our templates repository.

  * disable issues, projects, wiki 
  * protect `stable/*` branches and require pull requests before being able to push to stable branches from contributors 
    * admins don't need to create pull requests and can continue to push directly to stable branches 
    * we are fairly liberal when it comes to giving people push access when they make requests to include new packages in our infrastructure, I think this is beneficial as it lowers contributions barriers, might encourage them to continue to contribute and so split the maintenance work; however, by enforcing pull requests we still have some checks in place, before packages will be updated via CI and people might consume this from conan-center.....

**Comment by Croydon** [comment]
No. Don't do anything. I will use https://github.com/probot/settings

**Comment by Croydon** [comment]
General rule of thumb:

**Comment by SSE4** [comment]
@solvingj mentioned there are another approaches to handle that:

- GitHub actions
- GitHub apps
- also, seems like there are also bots available

need to look at them, and that can they do compare to GitHub REST API, and study how to build and integrate them

@DEGoodmanWilson probably may shed some more light

**Comment by Croydon** [comment]
Probot Settings is a GitHub app

**Comment by Croydon** [comment]
My plan is to use this config file based approach combined with this GitHub app. So we have all together in the repositories and can update it with all other configurations. Do you see any problems with that @SSE4?

**Comment by Croydon** [comment]
I admit that I should have provided more information in the issue description. However, please note that I have self-assigned this issue and didn't ask for help so far, so please first ask for more information or clarification before you start to prototype something 😄

**Comment by Croydon** [comment]
Disabling issues/projects/wiki is working fine, branch protection rules still make problems

https://github.com/probot/settings/issues/87
https://github.com/bincrafters/conan-templates/blob/9d90730ff157d8573440167af7b2850cbe0f54eb/.github/settings.yml

**Comment by SSE4** [comment]
@Croydon I think this is done, right?

**Comment by Croydon** [comment]
It isn't done in the original context of this issue.

However, I would say that with GitHub templates the situation is good enough. Closing.
