### ISSUE TITLE
Strategy for deprecating packages

### ISSUE THREAD

**Issue by Croydon** [bincrafters/community#546]
AFAIK we don't have a strategy to deprecate packages yet, do we?

There could be several scenarios in which this can happen, e.g.
  * we maintained a package, which now has official upstream support (e.g. #539) 
  * we maintained a package, which is unmaintained/EOL upstream

How to deal with this, when 
  * a) the package is only in our Bincrafters repository
  * b) the package is also in conan-center

**Comment by jgsogo** [comment]
I'm opening a mirrored issue in Conan repo to keep track of this one, but *I'm locking it there so no one can add comments to it*.

**Comment by uilianries** [comment]
[PEGTL](https://github.com/bincrafters/conan-pegtl/tree/stable/2.5.1) is a good example.

We should keep all packages in bintray, we shouldn't remove any package from bintray because this could break our users.

Also, we should update the recipe with a warning message and update the README file as well.

**Comment by jgsogo** [comment]
Uploading an alias must be considered too: https://docs.conan.io/en/latest/reference/commands/misc/alias.html#conan-alias

**Comment by uilianries** [comment]
excellent idea I think

**Comment by jgsogo** [comment]
Indeed, we could implement the alias making something like this (not tested, but it should work):

```python

class DeprecatedPackage(ConanFile):
   
    @property
    def alias(self):
        self.out.warn("Package .... is being deprecated. Change yours to require .... instead")
        return "..."

```

**Comment by solvingj** [comment]
Yes, alias with warning seems best.

**Comment by Croydon** [comment]
Agreed. Alias (if there is a replacement) + warning via Conan recipe + git readme + notice on the Bintray page seems fine.

In the cases where there is a replacement, e.g.
> we maintained a package, which now has official upstream support (e.g. #539)

I would suggest that we use the first version which has official upstream support as the "soft transition" version. What I mean is, for the case of Catch2:
  * Catch2 2.5.0 is the first version with official upstream Conan support and publishing/uploading
  * Bincrafters don't have yet a Catch2 2.5.0 published version
  * We should upload a 2.5.0 recipe, containing a warning and an alias on the new upstream recipe 
  * Add warnings in the readme, Bintray page, archive GitHub repository
  * Don't publish any further Catch2 recipes versions in Bincrafters 
  * Leave older recipe versions published by Bincrafters unchanged

**Comment by uilianries** [comment]
Sounds good, I would change the package icon on Bintray with "deprecated"

example: https://bintray.com/conan-community/conan/Boost%3Aconan

I'm going to work on Catch2 now

**Comment by uilianries** [comment]
BTW this strategy should be available on https://bincrafters.readthedocs.io/en/latest/

**Comment by uilianries** [comment]
Done, I've added step 0, where should be created a new branch version to execute a soft transition.

**Comment by Croydon** [comment]
Done from my point of view 👍

**Comment by solvingj** [comment]
Great work @uilianries

**Comment by uilianries** [comment]
thanks to @Croydon for providing us his idea :muscle:
