### ISSUE TITLE
Wrong gcc compiler version in cryptopp binary packages

### ISSUE THREAD

**Issue by db4** [bincrafters/community#549]
### Description of Problem, Request, or Question

Conan recommends to include gcc minor version to `compile.version` only when `gcc<=4.9`. But cryptopp binary packages advertise  `compiler.version=5.4` and `compiler.version=6.3` making building from sources necessary for `compiler.version=5` or `compiler.version=6`.

### Package Details (Include if Applicable)
* Package Name/Version: **cryptopp/5.6.5**
* Operating System: **Linux Ubuntu 16.04**
* Compiler+version: **gcc-5.4**

**Comment by SSE4** [comment]
@db4 do you need specifically 5.6.5 version, as there is 7.0.0?

**Comment by db4** [comment]
@SSE4 well, I just used it in some of my old projects which I'm converting to conan. Of course, moving to 7.0.0 is possible but requires some changes in the sources (e.g. cryptopp 5.6.5 defined some useful types like `byte` in the global namespace, but in 7.0.0 they're moved to `CryptoPP` namespace)

**Comment by SSE4** [comment]
okay, sure, I'll apply changes to both branches then

**Comment by SSE4** [comment]
@db4 I've applied required changes, could you possibly give an another try?

**Comment by db4** [comment]
@SSE4 works for me, thank you!

**Comment by SSE4** [comment]
confirmed as fixed, closing
