### ISSUE TITLE
conan-sdl2 - Missing prebuilt package for Windows

### ISSUE THREAD

**Issue by sixten-hilborn** [bincrafters/community#55]
As title states, [conan-sdl2](https://github.com/bincrafters/conan-sdl2) misses Windows binaries. Appveyor should be triggered on the stable branch.

**Comment by SSE4** [comment]
build was triggered https://ci.appveyor.com/project/BinCrafters/conan-sdl2
does it fix your problem?

**Comment by sixten-hilborn** [comment]
Thanks for the quick reply! I had some other issues and forgot to answer..

Now I have other issues with [missing binaries in libiconv](https://ci.appveyor.com/project/sixten-hilborn/conan-sdl-gpu/build/job/s44dxw6kn0tg4njb). That's related to a [change in the template](https://github.com/bincrafters/conan-templates/commit/f4cb08befc85818ce083a2412a6d90e33d221c2a) and many libraries haven't been rebuilt since (I'm using the bincrafters template in my recepies).

**Comment by solvingj** [comment]
Hey there, sorry about this one, let me try to refresh libiconv now with the latest.

**Comment by SSE4** [comment]
I currently am updating conan-libiconv recipe

**Comment by SSE4** [comment]
update: I've run into weird issue that make executable hangs for libiconv build, I am investigating it.

**Comment by solvingj** [comment]
Actually, we're currently building the normal "common builds" from conan package tools.  Based on the options you mentioned, we have:

`Windows/x86/Debug/MDd/static`
`Windows/x86/Debug/MTd/static`
`Windows/x86/Debug/MTd/shared` 


Can you give more specifics about the exact options you're not able to get?

**Comment by sixten-hilborn** [comment]
> conan search 'sdl2/2.0.7@bincrafters/stable' -r=bincrafters -q 'os=Windows AND build_type=Release AND arch=x86'
    There are no packages for reference 'sdl2/2.0.7@bincrafters/stable' matching the query 'os=Windows AND build_type=Release AND arch=x86'
    > conan search 'sdl2/2.0.7@bincrafters/stable' -r=bincrafters -q 'os=Linux AND build_type=Release AND arch=x86'
    There are no packages for reference 'sdl2/2.0.7@bincrafters/stable' matching the query 'os=Linux AND build_type=Release AND arch=x86'
    > conan search 'sdl2/2.0.7@bincrafters/stable' -r=bincrafters -q 'os=Linux AND build_type=Debug AND arch=x86_64'
    There are no packages for reference 'sdl2/2.0.7@bincrafters/stable' matching the query 'os=Linux AND build_type=Debug AND arch=x86_64'

Packages built before [this change](https://github.com/bincrafters/bincrafters-package-tools/commit/f4cb08befc85818ce083a2412a6d90e33d221c2a) were only built with the default profile for each compiler version. Check [the log](https://travis-ci.org/bincrafters/conan-sdl2/jobs/325014702) from latest stable sdl2 build:

    Builds list:
    [('settings', {}), ('options', {}), ('env_vars', {}), ('build_requires', {}), ('reference', sdl2/2.0.7@bincrafters/stable)]

When I build my packages with the current template I get this list:

    Builds list:
    [('settings', {'arch': 'x86', 'build_type': 'Release', 'compiler': 'gcc', 'compiler.version': '5'}), ('options', {'sdl_gpu:shared': False}), ('env_vars', {}), ('build_requires', {}), ('reference', sdl_gpu/20171201@sixten-hilborn/stable)]
    [('settings', {'arch': 'x86', 'build_type': 'Debug', 'compiler': 'gcc', 'compiler.version': '5'}), ('options', {'sdl_gpu:shared': False}), ('env_vars', {}), ('build_requires', {}), ('reference', sdl_gpu/20171201@sixten-hilborn/stable)]
    [('settings', {'arch': 'x86_64', 'build_type': 'Release', 'compiler': 'gcc', 'compiler.version': '5'}), ('options', {'sdl_gpu:shared': False}), ('env_vars', {}), ('build_requires', {}), ('reference', sdl_gpu/20171201@sixten-hilborn/stable)]
    [('settings', {'arch': 'x86_64', 'build_type': 'Debug', 'compiler': 'gcc', 'compiler.version': '5'}), ('options', {'sdl_gpu:shared': False}), ('env_vars', {}), ('build_requires', {}), ('reference', sdl_gpu/20171201@sixten-hilborn/stable)]

which results in this error:

    sdl2/2.0.7@bincrafters/stable: WARN: Can't find a 'sdl2/2.0.7@bincrafters/stable' package for the specified options and settings:
    - Settings: arch=x86, build_type=Release, compiler=gcc, compiler.version=5, os=Linux
    - Options: alsa=True, arts=False, directfb=True, esd=True, jack=True, mir=False, nas=True, pulse=True, shared=False, wayland=False, x11=True, xcursor=True, xinerama=True, xinput=True, xrandr=True, xscrnsaver=True, xshape=True, xvm=True, libiconv:fPIC=True, libiconv:shared=False
    ERROR: Missing prebuilt package for 'sdl2/2.0.7@bincrafters/stable'
    Try to build it from sources with "--build sdl2"

**Comment by solvingj** [comment]
My fault, indeed you were right.  Please give it a try now.  This build should have resolved your issue: 
https://ci.appveyor.com/project/BinCrafters/conan-sdl2

**Comment by solvingj** [comment]
@SSE4 do you have an update on this ? I believe it can be closed.

**Comment by SSE4** [comment]
closing, as packages are available
