### ISSUE TITLE
[folly] Include Google Snappy as Folly's requirement

### ISSUE THREAD

**Issue by uilianries** [bincrafters/community#551]

**Comment by SSE4** [comment]
@uilianries I see there is snappy package available, is it still actual?

**Comment by uilianries** [comment]
well, this weird, but I can't build Folly with snappy on XCode 9.0, however, I'm able to build for XCode 9.0 when snappy is not associated. As I don't have a mac hardware to reproduce, I spent some hours trying on Travis.

**Comment by SSE4** [comment]
I have Mac hardware, but my XCode is newer xD not sure what should we do, do you have at least build log?

**Comment by uilianries** [comment]
Yes, https://travis-ci.org/bincrafters/conan-folly/jobs/457088620#L5201

Seems related to libatomic. I tried to force with `-latomic` but the compiler said atomic doesn't exist.

**Comment by Croydon** [comment]
This recipe is now in the [Conan Center Index](https://github.com/conan-io/conan-center-index/).

Please migrate to the recipe version there. 
If this is still an issue, please create a new issue in the [Conan Center Index issue tracker](https://github.com/conan-io/conan-center-index/issues).

Thanks!
