### ISSUE TITLE
Physfs package fails to link on Windows 10

### ISSUE THREAD

**Issue by Josh-Thompson** [bincrafters/community#556]
### Description of Problem, Request, or Question
As said in the title, the PhysFS package fails to build properly on Windows 10. Untested on other platforms. It fails in the linking stage, details below.

### Package Details
* Package Name/Version: **physfs/3.0.1**
* Operating System: **Windows 10 Pro**
* Compiler+version: **gcc-7.3**

### Exact steps followed:
-Add the physfs package as a dependency for a project
-From my build directory:
    ```conan install .. -build=missing
    cmake -G "MinGW Makefiles" ..
    cmake --build . --config Release```
-At this point, ld fails on linking to objects.a.
-If the physfs:shared option is set to True rather than the default false, Conan emits a warning:
    ```WARN: Lib folder doesn't exist, can't collect libraries: .conan\data\physfs\3.0.1\bincrafters\stable\package\*long cache name*\lib```
-Either way it does not appear linking is working successfully

### Log Files:
With shared=True: https://hastebin.com/subolasulo.cs
With shared=False: https://hastebin.com/nozukiwice.sql

**Comment by Josh-Thompson** [comment]
Additionally, here is my conan profile:
```[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=7.3
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]```

**Comment by SSE4** [comment]
from the log - *.a files are built, but not copied, should be easy to fix

**Comment by SSE4** [comment]
@Josh-Thompson I've pushed the fix, could you possibly give an another try?

**Comment by Josh-Thompson** [comment]
Looks good, but the temp fix I added on line 68 of the conanfile.py will need to be remove as it'll fail now that an actual fix is in place.

**Comment by SSE4** [comment]
@Josh-Thompson sure, lemme check it

**Comment by SSE4** [comment]
@Josh-Thompson I reverted a temporary fix, please give a try

**Comment by Croydon** [comment]
@Josh-Thompson Ping

**Comment by SSE4** [comment]
@Josh-Thompson I am closing the issue for now, as fix was applied
please open new issue if you still experience problems
