### ISSUE TITLE
cryptopp package is missing file "cryptopp-config.cmake" 

### ISSUE THREAD

**Issue by crmoore** [bincrafters/community#557]
### Description of Problem, Request, or Question

The cryptopp package is missing the cmake package config file "{PREFIX}/lib/cmake/cryptopp/cryptopp-config.cmake".  It looks like this has been fixed in the upstream cryptopp cmake build files (from https://github.com/noloader/cryptopp-cmake).

### Package Details (Include if Applicable)
* Package Name/Version: **cryptopp/7.0.0**
* Operating System: **OSX**
* Compiler+version: **apple-clang**

### Steps to reproduce (Include if Applicable)

```
[requires]
cryptopp/7.0.0@bincrafters/stable
[generators]
cmake_paths
```

```
cmake_minimum_required(VERSION 3.10.0)
project(crypto-test)
find_package(cryptopp REQUIRED)
add_executable( crypto-test main.cpp )
target_link_libraries( crypto-test cryptopp-static )
```

```
#include <cryptopp/aes.h>
int main(){
	return 0;
}
```

```
mkdir build
cd build
conan install ..
cmake ../ -DCMAKE_TOOLCHAIN_FILE=conan_paths.cmake
```

**Comment by uilianries** [comment]
Thanks for reporting
