### ISSUE TITLE
Recent repositories have README.md files without section headers

### ISSUE THREAD

**Issue by solvingj** [bincrafters/community#558]
I've found a few very recent README.md files where section headers are all missing.  I'm not sure why. 

Examples:

https://github.com/bincrafters/conan-dirent-win32
https://github.com/bincrafters/conan-getopt

Here's what it should look like: 

https://github.com/bincrafters/conan-physfs

**Comment by Croydon** [comment]
I have fixed this in the testing branches of the two named repositories. If someone feels like it, it can be merged into stable, otherwise this will simply happen with the next recipe update
