### ISSUE TITLE
Simplifying use of bincrafters templates 

### ISSUE THREAD

**Issue by solvingj** [bincrafters/community#559]
I am making the following alterations to the `conan-templates` repository: 

- Remove gen_ci.py
- Remove azure-pipelines.yml
- Remove references to the readme generator
- Restore readme template, this time with URL template strings

I am also updating the template-related instructions in the Bincrafters documentation here: 

https://bincrafters.readthedocs.io/en/latest/contributing_to_packages.html

## Explanation of Changes
After reviewing the `readme-generator` and `gen-ci.py` code, it was clear that our "suggested process" is failing in it's goal because it's simply too complicated. The original intent of this repository was to make it easy for users to get started building an OSS package with Conan using our conventions and CI.  In the process, we've created two completely new "Bincrafters" programs, with a bunch of command-line arguments which users are supposed to learn in order to create a handful of trivial text files from templates, something most community contributors will do 2-5 times at most.  It's easy to see how this kind of thing happens.  Manually modifying templates is error-prone, seems tedious, which triggers the instinct to automate it away.  Also, there is a bit of conditional logic one must decide upon for each new project, which triggers the instinct to generalize and parameterize using a script.  However, in these cases we have over-indulged in the fun of scripting, and not properly balanced it with the weights of practicality, maintainability, and the original goal. 

I appreciate the time spent by everyone on these scripts, and I do not mean to deride or devalue the work they've done.  **I repeat, I really really appreciate peoples time and effort.**  However it's important to point out the loss of perspective that got us to this place so we don't end up here again.  Moving forward, I simply ask that before we invest time into automation projects, we discuss the idea and strategy with multiple other people from the team to ensure we avoid falling into the same trap (it's extremely easy to do).  

## Azure Pipelines and Future of Bincrafters CI 
@Croydon and @uilianries have spent significant time working with Azure Pipelines, and have gotten it to the point where it is now usable for Bincrafters projects.  This is great work, and it looks to be a really great resource, and may be something we use extensively in the future.  It may even become the only CI we use.  However, at this time, Travis + Appveyor is still the de-facto standard for all new projects, and projects will be changed to use Azure Pipelines on a case-by-case basis.  We are overdue for some updated documentation and information sharing about all the new developments, I will try to remedy this situation ASAP.

**Comment by Croydon** [comment]
We can talk about simplification, yes, but I see no advantage in removing stuff. 

It is getting even more complicated. When we remove the azure-pipelines.yml we need another place to store it so we are just splitting it into more places. And it's not true that it is fully ready yet, @uilianries, @ericLemanissier and me are still very actively working on it. And since it is work-in-progress it is also self explanatory why Travis+AppVeyor is still de-facto standard. 

If we don't advocate for the readme-generator anymore then people need to manually edit it, instead of just executing `conan-readme-generator` without any parameters (in the case for Bincrafters repositories). By the way the reference to the readme generator was just added a few days ago by me.

Again, talking about simplifications is great, but removing stuff not so much. We could consider unifying all our CLI tools into one for example.

**Comment by Croydon** [comment]
We could also move `gen.ci-py` to another location, by doing so all templates files can be copied manually without deleting this file (you don't need to know what each file is doing).

**Comment by SSE4** [comment]
for `gen-ci.py` - feel free to remove it. I have a copy, and Git history also keeps it, so no need to worry about. I think it wasn't right decision to put it into templates repository.

**Comment by uilianries** [comment]
In the past our development flow was fairly manual, but also simple to understand, where any newbie could contribute immediately. But over time we saw that it was necessary to have tools to speed up our development and cover the manual steps. 

This may have helped us, but it had a price. Now every newbie needs to learn the extensive flow before contributing, which in my view, makes it difficult to integrate new contributions. I agree with @solvingj, I think we have created barriers that may have hampered new contributions. However I don't see problem in using scripts, by those who already know the project. We could simplify steps and use what is really needed from another branch.

**Comment by SSE4** [comment]
@solvingj @uilianries @Croydon I think we should consider this done, WDYT?

**Comment by Croydon** [comment]
Agreed

**Comment by uilianries** [comment]
Yes :grinning:
