### ISSUE TITLE
[winpcap] Fix static library build on Appveyor

### ISSUE THREAD

**Issue by uilianries** [bincrafters/community#565]
### Description of Problem, Request, or Question
This is a weird case, 

Winpcap fails when built on Appveyor and the option shared is False, but it works for dynamic library version.

However, it works on my machine. :roll_eyes: 

When I say fail, it means the test package returns an error, but I don't know what could be. :thinking: 

### Package Details (Include if Applicable)
* Package Name/Version: **winpcap/4.1.3**
* Operating System: **Windows**
* Compiler+version: ** MSVC 14,15**

### Steps to reproduce (Include if Applicable)
- Execute a single build on Appveyor, where winpcap is built as static library :red_circle: 
- Execute the same build in your machine :large_blue_circle: 
- See, makes no sense. :confused: 

### Logs
- [msvc14](https://ci.appveyor.com/project/BinCrafters/conan-winpcap/builds/20808429/job/13h4gcehhy8wlhw3)

**Comment by Croydon** [comment]
The latest builds are green. Is this still a thing? @solvingj

**Comment by solvingj** [comment]
We've currently filtered out static library builds in `build.py`. It would be nice if someone could look into it and see if they can get a static build working.

**Comment by SSE4** [comment]
I don't see `shared` option is handled somehow in recipe at all.
for me, building `winpcap:shared=False` still produces DLL files.
is it really expected? is static configuration supported at all by library itself?

**Comment by solvingj** [comment]
Probably not, in which case, we should remove option and update build.py appropriately.

**Comment by SSE4** [comment]
@uilianries can you comment on that? I've inspected solution files within sources, and they have only configurations to build DLLs.

**Comment by uilianries** [comment]
I agree removing the option. I built the package again on my machine and I can confirm it, the option shared does not result in any change in the package. it's the same package when it is shared or static.

**Comment by SSE4** [comment]
@uilianries are we done with that one?

**Comment by uilianries** [comment]
I think we can close this, since winpcap does not support the shared option.
