### ISSUE TITLE
conan-colm build is broken - is this being maintained?

### ISSUE THREAD

**Issue by jaredkeithwhite** [bincrafters/community#566]
### Description of Problem, Request, or Question

The bincrafters/conan-colm repository has a broken link to bintray, and the Windows and Linux/Mac builds show that they are failing. 

Is this repository being maintained?  How shall we get this back into shape?  It is a pre-requisite for some packages I'd like to use. 

### Package Details (Include if Applicable)
* Package Name/Version: **colm/0.13.0.5**
* Operating System: Linux, Windows

**Comment by uilianries** [comment]
Thanks for reporting, we will take a look soon.

**Comment by solvingj** [comment]
It looks like this one has some challenges to build.  @uilianries has done some work since this ticket was opened but there are still a few hundred errors on the MSVC side, and some `test_package` errors on Clang and AppleClang side. @jaredkeithwhite  if you want to try to look into the errors and submit PR's to fix them, it would help get this one finished.

**Comment by uilianries** [comment]
Yeah, solvingj is right,  colm is not  too trivial, but I should re-visit in few days.

**Comment by Croydon** [comment]
I have updated the version and conventions of the package because of THIS issue just to see if it helps, doesn't seem to be the case.

**Comment by Croydon** [comment]
Is anyone still interested in this package and willing to get it stable?

If nobody steps up I think we should archive it. We still don't have made a single release in 3 years.

**Comment by Croydon** [comment]
I archived the repository (https://github.com/bincrafters/conan-colm)

If someone is still interested in a recipe for Colm please open an issue and/or pull request for it at https://github.com/conan-io/conan-center-index
