### ISSUE TITLE
Request for inclusion libffi/3.2.1 and libffi/3.3.0-rc0

### ISSUE THREAD

**Issue by madebr** [bincrafters/community#569]
### Description of Problem, Request, or Question
These packages are missing.

### Package Details (Include if Applicable)
* Package Name/Version: **libffi/3.2.1** and **libffi/3.3.0-rc0**
* Operating System: **ALL**
* Compiler+version: **ALL**

### Steps to reproduce (Include if Applicable)
Please include these.
conan scripts at https://github.com/madebr/conan-libffi

libffi has some issues on some architectures and compilers: https://github.com/libffi/libffi/issues/456

I've forked vuo's scripts, because these were compile specific.

**Comment by SSE4** [comment]
@madebr thanks for your contribution.
I've created the repository https://github.com/bincrafters/conan-libffi
CI is launched.
I gonna spend some time on libffi, as it's dependency of GStreamer, which I am going to package soon.

**Comment by Croydon** [comment]
Is there a good reason to include a release candidate?

**Comment by SSE4** [comment]
@madebr @Croydon I've also added write permissions for you for conan-libffi repository, you should get e-mail notification from GitHub with instructions

**Comment by madebr** [comment]
@Croydon Release 3.2.1 is from 2014, the rc from april this year. So I added it to check what changes the conanfile.py needs when a new release shows up.

**Comment by madebr** [comment]
Is there any progress on this?

**Comment by SSE4** [comment]
@madebr yep, I gonna push my changes soon

**Comment by SSE4** [comment]
@madebr  3.2.1 has passed CI, packages are available

**Comment by SSE4** [comment]
@madebr 3.3-rc0 is very read, as you've pointed earlier, it has lots of build issues. what do you think we should do with it for now?

**Comment by madebr** [comment]
@SSE4  Excellent work!
I would just keep 3.3-rc0 in testing so people can find it and eventually fix it.

**Comment by SSE4** [comment]
okay, I am closing the issue then
