### ISSUE TITLE
[conan-qt] Static built toolchain is not working

### ISSUE THREAD

**Issue by jgeudens** [bincrafters/community#572]
### Description of Problem, Request, or Question

The static build of Qt itself is now working with the compiler fix (#570), but I can't generate a static linked application with my generated toolchain. I'm getting errors about missing libstdc++-6.dll and libgcc_s_dw2-1.dll library when executing my application. This makes me think that the application wasn't completely linked static.

I suspect that a static qt toolchain requires some more configuration before compiling it. I have used a modified [PowerShell script](https://gist.github.com/jgeudens/a69559fb460b0d82eb565503e9752951) script to generate a static toolchain before.

The main changes that I can detect are in the mkspec file ($QtDir\mkspecs\win32-g++\qmake.conf). The script will append some options as prebuilt step before compiling the source and also as post build step.

It will append following lines to the qmake.conf file (`$QtSrcDir\qtbase\mkspecs\win32-g++\qmake.conf`) of the qt source before compiling

```
#[QT-STATIC-PATCH]
QMAKE_LFLAGS += -static -static-libgcc
QMAKE_CFLAGS_RELEASE -= -O2
QMAKE_CFLAGS_RELEASE += -Os -momit-leaf-frame-pointer
DEFINES += QT_STATIC_BUILD

```

and it will also append following line to the qmake.conf file (`$QtDir\mkspecs\win32-g++\qmake.conf`) in the generated toolchain

```
CONFIG += static
```

### Package Details (Include if Applicable)
* Package Name/Version: **conan-qt/stable/5.9.7**
* Operating System: **Windows 10**
* Compiler+version: **gcc-5.3**

**Comment by ericLemanissier** [comment]
Would you have a log of the failing build, including the exact error message and the compiler call which triggered it ?
At first sight it looks more like a Qt bug than a recipe bug

**Comment by jgeudens** [comment]
I'm at work, so I can't check my configuration or logs right now.

But did you try static compiling and running an actual test Qt application with the generated toolchain?

In my case, the compilation of Qt did work without errors. Also the static compilation of my application worked without errors. But the issue is when executing the application, the executable complains about some missing libraries. This indicates to me that the linking with gcc wasn't done completely static.

I use the same configuration of my application as I did with my manually static compiled Qt toolchain.

The changes in the files are mentioned on the static built wiki of Qt:
- [recent information with PowerShell script](https://wiki.qt.io/Build_Standalone_Qt_Application_for_Windows)
- [old information and manual configuration and compiling](https://wiki.qt.io/How_to_build_a_static_Qt_version_for_Windows_with_gcc)

**Comment by jgeudens** [comment]
I was indeed missing the `-static-runtime` option. Now I can generate truly static linked executables.

Thank you for the pointer and the maintenance of the qt package.
