### ISSUE TITLE
Add Chris Kohlhoff's executors library

### ISSUE THREAD

**Issue by Fohlen** [bincrafters/community#573]
The [executors](https://github.com/chriskohlhoff/executors) library by Chris Kohlhoff is a very valuable [addition to the standard functionality of C++](https://github.com/executors/executors/blob/master/explanatory.md) and will eventually be introduced to `C++20`. Thus far it would be nice to have the library on conan so that it can be used before that date of magical `C++20` :)
As far as I am concerned the official repository is now [`executors/executors-impl`](https://github.com/executors/executors-impl/)

### Package Details (Include if Applicable)
* Package Name/Version: **executors/0.1.0**

**Comment by uilianries** [comment]
Hi @Fohlen!

Thanks for sharing about Executors, but our official wishlist is [here](https://github.com/conan-io/wishlist/).

Could you please move your issue?

Regards!

**Comment by Fohlen** [comment]
Sure.

**Comment by uilianries** [comment]
Thanks!
