### ISSUE TITLE
mbedtls - expose all relevant cmake options as conan options

### ISSUE THREAD

**Issue by solvingj** [bincrafters/community#576]
It was brought to my attention today that we did not expose a significant number of required options for the mbedtls package. 

https://github.com/bincrafters/conan-mbedtls

We should spend the time and expand the options so that users have all the required flexibility of the library.

**Comment by SSE4** [comment]
options suggested by @solvingj :
```
cmake.definitions['CMAKE_POSITION_INDEPENDENT_CODE'] = 'ON'
            cmake.definitions['ENABLE_TESTING'] = 'OFF'
            cmake.definitions['ENABLE_PROGRAMS'] = 'OFF'
            cmake.definitions['CMAKE_BUILD_TYPE'] = self.settings.build_type
            if self.settings.os == 'Macos':
                cmake.definitions['CMAKE_OSX_DEPLOYMENT_TARGET'] = self.build_settings['osx_deployment_target']
                cmake.definitions['CMAKE_OSX_ARCHITECTURES'] = self.build_settings['cmake_osx_architectures']
            elif self.settings.os == 'iOS':
                cmake.definitions['CMAKE_TOOLCHAIN_FILE'] = self.build_settings['cmake_toolchain_file']
                cmake.definitions['IOS_DEPLOYMENT_TARGET'] = self.settings.os.version
                cmake.definitions['CMAKE_OSX_ARCHITECTURES'] = self.build_settings['ios_arch']
            elif self.settings.os == 'Android':
                cmake.definitions['CMAKE_TOOLCHAIN_FILE'] = self.build_settings['cmake_toolchain_file']
                cmake.definitions['ANDROID_PLATFORM'] = self.build_settings['android_platform']
                cmake.definitions['ANDROID_ABI'] = self.build_settings['android_abi']
                cmake.definitions['CMAKE_ANDROID_ARCH_ABI'] = self.build_settings['android_abi']
                cmake.definitions['ANDROID_NDK'] = self.build_settings['android_ndk']
            elif self.settings.os == 'Windows':
                cmake.definitions['MSVC_RUNTIME'] = 'static'
```

**Comment by SSE4** [comment]
- `CMAKE_POSITION_INDEPENDENT_CODE` - already set, not an option
- `ENABLE_TESTING` - already set, always off
- `ENABLE_PROGRAMS` - already set, always off
- `CMAKE_BUILD_TYPE` - doesn't conan set it?
- `CMAKE_OSX_DEPLOYMENT_TARGET` - doesn't conan set it?
- `CMAKE_OSX_ARCHITECTURES` - doesn't conan set it?
- `CMAKE_TOOLCHAIN_FILE` - not sure if it should be an option
- `IOS_DEPLOYMENT_TARGET` - doesn't conan set it?
- `ANDROID_PLATFORM` - doesn't conan set it?
- `ANDROID_ABI` - doesn't conan set it?
- `CMAKE_ANDROID_ARCH_ABI` - doesn't conan set it?
- `ANDROID_NDK` - doesn't conan set it?
- `MSVC_RUNTIME` - I don't see it is used anywhere in codebase. I believe, `conan_basic_setup` already sets runtime, right?

**Comment by SSE4** [comment]
options from mbedtls (https://github.com/ARMmbed/mbedtls/blob/mbedtls-2.15.1/CMakeLists.txt#L8):

- `USE_PKCS11_HELPER_LIBRARY` - requires an external library, need to package it first
- `ENABLE_ZLIB_SUPPORT` - added
- `USE_CRYPTO_SUBMODULE` - references library (`mbedtls-psa`) which seems to be removed? (https://github.com/ARMmbed/mbedtls-psa/tree/59fd5aee421bb203d2b8c31802b19eb0d6932ddb)
- `UNSAFE_BUILD` - I don't see it is used anywhere, seems like leftover?

**Comment by SSE4** [comment]
I am closing this for now, this doesn't appear to be requested by actual users
we may add options as soon as they are really requested

**Comment by solvingj** [comment]
We had a request from user in slack. I will reopen and assign to myself. This is an important library.

**Comment by Croydon** [comment]
This recipe is now in the [Conan Center Index](https://github.com/conan-io/conan-center-index/).

Please migrate to the recipe version there. 
If this is still an issue, please create a new issue in the [Conan Center Index issue tracker](https://github.com/conan-io/conan-center-index/issues).

Thanks!
