### ISSUE TITLE
conan-fmt Missing POWERS_OF_10_64 symbol

### ISSUE THREAD

**Issue by Manu343726** [bincrafters/community#577]
### Description of Problem, Request, or Question
*Pinging @vitaut since I'm not sure if this is a lib or packaging problem*.

I'm trying to link an executable that depends on `fmt/5.2.1` package, on Linux GCC 8.1 libstdc++11 ABI. The prebuilt package 319f7001eaf785d98ebfce3dc53dc78039a1482f is downloaded from bintray when running conan install. Linker fails with the following error:

```
[ 97%] Linking CXX executable ../bin/foo-exe
../lib/libfoo.a(foo.cpp.o): In function `fmt::v5::internal::count_digits(unsigned long)':
foo.cpp:(.text._ZN3fmt2v58internal12count_digitsEm[_ZN3fmt2v58internal12count_digitsEm]+0x40): undefined reference to `fmt::v5::internal::basic_data<void>::POWERS_OF_10_64'
```

If I examine the prebuilt fmt binary I get zero occurrences of `POWERS_OF_10_64` symbol:

```
 objdump -tC /home/manuel/.conan/data/fmt/5.2.1/bincrafters/stable/package/319f7001eaf785d98ebfce3dc53dc78039a1482f/lib/libfmt.a | grep "fmt::v5::internal::basic_data<void>::POWERS_OF_10_64"

```

but it appears to have a 32 variant:

```
objdump -tC /home/manuel/.conan/data/fmt/5.2.1/bincrafters/stable/package/319f7001eaf785d98ebfce3dc53dc78039a1482f/lib/libfmt.a | grep "fmt::v5::internal::basic_data<void>::POWERS_OF"
0000000000000000 u     O .data._ZN3fmt2v58internal10basic_dataIvE15POWERS_OF_10_32E     0000000000000028 fmt::v5::internal::basic_data<void>::POWERS_OF_10_32
```

If I explicitly build fmt with `conan install .. --build=fmt` I get the same. I'm opening the issue here because my spider-sense told me this 32 vs 64 thing could be an arch issue in the packaging. If that's not the case I will close this issue and follow in the fmt repo.

### Package Details (Include if Applicable)
* Package Name/Version: *fmt/5.2.1**
* Operating System: **Linux 4.15.0-33-generic #36~16.04.1-Ubuntu SMP Wed Aug 15 17:21:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux** (Linux Mint)
* Compiler+version: **gcc-8.1**

**Comment by vitaut** [comment]
The symbol seems to be there when the library is built manually (with gcc 8.2, but I don't think it makes a difference):
```
wget https://github.com/fmtlib/fmt/archive/5.2.1.tar.gz
tar xzf 5.2.1.tar.gz
cd fmt-5.2.1/
cmake .
make fmt
objdump -tC libfmt.a  | grep POWERS_OF_10_64
0000000000000000 l    d  .data._ZN3fmt2v58internal10basic_dataIvE23ZERO_OR_POWERS_OF_10_64E	0000000000000000 .data._ZN3fmt2v58internal10basic_dataIvE23ZERO_OR_POWERS_OF_10_64E
0000000000000000 u     O .data._ZN3fmt2v58internal10basic_dataIvE23ZERO_OR_POWERS_OF_10_64E	00000000000000a0 fmt::v5::internal::basic_data<void>::ZERO_OR_POWERS_OF_10_64
```

**Comment by SSE4** [comment]
there are 3 symbols within fmt library (https://github.com/fmtlib/fmt/blob/5.2.1/include/fmt/format.h#L885):

- POWERS_OF_10_32
- ZERO_OR_ POWERS_OF_10_32
- ZERO_OR_ POWERS_OF_10_64

there is no POWERS_OF_10_64 symbol. am I missing the point? where did this symbol come from?

**Comment by Manu343726** [comment]
That makes sense, it should be the case. One of my dependencies is pulling its own version of header only fmt and polluted the rest of the include paths.

@SSE4 thanks a lot.
