### ISSUE TITLE
Libpqxx not available in the public-conan bintray repository

### ISSUE THREAD

**Issue by JavierJF** [bincrafters/community#578]
### Libpqxx isn't available in the public-conan bintray repository

The package appears to have a [repository](https://github.com/bincrafters/conan-libpqxx) but the package is not available in bintray.

### Package Details
* lipqxx: Any version.

### Steps to reproduce
Search or try to install libpqxx latest version.

**Comment by Croydon** [comment]
This is because the package never seems to got beyond a testing version (so far).

Pinging @uilianries @jgsogo

**Comment by uilianries** [comment]
I'll need to revisit this one. I can't remember the current status.

**Comment by jgsogo** [comment]
Hi! I've completely forgot about this one. I see that bincrafters' is a fork of mine, we should transfer ownership, how can it be done? if I delete my repo then any of the forsk will become the main one :/ ..shall we make a PR to mine from this one, delete this and then transfer ownership?

+info: https://help.github.com/articles/what-happens-to-forks-when-a-repository-is-deleted-or-changes-visibility/

**Comment by uilianries** [comment]
well, you could archive your project and point bincrafters as new official:

Here https://bincrafters.readthedocs.io/en/latest/contributing_to_packages/package_deprecation.html we explain how to deprecate when the upstream becomes the new maintainer.

**Comment by jgsogo** [comment]
I'm talking about the Github repo, noone (I hope) is using my package from bintray. I just want to transfer my repo to bincrafters' org.

**Comment by uilianries** [comment]
According Github, you need to have write permission:

https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/

My idea is:

- Merge Bincrafters' changes: https://github.com/jgsogo/conan-libpqxx/compare/master...bincrafters:testing/6.2.4
- Remove Bincrafters' fork
- Give you temporary write premission
- Transfer your project to Bincrafters.

**Comment by JavierJF** [comment]
I have a suggestion for the package, I have been working with it recently, and looks like postgre doesn't compile with the latest version of "Visual Studio 2017" so, maybe will be better to enforce compiler and toolset in the package.

**Comment by uilianries** [comment]
@JavierJF Indeed libpqxx is not working well: https://ci.appveyor.com/project/BinCrafters/conan-libpqxx, we need to fix this. Did you try any fix?

**Comment by uilianries** [comment]
@jgsogo https://github.com/jgsogo/conan-libpqxx/pull/3

**Comment by JavierJF** [comment]
@uilianries I didn't tried any fix for the Bincrafters version for conan-libpqxx, because it sets [Bincrafters libpq](https://github.com/bincrafters/conan-libpqxx/blob/testing/6.2.4/conanfile.py#L22) as a dependency. And the conan recipe for that package doesn't support Visual Studio at all.

**Comment by jgsogo** [comment]
Hi! Let's organize this a little bit, I think it is important to have all the recipes available, working and ready to use.

 * postgresql: the are two available options: [bincrafters](https://github.com/bincrafters/conan-libpqxx/blob/testing/6.2.4/conanfile.py#L22) and [mine](https://github.com/jgsogo/conan-postgresql/blob/master/conanfile.py). I can transfer mine to conan-community and we may work on it there, mine is working on linux and windows (it should). We need this one for `libpqxx` to work
 * libpqxx, I will transfer mine to bincrafters' asap, it will be done today. We will work on this recipe in bincrafters community.

Are you ok with this, @uilianries?

**Comment by uilianries** [comment]
Agreed!

We moved @jgsogo's repo to https://github.com/bincrafters/conan-libpqxx. Now it is the official one.

We will revisit soon this recipe to fix it.

**Comment by SSE4** [comment]
@uilianries seems like builds are green. should we consider this done?
P.S. appveyor badge in readme points to the https://ci.appveyor.com/project/BinCrafters/conan-libpqxx, while correct URL seems to be https://ci.appveyor.com/project/BinCrafters/conan-libpqxx-dt888. what is this `dt888` suffix and can we fix URL or badge?

**Comment by Croydon** [comment]
I have switched things around https://ci.appveyor.com/project/BinCrafters/conan-libpqxx should be now the only active AppVeyor project for this repo

**Comment by uilianries** [comment]
@SSE4 @Croydon  I think libpqxx is ready to be promoted

**Comment by uilianries** [comment]
It's available on Conan center:

https://bintray.com/conan/conan-center?filterByPkgName=libpqxx%3Abincrafters
