### ISSUE TITLE
[libpqxx] Connect to a real database in tests

### ISSUE THREAD

**Issue by jgsogo** [bincrafters/community#580]
It would be great to connect to a real postgres database when building in travis/appveyor. 

To take into account:

 * conan_package_tools uses @lasote docker images, so we have to either install postgres inside the container or serve the database in the host and call it using TCP/IP.
   - but as far as I have tried, I cannot modify configuration of postgres in travis host to allow connections from other IPs 
   - binding a port (from the host) to unix domain socket (the one used by postgres) does not work, it seems it can make the request by no response is received :/

**Comment by uilianries** [comment]
Solved: https://github.com/bincrafters/conan-libpqxx/blob/stable/6.2.4/test_package/main.cpp#L10
