### ISSUE TITLE
Security vulnerability in 3.25 - Provide 3.26

### ISSUE THREAD

**Issue by onen5** [bincrafters/community#583]
There is a reported security whole in 3.25 of Sqlite.

### Package Details (Include if Applicable)
* Package Name/Version: 3.25
* Operating System: all
* Compiler+version: na
* Docker image: na

https://blade.tencent.com/magellan/index_en.html?fbclid=IwAR1ly0LPd9ltmXEIW-HMxmH40E2iCybRP9YA0s1gSoakt3cSv5iG-NFDffc

**Comment by SSE4** [comment]
@onen5 I've created new branch `stable/3.26.0`, please give a try

**Comment by onen5** [comment]
Works for me.  Thanks for the super fast turnaround
