### ISSUE TITLE
 boost_build package should not use os  and arch settings

### ISSUE THREAD

**Issue by grisumbras** [bincrafters/community#584]
### boost_build package should not use `os` and `arch` settings
The package uses `os` and `arch` settings, as a result, when cross-building a dependent package, incorrect cached binaries are downloaded. For example, when cross-building on Linux using MinGW,
binaries that are supposed to run on Windows are downloaded.

Instead, the package should use `os_build` and `arch_build` settings, or, possibly, `os_target` and `arch_target`. 
 
### Package Details
* Package Name/Version: **boost_build/1.69.0**

### Steps to reproduce
On Linux:
* create a new package;
* add `boost_build` to its `requires` or `build_requires`;
* create a profile for cross-building to Windows;
* run `conan install`, `boost_build` binaries are downloaded from remote serer;
* run `conan build`, the installed B2 executable is not found.

**Comment by SSE4** [comment]
@grisumbras I am not sure I understand the issue. I've looked at the boost_build recipe, and it uses `os_build` and `arch_build`, while `os` and `arch` aren't used:
https://github.com/bincrafters/conan-boost_build/blob/stable/1.67.0/conanfile.py#L14
am I missing the point?
/cc @solvingj @grafikrobot

**Comment by grisumbras** [comment]
I just checked. For some reason it was changed in `boost_build/1.68`:
https://github.com/bincrafters/conan-boost_build/blob/stable/1.68.0/conanfile.py#L17

**Comment by SSE4** [comment]
okay, I believe @grafikrobot had a strong reason to change this, let's wait until he replies

**Comment by solvingj** [comment]
I think you are likely correct.  This is a really good catch, thanks so much for finding and reporting it. Will push the fix ASAP.

**Comment by SSE4** [comment]
@grisumbras I've merged required changes to 1.67, 1.68 and 1.69 branches. please give an another try.

**Comment by grisumbras** [comment]
Tested all 3 and they work as expected. Thanks!
