### ISSUE TITLE
conan-icu/stable/62.1 doesn't respect the os.version setting

### ISSUE THREAD

**Issue by malwoden** [bincrafters/community#586]
### Description of Problem, Request, or Question

conan-icu does not respect the os.version setting flag on Macos which is used to set the minimum target sdk. For cmake based builds this will set CMAKE_OSX_DEPLOYMENT_TARGET.

This could be done by setting `-mmacosx-version-min=10.10` on the CFLAGS, CXXFLAGS and LDFLAGS.

I have filed something similar for zlib at https://github.com/conan-community/community/issues/125

### Package Details (Include if Applicable)
* Package Name/Version: **icu/62.1**
* Operating System: **Macos 10.13**
* Compiler+version: **apple-clang: Apple LLVM version 10.0.0**
* Conan version: **conan 1.10.2**
* Python version: **python 3.7**

### Steps to reproduce (Include if Applicable)

`conan create . user/channel -s os.version=10.10  -s arch_build=x86_64 -s arch_target=x86_64 -o icu:shared=False`

When the test binary is build you will see errors from the linker:
`ld: warning: object file (/Users/neil/.conan/data/icu/62.1/user/channel/package/9bb1d69992976860ee3883736c1438bed199ae59/lib/libicuuc.a(ucnv_err.ao)) was built for newer OSX version (10.13) than being linked (10.10)`

This is because the cmake based test package is honouring the os.version setting, but the icu lib itself is not.

**Comment by SSE4** [comment]
@malwoden I've applied required changes, please give an another try

**Comment by malwoden** [comment]
@SSE4 
Tested the latest stable/62.1 (7246f94a) and the warnings are now gone, the flags are now properly passed to the build.

Thanks for the fix.

**Comment by SSE4** [comment]
confirmed as fixed, closing
