### ISSUE TITLE
[libmp3lame] Android debug build not working

### ISSUE THREAD

**Issue by Linux13524** [bincrafters/community#588]
### Description of Problem
Creating a debug package of libmp3lame for Android produces this error:
```
util.c:917:12: fatal error: 'fpu_control.h' file not found
#  include <fpu_control.h>
           ^~~~~~~~~~~~~~~
1 error generated.
```
Creating a release package does work though... The error appears because of the `--enable-debug` option. Any ideas?

### Package Details (Include if Applicable)
* Package Name/Version: **libmp3lame/3.100**
* Operating System+version: **Linux Fedora 29**
* Compiler+version: **Cross compilation: Android NDK r16b Standalone Toolchain**
* Conan version: **conan 1.11.1**
* Python version: **Python 3.7.1**

### Steps to reproduce (Include if Applicable)
`conan create . libmp3lame/3.100@bincrafters/stable -p android_21_armeabi-v7a_clang_l -s build_type=Debug -tf=None`

**Comment by SSE4** [comment]
`fpu_control.h` is part of `glibc`, but probably `bionic` (android C library) misses that header (it's common for NDK to miss some headers or functions). need to check.

**Comment by SSE4** [comment]
NOTE: `--enable-debug` defines `ABORTFP`:
https://github.com/gypified/libmp3lame/blob/f416c19b3140a8610507ebb60ac7cd06e94472b8/configure.in#L947
and this causes `fpu_control.h` to be included (`#ifdef __linux__` path, there is no switch for android):
https://github.com/gypified/libmp3lame/blob/f416c19b3140a8610507ebb60ac7cd06e94472b8/libmp3lame/util.c#L908

**Comment by Linux13524** [comment]
This is how `util.c` gets compiled with `--enable-debug`: 
`/bin/sh ../libtool  --tag=CC   --mode=compile aarch64-linux-android-clang -DHAVE_CONFIG_H  -I. -I.. -I../include -I. -I../mpglib -I..    -O -g -Wall -Wall -pipe  -g -mmmx -msse -fPIC -fPIE -fPIC -I/tmp/android_21_arm64_toolchain/include/c++/4.9.x -MT util.lo -MD -MP -MF .deps/util.Tpo -c -o util.lo util.c`
And this without:
`/bin/sh ../libtool  --tag=CC   --mode=compile aarch64-linux-android-clang -DHAVE_CONFIG_H  -I. -I.. -I../include -I. -I../mpglib -I..  -DNDEBUG  -O3 -Wall -pipe -O3 -mmmx -msse -fPIC -fPIE -fPIC -I/tmp/android_21_arm64_toolchain/include/c++/4.9.x -MT util.lo -MD -MP -MF .deps/util.Tpo -c -o util.lo util.c`

@SSE4 I cannot see the `ABORTFP` you mentioned.

**Comment by SSE4** [comment]
it's defined by `config.h` https://github.com/gypified/libmp3lame/blob/f416c19b3140a8610507ebb60ac7cd06e94472b8/config.h.in#L7
