### ISSUE TITLE
Add mirrors for recipes

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [bincrafters/community#59]
Hello,
We host our recipes for now only on GitHub. It's quite dangerous. Can we support automaticalyy some mirrors? E.g. on GitLab, BitBucket, etc?

**Comment by uilianries** [comment]
This remember me about this article: https://www.wired.com/2015/06/problem-putting-worlds-code-github/

**Comment by uilianries** [comment]
Gitlab FTW !

Okay, I'm Gitlab fan, but I used since old tools, as Google project and Source Forge, until Bitbucket.

Using Gitlab import feature, ALL issues and branches will be copied. Also, it's possible to use "mirror" feature to get updated after each event on Github.

**Comment by solvingj** [comment]
@uilianries that sounds great.  just want to make sure it can continuously discover new repos, since that's a unique problem we have.

**Comment by SSE4** [comment]
checked GitLab, it sounds like a perfect fit. it also easily discovers new repositories. 
I also see someone has taken bincrafters group, is it you @uilianries ? :)

**Comment by uilianries** [comment]
Yes, it's me :)

Both you and @solvingj has maintainer powers.

I have used gitlab for some years, and it could fit well to work like a mirror.

**Comment by SSE4** [comment]
thanks, I'll try to add some scripts to use GitLab/GitHub REST API to set up automatic mirroring of all bincrafters repositories

**Comment by uilianries** [comment]
Thank you! :clap:

**Comment by SSE4** [comment]
I've created first prototype of mirroring script: https://github.com/bincrafters/mirror
started process of mirroring for all out repositories to the GitLab, it will take some time
I'll add cron job on travis once testing shows everything works as expected
any suggestions and comments are appreciated

**Comment by SSE4** [comment]
@Croydon default project visibility is private, that's why you haven't seen any projects. unfortunately, I don't have permissions to change visibility (probably, only @uilianries has as group creator).

**Comment by uilianries** [comment]
@SSE4 checking it now

**Comment by uilianries** [comment]
@SSE4  I just updated your role to Owner (was maintainer)

![gitlab](https://screenshotscdn.firefoxusercontent.com/images/63bc5157-6484-46fd-98b5-30339eec5b2d.png)

**Comment by SSE4** [comment]
@uilianries thanks!
@Croydon please check again, now projects should be public

**Comment by SSE4** [comment]
closing as mirror is done
