### ISSUE TITLE
protoc_installer: Protobuf_PROTOC_LIBRARY can't be found

### ISSUE THREAD

**Issue by Croydon** [bincrafters/community#594]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: protoc_installer/3.5.2
  * Operating System+version: all
  * Compiler+version: all
  * Docker image: all

### Steps to reproduce (Include if Applicable)
When trying to building grpc protoc can't be found:
https://travis-ci.org/inexorgame/conan-grpc/jobs/474514640#L1040

Any ideas what to do?

**Comment by uilianries** [comment]
I need to investigate further, but **libprotoc** is not installed in the package. :mag: 

    conan download -r bincrafters protobuf/3.5.2@bincrafters/stable -p b7da23a1db2bb86d8aba32cc1e0c9e386a2d19bd
    ls ~/.conan/data/protobuf/3.5.2/bincrafters/stable/package/b7da23a1db2bb86d8aba32cc1e0c9e386a2d19bd/lib

**Comment by uilianries** [comment]
Oh wait, **protoc_installer** does not distribute protobuf libraries.

**Comment by Croydon** [comment]
Originally, the grpc recipe only required the protobuf recipe, but I'm assuming this was while the recipe still included protoc. The recent refactoring of the protobuf/protoc_installer packages broke the former grpc recipe revisions and now I tried to add protoc_installer with the above result.

**Comment by Croydon** [comment]
Thanks for the patches, this brings the grpc installation at least further before it fails 😁 🙈 

This patch still needs to be applied to the 3.6.1 release

Thank you so much!

**Comment by uilianries** [comment]
Yes, 3.6.1 uses a different patch from 3.5.x

**Comment by Croydon** [comment]
Alright, then I'm guessing everything is done here, thanks again!
