### ISSUE TITLE
[freetype] RelWithDebInfo build configuration fails.

### ISSUE THREAD

**Issue by hylandnp** [bincrafters/community#597]
### Package & Environment Details:
  * Package Name/Version: **freetype/2.9.0**
  * Operating System+version: **Manjaro Linux 18.0.2**
  * Compiler+version: **gcc-8**
  * Conan version: **conan 1.11.1**
  * Python version: **Python 3.7.1**

### Conan Profile (default):
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=8
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]

### Steps to reproduce:
Add Bintray repo...
```console
conan remote add public-conan https://api.bintray.com/conan/bincrafters/public-conan
```

Then run install command for FreeType...
```console
conan install freetype/2.9.0@bincrafters/stable -s freetype:build_type=RelWithDebInfo --build=missing
```

### Note:
Both Debug and Release builds work for me.

### Logs:
[Build_Log_20190103.txt](https://github.com/bincrafters/community/files/2723523/Build_Log_20190103.txt)

**Comment by SSE4** [comment]
related to the https://github.com/bincrafters/community/issues/567
we need more reliable solution to hit both problems

**Comment by SSE4** [comment]
@hylandnp I've applied required changes to the 2.9.0: https://github.com/bincrafters/conan-freetype/commit/e2e3b3e28d3bab22dd387d539dfa981828cfaaeb
please give an another try

**Comment by hylandnp** [comment]
Tested that commit, built on my local machine (Debug, RelWithDebInfo, and Release mode builds). All stages of package creation (including Conan test step) worked.

No compilation or linking errors reported.

**Comment by SSE4** [comment]
confirmed as fixed, closing
