### ISSUE TITLE
Protobuf/Protoc: CMake files/config/location/target problem

### ISSUE THREAD

**Issue by Croydon** [bincrafters/community#598]
### Package and Environment Details (include every applicable attribute)
  * Package Name: **protobuf**
  * Operating System+version: **all**
  * Compiler+version: **all**

### Steps to reproduce (Include if Applicable)
grpc is searching for protobuf in the testing stages, but errors out with
> CMake Error at CMakeLists.txt:21 (find_package):
  Could not find a configuration file for package "Protobuf" that is
  compatible with requested version "".
  The following configuration files were considered but not accepted:
    /home/conan/.conan/data/protobuf/3.5.2/bincrafters/stable/package/e56189dbbe24b43c2845881775ce71754e788050/lib/cmake/protobuf/protobuf-config.cmake, version: 3.5.2 (32bit)

https://travis-ci.org/inexorgame/conan-grpc/jobs/475032017#L3211

The first thing I'm noticing is that it is searching for CMake files in `lib/cmake/protobuf/protobuf-config.cmake` while, at least on Windows locally, the generated CMake files are in `cmake/` for me instead of `lib/cmake/`.

Are the CMake files just in the wrong location and we should move them?

**Comment by Croydon** [comment]
At a second look, Protobuf itself is placing the CMake files in this path, so we should likely not move them. Maybe we aren't setting some CMake variable/path?

**Comment by Croydon** [comment]
Windows error, same build: https://ci.appveyor.com/project/inexorgame/conan-grpc-xr8rf/builds/21367231/job/oje9qhaarue3fhl9#L5436

**Comment by uilianries** [comment]
Now we have a problem ... both protoc_installer and protobuf generates a bunch of cmake files, including `protobuf::` target. However AFAIK it's not possible to generate the same target name by distinct files, I mean, both protoc_installer and protobuf are not able to generate `protobuf::`, so I opted to rename `protobuf::protoc` to `protoc::protoc`. As protoc_installer and protobuf are totally independent from each other we cant patch any cmake file generated.

**Comment by uilianries** [comment]
Sorry, the target `protobuf::protoc` is correct, however it is available through protoc_installer. So grpc should include `find_package(protoc CONFIG REQUIRED)`.

I'm checking what could be done to solve it on gRPC.

**Comment by Croydon** [comment]
> Sorry, the target protobuf::protoc is correct

Why is AppVeyor saying then that this target doesn't exist? 🤔 

If the target definining is a problem maybe we can do something similar as we are doing in the modular find_boost?
https://github.com/bincrafters/conan-cmake_findboost_modular/blob/stable/1.66.0/FindBoost.cmake#L208

along the lines of this pseudo code...
> if(TARGET protoc::protoc)
    create_target_alias(protobuf::protoc protoc::protoc)
endif()

**Comment by uilianries** [comment]
> Why is AppVeyor saying then that this target doesn't exist? thinking

I think it's because of cmake version:

```
if(CMAKE_SIZEOF_VOID_P AND "8")
  # check that the installed version has the same 32/64bit-ness as the one which is currently searching:
  if(NOT CMAKE_SIZEOF_VOID_P EQUAL "8")
    math(EXPR installedBits "8 * 8")
    set(PACKAGE_VERSION "${PACKAGE_VERSION} (${installedBits}bit)")
    set(PACKAGE_VERSION_UNSUITABLE TRUE)
  endif()
endif()
```

**Comment by Croydon** [comment]
So I decided with https://github.com/inexorgame/conan-grpc/commit/f5efb046f9d77c43a5a664d4edff62f7eb3eabf9 to not cross-compile but rather using the `-x86` containers and split by arch and the error went away.

However, I'm not sure now if these x86 packages are able to run on a x64 system? 🤔

**Comment by uilianries** [comment]
I've applied a patch to make possible to tin x86 on x86_64 but only for cmake, maybe there is something else missing

**Comment by Croydon** [comment]
I can't test this under the same circumstances as back then anymore.

I will close this for now and will re-open another issue if I run into a similar problem in the future.
