### ISSUE TITLE
emsdk_installer - Needs to be finished and refreshed

### ISSUE THREAD

**Issue by solvingj** [bincrafters/community#599]
This package was started, but the builds were never successful.  @tonka3000 just asked about the status, so maybe we can get it working now. 

https://github.com/bincrafters/conan-emsdk_installer

**Comment by SSE4** [comment]
@tonka3000 the reason it failed was extremely long paths on appveyor (> 260 characters), even with conan short paths enabled. emsdk includes nodejs, clang and few other dependencies which are installed inside it, this renders in very long paths. probably, using nodejs, etc. outside of emsdk folder may help, need to try.

**Comment by tonka3000** [comment]
Oh, the path limit in Windows is really painful, always have troubles with it.

**Comment by tonka3000** [comment]
I've started a [node.js recipe](https://github.com/tonka3000/conan-nodejs_installer) because bincrafters has no node.js installer recipe at the moment (and it would be a requirement for emsdk). If you like I would add this to your repos (when it's ready). I dumped it from bincrafters templates repo. The only thing I have not touch are `appveyor.yml` and `.travis.yml` because I never worked with them (I'm a gitlab-ci user). What is the "normal" way to get access to your CI stuff? Or should I register a travis/appveyor client myself?

**Comment by tonka3000** [comment]
appveyor and travis builds are now added

**Comment by SSE4** [comment]
update: I was able to resolve Windows build failures by switching to `nodejs_installer` (it was tricky to get emsdk to skip downloading of nodejs, but I found some ugly way). 
now need to fix Linux builds, and we good to go.

**Comment by SSE4** [comment]
@tonka3000 I've just got successful build for all platforms
for now, it creates the following `.emscripten` config file for me:
```
import os
emsdk_path=os.path.dirname(os.environ.get('EM_CONFIG')).replace('\\', '/')
LLVM_ROOT='' + emsdk_path + '/clang/e1.38.22_64bit'
EMSCRIPTEN_NATIVE_OPTIMIZER='' + emsdk_path + '/clang/e1.38.22_64bit/optimizer.exe'
BINARYEN_ROOT='' + emsdk_path + '/clang/e1.38.22_64bit/binaryen'
PYTHON='' + emsdk_path + '/python/2.7.13.1_64bit/python-2.7.13.amd64/python.exe'
EMSCRIPTEN_ROOT='' + emsdk_path + '/emscripten/1.38.22'
SPIDERMONKEY_ENGINE = ''
NODE_JS = 'node'
V8_ENGINE = ''
TEMP_DIR = '' + emsdk_path + '/tmp'
COMPILER_ENGINE = NODE_JS
JS_ENGINES = [NODE_JS]
```
so, it appears to be fully portable, as long as you have `EM_CONFIG` environment variable properly set (which recipe currently does at https://github.com/bincrafters/conan-emsdk_installer/blob/stable/1.38.22/conanfile.py#L92)
so in theory, it should be portable, if it's not, please lemme know and I will investigate it.

the next steps would be:
- do some testing of `emsdk_installer`
- try to build with it some of conan packages of various nature, like CMake one (e.g. `gtest`), autotools one (e.g. `libiconv`), and some custom (e.g. `boost`)
- add first-class emscripten support to the conan itself, it means define new `os` and `arch` in `settings.yml`, ensure build helpers (like `CMake` and `AutoToolsBuildEnvironment`) work properly with it, etc.

**Comment by SSE4** [comment]
@tonka3000 I've did some testing, and I was able to build some conan packages with the following profile:
```
[settings]
os=Emscripten
arch=asm.js
os_build=Linux
arch_build=x86_64
compiler=clang
compiler.version=6.0
compiler.libcxx=libc++
[options]
[build_requires]
emsdk_installer/1.38.22@bincrafters/stable
[env]
```
packages I was able to build:

- gtest
- libiconv (conan needs fix for GNU triplet for emscripten, so I've specified manually)
- libiconv
- zlib
- bzip2
- boost (small fix to recipe was required to recognize new arch)

I think we're now good to go with requesting official support in conan. WDYT?

**Comment by SSE4** [comment]
I think it's updated, so I am closing this issue for now
