### ISSUE TITLE
include glfw examples in test_package

### ISSUE THREAD

**Issue by danimtb** [bincrafters/community#6]
## Description

Feature Request:

I have made my first steps on using conan and took glfw examples to consume your glfw package.
I took apart the examples of the glfw library as well as the ```deps``` folder and then tuned the ```CMakeLists.txt``` to include the conan specifics (https://github.com/danimtb/glfw_examples)

I have only tested the examples in Windows, Visual Studio 15. However, I think it could be a good starting point to include the examples inside test_package of the glfw conan package. I would like to ask about the community opinion about this and what would be the best approach to do so.

BTW, thank you for creating the glfw package!
### package

glfw/3.2.1@bincrafters/stable (https://github.com/bincrafters/conan-glfw)

### Extra information

* Conan version: **v0.29.1**
* Operating System: **Windows**
* Compiler+version: **Visual Studio 15**

**Comment by uilianries** [comment]
Hi!

Your usage is okay, you are using conanfile.txt.

You could improve you implementation by replacing .txt to conanfile.py and invoke all cmake commands on your recipe.

For now, you mentioned to use:
```
mkdir build
cd build
conan install ..
cmake .. -G "Visual Studio 15 Win64"
cmake --build . --config Release
```

However, using conanfile.py you will be able to replace such block by only a statement:
```
$ conan create
```

Regards!

**Comment by danimtb** [comment]
Hi @uilianries
Thanks for your prompt feedback!

I have migrated it to a ```conanfile.py``` and it is working now with less build steps:

```
conan install . --install-folder build
conan build . --build-folder build
```

However I can't build the examples using ```glfw:shared=False```. Might be related to cmake flags.

**Comment by dimi309** [comment]
For static linking (glfw:shared=False) target_link_libraries to CONAN_LIBS is very important. I've noticed you only do it for particles. I don't know if this is the issue but, if not, what error are you getting?

**Comment by danimtb** [comment]
Yeah, that was it. I have just pushed the changes to my repo.

Will work on a PR to improve the tests with this!

**Comment by dimi309** [comment]
Great thanks! And I forgot to mention, it's also good to always add:

`set_target_properties(executable PROPERTIES LINK_FLAGS "${CONAN_EXE_LINKER_FLAGS}")`

That can also contain useful information.

**Comment by solvingj** [comment]
I don't want to discourage contributions or making packages better, but I want to say that regarding `test_packages`, we try to keep them lean because they tend to be brittle (just like unit tests).  The more code we add, the more brittle the test.  

However, I think examples on using packages are good, and even Conan team wanted to see this, so I would support discussion of a new convention...  A new folder in the template repo called "example", similar to test_package, but which we can make as extensive as we like, but don't care if it breaks because it won't break CI for future versions.  @dimi309 @uilianries what do you think?

**Comment by dimi309** [comment]
I tend to agree with @solvingj . A long series of tests and examples would probably make test_package too heavy and fragile. However I am not sure if @danimtb meant this, or just a bit more code to make package usage more obvious. I sometimes only add an include statement and a basic assignment but I consider myself lazy for doing so 😄 
About the example folder, it might be a bit risky. We might end up with a folder in each package with code that rarely gets executed, becomes stale over time, and maybe we will end up doing the work that tutorials, articles and the original library developer is / should be doing in the first place...

**Comment by uilianries** [comment]
I'm convinced that is a edge case.

Our goal is provide a conan recipe. Indeed, test_package is only proposed to make sure that our package is fine.

If I want to collect examples and tests, I search for the original project, where all examples and unit test should be. 

Finally, I don't see much value aggregating new examples in the recipe repository. Also, who wants to read an example could be confused when need to check two distinct repositories with similar files -- in this case the examples are not centralized and they respected to original project.

**Comment by dimi309** [comment]
Sounds, good, if we all agree.
And by the way thanks for removing my guilt for my very short package tests 🤣

**Comment by dimi309** [comment]
Btw is this issue resolved now? Should we close it?

**Comment by uilianries** [comment]
Please, wait for @danimtb comments

**Comment by dimi309** [comment]
Of course

**Comment by solvingj** [comment]
fair enough, i agree .  i never like copying code knowing that won't be maintained, and is redundant to the actual source.

**Comment by danimtb** [comment]
Yes, I see what you mean and I agree examples could break easily and adding all of them could be too much.

I still think we could add a better test just to make sure the library is linkable in both static and shared options.

**Comment by danimtb** [comment]
I would try to create a PR improving the current test for this package so I think this issue could be closed. Thanks!

**Comment by dimi309** [comment]
Thanks again for this contribution @danimtb !

https://github.com/bincrafters/conan-glfw/commit/f0343e93d70ccb978718fd2d90cdab02d3cb8abb
