### ISSUE TITLE
log4cplus: add branch for version 2.0.0

### ISSUE THREAD

**Issue by malirod** [bincrafters/community#60]
## Description
Log4cplus maintains a few versions simultaneously. Version  2.0.0 is for c+11 [see](https://github.com/log4cplus/log4cplus/releases)
To send a PR with recipe branch should be created first.

**Comment by solvingj** [comment]
Sorry for the delayed response.  We will work on this soon.

**Comment by solvingj** [comment]
assigning to see if someone can fix builds on appveyor and then bump version.

**Comment by malirod** [comment]
@solvingj , is it possible to just create empty branch? My intent was to sent a PR with v2.0.0 support. I just cannot do this without a branch.

**Comment by r-darwish** [comment]
@malirod that's a problem I often encounter here. The only solution I know is to ask a collaborator to create a branch before you make the pull request.

If you have a working version in your fork then I can create a 2.0.0 branch to which you can open your pull request. Would you like me to do that?

**Comment by solvingj** [comment]
In this case I would prefer we fix the current branch first.

**Comment by r-darwish** [comment]
I'll look into that

**Comment by malirod** [comment]
@r-darwish , 
>>  ask a collaborator
This is why I've created this ticket. Is any other to ask collaborator?

I have working  2.0.0 in my fork, but it slightly adjusted and not suitable for PR directly. My plan was to prepare suitable version but I've stuck on absence of destination branch.

**Comment by solvingj** [comment]
@malirod I've created a testing/2.0.0 branch, but it's currently not building on CI.  Sorry for the delay.

**Comment by r-darwish** [comment]
The exact problem seems [here](https://github.com/log4cplus/log4cplus/blob/REL_1_2_0/ConfigureChecks.cmake#L48). When cross-compiling from 64 bit to 32 bit it resolves `LIBRT` to `/usr/lib/librt.so`. However, it should resolve to `/usr/lib32/librt.so`. I'm not sure what's the proper solution.

**Comment by SSE4** [comment]
seems like related to the https://github.com/conan-io/conan/pull/2458
I am also awaiting this to be merged for SDL and other packages

**Comment by solvingj** [comment]
Wow, great work

**Comment by r-darwish** [comment]
@solvingj in the meantime we can disable 32 bit builds. What do you think?

**Comment by solvingj** [comment]
Perhaps this can be solved by using the x86 docker images created by @uilianries .

**Comment by r-darwish** [comment]
I suppose so. This issue is probably only relevant when cross-compiling from 64 to 32

**Comment by solvingj** [comment]
trying now

**Comment by r-darwish** [comment]
I pushed a [commit ](https://travis-ci.org/r-darwish/conan-log4cplus/jobs/341103178) without cross compiling. Let's see if this works. The next step is to compile 32 in the designated Docker images

**Comment by solvingj** [comment]
Ok, after asking the maintainer about a 1.2.1 release, he pushed a new release tag that was meant to be pushed a few weeks ago.  So, due to other issues in 1.2.0 discovered by @SSE4, we're ditching 1.2.0 and making 1.2.1 our first release. 

We currently have a stable/1.2.1 that is working. 

As for 2.0.0, the current latest release is 2.0.0-RC2, and currently we have a build failure on that.  It looks like it's taken a new dependency on a submodule for `ThreadPool.h` .  perhaps i can work on this tomorrow. 

Despite it being trivially small, I think we would package that library separately and depend on it via conan `requires`.

**Comment by malirod** [comment]
log4cplus uses submodules.
On my opinion the easiest way is to get log4cplus not from github but from sourceforge where full packages are stored: `https://downloads.sourceforge.net/project/log4cplus/log4cplus-stable/2.0.0/log4cplus-2.0.0-rc2.zip`

In my fork I've made a recipe which uses such approach: https://github.com/malirod/conan-log4cplus .

**Comment by solvingj** [comment]
@malirod there seems to be several breaking changes in the 2.0.0-rc2.  I tried your recipe and the `test_package` is currently broken due to the removal of the `conanfile_directory` variable.  I would like to hold off on packaging 2.0.0 until it is an official release (no longer rc2).

**Comment by solvingj** [comment]
@malirod good news, i did not realize that the sourceforge packages contained the git-submodules.  i've now switched the source method for 2.0.0-rc2 to pull from sourceforge and it build with no issue.  The CI is running now, hopefully you can test out the package when done and let us know if it works for you.

**Comment by SSE4** [comment]
seems like log4cplus hangs on exit, in thread pool waiting for jobs. might be related to one of these issues:
https://github.com/log4cplus/log4cplus/issues/285
https://github.com/log4cplus/log4cplus/issues/102
https://github.com/log4cplus/log4cplus/issues/251
https://github.com/log4cplus/log4cplus/issues/245
https://github.com/log4cplus/log4cplus/issues/146

**Comment by solvingj** [comment]
finally done. 2.0.0-rc2 required a different initialization in the test_package.

**Comment by malirod** [comment]
@solvingj great job! I think this issue can be closed.
