### ISSUE TITLE
conan-templates: Appveyor MAX_PATH length error

### ISSUE THREAD

**Issue by helmesjo** [bincrafters/community#601]
### Question Description
I'm (apparently) running into the MAX_PATH length issue when building [my recipe for Corrade](https://github.com/helmesjo/conan-corrade) for Windows. See failing build [here](https://ci.appveyor.com/project/helmesjo/conan-corrade/build/job/3lhkewwx4jpxtkoy#L587) (line 587). I used the [conan-templates](https://github.com/bincrafters/conan-templates) repo as base.

Anyone else got experience with this, and perhaps a workaround?

Thanks!

**Comment by Croydon** [comment]
You just need to add `short_paths=True` to the recipe like this:
https://github.com/inexorgame/conan-grpc/blob/33ec50c063c227491d43a0a4cc6aa188a450d8ba/conanfile.py#L18

**Comment by helmesjo** [comment]
Thanks, that did the trick!

And yeah, definitively! I actually I have a few more (thrift, aeron, winflexbison, gnu-m4, cucumber-cpp) that I've planned to suggest for inclusion into bincrafters. All using conan-templates as base so they should be _somewhat_ ok quality wise.

**Comment by helmesjo** [comment]
Ah, nice!
