### ISSUE TITLE
[protoc_installer] CMake variable PROTOBUF_PROTOC_EXECUTABLE isn't set?

### ISSUE THREAD

**Issue by Croydon** [bincrafters/community#604]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **protoc_installer/3.6.1**

### Steps to reproduce (Include if Applicable)
For Inexor I have added the protoc_installer package and it seemingly builds successfully. 
Later when we try to execute protoc like this: https://github.com/inexorgame/inexor-core/blob/master/inexor/network/require_run_gluegen.cmake#L99
it fails with 
> Rendering C++ GlueGen file completed.
/bin/sh: 1: PROTOBUF_PROTOC_EXECUTABLE-NOTFOUND: not found
inexor/server/CMakeFiles/inexor-core-server.dir/build.make:61: recipe for target 'inexor/network/inexor-core-server/RPCBindingandContext.gen.cpp' failed
make[2]: *** [inexor/network/inexor-core-server/RPCBindingandContext.gen.cpp] Error 127
make[2]: *** Deleting file 'inexor/network/inexor-core-server/RPCBindingandContext.gen.cpp'
CMakeFiles/Makefile2:887: recipe for target 'inexor/server/CMakeFiles/inexor-core-server.dir/all' failed
make[1]: *** [inexor/server/CMakeFiles/inexor-core-server.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 42%] [32m[1mLinking CXX static library ../../lib/libmodule_ui.a[0m
[ 42%] Built target module_ui
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

So another CMake config error?

Our code didn't change and worked with older revisions of the protobuf recipe, when protoc was directly included.

### Logs (Include/Attach if Applicable)
e.g.
https://travis-ci.org/inexorgame/inexor-core/jobs/475814935
https://api.travis-ci.org/v3/job/475814935/log.txt

**Comment by uilianries** [comment]
Again the problem is related to `find_package(protoc)`. The definition PROTOBUF_PROTOC_EXECUTABLE is available in lib/cmake/protoc/protoc-module.cmake.

Maybe we need to create some alias in protobuf package to find it from protoc package.

**Comment by uilianries** [comment]
Hi @Croydon !

Do you know after moving protoc and protobuf to the same repo, this error continued?

I checked the cmake files generated by the project, `PROTOBUF_PROTOC_EXECUTABLE` can be found in `<package_folder>/lib/cmake/protoc/protoc-module.cmake`

**Comment by Croydon** [comment]
Closing for now as I can't retest under the same configurations.

I will open a new issue if I should have troubles with this in the future.

@uilianries Thanks for having a look! 😄
