### ISSUE TITLE
bincrafters-conventions: Add detection if a recipe is using deprecated/removed method calls

### ISSUE THREAD

**Issue by Croydon** [bincrafters/community#605]

**Comment by Croydon** [comment]
Starting with Conan >= 1.0, before that it is history 😄

**Comment by uilianries** [comment]
https://docs.conan.io/en/latest/faq/conan1.0.html#deprecations-removals

https://docs.conan.io/en/latest/reference/tools.html#tools-build-sln-command-deprecated
https://docs.conan.io/en/latest/reference/tools.html#tools-msvc-build-command-deprecated
https://docs.conan.io/en/latest/reference/build_helpers/cmake.html#build-type-deprecated
https://docs.conan.io/en/latest/reference/generators/gcc.html#gcc
https://docs.conan.io/en/latest/integrations/boost_build.html#boost-build-logo-boost-build

**Comment by Croydon** [comment]
I'm just noticed that I wrote something else as I had in mind. 

I would actually suggest to only check for stuff what got deprecated in versions > 1.0, instead of >= 1.0.

I don't think that it matters what got removed before 1.0, because I guess there aren't really many recipes where it would matter
