### ISSUE TITLE
Protobuf - Cannot compile with Android ndkr18 with clang

### ISSUE THREAD

**Issue by ghost** [bincrafters/community#609]
### Package and Environment Details (include every applicable attribute)
os=Android
compiler=clang
compiler.version=6.0
compiler.libcxx=None
build_type=Debug
standalone_toolchain=PATH_TO_NDK_r18b

### Question Description
Hello

It is my first post here so please apologise me if I am not using the correct guidelines.

I am trying to compile protobuf with conan with the android ndk18 as explained on this blog:
https://blog.conan.io/2018/02/13/Android-Studio-project-Conan-Boost.html

It works fine with ndkr17, but with ndkr18, it fails for the protobuf package. The others packages work fine.
Basically I get an error that looks like this:
```
    Android: Did not detect API level from
      /Users/raphael/.conan/data/android-toolchain/r17/pixcap/dev/package/30b655527b868228ed236efb7f8e78943bdee163/bin/clang
    or
      /Users/raphael/.conan/data/android-toolchain/r17/pixcap/dev/package/30b655527b868228ed236efb7f8e78943bdee163/sysroot/usr/include/android/api-level.h
  
  Call Stack (most recent call first):
    /usr/local/Cellar/cmake/3.13.2/share/cmake/Modules/CMakeDetermineSystem.cmake:130 (include)
    CMakeLists.txt:2 (project)
  
  
  CMake Error at conanbuildinfo.cmake:360 (message):
    Incorrect 'clang' version 'compiler.version=6.0' is not the one detected by
    CMake: 'Clang=7.0'
  Call Stack (most recent call first):
    conanbuildinfo.cmake:425 (conan_error_compiler_version)
    conanbuildinfo.cmake:501 (check_compiler_version)
    conanbuildinfo.cmake:119 (conan_check_compiler)
    CMakeLists.txt:5 (conan_basic_setup)
```

Basically it seems to be overwriting the clang version to use, while ndk only provides 6.0.
Has anyone else experience some issues with ndkr18?

**Comment by SSE4** [comment]
user seems to be deleted from GitHub :(
anyway, to provide an answer just in case:

- as Android NDK r18 uses Clang 7, profile should point to the Clang 7 as well. the easiest way to fix is to run `conan profile update default -s compiler.version=7.0`
- another way to bypass an issue, is to disable this compiler check by passing `-D CONAN_DISABLE_CHECK_COMPILER=1` to the CMake
