### ISSUE TITLE
For log4cplus please add Linux clang 6 binaries

### ISSUE THREAD

**Issue by SebastianMosiej** [bincrafters/community#612]
### Description of Problem, Request, or Question
For log4cplus please add Linux clang 6 binaries

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **log4cplus/2.0.***
  * Operating System+version: **Linux Ubuntu 16.04**
  * Compiler+version: **clang 6.0**
  * Conan version: **Conan 1.11.0**
  * Python version: **Python 3.7.0**

**Comment by SSE4** [comment]
@SebastianMosiej I think now it's done, Clang 6 & 7 builds were added

**Comment by uilianries** [comment]
@SSE4 Some builds failed on stable channel:

https://travis-ci.com/bincrafters/conan-log4cplus/builds/98153500
https://ci.appveyor.com/project/BinCrafters/conan-log4cplus/builds/21802181
https://ci.appveyor.com/project/BinCrafters/conan-log4cplus/builds/21802167

I can restart, but today our CI service will be very busy (modular Boost).

**Comment by uilianries** [comment]
Only one last red job:

https://travis-ci.com/bincrafters/conan-log4cplus/jobs/172072571
