### ISSUE TITLE
sdl2_ttf. Incorrect use of source() conditioned on settings.

### ISSUE THREAD

**Issue by memsharded** [bincrafters/community#613]
https://github.com/bincrafters/conan-sdl2_ttf/blob/stable/2.0.14/conanfile.py
is using a ``source()`` method conditioned on compiler. 

This shouldn't be done, as it can produce errors:

### Steps to reproduce (Include if Applicable)
```
$ git clone https://github.com/bincrafters/conan-sdl2_ttf
$ cd conan-sdl2_ttf
$ conan create . user/testing -s compiler=gcc -s ....
# The source() method will run, not fixing Visual Studio
$ conan create . user/testing -s compiler="Visual Studio"
# Fails
```

``source()`` method shouldn't use conditionals based on settings or options. That logic should be moved to the ``build()`` method.

**Comment by uilianries** [comment]
Yes, Dani commented the same case for other package some time ago. Thanks for reporting this one.
