### ISSUE TITLE
Inclusion Request of nanomsg into Conan Center

### ISSUE THREAD

**Issue by danimtb** [bincrafters/community#615]
### Package Details
  * Package Name: **nanomsg/1.1.2@bincrafters/stable**
  * Conan recipe repository: **https://github.com/bincrafters/conan-nanomsg**

Hi guys!

Here are some of the missing points to get this package included:

- [x] Package license: no license is being collected from the library.
- [x] Bintray properties: Labels and maturity.
- [x] Remove outdated packages.
- [x] Seems this is recipe packages a C library so ``libcxx`` should be removed:
  ```
  def configure(self):
      del self.settings.compiler.libcxx
  ```

cc/ @Croydon

**Comment by uilianries** [comment]
Thanks for reporting! I'll update this one soon.

**Comment by uilianries** [comment]
Hi @danimtb !

nanomsg is up-to-date!

https://bintray.com/bincrafters/public-conan/nanomsg%3Abincrafters

![](https://screenshotscdn.firefoxusercontent.com/images/42af7461-8289-45fa-b19c-3104e4a628bb.png)

![](https://screenshotscdn.firefoxusercontent.com/images/455d9720-d940-4677-8719-3bb0f3210fdb.png)

**Comment by danimtb** [comment]
Included in conan center. Thanks!

**Comment by Croydon** [comment]
Thanks for taking care!
