### ISSUE TITLE
gsl_microsoft/20180102 causes errors compared to gsl_microsoft/2.0.0

### ISSUE THREAD

**Issue by acgetchell** [bincrafters/community#616]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **gsl_microsoft/20180102**
  * Operating System+version: **Linux Ubuntu 16.04**, **macOS 10.13**
  * Compiler+version: **Ubuntu 16.04 + gcc-8.2**, **Ubuntu 16.04 + clang-6.0**, **macOS 10.13 + Apple LLVM 10.0.0 (clang-1000.11.45.5)**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)

Depends on job, see https://travis-ci.org/acgetchell/CDT-plusplus/builds/482636050

### Steps to reproduce (Include if Applicable)
Use latest version of gsl_microsoft in Conan. Possibly an upstream issue. Generates
`error: no matching function for call to 'index(int)'` when `gsl::index` is used.

### Logs (Include/Attach if Applicable)

https://travis-ci.org/acgetchell/CDT-plusplus/jobs/482636051#L1359

Note that reverting to gsl_microsoft/2.0.0 fixes the problems.

https://travis-ci.org/acgetchell/CDT-plusplus/builds/482717209

**Comment by SSE4** [comment]
@acgetchell  `20180102` is an older version, before 2.0 and even 1.0. any reason to using it, if 2.0 works for you?

**Comment by acgetchell** [comment]
I think the reason it was used is because I had `gsl_microsoft/[>=2.0]@bincrafters/stable` in my `conanfile.py` and with that naming convention it is picked up instead of 2.0.

So I suppose until `gsl` goes to version 3, these older versions will be picked over the latest.

**Comment by SSE4** [comment]
oh, that's unfortunate. is it an option to specify an exact version?

**Comment by acgetchell** [comment]
Yes, I've gone back to specifying 2.0 directly.
