### ISSUE TITLE
[bincrafters-package-tools] Package not found anymore

### ISSUE THREAD

**Issue by helmesjo** [bincrafters/community#617]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **pthreads4w/2.9.1**
  * Operating System+version: **Windows**
  * Compiler+version: **Visual Studio-14/15**
  * Conan version: **Conan 1.11.2**

### Question Description
For some reason, my windows builds [stopped finding `pthreads4w/2.9.1@bincrafters/stable`](https://ci.appveyor.com/project/helmesjo/conan-aeron/build/job/rgk3y8462kep67tc#L371) on bincrafters/public-conan, but only on Appveyron, locally it works (same settings so I'm guessing it's the same package).
I even tried re-running old (passing) builds and they failed as well.

My appveyron script does have [bincrafters added to `CONAN_REMOTES`](https://github.com/helmesjo/conan-aeron/blob/44689093a1c266690851b5701c8d96ba82817a12/appveyor.yml#L12) (nothing has changed in this file since when it did work). Though I have no space after the comma [as in the examples](https://github.com/conan-io/conan-package-tools#working-with-bintray-configuring-repositories) (but again, this worked before).

The last passing build was [around 15 days ago](https://ci.appveyor.com/project/helmesjo/conan-aeron/builds/21428201/job/umbm3a99tauf96qt#L343), but notice that it found it in `remote1`. In the failing build there is no `remote1`, only `remote0`. Has something changed in conan-package-tools perhaps that messed up my additional remotes? @lasote

Not positive this has to do with bincrafters per se, hence a question. :)

**Comment by uilianries** [comment]
Did you upload some version of pthreads4w to your CONAN_UPLOAD address?

**Comment by helmesjo** [comment]
No, there is no `pthreads4w` in [my repository](https://bintray.com/helmesjo/public-conan)... 🤔

**Comment by uilianries** [comment]
I asked because the upload_repo is the first remote where Conan searches for the package reference. So if you uploaded at some time, maybe your problem could be related to this.

Looks like I've introduced a new bug in bincrafters-package-tools: https://ci.appveyor.com/project/helmesjo/conan-aeron/build/job/rgk3y8462kep67tc#L261 :man_facepalming: 

It's related to https://github.com/bincrafters/community/issues/506

**Comment by helmesjo** [comment]
> I asked because the upload_repo is the first remote where Conan searches for the package reference. So if you uploaded at some time, maybe your problem could be related to this.

How do you mean exactly? If I uploaded to that repo at one point (AKA there is a `pthreads4w` package), how would that give the current behavior (it works locally but not remotely)?

**Comment by uilianries** [comment]
I didn't check the logs before. The upload_repo should be the first remote to be checked when searching a package, so if you have different build environments for CI and local, it could happen when finding  pthreads4w in your remote repo, but windows built package could be missing there.

**Comment by helmesjo** [comment]
Alright. Anyways, I have no `pthreads4w` package in my repository.

**Comment by helmesjo** [comment]
Got another build having [the same issue](https://ci.appveyor.com/project/helmesjo/conan-magnum/builds/21755749/job/folcnffj43h9t662#L347), now for package `sdl2/2.0.8@bincrafters/stable`.

Anyone known changes regarding `CONAN_REMOTES`? @lasote @memsharded

**Comment by uilianries** [comment]
As I said before, it's a bug from bincrafters-package-tools!

https://ci.appveyor.com/project/helmesjo/conan-magnum/builds/21755749/job/folcnffj43h9t662#L272

I'll fix asap

**Comment by uilianries** [comment]
Ops!

Seems like sdl2/2.0.8@bincrafters/stable was removed :eyes:

**Comment by helmesjo** [comment]
> As I said before, it's a bug from bincrafters-package-tools!
> 
> https://ci.appveyor.com/project/helmesjo/conan-magnum/builds/21755749/job/folcnffj43h9t662#L272
> 
> I'll fix asap

Ah, ok! Didn't read completely. :) Just ping me when it's fixed and I'll retry!

**Comment by uilianries** [comment]
Hi! @helmesjo 

A newest version is available with a fix for your case:

https://pypi.org/project/bincrafters-package-tools/0.17.8/

Please, re-run your broken jobs. Thanks for finding this bug!

**Comment by helmesjo** [comment]
Yes, they appear to be building correctly. :)

Thanks!
