### ISSUE TITLE
Inclusion Request of cppnanomsg into Conan Center

### ISSUE THREAD

**Issue by danimtb** [bincrafters/community#618]
### Package Details
  * Package Name: **cppnanomsg/20181216@bincrafters/stable**
  * Conan recipe repository: **https://github.com/bincrafters/conan-cppnanomsg**

- Missing package license. Please include the original library in the Conan packages.

P.S. No big deal 🤣

cc/ @Croydon

**Comment by uilianries** [comment]
@danimtb cppnanomsg is ready!

https://bintray.com/bincrafters/public-conan/cppnanomsg%3Abincrafters

![](https://screenshotscdn.firefoxusercontent.com/images/44930f65-f2b1-4fdc-a920-3a9b91a0bf9b.png)

**Comment by Croydon** [comment]
cppnanomsg is now in conan-center https://bintray.com/bincrafters/public-conan/cppnanomsg%3Abincrafters

Thanks for pushing this forward. I will become more active in mid-February again 😄
