### ISSUE TITLE
Upstream Update: FreeType 2.9.1

### ISSUE THREAD

**Issue by Croydon** [bincrafters/community#621]
### Package Details
  * Package Name: Freetype
  * Latest available Version: 2.9.1

The above mentioned version is newly released by the upstream project and not yet available within Bincrafters. Please add this version.

**Comment by uilianries** [comment]
Done!

https://bintray.com/bincrafters/public-conan/freetype%3Abincrafters/2.9.1%3Astable

![freetype/2.9.1@bincrafters/stable](https://screenshotscdn.firefoxusercontent.com/images/b1d858f9-882f-4b24-9176-4613bb54de79.png)
