### ISSUE TITLE
Inclusion Request: tinytoml

### ISSUE THREAD

**Issue by ehargitt** [bincrafters/community#623]
### Package Details
  * Package Name: **tinytoml**
  * Operating Systems+versions: **Linux Ubuntu 16.04, Ubuntu 18.04, Windows**, header only
  * Compiler support: **VS15, clang5**
  * Conan recipe repository: **https://github.com/ehargitt/conan-tinytoml**

### Inclusion request
  * Fill all checkboxes with x if you agree with the statement or if it applies to your Conan recipe
  * [X] I want that my Conan recipe is getting included into the Bincrafters organisation
  * [X] I understand that if my request is accepted we are cloning your repository with all its history into Bincrafters, adapt some configurations and meta data if needed, and publishing it under the Bincrafters name and accounts
  * [X] I have used the Bincrafters templates to develop my Conan recipe - https://github.com/bincrafters/conan-templates
  * [X] My Conan recipe and all parts of it are licensed under the MIT license - https://choosealicense.com/licenses/mit/
    * Bincrafters are releasing all recipes under MIT license. If you want to have your recipe within Bincrafters we kindly ask you to do the same
    * it is okay if your test_package contains code from the upstream project under the upstream project's license, as long as it is clearly mentioned within the test_package files
  * [X] My Conan recipe covers (at least) the latest stable version which is available for the package
  * [X] I know that my Conan recipe is working on all operating system and compilers mentioned above right now
    * if not: please provide here links to your CI platforms and / or build logs and describe the problems you encounter
  * [X] I'm willing to help to maintain the recipe even after it is included into Bincrafters

### Checklist for the Bincrafters team
  * Ignore this if you are not part of the Bincrafters team
  * [ ] There is no such Conan package yet in conan-center, conan-community or Bincrafters
  * [ ] The project is either popular or deserves to be maintained for another good reason (we can't package every single project out there)
  * [ ] [bincrafters-conventions](https://github.com/bincrafters/bincrafters-conventions) reports no complains; the recipe fulfills our general quality requirements and conventions
  * [ ] The recipe is cloned into our organisation; CI is enabled and configurated and succeeds
  * [ ] There is a branch protection rule for `stable/*` branches, which requires a pull request with at least one approval first before things can get published
  * Considering granding the inclusion request author push rights to the recipe repository (there is no guarantee that everyone is getting push rights, we decide this on a case-to-case base)

**Comment by uilianries** [comment]
Looks amazing! I gonna copy your project

**Comment by ehargitt** [comment]
Perfect! Let me know what else I need to do.

**Comment by uilianries** [comment]
Done! Also, I've request the inclusion on Conan Center!

All commits from your authority were preserved as well.

Thanks for providing this recipe!

https://github.com/bincrafters/conan-tinytoml
https://bintray.com/bincrafters/public-conan/tinytoml%3Abincrafters

![tinytoml/0.4@bincrafters/stable](https://screenshotscdn.firefoxusercontent.com/images/e12e3576-6143-467f-8caf-f40b2126af07.png)
