### ISSUE TITLE
[libcurl] Support Mingw cross-compiling from Linux to Windows

### ISSUE THREAD

**Issue by nathan-fps** [bincrafters/community#626]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libcurl/7.61.1**
  * Operating System+version: **Linux Fedora 29**
  * Compiler+version: **gcc-8**
  * Conan version: **Conan 1.8.3**
  * Python version: **Python 3.7.2**

### Description of your feature
Would be nice to be able to cross-compile libcurl on Linux targetting Windows using Mingw. Currently, this fails with the following error:
```
ERROR: libcurl/7.50.3@bincrafters/stable: Error in build() method, line 133
        self.build_with_autotools()
while calling 'build_with_autotools', line 351
        self.run('./buildconf', win_bash=self.is_mingw)
        ConanException: Command only for Windows operating system
```

**Example profile:**
```
standalone_toolchain=/usr/x86_64-w64-mingw32
target_host=x86_64-w64-mingw32
cc_compiler=gcc
cxx_compiler=g++

[settings]
arch_build=x86_64
os_build=Linux
compiler=gcc
compiler.version=8
compiler.libcxx=libstdc++11
os=Windows
arch=x86_64
build_type=Release

[env]
CONAN_CMAKE_FIND_ROOT_PATH=$standalone_toolchain/sys-root
CHOST=$target_host
AR=$target_host-ar
AS=$target_host-as
RANLIB=$target_host-ranlib
CC=$target_host-$cc_compiler
CXX=$target_host-$cxx_compiler
LD=$target_host-ld
STRIP=$target_host-strip
RC=$target_host-windres
```

**Comment by theirix** [comment]
Thank you for the report! I will look at the issue soon.

**Comment by SSE4** [comment]
@nathan-fps we have applied required changes, please give an another try

**Comment by theirix** [comment]
Merged to stable/7.56.1. Conan package is published and available now.

**Comment by nathan-fps** [comment]
Great thanks folks! libcurl is building for me now :)

**Comment by Godrigos** [comment]
Almost 3 years latter I'm having a "similar" issue cross compiling from Linux to Windows.

**Package and Environment Details (include every applicable attribute)**
* Package Name/Version: libcurl/7.80.0
* Operating System+version: Ubuntu 20.04
* Compiler+version: gcc-9
* Conan version: Conan 1.43.1
* Python version: Python 3.8.10

`
configure: error: --enable-unix-sockets is not available on this platform!
libcurl/7.80.0: 
libcurl/7.80.0: ERROR: Package '19499a6264c1b0421a02e30db04515315404dea0' build failed
libcurl/7.80.0: WARN: Build folder /home/rodrigo/.conan/data/libcurl/7.80.0/_/_/build/19499a6264c1b0421a02e30db04515315404dea0
ERROR: libcurl/7.80.0: Error in build() method, line 218
        self._build_with_autotools()
while calling '_build_with_autotools', line 424
        autotools, autotools_vars = self._configure_autotools()
while calling '_configure_autotools', line 462
        self._autotools.configure(vars=self._autotools_vars, args=configure_args)
        ConanException: Error 1 while executing ./configure '--with-libidn2=no' '--with-librtmp=no' '--with-libpsl=no' '--with-schannel=no' '--with-secure-transport=no' '--with-brotli=no' '--enable-shared=no' '--enable-static=yes' '--enable-dict=yes' '--enable-file=yes' '--enable-ftp=yes' '--enable-gopher=yes' '--enable-http=yes' '--enable-imap=yes' '--enable-ldap=no' '--enable-mqtt=yes' '--enable-pop3=yes' '--enable-rtsp=yes' '--enable-smb=yes' '--enable-smtp=yes' '--enable-telnet=yes' '--enable-tftp=yes' '--enable-debug=no' '--enable-ares=no' '--enable-threaded-resolver=no' '--enable-cookies=yes' '--enable-ipv6=yes' '--enable-manual=no' '--enable-verbose=yes' '--enable-symbol-hiding=no' '--enable-unix-sockets=yes' '--with-ssl=/home/rodrigo/.conan/data/openssl/1.1.1l/_/_/package/344886eda55829e935447d0708e3b993938b32c8' '--without-wolfssl' '--without-libssh2' '--without-nghttp2' '--with-zlib=/home/rodrigo/.conan/data/zlib/1.2.11/_/_/package/344886eda55829e935447d0708e3b993938b32c8' '--with-zstd=no' '--prefix=/home/rodrigo/.conan/data/libcurl/7.80.0/_/_/package/19499a6264c1b0421a02e30db04515315404dea0' '--bindir=${prefix}/bin' '--sbindir=${prefix}/bin' '--libexecdir=${prefix}/bin' '--libdir=${prefix}/lib' '--includedir=${prefix}/include' '--oldincludedir=${prefix}/include' '--datarootdir=${prefix}/share' --build=x86_64-linux-gnu --host=x86_64-w64-mingw32
`
