### ISSUE TITLE
yaml-cpp/0.6.2 Debug works fine, release doesn't

### ISSUE THREAD

**Issue by izzyreal** [bincrafters/community#628]
.yaml contents:
```datasource:
# MySQL database
    mysql:
        url: localhost
        user: izmar
        password: foobar
```

Fetching values like this:
```
auto url = Feed::props["datasource"]["mysql"]["url"].as<string>().c_str();
auto user = Feed::props["datasource"]["mysql"]["user"].as<string>().c_str();
auto password = Feed::props["datasource"]["mysql"]["password"].as<string>().c_str();
```
Works as expected when running in debug mode. In release mode all 3 variables become 'foobar'.

OSX Mojave, Xcode 10.1, Conan 1.11.2
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0

**Comment by madebr** [comment]
In order to get a faster response, can you please provide a SSCCE (Short, Self Contained, Correct (Compilable), Example)?

**Comment by izzyreal** [comment]
[https://github.com/izzyreal/conan-yaml-cpp-fail-example](https://github.com/izzyreal/conan-yaml-cpp-fail-example)

Discovered a few more predicates for the failure, clearly visible in [the code](https://github.com/izzyreal/conan-yaml-cpp-fail-example/blob/master/src/main.cpp). Am I missing some basic C/C++ knowledge and is the failure expected behaviour?

Thanks.

**Comment by SSE4** [comment]
hi @izzyreal 
I am not familiar with `yaml-cpp`, but I believe `as<string>()` returns a temporary object, and `c_str()` gets a pointer to a temporary storage, therefore you got a dangling pointer.

**Comment by izzyreal** [comment]
@SSE4 @madebr Thanks for your help! Looks like I lack basic C/C++ knowledge indeed. You think we can close this based on the above?

**Comment by SSE4** [comment]
yep, I think it's issue in your code, not in package, so I am closing
