### ISSUE TITLE
Recipe for sqlite_orm

### ISSUE THREAD

**Issue by AlexandrePTJ** [bincrafters/community#63]
Hi,

I hope this is a good place for that. I created a package for sqlite_orm and I would like to submit it here to community.
Package is hosted here [conan-sqlite_orm](https://github.com/AlexandrePTJ/conan-sqlite_orm)

For for your help.

**Comment by uilianries** [comment]
Hi @AlexandrePTJ! Thanks for your effort and contribution!

It will be a pleasure to receive your recipe.

I just would like to understand why you prefer to move sqlite dependency to test_package? Should it not be a direct dependency?

Regards!

/cc @solvingj

**Comment by AlexandrePTJ** [comment]
Hi,

Thanks for your feedback.
Putting sqlite to test_package was a mistake, this is now fixed.

**Comment by solvingj** [comment]
Great, have you ever setup Appveyor and Travis CI on any projects before? If not, we're happy to help you walk through the process.  One of our guidelines is that contributors setup these CI builds under their own CI accounts and work through them before pushing to a bincrafters repository. This is to keep the "troubleshooting" load off of our CI accounts.

**Comment by AlexandrePTJ** [comment]
I am ok with travis and appveyor, I enable them right now.

**Comment by solvingj** [comment]
Ok, the variables you need are CONAN_LOGIN_USERNAME and CONAN_PASSWORD which you should set to your bintray username and bintray **API KEY**  (not your bintray password).

**Comment by solvingj** [comment]
Additionally, add a variable in your `conanfile.py` under the version called `commit_id`, and set it to the most recent stable commit.  Then, you can change your `source()` method to use the strategy seen in this example:  
https://github.com/bincrafters/conan-abseil/blob/stable/20171101/conanfile.py#L23

For libraries which don't do versioned releases, we lock our packages to a specific github commit. This has a few important reasons.

**Comment by AlexandrePTJ** [comment]
About `CONAN_LOGIN_USERNAME` and CONAN_`PASSWORD`, do I set them directly info corresponding .yml files or from websites ?

**Comment by uilianries** [comment]
on Travis and Appveyor settings, keep CONAN_PASSWORD in secret, it works like your private key.

**Comment by solvingj** [comment]
Right, always set in the Travis/Appveyor UI's, not the config files.

**Comment by AlexandrePTJ** [comment]
Thanks I did it.
All jobs are failing with this error:

> conans.errors.ConanException: Error 404 downloading file https://raw.githubusercontent.com/bincrafters/conan-templates/package_tools_modules/build_template_default.py

**Comment by solvingj** [comment]
Yes, please replace your `build.py` with this latest template version.  
https://github.com/bincrafters/conan-templates/blob/master/build.py

Also, reference add bincrafters-package-tools to two files as shown here: 
https://github.com/bincrafters/conan-templates/blob/master/appveyor.yml#L32
https://github.com/bincrafters/conan-templates/blob/master/.travis/install.sh#L23

**Comment by uilianries** [comment]
@AlexandrePTJ I just submitted a PR with some changes.

**Comment by AlexandrePTJ** [comment]
Thanks you ! It helps a lot

**Comment by AlexandrePTJ** [comment]
I finally get package build but only for appveyor. It looks like for travis job, if some dependencies binary is missing, it is not built. So how to add the `--build=missing` parameter as for `conan` command ?

**Comment by uilianries** [comment]
You shouldn't.  
Build missing is a problem on CI. It will need to build the same dependencies on each new build and after to upload, the user will need to build too.

The better approach is get all dependencies already built. If it doesn't have all ready, you could request to maintainer to upload, Otherwise, we could upload to bincrafters.

I'll try to check your travis job.

**Comment by uilianries** [comment]
```
sqlite_orm/20180118@AlexandrePTJ/testing (test package): Installing /home/conan/project/test_package/conanfile.py
Requirements
    sqlite3/3.21.0@bincrafters/stable from remote0
    sqlite_orm/20180118@AlexandrePTJ/testing from local
Packages
    sqlite3/3.21.0@bincrafters/stable:9e123ca709904e7ba82572308f57b24f39d39099
    sqlite_orm/20180118@AlexandrePTJ/testing:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
Cross-build from 'Linux:x86_64' to 'Linux:x86'
sqlite3/3.21.0@bincrafters/stable: WARN: Can't find a 'sqlite3/3.21.0@bincrafters/stable' package for the specified options and settings:
- Settings: arch=x86, build_type=Release, compiler=clang, compiler.libcxx=libstdc++, compiler.version=5.0, os=Linux
- Options: enable_json1=False, shared=False
ERROR: Missing prebuilt package for 'sqlite3/3.21.0@bincrafters/stable'
Try to build it from sources with "--build sqlite3"
```

Indeed Clang 5.0 was not used to build out SQLite package. I'll work to solve this.

**Comment by uilianries** [comment]
Create the PR https://github.com/bincrafters/conan-sqlite3/pull/2

**Comment by uilianries** [comment]
@AlexandrePTJ Please, run again. I just released a new sqlite3 package. Now it has clang 5.0

**Comment by AlexandrePTJ** [comment]
It works perfectly! Thanks!
Also @fnc12, author of sqlite_orm, plan to release a version. So when it will be done, I will update the package with this version.
There is something I missed, is how make the package going from `testing/x` to `stable/x` ?

**Comment by uilianries** [comment]
@AlexandrePTJ I just create a new PR: https://github.com/AlexandrePTJ/conan-sqlite_orm/pull/2

After this PR your recipe will be done to be migrated into Bincrafters.

About stable/x testing/x is like compare develop branch x master branch. The name is a convention adopted by conan community at beginning. Usually, stable is a protected branch and needs to be okay on CI, before to merge.

IMO, after this new PR, you could create the stable branch, just run `git checkout -b stable/<version>`

To pull into Bincrafters, we don't use fork, we create a new repo and copy from your. Of course we preserve your git log, the author must be credited. After that, we could give the permission to change/maintain the project on our side.

Regards!

**Comment by AlexandrePTJ** [comment]
Thanks for clarification. PR is merged and I create the stable version right now.

**Comment by AlexandrePTJ** [comment]
Or I might wait for sqlite_orm to finally set semantic versionning.

**Comment by uilianries** [comment]
No problem, we can pull you version now and after to have the new release, it can be updated.

**Comment by uilianries** [comment]
Great news!

I pulled your recipe into Bincrafters: [sqlite_orm](https://github.com/bincrafters/conan-sqlite_orm)
Don't worry, I preserved all commits.

Now you are able change the recipe directly on Bincrafters repo.
Also, I sent an invite on your email to join us at Slack.

Many thanks for the contribution.
