### ISSUE TITLE
[zstd] Unexpected Conan build package failure 

### ISSUE THREAD

**Issue by tarunbelagodu** [bincrafters/community#630]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **zstd/1.3.3**
  * Operating System+version: **Linux Ubuntu 16.04**
  * Compiler+version: **gcc-5.4**
  * Conan version: **conan 1.7.3**
  * Python version: **Python 2.7.0**
  * conan-package-tools-0.23.0**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)

[settings]
os=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=5.4
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]

### Steps to reproduce (Include if Applicable)
Seeing a failure in our build conan package step on circleci. 
Is occurring this morning, same recipe was working fine until 2 days ago when I last tried it. 

Here's the trace...

Traceback (most recent call last):
  File "build.py", line 17, in <module>
    conan_pkg_version = parse_conan_pkg_version()
  File "build.py", line 10, in parse_conan_pkg_version
    vc = VoyageCore(None, None)
  File "/usr/local/lib/python2.7/dist-packages/conans/model/conan_file.py", line 120, in __init__
    self.output = ScopedOutput(display_name, output)
  File "/usr/local/lib/python2.7/dist-packages/conans/client/output.py", line 115, in __init__
    self._stream = output._stream
AttributeError: 'NoneType' object has no attribute '_stream'
Exited with code 1

### Logs (Include/Attach if Applicable)

Our circleci script pip installs conan  and conan_package_tools 

$SUDO pip install conan --upgrade
$SUDO pip install conan_package_tools glob2

**Comment by tarunbelagodu** [comment]
Any suggestions? Any specific github repo I should look at. I am attempting out circleci build without the conan --upgrade

**Comment by uilianries** [comment]
Hi @tarunbelagodu how does your build.py looks like?

**Comment by tarunbelagodu** [comment]
`from conan.packager import ConanMultiPackager
from conans.client.loader import ConanFileLoader
from conans.client.graph.python_requires import ConanPythonRequire
import os
import sys

def parse_conan_pkg_version():
    loader = ConanFileLoader(None, None, ConanPythonRequire(None, None))
    VoyageCore = loader.load_class(os.path.join(os.getcwd(), 'conanfile.py'))
    vc = VoyageCore(None, None)
    print('Parsed version is', vc.version)
    return vc.version

if __name__ == "__main__":
    if len(sys.argv) == 2:
        git_tag = sys.argv[1]
        conan_pkg_version = parse_conan_pkg_version()
        will_upload = git_tag != '' and git_tag == conan_pkg_version
    else:
        will_upload = False

    if will_upload:
        print('Will upload to artifactory', conan_pkg_version)
        upload = "https://voyage.jfrog.io/voyage/api/conan/voyage"
    else:
        print('Will NOT upload to artifactory')
        upload = ''

    builder = ConanMultiPackager( archs=["x86_64"], build_policy="missing", upload=upload )
    builder.add(settings={'compiler.version': '5.4', 'compiler.libcxx': 'libstdc++11', 'build_type': 'Debug'}, options={"rti_connext_dds:shared":False})
    builder.add(settings={'compiler.version': '5.4', 'compiler.libcxx': 'libstdc++11', 'build_type': 'Release'}, options={"rti_connext_dds:shared":False})
    builder.run()
`

**Comment by tarunbelagodu** [comment]
Tracing it,the error is from Python ScopedOutput?

**Comment by uilianries** [comment]
If I understand, you want to get the version in the recipe. Do have some restriction to use Conan >1.10? My recommendation is get version using `inspect`. There is an example [here](https://github.com/bincrafters/bincrafters-conventions/blob/233ed725d48748870ea1e2ef3744769b747017a8/bincrafters_conventions/actions/check_for_spdx_license.py#L9) where we inspect the license, you just need to replace by `version`. Anyway, I'm trying to reproduce your error here ...

**Comment by tarunbelagodu** [comment]
Regarding version, as I described in the ticket, we do a pip install conan --upgrade
We have our own versioning of new code changes (version.txt)
`
class VoyageCore(ConanFile):
    name = "voyagecore"
    version = read_version()
    settings = "os", "compiler", "build_type", "arch"
    generators = "cmake"

    requires = "rti_connext_dds_pro/5.3.1@voyage/stable"
    default_options = "rti_connext_dds_pro:shared=False"

    exports_sources = "apps/*", "lib/*", "res/*", "test/*", "types/*", "CMakeLists.txt"
    exports = "version.txt"

    build_requires = ("rtiddsgen_pro/2.5.2@voyage/stable",
                      "gtest/1.8.1@bincrafters/stable")
`

**Comment by uilianries** [comment]
Hi again! Just update your build.py:

```python
def parse_conan_pkg_version():
    loader = ConanFileLoader(None, None, ConanPythonRequire(None, None))
    vc = loader.load_class(os.path.join(os.getcwd(), 'conanfile.py'))
    print('Parsed version is', vc.version)
    return vc.version
```

Since `load_class` an ConanFile object, you dont need to re-create it again.

**Comment by tarunbelagodu** [comment]
Cool, I see. Trying it now. Btw, is this related to a recent change maybe?
This piece of code has been working for months

**Comment by uilianries** [comment]
Yes, it's from Conan new version (1.12.0), it was changed 1 month ago.

**Comment by tarunbelagodu** [comment]
Ah! Okay that fixed it thanks for your help!

**Comment by tarunbelagodu** [comment]
could you please send me a link to the repo where this was released, I'd like to bookmark for future reference

**Comment by uilianries** [comment]
It was changed here: https://github.com/conan-io/conan/blob/1.12.0/conans/client/output.py#L115

If you apply git blame, you will see the last change from 1 month ago. The point is that you are using an internal code to build your project, I strongly recommend using the API, it is more stable and very used by other projects.

**Comment by tarunbelagodu** [comment]
We've had at least 5 PRs go through since the change you refer to. So I am not sure why it failed today. 
This conan packaging setup was by somebody else, but good you alerted me to this. I can tag it as an improvement item for our team - what API do you recommend using instead? Any sample code would be handy.

**Comment by uilianries** [comment]
The API is not documented yet, but the code is [here](https://github.com/conan-io/conan/blob/1.12.0/conans/client/conan_api.py). There are many tests that you could use as reference, but also there some extra projects using the API:

[bincrafters-remove-outdated](https://github.com/bincrafters/bincrafters-remove-outdated/blob/master/bincrafters_remove_outdated/bincrafters_remove_outdated.py#L24)
[bincrafters-conventions](https://github.com/bincrafters/bincrafters-conventions/blob/5fd562497d2a42122a75e6ff9baed1f3adea3e31/bincrafters_conventions/actions/check_for_deprecated_generators.py#L12)
[bincrafters-package-list](
https://github.com/bincrafters/bincrafters-package-list/blob/84ceeefde671909e69133ef01b7fee4a46d16d50/bincrafters-package-list.py#L45)

You could take them as example, but feel free to ask any help!
