### ISSUE TITLE
[Botan] Current package setup disables compiler optimization

### ISSUE THREAD

**Issue by reneme** [bincrafters/community#631]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **botan/2.8.0**
  * Operating System+version: **Linux, macOS**
  * Compiler+version: **....**
  * Conan version: **conan 1.12.0**

### Problem Description

Not sure whether this should be fixed in the recipe and/or the library's build system.
Anyway, at the moment the [botan conan package](https://github.com/bincrafters/conan-botan) builds the library without any compiler optimizations which is pretty unfortunate.

When adding the `--cxxflags` parameter to botan's `./configure.py`, it _replaces_ the default compiler flags (that contains `-O3`) and hence builds with the default `-O0`. The same is true when `--cxxflags` is not used but the `CXXFLAGS` environment variable is set. The recipe uses this to enable `-fPIC` in unix builds.

[See here](https://github.com/randombit/botan/blob/master/configure.py#L1946) for the culprit bit of botan's `./configure.py`.

**Comment by reneme** [comment]
Turns out that independently a related discussion just opened up in the botan issues:
https://github.com/randombit/botan/issues/1826

**Comment by reneme** [comment]
And it got fixed: (presumably) Botan 2.10.0 should include an extra flag: `—extra-cxxflags` that *adds* compiler flags, rather than *replace* the standard ones.

**Comment by SSE4** [comment]
@reneme I've applied changes to use `-cc-abi-flags` instead of `--cxxflags`, please give an another try and lemme know

**Comment by reneme** [comment]
Thanks for the quick response. The `--cc-abi-flags` workaround works in principle. In my case botan's `./configure.py` still stumbles over the `CXXFLAGS` environment variable that I set in my conan profile. I opened a [PR](https://github.com/bincrafters/conan-botan/pull/6) with a suggested second workaround.

**Comment by reneme** [comment]
Thanks for merging. It works for me now. I'd just love to have it in the 2.9.0 branch as well. Who is responsible for pulling fixes into the other branches? Shall I open another PR for that? Admittedly, I'm not sure how this is handled in the bincrafters community.

**Comment by uilianries** [comment]
Hi @reneme !

Thanks for providing that PR! Could I ask you to open a new PR for 2.9.0?

**Comment by reneme** [comment]
Sure! [here](https://github.com/bincrafters/conan-botan/pull/7) you go.

**Comment by uilianries** [comment]
Thanks! Waiting for CI result.

**Comment by reneme** [comment]
This works for me now, so that I could switch to the upstream package for our project. Thanks a lot.
