### ISSUE TITLE
Upstream Update: spdlog 1.3.1

### ISSUE THREAD

**Issue by IceflowRE** [bincrafters/community#632]
### Package Details
  * Package Name: **spdlog** (https://github.com/bincrafters/conan-spdlog)
  * Latest available Version: **1.3.1**

The above mentioned version is newly released by the upstream project and not yet available within Bincrafters. Please add this version.

**Comment by uilianries** [comment]
Done!

https://github.com/bincrafters/conan-spdlog/tree/stable/1.3.1
