### ISSUE TITLE
[Folly] Wrong error messange when build with MinGW

### ISSUE THREAD

**Issue by uilianries** [bincrafters/community#634]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **folly//2018.11.12.00**
  * Operating System+version: **Windows**
  * Compiler+version: **gcc-5.4**
  * Conan version: **conan 1.12.1**
  * Python version: **Python 3.7.0**

### Conan profile
os = Windows
compiler = gcc

### Steps to reproduce (Include if Applicable)
Just try to build the package as usual:

    conan create . bincrafters/testing

### Logs (Include/Attach if Applicable)
```
ERROR: lz4/1.8.3@bincrafters/stable: Error in build() method, line 77
        self.build_vs()
while calling 'build_vs', line 54
        if self.settings.compiler.runtime == 'MD':
        ConanException: 'settings.compiler.runtime' doesn't exist for 'gcc'
'settings.compiler' possible configurations are ['exception', 'threads', 'version'
```

**Comment by SSE4** [comment]
that seems like an error in lz4 recipe, not in folly itself

**Comment by SSE4** [comment]
@uilianries I've fixed `lz4` so it builds fine with MinGW

**Comment by uilianries** [comment]
Amazing! Thanks @SSE4 !

I've opened the PR https://github.com/bincrafters/conan-folly/pull/5

**Comment by SSE4** [comment]
@uilianries it seems like now we need libevent for MinGW

**Comment by uilianries** [comment]
![kill me](https://i.guim.co.uk/img/media/327e46c3ab049358fad80575146be9e0e65686e7/0_0_1023_742/master/1023.jpg?width=300&quality=85&auto=format&fit=max&s=02632218051da209be64b27e96722c43)

I gonna check later, thanks for reporting !

**Comment by SSE4** [comment]
@uilianries I think original issue has been solved, WDYT?

**Comment by uilianries** [comment]
Oh, this one is a nightmare! I spent some days trying to fix it. The problem is that many Folly dependencies doesn't have support for mingw ... I would say to abandon this support for now and only fix when requested by some real user

**Comment by SSE4** [comment]
@uilianries okay, I am closing the issue for now, until real users request MinGW support
