### ISSUE TITLE
[qt] circular dependency during build

### ISSUE THREAD

**Issue by derived-coder** [bincrafters/community#638]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.12.0@bincrafters/stable**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **clang-7.0.1**
  * Conan version: **conan 1.12.2**
  * Python version: **Python 3.6.5**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
CLANG=/usr/local/clang_7.0.1

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=clang
compiler.version=7.0
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
cmake_installer/3.13.0@conan/stable
[env]
CC=$CLANG/bin/clang
CXX=$CLANG/bin/clang++
```

### Steps to reproduce (Include if Applicable)
conan install . -if=build -pr=clang
it tells me:

```ERROR: Missing prebuilt package for 'double-conversion/3.1.1@bincrafters/stable'
Try to build it from sources with "--build double-conversion"
```

when I do this, it tells me:

```
harfbuzz/2.3.0@bincrafters/stable: WARN: Can't find a 'harfbuzz/2.3.0@bincrafters/stable' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=Release, compiler=clang, compiler.version=7.0, os=Linux
- Options: fPIC=True, shared=False, with_freetype=False
- Dependencies: 
- Package ID: abc45b7dce3f5194dea2377c33229fa4f20706b4

ERROR: Missing prebuilt package for 'harfbuzz/2.3.0@bincrafters/stable'
Try to build it from sources with "--build harfbuzz"
Or read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package"
```
And when I build harfbuzz, it will tell me again double-conversion is missing, and so on and so on...

**Comment by ericLemanissier** [comment]
Could you try `--build=outdated` ?

**Comment by derived-coder** [comment]
@ericLemanissier 
using build=outdated works
But is this still a bug?

**Comment by ericLemanissier** [comment]
This is not a bug, and this is not a circular dependency. As mentioned in [the documentation](https://docs.conan.io/en/latest/mastering/policies.html) `--build foo` will build only foo package. In you case you missed both harfbuzz and double-conversion, so you had to specify both `--build harfbuzz --build double-conversion` in a single call. Or use `--build=missing` or `--build=outdated` which build all missing binaries
