### ISSUE TITLE
boost-regex with icu failed to build on Ubuntu 18.10

### ISSUE THREAD

**Issue by malirod** [bincrafters/community#640]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **boost-regex/1.69.0**
  * Operating System+version: **Linux Ubuntu 18.10**
  * Compiler+version: **clang-7**
  * Conan version: **conan 1.12.0**
  
Boost-regex (with icu) requires icu 59.1 ( https://github.com/bincrafters/conan-boost_regex/blob/stable/1.69.0/conanfile.py ) 
Build of icu fails: `'xlocale.h' file not found`

Looks like `xlocale.h` has been removed in `glibc 2.26`

Changin icu to 63.1 worked for me.

**Comment by solvingj** [comment]
Thanks for the notice, we'll likely bump to `icu/63.1` then.

**Comment by solvingj** [comment]
Done: https://github.com/bincrafters/conan-boost_regex/commit/53f44842788b845b3ec9dfc74f05a12dbf0b5de0

**Comment by solvingj** [comment]
If you don't mind, please test and let us know if this works.

**Comment by malirod** [comment]
@solvingj , fix worked for me. thanks!
