### ISSUE TITLE
[conan-readme-generator] Support project logo

### ISSUE THREAD

**Issue by uilianries** [bincrafters/community#642]
### Description of your feature

Some packages have a logo, where it can localized at /images/logo.png or logo.png. Those image should be added in README, to provide a visual identity for the package. The same picture is used on Bintray.

Conan Community has adopted their logos in README file, however, Conan Readme Generator removed all of them. The idea is, when a logo is present on project folder, put it in README file.

**Comment by Croydon** [comment]
I was thinking about that in the past already.
One problem seems to be that the name of the file isn't uniform right now. We should settle for one name (`logo.png`?).

What about two paths? Do we really need that (like at root and in `/images/`)

**Comment by uilianries** [comment]
> We should settle for one name (`logo.png`?).

For github it does not make any effect, but for Gitlab the platform will used that file as project logo automatically.

> What about two paths? Do we really need that (like at root and in `/images/`)

I agree that we should follow one standard path only. For me it's okay move to `images` folder as used by conan community. It could be added to `bincrafters-conventions`, it's easy be implemented.

**Comment by solvingj** [comment]
In principle, I actually don't support the use of the Logo's in Github for several reasons: 
- It's purely cosmetic
- Current README seems concise to me, this clutters it
- Not all have a logo, so it makes things even less consistent
- Takes non-zero time/effort/thought to add it
- Might be misleading, indicating recipe is somehow "official" from upstream (IMO)

With that said, it's mostly a matter of opinion, and I'm not going to actively object to you guys moving forward with this.

**Comment by SSE4** [comment]
@solvingj I support it, we have many other important things to be done, and logo appears to be low-priority for me

**Comment by uilianries** [comment]
Okay, I agree hiding the logo from README and using it on Bintray page only, but it's a task for bintray-update hook.

Let's close this issue. Thanks everyone for sharing your opinions.
