### ISSUE TITLE
boost_stacktrace/1.69.0@bincrafters/stable is missing conanfile.py

### ISSUE THREAD

**Issue by bredej** [bincrafters/community#645]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: boost_stacktrace/1.69.0@bincrafters/stable
  * Operating System+version: Windows 10, 64-bit
  * Compiler+version: Visual Studio 2017, 15.9.7
  * Docker image: NA
  * Conan version: conan 1.10.2 (msi installer)
  * Python version: Python 3.6

### Conan profile
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=15
build_type=Release
[options]
[build_requires]
[env]

### Steps to reproduce
conan download -r=bincrafters boost_stacktrace/1.69.0@bincrafters/stable

### Logs
Downloading conanmanifest.txt
[==================================================] 103B/103B
Downloading conan_export.tgz
[==================================================] 758B/758B
Decompressing conan_export.tgz: 100%|██████████| 758/758 [00:00<00:00, 54.1kB/s]
ERROR: C:\Users\******\.conan\data\boost_stacktrace\1.69.0\bincrafters\stable\export\conanfile.py not found!

**Comment by bredej** [comment]
FYI This is the same issue I reported using the Feedback button on the bintray.com web site some time ago.
[#98307] conanfile missing in boost_stacktrace

**Comment by SSE4** [comment]
@danimtb do you think if it might be bintray issue?

**Comment by bredej** [comment]
I can use the web interface to verify the file is missing.  It is present in the testing channel.
https://bintray.com/bincrafters/public-conan/boost_stacktrace%3Abincrafters/1.69.0%3Astable#files/bincrafters%2Fboost_stacktrace%2F1.69.0%2Fstable%2Fexport

**Comment by danimtb** [comment]
It has been reported to the Bintray team. Please wait until we have a answer.

**Comment by solvingj** [comment]
Since it clearly doesn't exist, I am tempted to re-build stacktrace to get the file in place.  any objections @danimtb ?

**Comment by solvingj** [comment]
I did find a failed build on appveyor and restearted it. @bredej please retest and let us know if it still has an error.

**Comment by bredej** [comment]
@solvingj I get the same error as before.

**Comment by danimtb** [comment]
@solvingj Seems to be same issue with missing files. Please rebuild and let's see how it goes

**Comment by solvingj** [comment]
@bredej I've deleted the package and re-ran appveyor and travis.  I was then able to run `conan download` successfully.  Please try again when you have a chance.  

Here's the CI logs for posterity.
https://ci.appveyor.com/project/BinCrafters/conan-boost-stacktrace
https://travis-ci.com/bincrafters/conan-boost_stacktrace

**Comment by bredej** [comment]
It works!
Thanks for all the help and for providing a great tool.

**Comment by danimtb** [comment]
Thanks @solvingj 😞
