### ISSUE TITLE
[cmake_findboost_module] update to cover boost 1.68.0 & 1.69.0

### ISSUE THREAD

**Issue by weatherhead99** [bincrafters/community#646]
### Package and Environment Details (include every applicable attribute)
  * Operating System+version: **Linux Ubuntu 16.04**
  * Compiler+version: **gcc-5.4**
  * Conan version: **Conan 1.12.2**
  * Python version: **Python 3.6.5**

### Description of your feature
I use find_package() within cmake  scripts to find the Boost libraries. This no longer works for the latest boost packages, because the mechanism to achieve this (the cmake_findboost_module package) no longer exists for the new versions.

Thanks,
Dan W

**Comment by solvingj** [comment]
Dan, thanks for reporting this.

**Comment by weatherhead99** [comment]
1.69.0 seems to work fine for me at least
