### ISSUE TITLE
[glib] zlib, libffi, etc dynamic library dependencies in macOS

### ISSUE THREAD

**Issue by tanshihaj** [bincrafters/community#648]
* Package Name/Version: **glib/2.58.3**
  * Operating System+version: **macOS 10.12+**

If faced with problem when I want to build `glib` in macOS with dependencies builded dynamically.
For example I want `zlib` and `libffi` to be linked dynamically to `glib`:

`conan install -o zlib:shared=True -o libffi:shared=True glib/2.58.3@bincrafters/stable`

The problem is that `glib` build will fail, since during build `glib-compile-resources` executable will not find `libffi.6.dylib`. `glib-compile-resources` creates during build process and build process calls `glib-compile-resources` as child process. It depends on `libgobject-2.0.0.dylib` which in turn depends on `libffi.6.dylib`.

Install name of `libgobject-2.0.0.dylib` is `@rpath/libgobject-2.0.0.dylib` and `glib-compile-resources` contains rpath entry with `libgobject-2.0.0.dylib` location so system can find it. However `libffi.6.dylib` install name is just `libffi.6.dylib` without `@rpath/` prefix and therefore system expects to find it in current directory, and even as `libgobject-2.0.0.dylib` contains rpath entry with `libffi.6.dylib` location system can't load it.

Conan documentation suggests to set `DYLD_LIBRARY_PATH` environment variable to build process, but it will not work since SIP protocol will not allow to inherit environment variable by child process.

Does anyone have an idea how to deal with this problem? Maybe it would be more convenient to create shared libraries by default with `@rpath/` prefix?

**Comment by SSE4** [comment]
@tanshihaj we may try to use [RunEnvironment](https://docs.conan.io/en/latest/reference/build_helpers/run_environment.html) helper for this

**Comment by tanshihaj** [comment]
@SSE4 I've tried to use it:
```
...
env_build = RunEnvironment(self)
with tools.environment_append(env_build.vars):
    meson = self._configure_meson()
    meson.build()
...
```

however, it seems there is some issues with SIP and DYLD_* environment variables. I've not dug deep, but it seems it is not an option.

**Comment by SSE4** [comment]
then it probably makes sense to extract `Glib` tools like `glib-compile-resources` to their own package(s), and ensure they are always statically linked with dependencies

**Comment by SSE4** [comment]
from @danimtb:
```
Regarding this, it could be solved injecting the DYLD_LIBRARY_PATH just in front of the Meson build command. We could create a parameter in the build() method to pass the run_environment flag to conanfile.run()
```

**Comment by tanshihaj** [comment]
Well, I've tried to add `run_environment` to build() command inside Meson.build() source as well as wrapping it with `with tools.environment_append({"DYLD_LIBRARY_PATH": "/path/to/lib"}):` `self._conanfile.run(command)` invocation, however it wasn't very helpful `glib-compile-resources` still fails to find dynamic libraries.

**Comment by danimtb** [comment]
hi @tanshihaj 

What I meant is that you would need to inject the variable DYLD_LIBRARY_PATH just in front of the meson call as done in here: https://docs.conan.io/en/latest/howtos/manage_shared_libraries/env_vars.html#using-shared-libraries-from-dependencies

Using only the RunEnvironment tool is not enough.

The problem with this right now is that the Meson build helper does not allow to extract the command line calls to let the user manipulate it so it will require a new feature in the helper to extract each command. Howerver, this is something that could be done automatically with a ``run_environment`` parameter in ``Meson.build()`` method that activates the smae one in `conanfile.run(run_environment=True)` (See https://docs.conan.io/en/latest/reference/conanfile/other.html#running-commands).

I will propose both features for discussion with the team.

**Comment by tanshihaj** [comment]
hi @danimtb,

do you mean that it would be smth like that:

```
class Meson(object):
    ...
    def build(self, ..., run_environment=False):
        ...
        if run_environment:
            command = 'DYLD_LIBRARY_PATH=/path/to/the/lib ' + command
        self._conanfile.run(command)
```
?

**Comment by danimtb** [comment]
Yes @tanshihaj, Wouldn't that fix your issue?

**Comment by tanshihaj** [comment]
I think not, I've tried to do it in Conan sources, bit it will not help since `glib-compile-resources` is subprocess of `ninja` and not inherit `DYLD_LIBRARY_PATH` environment variable

**Comment by danimtb** [comment]
Thanks a lot for the insight. Unless we patch the call to `glib-compile-resources` and inject the DYLD var somehow, I don't see a way we can workaround this issue at the moment.

**Comment by tanshihaj** [comment]
Here is some links: https://apple.stackexchange.com/questions/215030/el-capitan-make-check-dyld-library-path

**Comment by Croydon** [comment]
This recipe is now in the [Conan Center Index](https://github.com/conan-io/conan-center-index/).

Please migrate to the recipe version there. 
If this is still an issue, please create a new issue in the [Conan Center Index issue tracker](https://github.com/conan-io/conan-center-index/issues).

Thanks!
