### ISSUE TITLE
Add new versions: openmpi/2.0.4 and 2.1.1

### ISSUE THREAD

**Issue by GavinNL** [bincrafters/community#656]
### Package Details
  * Package Name: **openmpi**
  * Latest available Version: **3.0.0**
  * Versions requesting: **2.0.4**, **2.1.1**

The openMPI version on Bincrafters is 3.0.0. Our project currently requires version 2.0.4. The current recipe is modular enough that changing the self.version to 2.0.4 will build project. It would be nice if this was included in Bincrafters.

Version 2.1.1 is the current version that is on the Ubuntu 18.04 repositories, it would be nice if this was included in the Bincrafters repo as well.

**Comment by SSE4** [comment]
cool, I'll add em

**Comment by SSE4** [comment]
I've added required versions
