### ISSUE TITLE
[libiconv/1.15] Prebuilt libiconv contains nonexistent paths

### ISSUE THREAD

**Issue by brianthelion** [bincrafters/community#659]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libiconv/1.15**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Conan version: **conan 1.12.3**
  * Python version: **Python 3.7.0**

### Conan profile
```Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=7
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

```bash
NONSENSE_PATH="/home/conan"
cd $(mktemp -d)
python3 -m venv _venv36
source _venv36/bin/activate
pip install --upgrade pip
pip install conan
export CONAN_USER_HOME=$(pwd)
conan install libiconv/1.15@bincrafters/stable
fgrep -r ${NONSENSE_PATH} ${CONAN_USER_HOME}/.conan
```

### Logs (Include/Attach if Applicable)

```
Binary file /tmp/tmp.9kiUZOMRt2/.conan/data/libiconv/1.15/bincrafters/stable/package/d50a0d523d98c15bb147b18fa7d203887c38be8b/lib/preloadable_libiconv.so matches
/tmp/tmp.9kiUZOMRt2/.conan/data/libiconv/1.15/bincrafters/stable/package/d50a0d523d98c15bb147b18fa7d203887c38be8b/lib/libcharset.la:libdir='/home/conan/.conan/data/libiconv/1.15/bincrafters/stable/package/d50a0d523d98c15bb147b18fa7d203887c38be8b/lib'
/tmp/tmp.9kiUZOMRt2/.conan/data/libiconv/1.15/bincrafters/stable/package/d50a0d523d98c15bb147b18fa7d203887c38be8b/lib/libiconv.la:libdir='/home/conan/.conan/data/libiconv/1.15/bincrafters/stable/package/d50a0d523d98c15bb147b18fa7d203887c38be8b/lib'
Binary file /tmp/tmp.9kiUZOMRt2/.conan/data/libiconv/1.15/bincrafters/stable/package/d50a0d523d98c15bb147b18fa7d203887c38be8b/lib/libcharset.a matches
Binary file /tmp/tmp.9kiUZOMRt2/.conan/data/libiconv/1.15/bincrafters/stable/package/d50a0d523d98c15bb147b18fa7d203887c38be8b/lib/libiconv.a matches
Binary file /tmp/tmp.9kiUZOMRt2/.conan/data/libiconv/1.15/bincrafters/stable/package/d50a0d523d98c15bb147b18fa7d203887c38be8b/bin/iconv matches
```

**Comment by SSE4** [comment]
do you have a problem with libtool .la files or with libraries themselves? does it work for you if you just remove libtool .la files?

**Comment by brianthelion** [comment]
My specific issue is with the libtool `.la` files. Due to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=297726, dependent recipes may try to pull the `.la` files from down the dependency chain. In this scenario, having non-existent paths in recipe `.la` files is problematic.

I have not yet attempted a fix yet, but will do so later in the week. Just wanted to make sure I wasn't missing something obvious here. I assume from your response @SSE4 that this is *not* a problem that `conan` has addressed previously?

**Comment by SSE4** [comment]
@brianthelion no, this is not something we have solved for any of our packages. I've run into such problem in the past, but didn't find any way to manage it. probably, the easiest way would be just not providing them (like LFS suggests: http://www.linuxfromscratch.org/blfs/view/8.3/introduction/la-files.html)

**Comment by brianthelion** [comment]
@SSE4 The question for conan recipe maintainers is: Who is on the hook for dealing with this? In my case, I'm building a new recipe and it's `libiconv` that's giving me trouble. Does my recipe need to filter out `.la` files in `libiconv`? Or should `libiconv` take care of that. There's no clear policy.

**Comment by SSE4** [comment]
if we decide to clean .la files, then definetely libiconv should do this itself, otherwise it doesn't scale

**Comment by brianthelion** [comment]
@SSE4 What does that decision process look like? Should I fork the `libiconv` recipe in the meantime?

**Comment by SSE4** [comment]
@brianthelion  first off, we need a confirmation that it really helps. would be nice if you can test it locally and confirm that removing .la files works for you. second, submit PR with your changes, so we can review. also, we probably will run a series of tests against current libraries importing libiconv to ensure they aren't broken after these changes.

**Comment by brianthelion** [comment]
@SSE4 Noted. I'll see if I can turn this around before the weekend.

**Comment by SSE4** [comment]
solution for now is to just remove these .la files. I'll do this in libiconv recipe right now. as builds work without libtool files, it's safe change. if anyone will really need these libtool files, we will need to provide conan's generator for them - that would be strategy (same as for cmake and pkg-config files).
