### ISSUE TITLE
Bump clara to 1.1.0 per author

### ISSUE THREAD

**Issue by solvingj** [bincrafters/community#66]
Within the next day or two, there will be a 1.1.0 release with several important fixes.  At that time we'll probably remove 1.0.0 branch and packages because of issues. This is just a reminder.

**Comment by uilianries** [comment]
Clara 1.1.0 was released 1 hour ago 😄 

I'll update our recipe

**Comment by uilianries** [comment]
I just updated now -- I started before to know about the bug

https://github.com/bincrafters/conan-clara/tree/testing/1.1.0

Just waiting for the release.

**Comment by uilianries** [comment]
Done! 

Clara 1.1.0 was released!

https://github.com/bincrafters/conan-clara/tree/stable/1.1.0

**Comment by solvingj** [comment]
great job, thank you so much for pushing this through !
