### ISSUE TITLE
Question: Modular Boost packages do not have shared option.

### ISSUE THREAD

**Issue by IceflowRE** [bincrafters/community#661]
The current (1.69.0) boost modular packages like `boost_algorithm` or `boost_asio` do not provide the shared option. Is there a reason?
If i require the shared libraries, must i use the normal boost package with shared on? (Which gives me them)

**Comment by SSE4** [comment]
@IceflowRE AFAIK asio and algorithm are header-only modules, so it doesn't make much sense to add shared/static option for them, WDYT?

**Comment by IceflowRE** [comment]
Ah ok. Did not knew that they are header only. Was nowhere mentioned.

**Comment by SSE4** [comment]
this is mentioned in official boost documentation, for instance: https://www.boost.org/doc/libs/1_69_0/doc/html/boost_asio/using.html
```
By default, Boost.Asio is a header-only library
```
I think question is answered, so closing
