### ISSUE TITLE
libpng with zlib yields linker errors

### ISSUE THREAD

**Issue by StefanSchulz-Tesyo** [bincrafters/community#663]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libpng 1.6.34**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **gcc-7.3**
  * Conan version: **conan 1.12.3**
  * Python version: **Python 3.6.7**

### Steps to reproduce (Include if Applicable)
Building libpng fails to link against zlib (unresolved symbols). At least if zlib is not installed on the system. 

### Fix
Add the following lines to the CMakeLists.txt directly after `conan_basic_setup()`
```
set(ZLIB_INCLUDE_DIR ${CONAN_INCLUDE_DIRS_ZLIB})
set(ZLIB_LIBRARY ${CONAN_LIBS_ZLIB})
```

**Comment by theirix** [comment]
@StefanSchulz-Tesyo , seems it is a zlib package problem, filled an issue.

To the future me:
```
conan create . -o libpng:shared=True bincrafters/testing
grep ZLIB_LIBR ~/.conan/data/libpng/1.6.34/bincrafters/testing/build/*/CMakeCache.txt
```

**Comment by theirix** [comment]
`conan-zlib` package just updated and the problem with conan-libpng fixed too. Please update package or just clean Conan cache.

**Comment by StefanSchulz-Tesyo** [comment]
That was quick, thank you. Works perfectly now.
