### ISSUE TITLE
Upstream Update: asio 1.12.2

### ISSUE THREAD

**Issue by IceflowRE** [bincrafters/community#665]
### Package Details
  * Package Name: **asio** (NON boost)
https://bintray.com/bincrafters/public-conan/asio%3Abincrafters
  * Latest available Version: **1.12.2**
https://github.com/chriskohlhoff/asio/releases/tag/asio-1-12-2

The above mentioned version is newly released by the upstream project and not yet available within Bincrafters. Please add this version.

**Comment by SSE4** [comment]
new version has been added, closing
