### ISSUE TITLE
[qt] support more build tools

### ISSUE THREAD

**Issue by derived-coder** [bincrafters/community#666]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.12.0**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **gcc-5.4**
  * Docker image: **conanio/gcc7**
  * Conan version: **Conan 1.12.1**
  * Python version: **Python 3.6.5**

### Description of your feature
I would like to use the conan recipe also for other build tools. like meson or premake.

**Comment by solvingj** [comment]
Hi @derived-coder , thanks for posting. I’m not sure how familiar you are with Conan yet, but generally speaking, one of the core features of Conan is that you can consume any dependency/library that is packaged with it from within your project, regardless of the build system the dependency uses, AND regardless of the build system you are using.  If you happen to be using a popular build system (including premake and meson) Conan’s built in generator system will produce the premake and meson files that you can just “include” in you project to get your dependencies.  Let us know if you have more questions.
