### ISSUE TITLE
icu/63.1 should be split in icu and icu_installer + missing executables

### ISSUE THREAD

**Issue by madebr** [bincrafters/community#668]
Currently, `icu` [already adds](https://github.com/bincrafters/conan-icu/blob/8015d3c1bfa052f7d5b593e462cc96dbd957bb76/conanfile.py#L175) the `bin` folder to `PATH`.
But this fails when `self.settings.arch` != `self.settings.arch_build`

Also, `icu` misses some executables such as:
- gencnval
- gennorm2
- genccode
- gensprep
- icupkg
- gencmn

**Comment by solvingj** [comment]
I don’t disagree, if someone has need and time, it will be a great improvement.

**Comment by madebr** [comment]
I have :smile: 
I will invest some time once bison and flex get accepted.

**Comment by SSE4** [comment]
@madebr do you have a conclusion on how are we going with such packages like `bison` (installer + library). I've seen two RFC's, one using `python_requires`, and one using regular inheritance. my understanding is that `python_requires` approach doesn't work right now and requires some fixes in CPT, is it accurate? so, did you decide to proceed with python requires or another approach?

**Comment by madebr** [comment]
@SSE4 Indeed. Both approaches currently do not work because a bug in CPT.
Once that bug has gone away, I propose to use the one using regular inheritance.
Please comment on 

I have not found another way to fix the problem with `python_requires`.
Please comment on bincrafters/conan-flex#4 about cosmetic remarks, code organization, ... :smile:

**Comment by SSE4** [comment]
@madebr do you have a link to CPT bug?

**Comment by madebr** [comment]
@SSE4  conan-io/conan-package-tools#325
It's already fixed and waiting to be released.

**Comment by SSE4** [comment]
@madebr ICU is now split into `icu` and `icu_installer` in order to suffice cross-compilation use-caset
