### ISSUE TITLE
tbb 4.4.4 does not seem to handle clang.

### ISSUE THREAD

**Issue by fulara** [bincrafters/community#669]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **tbb/4.4.4**
  * Operating System+version: **Linux Ubuntu 16.04**
  * Compiler+version: **clang-7.0**
  * Docker image: **lasote/conanclang60**
  * Conan version: **conan 1.12.3**
  * Python version: **Python 3.6.0**
### Short description
I tried to build tbb version 4.x but it seemed that tbb was being built with gcc instead. I looked briefly at tbb recipes and they do mention clang so I guess its supported.
### What did I do?
I forked off from your stable/4.4.4 and modified travis.yml to be like this:
`env: CONAN_CLANG_VERSIONS=7.0 CONAN_DOCKER_IMAGE=lasote/conanclang60`  
can be seen here: https://github.com/fulara/conan-tbb/blob/stable/4.4.4/.travis.yml
### What did  I expect?
That tbb would be built with clang
### what did i get?
In the build logs that are pasted below i can see following (examplary line)
`g++ -o concurrent_vector.o -c -MMD -DTBB_USE_DEBUG -DDO_ITT_NOTIFY -g -O0 -DUSE_PTHREAD -m32 -march=pentium4 -mrtm -fPIC -D__TBB_BUILD=1 -Wall -Wno-parentheses -Wno-non-virtual-dtor    -I../../src -I../../src/rml/include -I../../include ../../src/tbb/concurrent_vector.cpp`
So it seems to me that TBB is being built with g++ rather than clang here.  
Apologies if i made a mistake during setup of this travil.yml, however i saw this issue at work where i tried using:
`conan ... -s "compiler=clang" -s "compiler.version=7.0" ` and i got similar output as in attached travis output

### Logs (Include/Attach if Applicable)
https://travis-ci.org/fulara/conan-tbb/builds/500563739  
https://github.com/fulara/conan-tbb/blob/stable/4.4.4/.travis.yml

**Comment by madebr** [comment]
I'm just wondering.
Is there a reason why you're not using tbb/2019_U3@conan/stable?
The [4.4 branch on the official tbb github repo is 3 years old](https://github.com/01org/tbb/tree/tbb_4.4).

You should add clang7 packages to your travis.yml as:
```
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=7.0 CONAN_DOCKER_IMAGE=conanio/clang7
```

**Comment by fulara** [comment]
Updated my travis to use that docker image, g++ still being invoked. [travis log](https://travis-ci.org/fulara/conan-tbb/jobs/500896761)  
as to why i am using tbb thats 3 yo.. because i started using it ~3 years ago. :) I noticed that it seems that clang build works fine for that 2019_U3, so i am actually considering upgrading to that latest tbb.  

Still, raised an issue because probably this is not expected behavior, I will leave this up to maintainers whether they want to take a look at that or not.

**Comment by SSE4** [comment]
@fulara we have merged required changes, please give an another try

**Comment by fulara** [comment]
@SSE4  will give it a go later on today.  
by the way i wanted to upgrade to latest recipe but i noticed 2 things:  
1) in new recipes you are using:
`default_options = {"shared": False, "tbbmalloc": False, "tbbproxy": False}`
shared defaults to 'False' whereas in [old](https://github.com/conan-community/conan-tbb/blob/stable/4.4.4/conanfile.py#L28) version it was shared: True. intended?  
2) in new recipes i can see this, looks like a wrong if conditoin to me:
```
if self.settings.os != "Windows" and self.options.shared:
            self.output.warn("Intel-TBB strongly discourages usage of static linkage")
```
Isnt it meant to be 
`if self.settings.os != "Windows" and not self.options.shared` ?

**Comment by madebr** [comment]
@fulara This change to `shared=False` happened in https://github.com/conan-community/conan-tbb/commit/966e49346f4a10e6be2c40c22c25b7b4fffab7b4 by @uilianries .
That same commit also introduced the bad test for warning about a static tbb build.

I think it is a bug.

**Comment by SSE4** [comment]
shared cannot be default, as Windows doesn't support shared libraries, so it will end up into non-working default builds.
also, it's general practice for the most of conan packages to use `shared=False` by default, due to the various limitation of shared builds.
you still may apply `tbb:shared=True` in your profile or on command line, so it's just matter of default preferences.

**Comment by fulara** [comment]
@SSE4 Yep, this is something I expected - so to my opinion just that if statement is confusing.

I tested 4.4.4 and its working fine now. i did notice although a weird thing with 'version' not being propagated, but thats only used for building so its not a huge issue.  

Closing this issue.

**Comment by kepam** [comment]
Still this warning 
```
if self.settings.os != "Windows" and self.options.shared:
            self.output.warn("Intel-TBB strongly discourages usage of static linkage")
```
looks as mistake
could you @SSE4 , comment on this?
