### ISSUE TITLE
tbb 2019_UP4 doesnt build with clang and older gcc in path

### ISSUE THREAD

**Issue by fulara** [bincrafters/community#674]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **TBB/2019_U4**
  * Operating System+version: **Centos 7**
  * Compiler+version: **clang 7.0 + gcc 4.4.7**
  * Docker image: **unavailable**
  * Conan version: **conan 1.12.3**
  * Python version: **Python 3.7.0**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=clang
compiler.version=7.0
compiler.libcxx=libstdc++
build_type=Release
cppstd=14
os.version=rh6
```

### Steps to reproduce (Include if Applicable)
g++ --version -> g++ (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16)
clang --version -> clang version 7.0.1 
conan create . -s compiler=clang -s compiler.version=7.0 -s compiler.libcxx=libstdc++ test/test --build missing

### Logs (Include/Attach if Applicable)
First thing that raises eyebrows:
```
----Running------
> /usr/bin/make arch=intel64  stdlib=libstdc++ compiler=clang tbb tbbmalloc
-----------------
Created ./build/linux_intel64_clang_cc4.4.7_libc2.12_kernel2.6.32_release and ..._debug directories
```
notice how is says clang_cc4.4.7 i checked Makefiles in TBB and to get version out they use: `gcc --version`. so they do not check what compiler is being used. Whats more problematic is that based on that they enable/disable some of the features.

Letting the create run i am gettin gthis error:
```
../../include/tbb/pipeline.h:328:74: error: no template named 'has_trivial_copy_constructor' in namespace 'std'; did you mean 'is_trivially_copy_constructible'?
template<typename T> struct tbb_trivially_copyable { enum { value = std::has_trivial_copy_constructor<T>::value }; };
                                                                    ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                         is_trivially_copy_constructible
````
If i add gcc 7+ to my path build works.

Workaround i've decided to apply is this:
```
        if self.settings.compiler == "clang": 
@@ -85,6 +85,12 @@ that have future-proof scalability"""
         if not make:
             raise ConanInvalidConfiguration("This package needs 'make' in the path to build")
 
+        if self.settings.compiler == "clang": 
+            # manually set version as tbb currently extracts that always from 'gcc' command
+            add_flag('CXXFLAGS', '-DTBB_USE_GLIBCXX_VERSION=70000')
+
+        add_flag('CXXFLAGS', '-std=c++{}'.format(self.settings.cppstd))
+
```
Note use of USE_GLIBCXX variable. it seems to work for me now. however probably not a good way to go forward.

**Comment by madebr** [comment]
@fulara 
Can you test https://github.com/conan-community/conan-tbb/pull/25 and report back?

**Comment by fulara** [comment]
@madebr  only managed to test it now. looks good now thanks!
should i raise issue against tbb?

**Comment by madebr** [comment]
My patch has already been merged so there is no need for action.

Thanks for replying and testing!
