### ISSUE TITLE
[ffmpeg] Add support for openssl

### ISSUE THREAD

**Issue by bertrandGuyot** [bincrafters/community#676]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **ffmpeg/4.x**
  * Operating System+version: **Linux Debian Stretch**
  * Compiler+version: **gcc-8.2**
  * Conan version: **Conan 1.12.0**

### Description of your feature
The recipe is missing an option to enable/disable openssl, when building on Linux.

**Comment by SSE4** [comment]
@bertrandGuyot I've pushed changes to the testing branch: https://github.com/bincrafters/conan-ffmpeg/commit/71bd812c1f594a8f9394114592c205f3ec674ad1
it will take some time to build and merge into stable
please give a try and lemme know

**Comment by HOYS** [comment]
@SSE4 please see my comment on you commit concerning the incorrect disable option.

**Comment by SSE4** [comment]
@HOYS fixed, thanks for pointing

**Comment by bertrandGuyot** [comment]
I can now read HTTPS streams, so it seems to be good (at least in my context), thank you.

**Comment by SSE4** [comment]
okay, closing the issue then
