### ISSUE TITLE
Problem linking gflags when using glog package

### ISSUE THREAD

**Issue by dheater** [bincrafters/community#678]
### Description of Problem, Request, or Question
Using glog Conan package within my project

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **glog/0.3.5@bincrafters/stable**
  * Operating System+version: **Linux Centos 7.6**
  * Compiler+version: **4.8.5 20150623 (Red Hat 4.8.5-36)*
  * Docker image: **N/A**
  * Conan version: **Conan 1.7.0**
  * Python version: **Python 2.7.5**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)

```
[settings]
os=Linux
arch=x86_64
build_type=Debug
compiler=gcc
compiler.version=4.8
compiler.libcxx=libstdc++
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

Attempting to create a package using a `conanfile.py` with the following lines:

```
    requires = \
        "Catch2/2.6.1@catchorg/stable", \
        "glog/0.3.5@bincrafters/stable"
    generators = "cmake"
    default_options = "glog:shared=False", "glog:with_gflags=True"
```

### Logs (Include/Attach if Applicable)

Receving undefined references to gflags of the form:

```
.conan/data/glog/0.3.5/bincrafters/stable/build/ed3011e08a6082b45e0756976e89e85b1209be27/source_subfolder/src/logging.cc:106: undefined reference to `gflags::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)'
```

**Comment by uilianries** [comment]
Hi @dheater !

We will check this. Thanks!

**Comment by dheater** [comment]
Doh! Fixed it!

I needed:

```
target_link_libraries(myproj ${CONAN_LIBS})
```

Not

```
target_link_libraries(myproj glog)
```

Thanks. Daniel.

**Comment by dheater** [comment]
Posting a small example so I don't make that mistake again:

https://github.com/dheater/glog-test
