### ISSUE TITLE
xkbcommon/0.8.3 missing build requirement bison/3.0.5

### ISSUE THREAD

**Issue by danimtb** [bincrafters/community#682]
Please send inclusion request for bison/3.0.5 in case it is ready as it is needed to include xkbcommon whose inclusion request was already made.

Thanks!

**Comment by madebr** [comment]
Opportunity to review https://github.com/bincrafters/conan-bison/pull/4?

**Comment by SSE4** [comment]
@madebr @danimtb  I am looking closely into this

**Comment by SSE4** [comment]
@danimtb `bison/3.3.2@bincrafters/stable` and `bison_installer/3.3.2@bincrafters/stable` are now ready for the review.

**Comment by SSE4** [comment]
I am closing this, as inclusion requests were sent
