### ISSUE TITLE
[libcurl] Update OpenSSL version

### ISSUE THREAD

**Issue by Linux13524** [bincrafters/community#684]
### Question Description

Could you please update libcurls OpenSSL requirement to latest version?

**Comment by theirix** [comment]
@Linux13524, OpenSSL version can be overridden in your consuming conanfile, see [docs](https://docs.conan.io/en/latest/using_packages/conanfile_txt.html#overriding-requirements).

**Comment by Linux13524** [comment]
@SSE4 suggested to update the OpenSSL version

**Comment by SSE4** [comment]
unfortunately, it's hard to specify version range for OpenSSL, as it doesn't support semantic versioning, and their versioning scheme is completely crazy and changes all the time.

**Comment by Linux13524** [comment]
Would it be possible to use the [AliasConanfile](https://github.com/conan-community/conan-openssl/blob/release/1.0.2/conanfile.py) for OpenSSL 1.0.2?

**Comment by SSE4** [comment]
alias would definitely work
probably we need 3 of them - latest 1.0.2, latest 1.1.0, and latest 1.1.1

**Comment by Linux13524** [comment]
As far as I see it correctly there are already aliases for 1.0.2 and 1.1.1...

**Comment by SSE4** [comment]
cool, let's use them then, it would be much easier to update

**Comment by SSE4** [comment]
added aliases:

- OpenSSL/latest_1.0.1x@conan/stable
- OpenSSL/latest_1.0.2x@conan/stable
- OpenSSL/latest_1.1.0x@conan/stable
- OpenSSL/latest_1.1.1.x@conan/stable

updated libcurl: https://github.com/bincrafters/conan-libcurl/commit/e455c7d9891f0ecf28deaffc606a82721ac3c8af

**Comment by Linux13524** [comment]
Cool. Works fine. But Im curious: I can see them in bintray, but not in Github. Where did you add them?

**Comment by theirix** [comment]
@SSE4 using 'latest' alias for OpenSSL is essentially the same as using version ranges. I don't remember is it the recommended practice to use them in Bincrafters recipes or not? Wiki and tickets vary about it, reproducible builds required a fixed version before.

**Comment by SSE4** [comment]
@theirix version ranges are slow to resolve, they work like expressions which conan has to evaluate during the graph construction. aliases are different - they are just kind of "symbolic links" on bintray, and have no performance penalty. we're already using aliases across many packages, e.g. `msys2_installer/latest@bincrafters/stable` is an alias.

**Comment by SSE4** [comment]
confirmed as fixed, closing

**Comment by Croydon** [comment]
I'm disagreeing with introducing version ranges again as it is destroying reproducibility again. We should rather think about further automation for updating security relevant dependencies like this sooner.
