### ISSUE TITLE
[qt] installation error

### ISSUE THREAD

**Issue by AlbertoSacilotto** [bincrafters/community#686]
Package and Environment Details:
  * Package Name/Version: **qt/5.12.1/stable**
  * Operating System+version: **Windows 10 Home 1803 x64**
  * Compiler+version: **vc 15.9.7**
  * Conan version: **Conan 1.13.0**
  * Python version: **Python 3.7.2**
Configuration:
[requires]
qt/5.12.1@bincrafters/stable
[options]
Qt:qtserialport=True
Qt:qtserialbus=True
[generators]
qmake
cmake

Command:
conan install .. --build sqlite3 --build mysql-connector-c

Question Description
Trying to install I got this error:
qt/5.12.1@bincrafters/stable: Applying build-requirement: jom_installer/1.1.2@bincrafters/stable
qt/5.12.1@bincrafters/stable: WARN: Build folder is dirty, removing it: C:\.conan\11b929\1
qt/5.12.1@bincrafters/stable: Building your package in C:\.conan\11b929\1
qt/5.12.1@bincrafters/stable: Copying sources to build folder
qt/5.12.1@bincrafters/stable: Generator txt created conanbuildinfo.txt
qt/5.12.1@bincrafters/stable: Calling build()
c:\users\qtsdk\appdata\local\programs\python\python37-32\lib\site-packages\conans\util\fallbacks.py:9: UserWarning: Provide the output argument explicitly to function 'conans.client.tools.win.vcvars_command'
  warnings.warn("Provide the output argument explicitly{}".format(fn_str))
+ cd qtbase
+ C:\.conan\8b5685\1\qt5\qtbase\configure.bat -top-level -shared -confirm-license -silent -nomake examples -nomake tests -prefix C:\.conan\6afab1\1 -opensource -release -skip qtsvg -skip qtdeclarative -skip qtactiveqt -skip qtscript -skip qtmultimedia -skip qttools -skip qtxmlpatterns -skip qttranslations -skip qtdoc -skip qtlocation -skip qtsensors -skip qtconnectivity -skip qtwayland -skip qt3d -skip qtimageformats -skip qtgraphicaleffects -skip qtquickcontrols -skip qtx11extras -skip qtmacextras -skip qtwinextras -skip qtandroidextras -skip qtwebsockets -skip qtwebchannel -skip qtwebengine -skip qtcanvas3d -skip qtwebview -skip qtquickcontrols2 -skip qtpurchasing -skip qtcharts -skip qtdatavis3d -skip qtvirtualkeyboard -skip qtgamepad -skip qtscxml -skip qtspeech -skip qtnetworkauth -skip qtremoteobjects -skip qtwebglplugin -opengl desktop -openssl --glib=no --pcre=system --sql-mysql=yes --sql-psql=no --sql-odbc=yes -system-doubleconversion -system-freetype -system-harfbuzz -system-libjpeg -system-libpng -system-sqlite "ZLIB_INCDIR=C:\Users\QtSdk\.conan\data\zlib\1.2.11\conan\stable\package\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7\include" "ZLIB_LIBDIR=C:\Users\QtSdk\.conan\data\zlib\1.2.11\conan\stable\package\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7\lib" "ZLIB_LIBS=-lzlib" "OPENSSL_INCDIR=C:\Users\QtSdk\.conan\data\OpenSSL\1.1.1a\conan\stable\package\606fdb601e335c2001bdf31d478826b644747077\include" "OPENSSL_LIBDIR=C:\Users\QtSdk\.conan\data\OpenSSL\1.1.1a\conan\stable\package\606fdb601e335c2001bdf31d478826b644747077\lib" "OPENSSL_LIBS=-llibssl -llibcrypto -lcrypt32 -lmsi -lws2_32 -LC:\Users\QtSdk\.conan\data\zlib\1.2.11\conan\stable\package\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7\lib -lzlib" "PCRE2_INCDIR=C:\Users\QtSdk\.conan\data\pcre2\10.32\bincrafters\stable\package\286bd62b0b008f107ed63ab655dc322a5ce81db9\include" "PCRE2_LIBDIR=C:\Users\QtSdk\.conan\data\pcre2\10.32\bincrafters\stable\package\286bd62b0b008f107ed63ab655dc322a5ce81db9\lib" -D PCRE2_STATIC "PCRE2_LIBS=-lpcre2-posix -lpcre2-8 -lpcre2-16 -lpcre2-32 -LC:\Users\QtSdk\.conan\data\zlib\1.2.11\conan\stable\package\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7\lib -lzlib -LC:\Users\QtSdk\.conan\data\bzip2\1.0.6\conan\stable\package\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7\lib -lbz2" "DOUBLECONVERSION_INCDIR=C:\Users\QtSdk\.conan\data\double-conversion\3.1.1\bincrafters\stable\package\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7\include" "DOUBLECONVERSION_LIBDIR=C:\Users\QtSdk\.conan\data\double-conversion\3.1.1\bincrafters\stable\package\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7\lib" "DOUBLECONVERSION_LIBS=-ldouble-conversion" "FREETYPE_INCDIR=C:\Users\QtSdk\.conan\data\freetype\2.9.0\bincrafters\stable\package\bc24ecb3030892e9e91d30c72873e53de96982f6\include\freetype2" "FREETYPE_LIBDIR=C:\Users\QtSdk\.conan\data\freetype\2.9.0\bincrafters\stable\package\bc24ecb3030892e9e91d30c72873e53de96982f6\lib" "FREETYPE_LIBS=-lfreetype -LC:\Users\QtSdk\.conan\data\libpng\1.6.34\bincrafters\stable\package\606fdb601e335c2001bdf31d478826b644747077\lib -llibpng16 -LC:\Users\QtSdk\.conan\data\zlib\1.2.11\conan\stable\package\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7\lib -lzlib -LC:\Users\QtSdk\.conan\data\zlib\1.2.11\conan\stable\package\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7\lib -lzlib -LC:\Users\QtSdk\.conan\data\bzip2\1.0.6\conan\stable\package\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7\lib -lbz2" "HARFBUZZ_INCDIR=C:\.conan\7f07ed\1\include" "HARFBUZZ_LIBDIR=C:\.conan\7f07ed\1\lib" "HARFBUZZ_LIBS=-lharfbuzz -ldwrite -lrpcrt4 -lusp10" "LIBJPEG_INCDIR=C:\Users\QtSdk\.conan\data\libjpeg\9c\bincrafters\stable\package\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7\include" "LIBJPEG_LIBDIR=C:\Users\QtSdk\.conan\data\libjpeg\9c\bincrafters\stable\package\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7\lib" "LIBJPEG_LIBS=-llibjpeg" "LIBPNG_INCDIR=C:\Users\QtSdk\.conan\data\libpng\1.6.34\bincrafters\stable\package\606fdb601e335c2001bdf31d478826b644747077\include" "LIBPNG_LIBDIR=C:\Users\QtSdk\.conan\data\libpng\1.6.34\bincrafters\stable\package\606fdb601e335c2001bdf31d478826b644747077\lib" "LIBPNG_LIBS=-llibpng16 -LC:\Users\QtSdk\.conan\data\zlib\1.2.11\conan\stable\package\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7\lib -lzlib" "SQLITE_INCDIR=C:\Users\QtSdk\.conan\data\sqlite3\3.26.0\bincrafters\stable\package\984162a45217f92ffc38ce65fc57292bda5d14a6\include" "SQLITE_LIBDIR=C:\Users\QtSdk\.conan\data\sqlite3\3.26.0\bincrafters\stable\package\984162a45217f92ffc38ce65fc57292bda5d14a6\lib" "SQLITE_LIBS=-lsqlite3" "MYSQL_INCDIR=C:\Users\QtSdk\.conan\data\mysql-connector-c\6.1.11\bincrafters\stable\package\2dd376aed09d9690617bb9ae77e31f24847990db\include" "MYSQL_LIBDIR=C:\Users\QtSdk\.conan\data\mysql-connector-c\6.1.11\bincrafters\stable\package\2dd376aed09d9690617bb9ae77e31f24847990db\lib" "MYSQL_LIBS=-llibmysql -LC:\Users\QtSdk\.conan\data\zlib\1.2.11\conan\stable\package\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7\lib -lzlib" "ODBC_LIBS=-lodbc32 -lodbccp32" -mysql_config C:\Users\QtSdk\.conan\data\mysql-connector-c\6.1.11\bincrafters\stable\package\2dd376aed09d9690617bb9ae77e31f24847990db\bin\mysql_config -platform win32-msvc
 Please make sure to unset the QMAKESPEC, XQMAKESPEC, QMAKEPATH,
 and QMAKEFEATURES environment variables prior to building Qt.
qt/5.12.1@bincrafters/stable:
qt/5.12.1@bincrafters/stable: ERROR: Package '41bb8564d421c039b0d0cff47222f2f16281d5c8' build failed
qt/5.12.1@bincrafters/stable: WARN: Build folder C:\.conan\11b929\1
ERROR: qt/5.12.1@bincrafters/stable: Error in build() method, line 553
        _build("jom")
while calling '_build', line 546
        self.output.info(open('config.log', 'r').read())
        FileNotFoundError: [Errno 2] No such file or directory: 'config.log'

**Comment by ericLemanissier** [comment]
Hi
The log says `Please make sure to unset the QMAKESPEC, XQMAKESPEC, QMAKEPATH,
and QMAKEFEATURES environment variables prior to building Qt.`
Are these variables set before you call conan? Do you use a console provided by qt online installer?

**Comment by sassi67** [comment]
You are right: an ancient Qt4.8 installation left these variables set. Removed them and everzthing works

**Comment by ericLemanissier** [comment]
Great!
