### ISSUE TITLE
[libxml2] add ICU support

### ISSUE THREAD

**Issue by Johnnyxy** [bincrafters/community#687]
Hi there,
I am fiddling around with libxml2 and found out that it has [ICU](http://site.icu-project.org/) support. So one could build libxml2 that should use ICU for unicode processing. As I already adopted ICU in my code base I do not need an extra library ```iconv``` for libxml2 that does the same :).

A short description can be found at [libxml2@linuxfromscratch.org](http://www.linuxfromscratch.org/blfs/view/8.4/general/libxml2.html). In the end it means to build libxml2 with an additional ```./configure``` argument ```--with-icu```.

Best regards

**Comment by SSE4** [comment]
I think it depends on acquisition of `ICU` into conan-centre, which depends on splitting package into `icu` + `icu_installer`, which we have to model first.
but I suppose we can add it, with `False` by default, feel free to submit PR adding it.

**Comment by SSE4** [comment]
related: https://github.com/bincrafters/community/issues/668

**Comment by SSE4** [comment]
added option to link with ICU: https://github.com/bincrafters/conan-libxml2/commit/2ca0da93feda01d433b43e40c081a7ddd25e9671
it's off by default, as ICU is not yet in conan-centre
