### ISSUE TITLE
doctest copies headers instead of using CMake to install

### ISSUE THREAD

**Issue by cjdb** [bincrafters/community#688]
Right now Conan is simply copying the doctest header instead of using CMake to install it, which breaks `find_package`.

Would it be possible to get this installed using CMake instead please?

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **doctest/2.2.0@bincrafters/stable**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **gcc-5.4**
  * Docker image: **cjdb/cirrus-cpp:bionic**
  * Conan version: **conan 1.14.0**
  * Python version: **Python 3.7.0**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)

Any of the profiles matching `^[cg].*` found [here](https://github.com/cjdb/basic_project/tree/suggestions/config/conan/profiles).

### Steps to reproduce (Include if Applicable)

1. Install `doctest/2.2.0@bincrafters/stable`.
2. Add `find_package(doctest REQUIRED)` to your CMakeLists.txt
3. `conan install ...`
4. `conan build ... --configure`

### Logs (Include/Attach if Applicable)

Please let me know if these will be useful for this issue.

**Comment by SSE4** [comment]
@cjdb I've applied required changes to the testing branch, please give a try
https://github.com/bincrafters/conan-doctest/commit/101f5b832dbebd38b96539c388c9e8a1b3cdfa27

**Comment by cjdb** [comment]
Thanks! Which remote should I be pulling from in Conan?

**Comment by cjdb** [comment]
Looks like it's working now, thanks for your quick action 😄
