### ISSUE TITLE
[sqlite3] Build fails with android_ndk_installer (error: use of undeclared identifier 'posix_fallocate')

### ISSUE THREAD

**Issue by Linux13524** [bincrafters/community#689]
Building sqlite3 with the [android_ndk_installer](https://github.com/bincrafters/conan-android_ndk_installer) as build_requirement will fail.
Building with theodelrieu's [android-ndk package](https://github.com/theodelrieu/conan-android-ndk) works though, as well as setting `cmake.definitions["HAVE_POSIX_FALLOCATE"]` to `False`.

### Output:
```
[ 50%] Building C object CMakeFiles/sqlite3.dir/source_subfolder/sqlite3.c.o
/home/lk/.conan/data/sqlite3/3.27.2/linux13524/testing/build/bc062232bf4a54baac111c78fba085c836009822/source_subfolder/sqlite3.c:32842:42: error: use of undeclared identifier 'posix_fallocate'
  { "fallocate",    (sqlite3_syscall_ptr)posix_fallocate,  0 },
                                         ^
/home/lk/.conan/data/sqlite3/3.27.2/linux13524/testing/build/bc062232bf4a54baac111c78fba085c836009822/source_subfolder/sqlite3.c:32963:22: error: invalid application of 'sizeof' to an incomplete type
      'struct unix_syscall []'
    for(i=0; i<sizeof(aSyscall)/sizeof(aSyscall[0]); i++){
                     ^~~~~~~~~~
[...]
```

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **sqlite/3.27.2**
  * Operating System+version: **Fedora 29**
  * Compiler+version: **clang 8 ** ([android_ndk_installer](https://github.com/bincrafters/conan-android_ndk_installer))
  * Docker image: **-**
  * Conan version: **conan 1.11.2**
  * Python version: **Python 3.7.2**

### Conan profile (android)
```
[settings]
os=Android
arch=armv8
os.api_level=21
compiler=clang
compiler.libcxx=libc++
compiler.version=8
build_type=Release
os_build=Linux
arch_build=x86_64

[build_requires]
android_ndk_installer/r19b@bincrafters/stable
```

### Steps to reproduce
```
git clone https://github.com/bincrafters/conan-sqlite3.git
conan create . linux13524/testing -pr android -b missing
```

### Logs
[log.txt](https://github.com/bincrafters/community/files/2984290/log.txt)

**Comment by SSE4** [comment]
so, fix seems to be to define `HAVE_POSIX_FALLOCATE=False` for Android

**Comment by Linux13524** [comment]
@SSE4 Can you add it or should I create a PR?

**Comment by SSE4** [comment]
I'll add it

**Comment by SSE4** [comment]
@Linux13524 https://github.com/bincrafters/conan-sqlite3/commit/88e75ab7f3961390084e2b5b63f80a34f0bdc9b1

**Comment by Linux13524** [comment]
Cool. Thanks!
