### ISSUE TITLE
[qt] download xkbcommon from apt packages

### ISSUE THREAD

**Issue by Lorac** [bincrafters/community#690]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.12.2@bincrafters/stable**
  * Operating System+version: **Linux Debian 9.8**
  * Compiler+version: **gcc-6.3**
  * Docker image: **conanio/gcc6**
  * Conan version: **Conan 1.13.1**
  * Python version: **Python 3.5.3**

### Description of your feature

Given this configuration:
```
qt:opengl=desktop
qt:openssl=False
qt:with_pcre2=False
qt:with_pq=False
qt:with_odbc=False
qt:with_sqlite3=False
qt:with_mysql=False
qt:with_glib=False
qt:with_libjpeg=False
qt:with_freetype=False
qt:with_libpng=False
qt:with_libalsa=False
qt:with_openal=False
qt:with_doubleconversion=False
qt:widgets=False
qt:qtvirtualkeyboard=True
qt:qtgraphicaleffects=True
qt:qtxmlpatterns=True
qt:qtmultimedia=True
qt:shared=True
qt:qttranslations=True
qt:qtwayland=True
qt:qtquickcontrols2=True
```

`xkbcommon` should be fetched from my system packages. Since Qt 5.12.1, they removed the bundled version and the minimal required version now is 0.5.0. https://code.qt.io/cgit/qt/qtbase.git/tree/dist/changes-5.12.1?h=5.12.1#n152

I would like to make use of my zlib system packages too, instead of pulling from `conan/stable`

**Comment by ericLemanissier** [comment]
Thanks for the report. Completely replacing dependency on conan package by system packages does not seem to be a move in the right direction, because you loose all the benefits of conan. I would be very interested to have your rationale, because you are not the first one to ask such thing (https://github.com/bincrafters/community/issues/629#issuecomment-459153480)
If it is really needed, you can create a package named xkbcommon/system@foo/bar which just installs the system package, as described here https://github.com/bincrafters/community/issues/629#issuecomment-459625432
/cc @Croydon @solvingj @SSE4 @uilianries

**Comment by Lorac** [comment]
Well, I would like to be able to choose which one I want. When using the `configure` script from Qt I can choose from `-system` or bundled. Is this a limitation from Conan itself?

**Comment by ericLemanissier** [comment]
Well, the question is: in which case do you choose system package over conan package?

**Comment by Lorac** [comment]
As of right now, before Conan, we are building Qt ourselves without bundled libs, always used the system libraries. (First-time Conan users)

We don't need to fetch/build those libraries because they are already packaged in most distros. (we are all on Debian 9.8)

We always choose system packages.

I was surprised when for the first time it started to download zlib.. since I already have it on my system (not only for Qt)

Now that we are migrating towards Conan, maybe we shouldn't do that anymore?

**Comment by Croydon** [comment]
From my personal point of view using system packages in the Conan ecosystem should only be the last resort. If possible Conan packages should only rely on other Conan packages.

What is Conan trying to solve in the first place? The handling of dependencies, specific dependency versions with specific build flags across different operating systems and operating system versions. 

Relying on system packages, which may or may not exist, may exist in different versions and built with different flags it just a error-prone, unreliable mess. So why using Conan in the first place if we aren't using the advantages of it?

If for some reason there is a edge case where you want desperately to use system packages, then you can use the workaround @ericLemanissier suggested:

> If it is really needed, you can create a package named xkbcommon/system@foo/bar which just installs the system package, as described here #629 (comment) and override the requirement as described in https://docs.conan.io/en/latest/using_packages/conanfile_txt.html#overriding-requirements

**Comment by Lorac** [comment]
Perfect, I'll go ahead and use full Conan packages instead of trying to mismatch my own system packages and Conan's
