### ISSUE TITLE
Upstream Update: emsdk_installer 1.38.30

### ISSUE THREAD

**Issue by flostellbrink** [bincrafters/community#693]
### Package Details
  * Package Name: emsdk_installer 
  * Latest available Version: 1.38.30

The above mentioned version is newly released by the upstream project and not yet available within Bincrafters. Please add this version.

**Comment by SSE4** [comment]
seems like precompiled version `1.38.30` is not yet available. `emsdk list` gives me only:
```
The following precompiled SDKs are available for download: (Run "./emsdk update" to pull in the latest list)
         sdk-1.30.0-64bit         
         sdk-1.34.1-64bit         
         sdk-1.35.0-64bit         
         sdk-1.38.28-64bit        
         sdk-1.38.29-64bit        
```

**Comment by flostellbrink** [comment]
Thanks for looking into it. You are right, I did not check for precompiled versions.

I am specifically looking for a change I made in 1.38.28.
So I would be perfectly happy with an upgrade to either that or 29.

**Comment by SSE4** [comment]
new version has been added: https://github.com/bincrafters/conan-emsdk_installer/tree/stable/1.38.29
