### ISSUE TITLE
[sdl2] Problems with "jack" dependency on Linux

### ISSUE THREAD

**Issue by paulo-coutinho** [bincrafters/community#695]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **sdl2/2.0.9**
  * Operating System+version: **Ubuntu Xenial**
  * Compiler+version: **gcc-5**
  * Conan version: **conan 1.13.2**
  * Python version: **Python 3.7.0**

### Conan profile

```
include(default)

[settings]
os=Linux
arch=x86
```

and

```
include(default)

[settings]
os=Linux
arch=x86_64
```

### Steps to reproduce (Include if Applicable)

1. Clone: ```https://github.com/ezored/ezored-sdl2```  
2. Run: ```python3 make.py target linux_app conan```  
3. Run: ```python3 make.py target linux_app build```  

### Logs (Include/Attach if Applicable)

You can check travis for full log:

```https://travis-ci.org/ezored/ezored-sdl2```

Error:

```
Scanning dependencies of target Sample
[ 50%] Building CXX object CMakeFiles/Sample.dir/home/travis/build/ezored/ezored-sdl2/projects/samples/sdl2/main.cpp.o
[100%] Linking CXX executable bin/Sample
/usr/bin/ld: cannot find -ljack
collect2: error: ld returned 1 exit status
CMakeFiles/Sample.dir/build.make:83: recipe for target 'bin/Sample' failed
make[2]: *** [bin/Sample] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/Sample.dir/all' failed
make[1]: *** [CMakeFiles/Sample.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
ERROR: conanfile.py (linux_app/1.0.0@None/None): Error in build() method, line 38
	cmake.build()
	ConanException: Error 512 while executing cmake --build '/home/travis/build/ezored/ezored-sdl2/build/linux_app/Debug/x86/target' '--' '-j2'
```

**Comment by prsolucoes** [comment]
The same problem happens with "pulse".

I have disable both for now to try compile it, but i don't solve it.

I don't have problems with macos and windows.

Thanks for any help.

**Comment by SSE4** [comment]
these system requirements are always problematic, unfortunately, especially in case of cross-compiling, and also don't scale well due to the variations of processor architectures, linux distributions, package names and so on.
may be we can spend some time and figure out if things like pulseaudio, jack, vdpau, vaapi, X11 may be conanized as well

**Comment by ericLemanissier** [comment]
This recipe is now in the Conan Center Index.

Please migrate to the recipe version there.
If this is still an issue, please create a new issue in the Conan Center Index issue tracker.

Thanks!

https://conan.io/center/sdl
