### ISSUE TITLE
Upstream Update: catch2 2.7.0

### ISSUE THREAD

**Issue by mattgodbolt** [bincrafters/community#699]
### Package Details
  * Package Name: catch2
  * Latest available Version: 2.7.0

The above mentioned version is newly released by the upstream project and not yet available within Bincrafters. Please add this version.
 (2.6.0 is also missing if it's easy to add both at the same time).

Thanks!

**Comment by uilianries** [comment]
Hi @mattgodbolt !

The Catch2 package is no longer maintained by Bincrafters. We a [deprecation note](https://github.com/bincrafters/conan-catch2#packge-deprecation-notice) on the README.

The author CatchOrg the is current maintainer :100: 

https://github.com/catchorg/Catch2/blob/master/conanfile.py
https://bintray.com/catchorg/Catch2/Catch2%3Acatchorg

To install the official package:

    conan install -r conan-center Catch2/2.7.0@catchorg/stable

**Comment by mattgodbolt** [comment]
Understood: thanks for the quick reply!
