### ISSUE TITLE
[sdl2_ttf] Static build for Windows is not working

### ISSUE THREAD

**Issue by prsolucoes** [bincrafters/community#700]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **sdl2_ttf/2.0.15**
  * Operating System+version: **Windows**
  * Compiler+version: **vs2017**
  * Conan version: **conan 1.13.2**
  * Python version: **Python 3.7.0**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)

```
include(default)

[settings]
os=Windows
arch=x86_64
compiler=Visual Studio
compiler.version=15
```

### Steps to reproduce (Include if Applicable)

```
git clone https://github.com/ezored/ezored-sdl2.git
cd ezored-sdl2
python make.py target windows_app conan
python make.py target windows_app build
python make.py target windows_app package
```

### Logs (Include/Attach if Applicable)

Check "dist/windows_app/Release/x86_64". There is some **DLLs** inside it about SDL2 TTF project. The other like SDL2 IMAGE was statically compiled, only TTF is static in option but when compiled it generate shared library (DLL).

**Comment by prsolucoes** [comment]
Hi @SSE4,

Working with testing/2.0.15 !!!!

Can you put on release?

Thanks.

**Comment by SSE4** [comment]
@prsolucoes changes are now in stable branch, please give an another try

**Comment by prsolucoes** [comment]
Hi,

It is working.

Thanks.

**Comment by SSE4** [comment]
confirmed as fixed, closing
