### ISSUE TITLE
[glm] 0.9.9.4 conanfile.py not found

### ISSUE THREAD

**Issue by p-groarke** [bincrafters/community#701]
ERROR: C:\Users\me\.conan\data\glm\0.9.9.4\g-truc\stable\export\conanfile.py not found!

You can check your appveyor which is broken for windows. https://ci.appveyor.com/project/BinCrafters/conan-glm

**Comment by Croydon** [comment]
I restarted the job https://ci.appveyor.com/project/BinCrafters/conan-glm/builds/23402235

Might be a simple connection issue

**Comment by Croydon** [comment]
I noticed that two of the Travis jobs failed for the same reasons and restarted them as well https://travis-ci.com/bincrafters/conan-glm/jobs/187122668

Seems all good to me now

**Comment by p-groarke** [comment]
Yep looks good, will test this w-e. Thx

**Comment by p-groarke** [comment]
Still got the same error. Please reopen, thx.

**Comment by Croydon** [comment]
You are right the conan_export.tgz file is corrupt

**Comment by Croydon** [comment]
Now it should be fixed, please re-test

**Comment by p-groarke** [comment]
ayyy she builds! Thx for taking care of this quickly 👍
