### ISSUE TITLE
Upstream Update: Asio 1.13.0

### ISSUE THREAD

**Issue by Amphaal** [bincrafters/community#702]
### Package Details
  * Package Name:  **asio (standalone)**
https://bintray.com/bincrafters/public-conan/asio%3Abincrafters
  * Latest available Version: **1.13.0**
https://github.com/chriskohlhoff/asio/releases/tag/asio-1-13-0

The above mentioned version is newly released by the upstream project and not yet available within Bincrafters. 

Please add this version, as it fixes a critical bug interacting with websocketpp/0.8.1. Many thanks !

**Comment by SSE4** [comment]
new version has been added: https://github.com/bincrafters/conan-asio/tree/stable/1.13.0
