### ISSUE TITLE
Upstream Update: wxWidgets 3.1.2

### ISSUE THREAD

**Issue by nkshigeru** [bincrafters/community#703]
### Package Details
  * Package Name: **wxWidgets**
  * Latest available Version: **3.1.2**

The above mentioned version is newly released by the upstream project and not yet available within Bincrafters. Please add this version.

**Comment by Croydon** [comment]
It seems like the 3.1.2 release is changing the location of header files on Linux and macOS from `include/wx/...` to `include/wx-3.1/wx/` while keeping the old include path on Windows.

I think it's a pretty odd thing to do in such a version jump (do they follow semver?), and why this change only on macOS and Linus and not on all platforms?

@nkshigeru Are you aware of such changes? Is this expected?

**Comment by SSE4** [comment]
@Croydon check this out:
https://github.com/wxWidgets/wxWidgets/commit/8cf2b683be2c2878c2406d463f526524c5856b53
https://github.com/wxWidgets/wxWidgets/pull/1051
https://github.com/wxWidgets/wxWidgets/pull/1037

**Comment by Croydon** [comment]
@SSE4 Thanks for having a look

I see two options:
1) We do add `include/wx-3.1/` to the `includedirs`. Consumers can always just use the last part of the path in their applications no matter the platform. What version is getting used is managed by Conan either way
2) We leave it as it is. Consumers needs to add a switch-case to their includes depending on their platform. Updating means adapting the include paths

I think Number 1) is better here?

**Comment by nkshigeru** [comment]
@Croydon Thanks!

I think 1) is be better.
Because wx-config tells like that.

On Linux (Ubuntu on Windows Subsystem for Linux):
>  $ ./wx-config --cxxflags
-I/home/nkshigeru/.conan/data/wxwidgets/3.1.2/nkshigeru/testing/package/288c58d8845777dde884af24e640253e438dc8c5/lib/wx/include/gtk2-unicode-static-3.1
-I/home/nkshigeru/.conan/data/wxwidgets/3.1.2/nkshigeru/testing/package/288c58d8845777dde884af24e640253e438dc8c5/include/wx-3.1
-DWXUSINGDLL -D__WXGTK2__ -D__WXGTK__ -pthread

**Comment by Croydon** [comment]
I added `include/wx-{major}-{minor}` to the `includedirs`

3.1.2 seems to have more problems however. Now some linking issue is coming up:
https://travis-ci.com/bincrafters/conan-wxwidgets/builds/107159729
https://travis-ci.com/bincrafters/conan-wxwidgets/jobs/190532680#L5150

**Comment by nkshigeru** [comment]
bincrafters/conan-wxwidgets#7

**Comment by Croydon** [comment]
The Travis build will still take several hours. If it succeeds I guess we can close this

**Comment by SSE4** [comment]
binaries are available, closing
