### ISSUE TITLE
sdl2/2.0.9@bincrafters/stable fails to build on conanio/gcc7-armv7hf image

### ISSUE THREAD

**Issue by izzyreal** [bincrafters/community#704]
Reproduce:
* Download docker image [https://hub.docker.com/r/conanio/gcc7-armv7hf/](https://hub.docker.com/r/conanio/gcc7-armv7hf/)
* Run `docker run -it --rm conanio/conangcc7-armv7hf /bin/bash`
* Run `conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan`
* Run `conan install sdl2/2.0.9@bincrafters/stable --build sdl2`

Resulting error:
```
Cross-build from 'Linux:x86_64' to 'Linux:armv7hf'
sdl2/2.0.9@bincrafters/stable: ERROR: while executing system_requirements(): local variable 'arch_suffix' referenced before assignment
ERROR: Error in system requirements
```

**Comment by Croydon** [comment]
Related: https://github.com/bincrafters/community/issues/694

**Comment by Croydon** [comment]
So what is the difference between `armv7hf` and `armv7` when we are mapping it to the same Debian package suffix (`armhf`) anyway?

**Comment by izzyreal** [comment]
@Croydon I have no clue, except I read [somewhere](https://stackoverflow.com/questions/37790029/what-is-difference-between-arm64-and-armhf) that hf means hardware float(ing point instructions).

Also, mapping `armv7hf` to `armhf` is something I just tried and it's the first thing that made it build successfully -- as in, I'm not sure what I'm doing and whether it's the right thing.

I know very little about compilers and platforms, let alone ARM ones, so I'm sorry I can't be of more help here.

**Comment by Croydon** [comment]
I just saw that @helmesjo mapped `self.setting.arch == "armv7"` to `armel` which would be a contradiction to what we have done so far with `arvm7` (e.g. #694)

https://github.com/helmesjo/conan-magnum/blob/636125cc4620a1db38e9acd457e6c0d05b66f424/conanfile.py#L136

I believe we need a good source to figure that out or at least someone who is confident in this 😅

**Comment by uilianries** [comment]
Unfortunately Ubuntu artful doesn't provide armel remote. We could force to use armhf instead.

**Comment by Croydon** [comment]
> Unfortunately Ubuntu artful doesn't provide armel remote. We could force to use armhf instead.

So to get this right: The best thing would be mapping `armv7` to `armel`, but since Ubuntu doesn't provide packages for that, the next best match is `armhf`.

So we would map both `armv7` and `armv7hf` to `armhf`?

**Comment by uilianries** [comment]
Yes. I'll try to fix this.

**Comment by helmesjo** [comment]
Yeah don't trust what I did regarding this. I was totally shooting in the dark. 🔫😎

**Comment by uilianries** [comment]
It's not easy to be fixed ...

I can update the apt arch to `armhf`, but `pkg-config` can't find the correct .pc files from system. Even when I set `PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabihf/pkgconfig` 

Any ideas?

**Comment by ericLemanissier** [comment]
This recipe is now in the Conan Center Index.

Please migrate to the recipe version there.
If this is still an issue, please create a new issue in the Conan Center Index issue tracker.

Thanks!

https://conan.io/center/sdl
