### ISSUE TITLE
boost_build error on `--build` on some linux containers

### ISSUE THREAD

**Issue by solvingj** [bincrafters/community#705]
Per Mattew Jones in slack, the following command gives the following error when run in alpine linux docker container: 

https://github.com/bincrafters/conan-boost_build/blob/stable/1.69.0/conanfile.py

`conan install boost_build/1.69.0@bincrafters/stable --build`

```
ERROR: [Errno 2] No such file or directory: 
```

I was unable to reproduce locally on windows subsystem for linux.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **boost_build/1.69.0**
  * Operating System+version: **Linux Ubuntu 16.04**
  * Compiler+version: *?**
  * Docker image: **?**
  * Conan version: **Conan 1.12.0**
  * Python version: **Python 3.7.0**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux
os_build=Linux
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

`conan install boost_build/1.69.0@bincrafters/stable --build`

### Logs (Include/Attach if Applicable)
```
'/conan/.conan/data/boost_build/1.69.0/bincrafters/stable/package/44fcf6b9a7fb86b2586303e3db40189d3b511830/bin'
Traceback (most recent call last):
  File "/usr/bin/conan", line 11, in <module>
    load_entry_point('conan==1.12.0', 'console_scripts', 'conan')()
  File "/usr/lib/python3.6/site-packages/conans/conan.py", line 7, in run
    main(sys.argv[1:])
  File "/usr/lib/python3.6/site-packages/conans/client/command.py", line 1646, in main
    os.chdir(current_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/conan/.conan/data/boost_build/1.69.0/bincrafters/stable/package/44fcf6b9a7fb86b2586303e3db40189d3b511830/bin'
```

**Comment by solvingj** [comment]
This recipe also needs some refactoring.  Lines i would change: 

https://github.com/bincrafters/conan-boost_build/blob/stable/1.69.0/conanfile.py#L39
https://github.com/bincrafters/conan-boost_build/blob/stable/1.69.0/conanfile.py#L59
https://github.com/bincrafters/conan-boost_build/blob/stable/1.69.0/conanfile.py#L60

https://github.com/bincrafters/conan-boost_build/blob/stable/1.69.0/conanfile.py#L54-56
(make src and dst more explicit)

**Comment by matthew-d-jones** [comment]
This single docker command reproduces the problem:
```
docker run -it screamingudder/alpine-build-node:1.3.0 conan install boost_system/1.69.0@bincrafters/stable --build=boost_system -s arch=x86_64 -s arch_build=x86_64 -s build_type=Release -s compiler=gcc -s compiler.libcxx=libstdc++11 -s compiler.version=8 -s os=Linux -s os_build=Linux
```

Note, it downloads a docker image from dockerhub which is based on alpine linux and includes gcc, build tools and conan.

**Comment by solvingj** [comment]
Very strange situation.  I run the container interactively, then run the install command above, then cd to the following directory, the `b2` executable is there but will not run...

**Comment by remleduff** [comment]
The b2 that is downloaded is linked against glibc. Alpine linux only supplies limited glibc compatibility (it uses musl by default).

Adding --build boost_build to the command line above rebuilds b2 and works for me (TM).

**Comment by matthew-d-jones** [comment]
@remleduff Ooh, thank you, that makes perfect sense and does indeed solve the problem.

I'm used to conan just working when specifying `--build=outdated`, but I'm not sure there is anything it can do in this scenario.

**Comment by solvingj** [comment]
Thanks @remleduff , i thought about glibc, but i expected a different error for such a thing.  

@matthew-d-jones are we ok to close?

**Comment by matthew-d-jones** [comment]
Yes, please close. Many thanks for your time @solvingj and to @remleduff for the explanation.
