### ISSUE TITLE
Try to update and/or simplify build.py for conan-caf

### ISSUE THREAD

**Issue by solvingj** [bincrafters/community#71]
This recipe has a complex `build.py`.  There are a number of recent changes in Conan 1.0.0 that may enable us to simplify it, or change it in some way.  Just need someone to take a look for such an opportunity. 

https://github.com/bincrafters/conan-caf/blob/testing/0.15.5/build.py

**Comment by sourcedelica** [comment]
I'll take a look at it.

**Comment by sourcedelica** [comment]
Fixed in https://github.com/bincrafters/conan-caf/pull/7
