### ISSUE TITLE
Inclusion Request: Thrift

### ISSUE THREAD

**Issue by Croydon** [bincrafters/community#711]
### Package Details
  * Package Name: **thrift**
  * Operating Systems+versions: **Linux, Windows, macOS**
  * Compiler support: **all from current templates**
  * Conan recipe repository: **https://github.com/helmesjo/conan-thrift**
  * Wishlist url: **https://github.com/conan-io/wishlist/issues/143**

### Inclusion request
  * Fill all checkboxes with x if you agree with the statement or if it applies to your Conan recipe
  * [x] I want that my Conan recipe is getting included into the Bincrafters organisation (https://github.com/conan-io/wishlist/issues/143#issuecomment-478809818)
  * [x] I have used the Bincrafters templates to develop my Conan recipe - https://github.com/bincrafters/conan-templates
  * [x] My Conan recipe and all parts of it are licensed under the MIT license - https://choosealicense.com/licenses/mit/
    * Bincrafters are releasing all recipes under MIT license. If you want to have your recipe within Bincrafters we kindly ask you to do the same
    * it is okay if your test_package contains code from the upstream project under the upstream project's license, as long as it is clearly mentioned within the test_package files
  * [x] My Conan recipe covers (at least) the latest stable version which is available for the package
  * [x] I know that my Conan recipe is working on all operating system and compilers mentioned above right now
    * if not: please provide here links to your CI platforms and / or build logs and describe the problems you encounter
  * [x] I'm willing to help to maintain the recipe even after it is included into Bincrafters (https://github.com/conan-io/wishlist/issues/143#issuecomment-478809818)

**All credits to @helmesjo**

### Checklist for the Bincrafters team
  * Ignore this if you are not part of the Bincrafters team
  * [x] There is no such Conan package yet in conan-center, conan-community or Bincrafters
  * [x] The project is either popular or deserves to be maintained for another good reason (we can't package every single project out there)
  * [x] [bincrafters-conventions](https://github.com/bincrafters/bincrafters-conventions) reports no complains; the recipe fulfills our general quality requirements and conventions
  * [x] The recipe is cloned into our organisation; CI is enabled and configurated and succeeds
  * [x] There is a branch protection rule for `stable/*` branches, which requires a pull request with at least one approval first before things can get published
  * Considering granding the inclusion request author push rights to the recipe repository (there is no guarantee that everyone is getting push rights, we decide this on a case-to-case base)

**Comment by uilianries** [comment]
I think the recipe looks good but needs some update. We could accept and update, it will faster than requesting all changes

**Comment by Croydon** [comment]
Well, I'm bringing it in, so it's not really an outside request anyway. So that is exactly what I planned.

I see that you did go ahead an cloned the repo already. I actually wanted to squash the history, since it is originally a fork of the templates repository, which makes not much sense to more to keep around

**Comment by uilianries** [comment]
Ops, Sorry! We can squash anyway, we will need to force the push. I see no problem forcing the push, WDYT ?

**Comment by Croydon** [comment]
I have cut of the old history, should be fine now

The package should be ready now, but conan-center is blocked since libevent isn't in conan-center yet 🤔

**Comment by SSE4** [comment]
@Croydon we may send inclusion requests for both, libevent and thrift. libevent is here for a while, and used in many packages.

**Comment by Croydon** [comment]
Is the quality of libevent good enough?
  * there seems to be a weird workaround for a PATH problem on macOS? (in import())
  * do we really want to use an OpenSSL alias which is effectively a version range? Personally I would say no. I understand that we need to make sure that OpenSSL stays up-to-date but I would rather like to improve our tools in this direction

**Comment by SSE4** [comment]
1. we have to fix that
2. alias is not version range, it's a different concept. version range is dynamically computed expression, while alias is just a "symlink", or an alternative name of a package. it doesn't have overhead that version ranges have.

**Comment by Croydon** [comment]
> alias is not version range, it's a different concept. version range is dynamically computed expression, while alias is just a "symlink", or an alternative name of a package. it doesn't have overhead that version ranges have.

I didn't say that this alias **IS** a version range, but it **ACTS** like one. We still have non-reproducible builds

**Comment by uilianries** [comment]
let's use `OpenSSL/1.0.2r@conan/stable` to keep the package reproducible. And it's more explicit for who reads the recipe.

**Comment by uilianries** [comment]
@SSE4 Why we don't CMake to build libevent? The project offers a cmake file:

https://github.com/libevent/libevent/blob/release-2.1.8-stable/CMakeLists.txt

**Comment by SSE4** [comment]
@uilianries no idea, probably older versions didn't support CMake, or there were some issues with it. let's switch to CMake if possible.

**Comment by uilianries** [comment]
@SSE4 Yes, there is no cmake support for 2.0.x . I'll try the CMake approach

**Comment by Croydon** [comment]
For the protocol: We can look into using CMake starting with 2.2.x, but not right now: https://github.com/bincrafters/conan-libevent/pull/8

**Comment by Croydon** [comment]
Seems like @theirix have put this import() in several recipes. Could you please explain this problem further you workaround with this?

https://github.com/bincrafters/conan-libcurl/commit/0d4e7485d45739bc6f4d48a9218ef2d1e5335b0d
https://github.com/bincrafters/conan-libevent/commit/2d686d143ec90fee0496da80d0d458c1ab1876e1

**Comment by theirix** [comment]
@Croydon do you mean the problem that the copying solve? It is briefly described in a code comment. Autoconf creates little programs (`conftest`) that link against shared OpenSSL libraries and the only way to run `conftest` without dynamic linker errors is to bring dependent libraries into the current directory. It affects only shared library build on macOS 10.11+. The `imports` method guards the copying with OS check.

**Comment by uilianries** [comment]
Before to request Conan Center inclusion, I think we should update Thrift to follow Bison idea: 1 project x 2 recipes (1 installer + 1 library).

**Comment by Croydon** [comment]
@uilianries What is the advantage here? Saving disk space?

**Comment by uilianries** [comment]
It's not about disk usage, the problem is maintaining two separated projects which are related to the same thing. For us it looks normal, we can find easily I think, but most users will search for canon-thrift only.

For example, Protobuf created many confusion, I needed to explain about protobuf-installer many times.

**Comment by Croydon** [comment]
I don't mean why maintaining it in one repository, that is for sure better than having two repositories.

I mean why splitting it in two recipes (regular+installer). I know we had that discussion many, many times before... but I still don't see THE reason to do that. 🙈

**Comment by uilianries** [comment]
Oh sorry, the problem is when you need to cross compile some code. The thrift app needs to read some input to generate the cpp files, but it runs in your host (amd64), however the libraries that you need are built for your target arch (arm). 

For the thrift application you will need to use arch_build and for libraries you need arch. But you can't keep all together and install. Actually you could, but you would need to copy the application for all packages.

**Comment by Croydon** [comment]
Done! https://github.com/bincrafters/conan-thrift/pull/1
