### ISSUE TITLE
Upstream Update: Botan 2.10.0

### ISSUE THREAD

**Issue by reneme** [bincrafters/community#712]
### Package Details
  * Package Name: **conan-botan**
  * Latest available Version: **2.10.0**

The above mentioned version is newly released by the upstream project and not yet available within Bincrafters. Please add this version.

#### Prepared Recipe Update

I already pushed a branch [`stable/2.10.0`](https://github.com/reneme/conan-botan/tree/stable/2.10.0) that both bumps the version number and uses a newly added `--extra-cxxflags` configure parameter. The latter was added as a result of a discussion both [in the bincrafters community](https://github.com/bincrafters/community/issues/631) and in [a botan issue](https://github.com/bincrafters/conan-botan/pull/6). Please update the upstream recipe.

@SSE4 @uilianries

**Comment by SSE4** [comment]
doesn't build for OSX: https://travis-ci.com/bincrafters/conan-botan/jobs/189890848

**Comment by SSE4** [comment]
new version is available, closing
