### ISSUE TITLE
[protobuf] linker warnings from generating excessive library paths

### ISSUE THREAD

**Issue by Cyberdr8gon** [bincrafters/community#713]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **protobuf/3.5.1**
  * Operating System+version: **MacOS **
  * Compiler+version: **XCode 10.1**
  * Conan version: **conan 1.11.2**
  * Python version: **Python 2.7.10**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=10.0
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]

### Steps to reproduce (Include if Applicable)
(using correct python version)
pip install matplotlib numpy 
brew install swig
brew install cmake
git clone git@bitbucket.org:avslab/basilisk.git
cd basilisk
git checkout feature/Viz_Interface
mkdir dist
cd dist
cmake ../src -DUSE_PROTOBUFFERS=ON -G Xcode

Proceed to build the xcode project. The Xcode project produces a number of warnings as follows for all targets linking protobuffers:
Apple Mach-O Linker (ld) Warning:
Directory not found of option '-L/Users/example/.conan/data/protobuf/3.5.1/bincrafters/stable/package/(hash)/lib/Debug'

https://github.com/conan-io/cmake-conan/issues/130 suggested that it may be using multi-config definitions in package_info()

**Comment by Croydon** [comment]
Please provide a link to source and the full build logs
