### ISSUE TITLE
sdl2/2.0.9 X11 conflict

### ISSUE THREAD

**Issue by izzyreal** [bincrafters/community#714]
In conanfile.py we need to add
```
                elif self.settings.arch == "armv7hf":
                    arch_suffix = ':armhf'
```
This way we can almost compile succesfully for Raspberry Pi using [https://hub.docker.com/r/conanio/gcc7-armv7hf/](https://hub.docker.com/r/conanio/gcc7-armv7hf/).

I had to perform [this modification](https://github.com/anyc/steam-overlay/issues/61#issuecomment-20571907), then it compiles fine. Is there a way we can make the conan sdl2 package overcome this issue without having to modify `/usr/include/X11/Xlib.h`?

**Comment by Croydon** [comment]
Please don't combine different problems into one issue.

The missing architecture problem is already reported here: #704

**Comment by Croydon** [comment]
I added support for armv7hf a while ago

The remaining issue with X11 is tracked here: #696
