### ISSUE TITLE
[Question] Hooks inclusion

### ISSUE THREAD

**Issue by uilianries** [bincrafters/community#716]
### Question Description

Hi @bincrafters/administrators !

Since Conan offers some nice hooks, I think we could add them to our CI jobs.

Some possible hooks to be included:

- [Conan Center Reviewer](https://github.com/conan-io/hooks/blob/master/hooks/conan-center_reviewer.py)
- [Attribute Checker](https://github.com/conan-io/hooks/blob/master/hooks/attribute_checker.py)
- [Binary Linter](https://github.com/conan-io/hooks/blob/master/hooks/binary_linter.py)
- [Github Updater](https://github.com/conan-io/hooks/blob/master/hooks/github_updater.py)
- [SPDX Checker](https://github.com/conan-io/hooks/blob/master/hooks/spdx_checker.py)

Should we include those hooks?
If yes, should we consider any warning as error?

Regards!

**Comment by Croydon** [comment]
There is definitely some overlap to bincrafters-conventions, e.g. the SPDX checker hook got implemented by @SSE4 after it made its way into bincrafters-conventions (at least I don't think that was a coincident).

I'm not sure if it is helpful when we enable these hooks on all jobs. 
Why should we check the same thing like attributes on each job?
Why should we check if GitHub attributes need updating on each job?
On the other hand thinks like Binary Linter requires to run on every job
Enabling it on every job might add to the overall build time and makes logs even bigger
But if we don't enable it on all jobs, which one would we pick? Would be kinda random

With bincrafters-conventions we could add one additional job which is independent from any actual Conan build. The real problem I see here is some engineering overlap for the implementations

**Comment by SSE4** [comment]
I'd personally avoid running these hooks on CI, as they communicate with external services (GitHub, bintray), so they add additional points of failures in case of network errors. builds are already pretty unreliable.

**Comment by SSE4** [comment]
for now I think it's not going to happen. conan center inclusion requires all these things to pass, so no need to make CI even more long and unstable...
