### ISSUE TITLE
Upstream Update: cpprestsdk 2.10.12

### ISSUE THREAD

**Issue by prsolucoes** [bincrafters/community#719]
### Package Details
  * Package Name: **cpprestsdk**
  * Latest available Version: **2.10.12**

Official repository:
https://github.com/Microsoft/cpprestsdk/tree/v2.10.12

The above mentioned version is newly released by the upstream project and not yet available within Bincrafters. Please add this version.

**Comment by Croydon** [comment]
2.10.12 should be available in a while

https://travis-ci.com/bincrafters/conan-cpprestsdk/builds/109857813
https://ci.appveyor.com/project/bincrafters/conan-cpprestsdk/builds/24147540

https://github.com/bincrafters/conan-cpprestsdk/tree/stable/2.10.12
