### ISSUE TITLE
Troubleshoot ZMQ Mingw builds

### ISSUE THREAD

**Issue by solvingj** [bincrafters/community#72]
https://ci.appveyor.com/project/BinCrafters/conan-zmq/build/job/ts30wbje4gfnqcjv

Will disable mingw for now, but would like to see this revisited.

**Comment by SSE4** [comment]
@solvingj I've checked in branch mingw/4.2.2, it works locally

**Comment by solvingj** [comment]
disabling mingw builds per #80
