### ISSUE TITLE
[ruby_installer] ruby LoadError on Linux

### ISSUE THREAD

**Issue by nkshigeru** [bincrafters/community#721]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **ruby_installer/2.5.1**
  * Operating System+version: **Ubuntu 18.04.2 LTS (WSL)**
  * Compiler+version: **gcc-7.3.0**
  * Conan version: **conan 1.14.1**
  * Python version: **Python 2.7.15rc1**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=7
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]

### Steps to reproduce (Include if Applicable)
Create a conanfile that uses ruby on build.
```
from conans import ConanFile


class TestrubyConan(ConanFile):
    name = "test-ruby"
    version = "0.0.0"

    build_requires = "ruby_installer/2.5.1@bincrafters/stable"

    def build(self):
        self.run("ruby -v")   # OK
        self.run("ruby -e \"puts 'hello'\"")  # Error
```

### Logs (Include/Attach if Applicable)
On Linux, `conan create` fails with:
```
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
Traceback (most recent call last):
        1: from <internal:gem_prelude>:2:in `<internal:gem_prelude>'
<internal:gem_prelude>:2:in `require': cannot load such file -- rubygems.rb (LoadError)
```
On Windows, it works
```
ruby 2.5.1p57 (2018-03-29 revision 63029) [x64-mingw32]
hello
```

**Comment by nkshigeru** [comment]
With `--disable-gems`, the error about `rubygems.rb` will disappear:
```
self.run("ruby -e \"puts 'hello'\" --disable-gems")
=> hello
```
but `require` any standard libraries fails:
```
self.run("ruby -e \"require 'date';puts Date.today\" --disable-gems")
# expected: 2019-04-07
=> Traceback (most recent call last):
        1: from -e:1:in `<main>'
-e:1:in `require': cannot load such file -- date (LoadError)
```

Looking at LOAD_PATH($:)
```
self.run("ruby -e \"puts $:\" --disable-gems")
=>
/home/conan/.conan/data/ruby_installer/2.5.1/bincrafters/stable/package/44fcf6b9a7fb86b2586303e3db40189d3b511830/lib/ruby/site_ruby/2.5.0
/home/conan/.conan/data/ruby_installer/2.5.1/bincrafters/stable/package/44fcf6b9a7fb86b2586303e3db40189d3b511830/lib/ruby/site_ruby/2.5.0/x86_64-linux
/home/conan/.conan/data/ruby_installer/2.5.1/bincrafters/stable/package/44fcf6b9a7fb86b2586303e3db40189d3b511830/lib/ruby/site_ruby
/home/conan/.conan/data/ruby_installer/2.5.1/bincrafters/stable/package/44fcf6b9a7fb86b2586303e3db40189d3b511830/lib/ruby/vendor_ruby/2.5.0
/home/conan/.conan/data/ruby_installer/2.5.1/bincrafters/stable/package/44fcf6b9a7fb86b2586303e3db40189d3b511830/lib/ruby/vendor_ruby/2.5.0/x86_64-linux
/home/conan/.conan/data/ruby_installer/2.5.1/bincrafters/stable/package/44fcf6b9a7fb86b2586303e3db40189d3b511830/lib/ruby/vendor_ruby
/home/conan/.conan/data/ruby_installer/2.5.1/bincrafters/stable/package/44fcf6b9a7fb86b2586303e3db40189d3b511830/lib/ruby/2.5.0
/home/conan/.conan/data/ruby_installer/2.5.1/bincrafters/stable/package/44fcf6b9a7fb86b2586303e3db40189d3b511830/lib/ruby/2.5.0/x86_64-linux
```
LOAD_PATH indicates under `/home/conan/` the prefex path used at configure, but it deffers from runtime environment.

**Comment by SSE4** [comment]
@uilianries do you have an expirience with ruby? I am not really familiar with it

**Comment by uilianries** [comment]
No, but I can check it later

**Comment by uilianries** [comment]
I can confirm the bug, however ruby_installer/2.3.3 is working well.

**Comment by SSE4** [comment]
@nkshigeru may you test with `ruby_installer/2.3.3`?

**Comment by nkshigeru** [comment]
@uilianries @SSE4 Thank you for your reply.

`ruby_installer/2.3.3` does not work either.

```
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]
<internal:gem_prelude>:4:in `require': cannot load such file -- rubygems.rb (LoadError)
        from <internal:gem_prelude>:4:in `<internal:gem_prelude>'
```

**Comment by uilianries** [comment]
@nkshigeru !

Did you build ruby_installer or just installed?

How can I reproduce your error, which commands/scripts are you using?

Using your last conanfile.py it works well when running in Conan Docker images.

**Comment by nkshigeru** [comment]
@uilianries 
I did not build ruby_installer manually. 
When running `conan create . user/testing`, prebuilt ruby_installer binaries are downloaded. 

The problem is location of HOME directory.
If the username of the docker image is `conan`, it will work. Because the ruby_installer binaries are built with prefix `/home/conan/.conan`
But when downloading by different user, it will fail.

To reproduce the error with docker, change username.
[gcc_7.2_user.zip](https://github.com/bincrafters/community/files/3214910/gcc_7.2_user.zip)
(originally from https://github.com/conan-io/conan-docker-tools/tree/master/gcc_7.2)

**Comment by uilianries** [comment]
I see, thanks for your explanation, it clarifies our problem.

**Comment by SSE4** [comment]
@nkshigeru changes were applied, please give an another try and let us know

**Comment by nkshigeru** [comment]
@uilianries @SSE4  It works! Thank you!

**Comment by uilianries** [comment]
Nice! Closing this issue now. I'll request the inclusion of ruby_installer in Conan Center.
