### ISSUE TITLE
bincrafters-conventions: Check if system_requirement can be replaced with Conan package

### ISSUE THREAD

**Issue by Croydon** [bincrafters/community#722]
I would like the enhance the bincrafters-conventions tool with a check for the recipes:
  * Is it using system_requirements()?
  * If yes, is it installing packages we do created Conan packages for in the meantime?
  * If yes, let the check fail and remind the user to update the recipe to use the Conan package instead of the system_requirement

**Comment by uilianries** [comment]
It's a nice feature, but I think it's not easy to be implemented. For example, when installing with APT, most of libraries use the name libxxx-dev, but we use only conan-xxx. We will need to verify some chunks to validate the name.

**Comment by Croydon** [comment]
I did not had in mind to automate this, as it is too complex to do such a thing and doesn't justify what we get from it.

But I would implement a search for specific, hard-coded packages if we do have Conan packages for them and users will get a notice that they should probably replace the system_requirement with a Conan requirement.

Workflow for adding new ones to the list could be:
  * whenever anyone of us is replacing a system_requirement with a Conan requirement in a recipe
  * and it isn't already in the list
  * we add it to the list in bincrafters-conventions

It's too annoying that when a package has system_requirements that we would need to go through all them manually and look if we have a Conan package for them.

And not replacing them is also not nice.

**Comment by uilianries** [comment]
I totally agree and I think it's possible to filter by package name.

I don't have a good how to filter the correct package name. For example, we could install libasound-dev, but our Conan package is alsa. Maybe we could filter by name or even creating a table with most common names.

**Comment by Croydon** [comment]
This is actually extremely complicated

I would say we should see the transfer to CCI as an opportunity to work through our system_requirements() and reduce them to the absolute minimum. Allow very, very low-level stuff should be allowed as system_requirements()
