### ISSUE TITLE
boost_build should set BOOST_BUILD_PATH as a list

### ISSUE THREAD

**Issue by grisumbras** [bincrafters/community#725]
`boost_build` package has this line in its recipe:

```
self.env_info.BOOST_BUILD_PATH = os.path.join(self.package_folder, "share", "boost-build", "src", "kernel")
```

This allows b2 to correctly bootstrap itself, but because its not set as a list, Conan then treats it as a singular value and any modifications to it coming from other packages will be thrown away. This in particular makes it largely useless to distribute b2 extensions via Conan.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **boost_build/1.69.0**

**Comment by SSE4** [comment]
changes were merged
