### ISSUE TITLE
libcurl packaging issue when built a step at a time

### ISSUE THREAD

**Issue by mattgodbolt** [bincrafters/community#726]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libcurl/7.61.1((
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **gcc-8.2**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=7
compiler.libcxx=libstdc++11
build_type=Release
os.distro=ubuntu18.04
[options]
[build_requires]
[env]
```
### Steps to reproduce (Include if Applicable)

We build external packages in stages so we can interpose SHA checking in existing conanfile.pys and their intermediate source that the download.

* Grab source to `conan-libcurl` from GitHub
* Build in stages:
  * `conan install . --build=OpenSSL`
  * `conan imports .`
  * `conan source .`
  * `conan build .`
* Package (noting that `libcurl.a` _are_ included)
  * `conan package .`
* Export package:
  * `conan export-pkg . libcurl/7.61.1@mattgodbolt/testing`
  * **Note that the library files are missing**

It's expected that anything previously packaged by `conan package` should be included when one `export-pkg`s on the directory.

### Logs/output
`conan package .` :

```
 $ conan package .
conanfile.py (libcurl/7.61.1@None/None): Generating the package
conanfile.py (libcurl/7.61.1@None/None): Package folder /tmp/conan-libcurl/package
conanfile.py (libcurl/7.61.1@None/None): Calling package()
conanfile.py (libcurl/7.61.1@None/None) package(): Packaged 2 files: curl-config, COPYING
conanfile.py (libcurl/7.61.1@None/None) package(): Packaged 1 '.pem' file: cacert.pem
conanfile.py (libcurl/7.61.1@None/None) package(): Packaged 8 '.h' files
conanfile.py (libcurl/7.61.1@None/None) package(): Packaged 1 '.a' file: libcurl.a
conanfile.py (libcurl/7.61.1@None/None) package(): Packaged 1 '.la' file: libcurl.la
conanfile.py (libcurl/7.61.1@None/None) package(): Packaged 1 '.pc' file: libcurl.pc
conanfile.py (libcurl/7.61.1@None/None) package(): Packaged 1 '.m4' file: libcurl.m4
conanfile.py (libcurl/7.61.1@None/None): Package 'package' created
```

`conan export-pkg` :

```
Exporting package recipe
libcurl/7.61.1@mattgodbolt/testing exports: Copied 1 '.md' file: LICENSE.md
libcurl/7.61.1@mattgodbolt/testing exports_sources: Copied 1 '.am' file: lib_Makefile_add.am
libcurl/7.61.1@mattgodbolt/testing exports_sources: Copied 1 '.txt' file: CMakeLists.txt
libcurl/7.61.1@mattgodbolt/testing: A new conanfile.py version was exported
libcurl/7.61.1@mattgodbolt/testing: Folder: /home/mattgodbolt/.conan/data/libcurl/7.61.1/mattgodbolt/testing/export
libcurl/7.61.1@mattgodbolt/testing: WARN: Forced build from source
Packaging to 6f95efc04fe36dd48a14ca1bceb7e0d3f6026ced
libcurl/7.61.1@mattgodbolt/testing: Generating the package
libcurl/7.61.1@mattgodbolt/testing: Package folder /home/mattgodbolt/.conan/data/libcurl/7.61.1/mattgodbolt/testing/package/6f95efc04fe36dd48a14ca1bceb7e0d3f6026ced
libcurl/7.61.1@mattgodbolt/testing: Calling package()
libcurl/7.61.1@mattgodbolt/testing package(): Packaged 1 '.pem' file: cacert.pem
libcurl/7.61.1@mattgodbolt/testing package(): Packaged 1 file: COPYING
libcurl/7.61.1@mattgodbolt/testing: Package '6f95efc04fe36dd48a14ca1bceb7e0d3f6026ced' created
Package revision e5501162545ad35d90557b0cb74c426f
```

**Comment by Croydon** [comment]
If I understand you correctly you are doing this particular way of building for security reasons to check the checksum of the source code downloaded by the conanfile?

Would it also be enough for you when
a) the recipes have a sha256 checksum for downloads (that is a bincrafteers-convention for a while now, but long-existing recipes may not have it yet)
b) you make sure to use a specific revision of the recipe, i.e. you know the recipe and checked it and you know there is a specific checksum which you also checked

_________

This work flows should work nonetheless, but we have pretty regularly problems with paths/relative paths in several build tools/breakages for specific workflows etc. It's kinda hard to get so many different system and configurations to work together nicely

**Comment by Croydon** [comment]
I'm working on an update to libcurl 7.64.1 and also trying to clean up the recipe while doing so.

I would assume this problem is since `autotools.install()` is executed in `build()` instead `package()`, which is also a convention introduced some while ago

**Comment by mattgodbolt** [comment]
Replying to your first comment:

* If I can guarantee all sources downloaded have a SHA, yes. And any packages they depend on (which is probably already ok).
* Yes I already git clone a SHA of the recipe and build from that.

This will obviate my weird needs :)

Replying to your second: Sounds likely yes. Is this a problem, more generally?

**Comment by mattgodbolt** [comment]
And thanks so much for taking the time to look in to this!

**Comment by Croydon** [comment]
I realized that I used a misleading formulation earlier: It is a convention now that install() steps happen in package(), just got not applied to libcurl so far.

@mattgodbolt Could you please test curl/7.64.1?

**Comment by mattgodbolt** [comment]
To be clear I'm testing `libcurl/7.64.1` (not `curl/7.64.1` which is what I ended up calling my own homegrown package, which confused my testing initially... :) ) ...

So.,... it now seems that `export-pkg` re-configures and rebuilds everything a second time :/

```
Packaging...
conanfile.py (libcurl/7.64.1@None/None): Generating the package
conanfile.py (libcurl/7.64.1@None/None): Package folder /tmp/tmpb82hncod/git_src/package
conanfile.py (libcurl/7.64.1@None/None): Calling package()
conanfile.py (libcurl/7.64.1@None/None): Calling:
 > ./configure '--without-libidn2' '--without-librtmp' '--without-libmetalink' '--without-libpsl' '--without-nghttp2' '--without-brotli' '--with-ssl=/tmp/tmp2_uwqech/.conan/data/OpenSSL/1.1.0g/coinbase/stable/package/36b8df5b049c610aeab5726a4602ef4c8fb0f917' '--without-libssh2' '--with-zlib=/tmp/tmp2_uwqech/.conan/data/zlib/1.2.11/coinbase/stable/package/40432e82da0249d65623205af782aed88d808dcb/lib' '--disable-shared' '--enable-static' '--disable-ldap' '--prefix=/tmp/tmpb82hncod/git_src/package' '--bindir=${prefix}/bin' '--sbindir=${prefix}/bin' '--libexecdir=${prefix}/bin' '--libdir=${prefix}/lib' '--includedir=${prefix}/include' '--oldincludedir=${prefix}/include' '--datarootdir=${prefix}/share' 
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether make supports nested variables... yes
checking whether to enable debug build options... no
checking whether to enable compiler optimizer... (assumed) yes
checking whether to enable strict compiler warnings... no
checking whether to enable compiler warnings as errors... no
checking whether to enable curl debug memory tracking... no
checking whether to enable hiding of library internal symbols... yes
checking whether to enable c-ares for DNS lookups... no
checking whether to disable dependency on -lrt... (assumed no)
checking for path separator... :
checking for sed... /bin/sed
checking for grep... /bin/grep
```

... and so on. Will get a repro case as per my steps above.

**Comment by mattgodbolt** [comment]
```
$ conan --version
Conan version 1.14.1
```

I ran:
* `git checkout testing/7.64.1`
* `conan install . --build=OpenSSL`
* `conan imports .`
* `conan source .`
* `conan build .` (builds)...

Then...

* `conan package .`  <- this step starts the process all over again: configuring and building :face_with_head_bandage: The build is fast as the code has been already built, but still it means the configuration might just differ from the built stuff earlier...

* `conan export-pkg . libcurl/7.64.1@mattgodbolt/testing` <-- this step start the process a third time, configuring and building (again quickly but...)

**Comment by Croydon** [comment]
I believe that autotools behaves now the same way that CMake behaves in this workflow. I'm not sure if there are more elegant ways, but if so they would mean a change of conventions across all packages.

That or autotools configure is not comparable with CMake configure, but I wouldn't be aware of that as I'm not familiar enough with autotools.

I'm guessing that this is acceptable for now, as both workflows do work now.
And for the security matter: The download is now checked against the SHA256 checksum.

@mattgodbolt What do you think?

**Comment by mattgodbolt** [comment]
I guess so; please close this off. It's surprising (and disconcerting) as all the rest of the state is captured during the `build` step, but I don't have any ideas.
