### ISSUE TITLE
[qt] The recipes are not available from Conan-center anymore?

### ISSUE THREAD

**Issue by Adnn** [bincrafters/community#727]
Tried to install Qt today, following [the reference found here](https://bintray.com/bincrafters/public-conan/qt%3Abincrafters/5.12.2%3Astable), with:

    conan install qt/5.12.2@bincrafters/stable

But I am getting "not found" error:

> ...
> qt/5.12.2@bincrafters/stable: Trying with 'conan-center'...
> ERROR: Unable to find 'qt/5.12.2@bincrafters/stable' in remotes

Is there something obvious missing here, or did the package disappear?

---

Also:

    $ conan --version
    Conan version 1.14.1

    $ conan search -r conan-center qt/*
    There are no packages matching the 'qt/*' pattern

    $ conan remote list
    conan-center: https://conan.bintray.com [Verify SSL: True]

**Comment by ericLemanissier** [comment]
qt recipe is not yet available on conan-center. You should first add the bincrafters remote : `conan remote add <REMOTE> https://api.bintray.com/conan/bincrafters/public-conan` as specified in the "set me up!" button on the page you linked.

**Comment by Adnn** [comment]
I did not realize this was a different repository: thank you very much for pointing that out!

**Comment by ericLemanissier** [comment]
you are welcome, it's true that it is not always obvious
