### ISSUE TITLE
[SFML 2.5.1] Unable to build on linux with clang-8

### ISSUE THREAD

**Issue by Milerius** [bincrafters/community#729]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **sfml/2.5.1@bincrafters/stable**
  * Operating System+version: **Linux Ubuntu 19.04**
  * Compiler+version: **clang++-8**
  * Conan version: **conan 1.14.1**
  * Python version: **Python 3.7.0**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)

```
➜  build git:(master) conan profile show clang  
Configuration for profile clang:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=clang
compiler.version=8
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
conanfile.txt
```
[requires]
sfml/2.5.1@bincrafters/stable
entt/3.x.y-WIP@skypjack/stable
asio/1.13.0@bincrafters/stable
jsonformoderncpp/3.6.1@vthiery/stable
doctest/2.3.1@bincrafters/stable
doom_strong_types/1.0.0@bintray/stable

[generators]
cmake
```
remote:
```
➜  build git:(master) conan remote list       
bincrafters: https://api.bintray.com/conan/bincrafters/public-conan [Verify SSL: True]
skypjack: https://api.bintray.com/conan/skypjack/conan [Verify SSL: True]
conan-doom_strong_types: https://api.bintray.com/conan/milerius/doom_strong_types [Verify SSL: True]
```

```bash
mkdir build
cd build
conan install -pr clang --build sfml ../
```

output:
```
➜  build git:(master) conan install --profile clang --build sfml ../
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=clang
compiler.libcxx=libc++
compiler.version=8
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

sfml/2.5.1@bincrafters/stable: WARN: Forced build from source
conanfile.txt: Installing package
Requirements
    asio/1.13.0@bincrafters/stable from local cache - Cache
    doctest/2.3.1@bincrafters/stable from local cache - Cache
    doom_strong_types/1.0.0@bintray/stable from local cache - Cache
    entt/3.x.y-WIP@skypjack/stable from local cache - Cache
    jsonformoderncpp/3.6.1@vthiery/stable from local cache - Cache
    sfml/2.5.1@bincrafters/stable from local cache - Cache
Packages
    asio/1.13.0@bincrafters/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    doctest/2.3.1@bincrafters/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    doom_strong_types/1.0.0@bintray/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    entt/3.x.y-WIP@skypjack/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    jsonformoderncpp/3.6.1@vthiery/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    sfml/2.5.1@bincrafters/stable:b6ed6852348b865abb04a1f44074bcd81d14d521 - Build

asio/1.13.0@bincrafters/stable: Already installed!
doctest/2.3.1@bincrafters/stable: Already installed!
doom_strong_types/1.0.0@bintray/stable: Already installed!
entt/3.x.y-WIP@skypjack/stable: Already installed!
jsonformoderncpp/3.6.1@vthiery/stable: Already installed!
sfml/2.5.1@bincrafters/stable: WARN: Build folder is dirty, removing it: /home/milerius/.conan/data/sfml/2.5.1/bincrafters/stable/build/b6ed6852348b865abb04a1f44074bcd81d14d521
ERROR: Error while trying to get recipe sources for sfml/2.5.1@bincrafters/stable. No remote defined
```

### Logs (Include/Attach if Applicable)
{"_action": "COMMAND", "name": "install", "parameters": {"build": ["sfml"], "channel": null, "env": null, "generators": null, "install_folder": null, "manifests": null, "manifests_interactive": null, "name": null, "no_imports": false, "options": null, "path": "../", "profile_names": ["clang"], "remote_name": null, "settings": null, "update": false, "user": null, "verify": null, "version": null}, "time": 1554998343.5262256}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "sfml/2.5.1@bincrafters/stable", "time": 1554998343.5432796}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "entt/3.x.y-WIP@skypjack/stable", "time": 1554998343.5463552}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "asio/1.13.0@bincrafters/stable", "time": 1554998343.5478854}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "jsonformoderncpp/3.6.1@vthiery/stable", "time": 1554998343.5495205}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "doctest/2.3.1@bincrafters/stable", "time": 1554998343.5509207}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "doom_strong_types/1.0.0@bintray/stable", "time": 1554998343.5524251}
{"_action": "GOT_PACKAGE_FROM_LOCAL_CACHE", "_id": "asio/1.13.0@bincrafters/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9", "time": 1554998343.5610456}
{"_action": "GOT_PACKAGE_FROM_LOCAL_CACHE", "_id": "doctest/2.3.1@bincrafters/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9", "time": 1554998343.5617392}
{"_action": "GOT_PACKAGE_FROM_LOCAL_CACHE", "_id": "doom_strong_types/1.0.0@bintray/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9", "time": 1554998343.562323}
{"_action": "GOT_PACKAGE_FROM_LOCAL_CACHE", "_id": "entt/3.x.y-WIP@skypjack/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9", "time": 1554998343.5629473}
{"_action": "GOT_PACKAGE_FROM_LOCAL_CACHE", "_id": "jsonformoderncpp/3.6.1@vthiery/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9", "time": 1554998343.5635707}
{"_action": "EXCEPTION", "class": "ConanException", "message": "Error while trying to get recipe sources for sfml/2.5.1@bincrafters/stable. No remote defined", "time": 1554998343.5657244}

**Comment by SSE4** [comment]
weird error. @danimtb any ideas?

**Comment by Milerius** [comment]
build --missing option seem's to work for me here.

**Comment by Croydon** [comment]
We don't have Clang 8 prebuilds for any package, but this error is another one

**Comment by danimtb** [comment]
Yes, this could happen if you rename or remove a remote where the recipe was downloaded from and then try to rebuild it from sources. As Conan stores the remote used in the registry, it could fail.

However, this was supposed to be fixed by https://github.com/conan-io/conan/pull/4568

Anyway, to solve the issue it would be a matter of removing SFML package from the cache and trying the install again

**Comment by SSE4** [comment]
@Milerius could you try to remove it from cache as @danimtb suggests?

**Comment by Milerius** [comment]
I will try today when i'm coming back to work

**Comment by SSE4** [comment]
@Milerius ping :)

**Comment by Milerius** [comment]
Works for me now

**Comment by SSE4** [comment]
confirmed as fixed, closing
