### ISSUE TITLE
[libelf] Download Broken - URL is no longer working

### ISSUE THREAD

**Issue by venabled** [bincrafters/community#731]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libelf/0.8.13**
  * Operating System+version: **Macos**
  * Compiler+version: **clang-8**
  * Conan version: **conan 1.13.0-dev**
  * Python version: **Python 3.7.0**

Looks like the URL pointed to by the libelf package is no longer valid, [this project](https://github.com/spack/spack/issues/10757) points to: 

https://fossies.org/linux/misc/old/libelf-0.8.13.tar.gz

**Comment by uilianries** [comment]
Hi @venabled !

Thanks for reporting this issue! I gonna provide a fix ASAP. Thanks!

**Comment by uilianries** [comment]
Hi @venabled !

I new package will be released soon. We need to wait for CI service (Travis and Appveyor).

Regards!

**Comment by venabled** [comment]
Awesome, thanks!
