### ISSUE TITLE
[bincrafters-conventions] Update Travis URL

### ISSUE THREAD

**Issue by uilianries** [bincrafters/community#732]
### Description of your feature

Since Bincrafters are using travis.com, many recipes contain travis.org on README file. The application Bincrafters Conventions could update the URL to use .com

**Comment by Croydon** [comment]
It's true that at Bincrafters we are completely migrated to travis-ci.com, but most others aren't right now

The question is: Do we add such an update right now for us and others need to undo it (like conan-community, when executed there) or do we wait until Travis is migrating anyone?

**Comment by uilianries** [comment]
We can put some filter for bincrafters and update again in the future
