### ISSUE TITLE
[glm] Include dirs not found when using cmake_paths generator

### ISSUE THREAD

**Issue by Ansoulom** [bincrafters/community#733]
### Package and Environment Details
  * Package Name/Version: **glm/0.9.9.4**
  * Operating System+version: **Windows 10**
  * Compiler+version: **Visual Studio-15**
  * Conan version: **conan 1.9.1**
  * Python version: **Python 3.7.1**

### Conan profile
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=15
build_type=Release
[options]
[build_requires]
[env]
```

### Description
When I link the glm library to my own target, the compiler doesn't find the correct include folder.
In short: `#include <glm/glm.hpp>` doesn't work as that file can't be found.
I'm using the cmake_paths generator. The relevant parts of my CMakeLists.txt file look like this:
```
cmake_minimum_required(VERSION 3.7)
project(glmtest)
include(${CMAKE_SOURCE_DIR}/build/conan_paths.cmake)
add_executable(glmtest src/main.cpp)
find_package(GLM REQUIRED)
target_link_libraries(glmtest PRIVATE glm)
```
The output says that the package is found and that it worked to link the library. It's just the includes that can't be found. It even produces these messages:
```
** GLM ALREADY FOUND BY CONAN!
** FOUND GLM INCLUDE:  C:/Users/Anton/.conan/data/glm/0.9.9.4/g-truc/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include
```
This is the message I get when trying to compile:
`fatal error C1083: Cannot open include file: 'glm/glm.hpp': No such file or directory`

These are the commands I run:
```
conan install .. -s build_type=Debug --build missing
cmake .. -G "Visual Studio 15 2017 Win64"
cmake --build . --config Debug
```

I can note that GLFW, which is linked to the same target, works.

**Comment by Croydon** [comment]
Did you had a look into the `.conan/data/glm/0.9.9.4/g-truc/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include` directory to see if the files exist?

**Comment by Ansoulom** [comment]
Yes, the files exist.
I realize now what the problem is. The `FindGLM.cmake` script doesn't actually define a target to link against. I thought that `target_link_libraries(glmtest PRIVATE glm` worked because CMake didn't actually give me any error messages, even though the glm target apparently doesn't exist.
`target_include_directories(glmtest PRIVATE ${GLM_INCLUDE_DIR}` works though.

This makes me wonder though, why does this package even use a `FindGLM.cmake` script? It seems that the main glm repo exports a glm target and config files anyway, so there really shouldn't be a need for a `FindGLM.cmake` script at all. I even tried now to clone the glm repo and run `cmake --build . --target install` on it to install it on my system and it works flawlessly to use `target_link_libraries(glmtest PRIVATE glm)` when it's installed that way. I think that this Conan package should make use of that and just copy the CMake config files to the package instead of using a find-script.
