### ISSUE TITLE
[Qt / qt] Windows conan gets hung up on capitalization

### ISSUE THREAD

**Issue by cornytrace** [bincrafters/community#738]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.12.0@bincrafters/stable**
  * Operating System+version: **Windows 10 x64**
  * Compiler+version: **N/A**
  * Docker image: **N/A**
  * Conan version: **conan 1.14.3**
  * Python version: **Python 3.6.4**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=15
build_type=Release
[options]
[build_requires]
[env]

### Steps to reproduce (Include if Applicable)
require `qt/5.12.0@bincrafters/stable` in your conanfile.py
You will get this error:
`ERROR: Failed requirement 'qt/5.12.0@bincrafters/stable' from 'conanfile.py (openrw/master@None/None)'
ERROR: Requested 'qt/5.12.0@bincrafters/stable' but found case incompatible 'Qt'
Case insensitive filesystem can't manage this`
This is probably because there exists a deprecated Qt package, and the new qt package (note the capitalization). Windows errors out because it is looking first at Qt, and confuses it for an incorrect capitalization of qt.

**Comment by ericLemanissier** [comment]
The actual problem is that you have a `Qt` folder in your local cache. The solution (if  it can be done) is to remove this folder. This is basically this issue https://github.com/conan-io/conan/issues/1557

**Comment by Croydon** [comment]
Unfortunately, this is an annoyance in the transition but can't be worked around on Windows. As @ericLemanissier said if you don't rely on it anymore remove the upper case Qt (`conan remove Qt/*`)

To prevent such things in the future we have a policy that all new packages getting lower case names
