### ISSUE TITLE
giflib 5.1.3 FindGIF.cmake not working

### ISSUE THREAD

**Issue by joakimono** [bincrafters/community#74]
### package

giflib/5.1.3@bincrafters/stable

### Expected result

When consuming this package and using the included *FindGIF.cmake*,
the expected result is that the necessary gif-libraries will be linked to the target library/executable.

### Actual result

Linking to the gif-library fails with many *undefined references to '..'* symbols in linux. The find script does not find all the necessary libraries to link. It will link (e.g. static) only *libgetarg.a* and **not** *libgif.a*, which can be confirmed by inspecting the cmake-log. I have identified why and provide a solution below..

### Steps to reproduce

After following ordinary steps to install package and defining it in the projects *conanfile.txt*, and instead if leveraging variables defined by conan, I used the regular `find_package(GIF)`:

```cmake
cmake_minimum_required(VERSION 3.1.2)
project(GifProject CXX)
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()

find_package(GIF)
add_executable(ex code.cpp)
target_link_libraries(ex ${GIF_LIBRARIES})
target_include_directories(ex PRIVATE ${GIF_INCLUDE_DIRS})
```

### Extra information

* Conan version: **v1.0.2**
* Operating System: **Linux**
* Compiler+version: **gcc-5.4**

### Solution

Since giflib produces two libraries to be linked, some changes to the *FindGIF*-script are needed. `find_library` only finds a single library, where NAMES list candidate *names* to look for. `${CONAN_LIBS_GIFLIB}` is a list of libraries to be linked, so the proposed solution is (linux-verified: with shared: {True, False}):

```cmake
find_path(GIF_INCLUDE_DIR NAMES gif_lib.h PATHS ${CONAN_INCLUDE_DIRS_GIFLIB})

foreach(GIF_LIB ${CONAN_LIBS_GIFLIB})
  find_library(GIF_LIBRARY_${GIF_LIB} NAMES ${GIF_LIB} PATHS ${CONAN_LIB_DIRS_GIFLIB})
  if(NOT GIF_LIBRARY_${GIF_LIB}-NOTFOUND)
    list(APPEND GIF_LIBRARIES ${GIF_LIBRARY_${GIF_LIB}})
    mark_as_advanced(GIF_LIb_${GIF_LIB})
  endif()
endforeach()

SET(GIF_FOUND TRUE)
MESSAGE(STATUS " giflib found by conan!")
MESSAGE(STATUS ${GIF_LIBRARIES})
MESSAGE(STATUS ${GIF_INCLUDE_DIR})

set(GIF_INCLUDE_DIRS ${GIF_INCLUDE_DIR})

mark_as_advanced(GIF_INCLUDE_DIR)

set(GIF_VERSION 5)

```

**Comment by theirix** [comment]
Nice observation, thanks! I found the same issue today and fixed in commit https://github.com/bincrafters/conan-giflib/commit/90f393bb0b1ff22564bbcf878f230bb97635d475

Argument `NAMES` of the `find_library` call can only list synonyms of the library (such as `libgif`, `giflib`, `gif`, `gif.dll`) but it obviously cannot work with different libs. Iteration is needed. I think we need to fix it in other recipes. @solvingj , what do you think?

**Comment by solvingj** [comment]
Sorry, somehow have missed this ticket in my past few scans.  This does look like a project of it's own.  I think we need a few people who understand CMake well to try to think of a manageable or standardized/robust solution to `findXXX.cmake` files in various packages.

**Comment by SSE4** [comment]
@theirix @solvingj  I see FindGIF.cmake was removed from conan-giflib repository. seems to be standard CMake-provided module works well, right?
https://github.com/bincrafters/conan-giflib/commit/53731cbbfb135336ea028c98581d380995138725
if so, I believe ticket can be closed?

**Comment by theirix** [comment]
Yes, it works well with system finder. I'll open/reopen the issue if any problems will be found.
