### ISSUE TITLE
[SDL2] Inclusion of SDL2 net, rtf, and mixer modules?

### ISSUE THREAD

**Issue by Josh-Thompson** [bincrafters/community#740]
Hello,

Currently Bincrafters has Conan recipes for the main SDL2 project, as well as for its SDL2_image and SDL2_ttf modules. There are three remaining official SDL2 modules: net, rtf, and mixer. I would love to see recipes for these created as well, so that the entire SDL2 official library is supported by Bincrafters. I don't know a great deal about creating conan recipes but I would be willing to help in the capacity that I can if others are interested in taking on this project.

Thanks!

**Comment by Croydon** [comment]
Hi there!

sdl2_mixer is work in progress: https://github.com/bincrafters/conan-sdl2_mixer

Pull requests are always welcome!

In the case of sdl2_mixer I believe we are still missing some dependencies which we need to create first. @SSE4 know more about that 

For sdl2_net and sdl2_rtf I would recommend to create atomic issue on the wishlist: https://github.com/conan-io/wishlist/issues

**Comment by Josh-Thompson** [comment]
Alright, will do! Thanks :)

**Comment by Croydon** [comment]
mixer issue: https://github.com/conan-io/wishlist/issues/71
