### ISSUE TITLE
Qt compilation on windows

### ISSUE THREAD

**Issue by CallMarl** [bincrafters/community#741]
### Package and Environment Details (include every applicable attribute)
```
Conan version 1.11.1
```
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc

compiler.libcxx=libstdc++11
compiler.version=8.1
[options]
[build_requires]
[env]
```

### Conanfile.txt  
```
[requires]
qt/5.12.2@bincrafters/stable
OpenSSL/1.1.1a@conan/stable
mysql-connector-c/6.1.11@bincrafters/stable

[options]
qt:qtwebview=True
qt:qtwebengine=True
qt:qttools=True

[generators]
cmake

[imports]
lib, *.dylib* -> ./bin
```

### Question Description

Bellow the error message I have. I'm trying to compilate, QT librairie on windows, with MinGW, libjpeg is needed by but I can't install. I know that the $PATH environment var is from the WSL distribution. But in other topic I read [#418](https://github.com/bincrafters/community/issues/418) that WSL is needed by libjpeg because during the compilation some tools like sed, awk... are needed. 

```
libjpeg/9c@bincrafters/stable: configure: error: no acceptable C compiler found in $PATH
libjpeg/9c@bincrafters/stable: See `config.log' for more details
```

### End part of my windows PATH variable:

```
/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files/Conan/conan:/mnt/c/Users/CallMarl/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/CallMarl/AppData/Local/atom/bin:/mnt/c/Users/CallMarl/AppData/Local/hyper/app-2.1.2/resources/bin:/mnt/c/Users/CallMarl/AppData/Local/vcpkg:/mnt/c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin:/mnt/c/Program Files/CMake/bin
```

### More error detail :

```
ERROR: libjpeg/9c@bincrafters/stable: Error in build() method, line 86
        self._build_configure()
while calling '_build_configure', line 78
        env_build.configure(configure_dir=self._source_subfolder, args=config_args)
        ConanException: Error 1 while executing /mnt/c/Users/CallMarl/.conan/data/libjpeg/9c/bincrafters/stable/build/eb34f13b437ddfd63abb1f884c4b8886c48b74cd/source_subfolder/configure --enable-sha
red=no --enable-static=yes --prefix=/mnt/c/Users/CallMarl/.conan/data/libjpeg/9c/bincrafters/stable/package/eb34f13b437ddfd63abb1f884c4b8886c48b74cd --build=x86_64-w64-mingw32 --host=x86_64-w64-ming
w32
```

Please, what is the best way to fix it?
Thank you.

**Comment by ericLemanissier** [comment]
QWebEngine is compatibe only with msvc on windows.
Regarding jpeg, it is an optional part of the recipe, so you can use qt:with_libjpeg=False option to disable it.
Regarding wsl, it is a native linux system, so if you compile from wsl shell, it will create linix binaries (except if you cross-compile to windows, but it is provably not the simplest solution). You probably want to use msys instead.

**Comment by CallMarl** [comment]
Thank you a lot for your answer.
I spend time to take look of MCVS. So now I update my profile and it looks like: 

```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio

compiler.version=15
build_type=Release
[options]
[build_requires]
[env]
```

To install the MCSV compilation tool I use the choco package manager and this package: [vcredist140](https://chocolatey.org/packages/vcredist140)

I spent a lot of time finding the compiler path to include it in PATH var. The path looks like: 

```
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64
```

All these packages work with:

```
OpenSSL/1.1.1a@conan/stable
bzip2/1.0.6@conan/stable
double-conversion/3.1.1@bincrafters/stable
freetype/2.9.0@bincrafters/stable
harfbuzz/2.3.0@bincrafters/stable
libjpeg/9c@bincrafters/stable
libpng/1.6.34@bincrafters/stable
mysql-connector-c/6.1.11@bincrafters/stable
odbc/2.3.7@bincrafters/stable
pcre2/10.32@bincrafters/stable
qt/5.12.2@bincrafters/stable
sqlite3/3.26.0@bincrafters/stable
zlib/1.2.11@conan/stable
```
