### ISSUE TITLE
gTest - Please, add Windows MinGW gcc 7.0 binary

### ISSUE THREAD

**Issue by SebastianMosiej** [bincrafters/community#743]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **gtest/1.8.1@bincrafters/stable**
  * Operating System+version: **Windows 10 64b**
  * Compiler+version: **gcc-7.0**
  * Docker image: **conanio/gcc7**
  * Conan version: **Conan 1.11.0**
  * Python version: **Python 3.7.0**

### Description of your feature
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=gcc
compiler.version=7
compiler.exception=seh
compiler.threads=posix
compiler.libcxx=libstdc++11
[options]
gtest:shared=True
[build_requires]
[env]
CC=c:\Qt\Tools\mingw730_64\bin\gcc.exe
CXX=c:\Qt\Tools\mingw730_64\bin\g++.exe
PATH=[c:\Qt\Tools\mingw730_64\bin]

**Comment by SSE4** [comment]
added, thanks: https://github.com/bincrafters/conan-gtest/commit/1533f772f1f2b2ac9be28287445554785a5e9ad4

**Comment by SebastianMosiej** [comment]
Thank you. It's already available.
