### ISSUE TITLE
Inclusion Request: SPIRV-Headers

### ISSUE THREAD

**Issue by mmha** [bincrafters/community#744]
### Package Details
  * Package Name: **spirv-headers**
  * Operating Systems+versions: **Any (Header Only)**
  * Compiler support: **gcc-5.4, gcc6, clang7, MSVC**
  * Conan recipe repository: **https://github.com/mmha/conan-spirv-headers**

### Inclusion request
  * Fill all checkboxes with x if you agree with the statement or if it applies to your Conan recipe
  * [x] I want that my Conan recipe is getting included into the Bincrafters organisation
  * [x] I understand that if my request is accepted we are cloning your repository with all its history into Bincrafters, adapt some configurations and meta data if needed, and publishing it under the Bincrafters name and accounts
  * [x] I have used the Bincrafters templates to develop my Conan recipe - https://github.com/bincrafters/conan-templates
  * [x] My Conan recipe and all parts of it are licensed under the MIT license - https://choosealicense.com/licenses/mit/
    * Bincrafters are releasing all recipes under MIT license. If you want to have your recipe within Bincrafters we kindly ask you to do the same
    * it is okay if your test_package contains code from the upstream project under the upstream project's license, as long as it is clearly mentioned within the test_package files
  * [x] My Conan recipe covers (at least) the latest stable version which is available for the package
  * [x] I know that my Conan recipe is working on all operating system and compilers mentioned above right now
    * [Travis](https://travis-ci.com/mmha/conan-spirv-headers)
  * [x] I'm willing to help to maintain the recipe even after it is included into Bincrafters

### Notes
* This is part of the work towards resolving conan-io/wishlist#206

### Checklist for the Bincrafters team
  * Ignore this if you are not part of the Bincrafters team
  * [x] There is no such Conan package yet in conan-center, conan-community or Bincrafters
  * [x] The project is either popular or deserves to be maintained for another good reason (we can't package every single project out there)
  * [x] [bincrafters-conventions](https://github.com/bincrafters/bincrafters-conventions) reports no complains; the recipe fulfills our general quality requirements and conventions
  * [x] The recipe is cloned into our organisation; CI is enabled and configurated and succeeds
  * [x] There is a branch protection rule for `stable/*` branches, which requires a pull request with at least one approval first before things can get published
  * Considering granding the inclusion request author push rights to the recipe repository (there is no guarantee that everyone is getting push rights, we decide this on a case-to-case base)

**Comment by Croydon** [comment]
The recipe is now live at https://github.com/bincrafters/conan-spirv-headers

Please note for further submissions:
  * You didn't choose the right templates. Since this is a header_only recipe you should have used the `header_only` templates, instead you used the `default` ones
  * in the readme you need to manually replace `package_name` with the actual name

Thanks!
