### ISSUE TITLE
Inclusion Request: opencl-icd-loader

### ISSUE THREAD

**Issue by mmha** [bincrafters/community#748]
### Package Details
  * Package Name: **opencl-icd-loader**
  * Operating Systems+versions: **Linux Ubuntu 16.04, Ubuntu 18.04, Windows, macOS**
  * Compiler support: **gcc-5.4, gcc6, clang7, MSVC**
  * Conan recipe repository: **https://github.com/mmha/conan-opencl-icd-loader**

### Inclusion request
  * Fill all checkboxes with x if you agree with the statement or if it applies to your Conan recipe
  * [x] I want that my Conan recipe is getting included into the Bincrafters organisation
  * [x] I understand that if my request is accepted we are cloning your repository with all its history into Bincrafters, adapt some configurations and meta data if needed, and publishing it under the Bincrafters name and accounts
  * [x] I have used the Bincrafters templates to develop my Conan recipe - https://github.com/bincrafters/conan-templates
  * [x] My Conan recipe and all parts of it are licensed under the MIT license - https://choosealicense.com/licenses/mit/
    * Bincrafters are releasing all recipes under MIT license. If you want to have your recipe within Bincrafters we kindly ask you to do the same
    * it is okay if your test_package contains code from the upstream project under the upstream project's license, as long as it is clearly mentioned within the test_package files
  * [x] My Conan recipe covers (at least) the latest stable version which is available for the package
  * [ ] I know that my Conan recipe is working on all operating system and compilers mentioned above right now
    * The CI scripts expect `opencl-headers/bincrafters`, this is why it currently fails on GitHub.
    * I am going to create a branch with another remote added with the package being available there to prove that the package works as intended.
  * [x] I'm willing to help to maintain the recipe even after it is included into Bincrafters

### Notes
* This is the Khronos ICD Loader. There is a second implementation called [ocl-icd](https://github.com/OCL-dev/ocl-icd) that is far more popular among Linux distributions.
    * Should I change the name of the package to `khronos-ocl-icd` (like on Arch Linux) or similar to avoid confusion?
* The ICD Loader depends on `opencl-headers` (See #747)

### Checklist for the Bincrafters team
  * Ignore this if you are not part of the Bincrafters team
  * [x] There is no such Conan package yet in conan-center, conan-community or Bincrafters
  * [x] The project is either popular or deserves to be maintained for another good reason (we can't package every single project out there)
  * [ ] [bincrafters-conventions](https://github.com/bincrafters/bincrafters-conventions) reports no complains; the recipe fulfills our general quality requirements and conventions
  * [ ] The recipe is cloned into our organisation; CI is enabled and configurated and succeeds
  * [ ] There is a branch protection rule for `stable/*` branches, which requires a pull request with at least one approval first before things can get published
  * Considering granding the inclusion request author push rights to the recipe repository (there is no guarantee that everyone is getting push rights, we decide this on a case-to-case base)

**Comment by mmha** [comment]
Okay so I just learned that in contrary to the OpenCL spec, the ICD loader's `clGetPlatformIDs`  returns an error code if no implementation is found, regardless of whether the `platforms` argument is `nullptr` or not.

I ignore the return value in my test package now, Travis should run through this time.

**Comment by Croydon** [comment]
> Should I change the name of the package to khronos-ocl-icd (like on Arch Linux) or similar to avoid confusion?

This sounds reasonable to me. Ambiguous names are a problem

**Comment by uilianries** [comment]
Excellent point!

Yes, I think we should rename it, but I would prefer **khronos-opencl-icd-loader**

**Comment by uilianries** [comment]
Also, the same should be applied for opencl-headers

**Comment by uilianries** [comment]
Done:

https://github.com/bincrafters/conan-khronos-opencl-icd-loader
https://bintray.com/bincrafters/public-conan/khronos-opencl-icd-loader%3Abincrafters
