### ISSUE TITLE
conan-package-tools - Be aware of new builder.items structure

### ISSUE THREAD

**Issue by solvingj** [bincrafters/community#75]
I don't actually no if we ever call builder.builds in bincrafters-package-tools right now, but we should look, and i wanted to make others aware of this.  I know there are scattered manipulations of `builder.builds` in the `build.py` for various other packages, so we'll need to update those as we find them. 

I just stumbled across this snippet in conan-package-tools:

https://github.com/conan-io/conan-package-tools/blob/develop/conan/packager.py#L309

```
    @property
    def builds(self):
        # Retrocompatibility iterating
        logger.warn("\n\n\n******** ITERATING THE CONAN_PACKAGE_TOOLS BUILDS WITH "
                    ".builds is deprecated use .items() instead (unpack 5 elements: "
                    "settings, options, env_vars, build_requires, reference  **********\n\n\n")
```

Also, the other day in chat, @memsharded mentioned that the `reference` was already available as a variable so we probably don't need to manually parse the `conanfile.py` anymore. I guess this is related, so we should look here to eliminate our parsing code.

**Comment by theirix** [comment]
Oh, this changes once again…

**Comment by solvingj** [comment]
Note that it's deprecated, but the old signature should still work for some time.

**Comment by theirix** [comment]
Searched the organization:
https://github.com/search?l=Python&q=org%3Abincrafters+%22builder.builds%22&type=Code&utf8=%E2%9C%93

1. Just updated or not affected: libjpeg, libjpeg-turbo, machina.io, opus, libcurl, libxml2

2. Not updated: caf (too complex), azure-umqtt-c, cpprestsdk

**Comment by theirix** [comment]
3. Pending: libevent via #73
