### ISSUE TITLE
[libjpeg] Error with Visual Studio x86

### ISSUE THREAD

**Issue by nkshigeru** [bincrafters/community#754]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libjpeg/9c**
  * Operating System+version: **Windows 10 1803**
  * Compiler+version: **Visual Studio 15 2017**
  * Conan version: **conan 1.14.1**
  * Python version: **Python 3.7.3**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=15
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
conanfile.txt:
```
[requires]
libjpeg/9c@bincrafters/stable

[generators]
cmake
```
CMakeLists.txt:
```
cmake_minimum_required(VERSION 2.8.12)
project(test_libjpeg)

include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()

add_executable(test_libjpeg test_libjpeg.cpp)
target_link_libraries(test_libjpeg ${CONAN_LIBS})
```
test_libjpeg.cpp:
```
#include <iostream>
#include <jpeglib.h>

void error_exit_handler(j_common_ptr cinfo)
{
	char buffer[JMSG_LENGTH_MAX];
	(*cinfo->err->format_message)(cinfo, buffer); // <<-- Crash Here!
	std::cout << buffer << std::endl;
}

int main()
{
	struct jpeg_decompress_struct cinfo;
	struct jpeg_error_mgr jerr;
	cinfo.err = jpeg_std_error(&jerr);
	jerr.error_exit = &error_exit_handler;
	jpeg_create_decompress(&cinfo); // <<-- Error. go error_exit_handler. 
	return 0;
}
```
command:
```
conan install ../ -g cmake_multi -s arch=x86 -s build_type=Release
conan install ../ -g cmake_multi -s arch=x86 -s build_type=Debug
cmake -G "Visual Studio 15 2017" ../
```

### Logs (Include/Attach if Applicable)

Run test_libjpeg.exe in debugger, it fails on `(*cinfo->err->format_message)(cinfo, buffer);` 
output:
> Exception thrown at 0x770CBAC4 (ucrtbase.dll) in test_libjpeg.exe: 0xC0000005: Access violation reading location 0xFFFFFFFF.

This is not libjpeg message. `format_message` fails itself.

This problem only occurs when using x86 pre-built library.
No problem with x86_64 pre-built library.
In addition, when I clone bincrafters/conan-libjpeg and build by `conan create`, this problem does not occur.

**Comment by nkshigeru** [comment]
Looking at AppVeyor log,
https://ci.appveyor.com/project/BinCrafters/conan-libjpeg/build/job/bpqex8jeyokk5cu8?fullLog=true#L284

it seems that the 64bit flags `-D_AMD64_=1 -DWIN64 -D_WIN64` are enabled even on x86 build.

**Comment by uilianries** [comment]
Hi @nkshigeru !

Thanks for reporting this issue. A new fix is available here:

https://github.com/bincrafters/conan-libjpeg/pull/9

It will be merged soon.

Regards!

**Comment by uilianries** [comment]
Hi @nkshigeru !

Please, update your package, a new version is available for download.

**Comment by nkshigeru** [comment]
@uilianries Thanks!
It's working as expected.
