### ISSUE TITLE
[libiconv] Invalid configuration: This recipe needs a Windows Subsystem to be compiled.

### ISSUE THREAD

**Issue by acdemiralp** [bincrafters/community#755]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: libiconv/1.15
  * Operating System+version: Windows 10
  * Compiler+version: Visual Studio 2019 (msvc142)
  * Docker image: Unknown
  * Conan version: 1.14.4
  * Python version: Python 2.7

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
build_type=Release
[options]
[build_requires]
[env]

### Steps to reproduce (Include if Applicable)
Require "ffmpeg/4.1@bincrafters/stable" which indirectly requires "libiconv/1.15@bincrafters/stable", run.

### Logs (Include/Attach if Applicable)
ERROR: libiconv/1.15@bincrafters/stable: Invalid configuration: This recipe needs a Windows Subsystem to be compiled. You can specify a build_require to: 'msys2_installer/latest@bincrafters/stable' or 'cygwin_installer/2.9.0@bincrafters/stable' or put in the PATH your own installation

CMake Error at cmake/conan.cmake:387 (message):
  Conan install failed='6'

**Comment by Croydon** [comment]
This is the expected behaviour https://github.com/bincrafters/conan-libiconv/blame/ca0738cd79af07d4f72a3d74e561d7b3beea4ca4/conanfile.py#L119

AFAIK neither cygwin nor mysys2 are included automatically, because they are kinda big and people may prefer to use system installations for those.

The error messages suggest to put either mysys2 or cygwin directly to your build_requires. Is this working for you?

**Comment by acdemiralp** [comment]
The problem is I have msys2 installed locally and have it in my path (running msys2 on cmd launches an msys2 console) yet it complains. I have not tried the conan msys2 as you stated, and will try it and update now.

**Comment by acdemiralp** [comment]
I have added the build_requires to my conanfile.py, yet nothing changed. Perhaps its because its a chain dependency? I require FFMPEG, which in turn requires libiconv, which in turn requires msys2 or cygwin?
```
from   conans       import ConanFile, CMake, tools
from   conans.tools import download, unzip
import os

class Project(ConanFile):
    name            = "mt"
    description     = "Conan package for the malware toolkit."
    version         = "1.2.0"                
    url             = "https://github.com/acdemiralp/mt"
    settings        = "arch", "build_type", "compiler", "os"
    generators      = "cmake"
    build_requires  = "msys2_installer/latest@bincrafters/stable"
    requires        = (("acd/1.1.0@acdemiralp/makina"          ),
                       ("boost/1.69.0@conan/stable"            ),
                       ("catch2/2.2.0@bincrafters/stable"      ),
                       ("ffmpeg/4.1@bincrafters/stable"        ),
                       ("jsonformoderncpp/3.1.1@vthiery/stable"),
                       ("OpenSSL/1.1.1b@conan/stable"          ),
                       ("spdlog/1.3.1@bincrafters/stable"      ),
                       ("stb/20180214@conan/stable"            ),
                       ("websocketpp/0.8.1@bincrafters/stable" ),
                       ("zlib/1.2.8@conan/stable"              )) 
    options         = {"shared": [True, False]} 
    default_options = "shared=True"

    def configure(self):
        self.options["websocketpp"].asio         = "standalone"
        self.options["boost"      ].without_test = True

    def imports(self):
        self.copy("*.dylib*", dst="", src="lib")
        self.copy("*.dll"   , dst="", src="bin")

    def source(self):
        zip_name = "%s.zip" % self.version
        download ("%s/archive/%s" % (self.url, zip_name), zip_name, verify=False)
        unzip    (zip_name)
        os.unlink(zip_name)

    def build(self):
        cmake          = CMake(self)
        shared_options = "-DBUILD_SHARED_LIBS=ON" if self.options.shared else "-DBUILD_SHARED_LIBS=OFF"
        self.run("cmake %s-%s %s %s" % (self.name, self.version, cmake.command_line, shared_options))
        self.run("cmake --build . %s" % cmake.build_config)

    def package(self):
        include_folder = "%s-%s/include" % (self.name, self.version)
        self.copy("*.h"     , dst="include", src=include_folder)
        self.copy("*.hpp"   , dst="include", src=include_folder)
        self.copy("*.inl"   , dst="include", src=include_folder)
        self.copy("*.dylib*", dst="lib"    , keep_path=False   )
        self.copy("*.lib"   , dst="lib"    , keep_path=False   )
        self.copy("*.so*"   , dst="lib"    , keep_path=False   )
        self.copy("*.dll"   , dst="bin"    , keep_path=False   )

    def package_info(self):
        self.cpp_info.libs = [self.name]
        if self.settings.os == "Windows":
            if not self.options.shared:
                self.cpp_info.defines.append("%s_STATIC" % self.name.upper())

```

**Comment by SSE4** [comment]
@acdemiralp you need to do one of the following:
1. add either `msys2_installer/latest@bincrafters/stable` or `cygwin_installer/1.9.2@bincrafters/stable` to the `[build_requires]` section of your default conan profile (`%USERPROFILE%\.conan\profiles\default`)
2. if you have an existing MSYS2/Cygwin installation, define `CONAN_BASH_PATH` environment variable in the `[env]` section of your default conan profile (`%USERPROFILE%\.conan\profiles\default`), something like that:
```
[env]
CONAN_BASH_PATH=C:\msys64\usr\bin\bash.exe
```
(alternatively, you may just set `CONAN_BASH_PATH` in the shell or globally in system settings)

**Comment by acdemiralp** [comment]
That in fact solved it, thank you SSE4! Since it is due to lack of my knowledge of build_requires, I'm closing this issue.
