### ISSUE TITLE
[ffmpeg] ConanException: Error 2 while executing make -j12 on Windows 10.

### ISSUE THREAD

**Issue by acdemiralp** [bincrafters/community#756]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: ffmpeg/4.1
  * Operating System+version: Windows 10
  * Compiler+version: MSVC 2019 (v142)
  * Docker image: Unknown
  * Conan version: 1.14.4
  * Python version: Python 2.7

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
build_type=Release
[options]
[build_requires]
[env]

### Steps to reproduce (Include if Applicable)
Require ffmpeg/4.1@bincrafters/stable on Windows, set the following (because these optional dependencies also fail on Windows 10 / MSVC 2019):
 self.options["ffmpeg"     ].iconv        = False
 self.options["ffmpeg"     ].openh264     = False
 self.options["ffmpeg"     ].vpx          = False

### Logs (Include/Attach if Applicable)
ffmpeg/4.1@bincrafters/stable: ERROR: Package '927a87f1bd586467e658f074b754b3837630161c' build failed
ffmpeg/4.1@bincrafters/stable: WARN: Build folder D:\root\prebuilt\conan_storage\ffmpeg\4.1\bincrafters\stable\build\927a87f1bd586467e658f074b754b3837630161c
ERROR: ffmpeg/4.1@bincrafters/stable: Error in build() method, line 234
	self.build_configure()
while calling 'build_configure', line 363
	env_build.make()
	ConanException: Error 2 while executing make -j12

CMake Error at cmake/conan.cmake:387 (message):
  Conan install failed='1'

**Comment by SSE4** [comment]
hi @acdemiralp  unfortunately build log seems to be too short to say anything
is there anything in output above this line?
```
ffmpeg/4.1@bincrafters/stable: ERROR: Package '927a87f1bd586467e658f074b754b3837630161c' build failed
```

**Comment by acdemiralp** [comment]
The problem was not having msys2 and yasm in the default conan profile. Adding them fixed it. The new profile looks like:
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
build_type=Release
[options]
[build_requires]
msys2_installer/latest@bincrafters/stable
yasm_installer/1.3.0@bincrafters/stable
[env]
```

**Comment by uilianries** [comment]
I know this issue is already closed, but 12 jobs ?! Incredible, I would say!
