### ISSUE TITLE
[bincrafters-conventions] Check for conan model Version

### ISSUE THREAD

**Issue by uilianries** [bincrafters/community#757]
### Description of your feature

Conan will provide a Version helper on 1.15, which means we should move `from conans.model.version import Version` to `from conan.tools import Version`

https://github.com/conan-io/conan/pull/4963

**Comment by SSE4** [comment]
seems like it's too early to do it now, as even 1.15 isn't released yet

**Comment by uilianries** [comment]
Yes, thanks for updating its status.

**Comment by Croydon** [comment]
Do the parameters and/or return values differ or ca we automatically replace the import?

**Comment by uilianries** [comment]
Just replace the import. Otherwise, Conan will display a warning message.
