### ISSUE TITLE
Upstream Update: imgui 1.69

### ISSUE THREAD

**Issue by prsolucoes** [bincrafters/community#758]
### Package Details
  * Package Name: **imgui**
  * Latest available Version: **1.69**

The above mentioned version is newly released by the upstream project and not yet available within Bincrafters. Please add this version.

**Comment by SSE4** [comment]
pushed, thanks for the update https://github.com/bincrafters/conan-imgui/commits/testing/1.69

**Comment by Croydon** [comment]
The version is now available
