### ISSUE TITLE
[sdl2] Settings not compatible with all platforms

### ISSUE THREAD

**Issue by neobrain** [bincrafters/community#759]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **sdl2/2.0.9**
  * Operating System+version: **openSUSE Tumbleweed** / **Android**
  * Conan version: **Conan 1.14.1**
  * Python version: **Python 3.7.2**

### Question Description

I use SDL2 with the setting `sdl2:nas=False` since sdl2:nas requires dependencies that openSUSE does not provide. Since my project doesn't rely on this feature, I'd like to disable it in my project's conanfile.txt to make things work out of the box on all platforms.

However, doing so breaks this conanfile.txt on Android (and presumably others), since the option `sdl:nas` option is not recognized on that platform.

Currently, it looks like I need to either maintain package-specific configuration in my Conan profile or move towards using a python-based conanfile (where I can have OS-specific settings).

Instead of rejecting platform-specific options, could the conan-sdl2 recipe simply ignore these options?

**Comment by SSE4** [comment]
as an alternate thing, you may specify `*:nas=False` which don't fail if there is no such an option in package

**Comment by neobrain** [comment]
That's a nice workaround. I'll adopt this for my project. (Specifically, I'm using the somewhat more specific`sdl2*:nas=False`.) Thanks!

It still seems off to me to have the options inconsistent between different platforms. I see that it's weird to have options that don't do anything, but to me that seems like the lesser evil compared to having conanfiles being portable only via workarounds. Am I missing any other drawbacks to e.g. ignoring `sdl2:nas` on Windows?

**Comment by SSE4** [comment]
I personally don't like to expose options which doesn't have an any effect, as it would be confusing for users. it also will produce 2 set of packages for Windows, which will be absolutely identical, actually. of course, we may remove option from package_id for Windows only, but our current strategy is to expose options which actually have an effect.
as there are workarounds (1 - use different conanfile per platform 2 - use conditional conanfile.py 3 - use wildcard syntax for option), I believe there is nothing to be done.
