### ISSUE TITLE
MinGW build on templates might need to be split up

### ISSUE THREAD

**Issue by solvingj** [bincrafters/community#76]
`add_common_builds()` from conan package tools generates 24 mingw builds from the MinGW line of our `appveyor.yml` template.  I didn't realize this until now, but it's probably better to split that up over 2 jobs (possibly even 4).  Here's an example of one that seemed to take a while. 

https://ci.appveyor.com/project/BinCrafters/conan-lzma

Also, I'd like to hear from someone who will actually use the MinGW builds to ask if the collection of builds we're doing on MinGW make sense.

**Comment by theirix** [comment]
Exactly! Only three mingw configurations for libcurl took an hour to build.

**Comment by solvingj** [comment]
Right.  We definitely need to think it through more before we add it to any more recipes.  

Here's the list of current MinGW builds for the record, again, really would like someone who uses MinGW to comment on the relevance of this selection.  It seems a bit arbitrary to me, but I don't know enough about it. 

```
4.9@x86_64@seh@posix, 
4.9@x86_64@sjlj@posix, 
4.9@x86@sjlj@posix, 
4.9@x86@dwarf2@posix, 

6.3@x86_64@seh@posix, 
7.1@x86_64@seh@posix
```

**Comment by sigmoidal** [comment]
imho it is too resource-intensive to test many mingw compilers with all options. 

Maybe you'll find the following a good read (see also the comments and linked content):
https://stackoverflow.com/questions/29947302/meaning-of-options-in-mingw-w64-installer/30178674

I would consider building packages for 1 or 2 of the most recent and popular compilers only (6.x/7.x) with the posix threading and SEH exception model and only build x86_64. 

I think the other combinations could potentially be built by end-users if required locally. I don't have a picture of how many users are there for each of these, but I would expect people would prefer code generated by most recent compilers and probably try to go for 64-bit. 

no expert here, so just my uninformed amateur opinion here.

**Comment by solvingj** [comment]
Great feedback!!  I wonder if there's any indicator in C++ projects on Github when MinGW is used.  Maybe it would allow us to do a search.  It's a long-shot, but an idea.

**Comment by solvingj** [comment]
After discussing in bincrafters slack, we're disabling mingw builds for now since they are so difficult, and will re-evaluate when we have more data.  keeping open issue #80 for that purpose.
