### ISSUE TITLE
[protobuf] PDB files are not packaged

### ISSUE THREAD

**Issue by ltjax** [bincrafters/community#760]
Analogous to issue #387, but for protobuf - linker will generate the warning LNK4099.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **protobuf/3.5.2**
  * Operating System+version: **Windows 10**
  * Compiler+version: **Visual Studio 2019**
  * Conan version: **conan 1.14.3**
  * Python version: **Python 3.7.3**

### Conan profile 
[settings]
arch=x86
arch_build=x86_64
build_type=Debug
compiler=Visual Studio
compiler.runtime=MDd
compiler.version=15
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

**Comment by uilianries** [comment]
Hi @ltjax 

Usually we don't export PDB files, only when required by some user. I'll update the recipe.

**Comment by ltjax** [comment]
Hi Uilian!
Thank you!. What's the rationale for not including them? I guess I would be the kind of user that wants this for all the libs (and I was gonna make an issue for a few other libs I'm using) - but then again, maybe I'm just missing something?

**Comment by uilianries** [comment]
Yes, please read this issue to understand better: https://github.com/conan-io/conan/issues/4957

Also, few people request pdb files, which could increase the package size.
