### ISSUE TITLE
Upstream Update: libzip  1.5.2

### ISSUE THREAD

**Issue by qno** [bincrafters/community#762]
### Package Details
  * Package Name: **libzip**
  * Latest available Version: **1.5.2**

The above mentioned version is newly released by the upstream project and not yet available within Bincrafters. Please add this version.

**Comment by SSE4** [comment]
fails with weird error:
```
CMake Error at source_subfolder/CMakeLists.txt:207 (MESSAGE):
  -- ZLIB version too old, please install at least v1.1.2
```
https://travis-ci.com/bincrafters/conan-libzip/jobs/197657132

**Comment by uilianries** [comment]
It also requires libnettle

**Comment by uilianries** [comment]
okay, it's more complicated ...

libzip is in Conan Center, which means it's an official package. But, we need also nettle (Don Goodman-Wilson has a good scratch) and gmp (we have a recipe, but it's not official yet). 

I'll improve gmp and request Conan Center inclusion, and add nettle Recipe  for bincrafters.

**Comment by uilianries** [comment]
https://bintray.com/bincrafters/public-conan/gmp%3Abincrafters
https://bintray.com/bincrafters/public-conan/nettle%3Abincrafters

**Comment by qno** [comment]
Hi,

are there any news on this one?

**Comment by uilianries** [comment]
unfortunately not, we need both gmp and nettle in Conan Center. I'll ask to Conan team on next week for these inclusions.

**Comment by qno** [comment]
Great. Thank You!

**Comment by SSE4** [comment]
packages are available, closing
