### ISSUE TITLE
[OpenAL] option does not exist

### ISSUE THREAD

**Issue by oiltanker** [bincrafters/community#763]
### Package and Environment Details
  * Package Name/Version: `openal/1.18.2@bincrafters/stable`
  * Operating System+version: Windows 10 pro
  * Compiler+version: TDM GCC 5.1.0
  * Conan version: `Conan version 1.14.5`
  * Python version: `Python 3.7.3`

### Conan profile
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=5
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]
```
### Steps to reproduce
```
conan install "${CMAKE_SOURCE_DIR}" -b bzip2 -b flac -b freetype -b libpng  -b ogg -b openal -b vorbis -b zlib -b sfml
```

### Logs
Full log: [conan_cmake_sfml.log](https://github.com/bincrafters/community/files/3140183/conan_cmake_sfml.log)

```
> ERROR: openal/1.18.2@bincrafters/stable: Error in build() method, line 44
>  	cmake.definitions['CMAKE_POSITION_INDEPENDENT_CODE'] = self.options.fPIC
>  	ConanException: 'options.fPIC' doesn't exist
> Possible options are ['shared']
```

**Comment by oiltanker** [comment]
### Possible solution
#### replace line 43:
from: `if self.settings.compiler != 'Visual Studio':`
to: `if self.settings.os != "Windows":`

**Comment by oiltanker** [comment]
Yes, that is indeed the case.

**Comment by Croydon** [comment]
1.19.0 already had a fix for this. I back ported it to 1.18.2. Please re-test

**Comment by oiltanker** [comment]
Yes, it worked. It is not up to me to update. This version of package is required by [bincrafters/conan-sfml](https://github.com/bincrafters/conan-sfml).

**Comment by Croydon** [comment]
I pushed an update. Thanks for pointing out.
