### ISSUE TITLE
libpng - latest version don't need replace for arm

### ISSUE THREAD

**Issue by prsolucoes** [bincrafters/community#764]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **linbpng/1.6.36**
  * Operating System+version: **Linux Raspbian**
  * Compiler+version: **gcc-5.4**
  * Docker image: **conanio/gcc7**
  * Conan version: **conan 1.14.5**
  * Python version: **Python 2.7.10**

### Steps to reproduce (Include if Applicable)

Compile libpng to raspberry will throw error:

```
ERROR: libpng/1.6.36@bincrafters/stable: Error in build() method, line 67
	'PATHS /usr/lib /usr/local/lib /usr/arm-linux-gnueabihf/lib /usr/arm-linux-gnueabi/lib ')
	ConanException: replace_in_file didn't find pattern 'PATHS /usr/lib /usr/local/lib' in 'source_subfolder/CMakeListsOriginal.txt' file.
```

On earlier version we have this line:
https://github.com/winlibs/libpng/blob/master/CMakeLists.txt#L59

But on latest version we don't have more (replaced by find_library M_LIBRARY):
https://github.com/glennrp/libpng/blob/v1.6.37/CMakeLists.txt

So we don't need this replace:
https://github.com/bincrafters/conan-libpng/blob/stable/1.6.36/conanfile.py#L64

### Logs (Include/Attach if Applicable)

```
libpng/1.6.36@bincrafters/stable: Copying sources to build folder
libpng/1.6.36@bincrafters/stable: Building your package in /home/pi/.conan/data/libpng/1.6.36/bincrafters/stable/build/96c7f560a29094b34376d7f39b301b28f5024326
libpng/1.6.36@bincrafters/stable: Generator cmake created conanbuildinfo.cmake
libpng/1.6.36@bincrafters/stable: Calling build()
libpng/1.6.36@bincrafters/stable: 
libpng/1.6.36@bincrafters/stable: ERROR: Package '96c7f560a29094b34376d7f39b301b28f5024326' build failed
libpng/1.6.36@bincrafters/stable: WARN: Build folder /home/pi/.conan/data/libpng/1.6.36/bincrafters/stable/build/96c7f560a29094b34376d7f39b301b28f5024326
ERROR: libpng/1.6.36@bincrafters/stable: Error in build() method, line 67
	'PATHS /usr/lib /usr/local/lib /usr/arm-linux-gnueabihf/lib /usr/arm-linux-gnueabi/lib ')
	ConanException: replace_in_file didn't find pattern 'PATHS /usr/lib /usr/local/lib' in 'source_subfolder/CMakeListsOriginal.txt' file.
```

Can anyone fix it?

**Comment by SSE4** [comment]
pushed to testing: https://github.com/bincrafters/conan-libpng/commit/761a3687359cb5846b942a4b780140a656b6e133

**Comment by SSE4** [comment]
changes were applied
