### ISSUE TITLE
[SFML 2.5.1] Broken build with TGM GCC 5.1.0 on Windows

### ISSUE THREAD

**Issue by oiltanker** [bincrafters/community#767]
### Issue
```c++
sf::RenderWindow window(sf::VideoMode(200, 200), "SFML window");
```
Causes application to crash in `new_allocator.h`:
```c++
return static_cast<_Tp*>(::operator new(__n * sizeof(_Tp)));
      }

      // __p is not permitted to be a null pointer.
      void
      deallocate(pointer __p, size_type)
      { ::operator delete(__p); } <--- HERE
```

### Package and Environment Details
  * Package Name/Version: `sfml/2.5.1@bincrafters/stable`
  * Operating System+version: `Windows 10 Pro`
  * Compiler+version: `TDM GCC 5.1.0`
  * Conan version: `Conan version 1.14.5`
  * Python version: `Python 3.7.3`

### Conan profile
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=5
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce
Conanfile:
```
[requires]
sfml/2.5.1@bincrafters/stable

[options]
sfml:window=True
sfml:graphics=True
sfml:network=True
sfml:audio=True

[generators]
cmake
```
1. Conan install: `conan install /path/to/project --build=outdated`
2. CMake configure
3. CMake build

### Logs
[conan.log](https://github.com/bincrafters/community/files/3142609/conan.log)
[results.log](https://github.com/bincrafters/community/files/3142611/results.log)
[build.log](https://github.com/bincrafters/community/files/3142612/build.log)

**Comment by oiltanker** [comment]
I am unable to get to the root of the problem.
Steps I attempted:
* Added CMake definition: `cmake.definitions['SFML_USE_SYSTEM_DEPS'] = True`
* Completely hidden `extlibs` folder and commented lines 115 and 117

**Comment by oiltanker** [comment]
### Update
I was able to compile SFML by hand:
1. I deleted all libraries in `extlibs` except from `libs-mingw/x64`
2. Deleted all per-compiled libraries
3. Placed there all libraries compiled automatically by conan

### Issue
I was not able to make audio to work. It seems like `libOpenAL32.a` does not work properly, as it gives me `undefined reference to `__imp_al[...]'`.

**Comment by SSE4** [comment]
@oiltanker hello,
I am not familiar with TGM (or TDM?) GCC. is it something different from regular MinGW?
also, it would be nice if you could provide full logs of undefined references, as well as some details on how to set up the environment.

**Comment by oiltanker** [comment]
No it's MinGW-W64 but 5.1.0 with all new stuff and nicely packaged.

**Comment by oiltanker** [comment]
I think this is to do with the OpenAL library not properly compiling as well.

**Comment by oiltanker** [comment]
BTW, all default MinGW libraries provided within the source work fine for me, although I don't know what GCC version they are compiled in.

**Comment by oiltanker** [comment]
Nevermind, just don't use old gcc compilers.

I used **TGM GCC 5.1.0** because it was neatly packaged MinGW distribution, now I use new _(>5)_ MinGW ([compact Sourceforge installer](https://sourceforge.net/projects/mingw-w64/)).
