### ISSUE TITLE
[conan-doxygen_installer] Find_package (solution inside)

### ISSUE THREAD

**Issue by ManuelMeraz** [bincrafters/community#768]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **doxygen/1.18.15**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **clang 6.0**
  * Docker image: n/a
  * Conan version: **conan 1.14.4**
  * Python version: **Python 3.6.7**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)

```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=clang
compiler.version=6.0
compiler.libcxx=libstdc++11
build_type=Debug
[options]
enable_documentation=True
enable_tests=True
[build_requires]
[env]
CC=/usr/bin/clang-6.0
CXX=/usr/bin/clang++-6.0
```

This package provides `FindDoxygen.cmake` along with some a doxygen binary to use. There is a bug in `FindDoxygen.cmake` though. 

When doing:
```
find_package(Doxygen)
if(DOXYGEN_FOUND) 
#Do something here
endif()
```

The cmake variable `$DOXYGEN_EXECUTABLE` is supposed to generate a path directly to the doxygen executable (in this case the one provided for by the package on bintray), but it fails to do so.

Instead of generating the `/path/to/the/doxygen` it generates `/doxygen`, the reason being is because it uses 

```
set(DOXYGEN_EXECUTABLE "${CONAN_DOXYGEN_ROOT}/doxygen.exe" CACHE INTERNAL "")
```

`CONAN_DOXYGEN_ROOT` does not exist and is not generated by conan. Why? Conan generates the name of the package. After changing this to:

```
set(DOXYGEN_EXECUTABLE "${CONAN_DOXYGEN_INSTALLER_ROOT}/doxygen.exe" CACHE INTERNAL "")
```

I get the correct behavior. The environment variable is generated by `conanbuildinfo.cmake`. I wasn't sure how to contribute this because this is not reflected in the github repository (the exports, which are missing this)

If you look at the [prebuilt packages](https://bintray.com/bincrafters/public-conan/doxygen_installer%3Abincrafters#files

/bincrafters%2Fdoxygen_installer%2F1.8.15%2Fstable%2F0%2Fpackage%2F456f15897172eef340fcbac8a70811f2beb26a93%2F0), click on any of them and open a `conan_package.tgz` you will see in the `FindDoxygen.cmake` files what I am speaking about on line 76.

Maybe the `test_package` directory in the github repo could include a basic CMakeLists.txt with a `find_package` working correctly. At the moment it simply runs doxygen from inside the conan file.

**Comment by SSE4** [comment]
@ManuelMeraz thanks for the reporting, I'll try to add your use-case to the test_package and fix it

**Comment by SSE4** [comment]
@ManuelMeraz applied: https://github.com/bincrafters/conan-doxygen_installer/commit/2ccb0d762a256113323c2ebb97c33a63214a8b0a
please give an another try and lemme know

**Comment by SSE4** [comment]
I am closing, as changes were applied.
