### ISSUE TITLE
can conan-libmpg123 be updated to use Windows SDK 10 instead of 8.1?

### ISSUE THREAD

**Issue by JimmySnails** [bincrafters/community#769]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: libmpg123/1.25.10
  * Operating System+version: Windows 10
  * Compiler+version: Visual Studio 2019
  * Docker image: none ?
  * Conan version: Conan 1.14.4
  * Python version: Python 3.7.3

### Question Description

I've tried to build SDL2_mixer, which requires libmpg123, but it fails because it requires Windows 8.1 SDK.

Could you make it use the Windows 10 SDK, so we don't have to install the old SDK just for this library?

**Comment by SSE4** [comment]
I can try, I'll take a look

**Comment by JimmySnails** [comment]
Thank you, much appreciated!

**Comment by JimmySnails** [comment]
Fyi, libmpg123 can't be built for emscripten (1.15.0):
src/libout123/modules/jack.c:21:10: fatal error: 'jack/jack.h' file not found

**Comment by SSE4** [comment]
@JimmySnails does libmpg123 have an option to disable jack?

**Comment by JimmySnails** [comment]
I couldn‘t find one :-/

**Comment by SSE4** [comment]
okay, then we'll need to patch it to work in Emscripten :(
also, please open another issue, let's keep this one about Windows SDK

**Comment by JimmySnails** [comment]
ok, sry. i opened #783

**Comment by JimmySnails** [comment]
@SSE4 I've fixed this by replacing the SDK string in the vcxproj file.

`tools.replace_in_file( "libmpg123.vcxproj", "<WindowsTargetPlatformVersion>8.1</WindowsTargetPlatformVersion>", "<WindowsTargetPlatformVersion>10</WindowsTargetPlatformVersion>")
`

I've placed it in line 70 in the **conanfile.py**

because it's in the correct directoy there..

```
        with tools.chdir(os.path.join(self._source_subfolder, "ports", "MSVC++", "2015", "win32", "libmpg123")):
            configuration = str(self.settings.build_type) + "_x86"
            tools.replace_in_file( "libmpg123.vcxproj", "<WindowsTargetPlatformVersion>8.1</WindowsTargetPlatformVersion>", "<WindowsTargetPlatformVersion>10</WindowsTargetPlatformVersion>")
            if self.options.shared:
                configuration += "_Dll"
            msbuild = MSBuild(self)
            msbuild.build(project_file="libmpg123.vcxproj", build_type=configuration)
```

I don't know how you would fix this, maybe by checking the compiler version with something like
`if compiler_version >= 15` (Studio 2017 and 2019)
?

I also don't know if that's the correct part in the code to do that, but it's working.

Hopefully you can add that in the master, i don't want to install the old 8 SDK... :)

**Comment by SSE4** [comment]
@JimmySnails applied: https://github.com/bincrafters/conan-libmpg123/commit/2a99c1d9ba4fdc87d6ca1c2f88b4b400e2f6a587

**Comment by JimmySnails** [comment]
perfect, thx!

**Comment by SSE4** [comment]
merged, closing
