### ISSUE TITLE
Package proposal: conan-protobuf

### ISSUE THREAD

**Issue by jgsogo** [bincrafters/community#77]
I'm working on a new package (very surprised not to find it): **Google Protobuffers**.

I've seen memsharded and lasote old packages but those needed fresh air, so I created the package from scratch using bincrafters-template. It is almost ready, but I wanted to **receive feedback from you all before committing it to bincrafters**.

 * Repo url: https://github.com/jgsogo/conan-protobuf/tree/testing/3.5.1
 * Travis: https://travis-ci.org/jgsogo/conan-protobuf/branches
 * Appveyor: https://ci.appveyor.com/project/jgsogo/conan-protobuf/history

Issues/TODOs:
 * MinGW compilation fails with a ```error: 'nullptr' was not declared in this scope```
 * Shared build fails (issue: https://github.com/google/protobuf/issues/2502), it is disabled in CI.

Feel free to PR or comment here and I will make the changes. Thanks!

**Comment by solvingj** [comment]
This is great to see!  I will review it, and ask others to look as well.

**Comment by jgsogo** [comment]
Transferred to @bincrafters: https://github.com/bincrafters/conan-protobuf  Let's move conversation there.

**Comment by richardor** [comment]
@solvingj , @jgsogo ,  I have used the conan-protobuf library. there is somethin wrong built by MD on Windows x86.

**Comment by jgsogo** [comment]
Open issue here, please: https://github.com/bincrafters/conan-protobuf

**Comment by solvingj** [comment]
@richardor it looks like the test_package is passing on windows/x86/md.  Can you provide any description of the problem you are experiencing?

**Comment by solvingj** [comment]
Latest update was that @richardor was doing the following per @jgsogo : 

"compiling protobuf with static_rt=True (it is the default option), while your project is being compiled using dynamic. Check here how to handle static/dynamic flag."

Check here how to handle static/dynamic flag.  

https://github.com/bincrafters/conan-protobuf/blob/testing/3.5.1/test_package/CMakeLists.txt#L12
