### ISSUE TITLE
[glad] Allow c-debug generator for DEBUG type build

### ISSUE THREAD

**Issue by noizex** [bincrafters/community#770]
### Description of your feature
I noticed that by default GLAD Conan Package is built with "c" generator. There is no way to pass anything else, but to have debug capabilities in GLAD we need to use "c-debug" generator. It could be either enabled with a flag ("glad:debug") and/or decided by the build type (DEBUG = flag enabled, otherwise not). 

Without this generator there are no debug callbacks available in generated glad.h. 

For the reference, see here: https://github.com/Dav1dde/glad#cc-debug

**Comment by SSE4** [comment]
I  prefer to distinguish by build type then. I'll add required changes.

**Comment by noizex** [comment]
Thanks!

**Comment by SSE4** [comment]
@noizex actually, I see required changes are already here:
https://github.com/bincrafters/conan-glad/blob/stable/0.1.29/conanfile.py#L64
am I missing the point?

**Comment by noizex** [comment]
Ouch, you're right - that's the thing. I didn't see it in my case, maybe I used earlier version somehow. Sorry for confusion, I will check that one out. 👍

**Comment by SSE4** [comment]
I am closing this for now as there is nothing to be done
