### ISSUE TITLE
libmikmod/3.3.11.1 can't be built for Android

### ISSUE THREAD

**Issue by JimmySnails** [bincrafters/community#771]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libmikmod/3.3.11.1**
  * Operating System+version: **Linux Debian Stretch**
  * Compiler+version: **android toolchain, clang 8**
  * Docker image: **none**
  * Conan version: **conan 1.14.4**
  * Python version: **Python 3.5.3*

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)

```
Configuration for profile android_profile:

[settings]
os=Android
os_build=Linux
arch=armv8
arch_build=x86_64
compiler=clang
compiler.version=8
compiler.libcxx=libc++
build_type=Release
os.api_level=21
[options]
*:pic=True
*:with_oss=False
*:with_pulse=False
[build_requires]
*: android_ndk_installer/r19c@bincrafters/stable
[env]
```

### Steps to reproduce (Include if Applicable)
When building SDL2_mixer with conan for android, the dependency libmikmod fails:
> libmikmod/3.3.11.1@bincrafters/stable: Generator cmake created conanbuildinfo.cmake
> -- Conan: C++ stdlib: libc++
> CMake Error at CMakeLists.txt:634 (MESSAGE):
>  OSS support is disabled.

When disabling OSS for libmikmod, it fails because it can't find libpulse:
> /home/cwelsch/.conan/data/libmikmod/3.3.11.1/bincrafters/stable/build/f00c80f3dc02ec812c7be0be57b2a091dab10bf4/source_subfolder/drivers/drv_pulseaudio.c:33:10: fatal error: 
>     'pulse/simple.h' file not found

My android_profile:
```
include(default)

[settings]
os_build=Linux
os=Android
os.api_level=21
compiler=clang
compiler.version=8
arch=armv8
compiler.libcxx=libc++
arch_build=x86_64

[build_requires]
android_ndk_installer/r19c@bincrafters/stable
[options]
*:pic = True
```

I had to add to get it working:

```
*:with_oss = False
*:with_pulse = False
```

**Comment by SSE4** [comment]
probably, we need to disable bunch of features for Android. I'll take a look

**Comment by SSE4** [comment]
applied a fix: https://github.com/bincrafters/conan-libmikmod/commit/b56f186b8b8b9bdc17b4e6cc015cf6629d4658a8

**Comment by JimmySnails** [comment]
This is in the testing branch... how to i build it? 

I've tried adding it to the android_profile:
```
[settings]
arch=armv8
build_type=Release
arch_build=x86_64
compiler=clang
compiler.libcxx=libc++
compiler.version=8
os=Android
os.api_level=21
os_build=Linux
[build_requires]
android_ndk_installer/r19c@bincrafters/stable
libmikmod/3.3.11.1@bincrafters/testing
[options]
*:pic = True
*:with_oss = False
*:with_pulse = False
```

but it still uses stable.

When i try `conan install libmikmod/3.3.11.1@bincrafters/testing` it can't find it:

```
libmikmod/3.3.11.1@bincrafters/testing: Not found in local cache, looking in remotes...
libmikmod/3.3.11.1@bincrafters/testing: Trying with 'conan-center'...
libmikmod/3.3.11.1@bincrafters/testing: Trying with 'theodelrieu'...
libmikmod/3.3.11.1@bincrafters/testing: Trying with 'AFG'...
libmikmod/3.3.11.1@bincrafters/testing: Trying with 'bincrafters'...
ERROR: Unable to find 'libmikmod/3.3.11.1@bincrafters/testing' in remotes
```

and i think that if it would find it, it would only build for the host OS, not android crossbuild.
Sry, i'm a conan noob :)

Nevertheless, your change seems sane!

**Comment by SSE4** [comment]
testing branch is not uploaded on bintray.
in order to try, you need to clone the repository and run `conan create . bincrafters/testing` within it.
anyway, I've opened PR to merge into the stable: https://github.com/bincrafters/conan-libmikmod/pull/3

**Comment by JimmySnails** [comment]
Great, i think we can change this. Thank you so much for your quick response!
