### ISSUE TITLE
openal/1.18.2 mingw cross-compilation cmake issue

### ISSUE THREAD

**Issue by barsoosayque** [bincrafters/community#775]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **openal/1.18.2**
  * Operating System+version: **Linux Arch**
  * Compiler+version: **gcc-9.1**
  * Conan version: **conan 1.15.0**
  * Python version: **Python 3.7.3**
  * CMake version: **cmake 3.14.3**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)

```
Configuration for profile win32:

[settings]
os_build=Linux
arch_build=x86_64
os=Windows
arch=x86
compiler=gcc
compiler.version=9.1
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
CONAN_CMAKE_FIND_ROOT_PATH=$toolchain
CHOST=i686-w64-mingw32
AR=i686-w64-mingw32-ar
AS=i686-w64-mingw32-as
RANLIB=i686-w64-mingw32-ranlib
CC=i686-w64-mingw32-gcc
CXX=i686-w64-mingw32-g++
STRIP=i686-w64-mingw32-strip
RC=i686-w64-mingw32-windres
```

### Steps to reproduce (Include if Applicable)

I did try to cross-compile SFML via `conan install` in my tiny project. SFML required openal. 

I used the aforementioned profile to do a cross-compilation, and other dependencies were built quite well, yet the openal failed.

### Logs (Include/Attach if Applicable)

```
...
-- Could NOT find ALSA (missing: ALSA_LIBRARY) (found version "1.1.8")
-- Found OSS: /usr/include
-- Could NOT find AudioIO (missing: AUDIOIO_INCLUDE_DIR)
-- Could NOT find SoundIO (missing: SOUNDIO_LIBRARY SOUNDIO_INCLUDE_DIR)
-- Could NOT find QSA (missing: QSA_LIBRARY QSA_INCLUDE_DIR)
CMake Error at /usr/share/cmake-3.14/Modules/CheckIncludeFiles.cmake:68 (message):
  Unknown arguments:

    -D_WIN32_WINNT=0x0502

Call Stack (most recent call first):
  source_subfolder/CMakeLists.txt:968 (CHECK_INCLUDE_FILES)


-- Configuring incomplete, errors occurred!
```

---

I found a similar issue out there in [vcpkg repository](https://github.com/Microsoft/vcpkg/issues/2985). They fixed it by applying a patch. Since I'm personally not quite experienced with CMake, I can't really say if this is a good way to solve this (but I guess it's a nice workaround) or should this be fixed in the upstream instead ? Hence, creating a 'bug' issue.

**Comment by barsoosayque** [comment]
Oh. This was apparently fixed in 1.19.0 in the upstream, but latest stable SFML package still uses openal 1.18.2 (however, 1.19.0 on testing branch). Essentially, the issue will be closed when SFML _testing/2.5.1_ dependencies version changes will be merged into _stable/2.5.1_.

**Comment by Croydon** [comment]
The problem is that OpenAL 1.19.0 + 1.19.1 doesn't build with Clang 7 + 8; and 1.19.1 fails on all macOS versions additionally

I tried to update SFML to use OpenAL 1.19.1 as they use it upstream as well

**Comment by SSE4** [comment]
@barsoosayque @Croydon  as SFML now uses 1.19 (include our package), is there anything to be done?

**Comment by barsoosayque** [comment]
Thanks, yes. The initial error is gone now. However, when trying to cross-build Linux 64 to Windows 32, I have another error about `-rdynamic` flag, which seems to be not supported by *mingw32-gcc*. Although, I believe it's out of the scope of this issue.

**Comment by SSE4** [comment]
okay, I am closing this issue then
