### ISSUE TITLE
[libusb] Some libraries #include <libusb.h>

### ISSUE THREAD

**Issue by Morwenn** [bincrafters/community#777]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libusb/1.0.22**
  * Operating System+version: **Linux Ubuntu 18**
  * Compiler+version: **gcc-7.4**
  * Conan version: **Conan 1.14.1**
  * Python version: **Python 3.6.7**

### Description of your feature
I know that the canonical way to include libusb is to include `libusb-1.0/libusb.h`, but some libraries directly include `libusb.h`, which is quite unfortunate. It happened to me while I was trying to package the old libfreenect for a legay project.

Can we add `include/libusb-1.0` to the package's `includedirs` information, or should I patch the libraries trying to include `<libusb.h>` directly?

**Comment by SSE4** [comment]
yeah, let's add it, why not

**Comment by SSE4** [comment]
applied: https://github.com/bincrafters/conan-libusb/commit/8f4a3b966c6ad57db20dcdcb4138d92c38b9ee19#diff-2b1d42f71f22b7ea0412d7602dec166f

**Comment by Morwenn** [comment]
Thanks a lot! :)
