### ISSUE TITLE
[zmq] Update for new versions

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [bincrafters/community#779]
### Package Details
  * Package Name: **zmq**
  * Latest available Version: **4.3.1**

The above mentioned version is newly released by the upstream project and not yet available within Bincrafters. Please add this version.

**Comment by SSE4** [comment]
created new branch, running CI: https://github.com/bincrafters/conan-zmq/tree/testing/4.3.1

**Comment by SSE4** [comment]
new version is available
