### ISSUE TITLE
cannot download the file "build_template_default.py"

### ISSUE THREAD

**Issue by richardor** [bincrafters/community#78]
cannot download the file: "build_template_default.py"
the url is : https://raw.githubusercontent.com/bincrafters/conan-templates/package_tools_modules/build_template_default.py

**Comment by richardor** [comment]
@solvingj @uilianries thank you both.
And I want to know how to join bincrafters? Maybe I could do something for conan packages.

**Comment by uilianries** [comment]
@richardor join us on Slack: http://cpplang.slack.com/, channel #bincrafters

**Comment by solvingj** [comment]
Yes, please do, we're always looking for more help.
