### ISSUE TITLE
Contributing Backlog link broken

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [bincrafters/community#780]
### Steps to reproduce (Include if Applicable)

1. Navigate to [contributing](https://github.com/bincrafters/community/blob/master/.github/CONTRIBUTING.md)
2. Click [Backlog](https://trello.com/b/iFeFCPwa/conanio-package-backlog-looking-for-contributors) link in **Your First Code Contribution** section
3. Be greeted with Trello's **Board not found.**

Note: I did only just create a Trello account (using Google login). Don't think this should matter though.

**Comment by SSE4** [comment]
yeah, we're no longer using trello, I am removing this sentence

**Comment by SSE4** [comment]
removed: https://github.com/bincrafters/community/commit/50ecd2cbd8ec33f7d9f0afd710bd32b0734319bb#diff-8cc7b2b0d78dd2501610391c086a8516
