### ISSUE TITLE
GTest: Cannot get minimal example running

### ISSUE THREAD

**Issue by sebastian8000** [bincrafters/community#782]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **gtest/1.8.1**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **gcc-7.4.0**
  * Conan version: **Conan 1.15.0**
  * Python version: **Python 3.7.3**

### Question Description
I try to get a minimal Googletest example running using the `cmake_paths` generator, but linking fails.

My conanfile.txt:
```
[requires]
gtest/1.8.1@bincrafters/stable

[generators]
cmake_paths
```

My CMakelists.txt:
```
cmake_minimum_required (VERSION 3.0)

project (conan-gtest-test)

find_package(GTest REQUIRED)

enable_testing()

add_executable(foo foo_test.cpp)
target_link_libraries(foo PRIVATE GTest::GTest GTest::Main)
```

foo_test.cpp:
```
#include "gtest/gtest.h"

TEST(FooTest, TestA) {
  EXPECT_EQ(1, 1);
  EXPECT_EQ(1, 2);
}
```

I try to build the project using:
`conan install .. --build missing && cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_paths.cmake -DCMAKE_BUILD_TYPE=Release && make`

Linker error:

```
Scanning dependencies of target foo
[ 50%] Building CXX object CMakeFiles/foo.dir/foo_test.cpp.o
[100%] Linking CXX executable foo
CMakeFiles/foo.dir/foo_test.cpp.o: In Funktion »FooTest_TestA_Test::TestBody()«:
foo_test.cpp:(.text+0x8cb): Warnung: undefinierter Verweis auf »testing::internal::EqFailure(char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)«
collect2: error: ld returned 1 exit status
CMakeFiles/foo.dir/build.make:96: recipe for target 'foo' failed
make[2]: *** [foo] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/foo.dir/all' failed
make[1]: *** [CMakeFiles/foo.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by uilianries** [comment]
Hi @sebastian8000 !

As you can see, the signature contains `std::__cxx11::basic_string` which means it requires libstdc++11. Please, update your default profile to use the expected library:

    conan profile update settings.compiler.libcxx=libstdc++11 default

**Comment by sebastian8000** [comment]
Hi @uilianries,

thanks a lot. It solved problem.
