### ISSUE TITLE
libmpg123 can't be built for emscripten because jack.h is missing

### ISSUE THREAD

**Issue by JimmySnails** [bincrafters/community#783]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: libmpg123/1.25.10
  * Operating System+version: Windows 10
  * Compiler+version: Visual Studio 2019
  * Docker image: none ?
  * Conan version: Conan 1.14.4
  * Python version: Python 3.7.3

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
I don't have it here yet, but i used the one from the example. I can post it later if nececssary.

### Steps to reproduce (Include if Applicable)

Build libmp123 for emscripten.
This library is required for SDL2_mixer, that's why i need it.

During build, following error message appears.
src/libout123/modules/jack.c:21:10: fatal error: 'jack/jack.h' file not found

In the configure script, there are a bunch of variables. There is 
```
BUILD_JACK_FALSE
BUILD_JACK_TRUE
```

and there is this configure option:
`  --with-default-audio=jack           Use JACK as default low-latency audio server`

but i didn't find a way to disable it.

**Comment by SSE4** [comment]
@JimmySnails may you try to build with the following option?
https://github.com/gypified/libmpg123/blob/master/configure#L1641
```
--with-default-audio=dummy      Use dummy as default audio (when no sound card is available)
```

**Comment by JimmySnails** [comment]
Yes! That did the trick! :)

**Comment by JimmySnails** [comment]
Does this mean libmpg123 builds but won't work?

**Comment by SSE4** [comment]
depends on what do you need. decoding APIs will work, as you're decoding to the buffer. audio playback APIs won't work, and I am not currently sure which audio device API is suitable for the Emscripten. if you can clarify that, would be nice (and you can select suitable with configure flag).
for now, I guess I just will put `--with-default-audio=dummy` for Emscripten, until further clarification.

**Comment by SSE4** [comment]
applied: https://github.com/bincrafters/conan-libmpg123/commit/8a3853d991ba474e508d4b55b607037b23af173a
feel free to try other `--with-default-audio=xxx` options for the Emscripten and lemme know.

**Comment by JimmySnails** [comment]
I've tried all backends, that remotely make sense... The only one working is "sdl".

Unfortunately, i can't try it because i'm stuck with libPNG not building.  Don't know if dummy or SDL makes more sens

**Comment by SSE4** [comment]
not sure, may you try to run simple libmpg123 example in browser with SDL backend to verify if it actually plays an audio?

**Comment by SSE4** [comment]
I am going to look into other libraries (png, jpeg) today. I'll let you know how is it going.

**Comment by JimmySnails** [comment]
awesome! thank you! 

i don't have time to do a audio only example right now, and tbh i don't know yet how to compile my application for emscripten when the conan dependencies are solved. It was quite easy with the emcripten stuff alone ( -s SDL=2 and so on)

And i couldn't get SDL_mixer to work at all, so... :D

**Comment by JimmySnails** [comment]
Let's close this one for now and i'll do further tests later, since this one was about compiling and not functionality. 

Unfortunately, flac/1.3.2@bincrafters/stable also fails on emscripten. (i don't use flac anyway) and the SDLmixer stuff isn't at the bincrafters repo, but at the repo from one of my contributors.
