### ISSUE TITLE
libjpeg-turbo/1.5.2 can't be built for emscripten

### ISSUE THREAD

**Issue by JimmySnails** [bincrafters/community#786]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: libjpeg-turbo/1.5.2
  * Operating System+version: Debian Stretch
  * Compiler+version: emscripten toolchain compiler
  * Docker image: none ?
  * Conan version: Conan 1.15.0
  * Python version: Python 3.5.3

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)

```
[settings]
os=Emscripten
arch=asm.js
os_build=Linux
arch_build=x86_64
compiler=clang
compiler.version=6.0
compiler.libcxx=libc++
[options]
[build_requires]
emsdk_installer/1.38.22@bincrafters/stable
```

### Steps to reproduce (Include if Applicable)

emscripten has no SIMD support. If it's disabled, it works:
[options]
libjpeg-turbo:SIMD = False

Suggestion: Add this default flag for emscripten

**Comment by SSE4** [comment]
@JimmySnails  applied: https://github.com/bincrafters/conan-libjpeg-turbo/commit/4ac5fe85f6bcf96d13c7a79aef3d73c7c9e9cb50
please give an another try and lemme know

**Comment by JimmySnails** [comment]
Confirmed! Thx again for fixing that!

**Comment by SSE4** [comment]
merged, closing
