### ISSUE TITLE
OpenSSL/1.1.1a fails on emscripten crossbuild - unsupported operating system

### ISSUE THREAD

**Issue by JimmySnails** [bincrafters/community#787]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: OpenSSL/1.1.1a
  * Operating System+version: Debian Stretch
  * Compiler+version: emscripten toolchain compiler
  * Docker image: none ?
  * Conan version: Conan 1.15.0
  * Python version: Python 3.5.3

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Emscripten
arch=asm.js
os_build=Linux
arch_build=x86_64
compiler=clang
compiler.version=6.0
compiler.libcxx=libc++
[options]
[build_requires]
emsdk_installer/1.38.22@bincrafters/stable
[options]
libjpeg-turbo:SIMD = False
```

### Steps to reproduce (Include if Applicable)
build OpenSSL/1.1.1a for emscripten

### Logs (Include/Attach if Applicable)

```
OpenSSL/1.1.1a@conan/stable: ERROR: Package '4d26d78a37374f38419f1607939e7de75f52abf5' build failed
OpenSSL/1.1.1a@conan/stable: WARN: Build folder /home/cwelsch/.conan/data/OpenSSL/1.1.1a/conan/stable/build/4d26d78a37374f38419f1607939e7de75f52abf5
ERROR: OpenSSL/1.1.1a@conan/stable: Error in build() method, line 89
	raise Exception("Unsupported operating system: %s" % self.settings.os)
	Exception: Unsupported operating system: Emscripten
```

**Comment by SSE4** [comment]
@JimmySnails I was trying to build OpenSSL for Emscripten, but it seems like it's unsupported. were you able to find some instructions or ports for it?

**Comment by JimmySnails** [comment]
No, i couldn't find a port. :(

Tbh i don't know where the dependency is coming from...  I've disabled SDL2_mixer for now, and just using SDL2, SDL2_ttf, SDL2_image and libnoise... i don't use it actively and i was able to build my project with emscripten (without conan)

(see https://game.cytopia.net/ )
( my repo https://github.com/JimmySnails/Cytopia )

I think it'd be ok with disabling the openssl for emscripten

**Comment by SSE4** [comment]
may you try to run `conan info . -g graph.html` and attach graph here?

**Comment by JimmySnails** [comment]
Sure! Here you go:
[graph.zip](https://github.com/bincrafters/community/files/3172212/graph.zip)

**Comment by JimmySnails** [comment]
ahh, this is embarassing... it's in my conanfile.txt.

But i didn't write it, it was a PR... unfortunately, i have very little experience with conan

**Comment by JimmySnails** [comment]
But even i f iremove openssl from conanfile.txt in my src dir, it still tries to build it.
If i add openssl 1.1.1b, it also downloads 1.1.1a

Heres the update graph
[graph.zip](https://github.com/bincrafters/community/files/3172251/graph.zip)

**Comment by solvingj** [comment]
I think this ticket should be under conan-community organization. We can try to transfer the issue via github.

**Comment by JimmySnails** [comment]
I‘ll create a new one at the conan repo. I already noticed that it’s not in the bincrafters repo 😅
