### ISSUE TITLE
[zmq/4.3.1] Build fails on MSVC 2019

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [bincrafters/community#788]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **zmq/4.3.1**
  * Operating System+version: **Windows 10**
  * Compiler+version: **msvc-16**
  * Conan version: **conan 1.15.0**
  * Python version: **Python 3.7.3**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
Configuration for profile default:

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
compiler.toolset=v142
build_type=Release
[options]
[build_requires]
[env]

### Steps to reproduce (Include if Applicable)
conan install [some project dependent on zmq/4.3.1@bincrafters/stable] --build zmq

### Logs (Include/Attach if Applicable)
zmq/4.3.1@bincrafters/stable: Applying build-requirement: ninja_installer/1.8.2@bincrafters/stable
zmq/4.3.1@bincrafters/stable: WARN: Build folder is dirty, removing it: C:\Users\mirko.vonleipzig\.conan\data\zmq\4.3.1\bincrafters\stable\build\3fb49604f9c2f729b85ba3115852006824e72cab
zmq/4.3.1@bincrafters/stable: Copying sources to build folder
zmq/4.3.1@bincrafters/stable: Building your package in C:\Users\mirko.vonleipzig\.conan\data\zmq\4.3.1\bincrafters\stable\build\3fb49604f9c2f729b85ba3115852006824e72cab
zmq/4.3.1@bincrafters/stable: Generator cmake created conanbuildinfo.cmake
zmq/4.3.1@bincrafters/stable: Calling build()
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.0.3
** Copyright (c) 2019 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
CMake Error at CMakeLists.txt:2 (project):
  Generator

    Ninja

  does not support toolset specification, but toolset

    v142

  was specified.

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "C:/Users/mirko.vonleipzig/.conan/data/zmq/4.3.1/bincrafters/stable/build/3fb49604f9c2f729b85ba3115852006824e72cab/build_subfolder/CMakeFiles/CMakeOutput.log".
zmq/4.3.1@bincrafters/stable:
zmq/4.3.1@bincrafters/stable: ERROR: Package '3fb49604f9c2f729b85ba3115852006824e72cab' build failed
zmq/4.3.1@bincrafters/stable: WARN: Build folder C:\Users\mirko.vonleipzig\.conan\data\zmq\4.3.1\bincrafters\stable\build\3fb49604f9c2f729b85ba3115852006824e72cab
ERROR: zmq/4.3.1@bincrafters/stable: Error in build() method, line 53
        cmake = self._configure_cmake()
while calling '_configure_cmake', line 49
        cmake.configure(build_dir=self._build_subfolder)
        ConanException: Error 1 while executing cd build_subfolder && cmake -G "Ninja" -DCONAN_LINK_RUNTIME="/MD" -DCMAKE_BUILD_TYPE="Release" -DCONAN_EXPORTED="1" -DCONAN_IN_LOCAL_CACHE="ON" -DCONAN_COMPILER="Visual Studio" -DCONAN_COMPILER_VERSION="16" -DCONAN_CXX_FLAGS="/MP8" -DCONAN_C_FLAGS="/MP8" -DBUILD_SHARED_LIBS="OFF" -DCMAKE_INSTALL_PREFIX="C:\Users\mirko.vonleipzig\.conan\data\zmq\4.3.1\bincrafters\stable\package\3fb49604f9c2f729b85ba3115852006824e72cab" -DCMAKE_INSTALL_BINDIR="bin" -DCMAKE_INSTALL_SBINDIR="bin" -DCMAKE_INSTALL_LIBEXECDIR="bin" -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_INCLUDEDIR="include" -DCMAKE_INSTALL_OLDINCLUDEDIR="include" -DCMAKE_INSTALL_DATAROOTDIR="share" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -DENABLE_CURVE="True" -DWITH_LIBSODIUM="False" -DZMQ_BUILD_TESTS="False" -DWITH_PERF_TOOL="False" -DBUILD_SHARED="False" -DBUILD_STATIC="True" -Wno-dev -T "v142" C:\Users\mirko.vonleipzig\.conan\data\zmq\4.3.1\bincrafters\stable\build\3fb49604f9c2f729b85ba3115852006824e72cab

**Comment by Mirko-von-Leipzig** [comment]
I've now installed VS2017 and it's also failing with the same error except its toolset v141.

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=15
compiler.toolset=v141
build_type=Release
[options]
[build_requires]
[env]

**Comment by SSE4** [comment]
this is a definitely bug, conan shouldn't be passing `-T` to the CMake for the `Ninja` generator

**Comment by SSE4** [comment]
created an issue: https://github.com/conan-io/conan/issues/5133

**Comment by SSE4** [comment]
as a workaround, I am going to remove ninja from package for now

**Comment by SSE4** [comment]
removed: https://github.com/bincrafters/conan-zmq/commit/643b61900b6bf79d8f298998ef0e593ec2b11a1c

**Comment by Mirko-von-Leipzig** [comment]
Stupid question - how do I use this? Can I just change my dependency channel from stable to testing?
i.e. zmq/4.3.1@bincrafters/testing? Or must I clone the branch and conan from that?

**Comment by SSE4** [comment]
@Mirko-von-Leipzig I've merged to the stable now, please give a try

**Comment by Mirko-von-Leipzig** [comment]
It's working now. Thanks!

**Comment by SSE4** [comment]
okay, I am closing our issue then. there is conan issue opened to track bug.
