### ISSUE TITLE
pcre/8.41 add windows gcc 32-bit builds + gcc-8

### ISSUE THREAD

**Issue by madebr** [bincrafters/community#793]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **pcre/8.41**
  * Operating System+version: **Windows**
  * Compiler+version: **gcc**
  * Conan version: **all**

### Description of your feature
gcc 8 and gcc 32-bit bilds of pcre on Windows are missing.

https://github.com/bincrafters/conan-pcre/pull/10

**Comment by Croydon** [comment]
Merged
