### ISSUE TITLE
[qt] Remove Linux jobs from Travis CI

### ISSUE THREAD

**Issue by uilianries** [bincrafters/community#796]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.12.3**

### Question Description
Since we are using Azure DevOps to build Qt on Linux, the same jobs are duplicated on Travis CI. I think we could remove those jobs from Travis file and keep only in Azure file.

/cc @ericLemanissier

**Comment by ericLemanissier** [comment]
Unfortunately the upload of binaries still fails on azure DevOps: https://developercommunity.visualstudio.com/content/problem/388538/https-request-read-time-out-error.html

**Comment by uilianries** [comment]
Oh, I see ... Thanks for sharing your situation.

**Comment by uilianries** [comment]
@ericLemanissier What do you think about Circle CI for Linux Jobs? I could provide the CI file

**Comment by ericLemanissier** [comment]
I'm fine with everything, but it's true that I don't know anything about circle CI, so any help is welcome !

**Comment by uilianries** [comment]
No problem. We just tried Circle CI some ago. It's faster than Travis, but the web interface is like Appveyor, not much intuitive sometimes.
