### ISSUE TITLE
[bison/bison_installer] Paths hardcoded as /home/conan/... in the bison executable

### ISSUE THREAD

**Issue by Quincunx271** [bincrafters/community#797]
### Package and Environment Details
  * Package Name/Version: **bison_installer/3.3.2@bincrafters/stable** and **bison/3.3.2@bincrafters/stable**
  * Operating System+version: **Linux Ubuntu 16.04**
  * Compiler+version: **gcc-8.1.0**
  * Conan version: **conan 1.9.1** and **conan 1.15.1**
  * Python version: **Python 3.5.2**

### Conan profile

```
[settings]
os=Linux
compiler=gcc
compiler.version=8
compiler.libcxx=libstdc++11
build_type=Debug
arch=x86_64
cppstd=17
os_build=Linux
arch_build=x86_64

[options]

[env]
CC=gcc-8
CXX=/usr/bin/g++-8
```

### Steps to reproduce

After installing bison, try to use it with CMake's `bison_target`, or just call the executable directly:

```
~/.conan/data/bison_installer/3.3.2/bincrafters/stable/package/c2140270a5f39981f3573371b9a402cc4f4fb2f8/bin/bison sample.y
```

**sample.y**
```yacc
%%
empty: ;
%%
```

### Output:

```
/home/my_user/.conan/data/bison_installer/3.3.2/bincrafters/stable/package/c2140270a5f39981f3573371b9a402cc4f4fb2f8/bin/bison: /home/conan/.conan/data/bison_installer/3.3.2/bincrafters/stable/package/c2140270a5f39981f3573371b9a402cc4f4fb2f8/share/bison/m4sugar/m4sugar.m4: cannot open: No such file or directory
```

### Other information:

`grep -r '/home/conan' ~/.conan/data/bison_installer/3.3.2/bincrafters/stable/`:

```
Binary file /home/my_user/.conan/data/bison_installer/3.3.2/bincrafters/stable/package/c2140270a5f39981f3573371b9a402cc4f4fb2f8/bin/bison matches
```

`strings ~/.conan/data/bison_installer/3.3.2/bincrafters/stable/package/c2140270a5f39981f3573371b9a402cc4f4fb2f8/bin/bison | grep '/home/conan'`:

```
/home/conan/.conan/data/bison_installer/3.3.2/bincrafters/stable/package/c2140270a5f39981f3573371b9a402cc4f4fb2f8/share/locale
/home/conan/.conan/data/bison_installer/3.3.2/bincrafters/stable/package/c2140270a5f39981f3573371b9a402cc4f4fb2f8/share/locale
/home/conan/.conan/data/m4_installer/1.4.18/bincrafters/stable/package/44fcf6b9a7fb86b2586303e3db40189d3b511830/bin/m4
/home/conan/.conan/data/bison_installer/3.3.2/bincrafters/stable/package/c2140270a5f39981f3573371b9a402cc4f4fb2f8/bin
/home/conan/.conan/data/bison_installer/3.3.2/bincrafters/stable/package/c2140270a5f39981f3573371b9a402cc4f4fb2f8/share/bison
```

**Comment by madebr** [comment]
The bison executable needs some environment variables to be set correctly, namely `BISON_PKGDATADIR` for its scripts and `M4` for the m4 interpreter.

These are set in their conanfiles:
bison_installer: https://github.com/bincrafters/conan-bison/blob/ff378ced2b0426cae2e8c60eb32f5cada3828cd0/conanfile_installer.py#L19
m4: https://github.com/bincrafters/conan-m4_installer/blob/0f0698f45f4a6bbdd5ebbdaba42118f343d3d189/conanfile.py#L53

Your example will thus work correctly if you would execute is at follows:
```
M4=~/.conan/data/m4_installer/1.4.18/bincrafters/stable/package/44fcf6b9a7fb86b2586303e3db40189d3b511830/bin/m4 BISON_PKGDATADIR=~/.conan/data/bison_installer/3.3.2/bincrafters/stable/package/c2140270a5f39981f3573371b9a402cc4f4fb2f8/share/bison ~/.conan/data/bison_installer/3.3.2/bincrafters/stable/package/c2140270a5f39981f3573371b9a402cc4f4fb2f8/bin/bison sample.y
```

**Comment by Quincunx271** [comment]
So, in other words, the problem occurs because I'm not using a `CONAN_PKG::bison` target, but instead using `find_package(BISON ...)` to find Bison? If so, it may be a good idea to export a `BISONConfig.cmake` which is basically just `FindBISON.cmake` but also sets these env variables when talking with the `bison` executable.

Either way, strongly think that the bison executable should be executable without doing this. I know that `winflexbison` works with `find_package(BISON ...)`. Maybe there's some way to remove the relative paths from Bison, or incorporate m4 into it.

**Comment by SSE4** [comment]
yeah, I think I can merge additional changes from winflexbison, so it doesn't have hard-coded paths any longer

**Comment by SSE4** [comment]
update: I have identified all required changes and preparing patch, will keep you informed

**Comment by SSE4** [comment]
I've applied required changes (mostly taken from winflexbison): https://github.com/bincrafters/conan-bison/commit/ab1db668e1cab2b2c9a2c8ca07935733593a6e3e
bison executable no longer contains hard-coded paths and works without additional environment variables
