### ISSUE TITLE
sdl2_image/2.0.4 - Android No CMake minimum version 

### ISSUE THREAD

**Issue by JimmySnails** [bincrafters/community#799]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **sdl2_image/2.0.4**
  * Operating System+version: Linux Debian Stretch
  * Compiler+version: Android toolchain
  * Docker image: none ?
  * Conan version: Conan 1.15.1
  * Python version: Python 3.5.3

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)

```
[settings]
os=Emscripten
arch=asm.js
os_build=Linux
arch_build=x86_64
compiler=clang
compiler.version=6.0
compiler.libcxx=libc++
[options]
[build_requires]
emsdk_installer/1.38.22@bincrafters/stable
[options]
libjpeg-turbo:SIMD = False
```

### Steps to reproduce (Include if Applicable)

Same Problem as in #471 

### Logs (Include/Attach if Applicable)
```
-- Conan: Checking correct version: 8
CMake Error in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.13)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".


-- Configuring incomplete, errors occurred!
See also "/home/cwelsch/.conan/data/sdl2_image/2.0.4/bincrafters/stable/build/3bdab614864f5db6e2d3d724b096e2e12eba5677/build/CMakeFiles/CMakeOutput.log".
sdl2_image/2.0.4@bincrafters/stable: 

```

**Comment by SSE4** [comment]
applied: https://github.com/bincrafters/conan-sdl2_image/commit/30efc51d3cf9edbae4d52f6936c1f270a041abb9

**Comment by JimmySnails** [comment]
Can you merge this into the stable branch please? I verified that it's working before i created the issue

**Comment by Croydon** [comment]
We merge things into the `stable/` branch when the CI succeeded for the `testing/` branch.

I have merged it now. Done.
