### ISSUE TITLE
glew/2.1.0 - can't find openGL on android

### ISSUE THREAD

**Issue by JimmySnails** [bincrafters/community#801]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **glew/2.1.0**
  * Operating System+version: Linux Debian Stretch
  * Compiler+version: Android toolchain
  * Docker image: none ?
  * Conan version: Conan 1.15.1
  * Python version: Python 3.5.3

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
arch=armv8
build_type=Release
arch_build=x86_64
compiler=clang
compiler.libcxx=libc++
compiler.version=8
os=Android
os.api_level=21
os_build=Linux
[build_requires]
android_ndk_installer/r19c@bincrafters/stable
[options]
*:pic = True
*:with_oss = False
*:with_pulse = False
```

### Steps to reproduce (Include if Applicable)

building my sdl2 application fails during linkage because it can't find openGL functions. i thought GLEW could be the right package?

conan install glew/2.1.0@bincrafters/stable --build glew --profile=../android_profile

It can't find openGL. How can i resolve this?

### Logs (Include/Attach if Applicable)

```
-- Conan: Checking correct version: 8
CMake Error at /usr/local/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenGL (missing: OPENGL_opengl_LIBRARY OPENGL_glx_LIBRARY)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.13/Modules/FindOpenGL.cmake:395 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  _source_subfolder/build/cmake/CMakeLists.txt:40 (find_package)


-- Configuring incomplete, errors occurred!
```

**Comment by JimmySnails** [comment]
i figured out that i don't need glew. 

```
          find_library(OpenGLES2_LIBRARY GLESv2 REQUIRED)
          find_library(ANDROID_LOG_LIBRARY log REQUIRED)
          find_library(ANDROID_LIBRARY_LIBRARY android REQUIRED
```

is enough.

**Comment by SSE4** [comment]
from here: https://stackoverflow.com/questions/29492694/glew-is-just-and-extension-library-or-it-contains-opengl-es-2-0-implementation-a
```
The official version of glew does not support OpenGL ES at all, only desktop OpenGL.
```
