### ISSUE TITLE
Upstream Update: ICU 64.2

### ISSUE THREAD

**Issue by jmarrec** [bincrafters/community#802]
### Package Details
  * Package Name: **icu**
  * Latest available Version: **64.2**

The above mentioned version is newly released by the upstream project and not yet available within Bincrafters. Please add this version.

cf https://github.com/unicode-org/icu/releases
There is also 63.2 that isn't in bincrafters.

**Comment by solvingj** [comment]
Thanks very much for reaching out.  Creating `testing/64.2` branch. Please feel free to submit a PR to bump the version.

**Comment by jmarrec** [comment]
Thanks for the quick turn around. (PR at https://github.com/bincrafters/conan-icu/pull/18)
