### ISSUE TITLE
[qt] qt/5.12.X not buildable on Windows with -s qt:build_type=None

### ISSUE THREAD

**Issue by DirkScharff** [bincrafters/community#804]
I'm trying to build a qt package for use with cmake and visual studio 2019 including **debug and release configuration in one package**. 
Following #403 I defined -s qt:build_type=None to achive that. (Is this documented somewhere?)

If I build it with -o with_doubleconversion=True the package tries to link a debug version of doubleconversion to a release version of qtcore (or the other way around): 

> linking ..\..\lib\Qt5Cored.dll
double-conversion.lib(double-conversion.obj) : error LNK2038: Konflikt ermittelt f³r "_ITERATOR_DEBUG_LEVEL": Der Wert "0" stimmt nicht mit dem Wert "2" in qstring_compat.obj ³berein.
double-conversion.lib(double-conversion.obj) : error LNK2038: Konflikt ermittelt f³r "RuntimeLibrary": Der Wert "MD_DynamicRelease" stimmt nicht mit dem Wert "MDd_DynamicDebug" in qstring_compat.obj ³berein.
double-conversion.lib(bignum-dtoa.obj) : error LNK2038: Konflikt ermittelt f³r "_ITERATOR_DEBUG_LEVEL": Der Wert "0" stimmt nicht mit dem Wert "2" in qstring_compat.obj ³berein.
double-conversion.lib(bignum-dtoa.obj) : error LNK2038: Konflikt ermittelt f³r "RuntimeLibrary": Der Wert "MD_DynamicRelease" stimmt nicht mit dem Wert "MDd_DynamicDebug" in qstring_compat.obj ³berein.
double-conversion.lib(fast-dtoa.obj) : error LNK2038: Konflikt ermittelt f³r "_ITERATOR_DEBUG_LEVEL": Der Wert "0" stimmt nicht mit dem Wert "2" in qstring_compat.obj ³berein.
double-conversion.lib(fast-dtoa.obj) : error LNK2038: Konflikt ermittelt f³r "RuntimeLibrary": Der Wert "MD_DynamicRelease" stimmt nicht mit dem Wert "MDd_DynamicDebug" in qstring_compat.obj ³berein.
double-conversion.lib(fixed-dtoa.obj) : error LNK2038: Konflikt ermittelt f³r "_ITERATOR_DEBUG_LEVEL": Der Wert "0" stimmt nicht mit dem Wert "2" in qstring_compat.obj ³berein.
double-conversion.lib(fixed-dtoa.obj) : error LNK2038: Konflikt ermittelt f³r "RuntimeLibrary": Der Wert "MD_DynamicRelease" stimmt nicht mit dem Wert "MDd_DynamicDebug" in qstring_compat.obj ³berein.
double-conversion.lib(strtod.obj) : error LNK2038: Konflikt ermittelt f³r "_ITERATOR_DEBUG_LEVEL": Der Wert "0" stimmt nicht mit dem Wert "2" in qstring_compat.obj ³berein.
double-conversion.lib(strtod.obj) : error LNK2038: Konflikt ermittelt f³r "RuntimeLibrary": Der Wert "MD_DynamicRelease" stimmt nicht mit dem Wert "MDd_DynamicDebug" in qstring_compat.obj ³berein.
double-conversion.lib(bignum.obj) : error LNK2038: Konflikt ermittelt f³r "_ITERATOR_DEBUG_LEVEL": Der Wert "0" stimmt nicht mit dem Wert "2" in qstring_compat.obj ³berein.
double-conversion.lib(bignum.obj) : error LNK2038: Konflikt ermittelt f³r "RuntimeLibrary": Der Wert "MD_DynamicRelease" stimmt nicht mit dem Wert "MDd_DynamicDebug" in qstring_compat.obj ³berein.
double-conversion.lib(diy-fp.obj) : error LNK2038: Konflikt ermittelt f³r "_ITERATOR_DEBUG_LEVEL": Der Wert "0" stimmt nicht mit dem Wert "2" in qstring_compat.obj ³berein.
double-conversion.lib(diy-fp.obj) : error LNK2038: Konflikt ermittelt f³r "RuntimeLibrary": Der Wert "MD_DynamicRelease" stimmt nicht mit dem Wert "MDd_DynamicDebug" in qstring_compat.obj ³berein.
double-conversion.lib(cached-powers.obj) : error LNK2038: Konflikt ermittelt f³r "_ITERATOR_DEBUG_LEVEL": Der Wert "0" stimmt nicht mit dem Wert "2" in qstring_compat.obj ³berein.
double-conversion.lib(cached-powers.obj) : error LNK2038: Konflikt ermittelt f³r "RuntimeLibrary": Der Wert "MD_DynamicRelease" stimmt nicht mit dem Wert "MDd_DynamicDebug" in qstring_compat.obj ³berein.

(The errormessage is in german. In essence: ITERATOR_DEBUG_LEVEL of 0 in double-conversion does not match the value 2 in qt)

If i build with: -o with_doubleconversion=False I get the following error:

> ERROR: Your C library does not provide sscanf_l or snprintf_l.
You need to use libdouble-conversion for double/string conversion.

I also tried to build everything with build_type=None

> conan install --build=missing qt/5.12.3@bincrafters/stable -s build_type=None

but then the zlib package fails to package:

> zlib/1.2.11@conan/stable: Package '4068d26db0f235082dbcdd6f303d1cbf4d149cf1' built
zlib/1.2.11@conan/stable: Build folder C:\Users\DirkS\.conan\data\zlib\1.2.11\conan\stable\build\4068d26db0f235082dbcdd6f303d1cbf4d149cf1
zlib/1.2.11@conan/stable: Generated conaninfo.txt
zlib/1.2.11@conan/stable: Generated conanbuildinfo.txt
zlib/1.2.11@conan/stable: Generating the package
zlib/1.2.11@conan/stable: Package folder C:\Users\DirkS\.conan\data\zlib\1.2.11\conan\stable\package\4068d26db0f235082dbcdd6f303d1cbf4d149cf1
zlib/1.2.11@conan/stable: Calling package()
ERROR: zlib/1.2.11@conan/stable: Error in package() method, line 158
        self._rename_libraries()
while calling '_rename_libraries', line 123
        os.rename(current_lib, os.path.join(lib_path, "zlib.lib"))
        FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden: 'C:\\Users\\DirkS\\.conan\\data\\zlib\\1.2.11\\conan\\stable\\package\\4068d26db0f235082dbcdd6f303d1cbf4d149cf1\\lib\\zlibstatic.lib' -> 'C:\\Users\\DirkS\\.conan\\data\\zlib\\1.2.11\\conan\\stable\\package\\4068d26db0f235082dbcdd6f303d1cbf4d149cf1\\lib\\zlib.lib'

Any suggestions how I can get a package build?

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: qt/5.12.3
  * Operating System+version: Windows 10
  * Compiler+version: Visual Studio 2019 (msvc 16)
  * Conan version:  1.15.0
  * Python version: 3.7

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
build_type=Release
[options]
[build_requires]
[env]

### Steps to reproduce (Include if Applicable)

without doubleconversion:
conan install --build missing qt/5.12.3@bincrafters/stable -s qt:build_type=None  -o qt:with_doubleconversion=False

with doubleconversion:
conan install --build missing qt/5.12.3@bincrafters/stable -s qt:build_type=None -o qt:with_doubleconversion=True

everything build_type=None
conan install --build=missing qt/5.12.3@bincrafters/stable -s build_type=None

**Comment by ericLemanissier** [comment]
I have no idea if it could work, but can you try `-s qt:build_type=None -s double-conversion:build_type=None` ?
This multi-configuration package thing is not documented, because it is not really supported

**Comment by DirkScharff** [comment]
I tried it and it didn't work.

Same error message as before. 
> double-conversion.lib(double-conversion.obj) : error LNK2038: Konflikt ermittelt f³r "_ITERATOR_DEBUG_LEVEL": Der Wert "0" stimmt nicht mit dem Wert "2" in qstring_compat.obj ³berein.
double-conversion.lib(double-conversion.obj) : error LNK2038: Konflikt ermittelt f³r "RuntimeLibrary": Der Wert "MD_DynamicRelease" stimmt nicht mit dem Wert "MDd_DynamicDebug" in qstring_compat.obj ³berein.
double-conversion.lib(bignum-dtoa.obj) : error LNK2038: Konflikt ermittelt f³r "_ITERATOR_DEBUG_LEVEL": Der Wert "0" stimmt nicht mit dem Wert "2" in qstring_compat.obj ³berein.
double-conversion.lib(bignum-dtoa.obj) : error LNK2038: Konflikt ermittelt f³r "RuntimeLibrary": Der Wert "MD_DynamicRelease" stimmt nicht mit dem Wert "MDd_DynamicDebug" in qstring_compat.obj ³berein.
double-conversion.lib(fast-dtoa.obj) : error LNK2038: Konflikt ermittelt f³r "_ITERATOR_DEBUG_LEVEL": Der Wert "0" stimmt nicht mit dem Wert "2" in qstring_compat.obj ³berein.
double-conversion.lib(fast-dtoa.obj) : error LNK2038: Konflikt ermittelt f³r "RuntimeLibrary": Der Wert "MD_DynamicRelease" stimmt nicht mit dem Wert "MDd_DynamicDebug" in qstring_compat.obj ³berein.
double-conversion.lib(fixed-dtoa.obj) : error LNK2038: Konflikt ermittelt f³r "_ITERATOR_DEBUG_LEVEL": Der Wert "0" stimmt nicht mit dem Wert "2" in qstring_compat.obj ³berein.
double-conversion.lib(fixed-dtoa.obj) : error LNK2038: Konflikt ermittelt f³r "RuntimeLibrary": Der Wert "MD_DynamicRelease" stimmt nicht mit dem Wert "MDd_DynamicDebug" in qstring_compat.obj ³berein.
double-conversion.lib(strtod.obj) : error LNK2038: Konflikt ermittelt f³r "_ITERATOR_DEBUG_LEVEL": Der Wert "0" stimmt nicht mit dem Wert "2" in qstring_compat.obj ³berein.
double-conversion.lib(strtod.obj) : error LNK2038: Konflikt ermittelt f³r "RuntimeLibrary": Der Wert "MD_DynamicRelease" stimmt nicht mit dem Wert "MDd_DynamicDebug" in qstring_compat.obj ³berein.
double-conversion.lib(bignum.obj) : error LNK2038: Konflikt ermittelt f³r "_ITERATOR_DEBUG_LEVEL": Der Wert "0" stimmt nicht mit dem Wert "2" in qstring_compat.obj ³berein.
double-conversion.lib(bignum.obj) : error LNK2038: Konflikt ermittelt f³r "RuntimeLibrary": Der Wert "MD_DynamicRelease" stimmt nicht mit dem Wert "MDd_DynamicDebug" in qstring_compat.obj ³berein.
double-conversion.lib(diy-fp.obj) : error LNK2038: Konflikt ermittelt f³r "_ITERATOR_DEBUG_LEVEL": Der Wert "0" stimmt nicht mit dem Wert "2" in qstring_compat.obj ³berein.
double-conversion.lib(diy-fp.obj) : error LNK2038: Konflikt ermittelt f³r "RuntimeLibrary": Der Wert "MD_DynamicRelease" stimmt nicht mit dem Wert "MDd_DynamicDebug" in qstring_compat.obj ³berein.
double-conversion.lib(cached-powers.obj) : error LNK2038: Konflikt ermittelt f³r "_ITERATOR_DEBUG_LEVEL": Der Wert "0" stimmt nicht mit dem Wert "2" in qstring_compat.obj ³berein.
double-conversion.lib(cached-powers.obj) : error LNK2038: Konflikt ermittelt f³r "RuntimeLibrary": Der Wert "MD_DynamicRelease" stimmt nicht mit dem Wert "MDd_DynamicDebug" in qstring_compat.obj ³berein.

I just had a look at the qt tarball and found it already including sources of its dependencies. 
Take a look at qtbase/src/3rdparty

I've already often build qt by hand and have never dealt with adding that dependencies.
Is there a reason the conan package pulls them externaly?

If its build in one go with the included dependencies there shouldn't be a problem.

**Comment by ericLemanissier** [comment]
The point of a package manager is to use external dependencies, not a private copy of everything.
I made a change in branch `multiConfiguration` (https://github.com/bincrafters/conan-qt/tree/multiConfiguration). Can you clone the repository and call `conan create ...`. You should replace ` -s qt:build_type=None` with `-o qt:multiconfiguration=True` ?

**Comment by DirkScharff** [comment]
I just tried the multiconfiguration build and it seems to work. I haven't tried to use it to compile another project yet but the package looks promising. I will give feedback to this as soon as I get to try it (later today or tomorrow I guess).

Although the package is created successfully the included test fails:

> qt/5.12.3@bincrafters/stable (test package): Building with CMake
-- The C compiler identification is MSVC 19.20.27508.1
-- The CXX compiler identification is MSVC 19.20.27508.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.20.27508/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.20.27508/bin/Hostx64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.20.27508/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.20.27508/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:
    CMAKE_EXPORT_NO_PACKAGE_REGISTRY
    CONAN_COMPILER
    CONAN_COMPILER_VERSION
    CONAN_CXX_FLAGS
    CONAN_C_FLAGS
    CONAN_EXPORTED
    CONAN_IN_LOCAL_CACHE
    CONAN_LINK_RUNTIME
-- Build files have been written to: C:/Develop/Projects/qt/test_package/build/6f53852174db98e8c85d72247273c5e9c6887cdc
Microsoft (R)-Build-Engine, Version 16.0.461+g6ff56ef63c für .NET Framework
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.
  Checking Build System
  CMake does not need to re-run because C:/Develop/Projects/qt/test_package/build/6f53852174db98e8c85d72247273c5e9c6887cdc/CMakeFiles/generate.stamp is up-to-date.
  Automatic MOC and UIC for target test_package
  Building Custom Rule C:/Develop/Projects/qt/test_package/CMakeLists.txt
  CMake does not need to re-run because C:/Develop/Projects/qt/test_package/build/6f53852174db98e8c85d72247273c5e9c6887cdc/CMakeFiles/generate.stamp is up-to-date.
  Microsoft (R) C/C++-Optimierungscompiler Version 19.20.27508.1 für x64
  Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.
  cl /c /IC:\Develop\Projects\qt\test_package\build\6f53852174db98e8c85d72247273c5e9c6887cdc /IC:\Develop\Projects\qt\test_package /IC:\Develop\Projects\qt\test_package\build\6f53852174db98e8c85d72247273c5e9c6887cdc\test_package_autogen
  \include_Release /IC:\.conan\a9bab1\1\include /IC:\.conan\a9bab1\1\include\QtCore /I"C:\.conan\a9bab1\1\.\mkspecs\win32-msvc" /W3 /WX- /diagnostics:classic /O2 /Ob2 /D WIN32 /D _WINDOWS /D NDEBUG /D QT_CORE_LIB /D QT_NO_DEBUG /D "CMAK
  E_INTDIR=\"Release\"" /D _MBCS /Gm- /EHsc /MD /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"test_package.dir\Release\\" /Fd"test_package.dir\Release\vc142.pdb" /Gd /TP /errorReport:queue C:\Develop\Projects\qt\test_packa
  ge\build\6f53852174db98e8c85d72247273c5e9c6887cdc\test_package_autogen\mocs_compilation.cpp C:\Develop\Projects\qt\test_package\test_package.cpp
  mocs_compilation.cpp
  test_package.cpp
  Code wird generiert...
  test_package.vcxproj -> C:\Develop\Projects\qt\test_package\build\6f53852174db98e8c85d72247273c5e9c6887cdc\Release\test_package.exe
  Building Custom Rule C:/Develop/Projects/qt/test_package/CMakeLists.txt
  CMake does not need to re-run because C:/Develop/Projects/qt/test_package/build/6f53852174db98e8c85d72247273c5e9c6887cdc/CMakeFiles/generate.stamp is up-to-date.
qt/5.12.3@bincrafters/stable (test package): Running test()
qt/5.12.3@bincrafters/stable (test package): Testing qmake
Der Befehl "qmake_folder\release\test_package" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
ERROR: qt/5.12.3@bincrafters/stable (test package): Error in test() method, line 102
        self._test_with_qmake()
while calling '_test_with_qmake', line 85
        self.run(os.path.join(bin_path, "test_package"), run_environment=True)
        ConanException: Error 1 while executing qmake_folder\release\test_package

**Comment by ericLemanissier** [comment]
I just added a commit to the multiConfiguration branch, which should fix the test recipe. could you try it ?

**Comment by DirkScharff** [comment]
I tested the newer version and it compiles and tests fine. I will try to use the package to compile a real project later this day.
Thanks for the help. Will this option be available in future versions as well?

**Comment by ericLemanissier** [comment]
I'm working on integrating this in the 5.12.3/stable channel

**Comment by ericLemanissier** [comment]
fixed in stable/5.12.3 with https://github.com/bincrafters/conan-qt/commit/2971e49de77711a5a717bdc6559687ae007bcced
