### ISSUE TITLE
freetype/2.9.1 doesn't work on emscripten

### ISSUE THREAD

**Issue by JimmySnails** [bincrafters/community#807]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **freetype/2.9.1**
  * Operating System+version: Debian Stretch
  * Compiler+version: emscripten toolchain compiler
  * Docker image: none ?
  * Conan version: Conan 1.15.0
  * Python version: Python 3.5.3

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Emscripten
arch=asm.js
os_build=Linux
arch_build=x86_64
compiler=clang
compiler.version=6.0
compiler.libcxx=libc++
[options]
[build_requires]
emsdk_installer/1.38.22@bincrafters/stable
[options]
libjpeg-turbo:SIMD = False
sdl2_image:tif = False
```

### Steps to reproduce (Include if Applicable)
Seems there is a problem with finding libpng..

### Logs (Include/Attach if Applicable)
```
CMake Error at /usr/local/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PNG (missing: PNG_LIBRARY PNG_PNG_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.13/Modules/FindPNG.cmake:142 (find_package_handle_standard_args)
  source_subfolder/CMakeLists.txt:173 (find_package)
```

**Comment by SSE4** [comment]
the problem with `find_package`, `find_library` and so on in Emscripten is that CMake toolchain file sets the following:
```
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
```
so it never tries to discover libraries in conan directories.
changing them to `BOTH` fixes the issue.

**Comment by SSE4** [comment]
I think we may fix it in `emsdk_installer` package itself, @JimmySnails WDYT?

**Comment by SSE4** [comment]
fixed in toolchain: https://github.com/bincrafters/conan-emsdk_installer/commit/026be8775a5b9392e1802db729960333646525c0

**Comment by JimmySnails** [comment]
@SSE4 sry for the late reply. I‘ve been really busy. I think fixing it in the toolchain is a very good idea! I‘m going to try it this WE!

Thank you!

**Comment by SSE4** [comment]
@JimmySnails any update?

**Comment by JimmySnails** [comment]
@SSE4 Sry for taking so long... libfreetype does now work!

Now the build is failing for libjpeg turbo.. Should i create a seperate issue for that? 
Here's the log:

```
libjpeg-turbo/1.5.2@bincrafters/stable: Downloaded recipe revision 0
ERROR: libjpeg-turbo/1.5.2@bincrafters/stable: Error in configure() method, line 43
        if self.settings.os == "Emscripten":
        ConanException: Invalid setting 'Emscripten' is not a valid 'settings.os' value.
Possible values are ['Android', 'Arduino', 'FreeBSD', 'Linux', 'Macos', 'SunOS', 'Windows', 'WindowsStore', 'iOS', 'tvOS', 'watchOS']
Read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting"
```

**Comment by Croydon** [comment]
@JimmySnails Please create a separate issue for libjpeg-turbo

Closing as this seems to be fixed
