### ISSUE TITLE
[libcurl] fails to build on Windows

### ISSUE THREAD

**Issue by acgetchell** [bincrafters/community#809]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libcurl/7.56.1**
  * Operating System+version: **Windows 10**
  * Compiler+version: **Visual Studio 2015 & 2017 using clang-cl (clang 8.0.0)**
  * Conan version: **conan 1.15.1**
  * Python version: **Python 2.7.0**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)

Configuration for profile cdt:
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=clang
compiler.version=8
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]
CONAN_CMAKE_GENERATOR=Ninja

https://ci.appveyor.com/project/acgetchell/cdt-plusplus/build/job/os83jt68q1956jho?fullLog=true#L4807

### Steps to reproduce (Include if Applicable)

Use a package like `date/2.4.1@bincrafters/stable` that requires `libcurl`. The build process invokes `autoconf`, which I installed using `msys2`:

https://ci.appveyor.com/project/acgetchell/cdt-plusplus/build/job/dww1wr6j9q3ow99g?fullLog=true#L66

But this recipe doesn't seem to recognize it.

### Logs (Include/Attach if Applicable)

https://ci.appveyor.com/project/acgetchell/cdt-plusplus/build/job/os83jt68q1956jho?fullLog=true#L22030

**Comment by acgetchell** [comment]
From a discussion on the Conan channel in Slack, the recipe should invoke `tools.run_in_windows_bash()`.

**Comment by SSE4** [comment]
@acgetchell applied, please give an another try: https://github.com/bincrafters/conan-libcurl/commit/93b730b770097d96e6edbe8b03236863403f05d4

**Comment by acgetchell** [comment]
autoconf 2.69-5 is installed from msys2:

https://ci.appveyor.com/project/acgetchell/cdt-plusplus/build/job/j0qdhgc5t1ywv2ye?fullLog=true#L65

But not detected:

https://ci.appveyor.com/project/acgetchell/cdt-plusplus/build/job/j0qdhgc5t1ywv2ye?fullLog=true#L22497

**Comment by SSE4** [comment]
@acgetchell it's using Git Bash: `run_in_windows_bash: "C:\Program Files\Git\usr\bin\bash.exe"`
this is not intended, I'll take a look

**Comment by SSE4** [comment]
@acgetchell meanwhile, may you try to se `CONAN_BASH_PATH` environment variable to the right bash instance? it seems like on appveyor, Git prepends MSYS2 in PATH, so conan auto-detects wrong one

**Comment by SSE4** [comment]
I think we have got further with this one, and have https://github.com/conan-community/community/issues/222 to track it, so closing
