### ISSUE TITLE
Upstream Update: libevent 2.1.10

### ISSUE THREAD

**Issue by theirix** [bincrafters/community#811]
### Package Details
  * Package Name: **libevent**
  * Latest available Version: **2.1.10**

New release finally includes CMake build so the #723 can be resolved.

Packaging in progress.

**Comment by uilianries** [comment]
> New release finally includes CMake build so the #723 can be resolved.

Amazing!

**Comment by Croydon** [comment]
Instead of manually filtering builds out, I would rather add more pages to AppVeyor to avoid the timeout 

https://github.com/bincrafters/conan-libevent/commit/b532e0982443872426dd683e9c1cea74c234b215

**Comment by theirix** [comment]
@Croydon good idea, thanks. It explodes appveyor.yml though (builds cannot be auto-distributed to pages).

**Comment by Croydon** [comment]
Yes, but this is certainly the smaller burden :)

**Comment by theirix** [comment]
Almost done, waiting for dependencies on VS2019.

**Comment by Croydon** [comment]
I'm suggesting to either open pull requests for the missing dependencies build or add the builds to libevent nonetheless, ignore the failures for now and merge it anyway

**Comment by theirix** [comment]
Ok, OpenSSL builds are already in the queue so I'll merge anyway after they succeed (hopefully) or fail. I had not tried VS2019 with libevent yet.

**Comment by uilianries** [comment]
OpenSSL failed due connection error.

**Comment by SSE4** [comment]
`stable/2.1.10 was created`, OpenSSL failure disappeared after the restart
for VS2019, I'll add builds to OpenSSL soon (right now our CI is overloaded with boost, OpenCV, etc., so it will take some time)

**Comment by theirix** [comment]
Ok, thanks! Hope it would not require changes in libevent.
