### ISSUE TITLE
[zmq] Does not support MSVC toolset v142 when included

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [bincrafters/community#815]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **zmq/4.3.1**
  * Operating System+version: **Windows 10**
  * Compiler+version: **MSVC 2019**
  * Conan version: **conan 1.15.0**
  * Python version: **Python 3.7.3**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
[settings]
os=Windows
os_build=Windows
arch=x86
arch_build=x86
compiler=Visual Studio
compiler.version=16
compiler.toolset=v142
build_type=Release
[options]
[build_requires]
[env]

### Steps to reproduce (Include if Applicable)
- Require zmq/4.3.1@bincrafters/stable
- Use cmake generator
- conan install .. -build zmq (succeeds)
- This correctly builds the library **libzmq-v142-mt-s-4_3_1.lib**
- **conanbuildinfo.cmake** incorrectly adds set(CONAN_LIBS libzmq-None-mt-s-4_3_1.lib ws2_32 Iphlpapi ${CONAN_LIBS}) **emphasis on the -None-**
- This causes cmake to fail

### Logs (Include/Attach if Applicable)
[cmake] Conan: Adjusting output directories
[cmake] Conan: Using cmake targets configuration
[cmake] Library libzmq-None-mt-s-4_3_1.lib not found in package, might be system one

**Comment by uilianries** [comment]
Hi @Mirko-von-Leipzig !

Thanks for reporting this issue. I'll investigate.

**Comment by SSE4** [comment]
@Mirko-von-Leipzig changes were applied, please give an another try and let us know

**Comment by Mirko-von-Leipzig** [comment]
I've tested and it now works as expected, thanks.
