### ISSUE TITLE
sqlite3: build command line utilty too

### ISSUE THREAD

**Issue by Talkless** [bincrafters/community#816]
[sqlite3](https://github.com/bincrafters/conan-sqlite3) package does not build command line utility, only the library itself. It would be useful to have this tool independent of the fixed version that, for example, Linux distribution provides.

**Comment by SSE4** [comment]
@Talkless feel free to submit PR, it shouldn't be too hard to add this one.

**Comment by Talkless** [comment]
@SSE4 do you believe it is acceptable to make this work in the current package, or it should be separate "tool" package?

**Comment by SSE4** [comment]
@Talkless I think separate one, take a look at `conan-bison` as an example/starting point

**Comment by uilianries** [comment]
Hi @Talkless !

sqlite3 client is available by `sqlite3_installer/3.29.0@bincrafters/stable`

Regards!

**Comment by Talkless** [comment]
> sqlite3 client is available by

Awesome, thanks for noting!
