### ISSUE TITLE
[libpcap] hardcoded dependency on bison-3.0.4 makes it impossible to satisfy the dependency on systems with glibc-2.28+

### ISSUE THREAD

**Issue by Chemrat** [bincrafters/community#817]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libpcap/1.8.1**
  * Operating System+version: **Gentoo/amd64**
  * Compiler+version: **clang-9.0.0**
  * Conan version: **conan 1.15.0**
  * Python version: **Python 3.5.5**

### Conan profile
```
Configuration for profile default-clang:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=clang
compiler.version=9
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
CC=/usr/lib64/llvm/9/bin/clang
CXX=/usr/lib64/llvm/9/bin/clang++
```

### Steps to reproduce (Include if Applicable)
build `bison/3.0.4@bincrafters/stable`

### Logs (Include/Attach if Applicable)
Build fails with
```
lib/fseterr.c:77:3: error: "Please port gnulib fseterr.c to your platform! Look at the definitions of ferror and clearerr on your system, then report this to bug-gnulib."
 #error "Please port gnulib fseterr.c to your platform! Look at the definitions of ferror and clearerr on your system, then report this to bug-gnulib."
```
Seems to be caused by a problem with older bison versions and glibc 2.28 `libio.h` removal

**Comment by SSE4** [comment]
@Chemrat I've applied a fix: https://github.com/bincrafters/conan-libpcap/commit/bb9aad59669e14efdefd2b485f5cdde7eaa31d4e
please give a try and lemme know

**Comment by Chemrat** [comment]
Thanks, that fixed it

**Comment by SSE4** [comment]
confirmed as fixed, closing
