### ISSUE TITLE
[libwebsockets] libwebsockets fails to build with SSL

### ISSUE THREAD

**Issue by RelayrMA** [bincrafters/community#818]
### Package and Environment Details
  * Package Name/Version: **libwebsockets/2.4.0**
  * Operating System+version: **Gentoo 4.19.23**
  * Compiler+version: **gcc-7.3**
  * Conan version: **conan 1.15.2**
  * Python version: **Python 3.6.5**

### Conan profile 
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=7
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]

### Steps to reproduce
I'm trying to build libwebsockets with SSL.
To do this in my conanfile I set ```libwebsockets:lws_with_ssl=True```
Then trying to do conan install I get the following error:
```
ERROR: libwebsockets/2.4.0@bincrafters/stable: Error in requirements() method, line 48
        self.requires.add("OpenSSL/>=1.0.2r@conan/stable")
        InvalidNameException: Value provided for package version, '>=1.0.2r' (type Version), is an invalid name. Valid names MUST begin with a letter, number or underscore, have between 2-51 chars, including letters, numbers, underscore, dot and dash
```

I notice that the responsible commit is
https://github.com/bincrafters/conan-libwebsockets/commit/166690dcb0c16f6ec8e6e7e53337044011506379
Reverting the requirement version to ```[>=1.0.2r]``` makes the package build.

**Comment by uilianries** [comment]
Hi @RelayrMA !

Thanks for reporting and giving the solution. I'll fix ASAP.

**Comment by uilianries** [comment]
Hi @RelayrMA !

I just merged https://github.com/bincrafters/conan-libwebsockets/commit/409754392a5b23951eb03e4c16eca277ac81123c which a fix

Please update your package and try again.

**Comment by RelayrMA** [comment]
It works for me, thanks!
