### ISSUE TITLE
[conan-mongo-c-driver] What is header_path.patch for?

### ISSUE THREAD

**Issue by daravi** [bincrafters/community#819]
What is the purpose for header_path.patch? Is it still needed for the 1.14.0?

**Comment by Croydon** [comment]
It seems to enable static linking which would not be possible without https://github.com/bincrafters/conan-mongo-c-driver/commit/2a4ca8df8dd5f1ad54f77381d91ee8105811d9a9

Reminder for all bincrafters: please document in-code what the respective patches are for

**Comment by DEGoodmanWilson** [comment]
Howdy! My sincerest apologies. Croydon is correct. I plan on taking more time to work on this in the coming weeks. The older versions of the Mongo C Driver are not very flexible when it comes to compiling, and I am considering only supporting newer versions that should be easier to configure. I'll know more when I start digging.

**Comment by daravi** [comment]
Is it for enabling static linking, or for disabling shared library in case we only want static?

I recreated the patch for the latest release but issue still persists. If the patch only enables control over shared lib installation maybe we should consider not having it just to make life easier when updating the recipe. In any case I can open a PR for the updated recipe and patch if you want.

**Comment by SSE4** [comment]
this patch only controls installation of libraries. e.g. in case of static build, shared libraries are still installed, as well as some pkg-config files which aren't useful in case of static build.
I think it's not needed to update the patch. instead, we may just delete unwanted stuff in `package_info` (we already do the same for many other use-cases). patch is very large and it's hard to maintain it, so I'd prefer to avoid it.
I am closing this issue for now, as question about patch was answered.
if you want to update patch, I think it makes sense to open the issue in upstream repository and submit patch to them, so it's possible to build/install static without building shared libraries.
