### ISSUE TITLE
Minor refactoring of conan-sdl2 recipe

### ISSUE THREAD

**Issue by solvingj** [bincrafters/community#82]
Have the following questions for the author about this recipe:

Can we do this some other way without calling `Super()` ? It is an unusual technique, I've never seen it used, and it's not immediately clear to a reader what the goal/effect would be.  
https://github.com/bincrafters/conan-sdl2/blob/testing/2.0.7/conanfile.py#L57

What scenario does this situation address? It's checking for `settings.os==x86` but then `tools.detected_architecture()==x86_64`, and then setting a path of `i386`.  It's obscure and looks like a patch to a wierd bug, hard to guess.  If it's correct and necessary, would like to put a comment: 
https://github.com/bincrafters/conan-sdl2/blob/testing/2.0.7/conanfile.py#L162

The settings of flags should now be unnecessary, as they are now set by the helpers per @memsharded:  
example: `cmake.definitions['CMAKE_C_FLAGS'] = '-m32'`

https://github.com/bincrafters/conan-sdl2/blob/testing/2.0.7/conanfile.py#L160

If so, can we remove?

**Comment by solvingj** [comment]
Should this not be passed in a CMake toolchain file?  https://cmake.org/cmake/help/v3.10/variable/CMAKE_TOOLCHAIN_FILE.html

**Comment by SSE4** [comment]
yep, that will work as well

**Comment by lasote** [comment]
About the toolchain, I wouldn't do it, you would be removing the possibility of using a toolchain to cross build something or whatever. Remeber, there is a CONAN_CMAKE_TOOLCHAIN_FILE to inject toolchains.

**Comment by lasote** [comment]
We would need you to open an issue in the Conan repository explaining all this, thanks!

**Comment by solvingj** [comment]
@lasote should just keep copying this code to all the recipe's where it is relevant? 

```
        if self.settings.os == 'Linux':
            if self.settings.arch == 'x86':
                cmake.definitions['CMAKE_C_FLAGS'] = '-m32'
                cmake.definitions['CMAKE_CXX_FLAGS'] = '-m32'
            elif self.settings.arch == 'x86_64':
                cmake.definitions['CMAKE_C_FLAGS'] = '-m64'
                cmake.definitions['CMAKE_CXX_FLAGS'] = '-m64'
```

Also, I think the suggestion to look into using a toolchain file actually implies looking into how CONAN_CMAKE_TOOLCHAIN_FILE is implemented and exploring our options around enhancing it.  Basic logic might be something like:  

1.  If there were no toolchain file injected, the CMakeHelper should generate one and inject it for these kinds of options. 
2.  If there is a toolchainfile injected, amend it somehow.  Does it support `include()`?  If so, we can `include()` the user-injected toolchain file in our own generated one.  I'd just like to explore it. 

The existing implementation of toolchain file seems trivial, so enhancement should be easy: 
https://github.com/conan-io/conan/pull/1491/files

Also, as this thread indicates, the toolchain file can be used for many different Cmake things, including things like `FindProgram` and `FindPackage`.   I would like to explore doing `conan_basic_setup()` this way as well.  We still have annoying problems with some third-party CMake libraries.   We should open a separate ticket for this topic.

**Comment by solvingj** [comment]
@SSE4 can this be closed now?

**Comment by SSE4** [comment]
closing as feature implemented in conan codebase, workaround removed from sdl2 recipe
