### ISSUE TITLE
qt/5.12.2 Fails to install on Windows on first attempt but works on second attempt

### ISSUE THREAD

**Issue by tjwrona1992** [bincrafters/community#821]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.12.2**
  * Operating System+version: **Windows 10**
  * Compiler+version: **Visual Studio 2019 Preview**
  * Conan version: **conan 1.15.1**
  * Python version: **Python 3.7.1**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
    C:\WINDOWS\system32>conan profile show default
    Configuration for profile default:

    [settings]
    os=Windows
    os_build=Windows
     arch=x86_64
    arch_build=x86_64
    compiler=Visual Studio
    compiler.version=16
    build_type=Release
    [options]
    [build_requires]
    [env]

### Steps to reproduce (Include if Applicable)
Attempt to use the qt/5.12.2 package in a project by adding it to conanfile.txt

I am using cmake-conan to run the conan install during CMake generation: https://github.com/conan-io/cmake-conan

Upon CMake generation it will attempt to install Qt and start installing all of the prerequisites. Somewhere about half way through the install fails and it lists some errors (that I unfortunately didn't think to capture before I tried running CMake generation a second time) After running CMake generation a second time it succeeds and the install works.

This happened to me with both the Debug and Release configurations.

### Logs (Include/Attach if Applicable)
The previous log where it failed to build is now lost, but I have cleared my Conan data and installed the package a couple times and it seems to fail on the first install every time. I will try clearing the Conan data again once I have more time and see if I can get the exact log message.

**Comment by tjwrona1992** [comment]
[Output-CMake.txt](https://github.com/bincrafters/community/files/3249997/Output-CMake.txt)

I removed all of my Conan packages and tried a fresh install (In Debug configuration) and it failed. I saved the log this time and attached it.

After seeing this error if I try to install it again it succeeds.

**Comment by ericLemanissier** [comment]
thanks. Could you please send the log of the second run too ?

**Comment by tjwrona1992** [comment]
I'll have to try again when I get home. I'll probably have to remove the
whole thing again and start from scratch to get a clean log haha. Qt takes
a while to install so I'm not sure if I'll have time tonight or not.

**Comment by tjwrona1992** [comment]
[Output-CMake.txt](https://github.com/bincrafters/community/files/3259765/Output-CMake.txt)
[Output-CMake-success.txt](https://github.com/bincrafters/community/files/3259766/Output-CMake-success.txt)

I have attached both the failure log and the success log. Thank you for looking further into this,

**Comment by tjwrona1992** [comment]
I will look into 5.12.3 in the next day or 2 and see if I can get that to build successfully

**Comment by ericLemanissier** [comment]
Thanks. It gives a clearer view of the problem. The first run of the script starts with the following, whereas the second does not have have these line.:
```
1> [CMake] -- The CXX compiler identification is MSVC 19.22.27706.1
1> [CMake] -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Preview/VC/Tools/MSVC/14.22.27706/bin/HostX64/x64/cl.exe
1> [CMake] -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Preview/VC/Tools/MSVC/14.22.27706/bin/HostX64/x64/cl.exe -- works
1> [CMake] -- Detecting CXX compiler ABI info
1> [CMake] -- Detecting CXX compiler ABI info - done
1> [CMake] -- Detecting CXX compile features
1> [CMake] -- Detecting CXX compile features - done
1> [CMake] -- Downloading conan.cmake from https://github.com/conan-io/cmake-conan
```
The consequence is that CXX variable is set to "C:/Program Files (x86)/Microsoft Visual Studio/2019/Preview/VC/Tools/MSVC/14.22.27706/bin/HostX64/x64/cl.exe" in the first case, and not in the second, ending up crashing qmake because it does not handle spaces in the compiler path.
In the second run, qmake simply uses the default "cl.exe". I don't know conan.cmake, is the a reason why `CXX` variable is set only in the first run ? Is cl.exe available in path for the 1st or 2nd run ?

**Comment by tjwrona1992** [comment]
I don't really fully understand the inner workings of the "conan.cmake" script, but it comes from here: https://github.com/conan-io/cmake-conan

It seems to autodetect a lot of settings for you and allows you to run the conan install directly from CMake so it isn't a separate step.

**Comment by tjwrona1992** [comment]
This may be a bug with that script and not the package. I will try to look further into it, but to be honest the script reads a little like Egyptian to me so I'm not sure how far I'll get haha

**Comment by ericLemanissier** [comment]
Actually, the issue probably does not come from conan.cmake script, because the differences in the log happen before downloading it. Could you please send us your CMakeLists.txt file, and the command you use to invoke it ?
