### ISSUE TITLE
[conan-pcre2] cmake_minimum_required missing

### ISSUE THREAD

**Issue by ManuelMeraz** [bincrafters/community#822]
Description

CMake configuration step fails when using the Android cmake toolchain file:

CMake Error in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.10)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".

Passing -Wno-dev has no effect.
Package Details

    Package Name/Version: pcre2/10.32
    Operating System: Linux Ubuntu 18.04
    Compiler+version: Android NDK r19b clang 8.0

This is basically just a clone of the following:
https://github.com/bincrafters/community/issues/471

**Comment by Croydon** [comment]
Merged, thanks!
