### ISSUE TITLE
Upstream Update: ruby_installer 2.5.5

### ISSUE THREAD

**Issue by jmarrec** [bincrafters/community#824]
### Package Details
  * Package Name: **ruby_installer**
  * Latest available Version: **2.5.5**

The above mentioned version is newly released by the upstream project and not yet available within Bincrafters. Please add this version.

cf: https://github.com/oneclick/rubyinstaller2/releases/tag/RubyInstaller-2.5.5-1

**Comment by uilianries** [comment]
Hi @jmarrec !

Both 2.5.5 and 2.6.3 are available for download:

https://bintray.com/bincrafters/public-conan/ruby_installer%3Abincrafters/2.5.5%3Astable
https://bintray.com/bincrafters/public-conan/ruby_installer%3Abincrafters/2.6.3%3Astable

Regards!

**Comment by jmarrec** [comment]
@uilianres I had made a 2.5.5 branch already thinking you'd just create the branch to welcome PRs, but making these two available in one go is even better!

Thanks for the real quick turnaround too!
