### ISSUE TITLE
lzma/5.2.4 requires Windows SDK 10.0.15063.0 to build

### ISSUE THREAD

**Issue by lefticus** [bincrafters/community#827]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **lzma/5.2.4**
  * Operating System+version: **Windows 10**
  * Compiler+version: **MSVC 2019**
  * Conan version: **conan 1.16.0**

### Steps to reproduce (Include if Applicable)

Building lzma with MSVC fails if the specific SDK 10.0.15063.0 is not installed.

It seems the winsdk_version needs to be updated to the current SDK with the MSBuild command

**Comment by SSE4** [comment]
applied: https://github.com/bincrafters/conan-lzma/commit/17136882e5649b002280d936ebceec9727b40bbf

**Comment by SSE4** [comment]
I am closing this, as fix was applied, and it builds fine for VS 2019 on appveyor.
