### ISSUE TITLE
how to create my conan package which based on the existing package, such as poco?

### ISSUE THREAD

**Issue by richardor** [bincrafters/community#83]
Hi, @solvingj 
For code reuse purpose. I had coded a project based on conan-poco.  I don't know how to upload the project to artifactory.
Does there any demo used bincrafters-package-tools ?
thank you

**Comment by uilianries** [comment]
What do you mean when you say based on conan-poco? Did you fork conan-poco and changed the recipe?

To upload the package to artifactory, you need to obtain your Conan server address and add a new remote to your client:

`conan remote add artifactory http://localhost:9300`

After that, you just need to upload by command: 

`conan upload -r artifactory --all conan-poco/1.8.1@richardor/stable`

Of course, you could use Bincrafters package tools for that. It works like a wrapper for Conan package tools. So, you just need to set `CONAN_UPLOAD`.

To read more how to upload packages using Conan package tools: https://github.com/conan-io/conan-package-tools#upload-packages
To obtain more information about Conan + Artifactory: https://www.jfrog.com/confluence/display/RTF/Conan+Repositories

**Comment by solvingj** [comment]
@richardor i know you are now on slack, so please raise this topic for discussion there, as it seems like we need a lot of Q&A to determine what you're trying to accomplish.
