### ISSUE TITLE
Error while Creating harfbuzz package: Could NOT find Freetype

### ISSUE THREAD

**Issue by Zohratl** [bincrafters/community#830]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **harfbuzz/2.4.0**
  * Operating System+version: **Ubuntu 18.04.2 LTS**
  * Compiler+version: **gcc-7.3**
  * Conan version: **Conan version 1.11.2**
  * Python version: **Python 2.7.15rc1**

### Question Description
When I try to create Harfbuzz package for my Yocto Apalis using this command:
`conan create -k -pr yocto-apalis harfbuzz MyProject/testing`
I get this Error:
```
-- Could NOT find Freetype (missing:  FREETYPE_LIBRARY FREETYPE_INCLUDE_DIRS) 
    CMake Error at source_subfolder/CMakeLists.txt:265 (message):
    HB_HAVE_FREETYPE was set, but we failed to find it.  Maybe add a
    CMAKE_PREFIX_PATH= to your Freetype2 install prefix
```
Even though I have already created a Freetype Package.

yocto-apalis profile settings:
```
[settings]
os=Linux
os_build=Linux
os_target=Linux
arch=armv7
arch_build=x86_64
arch_target=armv7
compiler=gcc
compiler.version=7.3
compiler.libcxx=libstdc++
build_type=Release
toolchain=yocto
toolchain.name=poky-glibc-x86_64-core-image-full-cmdline-cortexa9hf-neon-toolchain-2.4.2-apalis-imx6.sh
toolchain.api_level=201808290900
```

Any hints?

**Comment by SSE4** [comment]
@Zohratl may you provide full log?

**Comment by uilianries** [comment]
@Zohratl I have no problem when building for x86 and x86_64, It's something related to your profile. Did you try set FREETYPE_LIBRARY and FREETYPE_INCLUDE_DIRS?

Also, harfbuzz is using ragel from APT, is it a problem for your profile? I just provided a new PR with ragel as a build requirement: https://github.com/bincrafters/conan-harfbuzz/pull/15
