### ISSUE TITLE
[libpq/10.4] Visual Studion support

### ISSUE THREAD

**Issue by Talkless** [bincrafters/community#834]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libpq/10.4**
  * Operating System+version: **Windows**
  * Compiler+version: **Visual Studio 2015 14.0**

### Description of your feature

I've noticed that libpq package no longer support building with Visual Studio since libpq 10.4 https://github.com/bincrafters/conan-libpq/blob/435277bc0fbd9f35ed2b8d30243aca0b88d33354/conanfile.py#L37

What was the reason for it? Is PostgreSQL >=10 source changes makes it too hard to make it work, or.. it's simply the lack of contributors for maintaining VS build?

Ping @uilianries 

**EDIT:** or maybe it did not worked earlier too, maybe it's that the warning added later for clarity...

**Comment by uilianries** [comment]
Hi @Talkless !

It's possible to libpq on Visual Studio, but we need a port. I'll provide one ASAP

**Comment by Talkless** [comment]
That would be amazing @uilianries !

**Comment by uilianries** [comment]
@Talkless the next revision contains Visual Studio support

Please, wait some time until our CI complete all jobs:

https://ci.appveyor.com/project/bincrafters/conan-libpq

After that, give a try.

https://github.com/bincrafters/conan-libpq/commit/e023cfe76e73a703a202f792bec1633a44a2c45f
