### ISSUE TITLE
libuv MinGW support

### ISSUE THREAD

**Issue by sourcedelica** [bincrafters/community#835]
### Package and Environment Details 
  * Package Name/Version: **libuv/1.27.0**

### Description of your feature
Add MinGW support.

I am in the process of [creating a recipe](https://github.com/sourcedelica/conan-cassandra) for the [Cassandra driver](https://github.com/sourcedelica/conan-cassandra).   I've got most of it completed but I want to include MinGW support.  The recipe depends on `libuv` and it looks like to get the Cassandra recipe working on MinGW the `libuv` recipe will also need to support MinGW.  

I may try to implement this though I'm not familiar with Ninja yet, and if it will be amenable to the usual `tools.replace_in_file` tricks that are so handy for getting CMake builds to work on MinGW.

**Comment by SSE4** [comment]
@uilianries is it something you can take a look into?

**Comment by uilianries** [comment]
I'm not a Mingw expert but I'll take a look

**Comment by uilianries** [comment]
I just added mingw and other new compilers as MSVC16 and GCC9. I'll need to wait for Appveyor.

**Comment by sourcedelica** [comment]
Awesome!  thanks!
