### ISSUE TITLE
Website: Add package list

### ISSUE THREAD

**Issue by uilianries** [bincrafters/community#839]
Hi!

My idea is create a simple page listing all conan packages provided by us.

The link may point to github address. e.g: 
[libpng](https://github.com/bincrafters/conan-libpng)
[zstd](https://github.com/bincrafters/conan-zstd)

I'm not a ruby guy, but I think that should be easy to execute this issue.

**Comment by Croydon** [comment]
I don't think we actually need another list for this.

Search on either GitHub or Bintray should be good enough. WDYT @uilianries and @SSE4?

**Comment by uilianries** [comment]
@Croydon I have to agree, we already have `conan search`, github and bintray. An extra list it would more work to be maintained. I think we could close this issue.
