### ISSUE TITLE
[wxWidgets] Segmentation fault when opening dialogs on Fedora 30

### ISSUE THREAD

**Issue by MB3hel** [bincrafters/community#841]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **wxwidgets/3.1.2@bincrafters/stable and wxwidgets/3.1.1@bincrafters/stable**
  * Operating System+version: **Linux Fedora 30**
  * Compiler+version: **gcc-9.1.1**
  * Conan version: **conan 1.16.0**
  * Python version: **Python 3.7.3**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
- Install dependencies (not automatic on non-apt systems)
`sudo dnf install libX11-devel libSM-devel gtk2-devel libsecret-devel mesa-libGL-devel libdrm-devel libsoup-devel cairo-devel`
- Build the attached project on Fedora 30 (run `make all`). Run the resulting executable and click either of the File menu options. The program will segfault. This does not occur with the same project on Ubuntu 18.04 nor on Ubuntu 16.04. 
- The project can be build without using conan for wxWidgets (instead using packages from https://wiki.codelite.org/pmwiki.php/Main/WxWidgets31Binaries#toc3) with `make noconan`. When built with the non-conan libraries the segfault does not occur. 

### Logs (Include/Attach if Applicable)
Valgrind output (conan build)
EDIT: Attached now instead of in post
[valgrind_output.txt](https://github.com/bincrafters/community/files/3341362/valgrind_output.txt)

**Comment by MB3hel** [comment]
The example
[MinExample.zip](https://github.com/bincrafters/community/files/3330449/MinExample.zip)

**Comment by SSE4** [comment]
wow, thanks for the reporting, I'll try to debug this

**Comment by MB3hel** [comment]
I don't know if it helps or not, but I have not been able to replicate this issue on Ubuntu 19.04 nor on Manjaro 18.0.4. It seems to only affect Fedora.

I'll try setting up a Fedora VM on a different PC, just to make sure it is not something strange going on with one specific Fedora install.

**Comment by MB3hel** [comment]
This also occurs on a VM (different PC entirely). Looks like a Fedora (or maybe a Fedora 30) specific issue.

**Comment by MB3hel** [comment]
If it helps these are all the configurations I tested so far. The default conan profile was used in each case with the only modification being to the `compiler.libcxx` setting. For all GCC tests this was changed to `libstdc++11` and for the clang test on Fedora 30 `libc++` was used (packages installed for clang: `clang llvm lldb libcxx*`)

| Distro         | Compiler    | Issue Occurs (with conan package) |
|----------------|-------------|-----------------------------------|
| Ubuntu 16.04   | GCC 5.4.0   | No                                |
| Ubuntu 18.04   | GCC 7.4.0   | No                                |
| Ubuntu 19.04   | GCC 8.3.0   | No                                |
| Ubuntu 19.04   | GCC 9.1.0   | No                                |
| Manjaro 18.0.4 | GCC 8.3.0   | No                                |
| Fedora 29      | GCC 8.3.1   | No                                |
| Fedora 30      | GCC 9.1.1   | Yes                               |
| Fedora 30      | Clang 8.0.0 | Yes                               |

**Comment by SSE4** [comment]
seems like conflict of two libpng instances/versions - one is from conan and used by wxWidgets itself, and one is from system and loaded by GTK installation.
some notes on it: https://trac.wxwidgets.org/ticket/14157

**Comment by SSE4** [comment]
added an option for custom API prefix for `libpng`: https://github.com/bincrafters/conan-libpng/commit/d503358fbc53807f02ef8e65fea36bb6e6b87539
might be used as: `libpng:api_prefix=wx` to make all API functions private

**Comment by MB3hel** [comment]
Great! Thanks. That fixes the problem. It would be good though to merge that option into the stable branch of libpng (as long as it won't break anything else?) as the wxwidgets package requires libpng/stable. Thanks for the fix!

**Comment by SSE4** [comment]
yeah, I'll merge it as soon as testing passes CI (it might be tomorrow, as CI is currently pretty packed). I'll let you know

**Comment by SSE4** [comment]
@MB3hel changes are in stable branch now

**Comment by MB3hel** [comment]
Everything works. Thanks.
