### ISSUE TITLE
cpprestsdk/2.10.13 cross compile from macOS to Android failed

### ISSUE THREAD

**Issue by dmn-star** [bincrafters/community#843]
### Description of Problem, Request, or Question
conan install failed with error ConanException: replace_in_file didn't find pattern 'find_host_package' in 'source_subfolder/Release/cmake/cpprest_find_boost.cmake' file.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **cpprestsdk/2.10.13@bincrafters/stable**
  * Operating System+version: **macOS Mojave 10.14.5**
  * Compiler+version: **NDK r20 clang (8?)**
  * Conan version: **Conan 1.16.1**
  * Python version: **Python 2.7.10**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
[settings]
os_build=Macos
arch_build=x86_64

compiler=clang
compiler.version=8
compiler.libcxx=libc++
os=Android
os.api_level=21
arch=armv7
build_type=Release

[build_requires]
android_ndk_installer/r20@bincrafters/stable

### Steps to reproduce (Include if Applicable)
Install & cross build cpprestsdk with custom profile

### Logs (Include/Attach if Applicable)
ERROR: cpprestsdk/2.10.13@bincrafters/stable: Error in source() method, line 81
	tools.replace_in_file(path.join(self._source_subfolder, 'Release', 'cmake', 'cpprest_find_boost.cmake'), 'find_host_package', 'find_package')
	ConanException: replace_in_file didn't find pattern 'find_host_package' in 'source_subfolder/Release/cmake/cpprest_find_boost.cmake' file.

**Comment by SSE4** [comment]
thanks, applied: https://github.com/bincrafters/conan-cpprestsdk/commit/c2bf03e8e49ea61248ea088aa41e2180d9cdfb0e

**Comment by dmn-star** [comment]
Thanks!
