### ISSUE TITLE
cpprestsdk/2.10.13 Android Conan adds -lpthread if build from terminal

### ISSUE THREAD

**Issue by dmn-star** [bincrafters/community#845]
### Description of Problem, Request, or Question
Conan adds -lpthread for Android if build from terminal => Mobile App linking failed

The android libc, bionic, provides built-in support for pthreads, so no additional linking (-lpthreads) is necessary. 
So not required to add -lpthreads and remove check also.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **cpprestsdk/2.10.13@bincrafters/stable**
  * Operating System+version: **macOS Mojave 10.14.5**
  * Compiler+version: **NDK r20 clang (8?)**
  * Conan version: **Conan 1.16.1**
  * Python version: **Python 2.7.10**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
[settings]
os_build=Macos
arch_build=x86_64

compiler=clang
compiler.version=8
compiler.libcxx=libc++
os=Android
os.api_level=21
arch=armv7
build_type=Release

[build_requires]
android_ndk_installer/r20@bincrafters/stable

### Steps to reproduce (Include if Applicable)
Install & cross build cpprestsdk with custom profile

**Comment by SSE4** [comment]
yeah I also noticed that, but it seems to be coming from dependencies, I need to check from which one

**Comment by dmn-star-home** [comment]
I think it comes from boost.

**Comment by dmn-star-home** [comment]
Ok. I've recompiled cpprestsdk and found  this in conanbuildinfo.cmake
set(CONAN_LIBS_BOOST_CYCLE_GROUP_C **pthread**)
...

set(CONAN_LIBS cpprest xml2 ssl crypto boost_random iconv boost_coroutine boost_date_time boost_context boost_thread **pthread** z boost_chrono boost_filesystem boost_math_c99l boost_math_tr1 boost_math_c99f boost_math_tr1l boost_math_c99 boost_math_tr1f bz2 lzma zstd boost_system boost_atomic boost_exception boost_regex boost_container ${CONAN_LIBS})

**Comment by dmn-star-home** [comment]
I've compiled **boost**  (boost/1.69.0@conan/stable) only. There's **no**  pthread in  conanbuildinfo.cmake. It's confusing.

**Comment by dmn-star-home** [comment]
So I've understood the difference now.  The  **boost** (boost/1.69.0@conan/stable) package is monolithic one, cpprestsdk uses the modular Boost packages.
From conan-cpprestsdk/conanfile.py
...
        self.requires.add("boost_random/1.69.0@bincrafters/stable")
        self.requires.add("boost_system/1.69.0@bincrafters/stable")
        self.requires.add("boost_thread/1.69.0@bincrafters/stable")
...

And the problem is   **boost_cycle_group_c**/1.69.0@bincrafters/stable. 
From  boost_cycle_group_c/conanfile.py
...
    def package_info_additional(self):
        if self.settings.os != "Windows":
            self.cpp_info.libs.append("pthread")
____

@SSE4 Do you want to try boost (boost/1.69.0@conan/stable) package only as cpprestsdk dependency?

**Comment by SSE4** [comment]
yes, that's the plan. I want to switch to non-modular boost (actually, 1.70). I'll do it and let you know.

**Comment by dmn-star-home** [comment]
Ok. That sounds really good. I tried non-modular boost by tweaking conanfile.py and my app is working now.  #844 is gone too! And last but not least the annoying slow downloads of little boost_* packages are also away.

**Comment by SSE4** [comment]
@dmn-star  update: there are some problems with switch to non-modular boost, specifically, the error is:
```
/usr/bin/ld: bin/test_package: hidden symbol `pthread_atfork' in /usr/lib32/libpthread_nonshared.a(pthread_atfork.oS) is referenced by DSO
```
https://travis-ci.com/bincrafters/conan-cpprestsdk/jobs/212686371
I'll try to find solution and let you know

**Comment by dmn-star-home** [comment]
May be this can [help]( http://ryanarn.blogspot.com/2011/07/curious-case-of-pthreadatfork-on.html?showComment=1539010570329#c7142395566229023001). See the last reply.

OpenSSL already fixed the similar issue https://github.com/openssl/openssl/issues/3884

**Comment by SSE4** [comment]
for the record, fixes:
https://github.com/nginx/nginx/commit/90ca1071b77b0fbb4373ae052b1242023295513f
https://github.com/openssl/openssl/pull/5135/files
https://github.com/openssl/openssl/pull/5134/files
(adding `-pthread` or `-lpthread`)

**Comment by dmn-star** [comment]
Ok. But you  added pthread already. 
>> if self.settings.os == "Linux":
   self.cpp_info.libs.append("pthread")<<

@SSE4 Would you upload cpprestsdk/2.10.13@bincrafters/**testing** to bincrafters?

**Comment by SSE4** [comment]
not yet, `pthread_atfork` problem still persists, I am investigating

**Comment by SSE4** [comment]
okay, seems like I have found a problem - CppRestSDK CMake didn't use `-lpthread` when building `libcpprestsdk.so`, fixed it

**Comment by dmn-star** [comment]
Nice. Ready to upload now? 

Your CI seems to be missing something like this "conan install --build=missing.."

**Comment by SSE4** [comment]
@dmn-star yeah, now it's ready, I've fixed some other things, but going to merge to the stable right away

**Comment by SSE4** [comment]
@dmn-star I think it's done now, changes are in stable, could you possibly give an another try and lemme know?

**Comment by dmn-star** [comment]
@SSE4 Yes of course.  I'll try it tomorrow.

**Comment by dmn-star** [comment]
I can compile cpprestsdk for Android now. Thank you very much @SSE4! But i can't link it with my app. 

Conan: Using cmake Targets configuration
All libs are found.

CMake Error at /Users/dmn-star/dev/app_ndk20/cmake/android/CMakeLists.txt:822 (add_library):
  Target "test_app" links to target "CONAN_PKG::cpprestsdk," but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?

**Comment by dmn-star** [comment]
I found the "problem".  I made target link libraries as _comma_ separated list. I close this issue.
