### ISSUE TITLE
android_ndk_installer/r20 dont adds the ndk cmake to path

### ISSUE THREAD

**Issue by dmn-star** [bincrafters/community#846]
### Description of Problem, Request, or Question
android_ndk_installer/r20@bincrafters/stable dont adds the ndk cmake to path. Build failed if no additional cmake installed.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **cpprestsdk/2.10.13@bincrafters/stable**
  * Operating System+version: **macOS Mojave 10.14.5**
  * Compiler+version: **NDK r20 clang (8?)**
  * Conan version: **Conan 1.16.1**
  * Python version: **Python 2.7.10**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
[settings]
os_build=Macos
arch_build=x86_64

compiler=clang
compiler.version=8
compiler.libcxx=libc++
os=Android
os.api_level=21
arch=armv7
build_type=Release

[build_requires]
android_ndk_installer/r20@bincrafters/stable

### Steps to reproduce (Include if Applicable)
Install & cross build cpprestsdk with custom profile  No another cmake installed.

**Comment by SSE4** [comment]
CMake is not part of Android NDK - it's distributed as part of Android SDK, which is a different thing. see also https://developer.android.com/studio/projects/add-native-code.
therefore, `android_ndk_installer` cannot know about this CMake installation, and the path to the CMake executable.
you have to add path to the CMake executable into your profile, for instance:
```
[env]
CONAN_CMAKE_PROGRAM=/home/someuser/android-sdk/bin/cmake
```
or whatever is valid path to the CMake executable in your case.

**Comment by dmn-star-home** [comment]
Thank you for clarifying. I'll try cmake_installer (https://github.com/conan-community/conan-cmake-installer) for our ci build.    If you can please close this issue. If not, I'll  (dmn-star) close this in 2-3 weeks.

**Comment by SSE4** [comment]
I am closing for now. please re-open or open a new one, if needed
