### ISSUE TITLE
compiler.cppstd subsetting is missing

### ISSUE THREAD

**Issue by Hbkhan** [bincrafters/community#847]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **conan-lzma**
  * Package Name/Version: **conan-libelf**
  * Package Name/Version: **conan-libxml2**

### Description of your feature

Since the new release, 'cppstd' is deprecated in favor of 'compiler.cppstd' and we are using  ( conan-lzma, conan-libelf, conan-libxml2 ) as upstream packages and these packages aren't using the new `compiler.cppstd` subsetting.

So we wanted to go with the new changes to use compiler.cppstd. Since Pure C packages often remove the compiler.libcxx setting the same thing we wanted to do with compiler.cppstd:

```diff
    def configure(self):
        del self.settings.compiler.libcxx
+       del self.settings.compiler.cppstd
```

This is further discussed in [Conan Documentation](https://docs.conan.io/en/latest/reference/conanfile/methods.html#configure-config-options)

> You can also restrict the settings used deleting any specific one. For example, it is quite common for C libraries to delete the `compiler.libcxx` and `compiler.cppstd` as your library does not depend on any C++ standard library

**Comment by SSE4** [comment]
@uilianries @Croydon do you think if it's worth to add to either `conan-templates` or `bincrafters-conventions`?

**Comment by uilianries** [comment]
It sounds legit ... Also I can check more pure_c using some script

**Comment by Croydon** [comment]
Since we don't have explicit templates for C-only builds I don't see how we could add this to our templates

However, I guess we could introduce a check in bincrafters-conventions. 

I guess there is _**NEVER**_ a scenario in which a C-only build wants to have the `compiler.cppstd` setting? If so, we could try to automate the adding of it. 

How could we detect C-only packages in a reliable way? I believe we have packages which are, depending on setting, **sometimes** C-only, but not always 🤔

**Comment by SSE4** [comment]
conan-center hook currently scans for C++ source files (like .cpp, .cxx, .cc, .hpp, etc.), it's not reliable, but still better than nothing
and yes, there are packages where you can conditionally enable/disable C++ wrappers

**Comment by uilianries** [comment]
As we need to check which files are in the source folder, the only option that I see is by hooks. 

Also, we could create a C template for conan-templates.

**Comment by SSE4** [comment]
encountered here: https://travis-ci.org/conan-community/conan-boost/builds/573745726
```
bzip2/1.0.8@conan/stable: WARN: Can't find a 'bzip2/1.0.8@conan/stable' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=Debug, compiler=apple-clang, compiler.cppstd=11, compiler.version=10.0, os=Macos
- Options: build_executable=True, fPIC=True, shared=False
- Dependencies: 
- Package ID: f21c01d705c0cb6ba7aec4679e155a8a3ebf7edf
```
going to add removal of cppstd into `zlib` and `bzip2`

**Comment by Croydon** [comment]
I will add an automated convention update for this
