### ISSUE TITLE
[variant] -std=c++11 flag set in conanfile.py propagates into entire project

### ISSUE THREAD

**Issue by jmatzen** [bincrafters/community#848]
### Package and Environment Details (include every applicable attribute)
  * variant/1.3.0 
  * Windows 10
  * VS2019
  * conan 1.16.1
  * python 3.6.3
  * cmake 3.14.5

When including this dependency, a -std=c++11 flag gets included in the [cppflags] and [cxxflags] sections of `conanbuildinfo.txt` which causes the flag to be used in every project in the solution:

```
[cppflags]
-std=c++11

[cxxflags]
-std=c++11
```

The offending code is:
```
def package_info(self):
        self.cpp_info.cppflags = ["-std=c++11", ]
```

https://github.com/bincrafters/conan-variant/blob/testing/1.3.0/conanfile.py

**Comment by SSE4** [comment]
thanks, applied: https://github.com/bincrafters/conan-variant/commit/8fb7eead32db64ee7e990a4ade014d2783f70790#diff-2b1d42f71f22b7ea0412d7602dec166f

**Comment by SSE4** [comment]
I am closing as fix was applied
