### ISSUE TITLE
[icu] 64.2 fails to build with MSVC and data_packaging=library

### ISSUE THREAD

**Issue by annulen** [bincrafters/community#849]
I'm building ICU package in AppVeyour. For 64.2, when MSVC 2015 or 2017 is used, build always fails with something like
```
icu/64.2@qtproject/stable: Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384
icu/64.2@qtproject/stable: Copyright (C) Microsoft Corporation.  All rights reserved.
icu/64.2@qtproject/stable: 
icu/64.2@qtproject/stable: fatal error RC1109: error creating out/tmp/icudata.res
icu/64.2@qtproject/stable: make[1]: *** [Makefile:230: out/tmp/icudata.res] Error 1
icu/64.2@qtproject/stable: make[1]: *** Waiting for unfinished jobs....
```

At the same time, 63.2 builds successfully. I've tried reverting bincrafters/conan-icu@8cc8404cf58dec35b8dbbbd26efbdcf051ce684c and bincrafters/conan-icu@0c0a41823b8890717aae38577fc9dd22afa01bb3 (independently), this does not help

**Comment by SSE4** [comment]
seems to be known issue: https://unicode-org.atlassian.net/browse/ICU-20531
added workaround: https://github.com/bincrafters/conan-icu/pull/21/commits/6f1522891dbc9121f2c8ee88c59def8b09b64af0

**Comment by annulen** [comment]
Thanks, it works! However, you've accidentally pushed a fix into my unrelated PR

**Comment by SSE4** [comment]
@annulen yeah, now it's in proper branch, so I am closing the issue as fixed.
