### ISSUE TITLE
Is it possible to specify platform-specific requirements?

### ISSUE THREAD

**Issue by wouterbeek** [bincrafters/community#850]
### Package and Environment Details
  * Package Name/Version: **winflexbison/2.5.18**
  * Compiler+version: **gcc-9.1**
  * Conan version: **Conan 1.16.1**
  * Python version: **Python 3.7.3**

### Question Description

Is it possible to specify in `conanfile.txt` (or anywhere else) that the third package must be installed when on Windows and that the first and second package must be installed otherwise?

```
[requires]
bison/3.3.2@bincrafters/stable
flex/2.6.4@bincrafters/stable
winflexbison/2.5.18@bincrafters/stable
```

The goal is to build Flex/Bison on Windows, Linux, and macOS, preferably by using one and the same Conan + CMake configuration.

**Comment by SSE4** [comment]
two ways:
1. use different conanfiles per platform, e.g. `conanfile_win.txt`, `conanfile_mac.txt`, etc.
2. use `conanfile.py` which allows more flexibility: https://docs.conan.io/en/latest/mastering/conanfile_py.html

**Comment by wouterbeek** [comment]
Thanks for the answer!  I guess this is the moment I will have to make the step from `.txt` to `.py` :-)

**Comment by wouterbeek** [comment]
In somebody else wants to know the specific code to the above issue later:

**Comment by solvingj** [comment]
of note, you might want `flex` and `bison` on `windows` if you use `cygwin` and your compiler is `gcc`. for this reason, it's usually good to think hard about whether to switch based on `self.settings.os` or `self.settings.compiler`.  In this case, using `compiler` would probably be strictly better, in handling the `cygwin` case, without affecting the other cases.
