### ISSUE TITLE
[gyp_installer] Usage of GYP's Command Expansions leads to an AttributeError exception

### ISSUE THREAD

**Issue by cher-nov** [bincrafters/community#851]
CC @uilianries @SSE4

### Notes
This is seems to be caused by the next piece of code:
https://github.com/bincrafters/gyp/blob/cc91d1b0dc0375a9087974a8fd09fe9539a6ab3e/pylib/gyp/input.py#L898-L905

The problem is `universal_newlines=True`. The Python3 documentation [states next](https://docs.python.org/3/library/subprocess.html#subprocess.Popen):

> If _encoding_ or _errors_ are specified, **or _text_ is true**, the file objects _stdin_, _stdout_ and _stderr_ **are opened in text mode** with the specified encoding and _errors_, as described above in Frequently Used Arguments. **The _universal_newlines_ argument is equivalent to _text_** and is provided for backwards compatibility. **By default, file objects are opened in binary mode.**

Note that there's also many `universal_newlines=True` in the other places, introduced in by the bincrafters/gyp@067a33bc1dd132136fc118dcb45a7b2ce61c47b9.

Also note that there's much [more Python3 compatibility fixes](https://chromium.googlesource.com/external/gyp/+log) appeared in [the official repo](https://chromium.googlesource.com/external/gyp), so it's maybe have sense to rebase onto it (not replacing with it!) the Bincrafters version (moreover, their version seems to retain compatibility with Python2).

### Steps to reproduce
Run on Linux: `python3 gyp/gyp_main.py --depth=. --format=gypd lemme_die.gyp`
Contents of `lemme_die.gyp`:
```
{
    'conditions': [
      [ '"<!(uname -m)" == "i686"', {

      }],
    ],
}
```

### Logs
```
Exception: 'str' object has no attribute 'decode'
Traceback (most recent call last):
  File "share/gyp/pylib/gyp/input.py", line 487, in CallLoadTargetBuildFile
    includes, depth, check, False)
  File "share/gyp/pylib/gyp/input.py", line 408, in LoadTargetBuildFile
    build_file_data, PHASE_EARLY, variables, build_file_path)
  File "share/gyp/pylib/gyp/input.py", line 1286, in ProcessVariablesAndConditionsInDict
    build_file)
  File "share/gyp/pylib/gyp/input.py", line 1301, in ProcessVariablesAndConditionsInList
    ProcessVariablesAndConditionsInDict(item, phase, variables, build_file)
  File "share/gyp/pylib/gyp/input.py", line 1260, in ProcessVariablesAndConditionsInDict
    ProcessConditionsInDict(the_dict, phase, variables, build_file)
  File "share/gyp/pylib/gyp/input.py", line 1139, in ProcessConditionsInDict
    variables, build_file)
  File "share/gyp/pylib/gyp/input.py", line 1260, in ProcessVariablesAndConditionsInDict
    ProcessConditionsInDict(the_dict, phase, variables, build_file)
  File "share/gyp/pylib/gyp/input.py", line 1133, in ProcessConditionsInDict
    build_file)
  File "share/gyp/pylib/gyp/input.py", line 1057, in EvalCondition
    cond_expr, true_dict, false_dict, phase, variables, build_file)
  File "share/gyp/pylib/gyp/input.py", line 1071, in EvalSingleCondition
    build_file)
  File "share/gyp/pylib/gyp/input.py", line 904, in ExpandVariables
    p_stdout = p_stdout.decode()
AttributeError: 'str' object has no attribute 'decode'
```

### Package and Environment Details
  * Package Name/Version: **gyp_installer/20190423**
  * Operating System+version: **Linux Xubuntu 18.04.2 LTS**
  * Compiler+version: **gcc-7.4**
  * Conan version: **conan 1.16.1**
  * Python version: **Python 3.6.8**

### Conan configuration
```
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=7
os=Linux
os_build=Linux
```

**Comment by Croydon** [comment]
We certainty shouldn't maintain our own fork of gyp. Node.js relies on gyp heavily, and they are discussing right now if they want to maintain gyp in their org. If they decide for that, we should switch to this. If not, looking for alternatives maintainers or considering freezing it.

I believe gyp_installer got only added because it is a dependency of another package?

**Comment by cher-nov** [comment]
> I believe gyp_installer got only added because it is a dependency of another package?

I don't know actually, but this was extremely useful at least for me to install it from Conan.

**Comment by uilianries** [comment]
Yeah, it would be nice having another alternative. @SSE4 spent a lot of time fixing our fork. If we could use node version I would be happy, at least they are updating more frequently than us.

**Comment by SSE4** [comment]
if they have added python3 compatibility to the official repo, we may try to use that, that's great news

**Comment by cher-nov** [comment]
> if they have added python3 compatibility to the official repo, we may try to use that, that's great news

They have, but its Ninja generator doesn't work properly on Windows and fails on `msvs_emulation.py:985` (`_ExtractImportantEnvironment`) with the exception `TypeError: argument should be integer or bytes-like object, not 'str'`. This also fails on POSIX systems, reporting `gyp: Variable uname -m must expand to a string or list of strings; found a bytes` in case of the aforementioned example.

**Comment by SSE4** [comment]
okay, and what about nodejs/npm, do they use their own fork of gyp or just Google's repository?

**Comment by cher-nov** [comment]
It seems that they use a their own fork:
https://github.com/nodejs/node-gyp/commits/master/gyp
It also seems that it's Python3-compatible and updated regularly.

**Comment by SSE4** [comment]
okay then, let's try to migrate to node-gyp, for me it looks like the best option for now

**Comment by SSE4** [comment]
for @Croydon : gyp installer was added because some package use it as build system, for instance `libuv`, may be few others.

**Comment by Croydon** [comment]
Google is barely maintaining GYP, it's pretty much dead for them as they have moved on to other build systems.

The Node.js community has still several discussion ongoing about the future of their build system, but in the short term they are likely going to migrate to another fork which has Python 3 support, see: https://github.com/nodejs/node/pull/26620

So we could use https://github.com/refack/GYP

**Comment by Croydon** [comment]
Python 2 works with this GYP fork. Python 3 fails currently with this error https://ci.appveyor.com/project/bincrafters/conan-gyp-installer/build/job/2pin2muby1qphq74#L412

even though they are supposed to have fixed that https://github.com/refack/GYP/blame/master/gyp/generator/xcodeproj_file.py#L160

maybe we should try to push @uilianries patch upstream as he removed the `cmp` parameter completely, which seems to be necessary https://github.com/bincrafters/gyp/commit/c606b59891b4eef212c29a4349c0b03a271c36b2#diff-b71148dfd080925ebc604279f4d3fe23R1416

**Comment by Croydon** [comment]
Actually, they should merge https://chromium.googlesource.com/external/gyp/+/aca1e2c3d346d704adfa60944e6b4dd06f4728be

**Comment by Croydon** [comment]
Created issue: https://github.com/refack/GYP/issues/48

**Comment by Croydon** [comment]
@cher-nov You spoke out against replacing our fork with the upstream version, why?

**Comment by cher-nov** [comment]
> @cher-nov You spoke out against replacing our fork with the upstream version, why?

Because of this: https://github.com/bincrafters/community/issues/851#issuecomment-507574208.

**Comment by Croydon** [comment]
We decided a while ago to archive our gyp recipe.

https://github.com/bincrafters/conan-gyp_installer

```
Unmaintained recipe. If you desire a Conan GYP package, I recommend to package https://github.com/nodejs/gyp-next which is an actively maintained, backwards compatible fork of the abandoned original with Python 3 support 
```
