### ISSUE TITLE
Upstream Update: Botan 2.11.0

### ISSUE THREAD

**Issue by reneme** [bincrafters/community#853]
### Package Details
  * Package Name: **botan**
  * Latest available Version: **2.11.0**
  * Release Ticket: https://github.com/randombit/botan/issues/1882

I already prepared the necessary adaptions to the recipe [on this branch](https://github.com/reneme/conan-botan/tree/testing/2.11.0). Please consider to publish it in the official bincrafters repo.

Adaptions:
* Removed a source patch that worked around an issue that is [now fixed upstream](https://github.com/randombit/botan/pull/1884)
* Add an option `system_cert_bundle` that is useful for Unix builds to specify the default location of the TLS certificate chain PEM file for the target distribution
* Add an optional dependency to boost (1.69 or higher) that provides `boost::asio::ssl::stream`-like TLS client abstraction (uses https://github.com/randombit/botan/pull/1964)
* FIX: make use of new compile time options for more reliable dependency pick up (https://github.com/randombit/botan/pull/1958, https://github.com/randombit/botan/pull/1960)

**Comment by SSE4** [comment]
@reneme I've created new branch: https://github.com/bincrafters/conan-botan/tree/testing/2.11.0
may you submit PR with your changes against it?

**Comment by reneme** [comment]
Marked as `stable/2.11.0`. Thank you.
