### ISSUE TITLE
Applied conventions on conan-libiconv, conan-readline, conan-termcap

### ISSUE THREAD

**Issue by madebr** [bincrafters/community#857]
Hello,

`bincrafters-conventions` and `conan-readme-generator` were executed on the following repositories:

- [x] conan-readline: testing/7.0 bincrafters/conan-readline#5
- [x] conan-termcap: testing/1.3.1 bincrafters/conan-termcap#4

These are dependencies of gdbm (=dependency of cpython)

**Comment by Croydon** [comment]
Merged
