### ISSUE TITLE
bincrafters-conventions might not find the sha256 checksum when written in a new line

### ISSUE THREAD

**Issue by Croydon** [bincrafters/community#858]
https://github.com/bincrafters/conan-opus/pull/9/commits/9ef56737c69ef058f16991b8f71f1c91ee6f98cd 

Investigate + fix

// @madebr

**Comment by madebr** [comment]
https://github.com/bincrafters/bincrafters-conventions/pull/12

**Comment by Croydon** [comment]
Merged.
