### ISSUE TITLE
Add Circle CI template for OSX

### ISSUE THREAD

**Issue by uilianries** [bincrafters/community#86]
### Description of Problem, Request, or Question

We are running Circle CI for next 2 weeks (trial version). Circle CI could be the solution for our bottleneck when speaking about OSX build.

Unfortunately, Conan there is no support for that (templates).

**Comment by uilianries** [comment]
Our pilot project is Conan Parson: https://github.com/bincrafters/conan-parson

On Circle CI was possible build, test and deploy on follow configuration:
* Linux
  * GCC 7
* OSX
  * XCode 8.3
  * XCode 9

The log is here: https://circleci.com/workflow-run/3fe120d7-b869-4ee5-bb96-515a45f9c3a7

**Comment by uilianries** [comment]
Next points are:

* Update Bincrafters package tools
* Update Conan Package tools

**Comment by solvingj** [comment]
Link is 404

**Comment by uilianries** [comment]
Login is required

**Comment by uilianries** [comment]
Update link:

https://circleci.com/gh/bincrafters/workflows/conan-parson/tree/stable%2F0.1.0

**Comment by uilianries** [comment]
PR to support Circle CI on Conan package Tools:
https://github.com/conan-io/conan-package-tools/pull/144
