### ISSUE TITLE
[WxWidgets 3.1.2] Depency libwebkitgtk-dev not available any more on Ubuntu 19.04

### ISSUE THREAD

**Issue by loloof64** [bincrafters/community#861]
### Package and Environment Details
  * Package Name/Version: **wxwidgets/3.1.2**
  * Operating System+version: **Linux Ubuntu 19.04 (64 bit)**
  * Compiler+version: **gcc-8.3.0**
  * Conan version: **conan 1.16.1**
  * Python version: **Python 3.7.3** (default is Python 2.7.16)

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)

Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=8
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]

### Main issue

I'm facing an issue with bincrafter wxwidget package : it depends on an obsolete ubuntu package `wxwidgets/3.1.2@bincrafters/stable: ERROR: while executing system_requirements(): Command 'sudo apt-get install -y --no-install-recommends libwebkitgtk-dev:amd64' failed` It seems that libwebkitgtk-dev has been removed from Ubuntu 19.04 for security reasons.

**Comment by madebr** [comment]
https://bugs.launchpad.net/ubuntu/+source/webkitgtk/+bug/1588150

Replaced by `webkit2gtk`?

**Comment by loloof64** [comment]
Does not exist neither

**Comment by madebr** [comment]
I meant `libwebkit2gtk-4.0-dev`

https://packages.ubuntu.com/eoan/libwebkit2gtk-4.0-dev

**Comment by loloof64** [comment]
Seems that I'd installed it already.
But thank's anyway, as I finally solved the problem by modifying the conan configuration file, and setting `sysrequires_mode` to `disabled`.

**Comment by Croydon** [comment]
Currently we are building not only with the old API but also with GTK 2. Not sure if WxWidgets supports the new API and GTK 4 🤔 

Could somebody find that out?

//cc @SSE4 https://github.com/bincrafters/conan-wxwidgets/blame/testing/3.1.2/conanfile.py#L90

**Comment by SSE4** [comment]
going forward, the solution is to create conan GTK package, as system requirements have too many problems and don't scale well

**Comment by gmeeker** [comment]
I found this when discussing cross compiling Linux in #1433.  There is a GTK package now here https://conan.io/center/gtk but I haven't tried updating the wxWidgets recipes.  It looks like wxWidgets assumes GTK 2 by default but supports GTK 3.  GTK 4 won't be supported for a while: it's not on the roadmap for 3.2.

https://www.wxwidgets.org/blog/2021/01/wxwidgets-in-2020-and-beyond/

The recipe could have an option to use the gtk/3 package by default but also select gtk/system (or gtk/4 in the future)?

**Comment by Croydon** [comment]
We want to get rid of system packages as much as possible. If wxWidgets supports GTK3 then we can replace it. An option to choose `gtk/system` instead is not really in our interest

**Comment by Croydon** [comment]
wxwidgets is now in CCI https://conan.io/center/recipes/wxwidgets
