### ISSUE TITLE
[freeglut] No link to Bintray

### ISSUE THREAD

**Issue by wouterbeek** [bincrafters/community#866]
The links to Bintray from the README file of the repo for freeglut (https://github.com/bincrafters/conan-freeglut) are broken.  I'm not sure whether the package still exists in Bintray at all: searching inside Bintray does not bring it up.

**Comment by Croydon** [comment]
We weren't able yet to make freeglut stable, so there isn't any release yet, therefore no uploads on Bintray

**Comment by Croydon** [comment]
Closing in favour of https://github.com/conan-io/wishlist/issues/124
