### ISSUE TITLE
libelf "Error, the file to download already exists"

### ISSUE THREAD

**Issue by planetmarshall** [bincrafters/community#868]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libelf/0.8.13**
  * Operating System+version: **Linux Ubuntu 19.04**
  * Compiler+version: **gcc-6.5**
  * Conan version: **conan 1.16.1**
  * Python version: **Python 3.7.3**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=6.5
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
CC=gcc-6
CXX=g++-6
```

### Steps to reproduce (Include if Applicable)

`conan install libelf/0.8.13@bincrafters/stable --build missing`

May need manual editing of the `conanfile.py`, occurs when libelf tries to use a mirror

### Logs (Include/Attach if Applicable)

```
libelf/0.8.13@bincrafters/stable: WARN: Downloding libelf from mirror
ERROR: libelf/0.8.13@bincrafters/stable: Error in source() method, line 45
	tools.get(mirror_url.format(self.name, self.version), sha256=sha256)
	ConanException: Error, the file to download already exists: '/home/andrew/.conan/data/libelf/0.8.13/bincrafters/stable/source/libelf-0.8.13.tar.gz'
```

**Comment by SSE4** [comment]
applied a fix: https://github.com/bincrafters/conan-libelf/commit/1484214fd8557e179e414666edef7f35bd1077c1

**Comment by SSE4** [comment]
@planetmarshall it's already fixed, could you please give an another try and lemme know?

**Comment by planetmarshall** [comment]
Hi, I haven't managed to reproduce it since the fix. Thanks.
