### ISSUE TITLE
Packaging spdlog_setup

### ISSUE THREAD

**Issue by jgsogo** [bincrafters/community#87]
Hi everyone!

I'm working on packaging [spdlog_setup](https://github.com/guangie88/spdlog_setup) and I have found all kind of things that I want to share with you all. I open this issue to grab your attention and to centralize efforts, but if it we want to discuss more deeply about anything we may [open issues in my repo](https://github.com/jgsogo/conan-spdlog_setup) with specific things.

This is the dependency graph I'm working in:

![deps](https://user-images.githubusercontent.com/1406456/35396594-6efd9714-01ed-11e8-8570-05a30110d404.png)

These are the corresponding repos for the packages. (not exported to my bintray account yet):
 * [conan-gtest](https://github.com/jgsogo/conan-gtest) (see issue below)
 * [conan-rustfp](https://github.com/jgsogo/conan-rustfp)
 * [conan-cpptoml](https://github.com/jgsogo/conan-cpptoml)
 * [conan-variant](https://github.com/jgsogo/conan-variant)
 * [conan-optional-lite](https://github.com/jgsogo/conan-optional-lite)
 * [conan-spdlog_setup](https://github.com/jgsogo/conan-spdlog_setup)

Some issues I have come accross in the original projects, just in case anyone wants to address a PR:
 * [x] [`mpark/variant`](https://github.com/mpark/variant/tree/v1.3.0) makes use of `config_compiler_and_linker` from `gtest` ([here](https://github.com/mpark/variant/blob/v1.3.0/test/CMakeLists.txt#L37)), that's the reason I have forked `conan-gtest`, just to export the `cmake` file and being able to use it (see [opened issue](https://github.com/mpark/variant/issues/39)).
 * Projects without tags or version branches:
   - [ ] [`guangie88/spdlog_setup`](https://github.com/guangie88/spdlog_setup)
   - [ ] [`guangie88/rustfp`](https://github.com/guangie88/rustfp)
   - [ ] [`skystrife/cpptoml`](https://github.com/skystrife/cpptoml) last release is almost three years old [people pledge for a new one](https://github.com/skystrife/cpptoml/issues/42)
 * Projects with `deps` or `3rdparty` git-submodules:
   - [ ] [`mpark/variant`](https://github.com/mpark/variant/tree/v1.3.0)
   - [ ] [`guangie88/rustfp`](https://github.com/guangie88/rustfp)
   - [ ] [`guangie88/spdlog_setup`](https://github.com/guangie88/spdlog_setup)
 * [ ] [`mpark/variant`](https://github.com/mpark/variant/tree/v1.3.0) triggers `ExternalProjectAdd` if it is configured to run `libc++` tests, I have disabled them, but it would be interesting to have that dependency as a package an make those tests available.
 * ...and lots of tweaks I've done to the original `CMakeLists.txt` files during conan's `source()` method.

I know I have to read about projects without versions, header only libraries, submodules,... and so on in bincrafter's guides, but these is just the first draft for these packages. I'll keep you updated with my progress, ah! and PR are more than welcome =D

**Comment by solvingj** [comment]
Actually yes, if you want to open a github project, that might make sense for these "larger-scale" packages that will take some time.  Create a "Card"  for each package separately.

**Comment by solvingj** [comment]
Please check out our latest `gtest` package. We have 1.7.0 and 1.8.0, and apparently the library is fundamentally different between the two. 

Here's an example of a package without semantic version: 
https://github.com/bincrafters/conan-abseil/blob/testing/20180102/conanfile.py

We use the date as the version, and lock it to a commit from that date.

**Comment by jgsogo** [comment]
Great! I was waiting for that `gtest` release, it has a lot of changes. I'll update it, and may submit packages if they are ready (now some of them have many tweaks).

**Comment by jgsogo** [comment]
I have just submitted [optional-lite](https://github.com/bincrafters/conan-optional-lite), but `variant` must wait for the referenced issue to be resolved, it still needs my modified [`conan-gtest` package](https://github.com/jgsogo/conan-gtest).

**Comment by jgsogo** [comment]
## mpark/variant

Moving forward: [`mpark/variant`](https://github.com/jgsogo/conan-variant) is almost ready (only one open issue here: https://github.com/bincrafters/community/issues/172 that is trivial to solve). It has some minor tweaks I want to share to with you:
 * I need a file from gtest not being distributed with it, so I download it. See [here](https://github.com/jgsogo/conan-variant/blob/ae6d991dbc4fbe6b91e6f7195d3502de365b9b26/conanfile.py#L44). Still waiting for this [issue](https://github.com/mpark/variant/issues/39) to be solved and remove the workaround.
 * I downgraded `cmake_minimum_required` versions [here](https://github.com/jgsogo/conan-variant/blob/ae6d991dbc4fbe6b91e6f7195d3502de365b9b26/conanfile.py#L48) because @lasote docker image for Macos has a lower one.
 * Remove 3rd party references in favor of conan ones. [here](https://github.com/jgsogo/conan-variant/blob/ae6d991dbc4fbe6b91e6f7195d3502de365b9b26/conanfile.py#L56)
 * Need to define `gtest_force_shared_crt` for Visual Studio /MD to compile. See [here](https://github.com/jgsogo/conan-variant/blob/ae6d991dbc4fbe6b91e6f7195d3502de365b9b26/conanfile.py#L76). I think that this fix should be implemented into conan-gtest package. <-- don't you think so, @SSE4 @dimi309 @solvingj?

Given this patches, do you think I should move to bincrafters?

**Comment by SSE4** [comment]
cmake_minimum_required - there is no docker images for Macos - it builds on travis virtual machine which has older CMake version
gtest_force_shared_crt - agree

**Comment by jgsogo** [comment]
I've being testing a little bit more and I need to set `gtest_force_shared_crt`  because mpark/variant is using `internal_utils.cmake` (which is not exported by the gtest package); so the recipe don't need to set this flag (I edit above)

**Comment by solvingj** [comment]
ping @jgsogo for update.  do we want to revisit?

**Comment by jgsogo** [comment]
Thanks for the reminder, I'm sure this is still interesting. It's being a year since then and I'm sure that many packages are now available and several issues have been solved. We would like to start a C++ project (artificially complicated) to test some of the Conan features and I'm sure we will implement some kind of logging and configuration (these packages could be a good starting point).

So, if there are other packages that deserve attention, focus on those ones; I'm going to add this issue to our TODO list and we will come back to it soon. If these packages are needed for another bigger one, let us know to prioritize it accordingly.

Thanks

**Comment by Croydon** [comment]
So we do have:

  * [x]  conan-gtest https://github.com/bincrafters/conan-gtest
  * [ ]  conan-rustfp
  * [ ]  conan-cpptoml
  * [x]  conan-variant https://github.com/bincrafters/conan-variant
  * [ ]  conan-optional-lite https://github.com/bincrafters/conan-optional-lite
  * [ ]  conan-spdlog_setup

**Comment by SSE4** [comment]
this should go to the https://github.com/conan-io/conan-center-index now
