### ISSUE TITLE
[qt] 'settings.arch_build' value not defined, 'settings.os_build' value not defined

### ISSUE THREAD

**Issue by Quincunx271** [bincrafters/community#871]
### Package and Environment Details
  * Package Name/Version: **qt/5.12.1@bincrafters/stable** through **qt/5.13.0@bincrafters/stable**
  * Operating System+version: **Linux Ubuntu 16.04**
  * Compiler+version: **gcc-8.3.0**, should be irrelevant
  * Conan version: **conan 1.15.1**. Also confirmed on **conan 1.17.0**
  * Python version: **Python 3.5.2**

### Conan profile

```
[settings]
os=Linux
compiler=gcc
compiler.version=8
compiler.libcxx=libstdc++11
build_type=Debug
arch=x86_64
compiler.cppstd=17

[options]

[env]
CC=/usr/bin/gcc-8
CXX=/usr/bin/g++-8
```

### Steps to reproduce

With the given profile and a `conanfile.txt` which just requires the qt package:

```
conan install -pr the.profile conanfile.txt
```

Output:

```
Configuration:
[settings]
arch=x86_64
build_type=Debug
compiler=gcc
compiler.cppstd=17
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux
[options]
[build_requires]
[env]
CC=/usr/bin/gcc-8
CXX=/usr/bin/g++-8
ERROR: qt/5.12.1@bincrafters/stable: 'settings.arch_build' value not defined
```

Adding `arch_build=x86_64` brings the message `'settings.os_build' value not defined`

### Expected behavior

When no `arch_build` setting is given, we should fall back to `arch`. Similarly for `os_build` and `os`.

**Comment by ericLemanissier** [comment]
As we are reading `settings.os_build` and `settings.arch_build` inside the recipe ([in the `build` method](https://github.com/bincrafters/conan-qt/blob/testing/5.13.0/conanfile.py#L501)), we have to declare them in https://github.com/bincrafters/conan-qt/blob/testing/5.13.0/conanfile.py#L55. It is the declaration which makes conan error, and recipes have no way to define fallback values at this level. In other word you should report this to conan.
