### ISSUE TITLE
libcurl/7.61.1 new binaries fail

### ISSUE THREAD

**Issue by piponazo** [bincrafters/community#872]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libcurl/7.61.1@bincrafters/stable**
  * Operating System+version: **Linux Ubuntu 16.04**
  * Compiler+version: **gcc-5.4**
  * Docker image: **conanio/gcc7**
  * Conan version: **conan 1.11.2**
  * Python version: **Python 3.7.0**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)

default

### Steps to reproduce (Include if Applicable)

A CI build I have setup for the Exiv2 project started to fail today. I noticed in the conan-center repository that you updated the binaries today, so that there could be a problem with that. Check the next link for seeing the errors

### Logs (Include/Attach if Applicable)

https://travis-ci.org/Exiv2/exiv2/jobs/557504191

**Comment by uilianries** [comment]
@SSE4 seems like we can't update libcurl as we thought ...WDYT @theirix ?

**Comment by SSE4** [comment]
error message is:
```
/usr/bin/ld: warning: libssl.so.1.1, needed by //home/travis/conanData/libcurl/7.61.1/bincrafters/stable/package/e0ff57928d1a2be3521b5a25389269bf0007aa88/lib/libcurl.so.4, not found (try using -rpath or -rpath-link)
```
what is about `libssl.so.1.1`? is it missing from the conan package?

**Comment by theirix** [comment]
Looks like an OpenSSL package referenced at the failed Travis build contains libssl.so.1.1 and undefined symbols (like BIO_free)

**Comment by theirix** [comment]
@piponazo looks like your conanfile does not import dynamic libs to the build directory.
Please try adding to the `imports` method:
```py
    self.copy("*.so*", dst="lib", src="lib")
```

It worked before with OpenSSL 1.0 because Exiv2 picked up libssl from system directories. Now when we switched to 1.1 the bug has shown up.

**Comment by piponazo** [comment]
> @piponazo looks like your conanfile does not import dynamic libs to the build directory.
I'll give it a try. Thanks for the prompt feedback!

**Comment by piponazo** [comment]
Hi! At the end, I ended up just upgrading to the latest conan version and to the latest version of libcurl `libcurl/7.64.1` to solve our issue. 

I did not want to spend much time trying to solve such linking issues in our Travis CI jobs, because we use them just to test that the project can handle the dependencies with conan. Then we have another bunch of builders with Gitlab for many different linux distributions which handle the dependencies with system packages. There we put more attention to linking issues that could reveal integration problems with distributions.

You can close the issue if you think that this topic does not need more attention. Thanks!

**Comment by theirix** [comment]
Upgrading Conan sometimes helps because recipes can use new Conan features. It's good that a simple upgrade autosolved your problem.
