### ISSUE TITLE
[libpng/1.6.37] Fails to build on self.settings.os == "Emscripten"

### ISSUE THREAD

**Issue by starcatter** [bincrafters/community#873]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libpng/1.6.37**
  * Operating System+version: Windows 10 1809
  * Compiler+version: **gcc  8.1.0 (x86_64-posix-seh-rev0, Built by MinGW-W64 project)**
  * Conan version: **conan 1.17.0**
  * Python version: **Python 3.7.2**
  * Build env: **CLion -> mingw -> gcc**, using **[conan.cmake](https://github.com/conan-io/cmake-conan)**

### Issue
libpng fails to build /w error shown in log below, says culprit is [line 78](https://github.com/bincrafters/conan-libpng/blob/testing/1.6.37/conanfile.py#L78) in package's conanfile.py

### Quick fix
removing the line and its following block fixed the build.

### Other steps taken
I've attempted adding **Emscripten** to os_build/os_target in the **settings.yml** file, it didn't help.

### Log
> Downloading conan_sources.tgz
> libpng/1.6.37@bincrafters/stable: Configuring sources in C:\Users\starcatter\.conan\data\libpng\1.6.37\bincrafters\stable\source
> libpng/1.6.37@bincrafters/stable: Copying sources to build folder
> libpng/1.6.37@bincrafters/stable: Building your package in C:\Users\starcatter\.conan\data\libpng\1.6.37\bincrafters\stable\build\e393111ba38dd85fcdf785ee91a62c480dbb33b8
> libpng/1.6.37@bincrafters/stable: Generator cmake created conanbuildinfo.cmake
> libpng/1.6.37@bincrafters/stable: Calling build()
> libpng/1.6.37@bincrafters/stable: libpng/1.6.37@bincrafters/stable: 
> ERROR: Package 'e393111ba38dd85fcdf785ee91a62c480dbb33b8' build failed
> libpng/1.6.37@bincrafters/stable: WARN: Build folder C:\Users\starcatter\.conan\data\libpng\1.6.37\bincrafters\stable\build\e393111ba38dd85fcdf785ee91a62c480dbb33b8
> ERROR: libpng/1.6.37@bincrafters/stable: Error in build() method, line 78
> 	if self.settings.os == "Emscripten":
> 	ConanException: Invalid setting 'Emscripten' is not a valid 'settings.os' value.
> Possible values are ['Android', 'Arduino', 'FreeBSD', 'Linux', 'Macos', 'SunOS', 'Windows', 'WindowsStore', 'iOS', 'tvOS', 'watchOS']
> Read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting"
> CMake Error at cmake/conan.cmake:401 (message):
>   Conan install failed='1'
> Call Stack (most recent call first):
>   cmake/conan.cmake:487 (conan_cmake_install)
>   app/wxCanvasApp/CMakeLists.txt:6 (conan_cmake_run)

**Comment by SSE4** [comment]
@starcatter you need to update your `settings.yml` file

**Comment by starcatter** [comment]
Where can I find an up to date config file? 
I've looked on official Github repo, in the installers, in the docs, sorry can't find it :(
I was hoping that it would be updated along with Conan.

Anyhow, I don't think packages should fail to build just because my installation doesn't have config entries for platforms I'm not building. Maybe wrap the check in a try/catch block?
```
        try:
            if self.settings.os == "Emscripten":
                cmake.definitions["PNG_BUILD_ZLIB"] = "ON"
                cmake.definitions["M_LIBRARY"] = ""
                cmake.definitions["ZLIB_LIBRARY"] = self.deps_cpp_info["zlib"].libs[0]
                cmake.definitions["ZLIB_INCLUDE_DIR"] = self.deps_cpp_info["zlib"].include_paths[0]
        except:
            self.output.warn("Emscripten missing from config.yml, update your config!")
```

**Comment by SSE4** [comment]
usually, in `%HOME%/.conan/settings.yml` (or `%USERPROFILE%\.conan\settings.yml` on Windows)
also, if there is `settings.yml.new`, you can just rename it to the `settings.yml`

**Comment by starcatter** [comment]
Thanks, I missed that bit of documentation. Replacing `settings.yml` with `settings.yml.new` didn't work, it was missing the `arch_build` entry (and a bunch of other ones), deleting `settings.yml` allowed Conan to create a new one that worked.

That solved the problem for me. Thanks!
