### ISSUE TITLE
[wxwidgets/3.1.2] actual library directory no longer in lib path

### ISSUE THREAD

**Issue by starcatter** [bincrafters/community#874]
### Package and Environment Details
- Package Name/Version: **wxwidgets/3.1.2**
- Operating System+version: **Windows 10 1809**
- Compiler+version: **gcc 8.1.0 (x86_64-posix-seh-rev0, Built by MinGW-W64 project)**
- Conan version: **conan 1.17.0**
- Python version: **Python 3.7.2**
- Build env: **CLion -> mingw -> gcc, using conan.cmake**

### Issue
Switching from version 3.1.1 to 3.1.2 no longer builds - the linker cannot find necessary libraries.

### Cause
Version 3.1.1 provides two lib dirs for wxWidgets:
```
[libdirs]
C:/Users/starcatter/.conan/data/wxwidgets/3.1.1/bincrafters/stable/package/fd79db286b289d76cc42cd74f4df4a67eadf1f1e/lib
C:/Users/starcatter/.conan/data/wxwidgets/3.1.1/bincrafters/stable/package/fd79db286b289d76cc42cd74f4df4a67eadf1f1e/lib/gcc_dll
```

Version 3.1.2 only provides one:
```
[libdirs]
C:/Users/starcatter/.conan/data/wxwidgets/3.1.2/bincrafters/stable/package/fd79db286b289d76cc42cd74f4df4a67eadf1f1e/lib
```

Perhaps also of note, while 3.1.1 placed the libraries in `lib/gcc_dll`, 3.1.2 uses `lib/gcc_x64_dll`. Both builds were 64bit.

### Quick fix
Manually adding `C:/Users/starcatter/.conan/data/wxwidgets/3.1.2/bincrafters/stable/package/fd79db286b289d76cc42cd74f4df4a67eadf1f1e/lib/gcc_x64_dll` as a library search dir made the project build again.

**Comment by SSE4** [comment]
@starcatter thanks for the report, I'll apply the fix
P.S. I don't understand why do they apply such breaking changes in minor releases?

**Comment by SSE4** [comment]
applied: https://github.com/bincrafters/conan-wxwidgets/commit/b311849e0f2bf19967775d1325e8817bc4daff3f
