### ISSUE TITLE
[Qt] Please, add binaries for Windows gcc 7 for Debug

### ISSUE THREAD

**Issue by SebastianMosiej** [bincrafters/community#876]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.12.4@bincrafters/stable**
  * Operating System+version: **Windows 10 64b**
  * Compiler+version: **gcc-7.3**
  * Conan version: **Conan 1.17.0**
  * Python version: **Python 3.7.0**

### Add binaries Windows gcc 7 for Debug
There's already Windows gcc 7 (posix) (libstdc++) (seh) for x86_64 Release (even if outdated).

**Comment by ericLemanissier** [comment]
currently, mingw binaries are generated only for release/shared configuration, because of CI time limitations on appveyor. debug builds and static builds will be added when windows CI will be migrated to azure pipelines, which is WIP currently, so hopefully in few days/week.

**Comment by Croydon** [comment]
In order to adapt to the Conan Center Index we aren't able anymore to offer any MinGW prebuilds.

Sorry!
