### ISSUE TITLE
[java_installer] recipe does not set JAVA_HOME in cmake generator

### ISSUE THREAD

**Issue by cleeland** [bincrafters/community#877]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **java_installer/8.0.153@bincrafters/stable**
  * Operating System+version: **Linux CentOS 7**
  * Compiler+version: **devtoolset-7 (gcc 7.3.1)**
  * Conan version: **conan 1.12.2**
  * Python version: **Python 2.7.5**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=7
compiler.libcxx=libstdc++
build_type=Release
[options]
gflags:namespace=google;gflags
mysql-connector-c:with_ssl=True
mysql-connector-c:with_zlib=True
pcre:with_jit=True
[build_requires]
[env]
```

### Description
When using `java_installer`, the recipe sets `JAVA_HOME` in the environment.  That setting gets added to `conanbuildinfo.txt` but not to `conanbuildinfo.cmake`.

Consequently, if a CMakeLists.txt has something like the following:
```
find_package(Java REQUIRED)
find_package(JNI REQUIRED)
...etc...
```
the `find_package(Java)` will find stuff made available by the `java_installer` package, but `find_package(JNI)` will not and will instead only search the system installs for JNI.

I'm not sure if this is a bug in the java_installer recipe, or in the cmake generator for conan (for not putting the environment settings into `conanbuildinfo.cmake`).

**Comment by SSE4** [comment]
it's currently impossible to propagate environment variables into the CMake generator, it's conan's limitation, not recipe's

**Comment by cleeland** [comment]
I was afraid that was the case.

For the moment, I actually use `awk` in my CMakeLists.txt to find the value of `JAVA_HOME` in conanbuildinfo.txt and then ```set(ENV{JAVA_HOME} <value_from_conanbuildinfo.txt>)```

That feels dirty or at least inelegant.

Besides adding the feature to conan to permit propagation, do you have any suggestions for a better way to get the JAVA_HOME value?

(Please note that I'll be filing a conan bug with jfrog and will post a link here.)

**Comment by SSE4** [comment]
sorry, I have no idea how to propagate that. you probably can use some CMake variables conan sets, like `CONAN_JAVA_INSTALLER_ROOT` instead of `ENV{JAVA_HOME}`

**Comment by uilianries** [comment]
@cleeland maybe you can try [Virtual Environ](https://docs.conan.io/en/latest/devtools/create_installer_packages.html#using-the-tool-packages-in-your-system) generator. As you need to export an env var, only `self.run("command", run_environemnt=True) and *virtual environment* are able to propagate them.

**Comment by Croydon** [comment]
This recipe is now in the [Conan Center Index](https://github.com/conan-io/conan-center-index/).

Please migrate to the recipe version there. 
If this is still an issue, please create a new issue in the [Conan Center Index issue tracker](https://github.com/conan-io/conan-center-index/issues).

Thanks!

**Comment by Croydon** [comment]
Hint: the new name is zulu-openjdk

https://conan.io/center/zulu-openjdk

**Comment by cleeland** [comment]
The new project doesn't offer older JDK versions, so this one will continue to be used.
