### ISSUE TITLE
Inclusion Request: whereami

### ISSUE THREAD

**Issue by notskm** [bincrafters/community#878]
### Package Details
  * Package Name: **whereami**
  * Operating Systems+versions: **Linux Ubuntu 16.04, Ubuntu 18.04, Windows, macOS**
  * Compiler support: **gcc-4.9+, clang3.9+, Visual Studio 2015+**
  * Conan recipe repository: **https://github.com/notskm/conan-whereami**

### Inclusion request
  * Fill all checkboxes with x if you agree with the statement or if it applies to your Conan recipe
  * [x] I want that my Conan recipe is getting included into the Bincrafters organisation
  * [x] I understand that if my request is accepted we are cloning your repository with all its history into Bincrafters, adapt some configurations and meta data if needed, and publishing it under the Bincrafters name and accounts
  * [x] I have used the Bincrafters templates to develop my Conan recipe - https://github.com/bincrafters/conan-templates
  * [x] My Conan recipe and all parts of it are licensed under the MIT license - https://choosealicense.com/licenses/mit/
    * Bincrafters are releasing all recipes under MIT license. If you want to have your recipe within Bincrafters we kindly ask you to do the same
    * it is okay if your test_package contains code from the upstream project under the upstream project's license, as long as it is clearly mentioned within the test_package files
  * [x] My Conan recipe covers (at least) the latest stable version which is available for the package
  * [ ] I know that my Conan recipe is working on all operating system and compilers mentioned above right now
    * CMake errors with "No CMAKE_CXX_COMPILER could be found." for Visual Studio 2019 builds. https://ci.appveyor.com/project/notskm/conan-whereami
    * All other builds work. https://travis-ci.org/notskm/conan-whereami
  * [x] I'm willing to help to maintain the recipe even after it is included into Bincrafters

whereami does not have a version number. It also has no releases. This library is designed to simply be copied into your project. I'm not sure how to handle the version number for a library like this, so I just used the commit hash. I can change that with some guidance.

As stated above, the Visual Studio 2019 builds are failing.

### Checklist for the Bincrafters team
  * Ignore this if you are not part of the Bincrafters team
  * [x] There is no such Conan package yet in conan-center, conan-community or Bincrafters
  * [x] The project is either popular or deserves to be maintained for another good reason (we can't package every single project out there)
  * [x] [bincrafters-conventions](https://github.com/bincrafters/bincrafters-conventions) reports no complains; the recipe fulfills our general quality requirements and conventions
  * [x] The recipe is cloned into our organisation; CI is enabled and configurated and succeeds
  * [ ] There is a branch protection rule for `stable/*` branches, which requires a pull request with at least one approval first before things can get published
  * Considering granding the inclusion request author push rights to the recipe repository (there is no guarantee that everyone is getting push rights, we decide this on a case-to-case base)

**Comment by Morwenn** [comment]
Hum, your recipe link points to conan-libpng.

**Comment by uilianries** [comment]
> Hum, your recipe link points to conan-libpng.

https://github.com/notskm/conan-whereami

**Comment by notskm** [comment]
> Hum, your recipe link points to conan-libpng.

Sorry about that. I had that open in another tab and must have copied that link accidentally.

**Comment by Croydon** [comment]
I believe in the case of no release numbers we have done both commit hash versions and date versions. Do we have some kind of standard for this? 🤔

**Comment by uilianries** [comment]
Yes, https://bincrafters.readthedocs.io/en/latest/using_packages.html#packages-without-official-releases

The problem using hash is that we can't guarantee the list order when printing. For instance, `conan search` will print a sorted order, but not by release date.

**Comment by uilianries** [comment]
Done! whereami is available for download:

https://github.com/bincrafters/conan-whereami

https://travis-ci.com/bincrafters/conan-whereami
https://ci.appveyor.com/project/bincrafters/conan-whereami

https://bintray.com/bincrafters/public-conan/whereami%3Abincrafters
