### ISSUE TITLE
Upstream Update: cpprestsdk 2.10.14

### ISSUE THREAD

**Issue by reneme** [bincrafters/community#879]
### Package Details
  * Package Name: **cpprestsdk**
  * Latest available Version: **2.10.14**

The above mentioned version is newly released by the upstream project and not yet available within Bincrafters. Please add this version.

The new version should build just fine after bumping the recipe's version number and the tarball's SHA256.

**Comment by Croydon** [comment]
https://github.com/bincrafters/conan-cpprestsdk/commit/add0beeafc2dd4be7551583f8b2af591b0994df7

Waiting for CI

**Comment by Croydon** [comment]
Rebased: https://github.com/bincrafters/conan-cpprestsdk/commit/2c99fea9c88786c08efc6460e980315bc8bcc907

It's available now
