### ISSUE TITLE
conan-sdl2 - system_requirements problems on CI

### ISSUE THREAD

**Issue by solvingj** [bincrafters/community#88]
### Description of Problem, Request, or Question
3 out of 6 jobs are failing on TravisCI because `apt-get install something` fails as part of `system_requirements()`
https://travis-ci.org/bincrafters/conan-sdl2/jobs/333324318

Note this is the `apt-get install` done by Conan inside the docker container, not on the TravisCI host OS. 

### Package Details (Include if Applicable)
* Package Name/Version: **sdl2/2.0.7**
* Operating System: **Linux**
* Compiler+version: **NA**
* Docker image: **lasote/conanclang3, lasote/conanclang4, lasotegcc6**

### Steps to reproduce (Include if Applicable)
Just review the CI logs:
https://travis-ci.org/bincrafters/conan-sdl2/jobs/333324318

**Comment by SSE4** [comment]
I was thinking it's network issue, but it appears to be repository data is somehow broken in docker container. will take a look at this.

**Comment by solvingj** [comment]
Have similar issue here, definitely feels docker container related now: 
https://travis-ci.org/bincrafters/conan-boost_python

**Comment by SSE4** [comment]
seems like happens only for clang images

**Comment by solvingj** [comment]
@uilianries any ideas on what would be different among these Docker images?

**Comment by SSE4** [comment]
may be this line causes problems?
`rm -rf /var/lib/apt/lists/* \`
see https://github.com/lasote/conan-docker-tools/blob/master/clang_4.0/Dockerfile

**Comment by solvingj** [comment]
@SSE4 I believe the x86 containers created by Uilian should allow us to solve this issue.

**Comment by SSE4** [comment]
@solvingj I've already have switched to them, but run into another issue: https://github.com/conan-io/conan-package-tools/issues/150

**Comment by SSE4** [comment]
problem solved, thanks to everybody
