### ISSUE TITLE
[qt/5.12.4] pkg-config required

### ISSUE THREAD

**Issue by bilke** [bincrafters/community#880]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.12.4**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **gcc-7.4.0**
  * Docker image: **ogs6/gcc:gui**
  * Conan version: **conan 1.16.0**
  * Python version: **Python 3.6.8**

### Conan profile

```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=7
compiler.libcxx=libstdc++
build_type=Release
```

### Steps to reproduce (Include if Applicable)

My custom docker image does not have `pkg-config` installed. But this seems to be required as the qt package depends on it when looking for dependencies installed via Conan, e.g. `xkbcommon` or `glib`.

Output without `pkg-config`:

```
...
Checking for GLib... no
...
Checking for xkbcommon >= 0.5.0... no
...
ERROR: Feature 'glib' was enabled, but the pre-condition 'libs.glib' failed.
ERROR: Feature 'xcb' was enabled, but the pre-condition 'features.thread && features.xkbcommon && libs.xcb' failed.
...
```

Installing `pkg-config` in the image fixes this.

Should this be added via `SystemPackageTool` in `build_requirements()`?

**Comment by ericLemanissier** [comment]
Can you please send the full log without `pkg-config` installed ?

**Comment by bilke** [comment]
@ericLemanissier Here is the full log: https://jenkins.opengeosys.org/job/ufz/job/ogs/job/PR-2573/16/execution/node/70/log/?consoleFull

I also carefully checked the log and it also outputs:

```
12:08:22  qt/5.12.4@bincrafters/stable: 
12:08:22  ERROR: Not able to automatically detect '/usr/bin/cc' version
12:08:22  ERROR: Unable to find a working compiler
```

**Comment by ericLemanissier** [comment]
I guess we could add `pkg-config_installer` to the build requirements of the recipe if the system `pkg-config` is not detected.
