### ISSUE TITLE
ffmpeg: cuda

### ISSUE THREAD

**Issue by Morkxy** [bincrafters/community#885]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **ffmpeg/4.1@bincrafters/stable**

### Question Description
Hello,
In the ffmpeg recipe, i found this comment :
"FIXME disable CUDA and CUVID by default, revisit later"

There is a roadmap for this feature ?

Thanks

**Comment by SSE4** [comment]
no plans yet, but if you can contribute with pull request, that would be absolutely nice

**Comment by Morkxy** [comment]
Yes of course, but for the moment i'm too beginner on Conan for make this :(

Thank you for your answer

**Comment by SSE4** [comment]
@Morkxy if you're CUDA user, may you possibly describe how do you use CUDA in general, I am more interested in installation, configuration and build system things (question below might be really stupid, but I didn't touch CUDA for ages):
1. on which platforms do you use CUDA? Mac/Linux/Windows? any others?
2. how do you install CUDA, do you use an installer from nVidia web-site, or do you use package from the system package manager (brew/apt/yum/pacman/etc)? or something else maybe?
3. is CUDA usually installed system-wide into known locations, e.g. headers are in `/usr/include` and libraries in `/usr/lib`, compilers are in `/usr/bin`, etc? in other words, is it safe to assume CUDA is always available in some well-known paths?
4. do you use `pkg-config` to get the appropriate compiler/linker flags to build with CUDA?
5. do you set some system environment variables to help compiler/build system to locate CUDA, or its components (headers, libraries, binaries, etc.) - e.g. `CUDA_HOME`, `CUDA_ROOT`, `CUDACXX`, etc.
6. do you use `nvenc` or `cuvid` in conjunction with CUDA?
7. do you need to pass some additional compiler/linker flags if you build CUDA applications?
8. what about binary compatibility, should CUDA (toolkit) version be modelled as a conan subsetting or option? in other words, if I compiled library with CUDA 10, may it be linked with library built with CUDA 9, and vice versa? is it forward/backward compatible? are there options which affect binary compatibility?

**Comment by Morkxy** [comment]
Hello
Finally I will not need to integrate Cuda with FFMPEG, but I will try to answer the questions...

1- All plateforms
2- For Linux OS (Debian), i use nvidia APT repository (from NVidia) and for others OS i download from NVidia website
3- hum... i don't know :/
4- I seem to not use pkg-config
5- no
6- yes
7- Yes, some flags like "path to SDK" and "path to cuda install dir"... when the QMake project is builded
8- Unfortunately I do not have enough experience on it to answer...
3-

**Comment by SSE4** [comment]
@Morkxy anyway, thanks for the information. it will help to design CUDA support in our packages in the future.
