### ISSUE TITLE
Inclusion Request: gsoap

### ISSUE THREAD

**Issue by madduci** [bincrafters/community#889]
### Package Details
  * Package Name: **gSOAP**
  * Operating Systems+versions: **Linux, Windows, macOS**
  * Compiler support: **gcc4.9+, clang3.8+, MSVC 12+**
  * Conan recipe repository: **https://github.com/madduci/conan-gsoap**

### Inclusion request
  * Fill all checkboxes with x if you agree with the statement or if it applies to your Conan recipe
  * [X] I want that my Conan recipe is getting included into the Bincrafters organisation
  * [X] I understand that if my request is accepted we are cloning your repository with all its history into Bincrafters, adapt some configurations and meta data if needed, and publishing it under the Bincrafters name and accounts
  * [X] I have used the Bincrafters templates to develop my Conan recipe - https://github.com/bincrafters/conan-templates
  * [X] My Conan recipe and all parts of it are licensed under the MIT license - https://choosealicense.com/licenses/mit/
    * Bincrafters are releasing all recipes under MIT license. If you want to have your recipe within Bincrafters we kindly ask you to do the same
    * it is okay if your test_package contains code from the upstream project under the upstream project's license, as long as it is clearly mentioned within the test_package files
  * [X] My Conan recipe covers (at least) the latest stable version which is available for the package
  * [X] I know that my Conan recipe is working on all operating system and compilers mentioned above right now
    * if not: please provide here links to your CI platforms and / or build logs and describe the problems you encounter
  * [X] I'm willing to help to maintain the recipe even after it is included into Bincrafters

### Checklist for the Bincrafters team
  * Ignore this if you are not part of the Bincrafters team
  * [ ] There is no such Conan package yet in conan-center, conan-community or Bincrafters
  * [ ] The project is either popular or deserves to be maintained for another good reason (we can't package every single project out there)
  * [ ] [bincrafters-conventions](https://github.com/bincrafters/bincrafters-conventions) reports no complains; the recipe fulfills our general quality requirements and conventions
  * [ ] The recipe is cloned into our organisation; CI is enabled and configurated and succeeds
  * [ ] There is a branch protection rule for `stable/*` branches, which requires a pull request with at least one approval first before things can get published
  * Considering granding the inclusion request author push rights to the recipe repository (there is no guarantee that everyone is getting push rights, we decide this on a case-to-case base)

**Comment by uilianries** [comment]
Hi @madduci ! Thanks for your inclusion request, we will review your recipe soon. Regards!

**Comment by madduci** [comment]
Thank you, in the waiting time, I've fixed the Windows build and it works on all the AppVeyors environments

**Comment by uilianries** [comment]
seems like your linux and macos build is broken: https://travis-ci.org/madduci/conan-gsoap/builds/565433374

**Comment by madduci** [comment]
Yes, as I mentioned in the text description above, I don't know why on Travis the build is broken. If i run it locally on my machine, it works without problem.

I guess it's a problem with permissions of the file system, because some files could not be written (in the specific, the ones generated from `bison` and `flex`)

**Comment by Croydon** [comment]
Maybe it requires another version of Flex/Bison?

**Comment by uilianries** [comment]
Maybe @SSE4 knows some magic, he is a bison/flex sorcerer

**Comment by madduci** [comment]
The bison/flex works as expected (see AppVeyor, in local on Linux it works too), but I see the error is still in the docker environment used to build the package --- maybe some bad permission? 
Internally in CMake I create an output folder to store the generated files from flex and bson

**Comment by madduci** [comment]
I've found the mistake. Somehow CMake wasn't creating the output folder before running flex and bison in Travis CI runners, while on my local machine it was.

I've included a dependency target in CMake, so the order of targets is now executed without problems.

meanwhile, I've updated the project to 2.8.91

**Comment by uilianries** [comment]
Done!

https://bintray.com/bincrafters/public-conan/gsoap%3Abincrafters
https://github.com/bincrafters/conan-gsoap

You need to consider this project contains binaries and libraries, which means we need to provide two separated packages. The same repo contains a recipe only for gsoap_installer (binaries only) and gsoap (libraries only).
