### ISSUE TITLE
conan-gtest library didnot build for build_gmock=true

### ISSUE THREAD

**Issue by richardor** [bincrafters/community#89]
hi @solvingj ,  
     the library gtest/1.8.0@bincrafters/stable doesnot contain the package , that built with "build_gmock=true"?  If i modify the default options to true, then it can be compiled successully.

    can you fix it? 
    thank you.

**Comment by solvingj** [comment]
With options like this, we generally only build with variants of the `shared` option.  When you consume the package, if you want to use with `build_gmock=True`, try specifying `--build=missing` in your command.

**Comment by solvingj** [comment]
@richardor i was able to build with the following command:
