### ISSUE TITLE
Upstream Update: jsonformoderncpp 3.7.0

### ISSUE THREAD

**Issue by IceflowRE** [bincrafters/community#890]
### Package Details
  * Package Name: **jsonformoderncpp**
  * Latest available Version: **3.7.0**

The above mentioned version is newly released by the upstream project and not yet available within Bincrafters. Please add this version.

**Comment by IceflowRE** [comment]
Invalid *facepalm*

**Comment by uilianries** [comment]
Bincrafters is so famous that you looked for us first :joy:

**Comment by IceflowRE** [comment]
That was exactly the reason, i was really confused until i found out, that i didn't got this package from bincrafters...

**Comment by ericLemanissier** [comment]
all conan packagers should subscribe to the issues of this repo, so that they receive upstream update request :stuck_out_tongue_winking_eye:
