### ISSUE TITLE
[OpenSSL/1.0.2r] Error in build (macOS)

### ISSUE THREAD

**Issue by rafsouzap** [bincrafters/community#891]
### Package and Environment Details
  * Package Name/Version: **OpenSSL/1.0.2r**
  * Operating System+version: **macOS Mojave**
  * Compiler+version: **clang 10**
  * Conan version: **Conan 1.18.0**
  * Python version: **Python 3.7.0**

### Conan profile
```
[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=10.0
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
I only put it into my conanfile.py and execute conan:

`self.requires('OpenSSL/1.0.2r@conan/stable')`

### Logs (Include/Attach if Applicable)
```
OpenSSL/1.0.2r@conan/stable: Applying build-requirement: darwin-toolchain/1.0.0@ezored/stable
OpenSSL/1.0.2r@conan/stable: WARN: Build folder is dirty, removing it: /Users/rafaeldepaula/.conan/data/OpenSSL/1.0.2r/conan/stable/build/a4ee6ef06b693e82242757a353a9fb1b411a9756
OpenSSL/1.0.2r@conan/stable: Copying sources to build folder
OpenSSL/1.0.2r@conan/stable: Building your package in /Users/rafaeldepaula/.conan/data/OpenSSL/1.0.2r/conan/stable/build/a4ee6ef06b693e82242757a353a9fb1b411a9756
OpenSSL/1.0.2r@conan/stable: Generator txt created conanbuildinfo.txt
OpenSSL/1.0.2r@conan/stable: Calling build()
OpenSSL/1.0.2r@conan/stable: ['"debug-darwin64-x86_64-cc"', 'no-shared', '--prefix=/Users/rafaeldepaula/.conan/data/OpenSSL/1.0.2r/conan/stable/package/a4ee6ef06b693e82242757a353a9fb1b411a9756', '--openssldir=/Users/rafaeldepaula/.conan/data/OpenSSL/1.0.2r/conan/stable/package/a4ee6ef06b693e82242757a353a9fb1b411a9756/res', 'no-unit-test', 'no-tests', '-fPIC', '-isysroot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk', '-mmacosx-version-min=10.9', '-arch', 'x86_64', '-m64', '-g', '--sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk', '--with-zlib-include="/Users/rafaeldepaula/.conan/data/zlib/1.2.11/conan/stable/package/751155b1cf7e608f3239f8ff5bef0225178bb391/include"', '--with-zlib-lib="/Users/rafaeldepaula/.conan/data/zlib/1.2.11/conan/stable/package/751155b1cf7e608f3239f8ff5bef0225178bb391/lib"']
target already defined - debug-darwin64-x86_64-cc (offending arg: x86_64)
OpenSSL/1.0.2r@conan/stable:
OpenSSL/1.0.2r@conan/stable: ERROR: Package 'a4ee6ef06b693e82242757a353a9fb1b411a9756' build failed
OpenSSL/1.0.2r@conan/stable: WARN: Build folder /Users/rafaeldepaula/.conan/data/OpenSSL/1.0.2r/conan/stable/build/a4ee6ef06b693e82242757a353a9fb1b411a9756
ERROR: OpenSSL/1.0.2r@conan/stable: Error in build() method, line 492
	self._make()
while calling '_make', line 464
	self.run('{perl} ./Configure {args}'.format(perl=self._perl, args=args), win_bash=self._win_bash)
	ConanException: Error 255 while executing perl ./Configure "debug-darwin64-x86_64-cc" no-shared --prefix=/Users/rafaeldepaula/.conan/data/OpenSSL/1.0.2r/conan/stable/package/a4ee6ef06b693e82242757a353a9fb1b411a9756 --openssldir=/Users/rafaeldepaula/.conan/data/OpenSSL/1.0.2r/conan/stable/package/a4ee6ef06b693e82242757a353a9fb1b411a9756/res no-unit-test no-tests -fPIC -isysroot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.9 -arch x86_64 -m64 -g --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk --with-zlib-include="/Users/rafaeldepaula/.conan/data/zlib/1.2.11/conan/stable/package/751155b1cf7e608f3239f8ff5bef0225178bb391/include" --with-zlib-lib="/Users/rafaeldepaula/.conan/data/zlib/1.2.11/conan/stable/package/751155b1cf7e608f3239f8ff5bef0225178bb391/lib"
```

**Comment by SSE4** [comment]
hi @rafsouzap 
thanks for the report. I've pushed the fix: https://github.com/conan-community/conan-openssl/commit/2f5d3c28d57a25e133859cff719084fb2efd124f
please give a new try and lemme know

**Comment by rafsouzap** [comment]
hi @SSE4
when I use OpenSSL/1.0.2s@conan/stable version another error occurs

ERROR: OpenSSL/1.0.2s@conan/stable: Error in build() method, line 492 self._make() while calling '_make', line 464 self.run('{perl} ./Configure {args}'.format(perl=self._perl, args=args), win_bash=self._win_bash) ConanException: Error 255 while executing perl ./Configure "debug-darwin64-x86_64-cc" no-shared --prefix=/Users/rafaeldepaula/.conan/data/OpenSSL/1.0.2s/conan/stable/package/a4ee6ef06b693e82242757a353a9fb1b411a9756 --openssldir=/Users/rafaeldepaula/.conan/data/OpenSSL/1.0.2s/conan/stable/package/a4ee6ef06b693e82242757a353a9fb1b411a9756/res no-unit-test no-tests -fPIC -isysroot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.9 -arch x86_64 -m64 -g --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk --with-zlib-include="/Users/rafaeldepaula/.conan/data/zlib/1.2.11/conan/stable/package/751155b1cf7e608f3239f8ff5bef0225178bb391/include" --with-zlib-lib="/Users/rafaeldepaula/.conan/data/zlib/1.2.11/conan/stable/package/751155b1cf7e608f3239f8ff5bef0225178bb391/lib"

**Comment by SSE4** [comment]
it was confirmed by @rafsouzap as fixed in slack
