### ISSUE TITLE
[OpenSSL/1.0.2r] Error in build (iOS)

### ISSUE THREAD

**Issue by rafsouzap** [bincrafters/community#892]
### Package and Environment Details
  * Package Name/Version: **OpenSSL/1.0.2r**
  * Operating System+version: **macOS Mojave**
  * Compiler+version: **clang 10**
  * Conan version: **Conan 1.18.0**
  * Python version: **Python 3.7.0**

### Conan profile
```
[settings]
arch=armv7
arch_build=x86_64
build_type=Debug
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=10.0
os=iOS
os.version=9.0
os_build=Macos
[options]
darwin-toolchain:enable_arc=None
darwin-toolchain:enable_bitcode=True
darwin-toolchain:enable_visibility=None
[build_requires]
[env]
```

### Logs (Include/Attach if Applicable)
```
OpenSSL/1.0.2r@conan/stable: Applying build-requirement: darwin-toolchain/1.0.0@ezored/stable
OpenSSL/1.0.2r@conan/stable: WARN: Build folder is dirty, removing it: /Users/rafaeldepaula/.conan/data/OpenSSL/1.0.2r/conan/stable/build/d36a622f61d98b444ec1de119fe6533b962869b5
OpenSSL/1.0.2r@conan/stable: Copying sources to build folder
OpenSSL/1.0.2r@conan/stable: Building your package in /Users/rafaeldepaula/.conan/data/OpenSSL/1.0.2r/conan/stable/build/d36a622f61d98b444ec1de119fe6533b962869b5
OpenSSL/1.0.2r@conan/stable: Generator txt created conanbuildinfo.txt
OpenSSL/1.0.2r@conan/stable: Calling build()
OpenSSL/1.0.2r@conan/stable:
OpenSSL/1.0.2r@conan/stable: ERROR: Package 'd36a622f61d98b444ec1de119fe6533b962869b5' build failed
OpenSSL/1.0.2r@conan/stable: WARN: Build folder /Users/rafaeldepaula/.conan/data/OpenSSL/1.0.2r/conan/stable/build/d36a622f61d98b444ec1de119fe6533b962869b5
ERROR: OpenSSL/1.0.2r@conan/stable: Error in build() method, line 492
	self._make()
while calling '_make', line 461
	args = " ".join(self._configure_args)
while calling '_configure_args', line 326
	args = ['"%s"' % (self._target if self._full_version >= "1.1.0" else self._ancestor_target),
while calling '_ancestor_target', line 309
	self.settings.os,
	TypeError: not enough arguments for format string
```

**Comment by SSE4** [comment]
hi @rafsouzap 
thanks for the report. I've pushed the fix: https://github.com/conan-community/conan-openssl/commit/2f5d3c28d57a25e133859cff719084fb2efd124f
please give a new try and lemme know

**Comment by rafsouzap** [comment]
hi @SSE4 
when I use OpenSSL/1.0.2s@conan/stable version another error occurs

`ERROR: OpenSSL/1.0.2s@conan/stable: Error in build() method, line 492
    self._make()
while calling '_make', line 464
    self.run('{perl} ./Configure {args}'.format(perl=self._perl, args=args), win_bash=self._win_bash)
    ConanException: Error 255 while executing perl ./Configure "debug-darwin64-x86_64-cc" no-shared --prefix=/Users/rafaeldepaula/.conan/data/OpenSSL/1.0.2s/conan/stable/package/a4ee6ef06b693e82242757a353a9fb1b411a9756 --openssldir=/Users/rafaeldepaula/.conan/data/OpenSSL/1.0.2s/conan/stable/package/a4ee6ef06b693e82242757a353a9fb1b411a9756/res no-unit-test no-tests -fPIC -isysroot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.9 -arch x86_64 -m64 -g --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk --with-zlib-include="/Users/rafaeldepaula/.conan/data/zlib/1.2.11/conan/stable/package/751155b1cf7e608f3239f8ff5bef0225178bb391/include" --with-zlib-lib="/Users/rafaeldepaula/.conan/data/zlib/1.2.11/conan/stable/package/751155b1cf7e608f3239f8ff5bef0225178bb391/lib"`
 `

**Comment by Croydon** [comment]
@rafsouzap It's fine for now, but please note for further issues that the correct issue tracker for OpenSSL related bugs is https://github.com/conan-community/community/issues

**Comment by SSE4** [comment]
it was confirmed by @rafsouzap as fixed in slack
