### ISSUE TITLE
[pugixml] Cross-compile fails for Android: No cmake_minimum_required set

### ISSUE THREAD

**Issue by William-Froelich** [bincrafters/community#893]
This builds fine with newer versions of cmake, but when using the cmake bundled with the android ndk, it will fail because cmake_minimum_required is not set.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: pugixml/1.9@bincrafters/stable
  * Operating System+version: OSX Mojave 10.14.6 (18G84)
  * Compiler+version: Android (5058415 based on r339409) clang version 8.0.2
  * Conan version: 1.17.2
  * Python version: 3.6.9
  * Cmake : Android SDK-bundled 3.10.2

### Conan profile 
```
10:16 $ conan install /Users/williamf3/projects/perseus/conan/conanfile.txt -pr /Users/williamf3/projects/perseus/conan/android_profile -s build_type=Debug -s compiler.libcxx=libc++ -s arch=armv7 -s arch_build=x86_64 -s os_build=Macos -g=cmake -g=cmake_paths -g=cmake_find_package -g=cmake --build=missing
Configuration:
[settings]
arch=armv7
arch_build=x86_64
build_type=Debug
compiler=clang
compiler.libcxx=libc++
compiler.version=8
os=Android
os.api_level=21
os_build=Macos
[options]
[build_requires]
*: android_ndk_installer/r20@bincrafters/stable
[env]
```

### Steps to reproduce (Include if Applicable)
```
conan install /Users/williamf3/projects/perseus/conan/conanfile.txt -pr /Users/williamf3/projects/perseus/conan/android_profile -s build_type=Debug -s compiler.libcxx=libc++ -s arch=armv7 -s arch_build=x86_64 -s os_build=Macos -g=cmake -g=cmake_paths -g=cmake_find_package -g=cmake --build=missing

conanfile.txt:
[requires]
pugixml/1.9@bincrafters/stable

```

### Logs (Include/Attach if Applicable)
```
CMake Error in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.15)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".


-- Configuring incomplete, errors occurred!
See also "/Users/williamf3/.conan/data/pugixml/1.9/bincrafters/stable/build/09b6d0611c0157cd1712a0c2156b6ae7368f7756/build_subfolder/CMakeFiles/
```

[CMakeOutput.log](https://github.com/bincrafters/community/files/3452692/CMakeOutput.log)
CMakeOutput.log".

**Comment by SSE4** [comment]
thanks for the report, pushed a fix: https://github.com/bincrafters/conan-pugixml/commit/29a66257d3e39775467be6804a711dc943213e64#diff-af3b638bc2a3e6c650974192a53c7291

**Comment by William-Froelich** [comment]
Thanks, how do I go about using the pugixml/1.9@bincrafters/testing package in the meanwhile?

**Comment by SSE4** [comment]
until it is uploaded, you may update locally:
```
git clone https://github.com/bincrafters/conan-pugixml.git
cd conan-pugixml
conan export . bincrafters/stable
```
but I think it should be available soon, e.g. tomorrow

**Comment by William-Froelich** [comment]
There's a typo in the commit. It should be cmake_minimum_required not make_minimum_required

**Comment by SSE4** [comment]
@William-Froelich  now changes are available on bintray

**Comment by William-Froelich** [comment]
@SSE4  thanks! I confirmed it working in my environment
