### ISSUE TITLE
[bincrafters-package-tools] build_shared is overriding kwargs passed

### ISSUE THREAD

**Issue by jmarrec** [bincrafters/community#895]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **bincrafters package tools, 0.18.0**

### Steps to reproduce (Include if Applicable)

build.py
```
from bincrafters import build_template_default

if __name__ == "__main__":

    builder = build_template_default.get_builder(build_policy="outdated",
                                                 upload_only_when_stable=False)
```

https://github.com/bincrafters/bincrafters-package-tools/blob/release/0.18.0/bincrafters/build_shared.py#L169

Should be `upload_when_stable = kwargs.get('upload_only_when_stable', get_upload_when_stable())` instead. Same of other kwargs probably.

**Comment by Croydon** [comment]
Is this done?

**Comment by jmarrec** [comment]
Fixed via https://github.com/bincrafters/bincrafters-package-tools/issues/25
