### ISSUE TITLE
[qt] Question: Copy all required libraries in one artifact folder

### ISSUE THREAD

**Issue by jgeudens** [bincrafters/community#897]
### Package and Environment Details (include every applicable attribute)
 * Package Name/Version: **conan-qt**
 * Operating System+version: **Windows 10 64bit**
 * Compiler+version: **MinGW-5.3**

### Question Description
I have used the conan-qt artifact as standalone toolchain for generating a static build of my application. I had an AppVeyor build which build the conan recipe to generate a static qt version. Then I zipped the resulting binaries (libraries). I could use this artifact with a MinGW compiler to compile my application on a random computer with the correct MinGW compiler.

This worked well until Qt v5.9.7. But when I build Qt v5.12.4 with openSSL, it generated several other libraries which are located in the .conan folder.  These files are required to compile my application. Is there a way to export all required libraries from the .conan folder in one folder which I can zip and use as standalone toolchain?

**Comment by ericLemanissier** [comment]
You can disable nearly all requirements of the qt package by using `openssl=False` and multiple `with_foo=False`. The only mandatory dependency is zlib (which is provided by MinGW too, so it should not be a problem if you don't include it).
If you need to be able to adapt to several sets of dependencies, I guess you can use `conan info` to get them, and assemble the binaries as you are currently doing. But you are trying to develop a feature which conan is able to provide. It would probably be easier to use conan all the way down to the computers compiling your application. Anyway, your question would probably be better answered on https://github.com/conan-io/conan/issues

**Comment by jgeudens** [comment]
Thank your information. And yes, this is proably a more general conan question.

It is possible to compile my application on the same computer as I have built my Qt toolchain (with conan). This work nicely. But the issue is that the complete artifacts of the Qt build are more than 2 GB and that the AppVeyor caching only allows 1 GB. So if I incorparate the complete conan build of Qt together with compiling my application. Every build would take much more time to complete, because Qt needs to compiled from source everytime.

**Comment by ericLemanissier** [comment]
did you try uploading the binaries to a remote (using `conan upload`) ? You can simply set up your bintray remote, make you appveyor build upload all binaries to this remote. then all the clients trying to compile should set up this remote (`conan remote add`) and conan will automatically notice that a binary is available for the qt package, and it will download it (if not already downloaded) instead of rebuilding it.

**Comment by jgeudens** [comment]
I'm very new to conan. I will try your suggestion. It sounds like this is exactly what is need.

**Comment by dmn-star** [comment]
>  Is there a way to export all required libraries from the .conan folder in one folder 

I use deploy generator for this.

from conanfile.txt
...
[generators]
deploy
...

**Comment by jgeudens** [comment]
Thank you for the suggestion. I will definitely try it, but currently I have some issue with my static conan qt build which I need to fix first.
