### ISSUE TITLE
[bincrafters-conventions] Remote option doesn't work

### ISSUE THREAD

**Issue by Croydon** [bincrafters/community#900]
bincrafters-conventions 0.7.8
Python 3.7.4

> $ bincrafters-conventions.exe --remote=bincrafters/conan-libmodplug --dry-run
[INFO]  2019-08-05 08:37:24 Clone project https://github.com/bincrafters/conan-libmodplug.git to C:\Users\Micha\AppData\Local\Temp\github9_ah1tuq\conan-libmodplug.git
[INFO]  2019-08-05 08:37:24 On branch testing/0.8.9.0
[WARNING]       2019-08-05 08:37:24 stat: path should be string, bytes, os.PathLike or integer, not NoneType
[INFO]  2019-08-05 08:37:24 On branch stable/0.8.9.0
[WARNING]       2019-08-05 08:37:24 stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by uilianries** [comment]
NIce bug, I didn't check Bincrafters Conventions on Windows. I'll check it later, thanks for reporting.

**Comment by SSE4** [comment]
didn't even know we had such an option, lol

**Comment by uilianries** [comment]
Yeah, usually I run locally, but that feature can save some time. It pushes automatically
