### ISSUE TITLE
[libcurl] embedded certificates are downloaded over an insecure connection

### ISSUE THREAD

**Issue by blastrock** [bincrafters/community#901]
### Package and Environment Details
  * Package Name/Version: **libcurl/7.64.1**

### Description

In the libcurl package, there is an option to embed the root CA certificates, however they are downloaded over an insecure connection according to this line: https://github.com/bincrafters/conan-libcurl/blob/testing/7.64.1/conanfile.py#L136 . Is there a reason why `verify` is false there?

**Comment by Croydon** [comment]
commits:
https://github.com/bincrafters/conan-libcurl/commit/d30b42b67599120ca129e25f2e54865dae63b057
https://github.com/bincrafters/conan-libcurl/commit/6f1150507752ea02590f862940959a84e20e4af2

**Comment by theirix** [comment]
Hmm, runs fine locally with `verify=True`. I change the testing branch to see if there are any build agents to blame for missing certs.

**Comment by blastrock** [comment]
Also, [this line just above](https://github.com/bincrafters/conan-libcurl/blob/testing/7.64.1/conanfile.py#L134) downloads the package from the same domain, and does the verification I suppose so it should just work.

**Comment by theirix** [comment]
Enabled verification in 7.64.1. Everything looks and buils fine.
