### ISSUE TITLE
[protobuf] Old gcc C ABI used in compiled library

### ISSUE THREAD

**Issue by begroettrup** [bincrafters/community#906]
### Report
I received a library apparently compiled with the old version of gcc when installing protobuf via `conan install protobuf/3.6.1@bincrafters/stable`.

Linking against protobuf produced linking errors of the kind 
```
undefined reference to `google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)'
```
Inspecting the library showed that the symbol was 
```
`google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::string const&, google::protobuf::io::CodedOutputStream*)'
```
instead.

Compiling protobuf from source (`conan install protobuf/3.6.1@bincrafters/stable -b`) solved the issue.

### Package and Environment Details
  * Package Name/Version: **protobuf/3.6.1**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **gcc-7.4.0**
  * Conan version: **conan 1.17.0**
  * Python version: **Python 3.6.8**

### Conan profile
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=7
compiler.libcxx=libstdc++11
build_type=Release
cuda=None
cudnn=None
[options]
[build_requires]
[env]

**Comment by bashbug** [comment]
We have the exact same problem! Building from source fixes it.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libprotobuf/3.6.1**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **gcc-7.4.0**
  * Conan version: **conan 1.12.3**
  * Python version: **Python 3.6.7**

### Conan profile
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=7
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]
```

### conanfile.txt
conanfile.txt
```
[requires]
protobuf/3.6.1@bincrafters/stable
protoc_installer/3.6.1@bincrafters/stable

[generators]
cmake_find_package
cmake_paths
```

### Logs
A lot of undefined reference during linking
```
...
test.pb.cc:(.text+0x141): undefined reference to `google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)'
positioning.pb.cc:(.text+0x199): undefined reference to `google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)'
lib.a(test.pb.cc.o): In function `test::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const':
test.pb.cc:(.text+0x231): undefined reference to `google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)'
lib.a(test.pb.cc.o): In function `test::InternalSerializeWithCachedSizesToArray(bool, unsigned char*) const':
test.pb.cc:(.text+0x650): undefined reference to `google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char*)'
test.pb.cc:(.text+0x680): undefined reference to `google::protobuf::io::CodedOutputStream::WriteStringWithSizeToArray(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char*)'
...
```

**Comment by uilianries** [comment]
@bashbug Your Conan profile is using **libstdc++**, but your CMake uses **libstdc++11** because you are running GCC7. You need to update your Conan profile or force `_GLIBCXX_USE_CXX11_ABI`

`conan profile update compiler.libcxx=libstdc++11 default`

More information here: https://docs.conan.io/en/latest/howtos/manage_gcc_abi.html#how-to-manage-the-gcc-5-abi

**Comment by uilianries** [comment]
@bashbug and @begroettrup Sorry, Now I see the problem. We used old CentOS images to build with gcc7 :man_facepalming: I gonna provide new packages for GCC7 ASAP. thanks for reporting

**Comment by uilianries** [comment]
Hi again! I've uploaded new packages for GCC7 (only x86_64, x86 is under construction right now). Please, update your local copy and try again.

**Comment by bashbug** [comment]
@uilianries works for us. Thanks for fixing it!

**Comment by uilianries** [comment]
This is a good question. I need to investigate, but my guess is CentOS 6 doesn't contain libstdc++11. That distro is 10 years old and we installed GCC 7 to build only installer package as cmake, bison, protoc ...

**Comment by begroettrup** [comment]
@uilianries Also works for us, thanks for fixing.

**Comment by uilianries** [comment]
Great! I'm closing this issue
