### ISSUE TITLE
[conan-cryptopp]: 8.1.0/testing doesn't build

### ISSUE THREAD

**Issue by William-Froelich** [bincrafters/community#908]
The testing/8.1.0 branch for conan-cryptopp is broken and has been since March.

I have a PR posted that I would like considered for inclusion at https://github.com/bincrafters/conan-cryptopp/pull/10  but I wasn't sure if I needed to post an issue here as well or not first.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **conan-cryptopp/8.1.0**
  * Operating System+version: **varied (OSX,  Linux. Windows)**
  * Compiler+version: **gcc, clang -- Multiple versions**

**Comment by uilianries** [comment]
Hi @William-Froelich I'm curious why did you close this issue? was it a false alarm?

**Comment by William-Froelich** [comment]
@uilianries I closed the issue because @SSE4  merged my open PR. Appveyor and Travis are green now.

I probably should have commented here that it is resolved now.

**Comment by uilianries** [comment]
@William-Froelich  Nice! Thanks for you feedback!
