### ISSUE TITLE
Question: libxslt  How to avoid app store (Apple) rejection?

### ISSUE THREAD

**Issue by dmn-star** [bincrafters/community#909]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libxslt/1.1.33@bincrafters/stable**
  * Operating System+version: **macOS Mojave 10.14.5**
  * Compiler+version: **Xcode 10.3**
  * Conan version: **Conan 1.18.0**
  * Python version: **Python 3.7.4**

### Question Description

I'm looking for the best way to do some strange things like renaming of xsltApplyStylesheet into my_xsltApplyStylesheet before I compile the libxslt package. 
 * Can I patch the source with Conan? 
 * Or should I make my own libxslt recipe?
 * Or can you make the bincrafters package app store conform?

_____

Apple answer:
 Non-public API usage - The app references non-public symbols in Frameworks: _xsltApplyStylesheet, _xsltFreeStylesheet, _xsltParseStylesheetDoc. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions.

**Comment by SSE4** [comment]
@dmn-star have you checked, if `libxslt` has a configure option to rename symbols?

**Comment by dmn-star** [comment]
Not yet. I want statically link all libs first. Maybe that'll help.

**Comment by madebr** [comment]
Maybe try recompiling the xslt library with hidden visibility instead of default?

**Comment by dmn-star** [comment]
@SSE4 Unfortunately I didn't find any options to rename symbols.

@madebr The functions are part of libxslt **_public_** interfaces. The hidden visibility will not help in this case. I like Apple's sense of humour.

**Comment by SSE4** [comment]
@dmn-star could you possibly check if solutions from the [stack-overflow](https://stackoverflow.com/questions/3640901/how-do-i-include-libxslt-in-my-iphone-app) help?
they use patch or sed to rename symbols, like `xslt*` -> `zxslt*`. if it helps, we can add something similar to our recipe.

**Comment by dmn-star** [comment]
Of course. I'll try it a little later.
