### ISSUE TITLE
Add -fPIC option to lzma

### ISSUE THREAD

**Issue by r-darwish** [bincrafters/community#91]
### Description of Problem, Request, or Question
When `lzma` is used as a shared object together with Boost built as a shared object, it has to be compiled with `-fPIC`. See [this failure ](https://travis-ci.org/bincrafters/conan-boost_iostreams/jobs/334411461#L4149 )for an example.

`bzip2` and `zlib` are [built with fPIC](https://github.com/lasote/conan-zlib/blob/5fcb5d0350fd59df18309b7852fb4f031c527b13/conanfile.py#L42) by default. We should probably do the same.

**Comment by solvingj** [comment]
Added by @SSE4
