### ISSUE TITLE
[qt] relpath.c fatal error

### ISSUE THREAD

**Issue by dinikolop** [bincrafters/community#911]
Tried to install qt, but got a fatal error
 
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.13.0**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **gcc-9.1.0**
  * Conan version: **conan 1.18.0**
  * Python version: **Python 3.6.8**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
```bash
conan install qt/5.13.0@bincrafters/stable -b missing
```

### Logs (Include/Attach if Applicable)
```bash
libpq/11.4@bincrafters/stable: 
libpq/11.4@bincrafters/stable: ERROR: Package '8e0939db49a1d312829524beb4d0b6824e47691d' build failed
libpq/11.4@bincrafters/stable: WARN: Build folder /home/dimitris/.conan/data/libpq/11.4/bincrafters/stable/build/8e0939db49a1d312829524beb4d0b6824e47691d
ERROR: libpq/11.4@bincrafters/stable: Error in build() method, line 79
	autotools.make()
	ConanException: Error 2 while executing make -j12
```

**Comment by ericLemanissier** [comment]
Could you please send the full log?
if you don't need PostgreSQL, you can simply use option `qt:with_pq=False`

**Comment by dinikolop** [comment]
Hello @ericLemanissier ! Thank you for your advice! I will close this ticket, because I opened another one (#912) where I reproduce the same problem but now with libpq, where the bug actually appears.
