### ISSUE TITLE
[wxWidgets] wx-config is not part of the package

### ISSUE THREAD

**Issue by kutschkem** [bincrafters/community#913]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **wxWidgets/3.1.1**
  * Operating System+version: **Linux Debian Stretch**

The wxWidgets recipe does not export [wx-config](https://wiki.wxwidgets.org/Wx-Config) to the package. This is however used by dependent libraries to figure out compiler flags needed.

**Comment by SSE4** [comment]
hi @kutschkem 
I think it's exposed, from the build [logs](https://travis-ci.com/bincrafters/conan-wxwidgets/jobs/224813478):
```
wxwidgets/3.1.2@bincrafters/testing package(): Packaged 2 files: wx-config, wxrc
```

**Comment by kutschkem** [comment]
Hmm ok I will try again with 3.1.2, with 3.1.1 it is not exposed.

**Comment by SSE4** [comment]
@kutschkem did it work for you with 3.1.2?
