### ISSUE TITLE
[cppzmq] Request for new version 4.4.1

### ISSUE THREAD

**Issue by gummif** [bincrafters/community#915]
### Package Details
  * Package Name: **cppzmq**
  * Latest available Version: **4.4.1**

The above mentioned version is newly released by the upstream project and not yet available within Bincrafters. Please add this version.

**Comment by uilianries** [comment]
The new branch is available:
https://github.com/bincrafters/conan-cppzmq/tree/stable/4.4.1

But you need to wait for CI job before updating your local copy:
https://travis-ci.com/bincrafters/conan-cppzmq/builds/123273904

**Comment by uilianries** [comment]
Done!

It's available for download:
https://bintray.com/bincrafters/public-conan/cppzmq%3Abincrafters/4.4.1%3Astable
