### ISSUE TITLE
Upstream Update: cryptopp 8.2.0

### ISSUE THREAD

**Issue by William-Froelich** [bincrafters/community#917]
### Package Details
  * Package Name: cryptopp
  * Latest available Version: 8.2.0

The above mentioned version is newly released by the upstream project and not yet available within Bincrafters. Please add this version.

I have a branch available at: https://github.com/William-Froelich/conan-cryptopp/tree/testing/8.2.0

**Comment by uilianries** [comment]
First try is ready, let's wait for CI result:

https://travis-ci.com/bincrafters/conan-cryptopp/builds/123419674
https://ci.appveyor.com/project/bincrafters/conan-cryptopp/builds/26730519

**Comment by uilianries** [comment]
Done!

Available for download: https://bintray.com/bincrafters/public-conan/cryptopp%3Abincrafters/8.2.0%3Astable

**Comment by William-Froelich** [comment]
Thanks!
