### ISSUE TITLE
[QT] Linux build failed

### ISSUE THREAD

**Issue by Morkxy** [bincrafters/community#918]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.13.0**
  * Operating System+version: **Linux Debian 9 x64**
  * Conan version: **conan 1.18.1**

# conan profile show default
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=6
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]conan profile show default
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=6
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]

Hello,
After fresh install of Debian 9 X86_64, i run this :
apt-get install build-essential
dpkg -i conan-ubuntu-64_1_18_1.deb 
conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
conan install qt/5.13.0@bincrafters/stable --build qt

And i have this error :

pcre/8.41@bincrafters/stable: Downloaded recipe revision 0
ERROR: Conflict in pcre/8.41@bincrafters/stable
    Requirement bzip2/1.0.8@conan/stable conflicts with already defined bzip2/1.0.6@conan/stable
    To change it, override it in your base requirements

(full trace in attachment)
[out.txt](https://github.com/bincrafters/community/files/3508732/out.txt)

Thank you :)

**Comment by ericLemanissier** [comment]
Could you please retry, now that https://github.com/bincrafters/conan-pcre2/pull/11 is merged?

**Comment by Morkxy** [comment]
Yes, it's works now
Thanks !
