### ISSUE TITLE
[libcurl] SSL peer certificate or SSH remote key was not OK

### ISSUE THREAD

**Issue by wouterbeek** [bincrafters/community#919]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libcurl/7.64.1**
  * Operating System+version: **Windows 10**
  * Compiler+version: **MSVC 19.22.27905 for x64**
  * Conan version: **conan 1.18.1**
  * Python version: **Python 3.7.3**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)

```
Configuration for profile default:

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

1. Create a project that uses `libcurl/7.64.1@bincrafters/stable` as a dependency.
2. Perform a simple HTTP GET request against a website that requires SSL support, e.g., `https://aap.nl`.
3. Observed the following error message:

```
SSL peer certificate or SSH remote key was not OK
```

### Workaround

Change the values for the options in the following way:

```python
    def config_options(self):
        if self.settings.os == "Windows":
            self.options["libcurl"].with_openssl = False
            self.options["libcurl"].with_winssl = True
        else:
            self.options["libcurl"].with_openssl = True
            self.options["libcurl"].with_winssl = False
```
With these options SSL requests work.

**Comment by theirix** [comment]
Hello, @wouterbeek ! We allow to build libcurl on Windows with winssl or openssl support. So the libcurl package has the option `libcurl:with_winssl` specifically for this purpose.

**Comment by wouterbeek** [comment]
@theirix Thanks for the info.  Then this is the intended behavior.
