### ISSUE TITLE
Upstream Update: GLM 0.9.9.5

### ISSUE THREAD

**Issue by ShadowMitia** [bincrafters/community#920]
### Package Details
  * Package Name: **glm**
  * Latest available Version: **0.9.9.5**

The above mentioned version is newly released by the upstream project and not yet available within Bincrafters. Please add this version.

**Comment by ShadowMitia** [comment]
Updated request as 0.9.9.6 isn't an official release yet.

**Comment by madebr** [comment]
There is already a [testing/0.9.9.5](https://github.com/bincrafters/conan-glm/tree/testing/0.9.9.5) branch

**Comment by SSE4** [comment]
`stable/0.9.9.5` was created. default branch was updated.

**Comment by ShadowMitia** [comment]
Thank you!
