### ISSUE TITLE
For libzip 1.5.2+ - bump bzip2 1.0.6 dependency to 1.0.8

### ISSUE THREAD

**Issue by solvingj** [bincrafters/community#922]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libzip /1.5.2+**

### Description of your feature
bump bzip2 1.0.6 dependency to 1.0.8

**Comment by uilianries** [comment]
consider it done!

**Comment by uilianries** [comment]
Done, it's available for download with bzip2/1.0.8
