### ISSUE TITLE
boost_mpi mpi dependency

### ISSUE THREAD

**Issue by KaiSzuttor** [bincrafters/community#923]
### Question Description
I could not find any dependency of ```boost_mpi``` on a mpi package like ```openmpi/3.0.0@bincrafters/stable```. I'm wondering how to use the ```boost_mpi``` package if a certain openmpi version is necessary.

**Comment by KaiSzuttor** [comment]
@solvingj could you please comment on that?

**Comment by solvingj** [comment]
In previous versions, we did have the conditional dependency, but it was in the `cycle_group_d`  package making it hard to find.   

https://github.com/bincrafters/conan-boost_cycle_group_d/blob/stable/1.68.0/conanfile.py#L77
In that particular example it's commented out, but it was there. 

Now it's implemented here, just in an even more abstracted far-off place: 
https://github.com/bincrafters/conan-boost_base/blob/testing/2.0.0/conanfile.py#L1440

Of note, we are still a fair distance away from releasing a stable version of 1.70.0.

**Comment by KaiSzuttor** [comment]
@solvingj thanks for your response!
so it's not possible to override the openmpi dependency. Do you know why it is not a direct dependency? I know of at least 1 project where it's mandatory to enforce a certain openmpi version.

**Comment by KaiSzuttor** [comment]
> you just want to override the version on the openmpi conan package?

yes

**Comment by solvingj** [comment]
Ah, in that case it's easy.  You can always override the version of any conan pacakge from any consuming recipe:

https://docs.conan.io/en/latest/reference/conanfile/methods.html#requirements

**Comment by KaiSzuttor** [comment]
are you sure this is also possible with build requirements?
