### ISSUE TITLE
Upstream Update: SQLiteCpp 2.4.0

### ISSUE THREAD

**Issue by prsolucoes** [bincrafters/community#925]
### Package Details
  * Package Name: **SQLiteCpp**
  * Latest available Version: **2.4.0**

The above mentioned version is newly released by the upstream project and not yet available within Bincrafters. Please add this version.

**Comment by uilianries** [comment]
Done:

https://github.com/bincrafters/conan-sqlitecpp/tree/stable/2.4.0
