### ISSUE TITLE
[qt] flag for installing opengl32sw.dll

### ISSUE THREAD

**Issue by Trafo** [bincrafters/community#926]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/12**
  * Operating System+version: **Windows 10**
  * Compiler+version: **msvc2017**
  * Conan version: **Conan 1.11.0**
  * Python version: **Python 3.7.0**

### Description of your feature
Qt is using in some circumstances his own Software Render (opengl32w.dll). But the problem of the conan receipt of qt is, that it will not be package/build. But this Software Render is needed under Windows if drivers of gpu is broken or not existent (virtual machine).

Can we add an extra flag and with this flag opengl32w.dll will be packaged as well?

bad Code:

```
url = "https://download.qt.io/development_releases/prebuilt/llvmpipe/windows/opengl32sw-64-mesa_12_0_rc2.7z"
filename = os.path.basename(url)
tools.download(url, filename)
Archive("opengl32sw-64-mesa_12_0_rc2.7z").extractall(".")
        
new_path = os.path.join(self.package_folder + "/bin", "opengl32sw.dll")
os.rename("opengl32sw.dll", new_path)
```

(need to distinguish the 32bit and 64 bit version)

Best regards,
Mathias

**Comment by ericLemanissier** [comment]
I don't know much about opengl32sw, but it looks like it is independent of qt : it does not use qt version numbers, it does not have a repo on https://code.qt.io. It does not have an influence neither on the compilation of Qt itself, nor on the compilation of application consuming qt. It just need to be available at run time.
So I think it should not be integrated in qt recipe, a separate recipe would be the proper vehicle for opengl32sw

**Comment by Trafo** [comment]
Yes I agree, but if you install Qt normally this dll will be their. Only with conan this .dll will not be provided.

**Comment by ericLemanissier** [comment]
the dll is there, but you still have to deploy it manually. It is not more complicated to add `opengl32sw`  to your requirements, than having a manual deploy step. 
It makes more sense to have sensible set of packages with sound separation between independent components than trying to replicate the content of binaries provided by the upstream library maintainer.
