### ISSUE TITLE
[libxml2] Provided FindLibXml2.cmake breaks with cmake_path generator

### ISSUE THREAD

**Issue by sjoubert** [bincrafters/community#930]
### Package and Environment Details
  * Package Name/Version: **libxml2/2.9.9@bincrafters/stable**
  * Operating System+version: **Linux Debian testing/11/Bullseye**
  * CMake version: **3.13.4**
  * Conan version: **conan 1.18.1**

### Conan profile
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=8
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce
conanfile.txt
```
[generators]
cmake_paths
[requires]
libxml2/2.9.9@bincrafters/stable
[options]
libxml2:shared=True
```
CMakeLists.txt
```
cmake_minimum_required(VERSION 3.13)
project(conan_test VERSION 0.1 LANGUAGES CXX)

include(${CMAKE_CURRENT_BINARY_DIR}/conan_paths.cmake)
find_package(LibXml2 REQUIRED)

add_executable(main main.cpp)
target_link_libraries(main PUBLIC ${LIBXML2_LIBRARY})
```
```
$ cmake ..
-- The CXX compiler identification is Clang 8.0.1
-- Check for working CXX compiler: /usr/lib/ccache/clang++-8
-- Check for working CXX compiler: /usr/lib/ccache/clang++-8 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
LOOK FOR  IN 
** LIBXML2 ALREADY FOUND BY CONAN!
** FOUND XML2:  LIBXML2_LIBRARY-NOTFOUND
** FOUND XML2 INCLUDE:  LIBXML2_INCLUDE_DIR-NOTFOUND
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBXML2_LIBRARY (ADVANCED)
    linked by target "main" in directory /home/sylvain/test/conan

-- Configuring incomplete, errors occurred!
See also "/home/sylvain/test/conan/build/CMakeFiles/CMakeOutput.log".
```

It appears that the provided `FindLibXml2.cmake` does not work well in the context of this generator. When using `cmake_path` I would expect the Find package from CMake to be found and used.
Removing this file from the conan package gives me a correct behavior (at least the one I expect)

**Comment by uilianries** [comment]
Hi @sjoubert ! Thanks for reporting!

I gonna take a look on this.

**Comment by uilianries** [comment]
Hi @sjoubert ! I created a new PR with FindLibXml2.cmake deletion. 

https://github.com/bincrafters/conan-libxml2/pull/21

**Comment by dmn-star** [comment]
Are you sure _**cmake**_ generator is still working right if you deleted FindLibXml2.cmake ?

**Comment by uilianries** [comment]
Yes! The file is from an old approach. Many other projects used to have a custom FindXXX.cmake file. But you don't need anymore since our support is much better. 

Only few projects requires a custom Find file, as protobuf and GTest, because they offer extra CMake macros.

**Comment by dmn-star** [comment]
Thanks for the clarification.

**Comment by uilianries** [comment]
Hi @sjoubert and @dmn-star !

A new version is available for download. At this moment, only Windows and part of Linux had been uploaded, we are waiting for OSX CI jobs. Please, update your local copy and try again.

**Comment by sjoubert** [comment]
Worked perfectly, thanks for the quick fix!
