### ISSUE TITLE
[bincrafters-conventions] Support a custom in-line annoation to prevent newer compiler jobs getting added

### ISSUE THREAD

**Issue by Croydon** [bincrafters/community#933]
Bincrafters-conventions is adding new CI jobs for newer compiler versions automatically.

If the software isn't supporting those compiler versions upstream this is undesired.
If you would remove this CI jobs manually they would get re-added the next time.

I'm planning to introduce some light-weight custom in-line annotation within the Travis/AppVeyor/AZP files to prevent this from happening.

This should only ever be used when the compiler versions aren't supported upstream.

**Comment by uilianries** [comment]
Nice!
