### ISSUE TITLE
[libcurl] invalid cacert.pem path for custom_cacert option

### ISSUE THREAD

**Issue by apanloco** [bincrafters/community#934]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libcurl/7.64.1@bincrafters/stable**
  * Operating System+version: **Ubuntu Linux 18.09**
  * Compiler+version: **gcc version 8.3.0 (Ubuntu 8.3.0-6ubuntu1~18.10.1)**
  * Docker image: **?**
  * Conan version: **Conan version 1.15.0**
  * Python version: **Python 2.7.15+**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)

Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=8
build_type=Release
compiler.libcxx=libstdc++11
[options]
[build_requires]
[env]

### Steps to reproduce (Include if Applicable)

Build libcurl with the option custom_cacert = True. You will see this in the log:
  ca cert bundle:   cacert.pem   (warning: certs not found)

The reason is that the cacert.pem is downloaded one level below the libcurl root. If you manually run ./configure ... with 
'--with-ca-bundle=../cacert.pem'
instead of
'--with-ca-bundle=cacert.pem'
this will show in the log instead:
  ca cert bundle:   ../cacert.pem

### Logs (Include/Attach if Applicable)
(attached!)

**Comment by theirix** [comment]
Currently, the `custom_cacert` option does not make sense and it is considered as a legacy option. Typical usage for `--with-ca-bundle` flag is to specify a custom bundle somewhere in a filesystem (for example, `/etc/ssl/cert.pem`). Pointing to a `cacert.pem` inside a Conan build directory that was previously downloaded by a Conan recipe is not useful. If it is needed to bake a path to a certificate store, it should be specified as an absolute path (currently not supported by options). So it is much easier to manage a custom certificate store for a Conan package at runtime.
