### ISSUE TITLE
Upstream Update: fmt 6.0.0

### ISSUE THREAD

**Issue by kaptenhonek** [bincrafters/community#937]
### Package Details
  * Package Name: **fmt**
  * Latest available Version: **6.0.0**

The above mentioned version is newly released by the upstream project and not yet available within Bincrafters. Please add this version.

**Comment by Croydon** [comment]
Since fmt is now included in the Conan Center Index, I'm closing this in favor of https://github.com/conan-io/conan-center-index/issues/69

Please migrate from `fmt/x.x.x@bincrafters/stable` to `fmt/5.3.0` (or newer when available) when you can
