### ISSUE TITLE
[qt] Build fails due to pcre and bzip conflict

### ISSUE THREAD

**Issue by planetmarshall** [bincrafters/community#939]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.12.4@bincrafters/stable**
  * Operating System+version: **Linux Ubuntu 19.04**
  * Compiler+version: **clang-8**
  * Conan version: **conan 1.18.0**
  * Python version: **Python 3.7.3**

### Conan profile

```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=clang
compiler.version=8
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]
CC=/usr/bin/clang-8
CXX=/usr/bin/clang++-8
```

### Steps to reproduce (Include if Applicable)

```
cd conan-qt
conan create . bincrafters/stable
```

### Logs (Include/Attach if Applicable)

```
ERROR: Conflict in pcre/8.41@bincrafters/stable
    Requirement bzip2/1.0.8@conan/stable conflicts with already defined bzip2/1.0.6@conan/stable
    To change it, override it in your base requirements
```

**Comment by ericLemanissier** [comment]
Can you call `conan info --graph graph.html .` in order to find which package requires `bzip2/1.0.6@conan/stable` ?

**Comment by ericLemanissier** [comment]
also, can you try to use the `-u` argument, in order to update the recipes if needed

**Comment by planetmarshall** [comment]
I can't run `conan info` because of the conflict error. `conan create -u` makes no difference.

**Comment by planetmarshall** [comment]
It's `pcre2/10.32@bincrafters/stable` that has the dependency on bzip 1.0.6. It's conflicting with freetype.

```
> conan info freetype/2.10.0@bincrafters/stable -n requires

bzip2/1.0.8@conan/stable
freetype/2.10.0@bincrafters/stable
    Requires:
        libpng/1.6.37@bincrafters/stable
        zlib/1.2.11@conan/stable
        bzip2/1.0.8@conan/stable
libpng/1.6.37@bincrafters/stable
    Requires:
        zlib/1.2.11@conan/stable
zlib/1.2.11@conan/stable
```

```
>  conan info pcre2/10.32@bincrafters/stable -n requires

bzip2/1.0.6@conan/stable
pcre2/10.32@bincrafters/stable
    Requires:
        zlib/1.2.11@conan/stable
        bzip2/1.0.6@conan/stable
zlib/1.2.11@conan/stable
```

**Comment by planetmarshall** [comment]
PR here - https://github.com/bincrafters/conan-qt/pull/36

**Comment by ericLemanissier** [comment]
pcre2/10.32 seems to require bzip2/1.0.8 already : https://github.com/bincrafters/conan-pcre2/blob/stable/10.32/conanfile.py#L52

**Comment by planetmarshall** [comment]
OK, I've found the issue. I have a cached copy of the old pcre2 recipe on another remote.
