### ISSUE TITLE
[libpng] download sources fails

### ISSUE THREAD

**Issue by IceflowRE** [bincrafters/community#940]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libpng/1.6.37**

```
conan install libpng/1.6.37@bincrafters/stable --build
```

```
libpng/1.6.37@bincrafters/stable: Configuring sources in C:\Users\iceflower\.conan\data\libpng\1.6.37\bincrafters\stable\source
ERROR: Error 500 downloading file https://sourceforge.net/projects/libpng/files/libpng16//1.6.37/libpng-1.6.37.tar.gz
Waiting 5 seconds to retry...
ERROR: libpng/1.6.37@bincrafters/stable: Error in source() method, line 40
        sha256="daeb2620d829575513e35fecc83f0d3791a620b9b93d800b763542ece9390fb4")
        ConanException: Error 500 downloading file https://sourceforge.net/projects/libpng/files/libpng16//1.6.37/libpng-1.6.37.tar.gz
```

Probably it is just temporary, but no hints in that direction. I will check tomorrow again.

**Comment by uilianries** [comment]
Hi @IceflowRE !

Thanks for reporting, but is sounds be an internal error from sourceforge. For the future, we can create a copy of source files to Bintray.

Anyway, I'll check this error. Thanks again.

**Comment by uilianries** [comment]
I sent an email to SourceForge support. Even the .tar.xz package is not available. I'll try to find some mirror.

**Comment by uilianries** [comment]
Hi @IceflowRE !

I added a new mirror in the recipe. It's working now, but you need to wait for CI service until upload the package
