### ISSUE TITLE
Upstream Update: harfbuzz 2.6.1

### ISSUE THREAD

**Issue by IceflowRE** [bincrafters/community#941]
### Package Details
  * Package Name: **harfbuzz**
  * Latest available Version: **2.6.1**

The above mentioned version is newly released by the upstream project and not yet available within Bincrafters. Please add this version.

Is likely the solution for #869 .

**Comment by Croydon** [comment]
macOS is failing right now https://travis-ci.com/bincrafters/conan-harfbuzz/builds/126183656 🤔

**Comment by uilianries** [comment]
@Croydon it's a bug from upstream ...

I tried to build by old style cd source_folder; mkdir build; cd build; cmake ..; cmake --build .

Same error

However, the author uses the autogen.sh script to build on MacOS:
https://circleci.com/gh/harfbuzz/harfbuzz/110371

I gonna open an issue to report this case

**Comment by Croydon** [comment]
Harfbuzz 2.6.1 is now available with an applied upstream patch to fix macOS
