### ISSUE TITLE
Inclusion Request: Google Crashpad

### ISSUE THREAD

**Issue by reneme** [bincrafters/community#942]
### Package Details
  * Package Name: **crashpad**
  * Operating Systems+versions: **Windows, macOS**
  * Compiler support: **all**
  * Conan recipe repository: **https://github.com/reneme/conan-crashpad**

### Inclusion request
  * Fill all checkboxes with x if you agree with the statement or if it applies to your Conan recipe
  * [x] I want that my Conan recipe is getting included into the Bincrafters organisation
  * [x] I understand that if my request is accepted we are cloning your repository with all its history into Bincrafters, adapt some configurations and meta data if needed, and publishing it under the Bincrafters name and accounts
  * [x] I have used the Bincrafters templates to develop my Conan recipe - https://github.com/bincrafters/templates
  * [x] My Conan recipe and all parts of it are licensed under the MIT license - https://choosealicense.com/licenses/mit/
    * Bincrafters are releasing all recipes under MIT license. If you want to have your recipe within Bincrafters we kindly ask you to do the same
    * it is okay if your test_package contains code from the upstream project under the upstream project's license, as long as it is clearly mentioned within the test_package files
  * [x] My Conan recipe covers (at least) the latest stable version which is available for the package
  * [x] I know that my Conan recipe is working on all operating system and compilers mentioned above right now
    * if not: please provide here links to your CI platforms and / or build logs and describe the problems you encounter
  * [x] I'm willing to help to maintain the recipe even after it is included into Bincrafters

The recipe refers to a (fairly old and presumably abandoned) `depot_tools_installer` build dependency. At least for me, it did not build with it. Instead, I created a [simplified spike](https://github.com/reneme/conan-depot_tools_installer) for the `depot_tools_installer` recipe. With that, I can successfully build and test the `crashpad` recipe and integrate it into our software product. We are currently in the early stages of migrating to `crashpad`, so changes to this recipe are likely.

Chromium comes with its own build system toolchain that gave us quite some headache while putting this recipe together. Any input on how to deal with that more elegantly is warmly welcome.

Note that Google `crashpad` does not issue specific releases. Right now, I pinned the recipe to the revision that is released with the latest stable build of Chrome. Not sure when and how often the recipe would need to be updated.

### Checklist for the Bincrafters team
  * Ignore this if you are not part of the Bincrafters team
  * [x] There is no such Conan package yet in conan-center, conan-community or Bincrafters
  * [x] The project is either popular or deserves to be maintained for another good reason (we can't package every single project out there)
  * [x] [bincrafters-conventions](https://github.com/bincrafters/bincrafters-conventions) reports no complains; the recipe fulfills our general quality requirements and conventions
  * [ ] The recipe is cloned into our organisation; CI is enabled and configurated and succeeds
  * [x] There is a branch protection rule for `stable/*` branches, which requires a pull request with at least one approval first before things can get published
  * Considering granding the inclusion request author push rights to the recipe repository (there is no guarantee that everyone is getting push rights, we decide this on a case-to-case base)

**Comment by uilianries** [comment]
Hi @reneme ! I'm curious how did you test this recipe ...

depot_tools_installer is broken for Python 3, and Conan doesn't work on Python 2.

**Comment by reneme** [comment]
So far, we did functional tests both with the included `test_package` and by integrating crashpad into our application with it. Automated CI tests are still a todo. I was hoping for some help from the bincrafters community with this. Do you have any pointers for where we can start?

Regarding Python 2/3: I stumbled over that while trying to build this recipe on Linux earlier today. Is there an idiomatic way to force `depot_tools` into using Python 2, even though the host system runs Python 3? I'm not exactly experienced with the Chromium toolchain, yet. However, I believe that they provide their own Python 2 redistributable.

**Comment by Croydon** [comment]
Our latest consensus was that we don't to commit-based versioning anymore, but rather date based versioning https://bincrafters.readthedocs.io/en/latest/using_packages.html#packages-without-official-releases

@reneme So please change the version to the date of the commit it builds in a `YYYYMMDD` format

**Comment by reneme** [comment]
> So please change the version to the date of the commit it builds in a YYYYMMDD format

Done.

**Comment by reneme** [comment]
@uilianries I [opened a PR](https://github.com/bincrafters/conan-crashpad/pull/2) that fixes the remaining CI issues and now builds successfully on macOS with Xcode 8.3, 9, 9.4 and 10.3 as well as Windows with VS 2017 and 2019.

I deliberately disabled builds on Linux for now. On the one Crashpad claims only basic support for Linux anyway and on the other hand it renders fairly complicated to build it due to Crashpad's build system depending on Python 2. I hope that Google's `depot_tools` will soon switch to Python 3.

If lacking Linux support is not an issue, I would consider the package complete and ready for further review and hopefully inclusion.

**Comment by reneme** [comment]
Unfortunately on Linux this still does not work out of the box because depot_tools don't work with Python3. I would suggest to wait for Google to fix their code for Python3. Otherwise, I believe the recipe is functional now. What do you think?

PS: I will open a PR for the latest version packaged in Chromium 77.0.3865.90 in the next few hours.

**Comment by uilianries** [comment]
GO ahead with the recipe, we can update later with full support from Google. If you need this recipe, please, submit the PR. Also, if the project doesn't offer a good support for Linux, is not our work patching the recipe, so let's wait for linux and deploy what we have for now.

**Comment by reneme** [comment]
Thanks for the commit access on the bincrafters repository!
What is the policy though? Do I just push a stable branch?

**Comment by Croydon** [comment]
@reneme You can freely push into `testing/` branches 
For `stable/` branches GitHub should enforce you to create a pull request. Even I believe the first push to create the branch might actually work without 🤔 

Independent from GitHub's behaviour please create pull request for the `stable/` branches

**Comment by reneme** [comment]
Thanks for the guidance. [PR is open](https://github.com/bincrafters/conan-crashpad/pull/5) and waiting for CI/review.

**Comment by reneme** [comment]
Done.
