### ISSUE TITLE
[depot_tools_installer] Incompatible with Python3

### ISSUE THREAD

**Issue by uilianries** [bincrafters/community#943]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **depot_tools_installer/master@bincrafters/stable**
  * Operating System+version: **Linux Majaro 18**
  * Compiler+version: **gcc-9.1**
  * Conan version: **conan 1.18.1**
  * Python version: **Python 3.7.2**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)

```
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

    git clone https://github.com/reneme/conan-crashpad
    cd conan-crashpad
    conan create .

### Logs (Include/Attach if Applicable)

```
crashpad/ee1d512: Applying build-requirement: depot_tools_installer/master@bincrafters/stable
crashpad/ee1d512: Applying build-requirement: ninja_installer/1.9.0@bincrafters/stable
crashpad/ee1d512: Configuring sources in /home/uilian/.conan/data/crashpad/ee1d512/_/_/source
Traceback (most recent call last):
  File "/home/uilian/.conan/data/depot_tools_installer/master/bincrafters/stable/package/cb054d0b3e1ca595dc66bc2339d40f1f8f04ab31/gclient.py", line 95, in <module>
    import urlparse
ModuleNotFoundError: No module named 'urlparse'
ERROR: crashpad/ee1d512: Error in source() method, line 53
	self.run("gclient config --spec=\"%s\"" % self._make_spec())
	ConanException: Error 1 while executing gclient config --spec="solutions=[{\"url\": \"https://chromium.googlesource.com/crashpad/crashpad@ee1d5124a2bfec578a1474b048cf934d92dcf7ba\", \"managed\": False, \"name\": \"crashpad\"}]"
```

**Comment by Croydon** [comment]
It is not our job to fix issues which aren't fixed upstream

Having a quick look into the commit history they do actively work on getting it Python 3 compatible.

https://chromium.googlesource.com/chromium/tools/depot_tools/+log

_______________

I'm noticing that we have only a master version, we should probably switch to a date based versioning?

**Comment by Croydon** [comment]
@reneme Maybe depot tools is now ready? 🤔  https://chromium.googlesource.com/chromium/tools/depot_tools/+/0e85f633c7c4364f4d616e9e13dce2c9a9dd518e

**Comment by Croydon** [comment]
I have updated the version, but AppVeyor throws an error which I can't reproduce locally on Windows with Python 3: https://ci.appveyor.com/project/bincrafters/conan-depot-tools-installer/builds/27446477#L282

Any ideas?

**Comment by Tymolc** [comment]
I'm trying this too and also can't reproduce the error, however, the last couple of builds failed the same way, so at least this is not related the new depot_tools version.
From what I can see, [this change](https://github.com/bincrafters/conan-depot_tools_installer/commit/812f936ba06d74391dc3a7cd365eac0073e620d3#diff-2b1d42f71f22b7ea0412d7602dec166fR35) MIGHT be responsible, but I don't really understand why this would work locally and not on Appveyor ... :/
Using the updated depot_tools, I can successfully build crashpad on Mac and Windows with Python 3.7.

**Comment by uilianries** [comment]
Maybe it's using relative path. I'll revert that change ...

**Comment by reneme** [comment]
> I have updated the version, but AppVeyor throws an error which I can't reproduce locally

Same here. Locally this works just fine for me as well. I assume that the "Invalid Argument" error code might be misleading. Some random google search brought up [an AppVeyor build](https://ci.appveyor.com/project/matysek/pyinstaller/build/531/job/d1y7x17k0xvil164#L3605) where a `self.outfile.flush()` failed with `OSError: [Errno 22] Invalid argument`. `.flush()` doesn't even have arguments.

Maybe there is some configuration in the AppVeyor setup that bites us here.

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "C:\Python34\lib\site-packages\execnet\gateway_base.py", line 984, in _send
INTERNALERROR>     message.to_io(self._io)
INTERNALERROR>   File "C:\Python34\lib\site-packages\execnet\gateway_base.py", line 430, in to_io
INTERNALERROR>     io.write(header+self.data)
INTERNALERROR>   File "C:\Python34\lib\site-packages\execnet\gateway_base.py", line 397, in write
INTERNALERROR>     self.outfile.flush()
INTERNALERROR> OSError: [Errno 22] Invalid argument
```

**Comment by reneme** [comment]
Another suspicious thing: There are several builds that failed ([#1](https://ci.appveyor.com/project/bincrafters/conan-depot-tools-installer/builds/27446477#L282), [#2](https://ci.appveyor.com/project/bincrafters/conan-depot-tools-installer/builds/27506808#L284), [#3](https://ci.appveyor.com/project/bincrafters/conan-depot-tools-installer/builds/27506810#L280)) that all fail with the same error when trying to open `cbuildbot`. Which neither appears special in any way nor is it the lexically "first" file in that directory.

**Comment by reneme** [comment]
> Another suspicious thing: There are several builds that failed (#1, #2, #3) that all fail with the same error when trying to open cbuildbot. Which neither appears special in any way nor is it the lexically "first" file in that directory.

Turns out: The packaging step actually copies a few files and then gets stuck at `cbuildbot`:
https://ci.appveyor.com/project/bincrafters/conan-depot-tools-installer/builds/27521120#L278

Before, the following files are already copied:

```
    .gitattributes 
    .gitignore 
    .style.yapf 
    .vpython3 
    annotated_gclient.py 
    auth.py 
    autoninja 
    autoninja.bat 
    autoninja.py 
    bb 
    bb.bat 
    breakpad.py 
    buildbucket.py 
    licenses/
        LICENSE 
```

**Comment by reneme** [comment]
Turns out, `cbuildbot` is a symlink. And further [turns out](https://ci.appveyor.com/project/bincrafters/conan-depot-tools-installer/builds/27521744#L319):
```
conans.errors.ConanException: The file is a broken symlink, verify that you are packaging the needed destination files: 'C:\.conan\13f4ac\1\cbuildbot'.You can skip this check adjusting the 'general.skip_broken_symlinks_check' at the conan.conf file.
```

**Comment by Tymolc** [comment]
[This check](https://github.com/conan-io/conan/pull/4991#discussion_r277249448) came in in April.

**Comment by reneme** [comment]
We printed [the whole content of the `package_folder`](https://ci.appveyor.com/project/bincrafters/conan-depot-tools-installer/builds/27524548#L279): Both the `cbuildbot` symlink and its (relative) destination `support/chromite_wrapper` are copied and reside where they should be. No idea why [os.path.exists() in conan/manifest.py](https://github.com/conan-io/conan/blob/64adf71cc691ef9c53aaf1331b8a9db0a89abe84/conans/model/manifest.py#L37) returns `False`. In our view, the symlink is valid.

**Comment by Tymolc** [comment]
Do we know what kind of Windows Appveyor is running? We just checked and found out, that `cbuildbot`  is indeed _not_ a symlink on our local Windows machine. Might be some kind of Windows 7 vs Windows 10 behaviour.

**Comment by reneme** [comment]
> We just checked and found out, that cbuildbot is indeed not a symlink on our local Windows machine.

In fact, even the `source_subfolder` does not contain a symlinks locally. Hence, the root cause of the problem is actually `tools.get()`. Locally, this seems to handle symlinks by copying the destination file in-lieu of the symlinks. While on AppVeyor it preserves the symlinks, which then causes the above described issues later on.

**Comment by reneme** [comment]
Probably digging deeper than we should, but this is what happens in [Python's "tarfile.py"](https://github.com/python/cpython/blob/a694f2394881fb68b5646061ded01fff6dc47778/Lib/tarfile.py#L2221):

```python
def makelink(self, tarinfo, targetpath):
    try:
        # For systems that support symbolic and hard links.
        if tarinfo.issym():
            os.symlink(tarinfo.linkname, targetpath)
        else:
            # See extract().
            if os.path.exists(tarinfo._link_target):
                os.link(tarinfo._link_target, targetpath)
            else:
                self._extract_member(self._find_link_target(tarinfo),
                                     targetpath)
    except symlink_exception:
        try:
            self._extract_member(self._find_link_target(tarinfo),
                                 targetpath)
        except KeyError:
            raise ExtractError("unable to resolve link inside archive")
```

Locally, `os.symlink()` throws `OSError: symbolic link privilege not held` and hence falls back to duplicating the destination file. On AppVeyor, we apparently hold this privilege and run the issue detailed above.

**Comment by reneme** [comment]
Bottom line: Windows 10 can "sort of" deal with symlinks, but it seems to be broken. In fact, if we open an _administrator_ command prompt, `tools.get()` the tarball of `depot_tools` and then try to run `python package/cbuildbot` (which symlinks to a python script) it yells:

```
python.exe: can't open file 'package/cbuildbot': [Errno 22] Invalid argument
```

Ouch!

**Comment by reneme** [comment]
The pull request above works around the issue. 🎉

**Comment by uilianries** [comment]
Version  stable/20190909  is ready and available! Thanks all for helping!

**Comment by reneme** [comment]
After hijacking this ticket for a build issue on Windows (sorry for that): Here are the (apparent) umbrella-tickets for chromium’s migration to Python 3:

* [Make our code work with Python 3](https://bugs.chromium.org/p/chromium/issues/detail?id=942720)
* [Support Python 3 for Chromium development (in src.git)](https://bugs.chromium.org/p/chromium/issues/detail?id=941669) (probably most relevant for this ticket)

**Comment by Croydon** [comment]
[Issue 984182: ☂ Make depot_tools Python 3 compatible](https://bugs.chromium.org/p/chromium/issues/detail?id=984182)

**Comment by reneme** [comment]
Apparently the depot_tools repo switched to Python3 by default.
Related commits:

* [Reland "depot_tools: Run using Python 3 by default."](https://chromium.googlesource.com/chromium/tools/depot_tools.git/+/17aaea21d40dc178638a5e295541fbd8757811c1)
* [Make Python 3 default on Windows](https://chromium.googlesource.com/chromium/tools/depot_tools.git/+/c621315d173a9832fc7dcbf3854fe53cdfc5ee6c)

I prepared [a branch that updates to today's HEAD of their repo](https://github.com/reneme/conan-depot_tools_installer/tree/testing/20200515) and would be happy if somebody could incorporate it into the bincrafters repo. (cc @uilianries, @Croydon)

Note that this removes the `DEPOT_TOOLS_UPDATE=0` environment variable. Unfortunately this prevented the depot_tools tools from bootstrapping (and therefore working properly) on Windows.

**Comment by uilianries** [comment]
@reneme Is there any PR?

**Comment by reneme** [comment]
Now yes. Note that it is targeted at testing/20200207 while it should be 20200515, actually.

**Comment by Croydon** [comment]
This recipe is now in the [Conan Center Index](https://github.com/conan-io/conan-center-index/).

Please migrate to the recipe version there. 
If this is still an issue, please create a new issue in the [Conan Center Index issue tracker](https://github.com/conan-io/conan-center-index/issues).

Thanks!

_____________________

`depot_tools/20200407` seem to support Python 3 good enough, so we probably don't need to track this specifically anymore?
