### ISSUE TITLE
[folly] bzip2 not listed as a first-level requirement, picked up regardless..?

### ISSUE THREAD

**Issue by andlaz** [bincrafters/community#945]
i'm trying to conan-ify rsocket/rsocket-cpp. I add the only version made available in the Artifactory repo as a requirement, ```folly/2018.11.12.00@bincrafters/stable``` in my conanfile.

My build then fails because Folly is attempting to include bzip2 headers from the conan cache, apparently in a version+configuration combination that's not available there.

i'm very new to Conan and have the following questions about this:
- bzip2 does not look like a transitive dependency of Folly, should it be listed in Folly's conanfile as a requirement?
- ..how did this not-previously-downloaded version and configuration hash of bzip2 make it's way in to Folly's includes..? Is it possible it was generated from a transitive dependency..?

i apologize if all the above is just a lack of basic understanding of Conan on my end.

thanks,
Andras

**Comment by uilianries** [comment]
Hi @andlaz ! Welcome!

> My build then fails because Folly is attempting to include bzip2 headers from the conan cache, apparently in a version+configuration combination that's not available there.

Which configuration do you need? Do you have the profile listed when building?

> bzip2 does not look like a transitive dependency of Folly, should it be listed in Folly's conanfile as a requirement?

bzip2 is not transitive, but a regular dependency: 

https://github.com/facebook/folly/blob/24606aeae7c18e2ae867eefe370ba03075e57276/CMake/folly-deps.cmake#L57

Out Folly package is outdated, and bzip2 has a new release available: 1.0.8

I'll update Folly soon.

Regards.

**Comment by andlaz** [comment]
thanks @uilianries !

> Which configuration do you need? Do you have the profile listed when building?

So, to my build, bzip2 is transitive, at least through Folly ( probably many others ) Not sure what bearing that should have on the configuration bzip2 was expected to be found in the cache.. Probably not much from my current understanding? Here's the default profile from my project's .conan folder

```bash
conan@def0821dabed:~/rsocket$ conan profile show default
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=8
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]
```

> bzip2 is not transitive, but a regular dependency:

in which case, should it be listed here..? https://github.com/bincrafters/conan-folly/blob/testing/2019.03.18.00/conanfile.py#L25

thanks again!!
ANdras

**Comment by uilianries** [comment]
You are right, it should be listed directly in conanfile.py, bzip2 took ride with other dependency.

Anyway, I'll provide a new version with bzip 1.0.8

**Comment by andlaz** [comment]
Thanks! I'm still wondering though, how would this omission result in an include being generated for a configuration ( hash ) that was never downloaded ? When building yarpl, a project hosted with and built from rsocket ( both consumers of Folly ) the following cmake error is raised

```
CMake Error in yarpl/CMakeLists.txt:
  Imported target "Folly::folly" includes non-existent path
  "/home/conan/.conan/data/bzip2/1.0.6/conan/stable/package/1d877a3df840030e6a8abb74c5ffb9088d08b47a/include"
```

this package is found in the cache in a different configuration ( i'm building in a docker container for reproduceability )

```bash
conan@388701826af9:~/rsocket$ ls /home/conan/.conan/data/bzip2/1.0.6/conan/stable/package/
a5875aed3fc7ae8dd0488f7e5e99acbc480d721d
```

how did ```1d877a3df840030e6a8abb74c5ffb9088d08b47a``` make it's way in to Folly includes?

sorry if this is coincidental and beyond the scope of the original problem.

**Comment by andlaz** [comment]
( the problem above was solved by adding `cmake_paths` as a generator and text processing the cmake project descriptor to include it and configuring bzip the same way  )

I also noticed a number of other changes in requirements for folly, i'll see if i can make progress with that today, if i can, i'll send some PRs to the folly branch with the updates.

**Comment by Croydon** [comment]
This recipe is now in the [Conan Center Index](https://github.com/conan-io/conan-center-index/).

Please migrate to the recipe version there. 
If this is still an issue, please create a new issue in the [Conan Center Index issue tracker](https://github.com/conan-io/conan-center-index/issues).

Thanks!
