### ISSUE TITLE
[ffmpeg] options for custom configure flags

### ISSUE THREAD

**Issue by cqjjjzr** [bincrafters/community#948]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **ffmpeg/4.2**
  * Operating System+version: **Windows 10**
  * Compiler+version: **Visual Studio 2019**
  * Docker image: **Not applicable**
  * Conan version: **Conan 1.18.2**
  * Python version: **Python 3.7.0**

### Description of your feature

Package ffmpeg has a lot of customizable entries in its configure script, for example:

```
  --enable-gpl
  --enable-runtime-cpudetect
  --enable-small
  --enable-x86asm
  --x86asmexe=yasm

  --disable-avfilter \
  --disable-avresample \
```

And since those flags are not relating to 3rd party libraries(`libx264` for example), they're not options entries like "`x264`". Also, if we add all those flags as options, the option list will be way too long.

However, there's still absolutely a need for customizing flags. For example, maybe I need to enable `--enable-small` for smaller artifacts.

I've already done a small patch achieving this. Would like to hear more suggestions.

**Comment by ericLemanissier** [comment]
This recipe is now in the Conan Center Index.

Please migrate to the recipe version there.
If this is still an issue, please create a new issue in the Conan Center Index issue tracker.

Thanks!

https://conan.io/center/ffmpeg
