### ISSUE TITLE
Help with "General package workflow", trying to create new package

### ISSUE THREAD

**Issue by lion10243** [bincrafters/community#95]
Hello, i'm experiencing, so far, two issues when trying to follow the general package workflow guide on bincrafters.readthedocs.io, to create a spdlog-0.16.3 package.

First issue:
I'm currently stuck on step 8 - "Setup publishing to your own Bintray account".  What does this imply? I cannot figure out how to setup this publishing to the bintray account I setup. What do I have to do? Perhaps some more documentation could be written about this point.

Second issue:
I was able to build spdlog-0.16.3 in travis, appveyor in a _testing_/0.16.3 branch. However, when I tried creating a _stable_/0.16.3 branch, I received the following python exception during the build in travis/appveyor:

```
Traceback (most recent call last):
  File "build.py", line 11, in <module>
    builder.run()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/conan/packager.py", line 407, in run
    if not self.skip_check_credentials and self._upload_enabled():
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/conan/packager.py", line 526, in _upload_enabled
    raise_error("password")
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/conan/packager.py", line 523, in raise_error
    raise Exception("Upload not possible, '%s' is missing!" % field)
Exception: Upload not possible, 'password' is missing!
```
Is this trying to upload my package into the conan-public bintray, and rejecting because the CONAN_XXX env credentials are missing?  I only want to publish to my personal conan bintray.

Creating and publishing conan packages is unfortunately still not a particularly easy, smooth process :-(

FYI, src github repo & bintray target
https://github.com/lion10243/conan-spdlog/tree/testing/0.16.3
https://bintray.com/lion10243/conan-spdlog/spdlog

**Comment by solvingj** [comment]
First issue: 
Good point, we should add a link here: 
http://docs.conan.io/en/latest/uploading_packages/using_bintray.html?highlight=bintray

Lets keep this ticket open until we do that. 
Second issue: 
Yes, conan package tools by default looks for CONAN_STABLE_BRANCH and CONAN_UPLOAD_WHEN_STABLE variables to decide if it's going to upload (to any Bintray/Conan repository, including your personal).    If it is, then it makes sure it has both CONAN_XXX credentials, otherwise it will build the whole thing, and then fail to upload, so it's trying to save you build time by making sure the credentials exist in advance.

**Comment by lion10243** [comment]
Thanks :) I'll try your suggestion out.

**Comment by AlexandrePTJ** [comment]
I would suggest to add that the personnal bintray repository must be named public-conan. This is not mention but it solved my builds.

**Comment by solvingj** [comment]
I thought our latest templates allow the repository to have a different name.  @uilianries do you know if that is correct or not?

**Comment by AlexandrePTJ** [comment]
It may be possible but what I mean is that it is not mention.
Anyway, I like what bincrafters community is creating so I will continue to create package and suggest ideas. It looks like its going to get close to what [aur](https://aur.archlinux.org/)community offer, and it is really good.

**Comment by solvingj** [comment]
Great to hear.  Can't tell you how grateful we are for your support and contribution!

**Comment by solvingj** [comment]
If someone see's how to do so using our package tools, the docs to be updated are here: 
http://bincrafters.readthedocs.io/en/latest/
