### ISSUE TITLE
[Qt] Windows Visual Studio 64 Bit linker error

### ISSUE THREAD

**Issue by qno** [bincrafters/community#950]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.9.8**
  * Operating System+version: **Windows 7 64 Bit Professional**
  * Compiler+version: **Visual Studio**
  * Conan version: **Conan 1.18.2**
  * Python version: **Python 3.7.4**

Configuration:
```  
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=14
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
```  
excerpt from conanfile.py:
```  
default_options = {
        "shared": True,
        "fPIC": True,
        "qt:qtmultimedia": True
        }
```

### Question Description

Hello,

I have the following problem. I created a conan recipe for an application which requires Qt.
It requires qtmultimedia support and therefore conan has to rebuild Qt in my local cache for Windows in this case.
After the whole dependencies of the programm are compiled linking fails with the following error:
```
...
$ Qt5Widgets.lib(Qt5Widgets.dll) : fatal error LNK1112: module machine type 'X86' conflicts with target machine type 'x64' [C:\.conan\be65e8\1\XXX\XXX.vcxproj]
...
```
For me it looks like that Qt was compiled by conan as X86 (32-Bit), because if I inspect e.g. the Qt5Widgets.lib with `dumpbin` it says it is X86. But I don't know what I have to setup with conan that Qt gets recompiled as X86_64 binary version.

Can someone please give my a hint what I'm maybe doing wrong here?

**Comment by ericLemanissier** [comment]
Could you please send the full build log of qt ?

**Comment by qno** [comment]
@ericLemanissier - her the log of the rebuild. It contains just Qt part as the rest of the information is somehow strictly confidential.

[conan-qt-5.9.8-rebuild-log.txt](https://github.com/bincrafters/community/files/3596921/conan-qt-5.9.8-rebuild-log.txt)

**Comment by qno** [comment]
@ericLemanissier - here I also added the qmake logs of the qt rebuild.

[qt-5.9.8-rebuild-qmake-logs.zip](https://github.com/bincrafters/community/files/3599382/qt-5.9.8-rebuild-qmake-logs.zip)

**Comment by ericLemanissier** [comment]
Thanks, the log contains `Checking for target architecture... i386`, so you are right that qt was built as a 32bits version. Your log also says `Conan:vcvars already set`, which means that whatever visual environment set before building qt is also used to build qt. If this pre-set visual environment is 32bits, then it leads qt to build as 32bits too, regardless of your profile.
long story short: please remove visual environment variables before trying to build qt, or make sure that the environment matches your conan settings

**Comment by qno** [comment]
@ericLemanissier - Thank you for your help. But now I'm really confused. Basically I don't know what I have to do here. Do you mean that I have to load before starting the build the `"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\vcvarsx86_amd64.bat"`? I did this already but it doesn't help either. What do you mean by 

> please remove visual environment variables before trying to build qt, or make sure that the environment matches your conan settings

I don't understand this.

**Comment by ericLemanissier** [comment]
Does normal cmd line shell also outputs `vcvars already set` after `qt/5.9.8@bincrafters/stable: Calling build()` ?

**Comment by qno** [comment]
Normal Cmd line doesn't compile at all - it says
``` 
qt/5.9.8@bincrafters/stable: Building your package in C:\.conan\053b1f\1
qt/5.9.8@bincrafters/stable: Generator txt created conanbuildinfo.txt
qt/5.9.8@bincrafters/stable: Calling build()
The specified configuration type is missing.  The tools for the
configuration might not be installed.
+ cd qtbase

+ C:\.conan\485738\1\qt5\qtbase\configure.bat -top-level -shared -confirm-license -silent -nomake examples -nomake tests -prefix C:\.conan\db2082\1 -opensource -release -skip qtsvg -skip qtdeclarative -skip qtactiveqt -skip qtscript -skip qttools -skip qtxmlpatterns -skip qttranslations -skip qtdoc -skip qtlocation -skip qtsensors -skip qtconnectivity -skip qtwayland -skip qt3d -skip qtimageformats -skip qtgraphicaleffects -skip qtquickcontrols -skip qtserialbus -skip qtserialport -skip qtx11extras -skip qtmacextras -skip qtwinextras -skip qtandroidextras -skip qtwebsockets -skip qtwebchannel -skip qtwebengine -skip qtcanvas3d -skip qtwebview -skip qtquickcontrols2 -skip qtpurchasing -skip qtcharts -skip qtdatavis3d -skip qtvirtualkeyboard -skip qtgamepad -skip qtscxml -skip qtspeech -skip qtnetworkauth -skip qtremoteobjects -opengl desktop -no-openssl -platform win32-msvc -qt-zlib

Bootstrapping qmake ...



jom 1.1.2 - empower your cores



	cl -c -Fo./ -Fdqmake.pdb  -W2 -nologo -O1  /MP /wd4577   -IC:\.conan\485738\1\qt5\qtbase\qmake -IC:\.conan\485738\1\qt5\qtbase\qmake\library -IC:\.conan\485738\1\qt5\qtbase\qmake\generators -IC:\.conan\485738\1\qt5\qtbase\qmake\generators\unix -IC:\.conan\485738\1\qt5\qtbase\qmake\generators\win32 -IC:\.conan\485738\1\qt5\qtbase\qmake\generators\mac  -IC:\.conan\485738\1\qt5\qtbase/include -IC:\.conan\485738\1\qt5\qtbase/include\QtCore -IC:\.conan\485738\1\qt5\qtbase/include\QtCore\5.9.8 -IC:\.conan\485738\1\qt5\qtbase/include\QtCore\5.9.8\QtCore  -I..\src\corelib\global  -IC:\.conan\485738\1\qt5\qtbase\mkspecs\win32-msvc   -D_CRT_SECURE_NO_WARNINGS -D_SCL_SECURE_NO_WARNINGS  -DQT_VERSION_STR=\"5.9.8\" -DQT_VERSION_MAJOR=5 -DQT_VERSION_MINOR=9 -DQT_VERSION_PATCH=8  -DQT_BUILD_QMAKE -DQT_BOOTSTRAPPED -DPROEVALUATOR_FULL  -DQT_NO_FOREACH -DUNICODE -c -Yc -Fpqmake_pch.pch -TP C:\.conan\485738\1\qt5\qtbase\qmake\qmake_pch.h

Der Befehl "cl" ist entweder falsch geschrieben oder

konnte nicht gefunden werden.

jom: C:\.conan\053b1f\1\qtbase\qmake\Makefile [qmake_pch.obj] Error 1

qt/5.9.8@bincrafters/stable: 
qt/5.9.8@bincrafters/stable: ERROR: Package '100061d82d2fb50b5ea137d4487947a09a2f3050' build failed
qt/5.9.8@bincrafters/stable: WARN: Build folder C:\.conan\053b1f\1
ERROR: qt/5.9.8@bincrafters/stable: Error in build() method, line 375
	_build("jom")
while calling '_build', line 368
	self.run("%s/qt5/configure %s" % (self.source_folder, " ".join(args)))
	ConanException: Error 1 while executing C:\.conan\485738\1/qt5/configure -shared -confirm-license -silent -nomake examples -nomake tests -prefix C:\.conan\db2082\1 -opensource -release -skip qtsvg -skip qtdeclarative -skip qtactiveqt -skip qtscript -skip qttools -skip qtxmlpatterns -skip qttranslations -skip qtdoc -skip qtlocation -skip qtsensors -skip qtconnectivity -skip qtwayland -skip qt3d -skip qtimageformats -skip qtgraphicaleffects -skip qtquickcontrols -skip qtserialbus -skip qtserialport -skip qtx11extras -skip qtmacextras -skip qtwinextras -skip qtandroidextras -skip qtwebsockets -skip qtwebchannel -skip qtwebengine -skip qtcanvas3d -skip qtwebview -skip qtquickcontrols2 -skip qtpurchasing -skip qtcharts -skip qtdatavis3d -skip qtvirtualkeyboard -skip qtgamepad -skip qtscxml -skip qtspeech -skip qtnetworkauth -skip qtremoteobjects -opengl desktop -no-openssl -platform win32-msvc -qt-zlib
```

**Comment by ericLemanissier** [comment]
`The specified configuration type is missing.  The tools for the configuration might not be installed.` is an MSVC error. googling it indicates that MSVC 2015 express does not have x64 toolset. Is that the version of visual studio you are using ?

**Comment by qno** [comment]
Now I think I've got it. So removing Qt source, package and build artifacts and rebuilding after setup the build environment with `vcvarsx86_amd64.bat` script seems to turn on 64-Bit support. I now see 
`Detected architecture: x86_64 (sse sse2)` and defines `-DWIN32 -DWIN64` which was not in the old build logs.

Thank you for your support on this.
