### ISSUE TITLE
[qt] qt/5.13.X on Windows with opengl contains user paths

### ISSUE THREAD

**Issue by giantmustache** [bincrafters/community#952]
I was trying to build qt with opengl enabled. Then I found out that there are actually user paths in Qt5GuiConfigExtras.cmake. Are there any options that I should take note of while building?

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.13.1**
  * Operating System+version: **Windows 10**
  * Compiler+version: **gcc-8**
  * Conan version: **conan 1.18.2**
  * Python version: **Python 3.7.3**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)

    [settings]
    os=Windows
    os_build=Windows
    arch=x86_64
    arch_build=x86_64
    build_type=Release
    compiler=gcc
    compiler.threads=posix
    compiler.libcxx=libstdc++11
    compiler.version=8
    compiler.exception=seh
    [options]
    qt:opengl=desktop
    qt:qtquickcontrols2=True
    qt:widgets=False
    qt:qtdeclarative=True
    qt:qtvirtualkeyboard=True
    qt:qtsvg=False
    qt:qtgraphicaleffects=True
    qt:with_harfbuzz=False
    qt:openssl=False
    qt:with_mysql=False
    qt:with_sqlite3=False
    qt:with_pq=False
    qt:with_odbc=False
    qt:with_openal=False
    [build_requires]
    *:mingw_installer/1.0@conan/stable
    *:msys2_installer/latest@bincrafters/stable
    cmake_installer/3.15.2@conan/stable
    [env]

### Steps to reproduce (Include if Applicable)

`conan install -pr=mingw_profile --build qt qt/5.13.1@bincrafters/stable`

See that Qt5GuiConfigExtras.cmake contains user paths:

`_qt5gui_find_extra_libs(OPENGL "C:/Users/MKr/.conan/data/mingw_installer/1.0/conan/stable/package/172e8aacd31e5c3838e00a3ed4fe3ef6c53f3122/x86_64-w64-mingw32/lib/libglu32.a;C:/Users/MKr/.conan/data/mingw_installer/1.0/conan/stable/package/172e8aacd31e5c3838e00a3ed4fe3ef6c53f3122/x86_64-w64-mingw32/lib/libopengl32.a;C:/Users/MKr/.conan/data/mingw_installer/1.0/conan/stable/package/172e8aacd31e5c3838e00a3ed4fe3ef6c53f3122/x86_64-w64-mingw32/lib/libgdi32.a;C:/Users/MKr/.conan/data/mingw_installer/1.0/conan/stable/package/172e8aacd31e5c3838e00a3ed4fe3ef6c53f3122/x86_64-w64-mingw32/lib/libuser32.a" "" "")`

**Comment by mjvk** [comment]
I believe this is related to  [this](https://github.com/meta-qt5/meta-qt5/issues/108), maybe we can use a similar (or same) patch as used there.

**Comment by ericLemanissier** [comment]
Would this be the same as https://bugreports.qt.io/browse/QTBUG-72903 ?
Can you try with qt 5.12.0 ?

**Comment by giantmustache** [comment]
I tried to build qt 5.12.0 and indeed that one doesn't seem to have an issue. The line changed to:

`_qt5gui_find_extra_libs(OPENGL "glu32;opengl32;gdi32;user32" "" "")`.

But 5.12.0 has a different issue: https://bugreports.qt.io/browse/QTBUG-71829, and therefore it won't build on windows. I would have to try 5.12.1, but as your issue already states, this might come with different issues again.

I will try to build Qt 5.13.1 and try to apply the same patch as described in the issue mentioned: https://bugreports.qt.io/browse/QTBUG-72903. I 
 will then make a PR that integrates https://github.com/qtproject/qtsdk/blob/master/packaging-tools/patch_qt.py into the conanfile.

**Comment by ericLemanissier** [comment]
A new commit landed in qtbase, which reverts to the non absolute library paths: https://github.com/qt/qtbase/commit/9864d2c6f3b628ca9f07a56b197e77bd43931cca
It's on branches 5.14 and 5.15. if you can't wait for qt 5.14.0 (end of the year), maybe the best solution is to apply this commit to qt 5.13.1 sources ?

**Comment by giantmustache** [comment]
I have created a pull request: https://github.com/bincrafters/conan-qt/pull/37.
It uses the patch_qt.py as stated in this issue and fixes qt 5.13.1 at least by removing the paths from /lib/cmake files.

**Comment by giantmustache** [comment]
I wasn't able to resolve it with patch_qt.py, because it would require too many changes to work in both python 2 and 3. I was using python 3, which was having UnicodeDecodeErrors. I am awaiting qt 5.14 to fix all my sorrows.

**Comment by ericLemanissier** [comment]
Thanks for the investigations. It's a shame there is no solution before 5.14.0.

**Comment by ericLemanissier** [comment]
upstream issue: https://bugreports.qt.io/browse/QTBUG-72903. Will be solved in qt 5.14.0
