### ISSUE TITLE
CCI changes: What to do about MinGW prebuilds

### ISSUE THREAD

**Issue by Croydon** [bincrafters/community#954]
CCI does not offer MinGW builds currently.

At Bincrafters we do not offer MinGW prebuilds by default, but we get sometimes requests to offer them for specific packages and have therefore added those build jobs.

When those recipes depend on other Bincrafters' recipes we have most of the time just added there MinGW jobs there as well.

What are we going to do with MinGW prebuilds offerings in the future?

Are we going to drop them?
Are we making use of `build=missing`?
Should we suggest an opt-in way for CCI recipes to build MinGW builds?

**Comment by uilianries** [comment]
We can build those dependencies and upload to Bincrafters. CPT offers this option.

I'm not opposite to drop, but I'm open to accept support when requested.
