### ISSUE TITLE
Upstream Update: bison 3.4.1

### ISSUE THREAD

**Issue by madduci** [bincrafters/community#956]
### Package Details
  * Package Name: **bison**
  * Latest available Version: **3.4.1**

The above mentioned version is newly released by the upstream project and not yet available within Bincrafters repository. 

I've sent a pull request fixing the compiler errors for the 3.4.1/testing branch on the github repository: it needs `flex_installer` as requirement due to some examples being built with the Makefile.

**Comment by Croydon** [comment]
This recipe is now in the [Conan Center Index](https://github.com/conan-io/conan-center-index/).

Please migrate to the recipe version there. 
If this is still an issue, please create a new issue in the [Conan Center Index issue tracker](https://github.com/conan-io/conan-center-index/issues).

Thanks!
