### ISSUE TITLE
conan-cli11 inclusion request review

### ISSUE THREAD

**Issue by danimtb** [bincrafters/community#96]
## Inclusion Request Review

This is a review for [conan-cli11](https://github.com/bincrafters/conan-cli11) inclusion request to conan-center.
This review follows the [inclusion guidelines or third party libraries](http://docs.conan.io/en/latest/uploading_packages/bintray/conan_center_guide.html#inclusion-guidelines-for-third-party-libraries).

### Package
cli11/1.3.0@bincrafters/stable

#### Recipe quality
- [x] Git public repository
- [x] Recipe fields (description, library license, url)
- [x] Linter: **Check imports, trailing whitespaces and long lines**
- [x] Updated
- [x] Clean
- [x] test_package
- [x] Raise errors on invalid configurations
- [x] LICENSE of the recipe
- [x] LICENSE of the library: **copy license files to *licenses* folder inside package**

#### CI Integration
- [x] Provide at least one CI configuration (header only)
- [x] ~(If not header only) CI configurations for Linux/MacOSX/Windows~

#### Bintray Package Information
- [x] Description
- [x] Licenses
- [x] Tags: **Add useful tags like: *CLI*, *commands*, *parameters*, *arguments*, *C++11***
- [x] Maturity: **Add maturity of project. In this case *stable***
- [x] Website (if any)
- [x] Issue tracker
- [x] Version control
- [x] GitHub repo (user/repo): **Not sure if it's done, please check and maybe link readme**

### Additional comments

Thanks for sending an inclusion request for this package!

It seems quite good.
Just  one thing to note in addition to the above checks:

- `package_id()` method is not needed in this case as the recipe does not have settings nor requirements. You can leave it but just for information.

**Comment by solvingj** [comment]
I've applied all the changes requested here and triggered a rebuild of the package.  Should be all set.

**Comment by danimtb** [comment]
Please, check Linter, copy of licenses, bintray tags and github user/repo

**Comment by danimtb** [comment]
All checks passed!
Thank you so much @solvingj and @bincrafters-user in general for this contribution

**Comment by danimtb** [comment]
approved! Thanks again 😃
