### ISSUE TITLE
glib package not compatible with Ubuntu 18.04 (libc6 <2.28)

### ISSUE THREAD

**Issue by planetmarshall** [bincrafters/community#962]
glibc package fails to link with undefined symbol `fcntl64` when `g_unix_open_pipe` or `g_unix_set_fd_nonblocking` is called. Note `fcntl64` is present in glibc >=2.28.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **glib/2.58.3**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **clang-8**
  * Docker image: **conanio/gcc7**
  * Conan version: **conan 1.18.3**
  * Python version: **Python 3.6.8**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)

```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=clang
compiler.version=8
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
CC=/usr/bin/clang-8
CXX=/usr/bin/clang++-8
```

### Steps to reproduce (Include if Applicable)

Add the following code to `test_package.c` (Taken from the Qt glib test)

```
g_thread_init(NULL);
(void) g_main_context_default();
(void) g_source_new(0, 0);
g_source_add_poll(NULL, NULL);
```

### Logs (Include/Attach if Applicable)

[error.log](https://github.com/bincrafters/community/files/3616558/error.log)

**Comment by ericLemanissier** [comment]
This looks to me like an incompatibility between binaries built with different libc version. Does your build use only binaries built on ubuntu 18.04, or are you using some pre built binaries from bintray? (same comment as https://github.com/bincrafters/community/issues/987#issuecomment-538341469)

**Comment by planetmarshall** [comment]
Only Ubuntu 18.04 provided binaries. The version of Glibc provided with Ubuntu 18.04 (2.27) does not define the `fcntl64` symbol, whereas Glibc >= `2.28` does (Ubuntu 19.04 includes Glibc 2.28, and the glibc package builds successfully. I note that the conan docker images are based on Ubuntu 19.04, but this option is not available to us as we require an LTS version)

**Comment by ericLemanissier** [comment]
In this case you have to make sure to use only binaries built with a compatible glibc, which rules out conan docker tools and bincrafters'bintray binaries.

**Comment by planetmarshall** [comment]
Yes thanks, I rebuilt qt from source and all is good.
