### ISSUE TITLE
Upstream Update: glib 2.62.0

### ISSUE THREAD

**Issue by IceflowRE** [bincrafters/community#966]
### Package Details
  * Package Name: **glib**
  * Latest available Version: **2.62.0**

The above mentioned version is newly released by the upstream project and not yet available within Bincrafters. Please add this version.

https://github.com/bincrafters/conan-glib

**Comment by Croydon** [comment]
It seems like the `stable/2.58.3` branch has many commits which didn't make it into the `testing/2.60.3` branch. @SSE4 Could you please have a look if this is desired?

**Comment by IceflowRE** [comment]
Would it be possible to update it soon?
The depencies should be updated to `libselinux/2.9` too, as 2.8 makes problems #1015. 
Aside of it 2.58.3 does not compile with clang on windows.

**Comment by uilianries** [comment]
ping @SSE4

**Comment by barcharcraz** [comment]
any progress on this?

**Comment by IceflowRE** [comment]
`glib/2.63.3` is available and works fine so far.
