### ISSUE TITLE
conan-cpprestsdk (but all really) how do I know what name the library uses?

### ISSUE THREAD

**Issue by ShamanTcler** [bincrafters/community#968]
Package Name/Version: conan-cpprestsdk
   Operating System+version: Win 10
   Compiler+version: MSVS 2015
   Conan version: 1.18.2
   Python version: 3.6.5

I am using the cmake / conan approach from : https://github.com/conan-io/cmake-conan

So I have a segment like:
```
conan_cmake_run(PROFILE  MSVS15-release.txt
        BUILD_TYPE "Release"
        REQUIRES
        cpprestsdk/2.10.14@bincrafters/stable
        IMPORTS ${CONANIMPORTS}
        BASIC_SETUP	CMAKE_TARGETS
        )
```
and then a line like:
```
target_link_libraries(${PROJECT_NAME} CONAN_PKG::cpprestsdk140_2_10)
```

My issue is the string "CONAN_PKG::cpprestsdk140_2_10" is not obvious. I found it by dumping all the variables in the CMAKE and looking for CONAN_PKG::

So it is possible to include this name in the github README.md?

You guys do a fantastic job, Thanks

Regards
Carl

**Comment by Croydon** [comment]
Including more information in the readme is a non-starter, as we are ultimately working towards getting recipes into the [Conan Center Index](https://github.com/conan-io/conan-center-index), and you would lose the information at this point from Bincrafers specific readme's. So it would be only a temporary thing and more work.

**Comment by ShamanTcler** [comment]
Ok sound reasonable, what about asking cmake-conan to include a a routine to print out all available CONAN_PKG:: libraries?

For someone new to the system, bring includes to the party via 
target_link_libraries(${PROJECT_NAME} CONAN_PKG::cpprestsdk140_2_10)

is not in my opinion obvious

**Comment by ericLemanissier** [comment]
I think this is a feature missing from conan itself: consumers should have an easy way to know:

1. which generators are compatible with a given package
2. how can the package be consumed by each of these generators (eg the cmake libraries name)

**Comment by SSE4** [comment]
I have no idea where is `CONAN_PKG::cpprestsdk140_2_10` is coming from...
the CMake target name should match project name, so it should be just `CONAN_PKG::cpprestsdk`.
@ShamanTcler  could you check if this one is available?

**Comment by ShamanTcler** [comment]
After Croydon comment I went to the cmake-conan project and asically asked this question there.

I will check on the  cpprestsdk vs cpprestsdk140_2_10

**Comment by Croydon** [comment]
https://github.com/conan-io/cmake-conan/issues/179
