### ISSUE TITLE
How to use boost-1.71 with cpprestsdk?

### ISSUE THREAD

**Issue by sinall** [bincrafters/community#969]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **cpprestsdk/2.10.14**
  * Operating System+version: **Windows 10**
  * Compiler+version: **MSVC2019**
  * Conan version: **Conan 1.18.2**

### Question Description
Currently cpprestsdk requires boost-1.69, is it possible to use boost-1.71 instead?

**Comment by SSE4** [comment]
it's not possible, they aren't compatible and don't compile together

**Comment by jmarrec** [comment]
Should be soon on stable. I patched websocket, and now they are compatible.

https://github.com/bincrafters/conan-cpprestsdk/pull/9#issuecomment-567045447
