### ISSUE TITLE
Inclusion request msys2_installer

### ISSUE THREAD

**Issue by lasote** [bincrafters/community#97]
## Inclusion Request Review

This is a review for [conan-msys2_installer](https://github.com/bincrafters/conan-msys2_installer) inclusion request to conan-center.
This review follows the [inclusion guidelines or third-party libraries](http://docs.conan.io/en/latest/uploading_packages/bintray/conan_center_guide.html#inclusion-guidelines-for-third-party-libraries).

### Package
conan-msys2_installer

#### Recipe quality
- [x] Git public repository
- [x] Recipe fields
- [x] Linter
- [x] Updated
- [x] Clean
- [x] test_package
- [x] Raise errors on invalid configurations
- [x] LICENSE of the recipe
- [x] LICENSE of the library

#### CI Integration
- [x] Provide at least one CI configuration (header only)
- [x] (If not header only) CI configurations for Linux/MacOSX/Windows

#### Bintray Package Information
- [x] Description
- [x] Licenses
- [ ] Tags
- [ ] Maturity
- [x] Website (if any)
- [x] Issue tracker
- [x] Version control
- [x] GitHub repo (user/repo)

### Additional comments

Great work, just add the Maturity and Tags in the bintray package information page. I usually add "build_require" tag when it is a tool to be used as build_require.

Thanks guys! fantastic job

**Comment by solvingj** [comment]
Done!

**Comment by lasote** [comment]
Inclusion request approved!!!
