### ISSUE TITLE
OpenSSL Exception while getting package

### ISSUE THREAD

**Issue by bvnp43** [bincrafters/community#971]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libcurl/7.66.0@bincrafters/stable**
  * Operating System+version: **Linux Ubuntu 16.04**
  * Compiler+version: **gcc-5.4**
  * Docker image: **conanio/gcc7**
  * Conan version: **conan 1.18.4**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)

[requires]
libcurl/7.66.0@bincrafters/stable

[options]

[generators]
cmake

### Logs (Include/Attach if Applicable)
```
OpenSSL/1.1.1c@conan/stable: Retrieving package d5204605bf864d4bd98fc6a9e624938e8e04ad03 from remote 'conan-center' 
Downloading conanmanifest.txt
.
Downloading conaninfo.txt
.
Downloading conan_package.tgz
Please log in to "conan-center" to perform this action. Execute "conan user" command.
If you don't have an account sign up here: https://bintray.com/signup/oss
OpenSSL/1.1.1c@conan/stable: ERROR: Exception while getting package: d5204605bf864d4bd98fc6a9e624938e8e04ad03
OpenSSL/1.1.1c@conan/stable: ERROR: Exception: <class 'conans.errors.ConanException'> EOF when reading a line. [Remote: conan-center]
OpenSSL/1.1.1c@conan/stable: WARN: Trying to remove package folder: /root/.conan/data/OpenSSL/1.1.1c/conan/stable/package/d5204605bf864d4bd98fc6a9e624938e8e04ad03
ERROR: EOF when reading a line. [Remote: conan-center]
CMake Error at cmake/conan.cmake:401 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  cmake/conan.cmake:487 (conan_cmake_install)
  CMakeLists.txt:23 (conan_cmake_run)
```

**Comment by bvnp43** [comment]
I've started getting same error for boost/1.71.0@conan/stable, wich worked fine before, is there anything happening with conan server arm?

**Comment by bvnp43** [comment]
Same issue on ubuntu 18.04 docker

**Comment by bvnp43** [comment]
If i upload those packages to my aws conan server - everything works fine

**Comment by lasote** [comment]
Bintray service is taking a look at it. Other users have reported the same error. Thanks.

**Comment by ericLemanissier** [comment]
https://github.com/conan-io/conan/issues/5780
