### ISSUE TITLE
[sdl2/2.0.9 | android_ndk_installer/r19c] Issue linking libSDL2.so to executable using android_ndk_installer with arch=armv8

### ISSUE THREAD

**Issue by joshgamer474** [bincrafters/community#973]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **sdl/2.0.9@bincrafters/stable | android_ndk_installer/r19c@bincrafters/stable**
  * Operating System+version: **Linux Manjaro 18.1.0**
  * Compiler+version: **clang 8**
  * Conan version: **conan 1.16.1**
  * Python version: **Python 3.7.4**

### Conan profile
[settings]
os_build=Linux
arch_build=x86_64

os=Android
os.api_level=28
compiler=clang
compiler.version=8
compiler.libcxx=libc++
build_type=Release
[options]
*:pic=True
[build_requires]
android_ndk_installer/r19c@bincrafters/stable
[env]

### Issue
Hello, recently I've been using the bincrafters **sdl2/2.0.9** and **android_ndk_installer/r19c** conan packages to build my own **GBCEmulator/0.0.3** conan package for Android. I've been mostly successful cross-compiling my **GBCEmulator/0.0.3** from Linux to Android for 3/4 archs (x86, x86_64, and armv7), however there seems to a linking issue when building with arch=armv8. The issue seems to be that libSDL2.so cannot find some essential **android_ndk_installer**-provided shared libraries.

I've tried to investigate the issue myself, but I'm having a hard time determining why arch=armv7 works while arch=armv8 does not. I believe that the issue may stem from the various different naming conventions that armv8 represents (e.g. aarch64, aarch64-linux-android, etc.) not matching/linking to the correct directory(ies), however I haven't been able to find any actual mismatches.

The prebuilt *.so(s) seem to be provided correctly for all arches: `/home/childers/.conan/data/android_ndk_installer/r19c/bincrafters/stable/package/84fc5086d5b84ea42507b9623275f83e74452fe1/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/`
and as far as I can tell, the **android_ndk_installer**'s conanfile.py seems to create build environment vars that match **android_ndk_installer**'s conan package directories.

I'm at a loss and would appreciate any help/insight into figuring this out as I believe **android_ndk_installer/r19c** isn't linking arch=armv8 packages correctly. 

### Steps to reproduce an unsuccessful build (arch=armv8)
`git clone https://github.com/joshgamer474/GBCEmulator.git`
`cd GBCEmulator`
`conan install . -if=build_android_armv8 --profile=profiles/android --build=outdated -o shared=True -s arch=armv8 -s cppstd=17`
`conan build . -bf=build_android_armv8`

### Steps to reproduce a successful build (arch=armv7)
`git clone https://github.com/joshgamer474/GBCEmulator.git`
`cd GBCEmulator`
`conan install . -if=build_android_armv7 --profile=profiles/android --build=outdated -o shared=True -s arch=armv7 -s cppstd=17`
`conan build . -bf=build_android_armv7`

### Logs (Include/Attach if Applicable)

> [childers@childers GBCEmulator]$ conan build . -bf=build_android_armv8
conanfile.py (GBCEmulator/0.0.3@None/None): WARN: Setting 'cppstd' is deprecated in favor of 'compiler.cppstd', please update your recipe.
conanfile.py (GBCEmulator/0.0.3@None/None): Running build()
-- Conan: called by CMake conan helper
-- Conan: Adjusting output directories
-- Conan: Using cmake targets configuration
-- Library SDL2 found /home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so
-- Library SDL2main found /home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2main.a
-- Library png16 found /home/childers/.conan/data/libpng/1.6.37/bincrafters/stable/package/d15614b1106a883893be58c9cd1ff8225f154c79/lib/libpng16.a
-- Library fmt found /home/childers/.conan/data/fmt/5.2.1/bincrafters/stable/package/4c23b03b5a343464e34c84a7c3def60889ab99dd/lib/libfmt.a
-- Library z found /home/childers/.conan/data/zlib/1.2.11/conan/stable/package/8793d2e714a5bc740f91356dc25f77df70018388/lib/libz.a
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
-- Conan setting CPP STANDARD: 17 WITH EXTENSIONS OFF
-- Conan: Compiler Clang>=8, checking major version 8
-- Conan: Checking correct version: 8
-- Conan: C++ stdlib: libc++
Building as SHARED
-- Configuring done
-- Generating done
-- Build files have been written to: /home/childers/Documents/Git/temp/GBCEmulator/build_android_armv8
[ 89%] Built target GBCEmulator
[ 94%] Linking CXX executable bin/GBCEmulator
/home/childers/.conan/data/android_ndk_installer/r19c/bincrafters/stable/package/84fc5086d5b84ea42507b9623275f83e74452fe1/toolchains/llvm/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: liblog.so, needed by /home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so, not found (try using -rpath or -rpath-link)
/home/childers/.conan/data/android_ndk_installer/r19c/bincrafters/stable/package/84fc5086d5b84ea42507b9623275f83e74452fe1/toolchains/llvm/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: libandroid.so, needed by /home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so, not found (try using -rpath or -rpath-link)
/home/childers/.conan/data/android_ndk_installer/r19c/bincrafters/stable/package/84fc5086d5b84ea42507b9623275f83e74452fe1/toolchains/llvm/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: libGLESv1_CM.so, needed by /home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so, not found (try using -rpath or -rpath-link)
/home/childers/.conan/data/android_ndk_installer/r19c/bincrafters/stable/package/84fc5086d5b84ea42507b9623275f83e74452fe1/toolchains/llvm/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: libGLESv2.so, needed by /home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so, not found (try using -rpath or -rpath-link)
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glActiveTexture'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glGenBuffers'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glGetProgramInfoLog'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `ASensor_getType'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `ALooper_pollAll'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glDrawArrays'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glGenFramebuffers'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glClear'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glBufferData'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glBufferSubData'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glBlendFuncSeparate'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `__android_log_write'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glUniformMatrix4fv'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `ASensorManager_getInstance'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glScissor'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glTexParameteri'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glGetShaderiv'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glDisableVertexAttribArray'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glBindFramebuffer'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glTexImage2D'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glEnable'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glUseProgram'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `ASensorManager_createEventQueue'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glGetBooleanv'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glPixelStorei'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glFramebufferTexture2D'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glBlendEquationSeparate'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glShaderSource'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `ASensor_getName'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glCreateProgram'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glGetProgramiv'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glBindBuffer'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glGetUniformLocation'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glVertexAttribPointer'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glDeleteShader'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `__android_log_print'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glFinish'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glGetAttribLocation'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glClearColor'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `ASensorManager_destroyEventQueue'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glGetError'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glCompileShader'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glReadPixels'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glGetString'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glUniform1i'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glShaderBinary'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `ANativeWindow_fromSurface'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `ASensorEventQueue_getEvents'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glBindAttribLocation'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glEnableVertexAttribArray'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `ALooper_prepare'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glUniform4f'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glTexSubImage2D'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `ANativeWindow_getHeight'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glGenTextures'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `ALooper_forThread'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glAttachShader'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `ASensorEventQueue_enableSensor'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glDeleteTextures'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glBindTexture'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glLinkProgram'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glCreateShader'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `ASensorManager_getSensorList'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glDisable'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glGetShaderInfoLog'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `ANativeWindow_getWidth'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `ASensorEventQueue_disableSensor'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glCheckFramebufferStatus'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glGetIntegerv'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `ANativeWindow_setBuffersGeometry'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glDeleteFramebuffers'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glViewport'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `ANativeWindow_release'
/home/childers/.conan/data/sdl2/2.0.9/bincrafters/stable/package/0c6fd0c86b09905d26754e6209d20a9c551c0dd7/lib/libSDL2.so: undefined reference to `glDeleteProgram'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/GBCEmulator_bin.dir/build.make:90: bin/GBCEmulator] Error 1
make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/GBCEmulator_bin.dir/all] Error 2
make: *** [Makefile:95: all] Error 2
ERROR: conanfile.py (GBCEmulator/0.0.3@None/None): Error in build() method, line 59
        cmake.build()
        ConanException: Error 512 while executing /home/childers/.conan/data/android_ndk_installer/r19c/bincrafters/stable/package/84fc5086d5b84ea42507b9623275f83e74452fe1/cmake-wrapper --build '/home/childers/Documents/Git/temp/GBCEmulator/build_android_armv8' '--' '-j8'

**Comment by ericLemanissier** [comment]
This recipe is now in the Conan Center Index.

Please migrate to the recipe version there.
If this is still an issue, please create a new issue in the Conan Center Index issue tracker.

Thanks!

https://conan.io/center/sdl
