### ISSUE TITLE
[qt] Unable to build, "multiple definition of QBasicMutex::lockInternal"

### ISSUE THREAD

**Issue by BastienGarcia** [bincrafters/community#974]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.12.5**
  * Operating System+version: **Linux Fedora 31**
  * Compiler+version: **gcc-9.2.1**
  * Conan version: **conan 1.18.4**
  * Python version: **Python 3.7.4**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]

### Steps to reproduce (Include if Applicable)
mkdir build && cd build && conan install .. --build qt

### Logs (Include/Attach if Applicable)
[log.txt](https://github.com/bincrafters/community/files/3641394/log.txt)

**Comment by ericLemanissier** [comment]
thanks for the report. Your problem looks very similar to https://bugreports.qt.io/browse/QTBUG-39273. Could you please try to add the `--update` argument to `conan install` and see if changes anything ?

**Comment by BastienGarcia** [comment]
Thank you for the quick answer.
I tried `conan install .. --update` but got the warning that qt wasn't prebuilt.
I then tried `conan install .. --update --build qt` and got the same warning about qmutex::lockInternal

**Comment by ericLemanissier** [comment]
ok. I reported it to https://bugreports.qt.io/browse/QTBUG-78729. Don't hesitate to give more information there.
