### ISSUE TITLE
Upstream Update: spdlog 1.4.1

### ISSUE THREAD

**Issue by darcamo** [bincrafters/community#975]
### Package Details
  * Package Name: **spdlog**
  * Latest available Version: **1.4.1**

The above mentioned version is newly released by the upstream project and not yet available within Bincrafters. Please add this version.

**Note**: Previously this library was a header only library, but now it can be compiled as a static or shared lib. Therefore, conan recipe should be updated to take advantage of this and reduce the compile time of a user of the library.

**Comment by Croydon** [comment]
Note: This requires fmt 6.0.0 first https://github.com/conan-io/conan-center-index/pull/72

**Comment by keysight-daryl** [comment]
Also looking forward to this update...

**Comment by Croydon** [comment]
If would be wonderful if somebody could contribute to make this new version happening :smile:

**Comment by uilianries** [comment]
Done! https://github.com/bincrafters/conan-spdlog/pull/10
