### ISSUE TITLE
[glib] Build fail with clang: unknown compilers

### ISSUE THREAD

**Issue by Cyberdr8gon** [bincrafters/community#976]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **glib/2.58.3**
  * Operating System+version: **MacOS Mojave 10.14.6**
  * Compiler+version: **Apple Clang 11.0**
  * Conan version: **conan 1.18.4**
  * Python version: **Python 3.7.4**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=11.0
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]

### Logs (Include/Attach if Applicable)
```
meson.build:612:2: ERROR: Unknown compiler(s): ['cc']
```

**Comment by ericLemanissier** [comment]
travis-ci is hitting the same error currently: https://travis-ci.com/bincrafters/conan-glib/jobs/247503806

**Comment by Croydon** [comment]
I pushed https://github.com/bincrafters/conan-glib/commit/42ebcf0836f5ee18f6cf731b2bd2aa3e337bb67c to testing

GCC 4.9 is failing because of https://github.com/conan-io/conan-center-index/issues/213

Windows failed in the 2.60.3 branch before this commit

Rest is still running at the time of writing, but looks good. WDYT?

**Comment by ericLemanissier** [comment]
for windows, I think we need to wait for the next version of meson, now that https://github.com/mesonbuild/meson/issues/6101 is fixed.

**Comment by itsjamie** [comment]
As a Mac user, how would I build with the meson version `0.52.0` that contains the fix for Mac but breaks Windows?

I tried with the documentation for replacing a transitive dependency by defining it, but it still uses the Meson_installer 0.50.0 version.

**Comment by mohawkjohn** [comment]
Is there a work-around for this issue?

**Comment by ericLemanissier** [comment]
https://github.com/conan-io/conan-center-index/pull/406 should be merged soon. In the meantime, you can install system version of meson 0.52.1, so that you don't rely on conan version of meson (https://github.com/bincrafters/conan-glib/blob/stable/2.58.3/conanfile.py#L74)

**Comment by Croydon** [comment]
This recipe is now in the [Conan Center Index](https://github.com/conan-io/conan-center-index/).

Please migrate to the recipe version there. 
If this is still an issue, please create a new issue in the [Conan Center Index issue tracker](https://github.com/conan-io/conan-center-index/issues).

Thanks!
