### ISSUE TITLE
Upstream Update: yas 7.0.4

### ISSUE THREAD

**Issue by bverhagen** [bincrafters/community#977]
### Package Details
  * Package Name: **yas**
  * Latest available Version: **7.0.4**

The above mentioned version is newly released by the upstream project and not yet available within Bincrafters. Please add this version.

**Comment by bverhagen** [comment]
I am not sure what the protocol is here, but I feel a bit like a nagger by having to create issues requesting an update and not doing anything else about it.

Is there a way I can help/contribute (for example only for this package)?

I also don't know why the yas people released two versions in 3 days, without bug fixing anything really.

**Comment by SSE4** [comment]
hi @bverhagen 
we're changing the process significantly right now, and we're in process of moving the repositories to the https://github.com/conan-io/conan-center-index. in short, it should bring many benefits for us, significantly reducing the maintenance and baby-sitting of recipes.
if you're willing to help, could you possibly create a pull request in **conan-center-index** adding the `yas` library?

**Comment by uilianries** [comment]
@bverhagen Yes, that's it. We are moving our recipes to Conan Center Index as a centralized repo. There are many advantages, for instance, you don't need to care about the CI files anymore (Conan package tools, travis ci, appveyor ...)

**Comment by SSE4** [comment]
if libraries are simple, and straightforward to package - yes, I'd say submit them directly to CCI (conan-center-index).
if they require some ongoing development to stabilze, e.g. if library has many options, dependencies and so on, like Qt, for instance - we may go with bincrafters first.

**Comment by Croydon** [comment]
If you need a short time solution: As long as a repository isn't archived we still accepted pull requests for it

**Comment by bverhagen** [comment]
I created a PR for 7.0.4: https://github.com/conan-io/conan-center-index/pull/115

I am waiting for the CI to run, so I am not sure yet whether it is actually ready to merge.

**Comment by Croydon** [comment]
Yas 7.0.4 is now available in CCI. 

Thanks!
