### ISSUE TITLE
Upstream Update: swig_installer 4.0.1

### ISSUE THREAD

**Issue by jmarrec** [bincrafters/community#978]
### Package Details
  * Package Name: **swig_installer**
  * Latest available Version: **4.0.0**

The above mentioned version is newly released by the upstream project and not yet available within Bincrafters. Please add this version.

https://github.com/bincrafters/conan-swig_installer is at 4.0.0. Swig 4.0.1 was released (cf https://github.com/swig/swig/releases/tag/rel-4.0.1), which happens to fix a bug with C++17 that I'm hitting (cf https://github.com/swig/swig/issues/1538)

cf https://github.com/bincrafters/conan-swig_installer/pull/1

**Comment by Croydon** [comment]
4.0.1 is now available
