### ISSUE TITLE
[sdl2] leaks exports when building static library

### ISSUE THREAD

**Issue by bugproof** [bincrafters/community#980]
See the same issue that was fixed in vcpkg:

https://github.com/Microsoft/vcpkg/issues/1351

**Comment by ericLemanissier** [comment]
This recipe is now in the Conan Center Index.

Please migrate to the recipe version there.
If this is still an issue, please create a new issue in the Conan Center Index issue tracker.

Thanks!

https://conan.io/center/sdl
