### ISSUE TITLE
[sdl2_image] Crash when initialized with JPG support

### ISSUE THREAD

**Issue by JanSimek** [bincrafters/community#981]
### Package and Environment Details
  * Package Name/Version: **sdl2_image/2.0.5@bincrafters/stable**
  * Operating System+version: **Windows 10**
  * Compiler+version: **Visual Studio Community 2019 version 16.3.1**
  * Conan version: **conan 1.18.5**
  * Python version: **Python 3.7.4**

### Conan profile (output of `conan profile show default`)
```ini
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=Visual Studio
compiler.version=16
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

Compile and run:

```c++
#include <SDL_image.h>
int main(int argc, char* args[])
{
	IMG_Init(IMG_INIT_JPG); // crash
	// IMG_Init(IMG_INIT_PNG); // does not crash
	return 0;
}
```

**conanfile.txt**

```ini
[requires]
sdl2/2.0.10@bincrafters/stable
sdl2_image/2.0.5@bincrafters/stable

[generators]
cmake

[options]
SDL2:shared=True
SDL2_image:shared=True
```

### Logs (Include/Attach if Applicable)

```
The thread 0x2d50 has exited with code 0 (0x0).
Exception thrown at 0x00007FFEACE56497 (SDL2_image.dll) in lazyfoo.exe: 0xC0000005: Access violation reading location 0x0000000000000001.
```

**Comment by Croydon** [comment]
@JanSimek Did you get any idea what could cause this?

**Comment by JanSimek** [comment]
No idea, sorry. Maybe libjpeg is not correctly linked to SDL_image?

**Comment by Croydon** [comment]
This should be fixed now via https://github.com/bincrafters/conan-sdl2_image/commit/764730abb5a0c4c757a41527a99095e5f92d06b5

Please re-try

**Comment by s7jones** [comment]
Can this be reopened?

I managed to build Falltergeist on Windows. I found that it crashed for me in `IMG_INIT_PNG`, and that `IMG_INIT_JPG` worked fine.

I think the crash seems to come from whether a define has been setup correctly when building SDL_image.

For me `LOAD_PNG_DYNAMIC` is equal to 0x1, and therefore it crashes in IMG_InitPNG().

I think for @JanSimek it would have been similar but for the JPG, so `LOAD_PNG_DYNAMIC` would be equal to 0x1, and therefore crash.

I believe that these defines should be null or LOAD_JPG_DYNAMIC="libjpeg-9.dll" or LOAD_PNG_DYNAMIC="libpng16-16.dll".

### Package and Environment Details
Package Name/Version: sdl2_image/2.0.5@bincrafters/stable
Operating System+version: Windows 10
Compiler+version: Visual Studio Community 2017 version 15.9.22
Conan version: conan 1.24.1
Python version: Python 3.8.2

### Conan profile (output of conan profile show default)
```
Configuration for profile vs:

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=15
build_type=Release
[options]
[build_requires]
[env]
```

### Logs (Include/Attach if Applicable)
```
Exception thrown: read access violation.
**string** was 0x1. occurred
```
