### ISSUE TITLE
Inclusion Request: Nana

### ISSUE THREAD

**Issue by kassane** [bincrafters/community#984]
### Package Details
  * Package Name: **nana**
  * Operating Systems+versions: **Linux, Windows**
  * Compiler support: **gcc-latest, clang-latest, msvc**
  * Conan recipe repository: **https://github.com/ppetraki/conan-nana**
  * Original Repo: **https://github.com/cnjinhao/nana**

### Inclusion request
  * Fill all checkboxes with x if you agree with the statement or if it applies to your Conan recipe
  * [x] I want that my Conan recipe is getting included into the Bincrafters organisation
  * [x] I understand that if my request is accepted we are cloning your repository with all its history into Bincrafters, adapt some configurations and meta data if needed, and publishing it under the Bincrafters name and accounts
  * [ ] I have used the Bincrafters templates to develop my Conan recipe - https://github.com/bincrafters/templates
  * [x] My Conan recipe and all parts of it are licensed under the MIT license - https://choosealicense.com/licenses/mit/
    * Bincrafters are releasing all recipes under MIT license. If you want to have your recipe within Bincrafters we kindly ask you to do the same
    * it is okay if your test_package contains code from the upstream project under the upstream project's license, as long as it is clearly mentioned within the test_package files
  * [ ] My Conan recipe covers (at least) the latest stable version which is available for the package
  * [x] I know that my Conan recipe is working on all operating system and compilers mentioned above right now
    * if not: please provide here links to your CI platforms and / or build logs and describe the problems you encounter
  * [x] I'm willing to help to maintain the recipe even after it is included into Bincrafters

### Checklist for the Bincrafters team
  * Ignore this if you are not part of the Bincrafters team
  * [ ] There is no such Conan package yet in conan-center, conan-community or Bincrafters
  * [ ] The project is either popular or deserves to be maintained for another good reason (we can't package every single project out there)
  * [ ] [bincrafters-conventions](https://github.com/bincrafters/bincrafters-conventions) reports no complains; the recipe fulfills our general quality requirements and conventions
  * [ ] The recipe is cloned into our organisation; CI is enabled and configurated and succeeds
  * [ ] There is a branch protection rule for `stable/*` branches, which requires a pull request with at least one approval first before things can get published
  * Considering granding the inclusion request author push rights to the recipe repository (there is no guarantee that everyone is getting push rights, we decide this on a case-to-case base)

**Comment by Croydon** [comment]
Hi @kassane!

Please fill out the entire inclusion request formular https://github.com/bincrafters/community/issues/new?labels=Packaging&template=inclusion_request.md&title=Inclusion+Request%3A+%3CLIBRARY+NAME%3E

**Comment by kassane** [comment]
> Hi @kassane!
> 
> Please fill out the entire inclusion request template https://github.com/bincrafters/community/issues/new?labels=Packaging&template=inclusion_request.md&title=Inclusion+Request%3A+%3CLIBRARY+NAME%3E

Ok

**Comment by Croydon** [comment]
Please use our templates next time this helps to avoid common mistakes.

For example, your recipe is performing a `git clone` which should be avoided when possible (use rather `tools.get()`) and you are running a `rm` command for cleanups which isn't working on e.g. Windows.

____________

Also Nana seems not be complicated, as such a Nana recipe should go directly to the [Conan Center Index](https://github.com/conan-io/conan-center-index/)
