### ISSUE TITLE
[abseil] Add -fPIC option

### ISSUE THREAD

**Issue by Talkless** [bincrafters/community#985]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **abseil/20180600@bincrafters/stable**
  * Operating System+version: **Debian 9 (stretch) amd64**
  * Compiler+version: **gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516**
  * Conan version: **Conan 1.18.5**
  * Python version: **Python 3.5.3**

### Description of your feature

While trying to package Google's or-tools, I've hit on error due to lack of `-fPIC`:
```
[ 79%] Linking CXX shared library libortools.so                                                                                      
/usr/bin/ld: /home/vincas/.conan/data/abseil/20180600/bincrafters/stable/package/dbc1e3cfd311e524aae72619c1b8bf14a12a97b5/lib/libabsl_strings.a(charconv_bigint.cc.o): r
elocation R_X86_64_PC32 against symbol `_ZN4absl16strings_internal10kFiveToNthE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value                                                              
collect2: error: ld returned 1 exit status                                                                                                                              
CMakeFiles/ortools.dir/build.make:539: recipe for target 'libortools.so.7.3.9999' failed 
```

So it seems it would be useful to have this option, also maybe shared build too?

**Comment by Croydon** [comment]
If both is working with abseil, then sure.

Could you perhaps try and create a pull request?
