### ISSUE TITLE
[conan-libuvc] Build status in README has wrong link.

### ISSUE THREAD

**Issue by SalDiAngelus** [bincrafters/community#986]
#### Package Name/Version: libuvc/0.0.6

Copying libuvc over from my repo didn't change travis CI links. It should link to https://travis-ci.com/bincrafters/conan-libuvc.

I also don't see libuvc on https://bintray.com/conan/conan-center. Is there something missing for that?

**Comment by Croydon** [comment]
Conan Center inclusion do work now over the [Conan Center Index](https://github.com/conan-io/conan-center-index/).

Before libuvc can be eventually included there, libusb needs to be included there first
