### ISSUE TITLE
[spdlog] Recipe missing option for new `SPDLOG_NO_EXCEPTIONS` attribute

### ISSUE THREAD

**Issue by torfinnberset** [bincrafters/community#989]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **spdlog/1.4.1** (#975)

In v1.4.0 of spdlog, a new parameter for compiling with exceptions disabled was introduced `SPDLOG_NO_EXCEPTIONS`. This should be exposed as a recipe option.

**Comment by tt4g** [comment]
I'm created pull request: bincrafters/conan-spdlog#12

**Comment by SSE4** [comment]
changes were applied
