### ISSUE TITLE
Upstream Update: botan 2.12.1

### ISSUE THREAD

**Issue by alnkpa** [bincrafters/community#991]
### Package Details
  * Package Name: **botan**
  * Latest available Version: **2.12.1**

The above mentioned version is newly released by the upstream project and not yet available within Bincrafters. Please add this version.

To update, something similar to https://github.com/bincrafters/conan-botan/pull/13 should be enough.

**Comment by reneme** [comment]
I reopened @alnkpa's PR ([see here](https://github.com/bincrafters/conan-botan/pull/14)) and added a few more adaptions to make Botan 2.12.0 build successfully. There is a good chance that CI will turn green now.

**Comment by reneme** [comment]
After the build system regressions found when trying to update the recipe to 2.12.0, we expect a patch release of Botan (2.12.1) very soon. I will keep this ticket updated, rather than opening another "Upstream Update" issue.

**Comment by reneme** [comment]
@SSE4 Thanks for merging `testing/2.12.0`. From my side, this can be considered `stable/2.12.0` now. 

Most likely, a patch release (2.12.1) will come out on monday. I'll create another PR for that once its out.

**Comment by reneme** [comment]
@SSE4 I created [a branch that updates the recipe to Botan 2.12.1](https://github.com/reneme/conan-botan/tree/testing/2.12.1). It would be awesome if you could open a Pull Request against a new branch `testing/2.12.1` so that it is checked in the CI. :)

**Comment by SSE4** [comment]
@reneme created: https://github.com/bincrafters/conan-botan/tree/testing/2.12.1

**Comment by reneme** [comment]
... build is on the way.

**Comment by reneme** [comment]
Thanks for helping on this @SSE4. I just merged the latest PR into `stable/2.12.1` and consider the update final. @alnkpa or @SSE4: please feel free to close this.
