### ISSUE TITLE
[mongo-c-driver] mongo-c-driver does not build - errors about 'dl' library on centos7.

### ISSUE THREAD

**Issue by fulara** [bincrafters/community#995]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **mongo-c-driver testing/1.14.0 - https://github.com/bincrafters/conan-mongo-c-driver**
  * Operating System+version: **CentOS Linux release 7.6.1810 (Core) **
  * Compiler+version: **gcc 8.2.1**
  * Docker image: **NONE - building on own build box**
  * Conan version: **conan 1.12.3**
  * Python version: **Python 2.7.5**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=8
compiler.libcxx=libstdc++11
build_type=Release
cppstd=17
os.version=rh7
[options]
[build_requires]
[env]

### Steps to reproduce (Include if Applicable)
conan create . test/test

### Logs (Include/Attach if Applicable)
everything builds but when it gets to linkinin mongoc-stat.c.  i get:
```
[ 99%] Building C object source_subfolder/src/libmongoc/CMakeFiles/mongoc-stat.dir/__/tools/mongoc-stat.c.o
[100%] Linking C executable ../../../bin/mongoc-stat
../../../lib/libmongoc-1.0.so.0.0.0: undefined reference to `dlsym'
../../../lib/libmongoc-1.0.so.0.0.0: undefined reference to `dlerror'
../../../lib/libmongoc-1.0.so.0.0.0: undefined reference to `dladdr'
../../../lib/libmongoc-1.0.so.0.0.0: undefined reference to `dlopen'
../../../lib/libmongoc-1.0.so.0.0.0: undefined reference to `dlclose'
```

my temporary workaround involves:
changing build to include setting of LDFLAGS:
```
...
    def build(self):
        #without this mongostat does not build. also added 'dl' to libs of this project. raised issue on bincrafters.
        os.environ["LDFLAGS"] = "-ldl"
...
```
changing package_info linux to include 'dl':
```
        if tools.os_info.is_linux:
            self.cpp_info.libs.extend(["ldl", "rt", "pthread"])
```

**Comment by Croydon** [comment]
This recipe is now in the [Conan Center Index](https://github.com/conan-io/conan-center-index/).

Please migrate to the recipe version there. 
If this is still an issue, please create a new issue in the [Conan Center Index issue tracker](https://github.com/conan-io/conan-center-index/issues).

Thanks!
