### ISSUE TITLE
Upstream Update: zmq 4.3.2

### ISSUE THREAD

**Issue by mjvankampen** [bincrafters/community#996]
### Package Details
  * Package Name: **zmq**
  * Latest available Version: **4.3.2**

The above mentioned version is newly released by the upstream project and not yet available within Bincrafters. Please add this version.

I created a branch [here](https://github.com/mjvk/conan-zmq/tree/testing/4.3.2) but a PR to a non-existing branch is not possible in github.

**Comment by Croydon** [comment]
You have calculated the checksum from the wrong file

zmq provides manually created downloads, while your recipe is using the archives automatically created by GitHub

4.3.2 is now available

**Comment by mjvk** [comment]
Ah rookie mistake, was getting too used to GitHub releases. Thank you very much!
