### ISSUE TITLE
Auto delete merged branches in CCI fork

### ISSUE THREAD

**Issue by Croydon** [bincrafters/community#997]

**Comment by uilianries** [comment]
I think GitHub provides an option for this on settings menu

**Comment by Croydon** [comment]
Yes, and it is already activated. It seems to only work for branches and pull requests within the very same repository. But we merge stuff upstream and afterwards push stuff to our master. GitHub doesn't seem to trigger deletion for this

**Comment by Croydon** [comment]
Done!
