### ISSUE TITLE
[cpprestsdk] Use of CONAN_xxx vars lead to hardcoded paths in cpprestsdk-targets.cmake

### ISSUE THREAD

**Issue by wdobbe** [bincrafters/community#998]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **cpprestsdk/2.10.14**
  * Operating System+version: **Linux OpenSuse 15.1 + Windows 10**
  * Compiler+version: **gcc 8.2.1 and VS2019 (but not relevant)**
  * Conan version: **conan 1.19.1**
  * Python version: **Python 3.6.5**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=8
compiler.libcxx=libstdc++11
build_type=Release
cppstd=17
[options]
[build_requires]
*: ninja_installer/1.8.2@bincrafters/stable, cmake_installer/3.14.3@conan/stable
[env]

### Steps to reproduce (Include if Applicable)
Create package cpprestsdk/2.10.14@bincrafters/stable. 
Check generated file <package_dir>/lib/cpprestsdk/cpprestsdk-targets.cmake
Observe that target_property INTERFACE_INCLUDE_DIRECTORIES for targets cpprestsdk::cpprestsdk_openssl_internal and cpprestsdk::cpprestsdk_websocketpp_internal are set to hardcoded paths into the conan cache of the current computer.
If the package is uploaded to artifactory and another user downloads the package, he will end up with a cpprestsdk-targets.cmake file that contain paths that don't exist on his computer.

The cause of these hardcoded paths is the patch in function _patch in the conanfile.py that overwrites files cpprest_find_websocketpp.cmake and cpprest_find_openssl.cmake. In the patched files variables ${CONAN_INCLUDE_DIRS_WEBSOCKETPP} and ${CONAN_INCLUDE_DIRS_OPENSSL} are used, that will always contain paths into the local conan cache. I checked the cpprestsdk  bincrafters bintray repo, **all 2.10.14 packages contain hardcoded paths to the cache of the packager**.

I don't know the purpose of the patches (introduced July 23 2019 by commit [bfaac560539d91ce52f0c33954f0800cddd88f3b)](https://github.com/bincrafters/conan-cpprestsdk/commit/bfaac560539d91ce52f0c33954f0800cddd88f3b#diff-2b1d42f71f22b7ea0412d7602dec166f). When I remove this patch and re-create the cpprestsdk package, my application that builds with cmake and uses cmake target cpprestsdk::cpprest builds fine.

### Logs (Include/Attach if Applicable)
Example of generated <package_dir>/lib/cpprestsdk/cpprestsdk-targets.cmake
```
set_target_properties(cpprestsdk::cpprestsdk_openssl_internal PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/wdobbe/.conan/data/OpenSSL/1.1.1c/conan/stable/package/0aa5d75786adb74ef00b402c54e806cb4f8b233d/include"
  INTERFACE_LINK_LIBRARIES "ssl;crypto;dl;pthread"
)

# Create imported target cpprestsdk::cpprestsdk_websocketpp_internal
add_library(cpprestsdk::cpprestsdk_websocketpp_internal INTERFACE IMPORTED)

set_target_properties(cpprestsdk::cpprestsdk_websocketpp_internal PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/wdobbe/.conan/data/websocketpp/0.8.2/bincrafters/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include"
)
```

**Comment by Croydon** [comment]
This recipe is now in the [Conan Center Index](https://github.com/conan-io/conan-center-index/).

Please migrate to the recipe version there. 
If this is still an issue, please create a new issue in the [Conan Center Index issue tracker](https://github.com/conan-io/conan-center-index/issues).

Thanks!
